### ISSUE TITLE
Als KCC medewerker wil ik een overzicht van zaken van een persoon kunnen opvragen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1]
zodat ik inzicht heb in de situatie van de klant (mits toegestaan volgens AVG/doelbinding) en de klant optimaal kan ondersteunen.

- [ ] geefLijstZaken op bsn
- [ ] onderdeel zaakbevragingen koppelvlak
- [ ] architectuur document
- [ ] ..

**Comment by TCIMEddy** [comment]
@sergei-maertens Is dit op dit moment al mogelijk?

**Comment by TCIMEddy** [comment]
Dit is mogelijk wanneer ORC is uitgebreid

**Comment by TCIMEddy** [comment]
Zaaklijst kan filterenen op betrokkenen-URI

**Comment by joeribekker** [comment]
Dit kan volgens mij nu op 2 manieren:

1. Op basis van een BRP-achtige API.
  - Zoek persoon in BRP API
  - Gebruik de URL uit de BRP API en filter zaken op `/api/v1/rollen?betrokkene=<URL>`

2. Indien er geen BRP-achtige API is.
  - Achterhaal persoonsgegevens (in een database, of via directe invoer in een GUI door KCC medewerker), bijvoorbeeld het BSN.
  - Filter zaken op `api/v1/rollen?betrokkeneType=NatuurlijkPersoon&betrokkeneIdentificatie__inp.bsn=<BSN>

@Hugo-ter-Doest Wellicht dit ticket sluiten na afronding #980?

**Comment by Hugo-ter-Doest** [comment]
Ja, deze kan dicht na #980

**Comment by joeribekker** [comment]
Oeps, iemand merkte terecht op dat we nog geen filtering hierop hebben.

**Comment by michielverhoef** [comment]
The end of an era ... ;-)

**Comment by basretera** [comment]
Super dat jullie deze user story in deze sprint nog hebben meegenomen!

**Comment by basretera** [comment]
Als ik naar de ZRC API kijk zie ik bij de Get "Alle ZAAKen opvragen" geen additionele query parameters. Hoe hebben jullie dit nu eigenlijk opgelost?

**Comment by joeribekker** [comment]
Dit is beantwoord op Slack, maar zodat anderen het ook kunnen vinden:

Via `/api/v1/rollen` kan je filteren op BSN. Hier komt een lijst met rollen uit waar ook een referentie naar de Zaak zit. Dit vergt dus wel enige calls om een lijst van zaken te verkrijgen.

@basretera gaf aan dat het wellicht fijn zou zijn om dit direct op de zaken-resource te kunnen filteren. Een alternatief is om via `?expand=zaak` op `rollen` de zaak details inline te ontsluiten. Indien gewenst moet hier en User Story voor worden aangemaakt.
