### ISSUE TITLE
Als ontwikkelaar wil ik op ref.tst.vng.cloud duidelijk de verschillende versies van een API standaardvan elkaar kunnen onderscheiden

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1007]
...zodat ik de juiste versie en de bij die versie behorend materiaal op kan halen.
Zo is er op de pagina https://ref.tst.vng.cloud/standaard/apis/zrc nog geen rekening gehouden met een evt. nieuwe release van deze API. Die gaat er echter wel komen en op dat moment moet die nieuwe release duidelijk te onderscheiden zijn van de oude release. Hetzelfde geldt voor de onderliggende pagina's.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest is dit niet voorwaardelijk voor RC?

**Comment by melsk-r** [comment]
Voor de komende RC lijkt me dit niet voorwaardelijk maar wel voor een evt. over een half jaar uit te brengen release.

**Comment by Hugo-ter-Doest** [comment]
Zie ook #995

**Comment by joeribekker** [comment]
Voorziene waarde: Meer duidelijkheid welke versie van de APIs er zijn met bijbehorende documentatie.

Concrete acties hierbij:

* We gaan op major versie onderscheiden in de documentatie op URL/menu niveau
* Minor versie changes komen met een labeltje erbij (badge 1.1)
* We voegen een tabelletje met actuele en historische versie van de API op de /standaarden/ @sergei-maertens geeft aan dat dit er al is

**Comment by sergei-maertens** [comment]
https://zaakgerichtwerken.vng.cloud/standaard/api-compatibiliteit bevat de api-compatibiliteit en dus ook de beschikbare versies

**Comment by CMasselink** [comment]
Minor versie changes gaan gelabeld worden in documentatie = werkafspraak.
Aanpassingen voor major versie wordt opgepakt worden in separate userstory
