### ISSUE TITLE
Als Consumer wil ik met één verzoek uitgebreide zaakinformatie kunnen opvragen

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1013]
...zodat het voor Consumers makkelijker wordt om de functioneel complete informatie aan de gebruiker te tonen. 
Dus een antwoord waarin de technische referenties naar andere 'objecten' als zijn omgezet naar functioneel bruikbare gegevens. 

Als KCC applicatie wil ik:
- met één verzoek de informatie van de zaken voor een bepaalde burger opvragen waarbij ik de informatie ontvang die een KCC medewerker relevant vindt
- met één verzoek alle details van een zaak inclusief alle documenten kunnen opvragen  

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest graag visie, reactie en prioriteit.

**Comment by joeribekker** [comment]
Ik kan al aangeven dat dit niet past in de visie van dit project. De ZGW APIs zijn losse componenten (zie ook GEMMA 2) en het is aan de consumer om de gewenste data bij elkaar te harken bij de juiste componeten. Dit is ook in elke situatie andere data.

Uiteraard kan er later een API bovenop de ZGW APIs gerealiseerd worden die al veel bij elkaar harkt en in 1 response terug geeft als de consumer nog klassiek alle data in 1 keer wil hebben.

**Comment by adgerrits** [comment]
Klassiek voorbeeld waarbij onderscheid in type API's verhelderend werkt. Mulesoft gebruikt het onderscheid in ['system', 'process' en 'experience' API](https://www.mulesoft.com/sites/default/files/resource-assets/API-led-connectivity-new-soa-updated.pdf)'s. Via dit issue wordt gevraagd om een typische process-API. @joeribekker zegt in die termen dat dit project zich beperkt tot system-API's en    "er kan later een API bovenop de ZGW APIs gerealiseerd worden". Dat roept wel de vraag op of en door wie dit zou dan zou moeten gebeuren. Gebeurt het niet dan is voorspelbaar dat er onnodig en dubbel werk bij consumers gedaan gaat worden.

**Comment by Hugo-ter-Doest** [comment]
Is niet conform visie en buiten scope.

**Comment by michielverhoef** [comment]
Opgenomen in Zaken API 1.5.0
