### ISSUE TITLE
In GitHub is het niet mogelijk om een item aan meer dan 10 personen te "assignen"

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#102]
# Impediment

In GitHub is het niet mogelijk om een item aan meer dan 10 personen te "assignen"

[assign aan Eddy, voeg label 'impediment' toe]

**Comment by jgortmaker1** [comment]
dan is het team te groot :-)

**Comment by TCIMEddy** [comment]
hahahahah wordt vanzelf kleiner, maar jij blijft en krijgt het heeeeel druk

**Comment by TCIMEddy** [comment]
In het issue zelf komen taken voor alle teamleden te staan, die kunnen worden afgevinkt.
