### ISSUE TITLE
500 internal server error bij openen van slides gemeente utrecht bij sprintdemo 11

### ISSUE THREAD

**Issue by RitaBerghuis** [VNG-Realisatie/gemma-zaken#1021]
# Bug

[beschrijf de bug]
Als ik op de site ref.tst.vng.cloud de presentatie van de gemeente utrecht in sprintdemo 11 wil openen, krijg ik de foutboodschap 500 internal server error. Ik werk op mijn ipad en gebruik de wifi van de gemeente amsterdam.

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)

Welke claims/payload bevat je JWT?

**Comment by TCIMEddy** [comment]
@RitaBerghuis ga ik oplossen

**Comment by TCIMEddy** [comment]
@sergei-maertens kun jij de jwt vraag beantwoorden

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest @sergei-maertens en de vraag over gehoste componenten graag, ik heb linkje gerepareerd....

**Comment by CMasselink** [comment]
@RitaBerghuis : het antwoord op je vraag over de JWT payload staat beschreven in het document over autorisatie:
https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/ontwikkelaars/algemeen/authenticatie-autorisatie.md

**Comment by RitaBerghuis** [comment]
Ik kreeg bij de sprintdemo in Amsterdam deze foutboodschap bij het openen van de presentatie van Utrecht. Inmiddels krijg ik de presentatie weer te pakken (of het nu ook in Amsterdam via de wifi mogelijk is, dat weet ik niet). 

Het gaat dus niet om een gehost component, maar om de volgende pdf op de site:
http://ref.tst.vng.cloud/community/bestanden/zgw2-demo-sprint-%2011-utrecht.pdf

Hoe dan ook, voor mij is het opgelost, dus ik close het issue (als ik dat mag)
