### ISSUE TITLE
Tijd/geld om #1032 te realiseren

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#1033]
# Impediment

Tijd/geld om gegevensmodel te realiseren

zie #1032

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Moet je hier nog iets mee sprint 14 anders graag close

**Comment by Hugo-ter-Doest** [comment]
Nog even openlaten omdat het nog niet is geregeld.

**Comment by EdwinCoster** [comment]
Inmiddels is het geregeld.
