### ISSUE TITLE
Organiseren 1e demo

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#104]
We hebben afgesproken dat we een demonstratie gaan organiseren voor alle stakeholders. De eerste zullen we alleen met het team doen als generale repetitie. Ik heb PO/SM en VNG als verantwoordelijke opgenomen. Denk dat het zinvol is dat we ruim voor de demo een keer om tafel gaan zitten om inhoud en vorm te bespreken. Voor nu in het algemene bord opgenomen.

**Comment by ehotting** [comment]
We moeten ergens bijhouden welke resultaten we allemaal kunnen demo'en. Er gaat meer ontstaan dan in de userstories is verwoord, en een maand is lang, om dat allemaal te onthouden. Bijv. zelfs de manier waarop dit traject en wat er na een paar dagen ligt is al interessant wellicht.

**Comment by TCIMEddy** [comment]
Goed idee Eelco, wat mij betreft leggen we het vast in de taak organiseren 1e demo op het bord organisatie en impediments
