### ISSUE TITLE
Als ontwikkelaar van de BiNG applicatie wil ik zaken kunnen filteren en sorteren...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1041]
...zodat ik niet meer data ophaal dan nodig is en client-side filteren/sorteren kan vervangen door server-side filteren/sorteren.

*Gewenste filter-parameters*

* `startdatum__gt`, `startdatum__gte`: alle zaken met een startdatum groter dan (of gelijk aan) de opgegeven datum

*Gewenste sorteerparameters*

Suggestie: een parameter `?order_by=field1,field2,-field3`, met initial support voor het `startdatum` veld.

Huidige work-around doet dit client-side, met de trade-off dat er dus eventueel meerdere calls gedaan moeten worden (want paginering) en sorteeroperaties kunnen duurder uitvallen dan gewenst.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
filteren begrijp ik goed, maar sorteren is convenience.

**Comment by sergei-maertens** [comment]
Nee, want sorteren hangt heel nauw samen met paginering. Als ik pagina 1 wil van de meest recente zaken, dan wil ik niet alle pagina's hoeven opvragen om client-side te kunnen sorteren en dan 90% van de data weer te negeren.

**Comment by joeribekker** [comment]
Eens met @sergei-maertens. Tevens is het beide weinig werk

**Comment by annashamray** [comment]
PR - https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/77
