### ISSUE TITLE
links staan goed in MD maar niet op red.tst.vng.cloud

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#1048]
# Bug

Op https://ref.tst.vng.cloud/introductie/begrippenlijst staan links die niet doorlinken. In MD-files met preview staat het wel goed en linkt het door. Ik weet niet hoe ik dit zelf kan oplossen.

**Comment by Hugo-ter-Doest** [comment]
Begrippenlijst zit op dit moment niet in de documentatie.
