### ISSUE TITLE
Als stakeholder wil ik naast het GitHub logo met doorverwijzing ook een logo van Slack met verwijzing naar vngapicommunity zodat ik alles centraal kan bereiken (wat dus makkelijk is)

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#1051]
![Schermafbeelding 2019-06-03 om 13 53 30](https://user-images.githubusercontent.com/39735549/58800268-ac974a80-8607-11e9-9c83-cf8640c831f4.png)
Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@sergei-maertens @joeribekker wellicht kost het 3 minuten... dan graag melden. Maakt prioriteren wat makkelijker.

**Comment by Hugo-ter-Doest** [comment]
Lage prio, maar meenemen als het weinig tijd kost.

**Comment by michielverhoef** [comment]
Ik heb geen idee wie het opgelost heeft maar inmiddels staat het (klikbare) logo van Slack op de site. Volgens mij kan dit issue gesloten worden.

**Comment by michielverhoef** [comment]
Woeps, alleen op de hoofdpagina staat het Slack logo maar dit willen we natuurlijk op alle pagina's hebben. Ik heropen het issue.

**Comment by michielverhoef** [comment]
De toevoeging van label Beheerprioriteit gaat niet zozeer over dit specifieke issue maar meer dat we als beheer willen weten hoe we de footer van de website kunnen aanpassen.
