### ISSUE TITLE
Als leverancier en/of implementerende organisatie wil ik weten hoe de relatie tussen aanvragen/verzoeken en zaken eruit ziet

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1055]
...zodat ik een beeld heb bij hoe een verzoek dat via bijvoorbeeld een e-formulierencomponent wordt omgezet naar een zaak.

**Toelichting**
Vraag naar aanleiding van het [ZGW in Gegevenslandschap v0.7](ZGW in Gegevenslandschap v0.7)-stuk. De openstaande vragen aan het eind daarvan zijn goeddeels opgelost, of buiten scope van de ZGW-API's. Uitzondering is de daarin voorgestelde relatie tussen zaken en verzoeken.

Uit het stuk:

> Eén verzoek kan leiden tot meerdere zaken. Meerdere Verzoeken kunnen ook leiden tot één Zaak. Bv. meerdere meldingen die als één zaak worden afgehandeld. Verzoek heeft juridisch ook een eigen betekenis, bijvoorbeeld in het kader van archivering en het bepalen van de afhandeltermijn (ontvangstdatum Verzoek). Een verzoek kan bv. een subsidieaanvraag of een melding zijn.

en

> We kiezen ervoor om Verzoeken als aparte registratie te onderkennen en op te nemen in het RGBZ (als apart Informatiemodel Verzoeken met relatie met Zaak). Zo wordt het eerder aangehaalde nadeel dat gestructureerde gegevens die in een formulier zijn ingevuld “verloren” dreigen te gaan voorkomen. Een e-formulierencomponent (of ander systeem waarin een burger of bedrijf een aanvraag kan doen) registreert het verzoek in de Verzoekenregistratie. De gegevens van de aanvrager (in figuur hieronder een burger) in de klantenregistratie (als deze niet al bestond) en de documenten bij de aanvraag in de documentenregistratie. Meldingspecifieke gegevens in de domeinspecifieke registratie voor meldingen. Denk aan aard van de melding, omschrijving van de klacht etc. De relatie tussen verzoek en alle informatie die bij de aanvraag aanwezig was, of eventueel later is aangevuld, wordt vastgelegd en mag niet meer gewijzigd worden. Zo is te allen tijde duidelijk welke gegevens er bij de aanvraag zaten.

![Model verzoeken](https://ref.tst.vng.cloud/architectuur/_assets/van_verzoek_naar_zaak2.png?raw=true)

Van de componenten in bovenstaand model is de klantenregistratie benoemd, de documentenregistratie gerealiseerd, "meldingspecifieke gegevens in de domeinspecifieke registratie voor meldingen" (MOR/inzageverzoek) worden opgeslagen in de overigeregistratie, en worden (via Zaakobjecten?) gekoppeld aan een zaak in de zakenregistratie. Maar wat gebeurt er met de aanvraag waarin al die elementen bij elkaar komen? Is die onderdeel van de standaard?

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prio en visie?

**Comment by Hugo-ter-Doest** [comment]
Je kunt met zaakobjecten relaties leggen met willekeurige andere objecten. In het RGBZ werd nog onderscheid gemaakt tussen zaakobjecten uit het RSGB en andere zaakobjecten. Dat onderscheid maken we in het gegevenslandschap niet meer. Voor nieuwe objecttypen moet de ondersteunde enum van objecttypen worden uitgebreid.
