### ISSUE TITLE
Communicatie leveranciers, gemeenten en andere stakeholders

### ISSUE THREAD

**Issue by wishalg** [VNG-Realisatie/gemma-zaken#107]
De leveranciers, gemeenten en andere stakeholders dienen op de hoogte gehouden te worden over ontwikkelingen van dit project en hoe ze bijdrage kunnen leveren. Hiervoor heb ik een interne communicatie adviseur van VNGR benaderd om na te gaan hoe we dit het beste kunnen aanpakken. Hij komt er woensdag op terug.

**Comment by TCIMEddy** [comment]
Graag subtaken toevoegen indien mogelijk!

**Comment by ehotting** [comment]
Deze taak is breder dan alleen communicatie, er moet ook worden nagedacht over de gewenste rol van leveranciers die stakeholder zijn bij de productie van een goede RESTful API standaard ZDS.

Voorstel: splitsen in organisatie issue voor communicatie naar stakeholders die alleen geïnformeerd moeten worden (meeste gemeenten) en organisatie issue voor communicatie naar hen die we willen werven in een bepaalde rol (leveranciers die iets doen met Zaken). 

Behelst in ieder geval "openbare consultatie". 
Wil graag leveranciers in rol technische review in vroeg stadium - niet in het scrum-team, wel voortdurend reflecterend op wat wordt opgeleverd. Juiste vorm voor vinden.

**Comment by ehotting** [comment]
@wishalg De feedback van communicatieadviseur vorige week woensdag, leidt dat tot wijziging / taken / etc?

**Comment by wishalg** [comment]
Ik zie niet dat de feedback van de communicatieadviseur tot wijzigingen leidt, of ik begrijp niet zo goed wat je bedoeld.

**Comment by ehotting** [comment]
Benieuwd naar wat de communicatieadviseur hier over te melden had - bij deze user story staan nog geen "taken" en ik hoopte die te kunnen invullen adhv die reactie. We moeten er wel mee verder, dit is een urgent punt.

**Comment by wishalg** [comment]
@ehotting VNG Realisatie wil het op de DA2020 website publiceren en een mailing via de werkgroepoverleg ZDS versturen zodat er bij de demo bijdrage kan worden geleverd en informeren dat VNG Realisatie een standaard aan het ontwikkelen is volgens een nieuwe werkwijze.
Roxit heeft VNG Realisatie benaderd via de werkgroepoverleg ZDS om mee te willen doen in het team voor API ontwikkeling en niet via Github. 
De splitsing lijkt me ok: welke vorm?

**Comment by TCIMEddy** [comment]
@wishalg status? Close?
