### ISSUE TITLE
Als gemeente wil ik een document kunnen ondertekenen

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#1073]
zodat een fysieke ondertekening niet meer nodig is

**Omschrijving / Context**
Het ondertekenen van een document wil in de praktijk zeggen dat je via een audit-trail (audit-trail component) kan aantonen dat een bepaalde persoon (autorisatie component) het document heeft geopend en akkoord heeft gegeven. Het resultaat kan dan een 'akte van ondertekening' opleveren (document registratie component), waarbij dit is samengevat. Veel overlap met de huidige componenten.

Daarnaast is er op API niveau nog geen standaard voor het laten ondertekenen en later weer kunnen controleren van de ondertekening. 

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest graag prio en visie?

**Comment by Hugo-ter-Doest** [comment]
Gaat dit over een handtekening die met metadata (wie heeft wanneer een vinkje gezet) wordt geregistreerd of over een gekwalificeerde digitale handtekening die rechtsgeldig etc. is?

**Comment by Hugo-ter-Doest** [comment]
@BoerBas kun jij even naar mijn vraag kijken ^
