### ISSUE TITLE
Als gemeente wil ik grote bestanden in het DRC kunnen plaatsen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1078]
...zodat ik niet geblokkeerd wordt.

De definitie van "grote bestanden" is niet voor iedereen hetzelfde. Op dit moment is tot 20 MB wel te doen met de DRC API, maar daarna wordt de overhead wel groot door base64 encoding.

Grote bestanden, tot zeg 2 GB, kunnen opgelost worden met multipart, om tegelijk meta data en het bestand zelf als binary mee te sturen. Eventueel opsplitsen van bestanden kan ook met de aanpak die Amazon S3 en WeTransfer gebruiken, door 1 request te doen voor het voorbereiden van een upload door bestandsnamen en groottes mee te sturen. De response bevat upload-URLs (eventueel meerdere voor 1 bestand zodat het bestand opgesplitst kan worden). In vervolg requests kunnen de bestanden naar de URLs geupload worden.

Een en ander wordt ondersteund in [OAS3 middels File Upload constructie](https://swagger.io/docs/specification/describing-request-body/file-upload/).

[Server configuratie is nodig](https://docs.nextcloud.com/server/14/admin_manual/configuration_files/big_file_upload_configuration.html) om het netjes af te handelen en resume mogelijk te maken. Er is [ook een iets andere aanpak mogelijk](https://stackoverflow.com/questions/44371643/nginx-php-failing-with-large-file-uploads-over-6-gb/44751210#44751210).

---

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by CMasselink** [comment]
Het toevoegen van grote bestanden zijn we met het gebruik van de zaak-dms koppeling er vaak tegenaan gelopen dat dit niet goed ging. Voor vergunningszaken worden er bijvoorbeeld vaak grote bestanden aan de zaak toegevoegd (bouwtekeningen etc.). 
Belangrijk dus inderdaad dat de standaard / de specificaties het toevoegen van grote bestanden niet in de weg zit.

**Comment by joeribekker** [comment]
Blog voor multipart support in DRF: https://medium.com/@ahm3d.hisham/drf-nested-params-and-multipart-488c86d89191

**Comment by EdwinCoster** [comment]
Prioriteit wacht op #1211

**Comment by CreuwelsBCT** [comment]
In aanbestedingen wordt regelmatig gevraagd naar mogelijk voor toevoegen (en ook weer openen uiteraard) van grote bestanden . We zien ook vaker een eis van minimaal 1Gb. De definitie van "groot" zou wat mij betreft dus minimaal 1Gb moeten zijn (analoog aan de aanbesteding eis). 

Er ook aanbestedingen waar "geen beperking" wordt geëist:

> E22 De Oplossing kent geen beperking voor het opslaan van type en grootte van bestanden (zoals
officebestanden, audiovisuele bestanden, e-mails incl. bijlagen etc.).

[Bron](https://www.tenderned.nl/tenderned-web/aankondiging/detail/documenten/document/eae4450fe53d6a58fac9b453c8de8b12/pageId/D909C/huidigemenu/aankondigingen/map/a07276e21d21f0aa1f17d8c8878733d0/akid/41dcbd22c713f2415704259c0470f396/da/false/actie/aa274b487977199c90ed89bf7fb5b3adf319e66f5d0d86ee89d634f7ec8ea825b560366cc6cb9e9ed68ee310df42c04f1cc1862341c2128997415317b39e2617b100d520d07b4e25519806451311da19/cid/141278;jsessionid=4D2DC8AB68F852DF27A9E3AC46119A6F.node5)

Als gekozen wordt voor een oplossing waarbij e.e.a. "streaming" wordt gemaakt is de grens theoretisch zelfs onbeperkt.

**Comment by PDG65** [comment]
- nog toevoegen aan de standaard
- tutorial toevoegen
- gegevensmodel bijwerken

**Comment by sergei-maertens** [comment]
@EdwinCoster toevoegingen voor gegevensmodel 

* `BestandsDeel` resource is toegevoegd aan documenten API. Een EIO kan meerdere bestandsdelen hebben (ook 0 mogelijk, als het klein genoeg is om in 1x te uploaden)
