### ISSUE TITLE
Foutmelding bij het openen van het attribuut zaakgeometrie in zaak_read in de zrc API spec

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#1082]
# Bug

Ik krijg een foumelding bij het openen van het attibuut `zaakgeometrie` in `zaak_read` in de documentatie van de [zrc API spec](https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_read).

De omschrijving is van het attribuut is ook niet echt verhelderend.

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:
Waar staan de componenten gehost? (ref.tst.vng.cloud)
Welke claims/payload bevat je JWT? nvt
Ik krijg de foutmelding in Google Chrome
In Internet Explorer krijg ik de API spec niet te zien.

**Comment by joeribekker** [comment]
Bug bevestigd. Ik zie dat Swagger de docs wel rendered maar ReDoc inderdaad niet. Of de OAS bevat een bug of ReDoc.

**Comment by sergei-maertens** [comment]
Is een vieze, ReDoc lijkt `allOf` niet te begrijpen, met dus de fix: https://github.com/VNG-Realisatie/vng-api-common/pull/65

Kanttekening is dat `GeometryCollection` niet werkt, want die moet naar `Geometriy` verwijzen, maar die verwijst zelf naar `Geometry -> circular reference probleem.
