### ISSUE TITLE
Als ontwikkelaar wil ik caching kunnen toepassen bij consumers (excl. ZTC)

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1096]
...zodat er niet onnodig veel netwerk verkeer plaats vind. Idealiter wordt dit onderdeel van de standaard en zodat dit een verwachte functionaliteit is van alle ZGW API implementaties.

Zie: https://docs.geostandaarden.nl/api/API-Strategie/#caching

---

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by joeribekker** [comment]
@Hugo-ter-Doest Prio en visie? /EddyMode

**Comment by Hugo-ter-Doest** [comment]
Moeten wel antwoord geven op de vraag waar dit relevant is:
> API principe: Waar relevant wordt caching toegepast

Voor alle resources? Of in eerste aanleg voor de resources in de ZTC. En later voor de andere resources?

**Comment by joeribekker** [comment]
Performance is altijd relevant :)

Maar het ZTC is het beste voorbeeld: veel lezen, weinig wijzigingen.

**Comment by michielverhoef** [comment]
De link bij "zie ..." werkt niet goed, dat moet waarschijnlijk https://docs.geostandaarden.nl/api/API-Strategie/#api-43-apply-caching-to-improve-performance  zijn?

**Comment by PDG65** [comment]
Todo: 
- merge conflicts verwerken
- inbouwen in de API's (excl. ZTC)
