### ISSUE TITLE
informatieobject_lock en _unlock operaties niet volgens de principes van de andere API's

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1099]
# Bug

De informatieobject_lock en informatieobject_unlock operaties zijn in de DRC OAS zo vormgegeven: https://ref.tst.vng.cloud/drc/api/v1/schema/#operation/enkelvoudiginformatieobject_lock  en https://ref.tst.vng.cloud/drc/api/v1/schema/#operation/enkelvoudiginformatieobject_unlock. 

Dit is een relatieklasse, een koppeltabel, en zou dus als aparte (sub)resource moeten bestaan, niet als bewerking van een informatieobject. Als het een bewerking van een informatieobject is (en lock dus een attribuut van informatieobject) zou dit ingevuld moeten worden met een partial update/patch waarbij alleen het lock attribuut gewijzigd wordt.

Daarnaast kan ik me voorstellen dat in de toekomst ook andere resources gelocked moeten worden en dan is deze werkwijze niet generiek toepasbaar. Dat maakt het risico op andere werkwijzen groter terwijl het juist goed zou zijn om voor dezelfde soort handeling (het locken/unlocken van een object om het te kunnen bewerken) een gelijk patroon gehanteerd wordt.

EDIT: in de presentatie tijdens de sprint demo is het lock wel een subresource van een informatieobject. Dan blijft alleen nog over mijn opmerking over het aanmaken/verwijderen van de subresources. 

Tenzij ik het verkeerd begrepen heb zou dit een POST en een DELETE van de subresource LOCK van de resource ENKELVOUDIGINFORMATIEOBJECT  moeten zijn.

**Comment by michielverhoef** [comment]
Iets te hard van stapel gelopen.

**Comment by TCIMEddy** [comment]
@hugo visie en prioriteit?

**Comment by sergei-maertens** [comment]
> Dit is een relatieklasse, een koppeltabel, en zou dus als aparte (sub)resource moeten bestaan, niet als bewerking van een informatieobject. 

Het is geen relatieklasse zoals andere relatieklassen dat zijn. Als je kijkt naar de URL, dan _is_ de `lock` een subresource, en je `create` het door te POST-en. Eventueel kunnen we `unlock` vervangen door een `DELETE` op de `lock` subresource, dat maakt het iets meer RESTful.

> Als het een bewerking van een informatieobject is (en lock dus een attribuut van informatieobject) zou dit ingevuld moeten worden met een partial update/patch waarbij alleen het lock attribuut gewijzigd wordt.

Dat valt niet te rijmen met een effectieve PATCH/PUT operatie waarbij inhoud gewijzigd wordt en je het `lock` attribuut moet meegeven om te bewijzen dat jij inderdaad de eigenaar van het `lock` bent. Je kan het onderscheid niet meer maken.

> Daarnaast kan ik me voorstellen dat in de toekomst ook andere resources gelocked moeten worden en dan is deze werkwijze niet generiek toepasbaar.

Dit snap ik niet. Waarom zouden voor andere resources niet ook `lock`/`unlock` toegevoegd kunnen worden? Het is een HTTP call op een subresource URL van de detail URL.

> Tenzij ik het verkeerd begrepen heb zou dit een POST en een DELETE van de subresource LOCK van de resource ENKELVOUDIGINFORMATIEOBJECT moeten zijn.

Het is echter niet gebruikelijk (maar wel toegestaan) om een body mee te sturen in een DELETE request, en dat is nodig om te kunnen unlocken.

**Comment by michielverhoef** [comment]
@sergei-maertens  je hebt gelijk, ik had eea verkeerd gezien en daarom zelf het issue al gesloten...  :-D

**Comment by sergei-maertens** [comment]
Sorry, was door mijn e-mail backlog aan het gaan en had niet opgemerkt dat het gesloten was :)
