### ISSUE TITLE
Als manager wil ik managementoverzichten kunnen maken

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#110]
...zodat ik mijn afdeling kan aansturen. 

Dit wordt soms ook wel eens stuurinformatie genoemd. Daarnaast wil je BI tooling kunnen aansluiten om rapportages te kunnen maken waarbij ook andere bronnen worden gebruikt.

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by jgortmaker1** [comment]
zie andere US: welke managementoverzichten?

En als het om aansluiten van BI-tooling gaat, moeten we dat denk ik niet via ZDS regelen.
zie https://www.gemmaonline.nl/index.php/Beschikbaar_stellen_managementinformatie (nog zonder ZRC als bron)

**Comment by Hugo-ter-Doest** [comment]
Gaat om beide:
- Stuurinformatie op basis van actuele gegevens. Bijv. welke zaken dreigen door de fatale datum heen te gaan?
- aansluiten op BI tooling. Liever niet via ETL (ouderwets), maar op basis van een API waar je wijzigingen sinds een bepaald tijdstip kunt ophalen. Graag ook de kijk van anderen op dit vraagstuk.

**Comment by jgortmaker1** [comment]
OK, helder. Weer een architectuurvraag te pakken rondom ETL..
Klinkt inderdaad wat ouderwets, maar een hele/halve database binnenladen via een API...geen idee of dit handig is..

**Comment by jgortmaker1** [comment]
@arnoudquanjer wat denk jij?

**Comment by arnoudquanjer** [comment]
Vanuit de GEMMA bezien is het zo dat gegevens die binnen een informatiesysteem worden opgeslagen via een ETL-proces worden overgezet naar een datawarehouse. Er zijn meerdere redenen waarom dit proces zo is ingericht in de GEMMA. Performance en beschikbaarheid van zijn daar voorbeelden van. Daarnaast is het zo dat in een ETL-proces transformaties op de gegevens kunnen worden uitgevoerd (denk aan pseudonimiseren of anonimiseren). 

Vanuit het oogpunt van actualiteit van gegevens zou ook een API gebruikt kunnen worden voor het ophalen van de gegevens. De vraag is dan of het gaat om het laden van gegevens in het datawarehouse of het opnemen van de API als databron binnen het datawarehouse. Voor het laatste zouden bijvoorbeeld APIs die zich conformeren aan de OData standaard geschikt zijn. Wij hanteren echter de landelijke API strategie (die gebaseerd is op de DSO API strategie) en die wijkt af van de OData standaard. 

Vanuit het oogpunt van performance en beschikbaarheid van de bronsystemen lijkt me een ETL-aanpak conform de huidige GEMMA patronen voorlopig nog de beste aanpak. Gezien de architectuur die we vanuit de Common Ground beweging nastreven is het onderzoeken van een aanpak waarbij gegevens via APIs uit bronsystemen worden gelezen wel een pad wat we verder zouden kunnen onderzoeken.

**Comment by Hugo-ter-Doest** [comment]
Is me duidelijk. Laten we voor BI voorlopig van ETL uitgaan. Voor stuurinformatie zijn API's volgens mij wel de juiste route.

Hugo

**Comment by RvdKlip** [comment]
ETL tbv BI is nog doenlijk zolang het interne bronnen betreffen. Voor externe bronnen heeft de API route de voorkeur. Zou dus daar toch de pijlen op richten en BI niet als een bijzondere afnemer willen zien.

**Comment by michielverhoef** [comment]
Als dit al via een API gerealiseerd zou moeten zou dit bij voorkeur in een aparte API of andere oplossing worden ondergebracht. 

Voor het aanmaken, opslaan en bevragen door afhandelcomponenten is het geen onderwerp. daarom sluit ik dit issue.
