### ISSUE TITLE
Wijziging op zaaktype moet in van toepassing kunnen zijn op lopende zaken.

### ISSUE THREAD

**Issue by erikdelepper** [VNG-Realisatie/gemma-zaken#1101]
Als zaaktypebeheerder wil ik na activering van een zaaktype een wijziging kunnen doorvoeren die meteen betrekking heeft op de lopende zaken van dat zaaktype, bijvoorbeeld het toeveogen van een ontbrekend resultaattype.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by joeribekker** [comment]
Ik begrijp de vraag maar dit is echt onwenselijk. Je doet eigenlijk aan geschiedsvervalsing met vreemde constructies tot gevolg. "Waarom heb je niet dit resultaattype toegekend aan de zaak?" - "Die was er niet" - "Volgens het Zaaktype wel!"...

Er zijn zeker scenario's te bedenken die "veilig" zijn: Er zijn nog geen Zaken van dit Zaaktype, maar dan zou een nieuwe versie ook geen ramp zijn. Een spellingsfout in een beschrijving verbeteren, maarja. Hoe controleer je dat een spellingsfout wordt gecorrigeerd en niet de intentie van de beschrijving wordt aangepast?

Het is vele malen veiliger netjes de flow te volgen: Zaaktype afsluiten per datum, en nieuwe versie op die datum laten ingaan.

**Comment by Hugo-ter-Doest** [comment]
Inderdaad is dit onwenselijk. Een lopende zaak die een update van het zaaktype moet krijgen, moet worden afgesloten waarna een nieuwe zaak kan worden aangemaakt van het nieuwe zaaktype.
