### ISSUE TITLE
Marketing standaard

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#1102]
# Improvement Story

Marketing en communicatie standaard (als stakeholder willen we weten wanneer de standaard de standaard is 18/7 RC)

**Comment by michielverhoef** [comment]
In https://discussie.kinggemeenten.nl/discussie/gemma/koppelvlak-zs-dms/apis-voor-zaakgericht-werken-release-candidate-1-gepubliceerd  is aangegeven dat wanneer een release candidate 2 maanden stabiel is en geen bevindingen opgeleverd heeft die versie vastgesteld wordt als een release.

**Comment by michielverhoef** [comment]
Eigenlijk zou dit nog in een FAQ beschreven moeten worden. Zie #1226
