### ISSUE TITLE
Rol.betrokkeneType underscores in enum/helptekst

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1108]
# Bug

Rol heeft een `betrokkeneType` waarvan de daadwerkelijke enum wel underscores bevat, maar de weergegeven helpteksten tonen zonder underscores: `Natuurlijk_persoon` vs `Natuurlijk persoon`.

**Comment by joeribekker** [comment]
Rendering issue van ReDoc gebleken, geen OAS isssue.

**Comment by sergei-maertens** [comment]
Is inderdaad issue in ReDoc, even kijken hoe dit oplossen

**Comment by sergei-maertens** [comment]
Blijkt niet triviaal te zijn:

* drf-yasg genereert Swagger 2.0
* wij converteren die output naar OAS 3 met [Swagger2OpenAPI](https://github.com/Mermade/oas-kit/blob/master/packages/swagger2openapi/README.md)
* Tijdens die conversie worden schema referenties met spaties omgezet naar underscores, en daar gaat het fout

ReDoc gebruikt ook swagger2openapi in de renderer om on-the-fly te converteren, wat ingebakken zit in drf-yasg package...

Ik maak een bug report aan bij upstream.

**Comment by joeribekker** [comment]
Met het antwoord in het upstream bug report moeten wij dus verder kunnen.

**Comment by sergei-maertens** [comment]
"Accidentally" fixed via https://github.com/VNG-Realisatie/vng-api-common/commit/74103e0345dbc9c5017d98a111e4d5344f9489fa#diff-d5d8b101d9465682893bdcbcb6f11cdb on July 12th.

Verified that this issue is no longer present in the current API spec.
