### ISSUE TITLE
Als VTH applicatie wil ik een handhavingsobject kunnen relateren als betrekking op

### ISSUE THREAD

**Issue by ArnauldvdHeijden** [VNG-Realisatie/gemma-zaken#1113]
...zodat ik inzichtelijk kan maken welken zaken uitgevoerd zijn op dit object.

Een handhavingsobject is een verzameling van een of meerdere ruimtelijke objecten en worden nu (ZDS 1) gerelateerd als ander zaakobject. Deze mogelijkheid is echter niet aanwezig bij ZRC.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio en visie?

**Comment by TCIMEddy** [comment]
@ArnauldvdHeijden Dank voor de user story!

**Comment by Hugo-ter-Doest** [comment]
Dit kan al via zaakobjecten.

**Comment by ArnauldvdHeijden** [comment]
@Hugo-ter-Doest Bij zaakobject is een (verplichte) ENUM gedefinieerd voor Type. Is deze dan vrij in te vullen?

**Comment by Hugo-ter-Doest** [comment]
Dat was te snel...de relatie voor zaakobjecten is er al. In deze sprint wordt ondersteuning voor zaakobjecten verder uitgebreid en komt er flexibiliteit om andere zaakobjecten te koppelen.

**Comment by ArnauldvdHeijden** [comment]
@Hugo-ter-Doest Duidelijk! Daar kunnen we wat mee. Dank voor de snelle reactie.

**Comment by Hugo-ter-Doest** [comment]
Dan sluit ik hem als duplicaat van #981
