### ISSUE TITLE
Overdragen van (de afhandeling van) een zaak van een applicatie (consumer) naar een andere applicatie (consumer).

### ISSUE THREAD

**Issue by JohnRooijakkers** [VNG-Realisatie/gemma-zaken#1114]
De afhandeling van een zaak vindt niet altijd plaats binnen één applicatie. Soms worden bepaalde stappen gezet en statussen bereikt in applicatie A. Vervolgens wordt de zaak "overgedragen" en wordt de zaak verder afgehandeld en afgerond in applicatie B. Hiervoor is in de Zaak-regie service de operatie "overdragen zaak" benoemd. In de praktijk werkt dit niet omdat bij de behandeling van de zaak veel zaaktype specifieke (dus geen RGBZ) gegevens worden verzameld en meten worden overgedragen, maar het centrale zaaksysteem ondersteunt nu meestal maximaal het RGBZ. Het is onduidelijk of en hoe dit vanuit de nieuwe ZGW API's worden ondersteund.

**Comment by ehotting** [comment]
Hoe het volgens mij moet werken:

- Beide applicaties gebruiken dezelfde API's om de zaak te manipuleren, namelijk de API's die worden aangeboden op de URI's die de zaak en documenten identificeren
- Zaaktype-specifieke gegevens van buiten RGBZ worden gelinkt als object maar aangeboden door een API buiten de ZGW scope. Dat zijn niet zozeer zaakgegevens maar objectgegevens die relevant zijn voor afhandeling van het proces. Idealiter uniformeren we langzaamerhand ook al dat soort gegevens door er aparte API's voor te specificeren zodat iedere leverancier die gegevens op dezelfde manier hanteert en migraties overbodig worden.

**Comment by JohnRooijakkers** [comment]
@ehotting: vindt de overdracht van de afhandeling daarbij in jouw ogen impliciet (bv het bereiken van een specifieke status) of expliciet (door overdracht event) plaats?

**Comment by ehotting** [comment]
@JohnRooijakkers Kunnen we het aan de hand van een heel concrete use case bekijken? Heb je een voorbeeld van een zaak die qua afhandeling wordt overgedragen van applicatie A naar B? Voor zover ik het nu kan zien gaat het namelijk niet zozeer om de applicatie maar om de behandelaar, eerst ligt de verantwoordelijkheid bij behandelaar via applicatie A, daarna via applicatie B. Dat regel je dan dus door een proces correct te configureren.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Graag prioriteit en visie?

**Comment by Hugo-ter-Doest** [comment]
Volgens mij kan dit al. Beide applicaties kijken naar dezelfde zaak in dezelfde bron. Overdracht moet door de applicaties (consumers) worden geregeld. Aan de zaak zijn zaakobjecten gekoppeld, dit kunnen zowel RSGB-objecten zijn als andere zaakobjecten. Deze staan ook in hun eigen registraties.

**Comment by JohnRooijakkers** [comment]
@ehotting Een voorbeeld binnen het sociaal domein is dat een voorziening (bv huishoudelijke hulp of een hulpmiddel) beschikt wordt in een regiesysteem. Vervolgens vindt de administratieve en financiële afhandeling en de aansturing van de zorgverlener plaats in een backoffice. Maar dit alles wel binnen één zaak (proces) waarbij informatie over de voorziening overgedragen wordt. In de C.G. architectuur is dit geen probleem als je proces en business logica gescheiden hebt, maar bij veel gemeenten en leveranciers zijn we nog niet in die situatie beland.

**Comment by JohnRooijakkers** [comment]
> 
> 
> Volgens mij kan dit al. Beide applicaties kijken naar dezelfde zaak in dezelfde bron. Overdracht moet door de applicaties (consumers) worden geregeld. Aan de zaak zijn zaakobjecten gekoppeld, dit kunnen zowel RSGB-objecten zijn als andere zaakobjecten. Deze staan ook in hun eigen registraties.

@Hugo-ter-Doest, je gaat er hierbij vanuit dat door de Zaak API ook niet-RGBZ en niet RSGB objecten worden ondersteund ... zover zijn we niet en het lijkt me niet wenselijk om hiervan afhankelijk te zijn.
