### ISSUE TITLE
Sprintplanning

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#112]
Aan het begin van de sprint is er een sprint planning overleg. Wij doen dit op de derde donderdag van de maand na backlog refinement. De eerste is echter op woensdag 20 juni 2018. 
In principe worden de bovenste, belangrijkste user-stories van de product backlog in de sprint opgenomen. Het is cruciaal dat het ontwikkelteam de user-stories kiest die worden opgenomen, Daarom bepaalt ook het team hoeveel werk kan worden opgenomen in de betreffende sprint en is het team tevens verantwoordelijk voor de inschatting van de hoeveelheid werk per user-story. Het ontwikkelteam moet ook bevestigen dat alles duidelijk is. Taken worden dan vervolgens verder binnen het ontwikkelteam verdeeld.  

- [x] organiseren (uitnodiging/lokatie etc) dagdeel per maand (@ehotting @wishalg )
- [x]   faciliteren bijeenkomst (@eddy)
- [x]   uitwerken uitkomsten (@eddy @eelco)
- [x]   alle teamleden nemen deel (@allen)

**Comment by wishalg** [comment]
[

](url)

**Comment by jgortmaker1** [comment]
volgens mij zijn de taken nog niet klaar. ik zie nl. niets in mijn agenda..

**Comment by wishalg** [comment]
Voor de eerst backlog refinement op  woensdag 20 juni 2018 is ruimte gereserveerd bij Regardz La Vie in Utrecht (https://www.regardz.nl/locaties/#Utrecht). Vanaf 09:30 uur inclusief lunch.
