### ISSUE TITLE
## OAS Sanity check

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#1121]
**Checklist OAS**

* Introductie aanwezig en in orde?
* Autorisatie omschrijving aanwezig en orde?
* Notificatie kanaal aanwezig?

**Per resource**

* Resource titel correct?
* Resource beschrijving correct?
* Resource CRUD correct?

**Per CRUD operatie/actie**

* Operatie beschrijving correct?
* Query parameters correct?
* Benodigde scopes correct?
* Attribuut naamgeving consistent?
* Attribuut omschrijving correct?
* Attribuut validatie omschreven?

**Comment by TCIMEddy** [comment]
@joeribekker Ik heb er even issue van gemaakt.

**Comment by joeribekker** [comment]
@TCIMEddy Oh sorry, ik had em als note laten hangen.

**Comment by joeribekker** [comment]
Besluiten API gedaan, zie: https://github.com/VNG-Realisatie/gemma-besluitregistratiecomponent/pull/27/files#diff-3dc0f8f7373b32ea3bf5eabe02993f9a
