### ISSUE TITLE
Structuur inhoud ZGW API's-site: was > wordt

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1132]
Onderstaand het resultaat van het doorlopen afgelopen maandag van de structuur van ZGW API's projectwebsite met als doel beschikbare documentatie toegankelijker te presenteren door @Hugo-ter-Doest, @CMasselink en @ondergetekende.

Niet in user story-format, want eigenlijk geen US.

<p><a></a><b><span>Home</span></b><br><i><span>Doelgroep: iedereen met mogelijke interesse in ZGW API’s</span></i><br><span>Inleiding: wat vind ik op deze website? Wegwijzer. Beknopte productvisie als basis?</span><ul><li><b><span>Productvisie</span></b><span></span><ul><li><i><span>Doelgroep: van proceseigenaren en product- of categoriemanagers tot ontwikkelaars (breed dus)</span></i></li><li><span>Waarom nú deze API’s Ontwikkelingen in Gemeentelijke informatie- en ICT-landschappen: Samen Organiseren, Common Ground, etc.</span></li><li><span>Aansluiting van op Gegevenslandschap incl. verwijzing naar GEMMA Online, API-strategie.</span></li><li><span>Beschrijving API’s: o.m. welke zijn specifiek voor ZGW en welke niet?</span></span></i></li></ul></li><li><b><span>Standaard</span></b><ul><li><i><span>Doelgroep: ontwikkelaars, architecten (gemeenten/leveranciers)</span></i></li><li><span>Inleiding: samenhang API’s (welke maken onderdeel uit van de standaard) én documentatie (wat is de status van verschillende onderdelen van de documentatie (schema’s standaard.md, gegevensmodellen, achtergronddocumentatie?))</span></li><li><i><span>Verwijzing naar productvisie voor context</span></i></li><li><span>Versiebeheer: wanneer is er sprake van een nieuwe versie, krijgt de hele set een versienummer of alleen individuele API’s?</span></li><li><span>Generieke documentatie (deel standaard.md dat relevant is voor alle API’s).</span></li><li><b><span>Documentatie per API (lijst met API’s)</span></b><ul><li><span>Korte inleiding (zoals <a href="https://ref.tst.vng.cloud/standaard/apis/ac">https://ref.tst.vng.cloud/standaard/apis/ac</a>, geen onderdeel van de standaard!)</span></li><li><span>Gedrag (standaard.md)</span></li><li><span>Schema (via link)</span></li><li><span>Gegevensmodel</span></li></ul></li><li><i><span>Verwijzing naar ‘Achtergronddocumentatie’ en ‘Ontwikkelaars (tutorials) voor meer/verdiepende info</span></i></li></ul></li><li><b><s><span>Architectuur</span></s></b><b><span></span></b><ul><li><s><span>ZGW in Gegevenslandschap 0.7</span></s><span> verplaatsen naar Productvisie</span></li><li><s><span>Ontwikkelstraat</span></s><span> naar Ontwikkelaars</span></li><li><s><span>Ontwerpkeuzes</span></s><span> en <s>ZGW vs ZDS</s> naar Achtergrondinformatie</span></li></ul></li><li><b><span>Ontwikkelaars</span></b><ul><li><i><span>Doelgroep: ontwikkelaars</span></i></li><li><span>Inleiding: beschrijving hulpmiddelen (tutorials, ontwikkelstraat)</span></li><li><b><span>Tutorials per onderwerp</span></b><ul><li><span>Wat nu ‘aan de slag’, ‘demo-applicatie’ en ‘api-guides’ heet omwerken naar tutorials<b></b></span></li></ul></li><li><span>Ontwikkelstraat<b></b></span></li><li><span>Testscenario’s<b></b></span></li><li><i><span>Verwijzing naar ‘standaard voor api-specs<b></b></span></i></li></ul></li><li><b><span>Achtergronddocumentatie (nieuw) (kunnen we hier een betere naam voor bedenken?)<i></i></span></b><ul><li><i><span>Doelgroep: divers</span></i></li><li><span>Inleiding: beschrijving soorten achtergronddocumentatie en relatie tot specs. Achtergronddocumentatie is dus geen onderdeel van de standaard!<b><i></i></b></span></li><li><b><span>Achtergronddocumentatie per API<i></i></span></b><ul><li><span>Invulling verschilt</span></li></ul></li><li><span>Ontwerpkeuzes<b><i></i></b></span></li><li><span>ZGW API’s vs ZDS<b><i></i></b></span></li></ul></li><li><b><span>Samenwerking (was <i>Community</i>)<i></i></span></b><ul><li><span>Bijdragen: how-to GitHub etc (deel van wat nu ‘Hoe komen we samen tot API-standaarden’ heet)</span></li><li><span>Werkwijze (inclusief wat nu Scrum-team heet onder ‘Community’, hangt samen met <i>productvisie</i>)<b><i></i></b></span></li><li><span>Bijeenkomsten (demo’s)<b><i></i></b></span></li></ul></li><li><b><s><span>Overige<i></i></span></s></b><ul><li><i><s><span>Veelgestelde vragen</span></s></i><i><span> opnemen in Productvisie</span></i></li><li><i><s><span>Samenwerking</span></s></i><i><span> naar Samenwerking</span></i></li><li><i><s><span>Bronnen</span></s></i><i><span>, <s>Begrippenlijst</s>, <s>Type documentatie</s>, <s>Functioneel</s> en <s>Technisch</s> niet publiceren of verwijderen</span></i></li></ul></li><li><b><span>Contact (nieuw)<i></i></span></b><ul><li><span>Contact met team ZGW API’s<i></i></span></li><i><li><span>Verwijzing naar ‘how to’ bijdragen onder Samenwerking<br/></li></ul> <br/> </span></i><span></span>

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Ik zie het als onderdeel van #945

**Comment by joeribekker** [comment]
Ik sluit #945 dan.

**Comment by joeribekker** [comment]
Wie gaat dit doen @Hugo-ter-Doest?

**Comment by Hugo-ter-Doest** [comment]
Voortgang is te volgen via #1191

**Comment by Hugo-ter-Doest** [comment]
gerealiseerd met #1191
