### ISSUE TITLE
Implementatie relaties

### ISSUE THREAD

**Issue by mvdbro** [VNG-Realisatie/gemma-zaken#1157]
In de ZGW API's worden relaties naar andere resources geïmplementeerd als een array van url's voor de resource waarnaar de relatie ligt, zie bijvoorbeeld de relaties van zaaktype naar roltype, besluittype, informatieobjecttype en dergelijke. Als de relatie zelf geen eigenschappen heeft, dan is de gerelateerde resource het object waarnaar de relatie ligt (besluittype) en als de relatie wel eigenschappen heeft, dan is de gerelateerde resource de relatie zelf (zaak_informatieobjecttype) met url's voor de parent en de gerelateerde en elementen voor de eigenschappen.

Er kunnen twee keuzen gemaakt worden bij de implementatie van dit patroon in een database:

1) Bij de resources worden de lijsten met url's voor relaties vastgelegd en de database bevat geen relaties.
2) De relaties worden vastgelegd in separate tabellen met foreign keys voor de parent en de gerelateerde.

De eerste keuze leidt tot resources die als losse ongerelateerde tabellen kunnen worden geïmplementeerd, maar geeft de referentiële integriteit op. Daarnaast wordt een relatie vanuit beide richtingen onafhankelijk van elkaar bijgehouden: Bij zaaktypen wordt een array met besluittypen bijgehouden en bij besluittype een array met zaaktypen. Het identiek zijn van de relaties in beide richtingen is niet geborgd, noch is geborgd dat de resource waarnaar de relatie ligt niet wordt verwijderd. Voordeel van deze keuze is dat je bij verschillende implementaties eenvoudig kunt refereren naar resources uit een andere implementatie. Dit is gelijk een nadeel van de tweede implementatie, want hier is het leggen van relaties naar resources in een andere implementatie en daarmee in een andere database lastig. Je zal dan naast de implementatie als relatietabel ten behoeve van referentiële integriteit in de eigen implementatie ook nog bij de resource zelf een lijst van resources uit andere implementaties moeten opnemen. Een tweede nadeel van de implementatie in relatietabellen is dat je bij de get op een resource ook gelijk alle relaties moet lezen in de database om de url's te kunnen samenstellen.

Ik ben benieuwd naar de implementatiekeuze van het ontwikkelteam en hun motivatie daarvoor en naar de ervaringen van andere implementerende partijen met deze problematiek.

**Comment by Hugo-ter-Doest** [comment]
@joeribekker kun jij deze beantwoorden?

**Comment by Hugo-ter-Doest** [comment]
De standaard doet geen uitspraken over de wijze waarop een component relaties in een database opslaat. De standaard vereist wel dat je relaties moet kunnen leggen naar resources die elders (dus niet in dezelfde component) worden beheerd. Als je dus besluit om meerdere API's aan te bieden met één component (toegestaan uiteraard) moet je nog steeds om kunnen gaan met URL's naar resources die de component niet zelf heeft.

**Comment by michielverhoef** [comment]
Zo te zien is de vraag beantwoord, daarom sluit ik dit issue.
