### ISSUE TITLE
Bij het zetten van een verkeerde status op een zaak krijg ik een html pagina terug

### ISSUE THREAD

**Issue by MarkHappel** [VNG-Realisatie/gemma-zaken#1161]
# Bug

Bij het updaten van de status van een zaak had ik per ongeluk de verkeerde status url gebruikt. Namelijk een status behorende bij een ander zaaktype. In plaats van dat ik een JSON foutmelding kreeg waarin stond dat dit geen geldige zaakstatus is, kreeg ik een html pagina met http status 500.

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie):
Eigen lokale docker

**Comment by joeribekker** [comment]
Bedankt voor de melding dat zou niet moeten mogen.

Dit moet netjes afgehandeld worden middels een JSON foutmelding.

**Comment by sergei-maertens** [comment]
Fixed via #1251
