### ISSUE TITLE
Als gemeente wil ik bestaande zaaktypes kunnen gebruiken

### ISSUE THREAD

**Issue by EduardWitteveen** [VNG-Realisatie/gemma-zaken#1162]
...zodat ik deze niet:
* in de organisatie de bestaande zaaktypes kan blijven gebruiken
* de sdu (inavigator) zaaktypecode's kan blijven gebruiken
* bij een migratie van de bestaande zaaksystemen ik geen informatie kwijt raak

Wanneer "zaaktypen" binnen de ZTC gebruik, dan zal sowieso de zaaktypecode van numeriek naar alfanumeriek moeten worden omgezet. 
(in ZDS  //ZKN:object[ StUF:entiteittype='ZAK']/isVan/gerelateerde/code )

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by joeribekker** [comment]
@EduardWitteveen Het beste is dat SDU de Catalogi API specificatie implementeerd :)

Volgens mij is zaaktypecode equivalent aan onze Zaaktype.identificatie die je daarvoor kan gebruiken.

**Comment by EduardWitteveen** [comment]
Excuus, nu ik het terug lees zie ik dat ik niet geheel duidelijk ben geweest.

Ik probeer inderdaad de zaaktypecode nu in zaaktype.identificatie te plaatsen.

Helaas mag het veld zaaktype.identificatie alleen maar numerieke waarden bevatten.  Wanneer zaaktype.identificatie als type alfanumeriek is, kan dezelfde zaaktypecodes blijven gebruiken.

nb: zaak.identificatie is wel alfanumeriek

**Comment by Hugo-ter-Doest** [comment]
Opnieuw geformuleerd als #1184. Ik sluit deze.
