### ISSUE TITLE
Afleidingswijze brondatum: Ingang besluit is nog niet geimplementeerd

### ISSUE THREAD

**Issue by MarkHappel** [VNG-Realisatie/gemma-zaken#1163]
# Bug

Bij het resultaattype is "Afleidingswijze brondatum: Ingang besluit" nog niet geimplementeerd en geeft een html foutmelding als antwoord op een API call.

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:
Lokale Docker

**Comment by sergei-maertens** [comment]
Geverifieerd

**Comment by sergei-maertens** [comment]
Geïmplementeerd in develop branch
