### ISSUE TITLE
Bevragen van ZTC op GET zaaktypen?identificatie=%id% geeft alles terug

### ISSUE THREAD

**Issue by EduardWitteveen** [VNG-Realisatie/gemma-zaken#1167]
# Bug

Wanneer ik het ZTC bevraag middels een GET http://10.0.75.1:8002/api/v1/zaaktypen?identificatie=2 krijg ik veel resultaten terug, waarbij een hoop ook NIET voldoen aan het criteria.

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)

Welke claims/payload bevat je JWT?

**Comment by joeribekker** [comment]
Goed gevonden @EduardWitteveen . De OAS zegt ook niet dat je kan filteren op `identificatie` vandaar dat het niet werkt.

Echter, er had een foutmelding moeten komen dat je niet kan filteren op dit veld. Dit merk ik aan als bug.

**Comment by joeribekker** [comment]
Overigens kan je per heden filteren op `identificatie` in Zaaktypen, maar de bug blijft bestaan dat query parameters die niet bestaan en wel worden meegegeven niet leiden tot een foutmelding.

**Comment by sergei-maertens** [comment]
Fixed in https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/commit/6cb039cb6770ca3d1b50087552401c9d1f1ae119

**Comment by PDG65** [comment]
Aantal punten gecorrigeerd van 13 naar 1 omdat 13 punten van vorige sprint is en hier alleen nog review voor nodig was
