### ISSUE TITLE
Als gemeente wil ik een betere naam dan "enkelvoudiginformatieobjectcanonical"

### ISSUE THREAD

**Issue by EduardWitteveen** [VNG-Realisatie/gemma-zaken#1169]
...zodat de ambtenaren straks ook begrijpen wat de term inhoud. Termen die bij ons in de organisatie gebruikt worden zijn: "Stuk" / "Registratie" / "DigitaalDocument" / "..."

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
De term canonical komt alleen voor in de API-spec. Die krijgen medewerkers niet te zien. Is daarmee het probleem opgelost?

**Comment by EduardWitteveen** [comment]
@Hugo-ter-Doest De naam "enkelvoudiginformatieobject" is nog steeds veel te lang, zeker wanneer je het afzet tegen "Zaak", "Besluit", "ZaakType". 
Wanneer we deze naam blijven gebruiken, zal dit ook overal doorwerken in de gemeentelijke organisatie.

**Comment by Hugo-ter-Doest** [comment]
Vooralsnog volgen we RGBZ en imZTC in het gebruik van de term informatieobject (alleen enkelvoudig op dit moment). Er zijn discussies geweest over het vervangen van de term door "document". Echter documenten zijn niet hetzelfde als informatieobjecten, documenten zijn een subklasse van informatieobject. Ook moeten we op later moment wsch. nog meervoudig informatieobjecten ondersteunen. Om die redenen blijven we nog even op de oude terminologie.
