### ISSUE TITLE
Als gemeente wil ik graag duidelijkheid over het gebruik van de attributen van enkelvoudiginformatieobjecten

### ISSUE THREAD

**Issue by EduardWitteveen** [VNG-Realisatie/gemma-zaken#1170]
...zodat ik weet welke waarden waar gebruikt moeten worden en verstandig zijn om mee te nmene, 
Op dit moment zijn er een hoop attributen, welke nu allemaal zijn over genomen uit het ZTC.
Het was ons onduidelijk hoe dit te gebruiken en dit is nog steeds zo.

Mogelijke oplossingen:
* voorbeelden van "goede" registraties zodat met welk doel welk veld er staat
* obsolete maken van een aantal attribuutwaarden zodat we weten welke niet meer belangrijk zijn (en in een nieuwe versie komen te vervallen oid)

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by joeribekker** [comment]
Zou je dit specifieker kunnen maken @EduardWitteveen ? Welke attributen bedoel je?

**Comment by EduardWitteveen** [comment]
Hallo @joeribekker , in onderstaande mijn tabel waarin ik heb gekeken hoe ik de huidige gegevens (ZDS) zou gaan opslaan in de ZGW. 

Hierin valt het me op dat we de volgende velden hebben:
- enkelvoudiginformatieobjecten.titel
- enkelvoudiginformatieobjecten.beschrijving
- enkelvoudiginformatieobjecten.bestandsnaam
- enkelvoudiginformatieobjecten.link
- zaakinformatieobjecten.titel
- zaakinformatieobjecten.beschrijving
(daarnaast ontbreekt content-type, had ik niet verwacht)

Vanuit de praktijk zien er veel variatie zit in het gebruik van deze gegevens, waardoor er niet duidelijk is waar nu precies welke informatie moet worden gebruikt.
Een oplossingsroute zou kunnen zijn dat er een aantal voorbeelden die ervoor zorgen dat we weten wat voor soort gegevens de velden voor bedoeld zijn.

|ZDS xpath|ZDS Verplicht|ZGW path|ZGW Verplicht|ZDS Sample|Opmerkingen| 
|---------|-------------|--------|-------------|----------|-----------| 
|object[entiteittype='EDC']/identificatie|X|enkelvoudiginformatieobjecten.identificatie|X|190046848|
|object[entiteittype='EDC']/dct.omschrijving|X|enkelvoudiginformatieobjecten.informatieobjecttype|X|Intern document|
|object[entiteittype='EDC']/creatiedatum|X|enkelvoudiginformatieobjecten.creatiedatum|X|20190515|
|object[entiteittype='EDC']/ontvangstdatum|X|enkelvoudiginformatieobjecten.ontvangstdatum||20190515|
|object[entiteittype='EDC']/titel|X|enkelvoudiginformatieobjecten.titel|X|document.pdf|
|object[entiteittype='EDC']/beschrijving||zaakinformatieobjecten.beschrijving|
|object[entiteittype='EDC']/formaat|X|enkelvoudiginformatieobjecten.formaat||pdf|
|object[entiteittype='EDC']/taal|X|enkelvoudiginformatieobjecten.taal|X|dut|
|object[entiteittype='EDC']/versie||enkelvoudiginformatieobjecten.versie|Wel in /admin, niet in api docs|
|object[entiteittype='EDC']/status|X|enkelvoudiginformatieobjecten.status||Definitief|
|object[entiteittype='EDC']/verzenddatum||enkelvoudiginformatieobjecten.verzenddatum|
|object[entiteittype='EDC']/vertrouwelijkAanduiding|X|enkelvoudiginformatieobjecten.vertrouwelijkheidaanduiding||ZAAKVERTROUWELIJK|
|object[entiteittype='EDC']/auteur|X|enkelvoudiginformatieobjecten.auteur|X|Eduard Witteveen (Gemeente Súdwest-Fryslân)|
|object[entiteittype='EDC']/link ||enkelvoudiginformatieobjecten.link|
|object[entiteittype='EDC']/inhoud|X|enkelvoudiginformatieobjecten.inhoud||BASE64|
|object[entiteittype='EDC']/inhoud/@contentType|X|<ontbreekt>||application/pdf|Niet in ZGW|
|object[entiteittype='EDC']/inhoud/@bestandsnaam|X|enkelvoudiginformatieobjecten.bestandsnaam||document.pdf|
|object[entiteittype='EDC']/tijdvakGeldigheid/beginGeldigheid||<ontbreekt>|Niet in ZGW|
|object[entiteittype='EDC']/tijdvakGeldigheid/eindGeldigheid||<ontbreekt>|Niet in ZGW|
|object[entiteittype='EDC']/tijdstipRegistratie||zaakinformatieobjecten.registratiedatum|
|object[entiteittype='EDC']/extraElementen/extraElement/@naam||<ontbreekt>|Niet in ZGW|
|object[entiteittype='EDC']/extraElementen/extraElement||<ontbreekt>|Niet in ZGW|
|object[entiteittype='EDC']/isRelevantVoor[entiteittype='EDCZAK']/gerelateerde[ZAK]/identificatie|X|zaak.identificatie|X|1900130589|
|<ontbreekt>||zaakinformatieobjecten.aardRelatieWeergave|Niet in ZDS|
|<ontbreekt>||zaakinformatieobjecten.titel|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.bronorganisatie|X||Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.bestandsomvang|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.beschrijving|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.indicatieGebruiksrecht|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.ondertekening.soort|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.ondertekening.datum|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.integriteit.algoritme|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.integriteit.waarde|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.integriteit.datum|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.integriteit.datum|Niet in ZDS|
|<ontbreekt>||enkelvoudiginformatieobjecten.locked|Niet in ZDS|

**Comment by michielverhoef** [comment]
Hoi Eduard, het was even zoeken maar hopelijk heb ik je vraag een beetje compleet beantwoord. 

De velden die je in je eerste lijstje noemt zijn ook in RGBZ1 en StUF-ZKN/ZDS 1.x al bestaande gegevens. Kun je die niet gewoon as is mappen naar de gegevens in de API's?

enkelvoudiginformatieobjecten.titel  => https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/document#Attribuutsoort_Documenttitel
enkelvoudiginformatieobjecten.beschrijving  =>  https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/document#Attribuutsoort_Documentbeschrijving
enkelvoudiginformatieobjecten.bestandsnaam => is in ZDS/StUF ZKN een attribuut van inhoud (/object/inhoud@bestandsnaam)
enkelvoudiginformatieobjecten.link => https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/enkelvoudig_document#Attribuutsoort_Documentlink 
zaakinformatieobjecten.titel  => https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/zaakdocument#Attribuutsoort_Zaakdocumenttitel
zaakinformatieobjecten.beschrijving  =>  https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/zaakdocument#Attribuutsoort_Zaakdocumentbeschrijving

content-type => is het enkelvoudiginformatieobject.formaat https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/enkelvoudig_informatieobject.formaat

Ik heb onderstaande tabel verder aangevuld waar bij stond dat het gegeven niet in ZDS staat. Wat kan helpen is de mapping RGBZ 1 naar RGBZ 2 zoals die op GEMMA Online is geplaatst: https://www.gemmaonline.nl/images/gemmaonline/4/4c/RGBZ_1.0_naar_2.0_-_versie_0.1_20141124.zip 

Weliswaar is het RGBZ niet blind overgenomen in ZGW API's maar het overgrote deel van het gegevensmodel is wel hetzelfde. 


|ZDS xpath|ZDS Verplicht|ZGW path|ZGW Verplicht|ZDS Sample|Opmerkingen| 
|---------|-------------|--------|-------------|----------|-----------| 
|object[entiteittype='EDC']/identificatie|X|enkelvoudiginformatieobjecten.identificatie|X|190046848||
|object[entiteittype='EDC']/dct.omschrijving|X|enkelvoudiginformatieobjecten.informatieobjecttype|X|Intern document||
|object[entiteittype='EDC']/creatiedatum|X|enkelvoudiginformatieobjecten.creatiedatum|X|20190515||
|object[entiteittype='EDC']/ontvangstdatum|X|enkelvoudiginformatieobjecten.ontvangstdatum||20190515||
|object[entiteittype='EDC']/titel|X|enkelvoudiginformatieobjecten.titel|X|document.pdf||
|object[entiteittype='EDC']/beschrijving||zaakinformatieobjecten.beschrijving||
|object[entiteittype='EDC']/formaat|X|enkelvoudiginformatieobjecten.formaat||pdf||
|object[entiteittype='EDC']/taal|X|enkelvoudiginformatieobjecten.taal|X|dut||
|object[entiteittype='EDC']/versie||enkelvoudiginformatieobjecten.versie|Wel in /admin, niet in api docs| versie wordt door de DRC gezet wanneer een nieuwe versie wordt weggeschreven. Versie wordt wel teruggegeven in de GET /enkelvoudiginformatieobjecten.|
|object[entiteittype='EDC']/status|X|enkelvoudiginformatieobjecten.status||Definitief||
|object[entiteittype='EDC']/verzenddatum||enkelvoudiginformatieobjecten.verzenddatum||
|object[entiteittype='EDC']/vertrouwelijkAanduiding|X|enkelvoudiginformatieobjecten.vertrouwelijkheidaanduiding||ZAAKVERTROUWELIJK||
|object[entiteittype='EDC']/auteur|X|enkelvoudiginformatieobjecten.auteur|X|Eduard Witteveen (Gemeente Súdwest-Fryslân)||
|object[entiteittype='EDC']/link ||enkelvoudiginformatieobjecten.link||
|object[entiteittype='EDC']/inhoud|X|enkelvoudiginformatieobjecten.inhoud||BASE64||
|object[entiteittype='EDC']/inhoud/@contentType|X|<ontbreekt>||application/pdf|Niet in ZGW|Dat is /enkelvoudigInformatieobjecten/{ID}/formaat|
|object[entiteittype='EDC']/inhoud/@bestandsnaam|X|enkelvoudiginformatieobjecten.bestandsnaam||document.pdf||
|object[entiteittype='EDC']/tijdvakGeldigheid/beginGeldigheid||<ontbreekt>|Niet in ZGW||
|object[entiteittype='EDC']/tijdvakGeldigheid/eindGeldigheid||<ontbreekt>|Niet in ZGW||
|object[entiteittype='EDC']/tijdstipRegistratie||zaakinformatieobjecten.registratiedatum||
|object[entiteittype='EDC']/extraElementen/extraElement/@naam||<ontbreekt>|Niet in ZGW| Dat klopt, extraElementen worden niet toegestaan in API's. Wanneer een gegeven ontbreekt bij een resource kan dit worden toegevoegd na het indienen van een userstory etc.
|object[entiteittype='EDC']/extraElementen/extraElement||<ontbreekt>|Niet in ZGW| Dat klopt, extraElementen worden niet toegestaan in API's. Wanneer een gegeven ontbreekt bij een resource kan dit worden toegevoegd na het indienen van een userstory etc.|
|object[entiteittype='EDC']/isRelevantVoor[entiteittype='EDCZAK']/gerelateerde[ZAK]/identificatie|X|zaak.identificatie|X|1900130589||
|<ontbreekt>||zaakinformatieobjecten.aardRelatieWeergave|Niet in ZDS| Dat klopt, dit is een technisch veld wat ingevuld zal moeten worden met de vaste waarde "hoort bij, omgekeerd: kent" zoals beschreven in de OAS.|
|<ontbreekt>||zaakinformatieobjecten.titel|Niet in ZDS| Wel in RGBZ1:https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/zaakdocument#Attribuutsoort_Zaakdocumenttitel|
|<ontbreekt>||enkelvoudiginformatieobjecten.bronorganisatie|X||Niet in ZDS| In RGBZ1 en ZDS is dit de gemeentecode, de eerste 4 karakters van de documentidentificatie https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/document#Attribuutsoort_Documentidentificatie|
|<ontbreekt>||enkelvoudiginformatieobjecten.bestandsomvang|Niet in ZDS| Klopt, het RGBZ (en daarmee StUF ZKN en ZDS) bevatten geen "technische" informatie, dat is implementatie. Overigens moet dit gegeven op te vragen zijn in het DMS lijkt mij? Het is een CMIS attribuut cmisContentStreamType.length http://docs.oasis-open.org/cmis/CMIS/v1.0/errata-01/os/cmis-spec-v1.0-errata-01-os-complete.html#_Toc243905624 |
|<ontbreekt>||enkelvoudiginformatieobjecten.beschrijving|Niet in ZDS| Zowel in RGBZ1 https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/document#Attribuutsoort_Documentbeschrijving  als in ZDS /edcLk01/object/beschrijving|
|<ontbreekt>||enkelvoudiginformatieobjecten.indicatieGebruiksrecht|Niet in ZDS| Klopt, is nieuw in RGBZ2/ZGW. https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/informatieobject.indicatie_gebruiksrecht| 
|<ontbreekt>||enkelvoudiginformatieobjecten.ondertekening.soort|Niet in ZDS| Klopt, dit is nieuw in RGBZ 2/ZGW|
|<ontbreekt>||enkelvoudiginformatieobjecten.ondertekening.datum|Niet in ZDS| Klopt, dit is nieuw in RGBZ 2/ZGW|
|<ontbreekt>||enkelvoudiginformatieobjecten.integriteit.algoritme|Niet in ZDS| Klopt, dit is nieuw in RGBZ 2/ZGW|
|<ontbreekt>||enkelvoudiginformatieobjecten.integriteit.waarde|Niet in ZDS| Klopt, dit is nieuw in RGBZ 2/ZGW|
|<ontbreekt>||enkelvoudiginformatieobjecten.integriteit.datum|Niet in ZDS| Klopt, dit is nieuw in RGBZ 2/ZGW|
|<ontbreekt>||enkelvoudiginformatieobjecten.integriteit.datum|Niet in ZDS| Klopt, dit is nieuw in RGBZ 2/ZGW|
|<ontbreekt>||enkelvoudiginformatieobjecten.locked|Niet in ZDS| Staat niet in RGBZ, dit is een technisch veld wat ingevuld zal moeten worden door de implementatie. Is overigens wel een DMS gegeven en CMIS attribuut (_ChangeToken_), zie de operatie changeTokens http://docs.oasis-open.org/cmis/CMIS/v1.0/errata-01/os/cmis-spec-v1.0-errata-01-os-complete.html#_Toc243905432. In ZDS zou je dit kunnen koppelen aan het veld checkedOutId in de berichten cancelCheckout_Di01 en updateZaakdocument_Di02.|

**Comment by melsk-r** [comment]
Ik kan me de behoefte van Eduard wel voorstellen. Als het voor ons redelijk eenvoudig is om in deze overzichten te voorzien dan moeten we dat niet nalaten.
Overigens kun je bij de properties in de yaml bestanden examples opnemen.
Dat is nu misschien met een goede reden niet gedaan maar anders zouden we kunnen bekijken of we die op kunnen nemen dan hoeven we ze niet op te nemen in de bovenstaande overzichten.

**Comment by michielverhoef** [comment]
Bij ons bezoek aan Sudwest Frysland zullen we dit doornemen en waar nodig meer/andere informatie toevoegen.
