### ISSUE TITLE
Als zaakbehandelaar wil ik een betrokkene met rol 'gemachtigde' kunnen toevoegen aan een zaak

### ISSUE THREAD

**Issue by wvnoortroxit** [VNG-Realisatie/gemma-zaken#1177]
Als zaakbehandelaar wil ik een betrokkene met rol 'gemachtigde' kunnen toevoegen aan een zaak zodat de betrokkenen in het ZRC matchen met de betrokkenen in het originele OLO of DSO-bericht.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Voor nu breiden we de enum uit voor gemachtigde. Bij nieuwe uitbreidingen stappen we over op een referentietabel.

**Comment by ArnauldvdHeijden** [comment]
Gemachtigde is geen rol meer in RGBZ 2 maar een indicatie op een rol.

**Comment by wvnoortroxit** [comment]
Terechte opmerking. Maar dan zou in de API het indicatie-veld toegevoegd moeten worden. 

Voor een OLO- of DSO-verzoek bericht is de enige manier nu om een gemachtigde toe te voegen de rol "initiator" te gebruiken, en in de roltoelichting aan te geven dat het om de gemachtigde gaat. Dit is echter een tekst-veld zonder constraints. De ZRC kan dan niet eenduidig bepalen wat de echte initiator is van de aanvraag.

**Comment by ArnauldvdHeijden** [comment]
"Maar dan zou in de API het indicatie-veld toegevoegd moeten worden." 
Dit zou ook mijn gewenste oplossing zijn. Hiermee blijft de standaard in lijn met RGBZ 2 en motiveert dit de DSO hopelijk om de nieuwe standaard te adopteren.

**Comment by sergei-maertens** [comment]
indicatieveld toevoegen lijkt me prima (als dat al in RGBZ zit)

**Comment by joeribekker** [comment]
@ArnauldvdHeijden @wvnoortroxit bedankt voor de toelichting. Hoewel ik vermoed dat weinig gebruik wordt gemaakt van RGBZ 2 lijkt me dit wel de juiste invulling.

Uit RGBZ 2 en de invulling van de ticket, in afwijking van wat @Hugo-ter-Doest heeft aangegeven, voegen we het volgende enum attribuut toe:

`indicatieMachtiging` (niet verplicht, ofwel, mag `null` zijn)

- `gemachtigde` (de betrokkene in de rol bij de zaak is door een andere betrokkene bij dezelfde zaak gemachtigd om namens hem of haar te handelen).
- `machtiginggever` (de betrokkene in de rol bij de zaak heeft een andere betrokkene bij dezelfde zaak gemachtigd om namens hem of haar te handelen)
