### ISSUE TITLE
In demo applicatie is product verplicht maar in API-specificatie niet

### ISSUE THREAD

**Issue by wvnoortroxit** [VNG-Realisatie/gemma-zaken#1178]
# Bug
In de demo applicatie is het product een verplicht veld, maar in de API-specificatie en de implementatie van de API methode voor het aanmaken van een zaak niet. Daardoor kan een zaak die is aangemaakt via de API (zonder product) niet worden gewijzigd in de demo applicatie.

Of de specificatie en de implementatie van de API bevat een fout, of de demo applicatie is fout.

Geconstateerd  bij de docker images voor de ZRC, gehost op lokale ontwikkel machine. 

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

**Comment by joeribekker** [comment]
Goed opgemerkt, lagere prio omdat het in de admin zit wat buiten de standaard valt.

product of dienst moet optioneel zijn inderdaad.

Bron: https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/zaak.product_of_dienst

**Comment by joeribekker** [comment]
Is meegegaan in andere update van #925
