### ISSUE TITLE
HTML en 404 bij het opvragen van enkelvoudiginformatieobjecten zonder authorisatie

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1180]
# Bug

In Postman doe ik de volgende call: https://ref.tst.vng.cloud/drc/api/v1/enkelvoudiginformatieobjecten/

Ik heb authorisatie gezet op "no authorization". Dan krijg ik een 404 error in een HTML pagina (zie onder). Doe ik gewoon iets verkeerd of krijg ik de verkeerde foutmelding terug?

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="/drc/static/vng_api_common/libs/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/drc/static/vng_api_common/libs/fontawesome/css/all.min.css">
        <link rel="icon" type="image/png" href="/drc/static/vng_api_common/ico/favicon.png">
        <title>Document Registratie Component (DRC) | Documenten</title>
    </head>
    <body>
        <h1>Sorry, the requested page could not be found (404)</h1>
        <div class="container">
            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        <img class="mb-2" src="/drc/static/vng_api_common/img/vng.svg" alt="" width="96" height="50">
                        <small class="d-block mb-3 text-muted">&copy; 2019</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Resources</h5>
                        <ul class="list-unstyled text-small">
                            <li>
                                <a class="text-muted" href="https://github.com/VNG-Realisatie/gemma-zaken/">Code op Github</a>
                            </li>
                            <li>
                                <a class="text-muted" href="https://ref.tst.vng.cloud/">Documentatie</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
          </div>
                    <div class="col-6 col-md">
                        <h5>Over Common Ground</h5>
                        <ul class="list-unstyled text-small">
                            <li>
                                <a class="text-muted" href="https://commonground.nl/">Common Ground</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </footer>
        </div>
        <script src="/drc/static/vng_api_common/libs/jquery/jquery-3.3.1.slim.min.js"></script>
        <script src="/drc/static/vng_api_common/libs/popper/popper.min.js"></script>
        <script src="/drc/static/vng_api_common/libs/bootstrap/js/bootstrap.min.js"></script>
        <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>
    </body>
</html>

[beschrijf de bug]

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)

Welke claims/payload bevat je JWT?

**Comment by sergei-maertens** [comment]
Heb je effectief met trailing slash de call gedaan? Die 404't inderdaad (correct), maar zonder trailing slash moet die 't wel doen.

**Comment by joeribekker** [comment]
Werkt naar behoren. @michielverhoef Graag heropenen indien het toch anders zit.
