### ISSUE TITLE
Als beheerder wil ik dat er gebruiksvoorwaarden voor de referentie-implementaties worden opgesteld

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1181]
...zodat helder is onder welke voorwaarden leveranciers en gemeenten gebruik mogen maken van de referentie-implementaties. Met name dat wordt vastgelegd dat het niet toegestaan is privacygevoelige informatie in de referentiecomponenten weg te schrijven.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by michielverhoef** [comment]
@Hugo-ter-Doest , is dit iets? Ik wil het niet te ingewikkeld maken en het moet denk ik alleen gaan over de door VNG gehoste referentieimplementaties, niet over de repositories met code of docker containers die men lokaal draait.
/*****/

Deze gebruiksvoorwaarden zijn van toepassing op de referentieimplementaties zoals gehost door VNG Realisatie, hierna te noemen de referentieimplementatie. Voor gebruik van een dockercontainer met daarin een referentieimplementatie en/of onderliggende broncode in een andere omgeving is voor elke referentieimplementatie de EUPL Licentie van toepassing. Deze EUPL Licentie is te vinden in de Github repository waar de broncode en documentatie van de referentieimplementatie staat.

Doel van de referentieimplementaties:
* Een referentieimplementatie is een onderdeel van de API standaard en heeft als doel om:
** Aan te tonen dat het mogelijk is om de API te realiseren
**  Het gewenste gedrag van de API te demonstreren
**  Gebruikers van de API standaard (ontwikkelaars) hun implementatie te testen

Wat is wel toegestaan?
* elk gebruik dat voldoet aan de doelen waarvoor de referentieimplementaties ontwikkeld zijn.

Wat is niet toegestaan? 
* Het opslaan en/of verwerken van privacy gevoelige gegevens . Onder privacy gevoelige gegevens wordt verstaan gegevens die:
** Bestaande personen, organisaties of situaties weergeven
** Of te herleiden zijn naar bestaande personen, organisaties of situaties
* Gebruik van de referentieimplementatie en/of de onderliggende gegevensopslag en/of infrastructuur voor andere doeleinden dan verduidelijking en beproeven van de API standaard die door de rereferentieimplementatie ondersteund wordt.


VNG Realisatie is niet verantwoordelijk voor (foutief) gebruik, misbruik en/of het openbaar worden van gegevens. Er kunnen geen rechten aan gebruik van de referentieimplementatie worden ontleend. Gegevens die voor (test)doeleinden gepersisteerd worden zijn vrij toegankelijk voor alle gebruikers van de referentieimplementatie en kunnen door alle gebruikers ingezien en aangepast of verwijderd worden.

**Comment by Hugo-ter-Doest** [comment]
Lijkt me goed zo. Nu een plekje zoeken in de documentatie.

**Comment by Hugo-ter-Doest** [comment]
met #1218 gerealiseerd.
