### ISSUE TITLE
Description ontbreekt bij http returncodes in OAS bestanden

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1186]
# Bug
Bij alle OAS bestanden (behalve die van de Besluiten API) ontbreken de descriptions van de responses. 

[beschrijf de bug]

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)

Welke claims/payload bevat je JWT?

**Comment by joeribekker** [comment]
Zie: https://github.com/VNG-Realisatie/vng-api-common/pull/72
