### ISSUE TITLE
Als gemeente wil ik alle bestaande (relevante) zaak-gegevens (ZDS) via ZGW-api kunnen ontsluiten

### ISSUE THREAD

**Issue by EduardWitteveen** [VNG-Realisatie/gemma-zaken#1188]
...zodat ik geen gegevens kwijt raak wanneer ik de ZGW api ga gebruiken.

1 - We gebruiken nu zaak-dossiers die aangemaakt/gevuld zijn mbv. ZDS en ook in de toekomst willen we de gegevens die hierin staan ontsluiten 
2- We willen één bron voor onze zaak-dossiers, wanneer de zaak-gegevens op verschillende plekken staan doen we afbreuk aan onze uitgangspunten en weten we ook niet waar we allemaal moeten zoeken vanuit bvb. een pip/kcc-applicatie
3 - We willen de bestaande ZDS-backoffice-applicaties nog een ruime termijn blijven gebruiken (~5 jaar) omdat we hier de contracten zo op hebben afgesloten en hier niet ZGW ondersteuning op zit
4 - We willen zo snel mogelijk de ZGW api gaan gebruiken.

Los van welke migratie strategie je hiervoor gaat gebruiken, betekend dit dat alles wat via ZDS is opgeslagen/ontsloten worden ook via de ZWG api moet kunnen worden ontsloten.

Wanneer dit niet het geval is, zal dit een overgang naar ZGW bemoeilijken, omdat dit dan conversies/transformaties, of zelfs breder wijzigingen nodig zijn om het te implementeren

Op dit moment is gebleken dat bij zaaktype.identificatie en enkelvoudiginformatieobjecten.contenttype de nieuwe standaard "smaller" is en de informatie dus niet kan worden opgeslagen/ontsloten

Ook gezien de ervaringen met andere api-updates en zaaktype/contenttype moet dit aantoont worden. Een mogelijke oplossing hiervoor zou kunnen zijn door alle (relevante) gegevens uit een zaaksysteem te bevragen via ZDS en deze via ZGW op te slaan in een ander zaaksysteem om dit aan te tonen.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Graag aangeven welke gegevens je mist in de ZGW API's en user stories opvoeren.

**Comment by EduardWitteveen** [comment]
Wanneer ik moet aangeven welke gegevens ik mis in de ZGW-api's vraagt dat ik ga aantonen dat de gegevens uit ZDS in ZGW-api's moeten passen. 

Dit vraagt een aardige inspanning van mijn kant en ik weet niet wat ik tegen ga komen: Graag wil ik dan vooraf weten of het ook een uitgangspunt is: dat ZDS gegevens inprincipe in de ZDS standaard moeten passen. Daarnaast voorzie ik mogelijk een conflict met #1181 omdat deze in de huidige vorm ook voor lokaal gebruik geldt.

Wanneer deze toezegging er ligt, kan ik er in mee gaan om voor de gevallen die ik tegen kom hier losse user stories voor op te voeren.

**Comment by Hugo-ter-Doest** [comment]
Dat is niet het uitgangspunt geweest. Uitgangspunt is dat de ZGW API's worden ontwikkeld op basis van user stories, dus echt gebruik in de praktijk. Nogmaals, als je bepaalde attributen mist en toegevoegd wilt zien, graag opvoeren.
