### ISSUE TITLE
User Stories op de backlog (Github) zetten 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#119]
We hebben tijdens de 3-daagse afgesproken dat iedereen user stories opvoert conform format

Omdat het issue niet is toe te wijzen aan meer dan 10 personen hieronder een opsomming van alle teamleden op GitHub. Graag via slack aan mij doorgeven dat je deze taak hebt uitgevoerd (of via wekelijkse call) dan zet ik het vinkje erbij (het is met GitHub even niet anders)

- [ ] @MarcelMoerman 
- [ ] @wishalg 
- [ ] @michielverhoef 
- [ ] @jgortmaker1 
- [ ] @ehotting 
- [ ] @BoerBas 
- [ ] @andyverberne 
- [ ] @Hugo-ter-Doest 
- [ ] @ppcjansen 
- [ ] @joeribekker 
- [x] @sergei-maertens 
- [ ] @lazo
- [ ] @EdwinCoster 
- [ ] @RvdKlip 
- [ ] @RitaBerghuis 
- [ ] @CMasselink

**Comment by Hugo-ter-Doest** [comment]
vinkje (ik kan het issue niet bewerken)

**Comment by TCIMEddy** [comment]
Ik begrijp van Hugo (dank) dat het vinken niet werkt, aangezien dit waarschijnlijk alleen kan wanneer je assignee bent. Geef het dus maar door aan mij via slack of tijdens de call dan regel ik het (grrrr)

**Comment by michielverhoef** [comment]
Dit issue blijft denk ik het hele project open staan omdat er altijd wel user stories boven kunnen komen.
Of gaat dit alleen over alle user stories die we nu kunnen verzinnen?

**Comment by TCIMEddy** [comment]
Mee een Michiel! zal iedere sprint wellicht terugkomen. Voor nu even belangrijk dat iedereen de user stories opvoert die voorbij gekomen zijn tijdens de 3-daagse en alle nieuwe uiteraard

**Comment by TCIMEddy** [comment]
Kun jij vinkje zetten Michiel? of werkt het bij jou ook niet. Vinkje kun je weer weghalen :-) indien nog niet gereed

**Comment by TCIMEddy** [comment]
Deze taak staat er dubbel op dus deze gesloten!
