### ISSUE TITLE
Als gemeente wil ik maximaal 1 initiator kunnen aanwijzen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1190]
...zodat het onmogelijk is om er meerdere te hebben.

Komt voort uit comment in #503 en is volgens RGBZ maar ik kan niet inschatten of het nooit moet kunnen voorkomen dat meerdere mensen een initiator zijn.

---

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by adgerrits** [comment]
Zie https://discussie.kinggemeenten.nl/discussie/gemma/stuf-301-zkn/zaak-met-meerdere-initiators voor welles-nietes discussies. Ik ben van het M:N kamp en vindt het vreemd dat er argumenten worden genoemd als: ‘komt maar weinig voor’. Ps: zowel in informatiemodel als technisch datamodel ;)

**Comment by Hugo-ter-Doest** [comment]
@adgerrits discussie op kinggemeenten doorgenomen. Zo te lezen is er behoefte aan de mogelijkheid meerdere initiatoren te koppelen. De werkgroep informatiemodellen heeft voor een suboptimale oplossing gekozen door een nieuw roltype te introduceren t.w. mede-initiator. Ik wil hiervan afwijken door meerdere initiatoren toe te staan. De consumers zijn vervolgens verantwoordelijk om hier goed mee om te gaan.

**Comment by Hugo-ter-Doest** [comment]
Ik sluit deze n.a.v. voorgaande discussie, en open #1239 om meerdere initiatoren toe te staan.
