### ISSUE TITLE
Als persoon of vertegenwoordiger van een persoon met een zaak bij de/ een overheid  wil ik kunnen reageren op een vraag, verzoek of opmerking bij mijn zaak

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#12]
Zodat mijn zaak in behandeling genomen kan worden dan wel verder behandeld kan worden

**Comment by ehotting** [comment]
Klantcontacten moeten afgehandeld worden middels CRM functionaliteit. Vanuit een dergelijke 'client' kunnen documenten worden toegevoegd etc. Vragen aan de klant kunnen vanuit zaakafhandelcomponent worden geïnitieerd, eventueel via CRM. Ik denk dat dit out-of-scope is. 

@jgortmaker1 Wat is jouw mening mbt klantcontacten?

**Comment by jgortmaker1** [comment]
Gaat deze US niet specifiek over het registreren van ene klantcontact en het relateren daarvan aan een zaak? Dat lijkt me wel binnen scope?

**Comment by Hugo-ter-Doest** [comment]
Kan functionaliteit van de ZAC zijn.
