### ISSUE TITLE
Website niet bereikbaar

### ISSUE THREAD

**Issue by JohnRooijakkers** [VNG-Realisatie/gemma-zaken#1201]
# Impediment

Website https://zaakgerichtwerken.vng.cloud/standaard/standaard is niet bereikbaar. Bij benadering volgt een 500-error (nginx/1.16.0). Is er een tijdelijk probleem of zijn / worden deze sites verplaatst naar de common ground website?

[assign aan Eddy, voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by Hugo-ter-Doest** [comment]
Ziet eruit als een foute link, waar heb je die gevonden? Dan kunnen we hem repareren.

**Comment by JohnRooijakkers** [comment]
@Hugo-ter-Doest deze staat in mijn browser favorieten en heb ik de afgelopen maanden gebruikt om naar de ZGW API documentatie te gaan.

Zelfde probleem speelt bij deze URL's:
https://zaakgerichtwerken.vng.cloud/overige/technisch/zds-vs-zgw

Deze werkt overigens wel correct:
https://zaakgerichtwerken.vng.cloud/

**Comment by Hugo-ter-Doest** [comment]
Als het in je favorieten staat, kan het inderdaad gebeuren dat wij in de tussentijd de structuur aanpassen. We hebben een volledig nieuwe structuur uitgerold deze week.

Relatie tussen onze API's en ZDS staat nu hier onder thema's: https://zaakgerichtwerken.vng.cloud/themas/achtergronddocumentatie/zds-en-zgw-apis

**Comment by JohnRooijakkers** [comment]
Thanks

**Comment by Hugo-ter-Doest** [comment]
Er zitten blijkbaar nog fouten in de voorpagina. Zie ook #1202. We werken eraan!
