### ISSUE TITLE
Link verwijst naar verkeerde pagina

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#1202]
# Bug in documentatie

### Main
De link op https://zaakgerichtwerken.vng.cloud/ bij 'De standaard staat hier beschreven' verwijst naar https://zaakgerichtwerken.vng.cloud/standaard/standaard. Dit resulteert in een 500 Internal Server Error. De juiste URL is https://zaakgerichtwerken.vng.cloud/standaard.

De link naar https://zaakgerichtwerken.vng.cloud/ontwikkelaars/aan-de-slag  ('direct aan de slag') moet ook aangepast worden. Ik vermoed dat '/aan-de-slag' er af kan.

En 'API's' moet van https://zaakgerichtwerken.vng.cloud/standaard/apis/index naar https://zaakgerichtwerken.vng.cloud/standaard/

### Standaard
Op https://zaakgerichtwerken.vng.cloud/standaard/ verwijst 'API strategie voor de Nederlandse overheid' naar https://zaakgerichtwerken.vng.cloud/standaard/api-strategie en dat moet (denk ik) https://docs.geostandaarden.nl/api/API-Strategie/ zijn.

'DSO API- en URI-strategie' verwijst naar https://zaakgerichtwerken.vng.cloud/standaard/dso-strategie en dat moet https://aandeslagmetdeomgevingswet.nl/digitaal-stelsel/technisch-aansluiten/standaarden/api-uri-strategie/ worden (zo staat het in de Productvisie).

Datzelfde geld voor 'API-20' link daaronder.

Welke URL jullie achter 'JSON-schema' willen hangen moeten jullie zelf even bepalen. De huidige (https://zaakgerichtwerken.vng.cloud/standaard/json-schema) is niet OK.

###Ontwikkelaars
Op https://zaakgerichtwerken.vng.cloud/ontwikkelaars/ verwijst 'Achtergronddocumentatie' naar https://zaakgerichtwerken.vng.cloud/themas/achtergronddocumentatie/index en dat moet https://zaakgerichtwerken.vng.cloud/themas/ worden.

###Ontwikkelstraat
In de tekening op https://zaakgerichtwerken.vng.cloud/themas/achtergronddocumentatie/ontwikkelstraat wordt nog verwezen naar ref.tst.vng.cloud.

Onder 'Ondersteunende tooling' is nog steeds sprake van een 'overige registratiescomponent'.

In het overzicht van de referentieimplementaties onder 'Kubernetes' zijn de adressen geen URL's

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? zaakgerichtwerken.vng.cloud (documentatie).

Welke claims/payload bevat je JWT? n.v.t.

**Comment by EdwinCoster** [comment]
Iemand gaat vast roepen dat ik een PR moet aanmaken...

**Comment by EdwinCoster** [comment]
Ja @Hugo-ter-Doest ik las dat issue en dacht, iemand is mij voor...maar hij gebruikte een favorietje...

**Comment by Hugo-ter-Doest** [comment]
Michiel heeft al een PR gemaakt.

**Comment by michielverhoef** [comment]
> Op https://zaakgerichtwerken.vng.cloud/ontwikkelaars/ verwijst 'Achtergronddocumentatie' naar https://zaakgerichtwerken.vng.cloud/themas/achtergronddocumentatie/index en dat moet https://zaakgerichtwerken.vng.cloud/ontwikkelaars/ worden.


@EdwinCoster : ik kan "achtergronddocumentatie" niet vinden op https://zaakgerichtwerken.vng.cloud/ontwikkelaars/ maar het lijkt me raar om op een pagina naar diezelfde pagina te verwijzen?

**Comment by EdwinCoster** [comment]
My bad, het moet https://zaakgerichtwerken.vng.cloud/themas/ zijn. De titel van die pagina is Achtergronddocumentatie.

**Comment by michielverhoef** [comment]
Ah. het is even de vraag of het kopje in het menu dan niet beter achtergronddocumentatie kan heten?

De title van dat bestand (https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/themas/index.md)  is nl. "Achtergronddocumentatie". Maar eea. staat juist in een map genaamd "themas".
ik zou zeggen hernoem de folder themas naar achtergrondinformatie. 
@Hugo-ter-Doest wat vind jij?

**Comment by Hugo-ter-Doest** [comment]
Nee, dat vonden we nu juist niet mooi. Ik heb vervolgens thema's voorgesteld, en daar is het bij gebleven.

**Comment by michielverhoef** [comment]
Ok, dan pas ik de titel aan

**Comment by Hugo-ter-Doest** [comment]
kan deze dicht?

**Comment by EdwinCoster** [comment]
Ik had nog 3 opmerkingen toegevoegd uit de Ontwikkelstraat pagina...dus nee.

**Comment by Hugo-ter-Doest** [comment]
Laatste issues opgelost via #1227
