### ISSUE TITLE
referentie implentatie: account gelocked

### ISSUE THREAD

**Issue by EduardWitteveen** [VNG-Realisatie/gemma-zaken#1206]
# Bug
Ik heb de referentie implementatie lokaal draaien.  Na 3 keer verkeerde te hebben ingelogd op http://10.0.75.1:8000/admin/login/?next=/admin/ (ZRC)  krijg ik de melding: "Account locked: too many login attempts. Please try again later" Ik heb later geprobeerd om opnieuw in te loggen, maar ik blijf de melding krijgen.

De tekst "Please try again later" suggereert dat ik moet wachten en het later weer gaat werken.
Ik heb gewacht (halfuurtje ofzo), maar ik kan nog steeds niet het login scherm ervoor krijgen

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)

Welke claims/payload bevat je JWT?

**Comment by michielverhoef** [comment]
Hmmm, dat is knap vervelend. Omdat op dit moment iedereen, dus ook/vooral Joeri en Sergei met de laatste loodjes voor morgen (18/7) bezig zijn kan het zijn dat dit pas vrijdag oid opgepakt wordt.

Maar het is zeker een dingetje wat opgelost moet worden!

**Comment by sergei-maertens** [comment]
@EduardWitteveen 

met de services draaiende, in een nieuwe shell/tab

```bash
docker-compose exec zrc_web src/manage.py axes_reset
```

**Comment by sergei-maertens** [comment]
Daarnaast - ben je zeker dat je een supergebruikeraccount aangemaakt hebt?

```bash
docker-compose exec zrc_web src/manage.py createsuperuser
```

**Comment by sergei-maertens** [comment]
Ik sluit dit issue wegens inactiviteit. Als er toch nog iets blijkt fout te zijn, dan kan deze wel heropend worden.
