### ISSUE TITLE
De ZGW demo geeft foutmeldingen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1215]
# Bug

De demo ZGW api's geven een authenticatie error: 'Authenticatiegegevens zijn niet opgegeven. '. Bijvoorbeeld: https://zgw-demo.vng.cloud/apps/mijngemeente/

**Comment by joeribekker** [comment]
Klopt, de demo app moet nog bijgewerkt worden.

**Comment by Hugo-ter-Doest** [comment]
@sergei-maertens bij de standup zei je hier iets over...gereed? close?

**Comment by sergei-maertens** [comment]
@joeribekker weet volgens mij beter wat de status is

**Comment by joeribekker** [comment]
Laatste docker image geupload, moet alleen nog even een trigger komen voor k8s om deze op zgw-demo.vng.cloud te zetten.

**Comment by joeribekker** [comment]
@CMasselink volgens mij werkt het nu maar als je kan bevestigen, graag.
