### ISSUE TITLE
MOR demo applicatie google maps kaart geeft een foutmelding

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1216]
# Bug

De MOR demo applicatie geeft een foutmelding bij het tonen van de kaart:
Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://zgw-demo.vng.cloud/apps/mor/

**Comment by joeribekker** [comment]
Ah ja, de nieuwe domeinen moeten authorized worden bij Google. En de demo app moet in zijn geheel nog geupdate worden.

**Comment by joeribekker** [comment]
Domein toegevoegd. Probleem verholpen.
