### ISSUE TITLE
Als gebruiker wil ik weten wat precies tot 'de standaard' wordt gerekend

### ISSUE THREAD

**Issue by adgerrits** [VNG-Realisatie/gemma-zaken#1229]
...zodat ik daar rekening mee kan houden bij toepassing er van.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by adgerrits** [comment]
Aanleiding was #910 waarin staat "Deze beslissing wijkt dus af van het mantra "spec en implementatie loopt in de pas", maar dit komt omdat het NRC en het AC op de rand van de scope ZGW zitten. Eigenlijk moet een ander team (of zelfde team in ander projectvorm) dit oppakken.". In de '1.0.0-rc1: Release candidate 1 van versie 1.0.0' zie ik dat NRC en AC zijn opgenomen waarbij ik me afvraag of dit betekent dat ze ook worden gezien als behorend tot de standaard. Meer algemeen geldt dat het me nuttig lijkt om helder te beschrijven hoe de standaard zich verhoudt tot de referentiecomponenten (enkele eerdere beschrijvingen daarvan leveren nu een 404).

**Comment by Hugo-ter-Doest** [comment]
Je bent niet verplicht alle API's te implementeren, maar er zijn wel afhankelijkheden. Als je bijv. de Zaken API implementeert, heb je de Catalogi API nodig. Als je een van Documenten, Zaken, Catalogi, Besluiten implementeert, heb je een Notificaties en Autorisaties API nodig. etc.  Die afhankelijkheden betekenen niet dat je het ook zelf moet implementeren, je kunt gebruik maken van API's van anderen.

De afhankelijkheden zijn beschreven in de API-specificaties, maar nog niet (zo expliciet) in de documentatie. Dat gaan we verbeteren.

We beschouwen de Notificaties en Autorisaties API als onderdeel van de standaard, maar verwachten een doorontwikkeling als generieke API's voor het gemeentelijk gegevenslandschap. 

De relatie met de referentiecomponenten kijk ik even naar. Maar het kan ook betekenen dat de referentiecomponenten moeten worden bijgesteld.

**Comment by Hugo-ter-Doest** [comment]
Afhankelijkheden toegevoegd via #1232

**Comment by hdksi** [comment]
Hoewel ik niet zeker ben of de vraag van @adgerrits zo concreet moet worden opgevat, hier een kopie van een reactie elders ter referentie aan toekomstige bezoekers.

Héél in het kort: alle API's behoren tot de standaard, maar uiteraard hoeven ze (afhankelijk van het gebruiksdoel) niet altijd allemaal geïmplementeerd te worden. De OAS3-specificatie en de beschrijving van het vereiste 'run-time'-gedrag zijn leidend en vormen de standaard. De referentie-implementatie is daarbij ondersteunend, maar in principe komen de twee overeen. Uitzondering hierop is het Notificatiecomponent: hier wordt door de referentieimplementatie niet de (betrouwbaarheids-/fallback)functionaliteit geboden die in de specificaties wél wordt vereist (#910). Gezien de hiërarchie van de verschillende onderdelen van het ZGW API-landschap zou hieruit duidelijk moeten worden dat die functionaliteit wél noodzakelijk is om aan de standaard te voldoen.

Wellicht kunnen we dit in de documentatie nog duidelijker beschrijven.

**Comment by Hugo-ter-Doest** [comment]
Zie ook #1232 

Rest nog de relatie met referentiecomponenten.

**Comment by adgerrits** [comment]
Voor alle helderheid: "Als je een van Documenten, Zaken, Catalogi, Besluiten implementeert, heb je een Notificaties en Autorisaties API nodig. etc." => Om (alleen) de 'Documenten API' te gaan gebruiken moet ik dus de Documenten, Notificaties en Autorisaties API's gebruiken. - 
(Ps: in [index.md](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/index.md) zie ik in de afbeelding ook een Referentielijsten-API, maar die wordt verder niet beschreven + linkje naar overkoepelend gegevensmodel moet nog worden ingevoegd.)

**Comment by melsk-r** [comment]
Ivo schrijft:

> Héél in het kort: alle API's behoren tot de standaard, ......

Hier wordt toch weer gerefereerd aan een hoger geheel (ZGW) dat als standaard wordt gezien. Misschien is het handiger om ZGW als een thema te beschouwen. Om het ZGW thema dan in zijn geheel in te kunnen vullen moet je kunnen beschikken over alle in dit project gebouwde API standaarden.

**Comment by adgerrits** [comment]
Issue mag van mij worden gesloten, maar het lijkt me nog steeds nuttig om een keer nauwkeurig te formuleren wat in deze contect met 'de standaard' wordt bedoeld. Zoals @melsk-r het formuleert vind ik het helder: je hebt API's die voor het doel dat ze hebben als 'standaard' worden beschouwd (en waar je in combinatie gebruik van kunt maken, bijv. om ZGW mee te ondersteunen) maar is het (toch?) wat anders dan in de [Read.me](https://github.com/VNG-Realisatie/gemma-zaken) staat: "Deze repository bevat alles wat nodig is voor de ontwikkeling van een nieuwe standaard rond Zaakgericht Werken, welke in samenwerking tussen verschillende partijen tot stand komt. Concrete resultaten zijn een OpenAPI Specificatie van de nieuwe Zaak- en Documentservices (v2.0) en bijbehorende referentie-implementaties met persistente data."

**Comment by CMasselink** [comment]
Staat reeds in documentatie
