### ISSUE TITLE
Aanleveren test data en mapping op RGBZ

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#123]
# Impediment

Een aantal User Stories / Taken van gemeentes vereist de benodigde velden, mapping op RGBZ (indien mogelijk), en aanleveren test data.

**Comment by TCIMEddy** [comment]
Als het goed is, is dit inmiddels beschikbaar gemaakt vanuit Haarlem (Bas) en Rotterdam (Ruud) Bij Paul staat het vandaag op de agenda

**Comment by TCIMEddy** [comment]
Volgens mij heeft iedereen aangeleverd (feedback vanuit teamleden ivm mappen rgbz van harte welkom)
