### ISSUE TITLE
Als API-beheerder wil ik een testscript dat checkt of een implementatie van een ZGW API voldoet aan de beschrijving van het gewenste gedrag die bij de OAS-specificatie hoort

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1233]
zodat we meer vertrouwen hebben dat de provider-implementatie voldoet aan de standaard inclusief de beschrijving van het gewenste gedrag.

**Toelichting**

Momenteel wordt er al gewerkt aan een [Postman script](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/ontwikkelaars/handleidingen-en-tutorials/test-scenarios.md) dat het gewenste gedrag van de ZGW API's test zoals dat beschreven is in het standaard.md document. Echter dit document beschrijft precies de aanvullende eisen die niet gespecificeerd kunnen worden in een OAS-specificatie. Dus het voorgestelde script is hierop een (noodzakelijke) aanvulling.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by HenriKorver** [comment]
Postman biedt al functionaliteit om een OAS te converteren naar een Postman collection:

https://documenter.getpostman.com/view/1681967/SVYjT2GX?version=latest#93635cd2-e184-48f5-8dcd-fa279652fa51

Echter om de calls echt aan de praat te krijgen moet er nog wel een handmatige slag overheen.

**Comment by HenriKorver** [comment]
De uitgeklapte calls in onderstaande screenshot heb ik reeds werkend gekregen:

![afbeelding](https://user-images.githubusercontent.com/37145898/61910378-c16fca80-af34-11e9-890a-d1c8b7000ccd.png)

**Comment by stevenbal** [comment]
het postman script voor de OAS tests staat [hier](https://github.com/VNG-Realisatie/gemma-postman-tests/blob/master/ZGW_OAS_tests.json) geupload

**Comment by joeribekker** [comment]
Wat mij betreft is dit ticket daarmee afgerond.
