### ISSUE TITLE
Intellectueel Eigendom in beheer van VNG Realisatie

### ISSUE THREAD

**Issue by wishalg** [VNG-Realisatie/gemma-zaken#124]
# Intellectueel Eigendom in beheer van VNG Realisatie

- [ ] Opstellen praktisch uitvoerbare instructies over IP
  - [ ] In overleg met developers, want juridisch juist != werkt ook voor devs
  - [ ] Moet er iets over © in elk source file, zo ja, wat
  - [ ] Is een Developer Certificate of Origin wenselijk
  - [ ] Hoe werkt het voor (niet-gecompenseerde) contributors
- [ ] Uitzoeken: Is overeenkomst nodig, zo ja, welke inhoud en met wie

Suggestie: Externe expertise inzetten om het voor alle volgende projecten ineens helder te hebben. Is geen triviaal onderwerp en werkt bij Open Source anders dan bij andere software.

**Comment by TCIMEddy** [comment]
@BoerBas Zou jij hier iets zinvols over willen zeggen? Voor de open source componenten is het duidelijk (dan is er volgens mij geen eigendom). Voor de API's weet ik het eigenlijk niet!

**Comment by TCIMEddy** [comment]
@wishalg In het vervolg ook bij project Organisatie & Impediment aangeven anders komt het niet op het bord (en zie ik het te laat)

**Comment by ehotting** [comment]
Heb in voorgaande trajecten gemerkt dat dit een niet-triviaal onderwerp is. Niet omdat er moeilijk over wordt gedaan, maar omdat niemand echt precies lijkt te weten hoe je dat nou moet doen. Mooie kans om dat in dit traject even goed uit te zoeken. Daarbij hoop ik dat we al te bureaucratische juridische hobbels achterwege kunnen laten. Leverancier heeft alle intentie om Open Source software te schrijven die onder vrije Open Source licentie wordt gepubliceerd door VNG-Realisatie - dat moeten we soepel tot uitvoering zien te brengen.

Voorstel: gespecialiseerd jurist (ICT Recht, Open Source) raadplegen met als doel te komen tot korte handrijking hoe dit voortaan kan worden uitgevoerd.

Vooralsnog staat in de repository dat de inhoud van de repository onder EUPL licentie is gepubliceerd.

**Comment by wishalg** [comment]
@ehotting Vandaag met Marc Maas gesproken, hij gaf aan dat als een devolpers bij VNG Realisatie gecontracteerd volgens de voorwaarden alle (API) codes eigendom van VNG Realisatie. Wat nog onduidelijk is krijgen we ook een kopie van de Haarlemse zaaksysteem ook onder IP of enkel een ZRC?

**Comment by BoerBas** [comment]
En hoe ga je om met alle mensen die dingen aanpassen en/of toevoegen? Je hebt als het goed is straks vele auteurs, niet alleen leveranciers maar ook uit gemeenten.

**Comment by ehotting** [comment]
Inhoud opgesplitst in aantal taken + onderwerpen die daar iig helder moeten worden

**Comment by TCIMEddy** [comment]
Wat mij betreft is dit geen impediment maar een taak (of aantal taken) om dit komende 7 sprints te regelen (non functioneel user story). Indien @wishalg en @ehotting akkoord dan wijzigen van impediment naar non functioneel user story en prioriteren door PO

**Comment by TCIMEddy** [comment]
Ik neem hem a.s. woensdag niet mee als impediment

**Comment by TCIMEddy** [comment]
@wishalg moet hier nog iets mee gebeuren of is dit gereed

**Comment by wishalg** [comment]
Ik zal dit intern nagaan

**Comment by wishalg** [comment]
Alle contracten onder VNGR zijn de AVRODI 2018 voorwaarden van toepassing.
Volgens VNGR control zijn dan ook alle intellectueel eigendommen bezit van VNG Realisatie.

Vraag: waarom zouden willekeurige participanten vrijwillig (o.a. codes) bijdragen?; om auteursrecht aan te vragen?

Overigens wordt er onder EUPL licentie gepubliceerd (het doel is uiteindelijk een vrijesoftwarelicentie).

**Comment by TCIMEddy** [comment]
@wishalg Volgens mij kan deze dan toch op close en naar done??

**Comment by wishalg** [comment]
Wat mij betreft wel.

**Comment by TCIMEddy** [comment]
@ehotting Moet hier nog wat gebeuren en zo ja wanneer (prioriteit)

**Comment by ehotting** [comment]
Even opnieuw de user story lezen.

Het is vrij eenvoudig, maar kan niet worden opgelost door steeds verder van het team met mensen te overleggen. We kunnen de checkboxes in de userstory 1 voor 1 aftikken. Moet resulteren in een documentje van 1 of 2 pagina's waarin al deze aspecten zijn afgedekt en welke kunnen worden gebruikt wanneer nieuwe developers worden betrokken bij VNG-R projecten. Wordt steeds urgenter naarmate we meer maken waarbij Intellectueel Eigendom speelt.

**Comment by TCIMEddy** [comment]
Staat al heel lang open. Als er weer noodzaak is dan nieuwe user story
