### ISSUE TITLE
Op welke wijze gaan we de OAS en schema's maken?

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#125]
# Impediment
Op dit moment zijn er drie mogelijkheden om de OAS file en bericht schema's te maken:
1/ handmatig
2/ genereren uit referentie implementatie 
3/ genereren uit UGM/BSM met behulp van Imvertor

Hoe de bestanden ook gemaakt worden, in ieder geval moeten ze inhoudelijk:
1/ ondersteunen van de user stories
2/ aansluiten op RGBZ 2.0

(technische eisen als voldoen aan OAS 3.0 etc. laat ik even buiten beschouwing)

Een mogelijk nadeel van handmatig kan zijn dat er onregelmatigheden in de bestanden kunnen sluipen, analoog aan de foutjes die nu soms in de StUF koppelvlakken voorkomen.

Genereren uit de referentie implementatie maakt dat de API indirect op het RGBZ aansluit, via de interpretatie die inde referentie implementatie aan het RGBZ is gegeven. Hoeft niet verkeerd te zijn maar maakt het voor informatiemodelleurs lastiger om de API zo snel mogelijk te kunnen beoordelen (aansluiting op RGBZ, voldoen aan GEMMA2?).

Genereren vanuit UGM/BSM staat nog in de kinderschoenen en zoals met alle nieuwe tools zullen daar bevindingen op komen.

Voor dit project denk ik dat we in het begin een combinatie van alle technieken moeten gaan gebruiken. Aan het eind van het traject is het wel zaak om alle berichten en de API definitie vanuit de UGM/BSM modellen te kunnen genereren zodat het koppelvlak ook goed in beheer genomen kan worden.

[assign aan Eddy, voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by TCIMEddy** [comment]
Op 20 juni gaan we hier afspraken over maken (naast sprintplanning en refinement)
