### ISSUE TITLE
Functioneel ontwerp/architectuurschetsje per US opstellen ontbreekt in ons proces

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/gemma-zaken#126]
# Impediment
Over veel user stories ontstaat discussie op Github of Slack over de functionele kant van de US. Hoe past dit in GEMMA, welke component levert welke API etc.

Ook is het obv enerzijds de zeer beknopte beschrijving van de US (3 zinnen) en anderzijds de eerste versies van de API moeilijk om gestructureerd en efficiënt de review op de GEMMA te kunnen doen of beter nog: vooraf richting vanuit de GEMMA te geven (of te ontdekken waar de GEMMA wellicht bijgesteld moet worden).
Daarom voorstel: per user story als eerste een beknopte architectuurschets, zodat iedereen daarover hetzelfde beeld heeft.
Kan als taak, of mogelijk als onderdeel van het ready maken?

**Comment by TCIMEddy** [comment]
Op 20 juni gaan we hier afspraken over maken (naast sprintplanning en refinement)
