### ISSUE TITLE
Backlog refinement verbeteren

### ISSUE THREAD

**Issue by PDG65** [VNG-Realisatie/gemma-zaken#1261]
Afkomstig uit retrospective sprint 15.

- Visie updaten
- DoR updaten
- User Stories meer helder krijgen
- User Stories bundelen op waarde

**Comment by PDG65** [comment]
DoR en DoD langsgelopen a.d.h.v. productvisie. Aantal verbetervoorstellen geformuleerd (zie bijlage[Visie, waarden, DoR en DoD.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/3515867/Visie.waarden.DoR.en.DoD.docx)). Deze bespreken bij start volgende Backlog Refinement sessie.

**Comment by PDG65** [comment]
Product Visie en Definition of Ready [Visie, waarden, DoR en DoD.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/3566016/Visie.waarden.DoR.en.DoD.docx)
[](url) doorgesproken met Hugo. Voorgelegd voor akkoord

**Comment by melsk-r** [comment]
Ik ben zo vrij geweest het document te reviewen en ik heb er enkele opmerkingen in geplaatst [Visie.waarden.DoR.en.DoD Review RM.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/3578136/Visie.waarden.DoR.en.DoD.Review.RM.docx)

**Comment by PDG65** [comment]
Aangepast tijdens planningsessie met team 09-09: 
[Visie.waarden.DoR.en.DoD.Review.RM en PG.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/3616682/Visie.waarden.DoR.en.DoD.Review.RM.en.PG.docx)

@Hugo-ter-Doest graag de aanpassing in de Productvisie doorvoeren en de Business Value nog eens doorlopen en aanscherpen / actualiseren
@melsk-r graag opmerkingen waar nodig in acceptatiecriteria beheer verwerken

**Comment by melsk-r** [comment]
@PDG65, acceptatiecriteria zijn aangescherpt. Ik heb daarin niet verwezen naar standaard.md aangezien een andere standaard een geheel andere documentatie structuur kan hanteren.

**Comment by PDG65** [comment]
User stories worden nu gebundeld op Epic/waarde
