### ISSUE TITLE
Lege max vertrouwelijkheidsaanduiding in AC leidt tot fout in ZRC

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1266]
# Bug

Het ZRC wil de Zaken filteren op de `max_vertrouwelijkheidsaanduiding`. Deze kan echter leeg ("") zijn volgens het AC model.

```python
            choice_item = VertrouwelijkheidsAanduiding.get_choice(
                authorization.max_vertrouwelijkheidaanduiding
            )
```

Als deze lege string terug komt uit het AC, is dit vervolgens geen geldige keus, wat leidt tot een 500-error in het ZRC.

Sentry: https://sentry.maykinmedia.nl/maykin-media/zrc-test/issues/256136/

2 oplossingsrichtingen mogelijk: 1) Omgaan met lege string, of 2) Dit niet toestaan in AC.

**Comment by sergei-maertens** [comment]
Ik neig naar striktere (en makkelijk uitbreidbare) validatie in het AC. Heb al een paar keer te veel mijn vingers hieraan gebrand.
