### ISSUE TITLE
Als developer wil ik op een zo efficiënt mogelijke manier zaken van een betrokkene kunnen opvragen

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/gemma-zaken#1268]
...zodat het aantal API-calls zich tot het minimum beperkt.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by basretera** [comment]
Deze user story is gerelateerd aan #1

**Comment by michielverhoef** [comment]
Zo te zien is dit een concretere user story waar in #413 om gevraagd is.

Om maar eens een knuppel in een hoenderhok te gooien: Is het een optie om hier een bijdrage aan de standaard van een leverancier van te maken? Het patroon staat wel beschreven in de VNG API Community Slack, de onderliggende calls om rollen en van daaruit zaken op te halen zijn er ook. 

Zou dit een process API kunnen worden die op zijn beurt weer de onderliggende System API's op de resources aanroept? In ieder geval voor de referentie-implementatie.

**Comment by joeribekker** [comment]
#957 is ook gerelateerd.

**Comment by michielverhoef** [comment]
Hoewel ik de vraag begrijp en onderschrijf is het wel strijdig met het uitgangspunt wat hier (https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/themas/achtergronddocumentatie/zds-en-zgw-apis.md) vermeld staat (3e item):

_Uitwisselen van informatie op basis van atomische resources, waarbij er gerefereerd wordt naar een resource in een component in plaats van deze te embedden._

**Comment by Hugo-ter-Doest** [comment]
Voorstel voor oplossingsrichting: het toevoegen van query parameters voor roltype en betrokkene (URL of identificerende gegevens van een persoon) aan de zaken API. @basretera is dat een antwoord op jullie behoefte?

**Comment by basretera** [comment]
@Hugo-ter-Doest: ik begrijp je vraag eerlijk gezegd niet. Jouw oplossingsvoorstel is nu toch al gerealiseerd? Dit issue gaat er juist om dat er een efficiëntere manier gevonden moet worden om de zaken op te vragen, bijvoorbeeld door een expand of een proces-api of door een search-api (3 ideeën die reeds geopperd zijn).

**Comment by Hugo-ter-Doest** [comment]
Volgens mij is dit nog niet gerealiseerd. @joeribekker ?

**Comment by MaartenRutten** [comment]
We willen tijdens API lab eind deze maand ons iKCS (Klant Contact Center) koppelen aan de ZRC. De eerste stap is om de zaken van de burger op te vragen. 
We konden deze vraag niet terugvinden in de API-documentatie en uit bovenstaande maak ik op dat dit nog niet ondersteund wordt in de API?

**Comment by Hugo-ter-Doest** [comment]
@MaartenRutten dat kan via rollen.

**Comment by michielverhoef** [comment]
In de VNG API Community is het algoritme als volgt omschreven:
_Gebaseerd op de API documentatie (https://zaken-api.vng.cloud/api/v1/schema)  kun je inderdaad op het endpoint /rollen filteren op BSN, hieruit komt een lijst met rollen, elke rol heeft een enkele betrokken zaak.
Op de zaak zelf is er geen directe koppeling met rollen zichtbaar, dus om betrokkenen bij zaken op te halen, of zaken bij betrokkenen lijkt /rollen het beginpunt.Als je de lijst met rollen krijgt, heb je alleen nog niet de metadata van de zaken om te tonen in een eventuele user-interface, alleen de URLs naar de betreffende zaken. Dat betekent dus dat je voor elke zaak nog apart de metadata moet ophalen voordat je ze bijvoorbeeld in een lijst zou kunnen tonen._

**Comment by sergei-maertens** [comment]
Query parameters werken maar tot op zekere hoogte, omdat persoonsgegevens in een andere API leven. Die grenzen kunnen we niet overstijgen.

Ik denk persoonlijk dat we inderdaad moeten kijken naar een search-api waarin "documenten" geïndexeerd worden (GEEN authoratieve bron voor persoonsgegevens, maar deze kunnen wel gedemoraliseerd mee geïndexeerd worden), of de mogelijkheden van GraphQL onderzoeken om over APIs heen te aggregeren.

Ik wil het hier deze namiddag wel even over hebben met het team wanneer we bij elkaar zijn.

**Comment by basretera** [comment]
@Hugo-ter-Doest Dit issue hebben jullie in oktober vorig jaar de prio H gegeven en volgens mij in een sprint review vermeld dat jullie hiermee nog in 2019 en anders Q1 2020 aan de slag gingen. Hebben jullie deze nog op de radar staan en zo ja, wat zijn de plannen m.b.t. dit issue?

**Comment by joeribekker** [comment]
@basretera Dit is volgens mij al mogelijk maar middels PR #1625 wordt dit verder vereenvoudigd en geoptimaliseerd.

**Comment by HenriKorver** [comment]
Wat mij betreft akkoord. 
@basretera Is hier mij jouw user story beantwoord?

**Comment by basretera** [comment]
Ik vind het lastig inschatten. Wat is er nu concreet veranderd dan? De filter parameters, zoals het inpBsn waren reeds aanwezig op de rol. Dat is m.i. dus niet veranderd. Wat maakt dat via issue #1625  ik nu dus efficiënter de zaken van een natuurlijk persoon kan opvragen?

**Comment by HenriKorver** [comment]
Nu de query parameters ook aanwezig zijn op het zaken-endpoint scheelt het sowieso round-trips. Als je nu (in de oude situatie) alle zaken van een betrokkene wilt opvragen via het rollen-endpoint dan krijg je alleen de url's van de zaken terug. Als je bijvoorbeeld 100 url's terugkrijgt dan moet je 100 extra bevragingen doen om de zaakdetails van die zaken op te halen. 
De grotere voordelen behaal je uit het feit dat je in de nieuwe situatie query-parameters van rollen en zaken kunt combineren. Bijv. haal alle zaken op van betrokkene X met zaaktype Y. In de huidige situatie moet je dan twee aparte lijsten met zaken ophalen:

- Een lijst met alle zaken van betrokkene X via het rollen-endpoint
- Een lijst met alle zaken met zaaktype Y via het zaken-endpoint

Deze twee lijsten moeten dan vervolgens  door de developer van de consumer-applicatie vergeleken worden. Geen ideale situatie, lijkt mij. Deze situatie is met mooi proza beschreven in #1599

**Comment by basretera** [comment]
Dit is duidelijk. Op deze manier lijken we inderdaad efficiënter tot resultaten te komen. Hierbij dan ook akkoord.

**Comment by basretera** [comment]
Oei, ik heropen het issue even. Ik weet namelijk niet of iemand anders vanuit het proces dit netjes procedureel moet doen.

**Comment by michielverhoef** [comment]
Het lijkt er op dat iedereen met de oplossing akkoord gaat dus ik sluit het issue. Is dit onterecht dan wordt het wel weer geopend.

**Comment by michielverhoef** [comment]
Opgenomen in Zaken API 1.5.0
