### ISSUE TITLE
Als gebruiker wil ik eenvoudiger autorisaties kunnen geven op alle zaaktypen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1269]
...zodat ik niet "alle rechten" hoef toe te kennen EN niet 800+ zaaktype permissies hoef uit te delen.

Lege string als zaaktype in AC betekent alle zaaktypen? Pretty please with sugar on top!

---

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by CMasselink** [comment]
Is het vanuit een security perspectief niet handig om "alle rechten" wel expliciet te maken met een bepaalde waarde anders dan een lege string?
Een lege string kan wellicht ook ontstaan omdat men vergeet het in te vullen en dan heb je ineens alle rechten....Desnoods iets van ALL?

**Comment by joeribekker** [comment]
Je hebt wel een punt maar aan de andere kant is dit UI ("ALLE rechten" + popup "Weet u het zeker?") vs API waarde vertaling ("").

**Comment by joeribekker** [comment]
We hebben nu in de Autorisaties API het attribute "heeftAlleAutorisaties" dat in principe dit wel afvangt en beheerlast voor test doeleinden verlaagt.
