### ISSUE TITLE
Een Zaak-Document relatie kan expliciet verwijzen naar een bepaalde document versie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1270]
# Bug

Dit gedrag is impliciet meegenomen in de functionaliteit dat je een URL opslaat als verwijzing naar een Document bij een Zaak. Als de URL een `?versie=3` query parameter bevat, wijs je technisch gezien naar een specifieke versie.

De vraag is echter of dit A) wenselijk functioneel gedrag is, of B) eigenlijk gewoon een bug is en toevallig werkt.

In het geval van A moeten we dit explicieter documenteren (en hoor ik graag de use cases). In het geval van B moet een validator dit afkeuren.

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat het inderdaad een bug is. ZaakDocument relatie zou m.i. standaard de meeste recente versie moeten verwijzen.

**Comment by sergei-maertens** [comment]
> Ik denk dat het inderdaad een bug is. ZaakDocument relatie zou m.i. standaard de meeste recente versie moeten verwijzen.

Hier hadden we vorige week een discussie over in het Utrecht team. Er zijn situaties waar je op het gedrag van "laatste" versie wil steunen, en er zijn situaties (bestuurlijke besluitvorming) waarbij je wel naar een specifieke versie wil verwijzen.

cc/ @MichelleDautzenberg @JurjenBert @FrankHarbers

**Comment by michielverhoef** [comment]
Dit is geen bug maar ontworpen en gewenst gedrag. Onder andere om deze user story op te lossen:

https://github.com/VNG-Realisatie/gemma-zaken/issues/459 

Dus het is A, ontworpen en wenslijk gedrag. Misschien moet de documentatie nog verbeterd worden maar dit mag zeker niet aangepast worden. 

Wat mij betreft sluiten we dit issue @Hugo-ter-Doest

**Comment by joeribekker** [comment]
Ongedaan gemaakt in https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/168 (dit is overigens nooit in een versie release gekomen).
