### ISSUE TITLE
De installatie instructie (../deploy-bot/INSTALL.rst) klopt niet

### ISSUE THREAD

**Issue by niekbruins** [VNG-Realisatie/gemma-zaken#1271]
# Bug

De instructie voor Docker klopt niet.

In de instructie staat overal deploy_bot_... Dit moet zijn deploy-bot_...
Om docker te kunnen starten moest ik ook de docker-compose.yml file aanpassen.
regel 11 aangepast in: image: vngr/deploy-bot
regel 14 heb ik een willekeurige string als Secret opgegeven.

Daarna kon ik de docker container starten.
Echter de laatste instructie in de beschrijving kon ik niet uitvoeren.

docker exec -it deploy-bot_web_1 /app/src/manage.py loaddata admin_index groups
Deze geeft de foutmelding:
CommandError: No fixture named 'admin_index' found.

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie) => lokaal op mij pc

Welke claims/payload bevat je JWT? => n.v.t.

**Comment by Hugo-ter-Doest** [comment]
Ik vermoed niet meer actueel. Graag heropenen als dit nog speelt.
