### ISSUE TITLE
drc nginx container start niet op onder windows

### ISSUE THREAD

**Issue by mkruitz** [VNG-Realisatie/gemma-zaken#1277]
# Bug

Bij het starten van de referentie implementatie (lokaal) krijg ik de volgende foutmelding.

```
PS D:\Docker\CG-ZGW\gemma-zaken\infra> docker-compose up drc_nginx
infra_drc_db_1 is up-to-date
Starting infra_drc_web_1 ... done
Starting infra_drc_nginx_1 ... done
Attaching to infra_drc_nginx_1
drc_nginx_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
infra_drc_nginx_1 exited with code 1
```

Op verzoek aangemaakt, @sergei-maertens @joeribekker

**Comment by joeribekker** [comment]
Ik kan dit helaas niet reproduceren.

```
$ docker-compose up drc_nginx
Starting infra_drc_db_1 ... done
Starting infra_drc_web_1 ... done
Recreating infra_drc_nginx_1 ... done
Attaching to infra_drc_nginx_1
drc_nginx_1     | + envsubst '$$DRC_HOST,$$DRC_UWSGI_PORT'
drc_nginx_1     | + envsubst '$$DRC_NGINX_PORT,$$MIN_UPLOAD_SIZE'
drc_nginx_1     | + exec nginx -g 'daemon off;'
drc_nginx_1     | 192.168.99.1 - - [05/Sep/2019:08:37:01 +0000] "GET /api/v1/ HTTP/1.1" 200 242 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
Gracefully stopping... (press Ctrl+C again to force)
Stopping infra_drc_nginx_1 ... done
```

Ik gebruik zelf Docker Toolbox (en niet Docker for Windows) wat wel iets van elkaar verschilt.

Wat je kan proberen is het volgende:

```
git pull  # Update configuratie
docker-compose down  # Stop eventuele draaiende containers
docker-compose down  # Nog een keer, voor als er iets niet lekker ging
docker-compose pull  # Update docker images
docker image prune  # Verwijder obsolete image om ruimte vrij te maken

docker-compose up drc_nginx  # En nogmaals proberen te starten
```

**Comment by sergei-maertens** [comment]
@mkruitz ben je volgende week op de hackaton? indien je daar aanwezig bent, is het misschien handig om even naast elkaar te zitten om te kijken wat er precies aan de hand is en het probleem op te lossen.

Vervolgvraag nog: gebruik je Docker for Windows, of Docker Toolbox? Op welke Windows versie?

**Comment by mkruitz** [comment]
Helaas ben ik niet bij de hackaton. Als je wilt kunnen we wel een teamviewer sessie opzetten.

Versies:
```
docker desktop community: Version 2.1.0.3 (38240), Channel stable
Windows 10 Pro x64
```

**Comment by michielverhoef** [comment]
Kan dit probleem hetzelfde zijn als wat hier gemeld is?
https://gitlab.com/commonground/haven/issues/71

**Comment by mkruitz** [comment]
@michielverhoef , ik verwacht van wel. Het ziet er in ieder geval hetzelfde uit als het issue dat ik heb.

**Comment by Hugo-ter-Doest** [comment]
Ik denk niet meer actueel, anders heropen hem maar.
