### ISSUE TITLE
De documenten-api standaard (1.0.0-RC) vereist onterecht notificaties en audittrail op ObjectInformatieObject

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1283]
Tijdens het implementeren van de release candidate in https://github.com/open-zaak/open-zaak kwamen we tot de vaststelling dat het versturen van notificaties en bijhouden van audittrail op `ObjectInformatieObject` vervelend is en geen toegevoegde waarde biedt.

Er is gesettled op het vastleggen van relaties tussen zaken en documenten in `ZaakInformatieObject`, en parallel tussen besluiten en documenten in `BesluitInformatieObject`. Deze worden door consumers respectievelijk in de zaken API en besluiten API aangemaakt.

Deze APIs zijn er vervolgens voor verantwoorlijk om de relatie-informatie ook in de relevante documenten API vast te leggen.

In de huidige vorm zorg dat dus voor dubbele notificaties:

* notificatie dat er een `(Zaak|Besluit)InformatieObject` is aangemaakt (= echt inhoudelijk relevant)
* notificatie dat er een `ObjectInformatieObject` is aangemaakt (verplicht door de standaard, inhoudelijk niet interessant).

Hetzelfde gaat op voor de audittrail, met als verschil dat de audittrail entries van OIO _altijd_ een andere API zullen zijn (en geen taak-applicatie consumer). De meerwaarde van audittrail hierop bijhouden vervalt dus helemaal.

Mijn voorstel is dan ook om in de release candidate voor `ObjectInformatieObject` geen notificaties te sturen, en geen auddittrail bij te houden. Deze zijn _altijd_ te herleiden tot het bijhorende `ZaakInformatieObject` en `BesluitInformatieObject`.

**Comment by michielverhoef** [comment]
Op zich klinkt het aannemelijk maar wat gebeurt er wanneer een ObjectInformatieObject aangepast wordt? Is er een situatie te bedenken waarin een ObjectInformatieObject aangepast wordt en deze wijziging van belang is , bv omdat het bijbehorende ZaakInformatieObject niet bijgewerkt is?

Gevoelsmatig is een ZaakInformatieObject  leidend en is een ObjectInformatieObject  slechts een afgeleid gegeven. Maar het is technisch altijd mogelijk (?) om een ObjectInformatieObject  aan te passen zonder het ZaakInformatieObject  aan te passen. Is het dan niet van belang dat die wijzigingen in ieder geval bijgehouden worden in een audittrail?

**Comment by sergei-maertens** [comment]
`ObjectInformatieObject` mag niet aangepast worden inderdaad, daar zijn (partial) update niet op toegestaan. Enkel create en delete, en die worden gecöordineerd door ZIO/BIO.

> Gevoelsmatig is een ZaakInformatieObject leidend en is een ObjectInformatieObject slechts een afgeleid gegeven.

100% correct

> Maar het is technisch altijd mogelijk (?) om een ObjectInformatieObject aan te passen zonder het ZaakInformatieObject aan te passen.

Wordt door de API businesslogica geblokkeerd, dit zou namelijk tot inconsistente situaties leiden.

**Comment by michielverhoef** [comment]
Ah, dus wanneer je wel een OIO aanpast doe je dingen die niet volgens de standaard zijn. Simpel zat dus, dan ben ik het eens met het voorstel van Sergei om voor ObjectInformatieObject geen notificaties te sturen, en geen auddittrail bij te houden.

**Comment by sergei-maertens** [comment]
Patch doorgevoerd in DRC: https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/commit/82f6b092c77a40d438eadd619ab94538c55f7bc3
