### ISSUE TITLE
Dode links naar architecuur pagina's

### ISSUE THREAD

**Issue by mkruitz** [VNG-Realisatie/gemma-zaken#1284]
# Bug

Op de volgende plekken staan dode links:
- link "Ontwerpkeuzes"
  - pagina: https://zaakgerichtwerken.vng.cloud/architectuur/ontwerpkeuzes
- link "Ontwikkelstraat"
  - pagina: https://zaakgerichtwerken.vng.cloud/architectuur/ontwikkelstraat
- link "ZDS versus ZGW"
  - pagina: https://zaakgerichtwerken.vng.cloud/architectuur/zds_zgw

- link "gedocumenteerd"
  - pagina: https://zaken-auth.vng.cloud/set-auth/

**Comment by Hugo-ter-Doest** [comment]
Documentatie is opnieuw opgezet op Github pages.
