### ISSUE TITLE
Dode links in API spec overzicht

### ISSUE THREAD

**Issue by lexuijthof** [VNG-Realisatie/gemma-zaken#1295]
# Bug

In https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/index.md staan links naar de verschillende API specificaties (en documentatie)
Deze links missen allemaal de .md extensie waardoor je een keurige 404 krijgt, zodra je er op klikt.

**Comment by MaartenRutten** [comment]
En vandaag nog steeds:
Voorbeelden van een dode link:

https://github.com/VNG-Realisatie/gemma-zaken/blob/master/ontwikkelaars/handleidingen-en-tutorials/installatie-en-configuratie

https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/ontwikkelaars/handleidingen-en-tutorials/api-guides

https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/ontwikkelaars/handleidingen-en-tutorials/installatie-en-configuratie

**Comment by CMasselink** [comment]
@lexuijthof @MaartenRutten als je de documentatie bekijkt via: https://zaakgerichtwerken.vng.cloud/ werken de genoemde URL's wel.
We werken met een geautomatiseerd documentatie systeem (Jekyll voor de geïnteresseerden) waarbij het in github noodzakelijk is de .md extentie weg te laten (anders heb je exact hetzelfde probleem maar dan op de documentatie pagina). Het gevolg hiervan is dat op dit moment de URL's en pagina's wel werken als je ze  via de zaakgericht werken documentatie website bezoekt maar helaas niet als je via github op de links klikt.  

Mocht je via https://zaakgerichtwerken.vng.cloud/ nog steeds dode links tegen komen, dan horen we dat uiteraard nog steeds graag.

/cc @michielverhoef
