### ISSUE TITLE
Is er een alternatie voor het aanmaken van een superuser in docker swarm?

### ISSUE THREAD

**Issue by itdinges** [VNG-Realisatie/gemma-zaken#1296]
# Impediment
Console interactie met een docker swarm is niet gewenst (en ook niet echt haalbaar zonder hacks) omdat het van te voren niet duidelijke is op welke machines binnen de swarm de container gaat draaien (ivm scaling)

echter het commando:
docker exec -it infra_ztc_web_1 /app/src/manage.py createsuperuser
gaat er vanuit dat je wel toegang het en weet op welke docker machine de container draait.

Is er een alternative manier om een initiële superuser aan te maken?

[assign aan Eddy, voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by michielverhoef** [comment]
Ik weet niet precies waar dit over gaat maar het komt mij over als systeem beheer van een Docker omgeving. 

Dit heeft niets te maken met de ZGW API's als standaard en is ook niet in de standaard op te lossen. De standaard gaat over processen en gegevensuitwisseling via API's. Systeem beheer valt daar buiten.

NB. Het is ook niet verplicht om een implementatie van een API in een docker container te realiseren. Docker is voor ons een relatief makkelijke manier om een referentieimplementatie te draaien maar het gebruik van docker is niet verplicht.

Ik sluit dit issue omdat het buiten scope van de ZGW API standaard valt.

**Comment by itdinges** [comment]
Hoi @michielverhoef .

Ik ben het niet helemaal eens dat het enkel een "beheer" dingetje is.

Ik doel op stuk dat staat in de documentatie die wordt meegeleverd :
https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/ontwikkelaars/handleidingen-en-tutorials/eenmalige-setup.md#aanmaken-supergebruikers

> 
> docker-compose exec drc_web src/manage.py createsuperuser
> docker-compose exec ztc_web src/manage.py createsuperuser
> docker-compose exec brc_web src/manage.py createsuperuser
> docker-compose exec nrc_web src/manage.py createsuperuser
> docker-compose exec ac_web src/manage.py createsuperuser

Deze commando's werken dus niet in een Docker Swarm, omdat er dan geen user interactie mogelijk is. Daarnaast werken de gemaakte client ID's niet meer goed bij het opschalen van containers.

**Comment by michielverhoef** [comment]
De referentieimplementaties zijn bedoeld om aan te tonen dat het mogelijk is om de standaard te implementeren. De bijgeleverde docker containers en de documentatie zijn niet bedoeld om in een productieomgeving te gebruiken, zie ook de gebruiksvoorwaarden (https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/beheer/gebruiksvoorwaarden.md) . Het kunnen opschalen van de containers met referentieimplementatie is dan ook buiten scope van de standaard.

De geleverde informatie is bedoeld voor het draaien van de docker containers op manier zoals beschreven. Maak je gebruik van een andere soort omgeving of draaien de referentie implementaties op andere poorten dan dien je zelf over de nodige kennis te beschikken om de commando's en voorbeelden uit de documentatie aan te passen.
