### ISSUE TITLE
As a developer I want all ZRC resources to be paginated

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#1297]
so that `list` requests won't crush API in case there are a lot of data in DB.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by sergei-maertens** [comment]
@Hugo-ter-Doest deze is wel een release blocker m.i.

**Comment by sergei-maertens** [comment]
Fix in ZRC: VNG-Realisatie/gemma-zaakregistratiecomponent@414dcc90a9508ef81dfb3eef03e7488e9282eee4 & VNG-Realisatie/gemma-zaakregistratiecomponent@60c27698236a41e4b767d5b433f44e5c7490cb1b

Spec update in gemma-zaken: 400afac8640cd8a4202f59efb7b2243f9dec3a99

@stevenbal de Postman tests moeten hier nog op bijgewerkt worden

**Comment by sergei-maertens** [comment]
Fix in ZRC: VNG-Realisatie/gemma-zaakregistratiecomponent@414dcc90a9508ef81dfb3eef03e7488e9282eee4 & VNG-Realisatie/gemma-zaakregistratiecomponent@60c27698236a41e4b767d5b433f44e5c7490cb1b

Spec update in gemma-zaken: 400afac8640cd8a4202f59efb7b2243f9dec3a99

@stevenbal de Postman tests moeten hier nog op bijgewerkt worden

**Comment by stevenbal** [comment]
@sergei-maertens de tests doen het nog als verwacht, geen aanpassingen nodig voor nu :)

**Comment by sergei-maertens** [comment]
Super, dankje voor de check!

Voorgestelde spec update zit in #1235, vanmiddag als team waren we het eens over deze wijzigingen, kan dus afgesloten worden.
