### ISSUE TITLE
Als persoon of vertegenwoordiger van een persoon met een zaak bij de/ een overheid wil ik een reactie kunnen plaatsen op een zaak

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#13]
Zodat ik kan reageren op een vraag, verzoek of opmerking van een behandelaar

**Comment by michielverhoef** [comment]
Reageren kan zijn:
* een antwoord geven op een vraag of opmerking
* een document toevoegen
* ?

**Comment by jgortmaker1** [comment]
Dit is ene dilemma. dit moet je vanuit dienstverleningsperspectief misschien wel willen. 
Maar vanuit rechtmatigheids- en doelmatigheidsperspectief weer niet. Een ambtenaar moet eens hij alle stukken heeft, ongestoord kunnen behandelen. Als de klant allerlei aanvullende berichtjes kan sturen, moet hij hier weer rekening mee houden werk overnieuw doen, etc.
negeert hij berichtjes, dan levert dat achteraf mogelijkerwijs juridische problemen op.

Ik zou het initiatief voor het aanleveren van aanvullende info bij de ambtenaar legen.
Maar wellicht is een grondiger onderzoekje nodig

**Comment by Hugo-ter-Doest** [comment]
Kan dicht omdat je al klantcontacten kun registreren.
