### ISSUE TITLE
Als vakapplicatieontwikkelaar wil ik weten hoe error-responses eruit zien...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#130]
...zodat ik deze consistent in mijn applicatie kan verwerken.

PR: #360 

**Definition of done**

- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] er is functionele documentatie conform het DSO-patroon
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [x] ~~Voldoet aan RGBZ 2.0~~ n.v.t.
- [x] ~~Voldoet aan GEMMA 2.0~~ n.v.t.
- [x] De foutmeldingen hebben een uniforme structuur
- [x] De foutmeldingen zijn gedocumenteerd:
  - [x] HTTP 400 validatiefouten
  - [x] HTTP 401
  - [x] HTTP 403
  - [x] HTTP 404
  - [x] HTTP 405
  - [x] HTTP 422

**Taken**
- [x] Foutcodes in referentie-implementatie implementeren [@sergei-maertens]
- [x] Foutschema's opnemen in OAS 3.0 spec [@sergei-maertens]
- [x] Zorgen dat foutschema's consistent zijn tussen componenten (ZRC, ZTC, DRC) [@sergei-maertens]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [@sergei-maertens]

**Comment by sergei-maertens** [comment]
@TCIMEddy yep, het puntje 'architectuur schetsje' is hier niet van toepassing.

**Comment by sergei-maertens** [comment]
Vraag uitgezet n.a.v. DSO API-strategie error-formaat: https://forum.pdok.nl/t/formaat-foutafhandeling-input-validatie-api-50/1848

**Comment by sergei-maertens** [comment]
Antwoorden zijn duidelijk (en worden deels in design-keuzes opgenomen)

1. Meerdere fouten op zelfde veld bij inputvalidatie: komen allemaal als aparte fout instance terug, in plaats van ze samen te voegen in 1 fout
2. Er worden basic HTML pagina's gebouwd die informatie over de fouten bevatten. Doelpubliek hiervoor is per de RFC developers, en dient NIET om automatische systeemafhandeling mee te doen.

**Comment by jgortmaker1** [comment]
iets voor @zomwoof denk ik

**Comment by zomwoof** [comment]
Volgens de DSO en de [RFC7807: Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807) dient het media type bij error-responses  `application/problem+json` te zijn in plaats van `application/json`.
