### ISSUE TITLE
Faciliteiten Scrumteam verbeteren

### ISSUE THREAD

**Issue by PDG65** [VNG-Realisatie/gemma-zaken#1301]
Uit retro sprint 15: 

1. conferencing audio puck zodat bij standup iedereen goed verstaanbaar is

2. beschikbaarheid ruimte Trindenborgh staat onder druk. Iets structureel regelen binnen Trindenborgh of Tribes.

**Comment by PDG65** [comment]
1. verzoek ruimte is door Ivo uitgezet bij Kenan

2. Wishal gaat na of conferencing puck beschikbaar is

**Comment by PDG65** [comment]
Puck is door mij geregeld

**Comment by PDG65** [comment]
@hdksi heb jij nog iets gehoord van Kenan over een andere werkruimte die we structureel kunnen gebruiken?

**Comment by hdksi** [comment]
Nee, hij hier ook niet vandaag, maar voor zover ik weet is er geen structurele oplossing.

Volgens mij moeten we eerst zeker weten of we na deze week wel of niet in Trindeborch terecht kunnen. Of is dat al duidelijk? Tribes is vanwege reserveringen ieder geval _geen_ optie.

Als het antwoord op de eerste vraag 'nee' is, dan moeten we in overleg met @wishalg of @jeffreygortmaker1 inderdaad op zoek naar een alternatief...

**Comment by PDG65** [comment]
@wishalg kun jij uitsluitsel geven over de beschikbaarheid van een vaste ruimte op maandag voor het ZWG API's team?

**Comment by PDG65** [comment]
Ruimte lijkt te zijn geregeld op devloer
