### ISSUE TITLE
Als medewerker van het klantcontactcentrum wil ik kunnen vastleggen in welke taal een vraag beantwoord is of moet worden

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1315]
zodat we kunnen beoordelen of we beschikken over de juiste/gevraagde taalvaardigheden en de vraag door een medewerker met de juiste taalvaardigheden kan worden beantwoord.

User story op basis van gesprek met gebruikers bij gemeente Utrecht.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by HenriKorver** [comment]
De gewenste taal kan op verschillende niveaus of zelfs op meerdere niveaus te gelijk worden vastgelegd:

- KLANT
- VERZOEK en CONTACTMOMENT
- ZAAK
- Etc.

Om de goede keuze te maken zal deze US verder moeten worden uitgewerkt.

**Comment by Hugo-ter-Doest** [comment]
Moet nog worden besproken op informatiemodel-niveau

**Comment by hdksi** [comment]
Informatiemodel wordt aangepast zodat (voorkeurs)taal wordt gestructureerd (taalcode) bij contactmoment kan worden vastgelegd

**Comment by HenriKorver** [comment]
Attribuut `voorkeurstaal` toegevoegd aan resource `contactmomenten`. Zie [OAS-specificatie Contactmomenten API in Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/gemma-zaken/master/api-specificatie/DESIGN/kic/contactmomenten/openapi.yaml#operation/contactmoment_create).

**Comment by stevenbal** [comment]
@joeribekker PR in contactmomenten API: https://github.com/VNG-Realisatie/contactmomenten-api/pull/3
