### ISSUE TITLE
Als medewerker van het klantcontactcentrum wil ik contactgegevens (voornaam, achternaam, adres, telefoon, e-mailadres) van de klant handmatig kunnen invoeren

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1321]
zodat ik de minimaal benodigde gegevens kan vastleggen en aan privacywetgeving en dienstverlening kan voldoen.

User story op basis van gesprek met gebruikers bij gemeente Utrecht

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by annashamray** [comment]
According to the schema https://github.com/VNG-Realisatie/gemma-zaken/issues/1323#issuecomment-540012153 the `Klant` object would be either `Vestiging` or `Naturlijk Persoon`

* In both cases `adres` attribute will duplicate `verblijfsadres` attribute in `Vestiging`  or `Naturlijk Persoon`
* `voornaam`, `achternaam` attributes will duplicate `voornamen` and `geslachtsnaam` attributes of `Naturlijk Persoon` and are not applicable to the `Vestiging`

Should these fields be added to `Klant` object?

**Comment by joeribekker** [comment]
@annashamray Discussed this with @hdksi which clarified it for me.

Focusing on `voornaam` as an example for the duplicate attributes, but goes for all of them.
There are (at max) 3 locations where this attribute can be found:

1. Klant.voornaam
2. Klant->(BRP)NatuurlijkPersoon.voornaam
3. Klant.KlantIdentificatie.NatuurlijkPersoon.voornaam

@1 is the adhoc `voornaam` that should always be registered (except when anonymous) and is not authentic or kept up to date.
@2 is recorded when the Klant has identified himself/herself and we can make the relation to a BRP
@3 same as 2, but only when there is no BRP available

so, 3 is alternative to 2, and not to 1.

Conclusion: All fields will be in :)

**Comment by joeribekker** [comment]
Using "subject" as attribuut (base) name (like `betrokkene`) to refer to an external authentic source, so:

* `subject`: URL to the authenticated natuurlijk persoon or vestiging in external API 
* `subjectIdentificatie`: Alternative to `subject` if no such URL is available. Contains an object of relevant information such as with Zaken API: `Rol.betrokkeneIdentificatie`.
* `subjectType`: Enum to indicate which object is behind the URL or which identification information should be provided

**Comment by annashamray** [comment]
@joeribekker Thanks for clearing out
the PR for this - https://github.com/VNG-Realisatie/gemma-klantcontactcomponent/pull/2
