### ISSUE TITLE
Als medewerker van het klantcontactcentrum wil ik een zaak kunnen koppelen aan een klantcontactmoment

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1323]
zodat collega’s op de hoogte zijn van contact over de betreffende zaak.

User story op basis van gesprek met gebruikers bij gemeente Utrecht.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Dubbel met #1324

**Comment by joeribekker** [comment]
Is denk ik autorisatie versmalling van #1324?

**Comment by hdksi** [comment]
Geen versmalling maar twee groepen gebruikers:

1. KCC-medewerkers slaan inkomende contactmomenten op, bijvoorbeeld een telefoontje van klant die vraagt om een statusupdate bij een lopende zaak (#1323)
2. medewerkers van de zaakbehandelende afdeling slaan (stel ik me voor) uitgaande contactmomenten op bij de zaak - bijvoorbeeld een ingesproken voicemail met verzoek om meer informatie of een e-mail waarin het resultaat van zaak wordt samengevat (#1324)

**Comment by Hugo-ter-Doest** [comment]
Voor de API wsch. dubbel met #1324

**Comment by PDG65** [comment]
Todo:
- bestaande zaak-api aanpassen (zaak kunnen koppelen aan 0 of meerdere contactmomenten)
- toevoegen mogelijkheid opvragen (read/list)
- testscripts

**Comment by EdwinCoster** [comment]
Deze user story leidt tot een wijziging van het gegevensmodel.

**Comment by hdksi** [comment]
<img width="847" alt="Modelletje_klantcontacten" src="https://user-images.githubusercontent.com/37660390/66487800-391db200-eaad-11e9-8239-6dc3e83471e2.png">

**Comment by hdksi** [comment]
Excuses voor het niet volgen van enige ZGW-modelleerconventie...

**Comment by joeribekker** [comment]
De contactmoment-zaak relatie is gedaan.

Zoals besproken komt er dus ook een relatie kant bij ZRC. Die moet nog.

**Comment by sergei-maertens** [comment]
@annashamray - I've dragged this one back in TODO:

> I just had a discussion with @joeribekker - we realized something went wrong in the communication.
> 
> We don't want to keep `zaak` information on the `ContactMoment` resource. The resources in this API are _very_ decoupled/standalone.
> 
> However, it should be possible from the Zaken API to attach zero or multiple `ContactMoment`en to a Zaak, and this relation information should be synchronised. This also means that a `ContactMoment` can be connected to multiple, different `Zaken`.

So, please:

1. Remove the `zaak` field
2. Modify the Zaken API: add a `ZaakContactMoment` resource, with create/delete support (no patch/put). It holds the URL to itself, the `zaak` and the `contactmoment`.
3. `ZaakContactMoment` needs the sync-logic in Contactmomenten API: `ObjectContactMoment` (like in DRC), where you can filter on `object` and `contactmoment`

**Comment by sergei-maertens** [comment]
https://zaken-api.test.vng.cloud/api/v1/schema/#tag/zaakcontactmomenten is available, closing
