### ISSUE TITLE
Als medewerker van het klantcontactcentrum of medewerker (die een verzoek tot terugbellen heeft ontvangen) wil ik kunnen aangeven dat een vraag is beantwoord

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1327]
zodat collega’s weten dat deze vraag geen verdere aandacht behoeft.

User story op basis van gesprek met gebruikers bij gemeente Utrecht.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

Verzoek?

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by joeribekker** [comment]
#1327, #1325, #1314, #1313, #1312, #1309, #1306 Klinken allemaal min of meer als een forum-thread (waar meerdere mensen reacties op elkaar geven), totdat de vraag is beantwoord.

Dit komt niet direct naar voren in losse User Stories.

**Comment by Hugo-ter-Doest** [comment]
Contacten hebben een aantal mogelijke statussen. Iets is als "in behandeling" en "afgehandeld".

**Comment by Hugo-ter-Doest** [comment]
Contacten API is alleen voor de registratie van contactmomenten. Deze hebben geen status.
