### ISSUE TITLE
Als leidingggevende van het KCC wil ik dat een klantcontactmoment gekoppeld kan worden aan een afdeling

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1329]
zodat we inzicht krijgen in de bereikbaarheid van afdelingen, en eventueel doorbelasting kunnen organiseren.

User story op basis van gesprek met gebruikers bij gemeente Utrecht.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Wat zijn onderwerpen. Is er een vaste lijst onderwerpen.

**Comment by hdksi** [comment]
Weet even niet meer of het hier ging om kennisbankonderdelen of direct op afdeling.

**Comment by joeribekker** [comment]
❓ Gaat dit om een link naar een api met onderwerpen (link) of gewoon een onderwerp veld (tekst)? Ik neig naar het laatste, tevens geen enum (enum is een limiet die opgelegd kan worden door applicaties in bovenste laag).

**Comment by hdksi** [comment]
@joeribekker en @Hugo-ter-Doest deze story lijkt inderdaad op #1311, terwijl ook #1316 enigszins verwant is. Wellicht zijn de stories niet helemaal helder opgeschreven. Vanuit businessperspecief is dit volgens mij het onderscheid:

- #1316: vastleggen van onderwerp uit de kennisbank bij een  klantcontactmoment, voor inzicht in veelgestelde vragen. Is dus management/productverbeteringsinformatie.
- #1311: vastleggen van onderwerp bij klantcontactmoment voor inzicht in veelgestelde vragen.  Doel voor zover ik gelijk aan #1316. Er staat ook iets over doorbelasten, maar het lijkt me dat je dat op afdeling doet, niet op onderwerp (hoewel je een onderwerp kan koppelen aan afdeling natuurlijk). Evengoed hoort het laatste deel van de 'zodat' eigenlijk meer bij #1329. Heb dit aangepast.
- #1329: vastleggen van een afdeling bij een klantcontactmoment, om zo inzicht te krijgen in bereikbaarheid, en doorbelasting te kunnen organiseren. Bereikbaarheid kan alleen gemeten worden i.c.m. #1312 en #1314.

Volgens mij verandert dit niets in prioritering.

**Comment by Hugo-ter-Doest** [comment]
Deze user story opgevat als koppelen/toewijzen aan een afdeling vanwege de tekst in het "zodat" gedeelte. Daarmee buiten scope.
