### ISSUE TITLE
Tooling op orde

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#133]

**Comment by TCIMEddy** [comment]
Is de tooling op orde? weet niet precies wat het allemaal inhoudt

**Comment by ehotting** [comment]
We werken nu in Slack en GitHub. Vooral GitHub laat te wensen over, maar vooralsnog doen we het er mee. Het scrum board is niet zozeer het struikelblok alswel de vindbaarheid en volgbaarheid van wijzigingen voor de niet-techneuten, maar dat wordt niet beter door een tool als Jira in te zetten. De tooling is op zich compleet, werkafspraken / communicatie scherpen we nog aan adhv retrospectives.
