### ISSUE TITLE
In het ZTC is het niet mogelijk om via de API deelzaaktypes aan te maken

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#1333]
# Bug

Momenteel is de relatie voor deelzaaktypes wel gedefinieerd op het ZaakType model, maar via de API is het niet mogelijk om een `ZaakType` een deelzaaktype van een ander `ZaakType` te maken, of om deze relaties te bekijken

Ook de beperkingen op operaties m.b.t. concepten zijn hierop van toepassing

**Comment by michielverhoef** [comment]
@Hugo-ter-Doest  dit moet geprioriteerd worden. Is dnek ik wel belangrijk.

Het gaat om deze relatie:
https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/gegevensgroeptype/zaaktype.deelzaaktypenrelatie_zaaktype

**Comment by joeribekker** [comment]
Fixed in #1438
