### ISSUE TITLE
webhook.site kan niet gebruikt worden als NRC callback bij het afsluiten van een abo

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1334]
# Bug

De documentatie beschrijft dat je webhook.site kan gebruiken als callback URL bij het afnemen van een abonnement bij het NRC. Echter, het NRC verplicht tegenwoordig autorisatie en dat biedt de gratis versie van webhook.site niet.

Idee: Even een dummy URL ontsluiten op `https://notificaties-api.vng.cloud/dummy-callback` met een standaard auth?

**Comment by annashamray** [comment]
Sorry I don't understand the issue. In the documentation (https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/ontwikkelaars/handleidingen-en-tutorials/notificeren.md) it's described that `dummy` can be used as an Authorization. 
I followed this example and didn't face problems in creating `abonnement`

**Comment by michielverhoef** [comment]
Is de simpelste oplossing niet gewoon de beschrijving van het gebruik van webhook.site uit de documentatie te verwijderen? Dat is implementatie, geen onderdeel van de API standaard.

**Comment by sergei-maertens** [comment]
Reference setting: https://github.com/VNG-Realisatie/gemma-notificatiecomponent/blob/develop/src/nrc/conf/api.py#L35

**Comment by sergei-maertens** [comment]
@annashamray there is a validation check in NRC that tries the url without auth. If the callback responds with a 201 without auth, validation fails, because auth is required. The setting above is an escape hatch to disable that validation.

The setting above should probably be a config option in the admin instead (via django-solo somewhere)

**Comment by annashamray** [comment]
@sergei-maertens yeah, I couldn't reproduce the error because I ran NRC locally, where this check is turned off. 

@joeribekker Is this check really needed? I think checking subscriber authentication is out of scope of NRC.

**Comment by joeribekker** [comment]
I agree, let's remove it and double check if its not mentioned in the standard documentation.
