### ISSUE TITLE
In de API spec staat dat we OIO's meeverwijderen bij het verwijderen van een IO

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1336]
# Bug

...maar dat is toch (hopelijk) niet zo? Je mag een IO alleen verwijderen als er geen OIO's meer zijn of superkrachten hebt (=een speciale permissie).

Zie: https://documenten-api.vng.cloud/api/v1/schema/#operation/enkelvoudiginformatieobject_delete

**Comment by sergei-maertens** [comment]
Fixed in https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/commit/450b743fd970440e302e330f5dbee079e2858f15
