### ISSUE TITLE
Als gemeente wil ik dat een besluit een status heeft zodat

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1339]
zodat 
- er geen beschikkingsdocumenten worden gemaakt op basis van een concept besluit
- het besluit nog niet gepubliceerd wordt
- zodat je wijzigingen kunt aanbrengen voordat een besluit definitief wordt. 
- zodat je voorkomt dat er nog wijzigingen kunnen worden aangebracht aan een definitief besluit

Statuswijzigingen moeten ook in de audit trail terechtkomen.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by AHNRoxit** [comment]
Nog een nuance. Nadat het besluit definitief is kan het worden gebruikt in een (definitief) beschikkingsdocument, verzonden naar de aanvrager en gepubliceerd op officiëlebekendmakingen. Maar een besluit heeft in het huidige model van de BRC een verzenddatum en een publicatiedatum. Dus ofwel deze gegevens moeten worden verwijderd uit het model, ofwel een besluit is voor wat betreft deze gegevens nog wel wijzigbaar nadat het besluit definitief is geworden.

**Comment by joeribekker** [comment]
@AHNRoxit Zijn jullie geholpen met een boolean veld `concept true/false`?

Even overleg gehad over het gedrag (Zoals: mag je een zaak afsluiten op API niveau als er een concept besluit aan hangt, of mag dat alleen met een bepaald resultaattype, etc.). Idee is nu dat we dit niet begrenzen op API niveau. Dat wil zeggen: De API maakt geen onderscheid in gedrag tussen concept/definitief besluit.

**Comment by AHNRoxit** [comment]
Over _Zijn jullie geholpen met een boolean veld concept true/false?_
Dat is misschien te kort door de bocht. Misschien moeten we meer denken in termen van de fasen van de besluitvorming. Zoals een fase ‘concept’, een fase ‘definitief’ en een fase ‘onherroepelijk’

**Comment by AHNRoxit** [comment]
Over _De API maakt geen onderscheid in gedrag tussen concept/definitief besluit._
Dat lijkt me juist. Niet de taak van de registratiecomponent maar van de afhandelingcomponent

**Comment by hdksi** [comment]
@AHNRoxit: uit de oude doos; wat is het verschil tussen een definitief en een onherroepelijk besluit? Kan je dat toelichten aan de hand van een voorbeeld?

**Comment by AHNRoxit** [comment]
We gebruiken zelf inmiddels de term 'vastgesteld' voor wat we eerder 'definitief' noemde omdat dat tot verwarring leidde. In die termen:
Een besluit is 'vastgesteld' wanneer het klaar is om te worden verstuurd naar de aanvrager en te worden gepubliceerd. Daarna (en daarmee) start de bezwaar/beroep/inzagetermijn voor het besluit. Pas nadat deze verstreken is wordt het besluit 'onherroepelijk'

**Comment by hdksi** [comment]
Dank @AHNRoxit, met deze terminologie is het onderscheid inderdaad duidelijker. @Hugo-ter-Doest volgens mij is deze met de toelichting van Arnold ready.

**Comment by michielverhoef** [comment]
concept is inmiddels toegevoeg aan Besluittype, Zaaktype en Informatieobjecttype. De werking hiervan staat beschreven in de documentatie:  https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/
