### ISSUE TITLE
Resultaattype verschijnt niet onder Zaaktype in admin?

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1345]
# Bug

Waarom staat https://catalogi-api.vng.cloud/admin/datamodel/resultaattype/494/change/?_changelist_filters=q%3DNiet-ontvankelijk deze niet hier: https://catalogi-api.vng.cloud/admin/datamodel/zaaktype/558/change/

**Comment by michielverhoef** [comment]
Wanneer ik de omschrijving van dit resultaattyype wijzig en opsla krijg ik een foutmelding. Ongetwijfeld omdat de omschrijving  de identifier is en als je die wijzigt klopt het niet meer. Wat er volgens mij mis gaat is dat van dit resultaattype de omschrijving niet meer afsluit met een `)` zoals de andere resultaattypen van dit zaaktype. 

Inmiddels is de omschrijving 30 tekens lang geworden en zou dit geen probleem meer moeten zijn.
