### ISSUE TITLE
Volgnummers kunnen dubbel voorkomen?

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1346]
# Bug

Volgnummers kunnen niet uniek zijn?

https://omgevingswet.wiki/bin/view/Zaaktypecatalogi/CAT_97oa2kKoeuKy8/zaaktype/ZKT_ERkw57ZOPhv7j/zaakinformatieobjecttype/?view=zaakinformatieobjecttype

Dat kan bij ons niet?

**Comment by CMasselink** [comment]
Ik ben sowieso benieuwd naar de rationale van volgnummers bij informatieobjecten. Iemand een idee waar we dat na kunnen vragen?

**Comment by joeribekker** [comment]
@hdksi Kan jij het nut van het volgnummer uitleggen in de context van Informatieobjecten bij een Zaak?

**Comment by hdksi** [comment]
Onze implementatie in ImZTC-conform, het voorbeeld niet, dus ik weet niet of er sprake is van een bug. Heeft iemand deze aangemeld?

Ik doe navraag over het hoe en waarom van het volgnummer.

**Comment by hdksi** [comment]
Nog even met een van de ImZTC-huisexperts gesproken: volgnummer is een gemaksattribuut, bedoeld om het ontwerp van zaaktypen te vereenvoudigen - het is makkelijker om een nummer dan een naam van een informatieonbjecttype aan een zaaktype te koppelen.

Voor wat betreft de 'bug'. Dat lijk inderdaad een echte bug te zijn, in het ImZTC wel te verstaan. De enumeratie 'richting' is namelijk niet compleet, waardoor de in de Omgevingswet-ZTC een workaround nodig was, en @joeribekker's voorbeeld inderdaad niet aan het ImZTC en de Catalogi API-specs voldoet.

De mogelijke attributen voor 'richting' zijn:
`intern`: ontstaan binnen de eigen organisatie en alleen te verspreiden binnen die eigen organisatie
`inkomend`: ontvangen van buiten de eigen organisatie, daarna alleen te verspreiden binnen de eigen organisatie
`uitgaand`: ontstaan binnen de eigen organisatie, daarna te verspreiden buiten de eigen organisatie.
`inkomend-uitgaand` _(niet in ImZTC)_: ontvangen van buiten de eigen organisatie, daarna te verspreiden buiten de eigen organisatie.

**Comment by hdksi** [comment]
Voorstel is dus wat mij betreft dat we een extra toegestane waarde voor 'richting' toevoegen.

@Hugo-ter-Doest: graag jouw reactie en eventueel prio.

**Comment by michielverhoef** [comment]
Veld `richting` is deprecated geworden met de introductie van relatieklasse `Verzending`. Bij een ZIOT wordt de richting niet meer vastgelegd, wanneer een IO ontvangen of verzonden wordt wordt een `Verzending` relatieklasse aangemaakt. Op deze manier kan een IO zowel inkomend, uitgaand, intern en alle combinaties daarvan zijn.
