### ISSUE TITLE
Als ontwikkelaar vraag ik me af waar de afhankelijkheid tussen resultaattypen en besluittypen vastgelegd zou moeten worden

### ISSUE THREAD

**Issue by AHNRoxit** [VNG-Realisatie/gemma-zaken#1347]
Zodat we bij de realisatie van een verzoekafhandelingcomponent de juiste procesondersteuning kunnen realiseren zonder de principes van common ground te frustreren.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by CMasselink** [comment]
Nog een beetje context:
Het kan zijn dat er bij een bepaald resultaat, altijd een besluit aanwezig moet zijn. Je zou daarbij dus een relatie kunnen leggen tussen resultaattype en besluittype. Is dit wenselijk?

**Comment by AHNRoxit** [comment]
Zie als voorbeeld de tab Resultaat in de zaaktypecatalogus op omgevingswet-wiki. Bijvoorbeeld deze:
https://omgevingswet.wiki/bin/view/Zaaktypecatalogi/CAT_97oa2kKoeuKy8/zaaktype/ZKT_E1MG2ylNbIy74/resultaattype/?view=resultaattype

**Comment by joeribekker** [comment]
Helder, er moet dus een 0-* relatie gelegd worden tussen resultaattypen en besluittype. Hier is niet eerder over gesproken maar komt overeen met RGBZ.

**Comment by joeribekker** [comment]
@Hugo-ter-Doest Trio en visie?

**Comment by Hugo-ter-Doest** [comment]
In de ZTC moet dus de relatie gelegd kunnen worden. Ook op zaakniveau heeft dit gevolgen: als je een resultaat van de zaak zet en er is een besluit verplicht, dan moet je dat direct mee kunnen geven. En als je een resultaat zonder besluit probeert te zetten krijg je foutmelding.

**Comment by michielverhoef** [comment]
De relatie [Resultaattype leidt tot Besluittype ](https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/relatiesoort/resultaattype.leidt_tot_besluittype) is opgenomen in Catalogi API versie 1.2.0
