### ISSUE TITLE
Als ontwikkelaar wil ik een scherpere definitie van 'besluittoelichting'

### ISSUE THREAD

**Issue by AHNRoxit** [VNG-Realisatie/gemma-zaken#1348]
Zodat ik weet waar het veldje wel en niet voor gebruikt zou moeten worden. 
Denk aan: tekst(fragment) voor beschikkingsdocument voor aanvrager v.s. metadata voor zoekfuncties en herkenbaarheid voor gebruikers. Als verschillende leveranciers verschillend gebruik gaan maken van dit veld sneuvelt de common ground gedachte  

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by michielverhoef** [comment]
In ImZTC 2.2 staat als beschrijving van het veld toelichting:
_Deze attribuutsoort heeft vooral een documentatiefunctie en is bedoeld om een toelichting te geven op dit BESLUITTYPE. Hier kan bijvoorbeeld een beschrijving worden gegeven van de betekenis van het besluit voor - het verloop van - een ZAAKTYPE._

Is dit al duidelijker of moet er echt een nieuwe definitie gemaakt worden? Het liefst blijf ik zo dicht mogelijk bij wat er ImZTC al beschreven is.

(zie ook https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/attribuutsoort/besluittype.toelichting)

**Comment by AHNRoxit** [comment]
Hallo Michiel. Waar jij op wijst is de toelichting op het besluit**type**, de issue die ik had aangemaakt gaat over de toelichting van het **besluit**.

**Comment by michielverhoef** [comment]
Woeps, had ik even de verkeerde toelichting te pakken. 

In https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/besluit.besluittoelichting staat:

_De (samenvatting van de) toelichting op het besluit zoals veelal vermeld in de besluittekst. Het betreft de attribuutsoort Beschikkingtoelichting in het GFO Zaken 2004._

Kun je hier wat mee?

**Comment by AHNRoxit** [comment]
Dit is de beschrijving waarvan ik denk dat dit veel te onduidelijk is. Het kan betekenen dat hier een tekstfragment staat dat gebruikt is bij de documentcreatie van de beschikking voor de aanvrager, maar ook een beschrijving bedoeld voor intern gebruik om besluiten gemakkelijk te kunnen vinden. Of iets dat handig was in het proces van het beheren van besluittypen.

**Comment by michielverhoef** [comment]
De voorbeelden die je noemt kan ik niet matchen met een (samenvatting van de) toelichting op het besluit.  Dit gaat over de inhoud van het besluit (dit specifieke besluit, niet iets generieks over besluittypen heen) en kan mogelijk gebruikt worden voor de doeleinden die je beschrijft maar zoals je weet kunnen waarden van attributen voor allerlei doeleinden gebruikt worden. Als voorbeeld: wanneer je in de titel van het document de zaakidentificatie opneemt is het vrij eenvoudig in een hoeveelheid bestanden alle bij een zaak behorende documenten terug te vinden. Maar die functionaliteit staat niet beschreven in de omschrijving van het attribuut titel.

Even voor mijn beeld, dit attribuut en de omschrijving ervan zaten ook al zo in RGBZ 1, StUF ZKN en Zaak- Documentservices. Was het gebruik van dit attribuut daar dan geen probleem?

**Comment by AHNRoxit** [comment]
Uh. Nu begrijp ik jouw niet zo goed. De tekst uit de RGBZ is _De (samenvatting van de) toelichting op het besluit zoals veelal vermeld in de besluittekst._. Dat klinkt voor mij toch heel erg alsof deze toelichting iets te maken zou kunnen hebben met wat in het beschikkingsdocument staat.

**Comment by michielverhoef** [comment]
Precies, het gaat over de inhoud van het besluit. 

Hoe dat gebruikt (zoekterm, tonen in een overzicht, ?) wordt is niet voorgeschreven. Dat moet je denk ik ook niet willen, zolang het gebruik een correcte invulling van het attribuut niet hindert.

Maar, zoals ik al vroeg: hoe gebruiken jullie dit gegeven nu dan? Want de toelichting op een besluit zit ook al in RGBZ 1 en StUF-ZKN/Zaak- Documentservices.
