### ISSUE TITLE
NRC checks callback URL and says no auth found

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1352]
# Bug

Van @adgerrits :

ik was vandaag wat aan het testen met de API's zoals ze nu voor het fieldlab klaar staan en loop op 1 ding vast waarbij ik er niet achter kom wat ik fout doe.
Mocht je zo weten wat ik fout doe dan zou het fijn zijn als je me dat even kunt laten weten.

Ik probeer een abonnement te nemen op de NRC via: https://notificaties-api.vng.cloud/api/v1/schema/#operation/abonnement_create
Heb een werkend token, en roep de API aan met:

```
{
    "callbackUrl": "http://cloud.ag4it.nl:4000/notificaties",
    "auth": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTU2OTQ0NDQzMH0.ZEgdXMME-c7dMFo_j3DZ2Kr7hYzYZ96Je-BrCK5GDaM",
        "kanalen": [
            {
                "filters": {},
                "naam": "autorisaties"
            }
        ]
}
```
Lijkt mij okee, maar de NRC blijft vinden:

```
{

"type":
"https://notificaties-api.vng.cloud/ref/fouten/ValidationError/",

"code":
"invalid",

"title":
"Invalid input.",

"status":
400,

"detail":
"",

"instance":
"urn:uuid:ba5e4394-b20c-4f1e-abb6-b9aa667b2253",

"invalidParams": [

{

"name":
"callbackUrl",

"code":
"no-auth-on-callback-url",

"reason":
"De opgegeven callback URL is niet beveiligd met autorisatie."

}

]

}
```

Op basis waarvan constateert de NRC dat de callback URL niet is beveiligd?

Krijgt zonder authenticatie bij aanroep van de callbackURL een 401 + een WWW-Authenticate (Bearer) header terug, dus ik zou denken dat hij kan constateren dat hij wel beveiligd is.

**Comment by joeribekker** [comment]
Ik heb over een soortgelijke vraag tijdens het Fieldlab een issue aangemaakt: https://github.com/VNG-Realisatie/gemma-zaken/issues/1334

Echter volgens mij is het probleem dat jij schetst anders en wordt er gecontroleerd op een 403 en niet 401. Ik maak hier ook een issue voor aan.

**Comment by adgerrits** [comment]
Nav https://github.com/VNG-Realisatie/gemma-zaken/issues/1334#issuecomment-535488042 lees ik dat er bij webhook.site ‘dummy’ gebruikt zou mogen worden. Niet getest maar al met wel fijn als de documentatie wat uitgebreider wordt.
