### ISSUE TITLE
Website DRC komt niet op na Installatie en configuratie van een lokale kopie van de referentie-implementatie

### ISSUE THREAD

**Issue by RvdKlip** [VNG-Realisatie/gemma-zaken#1357]
Hi,

We hebben de lokale installatie uitgevoerd van de referentie-implementatie ZGW API's. Alle containertjes komen goed op. Echter daarna is via de browser alleen de DRC (10.0.75.1:8001) niet te benaderen. De rest doet het dus wel netjes (10.0.75.1:8000 en 8002 t/m 8005). Tijdens het opbrengen van de containtertjes geeft hij wel keurig aan 'Starting infra_drc_web_1 ... done'

Enig idee waar dat aan ligt? Of behoort dit zo te werken?

Als deze bevinding niet op dit board thuis hoort, dan hoor ik het ook graag. Ik had de melding ook al geplaatst op de Gitlab Haven. Vanuit daar kreeg ik een verwijzing naar dit board.

Dank.

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost?
Binnen eigen organisatie. Win10pro  - docker desktop 2.1.0.2

**Comment by michielverhoef** [comment]
Zo maar een paar vragen die bij mij te binnen schieten:
* Wat is type en versie van de browser?
* Is de DRC wel te benaderen via ping?
* Draait er nog een ander proces op poort 8001?
* Lukt het op een andere machine wel?
* Lukt het wel om de DRC op een andere poort te laten draaien? Ik weet niet of dat kan maar kan me voorstellen dat dit met een config file in te stellen moet zijn.

Met het commando netstat -ab kun je nagaan of er services draaien en op welke poort.

Ik meen ooit eens gelezen te hebben dat poort 8001 gebruikt wordt in tunnel verbindingen (vpn en dat soort dingen). Dus het kan heel goed dat die poort al bezet is.

**Comment by Hugo-ter-Doest** [comment]
Als dit nog een issue is graag heropenen.
