### ISSUE TITLE
Als leverancier wil ik weten wat de bron wordt voor het opvragen van zaak informatie

### ISSUE THREAD

**Issue by JohnRooijakkers** [VNG-Realisatie/gemma-zaken#1358]
Binnen de Common Ground architectuur geldt als uitgangspunt dat informatie bij de bron wordt opgevraagd. Dit geldt voor informatie die is opgeslagen in basisregistraties, kernregistraties maar in principe ook voor taak specifieke registraties. Voor de meeste informatie (zoals opgenomen in het RSGB), is de bron registratie eenduidig te bepalen. Voor zaakinformatie (zoals opgenomen in het RGBZ) is dit niet het geval. De bron van zaakinformatie verschilt echter veelal per zaaktype.
 
In de huidige situatie (GEMMA) wordt de informatie over zaken veelal verzameld en bevraagd in één (gemeentelijk) zakenmagazijn. Wordt ook in de Common Ground architectuur een centraal zakenmagazijn voorzien of wordt voor iedere zaak de bronapplicatie (zaak specifieke applicatie) bevraagd.  De zaakregistratie component lijkt nu de rol van zakenmagazijn te gaan vervullen. Dit lijkt in tegenspraak met het bovenstaande principe (informatie bevragen bij de bron).

En hoe verhoudt een zaakregistratiecomponent zich tot organisaties als er bijvoorbeeld sprake is van een samenwerking tussen gemeenten binnen een domein (bv een belastingsamenwerking of een IGSD)? Heeft iedere organisatie een eigen zaakregistratie component? Of benadert de gemeentelijke samenwerking de zaakregistratie componenten bij de deelnemende gemeenten? Of wordt hier een andere implementatie voorzien?

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
John, dank voor deze vraag. Dit onderwerp is ook meermalen de revue gepasseerd in het ZGW-team. De API's doen geen aannames over het aantal registraties voor bijv. Zaken. Dus er kunnen en mogen meerdere registraties zijn voor dezelfde entiteit. Dus bijv. meerdere DRC's. De API's zijn daarop voorbereid doordat we met URI's werken om naar andere registraties te wijzen.

> Wordt ook in de Common Ground architectuur een centraal zakenmagazijn voorzien of wordt voor iedere zaak de bronapplicatie (zaak specifieke applicatie) bevraagd. 

In CG is hierover geen uitspraak gedaan, zover ik weet. Het lijkt me verstandig het aantal registraties van dezelfde soort binnen het applicatielandschap van de gemeente te beperken (uiteindelijk tot 1). Consumers die over domeinen heen zaakgegevens nodig hebben hoeven dan niet een hele trits registraties te bevragen.

> De zaakregistratie component lijkt nu de rol van zakenmagazijn te gaan vervullen. Dit lijkt in tegenspraak met het bovenstaande principe (informatie bevragen bij de bron).

Volgens mij is dit niet in tegenspraak omdat de registratie de bron is. niet de TSA. De TSA wordt slechts een van de consumers van zaakgegevens.

> En hoe verhoudt een zaakregistratiecomponent zich tot organisaties als er bijvoorbeeld sprake is van een samenwerking tussen gemeenten binnen een domein (bv een belastingsamenwerking of een IGSD)? Heeft iedere organisatie een eigen zaakregistratie component? Of benadert de gemeentelijke samenwerking de zaakregistratie componenten bij de deelnemende gemeenten? Of wordt hier een andere implementatie voorzien?

Ik denk dat organisaties hun eigen registratiecomponenten hebben, maar dit is ook afhankelijk van de samenwerkingsvorm. Ik pleit ervoor dat organisaties in termen van producten/diensten met elkaar samenwerken en niet in termen van zaken. Dat betekent dat organisaties niet in zaken werken van andere organisaties, maar bijv. wel zaken en documenten ophalen bij de andere organisatie.

Ik wil deze vraag even open laten staan voor discussie. 

Vanuit architectuur moet hier naar worden gekeken. @hdksi zou jij kunnen meelezen en reageren?

**Comment by CMasselink** [comment]
Ik kan me helemaal vinden in het antwoord van Hugo.
Ik zie een zaakregistratiecomponent als bron voor zaken en daardoor wel als eenduidig te bepalen. De standaard biedt inderdaad ruimte om meerdere zaak & documentregistraties te implementeren maar het lijkt me verstandig om functionaliteit (in dit geval zaakregistratie) zoveel mogelijk te hergebruiken en niet dubbel te implementeren. 
Dit gaat name een voordeel zijn voor werken in de keten. Zoals Hugo al aangeeft, hoeven TSA's maar denk specifiek ook aan KCS applicaties of 'Mijn' omgevingen niet in een veelvoud aan registraties te kijken om een integraal zicht op zaken (bijvoorbeeld van/over een burger) te geven.

**Comment by michielverhoef** [comment]
Ik kan me vergsissen maar ik heb het gevoel dat deze vraag voortkomt uit het proberen de ZGW API's te plotten op bestaande applicaties (silo's). 

Het zaakregistratie component heeft een heel andere rol dan het huidige zakenmagazijn. Waar het zakenmagazijn een afslag is van zaakgegevens die leven in de verschillende vakapplicaties (TSA's) is het zaakregistratiecomponent (ZRC) de enige opslag en bron voor deze zaakgegevens. De TSA zal de ZRC dan ook gebruiken om zaakgegevens op te halen en op te slaan.

Eén van de eisen aan de ZGW APi's was dat deze multi-tenant zouden worden opgezet. Door het opnemen van het attribuut bronorganisatie is het mogelijk om zaken en documenten van verschillende organisaties in de keten te  identificeren. Dit is weer noodzakelijk voor het samenwerken in termen van producten/diensten zoals Hugo dat beschrijft.

**Comment by hdksi** [comment]
Wellicht ten overvloede, want de opmerkingen van collega's zijn al redelijk uitputtend 👍. 

> Wordt ook in de Common Ground architectuur een centraal zakenmagazijn voorzien of wordt voor iedere zaak de bronapplicatie (zaak specifieke applicatie) bevraagd.

Een van de belangrijkste uitgangspunten van Common Ground/GEMMA Gegevelansdschap is dat proceslogica en procesgegevens worden gescheiden. Iedere 'zaakspecifieke applicatie' bestaat dus straks uit een proces- en interfacedeel dat middels een (gestandaardiseerde) gegevensdienst gekoppeld is aan één of meerdere registers waarin de gegevens die nodig zijn om een proces uit te voeren zijn opgeslagen. Een 'zaakafhandelapplicatie' slaat zaakgegevens op in een zakenregister, documenten in een documentenregister, besluiten in een besuitenregister etc. Die registers fungeren voor de daarin opgeslagen gegevens als (enige) bronregistratie. Andersom is het ook goed mogelijk, zelfs wenselijk en waarschijnlijk, dat meerdere 'zaakafhandelapplicaties' zaakgegevens opslaan in één (zaak)register, en ook één documentenregister, besluitenregister etc. delen.

Bovenstaande raakt aan een interessante (architectuur)vraag die ook @Hugo-ter-Doest al even noemde: mogen er meerdere zakenregisters, documentenregisters etc. naast elkaar bestaan binnen één organisatie? Vanuit architectuuroogpunt zie ik, zolang daartussen geen gegevens worden gedupliceerd, weinig bezwaren, maar ik kan me voorstellen dat het bevragen van een (groot) aantal registers de performance van het 'zakenapplicatielandschap' niet ten goede komt. Deze vraag geldt voor het hele Gegevenslandschap en is dus breder dan zaakgericht werken alleen. Iets om te bespreken met collega-architecten dus. Ik kom hierop terug.

Voor wat betreft samenwerken in de keten: daarover komt (op basis van een Omgevingswet-casus) binnenkort een handreiking.

**Comment by MaartenRutten** [comment]
_"Iedere 'zaakspecifieke applicatie' bestaat dus straks uit een proces- en interfacedeel dat middels een (gestandaardiseerde) gegevensdienst gekoppeld is aan één of meerdere registers waarin de gegevens die nodig zijn om een proces uit te voeren zijn opgeslagen._ "

Wordt daarmee gezegd dat een TSA niet operationeel kan worden ZONDER ZRC, DRC,...? 
Of anders gezegd: een TSA kan pas operationeel worden als 100% van de gegevens die nodig zijn voor afhandeling binnen de TSA, ondergebracht worden in het ZRC. 
Voor een complexe TSA kan op basis van de huidige mogelijkheden van het ZRC slechts ongeveer 10% van de noodzakelijke gegevens in het ZRC worden vastgelegd. Dit omdat ZRC gebaseerd is op de rol Zakenmagazijn. En binnen het Zakenmagazijn wordt de grootste gemene deler van de zaakgegevens vastgelegd. 
Is het de ambitie om dit te laten groeien naar 100%? Of komen er nog andere componenten waarin de TSA-gegevens ondergebracht gaan worden?

**Comment by hdksi** [comment]
`Wordt daarmee gezegd dat een TSA niet operationeel kan worden ZONDER ZRC, DRC,...?`
Zolang met die TSA zaken worden behandeld en documenten worden verwerkt klopt dat.
`Of anders gezegd: een TSA kan pas operationeel worden als 100% van de gegevens die nodig zijn voor afhandeling binnen de TSA, ondergebracht worden in het ZRC.`
Nee, dit is niet de insteek. Het zakenregister wordt gebruikt voor het opslaan van generieke zaakgegevens. Aanvullende gegevens, die alleen van belang zijn voor het zaakgericht afhandelen van zaken binnen een bepaald domein, krijgen hun eigen domeinspecifieke register. Zaakgegevens worden daarmee dus verspreid opgeslagen over generieke registers (zaakregister, documentregister, besluitenregister) en domeinspecifieke registers. Die specifieke registers vallen niet binnen de scope van het ZGW API's-ontwikkeltraject.

**Comment by JohnRooijakkers** [comment]
> 
> 
> > Wordt daarmee gezegd dat een TSA niet operationeel kan worden ZONDER ZRC, DRC,...?
> 
> Zolang met die TSA zaken worden behandeld en documenten worden verwerkt klopt dat.
> 
> > Of anders gezegd: een TSA kan pas operationeel worden als 100% van de gegevens die nodig zijn voor afhandeling binnen de TSA, ondergebracht worden in het ZRC.
> 
> Nee, dit is niet de insteek. Het zakenregister wordt gebruikt voor het opslaan van generieke zaakgegevens. Aanvullende gegevens, die alleen van belang zijn voor het zaakgericht afhandelen van zaken binnen een bepaald domein, krijgen hun eigen domeinspecifieke register. Zaakgegevens worden daarmee dus verspreid opgeslagen over generieke registers (zaakregister, documentregister, besluitenregister) en domeinspecifieke registers. Die specifieke registers vallen niet binnen de scope van het ZGW API's-ontwikkeltraject.
> 
> _edit: meer informatie over de voorgestelde inrichting is te vinden op [GEMMA Online](https://www.gemmaonline.nl/images/gemmaonline/f/f6/20190620_-_Zaakgericht_werken_in_het_Gemeentelijk_Gegevenslandschap_v101.pdf). Het stuk moet worden bijgewerkt, maar de uitgangspunten zijn onveranderd._

**Comment by JohnRooijakkers** [comment]
Excuus :-)
