### ISSUE TITLE
Als medewerker wil ik weten welke boot van welke rederij overlast veroorzaakt...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#136]
... zodat ik snel de bron van overlast kan vinden

Dit betreft het ontsluiten van domeinspecifieke gegevens naar betrokken partijen. Dit punt is best gevoelig, aangezien het vastleggen van het informatiemodel voor elk mogelijk proces onbegonnen werk is. Dit geeft vendors flexibiliteit in hoe en waar de infromatie bewaard wordt, met vendor lock-in als groot risico. Het betekent ook dat partijen onderling akkoord moeten zijn op de informatiestructuur om deze te kunnen uitwisselen.

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd
- [ ] er is consensus over WAAR deze gegevens bewaard worden

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Gekozen oplossing voorkomt bij voorkeur vendor lock-in
- [ ] Duidelijkheid wie eigenaar is van de data

**Taken**
- [ ] Bepalen waar de data bewaard worden
- [ ] Onderzoeken hoe vendor lock-in voorkomen/tegengegaan kan worden
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]

**Comment by michielverhoef** [comment]
Voor een koppelvlak naar domeinspecifieke gegevens moet wel degelijk een informatie model gemaakt worden. Een informatiemodel geldt niet voor één proces maar voor een domein waar een applicatie voor gebruikt wordt.
Op het moment dat er een domein-specifiek informatie model is en hier een koppelvlak voor gemaakt is is je vendor-lockin probleem een stuk kleiner. 
Het voor dit traject (API op ZRC) relevante deel van deze user story is het bevragen van zaken op zaaktype (melding overlast water). Het bevragen van een domeinspecifieke taakapplicatie ligt m.i. buiten de scope van het maken van een API op een ZRC.

**Comment by Hugo-ter-Doest** [comment]
Eens met het eerste deel van je opmerking. Echter, dat het buiten scope is ben ik niet mee eens. Die domeinspecifieke gegevens heb je nodig bij de behandeling van de zaak. Ze moeten dus op een of andere manier zijn te vinden als je de zaakgegevens ophaalt bij de ZRC. Een URL naar deze gegevens ligt dan toch erg voor de hand? Het raakt volgens mij wel de API specificatie.

**Comment by michielverhoef** [comment]
Ik heb Arjan Kloosterboer toegevoegd als assignee (het kan nu ;-) ),  weliswaar is hij nog met vakantie maar het lijkt me nuttig als hij er ook naar kijkt.

**Comment by Hugo-ter-Doest** [comment]
Tijdelijk oplossen met de ORC.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest deze komt vanuit water/mor/amsterdam nog relevant?

**Comment by TCIMEddy** [comment]
In overleg met indiener op close
