### ISSUE TITLE
Handmatig opvoeren testdata lukt niet

### ISSUE THREAD

**Issue by erikdelepper** [VNG-Realisatie/gemma-zaken#1361]
# Impediment

Wij hebben de referentiecomponten geïnstalleerd en willen nu testdata opvoeren om een bevraging vanuit een KCS te testen. Bij het opvoeren van een zaak, moet ik ook een zaakstatus opgeven. Bij de zaakstatussen van de het gekozen zaaktype, kan ik echter geen URI vinden.

[assign aan Eddy, voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by michielverhoef** [comment]
Dit klinkt als iets in de beheer-pagina's van de referentieimplementaties?

**Comment by CMasselink** [comment]
Ik gebruik de beheerschermen zelf niet maar wellicht helpt dit je voor nu alvast verder: 
Via onderstaande call kan je even alle statustypes ophalen en krijg je ook de URI terug die je weer kan gebruiken voor het zetten van een zaakstatus.
https://catalogi-api.vng.cloud/api/v1/schema/#operation/statustype_list 

(Verdere beantwoording/reactie laat ik even aan beheer over maar misschien haalt bovenstaande je impediment al weg)

**Comment by Hugo-ter-Doest** [comment]
Graag heropenen als het issue nog speelt.
