### ISSUE TITLE
Als manager wil ik een rapportage kunnen maken van meldingen in de openbare ruimte

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#137]
...zodat ik kan achterhalen hoe vaak welke categorie meldingen in welke straat, buurt of wijk voorkomen.

Idee voor demonstratie: met JasperServer een rapportage maken die de benodigde informatie ophaalt bij de rest service.

Zie isssue #183 voor de RGBZ-mapping.
Zie [hier](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Dimpact-MOR.md) voor de architectuurschets.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] er is een architectuurschets
- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [x] Maken architectuurschets [@Hugo-ter-Doest]
- [x] Opstellen welke velden bij een rapportage horen [@Hugo-ter-Doest]
- [ ] Aanleveren voorbeeldrapportages [@Hugo-ter-Doest]
- [ ] Schrijven (unit) test voor referentie-implementatie [Maykin Media]
- [ ] Implementeren in referentie-implementatie [Maykin Media]
- [ ] Genereren/opstellen van OAS 3.0 [Maykin Media]
- [ ] Functionele documentatie [Maykin Media]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [Maykin Media]

**Comment by ehotting** [comment]
Is dit op niveau zaaktype? Is een dergelijke rapportage niet logischer vanuit bron onder proces? Of is de veronderstelling hier dat meldingen volledig in de vorm van een zaak bestaan, zonder proces-instance met eigen informatie?

**Comment by Hugo-ter-Doest** [comment]
Nee dit is op niveau zaken, instanties dus. Ik begrijp je andere vragen over bron, proces en proces-instance niet?

**Comment by jgortmaker1** [comment]
ik zou de stelling willen poneren dat je hiervoor mij de MOR-applicatie moet zijn..
het hangt maar net van het type rapportage af of je hier een ZDS service voor nodig hebt...

Zit dus weer een architectuurvraag onder: welke rapportages wil ik vanuit mijn ZRC genereren en welke vanuit mijn vakapplicatie/domeinregistratie...

**Comment by Hugo-ter-Doest** [comment]
Moeten we bespreken.

**Comment by TCIMEddy** [comment]
Altijd discussie (ook in Haarlem waar we dit als eerste proces hebben gedaan). Essentieel is dat er een voorbeeld moet komen van de rapportage. Dan pas wordt discussie zinvol. @BoerBas kun jij voorbeeld schermprint of zoiets uit Haarlem toevoegen.

**Comment by Hugo-ter-Doest** [comment]
Architectuurschets is [hier](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Dimpact-MOR.md) te vinden.

**Comment by Hugo-ter-Doest** [comment]
In de architectuurschets zit nu een voorbeeld van een rapportage.

**Comment by TCIMEddy** [comment]
@ehotting Als jij als PO akkoord bent wil jij dan vinkje zetten bij PO akkoord (sorry)

**Comment by TCIMEddy** [comment]
@jgortmaker1 Wil jij hier nog iets over zeggen? Zo niet ook even vinkje zetten (ook sorry)

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Er staat een vinkje bij RGBZ klopt dit? (wederom sorry)

**Comment by michielverhoef** [comment]
Ik  ben het toch wel een beetje eens met de stelling van Jeffrey dat dit vanuit de MOR applicatie zou moeten kunnen komen. Daar staat (verwacht ik) ook de domein informatie, naast type melding, status, behandelaar etc.
Tenminste, ik ga er van uit dat de MOR applicatie de bron is van de gegevens die in het ZRC opgenomen worden. Of zijn er ook gegevens die wel in de ZRC staan maar niet in de MOR applicatie?

**Comment by Hugo-ter-Doest** [comment]
De domeininformatie voor Meldingen zal niet bij de MOR-applicatie komen te staan. We hebben afgesproken dat business objecten worden uitgemodelleerd (uiteindelijk in de toekomst) en dat daar weer een API bij komt. Voor de referentie-implementatie werken we met een substituut genaamd ORC waarin we tijdelijk dit soort objecten kunnen opslaan. Voor rapportages wil je dan een combinatie van ZRC en MeldingRegistratieComponent bevragen.

**Comment by ehotting** [comment]
@Hugo-ter-Doest Het voorbeeld van rapportage lijkt verdwenen, wil je daar nog even naar kijken?

De rapportages die Hugo beschrijft voegen zeker iets toe, maar eerst moet de API meer compleet werken. Vandaar nu prio M.

**Comment by michielverhoef** [comment]
Deze user story kan worden ingevuld met het zoeken op zaaktype en geo. 
TzT worden de zaakobjecten hier nog bij betrokken maar die zijn nu nog geen onderdeel van de API. Nu zullen deze gegevens ergens anders opgeslagen en te raadplegen zijn.

Ik sluit dit issue.
