### ISSUE TITLE
Als Consumer wil ik specifieke zaakkenmerken kunnen opvragen via een gestandaardiseerde API

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1370]
Scenario:
Een applicatie die de afhandeling die Meldingen Openbare Ruimte ondersteunt voor de buitendienst wil de openstaande meldingen kunnen opvragen bij ZRC inclusief de specifieke gegevens van de melding (voorbeeld: categorie van de melding (afval, reparatie, groen, ...).

**Comment by michielverhoef** [comment]
Als ik deze wens zo lees gaat dit meer richting (het kunnen opvragen van) verzoeken (een melding is uiteindelijk een vorm van een verzoek) aangezien er meer gegevens opgevraagd worden dan in een zaak opgeslagen zitten.
@Hugo-ter-Doest kun jij hier naar kijken?

**Comment by Hugo-ter-Doest** [comment]
Dit kan al met zaaktype-specifieke eigenschappen. Echter voorkeur is om dit in de toekomst met Verzoek en domeinspecifieke objecten op te lossen.
