### ISSUE TITLE
File size field has a limit of 2147483647

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#1371]
The field `bestandsomvang` of `EnkelvoudigInformatieObject` has a `PositiveIntegerField` type, which means that its value cant'be more than 2147483647. It makes impossible to upload files with size > 2 GB. 

This should be fixed before 1.1 version of standard is released, because this maximum values is shown in the OAS schema

**Comment by sergei-maertens** [comment]
Fixed in https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/commit/ac420e33f51b25d53ff4495e36da942bda0859b5
