### ISSUE TITLE
Als gemeente wil ik een melding openbare ruimte over afval in het buitengebied automatisch laten routeren naar een afdeling of ketenpartner op basis van de locatie en de categorie van de melding ...

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#138]
...zodat ik een efficiëntere bedrijfsvoering verkrijg.

We gaan ervan uit dat het klantcontact bij de gemeente blijft. Dus eventuele updates naar de burger over de afhandeling wordt door de gemeente gedaan.

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by jgortmaker1** [comment]
graag een paar voorbeelden toevoegen om de US te verduidelijken

**Comment by Hugo-ter-Doest** [comment]
Routeren, d.w.z. bepalen op welke afdeling dan wel medewerker de melding moet worden gezet is aan de ZAC. Blijft dus over dat je behandelende medewerker/afdeling moet kunnen zetten. En dat kan zover ik weet.
