### ISSUE TITLE
Filteren op resources met ongeldige urls als query parameters geeft een 400 error

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#1381]
# Bug

Als ik filter op een resource met een url die niet wijst naar de correcte resource of zelfs 404 geeft, dan zou ik een lege lijst verwachten als response i.p.v. een 400 error.

Als ik bijv. bij `Gebruiksrechten` probeer te filteren op `informatieobject` en ik een url zoals `https://google.com` geef (die dus niet wijst naar een informatieobject), dan krijg ik de volgende response:

```json
GET https://documenten-api.vng.cloud/api/v1/gebruiksrechten?informatieobject=https://google.com

{
    "type": "http://localhost:8000/ref/fouten/ValidationError/",
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:eb2a107d-e52e-4930-ad56-474b4ddc9cc4",
    "invalidParams": [
        {
            "name": "informatieobject",
            "code": "invalid",
            "reason": "Ongeldige resource URL opgegeven"
        }
    ]
}
```

Hierover staat momenteel ook nog niets over beschreven in de standaard

**Comment by sergei-maertens** [comment]
Implemented in:

* https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/commit/0e67f5fcc679628cfb9479ee8a91ed0f776da52f
* https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/commit/6a87d0887b0f36fa63e46940cdca406d8b03f6be
* https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/commit/2617615c443a7ab29bfdf81a6eddd5d8f148dfcb
