### ISSUE TITLE
In de standaard staat niet aangegeven dat gekoppelde Zaaktypes, Informatieobjecttypes en Besluittypes dezelfde catalogus moeten hebben

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#1383]
# Bug

In de referentieimplementatie van het ZTC wordt er bij het aanmaken/bijwerken van relaties tussen Zaaktypes en Besluittypes en Informatieobjecttypes gevalideerd of de twee types in kwestie dezelfde catalogus hebben, als dit niet het geval is, dan wordt er een 400 teruggegeven.

Dit gedrag staat niet gedocumenteerd in de [standaard](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/catalogi/index.md) van het ZTC

**Comment by joeribekker** [comment]
Zie: https://github.com/VNG-Realisatie/gemma-zaken/pull/1412
