### ISSUE TITLE
Relatie tussen Zaaktype en Informatieobjecttype van verschillende catalogi zou onmogelijk moeten zijn

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#1384]
# Bug

Momenteel is het in de referentieimplementatie van het ZTC mogelijk om een relatie te leggen tussen een Zaaktype en een Informatieobjecttype waarvan de catalogi niet hetzelfde zijn, terwijl dit een 400 error terug zou moeten geven

**Comment by sergei-maertens** [comment]
Closing as the tech is done for this
