### ISSUE TITLE
Als medewerker wil ik een of meerdere producten uit de PDC aan een verzoek koppelen

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1386]
...zodat duidelijk is wat er wordt verwacht van de gemeente.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by EdwinCoster** [comment]
Deze user story heeft mogelijk consequenties voor het gegevensmodel.

**Comment by hdksi** [comment]
Hoe moet ik deze story begrijpen? Als in 'medewerker definieert een verzoek(type) en koppelt daaraan één of meerdere producten zodat klanten verzoeken kunnen indienen'. Of als in 'medewerker koppelt één of meerdere producten aan een binnengekomen verzoek van een klant'? Ik vermoed het laatste, wat impliceert dat we 'ongestructureerde' verzoeken willen toestaan.

**Comment by joeribekker** [comment]
@hdksi De visie geeft aan:

> Verzoek kan meerdere producten/diensten omvatten (dit ondersteunt een winkelmandje) en derhalve tot meerdere zaken leiden. Anders is het een vraag, dus contactmoment. 

en 

> Bij een verzoek wordt alleen generieke metadata opgeslagen, domein- of procesgegevens worden in een andere registratie opgeslagen.

**Comment by ArjanKloosterboer** [comment]
Da's een interessante, dat eerste citaat uit de visie. Wat nu als een burger via het digitale kanaal een vraag stelt? Valt dat niet onder verzoeken (een verzoek tot antwoord op een vraag)? Waarin zit het onderscheid tussen een klantcontact en een verzoek? Als er in een vraag geen producten/diensten besteld worden, is het dan een klantcontact? Of is het onderscheidende aan een klantcontact dat er echt sprake is van contact, synchroon. Terwijl het digitaal indien van een verzoek en de reactie daarop asynchroon is. Is dan een klantcontact een subtype van een verzoek? En wat nu met digitaal chatten of de gemeente-Whatsapp? Klantcontact?

**Comment by hdksi** [comment]
Onderstaande volgens de _huidige_ visies op verzoeken en klantcontacten. Dit is een oefening in het doorredeneren van de keuzes daarbinnen, niet per se het definitieve antwoord.

> Da's een interessante, dat eerste citaat uit de visie. Wat nu als een burger via het digitale kanaal een vraag stelt? Valt dat niet onder verzoeken (een verzoek tot antwoord op een vraag)?

Is daarvoor een product? Zo niet, geen verzoek. In de (open, hulde!), Vlaamse PDC ([link](https://productencatalogus.vlaanderen.be/)) vind ik geen voorbeelden van generieke producten als 'antwoord op een vraag' of 'informatieverzoek'. Verzoeken als vragen behandelen? Dan daartoe een product toevoegen.

Consequentie hiervan is de vraag of we niet eigenlijk moeten spreken van 'bestellingen' in plaats van 'verzoeken'. Hoewel dat laatste vanuit klantperspectief (https://github.com/VNG-Realisatie/gemma-zaken/issues/1417#issuecomment-547348281) zeker niet duidelijker is.

> Als er in een vraag geen producten/diensten besteld worden, is het dan een klantcontact?

Inderdaad. Maar als er telefonisch contact is tussen klant en gemeente over een vergunningsaanvraag, en dat gesprek leidt ertoe dat een medewerker in opdracht van de klant een aanvraag indient, dan is sprake van een klantcontactmoment dat heeft geleid tot een verzoek.

> Of is het onderscheidende aan een klantcontact dat er echt sprake is van contact, synchroon.
Is dan een klantcontact een subtype van een verzoek? En wat nu met digitaal chatten? Klantcontact?

Klantcontact zou een subtype van verzoek worden als vraagbeantwoording een product is. Een bericht per mail of berichtenbox over een zaak aan een initiator is ook een klantcontact. Asynchroon mag dus ook.

> gemeente-Whatsapp?

Ik begreep dat het maar zeer de vraag of deze vraag na december nog relevant is.

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat we in de user story moeten loslaten wie het koppelen doet. Het moet mogelijk zijn een verzoek te koppelen aan een of meerdere producten. Meestal kan de koppeling direct tot stand komen bij het indienen door de klant (denk aan formulier) en soms moet de medewerker dit alsnog doen (of wijzigen).

**Comment by ArjanKloosterboer** [comment]
> Klantcontact zou een subtype van verzoek worden als vraagbeantwoording een product is. Een bericht per mail of berichtenbox over een zaak aan een initiator is ook een klantcontact. Asynchroon mag dus ook.

Aha, nu wordt het echt interessant. Is een klantcontact dan elke interactie met een klant: ontvangst van een brief, van een mail, idem verzending van beide, telefonisch contact, facebookcontact, ontvangst van een digitaal formulier, et cetera?  Dan zou verzoek, wat je neerzet als bestelling van een product, daarvan een subtype zijn. En is het iets anders dan wat nu in het RGBZ klantcontact heet.
Zie ook [deze analyse](https://www.gemmaonline.nl/index.php/Klantcontacten_en_het_RGBZ).

**Comment by hdksi** [comment]
@ArjanKloosterboer: dat klopt, en was één van de redenen voor het losknippen van klantcontacten. Volgens mij kunnen we de tabel waarnaar je linkt als volgt uitbreiden (informeel contact betekent hier contact dat niet over de levering van producten of diensten gaat).

**Soorten klantcontacten**

Klantcontact | Verzoekgerelateerd | Zaakgerlateerd | Niet zaak-/verzoekgerelateerd
-- | -- | -- | --
Synchroon   niet-anoniem leidend tot levering producten/diensten | x |   | x
Synchroon anoniem   leidend tot levering producten/diensten | x |   | x
Asynchroon   niet-anoniem leidend tot levering producten/diensten | x |   | x
Asynchroon anoniem   leidend tot levering producten/diensten | x |   | x
Synchroon   niet-anoniem met betrekking tot lopend(e) verzoek/melding/productaanvraag | Als overgang   zaak-verzoek atomair is kan dit niet. Zie https://github.com/VNG-Realisatie/gemma-zaken/issues/1404#issuecomment-547436681. | x |  
Synchroon anoniem   met betrekking tot lopend(e) verzoek/melding/productaanvraag | n.v.t.(?) | n.v.t.(?) | n.v.t.(?)
Asynchroon   niet-anoniem met betrekking tot lopend(e) verzoek/melding/productaanvraag | Als overgang   zaak-verzoek atomair is kan dit niet. Zie https://github.com/VNG-Realisatie/gemma-zaken/issues/1404#issuecomment-547436681. | x |  
Asynchroon anoniem   met betrekking tot lopend(e) verzoek/melding/productaanvraag | n.v.t.(?) | n.v.t.(?) | n.v.t.(?)
Synchroon   niet-anoniem informeel |   |   | x
Synchroon anoniem   informeel |   |   | x
Asynchroon   niet-anoniem informeel |   |   | x
Asynchroon anoniem   informeel |   |   | x

**Comment by Hugo-ter-Doest** [comment]
Producten kunnen worden gerelateerd via URI of via identificerende gegevens analoog aan personen/bedrijven.

**Comment by Hugo-ter-Doest** [comment]
Producten worden via URI gekoppeld.

**Comment by joeribekker** [comment]
@hdksi Ik weet niet precies wat we met je tabel moeten doen maar het ziet er nuttig uit?

Qua werkzaamheden in dit ticket ga ik het volgende doen:

`VerzoekProduct` als resource introduceren (relatie tussen verzoek en een product). Dit is helaas nodig omdat het PDC een nog niet officiele API-standaard betreft. Hierdoor moeten we identificerende gegevens ergens opnemen. Dat zou nog zonder deze resource kunnen maar gezien er ook aangegeven wordt "[een of] **meerdere** producten uit de PDC aan een verzoek koppelen" moet dit ondergebracht worden in een losse resource.

Overigens zit deze relatie dus alleen tussen een Verzoek en een Product, volgens de US en volgens het [IM diagram](https://github.com/VNG-Realisatie/gemma-zaken/issues/1417#issuecomment-555069158).

**Comment by hdksi** [comment]
De tabel gaat over wanneer sprake is van een klantcontact, en is een gevolg van de discussie die naar aanleiding van het issue ontstond, maar eigenlijk niet relevant voor het specifieke issue zelf.

**Comment by joeribekker** [comment]
Toegevoegd in https://github.com/VNG-Realisatie/klantinteracties-api/pull/16

Zie: [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/klantinteracties-api/1671068ae166efce0aba13c7cc4ed7b25a89e149/src/openapi.yaml#operation/verzoekproduct_create)
