### ISSUE TITLE
Als medewerker wil ik weten waar welk type melding openbare ruimte (categorie) is gedaan... 

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#139]
...zodat ik de melding kan doorzetten naar de juiste behandelaar of ketenpartner.

Medewerker kan van de gemeente zijn of ketenpartner in geval van outsourcing.

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Prio L vanwege het onderdeel catagorie melding dat niet in RGBZ zit.

**Comment by michielverhoef** [comment]
Het is inmiddels mogelijk aan een zaaktype één of meer trefwoorden toe te voegen. https://catalogi-api.test.vng.cloud/api/v1/schema/#tag/zaaktypen/operation/zaaktype_create 

Hiermee zou denk ik deze userstory prima ingevuld kunnen worden.
