### ISSUE TITLE
Als medewerker wil ik kunnen zien waarover het verzoek gaat

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1390]
...zodat ik de juiste afdeling of medewerker kan inschakelen.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by hdksi** [comment]
Heb de US iets aangepast: groeperen naar soort is eigenlijk al een oplossing om de behandeling te verdelen over verschillende medewerkers. In essentie gaat het er volgens mij dat een verzoek voldoende informatie omvat om te kunnen beoordelen door wie of welke afdeling het verzoek behandeld moet worden.

**Comment by Hugo-ter-Doest** [comment]
We ondersteunen iig de attributen van DSO Verzoeken en daarmee ook "Toelichting verzoek". Daaraan kan de medewerker zien waarover het verzoek gaat (in combinatie met gekoppelde documenten en verwijzing naar PDC en domeinspecifieke gegevens).

**Comment by hdksi** [comment]
> We ondersteunen iig de attributen van DSO Verzoeken

Nog even goed kijken naar welke attributen uit DSO verzoeken _generiek_ van belang zijn (en dus onderdeel moeten worden van de Verzoeken API) en welke met (omgevings)domeinspecifieke API ontsloten moeten worden

**Comment by joeribekker** [comment]
Ik schaar de DSO attributen even onder issue: #1421 en werk in dit issue aan het toevoegen van een medewerker aan een verzoek.

**Comment by joeribekker** [comment]
Verwerkt in https://github.com/VNG-Realisatie/gemma-zaken/pull/1448

Zie: [Redoc Contactmomenten API](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/6cf823943b3704d96c537dc04f01acb4d01d5c65/api-specificatie/kcc/1.0.x/openapi.yaml)

Code wijzigingen hier: https://github.com/VNG-Realisatie/gemma-klantcontactcomponent/pull/7

**Comment by hdksi** [comment]
> Ik schaar de DSO attributen even onder issue: #1421 en werk in dit issue aan het toevoegen van een medewerker aan een verzoek.

Ik vraag me bij nader inzien af of dat koppelen van medewerker aan verzoek nodig is. Is daar een user story voor?

**Comment by joeribekker** [comment]
Eh ja, zo had ik deze US geinterpreteerd.

**Comment by hdksi** [comment]
Conclusie van vanmorgen: een verzoek is eenrichtingsverkeer. Een medewerker komt tijdens de afhandeling uiteraard in beeld, maar dan is naar aanleiding van het verzoek al een zaak (of iets anders op basis van een alternatief afhandelconcept) ontstaan. Een koppeling tussen medewerker en verzoek is dus niet nodig.

**Comment by joeribekker** [comment]
@HenriKorver en ik hebben dit issue bekeken en concluderen er zit gene medewerker op verzoek, en naar aanleiding van Ivo's laatste opmerking is dat dus ook niet de bedoeling.

Daarmee sluit ik dit ticket.
