### ISSUE TITLE
Als medewerker wil ik meerdere verzoeken kunnen koppelen aan dezelfde zaak

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1391]
...zodat dubbele of overeenkomende verzoeken in een zaak kunnen worden behandeld.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by EdwinCoster** [comment]
Deze user story heeft mogelijk consequenties voor het gegevensmodel.

**Comment by PDG65** [comment]
gerelateerd aan #1392

**Comment by joeribekker** [comment]
Dit kan nu via OBJECT-CONTACTMOMENT en OBJECT-VERZOEK, door er simpelweg meerdere aan te maken.

Zie: http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/kic/1.0.x/openapi.yaml#operation/objectcontactmoment_create

Voorbeeld:

```http
POST /api/v1/objectcontactmomenten
{
  "contactmoment": "https://klantinteractie-api.vng.cloud/api/v1/contactmomenten/a59d27",
  "object": "https://zaken-api.vng.cloud/api/v1/zaken/61a8f4",
  "objectType": "zaak"
}
```

**Comment by HenriKorver** [comment]
Ik zou verwachten dat het koppelen van verzoeken aan zaken (en vice versa) dient te geschieden via de `zaakverzoek` resource in de Zaken API.

```http
POST /api/v1/zaakverzoeken
{
  "zaak": "http://...",
  "verzoek": "http://..."
}
```

Zie http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/zrc/1.1.x/openapi.yaml#operation/zaakverzoek_create

**Comment by HenriKorver** [comment]
Met de Zaken API kun je al verzoeken koppelen aan een zaak via de resource `/zaakverzoeken` (dit wordt tevens in de achtergrond gesynchroniseerd met de Klantinteractie API via de resource `/objectverzoeken`)
