### ISSUE TITLE
Als medewerker wil ik meerdere zaken aan een verzoek kunnen koppelen

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1392]
...zodat verschillende onderdelen van het verzoek door meerdere medewerkers of afdelingen gelijktijdig kunnen worden behandeld.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Ik stel me voor dat burger van alles tegelijk kan vragen, en dat je voor een goede afhandeling meerdere zaken nodig hebt.

**Comment by hdksi** [comment]
Klinkt logisch, mee eens. Ik probeer te achterhalen wat deze US oplevert voor de organisatie of de klant. Voor de eerste denk ik efficiëntere behandeling, voor de tweede een snellere (complete) reactie bij zijn verzoek. De tekst hierop wat aangepast. Mee eens?

**Comment by EdwinCoster** [comment]
Deze user story heeft mogelijk consequenties voor het gegevensmodel.

**Comment by Hugo-ter-Doest** [comment]
Gespiegelde relatie. Zaak is leidend.

**Comment by joeribekker** [comment]
Gedaan in: https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/130

[Redo](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaakregistratiecomponent/608afa562bc497e2f4740a198db373e525ba2374/src/openapi.yaml)
