### ISSUE TITLE
Als burger wil ik de mogelijkheid hebben om een verzoek te ondersteunen met een document, foto of filmpje

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1393]
...zodat ik relevante informatie kan doorgeven aan de gemeente.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by hdksi** [comment]
Of dit kan is denk ik kanaalafhankelijk. Telefonisch lijkt dit me bijvoorbeeld lastig. Vraag is of we willen concluderen dat we geen telefonische aanvragen kunnen behandelen ómdat je langs dat kanaal geen aanvullende documentatie kan aanleveren.

Ik denk niet dat dat de bedoeling is. Daarom heb ik de US aangepast: kern is nu dat het 'mogelijk moet zijn' om een document, foto of filmpje toe te voegen. Ik kan me voorstellen dat die mogelijkheid gekoppeld is aan specifieke kanalen.

Gaat deze US ook over het aanleveren van aanvullende documentatie ná het moment van eerste aanvraag?

**Comment by EdwinCoster** [comment]
Deze user story heeft mogelijk consequenties voor het gegevensmodel.

**Comment by Hugo-ter-Doest** [comment]
De relatie tussen informatieobject en verzoek wordt gespiegeld opgeslagen zoals bij zaak en informatieobject.

**Comment by joeribekker** [comment]
Wijziging in Contactmomenten API: TODO

Wijziging in Documenten API: https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/pull/104

Wijziging in VNG-API-Common: https://github.com/VNG-Realisatie/vng-api-common/pull/115

**Comment by sergei-maertens** [comment]
@joeribekker ik zag hier nog geen branch voor in https://github.com/VNG-Realisatie/klantinteracties-api/branches dus ik pak hem op

**Comment by HenriKorver** [comment]
Zie  http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/kic/1.0.x/openapi.yaml#operation/verzoekinformatieobject_create

```http
POST  /verzoekinformatieobjecten
{
  "informatieobject": "http://example.com",
  "verzoek": "http://example.com"
}
```

Hiermee kun je een document, foto of een filmpje toevoegen aan een verzoek

**Comment by HenriKorver** [comment]
Wordt dus al ondersteunt door Klantinteractie API en kan gesloten worden
