### ISSUE TITLE
Als medewerker wil ik een of meerdere contactmomenten kunnen koppelen aan een verzoek

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1394]
...zodat communicatie over een verzoek kan worden geregistreerd incl. eventuele aanvullende afspraken.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by EdwinCoster** [comment]
Deze user story heeft mogelijk consequenties voor het gegevensmodel.

**Comment by Hugo-ter-Doest** [comment]
Er komt een vrije relatie tussen contact en verzoek. In eerste instantie wordt de relatie alleen bij Verzoek geregistreerd.

**Comment by HenriKorver** [comment]
Ik heb de resource `/verzoekcontactmomenten` met bijbehorende operaties toegevoegd aan de OAS van Klantinteracties API, zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/ea05a2aedd889a520ac59c7d23b6d5bbebd911ee/api-specificatie/kic/1.0.x/openapi.yaml#tag/verzoekcontactmomenten).

**Comment by HenriKorver** [comment]
De toegevoegde resource is gevisualiseerd in onderstaande screenshot:

![afbeelding](https://user-images.githubusercontent.com/37145898/76083508-16d18700-5fae-11ea-8b3c-59b0a3faaad7.png)

**Comment by HenriKorver** [comment]
De exacte verschillen met de master zijn hier te vinden: 

https://github.com/VNG-Realisatie/gemma-zaken/compare/HenriKorver-patch-3

**Comment by HenriKorver** [comment]
@joeribekker @sergei-maertens Klaar voor implementatie!

**Comment by joeribekker** [comment]
> @joeribekker @sergei-maertens Klaar voor implementatie!

Sergei zit niet meer in het team.

**Comment by joeribekker** [comment]
Fixed here: https://github.com/VNG-Realisatie/klantinteracties-api/pull/21

Zie: [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/klantinteracties-api/2ea5603e1290a580dc3c6ed66f25137fea616905/src/openapi.yaml)
