### ISSUE TITLE
Als architect wil ik weten hoe verzoeken zich tot een zaak verhouden

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1396]
zodat ik de userstories die over verzoeken gaan, goed kan beoordelen/snappen.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by EdwinCoster** [comment]
Zie ook #1331

**Comment by joeribekker** [comment]
@CMasselink is #1423 voldoende?

**Comment by CMasselink** [comment]
@joeribekker In combinatie met #1331 wel inderdaad.
Deze userstory sluiten of open laten staan totdat PR is goedgekeurd en #1331 is afgerond?

**Comment by PDG65** [comment]
keuze is gemaakt, plaatje aanpassen, verhaaltje erbij en reviewen

**Comment by Hugo-ter-Doest** [comment]
Belangrijkste vraag is wat je met een verzoek doet voordat het een zaak wordt. En ook of een verzoek een status heeft.

**Comment by hdksi** [comment]
Verder in #1331.
