### ISSUE TITLE
Als persoon wil ik bij de/een overheid een verzoek of melding kunnen indienen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#14]
Zodat 
Ik toestemming krijg voor aan activiteit 
Ik de/een overheid een activiteit kan laten uitvoeren voor mij
Ik iets kan laten weten aan de/een overheid

**Comment by michielverhoef** [comment]
Een verzoek of melding leidt tot een zaak wanneer deze in behandeling wordt genomen.

**Comment by jgortmaker1** [comment]
een melding rondom een activiteit wordt straks afgehandeld door DSO

Deze dus aub afvoeren

**Comment by TCIMEddy** [comment]
@ehotting Wat mij betreft wat te breed en close, maar dat laat ik aan jou over!
