### ISSUE TITLE
Afspraak Product Owner en opdrachtgever

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#140]
- Mandaat PO en ingehuurd vanuit rol VNG/CG
- budget (fixed)
- scope en productvisie 
- backlog
- betrokkenheid (mag overal bij zijn alleen moet hij zijn mond houden)

**Comment by ehotting** [comment]
Afspraak op 25 juni

**Comment by TCIMEddy** [comment]
Verstuurd vanaf mijn iPhone

**Comment by ehotting** [comment]
Structureel gepland
