### ISSUE TITLE
Als medewerker wil ik kunnen zien binnen welke termijn een verzoek moet worden beoordeeld

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1400]
...zodat ik aan de verwachting van de klant kan tegemoet komen.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by CMasselink** [comment]
Ik ben benieuwd hoe de termijn van een verzoek zich tot 'doorlooptijd' van een zaak/zaaktype verhoudt. 
Voor de klant zal het niet uitmaken of wij zijn/haar vraag als verzoek of zaak modelleren/beschouwen. 
Zit er een juridisch verschil tussen het in behandeling nemen van een verzoek en zaak? 
Als je bijvoorbeeld een vergunningsaanvraag niet op tijd behandeld hebt, moet je de vergunning vanuit rechtswege verlenen... Is de doorlooptijd dan de termijn van het verzoek + van de zaak?

Definitie van doorlooptijd bij een zaaktype:
De periode waarbinnen volgens wet- en regelgeving een ZAAK van het ZAAKTYPE afgerond dient te zijn, in kalenderdagen.

**Comment by hdksi** [comment]
Sluit niet aan bij #1423. Sluiten?

**Comment by ArjanKloosterboer** [comment]
Een doorlooptiijd gaat over dingen die tijd kosten, in dit geval de werkzaamheden die nodig zijn om invulling te geven aan het verzoek. Die werkzaamheden voeren we in een proces zaakgericht uit. Die doorlooptijd gaat dan dus over de zaak. De zaak is de 'productieband' die aan het einde het bestelde product oplevert. Met dat product wordt een antwoord gegeven op het verzoek. Van die productieband wil je weten hoe lang die aan moet staan.

**Comment by Hugo-ter-Doest** [comment]
Kan worden gesloten omdat we dit bij de zaak laten, en niet aan verzoek gaan toevoegen.

**Comment by Hugo-ter-Doest** [comment]
Er valt nog veel meer over te zeggen, maar dat is toekomstmuziek: SLA moet eigenlijk bij het product staan. Product legt de afspraak of belofte vast tussen klant en leverancier. De zaak waarmee een bepaald product kan worden geleverd houdt zich vervolgens aan de afgesproken termijnen.
