### ISSUE TITLE
Als initiatiefnemer wil ik melden dat ik een uitrit ga aanleggen 

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1401]
zodat ik voldoe aan wat mijn gemeente mij verplicht.

‘Initiatiefnemer’ is een Omgevingswetterm. Het is degene die iets wil veranderen in de fysieke leefomgeving: het initiatief. Die initiatiefnemer, in dit geval de melder, kan een burger of een (vertegenwoordiger van een) bedrijf zijn. Hij/zij heeft in het Omgevingsloket de vragenboom doorlopen waaruit bleek dat een melding ingediend moest worden. De melding gaat vergezeld van de vragen en antwoorden (van de vragenboom), een foto of situatieschets van de bestaande situatie en een situatieschets met de aan te leggen uitrit.  

_Deze Omgevingswet-user stories zijn afgeleid van de soorten verzoeken die in de STAM-standaard onderscheiden worden. Zie de STAM-standaard voor de van een verzoek aan de gemeente te verstrekken gegevens._ 

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by CMasselink** [comment]
Is een melding met de intentie om iets te gaan doen hetzelfde als een verzoek?

**Comment by hdksi** [comment]
Goeie vraag, dat ligt eraan hoe we 'verzoek' definiëren denk ik. Misschien iets voor de backlogrefinement 😃

**Comment by joeribekker** [comment]
Uit de visie:

> * Flexibeler (2): bij het indienen van een verzoek hoeft nog niet duidelijk te zijn hoe dat verzoek zal worden behandeld. [...] Dit betekent dus ook dat een verzoek op een niet-zaakgerichte manier kan worden afgehandeld!

> Vooralsnog onderscheiden we geen typen verzoeken. De relatie met producten uit de PDC is waarschijnlijk voldoende om de afhandeling te bepalen. 

Verzoek hoeft dus geen Zaak te worden, en we onderscheiden geen type, zoals in deze US "melding". Het is dus gewoon een Verzoek, klaar.
