### ISSUE TITLE
Als vertegenwoordiger van mijn buurman wil ik een aanvraag indienen voor een vergunning voor een aanbouw aan zijn woonhuis

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1402]
zodat hij zo snel mogelijk toestemming heeft om te kunnen gaan bouwen.

De buurman waarvan sprake is heeft iemand gemachtigd om namens hem een vergunningaanvraag in te dienen. Die aanvraag bevat onder meer het (adres van het) pand dat uitgebouwd gaat worden, een (ver)bouwtekening, de omschrijving van de werkzaamheden en de NAW-gegevens van de buurman en van de gemachtigde.

_Deze Omgevingswet-user stories zijn afgeleid van de soorten verzoeken die in de STAM-standaard onderscheiden worden. Zie de STAM-standaard voor de van een verzoek aan de gemeente te verstrekken gegevens._ 

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by joeribekker** [comment]
informatie over aanvrager en gemachtigde moet dus kunnen worden opgenomen.

**Comment by Hugo-ter-Doest** [comment]
Initiator en gemachtigde worden als attributen opgenomen bij verzoeken. Gemachtigde mag niet gevuld worden als initiator leeg is.

Initiator kan zowel persoon als bedrijf zijn. 

Gemachtigde kan ook een bewindvoerder zijn in dienst van een bedrijf. Hoe wordt dat gemodelleerd.

**Comment by PDG65** [comment]
Eerst verder uitwerken: 
- lichtgewicht oplossing
- consistent met andere API's (m.n. met Contactmomenten)

**Comment by joeribekker** [comment]
Verzoeken onderbrengen in Contactmomenten API?

![CIM Klantinteracties diagram 20191104](https://user-images.githubusercontent.com/96970/68589382-0a1fa500-048c-11ea-814c-f7efbc3ccc7c.png)

**Comment by Hugo-ter-Doest** [comment]
Zie ook #1540 gemachtigde bij contacten.

**Comment by Hugo-ter-Doest** [comment]
Ivo en Paul maken ready.

**Comment by Hugo-ter-Doest** [comment]
De bedoeling is om betrokkenen in een rol aan verzoek te koppelen, net als bij zaken.

**Comment by HenriKorver** [comment]
Aan de specificatie van de _Verzoeken API_ is de resource `klantverzoeken` toegevoegd waardoor meerdere klanten in verschillende rollen (`belanghebbende, initiator, mede-initiator`) aan een verzoek gerelateerd kunnen worden. Bovendien kan aangegeven worden of de klant een `gemachtigde `of een `machtiginggever` is.  Zie onderstaande screenshot of [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/gemma-zaken/master/api-specificatie/DESIGN/kic/verzoeken/openapi.yaml#operation/klantverzoek_create).

![afbeelding](https://user-images.githubusercontent.com/37145898/83495001-65ac9100-a4b7-11ea-989b-0b7cdeec4c7f.png)

**Comment by HenriKorver** [comment]
Implementatie akkoord

**Comment by HenriKorver** [comment]
Bijgewerkt in presentatie voor sprint-demo
