### ISSUE TITLE
Als indiener van een vergunningaanvraag wil ik aanvullende informatie op die aanvraag verstrekken

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1404]
zodat ik voldoe aan de vraag om die informatie van de gemeente.

De initiatiefnemer heeft een aanvraag voor een vergunning ingediend. Deze is in behandeling genomen door de gemeente. De behandelaar heeft geconstateerd dat meer informatie nodig is om de aanvraag te kunnen behandelen. Hij/zij heeft de aanvrager daarom verzocht. Die vertrekt de gevraagde informatie aan de gemeente. Het gaat veelal om documenten zoals een begroting, berekening, onderzoeksrapport of technische tekening. 

_Deze Omgevingswet-user stories zijn afgeleid van de soorten verzoeken die in de STAM-standaard onderscheiden worden. Zie de STAM-standaard voor de van een verzoek aan de gemeente te verstrekken gegevens._

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Het moment waarop de zaak wordt gestart is hierbij belangrijk. Is het uitvragen van aanvullende gegevens onderdeel van de zaakafhandeling of is het onderdeel van de verzoek. Team denkt dat inhoudelijke beoordeling van de stukken onderdeel is van de zaakafhandeling.

**Comment by CMasselink** [comment]
@Hugo-ter-Doest 

> Als een aanvulling op een verzoek dat in behandeling is, wordt gedaan, moet het aan zowel het verzoek als aan de zaak worden gekoppeld.
> 
> Verzoeken mag je in principe niet meer aanpassen als het eenmaal is ingediend.

De bovenste regel uit de quote klopt niet meer naar aanleiding van de opgestelde visie:

>Nadat een verzoek in behandeling is genomen, wordt het verzoek niet langer voor communicatie met klant gebruikt. Het verzoek is na in behandelingname of afwijzing niet meer te wijzigen

Op het moment dat een verzoek in behandeling is genomen, mag een verzoek niet meer gewijzigd worden.

**Comment by ArjanKloosterboer** [comment]
> Het moment waarop de zaak wordt gestart is hierbij belangrijk. Is het uitvragen van aanvullende gegevens onderdeel van de zaakafhandeling of is het onderdeel van de verzoek? Team denkt dat inhoudelijke beoordeling van de stukken onderdeel is van de zaakafhandeling.
De zaak wordt gestart bij ontvangst van het verzoek. Daar zit geen licht tussen! Tijdens het opstellen van een verzoek kan de verzoeker nog gegevens van dat verzoek wijzigen. Na indienen niet meer. De userstory gaat er over dat er daarna nog aanvullende info benodigd is. Dat is een aanvulling op het eerder ingediende verzoek en grijpt in op de zaak die n.a.v. dat verzoek in behandeling is genomen.
Essentie is dat niet ieder verzoek tot een nieuwe zaak leidt.

**Comment by hdksi** [comment]
Naar aanleiding van een gesprek met @HenriKorver, @ppcjansen en @andyverberne vorige week een interessante vraag. In het DSO kan je een verzoek intrekken of aanvullen.

Eerder was het idee (vanuit het DSO) dat een aanvulling een nieuw DSO-verzoeknummer zou krijgen, maar het idee is nu dat een aanvulling bij een eerder verzoek hetzelfde verzoeknummer houdt, maar dat daaraan een driecijferig volgnummer wordt toegevoegd; dit waarschijnlijk om het mogelijk maken de informatie rondom één verzoek bij elkaar te houden. Hoe vertalen we dit naar ZGW-verzoeken? Als aan elkaar gerelateerde verzoeken met eventuele volgnummers toegevoegd aan het originele DSO-verzoekenummers in `externeIdentificatie`?

**Comment by hdksi** [comment]
Dit issue (samen met #1405) meenemen bij bespreking informatiemodel Klantinteracties.

**Comment by HenriKorver** [comment]
Het aanvullen van een verzoek wordt in de OAS mogelijk gemaakt door de volgende twee attributen toe te voegen:
![afbeelding](https://user-images.githubusercontent.com/37145898/83280283-b2058180-a1d6-11ea-9259-2618ae602130.png)

Het tweede attribuut is niet noodzakelijk maar wordt automatisch gezet voor praktische redenen. Als je naar een verzoek kijkt wil je meteen kunnen zien of ie wel of niet is aangevuld.

Zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/gemma-zaken/master/api-specificatie/DESIGN/kic/verzoeken/openapi.yaml#operation/verzoek_create).

**Comment by HenriKorver** [comment]
In de implementatie is het veld `aangevuldeVerzoek` nullable gemaakt. Dit komt niet overeen met het ontwerp (zie boven). Bovendien mis ik de beschrijving van het veld `aanvullendeVerzoek`.

![afbeelding](https://user-images.githubusercontent.com/37145898/83748489-911faf00-a662-11ea-8641-f1fe3fc08e60.png)

**Comment by joeribekker** [comment]
Nullable zoals besproken. Hier moet wel min/max length toegevoegd worden.

Aanvullend verzoek idd nog een beschrijving.

**Comment by HenriKorver** [comment]
> Nullable zoals besproken. Hier moet wel min/max length toegevoegd worden.

Inderdaad: aan beide velden nullable toevoegen inclusief min/max length. Analoog aan hoe we dat in #1405 hebben afgesproken.

> Aanvullend verzoek idd nog een beschrijving

Ja, dat zou idd fijn zijn.

**Comment by stevenbal** [comment]
@joeribekker PR in verzoeken API: https://github.com/VNG-Realisatie/verzoeken-api/pull/5

**Comment by HenriKorver** [comment]
Akkoord
