### ISSUE TITLE
Als indiener van een vergunningaanvraag wil ik die aanvraag intrekken

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1405]
zodat ik niet hoef te betalen voor de leges van de behandeling.  

Een initiatiefnemer kan tot het inzicht komen dat wat hij/zij van plan was niet meer gewenst of haalbaar is. De daarvoor ingediende aanvraag hoeft dan niet meer behandeld te worden. Daartoe trekt hij/zij de aanvraag in. 

_Deze Omgevingswet-user stories zijn afgeleid van de soorten verzoeken die in de STAM-standaard onderscheiden worden. Zie de STAM-standaard voor de van een verzoek aan de gemeente te verstrekken gegevens._

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by hdksi** [comment]
@ArjanKloosterboer: hoe werkt dit in de STAM-standaard? Met een nieuw (tweede) verzoek tot intrekking van het eerder ingediende verzoek?

**Comment by joeribekker** [comment]
Vanuit eenvoud geredeneerd: Een indiener kan een overzicht van zijn verzoeken inzien. De indiener moet zijn verzoek gewoon kunnen "intrekken" (vlaggetje zetten die het verzoek "annuleert", of direct de status "geannuleerd")

Deze redenatie gaat wel uit van communicatie (of inzage) over het verzoek dat niet in de visie staat beschreven (#1423):

> Terugkoppeling naar de klant over voortgang gebeurt in termen van opgestarte zaken of andere activiteiten, dus niet in termen van het verzoek.

**Comment by ArjanKloosterboer** [comment]
In de STAM-standaard moet dit nog uitgewerkt worden (Ivo / hdski), meen ik. Hoe dan ook, het leidt tot een (intrekkings)verzoek dat refereert aan een eerder ingediend verzoek (de aanvraag). Het Omgevingsloket heeft geen kennis van zaken en dus ook geen zaakid's. Het doordenken van verzoeken kan wel 's leiden tot aanpassing van de visie (voortschrijdend inzicht, heel agile) op het door Joeri aangehaalde punt.

**Comment by Hugo-ter-Doest** [comment]
> Deze redenatie gaat wel uit van communicatie (of inzage) over het verzoek dat niet in de visie staat beschreven (#1423):

We hebben inderdaad gisteren gekozen voor een vluchtig verzoek dat niet wordt gebruikt voor de interactie. Zullen we dat herzien en het patroon van DSO volgen voor intrekken?

**Comment by ArjanKloosterboer** [comment]
Waar kan ik in #1423 vinden dat hiervoor gekozen zou zijn. Ik zie geen enkel inhoudelijk comment. Deeplink?

**Comment by hdksi** [comment]
https://github.com/VNG-Realisatie/gemma-zaken/pull/1423/commits/156f1132b3144097d5c2771997199f72431a2493

**Comment by hdksi** [comment]
Nu het hele document, in plaats van alleen de laatste wijzigingen:

https://github.com/VNG-Realisatie/gemma-zaken/blob/e28ee478f20f22b07fd8f583bbff18a1a108eece/docs/_content/standaard/verzoeken/index.md

**Comment by hdksi** [comment]
https://aandeslagmetdeomgevingswet.nl/publish/pages/162386/20191129_stam_v1_0.pdf.

Zie ook #1404: intrekken is in feite niets anders dan aanvullen met een ander attribuut 'Intrekken' in plaats van 'Aanvullen', en een vooraf bepaald volgnummer (999) in aanvulling op het verzoeknummer.

**Comment by HenriKorver** [comment]
Het kunnen intrekken van een verzoek is mogelijk gemaakt in de OAS door de volgende twee attributen toe te voegen:
![afbeelding](https://user-images.githubusercontent.com/37145898/83278921-9f8a4880-a1d4-11ea-962b-ad4c0721b7ab.png)

Het tweede automatisch gegenereerde attribuut `intrekkendeVerzoek` is strict genomen niet noodzakelijk maar wel praktisch. Immers het is erg handig als je van een verzoek kunt zien dat er een (ander) verzoek is om het in te trekken.

Zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/gemma-zaken/master/api-specificatie/DESIGN/kic/verzoeken/openapi.yaml#operation/verzoek_create).

**Comment by HenriKorver** [comment]
Implementatie komt nog niet helemaal overeen met de laatste versie van het ontwerp. Zie de verschillen tussen bovenstaande screenshot (ontwerp) en die hieronder (implementatie):

![afbeelding](https://user-images.githubusercontent.com/37145898/83746948-266d7400-a660-11ea-86e1-00095ecb6c8e.png)

In het ontwerp zijn de twee velden niet meer nullable. Bovendien zijn de beschrijvingen van de twee velden aangepast.

**Comment by joeribekker** [comment]
Hmm, maar [1....1000] impliceert een verplicht veld, want dan moet je minimaal 1 karakter opgeven. En dat lijkt me niet terecht.

Ik denk dat dit in het grotere geheel van hoe om te gaan met URLs. Ik denk zo:

`[1...1000] + Nullable` - Optioneel
`[1...1000]` - Verplicht

**Comment by HenriKorver** [comment]
Het veld is niet verplicht, je kunt het gewoon weglaten. Maar als je het het veld wilt meegeven in een request of response, dan moet het minimaal karakter bevatten.

**Comment by HenriKorver** [comment]
Dus nullable is hier inj mijn ogen niet noodzakelijk, maar ik ben geen tegenstander om het niet te gebruiken. Er zijn meerdere wegen die naar Rome leiden. Maar als we nullable gebruiken, dan ook graag bij het tweede veld (intrekkendeVerzoek). Mijn voorstel is als volgt:

![afbeelding](https://user-images.githubusercontent.com/37145898/83889097-036bbe80-a74b-11ea-9a0b-fa8dc27dd161.png)

**Comment by stevenbal** [comment]
@joeribekker zie PR in verzoeken API: https://github.com/VNG-Realisatie/verzoeken-api/pull/4

**Comment by HenriKorver** [comment]
Akkoord
