### ISSUE TITLE
Als inwoner van mijn gemeente wil ik een product of dienst bestellen ...

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#1415]
... zodat ik daarvan gebruik kan maken en/of omdat wet en regelgeving voorschrijft dat ik dat moet hebben voor hetgeen ik van plan ben.

De Verzoeken-API is voor min of meer hetzelfde bedoeld als het bestaande [koppelvlak StUF-EF](https://www.gemmaonline.nl/index.php/StUF-EF) oftewel e-Formulieren en zou dat moeten kunnen vervangen. StUF-EF ondersteunt allerlei typen verzoeken. Die kunnen gevat worden in drie user-story's waarvan dit er één is. Het betreft de volgende producten en diensten:

- Automatisch betalen (aanvragen of veranderen) 
- Bewijs van in leven zijn 
- Bijzondere Bijstand 
- Eigen verklaring rijbewijs 
- Evenement Vergunning 
- Grofvuil op laten halen 
- Integrale horecavergunning 
- Kopie van een OZB-aanslag, WOZ-beschikking of WOZ-taxatieverslag 
- Kwijtschelding 
- Langdurigheidstoeslag 
- Leerlingenvervoer 
- Marktplaatsvergunning
- Parkeervergunning 
- Reclameontheffing 
- Rioolaansluitingvergunning 
- Standplaatsvergunning 
- Subsidie (aanvragen) 
- Uittreksel/afschrift uit de burgerlijke stand 
- Uittreksel/afschrift uit de gemeentelijke basisadministratie (GBA) 
- Vergoeding chronisch zieken en gehandicapten 

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by melsk-r** [comment]
@ArjanKloosterboer: Ik zie hier een strakke lijst aan diensten. Ik vraag me af of er niet ook een voorziening moet zijn om een specifieke gemeentelijke behoefte in te kunnen vullen. Bijvoorbeeld voor het aanvragen van een (tijdelijke) ontheffing van een parkeerverbod.
Daarnaast moeten we er toch ook rekening mee houden dat de Verzoeken API ook bij andere overheden gebruikt kan worden.
Maar wellicht had je dat in je achterhoofd toen je _'min of meer'_ schreef.

**Comment by ArjanKloosterboer** [comment]
Klopt. De lijst is niet limitatief. Een kenmerk van een userstory is dat deze een specifieke situatie beschrijft. Maar dat is dus niet de hele waarheid. Voor andere specifieke situaties zijn er andere userstory's. Er moeten dus ook andere producten besteld kunnen worden dan alleen deze. Het eigenaardige aan de werkwijze is dan weer dat als die andere userstory's er niet zijn, dat we dan net doen alsof ze niet bestaan. Wat mij betreft denken we toch even verder. En moet met een verzoek onder meer een willekeurig product of dienst besteld kunnen worden. Waaronder, maar niet alleen, de hier genoemde.

**Comment by PDG65** [comment]
Gesloten. Gelijk aan https://github.com/VNG-Realisatie/gemma-zaken/issues/1386
