### ISSUE TITLE
Als inwoner van mijn gemeente wil ik iets melden ...

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#1416]
... zodat ik voldoe aan de wet en regelgeving die dat voorschrijft en/of de gemeente dit kan oppakken en/of omdat ik daar belang bij heb.

De Verzoeken-API is voor min of meer hetzelfde bedoeld als het bestaande [koppelvlak StUF-EF](https://www.gemmaonline.nl/index.php/StUF-EF) oftewel e-Formulieren en zou dat moeten kunnen vervangen. StUF-EF ondersteunt allerlei typen verzoeken. Die kunnen gevat worden in drie user-story's waarvan dit er één is. Het betreft de volgende typen meldingen:

- Evenement melden 
- Gevonden of verloren voorwerpen melden 
- Graafwerkzaamheden voor telecomkabels melden 
- Hond aan- of afmelden voor hondenbelasting 
- Melding woon- of leefomgeving doen 
- Schade na Ramp melden 
- Subsidiegebruik aantonen
- Vakantie of verblijf in het buitenland doorgeven 
- Verhuizing doorgeven 
- Vertrek buitenland doorgeven 

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
We hebben de indruk dat het onderscheid van verschillende soorten verzoeken niet ingewikkeld zijn, en dat je dit eenvoudig kunt ondervangen met een type verzoeken, en met relaties naar de PDC.

**Comment by ArjanKloosterboer** [comment]
Dat lijkt me een valide analyse. En dat is nou juist wat er moet gebeuren met al die userstory's: bekijken vanuit de blik van een informatie-analist. En dan de informatievoorziening zo structureren dat die eenduidig en stabiel is en beantwoord aan de behoeften van gebruikers zoals vervat in userstory's. Mooi vak!

**Comment by PDG65** [comment]
gesloten. reden: geen onderscheid tussen verzoeken en meldingen (geen type, maar er wordt verwezen naar de juiste entry in de PDC)
