### ISSUE TITLE
Als inwoner van mijn gemeente wil ik een verzoek indienen ...

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#1417]
... zodat mijn gemeente dat gaat doen waar ik belang bij heb.

De Verzoeken-API is voor min of meer hetzelfde bedoeld als het bestaande [koppelvlak StUF-EF](https://www.gemmaonline.nl/index.php/StUF-EF) oftewel e-Formulieren en zou dat moeten kunnen vervangen. StUF-EF ondersteunt allerlei typen verzoeken. Die kunnen gevat worden in drie user-story's waarvan dit er één is. Het betreft de volgende typen verzoeken 'om iets te gaan doen':

- Bezwaar indienen
- Verzoek tot geheimhouding persoonsgegevens indienen 
- Klacht indienen 
- Bouwgrondinschrijving doen
- Industrie- of bedrijventerrein inschrijven 
- Naamgebruik veranderen 
- Bezwaar tegen gemeentelijke belastingen
- Kenteken wijzigen 

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Een verzoek moet breed genoeg zijn om:
* product of dienst aan te vragen (uit de PDC van de gemeente)
* een melding te doen (bijv. een melding openbare ruimte)
* gegevens aan te leveren bij een reeds bestaand verzoek

**Comment by hdksi** [comment]
@ArjanKloosterboer: waarom maak je specifiek onderscheid tussen verzoeken (#1417), aanvragen van producten en diensten (#1415) en meldingen (#1415)? Heeft dat te maken met een verschil in aan te leveren gegevens?

**Comment by ArjanKloosterboer** [comment]
De drie door Hugo genoemde punten zijn een mooie analyse van de drie eFormulieren-userstory's. Met dien verstande dat er nog een vierde groep is, de groep die bedoeld is met deze userstory. Want een in te dienen bezwaar, is dat een product of dienst dat besteld wordt? Lijkt me van niet. Het product zou iets zijn als een uitspraak op een bezwaar. Maar wie bestelt dat? Is het dan een melding? Het valt niet te hopen dat de gemeente het zo opvat. Zijn het dan gegevens bij een bestaand verzoek? Nee dus. Vandaar, een restgroep aan dingen waarvan een burger iets van de overheid wil. 
Hierin ligt ook het antwoord verscholen op de vraag van Ivo (hdksi). Een userstory is opgezet vanuit de wereld van die user. Die dient geen verzoek in maar bestelt iets, meldt iets, wil iets. Dat wij dat allemaal als typen verzoek beschouwen, dat is onze analyse. Laten we oppassen die analyse al in de beschrijving van de userstory te stoppen. Daar is een mooi woord voor: jumping to conclusions. Oppassen geblazen!

**Comment by joeribekker** [comment]
We gebruiken deze US om de "Verzoeken API" op te zetten met een

* Toevoegen aan documentatie
* CI-setup
* API-docs/specs
* 1 resource: Verzoek, met het URL-attribuut
* Github opzetten

**Comment by joeribekker** [comment]
@Hugo-ter-Doest Hugo zei vlak voordat hij vertrok dat deze resource ook wel in de Contactmomenten API er bij mag :)

**Comment by Hugo-ter-Doest** [comment]
Uiteraard wel vanuit een idee over de samenhang van de entiteiten. En de API zal dan een andere naam moeten krijgen. Klantinteractie bijv.

**Comment by hdksi** [comment]
![afbeelding](https://user-images.githubusercontent.com/37660390/69066243-3f466d00-0a21-11ea-9f3b-a58f375a9b00.png)
'Andere klantinteractie' is op dit moment buiten scope, want niet gerelateerd aan user stories in de sprint.

**Comment by joeribekker** [comment]
Voor de toevoeging van een NNP heb ik een nieuw US gemaakt: https://github.com/VNG-Realisatie/gemma-zaken/issues/1468

**Comment by joeribekker** [comment]
Verder is deze US gerealiseerd in https://github.com/VNG-Realisatie/gemma-klantcontactcomponent/pull/9

Zie: [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-klantcontactcomponent/f7d0203023c029e55a40d10791918c070412d7f0/src/openapi.yaml)

**Comment by PDG65** [comment]
Gegevensmodel nog bijwerken
