### ISSUE TITLE
Als developer wil ik weten hoe het concept Verzoek zich verhoudt tot reeds bestaande concepten in ZGW 

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1420]
...zodat ik de Verzoeken API kan uitwerken met de benodigde attributen en relaties.

Inclusief uitleg van verschillende soorten verzoeken.
Inclusief de relatie met klant.

...met aandacht voor [vul aan]

**Comment by joeribekker** [comment]
Volgens mij is https://github.com/VNG-Realisatie/gemma-zaken/pull/1423/files de start van de invulling van deze US.

**Comment by ArjanKloosterboer** [comment]
> Inclusief de relatie met klant.

M.i. ook inclusief de relatie tot zaak, zaaktype, product- en diensttype en klantcontact.

**Comment by EdwinCoster** [comment]
Deze user story heeft mogelijk consequenties voor het gegevensmodel.

**Comment by PDG65** [comment]
plaatje, praatje en review

**Comment by Hugo-ter-Doest** [comment]
Wordt afgedekt door het visiestuk en door #1396

**Comment by hdksi** [comment]
Naar kijken in relatie tot #1716
