### ISSUE TITLE
Als gemeente wil ik dat DSO Verzoeken compatible zijn met ZGW Verzoeken

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1421]
...zodat ik DSO Verzoeken kan registreren in de ZGW API voor Verzoeken.

...met aandacht voor [vul aan]

**Comment by Hugo-ter-Doest** [comment]
Hoe ziet het DSO-verzoek eruit. Hoe moet het compatible zijn. Moet er een mapping komen?

**Comment by hdksi** [comment]
Dit is nog geen antwoord, maar uit de presentatie van Paul:

Het verzoek-element bevat de volgende elementen:
- Doel
- indienDatum
- Type verzoeknummer
- Volgnummer
- projectId
- Ambtshalve
- betreftUitvoeringVan(VZKPAC) 
- heeftAlsVerantwoordelijkeVoorBehandeling(VZKBGZ) 
- isIngediendDoor(VZKGEM) 
- isUitbesteedVoorBehandelingAan(VZKUIN) 
- isGedaanVoor(VZKPRO) 
- betreftUitvoeringOp(VZKPLO) 
- heeftAlsVerantwoordelijkeVoorIndienen(VKZINI)

**Comment by joeribekker** [comment]
@hdski Kan je aangeven wat die 2x3 letter afkortingen zijn, wat de attributen daarvan zijn (relatietypen) en welke objecttypen daarachter zitten (bij naam).

**Comment by hdksi** [comment]
I.v.m. dode link op Omgevingswet-site

[standaard_aanvragen_en_meldingen_stam_v0_9_12-09-2019-1.pdf](https://github.com/VNG-Realisatie/gemma-zaken/files/3804736/standaard_aanvragen_en_meldingen_stam_v0_9_12-09-2019-1.pdf)

**Comment by joeribekker** [comment]
@hdksi Kan jij aangeven wat er moet gebeuren op API-specificatie niveau en/of documentatie wat er concreet moet gebeuren?

**Comment by hdksi** [comment]
Arjan heeft voor het informatiemodel klantinteracties een cross-check gedaan met de DSO-attributen. De attributen die in dat model niet zijn opgenomen zijn specifiek voor het DSO, en moeten dus uitendelijk landen in een (domein)specifieke registratie.

Vanwege het gebrek aan een klantinteractie-resource zouden we de attributen voor zowel 'klantinteractie' als 'verzoek' bij ons 'verzoek' moeten opnemen. Deze staan hieronder.

**Objecttype klantinteractie**

Attribuutnaam | Definitie | Formaat | Card
-- | -- | -- | --
**Bronorganisatie** | De (identificatie van de) organisatie, zijnde een niet-natuurlijk   persoon, onder wiens verantwoordelijkheid de klantinteractie plaats   vindt. | N9 | 1
**Klantinteractienummer** | De unieke identificatie van een KLANTINTERACTIE binnen de organisatie   die de interactie met de klant uitvoert. | N8 | 1
Klantinteractietype | Aanduiding van de aard van de Klantinteractie. | klantinteractietype | 1
**Datum-tijd** | De datum en het tijdstip waarop de KLANTINTERACTIE begint | DT | 1
Kanaal | Het communicatiekanaal waarlangs de KLANTINTERACTIE gevoerd wordt | AN20 | 0 .. 1
_Contactpersoon klantinteractie_ : | De gegevens van de persoon, zijnde een medewerker van een   niet-natuurlijk persoon of vestiging, waarmee de KLANTINTERACTIE plaats   vond. |   | 0 .. 1
_Contactpersoonnaam_ | De opgemaakte naam van de contactpersoon. | AN40 | 1
_Contactpersoon functie_ | De aanduiding van de taken, rechten en plichten die de contactpersoon   heeft binnen de VESTIGING. | AN50 | 0 .. 1
_Contactpersoon emailadres_ | Elektronisch postadres waaronder de contactpersoon in de regel   bereikbaar is. | AN254 | 0 .. 1
_Contactpersoon telefoonnummer_ | Telefoonnummer waaronder de contactpersoon in de regel bereikbaar is. | AN20 | 0 .. 1

**_Plus_** **Objecttype Verzoek**

Attribuutnaam | Definitie | Formaat | Card
-- | -- | -- | --
**Extern verzoeknummer** | Het verzoeknummer zoals toegekend door de voorziening waar het VERZOEK   is ingediend. | AN | 0 .. 1
**Verzoekstatus** | De voortgang van afhandeling van het VERZOEK. | verzoekstatustype | 1

De attributen 'klantinteractietype' hebben we vanzelfsprekend niet nodig. 'Kanaal' is volgens mij alleen voor klantcontacten relevant. 

In **vet** de attributen die volgens mij relevant zijn. 'Extern verzoeknummer' is alleen relevant als we zo'n extern (bijvoorbeeld door het DSO gegeven) verzoeknummer _niet_ kunnen overnemen om dat verzoek intern te identificeren.

In _cursief_ de attributen die volgens mij ook relevant zijn, maar mogelijk conflicteren met een eerdere visie op 'klant'. Als je bij contact met een bedrijf de vestiging definieert als klant, dan zou je bij ieder klantcontact of verzoek een contactpersoon moeten vastleggen om te weten met wie je contact hebt gehad.

Als je daarentegen de combinatie van vestiging en contactpersoon definieert als klant, dan hoef je de gegevens van de contactpersoon uiteraard niet nogmaals vast te leggen bij het contactmoment of verzoek. Volgens mij hebben wij eerder deze laatste definitie gevolgd.

**Plaatje**
![afbeelding](https://user-images.githubusercontent.com/37660390/70243073-35876e00-1772-11ea-8280-9c35662343a1.png)
(Excuus voor de lage resolutie)

**Comment by joeribekker** [comment]
Mag ik uitgaan van het volgende:

**Objecttype Klantinteractie**

Attribuutnaam | Actie
-- | --
**Bronorganisatie** | Opnemen in `ContactMoment` en `Verzoek`
**Klantinteractienummer** | Ik zie geen reden waarom dit nodig is, maar als het voor DSO handig is, dan neem ik het op bij `ContactMoment` en `Verzoek`
**Datum-tijd** | Hebben we al maar heet `datumtijd` **WIJZIGEN?**
Kanaal | Hebben we al
_Contactpersoon klantinteractie_ | Opgenomen via `Klant` relatie
_Contactpersoonnaam_ | Zit min of meer in `Klant` (voornaam/achternaam) **WIJZIGEN?**
_Contactpersoon functie_ | Opnemen in `Klant`
_Contactpersoon emailadres_ | Zit in `Klant`
_Contactpersoon telefoonnummer_ | Zit in `Klant

**Objecttype Verzoek**

Attribuutnaam | Actie
-- | -- 
**Extern verzoeknummer** | Opnemen in `Verzoek`
**Verzoekstatus** | Opnemen in `Verzoek`

**Comment by hdksi** [comment]
Klantinteractienummer is volgens mij puur ter identificatie opgenomen. Hoewel we daarvoor al een UUID hebben, moeten we ook een mensleesbaar 'verzoeknummer' kunnen opnemen. Analoog aan zaken stel ik voor dit attribuut 'identificatie' te noemen.

Voor + achternaam van contactpersoon samenvoegen lijkt me niet zinvol.

**Comment by joeribekker** [comment]
Wellicht bedrijfsnaam bij klant opnemen, maar indien ja, is dat een nieuw US.

**Comment by joeribekker** [comment]
Done in https://github.com/VNG-Realisatie/klantinteracties-api/pull/17

Zie: [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/klantinteracties-api/473a679e9a5fee4d05ab68596f66f32693e53df6/src/openapi.yaml)

**Comment by hdksi** [comment]
@HenriKorver Missen we nu uiteindelijk toch interactiemoment/interactiedatum of zit ik naar de verkeerde spec te kijken?

http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/verzoeken-api/master/src/openapi.yaml.
