### ISSUE TITLE
Bij een zaak op het PIP moet kunnen worden aangegeven via welke url de zaak kan worden ingezien

### ISSUE THREAD

**Issue by erikdelepper** [VNG-Realisatie/gemma-zaken#1425]
Uitgangspunt hierbij is dat een gemeente verschillende PIP's kan hebben (geleverd bij specifieke procesapplicaties). Vanuit één centrale, generieke, PIP waarin alle zaken van de burger staan, zou je dus de zaak willen kunnen tonen in zijn specifieke PIP met zijn eigen functionaliteit.

**Comment by Hugo-ter-Doest** [comment]
Dit is mogelijk.
