### ISSUE TITLE
Als product owner wil ik dat de externe hygiene van de infra op orde is

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#143]
...zodat we er qua security e.d. netjes uit zien

**Definition of done**
- [x] DNSSEC actief op gebruikte domeinen
- [x] TLS volgens richtlijnen NCSC
- [x] https security headers volgens best practise
- [x] bereikbaar via IPv4 en IPv6

**Acceptatiecriteria**
- [x] 100% @ https://internet.nl/site/ 
- [x]  A+ @ https://www.ssllabs.com/ssltest/analyze.html
- [x]  A @ https://securityheaders.io/?followRedirects=on

**Taken**

**Comment by TCIMEddy** [comment]
lijkt me ready :-) 
![schermafbeelding 2018-06-25 om 11 22 02](https://user-images.githubusercontent.com/39735549/41842635-a64e1528-786b-11e8-98a3-73e19ec206ff.png)

**Comment by sergei-maertens** [comment]
@ehotting DKIM ontbreekt nog voor ref.tst.vng.cloud (https://internet.nl/mail/ref.tst.vng.cloud/130973/)

Rest is OK.

**Comment by ehotting** [comment]
Ik pas de Definition of Done aan omdat we (vooralsnog) helemaal geen mailserver actief hebben op dat domein. SPF met -all en een DMARC p=reject zijn prima, DKIM niet nodig.
