### ISSUE TITLE
Datum eindgeldigheid zaaktype moet zijn datum-tot maar gedraagt zich als datum-tot-en-met

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1431]
# Bug
Zaaktype.eindeGeldigheid is de datum tot wanneer een zaaktype geldig is. In de RI blijkt deze zich echter als een datum-tot-en-met.

In het ImZTC staat dit ook beschreven als datum-tot: https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/zaaktype.datum_einde_geldigheid_zaaktype

Zie ook: https://app.slack.com/client/TEKT3Q32Q/CEM4Q5N7R 

[beschrijf de bug]

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)

Welke claims/payload bevat je JWT?

**Comment by sergei-maertens** [comment]
Ik pak op
