### ISSUE TITLE
Als teamlid wil ik dat de Klantinteracties OAS in github staat

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1432]
...zodat ik daar de YAML kan vinden om een provider/consumer te bouwen.

Op dit moment ontbreekt de gegenereerde OAS in Github.

**Comment by Hugo-ter-Doest** [comment]
Klantinteracties API hangt nog in https://github.com/VNG-Realisatie/klantinteracties-api

**Comment by HenriKorver** [comment]
Begrijp de vraag van @sergei-maertens niet. Er staat toch een OAS voor klantinteracties in Github?

https://github.com/VNG-Realisatie/gemma-zaken/tree/master/api-specificatie/kic/1.0.x

Of is die niet in overeenstemming met die van de referentie-implementatie?

https://klantinteracties-api.vng.cloud/api/v1/schema/

**Comment by joeribekker** [comment]
Deze moet worden bijgwerkt met de versie in de klantinteracties api

**Comment by joeribekker** [comment]
Is gedaan via: https://github.com/VNG-Realisatie/gemma-zaken/pull/1581
