### ISSUE TITLE
Als teamlid wil ik dat de Klantinteracties API automatisch gedeployed wordt

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1433]
...zodat dit me geen tijd kost.

Er moet een initiële deployment plaatsvinden en de infrastructure-as-code moet toegevoegd worden. Daarnaast moet Travis ingericht worden zodat er automatisch gedeployed wordt bij succesvolle builds.

**Comment by michielverhoef** [comment]
Volgens mij is dit issue inmiddels ingehaald door de ontwikkelingen. Zo gebruiken we geen travis meer en bestaat de Klantinteracties API niet meer.
