### ISSUE TITLE
Als developer wil ik dat correct gedocumenteerd wordt hoe we omgaan met de begin en einddatum geldigheid bij een zaaktype

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1434]
zodat hier geen verwarring over ontstaat.
Is een datum "tot en met" of "tot".

**Comment by michielverhoef** [comment]
Dit is nauw verwant aan #1838. 

In [het commentaar](https://github.com/VNG-Realisatie/gemma-zaken/issues/1838#issuecomment-974241313) van @ArjanKloosterboer staat onder andere: 
_Elk objecttype kent in het ImZTC een 'Datum begin geldigheid' en 'Datum einde geldigheid'. Deze gaan over de geldigheid van een instantie; wanneer is die ontstaan en wanneer is die beeindigd. Zeg maar, de geboortedatum en de sterfdatum. Dus niet de datum waarop de wijziging van de waarde van een element van een instantie ingaat, zoals ik ergens meen te lezen._

Als we dit gaan toepassen moet de documentatie zo wie zo aangepast worden.

**Comment by michielverhoef** [comment]
Opgelost met #2038
