### ISSUE TITLE
Als PO wil ik dat Klanten API wordt hernoemd naar Contactmomenten API

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1435]
zodat deze API een naam heeft die aansluit op de functionaliteit.

**Comment by EdwinCoster** [comment]
Gegevensmodel: Contacten API wordt Contactmomenten API

**Comment by Hugo-ter-Doest** [comment]
API heet nu Klantinteracties API en bevat ContactMomenten en Verzoeken.
