### ISSUE TITLE
Opmerkingen uit de sprint review 4-11-19 Contactmomenten API

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1436]
Verbeteringen Contactmomenten API
- Betrokkene moet subject heten
- Documentatie attributen

**Comment by joeribekker** [comment]
Verwerkt in https://github.com/VNG-Realisatie/gemma-zaken/pull/1448

[Redoc Contactmomenten API](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/6cf823943b3704d96c537dc04f01acb4d01d5c65/api-specificatie/kcc/1.0.x/openapi.yaml)

Code wijzigingen hier: https://github.com/VNG-Realisatie/gemma-klantcontactcomponent/pull/6

**Comment by sergei-maertens** [comment]
Staat goed op https://contactmomenten-api.test.vng.cloud/api/v1/schema/#operation/klant_create
