### ISSUE TITLE
Als gemeente wil ik een standaard PDC API

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1439]
zodat ik vanuit andere API's zoals zaken en verzoeken naar een product resource kan verwijzen.

**Comment by rubenvdlinde** [comment]
Hey Constantijn, Hier zijn we in trouwen mee bezig en daar ligt een first draft bij Thijs. Lijkt me dan
 handig om hem dan niet ook in ZGW op te pakken.

**Comment by Hugo-ter-Doest** [comment]
Als VNG dit oppakt, moet ook de OpenWeb PDC worden bekeken.

Voor nu gaan we uit van een URL om naar een product te verwijzen, of identificerende gegevens zoals bij betrokkenen.

**Comment by michielverhoef** [comment]
De PDC API staat op de API Onwtikkelagenda: https://www.gemmaonline.nl/index.php/Ontwikkelagenda_API-standaarden 
Daarom sluit ik dit issue.
