### ISSUE TITLE
Organiseren intensieve week werken in Utrecht

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#144]
Een "ZDS Hackathon" zo je wilt.

- Scrum team werkt door, maar wel samen op locatie
- Parallel intensief input / feedback verzamelen met gebruikers van de standaard

**Comment by ehotting** [comment]
Oktober oid?

**Comment by Hugo-ter-Doest** [comment]
Mag best wel eerder wat mij betreft. Ik zou in zo'n week ook wat tijd willen hebben om meer diepgaande discussies te voeren. Bijv. die van gisteravond over hoger niveau API's/functionaliteiten.

Gr. Hugo

**Comment by jgortmaker1** [comment]
dit zijn 2 dingen.
intensieve week (wat geen hele week hoeft te zijn) is nuttig als er gebruikersfeedback of anderssoortige extra input is
een sessie om de architectuur te bespreken idd graag eerder. maar daarvoor is een dag eerst wel genoeg (of al teveel). Dan wat nadenken en afstemmen en daarna wellicht nog een keer een halve dag..

**Comment by TCIMEddy** [comment]
Inderdaad 2 zaken. aparte sessies om architectuur e.d. te bespreken (eigenlijk ready maken van de user stories sprint 2 e.v.) en hackaton om versnelling aan te brengen. a.s woensdag maken wie afspraken over discussies architectuur en ik zal een poll opstellen voor een hackaton om versnelling aan te brengen (ik ben hier overigens groot voorstander van maar wel eind oktober.)

**Comment by ehotting** [comment]
Dit leek een aardig plan maar gelet op de praktijk zie ik niet helemaal welke werkzaamheden ieder lid van het team kan uitvoeren tijdens een dergelijke week. Wat denk jij @TCIMEddy ?

**Comment by TCIMEddy** [comment]
@ehotting Ik blijf net als jij voorstander van dit soort initiatieven, zeker gezien productiviteit op maandagmiddag. Voor nu maar even op de backlog laten. Maar wellicht blijven er in november nog zaken open te staan die met select gezelschap op te lossen zijn. Wat mij betreft niet closen maar op de backlog houden

**Comment by TCIMEddy** [comment]
@ehotting wat mij betreft mag deze op close, gaat niet meer gebeuren en met API-lab goed alternatief
