### ISSUE TITLE
Als gemeente wil ik eenvoudig de producten waar een contactmoment betrekking op heeft kunnen ophalen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1440]
zodat ik dat kan gebruiken voor analyse doeleinden.

**Comment by EdwinCoster** [comment]
Deze user story heeft mogelijk consequenties voor het gegevensmodel.

**Comment by Hugo-ter-Doest** [comment]
Lijkt erop dat je vraagt om een attribuut heeftBetrokkingOp dat een lijst producten als waarde heeft. Klopt dat?

**Comment by CMasselink** [comment]
Ja dat klopt inderdaad.

**Comment by Hugo-ter-Doest** [comment]
Hiervoor kan het attribuut onderwerpLinks worden gebruikt. Is voor een of meerdere links naar productpagina's.
