### ISSUE TITLE
Als PO wil ik een verdieping op contactmomenten (onderdeel visie)

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1441]
zodat duidelijk is hoe contactmomenten gebruikt moeten worden.
.

**Comment by EdwinCoster** [comment]
2 vragen:
- Now what?
- Hebben we de US template overboord gegooid?

**Comment by EdwinCoster** [comment]
Deze user story heeft mogelijk consequenties voor het gegevensmode.

**Comment by joeribekker** [comment]
Zie ook: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/klantinteracties/index.md

Zie ook: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/themas/achtergronddocumentatie/verzoeken.md

**Comment by michielverhoef** [comment]
De bestaande documentatie doornemen en kijken:
* wat er nu al beschreven is
* hoe up to date / relevant het is 
* wat er nog aan ontbreekt

In het ideale geval ook de ontbrekende documentatie schrijven

**Comment by Hugo-ter-Doest** [comment]
Dit doen we in #1331
