### ISSUE TITLE
Als PO wil ik een demo van sprint 19 goed voorbereiden

### ISSUE THREAD

**Issue by PDG65** [VNG-Realisatie/gemma-zaken#1442]
**Onderwerpen:**
- Grote bestanden (toelichting constructie, voorbeelden) (Joeri, Sergei)
- Cachen (toelichting constructie, voorbeelden) (Joeri, Sergei)
- Contactmomenten (visie, inzicht gegevensmodel, api, versie) (Hugo, Edwin, Joeri, Sergei)
- Beheer (ZGW API testdomeinen, versies, major/minor, documentatie gesplitst aanbieden) (Robert, Michiel)
- Feedback uit de markt (?)

**Comment by melsk-r** [comment]
Moeten we niet ook aandacht besteden aan de roadmap?
