### ISSUE TITLE
Als gemeente wil ik een zinvolle naam/titel aan een catalogus kunnen geven

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1449]
...zodat ik snel kan zien wat het doel is van een catalogus, d.w.z. welk soort zaaktypen de catalogus bevat.
...met aandacht voor [vul aan]

**Comment by michielverhoef** [comment]
opgelost in Catalogi API 1.2:
https://catalogi-api.test.vng.cloud/api/v1/schema/#tag/catalogussen/operation/catalogus_create
