### ISSUE TITLE
Architectuur- en visie-discussies zijn lastig te voeren on-line

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#145]
# Impediment

Er zijn af en toe diepgaande discussies over visie en architectuur. De teamleden lijken impliciet verschillende ideeën over de oplossingsrichting te hebben. 

Die discussies zijn goed, maar deze zijn moeilijk te voeren en volgen on-line. Ik denk dat we daar wat tijd aan moeten besteden in fysieke meetings.

**Comment by TCIMEddy** [comment]
Er is in ieder geval 1 dag in de maand backlogrefinement en ruimte voor discussie. Overige discussies die ontstaan op dat moment regelen en beslissen.
