### ISSUE TITLE
Als beheerder van de API standaarden wil ik graag 2 major versies van de standaarden via de vng.cloud pagina's beschikbaar kunnen stellen

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1450]
...zodat we zoals gesteld in API Beheer tegelijkertijd twee major versies kunnen ondersteunen.
Een manier waarop dit zou kunnen is als volgt:

![Portal naar API specs](https://user-images.githubusercontent.com/20185784/68572448-b13d1600-0465-11ea-8643-ced3ebbb7474.jpg)

Of dit dan ook voor de blokken zoals o.a. 'Notificaties' en 'API Scopes' gevolgen heeft moet nog bepaald worden.

...met aandacht voor [vul aan]

**Comment by Hugo-ter-Doest** [comment]
Heeft ook devops aspect vanwege meerdere referentie-implementaties die draaien.

**Comment by michielverhoef** [comment]
Ik zou liever de OASsen van de verschillende versies via de github pages documentatie ontsluiten.
