### ISSUE TITLE
Als ontwikkelaar wil ik de `X-NLX-Logrecord-ID` doorsturen met elk API-verzoek

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1453]
...zodat ik de logs van verschillende systemen aan elkaar kan knopen. Dit dient dus ook opgeslagen te worden in de auditlog.

Komt voort uit discussie bij #1428

**Comment by rubenvdlinde** [comment]
Of iets gedetailleerder wellicht:, Als ontwikkelaar wil ik de NL-X-Headers die ik ontvang koppelen aan mijn eigen logs zodat ik systemen aan elkaar kan knopen (er komt meer binnen dan `X-NLX-Logrecord-ID` ;).

**Comment by stevenbal** [comment]
@joeribekker PR in vng-api-common https://github.com/VNG-Realisatie/vng-api-common/pull/150

**Comment by michielverhoef** [comment]
reeds opgelost

**Comment by basretera** [comment]
Als X-NLX-Logrecord-ID bedoeld is voor het tracen van berichten door het hele netwerk heen, waarom is deze header info niet toegevoegd op alle requests?
