### ISSUE TITLE
Sprints 4 weken ipv maand

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#146]
Lijkt me goed de sprints idd 4 weken te laten zijn zoals afgesproken. Demo's staan nu om de maand. Daardoor duren alle sprints iets langer dan vier weken, verliezen we een sprting en ontstaat scheefgroei met de derde donderdagen. Graag heroverwegen en evt. demo's opnieuw plannen.

**Comment by TCIMEddy** [comment]
Ok ik zet het op de agenda van woensdag en vermeld dat maandelijkse sprint verkeerde aanname van mij was.
