### ISSUE TITLE
Als ontwikkelaar wil ik weten waar de Contactmomenten API voor gebruikt wordt

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1461]
...zodat ik deze goed kan plaatsen in het gegevenslandschap.

Zie: https://github.com/VNG-Realisatie/gemma-zaken/pull/1448/files#r345808573

**Comment by Hugo-ter-Doest** [comment]
Vgm is dit inmiddels wel duidelijk?
