### ISSUE TITLE
Als ontwikkelaar wil ik informatie over het synchroniseren van zaakcontactmomenten

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1462]
...zodat ik dit goed inbouwen.

Zie: https://github.com/VNG-Realisatie/gemma-zaken/pull/1448/files#r345808805

**Comment by Hugo-ter-Doest** [comment]
@joeribekker is deze vraag nog actueel?

**Comment by Hugo-ter-Doest** [comment]
Deze relatie wordt gespiegeld zoals bij zaakinformatieobjecten.
