### ISSUE TITLE
Status aanmaken met bestaande combinatie zaak_id en datum_status_gezet geeft internal server error

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#1465]
# Bug

Het aanmaken van een `Status` in het ZRC met een combinatie van `Zaak` en `Status.datum_status_gezet die al bestaat geeft een internal server error
```json
django.db.utils.IntegrityError: duplicate key value violates unique constraint "datamodel_status_zaak_id_datum_status_gezet_72963ee8_uniq"
DETAIL:  Key (zaak_id, datum_status_gezet)=(3, 2019-01-01 12:00:00+00) already exists.
```

Op deze combinatie van velden moet een `UniqueTogetherValidator`, zodat er een HTTP 400 teruggegeven wordt met de juiste error code

**Comment by sergei-maertens** [comment]
Merged & is going through CI
