### ISSUE TITLE
Als Niet-Natuurlijk Persoon wil ik ook een verzoek kunnen indienen in de  Verzoeken API

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1468]
...zodat [...]

*Placeholder tekst voor daadwerkelijke use case*

- to be or not be.
- to do or not to do.

**Comment by Hugo-ter-Doest** [comment]
Wordt opgelost analoog aan relatie Zaken-Niet natuurlijke persoon,

**Comment by hdksi** [comment]
Klant moet gekoppeld kunnen worden aan NNP zoals nu reeds mogelijk voor NP en vestiging.

**Comment by HenriKorver** [comment]
Aanpassingen aan de OAS:
- Bij het subjectType van een Klant `niet_natuurlijk_persoon` aan de enumeratie toegevoegd. 

- Discriminator uitgebreid met deze nieuwe waarde 

- Property subjectIdentificatie gegevens toegevoegd voor `niet_natuurlijk_persoon`

Zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/HenriKorver-patch-4/api-specificatie/kic/1.0.x/openapi.yaml#operation/klant_create).

De exacte verschillen zijn hier te vinden:
https://github.com/VNG-Realisatie/gemma-zaken/compare/HenriKorver-patch-4

**Comment by HenriKorver** [comment]
@joeribekker @sergei-maertens Klaar voor implementatie

**Comment by joeribekker** [comment]
Fixed here: https://github.com/VNG-Realisatie/klantinteracties-api/pull/22

Zie: [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/klantinteracties-api/2ea5603e1290a580dc3c6ed66f25137fea616905/src/openapi.yaml)
