### ISSUE TITLE
Als gemeente wil ik vanuit een besluit kunnen verwijzen naar de bekendmaking op officielebekendmakingen.nl (of een andere site in de toekomst) 

### ISSUE THREAD

**Issue by AHNRoxit** [VNG-Realisatie/gemma-zaken#1474]
Zou een besluit in de BRC niet ook een relatie naar de digitale publicatie van dat besluit op officiëlebekendmakingen moeten hebben? In plaats van alleen de publicatiedatum en de uiterlijkeReactiedatum?

**Comment by Hugo-ter-Doest** [comment]
@AHNRoxit Je kunt meerdere besluitdocumenten toevoegen aan de een besluit. In de toelichting kun je aangeven dat het om een gepubliceerd document gaat. Is dat voldoende? Of wil je een document specifiek als gepubliceerd document aanmerken?

**Comment by AHNRoxit** [comment]
Hoi @Hugo-ter-Doest. Dat lijkt mij iets anders. Het ging er mij om of de _bekendmaking_ van het besluit op officiëlebekendmakingen niet als gerelateerd object zou moeten kunnen worden toegevoegd aan het besluit in de BRC. Dat zou kunnen via de zogenaamde 'permanente link' naar de publicatie (bijvoorbeeld https://zoek.officielebekendmakingen.nl/gmb-2020-61427.html) kan worden toegevoegd aan het besluit. 
Dat is iets anders dan de vraag of bij een document dat is gerelateerd aan het besluit moet worden toegevoegd of het een gepubliceerd document is.

**Comment by Hugo-ter-Doest** [comment]
We stellen dan voor een attribuut aan besluit toe te voegen voor bekendmaking, type is URI.

**Comment by AHNRoxit** [comment]
Hoi @Hugo-ter-Doest. Klinkt goed! Het lijkt mij wel zo handig om deze relatie gemakkelijk te kunnen herkennen.

**Comment by Hugo-ter-Doest** [comment]
@AHNRoxit er is voortschrijdend inzicht in het team: we hebben gezien dat het hergebruik van de besluit-informatieobject wat problemen met zich meebrengt:
- officiele bekendmakingen zijn geen informatieobjecten zoals bedoeld in het RGBZ
- we moeten allerlei gedrag voor de relatie tussen besluiten en informatieobjecten aanpassen als het een officiele bekendmaking is.

Zie #1566 voor de user story met de aanpassing met een attribuut op besluit.
