### ISSUE TITLE
Als PO wil ik dat er een betere naam wordt bepaald voor de Contactmomenten API

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1480]
...zodat developers begrijpen wat de inhoud van de API is.

--> Klantinteracties is de nieuwe naam

Omdat Verzoeken resource is toegevoegd aan de Contactmomenten API dekt deze naam de lading niet meer.

Denk aan Klantinteractie(s) als mogelijke naam.

**Comment by EdwinCoster** [comment]
Deze US heeft consequenties voor het gegevensmodel.

KIC en KIA klinken wat mij betreft prima.

**Comment by PDG65** [comment]
- naam bepalen (Klantinteracties?)
- naam doorvoeren
