### ISSUE TITLE
Als gemeente wil ik een sessie samen met het ZGW team om de werking en design keuzes rond notificaties te bespreken

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1481]
zodat ik een beter begrip heb van hoe het component werkt.

**Comment by PDG65** [comment]
- voorbereiding (ism Joeri en Sergei)
- overleg van 1,5 uur

**Comment by PDG65** [comment]
Sessie is gedaan.

**Samengevat:**
- we kunnen GitHub blijven gebruiken voor discussies, maar opletten dat deze binnen de perken blijven en wanneer nodig overschakelen naar een off-line sessie zoals deze.
- demo en uitleg Notificatie oplossing team ZGW API's (Joeri en Sergei)
- vragenronde 
- Hugo voert User stories die vanuit deze sessie naar voren komen binnen GitHub op.

**Aandachtspunten:**
- SSL afdwingen bij registratie abonnement
- Uniformering Notificatie functionaliteit over alle API development projecten heen. Q1-2020 komt een architectuurplaat vanuit het project dat de overheidsbrede Notificatie ontwikkelt.
- Data bij de bron maximaal doorvoeren (dus geen kenmerken meegeven naar de abonnee). Veroorzaakt ook volledige logging van Get acties. Bij voorkeur informatie-loos ipv informatie-arm.
- Hervalideren van autorisatie abonnee bij versturen notificaties
- PubSub naar WebSub is geen naamsverandering, maar bevat andere structuur (doorontwikkeling voor Rest API's). De verschillen lijken nu echter minimaal, omdat er in lijn met WebSub is ontwikkelt. Daar met z'n allen nog eens naar kijken vanuit het project dat de overheidsbrede Notificatie ontwikkelt.
- Gemma compliance
- Audit trail
- NLX issue oplossen (header uit API verwijderen). Zorgen dat het met NLX te gebruiken is. 
- Documentatiepuntjes (worden offline afgestemd)

**Comment by Hugo-ter-Doest** [comment]
Zoals afgesproken drie user stories opgevoerd.

**Comment by sergei-maertens** [comment]
@PDG65 kan volgens mij gesloten worden aangezien de sessie gehouden is en er nieuwe US uit voortgekomen zijn?

**Comment by PDG65** [comment]
@sergei-maertens wat mij betreft geen probleem
