### ISSUE TITLE
Als Beheerder van de standaard wil ik uitleg over allerlei werkzaamheden die ik uit moet kunnen voeren

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1482]
...zodat ik, als dat noodzakelijk is, deze werkzaamheden zelf uit kan voeren of uit kan laten voeren door anderen.

Denk daarbij aan de volgende activiteiten:
* Ik wil graag een totaalplaatje van alle componenten die komen kijken bij het beheer en genereren van de diverse producten;
* Hoe genereren we een yaml bestand uit de code van de RI?
* De werking van de generatiescripts die ‘https://zaakgerichtwerken.vng.cloud’ genereren moet duidelijk zijn;
* De generatiescripts moeten er op berekend zijn dat we op de vng.cloud webpagina’s ook nieuwe en meerdere versies van de standaarden kunnen plaatsen;
* Het moet voor ons helder zijn hoe deze generatiescripts precies werken en hoe we deze kunnen controleren en/of aanpassen;
* Het moet ons duidelijk zijn hoe we een verlopen versie van de standaard uit de vng.cloud omgeving kunnen verwijderen en hoe we er voor kunnen zorgen dat die betreffende versie niet meer opnieuw gegenereerd wordt;
* Hoe worden de links die in GitHub worden geplaatst vertaalt naar de links in https://zaakgerichtwerken.vng.cloud. Hoe worden bijv. links als ‘[Catalogi API specificatie](catalogi/index)’ in ‘https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/docs/_content/standaard/index.md’ vertaalt naar de links in ‘https://zaakgerichtwerken.vng.cloud/standaard/’;
* Het moet voor ons duidelijk zijn hoe het genereren van de docker containers werkt;
* Het moet voor ons duidelijk zijn hoe we het genereren van de docker containers kunnen opstarten;
* Hoe werkt de creatie van een Changelog.rst? Ik vermoed dat het handmatigs is;
* Zijn er werkzaamheden die verricht worden t.b.v. de uitrol van de standaarden op de ATP of worden die werkzaamheden verricht vanuit het team van de ATP?

Eigenlijk zou ik graag zien dat alle API’s die bij VNG-R in beheer komen op eenzelfde wijze worden gepubliceerd. Dat kan op de wijze waarop we dat nu doen voor de ZGW API’s maar dat mag ook op een andere wijze zolang de functionaliteit maar bewaard blijft.
Indien we kiezen voor de huidige wijze is het de vraag hoe we dat voor andere API’s kunnen realiseren.

...met aandacht voor [vul aan]

**Comment by Hugo-ter-Doest** [comment]
@michielverhoef is deze kennis inmiddels overgedragen aan jou?

**Comment by michielverhoef** [comment]
@Hugo-ter-Doest Nope, nog niet. 
Een deel van de genoemde punten is (voorlopig) niet meer van toepassing, de kennisoverdracht van de referentieimplementaties moet nog gebeuren (de afspraak is indertijd verschoven).

**Comment by Hugo-ter-Doest** [comment]
@michielverhoef loopt door de lijst en checked of er al user stories van zijn, of maakt nieuwe aan indien nodig en linked deze.

**Comment by Hugo-ter-Doest** [comment]
Werkzaamheden zijn inmiddels duidelijk.
