### ISSUE TITLE
Als beheerder van een ZTC wil ik voor elke resource waarop een POST operation is gedefinieerd ook een DELETE operation hebben

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1485]
...zodat ik foutief aangemaakte ZTC componenten kan verwijderen.

De vraag is of dit ook niet voor de andere registratiecomponenten gewenst is.
Misschien geldt zelfs wel dat je voor alle resources waarvoor een post operation beschikbaar is ook een delete operation beschikbaar gesteld moet worden.

...met aandacht voor [vul aan]

**Comment by michielverhoef** [comment]
Op dit moment bestaat er geen DELETE  voor Catalogussen maar die kan eventueel via de beheerinterface verwijderd worden.
