### ISSUE TITLE
Als ontwikkelaar wil ik dat mogelijke foutresponses beschreven staan in de standaard

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1496]
...zodat ik altijd weet welke responses ik kan verwachten.

Op dit moment is 'title' en 'detail' nog vrij te bepalen. Voor 'detail' is dat vermoedelijk prima aangezien daarmee een zo specifiek mogelijke melding gegenereerd kan worden. Voor 'title' is een standaard melding echter wel handig zodat het bericht herkenbaarder wordt.

**Comment by HenriKorver** [comment]
Goed punt. Dit is ook handig voor het schrijven van scherpere testscripts.

**Comment by HenriKorver** [comment]
Nu lopen we het risico dat andere implementaties van de ZGW API's (Open-Zaak, Gemeente-Zaak, etc.) error-handling op een andere manier gaan realiseren

**Comment by michielverhoef** [comment]
Hier zijn nog geen vragen over geweest dus ik ga er van uit dat standaard http codes voldoende zijn.
