### ISSUE TITLE
De referentieimplementatie laat op dit moment toe dat nieuwe documenten aan een gearchiveerde zaak gekoppeld worden

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1498]
# Bug

Na het archiveren van een zaak is deze in principe immutable, het zou dus door (reguliere) users niet mogelijk mogen zijn om nieuwe documenten te relateren aan deze zaken.

Check:
- [ ] Documenten koppelen
- [ ] Nieuwe statussen zetten
- [ ] ???

**Comment by michielverhoef** [comment]
@sergei-maertens Voor de zekerheid: Dit gaat niet over afgehandelde zaken maar echt over gearchiveerde zaken?

**Comment by sergei-maertens** [comment]
Ik gok van wel aangezien ik het expliciet in de issue omschrijving opgenomen heb :-)

Gaat dan om gesloten zaken die of blijvend bewaard moeten worden, of de archiefactiedatum is nog niet aangebroken.

**Comment by michielverhoef** [comment]
Zo te zien moet er een controle komen bij het koppelen van documenten, zetten van een nieuwe status etc. of de zaak al gearchiveerd is.

**Comment by michielverhoef** [comment]
@michielverhoef beschrijven hoe afgeleid kan worden hoe een zaak gearchiveerd is.
