### ISSUE TITLE
ZTC referentieimplementatie toont niet alle resultaattypen inline

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1499]
Ondanks dat je meerdere resultaattypen hebt, zie je slechts 1 resultaattype in de zaaktype detail pagina in de admin.

-> Oorzaak is rename van model field met link-generatie/inline generatie die niet mee ging

**Comment by michielverhoef** [comment]
Probleem lijkt opgelost, ik zie nu in ieder geval meer dan 1 resultaatype.
