### ISSUE TITLE
Als behandelaar wil ik dat zaakgegevens die ik in mijn vakapplicatie toegevoegd heb, inzichtelijk zijn via het zaaksysteem

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#15]
zodat anderen hiervan kennis kunnen nemen zonder dat zij toegang moeten hebben tot de vakapplicatie

**Comment by TCIMEddy** [comment]
@ehotting Is volgens mij een duplicaten van meerder user stories.

**Comment by ehotting** [comment]
Idd, dit is essentie van de API's - dubbel  (maar wel eerder  ;) )
