### ISSUE TITLE
Als teamlid/gemeente wil ik een format voor het aanleveren van velden bij user stories

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#150]
...zodat het team mijn userstories soepel kan verwerken.

Concreet: Gemeenten ldie input leveren op basis waarvan ZDS 2.0 wordt gemaakt leveren concrete functionele wensen in de vorm van user stories, geformuleerd vanuit gezichtspunt eindgebruikers. De realisatie van de user story krijgt vorm in de gemeente zelf, in een app of anderszins. De randvoorwaarden qua API calls zijn wat in het ZDS 2.0 moet worden ingevuld. Daarvoor is het nodig om een vertaling te hebben van functionele wens naar een rijtje uit te wisselen velden.

Dit gaat nog heel veel gebeuren, daarom is een format nodig wat ingevuld kan worden. Daardoor:
- [ ] Weten gemeenten precies wat aangeleverd moet worden
- [ ] Kunnen developers de aangeleverde user stories beter en zonder verdere interactie verwerken

_Wanneer dit format er is kan het ook toegepast worden in andere trajecten._

**Definition of done**

- [ ] er is een format voor aanleveren uit te wisselen velden bij een user story

**Acceptatiecriteria**

- [ ] Mapping op RGBZ 2.0 helder zichtbaar in format
- [ ] Akkoord van developers die input moeten verwerken

**Taken**
- [ ] Opstellen format [_verantwoordelijke_]
- [ ] Bijwerken alle relevante acceptatiecriteria in reeds bestaande userstories [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
Zouden de vertegenwoordigers onderling 1 format willen kiezen en delen. Of is dit iets te gemakkelijk via deze weg?

**Comment by ehotting** [comment]
Dat is te makkelijk, denk ik tenzij @sergei-maertens al happy is met iets wat tot nu toe aangeleverd is

**Comment by sergei-maertens** [comment]
Laat ik het actieve US #39 dan als voorbeeld aangeven: https://github.com/VNG-Realisatie/gemma-zaken/issues/39#issuecomment-395697107

Een comment op github met de mapping van domeindata naar hoe dit in RGBZ past, in markdown is ideaal. De comment eronder heeft ook de voorbeelddata als json (maar dat kan ook XML zijn als dat nu net is wat jullie gebruiken).

Mijn voorkeur gaat in ieder geval uit naar binaire formaten vermijden (pdf, docx, xlsx...). Het is lastig om de meest recente versie van deze documenten te raadplegen (bijlage downloaden om te kijken of het gewijzigd is...) en als developer is 'platte tekst' een stuk prettiger omdat ik geen extra schermen met een PDF viewer/LibreOffice moet naast me hebben.

**Comment by ehotting** [comment]
Zoiets? https://github.com/VNG-Realisatie/gemma-zaken/blob/84a04a1427c8636609285382b951b958f5059368/.github/ISSUE_TEMPLATE/us-rgbz-mapping.md

**Comment by ehotting** [comment]
Voorlopig: Lever aan door een nieuw issue te maken: 
https://github.com/VNG-Realisatie/gemma-zaken/issues/new/choose

- [ ] Kies voor de template 'RGBZ-mapping US xx'
- [ ] Geef als titel 'RGBZ-mapping US #{nummer user story}'
- [ ] Vervang de voorbeeldregels
- [ ] Breid uit door lege regels te kopiëren / plakken

**Comment by RvdKlip** [comment]
De bedenker van een functionele wens/user story is soms niet in staat om de vertaling te maken naar het rijtje uit te wisselen velden (ik spiegel gemakshalve mijn eigen tekortkomingen).  

Het vertalen van functionele specificaties naar 
- velden in de interface en aanvullende velden die op de achtergrond meegegeven behoren te worden
- velden in termen van informatiemodellen
- velden in termen van de feitelijk berichtspecificaties (request - answer)
- velden in de daadwerkelijke gegevenslaag
... is een kunst op zich. 

Het lijkt me handig een US indiener hierbij actief te helpen door een systeemontwikkelaar vanuit het scrumteam of VNG.

**Comment by TCIMEddy** [comment]
Volgens mij is deze idd ready for sprint
![schermafbeelding 2018-06-25 om 11 22 02](https://user-images.githubusercontent.com/39735549/41842406-fd9c6fc4-786a-11e8-942d-3aa6b77bdc6d.png)
