### ISSUE TITLE
Als gemeente wil ik dat Verzoeken en ContactMomenten API's een audit trail kijgt...

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#1513]
...zodat teruggelezen kan worden wat er met een verzoek is gebeurd.

**Comment by HenriKorver** [comment]
Aan verzoeken resource de volgende operaties toegevoegd:
*  GET /verzoeken/{verzoek_uuid}/audittrail
*  GET /verzoeken/{verzoek_uuid}/audittrail/{uuid}

Aan contactmomenten resource de volgende operaties toegevoegd:
* GET /contactmomenten/{contactmoment_uuid}/audittrail
* GET /contactmomenten/{contactmoment_uuid}/audittrail/{uuid}

Aan het schema toegevoegd (gekopieerd uit Zaken API):
* AuditTrail
* Wijzigingen

Zie ook [Redoc ](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/HenriKorver-kic-1-0-x-1513-audittrail/api-specificatie/kic/1.0.x/openapi.yaml#operation/audittrail_list).

Uiteindelijk moeten we de schemadefinities die hergebruikt worden over de verschillende ZGW API's niet meer kopiëren maar delen via een gemeenschappelijke OAS-file door links te gebruiken. Ik zal hiervoor een US indienen.

**Comment by joeribekker** [comment]
@Hugo-ter-Doest Ik heb dit ticket even met @HenriKorver en intern met @sergei-maertens en @stevenbal besproken.

Het is niet triviaal om audittrail toe te voegen aan de API in zijn huidige vorm. Dit komt omdat de er 2 audit trails zijn gedesigned: 1 op Verzoeken, en 1 op Contactmomenten. Echter, we hebben de gedeelde resource Klant. Dit geeft 2 complexiteiten:

1) Als een Klant wordt aangemaakt zonder verder iets, dan is hier geen audittrail van.
2) Als een Contactmoment wordt aangemaakt en gelinked wordt aan een Klant, dan moet opeens de Klant aanmaak actie in de audit trail van Contactmoment terecht komen. Was hij echter gekoppeld aan Verzoek, dan komt hij bij Verzoeken audit trail terecht.

Er zijn wel oplossingen voor maar kost relatief veel tijd. @HenriKorver en ik denk dat we beter op features kunnen focussen en de API in het grotere plaatje dan op de audit trail nu, pending architecturele wijzigingen.

**Comment by HenriKorver** [comment]
Inmiddels is de Klantinteracties API opgesplitst in drie aparte API's:

- Klanten API
- [Contactmomenten API](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/gemma-zaken/master/api-specificatie/DESIGN/kic/contactmomenten/openapi.yaml#operation/audittrail_list)
- [Verzoeken API](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/gemma-zaken/master/api-specificatie/DESIGN/kic/verzoeken/openapi.yaml#operation/audittrail_list)

Hierdoor is het makkelijker geworden om audittrail te implementeren in de referentie-implementatie.

Audittrail wordt alleen bijgehouden voor contactmomenten en verzoeken (niet voor klanten). De specificaties voor audittrail kunnen bekeken worden door de twee bovenstaande links te volgen.

**Comment by HenriKorver** [comment]
Implementatie akkoord
