### ISSUE TITLE
Als gemeente wil ik dat notificaties die naar abonnees worden gestuurd informatieloos zijn

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1521]
...zodat 
1. er nooit door verkeerde inrichting van kenmerken privacygevoelige gegevens kunnen lekken
2. de consumer altijd een GET moet doen om de gewijzigde gegevens te kunnen bekijken. Hierdoor ontstaat er logging in NLX van de gebruikte gegevens. Voor AVG is dit belangrijk.

Deze user story komt voort uit de werksessie over notificaties van 9 december. Zie issue #1481 voor verslaglegging.

**Comment by joeribekker** [comment]
Het gaat om de berichten zoals hier gespecificeerd: https://notificaties.test.openzaak.nl/api/v1/schema/#operation/notificaties_create

Het "vrije" veld kenmerken ligt besloten in andere API specificaties, zoals hier voor Zaken: https://zaken-api.vng.cloud/api/v1/schema/

* bronorganisatie: Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef
* zaaktype: URL-referentie naar het ZAAKTYPE (in de Catalogi API) in de CATALOGUS waar deze voorkomt
* vertrouwelijkheidaanduiding: Aanduiding van de mate waarin het zaakdossier van de ZAAK voor de openbaarheid bestemd is.

**Comment by Hugo-ter-Doest** [comment]
Er worden geen privacygevoelige gegevens gelekt met het huidige mechanisme. Helemaal voorkomen van lekken is onmogelijk. We denken dat er voldoende waarborgen zijn in de huidige inrichting en eisen aan de Notificaties API.
