### ISSUE TITLE
Als teamlid wil ik dat de presentaties ook in PowerPoint-formaat aanwezig zijn

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1524]
zodat ik de presentaties kan aanpassen of hergebruiken.

**Toelichting**
Bijvoorbeeld, momenteel kan ik de presentaties van de sprint-demo's alleen vinden in PDF-formaat, zie

https://github.com/VNG-Realisatie/gemma-zaken/tree/023a4ca1b3a21a07820e893d1abe6108b271bcd4/docs/_content/community/bestanden

**Comment by michielverhoef** [comment]
Aangezien het presentaties betreft die reeds gegeven zijn zou ik deze in PDF laten. Dit ook om te voorkomen dat deels aangepaste versies van deze presentaties als de presentatie van de sprint demo gaan rondcirculeren.

Het is geen enkel probleem om intern de powerpoint te delen en te hergebruiken maar de presentaties zoals die gegeven zijn worden gearchiveerd en alleen-lezen aangeboden.
