### ISSUE TITLE
Graag de tekst voor de zaken API op de website aanpassen

### ISSUE THREAD

**Issue by NickHardy** [VNG-Realisatie/gemma-zaken#1527]
# Improvement Story

De beschrijving op onderstaande website graag verduidelijken:
https://zaakgerichtwerken.vng.cloud/standaard/zaken/index

In de beschrijving van de zaken API staat het volgende:
`Zaakcontactmomenten
Nieuw in versie 1.1.0

Voor versie 1.1.0 bestond er geen Klantinteracties API en werden klantcontacten in de Zaken API opgenomen. Vanaf versie 1.1.0 is deze resource deprecated - consumers horen van de contactmomenten API gebruik te maken.

Over een zaak kunnen één of meerdere contactmomenten plaatsvinden. Via zaakcontactmomenten kunnen zaken en contactmomenten aan elkaar gerelateerd worden, waardoor het mogelijk wordt om alle contactmomenten bij een zaak in te kijken.`

De consumers zullen van de Klantinteracties API gebruik moeten maken.

**Comment by michielverhoef** [comment]
Het gaat vermoedelijk om deze pagina: https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/index

Ik begrijp het issue niet helemaal, is het de bedoeling de zin
" consumers horen van de contactmomenten API gebruik te maken"
te vervangen door:
"De consumers zullen van de Klantinteracties API gebruik moeten maken. "

Dat is nl. niet correct. Er is niet 1 Klantinteracties API (als is dat ooit wel de bedoeling geweest maar voortschrijdend inzicht etc.). 
De resource Klantcontacten uit de Zaken API is deprecated geworden en vervangen door de resource Contactmomenten uit de Contactmomenten API https://contactmomenten-api.vng.cloud/api/v1/schema/ 

Dus los van een typo (contactmomenten met een kleine letter) klopt de tekst wel.

Ik sluit het issue, mocht ik het verkeerd begrepen hebben graag heropenen en aangeven wat er dan niet correct is.
