### ISSUE TITLE
Als Gemeente wil ik gestandaardiseerde voorzieningen om gegevens over te zetten naar Register van andere leverancier

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1528]
...zodat Gemeente eenvoudig kan wisselen van bijvoorbeeld het DocumentenRegister van leverancier-A naar het DocumentenRegister van leverancier-B. 
Dit om te voorkomen dat er sprake is van een lockin als eenmaal gekozen is voor een Register en voor een leverancier. 
Als gemeente wil ik garanties dat verschillende Registers van verschillende leveranciers naast elkaar gebruikt kunnen worden en dat de API voorzieningen heeft om data over te brengen van DocumentRegister-leverancier-A naar DocumentRegister-leverancier-B.

**Comment by michielverhoef** [comment]
De architectuur die ten grondslag ligt aan de Common Ground gedachten zoals bevragen bij de bron en eenmalige opslag schrijft niet expliciet voor dat er maar 1 applicatie/database gebruikt mag worden als register. 

Dit betekent dat wanneer een gemeente registers van meerdere leveranciers gebruikt deze in principe naast elkaar moeten kunnen bestaan, een gegeven staat immers maar op één plek opgeslagen.

Wanneer een gemeente een applicatie vervangt (register leverancier a vervangt register leverancier b) is dit een software migratie. Voor de consumer applicaties die de API aanroepen zou dit geen verschil mogen maken, beide registers ondersteunen immers de relevante API's. De beide registers zouden qua gegevensopslag dezelfde informatie aan moeten kunnen, inclusief historie etc. Anders is het niet mogelijk om de API's volledig te ondersteunen. 

Omn te voorkomen dat er sprake is van een lockin is het van belang dat een register alleen geraadpleegd wordt via de API's van de standaard. Wanneer informatie buiten de API's van de standaard om geraadpleegd wordt of zelfs extra, proprietary, informatie opgeslagen en geraadpleegd wordt kan deze informatie niet via de API's van de standaard ontsloten worden en is er sprake van een vendor lockin. Dit is een onwenslijke situatie en gemeenten moeten dan ook goed in de gaten houden dat registers aan de standaarden voldoen. Zowel qua ondersteuning van de API's als de informatie die opgeslagen en geraadpleegd kan worden. Mocht blijken dat er gegevens ontbreken in de API standaarden is het van belang dat leveranciers niet zelf eigen oplossingen gaan verzinnen maar de wensen, liefst in de vorm van userstories, indienen bij de beheerders van de API standaarden zodat de standaarden snel waar nodig uitgebreid kunnen worden en alle leveranciers deze gegevens op dezelfde manier op kunnen nemen in hun applicaties. Het is dus niet wenslijk om eigen gegevens-soorten of extra functionaliteit in registers die beschreven zijn in en horen bij een standaard op te nemen, dit beperkt de uitwisselbaarheid en werkt vendor lockin in de hand.

Voor VNG is het niet mogelijk om garanties te geven op producten van leveranciers en/of gemeenten. Wat kan is eisen voor het kunnen overbrengen van gegevens van het ene naar het andere register op te nemen in een tekstuele beschrijving. Mocht de topicstarter hier al ideeën over hebben is een pullrequest zeker welkom!

**Comment by HenriKorver** [comment]
Zoals @michielverhoef beschrijft is het zeker waar dat het belangrijk is dat zowel systeem A (van de leverancier voor de switch) als systeem B (van de leverancier na de switch) naadloos voldoen aan de ZGW API's. Echter dit is nog geen antwoord op de vraag. Immers hoe krijg je de data van systeem A naar systeem B als je wilt overstappen van leverancier?  Theoretisch gezien zou je dat via de API kunnen doen. Je vraagt alle data op van systeem A via de API met GET calls en je schrijft het vervolgens weg in systeem B met POST en PUT calls. In de praktijk is dit natuurlijk geen optie. Er zal export- en import-functionaliteit nodig zijn om de data te kunnen migreren van A naar B.
In de gewenste situatie zullen gemeenten zelf eigenaar moeten worden van de registersystemen waar data zoals zaken, documenten, besluiten zijn opgeslagen. Ze zijn dan zelf eigenaar van hun een eigen data en zullen die data nooit meer hoeven te migreren. Ze hoeven alleen maar consumer-applicaties te kopen  die slim gebruik maken van deze data via de ZGW API's. Het spreekt voor zich dat deze consumer-applicaties wel makkelijk te vervangen zijn omdat ze zelf geen data bevatten.

**Comment by michielverhoef** [comment]
> Echter dit is nog geen antwoord op de vraag

Ik had de vraag al in de eerste zin van de derde paragraaf beantwoord:

> Wanneer een gemeente een applicatie vervangt (register leverancier a vervangt register leverancier b) is dit een software migratie.

Software migratie is niet iets wat in de standaard thuis hoort en waar VNG garanties voor kan geven.
