### ISSUE TITLE
Als teamlid wil ik alle presentaties van de sprint-demo's terug kunnen zien

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1529]
Nu kan ik alleen de presentaties van de eerste 12 sprint-demo's terugvinden:

https://github.com/VNG-Realisatie/gemma-zaken/tree/023a4ca1b3a21a07820e893d1abe6108b271bcd4/docs/_content/community/bestanden

Echter er zijn al 19 sprint-demo's geweest, oftewel de presentaties van de laatste zeven sprint-demo's ontbreken nog. Het zou fijn zijn als die toegevoegd worden.

**Comment by PDG65** [comment]
Michiel en Hugo zouden deze moeten hebben.

**Comment by HenriKorver** [comment]
Ja het zou inderdaad fijn zijn als deze beschikbaar worden gesteld (zowel in pdf- als powerpoint-formaat). Misschien handig om meteen ook de opnamen van de presentaties erbij te zetten (links naar de YouTube-filmpjes)

**Comment by michielverhoef** [comment]
Er zijn weliswaar 19 sprints geweest maar na 18 juli 2019 is niet meer van elke sprint een sprint demo gegeven.

**Comment by HenriKorver** [comment]
Gelukkig dat scheelt weer werk voor de beheerder ;-)
