### ISSUE TITLE
Als burger wil ik een verzoek tot inzage in mijn persoonsgegevens kunnen doen via de website van de gemeente Delft

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#153]
...zodat ik o.a. inzicht krijg in welke van mijn persoonsgegevens bij de gemeente zijn geregistreerd, waar ze voor worden gebruikt en aan wie deze gegevens nog meer worden verstrekt.

**Definition of ready**
- [x] Userstory is ingevuld op template architectuurschets [link](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md)
- [x] Userstory is voorzien van veldmapping naar RGBZ2  #237 
- [ ] Userstory past op wenselijk gebruik ZGW volgens GEMMA 2

**Definition of done**
- [x] er is een OAS 3.0 specificatie
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

Specifiek voor deze user story:
- [ ] Voldoet aan AVG
Zie ook: https://autoriteitpersoonsgegevens.nl/nl/zelf-doen/privacyrechten/recht-op-inzage

**Taken**
- [ ] Opstellen welke velden bij een melding horen (@RitaBerghuis)
- [ ] Aanleveren testdata (@RitaBerghuis)
- [ ] Schrijven (unit) test voor referentie-implementatie (@EdwinCoster)
- [x] Implementeren in referentie-implementatie 
- [x] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Op basis van het [proces](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md), kom ik de volgende calls naar componenten. Ik kan echter niet alles plaatsen.

> De aanvrager dient via de website (VJV) een inzageverzoek persoonsgegevens in en geeft (na authenticatie via DigiD) op welke onderdelen geanalyseerd moeten worden. US #153;
```http
POST orc/avg/inzageverzoeken/  # Creeer InzageVerzoek
```

> De VJV wordt, na correct en volledige registratie, toegewezen aan de afdeling ‘Advies JZ’ en geregistreerd in VJV, de ZRC en de Domeinspecifieke gegevens. US #153, Status ‘Geregistreerd’.
```http
POST zrc/zaken/  # Creeer Zaak
POST zrc/zaakobjecten/  # Koppel Zaak aan InzageVerzoek
POST zrc/statussen/  # Geregistreerd
? POST zrc/rollen  # Behandelaar op basis van Zaaktype? Zie hieronder.
```

> Advies JZ routeert de VJV naar de Behandelaar van inzageverzoeken. Dit wordt geregistreerd in VJV en de ZRC. US #..., geen statuswijziging; Wij zouden graag zien dat deze actie uit het proces wordt gehaald omdat deze geen toegevoegde waarde heeft.
```http
POST zrc/rollen/  # Behandelaar van inzageverzoeken / handmatig
```

> De Behandelaar van inzageverzoeken controleert of aanvraag voldoet aan de voorwaarden. US #..., statuswijziging ‘Toetsing wet- en regelgeving afgerond’;
```http
POST zrc/statussen/  # Toetsing wet- en regelgeving afgerond
```

> Indien dit niet het geval is volgt een afwijzing. Registratie in VJV, ZRC en DRC. US #..., statuswijziging ‘Afgehandeld’.
```http
POST zrc/statussen/  # Afgehandeld
```

> Indien dit wel het geval is controleert de Behandelaar of nog aanvullende gegevens nodig zijn (b.v. voor ‘Overige systemen’ en ‘Algemeen’); Als er aanvullende gegevens nodig zijn, wordt per brief gevraagd om een precisering / aanvulling van het verzoek. Met een termijn van (b.v.) 2 weken. De behandeltermijn wordt met dezelfde termijn opgeschort. Registratie in VJV, ZRC en DRC. US…, statuswijziging ‘Geaccepteerd’; Nog afstemmen en uitbreiden met wat er gebeurt als de reactietermijn verstreken is. Gaan we rappelleren, of wordt het inzageverzoek afgehandeld?
```http
UPDATE zrc/zaken/XXX  # behandeltermijn opschorten (2 weken)
POST zrc/statussen/  # Geaccepteerd
```

> Als er geen aanvullende gegevens (meer) nodig zijn, dan verzamelt de behandelaar de benodigde gegevens bij deskundigen. Registratie in VJV en ZRC. US #..., statuswijziging ‘In behandeling genomen’.
```http
POST zrc/statussen/  # In behandeling genomen
```

> Idealiter worden hiervoor vanuit het ZAC taken toegewezen aan de diverse medewerkers ...
```http
? POST zrc/rollen/  # medewerkers koppelen als... behandelaar?
? POST zrc/deelzaken/  # medewerkers taken (=deelzaken) geven?
```

> ... die vervolgens hun resultaten toevoegen aan de Zaak. Het resultaat kan zijn:
> * Persoon komt niet voor;
```http
?
```

> * Een uitnodiging om het dossier in te zien. Het resultaat wordt opgeslagen in de Domeinspecifieke gegevens.
```http
?
```

> * Een afschrift van een dossier kan als informatieobject in de DRC worden opgenomen met vertrouwelijkheid ‘Zaakvertrouwelijk’. Een overzicht van systemen zou in de DRC als Informatieobject kunnen worden opgenomen met de vertrouwelijkheid ‘Intern’). Mogelijk moet of kun je hier Informatie-objecttypen voor definiëren; Ook hier met je wellicht nog iets met rappelleren…
```http
POST drc/enkelvoudigeinformatieobjecten/  # Afschrift (Zaakvertrouwelijk) / Overzicht van systemen (Intern)
POST drc/zaakinformatieobjecten/  # Zaak aan document koppelen
```

> Zodra alle deskundigen hebben gereageerd, stelt de behandelaar de beschikking op. De overzichten van systemen worden hierbij gecontroleerd en samengevoegd tot één overzicht. Registratie in VJV, ZRC en DRC. US #…, statuswijziging ‘Onderzoek afgerond’. De beschikking is een informatieobject met vertrouwelijkheid ‘Zaakvertrouwelijk’;
```http
? Hoe controleer je of iedereen heeft gereageerd? Toch met deelzaken werken?
POST drc/enkelvoudigeinformatieobjecten/  # Beschikking (Zaakvertrouwelijk)
POST drc/zaakinformatieobjecten/  # Zaak aan document koppelen
POST zrc/statussen/  # Onderzoek afgerond
```
> De Behandelaar stuurt de beschikking op naar de Aanvrager. Registratie in VJV, ZRC en DRC. US #..., statuswijziging ‘Afgehandeld’. Alle informatieobjecten met de vertrouwelijkheid ‘Intern’ kunnen nu verwijderd worden.
```http
POST zrc/statussen/  # Afgehandeld
```

**Comment by EdwinCoster** [comment]
> ? POST zrc/rollen  # Behandelaar op basis van Zaaktype? Zie hieronder.

Ik wil niet dat 'ADvies JZ' een behandelaar wordt. Eén van de medewerkers van Advies JZ wordt de behandelaar.

> ? POST zrc/rollen/  # medewerkers koppelen als... behandelaar?

Ja. De 'deskundigen' zijn degenen die gegevens gaan aanleveren (als die er zijn). De status van de zaak wijzigt naar 'In behandeling genomen'. Zodra de deskundigen hebben geantwoord, wijzigt de status in 'Advies ingewonnen'. 

> ? POST zrc/deelzaken/  # medewerkers taken (=deelzaken) geven?

Nee

> ? (bij persoon komt niet voor.)

Het is mogelijk dat een persoon niet voorkomt in de systemen van een bepaald aandachtsgebied. Dus dan is het antwoord dat de persoon niet voorkomt.

> ? (bij een uitnodiging om het dossier in te komen zien.

Soms is het te bewerkelijk om een afschrift van een dossier te maken dat ook recht doet aan de privacy van anderen. In zo'n geval wordt de initiator uitgenodigd om een afspraak te maken om zijn dossier in te zien (onder begeleiding uiteraard).

> ? Hoe controleer je of iedereen heeft gereageerd? Toch met deelzaken werken?

Dat zullen wij dus ergens in het proces moeten regelen. Zowel de initiator (als om aanvullende gegevens wordt gevraagd) als de deskundigen hebben een beperkte termijn om te reageren.

**Comment by joeribekker** [comment]
Thanks, ik was technisch aan het kijken of de User Story helder was, en welke API-calls er nodig waren. Eentje is nog open:

> ? (bij persoon komt niet voor.)
> ? (bij een uitnodiging om het dossier in te komen zien.
>
>> Het is mogelijk dat een persoon niet voorkomt in de systemen van een bepaald aandachtsgebied. Dus dan is het antwoord dat de persoon niet voorkomt.

Maar wat is dat antwoord bij beide? Een document? Of iets anders wat relevant is voor ZRC of DRC?

**Comment by EdwinCoster** [comment]
> Maar wat is dat antwoord bij beide? Een document? Of iets anders wat relevant is voor ZRC of DRC?

Ik voorzie een soort keuzelijst met 4 opties (per deskundige):
- Persoon komt niet voor;
- Persoon komt voor met een bestand gegevens uit één of meer applicaties;
- Persoon komt voor met een bestand met een afschrift van een dossier;
- Persoon komt voor met een uitnodiging om het dossier in te komen zien.

Die bestanden gaan de DRC in. Ik zie op dit moment niet iets voor de ZRC, meer iets voor de ORC.

**Comment by joeribekker** [comment]
Helder!

**Comment by joeribekker** [comment]
Zie: https://github.com/VNG-Realisatie/gemma-zaken/pull/313 voor de  API specificatie wijzigingen.

**Comment by EdwinCoster** [comment]
@TCIMEddy : wat is het nou?

**Comment by TCIMEddy** [comment]
@EdwinCoster Ik weet het ook niet sorry :-) het is of close en done of open en in progress. Mijn vraag aan jou is de API deze user story ondersteunt?

**Comment by jgortmaker1** [comment]
gemma vinkjes gezet, al is het wat lastig beoordelen door de grootte van de US en wat begripsverwarring tussen het inzageverzoek en de VJV en welk systeem nu wat doet..maar volgens mij wel in orde..

**Comment by jgortmaker1** [comment]
wat ik nog wel mis: krijgt de indiener van het inzageverzoek een referentienummer terug? en is dat een zaaknummer, of....

**Comment by EdwinCoster** [comment]
Jeffrey schreef:

> wat ik nog wel mis: krijgt de indiener van het inzageverzoek een referentienummer terug? en is dat een zaaknummer, of....

De indiener krijgt het VJV-referentienummer terug, dat ook als kenmerk bij de zaak is opgenomen.

**Comment by jgortmaker1** [comment]
interessant...zit dat ergens in de mapping, dat VJV-nummer?

**Comment by EdwinCoster** [comment]
Yep, onderaan...

| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
ZAAK.Kenmerken.Kenmerk bron | Naam bronsysteem | AN200 | De aanduiding van de administratie waar het kenmerk op slaat.
ZAAK.Kenmerken.Kenmerk | Unieke identificatie | AN20 | Identificeert de zaak uniek in een andere administratie.
