### ISSUE TITLE
Internal Server Error bij zaakinformatieobject_create operation

### ISSUE THREAD

**Issue by andyverberne** [VNG-Realisatie/gemma-zaken#1531]
Bij de aanroep van de ZRC operaton zaakinformatieobject _create met het volgende bericht:

`{
"beschrijving":"Verzoek in PDF formaat.",
"informatieobject":"http://localhost:8001/api/v1/enkelvoudiginformatieobjecten/41ef4d7c-1e24-4216-9ff2-b4456e06662f",
"titel":"Verzoek PDF",
"zaak":"http://localhost:8000/api/v1/zaken/676050f6-cd76-47b0-9481-10cfe5abd9dc"
}`

Ontvang ik de volgende response:

`{
  "type": "http://localhost:8000/ref/fouten/APIException/",
  "code": "error",
  "title": "Er is een serverfout opgetreden.",
  "status": 500,
  "detail": "Internal Server Error",
  "instance": "urn:uuid:f1d9c9fe-7981-4fcd-b85f-a53bb7697091"
}`

Het zaakinformatieobject is echter **WEL** correct aangemaakt.

in de log van de docker container zrc_web_1 staat de volgende stack trace:

[stacktrace1.txt](https://github.com/VNG-Realisatie/gemma-zaken/files/4040542/stacktrace1.txt)

De containers draaien lokaal en zijn gestart via:

`docker-compose -f docker-compose.yml -f docker-compose.hostnetwork.yml up`

Eerder kreeg de volgende stacktrace in zrc_web_1:

[stacktrace2.txt](https://github.com/VNG-Realisatie/gemma-zaken/files/4040543/stacktrace2.txt)

Daarin is te zien dat vanuit het DRC geprobeerd wordt om de zaak http://example.com/api/v1/zaken/bb51fbbf-cb62-4e72-b1d9-d873afdb96af te benaderen wat natuurlijk niet werkt. Ik heb toen de standaard aanwezige website example.com verwijderd maar dat gaf toen de stacktrace welke hierboven als eerste vermeld staat. Ook na het weer toevoegen van de exmaple.com website aan zowel ZRC als DRC krijg ik nog steeds de stacktrace die hierboven als eerste vermeld staat en niet meer de stacktrace met de melding http://example.com/api/v1/zaken/bb51fbbf-cb62-4e72-b1d9-d873afdb96af

**Comment by andyverberne** [comment]
Ondanks dat ik de stacktraces heb geformateerd als code zijn ze toch niet leesbaar omdat de carriage return niet wordt overgenomen. Daarom deze 2 stacktraces nogmaals als losse tekst files:

[stacktrace1.txt](https://github.com/VNG-Realisatie/gemma-zaken/files/4040527/stacktrace1.txt)
[stacktrace2.txt](https://github.com/VNG-Realisatie/gemma-zaken/files/4040528/stacktrace2.txt)

**Comment by sergei-maertens** [comment]
Zoals kort besproken op Slack, maar voor future reference:

Deze wordt veroorzaakt doordat het juiste domein van de 'site' niet ingesteld staat. Zie documentatie: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/ontwikkelaars/handleidingen-en-tutorials/eenmalige-setup.md#drc
