### ISSUE TITLE
De RI laat het wijzigen van zaakgegevens toe als de zaak afgesloten is

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1537]
# Bug

De standaard beschrijft dat gegevens van een zaak niet gewijzigd mogen worden als de zaak afgesloten is (tenzij je daarvoor de specifieke scope `zaken.geforceerd-bijwerken` hebt, aangezien archiefmedewerkers gesloten/gearchiveerde zaken moeten kunnen 'fixen' als data niet klopt).

Echter, dit is momenteel enkel op de `Zaak` resource zo - het is nog steeds mogelijk om documenten aan zaken te relateren, zaakobjecten aan te maken etc...

Ontdekt in https://github.com/open-zaak/open-zaak/pull/454

Taken:

- [x] RI bijwerken (https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/139)
- [x] API standaard verduidelijken (explicieter maken) (https://github.com/VNG-Realisatie/gemma-zaken/pull/1538)
- [ ] ATP bijwerken

**Comment by sergei-maertens** [comment]
@stevenbal kan jij ATP bijwerken hiervoor?

**Comment by stevenbal** [comment]
@sergei-maertens dit geldt ook voor verwijderen neem ik aan? Dus een gerelateerd resultaat oid mag niet verwijderd worden als de zaak is afgesloten? En besluiten in het BRC mogen ook niet bijgewerkt worden?

**Comment by sergei-maertens** [comment]
Correct!

Over het gedrag van BRC ben ik het nog niet 100% zeker, dat zullen we eigenlijk beter in het scrumteam bespreken. Staat nu zo dat je geen besluiten aan gesloten zaken kan toevoegen. Er moet eigenlijk een scope bijkomen `besluiten.geforceerd-bijwerken` als je dat alsnog wil, denk ik :thinking:

**Comment by Hugo-ter-Doest** [comment]
Besluiten worden niet afgesloten zoals zaken. Dan heb je dus niet zo'n moment waarna een besluit niet meer mag worden bijgewerkt. Ik denk dat als een besluit is gekoppeld aan een afgesloten zaak het besluit niet meer mag worden gewijzigd. En als je een besluit wilt koppelen aan een afgesloten zaak lijkt me voldoende dat je de zaak geforceerd mag bijwerken. Vanuit besluit gezien mag dit m.i. wel.

**Comment by stevenbal** [comment]
@sergei-maertens ik heb de tests op het ATP geupdate, op de referentieimplementatie faalt het nog omdat de fix nog niet gedeployed is (gok ik). Voor openzaak heb ik de travis job op master gerestart en die is geslaagd
