### ISSUE TITLE
Zaaktype.ProductenOfDiensten moet niet verplicht zijn

### ISSUE THREAD

**Issue by JurjenBert** [VNG-Realisatie/gemma-zaken#1539]
# Bug
Bij het aanmaken van een zaaktype is het veld “Poducten of diensten” een verplicht veld, waarin een url moet worden opgenomen moet worden. Er is gekozen voor URLs omdat het eigenlijk verwijzen zouden moeten zijn naar een PDC API. 

Dit veld zou niet verplicht moeten zijn omdat: er vaak geen relatie is met de PDC (interne processen, generieke processen).  Hierdoor kunnen we ook verder met ZT inrichting voor producten die wel voorkomen in de PDC zolanf er nog geen PDC API is.  

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)

Welke claims/payload bevat je JWT?

**Comment by Hugo-ter-Doest** [comment]
@sergei-maertens de array met URL's mag toch een lege lijst zijn?

**Comment by Hugo-ter-Doest** [comment]
Inderdaad kun je lege lijst toewijzen aan dit attribuut. Dat kan worden gebruikt voor de interne processen. Het attribuut laten we verplicht: bij zaakgericht werken leidt een zaak altijd tot een levering van een product of dienst.
