### ISSUE TITLE
Als burger wil ik de status en de relevante documenten van mijn inzage verzoek kunnen inzien op de PIP van de gemeente Delft

### ISSUE THREAD

**Issue by RitaBerghuis** [VNG-Realisatie/gemma-zaken#154]
...zodat ik deze op het moment dat het mij uitkomt kan bekijken.

**Gerelateerd aan**
* #166 

**Definition of ready**
- [x] Userstory is ingevuld op [template architectuurschets](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md)
- [x] Userstory is voorzien van veldmapping naar RGBZ2 US #239 
- [x] Userstory past op wenselijk gebruik ZGW volgens GEMMA 2

**Definition of done**
- [x] er is een OAS 3.0 specificatie
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [x] Bepalen wat 'relevant' is voor de burger (niet tonen van interne informatieobjecten) @EdwinCoster /@RitaBerghuis 
- [x] Opstellen welke velden bij een inzageverzoek horen @EdwinCoster /@RitaBerghuis 
- [x] Aanleveren testdata @EdwinCoster /@RitaBerghuis
- [x] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [x] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [x] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by RitaBerghuis** [comment]
Op 20 juni even samen afstemmen hoe deze precies zou moeten worden, om een vervolg te zijn op userstories die al in behandeling zijn.

**Comment by TCIMEddy** [comment]
@RitaBerghuis @ehotting prima lijkt me goed om de user stories dan samen te voegen en dat de contactpersonen gezamenlijk data aanleveren

**Comment by TCIMEddy** [comment]
Ondanks eerdere opmerking eens met eelco. User stories zo klein mogelijk houden

**Comment by joeribekker** [comment]
Technisch bestaat deze User Story uit (pseudo code/urls):

Een stukje "anti-explodeer-scope" registratie URL voor een Natuurlijk Persoon (NPS) in het Overige Registraties Component (ORC):

```bash
orc/nps/?bsn=<bsn>  # Opvragen NPS URL op basis van BSN
```

En enkele calls naar ZDS:
```bash
zrc/zaken/?betrokkene=<nps url>  # Zaken filteren op NPS URL als betrokkene
zrc/status/<uuid>  # Status details opvragen (reeds geïmplementeerd)

ztc/statustype/<uuid>  # Statustype opvragen (reeds geïmplementeerd)

drc/zaakinformatieobjecten/?zaak=<zaak url>  # Zaakinformatieobjecten filteren op Zaak
drc/enkelvoudiginformatieobjecten/<uuid>   # Enkelvoudig informatie objecten ophalen (deels geïmplementeerd, voornamelijk nog de RGBZ-mapping uitbreiden)
```

De Zaakinformatieobjecten zijn alleen nog onderhevig aan discussie: #166

**Comment by TCIMEddy** [comment]
@jgortmaker1 Gemma2 nog geen vinkje
@ArjanKloosterboer RGBZ nog geen vinkje
@RitaBerghuis kun jij beoordelen of deze user story gereed is
@joeribekker kun jij beoordelen of deze user story gereed is

**Comment by TCIMEddy** [comment]
Voor nu zet ik deze user story even in review

**Comment by joeribekker** [comment]
@TCIMEddy Hij is al geimplementeerd, dus wat mij betreft is hij gereed ;-)

Zie: https://github.com/VNG-Realisatie/gemma-zaken/pull/291
Deze PR was goedgekeurd door Michiel.

**Comment by ArjanKloosterboer** [comment]
Hij is pas af als ie gereviewd is. Waar kan ik de documentatie vinden?

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Zoek je de mapping? @RitaBerghuis Kun jij Arjan voorzien van deze mapping?

**Comment by RitaBerghuis** [comment]
De mapping staat in #239 @ArjanKloosterboer en @TCIMEddy

**Comment by ArjanKloosterboer** [comment]
Ik zoek niet de mapping. Die is nodig voor het reviewen van de user-story in de voorbereidingsfase. Maar de userstory zou inmiddels gerealiseerd zijn. Ik zoek de documentatie van wat er nu gerealiseerd is.

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer dit is denk ik de functionele documentatie die voor alle API's nog gemaakt moet worden (conform (nog te maken) voorbeeld Maykin))

**Comment by jgortmaker1** [comment]
US past volgens mij prima in GEMMA.
zou ook wel willen zien (functionele documentatie) hoe het is gebouwd maar dat staat het vinkje niet in de weg...

**Comment by michielverhoef** [comment]
De functionele documentatie van wat er tot nog toe gerealiseerd is (in de verschillende referentiecomponenten) staat open ter review.  Als het goed is staan ook de laatste wijzigingen nav opmerkingen van Arjan in de laatste versies van de pullrequests, mocht dat niet zo zijn, hoe krijg ik dat dan wel in orde?

**Comment by ArjanKloosterboer** [comment]
Wat is er nou gerealiseerd a.g.v. deze userstory? Waar is de desbetreffende pullrequest? Ik zie het nergens vermeld staan, zou in de beschrijving van deze userstory moeten staan. Ik kan dus niets reviewen.
