### ISSUE TITLE
EnkelvoudigInformatieObject.versie type 

### ISSUE THREAD

**Issue by rockxwre** [VNG-Realisatie/gemma-zaken#1541]
Volgens [de API specificatie](https://documenten-api.vng.cloud/api/v1/schema/openapi.json) is de eigenschap "versie" van de resource "EnkelvoudigInformatieObject" van het type "integer". De waarde van deze eigenschap is een getal dat automatisch wordt opgehoogd. 
Zou dit niet een "string" met een lengte van 5 (AN5) moeten zijn, waarbij de waarde een vrij te bepalen functioneel versienummer is? Dan is dit volgens mij conform de [RGBZ 2.0 specificatie](https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/informatieobject.versie).

**Comment by sergei-maertens** [comment]
RGBZ is ter inspiratie genomen, maar hiervan is bewust afgeweken omdat integers inherent wel netjes te sorteren zijn. De string-versie laat te veel verschillende versie-schema's toe die niet compatibel zijn met verschillende implementaties. Door een integer te gebruiken is het makkelijk om de laatste versie te bepalen (= hoogste waarde).

**Comment by Hugo-ter-Doest** [comment]
Ik ben het eens met het antwoord van Sergei.
