### ISSUE TITLE
Als ontwikkelaar wil ik dat de Zaakgericht werken documentatie weer beschikbaar komt (1)

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1544]
...zodat iedereen er de details over kan lezen.

VNG heeft besloten dat zaakgerichtwerken.vng.cloud snel weg moest (zonder veel uitleg en met nauwelijks vervanging op de officiele website). Het beschikbaar maken van de documentatie op een ander domein/manier heeft door team-wijzigingen, rol-verdelingen en budgettaire uitdagingen, is tot op heden nog niet gebeurt.

Er moet een alternatief "opzetje" komen, waarna iemand alle content moet overhevelen, aanpassen en eventueel herstructureren.

**Comment by joeribekker** [comment]
Voorwerk gedaan, aan @michielverhoef om het thema aan te passen.

**Comment by michielverhoef** [comment]
https://vng-realisatie.github.io/gemma-zaken/ De VNG look en feel  is vervangen door een eenvoudigere. Dit kan altijd aangepast worden maar voor nu kan het issue gesloten worden.
