### ISSUE TITLE
definitie url attributen in ObjectContactMoment niet gelijk

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1545]
# Bug

In de entiteit 'ObjectContactMoment' (zie openapi.yaml van Klantinteracties) staan 4 attributen waarvan er 3 een url voorstellen. Je zou verwachten dat de vorm van deze attributen gelijk is aan elkaar. Dat blijkt echter niet het geval.

* url
   heeft een maxLength van 1000 en een minLength van 1.
* contactmoment
   heeft geen maxLength en geen minLength.
* object
   heeft een maxLength van 200 en een minLength van 1.

**Comment by HenriKorver** [comment]
OAS design consistent gemaakt (conform bullet 1). Zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/gemma-zaken/master/api-specificatie/DESIGN/kic/contactmomenten/openapi.yaml). 
Nu ligt de bal bij @joeribekker om dit te implementeren in de referentie-implementatie.

**Comment by joeribekker** [comment]
URL-velden worden dus als volgt:

Algemene kenmerken
* min_length=1, max_length=1000

Indien het URL-veld optioneel is:
* Nullable=True

Zie ook: https://github.com/VNG-Realisatie/gemma-zaken/issues/1405#issuecomment-639543611

**Comment by joeribekker** [comment]
Toegevoegd aan API spec in https://github.com/VNG-Realisatie/gemma-zaken/pull/1630 voor contactmomenten, rest volgt.

**Comment by HenriKorver** [comment]
Akkoord
