### ISSUE TITLE
definitie url attributen in ObjectVerzoek niet gelijk

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1546]
# Bug

In de entiteit 'ObjectVerzoek' (zie openapi.yaml van Klantinteracties) staan 4 attributen waarvan er 3 een url voorstellen. Je zou verwachten dat de vorm van deze attributen gelijk is aan elkaar. Dat blijkt echter niet het geval.

* url
  heeft een maxLength van 1000 en een minLength van 1.
* verzoek
  heeft geen maxLength en geen minLength.
* object
  heeft een maxLength van 200 en een minLength van 1.

**Comment by HenriKorver** [comment]
@melsk-r Je hebt gelijk. De uri attributen moeten dezelfde vorm hebben zoals beschreven in jouw eerste bullet. Ik heb dit aangepast in het OAS-ontwerp van de Verzoeken API.

@sergei-maertens @joeribekker Is dit mogelijk een bugje in jullie generatiescript dat aangepast moet worden?

**Comment by sergei-maertens** [comment]
Voor mij is hier geen tijd voor gereserveerd, dus ik unassign mezelf.

**Comment by HenriKorver** [comment]
Opgelost in design OAS. Zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/gemma-zaken/master/api-specificatie/DESIGN/kic/verzoeken/openapi.yaml).

**Comment by joeribekker** [comment]
Zie ook: https://github.com/VNG-Realisatie/gemma-zaken/issues/1405#issuecomment-639543611

**Comment by HenriKorver** [comment]
Akkoord
