### ISSUE TITLE
definitie url attributen in VerzoekInformatieObject niet gelijk

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1547]
# Bug

In de entiteit 'VerzoekInformatieObject' (zie openapi.yaml van Klantinteracties) staan 3 attributen die een url voorstellen. Je zou verwachten dat de vorm van deze attributen gelijk is aan elkaar. Dat blijkt echter niet het geval.

* url en informatieobject
  hebben een maxLength van 1000 en een minLength van 1.
* verzoek
  heeft geen maxLength en geen minLength.

**Comment by HenriKorver** [comment]
Opgelost in design OAS. Zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/gemma-zaken/master/api-specificatie/DESIGN/kic/verzoeken/openapi.yaml).

**Comment by joeribekker** [comment]
Zie ook: https://github.com/VNG-Realisatie/gemma-zaken/issues/1405#issuecomment-639543611

**Comment by HenriKorver** [comment]
Akkoord
