### ISSUE TITLE
Als bijdragend lid van de community wil ik kunnen beschikken over het gegevensmodel in een formaat dat ik met een vrij beschikbare tool kan bewerken

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1550]
…op een applicatie onafhankelijke wijze zodat ik dat gegevensmodel in een door mij gewenst tool kan bewerken t.b.v. een userstory of andersoortig issue.

Toelichting: In het project wordt Enterprise Architect (EA) gebruikt voor het maken van het gegevensmodel. Het gegevensmodel wordt ook opgeslagen als EA bestand en dat maakt het lastig voor leden van de community om een bijdrage te leveren aan het gegevensmodel.

Het voorstel is daarom om het gegevensmodel ook beschikbaar te stellen in het XMI formaat wat in andere tooling ingelezen kan worden. De leden van de community kunnen daardoor met het gegevensmodel aan de slag en voorstellen voor verbetering doen.

**Comment by paul-pfc** [comment]
Even snel naar Modelio 4.0 gekeken. Eerste indruk veelbelovend, maar:
- Bij import/export met EA gaan gegevens verloren (Notes, diagrams)
- Eerste keer openen na installatie op MacOs gaat prima, is daarna niet meer op te starten
- Na uninstall en handmatig verwijderen van resterende (hidden) bestanden start het weer op. Na afsluiten van het programma is het wederom niet meer op te starten.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/59864998/77168276-d991ec80-6ab7-11ea-8629-ee675e77f35a.png">

**Comment by joeribekker** [comment]
https://www.sparxsystems.eu/enterprise-architect/ea-lite-edition/ ?

**Comment by michielverhoef** [comment]
Volgens mij hebben we momenteel alleen nog een plaatje van het gegevens model, dit gaat er over de bestanden zoals die in EA gebruikt worden ook beschikbaar te hebben via github.

**Comment by EdwinCoster** [comment]
Helpt dit? UML 2.5 - XMI 2.5.1
[20200501_ZGW_API's.zip](https://github.com/VNG-Realisatie/gemma-zaken/files/4563887/20200501_ZGW_API.s.zip)

**Comment by michielverhoef** [comment]
Hoi Edwin, dank je! 

Er is inderdaad niemand verder mee gegaan maar nu kunnen we het geheel een beetje netjes bij elkaar houden. Ik ga er een mooie plek voor vinden.
