### ISSUE TITLE
Waarom kun in een ZAAKOBJECT geen identificatiegegevens meegeven voor medewerker, natuurlijk persoon en niet-natuurlijk persoon?

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1551]
Uit de enumeratie van het veld `objectType` in ZAAKOBJECT zijn  de waarden `medewerker`, `natuurlijk_persoon` en `niet_natuurlijk_persoon` niet meegenomen in de dropdown van de discriminator, zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/zrc/1.1.x/openapi.yaml#operation/zaakobject_create). 

Hierdoor kun je niet verwijzen naar deze zaakobjecten door middel van `objectIdentificatie`-gegevens. Maar hoe kun je dan naar deze zaakobjecten verwijzen als daarvoor nog geen externe API's beschikbaar zijn zoals nu het geval is? Dus niet via een URL in het `object`-veld.

**Comment by HenriKorver** [comment]
Ter aanvulling: bij het toevoegen van een betrokkene aan een zaak kun je wel de identificatiegegevens van medewerker, natuurlijk persoon en niet-natuurlijk persoon toevoegen.

Zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/zrc/1.1.x/openapi.yaml#operation/rol_create).

**Comment by michielverhoef** [comment]
Een zaakobject is "Een OBJECT waarop de ZAAK betrekking heeft." aldus  https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/zaakobject 

Medewerkers, natuurlijk persoon, niet-natuurlijk persoon zijn betrokkenen, aldus 
https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/objecttype/betrokkene 
"Een individu of een als zodanig benoemde groep van individuen, die als groep kunnen handelen, die een rol speelt bij één of meer ZAAKen."

Populatie: Alle NATUURLIJK PERSOONen, NIET-NATUURLIJK PERSOONen, VESTIGINGen, ORGANISATORISCHE EENHEIDen (van de zaak-behandelende organisatie) en MEDEWERKERs (van die zaak-behandelende organisatie) die betrokken zijn in enigerlei rol bij één of meer zaken van de zaakbehandelende organisatie.

Een natuurlijk of niet-natuurlijk persoon toevoegen doe je dus niet via een ZAAKOBJECT maar via een ROL waarbij je het juiste betrokkenetype toepast. Zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/zrc/1.1.x/openapi.yaml#operation/rol_create) , het attribuut betrokkeneType.
