### ISSUE TITLE
BUG: De zaaktype_publish operatie documentatie werkt niet in redoc

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1556]
# Bug

Als je bij het zaaktype object bij zaaktype_publis kijkt, mist de documentatie in redoc. Er is niet zichtbaar wat de operatie doet, en welke attributen je kan posten etc..
Als je op de operatie klikt in het menu, zie je enkel documentatie voor een zaaktype.

![afbeelding](https://user-images.githubusercontent.com/39768984/75548499-b8485e00-5a2d-11ea-9c35-6d1257032bf4.png)

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar gehost:
https://catalogi-api.vng.cloud/api/v1/schema/#operation/zaaktype_publish

Welke claims/payload bevat je JWT?
NVT

**Comment by michielverhoef** [comment]
Het gedrag van de publish operatie staat beschreven in de documentatie:
https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/
