### ISSUE TITLE
Als medewerker van een gemeente wil ik een korte, menselijk uitspreekbare code kunnen gebruiken om een zaaktype aan te duiden

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1558]
...zodat ik eenvoudig het zaaktype kan aanduiden zonder een UUID, GUID of url te moeten gebruiken.

Wat ik wil is een zaaktypecode zoals dit in StUF ZKN en Zaak- Documentservices bestaat.

Een zaaktypecode is waarschijnlijk ook nodig voor de transitie van oud naar nieuw.

**Comment by EduardWitteveen** [comment]
Zaaktype:
-    zaaktype.identificatie 
-   zaaktype.omschrijving
Dit is voldoende om de code kwijt te kunnen of te kunnen identificeren

Statustype:
-   GEEN statustype.identificatie 
-   statustype.omschrijving
Wenselijk, omdat je niet een code kwijt kan, maar het herbruik is laag dus overkoombaar.

Resultaattype:
-   GEEN resultaattype.identificatie 
-   resultaattype.omschrijving
Wenselijk, omdat je niet een code kwijt kan, maar het herbruik is laag dus overkoombaar.

Documenttype:
-   GEEN documenttype.identificatie 
-   documenttype.omschrijving
Nodig, juist omdat de documenttype's over meerdere zaaktypes gebruikt worden is de noodzaak tot een identificatie wel aanwezig om ze goed aan te kunnen duiden.

**Comment by michielverhoef** [comment]
Aangezien zaaktype.identificatie en zaaktype.omschrijving ook al bestaande velden in ImZTC en RGBZ 1 zijn en mogelijk gevuld zijn met waarden zou ik deze velden niet willen misbruiken om er een code in op te slaan. Wat is er mis met het toevoegen van een code veld aan zaaktype?

Wat mij betreft is het altijd mogelijk om velden toe te laten voegen in de standaard als daar een goede reden voor is. Dus als er behoefte is aan een nieuw/extra veld: maak een user story aan en assign deze aan Hugo en mij. Dan pakken we hem op.

**Comment by Hugo-ter-Doest** [comment]
De reden dat identificatie een attribuut van zaak is is dat je als consumer zelf de identificatie van een zaak mag bepalen bij creeren. De eis daarbij is dat de combinatie bronorganisatie en identificatie uniek is. Consumers kunnen dus zinvolle leesbare identificatie maken zoals 074-2019-5524.

We zouden iets dergelijks voor zaaktypen kunnen maken. @michielverhoef ?

**Comment by michielverhoef** [comment]
Dat klinkt goed maar is dat niet ongeveer de zaaktypecode zoals we die nu kennen in StUF ZKN / Zaak- Documentservices 1.x?

**Comment by Hugo-ter-Doest** [comment]
Er is geen probleem met zaaktypes begrijpen wij en mogelijk wel met documenttypes, eventueel met statustypes en resultaattypes. Is het nodig om identificatie toe te voegen aan statustype, resultaattype en informatieobjecttype. En dan met hetzelfde mechanisme als bij zaaktypes.

**Comment by EduardWitteveen** [comment]
Vanuit onze huidige werkwijze gebruiken wij deze code's, waarbij voor documenten de noodzaak het meest is (deze is ook geen onderdeel van zaaktype in het model), we hebben bijvoorbeeld heel veel aanvraag-document-typen.  

Bij de het resultaattype en statustype speelt dit minder, maar ook daar wordt er nu veel gebruik gemaakt van de betreffende code's om ze uniek aan te duiden (en omdat de naam wel eens wil aangepast wil worden, zonder het resultaatype / statustype  zelf). 

Voorbeeld van een in-beheername-document van een zaaktype: https://github.com/Sudwest-Fryslan/OpenZaakBrug/blob/master/examples/soap/zds1.1/Suites4SociaalDomein/B1026%20-%20Midoffice-productie%20name%20Minimaregeling%20aanvraag%20-%20Aanvraag%20minima.docx?raw=true (dit is een simpel-zaaktype, wij hebben ze uitgebreider)

**Comment by michielverhoef** [comment]
```
Zaaktype:

zaaktype.identificatie
zaaktype.omschrijving
Dit is voldoende om de code kwijt te kunnen of te kunnen identificeren
Statustype:

GEEN statustype.identificatie
statustype.omschrijving
Wenselijk, omdat je niet een code kwijt kan, maar het herbruik is laag dus overkoombaar.
Resultaattype:

GEEN resultaattype.identificatie
resultaattype.omschrijving
Wenselijk, omdat je niet een code kwijt kan, maar het herbruik is laag dus overkoombaar.
Documenttype:

GEEN documenttype.identificatie
documenttype.omschrijving
Nodig, juist omdat de documenttype's over meerdere zaaktypes gebruikt worden is de noodzaak tot een identificatie wel aanwezig om ze goed aan te kunnen duiden.
```


De genoemde identificaties en omschrijvingen zijn opgenomen in Catalogi API 1.2.0. Dit lijkt me voldoende om dit issue af te sluiten.
