### ISSUE TITLE
Resultaattype toevoegen via Catalogi beheer scherm geeft server error (500)

### ISSUE THREAD

**Issue by andyverberne** [VNG-Realisatie/gemma-zaken#1570]
# Bug

Geprobeerd wordt om via het 'Catalogi beheer' scherm van de referentie implementatie een resultaattype toe te voegen wat resulteert in een Server error (500). 
In de log verschijnen geen meldingen.

![Screenshot resultaattype toevoegen 1](https://user-images.githubusercontent.com/3702729/76614081-a7b0e100-651f-11ea-8d14-120ae96a3cc7.png)
![Screenshot resultaattype toevoegen 2](https://user-images.githubusercontent.com/3702729/76614080-a67fb400-651f-11ea-8f07-53fe2216b13f.png)

Referentie componenten zijn op lokale laptop gehost via docker-compose

**Comment by michielverhoef** [comment]
Het is een beetje gokken zonder logfile maar ik zie in het veld " is relevant voor" de waarde "1" staan. Volgens de omschrijving (onder het veld) moet dit een URL referentie naar het ZAAKTYPE zijn waar dit RESULTAATTYPE bij hoort. 

Kan het zijn dat bij de validatie van het opgevoerde zaaktype de waarde "1"  niet geresolved kan worden omdat er geen URL van beschikbaar is en daarom een 500 optreedt?

@joeribekker Klinkt dit plausibel?

**Comment by joeribekker** [comment]
@michielverhoef Helaas is dat het niet. Dat veld is een foreign key verwijzing (dus ID) naar een andere tabel in hetzelfde component. In de API wordt dit echter uitgedrukt als URL en de help-teksten worden hergebruikt :)

**Comment by michielverhoef** [comment]
Ok, jammer maar helaas. Dan klinkt het als een bug die gefixt moet worden :-)

**Comment by michielverhoef** [comment]
Ik ga eerst kijken of ik dit kan reproduceren met een log er bij.

**Comment by joeribekker** [comment]
@michielverhoef heb je een statusupdate voor mij?

**Comment by michielverhoef** [comment]
Inmiddels werkt dit weer.
