### ISSUE TITLE
Links naar API specificaties werken niet meer

### ISSUE THREAD

**Issue by wvnoortroxit** [VNG-Realisatie/gemma-zaken#1571]
# Bug
De links op deze pagina:

https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/index.md

geven allen een 404 terug. Het is daardoor niet meer mogelijk om de API specificaties te raadplegen.

**Comment by michielverhoef** [comment]
De links zijn weer zodanig aangepast dat de nieuwe documentatie website weer werkt. Overigens is dit nog even "oude stijl" maar die site staat nu hier: https://vng-realisatie.github.io/gemma-zaken/
