### ISSUE TITLE
Validatie geldigheid zaaktype te strict

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1583]
Dit issue komt voort uit ervaringen tijdens een API lab en testen met conversies.

Op dit moment wordt een zaaktype geïdentificeerd op basis van de volgende velden:
* identificatie catalogus
* omschrijving zaaktype
* begindatum zaaktype
* einddatum zaaktype

Daarnaast is het niet mogelijk om een versie van een zaaktype aan te maken met dezelfde begindatum als een al bestaande versie, er moet minimaal één dag tussen zitten. Ongeacht of van de eerste versie van het zaaktype de einddatum al gevuld is of niet.

Dit geeft problemen wanneer een nieuwe versie van een zaaktype aangemaakt wordt en nog dezelfde dag worden fouten geconstateerd. Dit moet als volgt opgelost worden:
* Zaken die reeds aangemaakt zijn van die verkeerde versie van het zaaktype moeten afgesloten worden
* De huidige versie van het zaaktype moet beëindigd worden door een einddatum te zetten 
* Een nieuwe versie van het zaaktype moet aangemaakt worden
* Vervolgens kunnen nieuwe zaken met de nieuwe versie van het zaaktype aangemaakt worden.

Door de huidige validatie is het echter niet mogelijk om die nieuwe versie van het zaaktype ook weer op vandaag in te laten gaan. Dit zou betekenen dat dit zaaktype pas morgen actief kan worden en zaken pas vanaf morgen aangemaakt kunnen worden. 

Om dit op te lossen moet de validatie van het aanmaken en het opvragen van de zaaktypeinformatie aangepast worden. Een mogelijke oplossing kan zijn een expliciete versie op te nemen of bij het opvragen te controleren op de einddatum.  Voor het aanmaken van een zaak is dat relatief eenvoudig (einddatum mag niet gevuld zijn of moet gevuld zijn met een datum die groter is dan de aanmaakdatum van de zaak?) maar bij het opvragen van zaaktype gegevens van lopende zaken wordt dit ingewikkelder.

[beschrijf de bug]

[kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)

Welke claims/payload bevat je JWT?

**Comment by joeribekker** [comment]
Hmm, ik vind de omschrijving van het probleem en de oplossingsrichting niet heel helder.

**Volgens mij is het probleem samengevat**

_Als zaaktype versie 1 geldig is van 01-01-2020 t/m 01-01-2020 betekent dat een versie 2 alleen mag beginnen op 02-01-2020 (omdat de einddatum van de geldigheid inclusief is)_

Dit is het gevolg van het _feit_ dat er niet 2 versies van hetzelfde zaaktype tegelijkertijd geldig kunnen zijn en de _keuze_ dat dit wordt bepaald aan de hand van de geldigheid start- en einddatum (op basis van RGBZ).

**Mijn idee voor de oplossingsrichting:**

Feitjes vooraf: 
1. De geldigheid start- en einddatum wordt ALLEEN gecontroleerd bij gepubliceerde zaaktypen (zoals het nu dus ook al is).
2. De einddatum geldigheid MOET inclusief zijn (zoals het nu ook al is) anders kan je een zaaktypen aanmaken dat niet geldig is bijv. vanaf 01-01-2020 tot 01-01-2020, effectief dus niet bruikbaar maar kan wel gepubliceerd zijn.

We hebben nu een zaaktype status veld met 2 waarden: [`concept` en `gepubliceerd`]. Alleen gepubliceerde zaaktypen mogen worden gebruikt bij het aanmaken van zaken MITS de geldigheid einddatum van het zaaktype niet in het verleden ligt. Dit zijn dus 2 validatiecontroles die het ZRC moet uitvoeren om uberhaupt te zien of het zaaktype gebruikt mag worden (er zijn er nog wat meer maar nu niet relevant).

Als we het status veld nu uitbreiden naar [`concept`, `gepubliceerd`, **`ingetrokken` en `verlopen`**]. 

**ingetrokken**: Zaaktype is handmatig ingetrokken en direct niet meer geldig, los van de geldigheidsrange. Dit stelt je in staat een nieuw zaaktype te publiceren vanaf dezelfde dag als het ingetrokken zaaktype.

**verlopen**: Zaaktype krijgt deze status automatisch indien het zaaktype was gepubliceerd (dus niet reeds was ingetrokken of in concept staat) en de geldigheid einddatum is bereikt.

**Dit stelt je in staat om**

* Zaaktype versie 1: Geldig van 01-01-2020 t/m 01-01-2020 met status `ingetrokken` tegelijk met
* Zaaktype versie 2: Geldig van 01-01-2020 t/m 01-01-2020 met status `gepubliceerd` te hebben
* ...en op 2 januari krijgt zaaktype versie 2 de status `verlopen`.

Dit zorgt tevens voor 1 consistente validatie op de geldigheid van het zaaktype EN lost het probleem op van een zaaktype laten ingaan op dezelfde datum als de voorgaande versie.

Het is uiteraard wel mogelijk dat er een zaak is aangemaakt met zaaktype versie 1 toen deze nog gepubliceerd was, dat valt niet te voorkomen.

**Comment by michielverhoef** [comment]
@EduardWitteveen Kun jij hier ook naar kijken?

**Comment by joeribekker** [comment]
Ik haal dit issue uit de sprint pending antwoord.

**Comment by EduardWitteveen** [comment]
**Mijn wens:**
Dat er fouten gemaakt kunnen worden bij het het inrichten van het zaaktype en dat ik niet een dag hoef te wachten met het volgende zaaktype.
Ook dat alles wat ik doe, ook het testen, via de audittrail valt te volgen: meaw. niets verwijderen ook al hebben we het foutief ingericht. Ik zie het maken van dit soort foutennml. als proces gang op laag 4/5 (business logica)  en ik wil niets verwijderen.

**In reactie op opsomming Joeri**
a. Om mij inderdaad gaat het om de zaaktypes die gepubliceerd zijn
b. Het punt dat de einddatum inclusief is moet zijn begrijp ik niet, het voorbeeld maakt het meer verwarrend.
c. Bij het voorbeeld aangedragen: 
    Ik kan me heel goed voorstellen dat er een zaaktype gepubliceerd is geweest met:
      - vanaf 01-01-2020 
      - tot 01-01-2020
    Deze zou kunnen ontstaan door de volgende volgorde (vandaag = 01-01-2020):
    1 - inrichten zaaktype met vanaf 01-01-2020 en tot 01-01-2020
    2 - bij het testen met een zaak kom je erachter dat het niet werkt
    3 - je moet dus het zaaktype aanpassen, dus een nieuw zaaktype inlaten gaan vanaf 01-01-2020
    
d. Dat er een zaak is aangemaakt met het zaktype-versie 1 (de foutieve), is in mijn ogen ook juist de bedoeling. Zo houden we de audit trail op orde

**In reactie op de oplossingsrichting Joeri:**
Als gebruiker maakt de oplossing me niet uit, wel dat het kan en dat ik het simpel kan uitleggen aan mijn omgeving.
Vanuit mijn techische achtergrond zou ik een oplossingsrichting verwachten die generiek schaalbaar is.

a. Wanneer de status wordt uitgebreid met [concept, gepubliceerd, ingetrokken en verlopen] wordt het nog complexer, hoe leg ik dit de div medewerkers uit?
  Je kan het prima met een status oplossing, maar waarom is die begin/einddatum dan nog zo fundamenteel aanwezig (dan hoef je hem ook niet meer te zetten).

b. Mij ontgaat de behoefte om de functionaliteit van een embargo op zaaktype actief te plaatsen.

c. Binnen de BAG wordt er gewerkt met tijdschakels, waarbij het ongeveer op de volgende manier werkt:
    - de begindatum mag niet in de toekomst liggen
    - de einddatum >= begindatum
    - de actuele is degene waarbij de einddatum == null of einddatum <= huidige datum
    Natuurlijk moet je deze dan wat uitbreiden met zoiets als je mag een einddatum niet zetten op een tijdstip <= laatst aangemaakte zaak van dat type.
    Dit kun je natuurlijk ook ondervangen door te zeggen dat het niet in het verleden mag liggen.
    (eventueel zou begindatum ook datum/tijd kunnen worden)

Het lijkt me belangrijk om hier een goed en generieke methodiek te gebruiken, dit komt namelijk voor met een hoop objecten die enige vorm van versie-beheer kennen.
Zoals ik aangaf, de bag is er één bekend is binnen de organisaties en die men ook begrijpt, de keuze met status is ook te begrijpen.

(meer info over bag op linkjes zoals: https://vng-realisatie.github.io/StUF-Standaarden/discussie/gemma/stuf-301-standaard/eindgeldigheid-moet-groter-zijn-dan-begingeldigheid-van  / https://vng-realisatie.github.io/StUF-Standaarden/sites/king-community/files/bijlages/stuf0301-concept.pdf / https://vng-realisatie.github.io/StUF-Standaarden/discussie/gemma/rsgb/bag-begingeldigheid-en-eindgeldigheid ) 

Nog een eerder gemaakt voorbeeldje bijgevoegd met mogelijk gedrag (en hoe de bag het volgens mij ook doet), hierbij zijn A-B en C verschillende momenten in de tijd op dezelfde dag (vandaag = 2019-11-04)  ![tijdschakels](https://user-images.githubusercontent.com/6449834/78836969-6e22a700-79f3-11ea-90a2-dab1a399db43.png) (haha, is die al zo oud?)

**Comment by Hugo-ter-Doest** [comment]
Reactie op de probleembeschrijving:
> Zaken die reeds aangemaakt zijn van die verkeerde versie van het zaaktype moeten afgesloten worden

Dat moet hoe dan ook omdat je niet zomaar het zaaktype mag aanpassen van een zaak.

Reactie op de analyse van Joeri:
> Als zaaktype versie 1 geldig is van 01-01-2020 t/m 01-01-2020 betekent dat een versie 2 alleen mag beginnen op 02-01-2020 (omdat de einddatum van de geldigheid inclusief is)

Ik denk dat dit de kern van het probleem is.

Ik stel voor dat de begindatum van een zaaktype een datum/tijd veld wordt. Daarmee is het wel mogelijk om een nieuwe versie te maken die geldig is na de oude versie.

Dit blijft dichtbij de oorspronkelijke oplossing en biedt tijdschakels zoals bij BAG. 

En introduceert bovendien geen nieuwe statussen.

**Comment by EduardWitteveen** [comment]
Met datum tijd werkt het voor mij
(wel mis ik de elegantie)
