### ISSUE TITLE
Bezoek Maykinmedia

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#159]
Tijdens de call van afgelopen vrijdag 15/6/18 is er kort gesproken om Maykin een 1/2 of hele dag te bezoeken door Michiel en andere geïnteresseerden. Goed idee zeker gezien het feit dat we op afstand werken. Vandaar actiepunt opgenomen zodat we dit niet vergeten.

**Comment by michielverhoef** [comment]
Al via Slack met Joeri en vooral Sergei besproken. Langskomen is geen probleem, we gaan morgen even kijken wie er nog meer uitleg wil en dan maken we (hopelijk) een afspraak.

**Comment by TCIMEddy** [comment]
ok sluit ik deze weer, dank!
