### ISSUE TITLE
Als potentiele gebruiker van de API's wil ik snel zien wat de voordelen zijn t.o.v. de oude standaard

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1593]
...zodat ik een afweging kan maken waarom ik de nieuwe API's moet gaan gebruiken.

- [ ] Inventariseer bij @Hugo-ter-Doest 
- [ ] Inventariseer bij @hdksi 
- [ ] Inventariseer bij @joeribekker 
- [ ] Inventariseer bij @HenriKorver
- [ ] Inventariseer bij @michielverhoef  
- [ ] Inventariseer bij anderen?
- [ ] Plaats overzicht op documentatie site

Als iedereen in een comment dit aangeeft is het snel gedaan.

_Uit overleg d.d. 31-3-2020_

**Comment by HenriKorver** [comment]
Developers vinden REST/JSON veel makkelijker en leuker dan SOAP/XML.

**Comment by HenriKorver** [comment]
De nieuwe standaard is met een AGILE werkwijze tot stand gekomen. Hierdoor zijn de wensen van de gebruikers op een veel betere manier meegenomen.

**Comment by HenriKorver** [comment]
De nieuwe standaard heeft een referentie-implementatie zodat developers concreet met de API kunnen spelen in plaats van het lezen van een papieren standaard.

**Comment by michielverhoef** [comment]
> 
> 
> De nieuwe standaard is met een AGILE werkwijze tot stand gekomen. Hierdoor zijn de wensen van de gebruikers op een veel betere manier meegenomen.

Misschien in het verlengde hiervan: 

De nieuwe standaard is op basis van functionele wensen/eisen van gebruikers en stakeholders tot stand gekomen. Hierdoor sluit deze goed/beter aan bij de wensen en eisen van de gebruikers en 
stakeholders.

**Comment by michielverhoef** [comment]
> 
> 
> Developers vinden REST/JSON veel makkelijker en leuker dan SOAP/XML.

REST/JSON sluit beter aan bij de tooling zoals deze gebruikt wordt door developers dan SOAP/XML/StUF. Hierdoor is het correct implementeren van de standaard veel eenvoudiger.

**Comment by melsk-r** [comment]
De leercurve voor de nieuwe standaard is veel vlakker waardoor er sneller resultaat mee geboekt kan worden. Een developer hoeft zich niet eerst door een flink boekwerk te wurmen.

**Comment by michielverhoef** [comment]
De API standaarden sluiten aan op de nieuwe ontwikkelingen in het gegevenslandschap waarmee gemeenten weer eigenaar worden van hun eigen informatie.

**Comment by Hugo-ter-Doest** [comment]
Voor een deel is dit verwerkt in de vergelijking met ZDS.

Als er nog andere vragen zijn graag nieuwe user story openen.
