### ISSUE TITLE
Referentie-implementatie voldoet niet aan de standaard

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1598]
# Bug
In tegenstelling tot de productie-omgeving faalt de referentie-implementatie op api-test.nl. Dat betekent dat de referentie-implementatie niet voldoet aan zijn specificatie. Je zou van een referentie-implementatie verwachten dat die te alle tijden voldoet aan de standaard, vandaar de naam "referentie-implementatie".

Dit lijkt op een omgekeerde wereld.

[![afbeelding](https://user-images.githubusercontent.com/37145898/78884571-6e568d00-7a5b-11ea-942f-324b04b07bc5.png)](https://api-test.nl)

**Comment by michielverhoef** [comment]
De RI voldoet niet aan de tests maar de vraag is even waar deze tests vandaan komen en of die ook bijgewerkt zijn? Niet om de bal naar iemand anders te spelen maar om te weten waar we het moeten zoeken..

**Comment by HenriKorver** [comment]
De tests zijn opgesteld binnen dit project (zie #1233) door @stevenbal 
Dit probleem ligt volgens mij bij de referentie-implementatie en niet bij de testscripts. Als dat niet zo is, dan hoor ik dat graag van @joeribekker of @stevenbal

**Comment by michielverhoef** [comment]
Ik bedoelde meer dat als de RI inmiddels door ontwikkeld is maar we vergeten hebben de testscripts aan te passen dat er dingen fout gaan.

**Comment by HenriKorver** [comment]
Als dat zo is dan moet @stevenbal de testscripts aanpassen. De testscripts moeten te alle tijden in overeenstemming zijn met de huidige (nu geldige versie) van de RI. Maar daar ligt volgens mij dit probleem niet.

**Comment by michielverhoef** [comment]
Ik sluit dit issue. Momenteel werken de tests ook niet maar de vraag is even of dergelijke postman tests wel zinvol zijn. We kijken nu naar mogelijkheden om Gherkin te gebruiken.
