### ISSUE TITLE
Als Developer heb ik meer componenten nodig in de de AC

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#1600]
Zodat ik het autorisatie component ook buiten ZGW context kan gebruiken (concreet zou ik het mee willen nemen in huwelijksplanner, begraven en verhuizen).

**Comment by joeribekker** [comment]
@Hugo-ter-Doest denk dat we deze conceptueel even moeten doornemen aangezien ze veel aannames over mogelijke componenten bevatten die niet in GEMMA staan.

**Comment by Hugo-ter-Doest** [comment]
Mooie user story omdat hier op meer plekken behoefte aan is, en er ook bij NLX wordt gewerkt aan autorisatie.

**Comment by joeribekker** [comment]
@Hugo-ter-Doest Ik had precies dit punt in Teams opgegooid :)

**Comment by joeribekker** [comment]
Betreft overigens PR: https://github.com/VNG-Realisatie/vng-api-common/pull/127/files

**Comment by CMasselink** [comment]
Ik heb een tijd geleden deze userstory al aangemaakt met uiteindelijk hetzelfde doel:
https://github.com/VNG-Realisatie/gemma-zaken/issues/1548

Ook gezien de discussie in Teams: 1 van deze 2 sluiten en de oplossing in 1 van de twee uitwerken?

**Comment by michielverhoef** [comment]
Aangezien issue dan de doublure is stel ik voor dit issue te sluiten en #1548  op te pakken. Inmiddels heb ik daar al Prio H aan toegevoegd, net als aan dit issue is gedaan.
