### ISSUE TITLE
Als consumer wil ik dat zaakeigenschappen een volgorde hebben...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1601]
...zodat ik deze in een user-interface in de juiste volgorde kan presenteren.

Ik ben een user-interface aan het bouwen die de zaakeigenschappen `start` en `einde` toont. Hierbij haal ik de zaakeigenschappen in bulk op via `/api/v1/zaak/{uuid}/eigenschappen`. Echter, in de volgorde zoals de API mij deze teruggeeft, wordt "einde" voor "start" afgebeeld, en dit wil ik omgekeerd.

M.i. moet je in de zaaktypecatalogus de volgorde kunnen vastleggen van de eigenschappen, zodat ik als consumer op deze waarde kan sorteren. Nog beter zou zijn als de Zaken API de eigenschappen ook in deze volgorde teruggeeft.

Er is geen werkbaar alternatief. In mijn applicatie is het qua beheer niet zinvol om een volgorde van eigenschappen te gaan opnemen voor elk zaaktype, en je kan ook niet afdwingen dat de eigenschappen in de "juiste" volgorde aangemaakt worden om eventueel daarop te steunen.

**Comment by Hugo-ter-Doest** [comment]
Lijkt me een presentatieprobleem, volgorde hoort niet thuis in de ZTC denk ik.

**Comment by sergei-maertens** [comment]
@Hugo-ter-Doest en hoe los ik dat presentatieprobleem dan op? Ik beschrijf de mogelijke workarounds en waarom ze niet haalbaar zijn :/

**Comment by michielverhoef** [comment]
Ik ben het wel met Hugo eens dat dit niet in de registratie thuis hoort. Wat misschien wel een oplossing kan zijn is dat je bij het opvragen een bepaalde volgorde of sortering kunt aangeven. 

In dit geval: Einddatum zal misschien voor Startdatum komen omdat de attributen alfabetisch gesorteerd teruggegeven worden? Het lastige is dat je allerlei verschillende volgordes kunt verzinnen en dat we niet alle mogelijk volgordes in kunnen gaan bakken. Er is altijd wel weer een nieuwe volgorde te verzinnen. 

Een mogelijkheid zou kunnen zijn het array wat je ophaalt eerst op de keys descending te sorteren. Dan krijg je mogelijk andere sorteerproblemen met andere eigenschappen. In dat geval zit er niets anders op dan eigenschappen expliciet uitvragen. Bij veel eigenschappen wordt nog wel een dingetje. Is ook wel op te lossen met een apart array van de volgorde waarin je de eigenschappen op wilt halen en daarover loopen.  Maar dit valt een beetje buiten de standaard en bovendien ben jij daar veel beter in dan ik  :-D

**Comment by sergei-maertens** [comment]
> Wat misschien wel een oplossing kan zijn is dat je bij het opvragen een bepaalde volgorde of sortering kunt aangeven.

maar die sortering is niet in programmatie uit te drukken. Je kan niet sorteren op semantische betekenis van eigenschappen in een computersysteem dat geen semantiek begrijpt...

> In dit geval: Einddatum zal misschien voor Startdatum komen omdat de attributen alfabetisch gesorteerd teruggegeven worden?

Of omdat het een toevalstreffer is, maar dan nog, als je alfanumeriek sorteert, blijft `einde` voor `start` komen, en dat ziet er voor de eindgebruiker gewoon heel erg raar en onlogisch uit.

> Het lastige is dat je allerlei verschillende volgordes kunt verzinnen en dat we niet alle mogelijk volgordes in kunnen gaan bakken. Er is altijd wel weer een nieuwe volgorde te verzinnen.

Wat je dus heel makkelijk oplost door een optioneel `volgorde` attribuut toe te voegen aan `Eigenschap` in de ZTC, laat het vooral aan de inrichters/functioneel beheer om de volgorde in te stellen. In mijn generieke ZAC ga ik ook echt niet per zaaktype een andere sorteervolgorde gaan opvragen...

> In dat geval zit er niets anders op dan eigenschappen expliciet uitvragen.

In een generieke zaakafhandelapplicatie die dus op alle zaaktypen en zaken opereert? Daar worden medewerkers van gemeentes echt niet blijer van, en de overhead van niet in bulk op te vragen zorgt ook voor een tragere user-experience en meer load op systemen die helemaal niet nodig is.

>  Is ook wel op te lossen met een apart array van de volgorde waarin je de eigenschappen op wilt halen en daarover loopen.

Ja, die volgorde wil ik dus net kunnen vastleggen.

**Comment by joeribekker** [comment]
Hoewel ik het eens ben met @Hugo-ter-Doest dat dit de scope van meta gegevens oprekt naar User Interface, moet de standaard toch zeker in dienst staan van de eindgebruiker (in welke rol @sergei-maertens dit nu vraagt voor gemeente Utrecht). Een additioneel attribuut `volgorde` zou mijn inzien zonder veel moeite opgenomen kunnen worden dus het ticket sluiten is wellicht te snel door de bocht.

**Comment by michielverhoef** [comment]
>>    Is ook wel op te lossen met een apart array van de volgorde waarin je de eigenschappen op wilt halen en daarover loopen.

> Ja, die volgorde wil ik dus net kunnen vastleggen.

Ik bedoelde dat de consumer zelf de volgorde van uitlezen van de eigenschappen bepaalt. Dus het array met eigenschappen wordt niet sequentieel (beginnen bij het begin net zo lang tot er niets meer is) doorgelopen maar op basis van de key. Die keys heb je in een ander array in de juiste volgorde staan waar je dan wel sequentieel doorheen kunt gaan.

beetje zoiets als dit (steenkolenpseudocode, ik heb nog geen koffie op):

arraySortedEigenschappen = { "startdatum", "einddatum", "vervaldatum", "penvoerder" };
arrayEigenschappen = 
  {
      "einddatum" => "01-05-2020",
     "startdatum" => "17-04-2020",
     "vervaldatum" => "01-06-2020",
     "penvoerder" => "onbekend"
  }

for (int i = 0; i++) {
  eigenschapWaarde = arrayEigenschappen[arraySortedEigenschappen[i]];
  // eventueel doe je nog iets met die waarde natuurlijk
}

Nadeel is wel dat je dan elke consumer weer de volgorde moet laten bepalen. Dat maakt het wel flexibel maar als het eigenlijk altijd dezelfde volgorde is, is dat een onnodig extra werk. Aan de andere kant, hoe vaak komt dit voor, om hoeveel eigenschappen gaat het

Maar anders moeten we dit morgen bij de samenwerkdag maar even doornemen? @Hugo-ter-Doest  en @joeribekker?

**Comment by sergei-maertens** [comment]
> Die keys heb je in een ander array in de juiste volgorde staan waar je dan wel sequentieel doorheen kunt gaan.

dat begreep ik, en dat komt neer dus op het vastleggen van de volgorde in een ander "niet nader gedefinieerd" systeem. Alleen wordt dat dus helemaal onoverzichtelijk, want dat betekent dat iemand die een zaaktype aanmaakt met eigenschappen, vervolgens in een ander systeem die volgorde moet gaan vastleggen, en dat elke keer dat er een nieuw(e versie van een) zaaktype gemaakt wordt. Daar maak je de inrichters echt niet blij mee.

**Comment by michielverhoef** [comment]
Ga je dan in een registratie vastleggen hoe de gegevens gepresenteerd moeten worden?

Ik voel er wel wat voor om je morgenochtend toe te voegen aan de call, als @Hugo-ter-Doest het er ook mee eens is en jij dat wilt natuurlijk?
