### ISSUE TITLE
Als gebruiker wil ik documenten kunnen verwijderen

### ISSUE THREAD

**Issue by FrankHarbers** [VNG-Realisatie/gemma-zaken#1602]
zodat als ik een foutje heb gemaakt (verkeerde document toegevoegd aan een zaak) ik dat zelf weer kan herstellen.
Nu kan dit niet want dan krijgen we een foutmelding

**Comment by michielverhoef** [comment]
Deze functionaliteit zit er al in:
https://documenten-api.vng.cloud/api/v1/schema/#operation/enkelvoudiginformatieobject_delete

Waarschijnlijk komt de foutmelding omdat de relatie tussen de zaak als het informatieobject nog bestaat. Die moet eerst verwijderd worden door de relatie in de Zaken API te verwijderen met https://zaken-api.vng.cloud/api/v1/schema/#operation/zaakinformatieobject_delete. Onder water wordt die relatie dan ook in de DRC verwijderd en vervolgens kan het document ook verwijderd worden.

**Comment by FrankHarbers** [comment]
Maar dan kan dat de “gewone” gebruiker toch nog niet? Ik heb het hier over de medewerker van de gemeente.

Met vriendelijke groet,



Frank Harbers

Functioneel Beheerder E





T 030 - 28 61521

f.harbers@utrecht.nl<mailto:f.harbers@utrecht.nl>

www.utrecht.nl<http://www.utrecht.nl>


Gemeente Utrecht

Informatie- en Procesmanagement

DomstadIT






[cid:image001.png@01D61274.51240630]<https://www.facebook.com/GemeenteUtrecht> [cid:image002.png@01D61274.51240630] <https://twitter.com/gemeenteutrecht>  [cid:image003.png@01D61274.51240630] <https://www.linkedin.com/company/gemeente-utrecht>  [cid:image004.png@01D61274.51240630] <https://www.utrecht.nl/nieuwsbrieven>





[Standaard]<https://www.utrecht.nl/>






Van: Michiel Verhoef <notifications@github.com>
Verzonden: dinsdag 14 april 2020 15:44
Aan: VNG-Realisatie/gemma-zaken <gemma-zaken@noreply.github.com>
CC: Harbers, Frank <f.harbers@utrecht.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [VNG-Realisatie/gemma-zaken] Als gebruiker wil ik documenten kunnen verwijderen (#1602)


Deze functionaliteit zit er al in:
https://documenten-api.vng.cloud/api/v1/schema/#operation/enkelvoudiginformatieobject_delete

Waarschijnlijk komt de foutmelding omdat de relatie tussen de zaak als het informatieobject nog bestaat. Die moet eerst verwijderd worden door de relatie in de Zaken API te verwijderen met https://zaken-api.vng.cloud/api/v1/schema/#operation/zaakinformatieobject_delete. Onder water wordt die relatie dan ook in de DRC verwijderd en vervolgens kan het document ook verwijderd worden.

**Comment by michielverhoef** [comment]
De "gewone gebruiker" (de medewerker van de gemeente) gebruikt een consumerapplicatie die op zijn beurt weer gebruik maakt van de API's. De API standaarden gaan alleen over de API's, niet over de ontwikkeling van consumer applicaties.

Een consumer applicatie kan met de aanroepen die ik hierboven beschreven heb al een document verwijderen. Wanneer een consumer applicatie deze aanroepen implementeert kan de medewerker van de gemeente het document verwijderen. De API's bieden al de services om dit mogelijk te maken, vandaar dat ik de user story weer gesloten heb.

**Comment by FrankHarbers** [comment]
Oké, Bedankt.

Met vriendelijke groet,



Frank Harbers

Functioneel Beheerder E





T 030 - 28 61521

f.harbers@utrecht.nl<mailto:f.harbers@utrecht.nl>

www.utrecht.nl<http://www.utrecht.nl>


Gemeente Utrecht

Informatie- en Procesmanagement

DomstadIT






[cid:image001.png@01D61276.FBF051C0]<https://www.facebook.com/GemeenteUtrecht> [cid:image002.png@01D61276.FBF051C0] <https://twitter.com/gemeenteutrecht>  [cid:image003.png@01D61276.FBF051C0] <https://www.linkedin.com/company/gemeente-utrecht>  [cid:image004.png@01D61276.FBF051C0] <https://www.utrecht.nl/nieuwsbrieven>





[Standaard]<https://www.utrecht.nl/>






Van: Michiel Verhoef <notifications@github.com>
Verzonden: dinsdag 14 april 2020 16:00
Aan: VNG-Realisatie/gemma-zaken <gemma-zaken@noreply.github.com>
CC: Harbers, Frank <f.harbers@utrecht.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [VNG-Realisatie/gemma-zaken] Als gebruiker wil ik documenten kunnen verwijderen (#1602)


De "gewone gebruiker" (de medewerker van de gemeente) gebruikt een consumerapplicatie die op zijn beurt weer gebruik maakt van de API's. De API standaarden gaan alleen over de API's, niet over de ontwikkeling van consumer applicaties.

Een consumer applicatie kan met de aanroepen die ik hierboven beschreven heb al een document verwijderen. Wanneer een consumer applicatie deze aanroepen implementeert kan de medewerker van de gemeente het document verwijderen. De API's bieden al de services om dit mogelijk te maken, vandaar dat ik de user story weer gesloten heb.

**Comment by sergei-maertens** [comment]
@michielverhoef maar dat mocht toch niet in het concept zaakgericht werken? Ik begreep van Arjan toen dat het niet toegestaan is om informatie te verwijderen tenzij er permanent verwijderd wordt in het kader van archivering, of heb ik dat nu helemaal verkeerd begrepen?

**Comment by sergei-maertens** [comment]
Re-open zodat het iig op sprintbord bljft staan - Michiel gaat er induiken (via Slack)

**Comment by Hugo-ter-Doest** [comment]
Als je een verkeerd document aan een zaak toevoegt, betekent dit nog niet dat het nodig is het document te verwijderen. De relatie tussen de zaak en het document moet worden verwijderd. Dat kan met een delete op ZaakInformatieObject (en vervolgens op ObjectInformatieObject). Het document blijft vooralsnog staan in de DRC.
