### ISSUE TITLE
Eigenschap.specificatie is niet verplicht volgens de API spec

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#1604]
# Bug
Volgens de API spec van het ZTC, is `Eigenschap.specificatie` niet verplicht:
![image](https://user-images.githubusercontent.com/29249171/79548457-c746a680-8095-11ea-8fcf-b84bd93bfdfd.png)

Aangezien `referentie naar eigenschap` niet meer opgenomen is hierin, zou ik verwachten dat `Eigenschap.specificatie` verplicht moet zijn.

Dit zorgt er ook voor dat de Postman tests aangepast moeten worden

**Comment by Hugo-ter-Doest** [comment]
Dat klopt, volgens de het ZTC informatiemodel moet een van de twee gegeven zijn.
