### ISSUE TITLE
Als ontwikkelteam willen we argumenten verzamelen voor en tegen het splitsen van de klantinteracties API in individuele APIs voor contactmomenten, verzoeken en klanten

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1606]
zodat we beargumenteerd kunnen afwegen of zo'n splitsing een goed idee is.

Argumenten hieronder:

**Comment by hdksi** [comment]
Pro's:
- Betere aansluiting bij architectuur van losjes gekoppelde componenten
- Flexibeler doorontwikkelen en releasen (klantcontacten voordat verzoeken klaar is) (geldt ook voor informatiemodellen).
- Hergebruik mogelijk van klanten (CRM)

Contra
- meerwerk

**Comment by joeribekker** [comment]
Opsplitsen van Verzoeken en Contactmomenten impliceert mijn inziens automatisch dat Klanten ook apart komt te staan anders krijg je een resource die in beide APIs voorkomt en er dus 2 waarheden ontstaan en/of je moet syncen en/of steeds beide bevragen voor een volledig beeld van klanten (iets wat we dus niet willen!)

Voordelen van opsplitsen

* Doorontwikkeling kan sneller want scope is beperkter
* Gebruik los van elkaar is mogelijk; Geen toegang en/of rechten nodig binnen 1 API om bijvoorbeeld alleen verzoeken, contactmomenten en/of klanten te raadplegen/aan te maken
* Herbruikbaarheid is groter

Voordelen van bij elkaar houden

* Minder technische haken en ogen om relaties in beide API's bij te houden (sync) \*
* De consumer developer experience is groter
* Minder API's is wellicht minder werk

\* Wellicht goed afstemmen of een sync van relaties wel echt nodig is. Wil je echt weten welke contactmomenten bij een verzoek horen EN welke verzoeken bij een contactmoment horen? Of is die eerste voldoende?

**Comment by Hugo-ter-Doest** [comment]
> Wellicht goed afstemmen of een sync van relaties wel echt nodig is. Wil je echt weten welke contactmomenten bij een verzoek horen EN welke verzoeken bij een contactmoment horen? Of is die eerste voldoende?

Volgens mij is de eerste voldoende. En dat is geredeneerd vanuit dienstverlening voor burgers en bedrijven.

Ander aspect is inderdaad dat klanten buiten contactmomenten en verzoeken een zelfstandige resource zijn. En dat er een relatie is met betrokkenen bij zaakgericht werken.

**Comment by hdksi** [comment]
Met aandacht voor #1611

**Comment by joeribekker** [comment]
Er is unaniem besloten tot opsplitsing van de API's in 3 stuks:

- Verzoeken
- Contactenmomenten
- Klanten

Redenatie:

- Gegevens worden los van elkaar gebruikt [door consumers]
- Specificaties moeten los elkaar kunnen evolueren
- De 3 specificaties betreffen aparte (maar gerelateerde) domeinen
- Consistentie tussen verschillende componenten is belangrijk. Het samenvoegen conflicteert met de aanpak bij Zaakgericht werken.
- Consumers en providers zijn waarschijnlijk iets meer gebaat bij 1 API. Er is voor nu besloten dat dit argument niet opweegt tegen de voordelen van opsplitsen
- De 3 API's kunnen nog steeds verwerkt worden in 1 product
- Gespiegelde relaties worden zo veel mogelijk vermeden

**Comment by rubenvdlinde** [comment]
Even ter spiegel maar hoe verhoud dit zich tot de reeds bestaande verzoeken, klanten en contact momenten api's?

**Comment by hdksi** [comment]
Welke APIs bedoel je? Die in de CG-appstore of de bestaande (beta) Klantinteracties API? Die laatste omvat omvat op dit moment drie (hoofd-)objecten: klanten, klantcontacten en verzoeken. Voortschrijdend inzicht heeft geleerd dat die niet noodzakelijkerwijs (alleen) in relatie tot elkaar van waarde zijn. Klantenobjecten zouden bijvoorbeeld ook buiten het vastleggen van contactmomenten en verzoeken kunnen worden gebruikt (informering, CRM-toepassingen). En klantcontacten en verzoeken kunnen heel goed los van elkaar gebruikt worden. Dit vraagt eigenlijk om onafhankelijke implementatie en doorontwikkeling.

Deze user story dient om de Klantinteracties API hierop door splitsing in drie APIs voor te bereiden. Los van de hierboven genoemde aandachtspunten (synchronisatie, onderhoud) is het niet de bedoeling dat naar aanleiding van deze user story de functionaliteit van de APIs verandert of wordt uitgebreid. Daar zijn andere story's voor. Los van extra verwijzingen zou de verhouding tot andere componenten naar aanleiding deze story dan ook niet moeten veranderen.

**Comment by Hugo-ter-Doest** [comment]
@HenriKorver kijkt naar autorisaties en notificaties voor de drie API's

**Comment by HenriKorver** [comment]
Yes en ik zal ook naar de audit trail kijken voor de drie API's (reminder voor mezelf)

**Comment by Hugo-ter-Doest** [comment]
Besluit voor splitsen is genomen.
