### ISSUE TITLE
Dode links in documenten

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1609]
# Bug

De documenten 'ontwerpkeuzes.md', 'ontwikkelstraat.md' en 'zds_zgw.md' in https://github.com/VNG-Realisatie/gemma-zaken/tree/master/docs/_content/architectuur bevatten dode links. De locatie https://github.com/VNG-Realisatie/gemma-zaken/tree/master/docs/_content/overige/technisch waarnaar deze links verwijzen bevat slechts het document 'index.md'.

**Comment by michielverhoef** [comment]
Dit zijn geen dode links maar links naar de pagina's zoals die gepubliceerd worden op github pages.

Het VNG Jekyll Theme maakt van deze pagina vervolgens: https://vng-realisatie.github.io/gemma-zaken/themas/achtergronddocumentatie/ontwerpkeuzes 

Het is dus niet (meer) de bedoeling om de documentatie rechtstreeks vanaf github te raadplegen maar via github pages. Jammer genoeg moeten we kiezen en dan is github pages toch iets gebruiksvriendelijker voor het oog.
