### ISSUE TITLE
Als gemeente wil ik de behandeling van een aanvraag van een straatoptreden kunnen afronden 

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#161]
zodat het dossier en status afgesloten kan worden

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by BoerBas** [comment]
creeerZaak -> (rgbz_zaak) zaakidentificatie, omschrijving, toelichting, startdatum, (rgbz_zaaktype) zaaktypeidentificatie | (rgbz_natuurlijkpersoon) burgerservicenummer, naam_geslachtsnaam, naam_aanschrijving_voorletters_aanschrijving, naam_voorvoegsel_geslachtsnaam_voorvoegsel, geboortedatum_ingeschreven_persoon

**Comment by BoerBas** [comment]
Architectuur zie #171

**Comment by ehotting** [comment]
Wacht op discussie #162

**Comment by BoerBas** [comment]
Maken een BRC

**Comment by ArjanKloosterboer** [comment]
Waar is de nadere info over deze userstory te vinden, zoals de architectuuruitwerking en de RGBZ-mapping?
Wat heeft deze userstory met het Besluitenregister te maken? Het gaat toch alleen om het afsluiten van een zaak? 
Ik heb aldus onvoldoende info om 'm te reviewen.

**Comment by TCIMEddy** [comment]
@BoerBas Wil jij de vinkjes ajb zetten en zorgen dat het formeel ready is. Ik sleep hem wel de sprint in maar moet eigenlijk wachten totdat alles afgevinkt is.

**Comment by TCIMEddy** [comment]
@joeribekker @sergei-maertens nog niet alle vinkjes zijn ingevuld (Aan Bas gevraagd) maar volgens mij waren we het wel eens dat het in sprint 4 opgepakt zou worden (aparte api discussie)

**Comment by BoerBas** [comment]
@ArjanKloosterboer klopt, excuses, was bedoelt voor andere US die nog op onhold stond. Dit gaat inderdaad alleen om het afsluiten van de zaak (-status en zetten resultaat).

**Comment by BoerBas** [comment]
@jgortmaker1 kan jij naar het vinkje 'Userstory past op wenselijk gebruik ZGW volgens GEMMA 2' kijken?

**Comment by joeribekker** [comment]
@tcimeddy @arjankloosterboer Dit is het het moment om een klap te geven in de standaard over wanneer een zaak is afgesloten.

Voorstel (wat we aanhouden als deze US opgepakt moet worden): 

1. Attribuut toevoegen aan STATUSTYPE: isEindStatus (ja/nee). Maximaal 1x ja per ZAAKTYPE.
2. Einddatum op ZAAK wordt read-only.
3. Bij het toekennen van een STATUSTYPE met isEindStatus "ja" wordt de Einddatum automatisch ingevuld met de waarde uit STATUS.datumStatusGezet.

Of de ZAAK hierna niet meer kan worden aangepast is wellicht praktisch niet handig maar zou denk ik wel het zuiverste zijn. Het is alleen technisch niet 100% af te dekken. Je kan namelijk een document toevoegen aan een zaak, zonder dat het ZRC "dit weet" aangezien de relatie (op dit moment) ligt bij het DRC.

**Comment by ArjanKloosterboer** [comment]
Goed voorstel. Doen zo. Ik zorg dat het RGBZ hierop aangepast wordt. 
De zaak en dus ook de gerelateerde documenten en besluiten zouden daarna niet meer aangepast mogen worden anders dan vanwege correctie. Dat zou dus ook een constraint op de post, put en delete van de documenten- en besluitenresource moeten betekenen. Ik ga er vanuit dat dat kan. Anders hebben we een probleem. Ook in vergelijkbare gevallen.

**Comment by joeribekker** [comment]
Top!

Discussie hierover verhuist naar: https://github.com/VNG-Realisatie/gemma-zaken/pull/351

**Comment by jgortmaker1** [comment]
de opmerking van Arjan over de constraints behoeft wat meer aandacht...
anders denken we het straks geregeld te hebben, maar leveranciers weten niet dat ze dat moeten implementeren...

@BoerBas : als je er van maakt wil ik de behandeling van de aanvraag voor een straatoptreden kunnen afronden, dan kan ik geen regeltjes in GEMMA bedenken waarom dit niet zou mogen..

**Comment by sergei-maertens** [comment]
Blok wegens #351

**Comment by TCIMEddy** [comment]
Deze staat op blok en de gerelateerde us 351 staat op review. Wat moet er nog gebeuren om blok eraf te halen. (@sergei-maertens @joeribekker voor het gemak vraag ik het hierbij aan jullie, ik kan er geen wijs uit.)

**Comment by sergei-maertens** [comment]
Laat ik aan Joeri, die is het meest bezig/op de hoogte van "zaak afsluiten" als concept

**Comment by sergei-maertens** [comment]
Architectuurschets moet af (@TCIMEddy gaat met de zweep achter mensen aan)

**Comment by TCIMEddy** [comment]
@jgortmaker1 Zou je in dit stadium ff vinkje willen zetten ajb

**Comment by jgortmaker1** [comment]
volgens mij is het lijdend voorwerp van die zweep als ongeveer enige niet ge-assigned...:-)
maargoed, ik zal een vinkje zetten...

**Comment by TCIMEddy** [comment]
@jgortmaker1 dank dat je zo korte op de bal zit. Er moet nog wel architectuurschetsje komen voor de ander us mbt straatartiest

**Comment by joeribekker** [comment]
Nu #351 is goedgekeurd kan ik technisch aan de slag :)

**Comment by ArjanKloosterboer** [comment]
En? Wat moet er nu gereviewd worden? Graag een instructie of toelichting, in aanvulling op het 'naar Review slepen'.

**Comment by joeribekker** [comment]
Dit volgt uit PR: https://github.com/VNG-Realisatie/gemma-zaken/pull/489
