### ISSUE TITLE
Als ontwikkelaar van een taakapplicatie wil ik zaken filteren op vertrouwelijkheidaanduiding

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1612]
...zodat ik enkel de data opvraag die nodig is
...met aandacht voor performance.

In mijn taakapplicatie worden permissies gekoppeld aan eindgebruikers. Eén aspect daarvan is de maximale vertrouwelijkheidaanduiding van zaken die voor een gebruiker zichtbaar zijn. Dit wil ik meenemen in mijn call (`GET /api/v1/zaken`) zodat ik niet client-side de zaken hoef uit te filteren, en er enkel relevante data uitgewisseld wordt.

Ik zie twee implementatierichtingen, met een voorkeur voor de eerste:

1. Support voor `?maximaleVertrouwelijkheidaanduiding=beperkt_openbaar`. Deze geeft alle zaken terug met een vertrouwelijkheidaanduiding `beperkt_openbaar` of _meer_ publiek (dus ook `openbaar`).

2. Support een parameter `?vertrouwelijkheidaanduiding__in=openbaar,beperkt_openbaar`. Dit betekent dat ik langs de client zelf de volgorde van publiek -> geheim moet bijhouden en de benodigde set opbouw.

Voorkeur gaat naar 1. doordat er eventueel later makkelijker meer gradaties toegevoegd kunnen worden, het semantisch is en minst verbose.

Heel los gerelateerd aan #1586, wat over zaaktypen gaat. Deze gaat over zaken.

**Comment by joeribekker** [comment]
Zie voor PR: https://github.com/VNG-Realisatie/gemma-zaken/pull/1635

**Comment by HenriKorver** [comment]
PR #1635  is nog niet goedgekeurd, zie de requested changes

**Comment by HenriKorver** [comment]
PR is nu wel goedgekeurd
