### ISSUE TITLE
Als ontwikkelaar wil ik de documentatie van de API-standaarden sneller kunnen vinden

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1613]
...zodat ik niet rond blijf klikken.

De hoofd pagina van de API-standaarden is nu:
https://www.vngrealisatie.nl/producten/api-standaarden-zaakgericht-werken

Echter, hier staat geen directe link naar de documentatie van deze standaard. Een link naar Github is te vaag, want daar staan weer heel veel links.

Onderaan de pagina op de VNG Realisatie website moet een link komen naar: https://vng-realisatie.github.io/gemma-zaken/ om de documentatie toegankelijker te maken. Eventueel aangeduid met "Ontwikkelaarsdocumentatie"

**Comment by wvnoortroxit** [comment]
Op dit moment zijn de specificaties helemaal niet te vinden. Alle links op https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/index.md leveren een 404.

Date betekent dat ik op dit moment ook niet verder kan met ontwikkeling.

**Comment by michielverhoef** [comment]
@wvnoortroxit : Om de documentatie toch beter te kunnen presenteren is deze via github pages gepubliceerd. Dit staat inmiddels ook op de voorpagina vermeld, zij het niet in chocolade letters, maar wel met link er naar toe.

De verwijzingen in de documentatie etc. zijn hierop aangepast maar dat heeft helaas tot gevolg dat ze niet meer werken wanneer je rechtstreeks vanaf Github raadpleegt.

De documentatie is te bereiken via: https://github.com/VNG-Realisatie/gemma-zaken 

Deze link is ook terug te vinden op  de startpagina van de GEMMA Zaken repository: https://github.com/VNG-Realisatie/gemma-zaken
