### ISSUE TITLE
Als implementatieadvisieur van de 'ZGW' APIs wil ik dat de naamgeving van de van de APIs aansluit bij de toepassingsmogelijkheden daarvan

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1619]
...zodat ik duidelijker aan gemeenten kan overbrengen waarvoor de APIs gebruikt kunnen worden.
...met aandacht voor het feit dat de ZGW APIs niet alleen voor zaakgericht werken gebruikt kunnen worden, maar ook daarbuiten waardevol kunnen zijn.

**Comment by Hugo-ter-Doest** [comment]
Is bekend en wordt door VNG opgepakt met een plan voor API-ontwikkeling. Idee is dat de ZGW API's als separate API's worden beschouwd en beheerd.
