### ISSUE TITLE
Als gemeente wil ik dat het genomen besluit voor de aanvraag voor een straatoptreden wordt toegevoegd aan de zaak

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#162]
...zodat het besluit door alle betrokkenen inzichtelijk is

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [x] Voldoet aan GEMMA 2.0

**Taken**
- [x] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [x] Aanleveren testdata [_verantwoordelijke_]
- [x] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [x] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [x] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**BRC**
- [x] repository aanmaken
- [x] Docker hub project aanmaken
- [x] image(s) pushen naar Docker hub
- [x] Inrichten op https://ref.tst.vng.cloud
- [x] Opnemen in `docker-compose.yml` van gemma-zaken
- [x] Opnemen in ZIT (vng-Realisatie/gemma-zaken-test-integratie#6)

**Comment by BoerBas** [comment]
genereerBesluitIdentificatie -> ...
 
voegBesluitToe -> (rgbz_besluittype) besluittypeomschrijving; (rgbz_besluit) besluitdatum, besluittoelichting, ingangsdatum, vervaldatum, vervalreden

**Comment by BoerBas** [comment]
Architectuur zie #171

**Comment by ehotting** [comment]
Nog niet ready:  Is een besluit een aparte resource (aparte API) of niet?

**Comment by ehotting** [comment]
Assigned aan paar deskundigen die het hier over eens moeten worden

**Comment by ArjanKloosterboer** [comment]
> Architectuur zie #171 

Wat is nou het proces? Ik zie er drie maar geen van drieen lijkt me het complete proces op het niveau van een bedrijfsproces.  
Wat is nou jullie architectuur? Volg je volledig het aangehaalde architectuurplaatje vanuit GEMMA?

**Comment by ArjanKloosterboer** [comment]
> genereerBesluitIdentificatie -> ...
> voegBesluitToe -> (rgbz_besluittype) besluittypeomschrijving; (rgbz_besluit) besluitdatum, besluittoelichting, ingangsdatum, vervaldatum, vervalreden


Is dit bedoeld als RGBZ-mapping? En gaan we inderdaad eerst een besluitidentificatie opvragen en dan een besluit toevoegen? Of bieden we een nieuw besluit aan, zonder identificatie, en krijgen we de acceptatie en de identificatie terug?
Je besluit is vastgelegd in een document  dat je eerst als informatieobject moet vastleggen, zie #171. Die resource is er al. Volstaat die qua inhoud voor jouw userstory?  
V.w.b. de mapping:

- v.w.b. Besluittype heb je ook Domein en RSIN nodig omdat die samen met Besluittype-omschrijving de unieke aanduiding vormen. 
- van BESLUIT heb je ook Besluitidentificatie en Verantwoordelijke_organisatie nodig (tesamen de unieke aanduiding). 
- het besluit moet je relateren aan het toegevoegde document waarin het besluit verwoord is. Dus heb je van BESLUIT.kan_vastgelegd_zijn_als.INFORMATIEOBJECT ook de identificerende attributen nodig (van INFORMATIEOBJECT dus).
- het besluit moet je relateren aan de zaak waarin het besluit is genomen. Dus heb je van BESLUIT.is_uitkomst_van.ZAAK ook de identificerende attributen nodig (van ZAAK dus).

**Comment by TCIMEddy** [comment]
@BoerBas Wil jij de vinkjes ajb zetten en zorgen dat het formeel ready is. Ik sleep hem wel de sprint in maar moet eigenlijk wachten totdat alles afgevinkt is.

**Comment by TCIMEddy** [comment]
@joeribekker @sergei-maertens nog niet alle vinkjes zijn ingevuld (Aan Bas gevraagd) maar volgens mij waren we het wel eens dat het in sprint 4 opgepakt zou worden (aparte api discussie)

**Comment by joeribekker** [comment]
@TCIMEddy Klopt, daar staat een PR voor open in https://github.com/VNG-Realisatie/gemma-zaken/pull/325

**Comment by BoerBas** [comment]
@jgortmaker1 kan jij iets roepen over 'past in Gemma 2'? Mede gezien het ontwerpbesluit rondom 'besluiten'?

@TCIMEddy Vinkjes staan...

**Comment by TCIMEddy** [comment]
@BoerBas Mijn dank is groot...

**Comment by ArjanKloosterboer** [comment]
Voordat ik m vwb RGBZ ready kan geven zou ik graag een update van de RGBZ-mapping willen zien.

**Comment by jgortmaker1** [comment]
GEMMA 2 zegt niets over waar wat wordt opgeslagen...
Maar de architectuuruitwerking stelt (zoals besproken) dat we besluiten in een apart bakje opslaan. Daar gaan we gezien de bovenstaande discussies vanuit, dus vinkje gezet...

maar ik wil in het vervolg toch graag een architectuurbeschrijving per user story om dit goed te kunnen beoordelen. 
heb ik #352 voor aangemaakt

**Comment by sergei-maertens** [comment]
@ArjanKloosterboer in #362 is hier wat gebeurt die het e.e.a. vastlegt:

> v.w.b. Besluittype heb je ook Domein en RSIN nodig omdat die samen met Besluittype-omschrijving de unieke aanduiding vormen.

In een RESTful opzet met linked data hoef je enkel naar de resource te verwijzen. Dat is zodanig geimplementeerd (en hoort dus naar het ZTC te wijzen).

> van BESLUIT heb je ook Besluitidentificatie en Verantwoordelijke_organisatie nodig (tesamen de unieke aanduiding).

Deze opmerking leidde tot de correct implementatie hiervoor in #362 :+1: 

> het besluit moet je relateren aan het toegevoegde document waarin het besluit verwoord is. Dus heb je van BESLUIT.kan_vastgelegd_zijn_als.INFORMATIEOBJECT ook de identificerende attributen nodig (van INFORMATIEOBJECT dus).

Mogelijk via [`BESLUITINFORMATIEOBJECT`](http://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/vng-Realisatie/gemma-zaken/feature/us-162-brc/api-specificatie/brc/openapi.yaml#operation/besluitinformatieobject_create) resource in BRC. Doordat deze met resource-urls werkt (want linked data), zijn de identificerende attributen niet van toepassing.

> het besluit moet je relateren aan de zaak waarin het besluit is genomen. Dus heb je van BESLUIT.is_uitkomst_van.ZAAK ook de identificerende attributen nodig (van ZAAK dus).

Ook hier werk je met de resource URL van de zaak, en niet met de identificerende attributen.

**Comment by ArjanKloosterboer** [comment]
Ik wil wel reviewen maar wat? Wat is er opgeleverd? Waar vind ik dat? Waar is de documentatie?

**Comment by TCIMEddy** [comment]
@sergei-maertens Ik ben alles op de borden aan het opruimen. Is de status review nodig correct? (zie ook opmerking Arjan)

**Comment by michielverhoef** [comment]
De functionele documentatie van wat er tot nog toe gerealiseerd is (in de verschillende referentiecomponenten) staat open ter review. Als het goed is staan ook de laatste wijzigingen nav opmerkingen van Arjan in de laatste versies van de pullrequests, mocht dat niet zo zijn, hoe krijg ik dat dan wel in orde?

**Comment by ehotting** [comment]
Een PR is een voorstel om branch B in branch A te voegen. Zolang nog niet gemerged is, kun je branch B blijven wijzigen door commits naar die branch te pushen. Dat heb jeuur geleden voor het laatst gedaan, in die commit zaten deze wijzigingen: https://github.com/VNG-Realisatie/gemma-zaken/pull/476/commits/8413a4c7d711c4e535caf4960654e5b25ccae2af

**Comment by michielverhoef** [comment]
Dat idee had ik ook dat het zo werkte, alleen kreeg uit de reacties van Arjan het idee dat hij nog naar een oude versie keek. De vraag was even of dat kwam omdat ik mijn wijzigingen niet goed doorvoerde of dat het ergens anders aan lag.

**Comment by joeribekker** [comment]
@michielverhoef @sergei-maertens Waar hangt dit issue op?

**Comment by michielverhoef** [comment]
Arjan en ik zijn nog druk bezig met het verwerken van onze nieuwe inzichten mbt functionele documentatie.  Zolang we dat nog niet af hebben wordt de documentatie niet verder gereviewed en werk ik er ook niet verder aan.  Eerst de koers bepalen voor we op pad gaan, zeg maar.

De vraag die ik me serieus stel is in hoeverre een een system API voorzien moet worden van functionele documentatie. Een proces of experience API heeft absoluut een functionele documentatie nodig maar misschien is voor een system API een goed (technisch) gedocumenteerde API genoeg? 

Dit hangt ook samen met de API architectuur van de standaard, iets waar we totnogtoe ook nog steeds zoekende en lerende in zijn.

**Comment by joeribekker** [comment]
Wow, OK!

Dan is dit wel echt een mega impediment zeg maar. Functionele documentatie staat in de DoD. Als daar niet aan wordt gewerkt, blokkeert dus alles.

Ik heb nu in Slack en op Github het onderscheid al eens voorbij zien komen tussen dit soort APIs. Zelf heb ik aan het begin ook gesproken over composite APIs (denk vergelijkbaar met process APIs). Ik maak er wel een impediment voor aan.
