### ISSUE TITLE
Als PO wil ik een referentie-implementatie van de API-specificatie voor de ContactMomenten API

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1622]
...zodat [vul aan]
...met aandacht voor [vul aan]

**Comment by joeribekker** [comment]
Zie: https://github.com/HenriKorver/gemma-zaken/tree/master/api-specificatie/DESIGN/kic

**Comment by stevenbal** [comment]
@joeribekker PR: https://github.com/VNG-Realisatie/contactmomenten-api/pull/5

**Comment by joeribekker** [comment]
Toegevoegd aan API spec in https://github.com/VNG-Realisatie/gemma-zaken/pull/1630

**Comment by HenriKorver** [comment]
Akkoord
