### ISSUE TITLE
Als PO wil ik een referentie-implementatie van de API-specificatie voor de Verzoeken API

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1623]
...zodat [vul aan]
...met aandacht voor [vul aan]

**Comment by joeribekker** [comment]
Zie design: https://github.com/HenriKorver/gemma-zaken/tree/master/api-specificatie/DESIGN/kic

**Comment by joeribekker** [comment]
Voor nu akkoord. Losse issues apart behandelen in issues.
