### ISSUE TITLE
Docker containers starten niet met Docker Desktop

### ISSUE THREAD

**Issue by wvnoortroxit** [VNG-Realisatie/gemma-zaken#1626]
# Bug

Na het uitvoeren van een docker-compose pull (en upgrade naar de laatste versie van Docker Desktop for windows) krijg ik de containers voor de zrc_db, drc_db, ztc_db niet meer goed gestart. 

In de log staan foutmeldingen over starten van de postgres database (Error: Database is uninitialized and superuser password is not specified.) en over address reslve issues (psql: could not translate host name "drc_db" to address: Name does not resolve)

In het verleden heb ik wel alle containers kunnen starten op mijn DEV-machine. De documentatie op https://vng-realisatie.github.io/gemma-zaken/ontwikkelaars/handleidingen-en-tutorials/installatie-en-configuratie biedt ook onvoldoende informatie om dit probleem op te kunnen lossen.

[start.log](https://github.com/VNG-Realisatie/gemma-zaken/files/4680524/start.log)

**Comment by michielverhoef** [comment]
@joeribekker kun jij hier naar kijken?

**Comment by joeribekker** [comment]
Even ingedoken. De foutmelding is helder, in een minor versie update van de Postgres image op Docker hub is het meegeven van een password nu verplicht. We gebruiken zelf de meta tag versie 10, maar onder water is dat (bij nieuwe docker pulls) de laatste versie binnen de major versie 10, nu 10.13.

Docker Compose aangepast met een wachtwoord parameter.
