### ISSUE TITLE
Als gemeente wil ik dat de aanvraag tbv een straatoptreden als zaak wordt gecreëerd

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#163]
...zodat ik mijn dossiervorming op orde is en de voortgang transparant is

**Links**

* Zie #199 voor een WIP procesbeschrijving

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van een goedgekeurde veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [x] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [x] Aanleveren testdata [_verantwoordelijke_]
- [x] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [x] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [x] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by BoerBas** [comment]
creeerZaak -> (rgbz_zaak) zaakidentificatie, omschrijving, toelichting, startdatum, (rgbz_zaaktype) zaaktypeidentificatie | (rgbz_natuurlijkpersoon) burgerservicenummer, naam_geslachtsnaam, naam_aanschrijving_voorletters_aanschrijving, naam_voorvoegsel_geslachtsnaam_voorvoegsel, geboortedatum_ingeschreven_persoon

**Comment by BoerBas** [comment]
Architectuur zie #171

**Comment by TCIMEddy** [comment]
@BoerBas voor de mapping van de velden is er een speciaal issue gemaakt om het in te dienen

**Comment by TCIMEddy** [comment]
@BoerBas wil je als de user story ready is ook verslepen naar ready for sprint (moet ik dan echt alles doen?)

**Comment by joeribekker** [comment]
@ArjanKloosterboer @michielverhoef @Hugo-ter-Doest 

Hiervoor wordt duidelijk een Zaak voor aangemaakt. Echter, we moeten de data specifiek over de ontheffing ergens kwijt. Volgens mij moet er een (`Zaak -> betreft ->`) `Ontheffing` gemaakt worden, maar @BoerBas vond dat dit een `InformatieObject` moest worden.

Voordat deze Ready is, wat moet er gebeuren?

**Comment by ehotting** [comment]
Ontheffing = besluit (+ representatie daarvan in de vorm van een informatieobject)

**Comment by TCIMEddy** [comment]
@BoerBas wil jij kijken of deze user story wat jou betreft echt gereed is?
@michielverhoef kun jij jouw template voor deze user story toevoegen en invullen
@jgortmaker1 nog geen vinkje gemma2
Ik reopen de user story en zet hem in kolom in progress

**Comment by ArjanKloosterboer** [comment]
Er staat aangevinkt dat het zou voldoen aan RGBZ. Heb ik niet gezet en kan ik zo niet beoordelen. Waar kan ik de documentatie vinden om te reviewen?

**Comment by sergei-maertens** [comment]
Geloof dat https://github.com/VNG-Realisatie/gemma-zaken/issues/163#issuecomment-401010595 de RGBZ-mapping was.

**Comment by BoerBas** [comment]
Mapping staat in proces documentatie, is nog wen PR. Moet dus even naar de straatarties branche.

https://github.com/VNG-Realisatie/gemma-zaken/blob/Proces-Straatartiest/docs/processen/Haarlem%20Straatartiest.md

**Comment by ArjanKloosterboer** [comment]
@BoerBas, In het document waarnaar gelinkt wordt, vindt ik geen RGBZ-mapping. Zie ik iets over het hoofd?

**Comment by TCIMEddy** [comment]
@joeribekker dit is een user story die volgens mij bijna helemaal af is behalve functionele documentatie, wellicht deze user story gebruiken voor ‘eerste voorbeeld’. (Anders haal je je naam maar weer weg :-)

**Comment by jgortmaker1** [comment]
is er al een architectuurbeschrijving?

**Comment by TCIMEddy** [comment]
@ehotting helemaal ready, alleen architectuurschets

**Comment by TCIMEddy** [comment]
PO + betrokken gemeenten willen dat deze user story conform hun wensen wordt opgepakt. Deze user story is ready verklaard (ondanks dat de vinkjes RGBZ en GEMMA niet aanstaan)

**Comment by jgortmaker1** [comment]
is er dan al een architectuurschets?
en wordt het conform architectuurdocument (zie #390)  opgepakt?

**Comment by Hugo-ter-Doest** [comment]
Dit kan al.
