### ISSUE TITLE
Catalogi API 1.0.0 heeft bij Zaaktype een uniciteit op catalogus+omschrijving ipv catalogus+identificatie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1639]
# Bug

Catalogi API 1.0.0 heeft bij Zaaktype een uniciteit op catalogus+omschrijving ipv catalogus+identificatie. Dit is incorrect gemapped vanaf het ImZTC.

Dit is een bug in de Catalogi API standaard en zou met een patch release opgelost kunnen worden.

**Comment by michielverhoef** [comment]
Dit klopt inderdaad. Volgens het RGBZ: https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/zaaktype.zaaktype-identificatie 

Deze attribuutsoort identificeert een ZAAKTYPE uniek binnen de CATALOGUS waarin het ZAAKTYPE voorkomt, ook als daarin meerdere versies - onderscheiden door Datum begin geldigheid zaaktype en Datum einde geldigheid zaaktype - van een ZAAKTYPE voorkomen.

Overigens is de omschrijving ook uniek binnen een catalogus, https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/zaaktype.zaaktype-omschrijving : 
Binnen een CATALOGUS moet de Zaaktype-omschrijving uniek zijn. De attribuutsoort verandert alleen van waarde (materiële historie) op een datum die gelijk is aan een Versiedatum van het zaaktype.

Het betreft de gelijknamige attribuutsoort bij Zaak in het GFO Zaken 2004. Binnen een catalogus heeft elke zaaktype een unieke naam, de Zaaktype-omschrijving

Mijn aanname is dan even dat er maar 1 geldig (actief) zaaktype is met een bepaalde omschrijving maar dat er meerdere niet-actieve/ongeldige zaaktypen met diezelfde omschrijving kunnen zijn. Om het correcte zaaktype uit de catalogus te halen moet dan de versiedatum ook gebruikt worden om te zoeken. Dit is niet nodig wanneer de identificatie gebruikt wordt.

Gerelateerd aan #1650
