### ISSUE TITLE
Als straatartiest wil ik dat mijn aanvraag een uniek volgnummer krijgt

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#164]
...zodat ik in mijn communicatie snel kan verwijzen naar mijn aanvraag

**Links**
[ZRC pull request](https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/13)

**API spec aanpassingen**
-geen-

**Definition of done**

- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] er is functionele documentatie conform het DSO-patroon
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [x] Voldoet aan RGBZ 2.0
- [x] Voldoet aan GEMMA 2.0

**Taken**
- [x] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [x] Aanleveren testdata [_verantwoordelijke_]
- [x] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [x] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [x] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [x] Functionele documentatie [_verantwoordelijke_]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by BoerBas** [comment]
Geen mapping nodig: uniek zaakid ontvangen

**Comment by BoerBas** [comment]
Architectuur zie #171

**Comment by joeribekker** [comment]
Volgens mij is dit de zaakidentificatie. In onze discussie is het ID voor de relevante API resource een UUID maar een zaakidentificatie kan zelf door gemeente opgegeven worden (of gegenereerd) en kan aan de straatartiest worden gegeven.

**Comment by ehotting** [comment]
Waarom wil die straatartiest een uniek volgnummer dan?

**Comment by sergei-maertens** [comment]
@BoerBas ter verduidelijking - er is geen operatie om een unieke identificatie te krijgen, het is onderdeel van de `POST /zrc/api/v1/zaken` call.

Er zijn twee mogelijkheden:

1. Genereer client-side een identificatie. Dit laat je toe om het zo human-readable te maken zoals je wil. Indien er een clash is met een bestaande identificatie, dan krijg je een HTTP 400 terug met de validatie-fout en weet de client dat een andere identificatie moet gebruikt worden. Je zou kunnen zaken filteren op hetzelfde zaaktype en zo afleiden wat de laatst gebruikte identificatie is

2. Laat het ZRC een identificatie genereren. Dit gebeurt als je zelf het veld `identificatie` leeg laat. De implementatie van het ZRC kan dan business logic bevatten die het formaat van de identificatie kent/bepaalt. In de referentie-implementatie worden hiervoor gewoon uuids gebruikt.

Om dit praktisch te houden (als bijvoorbeeld een tussenlaag tussen eindgebruiker en API de identificatie genereert) zie ik wel een behoefte de kop opsteken om:
* zaken op te vragen (met filters op zaaktype bijvoorbeeld, momenteel mogelijk als ik me niet vergis)
* de lijst (aflopend) te sorteren op `identificatie`. Dan zou je een formaat als `straatartiest-0001` kunnen gebruiken, en weet de tussenlaag wat de 'laatste' waarde was. Een nieuwe identificatie genereren wordt dan `vorige waarde + 1`, en deze business logica kan in die tussenlaag blijven bestaan, hiervan hoeven eindgebruiker-applicatie en ZRC niet op de hoogte te zijn.

**Comment by BoerBas** [comment]
ok helder

**Comment by sergei-maertens** [comment]
Is geimplementeerd, moet alleen nog door informatie-architecten goedgekeurd worden in review, dus ik verwijder mezelf als assignee.

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Wil jij deze reviewen (wellicht al gedaan, maar kan ik niet zien)

**Comment by ArjanKloosterboer** [comment]
Wat kan ik waar reviewen?

**Comment by TCIMEddy** [comment]
heb je functionele documentatie voor nodig... dus naar in progress

**Comment by ArjanKloosterboer** [comment]
Ik begrijp uit het voorafgaande dat er niets anders aangepast is dan dat een gegenereerde zaakidentificatie uniek is. Gegenereerd in de referentie-implementatie, niet in de API. En het staat beschreven in de functionele documentatie. 
Akkoord met een en ander!

**Comment by sergei-maertens** [comment]
Wordt dus getackeld in de functionele documentatie die WIP, maar volgens mij kan deze US an sich gesloten worden @TCIMEddy

**Comment by michielverhoef** [comment]
Call me stupid maar ik begrijp niet zo goed wat deze user story met de functionele documentatie te maken heeft?  Een zaak krijgt een unieke identificatie (dit staat beschreven in het RGBZ), deze wordt teruggeven na het aanmaken van een zaak. Dit staat al beschreven in de response.

Wat missen we dan nog?

**Comment by TCIMEddy** [comment]
@michielverhoef Deze stond blijkbaar nog open en als het opgenomen is in de documentatie gaat deze nu op close!
