### ISSUE TITLE
Als ontwikkelaar wil ik eenvoudig zaken met een bepaalde actuele status kunnen opvragen

### ISSUE THREAD

**Issue by paul-pfc** [VNG-Realisatie/gemma-zaken#1642]
...zodat ik dit efficient kan doen.

Bijvoorbeeld: alle zaken van een zaaktype met status 'In te plannen'.

Ik heb nu twee mogelijke ingangen:
**GET /zaken**
Via GET /zaken kan ik alle zaken van het betreffende zaaktype opvragen. In de zaak is een referentie naar de actuele status opgenomen. Vervolgens moet ik bij iedere zaak de status opvragen om het bijbehorende statustype te bepalen. Hiermee kan ik de lijst van zaken filteren om het gewenste overzicht te krijgen. Dit is niet efficient, afhankelijk van aantal zaken van dit zaaktype veel overhead. Overhead is te beperken door gebruik te maken van query parameter startdatum__gt, maar dat is mogelijk niet sluitend.

**GET /statussen**
Via GET /statussen kan ik alle statussen van het gewenste statustype opvragen. Ik kan hierbij echter niet filteren op 'actuele status' (RGBZ attribuut _Indicatie laatst gezette status_), zodat ik dit in code moet gaan bepalen (is dit de actuele status van de bkijbehorende zaak). Ook dit is niet efficient.

**Comment by michielverhoef** [comment]
Dit is meegenomen in de 1.3.0 versie: https://zaken-api.test.vng.cloud/api/v1/schema/#operation/status_read

**Comment by michielverhoef** [comment]
Nog toevoegen aan filterparameters:

zaak (url)
statustype (url)
indicatieLaatstGezetteStatus (boolean)

**Comment by michielverhoef** [comment]
Opgelost met PR  https://github.com/VNG-Realisatie/zaken-api/pull/225
