### ISSUE TITLE
In de GET van `/klantcontactmomenten` is paginering vergeten

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1646]
# Bug

Zie user story #1631

**Comment by stevenbal** [comment]
@HenriKorver is nu opgenomen in de api spec: https://github.com/VNG-Realisatie/contactmomenten-api/blob/master/src/openapi.yaml#L1512

**Comment by HenriKorver** [comment]
Akkoord

**Comment by michielverhoef** [comment]
@HenriKorver Is dit issue nu opgelost?

**Comment by HenriKorver** [comment]
Ja in de post [hierboven](
https://github.com/VNG-Realisatie/gemma-zaken/issues/1646#issuecomment-705494952) gaf ik akkoord

**Comment by michielverhoef** [comment]
Merci, dan sluit ik dit issue
