### ISSUE TITLE
drc nginx container start niet op onder windows (reproduceerbaar) 

### ISSUE THREAD

**Issue by wvnoortroxit** [VNG-Realisatie/gemma-zaken#1648]
Bij het starten van de referentie componenten met Docker Desktop voor windows geeft de nginx container de volgende foutmelding:

  [0m standard_init_linux.go:211: exec user process caused "no such file or directory"

Dit wordt waarschijnlijk veroorzaakt omdat de container gebruik maakt van file mappings. Die worden onder Windows niet ondersteund (en het gebruik ervan wordt ook onder Linux afgeraden). Zie: https://github.com/moby/moby/issues/30555

Het is ook niet mogelijk om een volume te mounten naar '/'. Ik zag dat het probleem eerder gemeld was, maar gesloten was omdat probleem niet gereproduceerd kon worden. Met deze extra info kan het wel gereproduceerd worden.

**Comment by michielverhoef** [comment]
@joeribekker Kun jij hier naar kijken? Nu is het probleem wel reproduceerbaar.
