### ISSUE TITLE
Als Consumer wil ik Zaaktypen kunnen zoeken op basis van attributen omdat ik de URL naar het zaaktype als referentie moet opnemen bij de zaak

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1650]
...omdat vanuit de consumer de URL naar zaaktype-versie relevant is om op te nemen bij het maken van een zaak. De consumer heeft kennis heeft over attributen van het Zaaktype (omschrijving, ..?) en wil op basis van een of meerdere attributen én de registratiedatum de juiste versie van zaaktype kunnen opvragen.

**Comment by michielverhoef** [comment]
Aangezien omschrijving toch verplicht is en in het RGBZ 1 de identificatie van het zaaktype was lijkt mij kunnen zoeken op omschrijving en registratiedatum voldoende om de juiste versie van het juiste zaaktype op te kunnen vragen?

**Comment by MaartenRutten** [comment]
Bij configuratie van een Consumer-app wordt een zaaktype gekozen uit de lijst met mogelijke zaaktypen. Dit is een use-case waarbij de Zaaktypen in Catalogi bevraagd worden op basis van zoekcriteria anders dan {url}. 
Zoeken op naam is dan voldoende. Maar zoeken op 'trefwoorden', 'onderwerp',...zou prettig zijn  

Na selectie van het zaaktype wordt de verwijzing vastgelegd. Maar wat kan gebruikt worden als verwijzing? : 
- {url} -> maar wat als een nieuwe versie van hetzelfde zaaktype gemaakt wordt?
- {omschrijving} -> maar wat als de omschrijving van het zaaktype gewijzigd wordt? In de huidige praktijk komt dat regelmatig voor. 
- {identificatie} - is deze gelijk voor een groep van versies van zaaktypen?

Als het antwoord op de laatste vraag 'ja' is dan is het noodzakelijk om de Zaaktypen te kunnen bevragen op basis van {identificatie}  en datum.

**Comment by Hugo-ter-Doest** [comment]
- een nieuwe versie van een zaaktype heeft een nieuwe URL. 
- als de omschrijving van een gepubliceerd zaaktype moet worden gewijzigd dan leidt dat tot een nieuwe versie (en dus een nieuwe URL)
- identificatie is inderdaad gelijk voor de versies van een zaaktype. deze mogen geen overlappende geldigheid hebben. 

De oorspronkelijke user story gaat over het kunnen filteren op omschrijving en registratiedatum. Prio hoog voor die functionaliteit.

**Comment by Hugo-ter-Doest** [comment]
En passant zag ik dat de documentatie van de precieze werking van versies bij zaaktypen tekort schiet. Zie #1584, maar dat is niet het enige. Het mechanisme is niet beschreven.

**Comment by MaartenRutten** [comment]
Als identificatie verwijst naar een functionele groep van versies van een zaaktype dan is de bevraging op 'identificatie' en 'datum' wenselijk om de van toepassing zijnde zaaktype-versie te kunnen selecteren. 
Deze bevraging is onafhankelijk van eventuele wijzigingen van de omschrijving.

**Comment by michielverhoef** [comment]
> Als identificatie verwijst naar een functionele groep van versies van een zaaktype dan is de bevraging op 'identificatie' en 'datum' wenselijk om de van toepassing zijnde zaaktype-versie te kunnen selecteren. Deze bevraging is onafhankelijk van eventuele wijzigingen van de omschrijving.

De Zaaktypeidentificatie is wat hierboven als omschrijving wordt genoemd. Zie ook https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/zaaktype.zaaktype-identificatie 

Het is dus geen UUID of record-id

Vanaf versie 1.2.0 van de Catalogi API is het mogelijk om versies van Zaaktypen op te vragen via zaaktypeIdentificatie en datumGeldigheid: https://catalogi-api.vng.cloud/api/v1/schema/#tag/zaaktypen/operation/zaaktype_list
