### ISSUE TITLE
Als architect wil ik inzicht in de verschillende manieren waarop met zaken gewerkt kan worden (zaakgericht werken, zaakgericht registreren)

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1653]
...zodat ik een afwegingskader heb om te bepalen welke manier van werken met zaken het best aansluit bij mijn behoeften.

...met aandacht voor [vul aan]

**Comment by Hugo-ter-Doest** [comment]
Is buiten de scope van het team. Gaat over de (nieuwe?) positionering van het ZGW.
