### ISSUE TITLE
Als Consumer wil ik Informatieobjecttype kunnen zoeken op basis van omschrijving en datum  

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1657]
...zodat bij het vastleggen van een Document het juiste informatieobjecttype gevonden kan worden. 
waarbij ik de aanname doe dat een 'Documenttype' te vinden is als Informatieobjecttype via de Catalogi API. 

**Scenario:**
- in een app voor aanvragen van XYZ is vastgelegd dat het internetformulier als pdf vastgelegd moet worden met 'Aanvraag' als informatieobjecttype (Documenttype)
- en er is vastgelegd dat alle geuploade bijlagen vastgelegd moeten worden met 'Bijlage' als informatieobjecttype (Documenttype)
- op moment dat de app de documenten vastlegt in bv. OpenZaak dan is de URL naar het informatieobjecttype noodzakelijk
- deze zou te vinden moeten zijn via een API-verzoek waarin 'omschrijving' en 'datum' gebruikt kan worden als selectieparameters

**Comment by michielverhoef** [comment]
Het scenario is duidelijk maar de vraag is of je bevragen bij de bron zo letterlijk moet nemen. Eerlijk gezegd zou ik zelf in de configuratie van een app de url naar het correcte zaaktype, informatieobjecttype etc. opnemen. 

Het is niet per se verplicht om bij elke nieuwe zaak de bijbehorende catalogus informatie helemaal opnieuw op te vragen.

Sterker nog, ik zou het nogal omslachtig vinden om in de app (een consumer) wel de omschrijving en datum op te nemen maar de url naar de bijbehorende typen (zaaktype, informatieobjecttype, etc.) niet. Dan doe je in mijn ogen iets heel erg niet goed als app ontwikkelaar.

**Comment by MaartenRutten** [comment]
Waarschijnlijk is er sprake van verkeerde aannames.
Mijn aanname is dat een informatieobjecttype IOT meerdere keren kan voorkomen in de Catalogus met dezelfde omschrijving.

Als dat NIET het geval is dan heb je gelijk. Dan is vasthouden van de url voor de app voldoende en kan IOT op basis van url opgehaald worden. 
Als het echter WEL mogelijk is om 2 of meer IOT's in de catalogus te hebben met dezelfde omschrijving maar met niet overlappende begin- en einddatum geldigheid, dan is bevraging van de Catalogus op basis van omschrijving/datum vanuit de app wel nodig waarbij de datum gebruikt wordt om de juiste en geldige IOT te selecteren.  

Overigens de reden waarom het IOT telkens opgehaald moet worden is om de vertrouwelijkheid van het IOT te achterhalen. Deze vertrouwelijkheid wordt toegekend aan het Document dat vastgelegd wordt.

Andere vraag:
Welke informatiebron geeft inzicht in de constraints die van toepassing zijn op gegevens in objecten van ZGW API? Met andere woorden waar had ik m'n aanname kunnen verifiëren?

**Comment by michielverhoef** [comment]
Ik ga er even van uit dat dit gaat over verschillende versies van een IOT. 

- Elke versie kan maar 1 keer voorkomen. 

- De url is een unieke identifier en voor elke versie van een type (IOT of ander type) uniek. Elke versie van een IOT heeft dus een aparte url.

- Van een IOT is er ook maar 1 geldige versie, dat is de versie waarvan de huidige datum tussen "Datum begin geldigheid informatieobjecttype" en "Datum einde geldigheid informatieobjecttype" valt. 

- Een IOT kan gekoppeld zijn aan een Zaaktype (ZT) (in theorie kan het ook voorkomen dat een IOT niet zaakgericht gebruikt wordt en dus niet gekoppeld is aan een zaaktype. Dat is in dit issue niet het geval)  . Deze relatie is op te vragen via Zaaktype-Informatieobjecttypen https://catalogi-api.vng.cloud/api/v1/schema/#operation/zaakinformatieobjecttype_list

- Door bij het ZT op deze manier de bij dat ZT behorende versies IOT vast te leggen en op te vragen krijg je altijd de correcte versies van het IOT behorend bij de versie van het ZT. De url verwijst immers naar een uniek IOT.

 
Het ophalen van een IOT om de vertrouwelijkheid te achterhalen is goed, alleen kan dat rechtstreeks via de url, dat is immers een unieke identifier. Door met de url direct, zonder omweg, een IOT op te halen kun je altijd de vertrouwelijkheid een andere eigenschappen van dat IOT opvragen. Het is dus niet nodig dit te doen via een omschrijving en een datum. Wanneer de vertrouwelijkheid (of andere eigenschap) van een IOT wijzigt komt er een nieuwe versie van dat IOT met weer een eigen url (want unieke identifier).

Informatie over de resources, constraints etc. staat in de OAS specificatie van elke API. Deze zijn te bereiken via de documentatie site: https://vng-realisatie.github.io/gemma-zaken/standaard/ 
De Cataglogi API staat bijvoorbeeld hier beschreven: https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index  . Daar vind je ook een specificatie van gedrag wat verwacht wordt van de applicatie die de API implementeert.

Overigens zie ik wel iets geks in de API specificaties (OAS): de url is niet verplicht in het antwoord van de GET operaties. Toegegeven, in theorie kun je die als consumer ook zelf samenstellen maar voor validatie is dat misschien wel nodig. Ik heb er een issue van aangemaakt: #1658 
Overigens is de url al wel beschikbaar in het antwoord, alleen is het nog optioneel.

**Comment by Hugo-ter-Doest** [comment]
Op basis van antwoord van Michiel sluit ik het issue.
