### ISSUE TITLE
url is geen verplicht gegeven in het antwoord bij het opvragen van een resource

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1658]
# Bug
Het viel me op bij de Catalogi API maar ik zie het zo 1,2,3 bij alle GET operaties waarbij 1 specifieke resource weergegeven wordt. Dit is vreemd want de url is "de lijm" waarmee alle resources aan elkaar gerelateerd worden en dit gegeven is niet verplicht in het antwoord wanneer een resource opgevraagd wordt.

In theorie kun je een url zelf samenstellen maar ik zou verwachten dat de url altijd in het antwoord opgenomen moet zijn. Al was het maar om te kunnen controleren dat je ook echt de resource teruggekregen hebt waar je naar gevraagd hebt.

Volgens mij moet de url een verplicht gegeven in het antwoord bij een GET operatie zijn.

**Comment by stevenbal** [comment]
Ik heb even hiernaar gekeken, het blijkt alleen vrij lastig om een veld zowel read only als required te maken met de library die gebruikt wordt om het schema te genereren (drf_yasg)

**Comment by michielverhoef** [comment]
zo te zien opgelost.
