### ISSUE TITLE
Responsecode 400 ontbreekt bij alle DELETE berichten

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1661]
# Bug

Voor zover ik heb kunnen zien komt in alle berichten binnen de API's voor zaakgericht werken de responsecode 400 voor behalve in de DELETE berichten.
Ik ben er niet helemaal zeker van maar ik vermoed dat dit een ommissie is. Zo niet dan hoor ik graag waarom een responsecode 400 bij een DELETE bericht niet noodzakelijk is.

**Comment by joeribekker** [comment]
HTTP 400 is een "bad request". Dit is typisch iets wat je terug krijgt als je data opstuurt die niet voldoet aan bepaalde voorwaarden (bijv. validatieregels of ontbrekende/extra attributen)

Bij een DELETE stuur je geen data mee, dus er is ook geen data niet kan voldoen. Er zijn wel een paar scenario's die kunnen optreden, maar dat geeft een andere HTTP-status code terug:

- Verwijderen met verkeerde autorisatie headers -> 403/401 Unauthorized / Forbidden
- Verwijderen van niet bestaand object (verkeerde URL) -> 404 Not Found
- Verwijderen zorgt voor een fout aan de server kant -> 500 Internal Error
- Verwijderen van het object lukt niet omdat er iets is met een ander object (gaat in tegen stateless) -> 409 Conflict
etc.

Mocht het toch voorkomen dat er WEL een 400 kan terugkomen bij een DELETE-request, dan moet 400 ook opgenomen worden in de mogelijke responses, maar meestal kan dat niet.

Ik vind het alleen een bug als een API een 400 kan teruggeven en deze staat niet gedocumenteerd.

**Comment by michielverhoef** [comment]
@melsk-r Is dit een goede uitleg? Dan ga ik dit issue sluiten.

**Comment by melsk-r** [comment]
Wat mij betreft voldoet de uitleg. Ik kan niet beoordelen of op basis van deze uitleg het terecht is dat de 400 ontbreekt bij DELETE berichten maar daar vertrouw ik op het vakmanschap van Joeri. En mochten anderen een andere mening hebben dan kunnen ze dit issue weer openen.

**Comment by michielverhoef** [comment]
De crux zit volgens hem in: Bij een DELETE stuur je geen data mee, dus er is ook geen data die niet kan voldoen. 

Alle andere dingen die fout kunnen gaan staan uitgelegd en daar komen andere codes op terug.

**Comment by narmontas** [comment]
When trying to delete a published zaaktype, what response code should be returned? 409?
The business rule prevents deleting non-concept object and OAS tests in https://github.com/VNG-Realisatie/gemma-postman-tests expects status code 204.

**Comment by michielverhoef** [comment]
409 does not sound appropriate. See also https://httpstatuses.com/409 
A 409 indicates that the user (consumer) might be able to resolve the conflict but deleting a published zaaktype is simply forbidden. See also https://httpstatuses.com/409 

As described in https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index#ztc-009 it is not allowed to delete a zaaktype that is concept=false. 

I personally would expect a 405 Not allowed error. 
"A request method is not supported for the requested resource; for example, a GET request on a form that requires data to be presented via POST, or a PUT request on a read-only resource." (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

@joeribekker Does this make sense?
