### ISSUE TITLE
Link naar code documentatie op Besluiten API RI geeft 404

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1662]
# Bug
https://besluiten-api.vng.cloud/
De link naar de code documentatie (https://besluiten-api.vng.cloud/_docs/index.html) geeft een 404

**Comment by stevenbal** [comment]
@joeribekker PR in BRC: https://github.com/VNG-Realisatie/gemma-besluitregistratiecomponent/pull/61

**Comment by michielverhoef** [comment]
Het probleem is nog niet opgelost, ik krijg nog steeds (weer?) een 404
