### ISSUE TITLE
Als developer wil ik toegang mogelijk maken tot de juiste selectielijst

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1667]
...zodat ik deze kan gebruiken bij het aanmaken van Zaaktypen.

Afgeleide van #1641 waarbij in dit ticket concrete stappen worden gezet vanwege de noodzaak.
Het minimale wordt gedaan om de huidige situatie aan te kunnen.

* [x] Voeg jaartal attribuut toe aan procesTypen resource (huidige set is 2017)
* [x] Voeg filter methode toe aan procesTypen `?jaar=2017`
* [x] Maak migratie die alle huidige data naar jaartal 2017 overzet
* [x] Update management commando om selectielijst van bepaald jaar in te laden
* [x] Release nieuwe versie
* [x] Deploy nieuwe versie naar referentielijst-api.vng.cloud
* [x] Importeer 2020 versie van selectielijst op gedeployde instantie.

**Comment by stevenbal** [comment]
@joeribekker PR voor referentieimplementatie: https://github.com/VNG-Realisatie/VNG-referentielijsten/pull/14
