### ISSUE TITLE
Hoe werkt zaakgericht werken in Common ground?

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/gemma-zaken#167]
Zaakgericht werken in GEMMA is beschreven, zie: https://www.gemmaonline.nl/index.php/ZGW_in_GEMMA_2 en meer algemeen: https://www.gemmaonline.nl/index.php/Thema_Zaakgericht_werken

Common Ground (commonground.pleio.nl) beoogt gegevens uit vakapplicaties te halen door deze te splitsen in een proces- en interactiestuk en een datadeel. 

Dit heeft consequenties voor het zaakgericht werken en de interactiepatronen.

**Comment by TCIMEddy** [comment]
Graag meer ready maken?! wat wordt er einde sprint 2 dan opgeleverd (document of presentatie ter info is ook DoD).
![schermafbeelding 2018-06-25 om 11 22 02](https://user-images.githubusercontent.com/39735549/41842595-8ecd2e98-786b-11e8-8bc5-f2b5258bf5fc.png)

**Comment by jgortmaker1** [comment]
DoD: document met beschrijving hoe zaakgericht werken in Common Ground er op hoofdlijnen uit ziet.
Met wat nader uit te zoeken/discussiepunten. En indien nodig, of indien onvoldoende consensus meerdere scenario's.

**Comment by sergei-maertens** [comment]
Dit slaat op #249 toch?

**Comment by TCIMEddy** [comment]
@jgortmaker1 @sergei-maertens Ja dit klopt Sergei, ik close deze nu. Mocht dit niet goed zijn laat het dan weten dan open ik hem weer

**Comment by jgortmaker1** [comment]
ik moet de review nog verwerken..en nog antwoorden geven op de architectuurvragen...
maar ik ga voor de vragen aparte issues maken

**Comment by jgortmaker1** [comment]
klaar voor nieuwe review

**Comment by ehotting** [comment]
Eventuele verbeteringen van het doc kunnen op basis van nieuw issue of PR, deze gaat dicht. Dank!
