### ISSUE TITLE
Een paar vraagjes over ontwerpbeslissingen uit het verleden...

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1670]
In de catalogi api is de relatie tussen Zaaktype en Eigenschap 1-n. Zie https://catalogi-api.vng.cloud/api/v1/schema/#operation/eigenschap_create. Toch is de resource `eigenschappen` niet als sub-resource binnen `zaaktypen` gedefinieerd. Weet iemand waarom?

Ook zou ik verwachten dat het veld "eigenschappen" van de resource `zaaktypen` read-only moet zijn... Ja toch?

Bovendien zou in het run-time gedrag van de Catalogi API beschreven moeten zijn dat na het toevoegen van een eigenschap aan een zaaktype (via een POST op de `eigenschappen` resource) het veld `eigenschappen` van het betreffende zaaktype automatisch ververst moet worden. Ja toch?

**Comment by michielverhoef** [comment]
> In de catalogi api is de relatie tussen Zaaktype en Eigenschap 1-n. Zie https://catalogi-api.vng.cloud/api/v1/schema/#operation/eigenschap_create. Toch is de resource eigenschappen niet als sub-resource binnen zaaktypen gedefinieerd. Weet iemand waarom?

Goede vraag, functioneel is eigenschappen ook geen aparte resource maar een groepsattribuut van zaaktype. 


> Ook zou ik verwachten dat het veld "eigenschappen" van de resource zaaktypen read-only moet zijn... Ja toch?

Dat is het ook, eigenschappen is geen onderdeel van de payload van de schrijf-operaties van zaaktypen.

> Bovendien zou in het run-time gedrag van de Catalogi API beschreven moeten zijn dat na het toevoegen van een eigenschap aan een zaaktype (via een POST op de eigenschappen resource) het veld eigenschappen van het betreffende zaaktype automatisch ververst moet worden. Ja toch?

Eigenchappen is geen veld van een zaaktype. De relatie wordt gelegd vanuit Eigenschappen en bij het opvragen van een Zaaktype runtime opgehaald en teruggegeven.
