### ISSUE TITLE
Link op de standaard-pagina naar Verzoeken API is stuk

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1678]
Link naar de Verzoeken API op 
https://vng-realisatie.github.io/gemma-zaken/standaard/
is stuk.

Komt doordat er wordt verwezen naar :
https://vng-realisatie.github.io/gemma-zaken/standaard/Verzoeken/index

Met een hoofdletter V
Moet zijn:
https://vng-realisatie.github.io/gemma-zaken/standaard/verzoeken/index

Moet zijn 

# Bug

[beschrijf de bug]

[kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)

Welke claims/payload bevat je JWT?

**Comment by michielverhoef** [comment]
Opgelost met PR #1682 
https://github.com/VNG-Realisatie/gemma-zaken/pull/1682
