### ISSUE TITLE
Waar registreren we domeinspecifieke gegevens en hoe relateren we die aan een zaak?

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/gemma-zaken#168]
**Komt voort uit user stories**
* komt voort uit #39 
* discussie is nog op meer plaatsen gevoerd..

**Omschrijving**
in RGBZ wordt de relatie tussen Zaak en OBJECT gedefinieerd. Het zegt echter niets over waar deze objecten opgeslagen moeten worden.

**Comment by jgortmaker1** [comment]
dubbel van #67 
deze gesloten

**Comment by TCIMEddy** [comment]
@jgortmaker1 deze staat alleen op done/close omdat deze dubbel is toch?

**Comment by jgortmaker1** [comment]
ja, was dat niet duidelijk?

**Comment by TCIMEddy** [comment]
@jgortmaker1 jawel maar ik wilde het zeker weten voor de demo van a.s. maandag
