### ISSUE TITLE
In een Contact resource kan ik een verwijzing naar een klant opnemen, deze relatie kan ik ook leggen via klant-contactmoment. Wat is de bedoeling?

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1684]
# Bug

In een Contact resource kan ik een verwijzing naar een klant opnemen, deze relatie kan ik ook leggen via klant-contactmoment. Wat is de bedoeling?

https://contactmomenten-api.vng.cloud/api/v1/schema/#operation/contactmoment_create  
en
https://contactmomenten-api.vng.cloud/api/v1/schema/#tag/klantcontactmomenten

**Comment by HenriKorver** [comment]
In het design staat het goed :-)

https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/DESIGN/kic/contactmomenten/openapi.yaml

**Comment by joeribekker** [comment]
Bug in de referentie, gaan we oplossen!
