### ISSUE TITLE
Zaken API: rol filterparameter heeft foute naam

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1685]
De filterarameter `betrokkeneIdentificatie__vestiging__identificatie` in de operatie `rol_list` heeft de verkeerde naam:

https://github.com/VNG-Realisatie/gemma-zaken/blob/02c4388c65968265c42223550c5bc38147385f6b/api-specificatie/zrc/1.0.x/openapi.yaml#L1605

Deze filter op identificatie van de organisatorische eenheid en moet dus `betrokkeneIdentificatie__organisatorischeEenheid__identificatie` heten.

**Comment by HenriKorver** [comment]
Inderdaad, dit is een copy-paste bugje. 
@joeribekker kun jij deze oppakken in de referentie-implementatie?

**Comment by michielverhoef** [comment]
Lijkt opgelost met https://github.com/VNG-Realisatie/zaken-api/pull/158
