### ISSUE TITLE
As a TSA developer I want to query zaken efficiently

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1686]
so that I don't overwhelm the provider with an excessive amount of API calls.

Strongly related to #1625

In the application we're developing we are connecting end-user authorizations to the `Organisatorische Eenheden` they belong to. The relevant cases have a rol to the `Organisatorische Eenheden`.

**Problem**

Currently, we do a GET request on zaken list endpoint with `?rol__betrokkeneType=organisatorische_eenheid` to filter down the results as much as possible. Then, for each result and each OE that the user is a member of, we check if there is a matching rol, which does a GET request to the rollen list endpoint with `?betrokkeneType=organisatorische_eenheid&betrokkeneIdentificatie_vestiging_identificatie=<oe id>&zaak=<zaak url>` (see also #1685 for why `vestiging`).

This blows up insanely fast - a user with access to 3 OOS that gets 10 zaken needing checking means 1000 API calls (`n_zaken ^ n_oes`).

**Solution**

Short term

Add the query filter `rol__betrokkeneIdentificatie__organisatorischeEenheid__identificatie` to the zaken list endpoint, at least until there are registrations for the OEs (if those exist, we can use `rol__betrokkene` reference).

Another approach, but more complex and a more generic solution is to add the ability to fetch objects in bulk. We could query the rollen list endpoint to get the references to the zaken, and then use that to POST to a zaken list endpoint to fetch the resources in bulk:

```http
POST https://zaken-api.vng.cloud/api/v1/zaken/_bulk HTTP/1.1
Host: zaken-api.vng.cloud
Content-Type: application/json

[
    "https://zaken-api.vng.cloud/api/v1/zaken/1c64b748-6dbc-4d68-97a6-f39063ca3b49",
    "https://zaken-api.vng.cloud/api/v1/zaken/96d04dad-fedc-4c6e-8cd2-0865bcceb251",
    "https://zaken-api.vng.cloud/api/v1/zaken/89ceb6e2-6aa5-47d6-a148-d902d050fb2e"
]
```

Long term:

A search index where this information can be indexed and retrieved efficiently.

**Comment by michielverhoef** [comment]
Ik zie verbanden met oudere userstories die eerder afgeschoten zijn:
https://github.com/VNG-Realisatie/gemma-zaken/issues/523
en vooral
https://github.com/VNG-Realisatie/gemma-zaken/issues/413

@Hugo-ter-Doest  we moeten hier eens over praten maar wat mij betreft heropenen we #413 en gaan we een goede oplossing bedenken om dit soort vragen op een eenduidige manier op te lossen.

**Comment by sergei-maertens** [comment]
Nee, ik zie de relatie eigenlijk niet. Dit gaat puur om _dezelfde_ call met andere parameters niet meermaals te hoeven uitvoeren. Niet meerdere (maar verschillende) calls hoeven uitvoeren, wat wel het onderwerp van "convenience" API is.

Als jij een convenience API hebt die mijn consumer toelaat om 1 call te doen, maar die tegen de achterliggende API's nog steeds 1000 calls doet, dan zit je alsnog met een serieuze burst tegen de achterliggende API en het wachten daarop. En die convience API moet dan maar net slim genoeg zijn om te weten wat die wel/niet in parallel kan uitvoeren. Dit moet gewoon op het niveau van de Zaken API opgelost worden zodat je het ook op een database-efficiënte manier kan queryen, anders gaat de backend ook niet schalen.

**Comment by michielverhoef** [comment]
Maar dan ga ik toch nog een beetje zeuren: Regelmatig zien we in user stories vragen om filter parameters die ontbreken. 

Is het niet veel praktischer om op alle attributen te kunnen filteren, standaard? Want op deze manier werkt "we doen alleen wat er gevraagd wordt in een user story"  eerder als een beperking voor de implementatie dan als een middel om snel een goed toepasbare standaard te maken. Hiermee bedoel ik dat we wel de API (door)ontwikkelen op basis van user stories maar dat we ook elk attribuut standaard filterbaar maken, niet alleen maar het attribuut toevoegen en wachten tot er iemand om vraagt.
@Hugo-ter-Doest ?

**Comment by CMasselink** [comment]
>Is het niet veel praktischer om op alle attributen te kunnen filteren, standaard? Want op deze manier werkt "we doen alleen wat er gevraagd wordt in een user story" eerder als een beperking voor de implementatie dan als een middel om snel een goed toepasbare standaard te maken. Hiermee bedoel ik dat we wel de API (door)ontwikkelen op basis van user stories maar dat we ook elk attribuut standaard filterbaar maken, niet alleen maar het attribuut toevoegen en wachten tot er iemand om vraagt.
@Hugo-ter-Doest ?

Ik denk inderdaad dat het sowieso goed is om attributen standaard filterbaar te maken, dat geeft de gebruiker van de API sowieso meer flexibiliteit. 
Dat staat wat mij betreft dan nog even los van gewenste functionaliteit rond (bulk) zoeken.

**Comment by sergei-maertens** [comment]
> Is het niet veel praktischer om op alle attributen te kunnen filteren, standaard?

Deze US gaat al om attributen op relaties van zaken. Als je dat met alles wil doen, be my guest, maar je gaat heel veel dood gewicht maken op die manier. Ik raad het af.

Het klinkt nu namelijk "we krijgen concrete userstories van dingen die nodig zijn, en hebben geen tijd om er iets mee te doen". Ik denk dat het aspect "we hebben geen tijd om er iets mee te doen" moet opgelost worden, en niet kort even tijd reserveren om een blanket-oplossing te bouwen waar je overhead mee maakt.

**Comment by HenriKorver** [comment]
Eens met met @sergei-maertens. Laten we de query parameter `rol__betrokkeneIdentificatie__organisatorischeEenheid__identificatie` toevoegen aan de GET-operatie van het  `/zaken` endpoint. Kleine moeite, groot plezier. Dit is in feite een query-parameter die we waren vergeten toe te voegen in user story #1625. Het is duidelijk voor @joeribekker hoe dit te doen, ik hoef daar geen API Design voor te doen lijkt me. Dus wat mij betreft is dit nu "ready for implementation" en is het aan @Hugo-ter-Doest  om dit verzoek in de sprint slepen zodat Joeri aan de slag kan.

**Comment by michielverhoef** [comment]
Zo te zien is dit issue al opgelost en opgenomen in de ZAken API.

**Comment by CMasselink** [comment]
@michielverhoef Het is dus maar beperkt opgelost, De behoefte is om op meer attributen te kunnen filteren.  Zie ook mijn mail over laaghangend fruit

**Comment by michielverhoef** [comment]
@CMasselink inmiddels zijn in de nieuwe (alpha) versies ook filters mogelijk op zo ongeveer alle attributen. Begint dat te lijken op wat nodig is?

https://documenten-api.test.vng.cloud/api/v1/schema/ 
https://zaken-api.test.vng.cloud/api/v1/schema/
https://catalogi-api.test.vng.cloud/api/v1/schema/

**Comment by michielverhoef** [comment]
Opgenomen in Zaken API 1.5.0
