### ISSUE TITLE
Als burger wil ik een melding openbare ruimte kunnen doen ...

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#169]
...zodat de gemeente deze kan behandelen.

Idee voor demonstratie: met een app melding aanbieden bij het koppelvlak. Vervolgens aantonen dat melding is geregistreerd door deze weer op te vragen (bijv. met het zoekscherm van andere demo).

**Definition of done**

- [x] er is een architectuurschets
- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [ ] ~~er is functionele documentatie conform het DSO-patroon~~ apart ticket
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [x] Opstellen architectuurschets [@Hugo-ter-Doest]
- [x] Opstellen welke velden bij een melding horen [@Hugo-ter-Doest]
- [x] Aanleveren testdata [@Hugo-ter-Doest]
- [x] Schrijven (unit) test voor referentie-implementatie [@sergei-maertens]
- [x] Implementeren in referentie-implementatie [@sergei-maertens]
- [x] Genereren/opstellen van OAS 3.0 [@sergei-maertens]
- [ ] ~~Functionele documentatie [_verantwoordelijke_]~~ apart ticket
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [CI]

**pull requests**
* https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/9
* https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/pull/13
* https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/5
* https://github.com/VNG-Realisatie/gemma-zaken/pull/245

**Comment by Hugo-ter-Doest** [comment]
Architectuurschets is [hier](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Dimpact-MOR.md) te vinden.

**Comment by sergei-maertens** [comment]
@Hugo-ter-Doest in https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Dimpact-MOR.md#benodigde-apis-per-user-story zie ik dat de melding een document/informatieobject wordt - is dit correct? Moet ik dit zien als dat de melding uit de MOR-app als geheel naar bijvoorbeeld een PDF omgezet wordt, en deze wordt in het DRC toegevoegd?

Is het dan zo dat een medewerker vertrekt vanaf dit document, en dan al dan niet beslist om deze in behandeling te nemen en er een zaak van maakt (en dan bijvoorbeeld ook de geo-coordinaten toevoegt)?

**Comment by ArjanKloosterboer** [comment]
Opmerkingen bij fieldmapping #182 geplaatst.

**Comment by joeribekker** [comment]
Een eerste opzet voor demo is gedaan in een aparte repository: https://github.com/VNG-Realisatie/gemma-zaken-demo. Screenshots staan op Slack in #demo-en-sprintreview.

De Docker in de `gemma-zaken-demo` repo werkt prima samen met de `infra` Docker. Als je deze 2 Dockers dus draait, beetje configureert, heb je werkende componenten en een demo frontend :)

**Comment by ehotting** [comment]
Super!

**Comment by sergei-maertens** [comment]
Er zijn twee items/discussies die dit nu blokkeren:

* [onduidelijkheid over roltypen/afdelingen/medewerkers verantwoordelijke voor een zaaktype](https://github.com/VNG-Realisatie/gemma-zaken/issues/182#issuecomment-408899919)

* [hoe omgaan met betrokkenen bij een zaak](https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/9#issuecomment-407882637)

**Comment by ehotting** [comment]
Beide blokkades van een antwoord voorzien na overleg met @ArjanKloosterboer. Issue van @Hugo-ter-Doest wordt nog niet volledig geaddresseerd, maar het is niet wenselijk om de attriburen van betrokkenen te dupliceren in de ZRC - zoekwensen moeten dus worden opgelost middels calls naar API's die buiten onze huidige scope liggen. Wellicht wel goed om op dit punt nu de aanhaking te zoeken met het team wat werkt aan RSGB API's.

**Comment by sergei-maertens** [comment]
In VNG-Realisatie/gemma-zaakregistratiecomponent#9 is het issue van @Hugo-ter-Doest nu ook geadresseerd

**Comment by sergei-maertens** [comment]
En de ZTC aspecten zijn in https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/5 getackled, ready for review!

**Comment by sergei-maertens** [comment]
Automatische triggers zijn iets te ijverig :-)

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Volgens mij staan alle vinkjes er en is deze echt gereed. Ik verplaats deze dus naar archief. Mocht dit niet kloppen dan hoor ik het wel
