### ISSUE TITLE
VerzoekProduct mist validaties op uniciteit van attributen (vrz-007)

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#1693]
# Bug

De resource `VerzoekProduct` uit de Verzoeken API mist validatie op uniciteit op de volgende combinaties (https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/verzoeken/index.md#vrz-007):

- `product` en `verzoek`
- `productIdentificatie.code` en `verzoek`

**Comment by michielverhoef** [comment]
Zo te zien al opgelost
