### ISSUE TITLE
Als ontwikkelaar wil ik dat de OAS specificatie gecontroleerd wordt op fouten

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1699]
...zodat ze kloppen en er meer vertrouwen in de specificatie is.

Deels gebaseerd op Haal Centraal BRP API die bepaalde checks uitvoeren (maar niet rood kleuren als het fout gaat).

- [ ] OAS lint toevoegen
- [ ] Code generatie uitvoeren
- [ ] Postman collectie generatie (willen we dit ten faveure van collecties die we zelf maken?)

**Comment by michielverhoef** [comment]
Er wordt inmiddels al enige tijd gevalideerd.
