### ISSUE TITLE
Als behandelaar wil ik op de hoogte gebracht worden dat een zaak gewijzigd is

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#17]
zodat ik een (vervolg)actie kan uitvoeren

**Comment by TCIMEddy** [comment]
@michielverhoef ik zou deze aanscherpen met hoe of wie de zaak anders dan de behandelaar heeft gewijzigd.

**Comment by jgortmaker1** [comment]
er is een vergelijkbare user story.
blokkerende architetctuurvraag: hoe kan een zaak wijzigen, zonder dat een behandelaar op de hoogte is?

Slechts in een beperkt aantal gevallen lijkt mij (zie ook AWB). Graag specificeren.

**Comment by TCIMEddy** [comment]
@jgortmaker1 Je hebt hier het label blok opgezet. Wat is de reden en geldt het nog?

**Comment by jgortmaker1** [comment]
nee de uitwerking van Marco geaft precies de goede uitzonderingen aan..

**Comment by joeribekker** [comment]
Er zijn 2 methoden om dit ticket te scopen:

1. Definitie van "Zaak" opvatten als "Zaakdossier". Een wijziging van een Document leidt (ook) tot een Zaken notificatie (zodat je je alleen hoeft te subscriben op Zaken topic. Technisch kan dit bijv. door het ZRC zich te laten subscriben op de Documenten topic.
2. Als we de scope beperken tot "Zaken API" dekken we: Zaken, Statussen en relaties met Zaken die worden toegevoegd/verwijderd. We laten dan aan consumers om te subscriben op relevante kanalen.

We gaan voor nu voor optie 2, wat in principe alles mogelijk maakt maar efficienter kan door puntje 1 (wat niet onmogelijk wordt gemaakt!)

**Comment by joeribekker** [comment]
Kapstok US #792 dekt dit af, minus de taak/afhandel-applicatie functies die out-of-scope zijn.

**Comment by michielverhoef** [comment]
Dan kan wat mij betreft dit issue gesloten worden, als #792  dit inderdaad afdekt (wat volgens mij zo is). 
@Hugo-ter-Doest  Mee eens?
