### ISSUE TITLE
Als beheerorganisatie wil ik een goed beschrijving van de devstraat

### ISSUE THREAD

**Issue by jeffreygortmaker1** [VNG-Realisatie/gemma-zaken#170]
...zodat ik kan zien wat ik met gaan beheren en hier vroegtijdig input op kan meegeven

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@kciredor Ter info

**Comment by melsk-r** [comment]
Eigenlijk is dit een userstory die veel meer tot zijn recht komt in het project API Beheer. Je zou immers zeggen dat dit opgenomen moet worden als acceptatiecriterium voor in beheername.
Aan de andere kant moet dit er juist al veel eerder zijn zodat beheer zich kan voorbereiden op in beheername. Opname in de acceptatiecriteria zorgt er voor dat het er i.i.g. komt maar hoe zorgen we er voor dat het er op tijd is. 
En hoe zorgen we er voor dat hierin ook bij toekomstige standaarden wordt voorzien.

**Comment by Hugo-ter-Doest** [comment]
Ik stel voor dat we overdragen met een beschrijving van de devstraat.

**Comment by TCIMEddy** [comment]
@joeribekker @sergei-maertens Is hier beschrijving voor (is het nodig?)

**Comment by TCIMEddy** [comment]
Staat op backlog van beheer dus hier close
