### ISSUE TITLE
Als medewerker in het KCS of zaaksysteem wil ik zaken kunnen filteren op 'einddatum'

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/gemma-zaken#1700]
...zodat ik alleen openstaande zaken in een lijst kan tonen
...met aandacht voor 3 uitkomsten:
1. filter met lege einddatum => alleen openstaande zaken in het resultaat;
2. filter met gevulde einddatum (in lijn met filteren op startdatum) => alleen afgehandelde zaken in het resultaat; of
3. filter zonder einddatum (default query) => openstaande en afgehandelde zaken in het resultaat.

**Comment by michielverhoef** [comment]
opgelost in Zaken API 1.3:  https://zaken-api.test.vng.cloud/api/v1/schema/#tag/zaken/operation/zaak_list
