### ISSUE TITLE
HTTP statuscode 503 niet gespecificeerd in de OAS-specificaties?

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1708]
In de OAS specificaties van de ZGW API's wordt de HTTP statuscode 503 (Service Unavailable) niet gespecificeerd. In HaalCentraal doen ze dat wel. Is er een reden waarom we dat hier niet doen?

**Comment by sergei-maertens** [comment]
Verschillende componenten kunnen deze 503 genereren - typisch krijg je dat als de backend niet bereikbaar is. Kubernetes zelf bijvoorbeeld geeft ook een 503 response terug als de pods niet beschikbaar zijn.

Het probleem daarbij is dat je geen garanties kan geven hoe de response body eruit ziet. Vaak is dat zelfs niet eens JSON meer - hangt er van af hoe Traefik/Nginx/... geconfigureerd zijn.
