### ISSUE TITLE
Als behandelaar wil ik een document toevoegen aan de zaak

### ISSUE THREAD

**Issue by wishalg** [VNG-Realisatie/gemma-zaken#171]
...zodat ik mijn dossiervorming op orde heb

**Links**
[integratietests PR](https://github.com/VNG-Realisatie/gemma-zaken-test-integratie/pull/5)

**API spec wijzigingen**
-geen-

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [x] Voldoet aan RGBZ 2.0
- [x] Voldoet aan GEMMA 2.0

**Taken**
- [x] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [x] Aanleveren testdata [_verantwoordelijke_]
- [x] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [x] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [x] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by BoerBas** [comment]
(GenereerInformatieobject identifcatie) > ... id terug

(Informatieobject) zaakid, informatieobjectid, omschrijving, creatiedatum, titel, beschrijving, formaat, taal, versie, status, vertrouwlijkheidsaanduiding, auteur, inhoud.

**Comment by BoerBas** [comment]
[Architectuuruitwerking staatartiest.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/2145454/Architectuuruitwerking.staatartiest.docx)

**Comment by ehotting** [comment]
Let op hier is nog hoop discussie over:
- Samengesteld informatieobject
- Kent Zaak Document of andersom
- CMIS

Zie o.a. #166

**Comment by joeribekker** [comment]
Volgens mij hoort de comment die ik bij #163 maakte ook hier. De discussie kwam voor in een gezamenlijke meeting en wilde de meningen niet verloren laten gaan.

> Hiervoor wordt duidelijk een Zaak voor aangemaakt. Echter, we moeten de data specifiek over de ontheffing ergens kwijt. Volgens mij moet er een (Zaak -> betreft ->) Ontheffing gemaakt worden, maar @BoerBas vond dat dit een InformatieObject moest worden. Ontheffing komt overigens niet in het ZRC maar in een "Overige Registratie Component" voor nu.

> Voordat deze Ready is, wat moet er gebeuren?

**Comment by ArjanKloosterboer** [comment]
Of is het verstandiger om vooralsnog uit te gaan van de andere situatie: de inhoud van een Informatieobject is vastgelegd in één of meer bestanden cq. Enkelvoudige informatieobjecten (een email met bijlagen, een vergunningaanvraag met situatieschets en sterkteberekening als bijlagen). Feitelijk de situatie van het Samengesteld informatieobject. Dan zien we later wel hoe we het mogelijk maken dat één van die bestanden ook als zelfstandig Informatieobject een rol speelt in een andere zaak (de externe adviseur sterkteberekening die die sterkteberekening controleert).

**Comment by ArjanKloosterboer** [comment]
Wat is nu de - voorlopige - beperking of zelfs afwijking tov het RGBZ? Alleen een resource enkelvoudigeInformatieobjecten? En wordt die dan aan de zaak gerelateerd, in  tegenstrijd met het RGBZ? Of ook een resource informatieobjecten die dan aan de zaak gerelateerd wordt? En in welke Api en hoe wordt de relatieklasse Zaakinformatieobject vooralsnog geïmplementeerd? Als we dergelijke keuzes niet helder documenteren weten we niet waar nog nader over nagedacht moet worden en waar de Apis nog verbeterd moeten worden.

**Comment by sergei-maertens** [comment]
@ArjanKloosterboer en [hier](https://ref.tst.vng.cloud/drc/api/v1/schema/) kan je de AP spec resources bekijken.

* [enkelvoudiginformatieobject](https://ref.tst.vng.cloud/drc/api/v1/schema/#operation/enkelvoudiginformatieobject_read)
* [zaakinformatieobject](https://ref.tst.vng.cloud/drc/api/v1/schema/#operation/zaakinformatieobject_read)

**Comment by ArjanKloosterboer** [comment]
@sergei-maertens, Wat ik me afvraag is of de relatieklasse ZAAKINFORMATIEOBJECT wel in een resource uitgewerkt moet worden. Als resource krijgt 'ie een UUID terwijl kenmerkend voor een relatieklasse is dat het geen zelfstandig iets is, het betreft kenmerken van een relatie. Een relatieklasse bestaat bij de gratie van de aanwezigheid van de twee gerelateerde objecten, i.c. ZAAK en INFORMATIEOBJECT. Is één van beide er niet (meer), dan is de (instantie van de) relatieklasse weg! 
M.i. moeten we dus nog 's even goed nadenken hoe we relatieklassen in API's verwerken. Een andere uitwerking (bijv. analoog aan die van een repeterende gegevensgroep) zou in kunnen houden dat voor het leggen van de relatie alleen de zaak hoeft te bestaan en dat de relatie gelegd wordt bij het toevoegen van het informatieobject (i.p.v. dat eerst beide moeten bestaan).

**Comment by sergei-maertens** [comment]
@ArjanKloosterboer ik had het hier gisteren met @zomwoof over - dit is een noodzaak door de keuze om micro-services toe te passen. Als alles in 1 database leeft, dan kun je eenvoudig de tabellen joinen en bij ZAAK en INFORMATIEOBJECT een lijst naar de gerelateerde INFORMATIEOBJECTen en ZAAKen geven. Wanneer de data over twee databases verdeeld wordt, moet je expliciet ergens die relatie ontsluiten, om de relatie aan te kunnen maken of verbreken tussen twee objecten.

Dit is precies waarom ik blijf beweren dat het many-to-many karakter _wel_ relevant is - in databases kan je dit ook niet bewaren zonder een tussentabel. Dit is wel heel karateristiek om de relatie als resource te onsluiten in RESTful APIs.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest dit kan toch? Zo ja close
