### ISSUE TITLE
Token tool werkt niet

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1713]
# Bug
Zie https://zaken-auth.vng.cloud. 

Als ik op de button Volgende druk krijg ik een Bad Gateway error melding

![afbeelding](https://user-images.githubusercontent.com/37145898/97779725-35f5d800-1b80-11eb-948c-355cdfb6aa71.png)

**Comment by HenriKorver** [comment]
@Hugo-ter-Doest @michielverhoef Waarom heeft dit geen prio? Je kunt nu geen token meer genereren om toegang te krijgen tot de hosted versie van de referentie-implementatie. Lijkt mij toch een serieus probleem

**Comment by michielverhoef** [comment]
Ik heb er een prio zeer hoog van gemaakt maar je kunt je afvragen waar dit thuis hoort, bij het (door)ontwikkelen en beheer van de standaard of bij het beheer van het API Test Platform.  Persoonlijk neig ik naar dat laatste maar daar moeten we het nog maar eens over hebben.

**Comment by HenriKorver** [comment]
Dank voor de hogere prio, maar wat heeft dit te maken met het API Test Platform?

**Comment by michielverhoef** [comment]
Zojuist getest, bij mij werkt het en ik krijg geen fouten dus ik sluit dit issue.

Mocht het alsnog niet (meer) werken dan graag weer een issue openen.
