### ISSUE TITLE
Wijzigen van de waarde van een zaakeigenschap?

### ISSUE THREAD

**Issue by paul-pfc** [VNG-Realisatie/gemma-zaken#1714]
Waarom is het alleen mogelijk om een nieuwe zaakeigenschap aan te maken en biedt de Zaken API geen mogelijkheid om de waarde van een bestaande zaakeigenschap te wijzigen (of te verwijderen)?

**Comment by michielverhoef** [comment]
Hier lijkt inderdaad iets niet te kloppen.

Het is mogelijk een zaakeigenschap toe te voegen in de ZTC maar bij het aanmaken van een zaak lijk het niet mogelijk om deze eigenschappen ook aan te maken/vullen.  Dit geldt ook voor het (deels) bijwerken van de zaak, dan kan het ook niet. De eigenschappen worden echter wel teruggegeven bij het opvragen van een zaak.

Ik heb hiervan bug #1727  aangemaakt!

**Comment by paul-pfc** [comment]
Top!
