### ISSUE TITLE
het gewenste formaat en soort inhoud van de functionele documentatie is niet duidelijk.

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#172]
# Impediment

Ik worstel nog met de functionele documentatie. Suggestie van Eelco was om te kijken naar de DSO documentatie. Daar zie ik verschillende formaten en uitvoeringen. Dit varieert van een uitgebreid wollig verhaal tot een architectuurschets zoals Jeffrey die eerder deze week rondstuurde.
Wat is een handig formaat en invulling van de functionele documentatie?

https://pre-dso.iprox.nl/cmis/asset/site-13/item-323-v83/functionele_documentatie_registratie_omgevingsdocumenten_afnamepunt_api_v1.pdf
http://bp4mc2.org/modelleringswijze/

**Comment by TCIMEddy** [comment]
@ehotting is dit vanuit PO-perspectief het goede formaat?

**Comment by ehotting** [comment]
Ik zou 1 document per API doen, beginnen met een structuur en lichte vulling, en dit uitbreiden met wat we weten gedurende de sprints.

- Onderwerp
- Doel en doelgroep
- Gerelateerde documentatie
- Functionaliteit
- Plaats in de GEMMA
- Relaties met andere API’s

Zou er nu nog geen .pdf van maken maar een .md file op een logische plek in de repository. In een latere sprint kunnen we dan zorgen dat automatisch een .pdf wordt gegenereerd iedere keer wanneer een commit plaatsvindt op die .md

**Comment by TCIMEddy** [comment]
@michielverhoef volgens mij is er overeenstemming over hoe het opgepakt en uitgevoerd moet worden. Daarom close. Mocht dit niet correct zijn dan hoor ik het wel!
