### ISSUE TITLE
Het is niet mogelijk om de zaakeigenschappen  van een zaak te wijzigen of te verwijderen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1727]
Zie ook #1714 

Het is mogelijk een zaakeigenschap toe te voegen in de ZTC maar lijk niet mogelijk om deze eigenschappen ook aan te passen of te verwijderen.  De eigenschappen worden echter wel teruggegeven bij het opvragen van een zaak.

**Comment by michielverhoef** [comment]
NB. Bij het updaten van de eigenschappen moet ook het verwijderen van (de waarde van) een specifieke eigenschap meegenomen worden!

Bij het verwijderen van een zaak als geheel worden de eigenschappen al verwijderd dus dat lijkt al goed te gaan.

**Comment by paul-pfc** [comment]
Aanmaken van een zaakeigenschap kan overigens wel, met POST zaken/{uuid}/zaakeigenschappen.
Wijzigen van de waarde of verwijderen kan echter niet, er is geen PUT/PATCH/DELETE zaken/{uuid}/zaakeigenschappen/{uuid}

**Comment by michielverhoef** [comment]
Ik had even over het hoofd gezien dat het zaakeigenschappen endpoint onder het zaken endpoint zat. Ik ga de titel van dit issue aanpassen!

**Comment by sergei-maertens** [comment]
Dit wordt ook op korte termijn belangrijk voor Gemeente Utrecht om zaakgegevens te kunnen bewerken - bewerk/verwijder functionaliteit ontbreekt nu dus.

**Comment by paul-pfc** [comment]
Waarom is Zaakeigenschap overigens ook niet een root resource, net als Status en Resultaat?
In dat geval zou je de volgende operaties krijgen:
POST /zaakeigenschappen
GET /zaakeigenschappen
GET /zaakeigenschappen/{uuid}
PUT /zaakeigenschappen/{uuid}
PATCH /zaakeigenschappen/{uuid}
DELETE /zaakeigenschappen/{uuid}

**Comment by sergei-maertens** [comment]
We hebben dit nodig voor Gemeente Utrecht om zaakgegevens te kunnen bewerken - enige statusupdate wanneer dit komt?

**Comment by sergei-maertens** [comment]
@michielverhoef de patch met API schema wijzigingen staat in https://github.com/VNG-Realisatie/zaken-api/pull/195/files - ik heb deze gereviewed op techniek & de build gefixed.

Is er een indicatie wanneer jullie dit kunnen beoordelen & releasen?

**Comment by sergei-maertens** [comment]
@paul-pfc dit was cfr. de DSO API Strategie dat resources die enkel zinvol zijn binnen de context van de parent-resource genest zouden voorkomen. Hier wordt in een aantal situaties al van afgeweken om efficient in bulk voor een lijst van zaken bijvoorbeeld resources te kunnen opvragen.

Ik ben het op zich wel eens dat dit wel een root resource kan worden.

**Comment by sergei-maertens** [comment]
Hetzelfde probleem doet zich ook voor bij ZaakObjecten resource

**Comment by michielverhoef** [comment]
> Is er een indicatie wanneer jullie dit kunnen beoordelen & releasen?

Dit moet in ieder geval ook voorgelegd worden aan de andere gemeenten, in ieder geval die in de functionele gebruikersgroep. Ik verwacht geen problemen en dan zou dit met de volgende release (1.2, verwacht in september) mee kunnen.

> Ik ben het op zich wel eens dat dit wel een root resource kan worden.

Dat is dan een breaking change. Heb ik ook geen moeite mee maar dan wordt het een 2.0 versie.  Dat gaat wel wat langer duren.

**Comment by sergei-maertens** [comment]
Ik verwacht eigenlijk dat de toevoeging van de DELETE en PUT operaties in een patch release van 1.0 komen omdat dit een defect is wat eenvoudig kan opgelost worden.

Open Zaak bijvoorbeeld implementeert de 1.0.x versies en als we moeten wachten tot 1.2 van de standaard uit is, dan duurt het echt nog maanden voor er überhaupt nagedacht kan worden over dit implementeren in Open Zaak & de implementatie zelf omvat veel meer en vertraagt de beol. Als het een patch release is op 1.0, dan spreken we over dagen/weken om dit in Open Zaak te fixen.

**Comment by michielverhoef** [comment]
Een patch is het oplossen van een fout in bestaande functionaliteit van de standaard. Toevoegen van nieuwe operaties is weliswaar backwards compatible maar voor een minor release. Het is immers iets nieuws, een toevoeging. 

Weliswaar is het ontbreken van de mogelijkheid om zaakeigenschappen bij te werken een functioneel gebrek. Het is geen fout in de huidige functionaliteit van GET en POST operaties. Die operaties doen wat ze moeten doen en daar zitten geen fouten in.
