### ISSUE TITLE
Als gemeente Delft wil ik weten hoe ik kan aansluiten op Common Ground - ZDS

### ISSUE THREAD

**Issue by RitaBerghuis** [VNG-Realisatie/gemma-zaken#173]
...zodat ik gebruik kan maken van deze standaard en bij kan dragen aan nieuwe ontwikkelingen hier aan.

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@RitaBerghuis Volgens mij kan deze naar done en gesloten worden

**Comment by RitaBerghuis** [comment]
@TCIMEddy Klopt
