### ISSUE TITLE
Limiet aantal karakters voor eigenschaptype naam & catalogi-domein

### ISSUE THREAD

**Issue by TjerkVaags** [VNG-Realisatie/gemma-zaken#1732]
Zowel eigenschaptype.naam (max 20 karakters) als catalogi.domein (max 5 karakters) hebben een limiet aantal karakters. Waar is dit op gebaseerd?

Vooral eigenschaptype.naam is vreemd aangezien vanuit GEMMA er eigenschappen gedefinieerd zijn die meer karakters bevatten. Bijv. zaaktype 'incident melding behandelen' bevat eigenschap 'Organisatie van ontvangst'. 
Voor catalogi.domein kan ik mij voorstellen dat 5 karakters ook te weinig zijn aangezien de catalogi.naam vanuit de API niet opgeslagen wordt in Open Zaak beheer en ook dus niet op te halen valt met een GET.

**Comment by sergei-maertens** [comment]
Komt uit ImZTC

* `Catalogus.domein`:  https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/catalogus.domein
* `Eigenschap.naam`: https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/eigenschap.eigenschapnaam

**Comment by michielverhoef** [comment]
> Vooral eigenschaptype.naam is vreemd aangezien vanuit GEMMA er eigenschappen gedefinieerd zijn die meer karakters bevatten. 

Welke in de GEMMA gedefinieerde eigenschappen zijn dat dan?
Een eigenschap is volgens het RGBZ: 
Een relevant inhoudelijk gegeven dat bij ZAAKen van dit ZAAKTYPE geregistreerd moet kunnen worden en geen standaard kenmerk is van een zaak. 

Het moet mogelijk zijn om een semantische naam van een eigenschap in 20 karakters op te nemen. Een eventuele uitgebreidere beschrijving kan in de definitie en toelichting gegeven worden. 

>Voor catalogi.domein kan ik mij voorstellen dat 5 karakters ook te weinig zijn aangezien de catalogi.naam vanuit de API niet opgeslagen wordt in Open Zaak beheer en ook dus niet op te halen valt met een GET.

https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/attribuutsoort/catalogus.domein
In de toelichting staat:
Voor de waardenverzameling wordt door KING een waardenlijst beheerd waarin wordt bijgehouden welke afkorting welk domein betreft.

Over het gedrag van OpenZaak doe ik geen uitspraak maar aangezien het een vaste lijst met waarden van afkortingen beheerd door VNG Realisatie betreft moet dit goed gaan.

**Comment by sergei-maertens** [comment]
> Voor de waardenverzameling wordt door KING een waardenlijst beheerd waarin wordt bijgehouden welke afkorting welk domein betreft.

Ja, deze zin is op wel meerdere plaatsen te vinden en als je dan gaat navragen waar deze waardenlijst staat of wat de inhoud ervan is, dan blijkt die vaak niet te bestaan.

Deze lijsten zijn overigens uitstekende kandidaten om in een door VNG-beheerde API te onsluiten daar het toch maar alleen lezen is, en dan het hele land dezelfde waardenlijst kan gebruiken wat nu niet het geval is, en dan is er ook eindelijk duidelijkheid, vindbaarheid en transparantie over wat nu eindelijk eens de waarden in deze lijsten zijn.
