### ISSUE TITLE
Autorisaties API, applicatie entity clarification

### ISSUE THREAD

**Issue by aurimasroxit97** [VNG-Realisatie/gemma-zaken#1733]
In autorisaties API, applicatie has a list of autorisaties. This autorisaties entity has a field called "componentWeergave" on the response, but not on request.

My question is - where do the values come from for this field? Thanks!

**Comment by sergei-maertens** [comment]
@aurimasroxit97 this is the label aspect of this mapping: https://github.com/VNG-Realisatie/vng-api-common/blob/master/vng_api_common/constants.py#L291
