### ISSUE TITLE
Als ontwikkelaar wil ik dat alle verplichte TMLO attributen aanwezig zijn

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1734]
...zodat ik kan archiveren.

Bij het mappen van TMLO (voor Delft) op de API's kwamen er een paar puntjes naar voren:

* Archiefclassificatie -code en -bron ontbreken op het Zaaktype in de Catalogi API. (Element nummer 5.1 en 5.3 uit TMLO)
* Het is volgens mij niet mogelijk om gemakkelijk alle historie van een document op te vragen. Dit kan nodig zijn om de ontstaansgeschiedenis vast te leggen (Element nummer 12.1 in TMLO)
* Documenten kunnen zonder Zaak relatie ontstaan. Er zijn geen attributen op het document die archivering bewaken (Element nummer 13.1 en 21.8)

Ik heb als uitgangspunt genomen, dit document: https://www.gemmaonline.nl/images/gemmaonline/6/6d/KING_-_Vergelijking_TMLO_1.1_-_RGBZ_2.0_-_versie_0.9_20150901_-_met_opm_RGBZ_1.0.pdf

**Comment by erikdelepper** [comment]
Zouden we niet moeten focussen op MDTO, de opvolger van TMLO?

**Comment by michielverhoef** [comment]
Dat is een lastige, MDTO is nog in ontwikkeling dacht ik? Bovendien verwacht ik dat de TMLO attributen die Joeri bedoelt ook in MDTO aanwezig zullen zijn?

@hdksi Kun jij hier meer over zeggen?

**Comment by erikdelepper** [comment]
Dat klopt, maar ik heb begrepen dat MDTO wel zijn eindfase nadert. het is dus meer een questie van timing. Het zou zonde zijn we dadelijk met een nieuwe versie van de ZGW API's komen die al meteen verouderd is.

**Comment by michielverhoef** [comment]
Goed punt! @hdksi zou hier het verlossende woord moeten kunnen zeggen?

**Comment by hdksi** [comment]
De presentatie van de 1.0-versie van MDTO is gepland voor het eerste kwartaal van volgend jaar. Met aan zekerheid grenzende waarschijnlijkheid keren 'classificatie' en 'event(geschiedenis)' in MDTO terug.

Waar we wat mij betreft goed over moeten nadenken is of we metagegevens voor informatie-/archiefbeheer nog volgens RGBZ-conventies willen vastleggen om die later te converteren zoals het gelinkte document voorstelt. Ik zie er meer in om vanaf eerste vastlegging de MDTO-conventies te volgen. Dit maakt het mijns inziens makkelijker om later oplossingen voor informatiebeheer te ontwikkelen die ook buiten het zaakgericht werken kunnen worden toegepast.

De opmerking over documenten is terecht. Hetzelfde geldt volgens mij voor besluiten. Ik denk dat we er uiteindelijk niet aan ontkomen in alle API's die objecten die zonder relatie met een zaak kunnen bestaan beschikbaar stellen metadata voor duurzame toegankelijkheid op te nemen. Uiteraard moeten die, als dat mogelijk is, vanuit een zaak kunnen worden overerfd.

Welke metagegevens dit precies moeten zijn is de vraag. MDTO is wat dat betreft 'vrijer' dan TMLO; het aantal verplicht vast te leggen metagegevens wordt sterk beperkt. Dit betekent echter ook dat de verplichte MDTO-set niet per se voldoende is om aan eisen/verplichtingen ten aanzien van informatie- en archiefbeheer te voldoen.

Om te bepalen welke set metagegevens voor duurzame toegankelijkheid dan wel _in ieder geval_ moet worden vastgelegd, moeten we eerst weten welke functionaliteit we in het kader van duurzame toegankelijkheid nodig hebben. Verschillende kaders gegeven wel richting (zie de user stories rondom NEN 2082 - https://github.com/VNG-Realisatie/gemma-zaken/issues/364) maar zijn niet voldoende eenduidig, duidelijk en concreet.

Er zijn op dit moment twee groepen bezig uit te zoeken hoe we de voor informatie- archiefbeheer benodigde functionaliteit eenvoudiger kunnen beschrijven: één op basis van de bestaande eisen aan GEMMA referentiecomponenten in het kader van 'grip op informatie', en één naar aanleiding van implementatie van Open Zaak. Ik hoop dat we in de eerste helft van 2021 de uitkomsten hiervan naast een definitieve MDTO-versie kunnen leggen om zo een 'minimale metadataset' te beschrijven die we vervolgens in relevante API-specificaties kunnen opnemen.

**Comment by michielverhoef** [comment]
@SonnyBA  alle verplichte elementen zijn onderdeel van #1847
