### ISSUE TITLE
Als ontwikkelteam willen we dat referentieimplementaties een consequente en herkenbare naam hebben 

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1735]
zodat onder andere geen verwarring ontstaat met GEMMA-referentiecomponenten.

Nu zien we zowel namen volgens GEMMA-conventie (Documentregistratiecomponent) en namen die de naamgeving van de API volgen (Klanten API).

**Comment by michielverhoef** [comment]
Inmiddels zijn de repositories hernoemd en heten ze hetzelfde als de API die ze bieden. Dus Zaken API, Documenten API etc.
