### ISSUE TITLE
'Bepaling brondatum archiefprocedure'-gedeelte in het Resultaattype werkt niet

### ISSUE THREAD

**Issue by OlavAllema** [VNG-Realisatie/gemma-zaken#1741]
# Impediment
In een resultaattype kan je een 'Bepaling brondatum archiefprocedure'-gedeelte inrichten om de zaak te laten vervallen n.a.v. het belang van een 'afleidingswijze brondatum'. Laat ik eerst vragen:
1. Werkt dat al? 
2. Of werkt het niet? En, betekent het in dat geval dat we op dit moment zelf (in onze app) met de metadata aan de gang moeten om de archiefprocedure van deze zaken werkend te krijgen?

Het gaat om dit gedeelte van een resultaattype:
![image](https://user-images.githubusercontent.com/75848616/101923447-b1ab6180-3bcf-11eb-960f-b021ab937f75.png)

We hebben uiteraard getest om te zien of we 'een zaak kunnen laten vervallen na een belang' (zoals dat vaak wordt genoemd). We zien dat het veld 'archiefactiedatum' niet gevuld wordt bij een inrichting van de 'Bepaling brondatum archiefprocedure'. We hadden bijvoorbeeld als 'afleidingswijze brondatum' een hoofdzaak geselecteerd, geheel met inrichting van een bijpassend resultaattype in de deelzaak uiteraard. De hoofdzaak zette keurig een archiefactiedatum, maar de deelzaak deed daar niets mee. De deelzaak was afgerond, maar vult geen archiefactiedatum op basis van de archiefactiedatum van de hoofdzaak. Zo zou het wel moeten werken (lijkt ons). Het gevaar bestaat zo dat heel veel zaken zullen 'blijven hangen' om ze het 'vervallen belang' niet kunnen bepalen. 

TKN. Dit issue is vergelijkbaar met een issue bij de invoering van Zaakgericht Werken (ZGW). Dat ZGW-issue zorgde voor een groot archiefprobleem. Herstelacties daarvoor lopen nog steeds (!). Wat mij betreft is er dus een hoge prio voor het werkend krijgen van dit gedeelte. 

Vraag is uiteraard: kan dit gedeelte zo snel mogelijk werkend worden gemaakt 'as designed'?
Graag een reactie. 

Mvg. Olav

**Comment by michielverhoef** [comment]
Goedemorgen Olav,

Ik heb je vraag even omgezet naar een vraag. 

Zelf ben ik niet heel erg thuis in archiveren maar daarvoor heb ik mijn collega @hdksi aan de vraag toegevoegd. Het zou namelijk heel goed kunnen zijn dat het gedrag wat je verwacht nog niet in een user story naar voren is gekomen en daarom nog niet opgenomen is in de standaard.

Wat me in ieder geval opvalt is dat je graag wilt dat iets "werkend wordt gemaakt". Dit is echter een standaard, geen werkende, productierijpe applicatie. Zou je daarom wat meer context en achtergrond kunnen geven zodat ik beter kan plaatsen wat je precies verwacht? 

Je verwijst ook naar een issue "TKN. Dit issue is vergelijkbaar met een issue bij de invoering van Zaakgericht Werken (ZGW). Dat ZGW-issue zorgde voor een groot archiefprobleem. Herstelacties daarvoor lopen nog steeds (!). Wat mij betreft is er dus een hoge prio voor het werkend krijgen van dit gedeelte."

Om welk issue gaat dit, is dit een issue rondom de API standaarden?

Zoals ik het nu lees krijg ik het gevoel dat dit een issue is bij een leverancier en dan gaat het over de werking van die applicatie, niet over de standaard.

Mocht het zo zijn dat je bepaalde functionaliteit mist in de standaard, wil je dan een user story aanmaken? 

Alvast bedankt!

**Comment by OlavAllema** [comment]
Hoi Michiel,

Dank voor je snelle reactie en je wedervragen voor verduidelijking.
Ik zal ze hieronder beantwoorden in de tekst van je mailtje.
Ik heb het wat uitgebreid gedaan voor een evt. user story, zoals gevraagd.

Groet, Olav

Van: Michiel Verhoef <notifications@github.com>
Beantwoorden - Aan: VNG-Realisatie/gemma-zaken <reply@reply.github.com>
Datum: maandag 14 december 2020 om 08:22
Aan: VNG-Realisatie/gemma-zaken <gemma-zaken@noreply.github.com>
CC: Olav Allema <olav.allema@contezza.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [VNG-Realisatie/gemma-zaken] 'Bepaling brondatum archiefprocedure'-gedeelte in het Resultaattype werkt niet (#1741)


Goedemorgen Olav,

Ik heb je vraag even omgezet naar een vraag.
Door je antwoord onderaan begrijp ik dat het nú inderdaad op een applicatie-issue van Open Zaak lijkt.
Maar goed, dit gedeelte in hun app werkt niet doordat er nog geen standaard vanuit jullie voor is, schat ik in.
Ik zou dit bij hun kunnen inschieten, maar dan zullen zij het weer doorspelen naar jullie.
Vind je het oké om dit ticket hier te laten staan?

Prima dat het nu een vraag is geworden, maar weet dat het dan (ooit) een user story zal worden.

Zelf ben ik niet heel erg thuis in archiveren maar daarvoor heb ik mijn collega @hdksi<https://github.com/hdksi> aan de vraag toegevoegd. Het zou namelijk heel goed kunnen zijn dat het gedrag wat je verwacht nog niet in een user story naar voren is gekomen en daarom nog niet opgenomen is in de standaard. Prima. Goed om te weten.

Wat me in ieder geval opvalt is dat je graag wilt dat iets "werkend wordt gemaakt". Dit is echter een standaard, geen werkende, productierijpe applicatie. Zou je daarom wat meer context en achtergrond kunnen geven zodat ik beter kan plaatsen wat je precies verwacht?
Zeker. Heel kort gezegd gaat het over het plaatsen van de juiste ‘brondatum’ of ‘Archiefactiedatum’ (zoals het in Open Zaak is genoemd) voor elke zaak.
Binnen het archief zijn er 2 smaken aan een zaak te geven die gearchiveerd wordt:

  *   een ‘vernietigingsdatum’ (voor zaken die op termijn moeten worden vernietigd); OF
  *   een ‘overbrengingsdatum’ (voor zaken die voor altijd moeten worden bewaard; in een e-depot zoals dat heet).

Voor het beeld: record managers werken met ‘vernietigingslijsten’ waarop alle zaken komen te staan die in aanmerking komen om te vernietigen of over te brengen.
Zij bepalen de archiefnominatie voor het inrichten van resultaattypen bij zaaktypen allemaal op basis van de selectielijst van de VNG<https://vng.nl/nieuws/selectielijst-2020-vastgesteld>.
Daarin staat heel duidelijk of een zaak vernietigd of bewaard moet worden.

Er is echter nog een derde soort die ik meestal ‘na vervallen belang’ noem. Dit is ook de soort waar het in dit hele verhaal om gaat.
‘Na-vervallen-belang-zaken’ krijgen een brondatum/archiefactiedatum o.b.v. ‘een bepaald belang’ (een lijstje staat al in Open Zaak; in mijn screenshot in het ticket).

Bijvoorbeeld: Een ‘klacht-zaak’ of een ‘bezwaarschrift-zaak’ gaan inhoudelijk over verschillende soorten onderwerpen. Vaak over een andere zaak.
Er kan een bezwaar zijn over plannen voor een groot bouwproject, maar een bezwaar kan ook gaan over een uitbouw bij de buren.
Elk bezwaar zal de ‘brondatum/archiefactiedatum’ overnemen van een andere zaak of kenmerk (hoofdzaak, datumkenmerk, eigenschap, etc.) en daar de eigen archiefnominatie bij op tellen.
Dus: als de brouwprojectzaak altijd bewaard moet blijven, dan gaat de bezwaarschrift-zaak mee.
En, als de uitbouw-bij-de-buren-zaak 7 jaar na afhandelen vernietigd wordt, en de bezwaarschrift-zaak heeft een archiefnominatie van ‘1 jaar na vervallen belang’, dan wordt de bezwaarschrift-zaak na 8 jaar vernietigd.

Het gedeelte ‘bepaling brondatum archiefprocedure’ (in Open Zaak) is dus essentieel voor het bepalen van de juiste brondatum/archiefactiedatum voor zaken die een refererend belang hebben.
Er kan nu gewerkt worden met een work around, maar dat kan op termijn voor problemen gaan zorgen. Zie hieronder…
NB. Die work around is: het gedeelte ‘bepaling brondatum archiefprocedure’ helemaal niet gebruiken. Alle ‘na-vervallen-belang-zaken’ kunnen dan niet geautomatiseerd worden. Zonde natuurlijk.

Je verwijst ook naar een issue "TKN. Dit issue is vergelijkbaar met een issue bij de invoering van Zaakgericht Werken (ZGW). Dat ZGW-issue zorgde voor een groot archiefprobleem. Herstelacties daarvoor lopen nog steeds (!). Wat mij betreft is er dus een hoge prio voor het werkend krijgen van dit gedeelte."

Om welk issue gaat dit, is dit een issue rondom de API standaarden?

Nee, dit was geen issue rondom API-standaarden, want die waren er toen nog niet. Het gaat precies om dit issue: het bepalen voor de brondatum waarop een zaak naar het archief moet.
Ja, het is nu wel een issue voor API-standaarden. Alle zaken moeten een ‘brondatum/archiefactiedatum’ gaan krijgen. Ongeacht de applicatie waarmee gewerkt wordt.

Zaakgericht werken (ZGW) startte ergens in de zero’s (’00).
Als consultant ben ik al jaren betrokken bij projecten voor ZGW op allerlei vlakken, daarom kan ik wel zeggen dat ik er veel van weet.
Simpel gezegd gaat het bij ZGW om 2 dingen:

  *   (Digitale) dienstverlening;
  *   Archiveren.

Alles wat een zaaksysteem doet staat in het teken van één van die twee dingen, of beide. Hoe komt dat?
Dienstverlening aan burgers en organisaties is waar een gemeente voor is ontstaan; het bestaansrecht van een gemeente.
Archiveren moet. Omdat er een archiefwet is: Archiefwet 1995.
Dat betekent concreet dat alle gemeenten alle zaken die ze behandelen moeten archiveren volgens de selectielijst<https://vng.nl/nieuws/selectielijst-2020-vastgesteld>.
Common Ground is veelal een technische verandering, maar bouwt in mijn ogen ook voort op wat er met ZGW al is bereikt (qua procesmatig werken).
Dat zie je duidelijk terug in Open Zaak.

Terug naar de invoering van ZGW. Daar zagen we het gedeelte ‘bepaling brondatum’ fout gaan in het begin.
Dat gebeurde destijds namelijk handmatig. Veel zaken werden niet goed afgehandeld en kregen daarom geen ‘vernietig- of bewaardatum’ mee en bleven ‘zweven’.
Gezien de Archiefwet was dat een groot probleem, maar omdat ZGW nog in de kinderschoenen stond zagen archiefinspecteurs het door de vingers.
Toen nog wel! Nu niet meer. Binnenkort gaan we bij een niet nader te noemen grote gemeente dit probleem oplossen.

Om de ernst van het geheel aan te geven. Vorig jaar zat ik bij een gemeente die het archief behoorlijk goed op orde had, maar niet goed genoeg.
Ze hadden te maken met een strenge, doch rechtvaardige, archiefinspecteur die ‘een rommelig archief’ niet meer tolereerde. Terecht.
Het kostte bijna een jaar om alles op orde te krijgen. Daar was ook de nodige bestuurlijke kordaatheid voor nodig.
Was dit niet gelukt, dan wordt een archief van een gemeente volledig overgenomen door de archiefinspectie (+ achterliggende organisatie).
Dat betekent een ramp voor de bedrijfsvoering van een gemeente. Dat ligt op de loer als de archiefnominatie niet goed ingericht kan worden.

Samenvattend, het bepalen van de brondatum mag tegenwoordig dus niet meer fout gaan.
Gemeenten (e.a. overheidsinstanties) zijn volgens de Archiefwet verplicht dit zorgvuldig te doen.
Je ziet dus dat veel processen en zaaktype-inrichtingen grotendeels bepaald worden (of zouden moeten worden) door de selectielijst en record manager(s) van een gemeente.
Zij kunnen de standaarden daarvoor goed aangeven. Open Zaak heeft daar duidelijk al een voorschot op genomen.

NB. Veel mensen hebben het tegenwoordig over de AVG, maar de Archiefwet is minstens zo belangrijk.
Sterker nog, het goed uitvoeren van de Archiefwet betekent dat er al grotendeels voldaan wordt aan de AVG.

Zoals ik het nu lees krijg ik het gevoel dat dit een issue is bij een leverancier en dan gaat het over de werking van die applicatie, niet over de standaard.

Zoals ik hierboven al heb onderbouwd, dat klopt deels. Het werkt nu niet in de applicatie Open Zaak, maar ze zullen waarschijnlijk wachten op jullie.
Zij zijn al wel live met een versie 1.3 inmiddels. Die wordt al gebruikt door menig gemeente. Ik neem aan dat dat ook een bepaalde druk op jullie legt.
In ieder geval, wij hebben klanten die dit graag z.s.m. zouden gebruiken.

Ik kan er nog aan toevoegen: als dit goed wordt gemaakt, dan zal dat één van de grootste ‘verkooppunten’ zijn voor Common Ground.
Alle gemeenten zullen, als dit gestandaardiseerd wordt in een API, er snel gebruik van willen maken. Het zal de transitie goed doen.

Mocht het zo zijn dat je bepaalde functionaliteit mist in de standaard, wil je dan een user story aanmaken?

Heb je hier voldoende aan? Duidelijk genoeg? Missen er nog dingen die je nodig hebt voor de user story?

Benieuwd naar je reactie. Mvg, Olav

Alvast bedankt!

**Comment by michielverhoef** [comment]
Hoi Olav,

Zo te zien is het goed eerst even contact met je op te nemen om dit concreet te maken.  Er lopen teveel dingen door elkaar in je verhaal en ik zou graag de concrete wens voor de API standaarden hebben. 

Daarna zou het goed zijn wanneer jij of iemand anders van de gemeente zelf de user story aanmaakt zodat de wens ook goed beschreven is.

**Comment by OlavAllema** [comment]
Hoi Michiel,

Prima om contact te hebben, een afspraak doel je dan op neem ik aan.
Terecht ook dat je een concrete wens voor de API-standaarden wil.
Mede daarom dat ik Open Zaak ook aanhaal, zij lijken er namelijk al over na te hebben gedacht.
Bij de ontwikkeling daarvan waren meerdere gemeenten betrokken.
Handig om hen te laten aansluiten bij de afspraak? Ken je iemand daar? Of moet ik even vragen wie er kan aansluiten?


Groet, Olav

[signature_319806990]

E
olav.allema@contezza.nl<mailto:olav.allema@contezza.nl>
T
+31 (0)6 10290121
W
https://contezza.nl/contezza-common-ground/

Groet, Olav


Van: Michiel Verhoef <notifications@github.com>
Beantwoorden - Aan: VNG-Realisatie/gemma-zaken <reply@reply.github.com>
Datum: maandag 14 december 2020 om 16:01
Aan: VNG-Realisatie/gemma-zaken <gemma-zaken@noreply.github.com>
CC: Olav Allema <olav.allema@contezza.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [VNG-Realisatie/gemma-zaken] 'Bepaling brondatum archiefprocedure'-gedeelte in het Resultaattype werkt niet (#1741)


Hoi Olav,

Zo te zien is het goed eerst even contact met je op te nemen om dit concreet te maken. Er lopen teveel dingen door elkaar in je verhaal en ik zou graag de concrete wens voor de API standaarden hebben.

Daarna zou het goed zijn wanneer jij of iemand anders van de gemeente zelf de user story aanmaakt zodat de wens ook goed beschreven is.

**Comment by hdksi** [comment]
Net even met @OlavAllema gesproken. Er spelen hier inderdaad twee zaken

1. Bewaartermijnen die afhankelijk zijn van een object (zaak- of anders) buiten de zaak zelf stellen gemeenten voor problemen. Het na vervallen van belang alsnog vastleggen van een 'brondatum archiefprocedure' is lastig te automatiseren en gebeurt daardoor niet consequent. Dit beschouw ik als een 'wicked problem', waarvoor een oplossing erg gewenst is, maar tegelijkertijd bijzonder complex. Een manier om daar in de buurt te komen is te werken met notificaties door registers waarin objecten zijn opgeslagen waarvan de 'brondatum archiefprocedure' van zaken afhankelijk kunnen zijn. Dit vereist echter een veel completere implementatie van het gegevenslandschap dan nu realiseerbaar is.
2. In Open Zaak wordt na schijnbaar correcte configuratie voor deelzaken niet de archiefactiedatum (ik vermoed dat hier de `brondatumArchiefprocedure` wordt bedoeld) op basis van de archiefactiedatum van de hoofdzaak overgenomen. Dit is in de eerste instantie een issue voor Open Zaak, maar het lijkt me goed om naar aanleiding daarvan de volgende zaken in de standaard en bijbehorende documentatie te checken:

- Is in de standaard nu ruimte voor alle mogelijke afleidingswijzen voor de `brondatumArchiefprocedure`?
- Is het gedrag van implementerende applicaties voldoende (uitgebreid) beschreven?
- Is dit gedrag vertaald naar functionaliteit in de referentieimplementatie(s)?

Naar aanleiding hiervan eventueel concrete user stories aanmaken.

**Comment by OlavAllema** [comment]
- Wat is de status van dit issue? Wij hebben klanten die dit binnenkort nodig hebben voor livegang met Open Zaak. 
- Is er al contact geweest met Open Zaak (Maykin Media)? (Sergei Martens en Joeri Bekker weten hier van)

**Comment by michielverhoef** [comment]
@hdksi kun jij de vraag van Olav beantwoorden?

Valt dit onder het afmaken van het thema archiveren, zoals ook beschreven bij de TODO's op https://vng-realisatie.github.io/gemma-zaken/themas/achtergronddocumentatie/archiveren ?

**Comment by hdksi** [comment]
@OlavAllema excuses voor de late reactie. Het antwoord op de vragen is als volgt:

- alle afleidingswijzen voor de `brondatumArchiefprocedure` zitten erin.
- er is **géén** gedrag gespecificeerd dat iets zegt over het automatisch afleiden van de `archiefactiedatum` van een deelzaak op basis van `Zaak.hoofdzaak.einddatum` van de gekoppelde hoofdzaak.
- het is me niet duidelijk waar de benodigde functionaliteit in de referentieimplementatie is beschreven, maar uit het bovenstaande concludeer ik dat het automatisch overnemen **géén** onderdeel is van de standaardspecificatie. Dit alsnog implementeren lijkt een serieuze klus omdat de deelzaak (middels een notificatie?) op de hoogte moet worden gebracht van het zetten van een `Zaak.hoofdzaak.einddatum` op de gekoppelde hoofdzaak, terwijl die hoofdzaak geen kennis heeft van de daaronder hangende deelzaken omdat relaties tussen hoofd- en deelzaken (volgens mij) alleen bij de deelzaak (`via Zaak.hoofdzaak`) worden vastgelegd.
 
Bovendien zou je vanuit het oogpunt van compleetheid eigenlijk willen dat bovenstaand mechanisme ook voor andere `afleidingswijzen` werkt, en dus automatisch een `archiefactiedatum` kan worden gezet. Hoewel dit vanuit het oogpunt van goed informatiebeheer zeer gewenst is, kom je dan qua complexiteit mijns inziens wel heel dicht in de buurt van punt 1) in mijn vorige reactie.

Als het hierboven beschreven gedrag een juiste interpretatie van de wens is, dan zien we daarvoor graag een user story tegemoet. Tegelijkertijd ben ik bang dat we dit niet op korte termijn kunnen realiseren.

Los van bovenstaande staat het leveranciers (Open Zaak of anders) natuurlijk vrij de gewenste functionaliteit in hun oplossing in te bouwen. Wellicht kunnen we daar ook nog iets van leren en overschat ik de complexiteit...

@michielverhoef de hierboven beschreven functionaliteit staat niet in het lijstje waaraan je refereert, misschien wel goed om daar binnenkort nog eens doorheen te lopen.

**Comment by michielverhoef** [comment]
@hdksi Dank je voor het (denk ik) volledige antwoord. Zelf had ik dit ook al min of meer geconcludeerd maar ik laat het graag aan de expert over ;-)

De openstaande dingen doornemen is inderdaad een goed plan, ik plan wat in. Ook met @HenriKorver denk ik zo?

**Comment by OlavAllema** [comment]
Dank beiden voor de reacties. Het is helder en jullie onderbouwing is logisch. Wij weten nu beter op welk onderdeel we zelf aan de slag moeten om het lifecycle-management goed te regelen voor onze klanten (en ook hóe). Dus, nogmaals dank!
