### ISSUE TITLE
zaken-auth.vng.cloud does not work / is unresponsive

### ISSUE THREAD

**Issue by aurimasroxit97** [VNG-Realisatie/gemma-zaken#1745]
After creating a new client in https://zaken-auth.vng.cloud/ and clicking "Volgende" to configure client permissions, it times out most of the time - "ERR_CONNECTION_CLOSED" or 502 Bad Gateway error is thrown.

On rare occasions, I can get "Configureer de applicatie-autorisaties" to load, but most of the time it does not work.

**Comment by michielverhoef** [comment]
I just test this and everything seems to work fine now? 

Perhaps this is a long shot but yesterday  I experienced quite a lot of hiccups in my network connection at home, perhaps a similar thing happened?

Please retry to see if the problem still exists.

**Comment by aurimasroxit97** [comment]
The situation certainly did improve since yesterday. Although I've been trying to use this functionality for well over a week and it usually resulted in a time out. I think it's safe to close the bug for now, thanks.

**Comment by heuvea** [comment]
Goedemiddag,

Tijdens het aanmaken van een nieuw ClientID loop ik tegen hetzelfde issue aan. Kunnen jullie hier iets aan doen? Ik heb 10x geprobeerd en geeft telkens de foutmelding:

**Sorry, a server error has occurred (500)
We have been automatically notified about the problem and will investigate as soon as possible.

If you need assistance, you may reference this error as 57a4144677f64745b8d17349c917c46c.**

Bij voorbaat dank

**Comment by michielverhoef** [comment]
Goedemiddag, naar aanleiding van de vragen heb ik zelf meteen ook getest en bij mij werkte het meteen goed.  Hebben jullie geprobeerd om de cache te legen voordat je het nog eens test? Rechtsonderaan staat een knop "verwijder credentials uit deze sessie", mogelijk dat dat helpt.

Om toch niet helemaal dit issue gelijk te sluiten zal ik nagaan of er problemen zijn geweest waardoor het soms niet werkt.

**Comment by heuvea** [comment]
Goedemiddag,
Ik heb geprobeerd om de cache te legen (via het knopje rechts) met hetzelfde resultaat helaas. Geeft wederom de fout:
**Sorry, a server error has occurred (500)**

**Comment by aurimasroxit97** [comment]
I can also confirm that I am experiencing the same issue again.

**Comment by johannesbattjes** [comment]
`Hallo Michiel, heb je ook de tweede stap gedaan? daar gaat het namelijk (9 van de 10 keer) mis

Bijgaand drie screenshots. Na de tweede "volgende" gaat het mis.
Foutcode 748415439cab4847bd4a65390137e84b
[ref impl.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/5885946/ref.impl.docx)

**Comment by michielverhoef** [comment]
Ik had wel getest om de permissies aan te maken bij componenten, zowel los als overal super-user. Maar nu ging het bij mij ook mis wanneer ik enkele permissies wilde instellen. Mezelf overal als super-user aanmaken ging zonder problemen.

Dat is natuurlijk niet hoe het hoort maar misschien voor nu een work-around. In ieder geval ga ik dit melden om het op te laten lossen.

**Comment by michielverhoef** [comment]
Het blijft een aandachtspunt, zojuist getest en een `bad gateway` gekregen bij stap 2.

**Comment by michielverhoef** [comment]
zaken-auth has been replaced by the new token-issuer: https://github.com/VNG-Realisatie/token-issuer
