### ISSUE TITLE
Fout in documentatie: links naar Changelog.rst geven 404-fout

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#1747]
# Bug

De links naar Changelog.rst van de API's op [API versies](https://vng-realisatie.github.io/gemma-zaken/standaard/versions) geven een Page not found (404) error.

Vermoedelijk omdat in de link wordt verwezen naar /develop i.p.v. /master

**Comment by michielverhoef** [comment]
Opgelost via PR #1750
