### ISSUE TITLE
Als ontwikkelaar wil ik resources kunnen filteren op UUID  DOCUMENTEN API

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1759]
...zodat [vul aan]
...met aandacht voor [vul aan]

In #1728  Is dit voor Zaken aangevraagd. Om consequent te zijn zou dit voor alle resources van elke API een standaard functionaliteit moeten zijn. Dus ook voor Besluiten EnkelvoudigeInformatieobjecten, etc.

Voor de Catalogi API is dit voorlopig minder van belang

**Comment by michielverhoef** [comment]
Filtermogelijkheid op een lijst van UUID toegevoegd op de resources enkelvoudiginformatieobjecten en gebruiksrechten.

**Comment by michielverhoef** [comment]
PR https://github.com/VNG-Realisatie/documenten-api/pull/146 aangemaakt voor dit issue

**Comment by HenriKorver** [comment]
@michielverhoef Kun je mij wat meer context geven? Kan ook via teams...

**Comment by michielverhoef** [comment]
@HenriKorver Dit is een vervolg op  #1728 . Bijvoorbeeld om een lijst informatieobjecten op te kunnen vragen waarvan de UUIDs al bekend zijn bij de consumer.  Eigenlijk wil je de hoofdobjecten van een API op kunnen vragen in één zoekopdracht in plaats van tig aparte calls doen. Dus Informatieobjecten bij de Documenten API, Zaken bij de Zaken API, Besluiten bij de Besluiten API.

**Comment by michielverhoef** [comment]
Dit is opgenomen in Documenten API 1.3
