### ISSUE TITLE
Inrichten gemeentelijk project binnen gemeente Delft

### ISSUE THREAD

**Issue by RitaBerghuis** [VNG-Realisatie/gemma-zaken#176]
Definition of Done

- [ ] Proces  is bekend en afgestemd met betreffende proceseigenaar en betrokkenen, externe dienstverlening, ontwikkelaars, ict, programmeur en strategische informatie advies.
- [x] Toepassingen voor interface en zaakafhandeling zijn gekozen en ingericht in een testomgeving
- [ ] Datalaag is gekozen en ingericht in een testomgeving

**Comment by TCIMEddy** [comment]
@RitaBerghuis @EdwinCoster Volgens mij is dit gereed (voor zover dit gereed kan zijn). Het is in gang gezet dus wat mij betreft kun je deze sluiten en op done zetten.
