### ISSUE TITLE
Question about compliancy

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#1761]
We have a question about the following rule:
_Het is NIET TOEGESTAAN om gebruik te maken van operaties die niet beschreven staan in deze OAS spec, of om uitbreidingen op operaties in welke vorm dan ook toe te voegen._
(eg https://vng-realisatie.github.io/gemma-zaken/standaard/autorisaties/index)

Among our (Visma Roxit) developers we had the following discussion about two interpretations of the rule:
**a) operations means HTTP operations (POST, GET, ...).** If we implement a ZGW-component, we may add API-methods and functions that are not specified in the standard. For example if we implement the BRC, we have to implement all methods described in https://besluiten-api.vng.cloud/api/v1/schema/  and comply to the business rules in https://vng-realisatie.github.io/gemma-zaken/standaard/besluiten/index. In addition we may add an extra method to 'our' BRC in order to store extra data or to permit extra business rules. 
**b) Operations means everything** - HTTP methods, new functionality, fields, headers not described by VNG.  If we implement a ZGW-component, we may NOT add API-methods and functions that are not specified in the standard. For example if we implement the BRC, we have to implement all methods described in https://besluiten-api.vng.cloud/api/v1/schema/  and comply to the business rules in https://vng-realisatie.github.io/gemma-zaken/standaard/besluiten/index. In addition we may NOT add an extra method to 'our' BRC in order to store extra data or to permit extra business rules.  

Could you explain in depth what you mean with this rule and which interpretation (in any of them) is correct?

**Comment by sergei-maertens** [comment]
> Het is NIET TOEGESTAAN om gebruik te maken van operaties die niet beschreven staan in deze OAS spec, of om uitbreidingen op operaties in welke vorm dan ook toe te voegen.

The spirit of this rule is that vendors are not allowed to provide extensions to the standard _that make it seem that they are part of the standard_. Adding endpoints, or methods to existing endpoints that currently don't exist is dangerous:

* client application developers don't necessarily look at the standard documentation, but at the documentation of the vendor they're working with. They trust that the vendor provides only functionality provided in the standard, so that they can easily adapt their application to another vendor without having to change their code, at all.
* adding methods/endpoints would lead to breaking changes if the standard gets updated which adds the same endpoints/methods, as you now essentially created "namespace collissions"

This exists to prevent the problem of different dialects depending on which vendor offers the API - this is something that happened with StUF-ZKN & the ZDS standard.

Interpretation **b** is therefore correct.

As for the definition of operation, that is the definition as in the OpenAPI 3.0 specification: [Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operationObject).

Probably a good addition to add this definition to the ZGW docs @michielverhoef ;)

**Comment by michielverhoef** [comment]
@sergei-maertens volgens mij staat dit er al:  https://vng-realisatie.github.io/gemma-zaken/standaard/

Onder het kopje “Eisen en uitgangspunten die voor alle API’s gelden” staat:

* Endpoint: een pad dat ontsloten wordt in de API, al dan niet met dynamische parameters. Bijvoorbeeld: /api/v1/zaken/{uuid}
* Operatie: de combinatie van een HTTP method zoals POST, GET, PUT, PATCH of DELETE en een endpoint.


Het gaat dus om de combinatie van HTTP methode en endpoint.

@johannesbattjes  beantwoordt dit je vraag?

**Comment by sergei-maertens** [comment]
Verhip... had ik toch nog even moeten controleren :-) dank voor het opzoeken!

**Comment by johannesbattjes** [comment]
Beste Michiel, dank voor het verduidelijken.

Klopt het volgende: een ZGW-component zoals AC dus geen extra (niet beschreven) methodes mag ondersteunen?
Klopt de redenatie dat Open Zaak dus niet aan de standaard voldoet - want die ondersteunt een methode voor het toevoegen van een applicatie met heeftAlleAutorisaties: false en verder geen authorizations (wat niet kan volgens de specs - zie https://github.com/open-zaak/open-zaak/issues/835).

Het gaat mij overigens niet om Open Zaak hierbij maar om mijn beslissing of wij ook net als Open Zaak gaan afwijken van de specs bij de bouw van onze ZGW-componenten.

**Comment by CMasselink** [comment]
@johannesbattjes 
Ik volg dit issue met interesse en wil even vanuit gemeente perspectief (dit is dus geen VNG reactie) reageren.
Deze reactie staat ook los van of het genoemde punt over of Open Zaak al dan niet aan de spec voldoet, gaat om een algemeen principe:

Als gemeenten zijn we erbij gebaad als alle partijen in het common ground eco systeem zich aan de standaard houden, zo voorkomen we de situatie die we bij StUF hebben gezien: allerlei dialecten waardoor interoperabiliteit tussen systemen verminderd wordt en koppelingen weer duur worden, je moet immers eerst het dialect van de specifieke implementatie snappen. Overstappen op een andere leverancier wordt lastiger omdat die hetzelfde dialect niet spreekt.

Het kan natuurlijk dat jullie zien dat bepaalde functionaliteit handig is voor gemeenten die nog niet in de standaard zit. Het ontdekken van nieuwe of ontbrekende functionaliteit is waardevol en kan de standaard verrijken en beter maken.

Ik wil jullie dan ook vooral uitnodigen om userstories / wijzigingsverzoeken in te dienen op de standaard i.p.v. afwijkingen op de standaard te implementeren.

**Comment by sergei-maertens** [comment]
> Klopt het volgende: een ZGW-component zoals AC dus geen extra (niet beschreven) methodes mag ondersteunen?
Klopt de redenatie dat Open Zaak dus niet aan de standaard voldoet - want die ondersteunt een methode voor het toevoegen van een applicatie met heeftAlleAutorisaties: false en verder geen authorizations (wat niet kan volgens de specs - zie open-zaak/open-zaak#835).

Het lijkt hier als methodes geframet wordt buiten de context van een HTTP method op een API endpoint. Strikt gezien beschrijft de standaard enkel wat de API moet aanbieden en welk gedrag die moet vertonen, en ook dat je dus geen "extensies" op die API mag doen, wat bedoelt is: geen extra attributen in request/response bodies, geen extra endpoints, geen extra HTTP methods op bestaande endpoints.

Ik snap dat het voorbeeld van Open Zaak daar lijkt tegenin te gaan en dat het grijs gebied lijkt te zijn. Echter, wat Open Zaak biedt is een _interface_ (laag 5, in principe) op de registratie van applicaties/autorisaties (laag 1). Deze admin interface werkt direct op de database. Dit betekent dat deze interface niet herbruikbaar is met een andere AC implementatie en dus ook niet lost te deployen is van Open Zaak.

Het gedrag waardoor je objecten uit de Autorisaties API terugkrijgt die niet aan de standaard voldoen, dat is een bug in Open Zaak. Die data moet er voor de API uitgefilterd worden en mag dus niet zichtbaar zijn in de API. Via de beheerinterface is die wel zichtbaar, zodat het wel afgeconfigureerd kan worden. open-zaak/open-zaak#835 wordt dan ook als zodanig opgepakt.

**Comment by michielverhoef** [comment]
Als ik de reactie van @sergei-maertens  goed begrijp wordt de extra functionaliteit zoals deze in de gebruikersinterface gebruikt wordt niet gebruikt in de implementatie van de API. Behoudens de bug in Open Zaak die opgepakt wordt, maar dat is iets van Open Zaak.

Ik kan nu niet goed inschatten wat de gevolgen zijn van het op deze manier omzeilen van de Autorisatie API. Worden op deze manier autorisaties mogelijk gemaakt die via de API niet kunnen? Als daar behoefte aan is zou ik deze user stories graag in de standaard laten landen. 

Eigenlijk geldt dit ook voor alle partijen die de API's implementeren. Wanneer functionaliteit in de API's ontbreekt, benoem dit en maak svp user stories aan. Zo voorkomen we dat er dialecten onstaan zoals @CMasselink  hierboven beschreef. Ook het dan maar oplossen in de user interface en rechtstreeks in de database wegschrijven is dan niet de bedoeling. Dat het gebeurt om performance te verbeteren is geen probleem, zolang het technisch ook maar via de API kan. Want ook een extensie van functionaliteit is een vorm van extensie die we niet zouden moeten willen.  Want dan zijn de componenten nog niet compatible en dat maakt het nog steeds lastig, zo niet onmogelijk, om de taakapplicaties aan te sluiten op registers die de standaard wel correct ondersteunen.

@HenriKorver  zegt de Landelijke API strategie hier nog iets over?

**Comment by sergei-maertens** [comment]
> Ik kan nu niet goed inschatten wat de gevolgen zijn van het op deze manier omzeilen van de Autorisatie API. Worden op deze manier autorisaties mogelijk gemaakt die via de API niet kunnen? Als daar behoefte aan is zou ik deze user stories graag in de standaard laten landen.

Nee, en in open-zaak/open-zaak#867 is de bug nu ook gefixed, dus bij volgende release is die ge-squashed. De Open Zaak interface geeft je als gebruiker een point-and-click interface waarbij je zaaktypen etc. uit de catalogus kan selecteren, en onderwater worden dan voor de applicaties/autorisaties de juiste URLs voor de autorisaties ingevuld.

Open Zaak heeft als _eerste_ badge in de README de slagende api-test.nl test staan. Open Zaak weigert ook actief om functionaliteiten toe te voegen die (nog) niet onderdeel van de standaard zijn, en issues in de standaard contributen we ook terug naar upstream (jullie).

In Open Zaak zijn voor de beheersinterface van Autorisaties keuzes gemaakt: economisch (tijd en budget), en code-maintainability: met minder code meer doen op een performantere manier. Het resultaat in de API is identiek.

**Comment by michielverhoef** [comment]
@sergei-maertens  Dank je, volgens mij is nu wel duidelijk dat het gedrag wat tot niet voldoen aan de standaard leidde een bug was die inmiddels opgelost is.

Dit past in de lijn dat het niet toegestaan is eigen extensies te maken op de API standaard of anderszins af te wijken van de standaard. 

Volgens mij is dit issue dan verder duidelijk toch? Ik sluit het issue, mocht er nog iets niet duidelijk zijn kanhet altijd weer geopend worden @johannesbattjes
