### ISSUE TITLE
ZGW API postman test chain broken in ZTC

### ISSUE THREAD

**Issue by narmontas** [VNG-Realisatie/gemma-zaken#1762]
The change in [gemma-postman-tests](https://github.com/VNG-Realisatie/gemma-postman-tests/commit/4aa5fdad04c24da52905cd23ab27bc2c3932b191) did rename tests ztc-003s and ztc-003t.
However, in tests section of ztc-003s the next request is set to the old request name causing broken test chain for ZTC.

```javascript
pm.globals.set("NEXT_REQUEST_NAMES", ["(ztc-003t) Resultaattype met afleidingswijze termijn en selectielijstklasse.procestermijn vast_te_leggen_datum is mogelijk"]);
```

**Comment by michielverhoef** [comment]
@joeribekker Kan hier naar gekeken worden?

**Comment by michielverhoef** [comment]
The postman tests have been fixed and are running without errors again.
