### ISSUE TITLE
functionele en technische specificaties worden ook in het Engels gepubliceerd

### ISSUE THREAD

**Issue by wishalg** [VNG-Realisatie/gemma-zaken#177]
...zodat leveranciers ook niet-Nederlandse developers kunnen inzetten.

**Comment by ehotting** [comment]
Is het dan niet handiger om alléén Engels te doen?

**Comment by wishalg** [comment]
Wordt het niet te complex voor NL developers?

**Comment by jgortmaker1** [comment]
niet mee eens.
ik stel voor alleen Nederlands. Engels is nice to have, maar  laten we het eerst in het Nederlands goed doen..we zijn Nederlandse overheid.

**Comment by wishalg** [comment]
Dit zijn verzoeken van leveranciers die developers in het buitenland hebben, nice to have is ok, maar dient wel later in het proces ons aandacht hebben.

**Comment by jgortmaker1** [comment]
dan moeten we de hele GEMMA etc. ook vertalen...
en dan blijken die indiërs geen engels te kunnen, maar liever sanskriet te krijgen...
en daarna blijkt er ook nog een leverancier in Friesland te zitten...m.a.w. niet aan beginnen. Nederlands is de taal die we gebruiken.

**Comment by GeertJohan** [comment]
Ik ben als developer niet anders gewend dan dat specificaties in het Engels geschreven worden. Zelfs in teams waar (nog) geen Engels sprekende developers aan tafel zitten. Als developer is er niets vervelender dan specs in Nederlands, omdat alle code en frameworks sowieso Engels zijn moet je voortdurend vertalen. En vertalen kost niet alleen tijd, maar zal ook vaker tot foute interpretaties leiden. Alles gaat sneller als overheden zouden accepteren dat software maken in het Engels gebeurt.

**Comment by fsamwel** [comment]
Vanuit de Regiegroep Gegevens- en Berichtenstandaarden is er door een leverancier (Centric) ook het verzoek gedaan technische specificaties in het Engels op te leveren.
Bij de StUF koppelvlakken hebben we in het verleden ook regelmatig het verzoek om Engelstalige specificaties gekregen. Wanneer een leverancier of developer zelf gaat vertalen krijg je vrij zeker vertaal- en interpretatieverschillen.

Ik denk dat je bij de taalkwestie onderscheid zou moeten maken op doelgroep:
* Architecten, enz. bij gemeenten, product managers bij leveranciers, enz.
* Developers

Alleen de developers willen specificaties in het Engels, de andere doelgroep(en) niet.
De vraag is waar je de grens dan legt. Grof gezegd: technische specificaties in het Engels, al het andere in het Nederlands. 
Helaas ben je er dan niet, want de informatiemodellen zijn in het Nederlands, omdat het gaat om een beschrijving van Nederlandse informatiedomeinen en begrippenkaders. Hoe vertaal je bijvoorbeeld "burgerservicenummer" in het Engels? Dus alle objecttypen (resources) en hun eigenschappen (properties) en hun semantische definities zijn in het Nederlands en het lijkt mij erg lastig (onwenselijk)  die te vertalen. Maar de technische specificaties over de werking van de API zou denk ik prima in het Engels kunnen.
Resultaat is dan in dat binnen een document, de API specificatie yaml, zowel Nederlands als Engels door elkaar voorkomt. Maakt dat het werkelijk duidelijker voor een developer?

**Comment by michielverhoef** [comment]
Waar denk ik een groot verschil in zit is dat we geen software maar een standaard opleveren.  De documentatie is dan ook niet bedoeld om werking van een stuk software te beschrijven maar om de API van een refrerentiecomponent (ZRC, DRC, ZTC) te beschrijven.

Daarnaast zijn de informatiemodellen (RGBZ, ImZTC, RSGB etc.)  in het Nederlands opgesteld. Zoals Frank hierboven aangeeft is het lastig, zo niet onmogelijk om die in het Engels te vertalen. Wat dat betreft moeten, wat mij betreft, de standaarden zo strak zijn dat een bericht eenduidig gevalideerd kan worden en wanneer het niet correct is gewoon afgekeurd wordt, voorzien van een eenduidige foutmelding waar ook een niet-Nederlandssprekende ontwikkelaar iets mee kan. 

Functionele documentatie is zo wie zo bedoeld voor Nederlands-sprekend publiek: de architect van de gemeente, accountmanagers van de leverancier die moet bepalen of een standaard van toepassing is op zijn product etc. Die moet dus in het Nederlands zodat deze aansluit op het begrippenkader van deze doelgroepen.

Wanneer leveranciers op basis van de yaml en functionele documentatie technische specificaties gaan schrijven voor hun eigen producten mag dat best in het Engels natuurlijk. Ook commentaar in de code mag best in het Engels.

Wat misschien lastig gaat worden is documentatie en commentaar in de code van de referentie-implementatie. Daarvan kan ik me voorstellen dat die in het Engels gemaakt wordt. Alleen zal dat een mengelmoesje van Nederlands en Engels worden vanwege een Nederlandstalig begrippenkader, informatiemodel etc. En dan deel ik de zorg van Frank dat dit het misschien allemaal niet duidelijker maakt.

**Comment by TCIMEddy** [comment]
@ehotting Kunnen we deze close? of als aandachtspunt open houden?

**Comment by jgortmaker1** [comment]
mag geclosed worden. hier gaan we geen VNG geld aan besteden

**Comment by michielverhoef** [comment]
Eens met bovenstaande opmerking.

Afgelopen vrijdag werd door een aantal leveranciers wederom aangegeven dat ze graag documentatie in buitenlandse talen zagen. Waar het voorheen eerst alleen Engels was werd nu ook Duits gevraagd. Overigens werd in diezelfde sessie ook aangegeven door andere leveranciers dat het belangrijk is dat all documentatie en terminologie consequent en consistent is. Het is voor een niet-Nederlands sprekende ontwikkelaar goed te doen om te begrijpen wat en ZAAK is en welke attributen daar bij horen maar om ZAAK, CASE en wat voor vertaling dan ook door elkaar te gebruiken geeft teveel ruis. Het wordt er dan niet duidelijker op.

Volgens mij gaan we dan voorbij aan het doel van de documentatie. Wanneer leveranciers niet-Nederlands sprekende ontwikkelaars inhuren om software te maken is het mijns inziens ook de verantwoordelijkheid van die leveranciers zelf indien nodig voor een goede vertaling van documentatie en standaarden te zorgen.

**Comment by TCIMEddy** [comment]
Zelfde als #869 dus deze close
