### ISSUE TITLE
Als gebruiker van het zaaksysteem wil ik van een verzonden brief de geadresseerde vastleggen

### ISSUE THREAD

**Issue by ArjanKloosterboer-Telengy** [VNG-Realisatie/gemma-zaken#1770]
... zodat ik kan zien aan wie deze verzonden is en bovendien bij een subject de aan hem/haar verzonden brieven kan zien. 
Idem v.w.b. de afzender van een aan ons verzonden brief.  
Dat van die geadresseerde is onder meer nodig om van een document zijnde een aanslagbiljet vast te kunnen leggen aan wie (de aanslagplichtige) dit verzonden is. Dat kan niet bij de zaak. Die zaak is een zgn. kohierzaak oftewel een zaak voor het proces van het opstellen van een (belasting)kohier. Dat kan leiden tot tienduizenden aanslagbiljetten cq. documenten bij die zaak.  

Dit is een wijzigingsvoorstel dat verwerkt is in RGBZ 2.0. Deze RGBZ-versie is (nog) niet vastgesteld. Hoe gaan jullie hiermee cq. met de daarin verwerkte wijzigingsvoorstellen om? Is daar een planning van? Wat betekent dat voor dit issue cq. wijzigingsvoorstel?

**Comment by michielverhoef** [comment]
De geadresseerde is dan dit attribuut? https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/informatieobject.geadresseerde 

In het verlengde hiervan zou ik denken dat het ook nuttig is de afzender (https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/informatieobject.afzender) vast te kunnen leggen.

Overigens is het al mogelijk om de ontvangst- en verzenddatum vast te leggen, ergens  ius het dus een beetje raar dat geadresserde/afzender dan niet vastgelegd kan worden.

De vraag is even, doen we dit met een verwijzing naar een bron (BRP API oid) of met de gegevens die op dat moment gebruikt zijn? Qua bevragen bij de bron zou ik zeggen een verwijzing maar zolang die er nog niet is moet het denk ik ook mogelijk zijn om de gegevens zelf vast te leggen.  Vergelijkbaar met hoe in de Zaken API een Betrokkene vastgelegd kan worden in betrokkeneIdentificatie (https://zaken-api.vng.cloud/api/v1/schema/#operation/rol_create)

**Comment by ArjanKloosterboer-Telengy** [comment]
`De geadresseerde is dan dit attribuut? `
Nee. Er staat in de toelichting bij dat attribuut: "_Betreft de NAW-gegevens van de geadresseerde [...] indien de geadresseerde daarvan niet gestructureerd is vastgelegd door middel van de relatie ‘INFORMATIEOBJECT.is ontvangen van of verzonden aan BETROKKENE’_.". Het gaat mij om die relatie en de relatieklasse [VERZENDING](https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/verzending).

`In het verlengde hiervan zou ik denken dat het ook nuttig is de afzender vast te kunnen leggen.`
Is zekers nuttig. Maar gaat ook weer met genoemde relatie en relatieklasse. 

`Overigens is het al mogelijk om de ontvangst- en verzenddatum vast te leggen, ergens ius het dus een beetje raar dat geadresserde/afzender dan niet vastgelegd kan worden.`
Kan dus in 1.0 al als tekst, in 2.0 gestructureerd. En dat wordt nu wel 's tijd, lijkt me. 

`De vraag is even, doen we dit met een verwijzing naar een bron (BRP API oid) of met de gegevens die op dat moment gebruikt zijn?`
Het eerste dus. Er zit vast historie op die bron. Dus kan mbv verzend- of ontvangstdatum altijd achterhaald worden wat de bronwaarden op die datums waren.

**Comment by michielverhoef** [comment]
> De geadresseerde is dan dit attribuut?
> Nee. Er staat in de toelichting bij dat attribuut: "Betreft de NAW-gegevens van de geadresseerde [...] indien de geadresseerde daarvan niet gestructureerd is vastgelegd door middel van de relatie ‘INFORMATIEOBJECT.is ontvangen van of verzonden aan BETROKKENE’.". Het gaat mij om die relatie en de relatieklasse VERZENDING.


Helder, dank je!


> In het verlengde hiervan zou ik denken dat het ook nuttig is de afzender vast te kunnen leggen.
> Is zekers nuttig. Maar gaat ook weer met genoemde relatie en relatieklasse.



> Overigens is het al mogelijk om de ontvangst- en verzenddatum vast te leggen, ergens ius het dus een beetje raar dat geadresserde/afzender dan niet vastgelegd kan worden.
> Kan dus in 1.0 al als tekst, in 2.0 gestructureerd. En dat wordt nu wel 's tijd, lijkt me.


Ik bedoelde in de API, in het RGBZ kon dit al zie ik.



> De vraag is even, doen we dit met een verwijzing naar een bron (BRP API oid) of met de gegevens die op dat moment gebruikt zijn?
> Het eerste dus. Er zit vast historie op die bron. Dus kan mbv verzend- of ontvangstdatum altijd achterhaald worden wat de bronwaarden op die datums waren.


Ik neig er toch naar om beide te kunnen doen. Een beetje op de manier zoals de Betrokkene aan een Rol gekoppeld wordt: https://zaken-api.vng.cloud/api/v1/schema/#operation/rol_read 

Hiermee is het mogelijk te verwijzen naar een ander register maar bij gebrek daar aan kunnen de bekende gegevens ook vastgelegd worden in betrokkeneIdentificatie.

**Comment by michielverhoef** [comment]
https://github.com/VNG-Realisatie/documenten-api/pull/147

aangemaakt voor dit issue

**Comment by michielverhoef** [comment]
Zie https://app.swaggerhub.com/apis/michielverhoef/Documenten_API/1.2.0-alpha#/verzendingen/verzending_list

**Comment by michielverhoef** [comment]
Opgelost met relatieklasse Verzending: https://documenten-api.test.vng.cloud/api/v1/schema/#tag/verzendingen

**Comment by michielverhoef** [comment]
De in RGBZ2 gebruikte attribuut namen zijn verwarrend: https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/verzending 

Afwijkend...adres lijkt aan te geven dat normaal gesproken een ander adres gebruikt wordt. De vraag is dan: Welk adres? En wat gebeurt er wanneer dat adres verandert? 

Bij een Verzending moet altijd het adres vastgelegd worden waar dat Informatieobject/document naar verstuurd is, ongeacht het type adres. 

@MatthijsBekendam:

afwijkendBinnenlandsCorrespondentieadresVerzending moet worden binnenlandsCorrespondentieadres
afwijkendbuitenlandsCorrespondentieadresVerzending moet worden buitenlandsCorrespondentieadres
afwijkendCorrespondentiePosteadresVerzending moet worden correspondentiePostadres

**Comment by michielverhoef** [comment]
Bovenstaande wijzigingen zijn doorgevoerd  
https://documenten-api.test.vng.cloud/api/v1/schema/#tag/verzendingen/operation/verzending_retrieve
