### ISSUE TITLE
Updating a zaaktype (PUT) raises an IntegrityError on gerelateerdeZaken 

### ISSUE THREAD

**Issue by shea-maykinmedia** [VNG-Realisatie/gemma-zaken#1772]
# Bug

Bug was first described here https://github.com/open-zaak/open-zaak/issues/851 but happens in Catalogi API (https://github.com/VNG-Realisatie/catalogi-api) as well.

The error is that when doing a `PUT` on the `zaaktypen` endpoint with a `gerelateerdeZaaktypen` an `IntegrityError` will be thrown because there is a `unique_together` on the `ZaakTypenRelatie`

Waar staan de componenten gehost?

I just ran the project locally though I suspect this bug will happen on any environment

Welke claims/payload bevat je JWT?

The example payload I used is below

```
{
    "identificatie": 0,
    "doel": "some test",
    "aanleiding": "aangepast",
    "indicatieInternOfExtern": "extern",
    "handelingInitiator": "indienen",
    "onderwerp": "Klacht",
    "handelingBehandelaar": "uitvoeren",
    "doorlooptijd": "P30D",
    "opschortingEnAanhoudingMogelijk": false,
    "verlengingMogelijk": true,
    "verlengingstermijn": "P30D",
    "publicatieIndicatie": true,
    "verantwoordingsrelatie": [],
    "productenOfDiensten": ["https://example.com/product/123"],
    "vertrouwelijkheidaanduiding": "openbaar",
    "omschrijving": "some test",
    "gerelateerdeZaaktypen": [
        {
            "zaaktype": "http://example.com/zaaktype/3",
            "aard_relatie": "bijdrage",
            "toelichting": "test relations"
        }
    ],
    "referentieproces": {"naam": "ReferentieProces 0", "link": ""},
    "catalogus": "/catalogi/api/v1/catalogussen/1c47a639-51dc-4964-81b3-134dbf7ebd9d",
    "besluittypen": [],
    "beginGeldigheid": "2018-01-01",
    "versiedatum": "2018-01-01"
}
```

**Comment by michielverhoef** [comment]
Zo te zien is dit een versie van een zaaktype wat nog niet gepubliceerd is (concept=false).  Als dat niet zo is mag de PUT helemaal niet gedaan worden, tenzij het een correctie van het zaaktype betreft. zie [ztc-009](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/#ztc-009).

Zo op het oog klopt de payload ook niet. De url verwijzing naar het gerelateerde zaaktype is onzin en levert een 404 op.  Een verwijzing moet geldig zijn dus een http 200 opleveren. Tervens moet het gerelateerde zaaktype ook nog in concept bestaan, zie [ztc-010](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/#ztc-010).

Dit klinkt als verkeerd gebruik van de API.
