### ISSUE TITLE
Maatschappelijke Activiteiten toevoegen aan lijst objecttypes

### ISSUE THREAD

**Issue by OlavAllema** [VNG-Realisatie/gemma-zaken#1774]
# Impediment

Wij gebruiken Open Zaak dat gebaseerd is op informatiemodellen van de VNG. In één van die modellen is een lijst 'object type' onder zaakobjecten. In die lijst staat onder andere 'vestiging' en 'niet-natuurlijke persoon' als opties voor data die gerelateerd is aan organisaties. Het NHR (Nationaal Handelsregister) werkt inmiddels met meerdere objecttypes. De meest belangrijke zijn 'Vestigingen' (VES), 'Niet-Natuurlijke Personen' (NNP) én 'Maatschappelijke Activiteiten' (MA). De eerste twee zijn er dus, maar MA mist.

Ik zie Maatschappelijk Activiteit wel in GEMMA staan als objecttype: https://www.gemmaonline.nl/index.php/Rsgb_3.0/doc/objecttype/maatschappelijke_activiteit

Kort en praktisch gezegd: Kunnen jullie zorgen dat MA wordt toegevoegd aan het lijstje dat Open Zaak uitleest?

**Comment by michielverhoef** [comment]
Dit klinkt als een doublure van #656 . Daarom sluit ik dit issue. Overigens staat #656 wel op de rol om in de komende release opgelost te worden.

**Comment by OlavAllema** [comment]
Die had ik niet gezien, dank. Ik zal #656 gaan volgen
