### ISSUE TITLE
'taal' example value is incorrect in Documents API

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1775]
# Bug

https://documenten-api.vng.cloud/api/v1/schema/#operation/enkelvoudiginformatieobject_create describes for `taal`:

> Een ISO 639-2/B taalcode waarin de inhoud van het INFORMATIEOBJECT is vastgelegd. Voorbeeld: nld. Zie: https://www.iso.org/standard/4767.html

The example `nld` is incorrect - for example on https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes#D `nld` is the terminological code, while `dut` is the bibliographic code. And the `/B` in `ISO 639-2/B` stands for the bibliographic code.

-> the example should specify `dut` instead of `nld`.

**Comment by michielverhoef** [comment]
The easy change would be to replace "nld" with "dut". However, that would mean a breaking change, thus requiring a major release.

A way to migrate would be to label the "nld" value as deprecated and define behaviour of the API to replace incoming "nld" with "dut"to make sure any new data is correct. 

@sergei-maertens @HenriKorver do you have any thoughts on this idea?

**Comment by hdksi** [comment]
Het aanpassen van een voorbeeld veroorzaakt toch geen breaking change?

Overigens denk naar aanleiding van de volgende tekst van Wikipedia (bij gebrek aan toegang tot de bronnorm) dat de meeste wenselijke aanpassing zou zijn niet het voorbeeld, maar de normverwijzing aan te passen. 

> While most languages are given one code by the standard, twenty of the languages described have two three-letter codes, a "bibliographic" code (ISO 639-2/B), which is derived from the English name for the language and **was a necessary legacy feature**, and a "terminological" code (ISO 639-2/T), which is derived from the native name for the language and resembles the language's two-letter code in ISO 639-1. There were originally 22 B codes; scc and scr are now deprecated.
>
>**In general the T codes are favored**; ISO 639-3 uses ISO 639-2/T. 

Echter het afdwingen van het volgen van `/T`- in plaats van `/B`-codes levert wel een breaking change op :)

**Comment by michielverhoef** [comment]
Stom van me, daar had ik over heen gelezen. Ik dacht dat het ging om de enumeratie van toegestane waarden. 
Dat maakt het invuilen van dit issue al weer een heel stuk makkelijker :-) Dank je voor je scherpe blik!

Aangezien in het RGBZ de /B codes al heel lang gebruikt worden vermoed ik dat veel informatie bij gemeenten al gebruik maakt van de /B codes. Dan passen de API's wel beter wanneer die ook nog steeds de /B codes gebruiken.

Mocht het echt nodig zijn de /T codes te gaan gebruiken, kan dan een nieuwe user story ingediend worden?

**Comment by hdksi** [comment]
>daar had ik over heen gelezen

Altijd fijn als ik kan helpen :)

>Dan passen de API's wel beter wanneer die ook nog steeds de /B codes gebruiken.

Ik zie ook geen voldoende zwaarwegende reden om de norm achter de codes aan te passen.

**Comment by michielverhoef** [comment]
example value changed to "dut"

**Comment by sergei-maertens** [comment]
if `/B` is the common standard still used in the current landscape, that would make me in favour of sticking to `/B` and updating the example value, but I don't have any strong feelings about this. It should be an easy data migration if the standard were to switch to `/T` codes (the mapping from `/B` to `/T` can even be provided upfront, as the table is on wikipedia)

**Comment by michielverhoef** [comment]
PR https://github.com/VNG-Realisatie/documenten-api/pull/146 aangemaakt voor dit issue

**Comment by michielverhoef** [comment]
@MatthijsBekendam  dit is een tekstuele aanpassing. Dit graag meenemen bij het releasen van ofwel een volgende RC of de 1.2 versie van de Documenten API.
