### ISSUE TITLE
Zelfde informatieobjecttype meermaals mogelijk maken bij zaaktype

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#1782]
Op dit moment is het niet mogelijk hetzelfde informatieobjecttype twee maal op te voeren bij een zaaktype in Open Zaak.
Het meermaals opvoeren is gewenst als hetzelfde informatieobjecttype meerdere richtingen kan hebben zoals
-	Adviesrapport (intern)
-	Adviesrapport (uitgaand)
-	Adviesrapport (inkomend).
Wij kunnen geen business rule vinden waarin staat de combinatie informatieobjecttype - zaaktype uniek moet zijn. Volgens ons is de constraint van Open Zaak daarom niet conform standaard. 
Wij stellen voor de API-specificatie aan te passen en daarmee dit vraagstuk te verduidelijken op de volgende manier:
1.	De combinatie van de drie velden zaaktype – informatieobjecttype - richting  in zaaktype-informatieobjecttype is uniek (weergeven in informatiemodel of tekst)
2.	Bij zaakinformatieobject komt een nieuw veld richting dat zowel bij het aanmaken als opvragen beschikbaar is
3.	De ZRC valideert bij het aanmaken van een zaakinformatieobject of er een zaaktype-informatieobjecttype bestaat met de gespecificeerde informatieobjecttype en richting (uitbreiding van business rule zrc-003).

**Comment by michielverhoef** [comment]
De relatie tussen informatieobjecttype en zaaktype wordt niet vastgelegd bij informatieobjectype of zaaktype maar in de relatieklasse zaaktype-informatieobjecttype.
https://catalogi-api.vng.cloud/api/v1/schema/#tag/zaaktype-informatieobjecttypen

In deze relatieklasse is het al mogelijk een richting aan te geven. Om hetzelfde informatieobject in de verschillende richtingen te kunnen koppelen aan één zaaktype wordt dus niet drie keer hetzelfde informatieobjecttype aangemaakt maar wordt de relatieklasse drie keer aangemaakt met iedere keer een andere richting.

Nergens in de documentatie vind ik dat het slechts mogelijk is deze relatie maar één keer aan te maken dus dit zou moeten werken, ook in OpenZaak. Mocht dit anders werken moet hiervoor een issue bij OpenZaak aangemaakt worden.

Het lijkt er echter op dat het probleem meer in de praktijk zit en geprobeerd wordt hetzelfde document meerdere malen aan een zaak te koppelen, met als enige verschil de richting. Hiervoor moet niet de relatieklasse ZaakInformatieobject gebruikt worden maar Verzending (https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/verzending) 

In #1770  wordt gevraagd de relatieklasse Verzending toe te voegen. Hiermee kunnen afzender/ontvanger aangegeven worden en ook of het een inkomend of uitgaand document betreft (is ontvangen van of verzonden aan). 

Met Verzending wordt geregistreerd of een informatieobject verstuurd of ontvangen wordt, dit kan onbeperkt dus ook twee (of meer) keer verstuurd is op deze manier vast te leggen. Het enige wat nog niet in Verzending beschreven is, is de mogelijkheid "intern" maar dat nemen we gelijk mee.

**Comment by MNIJ** [comment]
Duidelijk, @michielverhoef, dit is dus blijkbaar een foutje in Open Zaak. Maar wat ons nog niet duidelijk is, is hoe je van een specifiek document bij een zaak kan bepalen wat de richting is. Zowel bij het aanmaken van de relatie (zaakinformatieobject) als bij het ophalen van de relatie.

Het lijkt namelijk niet mogelijk om bij het aanmaken van een zaakinformatieobject te specificeren welk zaaktype-informatieobjecttype gebruikt moet worden. En bij het ophalen zie je dat (dus) ook niet terug.
In Open Zaak kan je dat nu wel bepalen, omdat het er altijd precies één is voor het informatieobjecttype, maar als er meerdere zaaktype-informatieobjecttypes kunnen zijn voor hetzelfde informatieobjecttype (bij hetzelfde zaaktype), is dit niet meer te bepalen.

**Comment by michielverhoef** [comment]
> Het lijkt namelijk niet mogelijk om bij het aanmaken van een zaakinformatieobject te specificeren welk zaaktype-informatieobjecttype gebruikt moet worden.


Een zaakinformatieobject is een aparte relatieklasse:  https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/zaak-informatieobject. Het is dus ook niet mogelijk een zaaktype-informatieobjecttype te selecteren of aan te geven.

Een ZaakInformatieobject is dus geen instantie van het Zaak-Informatieobjecttype: https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/relatieklasse/zaak-informatieobject-type . Op deze pagina staat voor zover ik kan zien niet dat de zaaktype-informatieobjectype per informatieobjecttype slechts 1 keer bij een zaaktype kan worden aangemaakt. 

Een zaakinformatieobject  legt alleen maar vast welke informatieobjecten bij welke zaak horen, zeg maar in het dossier zitten. Dit omdat een document bij meerdere zaken kan horen en meer documenten bij dezelfde zaak. Deze N:M relatie leggen we vast via een relatieklasse. Voor meer informatie over het vastleggen van relaties: https://vng-realisatie.github.io/gemma-zaken/themas/achtergronddocumentatie/ontwerpkeuzes  onder het kopje "Vertaling van relaties".

Met zaaktype-informatieobjecttype wordt in de Zaaktypecatalogus bepaald welke documentsoorten voor een bepaald zaaktype nodig/toegestaan zijn. 

In de Zaken API kun je zien dat de attributen van ZaakInformatieObject niet volgens de structuur van Zaaktype-Informatiebjecttype zijn: https://zaken-api.vng.cloud/api/v1/schema/#operation/zaakinformatieobject_read 

Zoals ik al beschreven heb: Het registreren van het verzenden of ontvangen van een document gebeurt met de relatieklasse Verzending. In de Verzending kan ook de afzender of ontvanger, datum onvangst of verzending etc. worden vastgelegd. Dit is nu nog niet mogelijk in de huidige versie van de Documenten API maar zal meegenomen worden in de release die gepland staat voor deze zomer.  Voor meer uitleg over de oplossingsrichting en relatieklasse Verzending, zie ook #1770 en https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/verzending .

**Comment by johannesbattjes** [comment]
Beste Michiel, in dat geval verwoorden wij ons wijzigingsverzoek als volgt: Bij zaakinformatieobject komt een nieuw veld _richting_ dat zowel bij het aanmaken als opvragen beschikbaar is.

Zodat gebruikers in de UI gemakkelijk kunnen fileteren op inkomende documenten - bijvoorbeeld om die toe te voegen aan het besluit of om een advies op te baseren.

**Comment by michielverhoef** [comment]
Beste Johannes,

De door jullie gewenste richting wordt (zal worden) vastgelegd via de relatieklasse Verzending. samen met andere metadata zoals de (adres)gegevens van de afzender of verzender, ontvangst/verzenddatum etc. 

De relatieklasse ZaakInformatieobject geeft aan dat een Informatieobject onderdeel is van een zaakdossier, meer niet. Het is dus ook niet mogelijk of gewenst om meerdere ZaakInformatieobjecten aan te maken in het geval een Informatieobject bijvoorbeeld zowel ontvangen als  verstuurd is. 

Wel begrijp ik de behoefte aan kunnen filteren aan inkomende of uitgaande Informatieobjecten. Dit gaat dan ingevuld worden met een convenience call waarmee in één aanroep Informatieobjecten met een bepaalde richting opgevraagd kunnen worden. Analoog aan de zaak_zoek opdracht in de Zaken API: https://zaken-api.vng.cloud/api/v1/schema/#operation/zaak__zoek 


Ik stel deze user story voor:
Als ontwikkelaar wil ik Informatieobjecten op richting (inkomend, uitgaand, intern) kunnen filteren zodat ik relevante binnengekomen/verzonden Informatieobjecten toe kan voegen aan een Besluit of om een advies op te baseren.

**Comment by MNIJ** [comment]
Beste Michiel,
Dat klinkt werkbaar, maar het ligt er wel aan hoe de relatieklasse Verzending opgenomen wordt in de API standaard. Het gaat er dan vooral om of het mogelijk is om de richting van het informatieobject al via de Verzending vast te leggen, zonder dat er al een specifieke Geadresseerde/Afzender vast ligt. Als ik naar de klasse kijk, ben ik bang dat dat niet kan aangezien het een relatie tussen een informatieobject en een betrokkene vast legt en beide dus moeten bestaan.

Dat kan in de praktijk voor een kip-ei probleem zorgen en in ieder geval voor meer verplichte registratie bij het toevoegen van een document aan een zaak, waarbij dat zowel moet gebeuren door een eindgebruiker als deze een document toevoegt of door een client applicatie als het geautomatiseerd gebeurt.

Er zijn bovendien meer user stories voor een Zaak Afhandelcomponent waarin de richting van het informatieobject van belang is, een aantal voorbeelden:

"Als zaakbehandelaar wil ik alleen de relevante metadata kunnen vastleggen bij een informatieobject, zodat de metadata overzichtelijk is en ik geen fouten kan maken."
De ontvangstdatum is alleen bij een inkomend document van toepassing en de verzenddatum alleen bij een uitgaand document. Bovendien zijn bepaalde combinaties van informatieobject-status en deze datumvelden niet toegestaan [drc-005](https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/index#drc-005). Als een Zaak Afhandelcomponent de richting van het informatieobject weet, kan al in de UI gezorgd worden dat de eindgebruiker alleen datumvelden en statussen kan invullen die kloppen met de richting van het document.

"Als functioneel beheerder wil ik kunnen afdwingen dat een type informatieobject aanwezig is in de zaak als een bepaalde status wordt bereikt, zodat we weten dat het zaakdossier op orde is."
De entiteit Zaaktype-Informatieobjecttype bevat een veld _statustype_, met als beschrijving "URL-referentie naar het STATUSTYPE waarbij deze INFORMATIEOBJECTTYPEn verplicht aanwezig moeten zijn." De bedoeling daarvan is, als ik het goed begrijp, om aan te geven dat er minimaal één informatieobject van dat type in de zaak aanwezig moet zijn voor de zaak de opgegeven status bereikt. Nou is er zo te zien (nog) geen business rule in de ZRC die hier iets mee doet, maar als een Zaak Afhandelcomponent dit wil afdwingen (of op zijn minst de gebruiker waarschuwen), moet de richting van de informatieobjecten bij de zaak bekend zijn.
Bijvoorbeeld:
Een zaaktype "Advies verstrekken" heeft o.a. de zaaktype-informatieobjecten:

- Informatieobjecttype = Advies; Richting = inkomend; statustype = null
- Informatieobjecttype = Advies; Richting = uitgaand; statustype = 'Beoordeling uitgevoerd'

Vervolgens is een zaak van dit type in behandeling. De zaak heeft 1 of meer informatieobjecten van type 'Advies'.  Zonder de richting van deze adviezen te weten, kan het systeem niet bepalen of aan de voorwaarde "er moet een uitgaand advies aanwezig zijn" voldaan is en het dus is toegestaan om naar de status 'Beoordeling uitgevoerd' te gaan.

**Comment by michielverhoef** [comment]
Beste Michiel,

Het is m.i. niet zinvol om een Verzending vast te leggen als er nog geen sprake is geweest van een Verzending (ontvangen of verzenden) van een Informatieobject. Met Verzending wordt het daadwerkelijke verzenden of ontvangen vastgelegd, niet het feit dat een Informatieobject verzonden zou kunnen worden.

> Een zaaktype "Advies verstrekken" heeft o.a. de zaaktype-informatieobjecttypen:
> 
>    Informatieobjecttype = Advies; Richting = inkomend; statustype = null
>    Informatieobjecttype = Advies; Richting = uitgaand; statustype = 'Beoordeling uitgevoerd'
>
> Vervolgens is een zaak van dit type in behandeling. De zaak heeft 1 of meer informatieobjecten van type 'Advies'. Zonder de richting van deze adviezen te weten, kan het systeem niet bepalen of aan de voorwaarde "er moet een uitgaand advies aanwezig zijn" voldaan is en het dus is toegestaan om naar de status 'Beoordeling uitgevoerd' te gaan. 


In je voorbeeld gaat het om een informatieobjecttype Advies, ik ga er even vanuit dat dit in beide gevallen om hetzelfde informatieobjecttype (IOtype) gaat. Dit IOtype wordt in een bepaalde status van de zaak ontvangen en in een andere status verzonden.  De zaak heeft 1 keer een Informatieobject van het type "Advies".  Tenminste, zo begrijp ik je voorbeeld.

Het is dus niet zo dat er twee keer een Informatieobject aan een zaak wordt gekoppeld maar dat dit informatieobject twee keer een Verzending krijgt, In de validatie van de richting zal dus gecontroleerd moeten worden of er een Verzending met de juiste richting bestaat. Bij het voorbeeld wordt bij het statustype "Beoordeling uitgevoerd" dit Informatieobject niet nogmaals aangemaakt maar wordt een tweede instantie van Verzending aangemaakt.

Ik kan het verkeerd hebben maar ik krijg steeds de indruk dat jullie in dit voorbeeld het Informatieobject twee keer willen registreren. Dat is niet correct. Het Informatieobject wordt 1 (één) keer geregistreerd als ZaakInformatieobject en daarmee toegevoegd aan het dossier.  In het eerste geva;l wordt het ontvangen vanuit "intern" en wordt een Verzending aangemaakt. In het tweede geval wordt datzelfde Informatieobject (met dezelfde relatieklasse ZaakInformatieobject!) verstuurd en wordt wederom een Verzending aangemaakt. Er wordt *geen* nieuw ZaakInformatieobject aangemaakt.

Nogmaals, de validatie of het bewuste Informatieobject verstuurd is bij het bereiken van de status "Beoordeling uitgevoerd" is dus niet of er een zaakInformatieobject bestaat (dat bestaat al, het Informatieobject zit al in het zaakdossier) maar of er een Verzending aangemaakt is. 



Ik bespeur nog een dingetje in je argumenten: 

>Dat kan in de praktijk voor een kip-ei probleem zorgen en in ieder geval voor meer verplichte registratie bij het toevoegen van een document aan een zaak, waarbij dat zowel moet gebeuren door een eindgebruiker als deze een document toevoegt of door een client applicatie als het geautomatiseerd gebeurt

De API standaard schrijft niet voor wat voor handelingen een eindgebruiker moet verrichten. Dat is het domein van de leverancier om een zo gunstig mogelijk UX en procesflow te maken zodat de eindgebruiker het prettigst werkt. De gebruiiker van de API's is de ontwikkelaar. Aangezien de API's generiek (nl. het vastleggen van gegevens mbt zaakgericht werken) zijn en niet alleen voor specifieke applicaties kan het zijn dat een ontwikkelaar meerdere calls uit moet voeren om de eindgebruiker niet teveel verschillende dingen te moeten laten doen. Het optimaliseren van de eindgebruikerservaring verschilt per applicatie en is dus een taak van de leveranciers.

**Comment by michielverhoef** [comment]
Wellicht ten overvloedde maar voor de zekerheid: Ook vanuit de eindgebruiker geredeneerd is het registreren van Verzending volkomen logisch. Immers, je registreert het document niet nogmaals maar alleen dat je het document verstuurd of ontvangen hebt.

**Comment by MNIJ** [comment]
Wederom bedankt voor je snelle antwoord. Blijkbaar was mijn voorbeeld niet helemaal duidelijk.

Het is niet onze bedoeling om hetzelfde informatieobject meerdere keren bij dezelfde zaak te registreren. We voorzien wel meerdere informatieobjecten van hetzelfde type bij dezelfde zaak en in verschillende richtingen. Om weer het voorbeeld van die advieszaak te nemen:
Uiteindelijk moet die zaak één uitgaand adviesdocument leveren. Maar mogelijk heeft de behandelaar van de zaak voor het opstellen van dat advies zelf ook weer advies gevraagd binnen de eigen organisatie of bij andere organisaties en zijn er dus ook een aantal inkomende of interne adviesdocumenten bij de zaak geregistreerd (dit scenario komt in de praktijk gewoon voor). De inkomende en uitgaande informatieobjecten zijn dus echt verschillende documenten met een heel andere rol in het proces van de zaak, maar wel met hetzelfde Informatieobjecttype.

Dit is maar één van de scenario's waarin het van belang is om al voor een document daadwerkelijk verzonden is, te weten of het gaat om een uitgaand document, er staan in dit issue ook al een paar andere (filteren, de juiste metadata velden aanbieden). En daar voorziet de standaard ook bijna in, maar net niet helemaal, omdat zaaktype-informatieobjecttype wel het veld _richting_ kent, maar zaakinformatieobject niet. Waarmee ik niet wil suggereren dat een zaakinformatieobject een instantie is van een zaaktype-informatieobjecttype of zo. Maar het zaakinformatieobject zegt wat over de relatie van de zaak met het informatieobject en de richting is daar een belangrijk onderdeel van.

Verder heb je helemaal gelijk dat het aan ons als leverancier is om een Zaak Afhandelcomponent te maken die in een goede UX voorziet. Maar in dit geval biedt de standaard geen handvat om iets te bepalen wat volgens ons van wezenlijk belang is voor die goede UX. We zouden dit alleen kunnen oplossen door buiten de standaard om extra metadata bij Informatieobjecten te registreren en dat zouden we liever vermijden.

**Comment by MNIJ** [comment]
> Nogmaals, de validatie of het bewuste Informatieobject verstuurd is bij het bereiken van de status "Beoordeling uitgevoerd" is dus niet of er een zaakInformatieobject bestaat (dat bestaat al, het Informatieobject zit al in het zaakdossier) maar of er een Verzending aangemaakt is.

Ik had hier bewust deze status gekozen in het voorbeeld. Het later te verzenden adviesdocument moet dan al bestaan, maar moet nog geaccordeerd en vastgesteld worden en wordt pas 1 of 2 statussen later daadwerkelijk verzonden. Het is dus niet zo dat een document pas een uitgaand document wordt op moment van verzenden. Al bij de creatie van het document weet je of dit in het proces een inkomend, uitgaand of intern document is, ook al vindt de daadwerkelijke verzending van een uitgaand document pas later plaats, of zelfs helemaal niet omdat het voor verzending wordt afgekeurd of de zaak wordt ingetrokken. En al voor de verzending is het nuttig om het onderscheid te kunnen maken tussen ontvangen documenten en documenten die bedoeld zijn om verzonden te worden.

**Comment by michielverhoef** [comment]
>  En al voor de verzending is het nuttig om het onderscheid te kunnen maken tussen ontvangen documenten en documenten die bedoeld zijn om verzonden te worden.


Dat zou ik dan niet vastleggen in ZaakInformatieobject. Een Informatieobject (IO) kan immers ontvangen zijn bij bijvoorbeeld een aanvraag voor een bouwvergunning, denk aan een bouwtekening. Vervolgens wordt dat IO doorgestuurd naar een interne afdeling om beoordeeld te worden en tot slot wordt het IO als bijlage meegestuurd met bet Besluit waarin de vergunning verleend wordt. 

Bij het aanmaken van een Verzending kan dit wel.  Wat een mogelijkheid zou kunnen zijn is het attribuut concept toe te voegen. In dit voorbeeld wordt dan een Verzending met concept ="true" aangemaakt. Het IO is dan nog niet verzonden maar de overige gegevens zoals geadresseerde kunnen wel opgenomen zijn.  Na accordering kan het IO verzonden worden en wordt concept op false gezet.

Persoonlijk zou ik dan ook een verzend- of ontvangstdatum opnemen in plaats van die bij het EnkelvoudigInformatieObject op te nemen. Dat staat nu nog niet in https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/verzending beschreven maar door het aan Verzending te koppelen kun je in ieder geval het versturen aan meerdere ontvangers goed registreren.  Ik heb US #1785 hiervoor aangemaakt.

Wanneer Verzending een verzenddatum kent is het even de vraag of concept nog wel nodig is. Wanneer een Verzending nog geen verzenddatum kent is deze alleen klaargemaakt en nog niet daadwerkelijk verzonden.

**Comment by Jinze82** [comment]
Mooie ontwikkeling, de kip ei discussie vindt ik echter wel interessant ten aanzien van de documentflow. Een inkomend, intern of uitgaand document heeft een andere beginstatus en volgt een ander pad om te bewandelen. In het “oude” standaard zou de combinatie [Richting] + [documenttype-generiek] wat mij betreft uniek genoeg zijn om de juiste bij behorende documentflow definitie, met juiste achtereenvolgende statussen te bepalen. Maar mogelijk dat dit ook anders kan en mooier zonder het verwarrende begrip richting. 

**Een nieuw issue?**
_“Als gebruiker of beheerder zou ik bij een aan te maken of te registreren informatieobject niet alleen de juist begin status willen vastleggen maar ook de juiste documentflowdefinitie aan vast willen koppelen voor behandeling.“_

**Comment by michielverhoef** [comment]
Er vanuitgaande dat het laatste commentaar inderdaad in een nieuw issue opgepakt wordt is dit issue opgelost met relatieklasse Verzending in Documenten API 1.2: https://documenten-api.test.vng.cloud/api/v1/schema/#tag/verzendingen
