### ISSUE TITLE
Als PO van het API Test Platform wil ik dat het testscript voor de ZGW API's opgesplitst wordt per API

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#1788]
zodat je precies kunt zien welke API's uit de ZGW-familie voldoen aan de standaard. Nu is het zo dat als één van de onderdelen faalt de hele test faalt. Bovendien moeten leveranciers die een deel van de ZGW API's hebben geïmplementeerd ook de mogelijkheid hebben om hun API's te kunnen testen.

**Comment by HenriKorver** [comment]
Ik dacht dat we deze US al eens eerder hadden ingediend, maar ik kon hem niet terug vinden. Vandaar deze hernieuwde inzending.

**Comment by alextreme** [comment]
Helder en dank voor het aanmaken.

Ik heb dit al even besproken met Joeri, en de complicaties zit 'm in het feit dat er afhankelijkheden zijn tussen de componenten. Je kan (als ik de spec goed herinner) wel los een document indienen, maar zonder zaakcomponent kun je 'm niet aan een zaak hangen. En een zaak heeft een zaaktype nodig, dus er is een afhankelijkheid met een ZTC.

Dus hoewel het eenvoudig lijkt, we moeten dan wel per component bepalen welke testcases nog overblijven als we de afhankelijkheden eruit halen. Of jullie moeten ander beeld hierbij hebben hoe we de opsplitsing voor elkaar krijgen, bijvoorbeeld testsuites aanmaken waarbij wel alle componenten aanwezig dienen te zijn maar (behalve de setup-calls) de andere componenten slechts beperkt aanroepen. De vraag is dus hoe ver jullie de opsplitsing per API voor je zien.

Een derde mogelijkheid om een deel-test uit te voeren is door wel de volledige testsuite uit te voeren, maar bijvoorbeeld (als je alleen een DRC wilt testen) gebruik te maken van de referentiecomponenten voor alle componenten anders dan de DRC.

**Comment by HenriKorver** [comment]
@alextreme Ja je hebt gelijk de materie is taaier dan aanvankelijk gedacht. Ik dacht even aan een quick-win, maar ik vrees dat we deze wens toch nog maar even op de backlog moeten bewaren om goed uit te rijpen. De ZGW API's hebben blijkbaar teveel afhankelijkheden om zomaar even op een blauwe maandag uit elkaar te trekken.

**Comment by HenriKorver** [comment]
Dus laten we eerst maar zorgen dat we het bestaande integrale testscript werkend krijgen voor de referentie-implementaties, zie #1598

**Comment by alextreme** [comment]
Prima doen we dat. De enige quick-win die ik zag is dat we varianten van de huidige testscript maken die minder strikt zijn wat het makkelijker maakt om voor een deelgebied 'groen' te zijn, maar daarmee los je het probleem niet op dat je een leverancier met alleen een DRC zo'n component wilt kunnen laten testen zonder afhankelijkheden. "Loosely-coupled-but-dependant".

**Comment by michielverhoef** [comment]
> @alextreme Ja je hebt gelijk de materie is taaier dan aanvankelijk gedacht. Ik dacht even aan een quick-win, maar ik vrees dat we deze wens toch nog maar even op de backlog moeten bewaren om goed uit te rijpen. De ZGW API's hebben blijkbaar teveel afhankelijkheden om zomaar even op een blauwe maandag uit elkaar te trekken.

Op basis hiervan sluit ik dit issue. Mocht het toch nodig blijken kunnen we het altijd heropenen.
