### ISSUE TITLE
Als medewerker van 14070* wil ik dat het integrale klantbeeld proactief wordt opgehaald

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1791]
Als medewerker van 14070* wil ik dat het integrale klantbeeld (zaken lopend en historie, contact momenten, klant contact gegevens) proactief wordt opgehaald (op basis van een klantkenmerk bijv. telefoonnummer) op het moment dat een klant contact zoekt, zodat ik beter in staat gesteld wordt de vraag van de klant te beantwoorden en ik eenvoudig dit nieuwe contact moment kan vastleggen en indien nodig, een contact verzoek kan aanmaken.* 14070 staat ook voor baliemedewerkers, consulenten en het callcenter van SZW

**Comment by michielverhoef** [comment]
Dit is functionaliteit van de consumer applicatie, in dit geval het systeem van het KCC, en valt buiten scope van de API's voor Zaakgericht werken.
