### ISSUE TITLE
Als medewerker van 14070* wil ik dezelfde mogelijkheden hebben indien het contact via een ander kanaal binnenkomt.

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1792]
Als medewerker van 14070* wil ik dezelfde mogelijkheden hebben indien het contact via een ander kanaal dan de telefoon binnenkomt (mail, SMS, chat, social media)

**Comment by michielverhoef** [comment]
Welke mogelijkheden worden hier bedoeld?

**Comment by VerbeekIT** [comment]
De mogelijkheden die gevraagd worden in user story #1791. Dit is een hele set van user stories die ik aan het invoeren ben.

**Comment by michielverhoef** [comment]
Dan ga ik deze user story ook sluiten om dezelfde reden.

Dit is functionaliteit van de consumer applicatie, in dit geval het systeem van het KCC, en valt buiten scope van de API's voor Zaakgericht werken.
