### ISSUE TITLE
Als klant van de gemeente Den Haag wil ik mijn contact gegevens kunnen vastleggen en mijn voorkeurskanaal kunnen aangeven 

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1793]
Als klant van de gemeente Den Haag wil ik mijn contact gegevens kunnen vastleggen en mijn voorkeurskanaal kunnen aangeven zodat er via mijn voorkeurskanaal contact met mij wordt opgenomen. Dit wil ik soms per zaaktype kunnen overrulen.

**Comment by hdksi** [comment]
Zie ook #1794 voor het vastleggen van een `voorkeurskanaal` op klantniveau.  Ervan uitgaande dat in gevallen dat een inwoner of ondernemer het initiatief neemt voor het aanvragen van een product of dienst de `zaak` waarbij voorafgegaan wordt aan een `productaanvraag` (of verzoek), is het het meest logisch daar (en niet bij `zaak`) de mogelijkheid te bieden een `voorkeurskanaal` vast te leggen. In de huidige Verzoeken API is die mogelijkheid voorzien

**Comment by VerbeekIT** [comment]
Dan moet de klant voor ieder contact met de gemeente opnieuw zijn voorkeur vastleggen. Het is logischer om dit 1-malig en te doen en eventueel te overrulen voor een specifieke zaak indien nodig. Dit voorkeurskanaal is ook nodig indien er communicatie vanuit de gemeente naar de burger/ondernemer plaatsvindt(pro-actief) waar (nog) geen zaak aan ten grondslag ligt.

**Comment by hdksi** [comment]
Oplossing: generiek voorkeurskanaal kunnen vastleggen bij `klant`, specifiek voorkeurskanaal kunnen vastleggen bij `productaanvraag` of `contactmoment`.

@VerbeekIT: moet er dan ook nog een voorkeurskanaal bij `zaak` kunnen worden vastgelegd voor zaken die niet worden voorafgegaan door een productaanvraag?

**Comment by hdksi** [comment]
In de eerste instantie alleen een voorkeurskanaal invoegen bij Klant.

**Comment by hdksi** [comment]
Hoort bij #1794.

**Comment by HenriKorver** [comment]
@melsk-r Kun je deze twee velden toevoegen aan het SIM?

**Comment by HenriKorver** [comment]
Ivo's commentaar uit de review verwerkt, zie https://github.com/HenriKorver/gemma-zaken/commit/e68f8dcbf8f71bb7ca6aee920bceb1eca9b03784
