### ISSUE TITLE
Als medewerker van 14070* wil ik de klant contact gegevens kunnen inzien en deze kunnen vastleggen of wijzigen

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1794]
Als medewerker van 14070* wil ik de klant contact gegevens kunnen inzien en deze kunnen vastleggen of wijzigen of op verzoek van de klant. Daarbij wil ik kunnen aangeven wat het voorkeurskanaal van de klant is zodat er via dit voorkeurskanaal contact met de klant wordt opgenomen.
* 14070 staat ook voor baliemedewerkers, consulenten en het callcenter van SZW

**Comment by hdksi** [comment]
Binnen de specs van de bestaande Contactmomenten API is het mogelijk de volgende attributen vast te leggen

- `kanaal` Het communicatiekanaal waarlangs het CONTACTMOMENT gevoerd wordt
- `voorkeurskanaal` Het communicatiekanaal dat voor opvolging van de klantinteractie de voorkeur heeft van de KLANT.

Merk op dat hier gesproken wordt over 'opvolging van de klantinteractie'. Voor het 'duurzamer' vastleggen van een voorkeurskanaal (dus een voorkeurskanaal dat niet alleen binnen de context van één enkele interactie wordt gebruikt) is het voorstel een mogelijkheid op te nemen ook bij `klant` een `voorkeurskanaal` vast te leggen.

**Comment by joeribekker** [comment]
+1

**Comment by hdksi** [comment]
Oplossing: ook bij klant een voorkeurskanaal kunnen vastleggen.

**Comment by HenriKorver** [comment]
Gedaan, zie #1793
