### ISSUE TITLE
Als medewerker van 14070* wil ik een contactverzoek (terugbel notitie, TBN) kunnen uitzetten

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1795]
Als medewerker van 14070* wil ik een contactverzoek (terugbel notitie, TBN) kunnen uitzetten bij een andere medewerker of organisatie onderdeel van de gemeente Den Haag zodat de klant terug gebeld wordt indien ik de vraag van de klant niet heb kunnen beantwoorden.

**Comment by hdksi** [comment]
Grosso modo zijn er twee manieren om dit op te lossen:

1. 1. Een terugbelverzoek is een `zaak` van passend `zaaktype` met gekoppeld `contactmoment` dat de inhoud van het initiërende contact van de gemeente met de `klant` beschrijft. Deze `zaak` kan worden toegewezen aan de afdeling of persoon die de vraag van klant kan beantwoorden.
2. we voegen een resource `contactverzoek` (o.i.d.) toe aan de Contactmomenten API, waarbinnen relaties kunnen worden gelegd tussen:
- de indienende medewerker,
- het contactmoment dat de aanleiding voor het contactverzoek was,
- de afhandelende (dus terugbellende) medewerker of afdeling,
- een status (nieuw/afgehandeld), en
- het contactmoment dat de beantwoording van de klantvraag beschrijft.

**Comment by VerbeekIT** [comment]
Wat mij betreft optie 1. De medewerker ziet dan al zijn zaak gerelateerde taken in hetzelfde dashboard. Alle zaken worden op dezelfde manier afgehandeld.

**Comment by HenriKorver** [comment]
Optie 1 lijkt mij ook een prima keuze. Dit houdt in dat we geen nieuwe features aan de Contactmomenten API hoeven toe te voegen. Immers in de Zaken API is sinds versie [1.1.0](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/zaken-api/1.1.0/src/openapi.yaml#operation/zaakcontactmoment_create) de resource `zaakcontactmomenten` opgenomen waarmee zaken aan contactmomenten kunnen worden gekoppeld.

**Comment by hdksi** [comment]
Akkoord.
