### ISSUE TITLE
Als medewerker van 14070 wil ik inzicht in de status van openstaande contactverzoeken (TBN’s)

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1797]
Als medewerker van 14070 wil ik inzicht in de status van openstaande contactverzoeken (TBN’s) die ik heb uitgezet zodat ik kan zien of deze verzoeken zijn opgevolgd.

**Comment by hdksi** [comment]
Zie #1795 voor mogelijke oplossingen bij deze story.

**Comment by hdksi** [comment]
Dit inzicht wordt geleverd middels de status van de naar aanleiding van het contactverzoek gestarte zaak.
