### ISSUE TITLE
Als medewerker van de gemeente Den Haag  wil ik geattendeerd worden als er een contactverzoek (TBN) is

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1798]
Als medewerker van de gemeente Den Haag  wil ik geattendeerd worden als er een contactverzoek (TBN) voor mij of voor mijn organisatie onderdeel is aangemaakt. Daarbij wil ik eenvoudig toegang tot het contactverzoek (TBN) en de contact gegevens van de klant, zodat ik kan reageren op het contact verzoek van de de klant en daarbij de relevante gegevens bij de hand heb

**Comment by michielverhoef** [comment]
Dit is al mogelijk door gebruik te maken van de Notificaties API. Deze is daar speciaal voor gemaakt.

Zie ook #792
