### ISSUE TITLE
Als behandelaar wil ik een besluit inzake een lopende zaak kunnen invoeren in mijn vakapplicatie

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#18]
zodat deze in het zaaksysteem opgeslagen kan worden (en alle relevante) betrokkenen op de hoogte gebracht kunnen worden

**Comment by TCIMEddy** [comment]
@sergei-maertens Volgens mij kan dit al toch? (Met BRC-API)

**Comment by sergei-maertens** [comment]
@TCIMEddy klopt - de pull requests hiervoor zijn wel nog in progress/in review.

**Comment by TCIMEddy** [comment]
Deze zet ik op close en naar archief
