### ISSUE TITLE
Als medewerker van de gemeente Den Haag  wil ik inzicht in de openstaande contactverzoeken (TBN)

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1800]
Als medewerker van de gemeente Den Haag  wil ik inzicht in de openstaande contactverzoeken (TBN) voor mij of voor mijn organisatie onderdeel zodat ik weet welke contact verzoeken er nog open staan.

**Comment by hdksi** [comment]
Zie #1795 voor oplossingen bij terugbelnotities. Beide daar gegeven opties ondersteunen deze user story.

**Comment by michielverhoef** [comment]
aangezien https://github.com/VNG-Realisatie/klantinteracties/issues/114 gesloten is ga ik er van uit dat dit issue ook gesloten kan worden.
