### ISSUE TITLE
Als dienst binnen de gemeente wil ik persoonsgebonden tips kunnen verstrekken

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1804]
Als dienst binnen de gemeente wil ik persoonsgebonden tips kunnen verstrekken aan de klanten van de gemeente. Bijvoorbeeld: ‘ U heeft recht op een bijstandsuitkering. Weet U dat U ook huursubsidie kunt aanvragen ?’ zodat ik klanten van de gemeente opmerkzaam kan maken op aanvullende producten en diensten van de gemeente die relevant kunnen zijn in de specifieke situatie van deze klant.

**Comment by michielverhoef** [comment]
Zie ook #1807 #1808.
Dit is functionaliteit van een (vak)applicatie die de Notificaties ontvangt, relevante gegevens opvraagt en een bericht voor de betreffende klant samenstelt en dit verstuurt.

Dit is geen onderdeel van de API's voor Zaakgericht werken maar functionaliteit van een consumer.
