### ISSUE TITLE
Als dienst binnen de gemeente wil ik burgers van de gemeente op de hoogte /kunnen stellen van nieuwe producten en/of diensten

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1805]
Als dienst binnen de gemeente wil ik burgers van de gemeente via MijnDenHaag (multi channel) op de hoogte /kunnen stellen van nieuwe producten en/of diensten die door de gemeente worden aangeboden. Vanaf 1 januari 2021 is de regeling …. aangepast zodat de klanten van de gemeente op de hoogte zijn van veranderingen in het aanbod van producten en diensten van de gemeente.

**Comment by michielverhoef** [comment]
Zie ook #1807 #1808.
Dit is functionaliteit van een (vak)applicatie die de Notificaties ontvangt, relevante gegevens opvraagt en een bericht voor de betreffende klant samenstelt en dit verstuurt.

Dit is geen onderdeel van de API's voor Zaakgericht werken maar functionaliteit van een consumer.
