### ISSUE TITLE
Als dienst binnen de gemeente wil ik een klant van de gemeente proactief kunnen notificeren

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1807]
Als dienst binnen de gemeente wil ik een klant van de gemeente proactief kunnen notificeren dat er een status update heeft plaatsgevonden in een van de lopende zaken van deze klant zodat de klant voortdurend op de hoogte is van de status van de zaak.

**Comment by michielverhoef** [comment]
Zie ook #1808 Dit is functionaliteit van een (vak)applicatie die de Notificaties ontvangt, relevante gegevens opvraagt en een bericht voor de betreffende klant samenstelt en dit verstuurt.

Dit is geen onderdeel van de API's voor Zaakgericht werken maar functionaliteit van een consumer.
