### ISSUE TITLE
Als klant van de gemeente wil ik, op het moment dat ik een notificatie ontvang van de gemeente, direct geleid worden naar het betreffende onderwe

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1808]
Als klant van de gemeente wil ik, op het moment dat ik een notificatie ontvang van de gemeente, direct geleid worden naar het betreffende onderwerp / de betreffende zaak zodat ik niet hoef te zoeken.

**Comment by michielverhoef** [comment]
Ook hier moeten we even offline over praten om zeker te zijn dat we over hetzelfde praten.

In ieder geval in een notendop: De notificaties van de Notificatie API zijn geen berichten die rechtstreeks naar een burger, via mail of mijnBerichtenbox oid,  gaan. Dit zijn berichten die naar een ontvangend systeem gaan. Op basis van het bericht kan het ontvangende systeem dan de gewijzigde gegevens opvragen.

**Comment by VerbeekIT** [comment]
Hallo Michiel,

Ik zie een heleboel reacties van jou op mijn user stories. Deze user
stories heb ik op github geplaatst op verzoek van Ivo Hendriks.
Ze zijn bedoeld voor het valideren van de klant contact API's
Ik had vorige week een weekje vakantie en heb daarom niet eerder gereageerd.
Wil je een afspraak plannen om de stories door te spreken ?

 Met vriendelijke groet,



*Jan Verbeek*

Solution architect / informatie adviseur



TO I&A

Cluster Automatisering

Projecten & Architectuur

Gemeente Den Haag



Mobiel:  +31 6 4624 3617

Email :   ***@***.***

Op wo 21 apr. 2021 om 17:13 schreef Michiel Verhoef <
***@***.***>:

**Comment by hdksi** [comment]
Inderdaad hebben we op dit moment geen (API-)standaard in ons portfolio die deze functionaliteit ondersteunt. Vanuit het perspectief van de API-standaarden voor Zaakgericht werken is volgens mij alleen te zeggen dat dit is een kwestie is van de juiste resources via een link beschikbaar/toegankelijk maken voor de klant.

**Comment by Hugo-ter-Doest** [comment]
Lijkt me functionaliteit van een applicatie om een link toe te voegen aan het bericht aan de inwoner waarmee deze direct door kan klikken.

**Comment by hdksi** [comment]
Logische vraag, maar een antwoord valt zoals hierboven beschreven buiten scope van de API-standaarden voor Zaakgericht werken of Klantinteracties.
