### ISSUE TITLE
Als dienst binnen de gemeente wil ik een specifieke doelgroep proactief kunnen benaderen

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1809]
Als dienst binnen de gemeente wil ik een specifieke doelgroep proactief kunnen benaderen zodat de doelgroep op de hoogte is van wijzigingen in het aanbod van producten en diensten van de gemeente.. De doelgroep (BSN nrs / Klant nrs ?) en de mededeling worden hiervoor door de dienst aangeleverd aan de ZGW component.

**Comment by michielverhoef** [comment]
Deze user story is nog te vaag wat mij betreft. Mijn gevoel zegt me dat dit geen zaakgericht werken betreft.

Een ZaakRegistratieComponent (ZRC) is geen adresboek. Het is mogelijk betrokkenen (ROLlen) bij een zaak te registreren. Het is mogelijk deze betrokkenen (ROLlen) op te vragen en met die informatie iets te doen. Dat is echter aan de consumerapplicatie.

Misschien begrijp ik de casus helemaal verkeerd, ik zal volgende week even contact opnemen om hier eens offline over te praten.

**Comment by hdksi** [comment]
Vraag is welke segmenten je als doelgroep wil onderscheiden.

Je kan (mits de juiste grondslag/doelbinding voorhanden is) `klantgegevens` gebruiken, maar behalve op leefomgeving lijken me daar weinig gegevens in te zitten op basis waarvan je een waardevolle/relevante selectie kunt maken. Wel zou je bijvoorbeeld kunnen kijken welke klant binnen een bepaalde historische periode een specifiek product heeft aangevraagd. _Cruciaal is hier wederom de vraag met welke doelbinding en op basis van welke grondslag je deze gegevens hebt bewaard en verwerkt_

**Comment by VerbeekIT** [comment]
Het bepalen van de doelgroep valt buiten de scope van deze API's. Wat hier wel relevant is, is dat het bericht van de gemeente aan de burger/ondernemer in de doelgroep in de contactmomenten vastgelegd moet kunnen worden. Zodra de burger/ondernemer hierop reageert kan de medewerker van de gemeente in het integrale klantbeeld zien waarop gereageerd wordt.
