### ISSUE TITLE
Als beheerder van standaarden wil ik een goed advies uit kunnen brengen aan gemeenten die nu met de huidige StUF gebaseerde standaarden willen koppelen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#181]
...zodat gemeenten kunnen investeren in systemen en koppelingen die ook in de nabije toekomst blijven werken.

Toelichting:  Op dit moment zijn gemeenten en leveranciers ook aan het werk en worden zaaksystemen gekoppeld, onder andere met StUF ZKN en ZDS 1.1 (ZDS 1.2 is helaas niet geimplementeerd door leveranciers) . Deze oude standaarden voldoen niet aan de eisen die de Common Ground stelt, waaronder RGBZ 2.0, ImZTC 2.2, Multi Tenency etc. Toch zijn deze koppelingen realiteit en tot de eerste versie van ZDS 2.0 af en door de leveranciers geimplementeerd is zullen deze koppelingen nog gelegd worden. Ook daarna nog. Om gemeenten te helpen zo goed mogelijk aan te sluiten op de toekomst moet wel bekend zijn wat de aandachtspunten zijn.

Zaakgericht werken en gegevens uitvragen of toevoegen aan de zaakregistratiecomponent zit deels ook in andere standaarden verweven. Denk aan de Regie- Zaakservices maar ook aan bijvoorbeeld Wabo-BAG. Weliswaar zijn dit koppelvlakken die op kleinere schaal toegepast worden maar ze moeten wel in synch blijven met ZDS om ervoor te zorgen dat het ZRC niet gevuld raakt met incomplete informatie.

**Definition of done**

- [ ] er is een overzicht van de (totnogtoe bekende) verschillen tussen ZDS 1.x/StUF ZKN en ZDS 2.0
- [ ] er is een overzicht van de overige koppelvlakken waar (delen van) StUF ZKN opgenomen zijn
- [ ] er is een roadmap om deze koppelvlakken al dan niet te migreren.

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen overzicht verschillen ZDS 1.x/StUF ZKN en ZDS 2.0 [@michielverhoef]
- [ ] Opstellen overzicht koppelvlakken die gebruik maken van StUF ZKN of ZDS 1.x  [@michielverhoef]
- [ ] Opstellen roadmap/migratiepad [VNG Realisatie]

**Comment by TCIMEddy** [comment]
@ehotting Wil jij deze prioriteren maar ook voorzien van jouw visie hieromtrent. Heeft uiteraard ook veel te maken met implementatie... Wellicht moet user story anders omschreven worden

**Comment by ehotting** [comment]
Dit is voor ons team buiten scope. Stel voor dat @michielverhoef of @wishalg dit in A&S team aan de orde stelt en zorgt dat VNG-R het oppakt. Evt. in repo architectuur-cg. Dit issue dus een out-of-scope & close.
