### ISSUE TITLE
Als medewerker van de gemeente wil ik ook alle notificaties in de contact moment historie van de klant terugzien

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/gemma-zaken#1810]
Als medewerker van de gemeente wil ik ook alle notificaties in de contact moment historie van de klant terugzien zodat ik als medewerker van de gemeente kan zien wanneer deze klant een notificatie heeft ontvangen.

**Comment by michielverhoef** [comment]
Volgens mij is hier sprake van begripsverwarring, zie ook #1808 .

De notificaties van de Notificatie API zijn geen berichten die rechtstreeks naar een burger, via mail of mijnBerichtenbox oid, gaan. Dit zijn berichten die naar een ontvangend systeem (vakapplicatie) gaan. Op basis van het bericht kan het ontvangende systeem dan de gewijzigde gegevens opvragen.

**Comment by VerbeekIT** [comment]
Er is hier inderdaad sprake van begripsverwarring. In deze user story gaat het om de notificatie van de gemeente aan de burger waarin de burger bijvoorbeeld herinnerd wordt aan een afspraak, of aan een openstaande activiteit die uitgevoerd moet worden of een statusverandering in 1 van de openstaande zaken. Dit moet vastgelegd worden als een uitgaand contactmoment.

**Comment by hdksi** [comment]
Zie ook #1826 voor de meer algemene vraag over gebruik en definitie van contactmoment.

**Comment by rubenvdlinde** [comment]
@michielverhoef en @VerbeekIT volgens mij kan deze dan worden gesloten? Zowiezo is de discussie van notificaties inmiddels aan het verplaatsen naar de [nieuwe standaard berichten en notificaties services](https://samenwerken.pleio.nl/groups/view/1fde4814-ec84-49bd-a67a-935eb712e7a2/notificatieservices).

**Comment by michielverhoef** [comment]
@hdksi is de PO van de Klantinteracties API's, hij mag het zeggen.

**Comment by hdksi** [comment]
Deze story gaat niet zozeer over hoe notificaties werken, maar over of een notificatie naar een inwoner - in de vorm van een herinnering aan een afspraak, bijvoorbeeld - (ook) als (een vorm van) contactmoment gezien moet worden. Wat mij betreft is dat zo. 

Volgende vraag is dan of je zo'n notificatie ook als contactmoment moet of mag registreren. Zolang vanuit het traject notificatieservices geen uitspraken worden gedaan over of en hoe notificaties worden bewaard en welke gegevens daarbij worden vastgelegd neig ik als antwoord op deze vraag ook naar 'ja'.

Evengoed prima om dit issue te sluiten en een eventueel vervolg in #1826 te behandelen.
