### ISSUE TITLE
Als Consumer is het voor mij onduidelijk wat te doen als de archiefactietermijn (of brondatumArchiefprocedure) van Resultaattype wijzigt per zekere datum

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1814]
Scenario:
Stel dat per 1-1-2022 de bewaartermijn voor een Resultaattype wijzigt van 5 naar 10 jaar, is het dan noodzakelijk dat een nieuw Resultaattype toegevoegd wordt? 
En als het antwoord daarop 'ja' is:
1. staat de API het toe dat er een Resultaattype toegevoegd wordt met de gegevens 'omschrijving' en 'resultaattypeomschrijving' gelijk aan een reeds bestaand Resultaattype? 
2. zal de verwijzing in 'selectielijstklasse' dan anders zijn?   

Opmerking
Is het opnemen van een beginGeldigheid / eindeGeldigheid binnen Resultaattype een optie?

**Comment by hdksi** [comment]
Vreemd dat resultaattypen geen begin- en eindeGeldigheid kennen. In het ImZTC zijn deze kenmerken wel opgenomen, zie https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/objecttype/resultaattype.

Om met vraag 2 te beginnen: een bewaartermijn is altijd afhankelijk van een Selectielijstresultaat. Dus het aanpassen van bewaartermijn (op het niveau van een resultaattype, voor individuele zaken kan uiteraard worden afgeweken) kan volgens mij alleen als:
- Eerder een onjuist Selectielijstresultaat gekoppeld was;
- de bewaartermijn verandert doordat een nieuwe versie van de Selectielijst in werking is getreden.
In beide gevallen wordt de URI-verwijzing voor `selectielijstklasse` aangepast.

In het tweede geval lijkt me inderdaad het meest logisch dat je een nieuw `resultaattype` aanmaakt met een `beginGeldigheid` op het moment dat de nieuwe Selectielijst van kracht wordt. Het oude `resultaattype` sluit je dan af.

Mijn suggestie is dus de twee ontbrekende attributen `beginGeldigheid` en `eindeGeldigheid`bij `resultaattype` op te nemen. Is daarmee het issue opgelost?

**Comment by joeribekker** [comment]
> Vreemd dat resultaattypen geen begin- en eindeGeldigheid kennen. In het ImZTC zijn deze kenmerken wel opgenomen, zie https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/objecttype/resultaattype.

Het Zaaktype heeft wel een begin- en eindeGeldigheid, waarmee - mijn inziens - de gerelateerde resultaattypen dat ook hebben. Ik zou vind het vreemd vinden als een resultaatype een afwijken geldigheid heeft van het zaaktype, dat maakt de boel behoorlijk onoverzichtelijk.

Wijzigt er iets, voer dan een nieuw zaaktype op met daarin de wijziging van het resultaatype.

**Comment by hdksi** [comment]
Ik had nog iets verder moeten doorklikken; geloof dat je gelijk hebt. Van https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/attribuutsoort/resultaattype.datum_begin_geldigheid_resultaattype:

> Met deze datum wordt aangegeven vanaf wanneer het resultaattype bestaat en toegepast kan worden. _Dit vindt plaats met ingang van een versie van het zaaktype d.w.z. niet op tussenliggende datums._

Betekent inderdaad dat resultaattypen geen 'eigen' begin- en eindeGeldigheid kennen. Het vastleggen daarvan in attributen bij het resultaattype lijkt daarmee niet van toegevoegde waarde.
