### ISSUE TITLE
Als medewerker van de gemeente Rotterdam wil ik de informatie vanuit contactmomenten laten landen in ons lokale CRM,

### ISSUE THREAD

**Issue by RvdKlip** [VNG-Realisatie/gemma-zaken#1819]
...zodat we via de schermen van het CRM - en de aan de CRM aangesloten applicaties - deze informatie kunnen gebruiken.

**Comment by CMasselink** [comment]
Ik zie hiervoor ook twee mogelijkheden inderdaad: 
Het CRM implementeert de contacmomenten API specificatie als provider / registratie component (en biedt daarmee de API's ook aan voor gebruik door andere applicaties) of het CRM sluit aan op de contactmomenten API als die reeds in de organisatie aanwezig is.

@RvdKlip Ik ben wel benieuwd naar hoe jullie CRM positioneren in relatie tot deze API's en welke CRM tool jullie gebruiken. Daar zou ik graag via een ander kanaal een keer met je over doorpraten. In Utrecht zijn we ook net bezig met CRM.

**Comment by hdksi** [comment]
Volgens mij is dit een implementatievraagstuk waarvoor @CMasselink twee valide antwoorden geeft.

@RvdKlip kunnen jullie daarmee uit de voeten?
