### ISSUE TITLE
RGBZ-mapping US #169

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#182]
Mapping van velden behorend bij user story #169

Work in progress

### Request aan ZRC
Velden uit het formulier:

| RGBZ mapping | Veld(en) op het formulier | Opmerkingen |
| :--- | :--- | :--- |
| Domeinspecifiek `MELDING.hoofdCategorie` | Hoofdcategorie | Hoofdcategorie van de melding, bijv. Groen|
| DomeinSpecifiek `MELDING.subCategorie` | Subcategorie  | Subcategorie van de melding, bijv. Snoeien   |
| Domeinspecifiek `MELDING.omschrijving` en toevoegen aan `ZAAK.Toelichting` | Omschrijving Melding | Omschrijving zoals door de melder ingevoerd eventueel aangevuld met andere velden |
| `ZAAK.Zaakgeometrie`| Locatie melding | Locatie zoals door de melder op een kaart 'geprikt'|
| Domeinspecifiek `MELDING.locatieBeschrijving` en toevoegen aan `Zaak.Toelichting`| Aanvullende omschrijving locatie | In aanvulling op de coördinaten |
| `NATUURLIJK PERSOON.is.BETROKKENE.heeft_rol_in.ZAAK` | Naam, Straat, Huisnummer, Huisletter, Toevoeging, Postcode, Woonplaats, Telefoonnummer, E-mailadres | Optionele persoonsgegevens voor terugkoppeling over de melding |

Overige velden in het bericht:

| RGBZ mapping | Veldnaam | Opmerkingen |
| :--- | :--- | :--- |
| `ZAAK.isVan.ZAAKTYPE.Zaaktype-identificatie` | `zaaktypeIdentificatie` | Zaaktype van de zaak die gecreeerd moet worden voor de melding |
| `ZAAK.Bronorganisatie` | `bronOrganisatie` | het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd.|
| `ZAAK.Verantwoordelijke organisatie` | `verantwoordelijkeOrganisatie` | Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak.|
| `ZAAK.Omschrijving` | `omschrijving` | Zoiets als "Behandelen melding van ... te ... dd. ..." samengesteld uit andere gegevens uit de velden |
| `ZAAK.Startdatum` | `startDatum` | Datum van vandaag meegeven |
| `ZAAK.Einddatum` | `eindDatum` | Client kan de einddatum bepalen met ZAAKTYPE.Doorlooptijd (client doet call naar ZTC API) |
| `ZAAK.Geplande einddatum` | `geplandeEinddatum` | Client kan de einddatum bepalen met ZAAKTYPE.Servicenorm (client doet call naar ZTC API) |
| `ZAAK.BETROKKENEN` <- heeft rol in als Behandelaar <- MEDEWERKER of ORGANISATORISCHE EENHEID | `behandelaar` of `afdeling` | ORGANISATORISCHE EENHEID.is verantwoordelijk voor.ZAAKTYPE, idem voor MEDEWERKER (client doet call naar ZTC API) |

### Answer van ZRC
| RGBZ mapping | Veldnaam | Verklaring |
| :--- | :--- | :--- |
| `ZAAK.Zaakidentificatie` | zaakIdentificatie | Zaaknummer |
| `ZAAK.Registratiedatum` | registratieDatum |   |
| `ZAAK.Einddatum gepland` | einddatumGepland |   |

### Request aan DRC
| RGBZ mapping | Veldnaam | Opmerkingen |
| :--- | :--- | :--- |
| `INFORMATIEOBJECT.Inhoud` | inhoud | De foto van de melding in base64 encoding |
| `INFORMATIEOBJECT.Bronorganisatie` | bronorganisatie | |
| `INFORMATIEOBJECT.is van.INFORMATIEOBJECTTYPE` | informatieobjectType | |
| `ENKELVOUDIG INFORMATIEOBJECT.Taal` | taal | |
| `INFORMATIEOBJECT.Creatiedatum` | creatiedatum | |
| `INFORMATIEOBJECT.Titel` | titel | |
| `INFORMATIEOBJECT.VertrouwelijkheidAanduiding` | vertrouwelijkheidAanduiding | |
| `INFORMATIEOBJECT.Auteur` | auteur | |
| `ZAAK [0..*].kent.INFORMATIEOBJECT [1..*]` | zaakIdentificatie | Zaak waar het informatieobject bij hoort. |

### Answer van DRC
| RGBZ mapping | Veldnaam | Verklaring |
| :--- | :--- | :--- |
| `INFORMATIEOBJECT.Informatieobjectidentificatie` | `informatieobjectIdentificatie` | | |

### Requests aan ZTC
* Ophalen afdeling of medewerker behorende bij het zaaktype dat wordt gebruikt voor meldingen.
* Ophalen servicenorm behorende bij het zaaktype, om de geplande einddatum te kunnen berekenen.
* ophalen doorlooptijd behorende bij het zaaktype, om de einddatum te kunnen berekenen.

**Comment by ArjanKloosterboer** [comment]
Enkele opmerkingen.
Omschrijving_van_de_melding zou ik niet mappen op ZAAK.Omschrijving. Laatstgenoemde atribuutsoort betreft de naam van de zaak, iets als 'Behandelen melding van …. te … dd. …." Die zou je samen kunnen stellen mbv (hoofd)categorie, Aanvullende_omschrijving_locatie en datum ontvangst melding . Omschrijving_van_de_melding mapt dan op Zaak.Toelichting.
Aanvullende_omschrijving_locatie mapt (ook) op toelichting (in aanvulling op Omschrijving_van_de_melding) dan wel op een deel van de ZAAK.Omschrijving (zie vorige opmerking). 
Een Foto mapt op meerdere attributen van Enkelvoudig informatieobject en op de genoemde relatie. 
Tot zover wat er mapt. Om een zaak te creeren moeten een aantal attributen van een waarde voorzien worden. Zaakidentificatie en Registratiedatum zijn al genoemd.  Ook het andere deel van de unieke aanduiding, Bronorganisatie, moet gevuldworden. Verder ook Verantwoordelijke_organisatie en de Startdatum zijnde de datum waarop de melding ontvangen is. Aan de hand van ZAAKTYPE.Doorlooptijd moet de Einddatum gevuld worden, aan de hand van ZAAKTYPE.Servicenorm de Einddatum_gepland. 
Ook moet er minstens één betrokkene zijn. Indien niet de initiator dan tenminste een behandelaar (zou a.d.h.v. het zaaktype bepaald moeten kunnen worden). En dan ook nog het een en ander van INFORMATIEOBJECT en ENKELVOUDIG INFORMATIEOBJECT.  
Verder zouden een aantal andere attributen van een waarde voorzien kunnen worden, mits geautomatiseerd te bepalen (zoals Communicatiekanaal en Product_of_dienst).

**Comment by Hugo-ter-Doest** [comment]
Meeste commentaar verwerkt:
- onderscheid gemaakt tussen gegevens uit app/formulier en gegevens die in het bericht ook nog moeten worden meegegeven
- Requests voor DRC en ZTC toegevoegd die ook nog nodig zijn (bijv. voor toevoegen van de foto als informatieobject of opvragen servicenorm)

**Comment by ArjanKloosterboer** [comment]
Ziet er goed uit. Nog een paar opmerkingen.
Ik zou de 'Aanvullende omschrijving locatie' sowieso mappen op een domeinspecifiek element melding.locatieBeschrijving (het is immers specifiek uitgevraagd en ingevuld) en daarnaast (ook) toevoegen aan de Toelichting (zodat degene die wel de zaak in kan zien maar niet de meldingspecifieke gegevens, wel de locatiebeschrijving tot zich kan nemen). Het biedt tevens de mogeljkheid die beschrijving aan te scherpen door de behandelaar. Hetzelfde zou dan overigens ook moeten gelden voor 'Omschrijving Melding'. 
'ZAAK.BETROKKEN <- heeft rol in als Initiator <- NATUURLIJKE PERSOON' moet m.i. zijn 'NATUURLIJK PERSOON.is.BETROKKENE.heeft_rol_in.ZAAK'. Althans, als ik uitga van het RGBZ. En dat lijkt me het juiste vertrekpunt, toch? Het mapt dan tevens op ROL,rolomschrjvingGeneriek met de waarde 'initiator' en op de van toepassing zijnde waarde van ROL.rolomschrijvng van het desbetreffende zaaktype. 
Vraagpunt: hoe wordt die natuurlijk persoon 'aangereikt': d.m.v. de NAW-gegevens (oftewel de ZRC gaat op zoek naar de desbetreffende Natuurlijk persoon en zijn URL), de (functionele) identificatie van de natuurlijk persoon (i.c. het BSN of Nummer_ander_natuurlijk_persoon d.w.z. de client moet zelf eerst op zoek naar de desbetreffende Natuurlijk persoon) of d.m.v. de URL daarvan (d.w.z. de client moet zelf eerst op zoek naar de URL van de desbetreffende Natuurlijk persoon)? Ik neig naar het tweede, dat is conform RGBZ (de URL is een technische invulling). Dan zou dit dus ook mappen op het BSN en het Nummer_ander_natuurlijk_persoon van de Natuurlijk persoon zijnde de melder. 
V.w.vb. Zaaktype is er een vergelijkbare vraagstelling. Hoe weet de client eigenlijk welk zaaktype 'ie moet hebben? 
Ik vermoed dat een interactiepatroon veel helpt in de beeldvorming. De client roept niet alleen de ZRC aan maar moet o.a. ook de registratie met natuurlijke personen en de ZTC aanroepen.  
De Geplande einddatum heb je zowel bij de velden in het bericht staan als bij het answer. Is het inderdaad allebei? Oftewel als die datum niet door de client verstrekt wordt dan bepaalt de ZRC die a.d.h.v. het zaaktype in de ZTC? Of is het alleen het eerste (over hoeveel intelligentie willen we dat de ZRC beschikt)?
Tot zover mijn reactie vwb zaakgegevens. Deze is al lang genoeg ...

**Comment by ArjanKloosterboer** [comment]
Je noemt een aantal requests aan de ZTC, niet aan de ZRC en de DRC. Bewust?
V.w.b. de request(s) aan de ZTC, is het niet wenselijk om slechts één request te willen hebben, iets als 'Zaakconfiguratie verstrekken'? Dat is immers wat er hier benodigd is: aan de hand van het zaaktype de zaak kunnen configureren. Lever het zaaktype en de startdatum aan en je krijgt alles terug: behandelaar, einddatum, einddatum gepland en wat er nog meer nodig is. Het voordeel is dat de berekening van die einddatums nog maar op één plaats hoeft plaats te vinden ('service' van de ZTC) en niet door elke client met kans op fouten).

**Comment by Hugo-ter-Doest** [comment]
Die aan de DRC heb ik uitgewerkt in request en answer tabellen. Die aan de ZTC heb ik alleen nog benoemd, maar nog niet uitgewerkt. Eigenlijk moet dat ook nog; misschien doe ik dat later deze week nog. Je andere opmerkingen probeer ik ook nog voor vrijdag te doen. Het is vakantiewerk geworden nu... 

Met je eens dat het handig is om einddatum en geplande einddatum door de ZTC component te laten berekenen.

**Comment by sergei-maertens** [comment]
@ArjanKloosterboer waarom moet startdatum hetzelfde zijn als de datum waarop de melding is ontvangen? Wat is het verschil dan met registratiedatum?

**Comment by sergei-maertens** [comment]
@Hugo-ter-Doest @joeribekker ZRC-aspect staat ter review: https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/9

**Comment by Hugo-ter-Doest** [comment]
> Ik zou de 'Aanvullende omschrijving locatie' sowieso mappen op een domeinspecifiek element melding.locatieBeschrijving (het is immers specifiek uitgevraagd en ingevuld) en daarnaast (ook) toevoegen aan de Toelichting (zodat degene die wel de zaak in kan zien maar niet de meldingspecifieke gegevens, wel de locatiebeschrijving tot zich kan nemen). Het biedt tevens de mogeljkheid die beschrijving aan te scherpen door de behandelaar. Hetzelfde zou dan overigens ook moeten gelden voor 'Omschrijving Melding'.

Verwerkt.

>'ZAAK.BETROKKEN <- heeft rol in als Initiator <- NATUURLIJKE PERSOON' moet m.i. zijn 'NATUURLIJK PERSOON.is.BETROKKENE.heeft_rol_in.ZAAK'. Althans, als ik uitga van het RGBZ. En dat lijkt me het juiste vertrekpunt, toch?

Jazeker, dat is het juiste vertrekpunt. Ik zat wat te hannesen met de notatie omdat ik het vanuit ZAAK wilde opschrijven. Verwerkt.

> Vraagpunt: hoe wordt die natuurlijk persoon 'aangereikt': d.m.v. de NAW-gegevens (oftewel de ZRC gaat op zoek naar de desbetreffende Natuurlijk persoon en zijn URL), de (functionele) identificatie van de natuurlijk persoon (i.c. het BSN of Nummer_ander_natuurlijk_persoon d.w.z. de client moet zelf eerst op zoek naar de desbetreffende Natuurlijk persoon) of d.m.v. de URL daarvan (d.w.z. de client moet zelf eerst op zoek naar de URL van de desbetreffende Natuurlijk persoon)? Ik neig naar het tweede, dat is conform RGBZ (de URL is een technische invulling). Dan zou dit dus ook mappen op het BSN en het Nummer_ander_natuurlijk_persoon van de Natuurlijk persoon zijnde de melder.

Goede vraag. Ik ben bekend met onze situatie waarin een melder anoniem kan zijn, zelf zijn gegevens kan achterlaten (dus niet geidentificeerd bij BRP), of  via DigiD kan zijn ingelogd. De verantwoordelijkheid voor het al dan niet meesturen van persoonsgegevens ligt dan bij de client (app, formulier). Dat kan dus incl. BSN zijn, maar ook alleen een naam en een e-mailadres.

> V.w.vb. Zaaktype is er een vergelijkbare vraagstelling. Hoe weet de client eigenlijk welk zaaktype 'ie moet hebben?

Ik denk een kwestie van afspreken tussen de aanbieder van ZTC en DRC en aanbieder van de burgerapp. Misschien kan de PDC hierin een rol spelen? Je hebt een afbeelding nodig van producten op zaaktypen om het automagisch te doen.

**Comment by ArjanKloosterboer** [comment]
Mooi, automagisch!

> Ik snap ook niet meteen waarom einddatum al gevuld moet worden, dit veld is als optioneel aangeduid, net zoals geplande einddatum.

Foutje. Einddatum en Geplande_einddatum moeten zijn Geplande_einddatum (adhv. Servicenorm) en Uiterlijke_einddatum_afdoening (adhv. Doorlooptijd). 

> waarom moet startdatum hetzelfde zijn als de datum waarop de melding is ontvangen? Wat is het verschil dan met registratiedatum?

Startdatum is de datum waarop met de zaak begonnen had moeten worden conform wet- en regelgeving. V.w.b. aanleidingen van buiten, zoals een melding, is dat de datum waarop de gemeente die aanleiding had kunnen weten. Voor een meding is dat de datum waarop die melding ontvangen is. Het staat de gemeente vrij om er bij ontvangst meteen een zaak van te maken of dat later te doen. Voor de startdatum maakt dat niet uit, wel voor de registratiedatum. Bij een digitaal ontvangen melding zal er normaliter geen verschil zijn tussen beide datums. Voor een per post ontvangen melding kan dat wel 's een dag of enkele dagen schelen.

**Comment by sergei-maertens** [comment]
> ### Requests aan ZTC
> * Ophalen afdeling of medewerker behorende bij het zaaktype dat wordt gebruikt voor meldingen.
> * Ophalen servicenorm behorende bij het zaaktype, om de geplande einddatum te kunnen berekenen.
> * ophalen doorlooptijd behorende bij het zaaktype, om de einddatum te kunnen berekenen.

@Hugo-ter-Doest 'ophalen afdeling of medewerker' -> gaat dit dan om RolType dat hoort bij een ZaakType? Ik zie dat namelijk niet meteen terug in ImZTC

**Comment by ArjanKloosterboer** [comment]
Het gaat hier m.i. om het roltype met als generieke benaming 'Zaakcoordinator' (of indien niet aanwezig 'Behandelaar'). Gek genoeg bevat het ImZTC van roltypen geen eenduidge informatie over de afdeling of medewerker die die rol bij een zaak van dat type moet uitvoeren, anders dan een tekstuele omschrijving (in Soort_betrokkene). Terwijl je zou willen dat voor interne rollen verwezen zou worden naar een afdeling of medewerker. Qua afdeling of medewerker kom je dus nu niet verder dan een omschrijving; dat maakt het lastig om de zaak via rol (van het generieke type Zaakcoordinator) aan de juiste betrokkene zijnde een afdeling of medewerker te koppelen. Dat kan als de tekst in Soort_betrokkene) matcht met de naam van een afdeling of medewerker. Maar da's niet 'lekker'. Ik voel een verbetering van het ImZTC aankomen. Kunnen we voor nu volstaan met deze match?

**Comment by sergei-maertens** [comment]
Ik heb best wat moeite om te ontcijferen wat je schrijft @ArjanKloosterboer, waarschijnlijk doordat het heel generiek omschreven is. Voor mij lijkt het dat in dit userstory staat beschreven dat:

* bij het maken van een melding kan deze worden doorgezet naar een zaak
* bij het doorzetten naar een zaak, kan een betrokkene (behandelaar/zaakcoordinator/...) toegewezen worden op basis van informatie in het ZTC
* in het ZTC moet dus een mogelijkheid zijn om aan te geven welke medewerker of organisatorische eenheid verantwoordelijk is voor een zaaktype

Wat voor mij dan nog onduidelijk is, is de samenhang met `RolType`. Het voelt aan alsof `RolType` specifieert wat voor types betrokkenen je mag hebben voor een bepaalde roltypeomschrijving, terwijl het RGBZ eerder de indruk geeft dan een concrete betrokkene (medewerker of organisatorische eenheid) verantwoordelijk is voor een zaaktype.

**Comment by ArjanKloosterboer** [comment]
@sergei-maertens, die drie punten kloppen. De component die van de melding een zaak maakt, moet informatie hebben om dit te kunnen uitvoeren. Idealiter haalt 'ie dat allemaal uit het desbetreffende zaaktype icm. de in de melding ontvangen gegevens. Aan een zaak moet dan oa. een betrokkene gekoppeld worden die de behandeling doet, veelal een organisatorische eenheid of medewerker in de generieke rol van Zaakcoordinator of Behandelaar. Deze rollen en wie ze uitvoert staan in Roltype bij het zaaktype in de ZTC. Evenwel, wie dat doet, dus welke afdeling of welke medewerker, kan niet gestructureerd vastgelegd worden in Roltype. Alleen tekstueel, de naam van een afdeling, van een medewerker of een functiebenaming. De genoemde applicatie moet hieruit zien op te maken om welke org.eenheid of medewerker het in welke rol gaat. Maar goed, dat is het probleem van die applicatie. Wat vraagt die op bij de ZTC? M.i. roltypen, bij het zaaktype, met als generieke rol Zaakcoordinator en Behandelaar. Wat krigt 'ie terug? Alle roltypen bij dat zaaktype met die generieke rollen. En dan moet die applicatie daar maar chocola van zien te maken. Dat zal soms niet kunnen zonder tussenkomst van een echt mens als gebruiker van die applicatie. Het is voor nu niet anders. Kan beter maar dan moet het ImZTC op dit punt gewijzigd worden (toevoegen van Org.eenheid en Medewerker en relateren aan Roltype). Ik maak er een issue voor aan.

**Comment by joeribekker** [comment]
In eerste instantie leek mij [het](https://github.com/VNG-Realisatie/gemma-zaken/issues/182#issuecomment-409302092) geen goed idee om bij `Roltype` een concrete link te legen naar een specifieke `betrokkene`(n?):

1. Bij elke wijziging van deze link - dus als iemand anders de betrokkene wordt bij, wordt toegevoegd aan of wordt verwijderd van, een bepaald `Roltype`, dan komt is een nieuwe versie nodig van dit Zaaktype. Volgens mij was het ZTC vrij statisch van aard maar wordt hiermee veel dynamischer.
2. Hiermee wordt een oplossing waarbij het ZTC (zaaktypes, etc.) generieker wordt getrokken lastiger omdat er nu specifieke gemeente informatie informatie bij elk `Zaaktype`->`RolType` zit.

Sitenote 1) Versies van Zaaktypes mag sowieso wel een keer uitvoerig besproken worden (maandag middag overlegje!) want het antwoord dat ik ooit kreeg op het [discussieforum kreeg nog een staartje](https://discussie.kinggemeenten.nl/comment/5852)

Sitenote 2) Zelf dacht ik meer dat de invulling van specifieke betrokkene in het AD(FS) zou zitten, wat uitsluitend specifieke gemeente informatie bevat maar of dat nu een betere plek is dan het ZTC weet ik niet.

Wilde mijn gedachtes even neerzetten maar denk dat het goed is dat als @ArjanKloosterboer, @ehotting en @sergei-maertens zich hier in kunnen vinden we dit gewoon moeten doen :)

**Comment by ehotting** [comment]
Dat is niet hoe het bedoeld is denk ik. Praktisch moet het als volgt werken: Wanneer de zaak wordt aangemaakt wordt in ZTC gekeken welke ambtenaar of groep ambtenaren (organisatieonderdeel) in welke rol gekoppeld _moet_ worden. De ZTC schrijft dus een specifieke koppeling voor, zodat de afhandeling correct gerouteerd kan worden. Echter, voor andere rollen kan de ZTC niets voorschrijven (bijv. wie de initiator of belanghebbende is) en weer andere rollen zijn optioneel aanwezig in bepaalde instances van een proces (zoals een adviseur) - daarover heeft het ZTC ook geen info. Zaaktypen moeten niet wijzigen als een betrokkene wordt toegevoegd - betrokkenen moeten worden toegevoegd op basis van wat ZTC voorschrijft.

**Comment by ArjanKloosterboer** [comment]
Dit issue staat op closed maar komt wel voor op SCRUM-ZDS-voorbereiding onder 'Review - Ready for sprint?'. Wat nu? M.i. hoort 'ie op het Sprint3-board onder Review. Er zitten nog vele open einden in die in afgeleide userstorys aandacht moeten krijgen. @TCIMEddy ?

**Comment by sergei-maertens** [comment]
Tjah, is beetje lastig omdat het een RGBZ-mapping is die hoort bij een ander user story. Het userstory is gesloten, dus deze mapping die daarbij hoort, is ook gesloten. Is overigens geautomatiseerd gebeurd via aanpassingen in referentie-implementatie die geaccepteerd was.

Volgens mij waren we er redelijk over uit in de discussie hier, maar dit is natuurlijk tijdens jouw vakantie gebeurd.

**Comment by ArjanKloosterboer** [comment]
Deze mapping behoort bij een userstory die in sprint 3 op Done is gezet. Er werden wat discussies gevoerd die ik vertaald heb naar userstory #488. Dan is deze mapping wat mij betreft afgehandeld.

**Comment by TCIMEddy** [comment]
dank!
