### ISSUE TITLE
Cataogi API mist filters op unieke elementen om deze er uit te halen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1820]
# Bug

Idealiter wil je kunnen filteren op unieke elementen van elke resource bijv. `/informatieobjecttypen/?omschrijving=Blabla&catalogus=https://catalogi-api[...]` om zo het meest recente informatieobjecttype op te vragen. Het UUID kan namelijk door versionering wijzigen.

Dit geldt uiteraard voor alle typen, en niet alleen voor informatieobjecttypen.

Ik heb dit aangemerkt als bug omdat dit het eigenlijk onmogelijk maakt om Catalogi als bron te gebruiken. Je kan applicaties niet configureren met kenmerken anders dan een UUID... die dus kan wijzigen.

**Comment by michielverhoef** [comment]
Dit klinkt als een doublure van #1650

**Comment by michielverhoef** [comment]
Een andere oplossingsrichting kan zijn hoe het totnogtoe in veel (zo niet alle) zaaksystemen opgelost wordt: Bij het aanmaken van een Zaak of  Document of andere resource worden de relevante typen overgenomen uit de ZTC en opgeslagen bij de zaak in het zaaksysteem.

Daar is best iets voor te zeggen. De ZTC blijft de bron voor de structuur en default waardes van de zaaktype gegevens en de relevante gegevens (die mogelijk ook kunnen wijzgen) worden als onderdeel van de zaak opgeslagen in het zakenregister.

**Comment by michielverhoef** [comment]
In Catalogi API 1.2  is dit gedrag opgenomen, zie ook https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/
