### ISSUE TITLE
Als WerkSaam Westfriesland wil ik een ‘Verantwoordelijke’ kunnen vastleggen bij een zaaktype

### ISSUE THREAD

**Issue by Marjolein226** [VNG-Realisatie/gemma-zaken#1821]
zodat ik vanuit het DMS eenvoudig rapportages voor een proceseigenaar kan opstellen 
met aandacht voor juiste, volledige, tijdige registratie, archivering en vernietiging van zaken.

**Comment by michielverhoef** [comment]
Op dit moment zijn de volgende waarden toegestaan:

* adviseur - (Adviseur) Kennis in dienst stellen van de behandeling van (een deel van) een zaak.
* behandelaar - (Behandelaar) De vakinhoudelijke behandeling doen van (een deel van) een zaak.
* belanghebbende - (Belanghebbende) Vanuit eigen en objectief belang rechtstreeks betrokken zijn bij de behandeling en/of de uitkomst van een zaak.
* beslisser - (Beslisser) Nemen van besluiten die voor de uitkomst van een zaak noodzakelijk zijn.
* initiator - (Initiator) Aanleiding geven tot de start van een zaak ..
* klantcontacter - (Klantcontacter) Het eerste aanspreekpunt zijn voor vragen van burgers en bedrijven ..
* zaakcoordinator - (Zaakcoördinator) Er voor zorg dragen dat de behandeling van de zaak in samenhang uitgevoerd wordt conform de daarover gemaakte afspraken.
* mede_initiator - Mede-initiator

Deze is gebaseerd op ImZTC 2.1: https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/roltype.roltypeomschrijving_generiek 

Helaas is er voor ImZTC 2.2 geen waardenverzameling beschikbaar, zie ook https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/attribuutsoort/roltype.roltypeomschrijving_generiek .

Als ik functioneel naar "Verantwoordelijke" kijk zou ik zeggen, dat is de rol "zaakcoordinator".  In het geval het echt van belang is dat de omschrijving van de rol "Verantwoordelijke" is zou ik het volgende doen:

Maak een roltype aan met als omschrijving "Verantwoordelijke" en als omschrijvingGeneriek "zaakcoordinator". 
Koppel dit roltype aan de zaaktypen waarop dit roltype van toepassing is. 

De waarde van omschrijving bij roltypen is vrij te kiezen, hier kan dan "Verantwoordelijke" gebruikt worden.

Volgens mij lost dit jullie wens op, toch?

**Comment by MaartenRutten** [comment]
Roltype definieert de rollen die toegestaan zijn bij een Zaaktype. Als een afhandelende applicatie een betrokkene vastlegt bij een zaak dan kan gekozen worden uit de lijst met rollen die gedefinieerd zijn in Roltype.

Waar WerkSaam Westfriesland naar op zoek is een mogelijkheid om de verantwoordelijke medewerker te kunnen benoemen voor een groep van Zaaktypen waarbij 'verantwoordelijk' in die context betekent 'verantwoordelijk voor kwaliteit van archiveringsgegevens en archiveringsproces'.
Zo kan op basis van zaaktypen het archief in deelverzamelingen worden opgedeeld naar verantwoordelijke medewerkers.

**Comment by michielverhoef** [comment]
Het is mogelijk eigen rollen te definieren zoals ik eerder heb aangegeven. De mogelijke roltypen zijn niet beperkt tot de lijst die ik hierboven heb genoemd. Die beperking geldt alleen voor de omschrijving generiek. De omschrijving kan gevuld worden met eigen rolnamen, zoals in dit geval verantwoordelijke. Door dit eigen roltype te koppelen aan de bewuste zaken kan de gemeente volgens mij precies doen waar behoefte aan is.

De omschrijving generiek is bedoeld om rollen zoals die door een gemeente zelf gedefinieerd worden te kunnen mappen op lokale rollen gedefinieerd in andere gemeenten of generieke rollen in een landelijke catalogus. 

> Als ik functioneel naar "Verantwoordelijke" kijk zou ik zeggen, dat is de rol "zaakcoordinator". In het geval het echt van belang is dat de omschrijving van de rol "Verantwoordelijke" is zou ik het volgende doen:
>
> Maak een roltype aan met als omschrijving "Verantwoordelijke" en als omschrijvingGeneriek "zaakcoordinator".
Koppel dit roltype aan de zaaktypen waarop dit roltype van toepassing is.
>
> De waarde van omschrijving bij roltypen is vrij te kiezen, hier kan dan "Verantwoordelijke" gebruikt worden.

**Comment by MaartenRutten** [comment]
> Door dit eigen roltype te koppelen aan de bewuste zaken kan de gemeente volgens mij precies doen waar behoefte aan is.

Een medewerker is verantwoordelijk voor het archiefbeheer van alle zaken in het archief van zaaktypen A,B,C,.etc. Dit betreft duizenden zaken. Het is niet wenselijk/werkbaar om deze medewerker handmatig aan al die zaken toe te voegen met de rol 'Archiefbeheerder'. 

Op basis van voortschrijdend inzicht is mijn zienswijze nu dat deze verantwoordelijke archiefbeheerder niet in Catalogi opgenomen moet worden bij de Roltypen omdat de verantwoordelijke archiefbeheerder niet bij de zaak opgenomen zal worden in die rol. 
De rol van de medewerker kan wel een plaats krijgen in de Consumer-applicatie waarmee het archief beheerd wordt: deze applicatie ondersteunt het beheren van het archief (zoals in ZRC/DRC/... aanwezig) en één van de specifieke mogelijkheden van deze archief-beherende-applicatie is het toewijzen  van onderdelen van het archief (op basis van zaaktypen) aan verantwoordelijke medewerkers.

Analoog hieraan zou de Consumer-applicatie voor het onderhoud en beheer van de gegevens in de Catalogi ook zaaktypen kunnen toewijzen aan medewerkers op basis van de rol van de medewerker: Medewerker-A is verantwoordelijk voor juiste gegevens in Catalogi voor alle zaaktypen van domein Bouw&Wonen. 

Conclusie: 
- deze roltypen passen niet in de Roltype van Catalogi omdat ze niet van toepassing zijn voor individuele zaakregistraties
- een optie zou zijn om 'verantwoordelijke', 'archiefverantwoordelijke' ,.. als attributen toe te voegen aan zaaktype. 
Maar in mijn  ogen is dat geen wenselijke toevoeging omdat mogelijk een Consumer-applicatie op basis van andere criteria de verantwoordelijkheid wil kunnen verdelen. 
Bijvoorbeeld: alle zaken van zaaktype A met vertrouwelijkheid lager dan 'ZaakVertrouwelijk' zijn de verantwoordelijkheid van medewerker-A, de zaken met hogere vertrouwelijkheid zijn de verantwoordelijkheid van medewerker-B.

**Comment by michielverhoef** [comment]
> Een medewerker is verantwoordelijk voor het archiefbeheer van alle zaken in het archief van zaaktypen A,B,C,.etc. Dit betreft duizenden zaken. Het is niet wenselijk/werkbaar om deze medewerker handmatig aan al die zaken toe te voegen met de rol 'Archiefbeheerder'.

Het is ook niet nodig dit handmatig te doen. De gemeente kan in de ZTC een eigen roltype "archiefbeheerder" en deze aan de relevante zaaktypen koppelen. Voor alle zaken van deze zaaktypen kan dan de rol archiefbeheerder opgevraagd worden.

Wat nog wel een puntje zou kunnen zijn is het volgende: Zaakgericht werken gaat (momenteel vooral) over de dynamische fase van zaken. Zodra deze afgehandeld zijn komen deze in een andere fase waarbij archivering gaat spelen. De gemiddelde afhandelapplicatie gaat daar niet over, dat doet je RMA. Ik zou me zomaar voor kunnen stellen dat wanneer aan een zaaktype een rol als "archiefverantwoordelijke" gekoppeld is de RMA deze op zou kunnen halen uit de ZTC.

Bijj het afhandelen van de zaak is de archiefverantwoordelijke niet zo van belang maar voor het archiveren en/of vernietigen zou ik juist wel zeggen dat in de ZTC de archiefverantwooordelijke ingericht moet worden. Alleen hoeft de afhandelapplicatie daar niet per se iets mee te doen, dat doet de RMA.

**Comment by MaartenRutten** [comment]
De rol 'archiefverantwoordelijke' kun je opvoeren in ZTC bij de zaaktypen. Het toewijzen van medewerker-A als archiefverantwoordelijke kan niet binnen de ZTC.  

Vanuit je RMA kun je alle zaaktypen ophalen met de rol archiefverantwoordelijke maar je wilt alle zaaktypen waarvoor medewerker-A archiefverantwoordelijk is. En die informatie bevindt zich niet in de ZTC.
Of mis ik nu iets? 

En als de RMA een verantwoordelijkheidsindeling heeft gemaakt op basis van jaartallen dan heb je niets aan 'archiefverantwoordelijke'.  Daarom zou ik de mogelijkheid tot verdeling van verantwoordelijkheden binnen de RMA houden.

**Comment by michielverhoef** [comment]
> De rol 'archiefverantwoordelijke' kun je opvoeren in ZTC bij de zaaktypen. Het toewijzen van medewerker-A als archiefverantwoordelijke kan niet binnen de ZTC.

Dat klopt, dat gebeurt in de Zaken API door een rol aan te maken. Voor het aanmaken van die rol is het wel nodig dat het roltype in de Catalogi API bekend is en gekoppeld is aan het zaaktype.

>Vanuit je RMA kun je alle zaaktypen ophalen met de rol archiefverantwoordelijke maar je wilt alle zaaktypen waarvoor medewerker-A archiefverantwoordelijk is. En die informatie bevindt zich niet in de ZTC.
> Of mis ik nu iets?

Vanuit de RMA zou je dan alle zaken van een zaaktype waarvoor medewerker A de rol archiefverantwoordelijke heeft moeten ophalen. Grofweg filter je eerst op rollen met roltype archiefverantwoordelijke en geslachtsnaam "medewerker A". Van daaruit heb je ook de zaken waar medewerker A die rol heeft.


> En als de RMA een verantwoordelijkheidsindeling heeft gemaakt op basis van jaartallen dan heb je niets aan 'archiefverantwoordelijke'. Daarom zou ik de mogelijkheid tot verdeling van verantwoordelijkheden binnen de RMA houden.

Dan zou je alle zaken met registratiedatum in een bepaalde range van jaartallen kunnen koppelen aan een archiefverantwoordelijke. Door dit als een rol vast te leggen  bij (het aanmaken van?) die zaken kun je de verantwoordelijkheid binnen de RMA houden maar vastleggen bij de zaakgegevens. Immers, het is niet zo dat een zakenregister alleen maar door een vakapplicatie bijgewerkt of bevraagd mag worden.  Ik zit te weinig in de praktijk van het archiveren om hier een heel zekere uitspraak over te doen. Want wat doe je met een zaak waarvan de archiefverantwoordelijke inmiddels niet meer bij de gemeente werkt? Die moet je toch opnieuw indelen. 

Op dit moment neig ik er naar te denken dat dit iets is wat je in de RMA regelt. Wel zou je het vastleggen van de archiefverantwoordelijke door de RMA kunnen doen in de Zaken API.

@hdksi  ?

**Comment by hdksi** [comment]
> Wat nog wel een puntje zou kunnen zijn is het volgende: Zaakgericht werken gaat (momenteel vooral) over de dynamische fase van zaken. Zodra deze afgehandeld zijn komen deze in een andere fase waarbij archivering gaat spelen. 

Dit is volgens mij een belangrijke opmerking. En ik deel het inzicht van @MaartenRutten:

> Op basis van voortschrijdend inzicht is mijn zienswijze nu dat deze verantwoordelijke archiefbeheerder niet in Catalogi opgenomen moet worden bij de Roltypen omdat de verantwoordelijke archiefbeheerder niet bij de zaak opgenomen zal worden in die rol.

Dus: de archiefverantwoordelijke níet opnemen/vastleggen in de Catalogi- of Zaken API, maar in een RM-applicatie. Dit omdat:
1. Zaken gaan over vastlegging, sturing en monitoring van uitvoering van (vaak primaire) processen. Zaken zijn om allerlei redenen heel praktisch voor informatiebeheerders, maar ik zou de verantwoordelijkheden voor uitvoering/behandeling duidelijk scheiden van de verantwoordelijkheden voor beheer.
2. Activiteiten die in het kader van informatiebeheer worden uitgevoerd kunnen vele jaren omspannen. In die tijd gaan archiefverantwoordelijken met pensioen, worden ze aangenomen, krijgen een nieuwe functie etc. Een zaak is op een gegeven moment afgerond, en zaaktypen worden op een gegeven moment vervangen door een nieuwe versie. Zaaktype en een afgesloten zaak zijn in principe 'statisch'. Daarop zijn uitzonderingen mogelijk (aanpassen archiefnominatie/bewaartermijn), maar daarvan zou ik er zonder hele goede reden niet meer toevoegen.
3. een beetje een gelegenheidsargument, maar toch: álle informatieobjecten van een gemeente vallen onder de Archiefwet, en moeten worden beheerd, ook niet-zaken. Als je consequent bent hoort daarbij straks óók een archiefverantwoordelijke. Theoretisch is dat natuurlijk mogelijk, maar gewenst lijkt het me niet. Bovendien: moet je dan ook vastleggen wie de verantwoordelijk CISO (te benaderen bij een lacune in de beveiliging) of Privacy Officer (in geval van een lek van persoonsgegevens) opnemen?

**Comment by michielverhoef** [comment]
Nu ik de discussie nog eens teruglees constateer ik het volgende:
De archiefverantwoordelijke is een rol die speelt _na_ het behandelen van een zaak. Deze hoort dus ook niet in de zaakinformatie thuis maar in de RM-applicatie. Dit wordt door zowel @MaartenRutten als @hdksi gedeeld.

Op basis daarvan sluit ik dit issue.
