### ISSUE TITLE
Als Catalogi-Consumer kan ik weinig informatie vinden over de operatie 'publish', wat deze doet en hoe te gebruiken

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1822]
zodat ik niet kan bepalen wat de slimste manier is om een nieuwe versie van een Zaaktype te publiceren.
Hoe ziet de 'publish' operatie er uit? En wat doet die operatie in de Catalogi? 

Deze tekst kom ik tegen op https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index: 
"_Om de versie van een objecttype definitief te maken (“publiceren”), bestaat er een publish operatie. Dit is de tegenhanger van het attribuut concept, dus na publiceren heeft concept de waarde false_."

Ik verwacht/hoop dat als de Catalogi-component een request ontvangt voor Zaaktype waarbij het attribuut 'concept' van 'true' naar 'false' gezet wordt dat er automatisch een paar dingen gebeuren:
- dat het veld 'concept' van de versie van het zaaktype op 'false' gezet wordt.
- dat het attribuut  beginGeldigheid gelijk aan de systeemdatum wordt
- dat het attribuut eindeGeldigheid van de **vorige versie** van het zaaktype gelijk gemaakt wordt aan systeemdatum

De selectie van "vorige versie van zaaktype" wordt gedaan door te zoeken naar zaaktype met gelijke identificatie en met een lege waarde voor eindeGeldigheid. 
Sub-vraag: hoe ziet een dergelijke GET er uit?

**Comment by michielverhoef** [comment]
Dit is een goede vraag eerlijk gezegd. Als ik de documentatie lees zou ik in de OAS een publish operatie verwachten. Het zou wel de meest elegante manier zijn, dan kunnen regels zoals die hierboven ook daar in toegepast worden. 

Maar die operatie zie ik niet staan in https://catalogi-api.vng.cloud/api/v1/schema/ 

Ik ga dit na. @joeribekker Kun jij hier iets over zeggen?

**Comment by sergei-maertens** [comment]
De operatie staat er, alleen is er een bug in de documentatie waardoor die de verkeerde titel heeft: https://catalogi-api.vng.cloud/api/v1/schema/#operation/zaaktype_publish

> dat het veld 'concept' van de versie van het zaaktype op 'false' gezet wordt.

dit is inderdaad wat er gebeurt in deze operatie

> dat het attribuut beginGeldigheid gelijk aan de systeemdatum wordt

dat gebeurt niet, omdat een catalogusbeheerder de begindatum geldigheid specifieert. Deze kan om wettelijke redenen bijvoorbeeld in mei gebouwd worden, met een ingangsdatum van 1 juli (omdat dan bijvoorbeeld nieuwe wetgeving geldt o.i.d.). Het zaaktype kan dan alvast gepubliceerd zijn, maar het wordt pas echt actief vanaf 1 juli.

> dat het attribuut eindeGeldigheid van de vorige versie van het zaaktype gelijk gemaakt wordt aan systeemdatum

Deze wordt ook door catalogusbeheerder expliciet ingevuld. Het kan zijn dat een zaaktype versie stopt met geldig te zijn zonder dat er een nieuwe versie komt (omdat het zaaktype opgeheven wordt bijvoorbeeld).


Ik kan me op zich wel vinden in deze business-regels als _default_ waarden, waarbij je met de publish actie een body kan meegeven om de waarden expliciet te overrulen van de default. Dat zou een mooie toevoeging zijn op de standaard.

**Comment by sergei-maertens** [comment]
ja, de voorbeeld response is vooral _een_ invulling van het datatype (boolean in dit geval). De API specs worden gegenereerd uit de referentie-implementaties, dus zijn niet altijd semantisch ideaal, helaas.

**Comment by michielverhoef** [comment]
> Ik kan me op zich wel vinden in deze business-regels als default waarden, waarbij je met de publish actie een body kan meegeven om de waarden expliciet te overrulen van de default. Dat zou een mooie toevoeging zijn op de standaard. 

Als dit een wens is, user story svp  :-)
Ik vind het ook wel een mooie, zo worden default in ieder geval alle attributen gevuld met geldige waarden.

**Comment by michielverhoef** [comment]
> dat gebeurt niet, omdat een catalogusbeheerder de begindatum geldigheid specifieert. Deze kan om wettelijke redenen bijvoorbeeld in mei gebouwd worden, met een ingangsdatum van 1 juli (omdat dan bijvoorbeeld nieuwe wetgeving geldt o.i.d.). Het zaaktype kan dan alvast gepubliceerd zijn, maar het wordt pas echt actief vanaf 1 juli.


Hier heb ik toch wat vragen bij: Wat doe je wanneer in juni een fout in de gepubliceerde versie (die in juli actief wordt) blijkt te zitten? Weliswaar mag vanaf Catalogi API 1.2 die versie aangepast worden middels de scope `geforceerd_bijwerken` maar t/m Catalogi API 1.1 mag dat niet.

Of in een ander geval: Er komt een wijziging tussendoor waardoor tussen mei en 1 juli een nieuwe versie van dat zaaktype gemaakt en gepubliceerd moet worden. Deze wijziging heeft ook gevolgen voor het al gepubliceerde maar nog niet actieve zaaktype.

**Comment by sergei-maertens** [comment]
ja da's een goeie, je zou in die gevallen misschien toch nog correcties kunnen toestaan, want die zaaktypen mogen nog niet gebruikt worden omdat ze nog niet geldig zijn.

of je keert het om - je kan alvast de vlag concept=false zetten, maar de API blijft concept=true terug geven zolang de datum beginGeldigheid nog niet bereikt is? Luidop aan het denken hoor. De API moet vooral de echte wereld niet in de weg zitten, maar ook stabiliteit bieden aan de afnemers van de zaaktypen etc.

**Comment by michielverhoef** [comment]
Beschreven in #2038
