### ISSUE TITLE
CI build van Documenten API kapot

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1824]
# Bug

De automatische tests van https://github.com/VNG-Realisatie/documenten-api slagen bij mij niet (meer) lokaal, en ik zie ook nergens dat deze CI build nog automatisch uitgevoerd wordt.

In de [ithub Workflows](https://github.com/VNG-Realisatie/documenten-api/tree/master/.github/workflows) worden de unit tests niet uitgevoerd, en de laatste build op Travis CI dateert van 5 maanden geleden: https://travis-ci.com/VNG-Realisatie/documenten-api

In die tijd zijn er wel commits geweest, zie: https://github.com/VNG-Realisatie/documenten-api/commits/develop

Ik heb nu dus geen idee of mijn lokale environment kapot is, of dat de build gewoon stuk is, en dat hindert mijn werk in de zin dat ik dus https://github.com/VNG-Realisatie/documenten-api/pull/145/files niet kan reviewen/lokaal testen.

**Comment by sergei-maertens** [comment]
update: oorzaak van lokale falende tests is gevonden en verholpen in `develop` branch, maar de missende CI is wel echt iets wat opgelost moet worden

**Comment by michielverhoef** [comment]
Als het goed is worden de falende referentie implementaties bijgewerkt zodat deze weer draaien. Dan slagen de tests op het API Test Platform ook weer.

**Comment by alextreme** [comment]
Deze issue staat van wat ik heb uitgezocht los van de problemen op api-test.nl met de referentiecomponenten.

Zoals duidelijk is aan de banner op Travis, voor het weer uitvoeren op Travis CI zal VNG haar Travis account moeten upgraden. Dit is iets waar ik (nog) geen toegang toe heb. Jij wel @joeribekker ?

![Screenshot_2021-05-04_16-49-03](https://user-images.githubusercontent.com/226839/117022699-bb597100-acf8-11eb-870a-b6a0ac259fef.png)

**Comment by sergei-maertens** [comment]
Zoals Alex zegt - dit heeft niets met api-test.nl te maken. Tests zouden in principe gewoon naar Github workflows verhuisd moeten worden, dan is er geen Travis subscription nodig.

**Comment by michielverhoef** [comment]
Mij staat bij dat eind 2020 de acties al naar Github workflows omgebouwd waren en daarom een update van het Travis account niet meer nodig was. @joeribekker Dit was toch uitgevoerd?

**Comment by alextreme** [comment]
Bij deze is de PR gemerged naar master die Github Actions voor de documenten-api instelde.

**Comment by alextreme** [comment]
https://github.com/VNG-Realisatie/documenten-api/actions

**Comment by alextreme** [comment]
Besproken met @michielverhoef Github actions draait zoals het hoort voor de documenten-api op master
