### ISSUE TITLE
Zegt de ZGW-API standaard/richtlijnen iets over de wijze waarop multi-tenancy ondersteund wordt?

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1825]
Als Leverancier maken we een implementatie van een Register dat door meerdere klanten gebruikt gaat worden. Bij afhandeling van een Request is het belangrijk om te weten welke klant het request stuurt.
Welke optie past het beste in de standaard ZGW-API en/of zijn er richtlijnen waar men aan gehouden is? 

Een Organisatie-Id opnemen in de base URL?
Een Organisatie-Id opnemen in JWT Token?
In de Header?

Of staat ons dat vrij?

**Comment by michielverhoef** [comment]
De zaak kent het veld bronorganisatie, op die manier is bekend bij welke klant de zaak hoort.

Toegang wordt geregeld via de Autorisaties API. Een client/consumer wordt geindentificeerd door een client_id, Een client_id mag slechts bij één applicatie-object voorkomen. 

https://autorisaties-api.vng.cloud/api/v1/schema/#operation/applicatie_consumer

Wanneer in het client_id een organisatie_id opgenomen is is op die manier te achterhalen welke organisatie het request gedaan heeft.

@HenriKorver klopt dit?

**Comment by sergei-maertens** [comment]
Semantisch lijkt mij de tenant-identificatie in de base URL opnemen het beste. Dan heb je de opties tussen gebruik van verschillende (sub)-domeinen of een identifier in het request path (vb. `https://organisatie.nl/<tenant>/zaken/api/v1/`).

> Een Organisatie-Id opnemen in JWT Token?

dat lijkt me niet handig, omdat bestaande applicaties die nu al JWT's genereren (waaronder Open Zaak bijvoorbeeld om met externe API's te communiceren) het JWT formaat van de standaard gebruiken en hierdoor niet meer compatibel zouden zijn. Precies wat je _niet_ wil bij een breed uitwisselbare standaard.

> In de Header?

Zelfde bezwaar als hierboven.

**Comment by sergei-maertens** [comment]
> De zaak kent het veld bronorganisatie, op die manier is bekend bij welke klant de zaak hoort.

Is dat zo? Dat is niet hoe ik het attribuut in RGBZ interpreteer:

`Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd.` (van https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/objecttype/zaak)

**Comment by michielverhoef** [comment]
@sergei: klant heb ik in deze context opgevat als de klant van de leverancier van het Zakenregister, de gemeente, niet de burger.

NB. Het creeeren van de zaak is voor mij iets anders als initieren van een zaak. Als organisatie kan ik een verzoek of melding doen naar aanleiding waarvan een een zaak gestart wordt maar dan ben ik als organisatie de initator, niet de bronorganisatie die de zaak heeft gecreeerd. De bronorganisatie is de gemeente (of omgevingsdienst of ??) die de melding of het verzoek ontvangen heeft en de zaak aangemaakt heeft in het register. Tenminste, zo zie ik het.

**Comment by MaartenRutten** [comment]
> Semantisch lijkt mij de tenant-identificatie in de base URL opnemen het beste. Dan heb je de opties tussen gebruik van verschillende (sub)-domeinen of een identifier in het request path (vb. https://organisatie.nl/<tenant>/zaken/api/v1/).

Deze lijkt me inderdaad de beste optie. Hiermee is de kans op per ongeluk leveren van gegevens van de ene gemeente aan een andere gemeente het kleinste.  En blijft het mogelijk om eventueel meerdere RSIN's als bronorganisatie in één tenant op te nemen. 

Dank voor het meedenken!

**Comment by MaartenRutten** [comment]
o, ik weet niet of het de bedoeling is dat ik het issue sluit. 
Daarom weer heropend.

**Comment by michielverhoef** [comment]
> Deze lijkt me inderdaad de beste optie. Hiermee is de kans op per ongeluk leveren van gegevens van de ene gemeente aan een andere gemeente het kleinste. En blijft het mogelijk om eventueel meerdere RSIN's als bronorganisatie in één tenant op te nemen.


Hier ben ik het denk ik niet mee eens. Want op deze manier wordt niet in de zaakgegevens opgeslagen welke organisatie de behandelende organisatie is.  Dat staat nl. dan in de url. Op het moment dat een configuratie wijzigt of een zaak overgedragen wordt aan een andere behandelende organisatie (bv van gemeente naar omgevingsdienst oid) wordt dit niet opgeslagen en is dit niet in de historie terug te vinden. 

Dit gegeven hoort in het attribuut Verantwoordelijke organisatie: https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/zaak.verantwoordelijke_organisatie 
_Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak._

Mijn eerste reactie hierboven over het attribuut bronorganisatie was niet goed, dat had verantwoordelijkeOrganisatie moeten zijn.

@ArjanKloosterboer Kun jij hier nog iets over zeggen?
