### ISSUE TITLE
Als Consumer wil ik weten of Resultaattypen wel/geen 'Concept' heeft

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1827]
omdat ik daar nu geen duidelijkheid over kan krijgen.

1.
Bij https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/catalogi-api/1.1.0/src/openapi.yaml#operation/resultaattype_list staat de mogelijkheid om te filteren op Status.

2.
Het veld Concept komt echter niet terug in de beschrijving van de requests. Daar lijkt Resultaattype geen Status te hebben.

3.
Op pagina https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index wordt Resultaattypen niet genoemd. 
Daar staat:
_Concepten
De resources Zaaktype, InformatieObjecttype en Besluittype bevatten het veld concept, indien dit veld aangemerkt is als true, dan betreft het een niet-definitieve versie van het objecttype._

**Comment by sergei-maertens** [comment]
klopt, een zaaktype is het geheel van zaaktype + resultaattypen + roltypen + ...

Als het zaaktype dus concept-status heeft, dan zijn alle onderdelen ervan ook concept. Eenmaal zaaktype gepubliceerd is (en dus niet langer concept), dan kan je dit niet langer bewerken -> alle onderdelen zijn ook mee gepubliceerd en bevroren.
