### ISSUE TITLE
RGBZ-mapping US #137

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#183]
Mapping van velden behorend bij user story #137

We onderscheiden op dit moment vier typen managementrapportages voor meldingen:
1. Openstaande meldingen (periode van-tot)
2. Meldingen per wijk en periode (periode van-tot en per jaar/maand/week/dag)
3. Meldingen per wijk en categorie (periode van-tot en per jaar/maand/week/dag)
4. Melding per categorie en periode (periode van-tot en per jaar/maand/week/dag)

## Ad 1. Openstaande meldingen
Alle zaken van het zaaktype MOR die nog niet afgehandeld zijn (niet de eindstatus hebben) en die gestart zijn in de opgegeven periode.

### Request
| RGBZ mapping | Veld in huidige app | Verklaring |
| :--- | :--- | :--- |
| `ZAAK.Startdatum` | Datum vanaf | Datum vanaf voor de periode |
| `ZAAK.Startdatum` | Datum tot | Datum tot voor de periode |

Deze methode is gemakkelijk generiek te maken door de parameter zaaktype toe te voegen.

### Answer
Het resultaat is een array van openstaande zaken van zaaktype MOR. Alle beschikbare attributen van de zaak worden teruggegeven. Eventueel voegen we een scope parameter toe aan de methode om te specificeren welke attributen moeten worden teruggegeven.

## Ad 2. Meldingen per wijk en periode
Aantallen openstaande meldingen per wijk in een periode.

### Request
| RGBZ mapping | Veld in huidige app | Verklaring |
| :--- | :--- | :--- |
| `ZAAK.Startdatum` | Datum vanaf | Datum vanaf voor de periode |
| `ZAAK.Startdatum` | Datum tot | Datum tot voor de periode |
| - | Lengte periode (jaar, maand, week of dag) | De periode waarover de aantallen moeten worden geaggregeerd |

### Answer
Het resultaat is een array waarvan ieder element de aantallen per wijk bevat (of een map van periode naar array met aantallen, of een map van periode naar een map van wijken naar aantallen). Voorbeeld:

| Weeknummer | Wijk 1 | Wijk 2 |
| :--- | --- | --- |
| 2016 1 | aantal | aantal |
| 2016 2 | aantal | aantal |
| 2016 3 | aantal | aantal |

## Ad 3. Meldingen per wijk en categorie
Aantallen openstaande meldingen per wijk per categorie in een periode.

### Request
| RGBZ mapping | Veld in huidige app | Verklaring |
| :--- | :--- | :--- |
| `ZAAK.Startdatum` | Datum vanaf | Datum vanaf voor de periode |
| `ZAAK.Startdatum` | Datum tot | Datum tot voor de periode |

### Answer
Een map van Hoofdcategorie naar een map van subcategorie naar een map van wijk naar aantal.

## Ad 4. Melding per categorie en periode
Aantallen openstaande meldingen per wijk in een periode.

### Request
| RGBZ mapping | Veld in huidige app | Verklaring |
| :--- | :--- | :--- |
| `ZAAK.Startdatum` | Datum vanaf | Datum vanaf voor de periode |
| `ZAAK.Startdatum` | Datum tot | Datum tot voor de periode |
| - | Lengte periode (jaar, maand, week of dag) | De periode waarover de aantallen moeten worden geaggregeerd |

### Answer
Een map van Hoofdcategorie naar een map van Subcategorie naar een map van periode naar aantal.

In de architectuurschets is een voorbeeld opgenomen van deze rapportage.

**Comment by michielverhoef** [comment]
Er wordt nu een overzicht gemaakt van de zaken op basis van startdatum. De Startdatum is "De datum waarop met de uitvoering van de zaak is gestart". 
Is de registratiedatum niet ook interessant? Hoe lang duurt het voor een melding in behandeling wordt genomen?  Want de burger kijkt naar de tijd tussen het melden en de afhandeling, niet naar wanneer een zaak in behandeling is genomen.

**Comment by ArjanKloosterboer** [comment]
@Hugo-ter-Doest, deze staat in backlog. Is er al behoefte aan review van de RGBZ-mapping of kan ik wachten totdat je het label 'review nodig' er aan gekoppeld hebt (en het waarschijnlijk in 'Make ready' staat)? Vooralsnog doe ik even niks en wissel mijn met jouw assignment.

**Comment by Hugo-ter-Doest** [comment]
Deze kan voorlopig blijven staan omdat de user story voor managementinformatie generiek voor zaken is gemaakt. Zie #403.

Dank voor je oplettendheid.
