### ISSUE TITLE
Ik weet niet waar ik een vraag over de standaard moet indienen, er zit niet een item hiervoor bij de opties onder "issues"

### ISSUE THREAD

**Issue by EduardWitteveen** [VNG-Realisatie/gemma-zaken#1832]
Ik heb een vraag over het gebruik van de api's wat mogelijk een bug zou kunnen zijn.
Nu weet ik niet waar ik hem kwijt moet, wat is hier de procesgang voor?

Voor nu zal ik de vraag als een bug inschieten.

**Comment by michielverhoef** [comment]
@EduardWitteveen dat is wel een goede. Ik maak even een "vraag" sjabloon aan, dat is makkelijker.

**Comment by michielverhoef** [comment]
Er is nu een template voor het stellen van vragen. Dit is niet in beton gegoten dus als er dingen aan verbeterd kunnen worden, laat het vooral weten!
