### ISSUE TITLE
RGBZ-mapping #111

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#184]
Mapping van velden behorend bij user story #111 

Work in progress.

Elementen van de zoekvraag:
* Zaaktype is vrij te kiezen, maar bedoeld voor MOR zoekvragen in eerste instantie.
* Periode van-tot
* Verder kunnen alle ZAAK-kenmerken worden gebruikt voor zoeken
* Mogelijkheid om booleaanse expressies te maken met AND, OR en NOT.

### Request
| RGBZ mapping | Veld in huidige app | Verklaring |
| :--- | :--- | :--- |
| `ZAAK.ZAAKTYPE.Zaaktype-identificatie` | Zaaktype | -  |
| `ZAAK.heeft.STATUS.isVan.STATUSTYPE.Statustype-omschrijving` | Statustype | -  |
|`ZAAK.Omschrijving`|Omschrijving|Zoiets als "Behandelen melding van ... te ... dd. ..." samengesteld uit andere gegevens uit de velden|
| `ZAAK.Zaakgeometrie`| Locatie melding | Locatie zoals door de melder op een kaart 'geprikt'|
| `ZAAK.Startdatum` | Datum vanaf | Datum vanaf voor de periode |
| `ZAAK.Einddatum` | Datum tot | Datum tot voor de periode |
|`MELDING.hoofdCategorie`|Hoofdcategorie |Hoofdcategorie van de melding, bijv. Groen |
|`MELDING.subCategorie`|Subcategorie |Subcategorie van de melding, bijv. Maaien|
|`MELDING.omschrijving`|Omschrijving Melding |Omschrijving zoals door de melder ingevoerd |
|`MELDING.locatieBeschrijving`|Aanvullende omschrijving locatie |In aanvulling op de coördinaten|

### Answer
Het resultaat is een array van zaken met alle attributen (in zoverre geautoriseerd). Ook hier kunnen we eventueel werken met een scope parameter in de aanroep.
In de request moet je kunnen aangeven of de gekoppelde contacten mee moeten komen in het resultaat.

**Comment by ArjanKloosterboer** [comment]
Waarvoor wil je kunnen zoeken op Statustype-volgnummer? Dit is enkel een soort stuurgegeven voor de volgorde van statustypen. Ik zie hier geen nut in.

V.w.b. Zaak.Registratiedatum, als je wilt kunnen zoeken op een datum dan zal dat vanuit een achtergrond van de datum van melding zijn. Deze mapt op Startdatum, niet op Registratiedatum.
Wil je niet kunnen zoeken op bijvoorbeeld adres of straatnaam? Die zitten overigens in een gerelateerd zaakobject dus andere api (en andere resource) en die zouden buiten scope zijn.
En zoeken op een stuk tekst in de Omschrijving van de zaak?

**Comment by Hugo-ter-Doest** [comment]
> Waarvoor wil je kunnen zoeken op Statustype-volgnummer? Dit is enkel een soort stuurgegeven voor de volgorde van statustypen. Ik zie hier geen nut in.

Mee eens, aangepast.

> V.w.b. Zaak.Registratiedatum, als je wilt kunnen zoeken op een datum dan zal dat vanuit een achtergrond van de datum van melding zijn. Deze mapt op Startdatum, niet op Registratiedatum.

Aangepast.

Je moet ook kunnen zoeken op adres etc. Misschien moet ik een lijstje maken van attributen bij de user story waar je in ieder geval op moet kunnen zoeken?

**Comment by Hugo-ter-Doest** [comment]
Ik heb de zoekcriteria expliciet gemaakt. @ArjanKloosterboer kun jij hier even naar kijken?

**Comment by ArjanKloosterboer** [comment]
Ik mis de Omschrijving van het zaaktype. Of wordt je geacht eerst het gezochte zaaktype te selecteren? En zaak.startdatum wordt twee keer genoemd. De tweede moet wsl. Zaak.einddatum zijn. 
En verklaren we het kunnen zoeken op gegevens van gerelateerde (zaak)objecten buiten scope van deze userstory?

**Comment by Hugo-ter-Doest** [comment]
> Ik mis de Omschrijving van het zaaktype. Of wordt je geacht eerst het gezochte zaaktype te selecteren?

Ik ga ervan uit de de client de URL heeft naar het zaaktype waarnaar gezocht moet worden. In dit geval een zaaktype voor behandeling van meldingen.

> En zaak.startdatum wordt twee keer genoemd. De tweede moet wsl. Zaak.einddatum zijn.

Moet inderdaad Einddatum zijn. Aangepast.

> En verklaren we het kunnen zoeken op gegevens van gerelateerde (zaak)objecten buiten scope van deze userstory?

Misschien kan het niet gebouwd worden in de referentie-implementatie. Maar ik ben wel benieuwd naar de werking/mechanismen die daarbij komen komen kijken. Het gaat nl. vaker voorkomen.

**Comment by ArjanKloosterboer** [comment]
> En verklaren we het kunnen zoeken op gegevens van gerelateerde (zaak)objecten buiten scope van deze userstory?

> Misschien kan het niet gebouwd worden in de referentie-implementatie. Maar ik ben wel benieuwd naar de werking/mechanismen die daarbij komen komen kijken. Het gaat nl. vaker voorkomen.

Wat valt nu wel en niet binnen scope? Bijv. zoeken op adressen (zaakobject Nummeraanduiding) en straatnamen (zaakobject Openbare ruimte)?

**Comment by michielverhoef** [comment]
Aangezien dit de mapping is bij #111  en dat issue al gesloten is sluit ik dit issue ook.
