### ISSUE TITLE
Er wordt gesuggereerd dat met een admin interface meer kan dan met de API's

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#1840]
Op https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/index staat
"Merk op dat het aanmaken van de relatie niet gelimiteerd is tot het aanmaken via de API. Indien elders (bijvoorbeeld via een admininterface) een relatie tot stand kan komen, dan MOET deze ook gesynchroniseerd worden."

Maar die admin interface moet toch van dezelfde API's gebruik maken?
Immers op dezelfde pagina staat: "Het is NIET TOEGESTAAN om gebruik te maken van operaties die niet beschreven staan in deze OAS spec, of om uitbreidingen op operaties in welke vorm dan ook toe te voegen."
Of mag een admin interface buiten de API's om wijzingen aanbrengen?

**Comment by michielverhoef** [comment]
Er zijn situaties denkbaar waarbij bijvoorbeeld een backup terug gezet wordt. De API's in de huidige versie zijn daar niet heel praktisch voor. Op zich hoeft dat geen problemen te geven zolang het resultaat maar is dat de gegevens correct via de API's te ontsluiten zijn. Dus ook eventuele (gespiegelde) relaties moeten dan aangemaakt zijn.

> Immers op dezelfde pagina staat: "Het is NIET TOEGESTAAN om gebruik te maken van operaties die niet beschreven staan in deze OAS spec, of om uitbreidingen op operaties in welke vorm dan ook toe te voegen.

Hiermee wordt bedoeld dat het niet is toegestaan is eigen aanpassingen/uitbreidingen op de API's te maken. Bijvoorbeeld om eigen gegevens mee te kunnen sturen of totaal andere operaties te verzinnen. De standaard moet voor iedereen gelijk zijn en blijven.

Een ander voorbeeld kan zijn een zaaksysteem waar nu ook nog een zaakafhandel-deel bij zit. Dat zaakafhandel-deel zal niet direct gebruik maken van de API's. Uiteindelijk is het de bedoeling dat dat wel gebeurt maar in de transitie zullen leveranciers er mogelijk voor kiezen in eerste instantie een hybride oplossing te kiezen. Het belangrijkste is in zo'n geval dat de gegevens wel met de API's ontsloten en bewerkt kunnen worden. Dat betekent dus ook dat alle (onderwater) relaties aanwezig moeten zijn.

Wat absoluut niet de bedoeling is is dat gegevens die vanuit een (legacy) afhandelgedeelte/beheermodule etc. aangemaakt zijn niet voldoen aan de modellen die bij de API's horen en daarmee niet door de API's ontsloten  kunnen worden.
