### ISSUE TITLE
Link naar API specificatie in de referentieimplementatie van de documenten-api geeft http 404 in ReDoc

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#1844]
# Bug

Link naar API specificatie (API Specificaties) in de referentieimplementatie van de documenten-api geeft http 404

[kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? documenten-api.vng.cloud

Welke claims/payload bevat je JWT? nvt

**Comment by michielverhoef** [comment]
Ik heb dit gemeld bij onze onderhoudspartij. 

De link verwijst naar 
https://raw.githubusercontent.com/VNG-Realisatie/gemma-documentregistratiecomponent/1.1.0-alpha/src/openapi.yaml

Inmiddels is die repository hernoemd en is het pad geworden:

https://raw.githubusercontent.com/VNG-Realisatie/documenten-api/master/src/openapi.yaml

Maar goed, uiteindelijk moet de link verwijzen naar het door de API gegenereerde specificatie en niet naar een tekstbestand.

**Comment by michielverhoef** [comment]
De fout is nog niet opgelost maar de API specificatie is ook te bereiken via:
https://documenten-api.vng.cloud/api/v1/schema/

NB. Om de fout in dit issue op te lossen moet de referentie implementatie opnieuw uitgerold worden. Dat heeft wat meer voeten in de aarde maar zal zo gauw mogelijk gebeuren.

**Comment by michielverhoef** [comment]
Het probleem is inmiddels opgelost en ik sluit dit issue
