### ISSUE TITLE
Als ZTC-beheerder wil ik zaakobjecttypen kunnen inrichten

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#1846]
_…. zodat bij het aanmaken of wijzigen van een zaak helder is van welke objecttypen objecten aan de zaak gekoppeld kunnen of zelfs moeten worden._

Het “zaakobjecttype” staat wel in het [ImZTC](https://www.gemmaonline.nl/index.php/Informatiemodel_Zaaktypen_(ImZTC)), maar wordt nog niet gefaciliteerd in de [Catalogi API](https://catalogi-api.vng.cloud/api/v1/schema/). 

Door het “zaakobjecttype” wel te gaan faciliteren kan beter geborgd worden dat aan een zaak alleen relevante objecten worden gekoppeld én dat verplichte objecten ook daadwerkelijk gekoppeld worden. Met name het borgen van verplichtingen draagt bij aan de volledigheid van de zaakregistraties. 

Ook wil ik later nog een user story toevoegen om te borgen dat bij resultaattypen bij de 'brondatumArchiefprocedure’ alleen verwezen kan worden naar objecttypen die ook als zaakobjecttypen aan het zaaktype zijn gekoppeld. Die user story moet ik echter nog even goed uitdenken ;-).

Ieder ‘zaakobjecttype’ zal uiteraard aan een ‘zaaktype’ gekoppeld moeten worden. Ook moet ieder ‘zaakobjecttype’ aan een ‘objecttype’ gekoppeld moeten worden. Welke objecttypen er zijn staat momenteel deels in de [Objecttypen API](https://objects-and-objecttypes-api.readthedocs.io/en/latest/index.html) en deels in de [Stelselcatalogus](https://www.stelselcatalogus.nl/). Het is nog niet uit te sluiten of er in de toekomst nog andere bronnen bij komen. Overigens worden objecttypen in de Stelselcatalogus "begrippen" [genoemd](https://www.stelselcatalogus.nl/documenten/gegevensstructuur_stelselcatalogus). 

Ik zal een aparte user story aanmaken voor het koppelen van een zaakobject aan een zaak conform de inrichting van zaakobjecttypen en zaaktypen.

![Zaakobjecttypen-schets](https://user-images.githubusercontent.com/42862219/121664072-6226ef00-caa7-11eb-9bb9-86e0f00cb50e.PNG)

**Comment by michielverhoef** [comment]
Hallo Marco,

> Ik zal een aparte user story aanmaken voor het koppelen van een zaakobject aan een zaak conform de inrichting van zaakobjecttypen en zaaktypen.

Dat mag maar wat mij betreft mag dit ook vallen onder #1847

**Comment by MarcoKlerks** [comment]
> Dat mag maar wat mij betreft mag dit ook vallen onder #1847

Ik zie je reactie nu pas. Ik heb de user story al aangemaakt (#1848).

**Comment by michielverhoef** [comment]
Sorry, ik had #1847 al veel eerder aan moeten maken. Iets te ijverig aan de slag gegaan

**Comment by michielverhoef** [comment]
Hallo Marco,

Kun jij een aantal casussen aanleveren zodat we kunnen beoordelen of de huidige structuur van een ZAAKOBJECTTYPE voldoet? 
Het gaat dan om https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/objecttype/zaakobjecttype

Ik verwacht eigenlijk dat dit wel zal kloppen maar aangezien we het nu nieuw toevoegen kunnen we het maar beter gelijk goed doen.

**Comment by hdksi** [comment]
Voorwaarde lijkt me dat eenmaal gepubliceerde Objecttypes niet verwijderd worden. Issue aangemaakt bij de Objecten API om te vragen in welke mate de persistentie van Objecttypen gegarandeerd is: https://github.com/maykinmedia/objects-api/issues/206.

**Comment by MarcoKlerks** [comment]
> Kun jij een aantal casussen aanleveren zodat we kunnen beoordelen of de huidige structuur van een ZAAKOBJECTTYPE voldoet?
> Het gaat dan om https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/objecttype/zaakobjecttype

Casussen:
1. Reparatie of onderhoud aan objecten in de fysieke ruimte dienen 5 jaar bewaard te worden na sloop van het object. Neem bijvoorbeeld een zaaktype als "Het onderhouden van bruggen". Je wilt daar een ["overbruggingsdeel"](https://opendata.stelselcatalogus.nl/bgt/doc/begrip/Overbruggingsdeel) uit de BGT aan kunnen koppelen. De eigenschap "objectEinddatum" geldt als de brondatum voor het berekenen van de de archiefactiedatum.
2. Een sollicitatie die geleid heeft tot een aanstelling moet bewaard worden tot 10 jaar na einde dienstverband. Hiervoor zal vanuit obecten-API een "medewerker""-object of een "dienstverband"-object aan de zaak gekoppeld moeten kunnen worden. Op de registratie zal een datumveld met nog onbekende naam (afhankelijk van de inrichting van het objecttype) staan dat de brondatum is voor het berekenen van de archiefactiedatum.

Kunnen jullie daarmee uit de voeten?

**Comment by ArjanKloosterboer** [comment]
In de issuebeschrijving is een gegevensmodel gevisualiseerd. Strikt genomen is de daarin opgenomen relatie 'Zaakobject - Zaakobjecttype' m.i. niet nodig. Elke relatie 'Zaak - Object' (via Zaakobject) is uniek oftewel komt slechts één keer voor (d.w.z. eenzelfde object kan niet twee keer gerelateerd zijn aan één zaak). Dan kan uit de andere relaties afgeleid worden om welk zaakobjecttype het gaat. 
Verder, in ImZTC en RGBZ is nog sprake van 'Ander zaakobject(type)'. M.i. is dit in de CG-wereld niet meer nodig. Van elk te koppelen objecttype is daarin een registratie aanwezig. Het maakt dan niet meer uit of het een basisregistratieobject of een ander soort object is.

**Comment by MarcoKlerks** [comment]
> In de issuebeschrijving is een gegevensmodel gevisualiseerd. Strikt genomen is de daarin opgenomen relatie 'Zaakobject - Zaakobjecttype' m.i. niet nodig. Elke relatie 'Zaak - Object' (via Zaakobject) is uniek oftewel komt slechts één keer voor (d.w.z. eenzelfde object kan niet twee keer gerelateerd zijn aan één zaak). Dan kan uit de andere relaties afgeleid worden om welk zaakobjecttype het gaat.

Strikt genomen heb je gelijk. Echter wordt deze relatie ook gelegd bij:

- statussen en statustypen,
- resultaten en resultaattypen,
- rollen en roltypen,
- besluiten en besluittypen,
- informatieobjecten en informatieobjecttypen.

Al deze relaties zijn net zo uniek. Ik zou, om consistent te blijven, daarom ook het zaakobject aan het zaakobjecttype willen linken.

Overigens staat in het [ImZTC](https://www.gemmaonline.nl/index.php/Informatiemodel_Zaaktypen_(ImZTC)) het ZAAKOBJECTTYPE als een 'objecttype' gedefinieerd. Dit in tegenstelling tot bijvoorbeeld het ZAAK-INFORMATIEOBJECT-TYPE dat als een 'relatieklasse' staat gedefinieerd. Ook ROLTYPE en STATUSTYPE zijn bijvoorbeeld als 'objecttype' gedefinieerd. Dat is dus een argument voor de hierboven gestelde vergelijking.

Nu zou je overigens met een aanpassing van het ImZTC van het ZAAKOBJECTTYPE ook een 'relatieklasse' kunnen maken, maar dan... een relatie waarmee? In het ImZTC komt het 'objecttype' OBJECTTYPE namelijk niet voor! Zou je dat 'objecttype' wel in het ImZTC opnemen, dan moet m.i. de Catalogi API ook OBJECTTYPEn gaan ondersteunen. Maar het idee is juist om dat met de Objecten API te gaan doen. Lastig, lastig..... ;-)

> Verder, in ImZTC en RGBZ is nog sprake van 'Ander zaakobject(type)'. M.i. is dit in de CG-wereld niet meer nodig. Van elk te koppelen objecttype is daarin een registratie aanwezig. Het maakt dan niet meer uit of het een basisregistratieobject of een ander soort object is.

Zie ook #1871 .

**Comment by michielverhoef** [comment]
Zaakobjecttypen is opgenomen in de nieuwe versie van de Catalogi API: https://catalogi-api.test.vng.cloud/api/v1/schema/#tag/zaakobjecttypen

**Comment by michielverhoef** [comment]
@ArjanKloosterboer kunnen we hier nog even contact over hebben? Ik ben het met je eens dat we dit gelijk goed moeten doen maar zie ook nog wel kanttekeningen bij Objecttype.
@hdksi kun jij hier ook bij aansluiten?

**Comment by ArjanKloosterboer** [comment]
Plan maar een overlegje.

Met vriendelijke groet,
Arjan

________________________________
Van: Michiel Verhoef ***@***.***>
Verzonden: woensdag 8 juni 2022 16:56
Aan: VNG-Realisatie/gemma-zaken ***@***.***>
CC: Arjan Kloosterboer ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [VNG-Realisatie/gemma-zaken] Als ZTC-beheerder wil ik zaakobjecttypen kunnen inrichten (#1846)


@ArjanKloosterboer<https://github.com/ArjanKloosterboer> kunnen we hier nog even contact over hebben? Ik ben het met je eens dat we dit gelijk goed moeten doen maar zie ook nog wel kanttekeningen bij Objecttype.
@hdksi<https://github.com/hdksi> kun jij hier ook bij aansluiten?
