### ISSUE TITLE
Als gemeente wil ik dat de Catalogi API alles zoals gedefinieerd in het ImZTC ondersteunt

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1847]
...zodat de Catalogi API ook aansluit op de DSO.

Zie ook #1864

NB. Dit is een kapstok-issue voor de nieuwe Catalogi API die wordt ontworpen.

**Comment by MarcoKlerks** [comment]
De objecttypen zitten niet in het ImZTC. Ik vraag mij af of deze wel in de Catalogi-API zouden moeten zitten, want het zijn "typen". Ik heb hier echter geen hele stevige opvatting over. 

Maykin heeft in ieder geval al een [objecttypen-API](https://objects-and-objecttypes-api.readthedocs.io/en/latest/) ontwikkeld en heeft dit los gezet van de Catalogi-API.

**Comment by MarcoKlerks** [comment]
Ik heb een aantal stories opgevoerd t.b.v. de zaakobjecttypen. Ten behoeve van het overzicht:
- In #1846 vraag ik om de zaakobjecttypen toe te voegen aan de Catalogi API,
- In #1848 vraag ik om het koppelen van zaakobjecten aan zaken afhankelijk te maken van de zaakobjecttypen,
- In #1849 vraag ik om de 'brondatumArchiefprocedure' aan te passen aan de zaakobjecttypen,
- In #1850 vraag ik om de gewijzigde 'brondatumArchiefprocedure' toe te passen bij het bepalen van de 'archiefactiedatum' (plus een andere verbetering).

**Comment by michielverhoef** [comment]
> De objecttypen zitten niet in het ImZTC. Ik vraag mij af of deze wel in de Catalogi-API zouden moeten zitten, want het zijn "typen". Ik heb hier echter geen hele stevige opvatting over.


Door de ze in de Catalogi API op te nemen zou het verplicht worden voor een implementatie van de Objectenregistratie de gehele Catalogi API te implementeren. Dat is misschien een beetje veel van het goede.

Op zich ben ik wel voor gescheiden houden maar er moet wel iets bedacht worden om te borgen dat objecttypen niet zomaar kunnen verdwijnen uit de Objecttypen API en daarmee de Zaaktypeobjectypen uit de Catalogi API ongeldig worden.

**Comment by sergei-maertens** [comment]
Ik zie dat hiervoor in Catalogi API velden aan `RolType` toegevoegd zijn: catalogus, begin & einde geldigheid zonder enige aandacht voor data-integriteit met het zaaktype waar een roltype bij hoort. Ik snap deze ingeslagen weg niet, vooral omdat deze parameters direct uit het bijhorende zaaktype afgeleid (kunnen/moeten) worden.

Daarnaast zie ik dan dat er in https://github.com/VNG-Realisatie/catalogi-api/pull/135 hier bovenop gebouwd wordt, en ik zie dus vooral een referentie-implementatie ontstaan waarin het makkelijk is om inconsistente data op te voeren, niet in het minst omdat ImZTC op deze aspecten onvoldoende doordacht is op het gebied van data-integriteit & praktische implementatie van dit informatiemodel in software.

Ik wil er dus graag op aandringen dat VNG niet zomaar klakkeloos informatiemodellen naar code vertaalt. Ik verwacht echt kwaliteitsbewaking vanuit VNG/developers die voor VNG werken zodat de standaard en referentie-implementaties het makkelijk maken om de juiste patronen te implementeren (door leveranciers) en dat uiteindelijk consumers niet met de rotzooi van inconsistente data moeten omgaan. Gegevensintegriteit **moet** door de providers afgedwongen worden.

**Comment by sergei-maertens** [comment]
Ik had het in mijn eerste alinea vooral over de implementatie van de referentie-implementatie, maar goed, ik wacht af en kijk of ik er gaten in kan prikken die beter mijn kritiek ondersteunen.
