### ISSUE TITLE
Productvisie verduidelijking UGM/RGBZ 2.0

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#185]
Kan de betekenis van UGM verduidelijkt worden met afkorting uitleg en link naar relevante documentatie?

> RGBZ 2 en het daarvan afgeleide gegevensmodel UGM GBZ (GEMMA 2) zijn het startpunt voor de uitwerking van services. Wanneer blijkt dat aanpassingen nodig zijn voor goede werking van de Zaak- en Documentservices dan is dit mogelijk. In eerste instantie betreft dat het UGM GBZ. 

Zie commit: https://github.com/VNG-Realisatie/gemma-zaken/commit/f4e7e863c318ae1eb0bc588ef874946d19b1ee31

Impliceert deze alinea ook dat het RGBZ 2.0 (in concept) na afloop van dit project de status van RGBZ 2.0 definitief wordt?

Even aan @ehotting geassigned. Kan Arjan Kloosterboer niet vinden.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Wellicht jouw visie toevoegen (en prio :-))

**Comment by Hugo-ter-Doest** [comment]
We gaan niet met een UGM werken. We stellen een informatiemodel op dat precies aansluit op de API's en houden dat in het vervolg bij. Ik sluit hem af.
