### ISSUE TITLE
Als applicatiebeheerder wil ik een nieuwe versie van een zaaktype kunnen maken zonder impact op andere zaaktypes

### ISSUE THREAD

**Issue by MNIJ** [VNG-Realisatie/gemma-zaken#1851]
"Zodat ik niet de hele ZTC opnieuw hoef te maken als één zaaktype wijzigt."

Een zaaktype heeft een lijst van mogelijke deelzaaktypen en gerelateerdeZaaktypen. Deze relaties liggen momenteel vast op de URL van het zaaktype. Dat heeft het volgende gevolg: 

1. Stel bij zaaktype A staat zaaktype B als mogelijke vervolgzaak in het lijstje gerelateerdeZaaktypen.
2. Zaaktype A en B zijn gepubliceerd en in gebruik en kunnen dus niet aangepast worden.
3. Nu moet er een nieuwe versie van zaaktype B komen. Die nieuwe versie krijgt per definitie een nieuwe URL.
4. De URL van de nieuwe versie staat niet in de gerelateerdeZaaktypen bij A.
5. Om dat recht te trekken moet je dan ook een nieuwe versie van zaaktype A maken.
6. Als A dan ook weer bij andere zaaktypes voorkomt als gerelateerd zaaktype of deelzaaktype, dan krijg je een sneeuwbaleffect.

 
Dit kan voorkomen worden door de relaties tussen zaaktypen op Identificatie van het zaaktype te leggen, in plaats van op URL. Hiermee blijven de relaties tussen zaaktypes intact bij nieuwe versies van zaaktypes.
(daarmee wordt het wel noodzakelijk om van Identificatie een verplicht veld te maken in het zaaktype, maar dat lijkt sowieso heel logisch)

**Comment by michielverhoef** [comment]
Wanneer op de voorgestelde manier de relatie tussen twee gerelateerde zaaktypen gemaakt wordt is het niet meer te achterhalen wat het zaaktype was ten tijde van het aanmaken van een zaak. Immers, Zaaktype A verwijst op een gegeven moment naar een gewijzigd Zaaktype B.  Juist om de correcte versies aan elkaar te relateren (immers, het zaaktype van een zaak mag niet meer wijzigen) is het noodzakelijk een geheel nieuw zaaktype inclusief gerelateerden te maken.

Ditzelfde geldt ook voor Besluittypenen, Resultaattypen, Roltypen etc.  Zaaktype is geen losse resource, eigenlijk is een zaaktype-definitie het geheel van Zaaktype, Besluittype(n), Resultaattype(n), Roltype(n), Informatieobjectrtype(n), eigenschappen etc.

**Comment by MNIJ** [comment]
Voor alle door jou genoemde relaties ben ik het daar mee eens. Maar niet voor de gerelateerde zaaktypen, om de bovengenoemde reden. Het vastleggen van mogelijke gerelateerde zaaktypen is een functionele relatie tussen deze zaaktypen, geen technische relatie.

Laten we de oorspronkelijke versie van zaaktype B even B.1 noemen en de nieuwe versie B.2. Als dit voorstel wordt overgenomen, is het mogelijk dat de ene zaak van type A een relatie heeft met een B.1 zaak en een andere zaak van type A met een B.2 zaak. Het zou theoretisch zelfs kunnen dat dezelfde A zaak relaties heeft naar B.1 en B.2 zaken. Maar volgens mij is dat functioneel geen enkel probleem en zelfs wenselijk.
Om het even concreet te maken, je wil bijvoorbeeld dat je Vergunningszaaktype (A) een Controlezaaktype (B) als vervolg heeft. Wat exact de technische specificaties zijn van die Controlezaak, zoals welke Informatieobjecttypes er aan hangen, is voor de inrichting van het Vergunningszaaktype niet van belang.

Uiteraard moet de relaties tussen zaken zelf WEL direct op URL niveau gelegd worden en daarmee is ook altijd te achterhalen van welk zaaktype de gerelateerde zaak is. 

Het zou daarnaast wel goed zijn als er ook audit trailing op zaaktype niveau zou zijn, maar dat is een totaal andere user story. Daarmee zou, als daar noodzaak voor is, altijd nog achterhaald kunnen worden welk zaaktype met een bepaalde identificatie actief was op een bepaald moment. Maar de noodzaak daarvoor is klein en dat zijn echt edge-cases.

**Comment by MNIJ** [comment]
"Voor alle door jou genoemde relaties ben ik het daar mee eens." daar is ook nog wel nuance in aan te brengen, voor Besluittypen en Informatieobjecttypen zou je dezelfde argumenten kunnen maken.

Statustypen, Roltypen, Eigenschappen, zijn allemaal relaties die specifiek voor 1 zaaktype zijn, het zaaktype vormt dus inderdaad een volledige resource in combinatie met die gerelateerde entiteiten.

Maar Besluittypen, Informatieobjecttypen en gerelateerde zaaktypen zijn eigen resources die gedeeld worden tussen meerdere zaaktypen en ook op zichzelf staan. Als je dat ook allemaal als integraal onderdeel van de resource Zaaktype ziet, is in feite de gehele ZTC één resource die alleen in zijn geheel ge-update kan worden.

Het probleem speelt het meest bij de Zaaktype-Zaaktype relatie, maar er zouden een hoop dingen eenvoudiger en logischer worden als dezelfde logica (relateren op Identificatie, ipv URL) voor de relaties naar Besluittypen en Informatieobjecttypen gebruikt werd. Maar Besluittype en Informatieobjecttype hebben momenteel niet eens een Identificatie veld.

Maar de scope van deze story moet misschien wel op Zaaktype-Zaaktype blijven.

**Comment by michielverhoef** [comment]
> Als dit voorstel wordt overgenomen, is het mogelijk dat de ene zaak van type A een relatie heeft met een B.1 zaak en een andere zaak van type A met een B.2 zaak

Dit kun je niet vastleggen wanneer je niet naar de exacte versie van een zaaktype verwijst. Door alleen de identificatie te gebruiken (die blijkbaar voor zowel B1 als B2 hetzelfde is, anders heeft het geen nut) weet je vanuit zaaktype A niet of je naar B1 of B2 verwijst. Dan moet de consumer een ingewikkeld stuk logica implementeren om de juiste versie van zaaktype B op te halen. 

De audit trail waar je om vraag is in feite ingebouwd door bij een wijziging een nieuwe versie van het zaaktype vast te leggen. Dan kun je altijd achterhalen welke typen aan welke andere typen gerelateerd zijn.

Het voorstel wat je doet maakt het weer veel complexer om die audit trail te maken. Door een nieuwe versie op te slaan is de audit trail automatisch ingebakken. 

Zoals ik het nu zie neig ik er naar om dit niet te doen, het is het inwisselen van het ene voor het andere. Waarbij de audit trail veel lastiger te implementeren is dan op de correcte manier een nieuwe versie aan te maken.

> Maar de noodzaak daarvoor is klein en dat zijn echt edge-cases.

Dit is juist wat er altijd moet kunnen, vandaar de gekozen werkwijze. Ik denk eerlijk gezegd dat het wel mee zal vallen hoeveel zaaktypen aan elkaar gerelateerd zijn en hoe vaak dat moet wijzigen. Bovendien, als er een wijziging is dan is daar een reden voor en dan mag er best even over nagedacht worden.

**Comment by MNIJ** [comment]
Het punt is niet zozeer dat de relaties tussen zaaktypes vaak zullen wijzigen. Het punt is dat als A en B aan elkaar gerelateerd zijn en bij B moet ik iets willekeurigs wijzigen (zoals een nieuw Informatieobjecttype toevoegen) dan moet ik nu daardoor ook een nieuwe versie van A maken. En A kan ook weer relaties naar C en D hebben, enzovoorts.

**Comment by PaulaRuijter** [comment]
Als beheerder van een vergunningen applicatie ben ik het eens met Michiel Nijdam. Als ik naga (met expliciete zaaktypen waar verschillende soorten processen aan gekoppeld zijn) dat een vergunningszaak een controle zaak, bezwaarzaak, beroepzaak of handhavingzaak als koppeling kan hebben. Én diezelfde gekoppelde zaken allemaal ook kunnen worden gewijzigd door een meldingszaak.... Dan kom ik wel op potentieel aardige wijzigen. Ik zit er niet op te wachten om voor een nieuw mogelijk documentsoort of andere informatietypeobjecten de verschillende processen te updaten. Dan ben ik met nieuwe programmatuur langer bezig om wijzigingsverzoeken door te voeren dan huidige werkwijzen. Daarbij moet ik dan ook nog een schema voor mezelf gaan bijhouden wat allemaal aan elkaar gelinkt is om te zorgen dat ik door een wijziging bij zaaktype A niet een gebruiker van zaaktype B met foutmeldingen opzadel ofwel zelf telkens niet een wijziging kan doorvoeren, omdat ergens een ander zaaktype nog niet juist is aangepast. Ik zie zo voor me dat ik administratief veel extra werk tegemoet ga. De heer Michiel Verhoef aangeeft dat er niet vaak wijzigingen zullen zijn (dat ik betwijfel met de snelle wereld waar we in leven en de afgelopen jaren ook diverse infomatieobjecttypen aan wijziging onderhevig waren) is bij niet vaak uitvoeren van een dergelijke taak met alle mogelijke koppelingen nooit iets wat goed in je hoofd blijft zitten en dus makkelijk tig keer opnieuw moet. Is het toch inderdaad iets dat vaker voorkomt wordt je gek van al het werk in de verschillende zaken voor 1 enkele actie...  Kortom, mij lijkt het matchen van een IDcode ook logischer dan een URL waarmee alles vast komt.

**Comment by michielverhoef** [comment]
@PaulaRuijter ik begrijp wat je zegt maar dit is precies wat een consumer applicatie voor jou als menslijke gebruiker zou moeten afvangen/regelen. De API's zijn absoluut niet bedoeld om 1-op-1 de werkwijze van een menslijke gebruiker te bepalen.

Het schema bijhouden is dus iets wat de beheermodule voor jou zou moeten doen. Dat moet niet in jouw hoofd zitten en dat moet ook niet in de API's vastgelegd worden.

Het is aan de leverancier om hier een slimme oplossing voor te verzinnen en onder water de menslijke gebruiker zo goed mogelijk te ondersteunen. 

Voor jullie beider beeld: De gebruiker van de API's is de ontwikkelaar die met deze API's sneller en eenvoudiger een applicatie kan ontwikkelen.  Niet de functionele beheerder van de zaaktypen catalogus van de gemeente. Die moet door de leverancier bediend worden met applicatie die zijn/haar wensen ondersteunt.


> De ZTC API voorziet er bovendien al in om zaaktypes op basis van Identificatie op te halen, dus dat is vrij eenvoudig. Het is veel moeilijker aan onze gebruikers uit te leggen dat een wijziging in Zaaktype B betekent dat ze een groot deel van hun zaaktypes moeten aanpassen. En logica bouwen om dat te automatiseren is vele malen ingewikkelder, nog even afgezien van het feit dat het onwenselijk is om geautomatiseerd nieuwe zaaktypes te maken zonder dat dit de expliciete wens van de gebruiker is.

Nogmaals, het is een misverstand dat de beheerder zelf handmatig alle typen opnieuw aan moet maken. Dat is iets wat de leverancier in de applicatie in moet bouwen.

Tot slot, ik wil best geloven dat er verbeteringen mogelijk zijn maar dit voorstel is het verplaatsen van een probleem. Het probleem wordt op deze manier verplaatst van een correcte toepassing van een standaard naar een schemer gebied waar feitelijk hetzelfde gedrag moet worden geimplementeerd als wat de consumer nu al zou moeten uitvoeren met de huidige API's. Nl. de audit trail opbouwen. Want dat is precies wat er moet gebeuren.

**Comment by MarcoKlerks** [comment]
Ik heb niet de hele discussie gelezen, maar het deed me denken aan de oplossing in de Maykin's [Objects and Objecttyes API](https://objects-and-objecttypes-api.readthedocs.io/en/latest/index.html). Zie met name het [informatiemodel](https://objects-and-objecttypes-api.readthedocs.io/en/latest/introduction/information-model.html) en hoe daarin wordt omgegaan met versies van objecttypen.

**Comment by MNIJ** [comment]
> Het is aan de leverancier om hier een slimme oplossing voor te verzinnen en onder water de menslijke gebruiker zo goed mogelijk te ondersteunen.

Wij doen als leverancier dit soort voorstellen niet omdat we het onszelf makkelijk willen maken. Wij hebben ons gecommitteerd aan de ZGW standaard en willen die ten volle implementeren. We zien deze standaard ook op veel vlakken als een enorme verbetering ten opzichte van eerdere standaarden. Maar het is ook een vrije jonge standaard waar nog weinig ervaring in de praktijk mee is opgedaan en het is dus heel logisch dat er nog wat haken en ogen aan zitten. Wij doen alleen maar voorstellen als we echt denken dat het strikt volgen van de standaard het onmogelijk maakt om een goed werkende applicatie te bouwen waar eindgebruikers mee uit de voeten kunnen. Eerder in deze discussie gaf ik aan dat het automatiseren van de scenario's die ik en @PaulaRuijter schetsen ingewikkeld zou zijn. Ik wil dat wel aanscherpen naar "onmogelijk" binnen de standaard. Maar ik word graag overtuigd van het tegendeel.

> Tot slot, ik wil best geloven dat er verbeteringen mogelijk zijn maar dit voorstel is het verplaatsen van een probleem. Het probleem wordt op deze manier verplaatst van een correcte toepassing van een standaard naar een schemer gebied waar feitelijk hetzelfde gedrag moet worden geimplementeerd als wat de consumer nu al zou moeten uitvoeren met de huidige API's. Nl. de audit trail opbouwen. Want dat is precies wat er moet gebeuren.

Ik begrijp eerlijk gezegd nog niet hoe dit voorstel een probleem introduceert met verantwoording of data-integriteit. Elke zaak is nog steeds van een expliciet, op URL niveau vastgelegd zaaktype, daar verandert niks aan. Elke relatie tussen zaken is ook gewoon een directe referentie op URL niveau. Er is nog steeds op elk moment in de tijd één actieve versie van een zaaktype, welke ook achteraf bepaald kan worden. Het is voor de ZRC of een Zaak Behandelcomponent nog steeds mogelijk om te valideren of een zaak-zaak relatie aangemaakt mag worden conform de toegestane relaties in de zaaktypen.  Kan je concreet maken welk probleem hierdoor ontstaat?

**Comment by MNIJ** [comment]
> Ik heb niet de hele discussie gelezen, maar het deed me denken aan de oplossing in Maykin's [Objects and Objecttyes API](https://objects-and-objecttypes-api.readthedocs.io/en/latest/index.html). Zie met name het [informatiemodel](https://objects-and-objecttypes-api.readthedocs.io/en/latest/introduction/information-model.html) en hoe daarin wordt omgegaan met versies van objecttypen.

Dit datamodel is inderdaad ook een goede oplossing voor dit probleem. Maar overstappen op dat model zou wel een enorme wijziging zijn in de ZGW standaard, dan moet er heel veel op de schop.

Vertaalt naar de termen van dit model wordt nu eigenlijk het veld Zaaktype.Identificatie gebruikt als identifier van het Objecttype en Zaaktype.UUID (of URL) als identifier van de ObjecttypeVersion. Maar dan in de ene entiteit Zaaktype.

**Comment by joeribekker** [comment]
We hadden bij de Objecten en Objecttype API meer vrijheid, meer kennis en minder legacy mee te slepen. Ook is de API eenvoudiger en kent deze minder cross-afhankelijke resources. Dit leidde inderdaad tot andere keuzes. Ik zou ZGW nu nog niet gaan omgooien.

**Comment by michielverhoef** [comment]
Opgelost in #2038

**Comment by michielverhoef** [comment]
Het historiemodel is opgenomen in Catalogi API 1.3.0.
