### ISSUE TITLE
Bij zaakinformatieobject moet de richting vastgelegd kunnen worden (vervolg van #1782)

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#1856]
Op dit moment is het niet mogelijk de richting van een document vast te leggen (inkomend of uitgaand).
Voorstel: bij zaakinformatieobject komt een nieuw veld richting dat zowel bij het aanmaken als opvragen beschikbaar is.
Dit voorstel zou kunnen vervallen als #1785 gerealiseerd wordt.

**Comment by michielverhoef** [comment]
Ik laat het nog even open staan. Het is wel de bedoeling #1785 te realiseren en zo de richting vast te kunnen leggen dan kan deze wens daarmee ingevuld worden.

**Comment by michielverhoef** [comment]
Zie https://app.swaggerhub.com/apis/michielverhoef/Documenten_API/1.2.0-alpha#/verzendingen/verzending_list

Aan de hand van de Verzending en het attribuut "aardRelatie" kan worden afgeleid of het document ontvangen dan wel verzonden is. Overigens kan een document zowel ontvangen als verzonden zijn.

**Comment by michielverhoef** [comment]
Relatieklasse Verzendingen is onderdeel van de 1.3.0 versie https://documenten-api.test.vng.cloud/api/v1/schema/#tag/verzendingen

**Comment by michielverhoef** [comment]
Opgelost met relatieklasse Verzendingen.

**Comment by michielverhoef** [comment]
https://documenten-api.test.vng.cloud/api/v1/schema/#tag/verzendingen
