### ISSUE TITLE
Als gebruiker wil ik dat alle bedrijfsregels van de DRC API op 1 plek staan

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1858]
...zodat ik niet verschillende bronnen hoef na te zoeken en ik zeker weet dat ik alle informatie snel bij de hand heb.

Op dit moment staan de meeste bedrijfsregels in de documentatie als regel "drc-xxx" (etc.) beschreven. Daarnaast staat er logica in de API specificatie (OAS). De kans bestaat dat iemand een deel van de bedrijfsregels niet ziet en de validatie daarom niet helemaal correct is.

Bedrijfsregels moeten daarom allemaal in de documentatie opgenomen worden, in de API specificatie wordt dan (hooguit) verwezen naar relevante bedrijfsregels of de pagina in het algemeen.

Dit maakt het ook makkelijker om eventuele tik/taalfouten in de bedrijfsregels te corrigeren zonder dat een nieuwe versie van de API gemaakt moet worden.

**Comment by michielverhoef** [comment]
https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/index 
De "verborgen" regels uit de openapi.yaml zijn opgenomen in de specificatie van run-time gedrag.

De vraag is nog even hoe vanuit de openapi.yamp de verwijzing naar de regels gemaakt moet worden.Is het voldoende door een link naar de pagina https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/index op te nemen?
@johannesbattjes ?

**Comment by johannesbattjes** [comment]
Lijkt mij prima
