### ISSUE TITLE
Afhankelijkheden tussen API's

### ISSUE THREAD

**Issue by w-van-weelden** [VNG-Realisatie/gemma-zaken#1860]
Wanneer een document gekoppeld wordt aan een zaak, wordt de link in de Zaken API geïnitieerd. De Zaken API update zelf de Documenten API met de relatie naar de zaak, zodat er een dubbele relatie ontstaat. De Besluiten API heeft een soortgelijke functionaliteit. Ook bij het verwijderen van een zaak, moet de Zaken API de verwijdering doorgeven aan gerelateerde API’s. Dit betekent dat er een technische afhankelijkheid is tussen losse registraties.

De afhankelijkheid leidt tot een complex te beheren landschap, omdat de APIs niet los van elkaar staan. Dit zorgt voor complexer beheer en versie-afhankelijkheid van API’s. Gegeven de visie van Common Ground pleiten wij om de API’s los te houden en de afhankelijkheden in logica niet in API’s te beleggen.

Wij stellen voor om deze afhankelijkheden te verwijderen. We stellen voor om koppelingen naar andere resources eenmalig op te slaan in de hoofdregistratie. Bij de relatie tussen zaken en documenten is dit bijvoorbeeld bij de zaak. De integriteit moet de verantwoordelijkheid worden van de applicatie die de resources bewerkt.

**Comment by sergei-maertens** [comment]
> De afhankelijkheid leidt tot een complex te beheren landschap, omdat de APIs niet los van elkaar staan. Dit zorgt voor complexer beheer en versie-afhankelijkheid van API’s. Gegeven de visie van Common Ground pleiten wij om de API’s los te houden en de afhankelijkheden in logica niet in API’s te beleggen.

Dit is essentieel voor integriteit-garanties naar clients toe en down-the-road naar archivering. Je mag geen documenten in de documenten API vernietigen als er nog verwijzingen naar deze documenten zijn.

Als applicatie-ontwikkelaar die gebruik maakt van deze API's ben ik het niet eens met dit voorstel.

**Comment by w-van-weelden** [comment]
Het feit dat je geen documenten mag verwijderen als er nog verwijzingen naar bestaan betekent in mijn optiek niet dat je relaties dubbel moet gaan vastleggen. De DRC kan ook een request aan de operatie zaakinformatieobject_list sturen met de UUID van het document als parameter.

Mijn laatste zin is misschien een beetje ongelukkig: “De integriteit moet de verantwoordelijkheid worden van de applicatie die de resources bewerkt”. 

Aan de andere kant is het nu wel zo dat als jij als auteur een heel verkeerd document upload en iemand koppelt die aan zijn zaak, dan krijg jij dat document niet meer verwijderd. Dat betekent dus dat, als we spreken over integriteit, het idee van Sergei documenten ondergeschikt maakt aan zaken. En dan is de vraag of het terecht is dat die in een eigen, onafhankelijk component zijn ondergebracht. Het lijkt me dat we deze los willen houden.

**Comment by sergei-maertens** [comment]
> De DRC kan ook een request aan de operatie zaakinformatieobject_list sturen met de UUID van het document als parameter.

Dat kan dus niet tenzij de DRC weet welke Zaken API gebruikt wordt :) Deze API's zijn als distributed systeem opgezet omdat er leveranciers zijn die ervoor kiezen om de Zaken API in hun bestaande software in te bouwen, terwijl anderen gebruik maken van een productie-versie die alleen maar Zaken API aanbiedt en verder niets. Dit leidt dus tot de volgende situatie:

Zaken API 1, Zaken API 2, Zaken API n..., gecombineerd met een Documenten API (voor de eenvoud gaan we uit dat er maar 1 documenten API is, maar daarvan kunnen er ook meerdere zijn, dus).

Als de documenten API dus wil controleren of er nog een relatie bestaat, dan moet die:

1. geconfigureerd worden met een lijst van alle relevante Zaken APIs
2. alle Zaken API's afgaan om te valideren dat er geen relaties meer zijn

Daar komt ook bij dat een service down kan zijn, en dus een false negative geven dat er geen documenten meer zijn. Als expliciet bekend is in de Documenten API _waar_ de relaties vandoen zijn, dan:

1. Hoeft de documenten API niet expliciet geconfigureerd zijn, want de locatie van de Zaken API is meteen bekend uit OIO (uiteraard is er wel nog een credential-systeem nodig zodat de documenten API bij de Zaken API kan komen)
2. kan direct op de juiste plaats gezocht worden (`O(1)`) in plaats van een `O(n)` requests te maken, met n het aantal zaken API's.

> Dat betekent dus dat, als we spreken over integriteit, het idee van Sergei documenten ondergeschikt maakt aan zaken. En dan is de vraag of het terecht is dat die in een eigen, onafhankelijk component zijn ondergebracht. Het lijkt me dat we deze los willen houden.

Documenten kunnen ook aan besluiten gerelateerd worden ipv aan zaken! En dat is een patroon wat breder toepasbaar is, vandaar dat de Documenten API ook als "onafhankelijk" component bestaat.

**Comment by w-van-weelden** [comment]
Het is een goed punt dat de DRC niet weet welke Zaken API gebruikt wordt. Andersom is natuurlijk wel het geval omdat de koppeling met het document in de ZRC wordt vastgelegd.

Maar hiermee gaat het volgens mij toch niet helemaal goed. Je hebt dubbele vastlegging van de relatie maar ook is het document in een ondergeschikte positie. Waarom mogen we bijvoorbeeld niet het document verwijderen en wel de zaak? Technisch gezien zou je kunnen stellen dat in het eerste geval een dode link ontstaat en in het tweede geval niet. Maar functioneel is er waarschijnlijk wel een probleem als een zaak wordt verwijderd en de gekoppelde documenten niet. De meeste documenten die je aan zaken koppelt gaan immers over die zaak. Denk aan de originele aanvraag, de ontvangstbevestiging, het verzoek om aanvullende stukken, etc.

Als die relatie toch dubbel is vastgelegd, zou je er ook voor kunnen kiezen dat de DRC bij verwijderen van een document de gerelateerde componenten bijwerkt (of via notificaties?)

Ik zie dat bij het creëren van een besluit in de besluiten api ook een url referentie naar een zaak in het request kan worden opgenomen. Ook hier geldt dat de relatie door de consumer in de BRC wordt gelegd en de BRC deze ook vastlegt in de ZRC. Ook hier wordt de relatie dus dubbel vastgelegd (https://vng-realisatie.github.io/gemma-zaken/standaard/besluiten/index#brc-006). Maar hier is het wel mogelijk om een besluit te verwijderen als deze aan een zaak is gekoppeld (brc-009). Waarom hanteren we niet dezelfde aanpak ook voor documenten?   

Het punt is dat, als we op deze voet doorgaan, het idee van loosely coupled componenten verloren gaat in de dubbele koppelingen met controles. Denk bv. aan alle resources die straks met een URL referentie als zaakobject aan een zaak kunnen worden gekoppeld. Moeten die allemaal de mogelijkheid bieden om relaties over te nemen en vast te leggen? En dan alleen met zaken of bv ook met andere resources? Gaan we straks de relatie tussen personen en adressen zowel in de BRP als in de BAG bijhouden?

**Comment by sergei-maertens** [comment]
> Maar hiermee gaat het volgens mij toch niet helemaal goed. Je hebt dubbele vastlegging van de relatie maar ook is het document in een ondergeschikte positie. Waarom mogen we bijvoorbeeld niet het document verwijderen en wel de zaak?

Het is meer genuanceerd dan dat. Uiteindelijk zijn de record-management applicaties verantwoordelijk voor het vernietigen van het hele dossier, inclusief de documenten. Dat kan enkel als deze documenten niet aan andere dossiers (zaken, besluiten) gerelateerd zijn. Een document is niet ondergeschikt aan een zaak, maar een document kan wel een bestaansrecht hebben zonder zaak. De opzet van de Documenten API is net dat je documenten dus ook kan relateren aan andere objecten dan zaken/besluiten (in Utrecht bijvoorbeeld aan ad-hoc activiteiten). Helaas is die omgekeerde-relatie niet verder uitgewerkt.

> Als die relatie toch dubbel is vastgelegd, zou je er ook voor kunnen kiezen dat de DRC bij verwijderen van een document de gerelateerde componenten bijwerkt (of via notificaties?)

Historisch dingetje, notificaties kwamen pas later als het relateren van zaken en documenten er wel al was. Mijn persoonlijke voorkeur gaat ook uit naar het bijhouden van de relatie-informatie op basis van notificaties. Dat betekent dan wel dat een documenten API zich op de juiste notificatie API(s) moet abonneren. Misschien is dat iets voor v2 van de standaarden.

> Waarom hanteren we niet dezelfde aanpak ook voor documenten?

Dat is het verschil tussen een many-to-many relatie een een one-to-many. Besluiten kunnen ook bestaan zonder de context van een zaak (bijv. raadsbesluiten), al is dit vooral een theoretisch gegeven want ik moet echt nog de eerste persoon tegenkomen die daadwerkelijk besluiten gebruikt.

"Maar hier is het wel mogelijk om een besluit te verwijderen als deze aan een zaak is gekoppeld (brc-009)." -> de actie van het verwijderen van een besluit houdt meteen in dat hiermee de relatie ook verbroken wordt. Er is geen "koppeltabel" van doen hier, omdat het om een one-to-many relatie gaat.

> Het punt is dat, als we op deze voet doorgaan, het idee van loosely coupled componenten verloren gaat in de dubbele koppelingen met controles. Denk bv. aan alle resources die straks met een URL referentie als zaakobject aan een zaak kunnen worden gekoppeld. Moeten die allemaal de mogelijkheid bieden om relaties over te nemen en vast te leggen? En dan alleen met zaken of bv ook met andere resources? Gaan we straks de relatie tussen personen en adressen zowel in de BRP als in de BAG bijhouden?

Dit lijkt een beetje op een "slippery slope" falacy. Het is voor zaakobjecten niet zo doorgevoerd op dit moment, omdat de aard van die relatie minder tightly coupled is dan zaken/documenten. De ene service staat meer op zichzelf dan de andere en er zijn verschillende criteria waarom je services wel of niet zou opsplitsen. En zoals dat altijd gaat in IT, is dat een trade-off en bestaat er geen perfecte oplossing waar iedereen 100% mee blij is.

Wat betreft de controles + data-integriteit is het uitgangspunt altijd het CG principe geweest van "developer friendly" zijn, en dan vooral vanuit het perspectief van de client applicaties die de API's consumeren. Je kan de pijn eenmalig pakken aan de registratiekant waarmee je vele keren de garantie kan bieden naar de consumerkant dat de integriteit van de gegevens zo goed mogelijk bewaakt blijft en dat niet elke client dezelfde checks & defensive programming hoeft toe te passen en zich eerder kunnen focussen op nuttige functionaliteit voor de eindgebruikers.

**Comment by w-van-weelden** [comment]
Het is altijd een afweging wat pragmatisch de beste oplossing is. Vanuit pragmatisch oogpunt is er een keuze gemaakt. Het zou niet onze keuze zijn, maar laten we het voor nu accepteren. Maar bij meerdere koppelingen dit wel in de gaten houden. Ik stel voor dat we het nu accepteren en in volgende versies verder uitwerken qua notificaties. Is het handig om daar een ander item voor te maken en dit te sluiten?

**Comment by michielverhoef** [comment]
Eerlijk gezegd begrijp ik het probleem niet en zie vooral wel grote risico's wanneer niet aan beide kanten een relatie vastgelegd en bijgehouden wordt. 

Het is ook niet nieuw. Deze afhankelijkheid was er ook altijd al in de Zaak- Documentservices. Bij het aanmaken van een zaak (creeerZaak_zakLk01) voert het Zaaksysteem de volgende CMIS operaties uit (paragraaf 4.1.4.3):

Het ZS voert CMIS-operaties uit, zodat:
* In het DMS een Zaaktype-object (zie paragraaf 5.1) gecreëerd wordt indien deze nog niet bestaat. Het gecreeerde Zaaktype moet aanwezig zijn in de lijst met vastgelegde Zaaktypes;
* In het DMS een Zaakfolder-object (zie paragraaf 5.1) gecreëerd wordt;

Hiermee wordt geborgd dat in het DMS vastgelegd wordt bij welke zaak het document hoort. Dus ook in de oude wereld is het noodzakelijk om bij een document zowel bij de zaak als in het register/DMS vast te leggen bij welk(e) zaak(en) dit document hoort.

In de API's is er voor gekozen dit middels relatieklassen op te lossen. Dit maakt het ook eenvoudig om Informatieobjecten te relateren aan andere soorten gegevens (Besluiten, Resultaten, om maar eens wat te noemen) te koppelen.

De uitleg van @sergei-maertens maakt volgens mij voldoende duidelijk waarom in bepaalde gevallen voor de ene of de andere soort oplossing gekozen is.  Wat niet wil zeggen dat er niets te verbeteren valt, het blijft IT ;-).

Voor nu sluit ik dit issue, mocht er dringende behoefte zijn aan een andere manier van many-to-many relateren tussen registers mag daar altijd een nieuwe user story voor ingeschoten worden. Alleen zal dat een breaking change betekenen dus die kan niet zomaar even meegenomen worden in de eerste de beste release.
