### ISSUE TITLE
Als ontwikkelaar wil ik de laatste versiestatus van een resource in de ZTC ophalen via een GET  in plaats van een HEAD operatie

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1863]
...zodat ik de call kan combineren met eventueel ophalen van een (sub)set van  andere metadata.

NB. Dit is op het moment al mogelijk, de ETag wordt al in de header van een GET meegegeven. 
De vraag is of in de praktijk de HEAD methode ook echt gebruikt wordt of dat ontwikkelaars meestal is om de GET operatie uitvoeren met een beperkte hoeveel metatada in het request.

Met andere woorden, wat zijn de voor-/nadelen van het gebruik van de HEAD operatie in de standaard terwijl die informatie (ETag) ook beschikbaar is in de gewone GET?  Wordt de HEAD operatie ook daadwerkelijk gebruikt, worden de resources in kwestie gecached of is het net zo makkelijk om de informatie indien nodig op te halen?

NB: Ik kan me goed voorstellen dat in de praktijk zaaktype informatie bij het aanmaken van een zaak overgenomen wordt en niet elke keer opgevraagd wordt vanuit de ZTC.  Aangezien het zaaktype niet mag veranderen voor de reeds aangemaakt zaken is controleren of de overgenomen gegevens nog actueel zijn minder relevant.

**Comment by sergei-maertens** [comment]
Je gebruikt `HEAD` bijvoorbeels als je een call wil doen om te checken of je cache stale is of nog up to date. HEAD haalt de overhead weg van een response body te moeten genereren en verwerken -> server side is er minder werk nodig + er gaat minder data over de lijn = performanter.

**Comment by michielverhoef** [comment]
> Je gebruikt HEAD bijvoorbeels als je een call wil doen om te checken of je cache stale is of nog up to date. HEAD haalt de overhead weg van een response body te moeten genereren en verwerken -> server side is er minder werk nodig + er gaat minder data over de lijn = performanter.

Dit kan toch ook door een GET en de if-none-match header parameter? Tenzij je niet geinteresseerd bent in de nieuwe actuele versie van een resource en je alleen zou willen weten of je cache verouderd is.  Maar hoe nuttig is te weten dat je cache verouderd is en daar niets mee doen?

**Comment by michielverhoef** [comment]
Dit lijkt voorlopig geen issue. Ik sluit het ticket.
