### ISSUE TITLE
Documenten API: Werking grote documenten

### ISSUE THREAD

**Issue by w-van-weelden** [VNG-Realisatie/gemma-zaken#1868]
Bestanden kunnen groter zijn dan de minimale omvang die door providers ondersteund moet worden. De consumer moet dan

1. Het INFORMATIEOBJECT aanmaken in de API, waarbij de totale bestandsgrootte meegestuurd wordt en de inhoud leeggelaten wordt. De API antwoordt met een lijst van BESTANDSDEELen, elk met een volgnummer en bestandsgrootte. De API lockt tegelijkertijd het INFORMATIEOBJECT.
2. Het bestand opsplitsen: ieder BESTANDSDEEL moet de bestandsgrootte hebben zoals dit aangegeven werd in de response bij 1.
3. Voor elk stuk van het bestand de binaire data naar de overeenkomstige BESTANDSDEEL-url gestuurd worden, samen met het lock ID.
4. Het INFORMATIEOBJECT unlocken. De provider valideert op dat moment dat alle bestandsdelen correct opgestuurd werden, en voegt deze samen tot het resulterende bestand.

Binnen de OpenAPI specificatie is er ook een mogelijkheid voor grote documenten, zogenaamde multipart requests. (https://swagger.io/docs/specification/describing-request-body/multipart-requests/)

Is de implementatie binnen de Documenten API hetzelfde als de multipart requests? En zo niet, zouden multipart requests een goede mogelijkheid zijn?

**Comment by sergei-maertens** [comment]
@w-van-weelden de intentie is net dat bestandsdelen gebruikt worden omdat webservers typisch een bovengrens stellen aan de maximale request body size. Als je multipart requests gaat gebruiken en delen combineren, dan wordt je totale request body size weer groter dan wat de webserver/applicatieserver toelaat en kan je dus geen uploads doen.

In de Documenten API wordt de upload van grote bestanden net opgebroken in verschillende HTTP requests zodat je body (net) onder de webserver limiet blijft.

**Comment by w-van-weelden** [comment]
Bedankt voor de toelichting op de vraag! Wat mij betreft hebben we het daarmee voldoende behandeld.
