### ISSUE TITLE
[VRAAG] Genereer documentidentificatie

### ISSUE THREAD

**Issue by JohnRooijakkers** [VNG-Realisatie/gemma-zaken#1869]
In de ZSDMS implementaties wordt voorafgaand aan het maken en opslaan van een document, een document identificatie opgevraagd aan en gegenereerd door het DMS. Deze identificatie wordt in het document (content) opgenomen als uniek kenmerk voor de geadresseerde (burger, bedrijf of medewerker). Op welke manier is deze functionaliteit beschikbaar of beoogd bij het werken met de ZGW API's?

**Comment by michielverhoef** [comment]
Waar bij de Zaak- documentservices nog de identificaties gebruikt werden als uniek kenmerk om het gegeven (Zaak, Document, Besluit) op te halen is die rol bij de API's voor Zaakgericht Werken overgenomen door de url. Onderdeel van die url is een UUID, gegenereerd door het register.

In de API is het identificatie veld niet meer verplicht. Voor backwards compatibility kan het nog wel meegegeven worden en wanneer het veld leeggelaten wordt genereert de DRC zelf een identificatie. Deze identificatie wordt in het antwoord op de POST (aanmaken van een EnkelvoudigInformatieobject) mee terug gegeven.

Het apart laten aanmaken van een idenitificatie is nu niet meer nodig. In theorie zou het nog kunnen door eerst een container/placeholder EnkelvoudigInformatieobject (zonder inhoud) aan te maken (vgl. MaakZaakdocument bericht uit Zaak- Documentservices). Dan krijg je onder andere een identificatie teurg uit de DRC.

Met name voor aansluiten op bijvoorbeeld een documentgenerator die het gegenereerde document rechtstreeks in het DMS opslaat is dit wel belangrijk.

**Comment by JohnRooijakkers** [comment]
@michielverhoef Bedankt voor je uitleg over de werking. Maar je beantwoordt de vraag vanuit de techniek en ik bedoelde die vanuit de buIk siness functionaliteit. Gemeenten willen een unieke en voor burgers en bedrijven leesbare identificatie op uitgaande documenten plaatsen bij het genereren van deze documenten. Hiermee kunnen vragen over deze documenten aan het klant contact centrum eenvoudig worden doorgeleid naar de behandelaar van de zaak waartoe het document behoort. Zo'n unieke identificatie kan bijvoorbeeld bestaan uit de gemeente code, eventueel een jaartal en een uniek volgnummer. Ik zie graag een operatie binnen de document registratie component (en de zaak registratie component) om dergelijke identificaties te genereren.

**Comment by michielverhoef** [comment]
@JohnRooijakkers  Dan ga ik toch even de techniek weer in: In RGBZ 1 bevatte een identificatie als eerste vier karakters de gemeentecode. In RGBZ 2 is dit opgesplitst in de attributen identificatie en bronorganisatie.

Maar, zoals ik al zei, door een Enkelvoudiginformatieobject aan te maken zonder een identificatie mee te sturen wordt een unieke identificatie gegenereerd door de DRC. Deze identificatie is opgenomen in het antwoordbericht op het aanmaken van het Enkelvoudiginformatieobject  en kan doorgegeven worden aan burgers/bedrijven/medewerkers.

Volgens mij is het niet nodig om een aparte functie te hebben. De reden dat in Zaak- Documentservices een dergelijke functie nodig was is dat ZDS gebruik maakt van a-synchrone berichten. In het antwoord op een VoegZaakdocumentToe bericht (edcLk01) stond niet het resultaat van het aanmaken van het zaakdocument maar een functionele bevestiging dat het bericht verwerkbaar werd geacht. Op die manier was het niet mogelijk om een gegenereerde identificatie terug te geven als antwoord op een kennisgevingsbericht. Daar komt nog bij dat a-synchrone berichten niet gelijk verwerkt hoeven te worden dus dat een consumer mogelijk heel lang op antwoord zou moeten wachten voordat een identificatie bekend zou zijn.

Juist om de burger/bedrijf/medewerker de identificatie te kunnen geven,  is het synchrone genereerXIdentificatie bericht in het leven geroepen. Doordat de huidige API services synchrone services zijn is deze omweg niet meer nodig. De identificatie wordt gegenereerd op het moment dat het nodig is en wordt in het antwoord bericht direct teruggestuurd.

Dus ook vanuit de businesskant is deze behoefte ingevuld.

**Comment by JohnRooijakkers** [comment]
@michielverhoef Bedank en nog even samenvatten of ik het goed begrijp:

Als ik als gebruiker een document wil maken met een unieke en voor de burger leesbare identificatie, dan moet ik als applicatie:
1. Een enkelvoudig informatie object zonder identificatie en zonder content (inhoud) toevoegen in het DRC
    Ik krijg dan een unieke (en voor de burger leesbare) identificatie terug ... in welk attribuut wordt deze terugegeven?
2. De content (inhoud) van het document genereren en optioneel door de gebruiker laten aanpassen / aanvullen
3.  Het enkelvoudige informatie object met identificatie en met content (inhoud) wijzigen in het DRC

Is dit de beoogde werkwijze? En voor alle zekerheid: de genoemde "identificatie" is geen UID oid, maar een leesbare tekst?

**Comment by michielverhoef** [comment]
@JohnRooijakkers dit klopt helemaal.

De gegenereerde identificatie staat in het attribuut "identificatie". De omschrijving hiervan in de API is als volgt:
_string (Identificatie)   <= 40 characters  Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT._

Dit is dezelfde definitie als van het attribuut informatieobjectidentificatie: https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/informatieobject.informatieobjectidentificatie

In de referentieimplementatie worden momenteel identificaties gegenereerd met een formaat als dit:  "DOCUMENT-2021-7123456790"

Het formaat is bewust niet bepaald in de standaard omdat gemeenten hier ongetwijfeld een eigen mening over hebben. Dit kan en mag natuurlijk, zolang het maar een uinieke identificatie is. En het blijft mogelijk om de identificatie mee te sturen dus bestaande identificaties kunnen overgenomen worden. Dit helpt met migratie van oude documenten.

De uuid komt terug in het attribuut url en is iets heel anders.

**Comment by JohnRooijakkers** [comment]
Top. Hartelijk dank voor de discussie. Werkwijze is me nu duidelijk.

**Comment by JohnRooijakkers** [comment]
PS: Is dit wellicht een werkwijze die opgenomen kan worden in een "Best practices" document?

**Comment by michielverhoef** [comment]
Dat is een goed idee. Er is al eens een aanzet gemaakt voor een handleiding hoe aan de slag te gaan met de API's maar daar staan dit soort dingen (nog) niet in.

**Comment by michielverhoef** [comment]
De vraag is beantwoord, ik sluit het issue.
