### ISSUE TITLE
Als developer wil ik bij een zaakobject van het objecttype "overig" een referentie op kunnen nemen naar een objectdefinitie

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#1871]
zodat als ik het zaakobject terug krijg, van te voren kan zien wat het achterliggende schema is behorende bij het object.

Er zijn al verschillende userstories gemaakt die ditzelfde onderwerp raken. Het gaat om deze userstories:
https://github.com/VNG-Realisatie/gemma-zaken/issues/1864
https://github.com/VNG-Realisatie/gemma-zaken/issues/1848

In deze userstory zal ik de voorgestelde oplossingsrichting beschrijven en zal ik de samenhang met de andere userstories beschrijven. De verschillende userstories vullen elkaar aan en hoeven elkaar niet uit te sluiten.

**Beschrijving van de wens**
Op dit moment kan je bij het creëren van een zaakobject kiezen voor een lijst met objecttypen uit RSGB. Het schema / de definities van deze objecten is reeds bekend, namelijk  zoals deze in RSGB staan. 
Er kan echter ook gekozen worden voor objecttype "overig" wanneer een objecttype niet voorkomt in RSGB. "Overig" kan van alles zijn dus daar is het wel handig om een expliciete verwijzing te kunnen opnemen naar de definitie.

**Voorgestelde oplossingsrichting**
Het opnemen van het attribuut `objectTypeOverigeDefinitie` onder ZAAKOBJECT in de Zaken-API.
In dit veld kan een URL verwijzing opgenomen worden naar een schema/definitie. Dit kan bijvoorbeeld een objecttype beschrijving in de objecttypen-API zijn. 
De zaken-API valideert het gelinkte zaakobject tegen het schema.

Deze aanpassing is weinig complex. Mogelijke complexiteit zit hem met name in de samenhang met eerder genoemde userstories.

**Samenhang met de andere userstories**
 De eerder genoemde userstories beschrijven het kunnen vastleggen van (zaak)objecttypen bij een zaaktype in de catalogi API.
Een handige toevoeging, je kan dan direct zien welke objecten relevant zijn voor een zaak / bij een zaak benodigd zijn. Eventueel zelfs gekoppeld aan een bepaalde status in het proces.
Bij het zaakobjecttype in de catalogi API kan je direct ook een verwijzing naar de definitie / het schema van het objecttype opnemen.  Aan de hand van het zaaktype kan je dan gelijk alle informatie ophalen over de objecttypen die in het proces gebruikt worden.

Waarom dan nog deze userstory?
Het is goed om zoveel mogelijk structuur aan te brengen in het proces en dus ook zaaktypen, het heeft dus de voorkeur om zoveel mogelijk van te voren de relevante objecttypen aan te geven. 
Het is echter niet altijd mogelijk om vooraf alle mogelijke objecttypen vast te leggen bij een zaaktype. Neem bijvoorbeeld een zaaktype "melding openbare ruimte". Een melding kan betrekking hebben op een pand / adres, een prullenbak, lantaarnpaal, een stuk grond, een stuk straat etc. De mogelijke objecttypen bij het zaaktype melding openbare ruimte is dus enorm en onhaalbaar om dat vooraf te definiëren bij het zaaktype.

Het moet dus ook mogelijk zijn om zonder vooraf gedefinieerd objecttype een zaakobject vast te leggen en daarbij het schema aan te passen. 

In het geheel betekent dit dan het volgende:

- Het is wenselijk om in een zaaktype aan te kunnen geven welke objecttypen relevant zijn binnen het zaaktype en wat het bijbehorende schema is.
- Je wilt kunnen aangeven of een objecttype verplicht is (bij de zaak of zelfs een status)
- Het moet echter ook mogelijk zijn om buiten het zaaktype om, een zaakobject te kunnen toevoegen. Er komt dus de mogelijkheid om bij een zaak een zaakobject toe toe wijzen en daarbij een verwijzing naar het relevante schema op te nemen.

De scope van deze userstory is dus de onderste bullet

**impact op standaard**
Als zowel deze als de eerder genoemde userstories worden uitgevoerd, zal er waarschijnlijk geen gedeelte van de informatie die nu bij bij een zaakobject wordt vastgelegd, overbodig worden omdat dit al in de catalogi-API opgenomen zit. Dit moet echter blijken uit de verdere uitwerking van die userstories. 
Wat specifieker gemaakt moet worden is de volgende regel:
![image](https://user-images.githubusercontent.com/39768984/126176719-966f072f-dcaa-4f61-b581-20a91bf94cd1.png)
Dit geldt straks dan niet meer voor elke resource. 

**Voorgestelde implementatie volgorde**
Deze userstory kan uitgevoerd worden voordat de andere meer complexe userstories gerealiseerd zijn

**Comment by rubenvdlinde** [comment]
Hoewel ik denk dat de oplossing prima is een paar kleine opmerkingen:

1. Schema.org kent het concept "thing" wat min of meer neerkomt op ik wil een object maar weet nog niet hellemaal wat. 
2. De vraag is even of je echt extra objecten wilt toestaan (wat een soort gebed zonder eind kan zijn) of wil zegen ik verwacht een object maar weet niet wat (betreft van de melding bijvoorbeeld) in het geval van de melding weet je bijvoorbeeld niet welk van de 350 object je gaat krijgen, maar je weet wel dat je een "betreft " van de melding verwacht. Ik zou dan een wel een definitie in het zaaktype verwachten maar een type beperkingen in de trand van "thing" of null om aan te geven dat elke object op dat zaakObjectOverige toegestaan is.
3. Daarnaast is het best specifiek voor meldingen, ik denk dat het merendeel van de zaaktypen wel degelijke dicht getimmerd zijn, zeker interne zaken. Het lijkt me dus goed om in een zaakType expliciet op te voeren dat het toevoegen van extra objecten toegestaan is (dat lijkt me ook meer in lijn met de gedachte dat een zaak altijd gevalideerd moet worden aan het zaaktype)

Al met al zou ik de casus melding dus liever oplossen met configuratie op niveau van het zaakType, waarbij er twee mogelijkheden moeten worden toegevoegd

1.  Optie om de schema definitie op "alles mag" te zetten (hetzij door thing, het zij door null)
2.  Aangeven hoe vaak een zaakObjectOverige mag voorkomen om een zaak (waarbij null, of 0 dan terugslaat op zo vaak als je wilt)

Daarmee kan nog steeds worden gefaciliteerd dat op meldingen ad infinitum ongedefinieerde objecten kunnen worden ingeschoten maar dan mits zo gedefinieerd. Wat de voorspelbaarheid van zaken ten goede komt en zorgt dat er nog steeds een lat is waarlangs ook de ongedefinieerde objecten kunnen worden gevalideerd.

**Comment by michielverhoef** [comment]
Dat was eigenlijk iets waar ik gisteren ook aan zat te denken: Door een Zaakobjecttype "Overig" aan een Zaaktype te koppelen is het voor dat zaaktype toegestaan nog niet gedefinieerde waarden op te nemen. Punt 3 van de post hierboven.

Daar zijn dan wel #1864 en #1848 voor nodig. In ZaakObjecttype moet dan ook de mogelijkheid komen om "overig" of "thing" (of iets vergelijkbaars) aan te geven.

Wel zou ik dan bij het zaakobject (in de Zaken API) een link naar het schema van dat object willen kunnen opnemen, bijvoorbeeld omdat het iets is wat in een objectenregistratie staat. Want weliswaar weet ik vantevoren nog niet wat ik precies in ga voeren (thing) maar zodra ik het in ga voeren weet ik dat wel.

**Comment by CMasselink** [comment]
Even een snelle reactie tussen de afspraken door: 
Aansluitend op wat Michiel in zijn laatste alinea zegt, heeft dan volgens mij een attribuut als `objectTypeOverigeDefinitie` nog steeds waarde / zin al eerste stap en sluit het de hierboven beschreven mechanismen niet uit.

**Comment by rubenvdlinde** [comment]
@CMasselink eens, volgens mij zijn we hier gewoon naar een totaal oplossing aan het itereren. 

Overigens is krijgen we nu wel een dubbele manier van definiëren, namenlijk `objectType ` en `objectTypeOverigeDefinitie` dat leid tot gekke onderlinge verbanden van proporties en langzame groei van objecten.

Wat mij betreft zou het mooier zijn om 
- `objectType `
- `objectTypeOverige`
- `objectTypeOverigeDefinitie` 

Te laten vervallen, is namenlijk gewoon een WRC recommandatie voor dit soort relaties [RDFa](https://www.w3.org/TR/rdfa-primer/). Globale gedachte daarbij is dat je niet in je api specs lijsten gaat maken (wat nu hier wel gebeurd is) omdat dat in de praktijk onwerkbaar is (komen we nu via de objecten API ook achter). In lijn met de 'thing' definitie verwacht je dat een zaakObject een 'additionalType' heeft (wat we binnen ZGW nu objectType noemen) en dat dit ALTIJD een externe (URL) verwijzing is naar een schema dat buiten de API gedefineerd is, dus ook voor adres, besluit, buurt etc.

Dat betekend dan dus automatisch dat de selectie lijst in ZGW vervalt en er op VNG/Rijks niveau een schema libary moet worden ingericht waar naartoe kan worden verwezen (we kunnen trouwens ook gewoon schema.org extenden dat is daarvoor bedacht) . Dat ligt ook meer in lijn met de beweging die we bij de objecten API zien, en internationaal (centraal register en centrale definite van objecten). Het is ook plat gezegd is het niet aan ZGW om lijstjes te definiëren van algemene objecten (wat nu wel gebeurd).  

De huidige manier van werken leid dan ook tot gekke gevallen, zo staan in de standaard voor ZGW bijvoorbeeld objecten die nog niet gestandaardiseerd zijn, en het standaardiseren van andere API's zou dan weer tot een aanpassing op de ZGW standaard  en daarop gebaseerde producten moeten leiden. In mijn beleving kunnen we moeilijk aan alle zaaksysteem leveranciers vragen hun pakket bij te werken iedere keer als de VNG een willekeurige API standaardiseert.

**Comment by michielverhoef** [comment]
@rubenvdlinde begrijp ik maar dat is voor een major versie, eerst maar eens zorgen dat we de eerste stap kunnen doen, nl aangeven welk schema er bij een overigObjecttype hoort.

**Comment by rubenvdlinde** [comment]
@michielverhoef kunnen we hem dan taggen voor milestone  Zaken API 2.0? 

Overigens had ik de gedachte naar aanleiding van de vorige ZGW meeting dat we naar een major versie aan het toewerken waren. Veel van dit soort dingen zijn er randvoorwaardelijk voor een goed/überhaupt werkend GZAK en wat we nu in het veld zien is dat zaak afhandel applicaties aanvullende data in koppel en configuratie tabellen opslaan. Waarmee we defacto toch weer in de silo wereld terecht komen dat de zaken alleen afgehandeld kunnen worden door de applicatie die ze heeft aangemaakt. 

Als we er in de praktijk achter komen dat we een Major moeten gaan voorbereiden stel ik voor dat we dat gewoon gaan doen.

**Comment by michielverhoef** [comment]
@rubenvdlinde Deze userstory gaat over het toevoegen van een attribuut om het schema van het object op te kunnen halen. Dat gaan we meenemen in Zaken 1.2 die heel binnenkort (eind augustus) uitkomt.

Maar als je jouw commentaar opneemt in een nieuwe user story taggen we die met Zaken API 2.0. De Milestone is er inmiddels.

Ook bij de vorige meeting waren we nog niet naar een major versie aan het toewerken overigens. Ik zie alleen veel userstories die te maken hebben met niet-volledig geimplementeerd RGBZ en ImZTC (zowel resources als attributen). Als we dat in 1 keer opnemen is het weliswaar een vrij grote major maar wel iets wat het makkelijkste in 1 keer kan. Dat is voor mij ook makkelijker :-)

**Comment by sergei-maertens** [comment]
@michielverhoef de PR voor `objectTypeDefinitieOverige` is gemaakt, zie https://github.com/VNG-Realisatie/zaken-api/pull/203
