### ISSUE TITLE
Als informatiebeheerder wil ik een informatieobjecttype verplicht kunnen stellen bij een resultaattype

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#1876]
...zodat ik minder achteraf hoef te controleren of het dossier volledig is.

Bijvoorbeeld, bij een vergunning-zaak moet er een een 'besluit' in het zaakdossier zitten, wanneer het resultaat 'verleend' of 'afgewezen' is. Echter, wanneer het resultaat 'niet ontvankelijk' of 'ingetrokken' is, dan zal er geen besluit in het zaakdossier zitten.

Mogelijk wil een gemeente een informatieobjecttype 'vergunning' hanteren. Dan zal een informatieobject van dit type alleen verplicht zijn bij het resultaattype 'verleend'.

Dit vraagt m.i. om een wijziging van https://catalogi-api.vng.cloud/api/v1/schema/#tag/zaaktype-informatieobjecttypen .

**Comment by michielverhoef** [comment]
Dit is al opgenomen in ImZTC 2.2: https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/relatieklasse/zaak-informatieobject-type in de vorm van van Relatiesoort RESULTAATTYPE heeft verplichte ZAAK-INFORMATIEOBJECT-TYPE
https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/relatiesoort/resultaattype.heeft_verplichte_zaak-informatieobject-type 

In milestone Catalogi API 1.2 (https://github.com/VNG-Realisatie/gemma-zaken/milestone/17)  is opgenomen om in de Catalogi API het volledige ImZTC op te nemen, inclusief deze relatie.

**Comment by michielverhoef** [comment]
@SonnyBA Dit is relatie https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/relatiesoort/resultaattype.heeft_verplichte_zaak-informatieobject-type

Is ook onderdeel van #1847

**Comment by michielverhoef** [comment]
https://catalogi-api.test.vng.cloud/api/v1/schema/#operation/resultaattype_create

Het is nu mogelijk om bij een resultaattype aan te geven welk(e) informatieobjecttype(n) verplicht zijn.
