### ISSUE TITLE
Als ontwikkelaar wil ik kunnen zien in welke catalogus een type is opgenomen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1879]
...zodat ik kan controleren of ik het juiste type uit de juiste catalogus gebruik.

Op dit moment kan ik van een aantal typen niet opvragen in welke catalogus deze opgenomen zijn. Denk aan Roltype, Statustype, Resultaattype etc. Omdat ik ook niet kan filteren op de Catalogus en ik vanuit de Catalogus resource niet kan zien welke typen (anders dan Zaaktype, Informatieobjecttype en Besluittype) in de bewuste Catalogus zitten kan ik nooit controleren of een dergelijk type in de juiste catalogus opgenomen is. Volgens ZTC-013 zou dit wel moeten: https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index#ztc-013 

In elke resource moet dus opgenomen worden in welke Catalogus deze opgenomen is. Dit moet ook een filter worden.

**Comment by joeribekker** [comment]
@michielverhoef een statustype, eigenschap, etc. zitten allemaal onder een zaaktype, die weer aan een catalogus hangt.

Welk nut heeft het om te zien welke statustypen er allemaal in een catalogus zitten? De statustypen zijn immers niet generiek bruikbaar in meerdere zaaktypen. Elke statustype is uniek per zaaktype (ook al hebben de statustypen vaak dezelfde naam in meerdere zaaktypen).

Regel ZTC-013 was dus impliciet al geregeld. Ik zie ook geen schade in deze toevoeging dus ik maak er geen nieuw issue verder voor aan, maar wel even benieuwd wat de achterliggende reden was.
