### ISSUE TITLE
Formaat veld inn nnp id

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/gemma-zaken#1885]
Vraag vanuit een gemeente:

> Wanneer we een niet natuurlijk persoon/vestiging willen wegschrijven in OpenZaak lopen we tegen het probleem aan dat we nergens het KVK-nummer kunnen wegschrijven. Volgens ons is dit het veld inn nnp id heeft een verplichte lengte van N9 terwijl er in de specificatie staat max 9. Onderwater zien we btw dat dit RSIN moet zijn. Maar de definitie is: Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON, dit zou wat ons betreft een kvk-nummer kunnen zijn. Deze heeft echter soms maar 8 cijfers. Klopt de lengte of niet?

Ik heb dit verder uitgezocht en zowel OpenZaak als de ZGW zaken-api maken onderhuidsgebruik van een RSINField, wat stricter is dan wat de API specificatie aangeeft (namelijk een string met lengte <= 9):

![2021-09-13_22-30](https://user-images.githubusercontent.com/226839/133152582-9046d1ef-2fe2-424f-839f-dec351cd8949.png)

en: https://github.com/VNG-Realisatie/zaken-api/blob/637105368b42e06bd42da4e0ba25156f1e4012ad/src/zrc/datamodel/models/betrokkene.py#L115

Ben jij het ermee eens dat de definitie andere vormen van identificatie toestaat naast RSIN voor niet-natuurlijke personen, en dat we deze restrictie moeten loslaten?

**Comment by michielverhoef** [comment]
Dit is al een oudere discussie. 
In het RGBZ (ook RGBZ2) is het identificerend attribuut een RSIN.  Dit is op zich niet heel handig want voor eenmanszaken werkt dit niet, die krijgen immers geen RSIN vanuit de KvK.
https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/niet-natuurlijk_persoon.rsin

Loslaten van een RSIN formaat is in dit geval niet de oplossing, de richting zoals beschreven in #656 wel.

**Comment by alextreme** [comment]
Dank Michiel voor het verwijzen naar de discussie. Prima, in dat geval sluit ik deze issue. Zodra er uitsluitsel is over #656 dan kunnen we aan de slag.
