### ISSUE TITLE
Als gebruiker van de Zaken API zou ik graag willen weten hoe ik bij een GET /zaken de resultaten kan sorteren

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/gemma-zaken#1892]
...zodat ik in mijn API client de resultaten niet zelf hoef te sorteren en daardoor efficiënt gebruik kan maken van de /zaken endpoint

Momenteel ondersteunt GET /zaken de 'ordering' parameter. Echter het is vanuit de OpenAPI specificatie nog erg vaag wat ermee kan: 'Which field to use when ordering the results'.

Onduidelijk is:
1) Welke velden ik kan meegeven
2) Of ik ook meerdere velden kan meegeven
3) Wat de gebruikte volgorde is (ascending, decending)

Concreet betekent het dat elke Zaken API client zelf moet sorteren. Bij langere lijsten zaken betekent het dat alle zaken eerst opgehaald moeten worden om daarna zelf de volgorde te bepalen.

**1) Welke velden ik kan meegeven**

Vanuit de code hebben we kunnen afleiden dat momenteel het alleen mogelijk is om op 'startdatum' te sorteren.

Mijn voorstel is om dit uit te breiden naar de volgende velden, en de toegestane velden expliciet op te nemen in de OpenAPI specificatie: startdatum, einddatum, registratiedatum, publicatiedatum

Rationale hiervan is dat je in de regel alleen op datum of datumtijd velden sorteert. Op strings en enums wordt in de regel vooral gefilterd en gezocht (al zou je identificatie en andere string-velden alfabetisch kunnen sorteren, ik zie hier de meerwaarde niet echt van).

Het willen sorteren op de additionele datumvelden (archiefactiedatum, einddatumGepland, uiterlijkeEinddatumAfdoening, laatsteBetaaldatum) lijkt mij minder vanzelfsprekend, hier konden wij geen concrete casus bij bedenken maar ze zouden toegevoegd kunnen worden mocht je hier consistent in willen zijn.

**2) Of ik ook meerdere velden kan meegeven + 3) Wat de gebruikte volgorde is (ascending, decending)**

Concreet hebben we een casus bij Den Haag waarbij we eerst de lopende zaken (dus zonder einddatum) zouden willen kunnen krijgen, en daarna de afgeronde zaken (nieuwste eerst).

Ons voorstel hiervoor zou zijn dat we dit als volgt meegeven met de ordering parameter:

/zaken?ordering=-einddatum,-startdatum

Hiermee zou je eerst de zaken zonder einddatum (einddatum=null) krijgen die op startdatum zijn gesorteerd (nieuwste eerst), en daarna de afgeronde zaken (nieuwste eerst)

Dit is in lijn met hoe de 'sort' parameter werkt in de JSON:API specificatie: https://jsonapi.org/format/#fetching-sorting . Dus de toegestane velden mogen comma-separated worden meegegeven, zijn standaard laagste (oudste) waarde eerst (ascending), en eventueel met een min ervoor om aan te geven dat de hoogste (nieuwste) waarde het eerst is (descending).

De combinatie van additionele en meerdere velden mee kunnen geven en de richting te kunnen bepalen geeft een stuk meer mogelijkheden om direct via de API te kunnen sorteren.

Deze issue raakt deels #781 waarin wordt gekeken naar of de datum-velden aangepast dienen te worden naar datum-tijd velden. Deze issue staat er echter los van aangezien de wens met name is het expliciet maken hoe met 'ordering' omgegaan dient te worden: de ZGW standaard laat dit momenteel eigenlijk vrij.

Het viel ons ook op dat de 'ordering' parameter ontbrak bij de /enkelvoudigeinformatieobjecten in de Documenten API. Het ook daar toevoegen van deze parameter zou een mogelijke vervolgstap zijn, maar valt buiten deze user story in mijn ogen.

**Comment by michielverhoef** [comment]
In  https://zaken-api.test.vng.cloud/api/v1/schema/#operation/zaak_list is nu de volgende enumeratie opgenomen voor waarden voor de parameter ordering:

- startdatum 
- startdatum 
- einddatum 
- -einddatum 
- publicatiedatum 
- -publicatiedatum 
- archiefactiedatum

Mochten er nog meer waarden nodig zijn, graag een ticket hiervoor aanmaken.
