### ISSUE TITLE
Als gemeente Den Haag wil ik kunnen vastleggen dat een klant een document heeft geüpload tijdens een contactmoment

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#1894]
...aan te vullen

Document hangt aan zaak, maar het is nodig te kunnen achterhalen dat het door de klant in het kader van een specifiek contactmoment is ingediend.

**Comment by michielverhoef** [comment]
Volgens mij kan dit al. In de Contactmomenten API kennen we de resource ObjectContactmoment: https://contactmomenten-api.vng.cloud/api/v1/schema/#operation/objectcontactmoment_read

Vanuit de Documenten API kennen de we de resource ObjectInformatieobject: https://documenten-api.vng.cloud/api/v1/schema/#operation/objectinformatieobject_read 

Hiermee kan deze relatie gelegd worden lijkt me?

**Comment by hdksi** [comment]
Of dit wenselijk en nodig is, is afhankelijk van de definitie van 'contactmoment'.
