### ISSUE TITLE
Als behandelaar wil ik na het vastleggen van een besluit de zaakgegevens kunnen aanvullen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#19]
zodat het zaakdossier volledig gemaakt wordt

**Comment by ehotting** [comment]
@michielverhoef Heb je hier een concrete user story bij?

**Comment by Hugo-ter-Doest** [comment]
@michielverhoef Kun je deze user story concreet maken met welke gegevens van de zaak je wilt kunnen bijwerken.

**Comment by michielverhoef** [comment]
Of dit nodig is hangt af van de workflow die door gemeenten gehanteerd wordt. Normaal gesproken zou je zeggen dat wanneer een besluit genomen en vastgelegd is de zaak afgehandeld is. Is dat ook daadwerkelijk zo? Wordt na het vastleggen van een besluit ook de status van de zaak aangepast naar een eindstatus?

Als dat niet zo is kan deze US als niet verzonden beschouwd worden.

**Comment by TCIMEddy** [comment]
@CMasselink @BoerBas @MarcelMoerman @RvdKlip @RitaBerghuis @EdwinCoster Hebben jullie concreet voorbeeld van bovenstaande user story?

**Comment by CMasselink** [comment]
In Utrecht komt het voor dat er na het nemen van een besluit nog handelingen in de zaak plaatsvinden. Besluit is bij ons dus niet altijd de laatste status.

**Comment by Hugo-ter-Doest** [comment]
En je kunt ook meerdere besluiten in een zaak nemen... Dus statuswijzigingen en afsluiten van de zaak moet je los zien van besluiten.
