### ISSUE TITLE
Webhook bij abonnement onterecht niet geaccepteerd

### ISSUE THREAD

**Issue by adgerrits** [VNG-Realisatie/gemma-zaken#1903]
Bij het doorlopen van de [Tutorial notificeren](https://vng-realisatie.github.io/gemma-zaken/ontwikkelaars/handleidingen-en-tutorials/notificeren) gaat er bij het nemen van een abonnement iets mis als je webhook.site gebruikt (zoals beschreven). Er wordt door de NRC een POST gedaan die werkt (te zien bij webhook.site) maar toch volgt er een 400-melding: "De opgegeven callback URL kan geen notificaties ontvangen."
(nog even getest met webhooktest.com maar dat levert een 'De opgegeven callback URL is niet beveiligd met autorisatie.' melding op waaruit ik concludeer dat er ergens op wordt gecontroleerd maar is niet helder uit de documenatie wat dan). 

Ik gebruik https://notificaties-api.vng.cloud/api/v1 en heb alle rechten.

**Comment by adgerrits** [comment]
Geen idee of de documentatie is aangepast maar ik zeg: tijd om te closen. Vandaag trouwens bij apilab notificatie-api zelfde 'probleem'. Waarbij sommige leveranciers ook alleen een 200 konden retourneren dusndoor Sonny de 204-eis even uitgezet.

**Comment by michielverhoef** [comment]
Als ik de reactie van Ad zo lees is het probleem nog steeds actueel en is er zelfs een, denk ik, onterechte, aanpassing in de referentie implementatie gedaan omdat bepaalde leveranciers niet aan de standaard kunnen voldoen.

**Comment by HenriKorver** [comment]
Tijdens de API Lab is de 204-eis even tijdelijk uitgezet zodat leveranciers hun afnemende applicaties niet hoefden aan te passen (dat zou zonde zijn geweest van hun tijd), zie https://github.com/VNG-Realisatie/notificatieservices/issues/103#issuecomment-1156437373.
