### ISSUE TITLE
Als scrumteam en teamlid wil ik de pro's en con's van Scrum voor de ontwikkeling van standaarden op een rijtje zetten

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#192]
...zodat [vul aan].

**Definition of done**

- [x] Als scrumteam hebben we aandacht besteed aan de geschiktheid en valkuilen van Scrum voor ontwikkeling van standaarden versus software

- [ ] 

**Taken**
- [x] organiseren (discussie)bijeenkomst
- [x] vastleggen resultaten

**Comment by jgortmaker1** [comment]
ja, is prima. maar het resultaat van deze user story is een inzicht dat langzamerhand "vanzelf" tot ons moet komen...
dus of we het kunnen inplannen in een sprint en iemand aan kunnen toewijzen, dat weet ik nog niet helemaal..

**Comment by TCIMEddy** [comment]
@jgortmaker1 Maken we vorderingen op dit punt? Kan ik deze voor nu op close zetten?

**Comment by TCIMEddy** [comment]
Volgens mij hebben we hier veel aandacht aan besteed. Wel nog powerpoint toegevoegd met verzameling sheets.
