### ISSUE TITLE
Als gemeente wil ik een InformatieObjectType kunnen relateren aan bestaande versies van een zaaktype

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1923]
...zodat we de mogelijkheid hebben om bij lopende zaken nieuwe IOT's toe te voegen die voor de behandeling en registratie relevant zijn

Omdat tijdens de behandeling sprake kan zijn van voortschrijdend inzicht of gewijzigde omstandigheden. 

Implementatie:
- mogelijkheid om via een speciaal request bestaande versie aan te passen met bijvoorbeeld een extra IOT waarbij een startdatum opgegeven kan worden.
- Verzoek "Voeg IOT toe aan alle versies sinds 1-06-2021 van Zaaktype X"

**Comment by michielverhoef** [comment]
Het is niet mogelijk **de versie van het zaaktype** aan te passen wanneer het in gebruik is. Een zaak is van een bepaalde versie van het zaaktype zoals geldig ten tijde van het aanmaken van de zaak. Dit om te voorkomen dat tijdens het afhandelen van een zaak achteraf delen van het proces niet correct afgehandeld zijn etc. Een beetje achteraf de spelregels aanpassen.

Bovendien, hoe ga je om met reeds afgesloten zaken van dat zaaktype? Die zijn ineens niet meer geldig volgens het zaaktype. Dingen als archivering etc. gaan dan ongetwijfeld ook niet goed.

Voortschrijdend inzicht of gewijzigde omstandigheden leiden tot een nieuwe versie van een zaaktype. De enige zuivere manier om dit op te lossen is de zaak afsluiten en opnieuw aanmaken met het gewijzigde zaaktype.

@hdksi @ArjanKloosterboer of sla ik de plank mis?

**Comment by MaartenRutten** [comment]
Er worden nieuwe gegevens toegevoegd. Dat blijft zonder gevolgen voor de afgesloten zaken. 
De praktijk is dat een gemeente er niet altijd in slaagt om direct bij het in productie nemen van een zaaktype compleet en volledig te zijn (nog afgezien van de wijzigende omstandigheden). 
Tijdens de behandeling blijkt een IOT te ontbreken of zelfs een Resultaattype (zie https://github.com/VNG-Realisatie/gemma-zaken/issues/1924 ).  

Ik snap dat het vanuit automatiseringsoogpunt niet makkelijk en wenselijk is maar als leverancier wil ik wel de mogelijkheid om via een gestandaardiseerd verzoek aan de klantwens tegemoet te komen. 

In wat bredere context zou de API mogelijkheden moeten bieden om fouten te herstellen. Als bijvoorbeeld een verkeerde bewaartermijn is ingegeven bij een Resultaattype dan wil de klant de mogelijkheid om dit ook in bestaande en gebruikte zaaktype versies te corrigeren.

**Comment by michielverhoef** [comment]
Opgelost met #2038

**Comment by michielverhoef** [comment]
Het kan voorkomen dat een versie van een object in gebruik is en fouten bevat. Normaal gesproken moet dan van dat object een nieuwe versie gemaakt worden maar die wijzigingen hebben dan geen effect op zaken, informatieobjecten of besluiten die reeds aangemaakt zijn. Daarom is het mogelijk om onder bepaalde omstandigheden correcties aan te brengen. Dit kan dan met een expliciete scope: geforceerd-bijwerken.
De voorwaarden waaronder een correctie op een objecttype uitgevoerd mag worden zijn:

    * De wijziging is een uitbreiding, bijvoorbeeld het toevoegen van een optioneel informatieobjecttype aan een zaaktype of een statustype aan het eind van de reeds geconfigureerde statustypen aan een zaaktype. Er mogen dus geen releaties of gerelateerde objecten verwijderd worden.
    * De wijziging is een uitbreiding, bijvoorbeeld het toevoegen van een trefwoord aan een Informatieobjecttype
    * Zaken van het zaaktype blijven nog steeds geldig en kunnen nog steeds afgehandeld worden. Met andere woorden, de afhandeling van deze zaken is nog steeds geldig.
    * Besluiten van het Besluittype blijven nog steeds geldig.
    * Informatieobjecten van het Informatieobjecttype blijven nog steeds geldig.

**Comment by michielverhoef** [comment]
Logica bij validatie van [ztc-010](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index#ztc-010):
Aanmaken (POST) of bewerken (PATCH/PUT) van een gerelateerd objecttype (Statustype etc.)
Wanneer het gerelateerde Zaaktype reeds gepubliceerd is (concept=false) dan mag de POST/PATCH/PUT operatie alleen uitgevoerd worden met een [correctie](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index#correctie)

Dit geldt voor:
- Statustype
- Roltype
- Resultaattype
- Eigenschap
- Zaakobjecttype

Het maken of aanpassen van een relatieklasse ZaaktypeInformatieobjecttype waarbij zowel Zaaktype als Informatieobjecttype gepubliceerd zijn (concept=false) is toegestaan met een [correctie](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index#correctie)

**Comment by michielverhoef** [comment]
Opgelost met https://github.com/VNG-Realisatie/catalogi-api/pull/146
