### ISSUE TITLE
Als gemeente wil ik een nieuw Resultaattype kunnen toevoegen aan lopende zaken

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1924]
...zodat de behandelaar kan kiezen uit de relevante en actuele Resultaten
omdat na de registratie van de zaak er binnen de organisatie besluiten zijn genomen die hebben geleid tot een nieuw Resultaattype.

Voorbeeld:
Tijdens bespreking in de raad wordt besloten dat een subsidie ook gedeeltelijk toegekend kan worden. Het nieuwe Resultaat dat ook voor de geregistreerde subsidieaanvragen toegevoegd moet worden is 'Gedeeltelijk toegekend'.

Implementatie
- een speciaal verzoek waarmee bestaande zaaktype versies aangepast kunnen worden
- waarbij een datum  aangeeft vanaf welke datum de versies van het zaaktype aangepast moeten worden

**Comment by michielverhoef** [comment]
Hier geldt hetzelfde voor als voor #1923 

Om mijn reactie van daar te herhalen:
Het is niet mogelijk de versie van het zaaktype aan te passen wanneer het in gebruik is. Een zaak is van een bepaalde versie van het zaaktype zoals geldig ten tijde van het aanmaken van de zaak. Dit om te voorkomen dat tijdens het afhandelen van een zaak achteraf delen van het proces niet correct afgehandeld zijn etc.  Dit is een beetje als achteraf de spelregels aanpassen.

Bovendien, hoe ga je om met reeds afgesloten zaken van dat zaaktype? Die zijn ineens niet meer geldig volgens het zaaktype. Dingen als archivering etc. gaan dan ongetwijfeld ook niet goed.

Voortschrijdend inzicht of gewijzigde omstandigheden leiden tot een nieuwe versie van een zaaktype. De enige zuivere manier om dit op te lossen is de zaak afsluiten en opnieuw aanmaken met het gewijzigde zaaktype.

@hdksi @ArjanKloosterboer of sla ik de plank mis?

**Comment by michielverhoef** [comment]
Is opgelost met correcties
