### ISSUE TITLE
Als Consumer wil ik weten of registratiedatum of startdatum van een zaak bepaalt welke versie van het gekoppelde zaaktype gebruikt gaat worden

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1925]
De vraag is of de standaard bepaalt welke datum gebruikt moet/zal worden.

De huidige praktijk is dat de Startdatum bepalend is voor de keuze van de versie van het zaaktype. 
De ontvangstdatum van de zaak wordt doorgaans de startdatum van de zaak.

**Comment by michielverhoef** [comment]
Een zaak wordt aangemaakt (zaak.registratiedatum) met de op dat moment geldende/actuele versie van het zaaktype. Wanneer een zaak aangemaakt wordt van een versie van het zaaktype die reeds een datumeindGeldigheid (in het verleden) heeft is dat niet toegestaan, die versie van het zaaktype is immers niet meer geldig.

Nu kun je een aardige boom opzetten over of een zaak gestart wordt op de datum dat hij aangemaakt wordt. de ontvangstdatum is de registratiedatum. Die datum bepaalt ook de keuze van de versie van het zaaktype.

Het zou nl. een beetje vreemd zijn wanneer ik op een vrijdag een aanvraag doe die geldig is volgens de dan geldende versie van het zaaktype. Jammer genoeg wordt niet automatisch een zaak aangemaakt dus wanneer maandag een medewerker de aanvraag beoordeelt en een nieuwe versie van het zaaktype ingegaan is zou het kunnen zijn dat mijn aanvraag als niet geldig wordt beschouwd terwijl deze dat wel was op met moment van indienen.

De startdatum van de zaak is het moment waarop de zaak in behandeling genomen wordt. Die datum bepaalt echter niet de keuze van de versie van het zaaktype, die keuze is al gemaakt bij het aanmaken van de zaak.

Ik bestrijd niet dat de huidige praktijk is zoals beschreven door @MaartenRutten maar volgens mij klopt het niet.
