### ISSUE TITLE
ZRC component 500 error na installatie

### ISSUE THREAD

**Issue by Dahlhaus** [VNG-Realisatie/gemma-zaken#1938]
# Bug

Na installatie van gemma-zaken op locale machine is het zrc component niet beschikbaar in de browser (500 error). Na aanpassing van ' ALLOWED_HOSTS= * ' base.py (suggestie van Sergei), was front end wel beschikbaar met loginscherm.
Na inloggen krijg ik alsnog een zwart scherm met error.  

De componenten heb ik lokaal gehost op mijn Macbook. Ik heb zelfde installatie ook uitgevoerd in Parrallels omgeving met schone  Windows installatie met hetzelfde resultaat. 

Zie bijgaande log zrc web
[zrc_web_log.txt](https://github.com/VNG-Realisatie/gemma-zaken/files/7968924/zrc_web_log.txt)

**Comment by michielverhoef** [comment]
Bedankt voor deze update. Onze ontwikkelaar is hier mee bezig deze week en ik geef dit direct aan hem door.

**Comment by michielverhoef** [comment]
Als het goed is is het probleem nu opgelost met https://github.com/VNG-Realisatie/gemma-zaken/pull/1940

**Comment by Dahlhaus** [comment]
Yes! Ik heb het getest en het werkt! Merci!
