### ISSUE TITLE
Als zaakbehandelaar wil ik een zaak kunnen opschorten en verdagen zodat de doorlooptijden van een zaak worden aangepast

### ISSUE THREAD

**Issue by RoyBuis** [VNG-Realisatie/gemma-zaken#1953]
De volgende functionaliteit willen wij in een zaakafhandelcomponent toepassen. Is dit mogelijk vanuit de ZGW API's of verwachten die ander gedrag?

**Als een zaakbehandelaar een zaak met x aantal dagen wil opschorten dan verwachten we het volgende gedrag:**

- indicatie opschorting wordt op true gezet
- reden opschorting wordt ingevuld
- de einddatum gepland wordt x aantal dagen naar achter geschoven
- de uiterlijke einddatum afdoening wordt x aantal dagen naar achter geschoven
- als de opschorting wordt opgeheven (zaak wordt hervat) dan wordt het daadwerkelijke aantal dagen dat de opschorting geduurd heeft opgeteld bij de oorspronkelijke einddatum gepland en uiterlijke einddatum afdoening

**Als een zaakbehandelaar een zaak met x aantal dagen wil verdagen dan verwachten we het volgende gedrag:**
- reden verdagen wordt ingevuld
- de einddatum gepland wordt x aantal dagen naar achter geschoven
- de uiterlijke einddatum afdoening wordt x aantal dagen naar achter geschoven

**Comment by Hugo-ter-Doest** [comment]
In de Zaken API werkt opschorten met een gegevensgroep `opschorting` die bestaat uit `indicatie` en `reden`. Je kunt niet het aantal dagen van de opschorting zetten. De zaak is opgeschort of niet.

Verdagen heet verlengen in de Zaken API. Daar is ook een gegevensgroep voor: `verlenging`. Die bevat een `reden` en een `duur`. Ik kon niet ontdekken of de API de `einddatumGepland` en `uiterlijkeEinddatumAfdoening` bijwerkt als verlenging wordt gevuld.

@michielverhoef kun jij even meelezen en weet jij of de einddatums (moeten) worden bijgewerkt bij een verlenging? D.w.z. of dat vereist gedrag is van de API. Dank alvast!

**Comment by michielverhoef** [comment]
@Hugo-ter-Doest  Wat ik zo 1,2,3 zie is dat momenteel einddatumGepland en uiterlijkeEinddatumAfdoening niet bijgewerkt worden.

Op zich zou ik het wel logisch vinden om dit wel te verwachten dat de API dit doet.  Is het wat om dit te bespreken in de functionele gebruikersgroep as. donderdag?

**Comment by Hugo-ter-Doest** [comment]
Ik kan er donderdag a.s. niet bij zijn. Eventueel een volgende keer kan ik het wel toelichten.

Het is al als een user story geformuleerd. We zouden het als user story op de backlog kunnen zetten.

**Comment by michielverhoef** [comment]
De user story staat nu op de backlog.  Op zich vind ik het voorgestelde gedrag wel logisch en te verwachten.

**Comment by MNIJ** [comment]
Het beschreven gedrag is inderdaad logisch. Maar is het logisch dat de ZRC (Zaak Registratie Component) dit doet of de Zaak Afhandel Component?

Correcte termijnberekening is ontzettend belangrijk voor zaakafhandeling, omdat er juridische consequenties aan zitten. Het is daarom ook noodzakelijk dat de verantwoordelijkheid daarvoor in één component zit, want als meerdere componenten onafhankelijk van elkaar business logica op deze velden gaan toepassen, gaat de berekening ongetwijfeld mis.

Op dit moment doet de ZRC helemaal niets met termijnberekening, de velden _einddatumGepland_ en _uiterlijkeEinddatumAfdoening_ zijn in de ZRC volledig vrij in te vullen. Ze zijn niet eens verplicht. Dat legt dus de verantwoordelijkheid om die velden correct te vullen en bij te werken bij de afhandelcomponent.

En voor correcte termijnberekening in alle omstandigheden is er veel meer nodig dan alleen de datums herberekenen bij opschorten en verlengen, het is dus zeer onverstandig om alleen dat in de ZRC op te nemen. En aangezien ik niet zie hoe een generieke ZRC ooit alle logica kan bevatten voor correcte termijnberekening in alle gevallen, lijkt het me verstandig om die verantwoordelijkheid dan dus ook volledig bij de afhandelcomponent te laten.
Zo niet, dan moet er volledig in ZRC uitgewerkt worden hoe termijnen berekend moeten worden en moeten de velden _einddatumGepland_ en _uiterlijkeEinddatumAfdoening_ niet meer direct aanpasbaar zijn maar ook echt alleen via automatische berekening gevuld worden.

**Comment by PaulaRuijter** [comment]
Houdt bij de ontwikkeling er ook rekening mee dat opschorting meerdere keren per zaak kan worden gedaan.
