### ISSUE TITLE
Heeft de Catalogi beheerder de mogelijkheid om een Zaaktype te definiëren/publiceren met een begindatum/einddatum in de toekomst?

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#1954]
Scenario:
- beheerder is bezig om een zaaktype te definiëren die per 1-9-2022 gebruikt gaat worden en per 31-12-2022 zal vervallen
- gedurende het proces van definiëren wordt het zaaktype verschillende keren gepubliceerd

Naar mijn idee is er verschil tussen geldigheidsdatum en publicatie- cq versiedatum.
In bovenstaand voorbeeld is de laatste versiedatum ergens in juli 2022. 
Maar het zaaktype kan pas per 1-9 door de organisatie gebruikt worden.

**Comment by michielverhoef** [comment]
Een goede vraag. Wel vraag ik me af waarom het zaaktype tijdens het proces van definiëren gepubliceerd wordt? Als het nog niet klaar is zou ik een zaaktype niet publiceren. Publiceren is niet hetzelfde als committen in een versiebeheer systeem.

Er is inderdaad een verschil tussen een geldighiedsdatum en een versiedatum. In de huidige beschrijving van het historiemodel staat beschreven dat de datum begin geldigheid van de eerste versie van het zaaktype gelijk is aan de versiedatum van die eerste versie.  Maar dat is nog met de "oude" betekenis van datum begin geldigheid (nl. geboorte datum van het object, niet van de versie). 

In het technisch gebruikersoverleg hebben we afgesproken datum begin geldigheid en datum eind geldigheid te gebruiken zoals nu in de Catalogi API ook al gebeurt, nl. de begin en einddatum (t/m) van de versie van het object.

Ook is afgesproken de attributen datum begin object en datum einde object toe te voegen zodat ook duidelijk is wanneer het object is "geboren" en/of "overleden". Dit kan ook afgeleid worden door de eerste respectievelijk laatste versie op te halen maar gemak dient de mens en het sluit aan op het ImZTC (waar deze gegevens ook in opgenomen zijn).

Je zou dit op kunnen lossen door datum begin object op 1-9-2022 te zetten maar dat is wel apart aangezien datum begin geldigheid (van de versie) op een veel eerdere datum staat. 

Wat deze situatie latig maakt is het publiceren voordat het zaaktype in gebruik genomen wordt. Een veel betere aanpak zou denk ik zijn het zaaktype pas te publiceren kort voordat het  in gebruik genomen wordt en het tot die tijd in concept te laten staan. 

Het doel van publiceren van een zaaktype is aangeven dat zaken van het zaaktype aangemaakt kunnen worden.  Dus wanneer een zaaktype nog niet gebruikt moet kunnen worden zou ik het ook niet publiceren.  Daarmee voorkom je heel dit probleem.

**Comment by michielverhoef** [comment]
Een zaaktype wat reeds gepubliceerd is kan gecorrigeerd worden om eventuele fouten te repareren zodat reeds lopende zaken correct afgehandeld kunnen worden. 

Hier zijn echter wel eisen aan verbonden. Zo mag het alleen uitbreidingen betreffen die reeds lopende zaken niet kunnen verstoren. Bijvoorbeeld het toevoegen van een status aan het einde (hoogste volgnummer) of het toevoegen van zaakinformatieobjecten. 
Zie ook #1923 

De vraag is of je een gepubliceerd zaaktype wat nog niet actief is niet volledig zou moeten mogen wijzigen. Er zijn geen zaken die hier last van kunnen hebben. Aan de andere kant, wanneer een zaaktype dusdanige fouten bevat dat het niet correct is en de wijzigingen zijn ingrijpend zou ik verwachten dat het haast eenvoudiger is het foute, niet geldige zaaktype terug te trekken en een nieuwe versie van het zaaktype te maken.

**Comment by michielverhoef** [comment]
Eea. nalezende denk ik dat deze vraag beantwoord is.
