### ISSUE TITLE
DRC staat het verwijderen van gelockte documenten toe, is dat correct?

### ISSUE THREAD

**Issue by MNIJ** [VNG-Realisatie/gemma-zaken#1956]
Het is momenteel in de DRC mogelijk om een informatieobject dat een lock heeft te verwijderen met een DELETE request. Daar hoef je niet eens het lock-id voor mee te sturen. 

De specificatie is hier niet 100% duidelijk in, er staat dat "WRITE acties niet zijn toegestaan" op een gelockt object en je kan een semantische discussie houden of DELETE onder WRITE acties valt. Maar vanuit een functioneel oogpunt lijkt me dit zeer onwenselijk. Het kan ook technische problemen opleveren, bijvoorbeeld gebruiker 1 upload een groot document en tijdens de upload verwijdert gebruiker 2 het informatieobject.

Ik zou dus ook willen voorstellen dat een DELETE op een object met een lock resulteert in een foutmelding. Een andere richting zou kunnen zijn om DELETE toe te staan mits het lock-id wordt meegegeven, maar dat is een ongebruikelijke constructie en heeft geen functionele waarde volgens mij.

**Comment by michielverhoef** [comment]
Dit is inderdaad niet goed. Een gelocked document zou eerst vrijgegeven moeten worden (een nieuwe versie terugschrijven of een undo_checkout) en daarna kan het pas verwijderd worden. Dat lijkt me de meest logische manier om hier mee om te gaan.

Ik heb er een bug van gemaakt die in de volgende versie opgelost gaat worden.
