### ISSUE TITLE
Als architect van een gemeente wil ik dat de GEMMA 2 referentiecomponenten aangepast worden aan de huidige ontwikkelingen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#196]
...zodat ik up to date informatie kan vinden over de functionaliteit van de referentiecomponenten.

Toelichting: Bijvoorbeeld het ZRC https://www.gemmaonline.nl/index.php/GEMMA2/0.9/id-a97b6545-d5a7-485d-9b13-3ce22db5b9cf kent nog als aanbevolen StUF ZKN, gebaseerd op SOAP en XML, terwijl de standaard waar we nu mee bezig zijn gebaseerd is op REST/JSON.

In theorie kan dit ondervangen worden door dat de verplichte ondersteuning van Zaak- Documentservices geen versienummer kent maar misschien moet er toch iets over gezegd worden?

Want ZDS 1.x/StUF ZKN en ZDS 2.0 zijn absoluut niet compatible met elkaar.

**Definition of ready**
- [ ] Ontbrekende eisen aan de relevante referentiecomponenten zijn bekend en beschreven

**Definition of done**
- [ ] Beschrijvingen van de relevante referenticomponenten ZRC, DRC en ZTC op website GEMMA Online zijn aangepast aan nieuwe ontwikkelingen.

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan nieuwe architectuur en techniek inzichten van ZDS 2.0

**Taken**
- [ ] Aanpassen beschrijvingen referentiecomponenten in BIZZ Design (?) [_@jgortmaker1_]
- [ ] Exporteren beschrijvingen naar media wiki formaat GEMMA Online [_@jgortmaker1_]

**Comment by jgortmaker1** [comment]
die standaarden zijn van de SWC en Mark Backer...daar mag ik niet aankomen :-)

**Comment by michielverhoef** [comment]
Dan moeten we het Mark vragen :-) 
Maar het is wel belangrijk dat de GEMMA Online in synch gehouden wordt met de ontwikkelingen hier.

**Comment by ehotting** [comment]
Er zal een tijd zijn dat SOAP/XML services en REST/JSON API's naast elkaar bestaan - het lijkt me goed dat ook in GEMMA tot uitdrukking te laten komen. Dan moet je eigenlijk gaan werken met een doelarchitectuur  (In TOGAF: baseline en target).  In de referentiearchtiectuur zou je twee interfaces kunnen tekenen bij de betreffende referentiecomponenten.

**Comment by TCIMEddy** [comment]
@jgortmaker1 Moet dit nog op het bord van zds?

**Comment by Hugo-ter-Doest** [comment]
Dit moet op de backlog bij de squad architectuur. https://github.com/VNG-Realisatie/Squad-Architectuur-Samen-Organiseren
Ik sluit hem hier af.
