### ISSUE TITLE
Als medewerker van de gemeente wil ik de werkvoorraad van open zaken snel kunnen inzien

### ISSUE THREAD

**Issue by andyverberne** [VNG-Realisatie/gemma-zaken#1961]
Als medewerker van de gemeente wil ik de werkvoorraad zien van open zaken. Zie hiervoor het screen shot hieronder. Bij het opbouwen van deze tabel ondervinden wij 2 problemen welke het opbouwen van de lijst sterk vertragen.

1)	Voor het ophalen van de lijst gebruiken wij ‘zaak_list’ operatie. Aan deze operatie kan geen filter parameter worden meegegeven om alleen open (niet beëindigde) zaken te retourneren. Als workaround halen wij daarom alle zaken op om daarna te filteren op de openstaande zaken. Zoals te zien is in onderstaande screenshot wordt de werkvoorraad gepagineerd weergegeven. De ‘zaak_list’ operatie ondersteund ook paginering maar deze kunnen we dus niet gebruiken omdat we alle zaken moeten ophalen om de open zaken daaruit te kunnen filteren
2)	Het resultaat van de ‘zaak_list’ operatie is een lijst met zaken in JSON formaat. Deze zaken bevatten echter niet alle informatie die nodig is om in onderstaande tabel te kunnen tonen. Voor elke zaak moeten daarom nog de volgende operaties aangeroepen worden om de benodigde informatie te krijgen:
-- ‘zaaktype_read’ operatie om de omschrijving van het zaaktype op te halen
-- ‘status_read’ en ‘statustype_read’ operatie om de omschrijving van het statustype van de status van de zaak op te halen
-- ‘roltype_read’ en ‘rol_list’ operatie om de Groep op te halen
-- ‘roltype_read’ en ‘rol_list’ operatie om de Behandelaar op te halen
-- ‘resultaat_read’ en ‘resultaattype_read’ om het Resultaat op te halen
Dus nadat de lijst met zaken is opgehaald zijn er per zaak nog 9 extra REST calls nodig om de tabel te vullen.

![werklijst](https://user-images.githubusercontent.com/3702729/158202431-3b164111-e351-44d2-ba60-3b2db2b2db7d.jpg)

**Comment by andyverberne** [comment]
Analyse in hoeverre bovengenoemde problemen worden opgelost met de  1.3.0-alpha2 versie van de Zaken API.

1. Om te bepalen of een zaak afgesloten is wordt gecontroleerd of het attribuut 'archiefnominatie' gevuld is. In de nieuwe versie kan gefiltered worden op specifieke waarden voor 'archiefnominatie' maar kan er ook gefiltered worden op een lege waarde?

**Comment by michielverhoef** [comment]
Expand de verschillende typen is iets om nog eens goed naar te kijken. Hoewel dit resources zijn uit een andere API is het ook niet echt een API waar je geen controle over hebt. Hooguit over de inhoud (waarden) maar de  structuur zal wel meevallen.

**Comment by sergei-maertens** [comment]
Zie ook: https://github.com/VNG-Realisatie/gemma-zaken/discussions/1960

**Comment by sergei-maertens** [comment]
Ik had net nog even de API spec doorgelopen (https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/vng-Realisatie/zaken-api/master/src/openapi.yaml#operation/status_list) en inderdaad - er is geen filter parameter voor open zaken. Ik had verwacht dat die er was in de vorm van `einddatum__isnull=true` o.i.d., maar die ontbreekt helemaal.

Ik denk dat een filter parameter `behandelStatus` met mogelijke waarden `open` of `gesloten` hier voldoende uitkomst biedt. Dit laat je toe om:

1. De parameter weg te laten, dan krijg je open en gesloten zaken
2. `?behandelStatus=open` geeft je enkel de zaken relevant voor een werkvoorraad, en het bijkomend voordeel is dan dat server-side pagination wel weer effectief is
3. `?behandelStatus=gesloten` - tegenhanger van 2. uiteraard

**Comment by andyverberne** [comment]
Een expliciet filter 'behandelStatus' lijkt mij ook beter. Echter wat maakt dat een zaak open of gesloten is? Het al dan niet gevuld zijn van de einddatum lijkt voor de hand te liggen, en dat gebruiken wij ook zo in de e-Suite. Echter voor Open Zaak gebruiken we nu 'archiefnominatie'. Daar was volgens mij een reden voor alleen weet ik ni even niet welke. Ik ga dat uitzoeken.

**Comment by michielverhoef** [comment]
Opgenomen in Zaken API 1.5.0
