### ISSUE TITLE
Welke gegevens bevat de property 'bezoekadres' component 'RolNietNatuurlijkPersoon' in de ZRC API specificatie?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#1964]
In de component 'RolNietNatuurlijkPersoon' in de ZRC API specificatie komt de property 'bezoekadres' voor. De omschrijving daarvan is als volgt 'De gegevens over het adres van de NIET-NATUURLIJK PERSOON'.
In het RSGB loopt de relatie 'heeft als bezoekadres' van NIET-NATUURLIJK PERSOON naar ADRESSEERBAAR OBJECT AANDUIDING.
Het lijkt er op dat de property 'bezoekadres' een aggregatie is van de gegevens in dat objecttype en daaraan gerelateerde objecttypes. Wat echter niet duidelijk is welke gegevens geaggregeerd worden. Betreft dat alleen:
* Naam openbare ruimte (OPR)
* Huisnummer (AOA)
* Huisletter (AOA)
* Huisnummertoevoeging (AOA)
* Postcode (AOA)
* Woonplaatsnaam (WPL)

of kan het nog meer gegevens bevatten?

**Comment by michielverhoef** [comment]
Dat is een interessante vraag.. Voor de zekerheid heb ik het even nagekeken maar zo te zien is bezoekAdres altijd al een string geweest in plaats van een groepsattribuut. Voor wat ik er nu van kan maken is bezoekAdres inderdaad een aggregatie en de genoemde gegevens zouden daar heel goed in kunnen zitten. Maar 100% zeker weten doe ik het (nog) niet.

**Comment by michielverhoef** [comment]
Voor nu sluit ik het issue aangezien er verder geen onderliggende problematiek of behoefte is aangeven.
