### ISSUE TITLE
Toevoegen datum begin/eind geldigheid aan alle resources

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1972]
Voorbeelden zie ook https://app.swaggerhub.com/apis/michielverhoef/Catalogussen_API/1.2.0-alpha#/

Met deze attributen wordt formele historie geimplementeerd.
zie ook #1970

**Comment by michielverhoef** [comment]
Datum begin/eind geldigheid  is nog niet bij  alle resources ingebouwd. De attribuutnamen zijn beginGeldigheid en eindGeldigheid.

De logica is als volgt:
Resource R heeft 2 versies, R[1] en R[2].

 eind geldigheid van R[1] is de dag voor de datum begin geldgheid van R[2] .

Bv:
R[1].beginGeldigheid 01-01-2021
R[1].eindGeldigheid 28-2-2021

R[2].beginGeldheid 01-03-2021
R[2].eindgeldgheid 

Omdat R[2] de huidige versie is heeft eindGeldigheid nog geen waarde.

**Comment by michielverhoef** [comment]
Aan de list operatie moet filtering met beginGeldigheid en eindGeldigheid ingebouwd worden.
Dit om het object op basis van identicficatie/omschrijving en begin-/eindGeldigheid op te kunnen halen.

**Comment by MatthijsBekendam** [comment]
geldigheid zit al in master. Filtering word toegevoegd in nieuwe historie model.
