### ISSUE TITLE
zaaktypeindentificatie toevoegen aan resource Zaaktypen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#1973]
Het attribuut zaaktypeidentificatie bestaat reeds als "identificatie".

In logica toevoegen:

1/ Ophalen versie van een zaaktype op basis van (zaaktype)identificatie + datumgeldigheid

Defaultwaarde datumgeldigheid is "vandaag", anders moet de versie geldig zijn op gegeven datum (gegeven datum tussen datum begin geldigheid en datum eind geldigheid)

**Comment by michielverhoef** [comment]
Zaaktypeidentificatie is reeds opgenomen in Zaaktype onder de naam identificatie: https://catalogi-api.test.vng.cloud/api/v1/schema/#operation/zaaktype_read

**Comment by MatthijsBekendam** [comment]
Dit wordt toegevoegd in nieuwe historie model.
