### ISSUE TITLE
Catalogi API: API documentation incorrect

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1976]
# Bug

In the Catalogi API, the "publish" actions are not correctly documented, e.g. https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/catalogi-api/1.1.0/src/openapi.yaml#operation/besluittype_publish

The response status code is HTTP 200 instead of the documented HTTP 201, and the titles/summaries of the operations in the API spec also do not correctly reflect the behaviour.

This has been fixed in Open Zaak, so we can probably contribute that back relatively easily.

Additionally, the error response status codes are missing for these actions (HTTP 4xx, HTTP 5xx)

**Comment by michielverhoef** [comment]
> This has been fixed in Open Zaak, so we can probably contribute that back relatively easily.

PR's are welcome anytime :-)

**Comment by sergei-maertens** [comment]
@michielverhoef I've created a PR: https://github.com/VNG-Realisatie/catalogi-api/pull/130

I'd like to argue to get this in Catalogi API 1.1.1 rather than 1.2.0, since there is effectively a bug in the documentation - the publish endpoint documents a response status code HTTP 201, but in reality this is a HTTP 200
