### ISSUE TITLE
Zaken API (and probably others) incorrectly document ETag response header

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1978]
Because of an oversight in the implemenation, a number of endpoints document the `ETag` response header while it's not actually emitted (or intended to be emitted). Consequently, the conditional retrieve behaviour is also non-functional.

I shall make pull requests to correct this documentation bug to the respective APIs.

**Patches**

- [x] Zaken API https://github.com/VNG-Realisatie/zaken-api/pull/211
- [x] Documenten API https://github.com/VNG-Realisatie/documenten-api/pull/157
- [x] Catalogi API https://github.com/VNG-Realisatie/catalogi-api/pull/131
- [x] Besluiten API https://github.com/VNG-Realisatie/besluiten-api/pull/84
- ~~Autorisaties API~~ Looks unaffected

**Comment by michielverhoef** [comment]
@MatthijsBekendam  zijn deze PR's opgenomen in onze RI's?

**Comment by MatthijsBekendam** [comment]
@michielverhoef Ja

**Comment by michielverhoef** [comment]
Dan sluit ik het ticket.
