### ISSUE TITLE
Als klant wil ik de doorlooptijd bij een bepaalde status weten

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1988]
...zodat ik weet wanneer er weer actie van mij wordt verwacht of wanneer ik bepaalde reactie kan verwachten.

Dit is overigens een ImZTC-attribuut: https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/gegevensgroeptype/statustype.doorlooptijd_status

...maar zit dus niet in de ZGW API's.

*namens Laura, Gemeente Buren; tijdens de Product Dienst Status-hackaton*

**Comment by michielverhoef** [comment]
https://catalogi-api.vng.cloud/api/v1/schema/#operation/statustype_read

In Statustype moet ook een doorlooptijd attribuut bij komen van het type Duration, net als doorlooptijd van een Zaaktype.

**Comment by michielverhoef** [comment]
https://catalogi-api.test.vng.cloud/api/v1/schema/#operation/statustype_read

Doorlooptijd is opgenomen in de 1.2.0 versie.
