### ISSUE TITLE
Zaken API 1.1.x API spec verwarrend (ZIO create)

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#1998]
# Bug

Waarschijnlijk een merge conflict - de beschrijving bij de ZaakInformatieobject create operatie ziet er niet helemaal goed uit:

API spec: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/zaken-api/1.1.1/src/openapi.yaml#tag/zaakinformatieobjecten/operation/zaakinformatieobject_create

![image](https://user-images.githubusercontent.com/5518550/166480960-27b4cca4-1d03-4e9f-bb72-b7fe869588d0.png)

**Comment by michielverhoef** [comment]
Zo te zien is dit opgelost.
