### ISSUE TITLE
Controleren checken/toevoegen datum begin/einde geldigheid

### ISSUE THREAD

**Issue by SonnyBA** [VNG-Realisatie/gemma-zaken#1999]

**Comment by michielverhoef** [comment]
https://catalogi-api.test.vng.cloud/api/v1/schema/

De toelichting bij de velden beginGeldigheid en eindGeldigheid is nog overgenomen uit ImZTC. Ik zou deze aanpassen naar iets als:

Begin datum geldigheid van de versie
Eind datum geldigheid van de versie

De oorspronkelijke betekenis van datumBeginGeldigheid en datumEindGeldigheid is die van geboortedatum/sterftedatum van het object (ongeacht de versie). Hiervoor zijn de nieuwe velden datumBeginObject en datumEindObject bedacht.
Deze velden komen in de API terug als beginObject en eindeObject.

**Comment by michielverhoef** [comment]
Zie ook #2006

**Comment by MatthijsBekendam** [comment]
Eigenlijk hebben alle resources een GeldigheidsMixin waar datum_begin_geldigheid en datum_eind_geldigheid in staan. Alleen bij sommige resources wordt deze overschreven met een eigen datum_begin_geldigheid. @SonnyBA weet jij waarom dit gedaan wordt? Zoals bij de eigenschap.py model.

**Comment by SonnyBA** [comment]
Deze velden zijn waarschijnlijk overschreven omdat de wijzigingen backwards compatible moesten zijn met eerdere versies. Als je kijkt in de `GeldigheidsMixin` zie je dat [het veld](https://github.com/VNG-Realisatie/catalogi-api/blob/4e0a266a8264f818f07e668aafa48ff8e0a8aaf1/src/ztc/datamodel/models/mixins.py#L9) standaard verplicht is en het veld wat overschrijft optioneel is.

**Comment by MatthijsBekendam** [comment]
En is er een rede dat dit dan niet gewoon in Geldigheidsmixin word aangepast?

**Comment by SonnyBA** [comment]
Ik vermoed omdat het veld bij andere resources destijds wel verplicht was (en is).

**Comment by MatthijsBekendam** [comment]
ah that makes sense

**Comment by MatthijsBekendam** [comment]
Staat al in master.
