### ISSUE TITLE
geefLijstZaken op <parameter> 

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2]
- [ ] geefLijstZaken
- [ ] zoekparameter bsn initiator
- [ ] zoekparameter zaaktype
- [ ] zaakbevragingen koppelvlak

**Comment by ehotting** [comment]
Reference #44

**Comment by TCIMEddy** [comment]
@michielverhoef Is dit nog een user story, zo ja graag verwoorden als user story (wellicht is de voorzet van jgortmaker1 in de comments goed). Zo niet dan graag op done

**Comment by michielverhoef** [comment]
Dit is geen user story (nooit geweest ook) maar een gewenste functionaliteit. Het is nog een relict van voor dat we user stories maakten.  Het issue kan zeker niet op done aangezien het nog niet gedaan is :-).
Wat mij betreft mag dit issue wel gesloten worden omdat de functionaliteit bij diverse userstories nodig is.

**Comment by TCIMEddy** [comment]
Begrepen en dank!
