### ISSUE TITLE
Als behandelaar wil ik een verkeerd toegevoegd document van een zaak kunnen ontkoppelen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#20]
zodat het zaakdossier correct is en de zaakdocumenten in het correcte dossier zitten

DRC kan dit al, ZRC nog niet.

**Comment by ehotting** [comment]
Volgens mij gaat het om twee dingen die allebei moeten kunnen:
- Relatie tussen een zaak en document doorknippen
- Document compleet verwijderen

Dit moet inderdaad kunnen. Bij ready maken evt. opsplitsen in twee user stories.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest kan dit niet al?

**Comment by michielverhoef** [comment]
Net even nagekeken, in de DRC kan het al wel maar in de ZRC nog niet. Daar is nog geen Delete mogelijk op Zaakinformatieobject, alleen nog maar Create en List.

De relatie Zaak - Informatieobject kan zo te zien nog niet in de ZRC verbroken worden maar wel in de DRC (??)

**Comment by Hugo-ter-Doest** [comment]
@michielverhoef dank! Ik prioriteer hoog.

**Comment by Hugo-ter-Doest** [comment]
Dubbel met #769
