### ISSUE TITLE
Controleren/toegevoegen identificatie veld

### ISSUE THREAD

**Issue by SonnyBA** [VNG-Realisatie/gemma-zaken#2000]

**Comment by michielverhoef** [comment]
Het gaat om de volgende resources:

Zaaktype
https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/objecttype/zaaktype
zaaktype.identificatie: https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/attribuutsoort/zaaktype.zaaktype-identificatie

Informatieobjecttype
https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/objecttype/informatieobjecttype
informatieobjecttype.omschrijving: https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/attribuutsoort/informatieobjecttype.informatieobjecttype-omschrijving


Besluittype
https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/objecttype/besluittype
besluittype.omschrijving: https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/attribuutsoort/besluittype.besluittype-omschrijving

**Comment by MatthijsBekendam** [comment]
- zaaktype.indentificatie (aanwezig)
- informatieobjecttype.omschrijving (informatieobjecttype_omschrijving_generiek gevonden)
- besluittype.omschrijving (aanwezig)

Is het voor de andere resources niet relevant dat ze een identificatie veld hebben?

**Comment by michielverhoef** [comment]
De drie hoofd-resources zijn Besluittype, Informatieobjecttype en Zaaktype.

De andere resources verwijzen naar deze resources. Als je naar het diagram op https://www.gemmaonline.nl/index.php/ImZTC_2.2_in_ontwikkeling kijkt zie je de pijlen van bijvoorbeeld Statustype of Roltype lopen naar Zaaktype.  De relatie wordt gelegd in Statustype. Daar wordt de identificatie vastgelegd van het zaaktype waar het statustype bij hoort.

**Comment by MatthijsBekendam** [comment]
Ah check, thanks!

**Comment by michielverhoef** [comment]
Als ik dit zo zie zitten de drie benodigde resources er nu toch in? @MatthijsBekendam dan mag dit issue gesloten worden

**Comment by MatthijsBekendam** [comment]
Deze zitten al in master
