### ISSUE TITLE
Toevoegen beginObject en eindeObject aan resources

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2006]
Gerelateerd aan #1999 

Alle resources met  beginGeldigheid en eindGeldigheid moeten de attributen  beginObject en eindObject worden toegevoegd.

In deze attributen wordt de oorspronkelijke betekenis van datumBeginGeldigheid en datumEindGeldigheid opgeslagen. Nl. die van geboortedatum/sterftedatum van het object (ongeacht de versie).

**Comment by MatthijsBekendam** [comment]
In de ZaakType resource zit een object:

   versiedatum = models.DateField(
        _("versiedatum"),
        help_text=_(
            "De datum waarop de (gewijzigde) kenmerken van het ZAAKTYPE geldig zijn geworden"
        ),
    )

Deze word dan irrelevant neem ik aan?

**Comment by MatthijsBekendam** [comment]
En eigenlijk moet ik dus begingeldigheid/eindgeldigheid objecten hernoemen naar eind/beginObject zodat deze huidige logica blijft bestaan? En vervolgens nieuwe logica schrijven voor beginGeldigheid/eindgeldigheid?

**Comment by michielverhoef** [comment]
> Deze word dan irrelevant neem ik aan?


Om de API backwards compatible te houden laten we dit soort dingen er wel in. 

> En eigenlijk moet ik dus begingeldigheid/eindgeldigheid objecten hernoemen naar eind/beginObject zodat deze huidige logica blijft bestaan? En vervolgens nieuwe logica schrijven voor beginGeldigheid/eindgeldigheid?


Er komen uiteindelijk 4 velden:

beginGeldigheid : begin geldigheid van de versie van het object
eindGeldigheid : eind geldigheid van de versie van het object

beginObject : geboortedatum van het object (eerste datum waarop de eerste versie van het object geldig is)
eindObject : overlijdensdatum van het object (laatsste datum waarop de laatste versie van het object geldig is)

begingeldigheid en eindgeldigheid zijn als het goed is al bij elke resource aangemaakt, alleen klopt de omschrijving nog niet.

beginObject en eindObject moeten nog toegevoegd worden.

**Comment by MatthijsBekendam** [comment]
mogen beginObject en eindObject gelijk zijn aan elkaar? Of moet er altijd een dag tussen zitten bijvoorbeeld?

**Comment by MatthijsBekendam** [comment]
Moeten er default values aan worden geplakt voor de data die momenteel in de database zit? Of mogen die blanco zijn?

**Comment by michielverhoef** [comment]
> mogen beginObject en eindObject gelijk zijn aan elkaar? Of moet er altijd een dag tussen zitten bijvoorbeeld?

Goede vraag, ga ik uitzoeken. 


> En het de resource mag niet meer aangepast worden wanneer er een eind datum op zit?

Wanneer eindGeldigheid gevuld is is er inmiddels een nieuwe versie dus dan zou die oudere versie niet meer bijgewerkt hoeven te worden (tenzij het een correctie betreft maar dat is dan een uitzondering).

Wanneer eindeObject gevuld is is het hele object komen te vervallen. Ook dan mag alleen een correctie uitgevoerd worden denk ik. Omdat het voor kan komen dat er bijvoorbeeld nog zaken van een zaaktype in behandeling zijn terwijl het zaaktype al wel is komen te vervallen. Dan kunnen er geen nieuwe zaken meer aangemaakt worden maar het zaaktype moet nog wel geraadpleegd kunnen worden.

> Moeten er default values aan worden geplakt voor de data die momenteel in de database zit? Of mogen die blanco zijn?

Je bedoelt als er een beginObject gevuld moet worden? Om het netjes te doen zou de datum beginGeldigheid van de eerste versie van een object gebruikt moeten worden om datum beginObject te vullen. Is het veel werk om alles bij te werken of kunnen we beter een dump maken en een goede testset via SQL laden?

**Comment by michielverhoef** [comment]
Werking beschreven in #2038
