### ISSUE TITLE
DSO API-46 beveelt HAL aan voor paginering - nog in te bouwen

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#201]
HAL implementatie zoals aanbevolen in DSO API strategie wordt vooralsnog uitgesteld tot later moment.

Context, snippet uit DSO API strategie:
<img width="583" alt="dso api-46" src="https://user-images.githubusercontent.com/20684884/42646260-a29f4094-8600-11e8-85d7-18eba7cb1488.png">

**Comment by ehotting** [comment]
@zomwoof Als we op voorhand kunnen besluiten HAL achterwege te laten, scheelt dat in het ready maken user story etc. We handelen het dan af met een gedocumenteerde Design Choice. Input heel welkom. :)

**Comment by zomwoof** [comment]
@ehotting Het wel of niet verplicht gebruik van HAL wordt niet helder in de DSO API Strategie beschreven (zie ook https://forum.pdok.nl/t/onduidelijkheid-gebruik-hal-in-de-api-strategie/1109). Mijn interpretatie is dat HAL alleen verplicht is wanneer de API het mediatype `application/hal+json` teruggeeft in de response-header. In dat geval is het logisch dat de paginering conform HAL moet zijn.  Het gebruik van `application/json+hal` moet volgens mij slechts een mogelijkheid zijn (hoewel de DSO Strategie daar niet duidelijk over is). Je kunt ook gewoon `application/json` als mediatype gebruiken en dan ben je vrij om de manier van pagineren zelf te bepalen. Uiteindelijk zou het mooi zijn als we in de Landelijke API Strategie een uniforme manier van pagineren voor 'application/json' kunnen voorschrijven, maar dat zal niet van de een op andere draagvlak voor zijn.

**Comment by ehotting** [comment]
In dat geval stel ik voor dat wij géén HAL gebruiken. Prima om standaarden te gebruiken, maar moeten dan wel echte, breed gedragen en onderhouden standaarden zijn.

**Comment by TCIMEddy** [comment]
Dit besluit is genomen en vastgelegd in de besluitenlijst en daarom sluit ik dit issue

**Comment by zomwoof** [comment]
@TCIMEddy Waar staat de besluitenlijst?

**Comment by TCIMEddy** [comment]
@zomwoof 
https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/content/developers/design-keuzes.md

Mocht je aanvullingen vragen hebben dan kan dat uiteraard in het Md-document. We zijn hier net mee gestart

**Comment by JohanBoer** [comment]
> @zomwoof
> https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/content/developers/design-keuzes.md
> 
> Mocht je aanvullingen vragen hebben dan kan dat uiteraard in het Md-document. We zijn hier net mee gestart

In de design-keuzes zie ik geen besluit dat met deze discussie gerelateerd is.
