### ISSUE TITLE
Niet mogelijk om concept ZaakType (deels) bij te werken indien gerelateerd aan niet-concept InformatieObjectType

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#2010]
# Bug

In de [standaard](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index#ztc-010) staat beschreven dat het mogelijk moet zijn om concept `ZaakType`n bij te werken, ook als deze gerelateerd zijn aan niet-concept `InformatieObjectType`n. Momenteel is dit niet mogelijk in de referentieimplementatie

**Stappen om te reproduceren**:
1. Maak een `InformatieObjectType` en publiceer het
2. Maak een nieuw `ZaakType`
3. Relateer het `ZaakType` aan het `InformatieObjectType` met een `ZaakType-InformatieObjectType` relatie
4. Probeer een PUT/PATCH te doen op het `ZaakType`, dit resulteert in een status code 400

**Verwacht gedrag**:
Het zou mogelijk moeten zijn om concept `ZaakType`n bij te werken, ook als deze gerelateerd zijn aan niet-concept `InformatieObjectType`n

**Comment by michielverhoef** [comment]
Is zo te zien opgelost
