### ISSUE TITLE
Als frontend developer wil ik minder calls doen naar de ZGW API's,

### ISSUE THREAD

**Issue by RvdKlip** [VNG-Realisatie/gemma-zaken#2016]
zodat ik de performance optimaliseer, complexiteit reduceer, de foutgevoeligheid/foutafhandeling verlaag en daarmee het beroep op functioneel beheer verminder. 

Dit kan bijvoorbeeld op niveau van: Opvragen zaak & Aanmaken van een zaak

**Opvragen zaak** 
Om een overzicht op het scherm te maken van een zaak moeten er een aantal calls gedaan worden naar de ZGW API's. Voor het tonen van de zaak met: de laatste status, resultaat, 1 document (met naam), aanvrager, 1 zaakobject en 1 eigenschap moeten er in totaal 9 aanroepen gedaan worden naar de zaken API en dan nog 5 à 6 naar de zaak catalogus om URL's te vertalen naar zinnige teksten (v.b. status URL, zaaktype URL). Deze laatste kunnen we eventueel cachen. Zijn er meer documenten, of als er nog geen resultaat is, kan het aantal calls iets meer zijn. Wil je een besluit tonen dan komen er weer een aantal calls bij.

Als één van deze calls fout gaat dan kan er geen complete zaak getoond worden.
Aanroepen:
• Zaak
o ZaakType voor naam van de zaak (Ztc)
• ZaakInformatieObjecten (Documenten)
o Per object het enkelvoudigInformatieObject. Hierin staat de naam van het document
• Rollen voor aanvrager
o I.v.m. dynamische betrokkene moet ik per type (5x) een Request doen.
o Per rol het RolType (Ztc)
• Zaakobjecten (Boom)
• Eigenschappen
o Per eigenschap nog de EigenschapType omschrijving (Ztc)
• Laatste Status
o StatusType met omschrijving (Ztc)
• Resultaat
o ResultaatType voor naam (Ztc)

Aanmaken van een zaak.
Om dezelfde zaak aan te maken zijn 7 REST calls nodig. Als er meer of minder documenten en eigenschappen zijn kan dat meer of minder REST calls zijn. Elk van deze REST calls kan fout gaan. Als dit gebeurt dan staat er maar een halve zaak in de ZGW API's. We zetten daarom de status als laatste zodat een BackOffice applicatie niet te vroeg een zaak oppakt.
Voor een applicatie betekent dit ook dat er uitgebreide foutafhandeling nodig is om de gefaalde stappen opnieuw uit te voeren. Al dan niet geautomatiseerd maar uiteindelijk door interventie van functioneel beheer.
Een voorbeeld wat fout kan gaan is het toevoegen van documenten (enkelvoudige data objecten). Hier zijn 2 REST calls voor nodig. De eerste om een document aan te maken en een tweede om het document te koppelen aan de zaak. Gaat de eerste call fout dan is er geen document toegevoegd aan de zaak; gaat de 2e call fout dan zit er wel een document in het zaak systeem maar die is aan geen enkele zaak gekoppeld.

De stappen zijn:
• Zaak aanmaken (verplicht)
• Rol; aanvrager toevoegen (procedureel verplicht)
• Zaakobject toevoegen (zoals een Boom/ ObjectAPI object) (0-n)
• Eigenschappen toevoegen (0-n)
• Aanmaken document(en) (0-n). Twee REST calls per document
o EnkelvoudigInformatieObject (document aanmaken)
o Informatie Object (document koppelen aan de zaak)
• Status aanmaken (procedureel verplicht)

In de huidige zaaksystemen van de Gemeente Rotterdam is het mogelijk om al de stappen in 1 Webservice operatie uit te voeren. Het opvoeren van de zaak kan nog steeds fout gaan maar je hebt geen zaken die maar half zijn doorgezet.

(Doorverwijzing vanuit: https://github.com/open-zaak/open-zaak/issues/1175)

**Comment by joeribekker** [comment]
Frontend moet ook niet direct de ZGW API's bevragen maar dit moet via een BFF (backend for frontend, of gewoon backend) gaan omwille van security en inderdaad om de informatie en performance op te halen die je specifiek nodig hebt voor je frontend (dus dat wil je altijd filteren uit bijvoorbeeld een zaak-response waar je niet perse wilt tonen wie de behandelaar is).

**Comment by michielverhoef** [comment]
Inmiddels is in Zaken API 1.5 en Documenten API 1.4 de mogelijkheid opgenomen via expand gerelateerde resources mee op te vragen en zo het aantal calls drastisch te verminderen. 

Daarom wordt dit issue gesloten.
