### ISSUE TITLE
Dynamische gedrag REST berichten is lastig voor frontend developers

### ISSUE THREAD

**Issue by RvdKlip** [VNG-Realisatie/gemma-zaken#2017]
Sommige delen van de REST berichten zijn dynamisch. Dit houdt in dat het eerste veld een type specificeert en dat type bepaald welke velden er volgen.
Voorbeeld is geometrie. Het type is onder andere POINT en POLYGON. De volgende velden in het bericht zijn anders per type: Array van 2D punten of een Array van een Array van 2D punten.
Systemen als Java/Mendix kunnen niet goed omgaan met dit dynamische gedrag. Vooraf worden mappings gemaakt hoe de velden naar attributen in entiteiten (Mendix) of klassen (Java) mappen. Dit mappen kan niet voor elk bericht gebruikt worden en er moet extra functionaliteit gemaakt worden om de berichten veld voor veld te verwerken. Een geometrie kan niet de ene keer een punt zijn en de andere keer een polygoon.
Dit speelt bij meerdere berichten zoals adres (pand, wijk, buurt etc.) of zaakobject (30 verschillende soorten). Maar ook bij rollen waar het betrokkene Type het deelobject betrokkene Identificatie beïnvloed wordt (v.b. natuurlijk persoon, niet natuurlijk persoon, vestiging …).

**Comment by michielverhoef** [comment]
Ik heb geen ervaring met Mendix maar bij Java zou ik denken dat een Factory dynamisch verschillende soorten klassen terug moet kunnen geven. Analoog aan een database-factory die op basis van een parameter/omgevingsvariable bijvoorbeeld een databasehandler voor SQL Server, MySQL of Oracle teruggeeft.  Dat is dynamisch polymorfisme.

Zie bijvoorbeeld een artikel als dit: https://medium.com/edureka/polymorphism-in-java-9559e3641b9b
