### ISSUE TITLE
Helderheid nodig op 'Definition of ready'

### ISSUE THREAD

**Issue by RvdKlip** [VNG-Realisatie/gemma-zaken#203]
# Impediment

In de laatste retrospective bijeenkomst zijn de eisen rondom 'definition of ready zijn van User stories' aangescherpt. 

Ik meen dat er was afgesproken dat iemand deze alsnog zou toevoegen aan bestaande user stories. Dit is nog niet gebeurd. Ik worstel daarom nu met de vraag welke 'definition of ready' eisen ik moet geven aan mijn bestaande user stories. In de template staan er 3. 

**Definition of ready**
- [ ] Userstory is ingevuld op template architectuurschets
- [ ] Userstory is voorzien van veldmapping naar RGBZ2
- [ ] Userstory past op wenselijk gebruik ZGW volgens GEMMA 2

Maar in de bijeenkomst waren het er meer...

**Comment by RvdKlip** [comment]
De tweede DOR eis 'Userstory is voorzien van veldmapping naar RGBZ2' gaat een gemeente niet zonder hulp lukken! Hoe organiseren we deze hulp. Moet dit afgevinkt zijn voordat US naar de kolom 'ready for sprint' wordt overgezet?

**Comment by TCIMEddy** [comment]
Hoi Ruub , de template is aangepast voor nieuwe issues. Voor een aantal bestaande issues heb ik wijzigingen aangebracht. Je kunt voor user stories waarin dit nog niet gebeurt is onderstaande dor kopiëren en plakken in de user story

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Comment by TCIMEddy** [comment]
Voor veldmapping RGBZ kun je @ArjanKloosterboer inschakelen voor hulp.
