### ISSUE TITLE
[VRAAG] Zaaktype met een begindatum geldigheid in de toekomst wijzigen

### ISSUE THREAD

**Issue by RoyBuis** [VNG-Realisatie/gemma-zaken#2055]
Wij zijn bij het werken met de catalogi tegen een punt aangelopen waarvan we ons afvragen of dit geen problemen oplevert in de praktijk. Als je een zaaktype definieert met een begindatum geldigheid in de toekomst en deze publiceert dan is het niet meer mogelijk om een nieuwe versie aan te maken met een begindatum die voor de vorige versie ligt. Als je abusievelijk een verkeerde begindatum in de toekomst hebt ingevuld dan moet je dus wachten tot die datum voordat je een nieuwe versie van een zaaktype kan definieren. Dat kan een lastige situatie op leveren voor een catalogi beheerder, die moet dan of wachten of een heel nieuw uniek zaaktype maken. Hoe kijken anderen hier tegenaan?

**Comment by michielverhoef** [comment]
Dit probleem is onderkend en kan worden opgelost met een zgn [correctie](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/#correctie).
