### ISSUE TITLE
Als bevoegd gezag wil ik labels kunnen plaatsen bij documenten en op kunnen zoeken en sorteren

### ISSUE THREAD

**Issue by Jinze82** [VNG-Realisatie/gemma-zaken#2057]
Als bevoegd gezag wil ik labels kunnen plaatsen bij documenten en op kunnen zoeken. We zien dat de eerste uitwerkingen leiden tot generieke benamingen van documenttype als bijvoorbeeld “bijlage bij verzoek” in de ZTC-OW. Dit is niet voldoende voor een gebruiker en onvoldoende voor de terug vindbaarheid. Qua mapping van inkomende documenten snappen we het principe achter deze keuze, vandaar het verzoek voor een al in praktijk veelgebruikte functionaliteit mogelijk te maken.  Graag zouden we dan ook labels willen kunnen plaatsen als “tekening”, “berekening”, “rapport”, enz. Zeker bij vergunningszaken waarin het aantal documenten oploopt tot 3000 per zaak. Terug vindbaarheid en sorteerbaarheid op labels in dan wel een must. 

Dit past tevens bij de beweging van automatisch meta-dateren op basis van de inhoud van het document. Bij de typeringen in het model zien we dit wel terug in de vorm van trefwoorden echter bij documenten (gebruikerskant) niet.

**Comment by michielverhoef** [comment]
Zijn dit dan labels die free-format ingevuld moeten kunnen worden of moeten deze labels eerst aangemaakt worden zodat je er later uit kunt kiezen? Bijvoorbeeld In github kun je alleen kiezen uit vantevoren aangemaakte labels maar met de juiste rechten kun je on the fly wel nieuwe labels aanmaken die je vervolgens kunt gebruiken.

**Comment by Jinze82** [comment]
Ik zie het in deze situatie enigszins wel vrij in het standaard. Het heeft voor ons niet als doel om te rubriceren, dat doe je mijn inziens via informatie-objecttype. Ik zie wel dat er sturing op waarden kan komen, maar lijkt mij meer een intelligentie die leveranciers inbouwen. Men kijkt dan naar eerder ingevulde waarden en geeft dat als suggestie terug.

**Comment by michielverhoef** [comment]
Is dit dan een trefwoord?
https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/attribuutsoort/informatieobjecttype.informatieobjecttypetrefwoord

Dan zou dat trefwoord ook in het informatiebject moeten worden opgenomen.

In ieder geval moet dan #2058 worden uitgevoerd en dan zou dit een uitbreiding van de Documenten API zijn.
@Jinze82 is dit wat je bedoelt?

**Comment by Jinze82** [comment]
Ja en dan vrij op een informatieobject kunnen toevoegen. Deze behoefte is breder dan de eerste aanleiding wat voortkwam uit de frustratie dat we niks kunnen met informatieobjecttype "bijlage bij verzoek". Je ziet nu in productie dat een verantwoordelijke, woorden toevoegt aan titel of omschrijving bij een document om er tijdens behandeling overzicht in te behouden. Titel en omschrijving kennen qua verschijningsvorm werkafspraken,  zodat ze eenduidig kunnen worden gepubliceerd en gedeeld. Daar hebben we dus last van als ze dat doen. Het is dus ook functionaliteit om tijdens de proces behandeling steekwoorden te plaatsen opbasis van de inhoud van een document dat je snel de documenten kan vinden. Je merkt nu al deze wens bij verantwoordelijke omdat ze misbruik maken van bestaande velden.

**Comment by Jinze82** [comment]
Sluit ook aan bij het MDTO. GEMMA omschrijving en MDTO hierop op elkaar afstemmen?

https://www.nationaalarchief.nl/archiveren/mdto/trefwoord

**Comment by RemcovBeelen** [comment]
Dit is ook een wens vanuit de gemeente Nieuwegein

**Comment by Nunspeet** [comment]
Dit is ook een uitdrukkelijke wens vanuit de gemeente Nunspeet

**Comment by HenriKorver** [comment]
@Jinze82 Zie pull request #2226. Ik heb het attribute `trefwoorden` toegevoegd waarmee je een lijstje trefwoorden kunt toevoegen aan een document. Het gelijknamige attribuut is aanwezig als query parameter bij de operatie `GET /enkelvoudiginformatieobjecten` zodat je op één of meerdere trefwoorden kunt filteren. Is het zo naar wens?

**Comment by HenriKorver** [comment]
@MatthijsBekendam  Zie deze commit https://github.com/VNG-Realisatie/gemma-zaken/commit/9d0383f8c6d8546cb531d625bcae57fb0e2b7e9f voor de aanpassingen in de OAS voor dit ticket.

**Comment by michielverhoef** [comment]
Wat is de PR voor dit issue?

**Comment by HenriKorver** [comment]
> Wat is de PR voor dit issue?

https://github.com/VNG-Realisatie/gemma-zaken/pull/2226

**Comment by michielverhoef** [comment]
Opgenomen in Documenten API 1.4.0
