### ISSUE TITLE
DRC api: hernoemen zoeksleutel id naar informatieobjectIdentificatie

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#206]
Zoals besproken tijdens de conference call eerder vanochtend de opmerkingen over de API's van #39 

'/enkelvoudiginformatieobjecten/{id}':
{id} heet volgens RGBZ2 informatieobjectIdentificatie
Omschrijving moet zijn "Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT" (uit RGBZ2)

Wanneer de parameternamen aansluiten bij de naam van het gegeven in RGBZ2 is duidelijk om welke sleutel het gaat. Voorstel is de parameter te hernoemen

**Comment by sergei-maertens** [comment]
In https://github.com/VNG-Realisatie/gemma-zaken/issues/208#issuecomment-406250658 is de conclusie gevallen op het gebruik van UUID
