### ISSUE TITLE
ZGW: required fields in the PATCH method

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#2067]
The ZRC Redoc-documentation for PATCH zaken/uuid  (https://zaken-api.vng.cloud/api/v1/schema/#operation/zaak_partial_update) mentions required fields in the request body schema: bronorganisatie, zaaktype, ...)

At present we are testing the ZGW-interaction between two applications by two different companies. The integration fails because a PATCH on zaak is sent without the required fields, while the ZRC considers them to be mandatory. 

In our (Visma Roxit) eyes no field in the Patch method should be required 
-  since the patch is meant to send only fields that have been changed, sending required (but not changed) fields would suggest that fields have been changed while they have not been changed;
- Open Zaak also accepts Patches on Zaak without required fields;
- The Dutch API Design rules says about PATCH   "The request only contains the resource modifications....." (https://publicatie.centrumvoorstandaarden.nl/api/adr/#http-methods).

**Comment by michielverhoef** [comment]
Goed punt. De bewuste velden zijn al ingevoerd bij het aanmaken van de zaak (daar zijn ze verplicht) dus er is geen reden die nogmaals op te voeren in een PATCH/partial_update. 

> Open Zaak also accepts Patches on Zaak without required fields;

Dit is een leuke, ik dacht dat Open Zaak zich altijd aan de standaard hield? ;-)

Nu ik hier zo naar kijk is het wel goed om naar alle PATCH/partial_update operaties te kijken, daar zie ik wel wat vergelijkbare of andere rare dingen.

**Comment by WilliamRoxit** [comment]
Er zijn ook een flink aantal velden (zowel in post, put als patch) die niet-required maar ook niet-nullable zijn. OAS technisch gezien kan dat wel, maar als consumer voelt dat heel erg gek. Zaak.Betalingsindicatie is daar een voorbeeld van. Dit is een enumeration die niet verplicht is, maar ook niet nullable. Het is dan niet te voorspellen welke van de enumeration-waarden de implementatie kiest als er niks wordt meegestuurd. Niet-required velden altijd nullable maken, en required velden altijd not-nullable is een stuk duidelijker :)

**Comment by michielverhoef** [comment]
Ook daar ben ik het mee eens. Tenzij er een default waarde is die gehanteerd moet worden maar dat zou dan beschreven moeten staan. Dat is in dit geval niet zo.

**Comment by WilliamRoxit** [comment]
> Ook daar ben ik het mee eens. Tenzij er een default waarde is die gehanteerd moet worden maar dat zou dan beschreven moeten staan. Dat is in dit geval niet zo.

Ik heb een apart issue gemaakt voor het required/nullable en de validaties op string($specificatie) velden: https://github.com/VNG-Realisatie/gemma-zaken/issues/2090

**Comment by michielverhoef** [comment]
Vanaf versie 1.3.0 is dit probleem van verplichte velden in de PATCH reeds opgelost. Daarom sluit ik dit issue.
