### ISSUE TITLE
Als gebruiker van de Zaken API wil ik Zaken kunnen filteren op meer dan één ZaakType

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#2072]
...zodat ik minder calls hoef te doen om Zaken van een paar ZaakTypen op te halen

Het zou handig zijn als de bestaande query parameter `zaaktype` op het Zaken endpoint een kommagescheiden lijst van zaaktype URLs accepteert, om zo het aantal requests te verminderen

cc @alextreme

**Comment by alextreme** [comment]
Dank Steven, je bent wel iets te snel aangezien Jan nog bezig is per mail met een uitgebreidere user story voor Michiel. Dus ik zou deze issue pas aan Michiel assignen op het moment dat dat is afgestemd.

**Comment by sergei-maertens** [comment]
Er is hier wel een praktische limitatie op maximale lengte van URLs (leve Internet Explorer en de invloed die het na irrelevant te zijn nog steeds heeft). Persoonlijk ben ik wel gecharmeerd van deze optie via de `POST` body in de `zaak__zoek` operation.

**Comment by alextreme** [comment]
Zelfde issue als #2076

**Comment by alextreme** [comment]
@michielverhoef graag horen we of we hiervoor de zaaktype__in filter dienen toe te voegen of dat de POST zaak_zoek gebruikt dient te worden. Dit ook omdat Jan volgens mij alleen met het eerste verder kan met waar hij dit voor nodig heeft in #2076

**Comment by MaartenRutten** [comment]
Als een lijst van zaken opgevraagd wordt van een bepaald zaaktype, is het dan de bedoeling dat de URL's van alle versies van dat zaaktype in de "zaaktype__in" parameter opgenomen worden? 
En als je zaken van meerdere zaaktypen wil opvragen alle versies van alle gewenste zaaktypen.

Of komt er een andere oplossing?

**Comment by alextreme** [comment]
@MaartenRutten dit wordt zo te zien besproken in #1857 , het staat los van deze aanpassing. Dus ja, je zou dan meerdere zaaktype URLs kunnen opgeven als je wilt filteren op verschillende versies van een zaaktype.

**Comment by michielverhoef** [comment]
> Als een lijst van zaken opgevraagd wordt van een bepaald zaaktype, is het dan de bedoeling dat de URL's van alle versies van dat zaaktype in de "zaaktype__in" parameter opgenomen worden? En als je zaken van meerdere zaaktypen wil opvragen alle versies van alle gewenste zaaktypen.
> 
> Of komt er een andere oplossing?

Dan zou je moeten kunnen filteren op de zaaktypeidentificatie.  Dat is op dit moment nog niet zo maar wellicht kan het nog ingebouwd worden indien er voldoende behoefte aan is.

**Comment by vwmvanbeek** [comment]
@michielverhoef  kan je ons helpen om deze voorgestelde wijziging door het proces te krijgen? Graag je advies hoe verder

**Comment by michielverhoef** [comment]
@vwmvanbeek  zie ook https://github.com/VNG-Realisatie/gemma-zaken/issues/2076#issuecomment-1285187136

**Comment by michielverhoef** [comment]
In de geplande Zaken API 1.4.0 is het mogelijk om op meerdere waarde van zaaktype URL te filteren met de parameter zaaktype__in:
https://redocly.github.io/redoc/?nocors&url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/DESIGN/zaken/1.4.x/openapi.yaml#tag/zaken/operation/zaak__zoek

**Comment by michielverhoef** [comment]
In de 1.4.x versie is in de zaak_zoek operatie de parameter zaaktype__in toegevoegd waarmee dit mogelijk is.
https://zaken-api.vng.cloud/api/v1/schema/#tag/zaken/operation/zaak__zoek
