### ISSUE TITLE
Als toepasser van zaakgericht werken wil ik niet beperkt zijn door maximale lengtes van tekstvelden

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#2073]
...zodat ik alle relevante informatie bij de zaak kan opnemen zonder informatieverlies.

**Context**

Ik ben bezig met een migratie van een op StUF-ZKN gebaseerd zaaksysteem naar de ZGW API's voor Gemeente Haarlem/Zandvoort. Bij het migreren de zaakgegevens ben ik beperkt in de informatie die ik in de Zaken API kan registreren, met name de `omschrijving` en de `toelichting` van de zaak. De bestaande gegevens zijn langer dan de toegestane lengtes in de API (gebaseerd op RGBZ 2.0), `AN80` respectievelijk `AN1000`.

Concreet bevat mijn dataset:

* 106K zaken
* waarvan 12525 zaken een `omschrijving` hebben langer dan 80 karakters
* waarvan 1218 zkaen een `omschrijving` hebben langer dan 160 karakters (dubbel van toegestane lengte)
* waarvan 1098 zaken een toelichting hebben langer dan 1000 karakters
* de maximale toelichting lengte is 4000 karakters
* de maximale omschrijving lengte is 862 karakters

Migreren van deze dataset naar de ZGW API's heeft informatieverlies tot gevolg.

**Comment by michielverhoef** [comment]
Het betreffende zaaksysteem zal dan ook niet voldaan hebben aan de oude RGBZ1 gebaseerde Zaak- Documentservices. Bijvoorbeeld https://www.gemmaonline.nl/index.php/Rgbz_01.01/doc/attribuutsoort/zaak.omschrijving 

Uitbreiden van de huidige  standaard omdat een leverancier zich indertijd niet aan de toenmalige standaard heeft gehouden lijkt me geen goede reden. Wanneer er een goede, functionele en/of technische reden is kan er altijd over gepraat worden maar dit vind ik geen goede reden.

Er is al veel vaker een discussie geweest over de lengte van omschrijving, , in ieder geval voor andere resources. Volgens mij kwam daar altijd wel uit dat er andere gegevens in gezet werden dan bedoeld volgens het informatiemodel.

Mijn eerste vraag is toch: Wat staat er in die bewuste omschrijving dat er meer dan 80 karakters nodig zijn? En is dat wel een omschrijving zoals bedoeld volgens het RGBZ https://www.gemmaonline.nl/index.php/Rgbz_01.01/doc/attribuutsoort/zaak.omschrijving ?

**Comment by sergei-maertens** [comment]
> Het betreffende zaaksysteem zal dan ook niet voldaan hebben aan de oude RGBZ1 gebaseerde Zaak- Documentservices.

Dat blijkt uit meer dingen, inderdaad. 

> Uitbreiden van de huidige standaard omdat een leverancier zich indertijd niet aan de toenmalige standaard heeft gehouden lijkt me geen goede reden. Wanneer er een goede, functionele en/of technische reden is kan er altijd over gepraat worden maar dit vind ik geen goede reden.

Eens - en nu heb ik een duidelijk linkje wat ik terug kan kaatsen dat aantoont dat het "niet mijn probleem" is, dus dit is voldoende munitie! Dankje
