### ISSUE TITLE
ZRC api: in zoeksleutel op /zaken/ ontbreekt de bronorganisatie

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#208]
Zoals besproken tijdens de conference call eerder vanochtend de opmerkingen over de API's van #39 

'/zaken/{id}':
{id} heet in RGBZ2 zaakidentificatie
Omschrijving: De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK.(uit RGBZ2) 
Formaat AN40 ipv integer

NB: Bronorganisatie ontbreekt nog. De unieke identificatie van een zaak is zaakidentificatie icm bronorganisatie. 

Opvragen op basis van een recordid is mogelijk maar risicovol, een recordid kan technisch mogelijk veranderen terwijl de inhoud van het record nog gelijk is. Bovendien kan dan onduidelijkheid zijn over wat nou de correcte identificatie is: zaakidentificatie icm bronorganisatie of een recordid (wat technisch overal voor kan komen).

**Comment by sergei-maertens** [comment]
Opmerking: `id` != `zaakidentificatie`, zie https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/zrc/openapi.yaml#L520

Deze staat weldegelijk in de API spec op dit moment, wordt alleen niet gebruikt in de URL van de resource. Bronorganisatie ontbreekt inderdaad.

**Comment by michielverhoef** [comment]
Als ik zo je reactie in https://github.com/VNG-Realisatie/gemma-zaken/pull/142#discussion_r202319126
bekijk zitten we wel op 1 lijn. 
De voorgestelde oplossing van api/v1/zaken/{bronorganisatie}/{zaakidentificatie} vind ik er goed uitzien.

**Comment by zomwoof** [comment]
Quote van @sergei-maertens:
> Ik voel wel dat we de zaakidentificatie e.d. waarschijnlijk moeten gaan gebruiken in plaats van interne database IDs. Ik ben benieuwd wat dat gaat betekenen op plaatsen waar dit toch niet unique blijkt te zijn (maar unique together met een ander attribuut). Ik denk dat hier concreet dan het path er gaat uitzien als api/v1/zaken/{bronorganisatie}/{zaakidentificatie}

Dat kan maar een pad met twee parameters vlak na elkaar ziet er een beetje vreemd uit en is volgens mij geen gebruikelijke REST-conventie.  Ik zou eerder `{zaakidentificatie}` een concatenatie laten zijn van `bronorganisatie` (RSIN, N9) en `zaakidentificatie` (AN40). Dan kun je volledig uit de voeten met het pad api/v1/zaken/{zaakidentificatie}. 

Een dergelijke concatenatie zou in het UGM geformaliseerd kunnen worden.

**Comment by michielverhoef** [comment]
Met een dergelijke concatenatie is zaakIdentificatie weer terug bij de oude zaakidentificatie uit RGBZ1: 
https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/zaak#Attribuutsoort_Zaakidentificatie

(afgezien van het feit dat bronorganisatie een ander formaat heeft dan de oude gemeentecode).
Het vervelende is dat veel leveranciers hier in de praktijk nogal creatief mee om springen (mild uitgedrukt) en de splitsing in zaakidentificatie en bronorganisatie maakt het nu juist makkelijker om te valideren (denk ik).

**Comment by sergei-maertens** [comment]
Belangrijk hierbij is dat dit _maar_ om een URL gaat. De attributen `bronorganisatie` en `zaakidentificatie` blijven bestaan binnen de resource `Zaak`, het gaat er enkel om hoe we 'mooie' URLs maken. In die zin maakt het dan ook niet uit of je database ID gebruikt zoals nu, of meerdere parameters in het pad, of dat het eerder `{bronorganisatie}-{zaakidentificatie}` wordt dan `{bronorganisatie/zaakidentificatie}`. Al deze vormen doen niet af aan het REST karakter, omdat we linked data gebruiken. Systemen moeten in principe de volledige resource URL opslaan, en niet enkel de zaakidentificatie, omdat enkel de volledige URL de resource uniek vastlegt.

**Comment by zomwoof** [comment]
Ja eens. Er zijn meerdere mogelijkheden en het is uiteindelijk een kwestie van smaak. Hoe langer ik ernaar kijk, hoe minder moeite ik heb met de meervoudige pad-parameters voor identificatie. Ben benieuwd hoe anderen denken over deze conventie en of we hem uiteindelijk kunnen verzilveren in de landelijke API strategie. Het zou natuurlijk fijn zijn als iedereen op dezelfde manier met gecombineerde sleutels omgaat in API-land.

**Comment by sergei-maertens** [comment]
Zoals net gezamelijk besloten: alle resources worden via UUID ontsloten - je krijgt dus `/zaken/{uuid}` in plaats van de huidige `/zaken/{id}`.

De motivering hiervoor is:

1. `/zaken/{id}` lekt database informatie en is sequentieel
2. `/zaken/{bronorganisatie}/{zaakidentificatie}` is mooi en semantisch, echter kan dit patroon niet consistent in alle endpoints doorgevoerd worden. Een voorbeeld is `/zaakobjecten/?`, waar enkel URLs bekend zijn en de identificatie in een extern systeem/component leeft.
3. UUID is aangeraden door de DSO, het is niet-sequentieel en lekt geen database informatie. Tevens maakt het niet uit waar dit gegenereerd wordt - mogelijk kan de client deze opvoeren, of de backend genereert deze.

De 'sleutels' komen nog steeds voor in de resource, en ze kunnen nog steeds ingezet worden als zoekparameters.
