### ISSUE TITLE
indicatieLaatstGezetteStatus wordt niet berekend door ZRC

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2088]
Het attribuut Status.indicatieLaatstGezetteStatus wordt niet berekend door de ZRC maar gezet in een POST/PUT/PATCH operatie.

De omschrijving van dit veld is echter: _Het gegeven is afleidbaar uit de historie van de attribuutsoort Datum status gezet van van alle statussen bij de desbetreffende zaak._

indicatieLaatstGezetteStatus moet daarom berekend worden door de ZRC op het moment dat de status gezet wordt.

**Comment by michielverhoef** [comment]
Nog afwachten wat uit #2087 komt.

**Comment by joeribekker** [comment]
Kudos naar @sergei-maertens voor het originele bugreport op 12 augustus.

**Comment by michielverhoef** [comment]
Een nummertje maakt het nog makkelijker ..

**Comment by michielverhoef** [comment]
`indicatieLaatsGezetteStatus` moet uit de requestbody van de POST operatie gehaald worden en berekend worden aan de hand van de hoogste waarde voor `datumStatusGezet`.

Het is een "virtueel veld" en wordt berekend bij het ophalen van een status. Het hoeft niet opgeslagen te worden in de database. Dit ook om te voorkomen dat de `indicatieLaatsGezetteStatus` van de vorige laats gezette status leeg gemaakt moet worden en zo onnodige controles en acties plaats moeten vinden bij het opslaan van een nieuwe status.

**Comment by sergei-maertens** [comment]
> Een nummertje van dat originele bug report maakt het nog makkelijker ..

Dit was gemeld in de e-mail die ik je 12 augustus gestuurd had :)

**Comment by michielverhoef** [comment]
> > Een nummertje van dat originele bug report maakt het nog makkelijker ..
> 
> Dit was gemeld in de e-mail die ik je 12 augustus gestuurd had :)

Daar moet ik nog op reageren, er stond nogal wat in die mail.  :-)
