### ISSUE TITLE
Informatieobjecttype.omschrijvinggeneriek ontbreekt in Catalogi API 1.2

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2098]
Zoals ik het nu kan zien op https://catalogi-api.test.vng.cloud/api/v1/schema/#operation/informatieobjecttype_read
ontbreekt het (optionele) attribuut omschrijvingGeneriek in Informatieobjecttype.
Dit moet toegevoegd worden voor de POST, PUT, PATCH en GET operaties.

https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/attribuutsoort/informatieobjecttype.informatieobjecttype-omschrijving_generiek

**Comment by hdksi** [comment]
Bij dit attribuut hoort een omvangrijke waardenlijst (https://www.gemmaonline.nl/index.php/ZTC2_waardenlijst_%27Documenttype-omschrijving_generiek%27). Ter overweging de vraag op welke manier we bij het vullen van dit attribuut aansluiting daarbij kunnen waarborgen.

**Comment by michielverhoef** [comment]
reeds ingevoerd, het laatste commentaar van @hdksi wordt geborgd in #2348
