### ISSUE TITLE
Als ambtenaar wil ik een foutief toegevoegd document omhangen naar het correcte zaakdossier

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#21]
zodat het zaakdossier correct is en de zaakdocumenten in het correcte dossier zitten

**Comment by Hugo-ter-Doest** [comment]
@michielverhoef Kun je deze slicen naar user stories voor "document verwijderen uit een zaakdossier" en "document toevoegen aan een zaakdossier"?

**Comment by michielverhoef** [comment]
@Hugo-ter-Doest : Ik heb #696 aangemaakt voor het kunnen verwijderen van een document.
Het toevoegen van een document aan een zaak is volgens mij opgelost in #171 , moet ik daar nog een nieuwe US voor maken? Lijkt me een beetje overkill.

**Comment by Hugo-ter-Doest** [comment]
Nee, dat hoeft niet. Ik sluit deze dan af.
