### ISSUE TITLE
Hoe verwerk ik eIDAS-attributen bij het ZRC-schema 'betrokkene_identificatie_RolNatuurlijkPersoon'

### ISSUE THREAD

**Issue by joeridiederen** [VNG-Realisatie/gemma-zaken#2110]
eIDAS levert na authenticatie een aantal attributen; 

Verplicht

- Dienstverlener specifiek identificatienummer burger
- Huidige familienaam of –namen
- Tussenvoegsel(s) (wanneer aanwezig)
- Huidige voornaam of –voornamen
- Geboortedatum

Optioneel

- Familienaam of –namen bij geboorte
- Voornaam of –namen bij geboorte
- Geboorteplaats
- Huidig adres
- Geslacht

**Huidige familienaam**
Als deze persoon aan een zaak gekoppeld moet worden lijkt er een kleine discrepantie op basis van het eIDAS attribuut 'Huidige familienaam of –namen' in relatie tot het attribuut 'Geslachtsnaam' in het ZRC-schema betrokkene_identificatie_RolNatuurlijkPersoon. Waar het ZRC-schema lijkt te verwijzen naar de geboortenaam, levert eIDAS de naam die in ZRC-schema de samenvoeging 'Geslachtsnaam' in combinatie met 'Aanduidingnaamgebruik'. 

De optionele attributen kunnen niet allemaal verwerkt worden. 

**Verblijfsadres**
Het verblijfsadres wordt als een enkele string aangeleverd, terwijl de ZRC-api per adresregel unieke input wenst (wplWoonplaatsNaam, aoaPostcode, etc). 

**Geboorteplaats**
Het veld geboorteplaats komt niet voor in het ZRC schema van betrokkene_identificatie_RolNatuurlijkPersoon. 

<div class="OutlineElement Ltr SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXW167551770 BCX8" paraid="802564463" paraeid="{3fa91f96-c4b7-4903-9875-b4ae919db0e3}{181}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; white-space: pre-wrap; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;"><span class="EOP SCXW167551770 BCX8" data-ccp-props="{}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 12pt; line-height: 20.5042px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"> </span></p></div><div class="OutlineElement Ltr SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TableContainer Ltr SCXW167551770 BCX8" style="margin: 2px 0px 2px -5px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; position: relative; display: flex; justify-content: flex-start;"><div id="{72d4e664-886a-4f89-8049-a1d54f80ecf9}{201}" class="WACAltTextDescribedBy SCXW167551770 BCX8" aria-hidden="true" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; position: absolute; visibility: hidden; z-index: -100;"></div>

Omschrijving | eIDAS ID | ZRC-API
-- | -- | --
Huidige familienaam of familienamen | FamilyName | **
Huidige voornaam of voornamen | FirstName | voornamen
Geboortedatum | DateOfBirth | geboortedatum
Unieke identificatiecode | EntityConcernedID:BSN | anpIdentificatie
Familienaam of familie- namen bij geboorte* |   | geslachtsnaam
Voornaam of voornamen bij geboorte* |   | **
Geboorteplaats* |   | **
Adres*** en * |   | ***
Geslacht* |   | geslachtsaanduiding

</div></div><div class="OutlineElement Ltr SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXW167551770 BCX8" paraid="96353370" paraeid="{834d3b9b-cbf8-42fb-9d52-6d7a04ebc584}{222}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; white-space: pre-wrap; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;"><span data-contrast="auto" xml:lang="NL-NL" lang="NL-NL" class="TextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; font-size: 12pt; line-height: 20.5042px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"><span class="NormalTextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;"></span></span><span class="EOP SCXW167551770 BCX8" data-ccp-props="{}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 12pt; line-height: 20.5042px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"> </span></p></div><div class="OutlineElement Ltr SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXW167551770 BCX8" paraid="148865771" paraeid="{834d3b9b-cbf8-42fb-9d52-6d7a04ebc584}{226}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; white-space: pre-wrap; font-weight: normal; font-style: italic; vertical-align: baseline; font-kerning: none; background-color: transparent; color: rgb(68, 84, 106); text-align: left; text-indent: 0px;"><span data-contrast="none" xml:lang="NL-NL" lang="NL-NL" class="TextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: rgb(68, 84, 106); font-size: 9pt; font-style: italic; line-height: 15.1083px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">Toelichtingen:</span><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;"> </span></span><span class="LineBreakBlob BlobObject DragDrop SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 9pt; line-height: 15.1083px; font-family: WordVisiCarriageReturn_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; color: rgb(68, 84, 106);"><span class="SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; white-space: pre !important;"> </span><br class="SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; white-space: pre !important;"></span><span data-contrast="none" xml:lang="NL-NL" lang="NL-NL" class="TextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: rgb(68, 84, 106); font-size: 9pt; font-style: italic; line-height: 15.1083px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">*</span><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">Bij een optioneel attribuut </span><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">(*) </span><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">bepaalt de </span><span class="SpellingError SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-repeat: repeat-x; background-position: left bottom; background-image: url(&quot;data:image/gif;base64,R0lGODlhBQAEAJECAP////8AAAAAAAAAACH5BAEAAAIALAAAAAAFAAQAAAIIlGAXCCHrTCgAOw==&quot;); border-bottom: 1px solid transparent;">inlogger</span><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;"> of die data doorgegeven mag worden.</span><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;"> Bij toestemming mag de </span><span class="SpellingError SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-repeat: repeat-x; background-position: left bottom; background-image: url(&quot;data:image/gif;base64,R0lGODlhBQAEAJECAP////8AAAAAAAAAACH5BAEAAAIALAAAAAAFAAQAAAIIlGAXCCHrTCgAOw==&quot;); border-bottom: 1px solid transparent;">inlogger</span><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;"> verwachten dat de data daadwerkelijk </span><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">verwerkt </span><span class="NormalTextRun SCXW167551770 BCX8" data-ccp-parastyle="caption" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">wordt.</span></span><span class="EOP SCXW167551770 BCX8" data-ccp-props="{&quot;134245418&quot;:true,&quot;335559739&quot;:200}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 9pt; line-height: 15.1083px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; color: rgb(68, 84, 106);"> </span></p></div><div class="OutlineElement Ltr SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXW167551770 BCX8" paraid="1007896408" paraeid="{834d3b9b-cbf8-42fb-9d52-6d7a04ebc584}{252}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; white-space: pre-wrap; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;"><span data-contrast="none" xml:lang="NL-NL" lang="NL-NL" class="TextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: rgb(68, 84, 106); font-size: 9pt; font-style: italic; line-height: 15.1083px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"><span class="NormalTextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">** Geen onderdeel van </span><span class="NormalTextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">de metadata van </span><span class="SpellingError SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-repeat: repeat-x; background-position: left bottom; background-image: url(&quot;data:image/gif;base64,R0lGODlhBQAEAJECAP////8AAAAAAAAAACH5BAEAAAIALAAAAAAFAAQAAAIIlGAXCCHrTCgAOw==&quot;); border-bottom: 1px solid transparent;">object_identificatie_RolNatuurlijkPersoon</span></span><span data-contrast="none" xml:lang="NL-NL" lang="NL-NL" class="TextRun Footnote BlobObject DragDrop SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; position: relative; font-variant-ligatures: none !important; color: rgb(68, 84, 106); font-size: 7pt; font-style: italic; line-height: 15.1083px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"><span class="Superscript SCXW167551770 BCX8" data-fontsize="9" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; white-space: pre !important; background-color: inherit; vertical-align: super;">2</span></span><span data-contrast="none" xml:lang="NL-NL" lang="NL-NL" class="TextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; color: rgb(68, 84, 106); font-size: 9pt; font-style: italic; line-height: 15.1083px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"><span class="NormalTextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">, lijkt </span><span class="NormalTextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">een samenvoeging van ‘geslachtsnaam’ in combinatie met ‘</span><span class="SpellingError SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; background-repeat: repeat-x; background-position: left bottom; background-image: url(&quot;data:image/gif;base64,R0lGODlhBQAEAJECAP////8AAAAAAAAAACH5BAEAAAIALAAAAAAFAAQAAAIIlGAXCCHrTCgAOw==&quot;); border-bottom: 1px solid transparent;">aanduidingnaamgebruik</span><span class="NormalTextRun SCXW167551770 BCX8" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">’, waarvan die laatste geen onderdeel is van datzelfde zrc-schema</span></span><span class="EOP SCXW167551770 BCX8" data-ccp-props="{}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 9pt; line-height: 15.1083px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; color: rgb(68, 84, 106);"> </span></p></div>

De vraag; is er een richtlijn voor de mapping van eIDAS-attributen richting de ZRC-API?

**Comment by michielverhoef** [comment]
Het antwoord is kort en simpel: Niet. 

Het blokje betrokken_identificatie is een tijdelijke mogelijkheid om te kunnen verwijzen naar een betrokkene in een register wat nog niet via een API ontsloten wordt.  Bijvoorbeeld een gegevensmagazijn. De betrokkene_identificatie bevat de zogenaamde StUF matchinggegevens (vroeger kerngegevens geheten) die ook gebruikt kunnen worden om met een StUF bericht een NP, NNP, VES etc. op te vragen. Het is dus een structuur afkomstig uit de oude StUF ZKN berichten.

Het blok betrokkene_identificatie is dan ook niet bedoeld om gegevens in op te slaan maar om de sleutel te vormen tot een register waar de gegevens opgeslagen zijn. 


NB in reactie op de mapping: bsn is niet de anpIdentificatie. anpIdentificatie is de Ander Natuurlijk Persoon identifcatie, de identificatie voor niet-ingezetenen. Mensen zonder bsn.  Het bsn wordt opgenomen in het attribuut inpA_nummer.
