### ISSUE TITLE
DRC 1.2: verzendingen geschikt maken voor VTH-communicatie

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#2113]
In https://documenten-api.test.vng.cloud/api/v1/schema/#operation/verzending_create is alleen plaats is voor postadressen. 
Maar de meeste VTH-correspondentie is niet via post en wel via andere kanalen? (e-mail, mijnoverheid, mijn-…..site, ….)

Voorstel tot uitbreiding met de volgende velden:

- richting (inkomend, uitgaand, intern) 
- kanaal (vrije tekst)
- emailadres 
- telefoonnummer 

Verder is contactpersoon nu verplicht maar niet altijd is er een contactpersoon. Voorstel: contactpersoon niet verplicht maken

**Comment by shazada** [comment]
Dit lijkt op de kanalen van de referentielijst, voor een zaak is dat ook te gelimiteerd. 
https://referentielijsten-api.vng.cloud/api/v1/schema/

Lijkt me interessant om een entiteit toe te voegen met extra info, adres, email, telefoon, etc. Of inderdaad basic zoals voorgesteld wordt en een losse veld.

**Comment by michielverhoef** [comment]
@johannesbattjes  Een Verzending is geen contactmoment. Waar zou een telefoonnummer voor gebruikt worden? Of worden ook Whatsapp/SMS berichten opgeslagen in het DMS?

**Comment by ArjanKloosterboer** [comment]
> Een Verzending is geen contactmoment.

Waar staat dat? Of is het nu niet opgenomen in de modellering en hebben we op dit punt voortschrijdend inzicht?

**Comment by RickBalvers** [comment]
Ik weet uit de praktijk dat er inderdaad contactmomenten zijn via whatsapp en soms nog sms berichten. Bij whatsapp komt het voor dat hiermee ook informatieobjecten worden gedeeld tijdens zo een contactmoment. Deze contactmomenten met eventuele verzending van informatieobjecten wil je bij de zaak kunnen registreren. Uit ervaring weet ik dat bij rechtszaken ook om deze contactmomenten en informatieobjecten gevraagd kan worden. Dit is over het algemeen niet de gebruikelijke wijze voor verzending voor informatieobjecten. Dit komt echter wel vaak voor tijdens spoedeisende behandeling van zaken zoals controle uitvoeren in het kader van ongewone voorvallen en incidenten.

**Comment by michielverhoef** [comment]
Dat kan ik me voorstellen, dat je een contactmoment bij een zaak wilt kunnen registreren. Dat doe je met de [Contactmomenten API](https://contactmomenten-api.vng.cloud/api/v1/schema/) 

Dit issue gaat echter over Verzending. Dit wordt geregistreerd bij het informatieobject. Maar als ik het goed begrijp worden informatieobjecten soms gedeeld via whatsapp en is daarvoor het telefoonnummer nodig.

@MatthijsBekendam

**Comment by michielverhoef** [comment]
Telefoonnummer is nu onderdeel van resource Verzending in de Documenten API:
https://documenten-api.vng.cloud/api/v1/schema/#tag/verzendingen/operation/verzending_retrieve
