### ISSUE TITLE
Als ontwikkelaar wil ik snel inzicht in de verschillende versies van de API's

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2116]
Zodat ik eenvoudig oudere dan de laatste versie van een OAS kan raadplegen.

Voorstel: geef op bijvoorbeeld https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/ links naar alle versies dus in het geval van DRC naar
•	1.0
•	1.1 (laatste officiële)
•	1.2 (in voorbereiding)

**Comment by WilliamRoxit** [comment]
Als er ook nog bij vermeld wordt welke versies actueel en supported moeten zijn, en welke niet meer supported zijn zou het helemaal top zijn.

**Comment by michielverhoef** [comment]
Een goede aanvulling, dank!

**Comment by michielverhoef** [comment]
Een overzicht van de versies staat op: 
https://vng-realisatie.github.io/gemma-zaken/standaard/versions
