### ISSUE TITLE
API documentatie Catologi API niet duidelijk voor zaaktype.indicatieInternOfExtern

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/gemma-zaken#2119]
In de API documentatie van de Catalogi API staat het volgende beschreven onder indicatieInternOfExtern:

---
string (Indicatie intern of extern)
Enum: "intern" "extern"
Een aanduiding waarmee onderscheid wordt gemaakt tussen ZAAKTYPEn die Intern respectievelijk Extern geïnitieerd worden. Indien van beide sprake kan zijn, dan prevaleert de externe initiatie.

Uitleg bij mogelijke waarden:

- inkomend - Inkomend
- intern - Intern
- uitgaand - Uitgaand
---

Uitleg bij mogelijke waarden is een beetje vreemd. Ik zou hier verwachten een toelichting bij de genoemde enum "intern", "extern".

**Comment by michielverhoef** [comment]
Ik denk dat dit een fout is. Wanneer ik in ImZTC 2.2 kijk zie ik het volgende:

https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/enumeration/indicatieinternextern

Definitie: Opsomming van waarden van de aanduiding waarmee onderscheid wordt gemaakt tussen waar een ZAAKTYPEn geïnitieerd wordt.

Waarden enumeratie:
| Extern | de aanleiding voor het starten voor de zaak ligt buiten de zaakbehandelende organisatie
| -- | --
| Intern | de aanleiding voor het starten voor de zaak ligt binnen de zaakbehandelende organisatie



Ook in ImZTC 2.1 staat eigenlijk hetzelfde:
https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/zaaktype.indicatie_intern_of_extern

Definitie | Een aanduiding waarmee onderscheid wordt gemaakt tussen ZAAKTYPEn die Intern respectievelijk Extern geïnitieerd worden.
-- | --
Waardenverzameling | - ‘Intern’ (de aanleiding voor het starten voor de zaak ligt binnen de zaakbehandelende organisatie) - ‘Extern’ (de aanleiding voor het starten voor de zaak ligt buiten de zaakbehandelende organisatie)


De vraag is dus waar de genoemde uitleg bij de mogelijke waarden (die zo wie zo niet overeenkomen met de waarden van de enumeratie) vandaan komt.  Ik ga het na maar krijg nu het idee dat het een foutje in het genereren van de OAS is.

**Comment by michielverhoef** [comment]
@joerivrij kun jij nagaan waar het stukje uitleg vandaan komt in de OAS? Voor zover ik het terug kan vinden in de code wordt alleen een enumaratie InternExtern (https://github.com/VNG-Realisatie/catalogi-api/blob/cc6cd3cf86442377477cf59a30d7811a8c077cd2/src/ztc/datamodel/choices.py#L30) gebruikt., Maar het lijkt er op dat RichtingChoices (https://github.com/VNG-Realisatie/catalogi-api/blob/cc6cd3cf86442377477cf59a30d7811a8c077cd2/src/ztc/datamodel/choices.py#L35) de boel vervuilt?

Uitleg bij mogelijke waarden:

inkomend - Inkomend
intern - Intern
uitgaand - Uitgaand

**Comment by michielverhoef** [comment]
https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/enumeration/indicatieinternextern

Definitie: Opsomming van waarden van de aanduiding waarmee onderscheid wordt gemaakt tussen waar een ZAAKTYPEn geïnitieerd wordt.

Waarden enumeratie:

Extern	de aanleiding voor het starten voor de zaak ligt buiten de zaakbehandelende organisatie
Intern	de aanleiding voor het starten voor de zaak ligt binnen de zaakbehandelende organisatie

Ook in ImZTC 2.1 staat eigenlijk hetzelfde: https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/zaaktype.indicatie_intern_of_extern
 
Definitie	Een aanduiding waarmee onderscheid wordt gemaakt tussen ZAAKTYPEn die Intern respectievelijk Extern geïnitieerd worden.
Waardenverzameling	- ‘Intern’ (de aanleiding voor het starten voor de zaak ligt binnen de zaakbehandelende organisatie) - ‘Extern’ (de aanleiding voor het starten voor de zaak ligt buiten de zaakbehandelende organisatie)



@MatthijsBekendam Ik denk dat dit in de description fout zit, het gaat om zaaktype.indicatieInternOfExtern

**Comment by michielverhoef** [comment]
Dit is een documentatiefout en deze wordt hersteld in de OAS yaml. In de referentie implementatie is alleen de enum `intern` of `extern` mogelijk.
