### ISSUE TITLE
Aandachtspunt 'Toekomstig ontwikkelproces' 

### ISSUE THREAD

**Issue by RvdKlip** [VNG-Realisatie/gemma-zaken#212]
Gemeenten en VNG doen in dit traject ervaring op in de totstandkoming van een nieuwe standaard en referentie implementatie via een agile/scrum aanpak. 

Vraag is wat na afronding van de laatste sprint aan structuur over blijft, om ten eerste de ZDS 2.0 standaard door te ontwikkelen en ten tweede andere standaarden op gelijksoortige wijze te gaan ontwikkelen. Blijven we dit op deze manier doen?

Als het antwoord 'ja' is, moet de toegankelijkheid van de methodiek verbeterd worden om te zorgen dat gemeenten gemakkelijk kunnen participeren en _aangehaakt_ blijven. In mijn ogen essentieel om de meerwaarde 'medeverantwoordelijkheid users in eindresultaat' niet te verliezen. 

Dus, als de methodiek blijvend gebruikt gaat worden, dan moeten we in vervolgtrajecten zorgen dat de User-rol met zo min mogelijk drempels kan deelnemen:

Toegankelijkheid:
- overzichtelijkheid opgeleverd, onderhanden, in wachtrij
- overzichtelijkheid persoonlijke to do 
- geen cursus nodig hebben om dingen toe te voegen / aan te passen / een review te doen / standaard office documenten toe te voegen / bullets in de tekst te zetten 
- geen verwarrend gebruik van slack ernaast  
- geen insiders-termen moeten gebruiken als pull/push/md/branche/impedement/merge 

Participeren:
Ondersteuning organiseren (VNG taak?) voor User mbt:
- architectuur beschrijvingen maken
- vertalingen naar bestaande informatiemodellen, gegevensmodellen, UML's, etc (feitelijk de Gemma referentie architectuur)
- implementeren van referentiecomponenten.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest  sorry voor de spam Eelco had deze Out-of-scope geplaatst maar graag nog even jouw visie

**Comment by Hugo-ter-Doest** [comment]
Is buiten scope inderdaad, en kan bij het beheerteam worden opgevoerd: https://github.com/VNG-Realisatie/api-beheer
