### ISSUE TITLE
Als Developer en als aansluitende leverancier wil ik support voor GraphQL zodat ik minder requests hoef te doen

### ISSUE THREAD

**Issue by shazada** [VNG-Realisatie/gemma-zaken#2128]
# Improvement Story

Op dit moment moet een Client via de REST API soms wel 5 requests doen om informatie terug te krijgen
Dit kan veel slimmer door bijv. GraphQL implementeren.
Dit kan 2 dingen oplossen:

1. De hoeveelheid data die over de lijn gaat, er gaat in 1x meer of juist heel weinig data over de lijn
2. Performance wordt verbeterd

Bij sommige klanten hebben we een workaround door de data in SOLR of ElasticSearch te dumpen en daar deze data uit te halen.
Echter is dit maatwerk en willen we vanaf.

[assign aan teamlid en voeg label 'improvement story' toe]

**Comment by michielverhoef** [comment]
In team Asterix wordt gekeken naar hoe de API's in de toekomst opgezet moeten worden. Het is niet ondenkbaar dat bevragen en schrijven van gegevens op andere manieren opgelost worden dan nu het geval is. REST is niet heilig. Het is echter te vroeg om nu al in de oplossingsrichting te schieten door specifieke formaten als de oplossing te vragen.

> Op dit moment moet een Client via de REST API soms wel 5 requests doen om informatie terug te krijgen


Als ik  dit als de eigenlijke vraag achter de vraag zie (er zijn teveel calls nodig om een zaak op te halen) dan is dit ticket een doublure van bijvoorbeeld #1013 .

Hoewel ik het als een belangrijk signaal zie sluit ik dit issue toch. We zijn er mee bezig maar gaan het goed doen in plaats van ad hoc een formaatje toevoegen.
