### ISSUE TITLE
JWT tokens met kid 

### ISSUE THREAD

**Issue by Dadinos** [VNG-Realisatie/gemma-zaken#2133]
Ik zou graag via de **kid** parameters in de header van de JWT de verificatie willen doen welk secret er gebruikt kan worden bij meerdere consumers van onze CommonGround API.

Er is een mechanisme beschikbaar waar op basis van de kid parameters het secret kan worden gematched en dan kan worden gebruikt voor de jwt decodering.

> kid (key id)
> If the security layer in your app uses just one algorithm for signing the JWTs, you don't have to worry about the alg parameter, because you are always checking integrity of the token with the same key and algorithm. If however, your app uses a bunch of different algorithms and keys, you need to be able to figure out which the token was signed with.
> 
> As we saw earlier, relying on the alg parameter alone may lead to some... inconveniences. However, if your application maintained a list of key/algorithm pairs, and each of the pairs had a name (id), you could add that key id to the header and then during verification of the JWT you would have more confidence in picking the algorithm. That's what goes into the kid header parameter - the id of the key your app used to sign the token. The id is arbitrary and it's up to you to assign it. What's most important here - you gave the id, so you can verify it.
> 

Nu wordt er op basis van de client_id bepaald met één secret voor alle consumers wie de client is.
Ik zou graag een secretkey willen gebruiken per consumer van de API's.

Is het zinvol om deze **kid** parameters als een standaard (required) te voorzien in de JWT header?

**Comment by michielverhoef** [comment]
Wat mij betreft klinkt dit goed. Doorontwikkeling van de huidige Autorisaties API is echter buiten scope van de huidige ZGW ontwikkelingen en zou in een breder verband (lees: voor meer dan alleen ZGW) opgepakt moeten worden.

**Comment by michielverhoef** [comment]
ik sluit dit issue omdat het buiten scope van de kern API's voor ZGW is.
