### ISSUE TITLE
Logviewer

### ISSUE THREAD

**Issue by Dadinos** [VNG-Realisatie/gemma-zaken#2137]
Is het mogelijk de https://notificaties-api.vng.cloud/logviewer/ pagineer baar te maken.
Duurt nu erg lang met het laden van bijna 1 miljoen notificaties in één keer.

**Comment by michielverhoef** [comment]
Zoals ik het nu zie zijn de logs gepagineerd en lijkt het issue opgelost.

**Comment by Dadinos** [comment]
Het is nog niet opgelost.
Alles wordt (> miljoen) geladen en ondanks dat er paginering onderstaat worden deze iedere keer opnieuw geladen 🫣
