### ISSUE TITLE
Als archiefbeheerder wil ik eenvoudig zaken vinden die gearchiveerd moeten worden

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#2139]
...zodat de recordmanagers en archivarissen hun werk kunnen doen.

Er was al heel veel toegevoegd, zoals einddatum(gt/lt) maar we willen meer :)
Ten behoeve van o.a. archivering zouden een aantal extra query parameters nodig zijn:

Filters in Zaken API:

* [ ] bronorganisatie__in (lijst van...)
* [ ] zaaktype__in (lijst van... dacht dit wel gezien te hebben maar zie het niet meer in 1.3)
* [ ] einddatum__isnull (lege einddatum zaken zijn niet relevant voor archiveren)
* [ ] archiefactiedatum__isnull (lege archiefactiedatum is wel relevant voor archiveren)

Ordering in Zaken API:

* [ ] "einddatum", "-einddatum" 
* [ ] "publicatiedatum", "-publicatiedatum" 
* [ ] "archiefactiedatum", "-archiefactiedatum" 
* [ ] "registratiedatum", "-registratiedatum" 
* [ ] "identificatie", "-identificatie"

Het minnetje betekent omgekeerde volgorde.

Rationale: Deze toevoegingen zijn in samenwerking met recordmanagers en archivarissen van Delft, Utrecht, Rotterdam en Hoorn opgesteld.

Volgens mij een kleine aanpassing maar zou heel fijn zijn omdat het hier gaat over ALLE zaken (in tegenstelling tot veel usecases waar het gaat om zaken van 1 zaaktype of 1 betrokkene)

**Comment by michielverhoef** [comment]
De parameter zaaktype_in (met lijst van UUIDs) kan gebruikt worden in de operatie zaak_zoek:
https://zaken-api.vng.cloud/api/v1/schema/#tag/zaken/operation/zaak__zoek

Dit jaar gaan we over op vele kleine releases waarin we snel dingen oppakken in plaats van verzamelen en aan het eind van het jaar een grote release uit te brengen. Dit ticket willen we gebruiken om als eerste op te pakken en hiervoor in februari een release uit te brengen.

Hoewel het geen heel spannend ontwerp zal zijn gaat @HenriKorver dit van de week bekijken en dan kan @MatthijsBekendam dit volgende week oppakken en Zaken API 1.4.0 eind van de sprint gereleased worden.

**Comment by michielverhoef** [comment]
Is het trouwens ook handig om zaken aan de hand van een lijst met zaakidentificaties op te halen? Dus identificatie_in, analoog aan uuid_in?

**Comment by michielverhoef** [comment]
Uitwerking in #2161

**Comment by HenriKorver** [comment]
@joeribekker Bij deze de draft OAS in [redoc-view](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/HenriKorver-patch-zaken-1.4.x/api-specificatie/DESIGN/zaken/1.4.x/openapi.yaml#tag/zaken/operation/zaak_list) met de toegevoegde filters voor archivering. In deze versie is de query parameter `zaaktype__in`  een lijst met URL's van zaaktypen. Hierdoor kan de omvang van de  totale URL voor de GET-aanroep erg groot worden als je op veel zaaktypen wilt filteren en mogelijk de limiet van de maximale URL-lengte overschrijden. 

Dit probleem is op te lossen door zaaktypen te identificeren op basis van het kleinere veld `identificatie` in plaats van `url`. In dat geval wordt het gedrag van de API ingewikkelder. Dan moeten eerst de  `url`-waarden van de zaaktypen behorende bij de `identificatie`-waarden van het zaaktypen uit de Catalogi API opgehaald worden alvorens de Zaken API de filtering kan uitvoeren. Hierbij moet de Zaken API ook op de hoogte zijn van welke Catalogi API er gebruik gemaakt wordt als er meerdere zijn.

Een andere oplossing is om de lijst van url's van de te filteren zaaktypen mee te geven in de body van het bericht i.p.v. in de URL. In dat geval wordt de bevraging een POST-operatie. Dit gaat wel tegen de REST principes in, dus dat doe je alleen als er geen andere mogelijkheden meer zijn.

**Comment by HenriKorver** [comment]
> Een andere oplossing is om de lijst van url's van de te filteren zaaktypen mee te geven in de body van het bericht i.p.v. in de URL. In dat geval wordt de bevraging een POST-operatie.

Na gesprek met @joeribekker en @michielverhoef is gekozen voor de hierboven geciteerde oplossing.  De volgende wijzigingen zijn doorgevoerd:

1. De voorgestelde query parameters voor archivering zijn toegevoegd als zoekvelden aan het `zaak__zoek`-bericht (POST-operatie voor het uitvoeren van complexe zoekopdrachten  op zaken). 

2. De volgende velden zijn toegevoegd om dit bericht in lijn te krijgen met de query parameters van het `zaak_list`-bericht (GET-operatie om zaken op te vragen):
    - registratiedatum
    - registratiedatum__gt
    - registratiedatum__lt
    - einddatum
    - einddatum__isnull
    - einddatum__gt
    - einddatum__lt
    - einddatumGepland
    - einddatumGepland__gt
    - einddatumGepland__lt
    - uiterlijkeEinddatumAfdoening
    - uiterlijkeEinddatumAfdoening__gt
    - uiterlijkeEinddatumAfdoening__lt

3. De parameters voor archivering zijn ook toegevoegd aan het `zaak_list`-bericht (GET-operatie om zaken te bevragen) behalve de parameter "zaaktype__list" omdat die niet geschikt is als query parameter.

Als het goed is zijn de twee berichten voor het bevragen van zaken (de Get en POST) nu volledig symmetrisch op twee velden na:

- uid__in
- zaaktype__in

Deze twee zoekvelden zijn alleen in de body opgenomen van het POST-bericht omdat ze anders als query parameter van het GET-bericht de URL kunnen opblazen tot over de maximale limiet.

De nieuwe 1.4.0 versie van de OAS kan bekeken worden in [Redoc](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/HenriKorver-patch-zaken-1.4.x/api-specificatie/DESIGN/zaken/1.4.x/openapi.yaml).
De wijzigingen t.o.v. de 1.3.1 versie zijn te vinden in de [PR](https://github.com/VNG-Realisatie/gemma-zaken/pull/2161/commits/49e550a26121ecb5f90541ff1b0300580a409f62).

**Comment by joeribekker** [comment]
Dat ziet er goed uit @HenriKorver, hiermee kunnen we verder.

**Comment by HenriKorver** [comment]
@MatthijsBekendam Zie mijn reviewcommentaar: https://github.com/VNG-Realisatie/zaken-api/pull/257#issuecomment-1450159416

**Comment by HenriKorver** [comment]
@MatthijsBekendam Ik kwam deze melding tegen bij het testen met Postman:

```
{
    "type": "[https://zaken-api.test.vng.cloud/ref/fouten/ValidationError/"](https://zaken-api.test.vng.cloud/ref/fouten/ValidationError/%22),
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:f4305732-a823-45ac-8720-4aaab972067a",
    "invalidParams": [
        {
            "name": "nonFieldErrors",
            "code": "unknown-parameters",
            "reason": "Onbekende query parameters: archiefactiedatum__isnull"
        }
    ]
}
```

**Comment by michielverhoef** [comment]
@MatthijsBekendam dit mag uitgerold worden naar productie

**Comment by michielverhoef** [comment]
https://zaken-api.vng.cloud/api/v1/schema/#tag/zaken/operation/zaak__zoek


Filters in Zaken API:

* [ x] bronorganisatie__in (lijst van...)
* [ x] zaaktype__in (lijst van... dacht dit wel gezien te hebben maar zie het niet meer in 1.3)
* [ x] einddatum__isnull (lege einddatum zaken zijn niet relevant voor archiveren)
* [ x] archiefactiedatum__isnull (lege archiefactiedatum is wel relevant voor archiveren)

Ordering in Zaken API:

* [x ] "einddatum", "-einddatum" 
* [ x] "publicatiedatum", "-publicatiedatum" 
* [ x] "archiefactiedatum", "-archiefactiedatum" 
* [ x] "registratiedatum", "-registratiedatum" 
* [ x] "identificatie", "-identificatie"
