### ISSUE TITLE
Als functioneel beheerder wil ik dat een zaaktype nog geen einddatum heeft zodat ik deze nog kan wijzigen

### ISSUE THREAD

**Issue by vwmvanbeek** [VNG-Realisatie/gemma-zaken#2141]
# Impediment

Heren! (en Demi (collega FB) in de CC),

Gisteren ben ik tegen een boel werk aangelopen om in https://openzaak-zgw.test.denhaag.nl/ een zaakType te kopierën, danwel bijna identiek als nieuw zaakType toe te voegen en deze dan ook meteen als deelzaak te koppelen.

Naast het vele typewerk zijn de problemen die je hiermee creëert voor lopende (al in productie zijnde) zaken enorm. Alle objecten (zaak, informatieobject)  worden beëindigd, zijn tijdelijk niet beschikbaar (voor nieuwe zaken) en eigenlijk nooit meer beschikbaar (voor al lopende zaken), want ze zijn beëindigd. Dit houdt in dat alle zaken van ons nu bevroren zijn in de toestand waarin ze nu zitten in Centric Leefomgeving (auw). Ik heb gistermiddag contact gehad met Alex en op het einde kwam het er op neer dat je dit ook niet via de userinterface moet doen maar via de API, “want dan kan wel wat je wilt”.

Dit is natuurlijk niet goed te beheren. Ten eerste weet (wist) ik deze werkwijze als beheerder van mijn zaakType niet, en daarnaast kan ik toevallig wel bij de API, maar hoe ik dit mijn collega uit ga leggen die ook zaakTypes toe gaat voegen?

Als je het doet met wat de userinterface biedt dan krijgt je ongewild de indruk dat het moet zoals de UI het aan mogelijkheden biedt. Maar ondertussen blijkt dat de UI beperkter is dan wat mogelijk is, maar je dus ook op het verkeerde spoor zet, met alle gevolgen van dien als iemand (dus per ongeluk) toch een object van een einddatum voorziet omdat ze veronderstellen een nieuw object te moeten maken omdat de UI bepaalde wijzigingen van een actief object niet toestaat.

Van Alex begreep ik dat dit niet (hoog) op de prioriteitenlijst staan. 

Daarnaast is het eerst moeten beëindigen van een object voordat je een nieuwe (als CONCEPT) kunt maken en inrichten geen prettige werkwijze, want je kunt niet eerst alles klaarzetten en inrichting omdat ondertussen je gebruikers dat object niet kunnen gebruiken! Graag zou ik zien dat er pas een einddatum van een object ingevuld hoeft te worden als een concept gepubliceerd wordt  en niet als deze wordt aangemaakt.

Het inrichten van OpenZaak is een niet te onderschatten klus op dit moment ook om andere UI redenen die ik nu even achterwege laat. OpenZaak is meer dan API’s…

Met vriendelijke groet,

Geert-Jan Pes
Functioneel beheerder senior, Informatievoorziening / Team vergunningen
06 52 51 32 63

**Comment by vwmvanbeek** [comment]
Issue was reeds opgenomen op andere backlog, duplicaat

**Comment by michielverhoef** [comment]
> Issue was reeds opgenomen op andere backlog, duplicaat

Het issue is al opgelost in Catalogi API 1.2
