### ISSUE TITLE
Zaken API voldoet niet aan API Design Rule 51

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#2142]
# Bug

Omdat de Zaken API de OAS-specificatie niet op de goede locatie publiceert voldoet deze niet aan de verplichte design rule [API-51](https://publicatie.centrumvoorstandaarden.nl/api/adr/1.0/#api-51). Hierdoor voldoet de Zaken API niet aan de Landelijke API Strategie en krijgt de Zaken API geen 100% score op [deverloper.overheid.nl](https://developer.overheid.nl/apis/vng-zrc/score-detail).  Doordat de OAS niet kan worden gevonden kunnen ook twee andere design rules niet worden gecheckt waardoor de score beperkt blijft tot 4 uit 7.

Dit probleem geldt waarschijnlijk ook voor de andere API's uit de ZGW-familie.

**Comment by michielverhoef** [comment]
https://zaken-api.vng.cloud/api/v1/schema/openapi.yaml 

Dit werkt gewoon, de API specificatie van de Zaken API is op deze manier te bereiken (download in je browser, als je de Redoc wilt zien is https://zaken-api.vng.cloud/api/v1/schema/  voldoende) .  Op dezelfde manier is de openapi.yaml op te vragen voor de Documenten API, Catalogi API en Besluiten API.

Volgens mij kan dit issue gesloten worden?

**Comment by HenriKorver** [comment]
Volgens API-51 moet de de openapi.yaml of openapi.json direct achter de base url, dus zonder tussenkomst van de term "schema". Dus zo:

https://zaken-api.vng.cloud/api/v1/openapi.yaml

of zo

https://zaken-api.vng.cloud/api/v1/openapi.json

**Comment by joerivrij** [comment]
Dit is een instelling maar die wordt in code gezet. Dat betekent dat dit voor elke API aangepast zou moeten worden. 

```python
                # API documentation
                url(
                    r"^schema/openapi(?P<format>\.json|\.yaml)$",
                    SchemaView.without_ui(cache_timeout=settings.SPEC_CACHE_TIMEOUT),
                    name="schema-json",
                ),
                url(
                    r"^schema/$",
                    SchemaView.with_ui(
                        "redoc", cache_timeout=settings.SPEC_CACHE_TIMEOUT
                    ),
                    name="schema-redoc",
                ),
```

**Comment by terborg** [comment]
Het beheer en de ontwikkeling van de referentie-implementaties is stopgezet. Dit issue wordt daarom gesloten.
