### ISSUE TITLE
Link op https://vng-realisatie.github.io/gemma-zaken/standaard/autorisaties/index werkt niet

### ISSUE THREAD

**Issue by EduardWitteveen** [VNG-Realisatie/gemma-zaken#2163]
# Bug

Op de pagina https://vng-realisatie.github.io/gemma-zaken/standaard/autorisaties/index staat een url met de tekst: "Tutorial autorisatie" naar de locatie: https://vng-realisatie.github.io/gemma-zaken/standaard/autorisaties/gemma-zaken/content/ontwikkelaars/handleidingen-en-tutorials/_assets/autorisatie.pptx 
De presentatie bestaat niet op de genoemde plek.

**Comment by michielverhoef** [comment]
Opgelost met #2164
