### ISSUE TITLE
[VRAAG] Op welke wijze kan een Consumer de URI's opvragen van de versies van een bepaald functioneel zaaktype?

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#2189]
**Use Case**
Als Consumer wil ik via ZGW API (1.4.x) 'GET / zaken' een lijst van zaken van een bepaald zaaktype opvragen van een burger. 

**Vraag**
Omdat het niet mogelijk is om te selecteren op basis van functionele gegevens van het zaaktype (Omschrijving, Zaaktypecode,..) maar enkel op basis van URI's van zaaktypen moet een vraag gesteld worden aan de Catalogi API. 

Een voorbeeld van een functioneel geformuleerde vraag is 'Geef me de URI's van alle zaaktypen-versies van het zaaktype met zaaktypecode 834 die sinds 1-11-2022 actief waren'.
De toevoeging van de datum is gedaan om niet alle versies van het zaaktype terug te krijgen maar enkel de versies vanaf een bepaalde datum. Dus de Consumer verwacht de versie die op 1-11-2022 actief was én alle versies na 1-11-2022.

Op welke wijze kan die vraag via ZGW API's gesteld worden aan Catalogi? 

Of zit ik op de verkeerde weg?

**Comment by michielverhoef** [comment]
https://catalogi-api.vng.cloud/api/v1/schema/#tag/zaaktypen/operation/zaaktype_list

> Omdat het niet mogelijk is om te selecteren op basis van functionele gegevens van het zaaktype (Omschrijving, Zaaktypecode,..) maar enkel op basis van URI's van zaaktypen moet een vraag gesteld worden aan de Catalogi API.

Filteren kan op basis van zaaktypeidentificatie,  de "Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt." 

Door te filteren op zaaktypidentificatie krijg je een lijst van alles versies van een bepaald zaaktype. Eventueel kan dit nog gecombineerd worden met de datumGeldigheid om de vraag `Geef me de URI's van alle zaaktypen-versies van het zaaktype met zaaktypecode 834 die sinds 1-11-2022 actief waren.` te beantwoorden.
