### ISSUE TITLE
Betrokkene velden niet conform RGBZ 2.0/RSGB 3.0

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/gemma-zaken#2193]
Het valt ons op dat meerdere velden in de ZGW API's niet conform onderliggende informatiemodellen zijn, waaronder RGBZ 2.0 en/of RSGB 3.0, namelijk:

- rol.betrokkene.verblijfsadres.aoaIdentificatie: max. 100 karakters (AN100) in Zaken API vs. max. 16 karakters (AN16) in RGBZ 2.0
- rol.betrokkene.verblijfsadres.aoaPostcode: max. 7 karakters (AN7) in Zaken API vs. max. 6 karakters (AN6) in RGBZ 2.0
- rol.betrokkene.verblijfsadres.inpLocatiebeschrijving:  max. 1000 karakters (AN1000) in Zaken API vs. max. 35 karakters (AN35) in RGBZ 2.0
- rol.betrokkene.verblijfsadres.gorStraatnaam (AN24) ontbreekt volledig

Dit resulteert in fouten bij opslag in de database die wel conform RGBZ en RSGB zijn aangemaakt en in communicatie via StUF (backward compatibility).

Bovenstaande geldt voor Natuurlijke personen als voor Vestigingen.

Daarnaast verbaast het mij dat voor Niet-natuurlijke personen ervoor gekozen is juist het bezoekadres helemaal niet op te splitsen in de losse attributen, maar volledig tot één property terug te brengen namelijk rol.betrokkene.bezoekadres (AN1000).

**Comment by michielverhoef** [comment]
De API's voor Zaakgericht werken zijn nooit gemaakt om backwards compatible met StUF en de informatiemodellen RGBZ/RSGB etc. te zijn.  Dus ook niet om geïmplementeerd te worden bovenop een oude database die informatie nog op de oude manier structureert.

De architectuur van het gegevenslandschap/Common Ground is ook niet bedoeld om zowel StUF als API's te bedienen.  Een transitie zou dan bijvoorbeeld per proces van oud naar nieuw overgezet kunnen worden waarbij de communicatie ofwel StUF blijft (in de oude systemen en oude vakapplicatie) of API's (met de nieuwe systemen en nieuwe vakapplicatie).

Beide standaarden (StUF en API's) ondersteunen is niet te doen, ze passen niet op elkaar en het is ook niet de bedoeling om de API standaarden te laten beperken door oude modellen. Het is dus een breaking change.

**Comment by basretera** [comment]
Ik snap het antwoord maar het doet geen recht aan de problematiek die ik schets. Ik noemde nu de informatiemodellen RGBZ en RSGB. Ik had ook gewoon kunnen noemen dat het niet voldoet aan hoe de informatie in de Basisregistratie voor Adressen en Gebouwen (BAG) aanwezig is. En dat het niet voldoet aan Haal Centraal BAG bevragen of Haal Centraal BRP bevragen. Het matcht gewoon niet en zal in de toekomst gewoon leiden tot issues. Daar wil ik voor waken en zodoende deze melding.

**Comment by michielverhoef** [comment]
Als je bedoelt dat gegevens opgeslagen in de Zaken API niet in de BAG of BRP passen: Daar zijn deze gegevens ook niet voor bedoeld.  

Een Rol is een relatieklasse tussen Roltype en Betrokkene. In de Zaken API is dit gecombineerd tot de resource Rol. Normaal gesproken zou een Rol een verwijzing naar een roltype en een verwijzing naar een betrokkene bevatten. Dat zijn de attributen `roltype` en `betrokkene`.  Ten tijde van het maken van de Zaken API  was er nog geen registratie om naar te verwijzen voor betrokkenen. De rol.betrokkeneIdentificatie is bedoeld als tijdelijke maatregel om bijvoorbeeld aan te sluiten op een gegevensmagazijn wat nog met StUF ontsloten kan worden. Daarom staan hier de oude StUF matchinggegevens (voorheen kerngegevens)  in. Het is nooit de bedoeling geweest een betrokkene in zijn geheel op te kunnen nemen in een Rol.

NB. Persoonlijk vind ik dat de betrokkeneIdentificatie uit de Rol gehaald moet worden. Betrokkene verwijst dan naar "iets" en dat "iets" mag best een tijdelijk register zijn dat Betrokkenen koppelt aan gegevens in een gegevensmagazijn of HaalCentraal of ...   Dan blijft de Zaken API zuiver zoals die zijn moet en leggen we dit soort problemen neer waar ze moeten worden belegd. Het scheelt ook een hoop qua beveiliging van gegevens die eigenlijk niets met Zaken te maken hebben.
