### ISSUE TITLE
Als persoon of vertegenwoordiger van een persoon met een of meer zaken bij de/ een overheid  wil ik een overzicht van de zaken bij de/ een overheid waarbij ik betrokken ben (mijn zaken)

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#22]
zodat ik een volledig beeld kan krijgen van klantcontacten die in het kader van de afhandeling van een zaak hebben plaatsgevonden

**Comment by michielverhoef** [comment]
Voorwaarde voor #8 Een klantcontact kunnen raadplegen

**Comment by ArjanKloosterboer** [comment]
Wat is hier de user-story? Waarom wil iemand een klantcontact relateren aan een zaak? Het antwoord op die vraag brengt ons al dichter bij de user-story.

**Comment by TCIMEddy** [comment]
@ehotting Volgens mij ook al meerdere keren benoemd. US moet iig scherper

**Comment by ehotting** [comment]
Ja, veel user stories uit de eerste paar dagen zijn te vaag. Deze is dubbel.
