### ISSUE TITLE
Verbeteren opvragen Zaakgegevens met expand/grote berichten

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2205]
Kapstok  issue voor het toepassen van een expand/include mechanisme in de Zaken API

Gerelateerde issues:
#389 
#523 
#932 
#1013 
#1268 
#1686 
#1890 
#1961

**Comment by HenriKorver** [comment]
Het voorstel hoe we het expand-mechanisme willen gaan vormgeven is [hier](https://github.com/VNG-Realisatie/gemma-zaken/discussions/1960#discussioncomment-3662403) beschreven. Een concept uitwerking van de OAS is te vinden in pull request https://github.com/VNG-Realisatie/gemma-zaken/pull/2192.

**Comment by joerivrij** [comment]
Kunnen we voor nu (ivm tests) een afspraak maken over max lengte van de expansion query en hoe diep je mag gaan?

Het maakt me niet zoveel uit wat dit wordt maar dan kan ik daar tests op klaar zetten. @michielverhoef @HenriKorver meningen?

**Comment by michielverhoef** [comment]
Opgenomen in Zaken API 1.5.0
