### ISSUE TITLE
Demo sprint 2 (voorbereiding en uitvoering)

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#221]

**Comment by RitaBerghuis** [comment]
@TCIMEddy , kun je de taakverdeling van afgelopen donderdag mbt de sprint demo hier aan toevoegen?

**Comment by RitaBerghuis** [comment]
<img width="457" alt="demo programma" src="https://user-images.githubusercontent.com/40032082/43080637-a7cc9d64-8e7f-11e8-884e-8778777d8c0a.png">
