### ISSUE TITLE
API specificatie Notificaties niet bereikbaar

### ISSUE THREAD

**Issue by AHNRoxit** [VNG-Realisatie/gemma-zaken#2213]
De Redoc en Swagger definities van de Notificaties api zijn niet beschikbaar vanaf de pagina https://vng-realisatie.github.io/gemma-zaken/standaard/notificaties/. Ik kan ook geen andere toegang vinden. De link naar de json werkt wel

**Comment by michielverhoef** [comment]
Bedankt voor het doorgeven, het probleem is nu opgelost.

Mocht er weer iets niet goed staan is de redoc van de huidige versie bereikbaar via https://notificaties-api.vng.cloud/api/v1/schema/ .

De verschillende versies staan ook in github: https://github.com/VNG-Realisatie/gemma-zaken/tree/master/api-specificatie 
Wanneer je het volgende stukje voor de raw weergave van de OAS plakt krijg je de redoc: 
`https://redocly.github.io/redoc/?nocors&url=`

Let op, `nocors&` is nodig wanneer je chrome als browser gebruikt, firefox werkt ook zonder.
