### ISSUE TITLE
Hoe om te gaan met CMIS als toegang voor een DRC

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#223]
In de huidige Zaak- Documentservices staat CMIS voorgeschreven als verplicht voor het DMS/DRC. Dit staat ook in de beschrijving van de DRC in GEMMA 2 en op de pas-toe-of-leg-uit klijst van het forum standaardisatie (https://www.forumstandaardisatie.nl/standaard/cmis) 

CMIS is niet REST-ful en past als zodanig niet in de architectuur maar is wel verplicht. 

Hoe gaan we hier mee om?

**Comment by sergei-maertens** [comment]
Doordat we met linked data werken, is er behoefte aan een RESTful API voor DRC, en die is er ook op dit moment: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/drc/openapi.yaml

In ZDS 1.2 werden ook berichten geformuleerd die naar CMIS vertaald moesten worden, dat kan hier op dezelfde manier. Wat achter deze API zit maakt niet zoveel uit, de DMS backend kan prima Alfresco zijn met daarop een REST-API laagje.

Andere (bestaande) software kan dan nog steeds CMIS (SOAP gebaseerd) gebruiken om direct Alfresco aan te spreken indien dat nodig/wenselijk is (en dat is het, vermoed ik).

**Comment by michielverhoef** [comment]
Kleine vergissing van mijn kant, CMIS kent wel degelijk RESTFUL bindings, zie ook http://docs.oasis-open.org/cmis/CMIS/v1.1/cs01/CMIS-v1.1-cs01.html . Deze bindings zijn echter niet volgens het RGBZ gemodelleerd.

In de huidige ZDS 1.x standaard wordt CMIS gebruikt om vanuit het Zaaksysteem (ZS) een DMS aan te spreken. De documentserviceconsumer (de vakapplicatie of DSC) gebruikt StUF berichten om met het ZS te communiceren. In het ZS wordt opgeslagen welke zaakdocumenten bij een bepaalde zaak horen om zo relevante documenten uit het DMS op te kunnen halen, via CMIS. Communicatie tussen DSC en CMS verloopt dus via het ZS als intermediair.

De DRC component zou een dergelijke intermediair rol kunnen vervullen (vertaling DRC API naar CMIS en andersom) maar is dat ook gewenst? Of maken we dan niet onnodig veel API calls terwijl een ZRC ook direct via CMIS het DMS kan benaderen?

**Comment by sergei-maertens** [comment]
Ik zie ook precies die rol als intermediair voor me, en dan precies om die reden dat de voorkeur gaat naar het opslaan van de relatie tussen documenten en zaken in het DRC.

De RESTful bindings van CMIS zijn niet zo netjes. In het Haarlem ZS maken we hiervan gebruik, en het is eigenlijk niet veel meer dan een hack bovenop hun SOAP services. Daarenboven komt dat hiervoor geen OAS 3.0 specificatie beschikbaar is (en dat is wat we moeten opleveren).

Met de ervaringen van ZDS 1.2 wordt ook maar een kleine subset van CMIS gebruikt, dus het is wel prettig als je via het DRC de scope klein kan houden.

**Comment by ehotting** [comment]
Consequentie is dat een DRC (component uit GEMMA 2)  zowel CMIS moet ondersteunen als ZDS 2.0, waarbij dat laatste een kleine subset van CMIS betreft omgezet naar API volgens OAS 3. Dat laatste wordt niet geleverd door bijv. Alfresco, en wordt dus een kleine toevoeging die er naast staat. Klopt dat?

**Comment by ehotting** [comment]
Ik begrijp dit graag beter, wellicht een toelichting van @sergei-maertens tijdens een refinement

**Comment by RvdKlip** [comment]
Voor Rdam is het ook belangrijk om inzicht te krijgen op de wijzigingen in deze integratiepatronen. 

We gebruiken nu ook Alfresco onderliggend aan taakapplicaties en integreren nu via CMIS, webdav, Rest API (https://docs.alfresco.com/5.2/concepts/dev-platform-integration-arch.html) en niet te vergeten AOS (Alfresco Office Services), de integratiemethode met Microsoft Office. Waar in dit spel zit straks de API?

**Comment by michielverhoef** [comment]
Ik denk dat hier binnenkort wel een overleg over gevoerd zal worden maar de API wordt de toegang tot de opslag van informatieobjecten in de DRC. De referentie-implementatie van de DRC gebruikt geen CMIS of Alfresco maar in principe is het heel goed mogelijk om een DRC te bouwen die de informatieobjecten opslaat in Alfresco. In dat geval is de API één van de kanalen waarmee Alfresco benaderd kan worden. 
Wanneer taakapplicaties de API gaan gebruiken kunnen zij dan op die manier koppelen met Alfresco waar zij voorheen op een andere manier koppelden (één van de door jou genoemde manieren). Dit zou natuurlijk een sterke voorkeur hebben :-)

Tenminste, zo zie ik het maar verbeter me gerust.

**Comment by Hugo-ter-Doest** [comment]
Ik sluit deze met out of scope. Gemeente Utrecht realiseert een adapter die DRC API vertaalt naar CMIS.

**Comment by michielverhoef** [comment]
Begrijpelijk. Vanuit beheer is het denk ik wel goed om tzt met gemeente Utrecht te kijken of de adapter een toevoeging kan worden op de standaard. Maar dat komt wel als het zover is.
