### ISSUE TITLE
Als gebruiker wil ik met in 1 aanroep meer informatie zien over documenten

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2235]
Zodat ik niet apart gerelateerde informatie als informatieobjecttype etc. hoef op te vragen.

Expand mogelijkheid in de Documenten API

**Comment by HenriKorver** [comment]
@MatthijsBekendam  De volgende elementen moet geëxpandeerd kunnen worden.

/enkelvoudiginformatieobjecten

- informatieobjecttype
- bestandsdelen.url

/gebruiksrechten

- informatieobject

/objectinformatieobjecten

- informatieobject
- object

/verzendingen

- betrokkene
- informatieobject

**Comment by michielverhoef** [comment]
Doorgevoerd in Documenten API 1,4,0
