### ISSUE TITLE
Link naar de api spec voor verschillende API's werkt niet

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#2236]
# Bug

De URL's naar de API spec (redoc en swagger) op https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/ leidt tot een 404.
Idem voor https://vng-realisatie.github.io/gemma-zaken/standaard/besluiten/besluiten/redoc-1.0.1 op de besluiten pagina.

**Comment by michielverhoef** [comment]
Er stond een `/catalogi` teveel in het pad naar de bewiste pagina's, excuses. Opgelost met https://github.com/VNG-Realisatie/gemma-zaken/pull/2237

**Comment by CMasselink** [comment]
@michielverhoef kan je de besluiten API spec ook nog fixen? Zelfde probleem denk ik...

**Comment by michielverhoef** [comment]
In de Documenten API docs stond ook nog zo'n foutje. Beide heb ik opgelost in #2238
