### ISSUE TITLE
DRC: verbod op aanpassen informatieobject laten vervallen

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#2241]
Wij stellen voor business rules die verbieden documenten te wijzigen te laten vervallen. Op dit moment is de regel dat definitieve documenten niet mogen worden gewijzigd.

Motivatie:
In de VTH-praktijk moeten er altijd wijzigingen worden doorgevoerd op metadata, ook bij definitieve documenten, maar ook bij het archiveren (statusovergang). Ook de inhoud van de documenten wijzigt zonder dat er daarbij verder één woord verandert in het document. Denk aan stempelen, ondertekenen of het invullen van een verzenddatum. Binnen dit ticket noemen we dit voor het gemak “technisch wijzigen”. Wie wat mag aanpassen verschilt per type applicatie, rol, gebruiker, documenttype en zaakfase. Het is ondoenlijk om dit in business rules voor de DRC vast te leggen door de hoeveelheid variabelen en situaties, maar ook omdat de DRC geen kennis heeft van deze variabelen en dus niets kan afdwingen of toetsen. Stel bijvoorbeeld dat de regel is: “uitgaande documenten mogen alleen technisch gewijzigd worden om een verzenddatum er in te plaatsen door een proceduremedewerker”. De DRC bevat op dit moment geen informatie om dit te toetsen. Bovendien kan in een andere situatie de regel weer anders zijn en elk domein en elke consumer kan andere business logica vereisen. Het is dus noodzakelijk de regels voor het mogen wijzigen aan de apps/TSA’s over te laten. 

Concreet houdt ons voorstel in de dikgedrukte regel te laten vervallen:

Wijziging: DRC-010:
Bijwerken van documenten ([drc-010](https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/#drc-010))
overgenomen uit de openapi.yaml Bij het werken wordt gevalideerd of:
•	Een correcte lock waarde aanwezig is (zie ([drc-009](https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/#drc-009))
•	**De status NIET definitief is**
•	**Het informatieobjecttype niet gewijzigd wordt**

Wijziging: Redoc bijwerken bij PUT en PATCH:
Er wordt gevalideerd op
•	correcte lock waarde
•	**status NIET definitief**

Dit voorstel is gezamenlijk voorbereid door de volgende organisaties:
Gemeente Tilburg
ODMH
Gemeente Maastricht
Avolve Software
Visma Roxit

**Comment by mjvanantwerpen** [comment]
Vanuit de gemeente Noord-Beveland ondersteunen we dit voorstel

**Comment by michielverhoef** [comment]
In Documenten API 1.3.x is het al mogelijk om het informatieobjecttype te wijzigen: [DRC010](https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/#drc-010) . In de [PATCH ](https://documenten-api.vng.cloud/api/v1/schema/#tag/enkelvoudiginformatieobjecten/operation/enkelvoudiginformatieobject_partial_update)en [PUT ](https://documenten-api.vng.cloud/api/v1/schema/#tag/enkelvoudiginformatieobjecten/operation/enkelvoudiginformatieobject_update) operaties is dit al mogelijk.

Dan blijft over de controle op `status`  met waarde `niet definitief`.

**Comment by michielverhoef** [comment]
Doorgevoerd in Documenten API 1.4.0
