### ISSUE TITLE
Als ontwikkelaar wil ik dat in de aanvullende sepcificaties beschreven staat hoe met bestandsdelen om te gaan

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2257]
Ticket hernoemd omdat het inmiddels wel duidelijk(-achtig) is hoe met bestandsdelen omgegaan moet worden maar de beschrijving duidelijker kan.

Oorspronkelijke tekst:

Uit de header van de OAS van de Documenten API:
`Uploaden van bestanden

Binnen deze API bestaan een aantal endpoints die binaire data ontvangen, al dan niet base64-encoded. Webservers moeten op deze endpoints een minimale request body size van 4.0 GiB ondersteunen. Dit omvat de JSON van de metadata EN de base64-encoded bestandsdata. Hou hierbij rekening met de overhead van base64, die ongeveer 33% bedraagt in worst-case scenario's. Dit betekent dat bij een limiet van 4GB het bestand maximaal ongeveer 3GB groot mag zijn.

Nieuw in 1.1.0

Bestanden kunnen groter zijn dan de minimale die door providers ondersteund moet worden. De consumer moet dan:

- Het INFORMATIEOBJECT aanmaken in de API, waarbij de totale bestandsgrootte meegestuurd wordt en de inhoud leeggelaten wordt. De API antwoordt met een lijst van BESTANDSDEELen, elk met een volgnummer en bestandsgrootte. De API lockt tegelijkertijd het INFORMATIEOBJECT.
- Het bestand opsplitsen: ieder BESTANDSDEEL moet de bestandsgrootte hebben zoals dit aangegeven werd in de response bij 1.
Voor elk stuk van het bestand de binaire data naar de overeenkomstige BESTANDSDEEL-url gestuurd worden, samen met het lock ID.
- Het INFORMATIEOBJECT unlocken. De provider valideert op dat moment dat alle bestandsdelen correct opgestuurd werden, en voegt deze samen tot het resulterende bestand.`

Volgens de uitleg is het dus alleen mogelijk om een **nieuw**  informatieobject groter dan 4GB aan te maken. Het is dus niet mogelijk om een informatieobject te laten groeien of een placeholder aan te maken die later nog gevuld kan worden met een inhoud groter dan 4GB, bijvoorbeeld na het scannen of genereren van een document via Documentcreatieservices.

Het is ook niet mogelijk om dan alvast maar een informatieobject met meerdere bestandsdelen aan te maken omdat de bestandsgrootte mee gegeven moet worden en die is nog niet bekend.

In de PUT of PATCH operaties is het gedrag zoals bij de POST operatie niet beschreven maar er zou wel een mogelijkheid moeten zijn om een document gaandeweg te laten groeien en alsnog op te kunnen splitsen in bestandsdelen.  

In het verlengde hiervan: Ook wanneer een informatieobject met bestandsdelen is aangemaakt is het niet mogelijk het aantal bestandsdelen uit te breiden of te laten krimpen. 

De enige oplossing zou dus zijn een nieuw informatieobject aan te maken middels een POST maar dan krijg je een nieuwe url met nieuw UUID. Eventuele verwijzingen naar het oude informatieobject worden dan niet bijgewerkt en het oude informatieobject wordt dan getoond.

**Comment by MNIJ** [comment]
In de huidige implementaties die ik ken (in ieder geval Open Zaak en de Roxit implementatie van de DRC) is dit al gewoon mogelijk. Het uploaden in bestandsdelen werkt daarin niet alleen op de POST voor de initiele creatie, maar ook op de PUT en PATCH om een nieuwe versie te uploaden. En dat geldt zowel voor een bestand waarvan de initiele versie als BASE64 is geupload als voor een bestand dat al initieel met bestandsdelen is geupload.

En dat is ook essentieel. Want nadat de upload voltooid is, is er op API niveau geen verschil meer tussen een via BASE64 geupload document en een in bestandsdelen geupload document. De bestandsdelen bestaan alleen tijdens de upload. 
Als het alleen via de POST mogelijk zou zijn om in bestandsdelen te uploaden, dan zou je dus ook nooit meer een nieuwe versie kunnen toevoegen aan een eerder geupload groot bestand.

Dus volgens mij is hier helemaal geen probleem, hooguit in de uitleg van het werken met bestandsdelen.

**Comment by michielverhoef** [comment]
> Dus volgens mij is hier helemaal geen probleem, hooguit in de uitleg van het werken met bestandsdelen.

Dit is nou juist de functie van een standaard dus als dat niet duidelijk beschreven is komen er interpretaties en wijken implementaties van elkaar af. 

Ik zeg niet dat het niet op te lossen is maar in de standaard staat het niet beschreven.

**Comment by sfdreverman** [comment]
Het gaat hier over het tijdelijk opsplitsen van een bestand voor transport. Per consumer kan het verschillen (door stabiliteit en max doorvoer van verbinding) welke grootte bestandsdeel het beste werkt. Het is daarom logischer als de consumer de provider vertelt:
- Wat de totale bestandsgrootte is (Hoeveel bytes gaan worden ontvangen)
- In hoeveel delen dit opgestuurd gaat worden
- Wat de hash van het complete bestand is (controle of het eindresultaat goed is ontvangen)

De provider geeft dan een sleutel terug onder welke de bestandsdelen opgestuurd kunnen worden. Deze sleutel heeft een geldigheidsduur (om de provider niet eeuwig te laten wachten als de consumer afziet van opsturen). De consumer kan de bestandsdelen onder deze sleutel opsturen. De provider plakt de delen aan elkaar en slaat dit bij succes op als één bestand.

Elk bestandsdeel kan ook begeleid worden door een hash zodat ook per bestandsdeel duidelijkheid is over de correctheid van de ontvangen data. (OK / NOK per deel)

De voornaamste redenen om het zo te doen zijn performance en stabiliteit van de verbinding die per consumer verschillend kunnen zijn. Als je 3GB gaat up-/downloaden dan houdt dat een verbinding vrij lang bezet. Dat is voor kleinere, drukkere of oudere verbindingen niet optimaal. Als de provider dit bepaalt dan zijn alle consumers afhankelijk van de zwakste schakel.

NB dit kan ook voor het downloaden worden gedaan. Dus: 
- Consumer laat weten dat het bestand X in delen van xxxMB (of in y delen) wil downloaden
- Provider geeft het aantal delen, de hash en de links voor download van de bestandsdelen

**Comment by MNIJ** [comment]
> De vraag komt natuurlijk niet voort uit of een DMS hier mee om kan gaan, dat staat ook niet in de vraag.
> 
> De vraag is: Het staat niet in de standaard beschreven, moet dit kunnen en zo ja hoe? In de standaard dus, niet hoe je dit in een DMS implementeert.
> 
> Na een zoveelste keer de beschrijving te hebben gelezen zag ik deze regel staan:
> 
> 'Het bijwerken van een INFORMATIEOBJECT heeft een gelijkaardig verloop.'
> 
> Op basis hiervan snap ik de uitleg van @MNIJ .

Dus daarmee staat het al correct beschreven in de standaard en is dit dus inderdaad helemaal geen issue.

**Comment by michielverhoef** [comment]
> Dus daarmee staat het al correct beschreven in de standaard en is dit dus inderdaad helemaal geen issue.


Correct als "niet fout", dat klopt. Maar wat mij betreft is de omschrijving wel voor verbetering vatbaar. Bovendien moet de beschrijving niet in de header van de OAS staan maar in de aanvullende specificaties met bedrijfsregels en mogelijk een uitgebreidere tutorial.

**Comment by michielverhoef** [comment]
Opgelost in Documenten API 1.4.0:  https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/
