### ISSUE TITLE
Omgaan met fouten bij het ophalen van gerelateerde gegevens met expand

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2259]
Bij het ophalen van gegevens uit de Zaken API of Documenten API met expand worden er gerelateerden opgehaald, onder andere uit de Catalogi API. Het kan voorkomen dat er een fout optreedt. Bijvoorbeeld omdat niet de juiste rechten meegegeven worden in het token of omdat de Catalogi API down is.

Er zijn verschillende manieren om hier mee om te gaan:

1. Alleen een foutmelding teruggeven en verder geen resultaten
2. Alleen het resultaat van de GET list/retrieve operatie, bijvoorbeeld de Zaak of het Informatieobject. Geen gerelateerden, in de plaats daarvan wordt een foutmelding gegeven
3. Er worden zoveel mogelijk gerelateerden opgehaald en teruggegeven. Waar het niet lukt om een gerelateerde terug te geven wordt een foutmelding gegeven.
4. ?

Welke optie zouden we absoluut wel/niet moeten kiezen en waarom?

**Comment by MNIJ** [comment]
Wat ons betreft is optie 1) de meest voor de hand liggende. Dus gewoon een foutmelding teruggeven.

Dat is namelijk:

- Het meest zuiver en eenduidig
- Het eenvoudigst te implementeren in de services
- Het eenvoudigst te beschrijven en dus het minste kans op interpretatie- en implementatieverschillen
- Voor de consumer ook het meest eenduidig, deze vraagt immers niet voor niks deze data op, dus als die niet meekomt is het een foutsituatie

In optie 2) en 3) wordt het al snel veel complexer. Wat moet bijvoorbeeld de http status code zijn? Het is geen succes, dus geen 200 en geen bad request dus geen 400. Je kan dan werken met 207 multi-status, maar dat past niet binnen REST API's.

**Comment by sfdreverman** [comment]
Eens met MNIJ, de eenvoudigste oplossing is vaak de beste: Laat de service een foutmelding teruggeven als deze niet aan het request kan voldoen.

**Comment by michielverhoef** [comment]
Opgenomen in Zaken API 1.5.0
