### ISSUE TITLE
Minimum en maximum diepte expand, hoe diep?

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2260]
In #2192  staat beschreven dat een consumer zelf kan bepalen welke gerelateerden opgehaald moeten worden met expand.
Dit helemaal vrij laten brengt risico's met zich mee. Te diep te veel gerelateerden opvragen maakt het mogelijk met 1 aanroep de hele API omver te trekken. Aan de andere kant moet er wel een zinvolle diepte opgevraagd kunnen worden zodat de consumer ook de informatie op kan vragen die nodig is.

```
Zaak
	zaaktype
	status
		statustype
	gerelateerdeZaak
		zaaktype
		status
			statustype

```			

In bovenstaand voorbeeld is het mogelijk een zaak met onderliggende gerelateerden (`Status`, `Rol`, `gerelateerdeZaak` etc.) op te vragen en hiervan ook de bijbehorende ZTC informatie. Scope van de opdracht is de zaak die opgevraagd is. Wil ik meer weten over de `gerelateerdeZaak` dan vraag ik die op met de bijbehorende gerelateerden.

Wanneer we de Zaak als niveau 0 beschouwen zou `Statustype` van de gerelateerde zaak niveau 3 hebben. Een expand van 3 diep dus.
Dit zou het minimum niveau moeten zijn wat opvraagbaar moet kunnen zijn voor een consumer. Let wel, de consumer hoeft dit niet per se op te vragen maar het kan. De grote vraag is hoe diep is een expand nog zinvol? Bovenstaande situatie lijkt me nog redelijk vaak kunnen voorkomen, hoeveel dieper komen leveranciers in de praktijk tegen?

**Comment by MNIJ** [comment]
Ik zie ook geen scenario's waar je dieper dan niveau 3 moet gaan, die je niet beter op een andere manier kan oplossen. Eigenlijk vind ik 3 al veel, maar is inderdaad wel nodig voor dit voorbeeld met de status van een een gerelateerde zaak.

Het is al twijfelachtig of het wel verstandig is om in één call de data van een zaak + alle gerelateerde zaken op te halen. Maar om dat scenario te vermijden zou het handig zijn om wel met één call alle gerelateerde zaken van een zaak op te halen. Om daar dan bijv. statustype van te kunnen tonen heb je nog maar twee niveaus inclusion nodig.

Dat zou een nieuwe query parameter vereisen op `GET Zaken?gerelateerdAanZaak={zaak-url}` en is dus ook een andere story dan deze.

**Comment by michielverhoef** [comment]
Opgenomen in Zaken API 1.5.0
