### ISSUE TITLE
Expand op zaken api werkt niet bij ophalen van een specifieke zaak

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#2268]
`https://zaken-api.test.vng.cloud/api/v1/zaken/c9603037-0427-4f1b-a0ce-3c56c86e58c7?expand=zaaktype.statustypen&expand=status
`
geeft alleen de zaak terug.

`https://zaken-api.test.vng.cloud/api/v1/zaken?expand=zaaktype.statustypen`

geeft in _expand de gewenste extra informatie terug.

**Comment by HenriKorver** [comment]
Bug opgelost
