### ISSUE TITLE
JWT Token Issuer & maxVertrouwelijkheidsaanduiding

### ISSUE THREAD

**Issue by sfdreverman** [VNG-Realisatie/gemma-zaken#2273]
De maxVertrouwelijkheidsAanduiding wordt bij het genereren van een token met de Token Issuer niet meegegeven, maar staat wel in de voorbeelden (op de github). Kan deze toegevoegd worden bij het genereren van een JWT Token met de Token-issuer?

NB Dit is een requirement voor de Documenten API:
o	Een User heeft een maxVertrouwelijkheidsaanduiding. Deze wordt gezet door de consumer.
o	Een Document heeft een Vertrouwelijkheidsaanduiding. Deze wordt gezet door de consumer.
o	Bij het ophalen controleert de provider (Documenten API) of gegeven User het Document mag inzien mbv bovenstaande.

**Comment by joerivrij** [comment]
Hallo Stefan,

De scopes staan toe dat je een maxVertrouwelijkheidsaanduiding meegeeft. De huidige implementatie van autorisatie (https://github.com/VNG-Realisatie/autorisaties-api) en het aanmaken en controleren van tokens geeft dit veld niet mee in  het token. 

Wat er gebeurt als je een call doet met een token is dat daaruit de secret en client_id worden genomen en aan de autorisatie-api wordt gevraagd of het met dit specifieke token is toegestaan een bepaalde actie uit te voeren. Daar staat de maxVertrouwelijkheidsaanduiding ook bij en de call wordt afgekeurd als je niet autorisatie niet toereikend is.

**Comment by sfdreverman** [comment]
Dus ook met de token-issuer is het nog steeds nodig om de autorisatie-api aan te roepen? (alles in JWT scheelt minimaal een call (per call) => minder afhankelijkheid, meer performance)

**Comment by joerivrij** [comment]
De token-issuer heeft als enige taak het aanmaken van een token en de registratie te doen bij de autorisatie-api en indien nodig bij de onderliggende apis.

We zijn ons bewust dat dit verre van ideaal is. Een JWT kan prima al deze data zelf in de payload dragen. Echter is dit niet het model waar voor gekozen is en dan herhaal ik wat ik in de andere issue ook zeg; dat is helaas historische bagage die wie niet zomaar aan kunnen passen.
