### ISSUE TITLE
Betekenis van UserID & ClientID binnen JWT Token (issuer)

### ISSUE THREAD

**Issue by sfdreverman** [VNG-Realisatie/gemma-zaken#2274]
Bij het genereren van een JWT met de token-issuer, komt een UserID mee (welke niet in de documentatie van github voorkomt). 

Welke betekenis hebben de ClientID en de UserID?

Is het:
o	ClientID => identificeert het consumer systeem?
o	UserID => identificeert de gebruiker (een gebruiker binnen het consumer systeem)?

**Comment by joerivrij** [comment]
user_id heeft geen waarde maar is een historisch overblijfsel. Op dit moment komt hij altijd leeg mee en je kunt hem dus negeren.

**Comment by sfdreverman** [comment]
Duidelijk. 
Impliceert dit dat de ClientID de user (de gebruiker binnen het consumer systeem) vertegenwoordigt?
Als in: Systeem X van bedrijf Y gebruikt de Common Ground API.
Bert en Anne zijn gebruikers van Systeem X.
De ClientID van Bert (plus autorisaties) wordt meegegeven in het JWT token.

(Reden van de vraag: de Documenten API heeft het ID van de gebruiker nodig voor de Audit Trail zodat getraceerd kan worden welke gebruiker wanneer welke acties op welk document hebben uitgevoerd)

**Comment by joerivrij** [comment]
De stelling klopt, de clientId wijst naar de gebruiker(s). Een Userid wordt intern gebruikt om een applicatie aan te duiden (bijvoorbeeld user_id: drc) maar dat is een ander proces.
