### ISSUE TITLE
Uniek zaaktype: Verschil tussen wijzigingen-log en OAS van Catalogi API 1.2

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#2291]
# Bug

Er lijkt een verschil te zitten tussen de CHANGELOG/Wijzigingen en de OAS-omschrijving van de Catalogi API 1.2:

According to CHANGELOG of the reference implementation:

> Change unique constraint of ZaakType.omschrijving & ZaakType.catalogus to ZaakType.identificatie & ZaakType.catalogus (https://github.com/VNG-Realisatie/gemma-zaken/issues/1639);

But in [OAS in gemma_zaken](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/ztc/1.2.x/openapi.yaml) there is no such change, it sill requires the uniqueness of ZaakType.omschrijving:

>      operationId: zaaktype_create
>      description:
>        "Er wordt gevalideerd op:\n- geldigheid `catalogus` URL, dit moet\
>        \ een catalogus binnen dezelfde API zijn\n - Uniciteit `catalogus` en `omschrijving`.\
>        \ Dezelfde omeschrijving mag enkel  opnieuw gebruikt worden als het zaaktype\
>        \ een andere geldigheidsperiode  kent dan bestaande zaaktypen.\n - `deelzaaktypen`\
>        \ moeten tot dezelfde catalogus behoren als het ZAAKTYPE."

Ik vermoed dat de OAS niet is aangepast en dat dit wel een gewenste wijziging is.

**Comment by joeribekker** [comment]
Met Michiel besproken: Lijkt inderdaad dat dit aangepast moet worden in de beschrijving.

**Comment by michielverhoef** [comment]
fixed met #2359
