### ISSUE TITLE
Lock attribuut ontbreekt in EIO.bestandsdelen in response op POST/GET/PUT/PATCH enkelvoudigeinformatieobjecten

### ISSUE THREAD

**Issue by shazada** [VNG-Realisatie/gemma-zaken#2293]
Zie ticket bij Open-Zaak project https://github.com/open-zaak/open-zaak/issues/1386
Er is een bug in de GET als er een EIO wordt aangemaakt zonder inhoud, maar wel een bestandsomvang.

Bij de get van de stukje bestandsdelen mist er een lock wat volgens de OAS een verplichte (required) veld is.

Zie extra info + voorbeelden in gerelateerde ticket.

**Comment by shazada** [comment]
https://github.com/open-zaak/open-zaak/issues/1386#issuecomment-1651437590

Er zitten verschillen tussen 1.1, 1.2 & 1.3 en de link in de readme van 1.3 verwijst naar 1.1 yaml.

**Comment by michielverhoef** [comment]
Na contact met @shazada en nog eens goed rondneuzen is duidelijk wat het probleem is. Vandaar de aanpassing van de titel van dit ticket.

Het issue is dat in de response van de Enkelvoudiginformatieobject (EIO) operaties (POST/PUT/PATCH/GET) het attribuut bestandsdelen.lock ontbreekt vanaf Documenten API 1.2.0 en hoger.  Het lock attribuut is wel aanwezig in de EIO zelf
In het endpoint /Bestandsdelen is het attribuut wel aanwezig.

Wat het lastig maakt is dat de consumer in dit geval een DRC versie 1.2.0 bevraagt en de reponse valideert tegen de OAS van DRC 1.1.0 . Je kunt je afvragen of dat correct is.

Als de situatie andersom was geweest, in 1.2.0 was een veld toegevoegd, dan was deze validatie ook niet goed gegaan. Immers, in de 1.1.0 OAS ontbreekt een attribuut wat dan in de response staat.

Het is niet verplicht volgens de standaard maar het lijkt er sterk op dat het zeker voor een consumer die een oudere versie van de API gebruikt belangrijk is aan te geven welke versie van de API gewenst is. De provider moet dan antwoord geven volgens het schema van de gevraagde versie en dan zou het lock attribuut op de verwachtte plaats hebben moeten staan.

Ik zie hier dus twee dingen:
1/ Een consumer die een reponse valideert tegen een oudere versie van het JSON schema. Dit geeft fouten.
2/ Een attribuut wat in Documenten API versie 1.2.0 verdwenen is.

Dat eerste kan ik niet oplossen vanuit de standaard. Het tweede wel. Omdat we momenteel maar zeer beperkt capaciteit hebben om de referentie implementatie aan te passen ga ik even kijken hoe dit door te voeren. In de huidige versie 1.4.0 moet het geen probleem zijn, voor 1.2.x en 1.3.x kan het zijn dat dit alleen een aanpassing in de standaard wordt. Maar daar kom ik nog op terug.

**Comment by michielverhoef** [comment]
We hebben hier naar gekeken en de korte samenvatting luidt: Doordat het lock veld van Bestandsdelen een write-only veld is werd het niet goed gegenereerd in de OAS. Versie 1.2 van de Documenten API kende inderdaad nogal wat problemen met het genereren van de OAS. 

Hiervoor wordt patches uitgebracht van de Documenten API: 1.2.2, 1.3.1 en 1.4.1. Het streven is om dit nog van de week opgelost te hebben.

**Comment by michielverhoef** [comment]
Opgelost in patches 1.2.4, 1.3.1 en 1.4.1: https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/

**Comment by shazada** [comment]
@michielverhoef ik heb ook een mail verstuurd, ik wil deze niet her-openen, maar 1.4.1 zit er in de YAML geen bestandsdelen.lock.
In 1.3.1 is de YAML wel netjes aangepast, maar de Referentie-implementatie geeft een 500 foutmelding. Daarvoor is een nieuwe issue aangemaakt.

**Comment by rderooij** [comment]
Wijziging lijkt niet zijn opgelost in patches 1.3.1 en 1.4.1. Zie ticket #2337 en #2336.

**Comment by michielverhoef** [comment]
> @michielverhoef ik heb ook een mail verstuurd, ik wil deze niet her-openen, maar 1.4.1 zit er in de YAML geen bestandsdelen.lock. In 1.3.1 is de YAML wel netjes aangepast, maar de Referentie-implementatie geeft een 500 foutmelding. Daarvoor is een nieuwe issue aangemaakt.



In de operaties van enkelvoudiginformatieobjecten staat het attribuut lock opgenomen bij de responses van de operaties (GET/POST/PUT/PATCH):
GET 
https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/swagger-ui-1.3.1#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_retrieve
https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/swagger-ui-1.4.1#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_retrieve

POST:
https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/swagger-ui-1.3.1#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_create
https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/swagger-ui-1.4.1#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_create

PATCH:
https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/swagger-ui-1.3.1#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_partial_update
https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/swagger-ui-1.4.1#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_partial_update

PUT:
https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/swagger-ui-1.3.1#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_update
https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/swagger-ui-1.4.1#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_update

**Comment by michielverhoef** [comment]
Er bleek een fout in de description van de attributen Verzenddatum en Ontvangstdatum te zitten, al in Documenten API 1.4.0, hierdoor werkte de redoc weergave niet. Dit is inmiddels ook opgelost.
