### ISSUE TITLE
[VRAAG] DRC: Why does OAS have only 1 parameter for `/enkelvoudiginformatieobjecten/_zoek` endpoint? 

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#2294]
In DRC OAS states, that `/api/v1/enkelvoudiginformatieobjecten/_zoek` endpoint can have only one property in request body: `uuid_In` 
Why does it not included query parameters from GET  `/api/v1/enkelvoudiginformatieobjecten` endpoint, such as `identificatie` and `bronorganisatie` ? 

1. The reference implementation supports these parameters for `/api/v1/enkelvoudiginformatieobjecten/_zoek` endpoint, so there is an inconsistense between OAS and the behaviour of the reference implementation
2. In my opinion if this endpoint is created solely for advanced search purposes it should support all search/filter properties like it happens with ZRC `/api/v1/zaken/_zoek` endpoint. So now there is inconsistency between DRC and ZRC `_zoek` endpoints

**Comment by joeribekker** [comment]
Besproken met Michiel: Inderdaad een bug in de specificatie, wordt aangepast want zou inderdaad alle attributen moeten bevatten waarop je (ook) kan filteren.

**Comment by michielverhoef** [comment]
@michielverhoef  testen of de RI al wel werkt, anders alleen de specs aanpassen.

**Comment by michielverhoef** [comment]
Is denk ik hetzelfde issue als #2300
