### ISSUE TITLE
[VRAAG] DRC: Properties `verzenddatum` and `ontvangstdatum` are included in 2 resources

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#2295]
In DRC 1.2 a new resource `Verzending` was introduced. I have questions about its properties `verzenddatum` and `ontvangstdatum` :

1. `Verzending` has one-to-many relation to `InformatieObject` resource which also has `verzenddatum` and `ontvangstdatum`. What is the difference between these attributes? Is there any connection or relation between them? Is there any validation between them?
2. I can't find these attributes in RGBZ - https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/verzending . Are they included in RGBZ?

**Comment by michielverhoef** [comment]
the attributes `verzenddatum` and `ontvangstdatum` of the resource `enkelvoudiginformatieobject` have become obsolete after the introduction of the resource `verzending`.

With the resource `verzending` it is possible to log for instance re-sending (including the address and the date the original sending and the resending was done).

It is best to not use the attributes on the enkelvoudiginformatieobject anymore. To prevent breaking changes we cannot remove the attributes but issue #2304 requests to make these deprecated in the OAS.

**Comment by michielverhoef** [comment]
> It is best to not use the attributes on the enkelvoudiginformatieobject anymore. To prevent breaking changes we cannot remove the attributes but issue #2304 requests to make these deprecated in the OAS.

This is also mentioned in https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/ at the end of the description of `Verzending`.

**Comment by michielverhoef** [comment]
> I can't find these attributes in RGBZ - https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/verzending . Are they included in RGBZ?

These attributes represent the relations `is verzonden aan`  (`verzenddatum`) and `is ontvangen van` (`ontvangstdatum`).  

Does this (and the answers above) answer your question?

**Comment by annashamray** [comment]
yes, thank you!
