### ISSUE TITLE
[VRAAG] DRC: Verzending properties which are absent in RGBZ

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#2296]
In DRC 1.2 a new resource Verzending was introduced. In the OAS there are properties that are not included in [RGBZ](https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/verzending ) :
   * `telefoonnummer`
   * `faxnummer`
   * `mijnOverheid`

There are also `verzenddatum` and `ontvangstdatum`, but there is already question about them - #2295

Are these properties described somewhere in RGBZ?

**Comment by michielverhoef** [comment]
The attributes 
- telefoonnummer
- faxnummer
- mijnOverheid 
 
were introduced as a result of #2113
