### ISSUE TITLE
Als ontwikkelaar wil ik duidelijkheid over wanneer een API resource "genest" moet worden...

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#230]
...zodat hier geen discussie over ontstaat.

Het gaat hier concreet over de URLs van bijvoorbeeld een Zaakstatus. Er zijn 2 manieren:

1. `/statussen/` die geeft een lijst van alle statussen van alle zaken. Deze lijst kan gefilterd worden door bijvoorbeeld aan te geven: `/statussen/?zaak=https://www.example.com/api/v1/zaak/1234`
2. `/zaken/1234/statussen/` die geeft een lijst van alle statussen van de zaak 1234 zoals besloten in de URL als verplichte parameter.

De DSO geeft aan om geneste resources te gebruiken wanneer dit logisch is. In een forum-post (van DSO) werd dan weer aangegeven om niet te diep te nesten, maar typisch 1 laag diep.
In mijn optiek is een Zaak het hoofdobject, en de meeste andere objecten hangen aan een zaak, en moeten dus genest worden. Meestal heeft het geen zin om een lijst van "alles" te verkrijgen, maar alleen "alles binnen de scope van..."

**Definition of done**
- [ ] er is een design decision gemaakt en leesbaar hieromtrent
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Taken**
- [ ] Design desicision maken en documenteren
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ArjanKloosterboer** [comment]
Wat bedoel je met 'nesten', en dan in functionele zin? Wat ik uit je toelichting begrijp is dat het bijvoorbeeld om de statussen bij een zaak gaat. Opvragen van alle statussen is m.i. zinloos, zoals je zelf ook al vermoed. Een status bestaat bij de gratie dat er een zaak is en zal veelal dan ook opgevraagd worden in de context van een zaak. Voor managementinfo kan ik me voorstellen dat er een andere informatiebehoefte is: alle zaken met een actuele status die de maximale status-doorlooptijd bijna bereikt heeft (of al overschreden heeft). Uiteindelijk bepalen de userstory's dus wat de functionele vragen zijn en stelt dat eisen aan de API's.

**Comment by joeribekker** [comment]
@sergei-maertens Prima, ik zeg doen. Maar geen prio denk ik.

Dit issue is vooral om de "genestheid" in de API te krijgen (moet via een issue/user story). Deze genestheid is nu namelijk niet het geval voor het ZRC.

> Voor managementinfo kan ik me voorstellen dat er een andere informatiebehoefte is: alle zaken met een actuele status die de maximale status-doorlooptijd bijna bereikt heeft (of al overschreden heeft).

Dat zou typisch een verzoek zijn op de Zaak resource (met filter op Zaakstatus) en staat los van de Zaakstatus resource.

> Uiteindelijk bepalen de userstory's dus wat de functionele vragen zijn en stelt dat eisen aan de API's.

Functioneel maakt het niet zo veel uit. De genestheid beperkt de op te vragen objecten per parent object. Deze beperking zouden we ook met filtering kunnen krijgen.

Logischerwijs echter voegt het opvragen van alle objecten van bepaalde objecttypes niets toe en zouden dus genest kunnen worden. Ik ben voor, en als ik @ArjanKloosterboer comment goed heb begrepen hij ook :)

**Comment by ArjanKloosterboer** [comment]
Ik kan de voor- en nadelen en consequenties van nesting t.o.v. andere constructies niet overzien dus kan er moeilijk over oordelen. Zou het een valide uitgangspunt kunnen zijn dat daar waar de unieke aanduiding van een objecttype deels bestaat uit de unieke aanduiding van een gerelateerd objecttype, dat dan nesting voor de hand liggend is (vanuit dat gerelateerde objecttype)? Let wel, uitgangspunt, geen regel!
> in het ZTC zit je al snel erg diep, maar in ZRC is echt wel de zaak het centrale object
In de ZTC is het vergelijkbaar, daar is het Zaaktype de centrale component.

**Comment by joeribekker** [comment]
Ai, nu loop ik toch net tegen een praktijk scenario aan waar de genestheid tegen werkt... (ben bezig met demo applicatie).

Het is uitermate efficient om in 1x alle Statustypes (van 1 catalogus, dat dan wel) uit bijvoorbeeld het ZTC te halen, ook al horen deze toe aan verschillende Zaaktypes. Zo hebben we namelijk een volledige mapping van URL<->Naam van alle Statustypes, en kan in een lijst van Zaken, in 1x alle StatusType namen worden weergegeven.

Anders is per Zaaktype een call nodig om de beschikbare Statustypes op te vragen.

Dat alles onder Catalogus hangt klinkt nog steeds wel logisch maar hoeft wellicht ook niet eens. Catalogus fungeert nog steeds als een filter, terwijl een gemeente meerdere catalogussen kan hebben.

**Comment by ehotting** [comment]
@joeribekker Dit puzzeltje is inmiddels opgelost toch?

**Comment by joeribekker** [comment]
Denk nog even expliciet in design keuzes zetten.

**Comment by TCIMEddy** [comment]
@joeribekker hij staat nu op de backlog (dus er zou niets mee hoeven te gebeuren) maar als het alleen een kwestie is van beschrijven design keuzes dan zou ik zeggen close ..?

**Comment by joeribekker** [comment]
Nee, pas als de design keuze is opgeschreven. Denk dat ze juist erg belangrijk is voor consistente APIs. De keuze documenteren is niet veel werk

**Comment by joeribekker** [comment]
Design keuze toegevoegd in #456
