### ISSUE TITLE
De Documenten API 1.3 heeft een _zoek endpoint met daarin een verkeerde parameter

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#2300]
# Bug

De Documenten API 1.3 (laatste versie op dit moment) heeft een afwijkende `_zoek` parameter in vergelijking met de Zaken API 1.4 (laatste versie op dit moment). Het gaat om `uuid_In` vs `uuid__in`. Ik vermoed dat dit niet bewust is gedaan en dat bij de Documenten API hetzelfde moet worden gebruikt als bij de Zaken API (dus `uuid__in` -- die was er immers al langer).

![image](https://github.com/VNG-Realisatie/gemma-zaken/assets/96970/c64e5214-3418-43ad-8c88-43f3a6309cae)

**Comment by michielverhoef** [comment]
We hebben het uitgezocht en het blijkt dat de parameter in de code wel `uuid__in` heet en zo gebruikt kan worden.  Waar het mis gaat is in de generatie van de OAS yaml. Dit kunnen we op korte termijn niet makkelijk oplossen maar we trekken het recht in de documentatie.
