### ISSUE TITLE
Documenten API specificaties moeten op een specifieke versie staan, niet op een variabele versie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#2301]
In de README van de Documenten API staan wat foutjes bij de API datums/versies. Die eindigen allemaal op `.x` maar dat moeten volgens mij concrete versies zijn. Dus in plaats van `1.3.x` -> `1.3.0`. Ik zag overigens ook dat deze naar de verkeerde versie verwees.

Zie: https://github.com/VNG-Realisatie/documenten-api

**Comment by michielverhoef** [comment]
Documentatie aangepast op de develop-branch, komt mee met de volgende release (eind september).
