### ISSUE TITLE
Als spec-beheerder wil ik dat de API-spec in gemma-zaken in sync is met de referentie-implementaties

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#232]
...zodat er geen verschillende waarheden heersen.

De referentie-implementaties worden in andere repositories ontwikkeld. Deze kunnen (in bepaalde branches) voorlopen. Daarnaast kunnen meerdere pull-requests hier verschillende wijzigingen doorvoeren, en merge conflicts daartussen zouden tot een afwijkende spec kunnen leiden. Om te garanderen dat de spec die in `master` terecht komt in sync is, is deze automatische check wenselijk.

**Definition of done**
- [ ] er is een automatische check voor:
    - [ ] zrc@master
    - [ ] drc@master
    - [ ] ztc@master
- [ ] indien er verschillen zijn, moeten deze inzichtelijk zijn/gerapporteerd worden

**Acceptatiecriteria**

- [ ] de check is semantisch - verschillende volgorde in de yaml file mag de check niet doen falen
- [ ] de check is geautomatiseerd in Jenkins
- [ ] de check wordt apart weergegeven in pull requests/commit builds

**Taken**
- [ ] Tool zoeken die de check doet [@sergei-maertens]
- [ ] Scripten van check tegen verschillende referentiecomponenten [@sergei-maertens]
- [ ] Jenkins builds configureren
    - [ ] Build voor pull-requests
    - [ ] Build voor commits op master

**Comment by TCIMEddy** [comment]
@sergei-maertens Is dit niet al mogelijk?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest visie?

**Comment by Hugo-ter-Doest** [comment]
Ja, dit is nodig. Vraag staat bij @sergei-maertens

**Comment by sergei-maertens** [comment]
het is nog niet fout gegaan tot nu toe, maar de automatische checks toevoegen zou wel fijn zijn om het extra af te dichten (detecteert menselijke fouten). Is wel wat werk om dit in te richten en ik focus liever op api-inhoud. Dit hoort meer bij het beheertraject m.i.

**Comment by joeribekker** [comment]
Mijn visie hierop is in ieder geval dat het niet zo erg is dat bijv. de master van een OAS niet gelijk loopt met de master van een referentie implementatie (of als het in 1 repository zit, dat ze uit elkaar lopen).

Wat belangrijk is, is dat er goede afspraken en uitspraken gedaan worden of wat wel bij elkaar hoort. 

Voorbeeld:

1.0.0 van de OAS moet overeenkomen met een versie van de referentie implementatie. Ik denk dat de referentie implementatie een eigen versie heeft, die daarin meeneemt welke versie van de API er in zit verwerkt.

Dit vertaald zich dan naar:

* Zaken API referentie implementatie 1.0.0 (Zaken API 1.0.0)
* Zaken API referentie implementatie 1.0.1 (Zaken API 1.0.0) // Bugfix in de implementatie, geen effect op OAS
* Zaken API referentie implementatie 1.1.0 (Zaken API 1.1.0) // OAS minor update verwerkt in implementatie
* Zaken API referentie implementatie 1.1.1 (Zaken API 1.1.1) // Patch in de OAS die ook in de referentie implementatie is verwerkt.
