### ISSUE TITLE
[VRAAG] How to fill `Rol.statussen` property?

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#2320]
In Zaken 1.3 a new read-only property `Rol.statussen` was added. What information should be displayed in this field? 
`Status` resource also doesn't have any property to add relation to the `rol`

**Comment by michielverhoef** [comment]
Rol.statussen is meant to contain the Statussen set by this particular Betrokkene in a specific Rol (https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatiesoort/rol.zet_als_betrokkene_status) . It is kind of a logging feature.

For instance if `Jan Jansen` is a Betrokkene (type `Behandelaar`) who sets the Status of the Zaak to `in behandeling` and `afgehandeld` the urls to both these Statussen will be registered in Rol.statussen.

**Comment by annashamray** [comment]
Thank you for the fast reply! Could you please specify which API endpoint should be used for it?

**Comment by michielverhoef** [comment]
That would be the /statussen/{UUID} endpoint, eg. https://zaken-api.vng.cloud/api/v1/statussen/{uuid}

**Comment by annashamray** [comment]
I can't find any Rol-related property in /statussen/{UUID} endpoint.
Could you please specify what the property is?

**Comment by michielverhoef** [comment]
That would be Status.isGezetdoor

**Comment by annashamray** [comment]
So am I correct that `Status.isGezetdoor` should be filled with the url to Rol resource in the same Zaken API? 
I was confused because in the reference implementation `Status.isGezetdoor` field doesn't have any relation to Rol. 

And I have one more question. Should be any validation added? For example, can I add any Rol to  `Status.isGezetdoor` or only the rollen which belong to the same Zaak ?

**Comment by michielverhoef** [comment]
Good question, I will add validation rules to the documentation.  I guess this was too obvious for me but it is best to describe matters clearly.

Both the `Rol` and `Status` should belong to the same `Zaak`.

**Comment by annashamray** [comment]
Ok! Thanks for clearing this out
