### ISSUE TITLE
API documentatie toont ook response body bij HEAD operaties

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/gemma-zaken#2328]
In de laatste x versies van de uitgebrachte API's zijn de HEAD operaties allemaal voorzien van een Response Body in de 200 OK response. Dit is niet correct. De HEAD operatie retourneert alleen een response header. Dit issue speelt vanaf:

- Catalogi API 1.2
- Documenten API 1.2
- Zaken API 1.3

**Comment by michielverhoef** [comment]
Scherp gezien, bedankt! We gaan hier gelijk een patch voor uitbrengen.
