### ISSUE TITLE
[VRAAG] How to fill `resultaattypen` and `statustypen` for `ZaakObjectType` in Catalogi API

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#2334]
There are two read-only properties in `ZaakObjectType`:
* `resultaattypen`
* `statustypen`

It looks like there should be related properties in `ResultaatType` and `StatusType` resources, but I can't find them in the OAS
Could you please specify what these properties are? 
And could you pelase specify how to fill the `ZaakObjectType` properties?

**Comment by michielverhoef** [comment]
@MatthijsBekendam dit is een bug die we nog niet gezien hebben. De relatie moet gelegd worden bij de POST van Zaakobjecttype.

**Comment by michielverhoef** [comment]
@annashamray thank you for noticing, this problem is solved by PR [186](https://github.com/VNG-Realisatie/catalogi-api/pull/186 )

**Comment by joeribekker** [comment]
@michielverhoef It looks like this was added to the API specification in the opposite way.

The relation is defined as: STATUSTYPE [0..1] --> [0..*] ZAAKOBJECTTYPE
See: https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/objecttype/statustype

However, in the API specification it is now allowed to make one zaakobjecttype required for multiple statustypes:

![image](https://github.com/VNG-Realisatie/gemma-zaken/assets/96970/adc38bdb-5fbc-4543-8877-de7413d1479f)
