### ISSUE TITLE
[VRAAG] What to do with required `Zaaktype.verantwoordelijke` for existing zaaktypen? 

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#2335]
In Catalogi API 1.2 a new required property `verantwoordelijke` was added for `Zaaktype` resource
Since it's required and can't be empty what should we do with existing zaaktypen which don't have this property? 
Is there a default value?

**Comment by michielverhoef** [comment]
There is no default value as this will differ for every gemeente but part of migrating to a newer version of the Catalogi API is a data migration.  In this case the zaaktypencatalogus has to be updated to include the correct values for `verantwoordelijke`.

BTW chances are that existing zaaktypen can be updated fairly easily as the information is usually present in existing ZTC applications. It was just never included in the Catalogi API until now.

**Comment by joeribekker** [comment]
Joeri geeft aan dat we `verantwoordelijke` kunnen vullen met `bronorganisatie` tbv de datamigratie. Michiel zegt: goed plan.

@EduardWitteveen andere overwegingen?

**Comment by annashamray** [comment]
@joeribekker Since ZaakType doesn't have `bronorganisatie` property, I'll use `Catalogus.rsin` as a temporary default

**Comment by michielverhoef** [comment]
Hmm, nu ik er over nadenk is `bronorganisatie`  niet zo'n goed plan.  Dan is inderdaad `catalogis.rsin` een betere optie.
