### ISSUE TITLE
Referentie implementatie DRC 1.4.1 ontbreekt 'lock' bij bestandsdelen

### ISSUE THREAD

**Issue by rderooij** [VNG-Realisatie/gemma-zaken#2337]
Ben bezig met het testen van DRC 1.4.1 en er blijkt geen lock aanwezig te zijn in bestandsdelen. Ik heb nu een situatie waarbij in versie 1.3.1 ik nu geen document kan aanmaken vanwege een internal error (zie #2336) en bij versie 1.4.1 lijkt nu de hele implementatie te ontbreken. 

**1.3.1**

https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/documenten-api/1.3.1/src/openapi.yaml#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_create

```
  "bestandsdelen": [
    {
      "url": "string",
      "volgnummer": 0,
      "omvang": 0,
      "voltooid": true,
      "lock": "string"
    }
  ],
```

**1.4.1**

https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/documenten-api/1.4.1/src/openapi.yaml#/enkelvoudiginformatieobjecten/enkelvoudiginformatieobject_create

```
  "bestandsdelen": [
    {
      "url": "string",
      "volgnummer": 0,
      "omvang": 0,
      "voltooid": true
    }
  ],
```

**Comment by michielverhoef** [comment]
Volgens de links kijk je naar de referentie implementatie. Hier lijkt een fout in te zitten die opgelost moet worden maar het is belangrijk dat je altijd naar de **standaard** kijkt. Deze is te vinden via:

https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/

https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/redoc-1.3.1#tag/enkelvoudiginformatieobjecten/operation/enkelvoudiginformatieobject_create

https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/redoc-1.4.1#tag/enkelvoudiginformatieobjecten/operation/enkelvoudiginformatieobject_create
