### ISSUE TITLE
[VRAAG] Catalogi API: what to do with `InformatieObjectType.informatieobjectcategorie` for existing informatieobjecttypen?

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#2344]
In Catalogi API 1.2 a new required property `informatieobjectcategorie` was added for `InformatieObjectType` resource
Since it's required and can't be empty what should we do with existing informatieobjecttypen which don't have this property?
Is there a default value?

**Comment by joeribekker** [comment]
Besproken met Michiel: Waarschijnlijk hebben systemen die nog gebruik maakten van StUF wel deze data, omdat het uit RGBZ komt. Als de bron gerealiseerd op basis van de nieuwe API's dan moet de data aangeleverd/ingevuld worden door de gemeente. Waar deze ten tijde van de migratie vandaan komt is ... onduidelijk :)

Joeri geeft aan dat in Open Zaak de standaard waarde "onbekend" waarschijnlijk wordt ingevuld omdat we nergens anders een waarde vandaan kunnen trekken. Naar de gemeente zal dan gecommuniceerd worden dat ze bij hun documenttypen de categorie nog moeten vullen.

**Comment by michielverhoef** [comment]
To summarize: There is no default value defined in the ZGW standard. The value `onbekend`  can technically be used to fill in the blanks, although a lot of older, systems that implemented RGBZ may already contain the necessary information.

**Comment by michielverhoef** [comment]
I suppose this issue can be closed now @annashamray ?

**Comment by annashamray** [comment]
Yes! Thank you for clearing this out
