### ISSUE TITLE
POST /zaken/_zoek: query parameter expand ontbreekt in de documentatie van het request   

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#2345]
# Bug
POST /zaken/_zoek: query expand parameter ontbreekt in de documentatie van het request
zie [https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/redoc-1.5.0#tag/zaken/operation/zaak__zoek](url)

Kunnen we er vanuit gaan dat die parameter wel opgenomen is/wordt in de standaard voor POST / zaken/_zoek?
Anders moeten we na gebruik van POST per gevondeen zaak de "GET /zaken" uitvoeren met parameter expand.

**Comment by michielverhoef** [comment]
Bedankt voor het melden, die hadden we over het hoofd gezien. Hier moet natuurlijk de expand parameter wel in opgenomen worden!
