### ISSUE TITLE
Als ontwikkelaar wil ik de ZDS client in aparte repository

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#235]
...zodat ik deze los van alle andere onderdelen kan gebruiken om te communiceren met de componenten.

**Definition of ready**
- [x] Userstory past op wenselijk gebruik ZGW volgens GEMMA 2

**Definition of done**
- [x] Er is een werkende client beschikbaar in een aparte repo [dit is voor nu geen onderdeel van de referentie implementatie]
- [x] De aparte repo wordt gebruikt in integratie testen en demo omgeving.

**Taken**
- [x] Creeer aparte repo voor client
- [x] Merge demo/integratie clients
- [x] Voeg afhankelijkheid toe aan demo/integratie repo's

**Comment by TCIMEddy** [comment]
@ehotting wellicht al gereed maar wil jij er nog wat over zeggen...

**Comment by ehotting** [comment]
@joeribekker Neem aan dat het deze betreft? https://github.com/VNG-Realisatie/gemma-zds-client

Zo ja, graag als "done" markeren en archiveren in juiste sprint

**Comment by sergei-maertens** [comment]
Is inderdaad gedaan
