### ISSUE TITLE
[VRAAG] Reden achter de opname van het Catalogus-attribuut bij (bijv.) Statustype

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#2365]
Ik ben even nieuwsgierig wat de redenatie is van de opname van het `Catalogus`-attribuut bij bijv. `Statustype`.

De `Catalogus` is al te achterhalen via: `Statustype->Zaaktype->Catalogus`. Is het toevoegen van de `Catalogus` aan `Statustype` puur voor convenience?

**Comment by michielverhoef** [comment]
> Ik ben even nieuwsgierig wat de redenatie is van de opname van het `Catalogus`-attribuut bij bijv. `Statustype`.
> 
> De `Catalogus` is al te achterhalen via: `Statustype->Zaaktype->Catalogus`. Is het toevoegen van de `Catalogus` aan `Statustype` puur voor convenience?

Ja, puur voor convenience.
