### ISSUE TITLE
Als gemeente wil ik kunnen zoeken op betrokken via de ZGW-api

### ISSUE THREAD

**Issue by Jinze82** [VNG-Realisatie/gemma-zaken#2367]
Als gemeente wil ik kunnen zoeken op betrokken via de ZGW-api, zodat ik alle zaken kan ophalen waar klant bij betrokken is. 
Op de persoonlijke pagina van een persoon of bedrijf willen we laten zien wat zijn lopende aanvragen zijn, waar hij betrokken is of waar zijn gegevens in staan (AVG). Met deze eerste stap geef je een persoon inzage in zijn gegevens waar wij zorgvuldig mee omgaan. Een logische vervolg stap hierop zou zijn dat de persoon ook grip krijgt over zijn gegevens.

**Comment by michielverhoef** [comment]
https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/redoc-1.5.1#tag/zaken/operation/zaak_list

Het is al geruime tijd mogelijk om met diverse zoekparameters als bsn en/of rol een lijst van zaken op te vragen. Hiermee kan dus een bsn in de rol van initator worden opgevraagd. Idem voor identifcaties van Niet Natuurlijke Personen, organisaties etc.

Volgens mij kan dit al. @Jinze82  wat mis je nog aan zoekingangen?

**Comment by MaartenRutten** [comment]
Zoals ik de standaard interpreteer.

- Als 'rol__betrokkeneIdentificatie__natuurlijkPersoon__inpBsn' het bsn bevat van de burger
- en als 'rol__omschrijvingGeneriek' **geen** waarde bevat
- dan worden alle zaken geselecteerd waarbij de natuurlijkePersoon betrokken is in een willekeurige rol

**Comment by Jinze82** [comment]
@michielverhoef Ik denk dat ik heb gemist dat dit al kan!

**Comment by michielverhoef** [comment]
Beter zo dan andersom :-) 
Ik sluit het ticket, mocht er toch nog iets ontbreken kan altijd een nieuw ticket geopend worden.
