### ISSUE TITLE
RGBZ-mapping US #153

### ISSUE THREAD

**Issue by RitaBerghuis** [VNG-Realisatie/gemma-zaken#237]
Mapping van velden behorend bij user story #153 

### Request
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| ZAAK/ZaakIdentificatie | id | UUID | Uniek volgnummer zaak |
|ZAAK.is_van.ZAAKTYPE.Zaaktype-identificatie | Zaaktype | AN5 | Uniek volgnummer van het zaaktype|
|ZAAK.is_van.ZAAKTYPE.Domein | Domein| AN40 |Een afkorting waarmee wordt aangegeven voor welk domein in een CATALOGUS ZAAKTYPEn zijn uitgewerkt. |
|ZAAK.is_van.ZAAKTYPE.RSIN | RSIN | N9 | Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON die de eigenaar is van een CATALOGUS. |
|NATUURLIJK   PERSOON.is.BETROKKENE.heeft_rol_in.ZAAK | Naam | AN200 |Naam van de aanvrager|
NATUURLIJK   PERSOON.is.BETROKKENE.heeft_rol_in.ZAAK | Burgerservicenummer | AN9 | Burgerservicenummer   van de aanvrager
NATUURLIJK   PERSOON.is.BETROKKENE.heeft_rol_in.ZAAK | E-mail | AN254 | E-mail van de aanvrager
NATUURLIJK   PERSOON.is.BETROKKENE.heeft_rol_in.ZAAK | Telefoonnummer | AN20 | Telefoonnr   van de aanvrager
ZAAK.Bronorganisatie |   | N9 |  
ZAAK.Verantwoordelijke organisatie |   | N9  |
ZAAK.Omschrijving |   | AN80  | Het behandelen van een verzoek voor   inzage van persoonsgegevens
ZAAK.Startdatum | Huidige datum  | DATUM  | Datum   van registratie van het inzageverzoek
ZAAK.Uiterlijke  einddatum afdoening |   | DATUM | Bepalen met ZAAKTYPE.Doorlooptijd (call ZTC API)
ZAAK.Geplande einddatum |   | DATUM | Bepalen met ZAAKTYPE.Servicenorm (Call ZTC API)
ZAAK.COMMUNICATIEKANAAL.Naam communicatiekanaal |   | AN20 | Kanaal wat gebruikt is bij de aanvraag
ZAAK.STATUS.STATUSTYPE.Statustypevolgnummer |   | N4 | Een volgnummer voor statussen van het STATUSTYPE binnen een zaak
ZAAK.STATUS.STATUSTYPE.Statustype-omschrijving |   | AN80 | Statusomschrijving van de actuele status (
ZAAK.STATUS.Datum status gezet | Huidige datum  | DATUM | De datum waarop de ZAAK de status heeft verkregen.
ZAAK.STATUS.Indicatie laatst gezette status | TRUE  | INDIC | Aanduiding of het de laatst bekende bereikte status betreft.
AVG-rechten.Inzage WMO | Inzage WMO | INDIC | Indicatie Inzage WMO (tevens opnemen in ZAAK.Toelichting)
AVG-rechten.Inzage Jeugd | Inzage Jeugd | INDIC | Indicatie Inzage Jeugd (tevens opnemen in ZAAK.Toelichting)
AVG-rechten.Inzage Participatie | Inzage Participatie | INDIC | Indicatie Inzage Participatie (tevens   opnemen in ZAAK.Toelichting)
AVG-rechten.Inzage Veiligheidskamer | Inzage Veiligheidskamer | INDIC | Indicatie Inzage Veiligheidskamer (tevens opnemen in ZAAK.Toelichting)
AVG-rechten.Inzage Schuldhulpverlening | Inzage Schuldhulpverlening | INDIC | Indicatie Inzage Schuldhulpverlening (tevens opnemen in ZAAK.Toelichting)
AVG-rechten.Inzage Overige regelingen | Inzage Overige regelingen | INDIC | Indicatie Inzage Overige regelingen (tevens opnemen in ZAAK.Toelichting)
AVG-rechten.Onderwerp | Onderwerp bij Overige Regelingen | AN1000 | Onderwerp bij Overige Regelingen (tevens opnemen in ZAAK.Toelichting)
AVG-rechten.Inzage Algemeen | Inzage Algemeen | INDIC | Indicatie Inzage Algemeen (tevens opnemen in ZAAK.Toelichting)
AVG-rechten.Reden | Reden Algemeen | AN1000 | Reden Algemeen (tevens opnemen in ZAAK.Toelichting)
DOMEINSPECIFIEK.Antwoord per e-mail | Antwoord per e-mail | INDIC | Indicatie Antwoord per e-mail (tevens opnemen in ZAAK.Toelichting)
ZAAK.Kenmerken.Kenmerk bron | Naam bronsysteem | AN200| De aanduiding van de administratie waar het kenmerk op slaat.
ZAAK.Kenmerken.Kenmerk | Unieke identificatie | AN20 | Identificeert de zaak uniek in een andere administratie.

### Answer
| RGBZ mapping | Veld in huidige app | Datatype |Verklaring |
| --- | --- | --- | --- |
ZAAK.Registratiedatum | Datum inzageverzoek | DATUM | Datum van registratie van het Inzageverzoek

**Comment by ArjanKloosterboer** [comment]
Enkele opmerkingen bij de mapping.
Datum inzageverzoek is, neem ik aan, de datum waarop het verzoek tot inzage is ingediend. Dat mapt op Startdatum van de zaak. Registratiedatum is de datum waarop de zaak is geregistreerd. 
Voor identificatie van het zaaktype heb je ook Domein en RSIN nodig.
Van STATUS heb je STATUS.STATUSTYPE.Volgnummer nodig (i.p.v. ….omschrijving) aangezien dat i.c.m. de unieke aanduiding van het Zaaktype de unieke aanduiding van Statustype is. En veder heb je nog nodig STATUS.Datum_status_gezet en STATUS.Indicatie_laatst_gezette_status (=TRUE). 
Wat wil je met ZAAK.Kenmerken? 
ZAAK.Zaakidentificatie lever je m.i. niet aan (of moet die eerst opgehaald worden?).
Als Answer krijg je m.i. alleen de Zaakidentificatie terug, niet de genoemde datums (die lever je aan), maar wel de Registratiedatum.

**Comment by EdwinCoster** [comment]
Aanpassingen:
* ZAAK.Registratiedatum wordt ZAAK.Startdatum
* ZAAKTYPE.Domein en ZAAKTYPE.RSIN toevoegen
* STATUS.STATUSTYPE.Statustypevolgnummer toevoegen (mag ik Omschrijving laten staan?)
* STATUS.Datum_status_gezet en STATUS.Indicatie_laatst_gezette_status toevoegen (en het is dus 'TRUE/FALSE', mooi)

ZAAK.Kenmerken wil ik gebruiken om de referentie naar het processysteem (nu nog VJV) vast te leggen. 

M.b.t. ZAAK.Zaakidentificatie weet ik niet zo goed wat wijsheid is. Eerst ophalen (omdat je het op meerdere plaatsen gaat gebruiken). Of gewoon de zaak registreren, terugkrijgen en hergebruiken. Als ik het eerste kies dan ga ik deze mapping waarschijnlijk aanpassen omdat ik alleen een Registratiedatum terugkrijg.

Dus 'Einddatum gepland' en de 'Uiterlijke datum afdoening' moet ik eerst zelf opvragen bij de ZTC API en vervolgens meegeven? Kunnen de API's dat niet 'onderling' oplossen?

**Comment by EdwinCoster** [comment]
#281

**Comment by joeribekker** [comment]
Deze User Story beschrijft de request/response velden in de huidige situatie toch?

Het lijkt namelijk alsof de discussie ook gaat over de request/response velden in de REST API, maar dat werkt zo niet. Er moeten namelijk meerdere API calls gemaakt worden naar resources, die elk een eigen antwoord geven, namelijk de "state" van het object (vandaar, REpresentative "State" Transfer, ofwel REST :smile: ).

Aantal vragen en opmerkingen:

1. Ten aanzien van de vraag:

   > M.b.t. ZAAK.Zaakidentificatie weet ik niet zo goed wat wijsheid is. Eerst ophalen (omdat je het op meerdere plaatsen gaat gebruiken). Of gewoon de zaak registreren, terugkrijgen en hergebruiken.
   _- EdwinCoster_

   Er is op dit moment geen "identificatie generator". Dit kan prima een nieuwe US zijn, voor nu laat ik het buiten scope. Het wel of niet gebruik maken hiervan, maakt in principe ook niets uit. En, je krijgt de hele "state" van de `Zaak` terug, dus ook de `identificatie` voor als je het niet zelf had aangeleverd.

2. Er zit geen `Domein` of `RSIN` op `Zaaktype` direct. Een `Zaaktype` hoort bij een `Catalogus` en die heeft deze 2 velden wel. Ik neem aan dat we dat niet veranderen?

3. `ZAAK.Verantwoordelijke organisatie` is nu een RSIN maar kan een URL worden naar een Organisatie?

4. `STATUS.Indicatie_laatst_gezette_status` Kunnen we dit niet eenvoudiger maken? Aangezien de `Datum status gezet` ook aangeleverd wordt, is de laatste status toch gewoon diegene met de meest recente datum? Dan komt het indicatie veld helemaal te vervallen.

   Mocht het er toch in moeten, geen probleem. Ik mis alleen de business logica in RGBZ dat als je de indicatie op True zet, dat de vorige status dan automatisch False wordt. Of moet dit handmatig met een call (ala updateZaakstatus...)?

5. Wat is `DOMEINSPECIFIEK` nu eigenlijk voor object? Het doet mij aan als een soort grofmazig verwerkingsregister-achtig dingetje?

6. Bij `DOMEINSPECIFIEK.onderwerp` als RGBZ veld lijkt me `onderwerpBijOverigeReglingen` als veld naam duidelijker?

**Comment by michielverhoef** [comment]
> Er is op dit moment geen "identificatie generator". Dit kan prima een nieuwe US zijn, voor nu laat ik het buiten scope. Het wel of niet gebruik maken hiervan, maakt in principe ook niets uit. En, je krijgt de hele "state" van de Zaak terug, dus ook de identificatie voor als je het niet zelf had aangeleverd.

1 van de functies van het Zaakregistratiecomponent is het genereren van unieke zaakanduidingen: 
https://www.gemmaonline.nl/index.php/GEMMA2/0.9/id-a97b6545-d5a7-485d-9b13-3ce22db5b9cf

(zie toegewezen functies (1) ).
Aangezien we die nu niet hebben zou dit een nieuwe userstory moeten zijn. Alleen misschien wat lastig omdat REST natuurlijk uitgaat van het benaderen van Resources en een zaakidentificatie is geen aparte resource ... Maar daar verzinnen Joeri en Sergei vast wel wat op? :-D


> Er zit geen Domein of RSIN op Zaaktype direct. Een Zaaktype hoort bij een Catalogus en die heeft deze 2 velden wel. Ik neem aan dat we dat niet veranderen?

Volgens ImZTC 2.2 concept 13-6-2018 heeft een zaaktype een:

Broncatalogus   zaaktype : | De   CATALOGUS waaraan het ZAAKTYPE is ontleend.
-   Domein | Het   domein van de CATALOGUS waaraan het ZAAKTYPE is ontleend.
-   RSIN | Het   RSIN van de INGESCHREVEN NIET-NATUURLIJK PERSOON die beheerder is van de   CATALOGUS waaraan het ZAAKTYPE is ontleend.

Maar dit is geen REST manier van verwijzen naar de catalogus (want dat zou een URI moeten zijn denk ik?). In dat geval moeten die gegevens opgehaald worden bij de catalogus.

> ZAAK.Verantwoordelijke organisatie is nu een RSIN maar kan een URL worden naar een Organisatie?

Volgens mij wel

> STATUS.Indicatie_laatst_gezette_status

Die uitleg staat in de slack :-)

> Domeinspecifiek

Volgens mij is dit alles wat niet in het RGBZ staat, vergelijkbaar met de de domeinspecifieke/niet-RGBZ  gegevens uit water en MOR?

**Comment by joeribekker** [comment]
> Alleen misschien wat lastig omdat REST natuurlijk uitgaat van het benaderen van Resources en een zaakidentificatie is geen aparte resource ... Maar daar verzinnen Joeri en Sergei vast wel wat op? :-D

Kan prima (maar is inderdaad niet heel RESTful), uitleg volgt als er een User Story voor komt.

> Volgens ImZTC 2.2 concept 13-6-2018 heeft een zaaktype een: Broncatalogus zaaktype [...]

Volgens mij is dat iets anders (maar ik weet niet wat het precies is, en jij bent de guru hehe): 

* Jij doelt op: `Zaaktype.Broncatalogus.domein`,
* Ik denk dat Edwin doelt op `Zaaktype - maakt deel uit van - Catalogus.domein`

In beide gevallen zou het inderdaad een linkje worden, maar ik wilde even dubbelchecken dat de attributen `domein` en `rsin` niet opeens op `Zaaktype` komen te staan.

>> Domeinspecifiek
> Volgens mij is dit alles wat niet in het RGBZ staat, vergelijkbaar met de de domeinspecifieke/niet-RGBZ gegevens uit water en MOR?

Yes! Maar wat is het? Nu heet het in de API `/api/v1/domeinspecifiek/` en ik neem aan dat het iets moet worden als `/api/v1/avg-permissies/` o.i.d?

@EdwinCoster: Vragen 2, 5, 6 en 7 staan nog open :)

**Comment by EdwinCoster** [comment]
Vraag 2
> Er zit geen Domein of RSIN op Zaaktype direct. Een Zaaktype hoort bij een Catalogus en die heeft deze 2 velden wel. Ik neem aan dat we dat niet veranderen?
 Eerst stond er alleen Zaaktypeidentificatie en toen schreef Arjan:
> Voor identificatie van het zaaktype heb je ook Domein en RSIN nodig.

In RGBZ authenticeert Zaaktypeidentificatie, samen met Domein en RSIN het Zaaktype.
In imZTC ziet dat er weer anders uit.

Ik dwaal rond in een pretpark met allemaal attracties die ik nog nooit heb gezien. Dus ik weet niet zo goed wat ik hier nu in kan bijdrage.

Wat er moet gebeuren (denk ik) is dat de authenticatie van het zaaktype zoals wij dat hebben geïmplementeerd opgehaald kan worden uit de ZTC en aan de zaak wordt gehangen. Waarbij je er vanuit gaat dat die ZTC catalogi van verschillende domeinen en organisaties bevat.

**Comment by EdwinCoster** [comment]
Vraag 5.
> Wat is DOMEINSPECIFIEK nu eigenlijk voor object? Het doet mij aan als een soort grofmazig verwerkingsregister-achtig dingetje?

Dat is het niet. Het zijn de domeinspecifieke gegevens die (vooralsnog) in de ORC terechtkomen. In lijn met naam boot, soort boot, rederij bij Water. Ik heb ergens in een issue voorbij zien komen, maar nu kan ik het niet terugvinden.

**Comment by EdwinCoster** [comment]
Vraag 6.
> Bij DOMEINSPECIFIEK.onderwerp als RGBZ veld lijkt me onderwerpOverigeRegelingen als veld naam duidelijker?

Eens! en dan word de Reden bij Algemeen: redenAlgemeen

**Comment by EdwinCoster** [comment]
Vraag 7
> Wat is ZAAK.COMMUNICATIEKANAAL? Lijkt op Klantcontact o.i.d?

Verwijzing naar een referentielijst 'COMMUNICATIEKANAAL', medium waarlangs het binnenkomt (in dit geval e-formulier). Het is niet verplicht en op dit moment nog niet echt van belang, want we beperken we ons tot één kanaal. Maar er komt natuurlijk een moment waarop er één een brief gaat sturen. En dan loopt het proces net even anders. En dan wil je in een later stadium kunnen terugzoeken via welk kanaal het verzoek is binnengekomen.

**Comment by michielverhoef** [comment]
Joeri schreef:
> Volgens mij is dat iets anders (maar ik weet niet wat het precies is, en jij bent de guru hehe):
>    Jij doelt op: Zaaktype.Broncatalogus.domein,
>    Ik denk dat Edwin doelt op Zaaktype - maakt deel uit van - Catalogus.domein
>
> In beide gevallen zou het inderdaad een linkje worden, maar ik wilde even dubbelchecken dat de attributen domein en rsin niet opeens op Zaaktype komen te staan.

Nog eens nakijkende: ik denk dat je gelijk hebt. Maar inderdaad, in beide gevallen wordt naar een andere resource verwezen dus wordt het een URI.


Edwin schreef:
> In RGBZ authenticeert Zaaktypeidentificatie, samen met Domein en RSIN het Zaaktype.
In imZTC ziet dat er weer anders uit.

Hmm, ja, in RGBZ.Zaaktype lijken ImZTC.Zaaktype en ImZTC.Catalogus gecombineerd, in ieder geval voor deze attributen. De vraag is nu of we in deze API gebruik gaan maken van RGBZ.Zaaktype of ImZTC. Momenteel verwijzen we naar de ZTC denk ik (?)  maar misschien is het makkelijker om vanuit RGBZ.Zaak te verwijzen naar RGBZ.Zaaktype en van daaruit naar ImZTC.Zaaktype en ImZTC.Catalogus etc.

Dit is een lastige....

Joeri schreef:
> Yes! Maar wat is het? Nu heet het in de API /api/v1/domeinspecifiek/ en ik neem aan dat het iets moet worden als /api/v1/avg-permissies/ o.i.d?

Dat is een goede vraag en zolang er nog geen API voor is een lastige. Misschien moeten we in het begin maar heel globale domeinen onderscheiden waar we dan weer subdomeinen oid voor maken? Zoals melding wateroverlast een specialisatie van een MOR is dan misschien iets als 
/api/v1/mor/water voor de wateruserstories? En /api/v1/veiligheid/avg/permissies ?

**Comment by EdwinCoster** [comment]
Michiel schreef:

> Dit is een lastige....

Als we dit combineren met het architectuurverhaal van @jgortmaker1 zou ik denken dat we gebruik maken van zaaktype uit imZTC.

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Heb jij deze gereviewd

**Comment by ArjanKloosterboer** [comment]
@tcimeddy, ja en nee. Ik heb vier weken geleden gereageerd op de toenmalige mapping. Drie weken geleden heeft Edwin daarop gereageerd met mapping-aanpassingen en functionaliteitsvragen. Mede nav het laatste is er vervolgens veel gediscussieerd. Als de uitkomst van die discussie geen consequenties heeft voor de mapping van drie weken geleden dan ben ik akkoord. Is dat zo?

**Comment by TCIMEddy** [comment]
@EdwinCoster Wil jij een check doen of de vraag van @ArjanKloosterboer mbt uitkomsten discussie - invloed mapping (moet helaas even om proces scherp te krijgen)

**Comment by EdwinCoster** [comment]
@TCIMEddy. Ik heb na de aanpassingen n.a.v. de eerste review van @ArjanKloosterboer geen wijzigingen in de mapping meer doorgevoerd.

**Comment by ArjanKloosterboer** [comment]
Gezien [deze comment](https://github.com/VNG-Realisatie/gemma-zaken/issues/237#issuecomment-417658660) van mezelf en [deze daarop reagerende comment](https://github.com/VNG-Realisatie/gemma-zaken/issues/237#issuecomment-418654929) van Edwin ben ik akkoord met de mapping.

**Comment by TCIMEddy** [comment]
gedaan en relevantie?
