### ISSUE TITLE
DRC API: Onduidelijke fout (reden) bij het aanmaken van een VERZENDING

### ISSUE THREAD

**Issue by heuvea** [VNG-Realisatie/gemma-zaken#2373]
# Bug

Als ik op jullie DRC referentie API (v1.4) een VERZENDING probeer aan te maken krijg ik de volgende validatie fout (400)

 **"Verzending must contain precisely one correspondentieadress"**

![error](https://github.com/VNG-Realisatie/gemma-zaken/assets/66989902/25de78e6-6a01-455d-9213-00df34bce757)

Mis ik iets? Staat in de documentatie misschien een verkeerd veld genoteerd?

**Comment by michielverhoef** [comment]
Een verzending kan maar afkomstig zijn van 1 adres of geadresseerd zijn aan 1 adres. In het bericht wat je stuurt wordt zowel een correspondentieadres (postadres) als een emailadres gegeven. 

Dat kan niet. Om een informatieobject naar twee verschillende adressen te sturen moeten twee Verzendingen aangemaakt worden.

**Comment by johannesbattjes** [comment]
@michielverhoef waar staat in de standaard dat emailadres niet gevuld mag zijn als correspondentieadres gevuld is?
Ik zie het namelijk niet staan op https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/ en niet op https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/redoc-1.4.3
Als het er niet staat - zou je dan de regels voor wat en niet tegelijk gevuld mag zijn willen toevoegen aan https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/ zodat het duidelijk wordt?

**Comment by heuvea** [comment]
Ik haal nu het email weg en krijg ik nog steeds dezelfde fout:
![image](https://github.com/VNG-Realisatie/gemma-zaken/assets/66989902/2ff56826-33b5-4594-8b86-d524c1f07717)

**Comment by heuvea** [comment]
Ik zie het al : Als ik "mijnOverheid": false zet wordt ie correct verwerkt

**Comment by michielverhoef** [comment]
> Ik haal nu het email weg en krijg ik nog steeds dezelfde fout: ![image](https://user-images.githubusercontent.com/66989902/283352124-2ff56826-33b5-4594-8b86-d524c1f07717.png)

Er staat nog een kanaal in: Mijn Overheid.

Maar ik begrijp uit de vraag van Johannes dat inderdaad niet duidelijk is dat een Verzending slechts via 1 kanaal plaats vindt. Dus of een (post)adres, of email, of telefonisch, of via Mijn Overheid. Vandaar ook dat de relatie EnkelvoudigInformatieobject - Verzending een 1 op n relatie is.

Ik zal eea. verder verduidelijken in de documentatie.

**Comment by michielverhoef** [comment]
De documentatie is bijgewerkt, zie https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/
Mocht dit alsnog niet duidelijk zijn, laat dit dan svp weten. 

Ik sluit dit issue.

**Comment by johannesbattjes** [comment]
Wat mij betreft heel duidelijk, dank voor deze toelichting @michielverhoef
