### ISSUE TITLE
Sprintdemo van 24 september valt samen met fieldlab

### ISSUE THREAD

**Issue by RitaBerghuis** [VNG-Realisatie/gemma-zaken#238]
# Impediment
Sprintdemo van 24 september valt samen met fieldlab.
Een (groot) aantal van de deelnemers van het scrumteam zullen ook aan het fieldlab willen deelnemen.
Sprintdemo data zijn al gepubliceerd op vng site en locatie is al voorbereid door Amsterdam

**Comment by ehotting** [comment]
Betreft Fieldlab Dienstverlening in Zwolle, hele week.

**Comment by TCIMEddy** [comment]
Alle data verzet door Wishal
