### ISSUE TITLE
RGBZ Mapping bij US #154

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#239]
Mapping van velden behorend bij user story #154

### Request
| RGBZ mapping | Veld in huidige app | Verklaring |
| --- | --- | --- |
| ZAAK.ZaakIdentificatie | Zaakidentificatie | Uniek volgnummer zaak |

### Answer ZRC (De actuele status)
| RGBZ mapping | Veld in huidige app | Verklaring |
| --- | --- | --- |
| STATUS.STATUSTYPE.Statustype-omschrijving | Status | Statusomschrijving van de actuele status |
| STATUS.Indicatie laatst gezette status |   | Uit de collectie statussen waarbij 'Indicatie laatst gezette status' = TRUE |

### Answer DRC (Een collectie informatieobjecten met vertrouwelijkheidaanduiding 'ZAAKVERTROUWELIJK')
| RGBZ mapping | Veld in huidige app | Verklaring |
| --- | --- | --- |
| ZAAK.kent.INFORMATIEOBJECT | | Informatieobject behorend bij de zaak |
| ENKELVOUDIGINFORMATIEOBJECT.Formaat | Formaat | De code voor de wijze waarop de inhoud is vastgelegd in een computerbestand. |
| ENKELVOUDIGINFORMATIEOBJECT.Taal | Taal | Een taal van de intellectuele inhoud |
| ENKELVOUDIGINFORMATIEOBJECT.Inhoud | Inhoud | Datgene wat wordt meegedeeld. |
| ENKELVOUDIGINFORMATIEOBJECT.Link | URL | De URL waarmee de inhoud op te vragen is. |
| INFORMATIEOBJECT.Informatieobjectidentificatie | Informatieobjectidentificatie |  Unieke identificatie van het informatieobject |
| INFORMATIEOBJECT.Creatiedatum | Aangemaakt op | Een datum of een gebeurtenis in de levenscyclus van het INFORMATIEOBJECT. |
| INFORMATIEOBJECT.Titel | Titel | De naam waaronder het INFORMATIEOBJECT formeel bekend is. |
| INFORMATIEOBJECT.Auteur | Auteur | De persoon of organisatie die in de eerste plaats verantwoordelijk is voor het creëren van de inhoud van het INFORMATIEOBJECT. |
| INFORMATIEOBJECT.Beschrijving | Beschrijving | Een generieke beschrijving van de inhoud van het | INFORMATIEOBJECT. |
| INFORMATIEOBJECT.Vertrouwelijkheidaanduiding | Vertrouwelijkheid | Aanduiding van de mate waarin het INFORMATIEOBJECT voor de openbaarheid bestemd is. |
| INFORMATIEOBJECT.is van.INFORMATIEOBJECTTYPE | Type informatieobject |  Voor het ophalen van de omschrijving |
| INFORMATIEOBJECTTYPE.Informatieobjecttype-omschrijving | Omschrijving van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE |

**Comment by ArjanKloosterboer** [comment]
Naar de mapping ga ik nog kijken. Voor nu alvast een reactie op het comment van @joeribekker hiervoor.

> Wellicht is dit een goed moment om SamengesteldInformatieObject uit RGBZ te halen, en InformatieObject en EnkelvoudigInformatieObject samen te voegen.

Het lijkt mij dat tijdsaspecten geen redenen zijn om functionaliteit of een ontwerp te wijzigen. Ik ben benieuwd naar de inhoudelijk argumentatie. Ik zie vooralsnog geen enkele reden om het RGBZ op dit punt aan te passen. Er is voldoende argumentatie om dit objecttype te behouden.
 

> Wat mij betreft leeft een InformatieObject ook alleen maar in het DRC (bijv Alfresco).

Wat bedoel je hiermee? 

> Bij Vernietigingsdatum vraag ik me (als ontwikkelaar) af wie verantwoordelijk is voor het vernietigen.

Primair is daarvoor de (verantwoordelijke voor de) DocumentenBeheerComponent verantwoordelijk. 

> Ten slotte kunnen we eens kijken of Titel, Beschrijving en wellicht meer velden niet op Zaak-InformatieObject moeten staan. Volgens mij wordt wordt dit in de praktijk bijna altijd een kopie van de Titel en Beschrijving van het InformatieObject zelf.

Nee, die gegevens horen bij Informatieobject. Ze beschrijven het Infrmatieobject los van zijn context. Zaakinformatieobject biedt de mogelijkheid om binnen de scope (context) van een zaak daar net even anders tegen aan te kijken, indien daar redenen voor zijn.

**Comment by joeribekker** [comment]
>> Wellicht is dit een goed moment om SamengesteldInformatieObject uit RGBZ te halen, en InformatieObject en EnkelvoudigInformatieObject samen te voegen.
> 
>Het lijkt mij dat tijdsaspecten geen redenen zijn om functionaliteit of een ontwerp te wijzigen. Ik ben benieuwd naar de inhoudelijk argumentatie. Ik zie vooralsnog geen enkele reden om het RGBZ op dit punt aan te passen. Er is voldoende argumentatie om dit objecttype te behouden.

Ik bedoelde niet dat er geen tijd voor is, maar dat deze User Story en mapping een goede aanleiding vormen om het er over te hebben. Het ZDS (1.1 of 1.2) biedt geen mogelijkheid om een `SamengesteldInformatieObject` te ontsluiten of aan te maken. Waarom zou het dan in het RGBZ moeten zitten?

>> Ten slotte kunnen we eens kijken of Titel, Beschrijving en wellicht meer velden niet op Zaak-InformatieObject moeten staan. Volgens mij wordt wordt dit in de praktijk bijna altijd een kopie van de Titel en Beschrijving van het InformatieObject zelf.
> 
> Nee, die gegevens horen bij Informatieobject. Ze beschrijven het Infrmatieobject los van zijn context. Zaakinformatieobject biedt de mogelijkheid om binnen de scope (context) van een zaak daar net even anders tegen aan te kijken, indien daar redenen voor zijn.

Ik begrijp de achterliggende gedachte wel, maar het onderscheid tussen `InformatObject.titel` en `ZaakInformatieObject.titel` valt niet te maken via ZDS (1.1 of 1.2) waar maar 1 attribuut is voor `titel`. Ik vraag me daarom af of het in de praktijk gebruikt wordt. Als jij, gemeenten of leveranciers daar voorbeelden van hebben vind ik het prima om het op te nemen.

Ik zou meer neigen naar een "opmerkingen" veld dat de relatie tussen het document en een zaak beschrijft dan een alternatieve titel en beschrijving.

**Comment by ArjanKloosterboer** [comment]
> Het ZDS (1.1 of 1.2) biedt geen mogelijkheid om een SamengesteldInformatieObject te ontsluiten of aan te maken. Waarom zou het dan in het RGBZ moeten zitten?

In het ontwerp van StUF-Zaken, waarop de ZDS 1.x gebaseerd is, zijn enkele fouten geslopen waaronder het niet ondersteunen van samengestelde informatieobjecten. De ZDS 2 standaard biedt de mogelijkheden deze fouten te herstellen (incl. evt. voortschrijdend inzicht). Het RGBZ is maatgevend voor de gegevens over zaken en documenten, niet de ZDS 1.x-standaarden!

> Ik begrijp de achterliggende gedachte wel, maar het onderscheid tussen InformatObject.titel en ZaakInformatieObject.titel valt niet te maken via ZDS (1.1 of 1.2) waar maar 1 attribuut is voor titel. Ik vraag me daarom af of het in de praktijk gebruikt wordt. Als jij, gemeenten of leveranciers daar voorbeelden van hebben vind ik het prima om het op te nemen. Ik zou meer neigen naar een "opmerkingen" veld dat de relatie tussen het document en een zaak beschrijft dan een alternatieve titel en beschrijving. 

Ook hier, RGBZ is maatgevend, niet de ZDS 1.x-standaarden. Je alternatief, een opmerkingenveld, is wellicht een reeel voorstel. Maar dit issue is niet de plek om over de inhoud van het RGBZ te discussiëren. Dat moet breder plaatsvinden, wat mij betreft in de daarvoor bedoelde discussiefora.

**Comment by joeribekker** [comment]
Ik vind dat je en beetje voorbij gaat aan de productvisie hieromtrent, volgens mij van jouw hand:

> Indien uit de user-storys blijkt dat 'de werkelijkheid' niet correct gemodelleerd is in het RGBZ, dan is aanpassing mogelijk.

Het RGBZ is het uitgangspunt maar als het niet in het ZDS zit, kan het nu in de praktijk niet gebruikt worden? De vraag is dus of de bewuste attributen/objecttypen in de werkelijkheid wel nodig zijn. Ik vind het antwoord "Ja, omdat het in het RGBZ zit" niet voldoende.

Ook kan ik uit de User Story niet halen dat de bewuste attributen/objecttypen nodig zijn (anders dan dat ze in de mapping staan).

>> Wat mij betreft leeft een InformatieObject ook alleen maar in het DRC (bijv Alfresco).
> 
> Wat bedoel je hiermee?

Dat alle attributen in het DRC (of eigenlijk het DMS) zitten, en niet dat er een soort tabel buiten het DMS leeft waarin de attributen van `InformatieObject` leven. Het ZDS lijkt dit namelijk wel te suggereren (temeer ook door de CMIS-integratie-service).

Wellicht tijdens een meeting even sparren hierover.

**Comment by ArjanKloosterboer** [comment]
Dan nu een reactie op de mapping. Ziet er goed uit.
Ik denk dat je niet de attributen van ZAAK-INFORMATIEOBJECT moet hebben maar van INFORMATIEOBJECT zelf. Aangezien die verderop al staan kunnen de eerstgenoemde vervallen.
INFORMATIEOBJECT.Bronorganisatie lijkt me niet nodig. 
Van INFORMATIEOBJECTTYPE heb je m.i. de Informatieobjecttype-omschrijving nodig. 

Al met al vraag ik me wel af of je al deze attributen wel nodig hebt. Wat wil die burger van die documenten zien? Het lijkt mij een naam (titel), wellicht een identificatie en vooral de inhoud (en wellicht formaat).

**Comment by EdwinCoster** [comment]
ZAAK-INFORMATIEOBJECT heeft een attribuut Vernietigingsdatum. Dat wil(de) ik gebruiken voor de Informatieobjecten die door medewerkers vanuit verschillende domeinen (Deskundigen) worden aangereikt. Die Informatieobjecten worden door de Behandelaar verwerkt in de Beschikking en kunnen daarna weg. Als we dit nu echt geautomatiseerd/op de achtergrond zouden willen faciliteren, dan:
* stel ik de vernietigingsdatum in op de (voorlopige) einddatum van de zaak, en;
* vernietig ik ze zodra de status van de zaak veranderd in 'afgehandeld'.
Maar wellicht moeten we dat op een andere manier aanpakken. Wat kan ik gebruiken om Informatieobjecten te kunnen herkennen die bij afronding van de zaak verwijderd kunnen worden?

Ik begrijp zelf ook niet zo goed waarom ik die bronorganisatie heb opgenomen. Ik heb vooral geprobeerd goed te kopiëren in plaats van iets slecht te bedenken.

Ik zal INFORMATIEOBJECTTYPE.Informatieobjecttype-omschrijving toevoegen.

**Comment by EdwinCoster** [comment]
Oeps

**Comment by joeribekker** [comment]
> RGBZ mapping | Veld in huidige app | Verklaring
> -- | -- | --
> STATUS.STATUSTYPE.Statustype-omschrijving | Status | Statusomschrijving van de actuele status
> STATUS.Indicatie laatst gezette status |   | Uit de collectie statussen waarbij 'Indicatie laatst gezette status' = TRUE

Dit stukje werkt echt anders in de REST API's maar zit in de database wel soortgelijk als hierboven omschreven in elkaar.

`Zaak` heeft een veld `zaakstatus` dat altijd de laatst gezette status teruggeeft. Om de historie van statussen te zien kan je `/statussen/?zaak=<url>`

**Comment by EdwinCoster** [comment]
Dat 'lees' ik dan verkeerd. Als ik RGBZ probeer te ontcijferen vind ik bij `ZAAK` geen attribuut `Status`, zelfs geen relatie met een Object `STATUS`. Alleen bij `STATUS` zie ik een relatie met `ZAAK` die een collectie `STATUSsen` heeft waarvan er blijkbaar één de `Indicatie laatste gezette status = TRUE` heeft.
