### ISSUE TITLE
#2241 in DRC 1.4 niet volledig geimplementeerd

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#2396]
#2241 is opgelost in DRC 1.4 (zie https://github.com/VNG-Realisatie/gemma-zaken/milestone/32?closed=1).
Dit is te zien in business rule drc-009 (https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/#drc-009) waar de constraint op status definitief is doorgehaald.
Maar in de redoc staat de regel nog steeds:

> Werk een (ENKELVOUDIG) INFORMATIEOBJECT in zijn geheel bij.
> Dit creëert altijd een nieuwe versie van het (ENKELVOUDIG) INFORMATIEOBJECT.
> Er wordt gevalideerd op
> correcte lock waarde
> status NIET definitief

Voorstel: in een bugfix op 1.4 de regel _status NIET definitief_ overal laten vervallen

@HenriKorver

**Comment by HenriKorver** [comment]
Goed gezien! We nemen deze bugfix mee in de DRC 1.5 versie.
