### ISSUE TITLE
zrc/openapi.yaml Schema error at components.schemas['Geometry']

### ISSUE THREAD

**Issue by sjefvanleeuwen** [VNG-Realisatie/gemma-zaken#240]
# Impediment

gemma-zaken/api-specificatie/zrc/openapi.yaml

Schema error at components.schemas['Geometry']
should have required property '$ref'
missingProperty: $ref
Jump to line 695
Schema error at components.schemas['Geometry']
should match exactly one schema in oneOf
Jump to line 695
Schema error at components.schemas['Geometry'].required
should be array
Jump to line 698
 
Could be a false negative, this is in https://editor.swagger.io/

[assign aan Eddy, voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by sergei-maertens** [comment]
Fixed in https://github.com/VNG-Realisatie/gemma-zaken/commit/09fce0a2250e5ccd4ae984d4cba1eca6f39a7bd9
