### ISSUE TITLE
Als burger wil ik een indicatie van proof of existence op het enkelvoudig informatie object

### ISSUE THREAD

**Issue by sjefvanleeuwen** [VNG-Realisatie/gemma-zaken#244]
...zodat men buiten de gemeente (decentraal) kan controleren of een object daadwerkelijk bestaat, zonder dat men deze  binnen een gecentraliseerde resource zoals een DMS te hoeven bevragen.

Bijvoorbeeld:

    ProofOfExistence:
      required:
        - bron
        - digest
      type: object
      properties:
        bron:
          title: Bron
          type: string
          format: urn
          description: De bron welke de digest bevat van het ENKELVOUDIG INFORMATIEOBJECT. Bijvoorbeeld een MNID op Ethereum blockchain.
          example: urn:bron:mnid:0x1:0x00521965e7bd230323c423d96c657db5b79d099f
        digest:
          title: Digest
          type: string
          format: urn
          description: De signatuur / digest op het ENKELVOUDIG INFORMATIEOBJECT. Bijvoorbeeld in sha256 hash op het object.
          example: urn:digest:sha256:0x39b65bac61402b994c625bc6c0cf5bd83e5104a5fd5e299e8fda0694012ae2e3

**Definition of ready**
- [ ] Userstory is voorzien van de benodigde eigenschappen om proof of existence aan te kunnen tonen

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een dergelijke signatuur horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Interessant!

Kan je een concrete use case geven?

**Comment by sjefvanleeuwen** [comment]
Proof of Existence is een service die het bestaan van computerbestanden vanaf een specifieke tijd verifieert via tijdgestampte transacties in een publiek toegankelijk grootboek. 

Samenlevingsvormen die we bij de overheid laten vastleggen, zoals het huwelijk of een samenlevingscontract, maar ook echtscheidingen kunnen zo bijv. worden opgenomen.

Dit heeft de volgende voordelen:

1. Het toont het eigenaarschap van gegevens zonder de feitelijke gegevens te onthullen.
2. Het controleert op documentintegriteit.
3. Met behulp van technologieen zoals blockchain kan het bestaan van het document gecertificeerd worden zonder de noodzaak van een centrale autoriteit.
5. In de praktijk kan dit gedecentraliseerde bewijs door niemand worden gewist of gewijzigd.
6. Het is anoniem, zodat anderen de gegevens niet kunnen identificeren.

**Comment by joeribekker** [comment]
> Proof of Existence is een service die het bestaan van computerbestanden vanaf een specifieke tijd verifieert via tijdgestampte transacties in een publiek toegankelijk grootboek.

Zo'n grootboek, of laten we het gewoon maar blockchain noemen, valt alleen redelijk buiten scope van dit project. Het raakvlak kan zijn dat er een service is die een hash van een bestand teruggeeft, en dat iemand vanaf daar verder gaat, maar zelfs dat zie ik niet binnen scope van ZDS 2.0.

Ik denk ook de de User Story, zoals hij nu is, vanuit het oogpunt van de burger moet zijn.

Verder laat ik het vervolg aan de PO over :)

**Comment by sjefvanleeuwen** [comment]
joerbekker, begrijpelijk, dit is ook een EPIC. Goed dat hij dan op de backlog staat voor de PO!

Citaat uit: uit Gemma online:
_"Efficiënt zaakgegevens ontsluiten intern en naar ketenpartners, burgers en bedrijven; de kwaliteit van informatieoverdracht kan beter gegarandeerd worden waardoor samenwerking efficiënter en effectiever verloopt;"_
https://www.gemmaonline.nl/index.php/Zaak-_en_Documentservices

Daar wordt nogal een supply chain genoemd die erg gedecentraliseerd is. De benoemde proof of existence kan efficiency vergroten.

**Comment by ehotting** [comment]
Interessante innovatie waarover we een keer moeten sparren - vooralsnog denk ik niet dat dit in de eerste versie van de API komt

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat dit in een ander project opgelost moet worden. Er loopt een traject vanuit ICTU met gemeenten om waardepapieren te kunnen valideren.
