### ISSUE TITLE
String velden - null of lege string of ...

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/gemma-zaken#2447]
In onze testen met andere leveranciers lopen we tegen een issue aan m.b.t. optionele string velden. Via dit issue wil ik nogmaals vragen om een uitspraak te doen in hoe we hiermee om moeten gaan aangezien de standaard niet eenduidig is. Dit issue is in navolging op issue #1901 en issue #2090 aan. De standaard is gewoonweg niet duidelijk genoeg hierin. Wat moeten we nu doen met niet verplichte (string) velden? Opties die er zijn:

1. Het veld weglaten in de request body;
2. Opnemen maar met de waarde null; of
3. Een lege waarde "" meegeven.

Optie 3 vind ik totaal niet fraai, maar het belangrijkste is dat er duidelijkheid komt. De voorgaande issues staan inmiddels 1,5 jaar open en iedere leverancier maakt hier zijn eigen keuzes in die mogelijkerwijs niet stroken met elkaar. Graag op korte termijn een uitspraak hierover zodat het voor alle leveranciers duidelijk is.

**Comment by basretera** [comment]
Dit issue ligt alweer 7 dagen zonder enige reactie. Dit moet echt prioriteit krijgen. We lopen in onze testen hier zwaar tegenaan. Hier moet echt snel duidelijkheid over komen!

**Comment by HenriKorver** [comment]
Ik begrijp het issue niet goed. Kun je een concreet voorbeeld geven waar precies de problemen optreden?

**Comment by basretera** [comment]
![image](https://github.com/VNG-Realisatie/gemma-zaken/assets/43234516/b6d4142d-5f68-4505-a8e4-fd9389264a74)

In de specificatie van deze optionele stringvelden staat veelal bovenstaande (voorbeeld) gespecificeerd. Namelijk dat een veld een stringwaarde moet bevatten <= x karakters. Wat wordt hiermee bedoeld? Moeten deze optionele velden dan met een lege stringwaarde "" aangeboden worden? Logischer zou zijn dat deze een null-waarde zouden kunnen hebben. Maar op andere plekken (zie hieronder) staat weer gespecificeerd string or null voor een vergelijkbaar veld.

![image](https://github.com/VNG-Realisatie/gemma-zaken/assets/43234516/d608e434-74e4-43f5-aa89-65da55c0fa23)

En mag je optionele velden helemaal weglaten? Of moet je ze wel altijd teruggeven/meesturen maar dan inderdaad met een null-waarde of lege string-waarde ""?

**Comment by HenriKorver** [comment]
> Namelijk dat een veld een stringwaarde moet bevatten <= x karakters. Wat wordt hiermee bedoeld? 

Bijvoorbeeld `<= 80` betekent dat de string niet langer mag zijn dan 80. Dus de string mag wel een lengte 0 hebben, oftewel leeg zijn.

**Comment by basretera** [comment]
Dat snap ik ook natuurlijk ook. Maar daar gaat het niet om.

**Comment by HenriKorver** [comment]
> En mag je optionele velden helemaal weglaten? Of moet je ze wel altijd teruggeven/meesturen maar dan inderdaad met een null-waarde of lege string-waarde ""?

In principe mag je zelf bepalen of je de niet-verplichte (lees: optionele) attributen wel of niet opneemt in een bericht als ze leeg zijn. In een request bericht laat ik de lege velden altijd weg als ze niet verplicht zijn. Echter, bij een respons-bericht vind ik het wel weer prettig als alle attributen worden teruggeven inclusief de attributen met een lege waarde, want dan an zie ik namelijk  in één oog opslag welke attributen wel of niet gevuld zijn. De referentie-implementatie doet het ook zo.

**Comment by basretera** [comment]
Dank voor je antwoord, maar het geeft nog steeds geen antwoord op de meest prangende vraag: moet een leeg veld als lege string "" of als null-waarde in een request meegegeven en in een response teruggegeven worden?

**Comment by HenriKorver** [comment]
In de meeste gevallen zijn de attributen zo gespecificeerd dat er maar één waarde voor het leeg zijn mogelijk is, dus of null of "" (lege string), maar niet beide. Dus daar speelt dit probleem niet. Helaas zijn er een paar gevallen waarbij dit niet goed is gegaan zoals bij het attribuut "processobjectaard". In dat geval moet de API beide waarden ondersteunen (null en lege string). Het is niet fraai maar het werkt wel. Bij het toevoegen van nieuwe attributen in toekomstige versies moeten we goed in de gaten houden dat we slechts één leeg-waarde toelaten. De vraag is of we in een volgende major release ook alle oude attributen waar dit probleem speelt willen fixen  want dat zal mogelijk tot veel backwards compatibiliteits problemen kunnen leiden.

**Comment by basretera** [comment]
Laatste vraag: Kun jij mij uitleggen waarom er gekozen is voor een lege string "" waarde i.p.v. null? Wat veel logischer lijkt voor mij.

**Comment by HenriKorver** [comment]
Ik weet niet wat de exacte beweegredenen waren om te kiezen voor een lege string "" i.p.v. null en ik weet ook niet wat de beweegredenen waren om daar weer soms van af te wijken zoals bij het attribuut 'processobjectaard'. Het niet consequent zijn is een groter probleem dan de waarom-vraag denk ik. 

Persoonlijk vind ik dat attributen van het type "string" een lege string "" als lege waarde moeten teruggeven en niet null. Het is namelijk een lege waarde die het datatype string al van zichzelf heeft en je hoeft dan geen nieuw concept zoals null te introduceren. Hetzelfde verhaal voor attributen van het type "array": die geef je de lege lijst [] terug en niet de waarde null. 
Het handige is dan ook dat je in de respons-berichten kunt zien van welke type het lege attribuut is.

```json
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "url": "https://zaken-api.vng.cloud/api/v1/zaken/01a50969-359c-4a0e-95ca-79293914534b",
            "uuid": "01a50969-359c-4a0e-95ca-79293914534b",
            "identificatie": "ZAAK-2019-0000000002",
            "bronorganisatie": "000000000",
            "omschrijving": "aangepast",
            "toelichting": "string",
            "zaaktype": "https://catalogi-api.vng.cloud/api/v1/zaaktypen/f0cdd277-c62d-4464-a0a7-ddffd6d29f6b",
            "registratiedatum": "2019-04-09",
            "verantwoordelijkeOrganisatie": "000000000",
            "startdatum": "2019-04-09",
            "einddatum": null,
            "einddatumGepland": "2019-04-20",
            "uiterlijkeEinddatumAfdoening": "2019-04-09",
            "publicatiedatum": "2019-04-09",
            "communicatiekanaal": "",
            "productenOfDiensten": [],
            "vertrouwelijkheidaanduiding": "openbaar",
            "betalingsindicatie": "geheel",
            "betalingsindicatieWeergave": "De met de zaak gemoeide kosten zijn geheel betaald.",
            "laatsteBetaaldatum": null,
            "zaakgeometrie": {
                "type": "Point",
                "coordinates": [
                    53.0,
                    5.0
                ]
            },
            "verlenging": {
                "reden": "",
                "duur": null
            },
            "opschorting": {
                "indicatie": true,
                "reden": "string"
            },
            "selectielijstklasse": "https://referentielijsten-api.vng.cloud/api/v1/resultaten/fb65ae34-e820-4ace-815a-cf5da7d04a12",
            "hoofdzaak": null,
            "deelzaken": [],
            "relevanteAndereZaken": [],
            "eigenschappen": [
                "https://zaken-api.vng.cloud/api/v1/zaken/01a50969-359c-4a0e-95ca-79293914534b/zaakeigenschappen/e5235521-e735-40a3-8005-2b9953757c2c"
            ],
            "rollen": [],
            "status": null,
            "zaakinformatieobjecten": [],
            "zaakobjecten": [],
            "kenmerken": [],
            "archiefnominatie": null,
            "archiefstatus": "nog_te_archiveren",
            "archiefactiedatum": null,
            "resultaat": null,
            "opdrachtgevendeOrganisatie": "",
            "processobjectaard": null,
            "startdatumBewaartermijn": null,
            "processobject": {
                "datumkenmerk": "",
                "identificatie": "",
                "objecttype": "",
                "registratie": ""
            }
        }
    ]
}
```

In mijn ogen is de definitie van het attribuut "processobjectaard" een designfout en had er een lege string "" teruggeven moeten worden in plaats van null. Want alle andere attributen van het type string geven wel een lege string "" terug zoals datumkenmer, identificatie, objecttype , etc.

**Comment by sergei-maertens** [comment]
OpenAPI maakt gebruik van JsonSchema (ze zijn niet 100% gelijk, maar bewegen wel die kant op), dus om deze vraag te beantwoorden moet je naar de details van JsonSchema kijken. Een eenvoudig voorbeeld:

```yaml
type: object
required:
  - property1
properties:
  property1:
    type: string
    maxLength: 80
  property2:
    type:
      - string
      - 'null'
    maxLength: 20
```

* `required` betekent dat deze attributen (`property1`) altijd aanwezig moeten zijn. `{}` is dus niet valide, `{"property1": ""}` en `{"property1": "", "property2": ""}` zijn dat wel. Required zegt nooit iets of een lege waarde toegestaan is of niet, alleen of er een garantie is dat de key aanwezig is of niet.
* `property1` heeft als mogelijke datatypes (meervoud belangrijk!) enkel `string`, met hierboven een extra restrictie: maximaal 80 karakters. Dus, deze mag een lege string zijn, maar mag niet afwezig zijn en mag niet langer dan 80 karakters zijn.
* `property2` heeft als mogelijke datatypes `string` en `null`. Dus, als de property aanwezig is, dan mag die `null` zijn, en als die een `string` is, dan mag die een lege string zijn of maximaal 20 karakters tellen. De property mag ook helemaal afwezig zijn.

Extra validates zijn altijd bovenop het type waarop de validatie betrekking heeft. `maxLength` heeft geen betekenis voor `null`, en is dus niet relevant. Een property die niet required is, mag enkel als `null` meegestuurd worden als het type van de property `null` toestaat.

In OpenAPI 3.1 gebruiken ze deze array voor types, voor eerdere versie is hier de `nullable: true` schema key beschikbaar (even uit het hoofd).

De volgende ("lege") data objecten zijn dus *wel* geldig voor het schema hierboven:

```json
{"property1": ""}
```

```json
{"property1": "", "property2": ""}
```

```json
{"property1": "", "property2": null}
```

Dit is een onderwerp waar veel verwarring over bestaat, maar het is wel gespecifieerd in de onderliggende JsonSchema specificatie.

**Comment by sergei-maertens** [comment]
@HenriKorver 

> Persoonlijk vind ik het mooier als attributen van het type "string" een lege string "" als lege waarde teruggeven en niet null. Het is namelijk een lege waarde die het datatype string al van zichzelf heeft en je hoeft dan geen nieuw concept zoals null te introduceren. Hetzelfde verhaal voor attributen van het type "array": die geeft je de lege lijst [] terug en niet de waarde null. Immers het datatype array heeft intrinsiek een eigen lege waarde namelijk de lege lijst [] net zoals string ook zijn eigen lege waarde heeft namelijk de lege string "".

Hier zit wel nuance die relevant kan zijn! `null` is een weergave dat er niets gezet is, het is onbekende informatie. Terwijl een lege array `[]` gewoon kan betekenen dat er wel iets gezet is, maar er is geen relevante informatie. `null` lees je typisch als "onbepaald", in plaats van "leeg". Tri-state logica kent bijvoorbeeld `true | false | null` om dit weer te geven.

**Comment by basretera** [comment]
@sergei-maertens Dank voor je heldere uiteenzetting!

**Comment by erikhoevenberg** [comment]
Bovenstaande maakt het een en ander duidelijk maar ik heb nog een vervolg vraag. Is "" een geldige waarde voor een url/datum/duration? Voor enum kan ik afleiden dat dit niet het geval is omdat er soms expliciet een "Empty Enum" optie staat gespecifieerd.

**Comment by sergei-maertens** [comment]
Voor de zekerheid heb ik het zelf even getoetst op https://www.jsonschemavalidator.net/, met schema:

```json
{
  "type": "string",
  "format": "date-time"
}
```

en waarde:

```json
""
```

en deze is inderdaad niet geldig. Daarom zou je dus typisch wel `null` toelaten om een onbekende waarde te communiceren.

**Comment by erikhoevenberg** [comment]
Moeten wij in plaats van null een lege string teruggeven als bijvoorbeeld de toelichting op een zaak niet gespecificeerd is?

Zelf vind ik dit niet logisch namelijk omdat dit niet de waarde is die origineel is opgegeven. Daarbij moet de api dan zelf een onbekende waarde mappen op "" wat ik als ontwikkelaar irritant vind omdat het een extra stukje complexiteit toevoegt. Verder zou het inconsistent zijn met strings die een bepaald formaat hebben, die kunnen immers niet "" zijn zoals hierboven vastgesteld. Tenzij er bewust voor wordt gekozen af te wijken van hoe json schema’s normaal gesproken werken.

@HenriKorver, zou jij je antwoord nog eens kunnen bekijken? Ik volg je redenering maar ik vraag me af of het handig is.

**Comment by sergei-maertens** [comment]
`toelichting` kan nooit `null` zijn in de response, want de API spec laat het niet toe, maar zo te zien wordt dat niet netjes gerenderd op zaken-api.vng.cloud

Dezelfde spec uit Open Zaak:

![image](https://github.com/VNG-Realisatie/gemma-zaken/assets/5518550/e9acf346-4bea-41e2-808e-4f0cff3e1177)

v.s. een veld wat wel `null` kan zijn:

![image](https://github.com/VNG-Realisatie/gemma-zaken/assets/5518550/79b669b0-875d-425e-96e9-e12be1027859)

Dus voor een toelichting die niet opgegeven is kan de enige geldige waarde de lege string `""` zijn.

**Comment by HenriKorver** [comment]
@erikhoevenberg, helaas kan ik mijn antwoord niet herzien, zie bovenstaande uitleg van @sergei-maertens

**Comment by HenriKorver** [comment]
> ..., maar zo te zien wordt dat niet netjes gerenderd op zaken-api.vng.cloud

@sergei-maertens Wat gaat er precies mis met de rendering op zaken-api.vng.cloud, want ik kan dat hier niet reconstrueren?

**Comment by erikhoevenberg** [comment]
Zo kun je er ook naar kijken en dan is het antwoord op mijn vraag dus gewoon ja.

Als ik de standaard nu letterlijk neem ben ik niet in staat om bijvoorbeeld communicatiekanaal leeg te maken via de PATCH. Want null is geen optie en een lege string ook niet. Ik kan hem wel via de PUT updaten en dan simpelweg het veld weglaten. Dit lijkt me niet de bedoeling en zou worden opgelost als null wel was toegestaan.

Ik zou zelf liever zien dat null altijd was toegestaan voor een string, tenzij er een functionele reden is waarom het gevuld moet zijn natuurlijk. Maar ik schat zo in dat ik op dit punt geen gelijk ga krijgen.

Ik was er vanwege de opmerking van Sergei vanuit gegaan dat null impliciet een mogelijk waarde was op communicatiekanaal, maar dat is natuurlijk niet zo.

Overigens geeft de referentie implementatie en lege string terug bij communicatiekanaal.

We kunnen hier wel mee verder in ieder geval. Dankjulliewel voor de uitleg.

**Comment by sergei-maertens** [comment]
> > ..., maar zo te zien wordt dat niet netjes gerenderd op zaken-api.vng.cloud
> 
> @sergei-maertens Wat gaat er precies mis met de rendering op zaken-api.vng.cloud, want ik kan dat hier niet reconstrueren?

My bad, de null voor einddatum staat er wel, in nieuwere redoc versies staat die alleen wat prominenter in beeld!

**Comment by HenriKorver** [comment]
@basretera Ik begrijp je probleem niet zo goed. Kun je een concreet voorbeeld geven waar je deze velden niet fatsoenlijk kunt ondersteunen bij POST/PUT/PATCH?

**Comment by basretera** [comment]
Zie citaat en eerdere reacties van @sergei-maertens: een lege string "" is geen geldige URL volgens json schema validator. Dit geldt ook voor date-time en duration velden. M.a.w. zou het dus eigenlijk niet geaccepteerd moeten worden dat een URL-veld zoals bijvoorbeeld "communicatiekanaal" een lege string mag bevatten. Je laat het veld dus weg, of je geeft als clientapplicatie ook daadwerkelijk een geldige URL mee als waarde of null.

Als we er niet uitkomen, zou ik willen opteren voor een mondeling overleg met wat belanghebbenden/betrokkenen.

**Comment by terborg** [comment]
Beste allemaal,

Ook mij lijkt het de consistentie ten goede komen als we hier een verduidelijking op maken. Als we kijken naar wat er gekozen is in recentere programmeertalen zoals Go en Rust, en in de updates die gedaan zijn op bijv. Protocol Buffers (versie 3), dan kom je uit op een *zero-default policy*. De genoemde voordelen van deze policy zijn minder fouten en kortere code.

Dit houdt in dat properties op de volgende waarden gezet worden als deze zijn weggelaten in json:

 * `int` wordt `0`
 * `float` wordt `0.0`
 * `bool` wordt `false`
 * `string` wordt `""` (een lege string)
 * `array` wordt `[]` (een lege array)
 * `object` wordt `{}` (een leeg object)
 * bij enumeraties een expliciet eerste zero value veld

Defaults anders dan zero zouden we kunnen deprecaten, ook vanwege het principle of least surprise. 

Concrete voorbeelden:

 1. Veld weglaten in de request body: Conform de zero-default policy, als een optioneel veld niet in de JSON-body voorkomt, interpreteert de ontvangende applicatie dit als de zero-value: bijvoorbeeld als lege string ("").
 2. Veld opnemen met de waarde null: Dit wordt met deze policy expliciet afgeraden voor het aanduiden van een "niet-ingevulde" of "afwezige" waarde. De zero-value ("" voor strings) vervult die rol.
 3. Veld opnemen met een lege waarde "", [], etc.: Dit is perfect in lijn met de policy en functioneel equivalent aan het weglaten van het veld (beide resulteren in een lege string aan de ontvangende kant).

Om punt 3 toe te blijven staan in combinatie met JSON schema validators, zouden we voor velden die gebruik maken van de format:-specifier een aanpassing moeten doen naar het volgende voorbeeldstuk OpenAPI spec,

```yaml
OptioneelDatumType:
  type: string
  default: ""
  oneOf:
    - type: string
      enum: [""]                  # Optie 1: leeg / nul-state (zelfde als weglaten)
    - $ref: "pad/naar/DatumType"  # Optie 2: gezet datumveld

DatumType:
  type: string
  format: "date"
```

wat dan opgenomen zou kunnen worden in bijvoorbeeld een common schema. Het lijkt me dat deze policy niet alleen de consistentie van de spec zou verhogen, maar ook de robuustheid (testbaarheid) en onderhoudbaarheid van de API's.

Graag jullie feedback.

**Comment by sergei-maertens** [comment]
Ik denk dat dit te kort door de bocht is. Waarom is voor een numerieke waarde `0` de default cfr. de zero-default policy? De waarde `0` vs `null` (niet bepaald) is semantisch relevant. Dit komt ook voor bij booleans met tri-state logic: `true`, `false` of `null` (nog niet bepaald). Dit is bijvoorbeeld relevant voor de gebruiksrechten in de Documenten API.

Voor een verlenging bijvoorbeeld is `null` (geen verlenging bepaald) ook iets heel anders dan `0` (de verlenging is 0 <tijd>).

Ik vind dit soort gedragsregels bovenop OAS leggen net wél een grote verrassing en zou adviseren om binnen de gedefinieerde mechanismen van JSON-Schema + OAS blijven, deze zijn namelijk ook voorgeschreven door de NL API strategie.

**Comment by terborg** [comment]
@sergei-maertens dank voor je feedback. Ik begrijp je zorgen over semantische ambiguïteit. Ik zoek naar een policy die het over het algemeen goed zou doen; veel fast messaging wordt met de zero-default gedaan, en hierbij wordt de context of een veld null/None/void is of niet op basis van (sub-) berichttype gedaan.

Maar goed, een expliciete null per veld zou ook kunnen, zolang het maar een consistente policy is. We zouden het dan bijvoorbeeld voor enums moeten aanpassen, want de huidige lege string "" (met BlankEnum et al) is niet een nullable enum. Zie ook hier https://swagger.io/docs/specification/v3_0/data-models/enums/#nullable-enums

Je krijgt dan dergelijke enums,

```yaml
type: string
nullable: true
enum:
  - null
  - waarde1
  - waarde2
```

De snippets die ik stuurde zijn uiteraaard geldige OpenAPI (3.0). Mocht je het in een JSON schema validator willen proberen, dan zie je zoiets

![Image](https://github.com/user-attachments/assets/5d794467-c33b-4973-81a0-3fb3edf44b9e)

Het wordt bij OpenAPI mixed type genoemd, zie hier https://swagger.io/docs/specification/v3_0/data-models/data-types/#mixed-types

**Comment by terborg** [comment]
Oké, hierbij take 2 voor een *null-value policy*:

 * een property kan ofwel optioneel zijn of required, maar niet allebei
 * optioneel is hetzelfde als nullable, kan null zijn, en heeft als default null
 * required is hetzelfde als has-value en kan niet null zijn

Voorbeelden:

Optional scalar types
```yaml
properties:
 value:
   type: integer
   nullable: true
   default: null

required:
 # - value:    <- LINTER ERROR
```

Required scalar types
```yaml
properties:
 value:
   type: integer
   # nullable: <- LINTER ERROR
   # default:  <- LINTER ERROR

required:
 - value
```


Optional date type
```yaml
properties:
 value:
   type: string
   nullable: true
   default: null
   format: date

required:
 # - value:    <- LINTER ERROR
```

Optional enum
```yaml
properties:
 value:
   type: string
   nullable: true
   default: null
   enum:
    - null  
    - waarde1
    - waarde2

required:
 # - value:    <- LINTER ERROR
```


Zo beter?

**Comment by terborg** [comment]
@sergei-maertens  Bedankt voor je reactie!

Ik heb de betreffende HTTP-operaties nu expliciet toegevoegd aan de [policy hierboven](https://github.com/VNG-Realisatie/gemma-zaken/issues/2447#issuecomment-2916415145) ter verduidelijking.

Mijn voorstel voor de null-value policy met `application/merge-patch+json` is gebaseerd op en volgt  [RFC 7396](https://datatracker.ietf.org/doc/html/rfc7396) voor PATCH operaties. Als we die standaard als uitgangspunt nemen voor dit mediatype en dit mediatype specificeren voor PATCH operaties, wordt er hopelijk minder gediscusieerd over PATCH-gedrag.

De werking van `application/merge-patch+json` volgens RFC 7396 is specifiek anders dan je beschrijft; het biedt bijvoorbeeld geen ondersteuning voor het atomair toevoegen van elementen aan een array (arrays worden in hun geheel vervangen). De functionaliteit die je noemt is kenmerkend voor een ander media-type en RFC, namelijk `application/json-patch+json` uit [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902). Wellicht zat je daaraan te denken?

Mocht je nog andere onduidelijkheden of inconsistenties vinden in de null-value policy, dan hoor ik het graag.

**Comment by sergei-maertens** [comment]
> Wellicht zat je daaraan te denken?

Ik gooi ze warschijnlijk inderdaad door elkaar.

Ik vind het voorstel om diverse RFCs aan te houden en via content types te werken om gedrag duidelijk te maken een enorm goed initiatief. Tegelijkertijd voel ik me verplicht om vanuit ervaringen in het ZGW traject wat somberdere adviezen te delen.

Het gebruik van JSON API's is/was voor veel leveranciers al een ongemakkelijke situatie door gebrek aan herkenning/ervaring hiermee, met name omdat ze voordien vooral (enkel?) SOAP/XML toepasten. Ik ben er zelf achter gekomen dat dingen die voor mij evident waren (zoals hoe een HTTP header meesturen voor authenticatie) absoluut niet evident was. In dezelfde lijn dus ook mijn ervaring dat het correct interpreteren van een eenvoudige OpenAPI-specificatie ook niet evident bleek, omdat mensen nogal snel geneigd zijn te denken dat ze begrijpen wat er staat, maar niet vertrouwd zijn met de achterliggende specificaties en semantiek.

In de geschiedenis van standaarden toegepast binnen de NL overheid zie je dat er ook vaak specifieke constructies bedacht zijn die enkel in NL toegepast worden. Vaak omdat men gewoon niet wist dat er een internationale standaard dan wel conventie voor bestond, of omdat die op dat moment nog niet bestond. Dit heeft echter wel als effect dat partijen die de standaard implementeren vaak pas voor het eerst met deze in aanraking komen, en dus een steile leercurve hebben. Ik ben bang dat dit soort "geavanceerde" content types zijn nuances en details die door weinig partijen opgemerkt gaan worden dan wel correct geïmplementeerd worden.

Met veel van deze zaken merk je dat er mooie bedoelingen zijn om generieke (REST/HATEOAS) clients te bedienen, maar dat in de praktijk heel weinig partijen ook daadwerkelijk dergelijke clients bouwen/gebruiken. Dat is eenvoudig te verklaren - een specifieke client implementeren is veel sneller gerealiseerd en je kan alle edge cases en theoretische details vermijden. Ik heb bijvoorbeeld nog nooit een partij/client gezien die bewust/actief met `application/problem+json` omgaat voor validatiefouten, maar de bulk interpreteert gewoon eender welke response als `application/json`. Content-type negotation is ook awkward, want technisch gezien zou je dan een `Accept: application/json, application/problem+json` moeten meesturen als je expliciet verwacht dat er validatiefouten kunnen zijn.

Dit hele verhaal hierboven vermeld ik omdat de PATCH nuances nog een stuk ingewikkelder en minder intuitief zijn dan de content type voor validatiefouten, en ik heel pessimistisch ben over welke partijen hier daadwerkelijk gebruik van gaan maken. Dit is ook waarom voor het pragmatische applicatie-specifieke PATCH-gedrag (zelfs per endpoint) gekozen is - het is waarschijnlijk een stuk intuitiever en laagdrempeliger, maar het vereist dus wel een manier om twijfels/ambiguiteiten te kunnen valideren (bijvoorbeeld tekstuele/functionele documentatie).

Ik ben heel groot voorstander om per endpoint/stuk funtionaliteit in de API te bepalen wat het meest developer-friendly gedrag is, en daarom ben ik dus géén voorstander van dergelijke (ingewikkelde) rigide constructies, hoe elegant en standards-compliant het ook is (waar ik wél door gecharmeerd ben). Voor Echte Wereld APIs kijk ik ook graag naar de developer portals van grote bedrijven die APIs aanbieden documenteren, zoals Bol en Zalando bijvoorbeeld, maar ook de Github APIs. Als je ziet dat hun ook bepaalde pragmatische keuzes maken, dan zie ik dat als een argument die mijn bevindingen kracht bijzetten.

**Comment by terborg** [comment]
Hoi @sergei-maertens , Bedankt voor je uiteenzetting. Echte-wereld API's zijn in mijn beeld best divers. Bijvoorbeeld, in de trading-platform wereld zijn veel platform-specifieke protocollen, elk met hun eigen specificaties voor content, encoding (soms tot aan binary delta-encodings), transport en business rules. Grote bedrijven komen vaak weer met hun eigen protocollen (e.g., Protocol Buffers). Met andere woorden, be careful what you wish for :-) Het lijkt me dat we zo helder mogelijk moeten blijven specificeren, bij voorkeur met standaarden.

Goed dat je Zalando noemt, hun API Guidelines (https://opensource.zalando.com/restful-api-guidelines/#patch) specificeren expliciet het media-type `application/merge-patch+json` voor PATCH operaties en een [null-afhandeling](https://opensource.zalando.com/restful-api-guidelines/#123) die overeenkomt met het eerdere voorstel. De [Swiss API Guidelines](https://github.com/swiss/api-guidelines ) zijn hierop gebaseerd en hanteren dezelfde standaarden.

NL API Design Rules: die komen zover als zeggen dat PATCH een update doet :-)

Deze voorbeelden laten zien dat er internationale consensus lijkt te bestaan voor [bovenstaande](https://github.com/VNG-Realisatie/gemma-zaken/issues/2447#issuecomment-2916415145) null-value policy en het gebruik van `application/merge-patch+json` voor PATCH.

**Comment by basretera** [comment]
Oké! En hoe nu verder?
