### ISSUE TITLE
Gebruik maken van data uit nieuwe versie van een zaaktype

### ISSUE THREAD

**Issue by OlavAllema** [VNG-Realisatie/gemma-zaken#2450]
In de praktijk ervaren we dat er behoefte is aan het toepassen van wijzigingen aan een zaaktype en die toe te passen voor lopende zaken. Een nieuwe versie van een zaaktype is nu niet geldig voor lopende zaken.

Verdere toelichting:
Sommige zaken lopen lang. Er is dan kans dat er nieuwe metadata (nodig) is. De mogelijkheid om een lopende zaak bij te werken met nieuwe info uit een nieuwe versie van een zaaktype is er nu niet.

Hoe staan jullie t.o.v. deze casus? 

Zie de eerdere reactie vanuit Maykin/Open Zaak hier:
https://github.com/open-zaak/open-zaak/issues/1620#issuecomment-2160344344

**Comment by michielverhoef** [comment]
Het is tegenwoordig mogelijk om het zaaktype aan te passen van een zaak. Daar zitten wat haken en ogen aan maar in principe is het dan mogelijk om naar een nieuwere versie van hetzelfde zaaktype te wijzen.

Overigens is het idee juist om een zaak af te handelen volgens de spelregels die gelden op het moment van indienen van de zaak, ongeacht wanneer die zaak afgehandeld wordt. Met andere woorden, een zaak kan niet achteraf tegen andere eisen beoordeeld en afgehandeld worden dan bekend tijdens het indienen van de zaak.

(Plat voorbeeld: Wanneer je een boete krijgt voor te hard rijden op een snelweg (max snelheid 100 km/u, boete voor 120 km/u) en ondertussen wordt de max snelheid aangepast naar 130 km/u kun je niet achteraf zeggen dat je volgens de nieuwe regels wel binnen de snelheid gebleven bent.)

Persoonlijk ben ik niet zo'n voorstander van het voorstel uit de casus, het idee het zaaktype aan te passen tijdens het afhandelen. Wanneer blijkt dat in een versie van een zaaktype fouten zitten die hersteld moeten worden om lopende zaken correct af te handelen kan het zaaktype aangepast worden met behulp van een [correctie](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/#correctie). Maar die wijzigingen gelden dan voor alle zaken van (die versie van) dat zaaktype. Niet slechts voor een paar zaken die (te) lang op de plank hebben gelegen.

**Comment by OlavAllema** [comment]
Dank voor je uitgebreide reactie Michiel.

Groet, Olav

Van: Michiel Verhoef ***@***.***>
Beantwoorden - Aan: VNG-Realisatie/gemma-zaken ***@***.***>
Datum: woensdag 19 juni 2024 om 12:29
Aan: VNG-Realisatie/gemma-zaken ***@***.***>
CC: Olav Allema ***@***.***>, Author ***@***.***>
Onderwerp: Re: [VNG-Realisatie/gemma-zaken] Gebruik maken van data uit nieuwe versie van een zaaktype (Issue #2450)


Het is tegenwoordig mogelijk om het zaaktype aan te passen van een zaak. Daar zitten wat haken en ogen aan maar in principe is het dan mogelijk om naar een nieuwere versie van hetzelfde zaaktype te wijzen.

Overigens is het idee juist om een zaak af te handelen volgens de spelregels die gelden op het moment van indienen van de zaak, ongeacht wanneer die zaak afgehandeld wordt. Met andere woorden, een zaak kan niet achteraf tegen andere eisen beoordeeld en afgehandeld worden dan bekend tijdens het indienen van de zaak.

(Plat voorbeeld: Wanneer je een boete krijgt voor te hard rijden op een snelweg (max snelheid 100 km/u, boete voor 120 km/u) en ondertussen wordt de max snelheid aangepast naar 130 km/u kun je niet achteraf zeggen dat je volgens de nieuwe regels wel binnen de snelheid gebleven bent.)

Persoonlijk ben ik niet zo'n voorstander van het voorstel uit de casus, het idee het zaaktype aan te passen tijdens het afhandelen. Wanneer blijkt dat in een versie van een zaaktype fouten zitten die hersteld moeten worden om lopende zaken correct af te handelen kan het zaaktype aangepast worden met behulp van een correctie<https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/#correctie>. Maar die wijzigingen gelden dan voor alle zaken van (die versie van) dat zaaktype. Niet slechts voor een paar zaken die (te) lang op de plank hebben gelegen.
