### ISSUE TITLE
Is het toegestaan om de verantwoordelijkOrganisatie van een zaak aan te passen?

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/gemma-zaken#2460]
Uitgangssituatie (voorbeeld):
- Er is in het ZTC een catalogus aanwezig gekoppeld aan RSIN 123456782, zijnde gemeente Zonnedael.
- Er is in het ZTC een zaaktype "Bezwaar behandelen" aanwezig die deel uit maakt van deze catalogus.
- Er is een zaak in de ZRC geregistreerd met zaaktype "Bezwaar behandelen" en verantwoordelijkOrganisatie 123456782.

Vragen:
1. Klopt de aanname dat de verantwoordelijkOrganisatie van de zaak moet matchen met het RSIN van de zaak.zaaktype.catalogus?

Zo nee:
2. Hoe moet ik dit dan interpreteren?
3. Zit er een überhaupt een relatie tussen de catalogus en de verantwoordelijkOrganisatie van een zaak? Of evt. bronorganisatie?

Zo ja:
4. Waarom mag ik dan de verantwoordelijkOrganisatie aanpassen in een PUT of PATCH van de zaak? Ik mag namelijk het zaaktype niet wijzigen? Dit zou dan resulteren in een mismatch.
5. Zou er run-time gedrag beschreven moeten worden hiervoor in de standaard?

**Comment by sergei-maertens** [comment]
Bij mijn weten moet je niet afdwingen dat RSIN van zaaktypecatalogus overeenkomt met RSIN in de zaak zelf. Enkel zaaktyp een zaakidentificatie mogen niet gewijzigd worden, de rest is muteerbaar.

**Comment by HenriKorver** [comment]
Eens  met het antwoord van @sergei-maertens
