### ISSUE TITLE
Wijzigen van afgesloten zaken

### ISSUE THREAD

**Issue by peterDenHaag** [VNG-Realisatie/gemma-zaken#2480]
# Impediment

Een basis uitgangspunt van het zaakgericht werken is dat een gesloten zaak niet meer gewijzigd mag worden. De werkzaamheden zijn afgerond en er vinden dus geen handelen meer plaats. In praktijk is dit niet realistisch en levert dit problemen op.
 
Er zou -voor het wel of niet kunnen wijzigen van zaken- onderscheidt moeten worden gemaakt tussen de verschillende acties. Te weten 1) administratieve verwerkingen én 2) het uitvoeren van (werk)processen. Het eerste zou moeten kunnen na het sluiten van een zaak, maar het tweede is uitgesloten en moet in een nieuwe zaak. Voor de volledigheid heb ik deze tweede ook toegevoegd.
 
**Voorbeeld:**
Administratieve handelingen die **wel** kunnen in een afgesloten zaak, zoals:

1. Nagezonden documenten toevoegen aan een gesloten zaak (sec archivering);
2. Wijzigen van metadata van een zaak, zoals gerelateerde zaken toevoegen
 
Uitvoeren van (werk)processen die **niet** kunnen in een afgesloten zaak, zoals:

3. Reageren of andere acties verrichten naar aanleiding van aangeleverde documenten;
4. Herzien van eerder ondernomen acties door de behandelend medewerker;
Voor deze werkzaamheden moet een nieuwe zaak worden gestart

Voor de beeldvorming is een aantal veel voorkomende scenario's beschreven waarbij het nu misgaat:

**ad 2. Bezwaar- en beroep n.a.v. afgeronde zaak:** 
Op het moment dat een beschikking is verstuurd naar de aanvrager, is een zaak afgerond. In de meeste gevallen kan de aanvragen binnen 6 weken bezwaar en/of beroep aantekenen tegen het genomen besluit. De behandeling van het bezwaar/beroep is een nieuwe zaak. Het bezwaar heeft een relatie met de zaak waartegen bezwaar is gemaakt. Het is alleen niet mogelijk om aan de afgesloten zaak de later gestarte bezwaar-zaak op te voeren als gerelateerde zaak. Een traject van bezwaar, beroep en hoger beroep kan jaren duren. In geval van een weigering betekent dit veelal dat de oorspronkelijke zaak waartegen bezwaar is gemaakt al vernietigd is alvorens het juridische proces is afgerond. Door aan de oorspronkelijke afgesloten zaak de later gestarte gerelateerde zaken toe te voegen, kan worden voorkomen dat de afgesloten zaak voortijdig wordt vernietigd.

**ad. 1 melding voltooiing werkzaamheden:** 
De buitendienst constateert tijdens een werk rit dat de werkzaamheden van een afgegeven omgevingsvergunning zijn afgerond. De medewerker belt aan en - op basis van digitale stuken die hij ter plaatse kan oproepen - voort deze medewerker de eindcontrole uit en sluit deze de zaak. De vergunninghouder besluit naderhand om voor de volledigheid nog de voltooiingwerkzaamheden te versturen naar de gemeente. Dit resulteert niet in nieuwe werkzaamheden en het document dient alleen te kunnen worden toegevoegd aan de reeds gesloten zaak.
 
**De functionele vraag:**
Het - met een systeemaccount - kunnen wijzigen van zaakgegevens van afgesloten zaken. Dit betreft metadatering van zaken en DMS.
Medewerkers mogen geen wijzingen kunnen aanbrengen in afgesloten zaken.

**Comment by michielverhoef** [comment]
Dit kan al enige tijd met de scope `zaken.geforceerd-bijwerken` en `documenten.geforceerd-bijwerken`.

@terborg @HenriKorver

**Comment by peterDenHaag** [comment]
Dat was bij ons niet bekend. We gaan dit uitzoeken!
