### ISSUE TITLE
[VRAAG] Koppelen van zaakrelaties 

### ISSUE THREAD

**Issue by KarinMasselink** [VNG-Realisatie/gemma-zaken#2492]
Ik ben bezig met het koppelen van zaken, daar kennen we binnen OpenZaak 2 versies van namelijk Hoofd en deelzaaktypen en gerelateerdezaaktypen (Deze laatste in 3 vormen, bijdrage, onderwerp en vervolg). Die gerelateerde zaken match op dit moment niet met de gemeentelijke bewoording voor het leggen van zaakrelatie. 

In het gemma model gaven ze hier eerder ook andere bewoording aan: [https://www.gemmaonline.nl/wiki/Hoofd-_en_deelzaken_en_gerelateerde_zaken#Let_op:_deze_pagina_is_gearchiveerd](url) maar nu blijkt deze pagina ook gearchiveerd er is geen referentie naar een nieuwe pagina. 

Mijn vraag: hoe kom ik erachter waarom jullie voor die 3 benamingen gekozen hebben en waar vind ik meer tekst en uitleg over de drie vormen wat ze inhouden: Volgens de API specificaties zie ik nu de volgende 3 benamingen:
vervolg - Vervolg
bijdrage - Bijdrage
onderwerp - Onderwerp

Ik ben opzoek naar informatie hoe ik versus het oude Gemma informatiemodel nu zaakrelaties moet gaan koppelen en hoe dit informatiemodel er nu uit ziet? Waar kan ik dit vinden, zodat ik met mijn zaaksysteem kan aansluiten hierop. 
Gemeenten willen graag zaken relateren en kennen nu het oude model en zien dit graag terug.

**Comment by HenriKorver** [comment]
De informatiemodellen, api standaarden en stuf standaarden zijn verhuisd van GEMMA naar GitHub. Informatie over het RGBZ is nu hier te vinden:

- https://vng-realisatie.github.io/RGBZ
- https://vng-realisatie.github.io/RGBZ/documentatie
- https://vng-realisatie.github.io/RGBZ/documenten/RGB_Zaken_1%200_(in_gebruik)_201000922.pdf

**Comment by HenriKorver** [comment]
Ik zie nu dat de voor deze vraag relevante versies van het RGBZ verloren zijn geraakt tijdens de migratie van GEMMA Online naar GitHub. Ik heb ze hieronder toegevoegd:

- [GEMMA_RGBZ_2.0_deel_1_CONCEPT3_20141204.pdf](https://github.com/user-attachments/files/17845474/GEMMA_RGBZ_2.0_deel_1_CONCEPT3_20141204.pdf)

- [GEMMA_RGBZ_2.0_deel_2_CONCEPT3_20141204.pdf](https://github.com/user-attachments/files/17845460/GEMMA_RGBZ_2.0_deel_2_CONCEPT3_20141204.pdf)

**Comment by HenriKorver** [comment]
@melsk-r Kun je de twee bovenstaande PDF's toevoegen aan deze github-repo:

https://vng-realisatie.github.io/RGBZ/documentatie

**Comment by HenriKorver** [comment]
@melsk-r Vroeger waren op GEMMA Online het RGBZ en imZTC beschikbaar als clickable maps. Dan kon je door de class diagrammen en relaties heen klikken, heel handig. Zijn die er ook niet meer?
