### ISSUE TITLE
De kerngroep CG wil voor andere gemeenten en ketentoepassingen een referentieimplementatie maken van het Haarlemse zaaksysteem (zaakmagazijn, ZTC, ...) ... #46

### ISSUE THREAD

**Issue by WouterBRu** [VNG-Realisatie/gemma-zaken#25]
zodat er een gezamenlijke open source basis is voor het toepassen van zaakgerichte componenten.

**Comment by jgortmaker1** [comment]
- [ ]  #23 
- [ ]  #24 
- [ ]  #28 
- [ ]  #29 
- [ ]  #30

**Comment by ehotting** [comment]
Buiten scope, zie #28.  Kan user story zijn op https://github.com/Haarlem evt., maar beheerorganisatie zal dan nodig zijn.
