### ISSUE TITLE
Interne links in documentatie werken niet in Hugo

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#251]
De .md files worden getoond als page in de browser, met een trailing '/'

Hierdoor werken interne links niet correct.

Bijvoorbeeld:  ./faq.md wordt getoond als /faq/ , bij een link naar ./productvisie.md probeert browser naar /faq/productvisie.md te gaan, resultaat 404

**Comment by ehotting** [comment]
Upstream: https://gitlab.com/commonground/nlx/issues/270

**Comment by joeribekker** [comment]
Lijkt niet opgepakt te worden: https://github.com/gohugoio/hugo/issues/1921

**Comment by joeribekker** [comment]
In je opschoon branch bijgewerkt om met Hugo om te gaan: https://github.com/VNG-Realisatie/gemma-zaken/pull/252/commits/8e9a0c7ffc59cccaecab99dd301dcdda509b8506
