### ISSUE TITLE
Uitbreiden FAQ met vragen en antwoorden

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#253]
Alleen vragen aan FAQ toevoegen wanneer ook direct het antwoord wordt gegeven a.u.b.

Vragen waarop antwoord gewenst is:

- [ ] Komt er een landelijke versie van dit "product"?
- [ ] Worden zaaksystemen hiermee beter, goedkoper, sneller, beter uitwisselbaar, etc.?
- [ ] Kan ik als gemeente aansluiten tijdens het project?
- [ ] Kan ik als leverancier aansluiten tijdens het project?
- [ ] Wat betekent dit voor gemeentes?
- [ ] ..
- [ ] ..
- [ ] ..
- [ ] ..

**Comment by ehotting** [comment]
@TCIMEddy Laten we bij wijziging FAQ alleen complete setjes vragen / antwoorden toevoegen, geen 'To Do'. Hierboven de vragen die nog niet beantwoord zijn. In https://github.com/VNG-Realisatie/gemma-zaken/pull/252 staat momenteel update FAQ klaar, graag daarop aanvullen na de merge.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Ik weet niet wat de status is en is meer ongein. Blijft wel punt van aandacht. Kan wat mij betreft op close!
