### ISSUE TITLE
Als PO wil ik een indicatie van de 'code coverage' bij testen referentieimplementaties

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#255]
...zodat we aannemelijk maken dat de CI effectief wordt toegepast.

**Definition of done**
- [ ] Er is integratie van Codecov (of iets dergelijks) met Jenkins & Github op de drie referentieimplementaties

**Taken**
- [ ] Integratie code coverage in CI

**Comment by sergei-maertens** [comment]
@ehotting https://jenkins.nlx.io/view/Gemma/ toont de coverage, dat lijkt mij voldoende? Detailvoorbeeld: https://jenkins.nlx.io/view/Gemma/job/gemma-zaakregistratiecomponent-stable/17/cobertura/

**Comment by ehotting** [comment]
Vind het vooral interessant om het als badge te tonen op de Readme van de drie 
referentieimplementaties

**Comment by sergei-maertens** [comment]
Duidelijk - even snel google-werk toont dat https://jenkins-badges.readthedocs.io/en/latest/ misschien een optie is. Zit in ieder geval niet standaard in Jenkins gebakken.

**Comment by joeribekker** [comment]
Lijkt me prima om dit via een externe service te laten lopen als codecov.io. Zorgt ook voor mooie coverage reports in PRs en je kan ze als merge requirement meenemen.

Gebruiken we nu voor Haarlem ZTC en Zakenmagazijn ook.

**Comment by sergei-maertens** [comment]
Moet nog omgekat worden naar een externe service, dus niet helemaal klaar.

**Comment by ehotting** [comment]
In ieder geval is het dan in progress en moet het dus ergens op juiste board worden gezet...

**Comment by TCIMEddy** [comment]
@ehotting @joeribekker @sergei-maertens Heren ik heb deze user story in sprint 5 (in progress) gezet. Mocht dit niet kloppen laat het weten

**Comment by joeribekker** [comment]
Prima wat mij betreft (maar dit ticket is nu nog niet in progress).

**Comment by ehotting** [comment]
Indien nog niet in progress, er zijn andere dingen belangrijker

**Comment by TCIMEddy** [comment]
@kciredor Ter info

**Comment by TCIMEddy** [comment]
![Schermafbeelding 2019-03-27 om 15 20 10](https://user-images.githubusercontent.com/39735549/55083866-805dcb80-50a4-11e9-83dd-bb0cb868023d.png)

**Comment by michielverhoef** [comment]
Volgens mij is codecov inmiddels in gebruik
