### ISSUE TITLE
Als ontwikkelaar/VNG-contributor wil ik de ZDS-client als standalone library

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#256]
...zodat de code centraal bijgehouden worden en fixes/toevoegingen niet op meerdere plaatsen maintained moeten worden.

De ZDS-client wordt gebruikt in de integratietst, en ondertussen ook in de demo-applicatie. Op dit moment zijn het copies van de code, en lopen ze al lichtjes uit elkaar.

Daarboven komt dat een client-implementatie ook voor taakapplicaties handig kan zijn, mogelijks met later een opstap naar andere programmeertalen.

**Definition of done**
- [x] Er is een Python client in een VNG-Realisatie repository
- [x] De client is op PyPI gepubliceerd
- [x] Gebruik van de client is gedocumenteerd
- [ ] De client wordt als dependency gebruikt in de demo applicatie en integratie-testsuite

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] De client werkt op dezelfde manier als voorheen
- [ ] De owner op PyPI is een VNG-Realisatie account, andere mensen kunnen als maintainer aangeduid worden

**Taken**
- [x] Code verhuizen naar nieuwe repository
- [ ] Samenvoegen wijzigingen Demo/ZIT
- [ ] Aanmaken PyPI account voor `vngr` & credentials aan Eelco bezorgen
- [ ] Publiceren op PyPI
- [ ] Toevoegen als dependency aan ZIT/Demo

**Comment by joeribekker** [comment]
Eens uiteraard. En de eat-your-own-dogfood past goed in de DoD. En, alleen om OAuth voor mensen simpel te houden lijkt me deze client al een goed idee.

Wel enige gedachten hierbij:

1. Wellicht aardig om dezelfde client in Java, C# of PHP te hebben (uiteraard andere issues).

2. Vraag me wel af of het een ZDS specifieke client wordt? Het is op dit moment vooral een generieke OAS client zonder specifieke functies voor ZDS. Ik twijfel of die er wel komen.

3. Ook kan deze client flink wat documentatie gebruiken, de echte API-guide. Er worden denk ik meer clients dan servers gebouwd straks.

**Comment by joeribekker** [comment]
Demo app en Integratie tests maken hier nu gebruik van.

**Comment by joeribekker** [comment]
@sergei-maertens: PyPI-account moet nog naar VNG.

**Comment by sergei-maertens** [comment]
De credentials zitten bij @michielverhoef, `vngr` is owner van de PyPI packages zds-client en zds-schema
