### ISSUE TITLE
Als belanghebbende wil ik presentaties van de sprint review/demo kunnen inzien...

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#258]
...zodat ik alles kan nalezen.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [x] het staat op de documentatie site.

**Acceptatiecriteria**
- [x] Presentaties zijn via de documentatie site te downloaden

**Taken**
- [x] Presentaties verzamelen
- [x] Omzetten naar PDFs
- [x] PDFs opnemen in Github documentatie pagina

**Comment by TCIMEddy** [comment]
Dit is mogelijk via de gehoste site (via GitHub). Alleen moet iemand de documenten in GitHub bijwerken. Separaat heb ik hier een poging toe gedaan.
