### ISSUE TITLE
Als gemeente wil ik toegangsbeheer kunnen inregelen op mijn dossiers ...

### ISSUE THREAD

**Issue by WouterBRu** [VNG-Realisatie/gemma-zaken#26]
... zodat ik aan privacy en beheer regels kan voldoen.

Concrete invulling hiervan:
- #66 

Let op! Dit kunnen ook gearchiveerde dossiers zijn.

** LET OP MOET SLICED WORDEN **

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [ ] er zijn 1 of meer aanbevolen patronen beschreven voor autorisatie binnen de ZDS 2.0
  - [ ] hoe wordt omgegaan met scopes
  - [ ] hoe wordt omgegaan met data visibility, bij voorkeur kan requester zelf beperken
  - [ ] welke methoden zijn aanbevolen om scopes aan autorisaties toe te kennen
  - [ ] welke autorisatiemechanismen worden aanbevolen
- [ ] de OAS 3.0 specificatie is uitgebreid met wat nodig is voor autorisatie
- [ ] deze specificatie is gepubliceerd
- [ ] de referentieimplementatie ondersteunt de aanbevolen patronen
- [ ] er is functionele documentatie waarin de patronen functioneel worden beschreven

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] de DSO URI- en API-strategie worden gevolgd
- [ ] Standaarden van de Pas-toe-of-leg uit lijst van Forum Standaardisatie worden gevolgd

**Taken**
- [ ] Beschrijven welke mechanismen gewenst zijn [ ]
- [ ] Analyse welke uitbreiding van de OAS nodig is [ ]
- [ ] Schrijven (unit) test voor referentie-implementatie [@sergei-maertens]
- [ ] Implementeren in referentie-implementatie [@sergei-maertens]
- [ ] Genereren/opstellen van OAS 3.0 [@sergei-maertens]
- [ ] Functionele documentatie [@michielverhoef ]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [?]

**Comment by ehotting** [comment]
Toegangsbeheer (autorisatie) is mogelijk een complex vraagstuk, waar idealiter vroegtijdig een User Story voor wordt ingediend. Qua prio zou ik dit graag in een vroege sprint hebben. Deze (meer concreet maken), of een andere  meer concrete User Story vanuit een gemeente. Suggesties?

**Comment by jgortmaker1** [comment]
idd concreter maken
met name wat wordt bedoeld met toegangsbeheer: hoe ver wil je daarin gaan? RGBZ ondersteunt basaal toegangsbeheer (vertrouwlijkheid-aanduiding). is dat voldoende of wil je meer? en zo ja, hoeveel meer?

**Comment by EdwinCoster** [comment]
Heeft dit een relatie met https://www.gemmaonline.nl/index.php/Gegevenslandschap_-_Aansluiting_op_het_het_gegevenslandschap_vanuit_gemeentelijk_perspectief

**Comment by sergei-maertens** [comment]
Overleg op 1 oktober

**Comment by michielverhoef** [comment]
Omdat dit koppelvlak-overstijgend is schuif ik graag aan.

**Comment by ehotting** [comment]
Nu we een aantal technische user stories hebben om autorisatie en authenticatie vorm te geven is het goed om een (of meer) concrete user story te hebben waarin een realistisch scenario wordt beschreven. Deze is niet concreet genoeg en daarmee dubbel t.o.v. #424 en #427. @WouterBRu @CMasselink is het mogelijk hiervoor 1 of meerdere user stories te definiëren uit de praktijk, waaraan we de oplossing kunnen toetsen? Dan kan deze worden gesloten.

**Comment by TCIMEddy** [comment]
66 hogere prio en make ready en deze dan close
