### ISSUE TITLE
‘Overzichtsplaatjes’ doelstelling en context API’s

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#260]
Zoals besproken tijdens de retrospective. Duidelijk plaatje maken zodat we daar altijd naar terug kunnen grijpen (en gebruiken tijdens demo)

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Weet je nog wat je bedoelde, zo ja toevoegen en zo nee close

**Comment by ArjanKloosterboer** [comment]
Ik vermoed dat dit ging over een plaatje over hoe ver we nu zijn met het verAPIen van RGBZ en ImZTC. 
Ik heb een idee in mijn hoofd. Werk dat binnenkort uit en kom met een voorstel.

**Comment by ArjanKloosterboer** [comment]
Ziehier een plaatje met een indicatie hoe ver we zijn. Nog slechts voorbeeldgewijs uitgewerkt voor twee objecttypen en fake-verhoudingen. Dit is eenvoudig te onderhouden: simpelweg vinkjes zetten (in de onderliggende spreadsheet) bij gegevens en relaties die in een API cq. resource opgenomen zijn.
![afbeelding](https://user-images.githubusercontent.com/23450232/46026689-48bd9900-c0ec-11e8-92ad-719b7afdd45f.png)
Is dit wat?

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Dit was niet het plaatje dat je hier bedoelde maar heeft betrekking op een andere user story (die op naam van jou en @joeribekker staat). Ik vind het een bijzonder overzichtelijk plaatje en zeer bruikbaar mits eenvoudig bij te houden. @ehotting Graag jouw visie hierop want dit is een user story die door jou is ingebracht. Deze user story zet ik dan op wontfix en close en plak je plaatje in de juiste user story.

**Comment by ArjanKloosterboer** [comment]
OK, over naar #405 dus.
