### ISSUE TITLE
Locatie human readable API specs 

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#262]
[Deze links ](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/content/developers/api-specificaties.md)verwijzen nog naar swagger.io, is onze eigen Redoc inmiddels niet aangewezen locatie daarvoor?

**Comment by joeribekker** [comment]
Ad-hoc generatie kan ook via de Redoc site, zoals: http://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/zrc/openapi.yaml

Handig voor versies die nog niet in master zitten.
