### ISSUE TITLE
Als leverancier wil ik kunnen bewijzen dat mijn software compliant is met de standaard

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#263]
...zodat klanten daar bij de selectie en inkoop rekening mee kunnen houden.

Issue afkomstig uit feedback tijdens Demo Sprint 2.
Het huidige StUF-testplatform is zodanig opgebouwd dat wanneer een serie testen met goed gevolg doorlopen is, de software die tegen het testplatform getest is wordt voorzien van een label in de softwarecatalogus. Iets dergelijks moet er ook komen voor de nieuwe standaard.

``` Let op: Vooralsnog out-of-scope, valt niet binnen productvisie```

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Dit is overigens buiten scope voor huidige scrum team. Ik schat in dit dit een niet-triviale uitbreiding van scope behelst. Bovendien wil je dit zodanig generiek opzetten dat ook volgende standaarden op zelfde wijze getest kunnen worden. En je wilt zowel de software van API aanbieders als afnemers valideren - zodat inkopers in hun bestek kunnen opnemen dat een bepaalde validatie op de software een eis is.

**Comment by joeribekker** [comment]
> Dit is overigens buiten scope voor huidige scrum team. 

Awwww :-/

**Comment by ehotting** [comment]
Het is Open Source, Pull Requests zijn altijd welkom  ;)
