### ISSUE TITLE
Als afdeling wil ik de behandelaar van een zaak kunnen wijzigen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#276]
zodat de zaak in het ZRC de praktijk van de vakapplicatie correct weergeeft en deze informatie door andere afdelingen (bijvoorbeeld KCC) gebruikt kan worden.

Toelichting: deze userstory is gebaseerd op een een actuele vraag van gemeente Alkmaar wat het patroon (in de huidige StUF gebaseerde ZDS standaard) is om een behandelaar bij een reeds bestaande zaak te wijzigen. Dit kan bijvoorbeeld ook voorkomen wanneer nog geen behandelaar bekend is bij het aanmaken en de zaak in behandeling genomen wordt door een medewerker. De userstory is generiek maar kan bij bijvoorbeeld de melding wateroverlast of MOR ingevuld worden.

Hierbij hoort ook het uitwerken van de relatieklasse ROL, meer specifiek ZAKBTRBHL (Behandelaar) zoals beschreven in keuzenverStUFfing RGBZ 2.0 op pagina 8.

[keuzenVerStUFfing RGBZ2.0.pdf](https://github.com/VNG-Realisatie/gemma-zaken/files/2265670/keuzenVerStUFfing.RGBZ2.0.pdf)

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Dit moet inderdaad kunnen en ik verwacht dat het ook kan in de API. Als het al kan graag close @sergei-maertens

**Comment by sergei-maertens** [comment]
Kan volgens mij inderdaad al via `Rollen` en `Betrokkenen`, ik wil hem wel graag formeel opnemen in een sprint zodat ik hem nog even kan technisch aftikken dat het inderdaad voorzien is.

**Comment by TCIMEddy** [comment]
@sergei-maertens Deze is dan ready for sprint neem ik aan!

**Comment by TCIMEddy** [comment]
en heb alle vinkjes voor de vorm gezet

**Comment by TCIMEddy** [comment]
@sergei-maertens bedoel je met ‘technisch’ aftikken Review? Dan wat mij betreft in sprint 5 in review

**Comment by ArjanKloosterboer** [comment]
Waar is de RGBZ-mapping? Hoe kan zonder een mapping geverifieerd worden of al in de userstory wordt voorzien? @TCIMEddy ?

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Ik zet alle vinkjes weer uit

**Comment by TCIMEddy** [comment]
@TCIMEddy mapping maken

**Comment by Hugo-ter-Doest** [comment]
Dit kan al. Sluit hem af derhalve.
