### ISSUE TITLE
Als kerngroep CG willen we een  Referentie implementatie van een zaaksysteem in de app store

### ISSUE THREAD

**Issue by WouterBRu** [VNG-Realisatie/gemma-zaken#28]

**Comment by ehotting** [comment]
Referentie-implementatie komt online, niet in app-store.
App-store is een afhankelijkheid die vooralsnog niet is ingevuld.
Deze US is buiten scope voor huidig scrum team. Kan evt. worden opgepakt wanneer een beheerorganisatie wordt gevonden, de software zal wel beschikbaar komen - bijv. op GitHub Haarlem
