### ISSUE TITLE
Hoe borgen we dat het qua complexiteit niet explodeert?

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#281]
_op basis van een vraag gesteld tijdens demo sprint 2_

Hoe borgen we dat de complexiteit van op deze wijze standaardiseren niet explodeert? Blijft dit te managen? Welk proces hoort daar bij?

Hierop is een goed antwoord nodig.

**Comment by michielverhoef** [comment]
Een ander probleem wat ik zie is dat er niet goed vantevoren nagedacht is/wordt over de manier hoe een referentiecomponent zoals een ZRC hoort te werken.

Gaandeweg de userstories worden steeds meer gegevens toegevoegd aan het aanmaken van een zaak.  Misschien is het inderdaad nodig dat dit kan maar als je niet oppast hebben we straks een REST/JSON variant van het huidige creeerZaak StUF bericht waar bijna het hele RGBZ aan meegegeven kan worden. 
Dit kan nooit de bedoeling zijn.

We zouden een aantal leidende principes moeten formuleren hoe een ZRC behoort te werken. Bijvoorbeeld: 
* Het aanmaken van een zaak gebeurt met een minimale set gegevens: 
** zaakidentificatie (optioneel)
** zaaktype
** omschrijving
** initiator
** startdatum (optioneel, bij leeg de datum van het bericht)

* Het ZRC bepaalt aan de hand van zaaktype zelf attributen als verwachte einddatum, behandelaar etc.
* Andere gegevens worden in een update van de zaak gestuurd.

Dit is maar een voorbeeld maar dan is wel duidelijk wanneer er meer gegevens vanuit een userstory nodig blijken te zijn hoe deze dan in de ZRC (of een andere referentiecomponent, dit is maar een voorbeeld) terecht moeten komen. 

Dit soort spelregels zouden in de vorm van patronen uitgewerkt moeten worden waar de referentie implementatie zich dan ook aan moet houden.

**Comment by EdwinCoster** [comment]
Ik zie bovenstaande terugkomen in US #237. Ik twijfel even over waar ik welk commentaar moet plaatsen dus daar komt ie nog een keer...

Als we het patroon zoals Michiel dit nu beschrijft zouden toepassen. Zou ik eerst een een zaak moeten aanmaken met minimale gegevens, maar krijg ik (op basis van het zaaktype) dan wel gelijk een aantal dingen terug.

En vervolgens sla ik de overige gegevens van het inzageverzoek op met een update.

Ik vind het prima om het zo uit te werken, want het resultaat is hetzelfde, maar dan moeten we dat wel even afspreken.

En is dat dan een impediment?

**Comment by EdwinCoster** [comment]
Verder werd, in een vrij vroeg stadium, US #154 gerelateerd aan US #44, waarbij @ehotting aangaf dat het goed is om de user stories apart te houden, zodat ze "compromisloos" leiden tot verdieping van de API's. Als het goed is kan groot deel user story zonder extra effort worden ingevuld wanneer #44 opgeleverd is, maar als er een extra veld nodig blijkt dan is dat de gewenste verdieping zonder dat we de API onnodig op voorhand uitbreiden.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest ??

**Comment by Hugo-ter-Doest** [comment]
Hier lopen complexiteit van het proces en van de API's door elkaar. API's kunnen complex worden bijv. door grote hoeveelheid afhankelijkheden van andere API's of door grote aantal attributen (door Michiel benoemd). Het proces om tot de API's te komen kan daarnaast onbeheersbaar worden bijv. door onoverzichtelijke backlog of door tegenstrijdige user stories. Beide moeten we m.i. apart behandelen als risico's. Dus risico, kans, impact, maatregel uitwerken. @TCIMEddy kun jij twee impediments van die strekking maken?

**Comment by michielverhoef** [comment]
Ik heb dit ook al bij het api-beheer project genoemd maar misschien kunnen we voor het proces om tot de API's te komen ook eens kijken bij het proces document van W3C: https://www.w3.org/2018/Process-20180201/ ? Niet dat we alles over moeten nemen maar alles wat we niet zelf uit hoeven te vinden is mooi meegenomen..
