### ISSUE TITLE
Als developer wil ik eerst bouwen op basis van een user story, zodat we op basis van de praktijk een discussie kunnen voeren

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#285]
zodat we op basis van de praktijk een discussie kunnen voeren

Deze improvement story is uit de retrospective als improvement gekomen

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [x] In de volgende retrospective is er door de developers een verbetering ervaren

Dit betreft een improvement story waarbij we als team op ons gedrag moeten letten

**Comment by michielverhoef** [comment]
Volgens mij staat deze userstory haaks op #281 en wordt op deze manier nog steeds niet genoeg gekeken naar het maken van een standaard maar een applicatie gebouwd.

Want zoals ik de userstory lees is dit juist de werkwijze die nu gehanteerd wordt en mijns inziens is dat niet de goede om tot een goede standaard te komen.
