### ISSUE TITLE
Als team (en teamleden) werken wij verplicht op maandagmiddag op een nader te bepalen lokatie bij en met elkaar

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#286]
...zodat we 
- beter team worden
- beter en sneller discussies kunnen voeren en beslechten
- inzicht krijgen in elkaars kwaliteiten
- gebruik maken van elkaars kwaliteiten

Deze user story is voortgekomen uit de retrospective van sprint 2. Een aantal opmerkingen heb ik samengevoegd tot deze user story.

Verplicht op maandagmiddag centraal werken geldt in ieder geval voor:
- PO en SM
- Architect en informatie-specialist
- Developers 
- overige teamleden zijn van harte welkom maar niet verplicht iedere maandag maar graag wel een (aantal) keer.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Acceptatiecriteria**
- [ ] De verplichte deelnemers blokken maandagmiddag en werken op centrale lokatie
- [ ] Er is centrale lokatie

**Taken**
- [ ] Centrale lokatie regelen
- [ ] Verplichte deelnemers blokken agenda

**Comment by joeribekker** [comment]
Lijkt me goed! DoD mag er wel uit :)

Het moet alleen niet te veel reistijd kosten voor iedereen zo midden op de dag, dat is zonde. Zijn er al mogelijke locaties?

**Comment by michielverhoef** [comment]
Ik heb het gisteren al bij Eddy aangegeven: voor mij zit er een kleine maar aan het geheel, maandagmiddag en vrijdagmiddag (dit had ik al eerder doorgegeven aan Eddy) zijn mijn parttime middagen en ben ik thuis voor de kinderen. Op dit moment is een groot deel van de activiteiten (sport, muziek etc.) juist daarom precies dan geregeld dus als ik maandagmiddag moet werken moeten er wat dingen omgegooid worden. Dit moet ik kunnen regelen.

De maandelijkse aanwezigheid bij de sprintdemo's is nog te regelen maar dit is nog even iets wat passend gemaakt moet worden.

Overigens zou ik er zelf een sterke voorkeur voor hebben om dit 's ochtends te plannen. Mochten we dan uit lopen hebben we de middag nog. Bovendien is het qua reistijd efficiënter denk ik.

**Comment by TCIMEddy** [comment]
@michielverhoef begrijp je probleem maar tijdens de retrospective bleek dit de beste datum. Arjan en Jeffrey vanuit VNG kunnen in ieder geval

**Comment by TCIMEddy** [comment]
@joeribekker probeer centraal utrecht bij station

**Comment by michielverhoef** [comment]
@TCIMEddy : dat is makkelijk gezegd maar je wist 2 maanden geleden al dat maandagmiddag mijn vaste vrije middag is.  Om dan zo'n besluit te nemen terwijl ik er niet bij ben want met vakantie (wat ook ruim vantevoren bekend is) vind ik eerlijk gezegd nogal teleurstellend, om het zachtjes uit te drukken.

**Comment by TCIMEddy** [comment]
Ik ga het centraal werken proberen te verplaatsen van maandagmiddag naar maandagochtend
