### ISSUE TITLE
Als kerngroep CG willen we dat de cmis opschaalbaar is zonder afnamen van Alfresco Enterprise licenties.

### ISSUE THREAD

**Issue by WouterBRu** [VNG-Realisatie/gemma-zaken#29]

**Comment by ehotting** [comment]
Is dit niet een mooie user story om in te brengen als Utrecht?
En wie wil het dan? Niet de kerngroep CG denk ik. Er moet een rol in een gemeente zijn die dit wil. Inkoper? Architect? CIO?

**Comment by TCIMEddy** [comment]
Zeker mee eens. ~Deze User store beter verwoorden en ons scrumteam levert services onafhankelijk van voor en achterkant. Uiteraard moeten voor en achterkant wel voldoen aan standaarden

**Comment by ehotting** [comment]
@WouterBRu Bij nader inzien denk ik dat dit een issue is om te melden bij https://github.com/Alfresco of een implementatiepartner. Buiten scope voor dit team.
