### ISSUE TITLE
Besluitvorming systeem-systeem communicatie API's

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#294]
Hoeveel de componenten 'tegen elkaar' praten. Dit gaat om systeem-tegen-systeem communicatie die ook van de APIs gebruik maakt. We moeten bepalen of we dat willen, en zoja, hoe ver we daarin gaan
ik denk dat de betrokken mensen hiervoor zijn:
- Arjan
- Eelco
- Joeri
- Hugo
- Michiel
- ikzelf

Op verplichte maandag bespreken waarbij bovenstaande personen aanwezig kunnen zijn.

**Discussie moet leiden tot een document waarin besluitvorming staat en waarmee de developers verder kunnen.**

**Comment by michielverhoef** [comment]
Is dit iets waar @jgortmaker1 ook bij aan moet haken?

**Comment by michielverhoef** [comment]
Ik heb deze vraag volgens mij niet gesteld maar het is wel goed om hier over na te denken.

Zeker nu we bv besluiten in een apart component gaan onderbrengen. Delen van een zaak worden nu niet meer in de ZRC opgeslagen maar in de BRC en om een zaak op te vragen moeten onder water verschillende componenten bevraagd worden. Het lijkt me dat dit issue daar over gaat?

**Comment by TCIMEddy** [comment]
O sorry vergissing

**Comment by michielverhoef** [comment]
Geeft niet, het is absoluut een valide punt en er moet wel over nagedacht worden.

**Comment by jgortmaker1** [comment]
kan iemand kort uitleggen wat specifiek hier met systeem-tot-systeem communicatie via API's wordt bedoeld?
in principe worden API's altijd in een systeem-tot-systeem-context gebruikt....maar hier wordt vast iets specifiekers bedoeld..

**Comment by TCIMEddy** [comment]
Onduidelijk en waarschijnlijk geen impediment (meer)
