### ISSUE TITLE
Als medewerker vergunningen wil ik het vergunningsdocument dat bij de oorspronkelijke vergunningszaak hoort, kunnen toevoegen aan een toezichtzaak ...

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#297]
...zodat onze medewerkers in het veld inzicht hebben in de vergunning.

Rationale: documenten moet bij meerdere zaken kunnen horen. Vergelijkbare user stories kunnen worden bedacht voor andere toepassingen.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting dit lijkt me goede kandidaat om ready te maken

**Comment by ehotting** [comment]
Vraag aan @ArjanKloosterboer voor mijn begrip... Is deze user story correct geformuleerd? Waar ik met name over twijfel is over versies van documenten - ik vermoed dat je wanneer vanuit meerdere zaken gerelateerd wordt aan 1 document, er een probleem ontstaat wanneer in de ene zaak het document wordt bijgewerkt (nieuwe versie) en in de andere zaak dit juist niet mag. Record management. Linken zaken naar een document of naar een specifieke versie van dat document?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest dit kan toch gewoon vanuit de consumer? zo ja close

**Comment by Hugo-ter-Doest** [comment]
Je kunt hetzelfde document aan meerdere zaken koppelen. Het door Eelco benoemde probleem van versies van documenten is nog niet opgelost maar een ander probleem.
