### ISSUE TITLE
Als persoon of vertegenwoordiger van een persoon met een of meer zaken bij de/ een overheid  wil ik een overzicht van de zaken bij de/ een overheid waarbij ik betrokken ben (mijn zaken)

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#3]
Zodat ik geen enkele zaak over het hoofd zie

En mijn zaken kan raadplegen

En kan zien welke zaken lopen en welke zaken zijn afgesloten.

**Comment by TCIMEddy** [comment]
@ehotting Nog actueel?

**Comment by ehotting** [comment]
Aspect 'of vertegenwoordiger van' is out-of-scope.

De rest zou moeten kunnen, goed om dit te checken. Wel handig om dan een RGBZ mapping te maken van gewenste velden in de user interface van wat naar ik aan neem een MijnGemeente pagina is, alvorens deze naar Realisatie te brengen. Welke gemeente pakt dat op?

**Comment by sergei-maertens** [comment]
Zie ook #1

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest label verwijderen en work-around weergeven. Dank!!!

**Comment by joeribekker** [comment]
m.b.t. deze oplossing en https://github.com/VNG-Realisatie/gemma-zaken/issues/980#issuecomment-499385022 in het achterhoofd, kan je zoeken op BSN (bijvoorbeeld) aangezien deze in het ZRC zit.

**Comment by joeribekker** [comment]
m.b.t. deze oplossing en https://github.com/VNG-Realisatie/gemma-zaken/issues/980#issuecomment-499385022 in het achterhoofd, kan je zoeken op BSN (bijvoorbeeld) aangezien deze in het ZRC zit.

**Comment by joeribekker** [comment]
Duplicate van #1 vanuit onze scope gezien.
