### ISSUE TITLE
Als kerngroep CG willen we een overzicht over de componenten mbt zaakgericht werken vaststellen welke onderdelen door welk team worden gerealiseerd. (modulen vaststellen, prioriteren, toewijzen, …. )

### ISSUE THREAD

**Issue by WouterBRu** [VNG-Realisatie/gemma-zaken#30]

**Comment by TCIMEddy** [comment]
@ehotting Zinvol maar wat mij betreft op won't fix aangezien wij niet de kerngroep CG zijn

**Comment by ehotting** [comment]
Dit is afhankelijk van keuze al dan niet software te gaan hosten, beheerorganisatie etc. Buiten scope voor huidige scrum team / deze repo.
