### ISSUE TITLE
Als behandelaar wil ik kunnen vastleggen dat een inzageverzoek voldoet aan de voorwaarden vanuit wet- en regelgeving

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#301]
...zodat we alleen inzageverzoeken behandelen die aan die voorwaarden voldoen.

Dit betreft een statuswijziging van de zaak.

Architectuurschets (origineel): [Delft AVG](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md)
RGBZ Mapping: #312 

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van goedgekeurde veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan AVG

**Taken**
- [ ] Opstellen welke velden bij een melding horen [@EdwinCoster]
- [ ] Aanleveren testdata [@EdwinCoster]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Zaak.Zaakstatus: 'Toetsing wet- en regelgeving afgerond'

De voorwaarden zijn: 
- initiator is 16 jaar of ouder
- de initiator vraagt inzage van zijn/haar eigen gegevens

**Comment by EdwinCoster** [comment]
#51

**Comment by ArjanKloosterboer** [comment]
Ik heb de mapping gereviewd. De bal ligt nu bij Edwin (voor aanpassing van de mapping).

**Comment by ArjanKloosterboer** [comment]
Ik heb zojuist de mapping weer gereviewd. Ik ga er van uit dat je met de opmerkingen de juiste dingen doet en heb de mapping hierboven alvast goedgekeurd.

**Comment by EdwinCoster** [comment]
@Hugo-ter-Doest : volgens mij zit dit er al in.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest zo ja close :-)
