### ISSUE TITLE
Als behandelaar wil ik een inzageverzoek dat niet voldoet aan de voorwaarden afwijzen

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#302]
...zodat we alleen inzageverzoeken behandelen die aan die voorwaarden voldoen.

Architectuurschets (origineel): [Delft AVG](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md)
RGBZ Mapping: #402 

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan AVG

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Zaak.Zaakstatus: In behandeling genomen
Zaak.Einddatum gepland: +2 weken
Zaak.Uiterlijke einddatum afdoening: +2 weken (?)
Informatieobject: 'Verzoek aanvullende gegevens'

**Comment by sergei-maertens** [comment]
Voor besluiten: zie #362 
Voor afsluiten zaak: zie #351

**Comment by ArjanKloosterboer** [comment]
Ik heb de mapping gereviewd. Best complex voor de client met al die schrijf- en lees-API-acties. Voor de gebruiker (Kees) kan het desondanks heel eenvoudig zijn: zaak selecteren en client toont voorstel voor (eind)status, einddatum (actuele datum) en potentiele resultaten, obv geselecteerd resultaat worden potentiele besluittypen getoond (veelal één) en o.b.v. geselecteerd besluittype de potentiele informatieobjecttypen (veelal één), document uploaden of laten genereren en klaar is Kees. De client nog niet, die moet nog aan het rekenen voor archiefactietermijnen en zo en alles opslaan. Maar dat zal Kees een zorg zijn.

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Ben jij akkoord met de mappen of moet er nog iets aan gebeuren en zo ja wat?

**Comment by ArjanKloosterboer** [comment]
Zie mijn review van de mapping [alhier](https://github.com/VNG-Realisatie/gemma-zaken/issues/402#issuecomment-436786355). Moet dus nog wel het een en ander aan gebeuren.

**Comment by TCIMEddy** [comment]
@EdwinCoster wil je hier naar kijken, maar begrijp dat je je even in moet lezen

**Comment by EdwinCoster** [comment]
@TCIMEddy On it, we gaan de goede kant op.

**Comment by ArjanKloosterboer** [comment]
Ik heb zojuist de mapping weer gereviewd. Ik ga er van uit dat je met de opmerkingen de juiste dingen doet en heb de mapping hierboven alvast goedgekeurd.

**Comment by TCIMEddy** [comment]
Dit kan

**Comment by EdwinCoster** [comment]
> Dit kan

Als je alles voor archivering regelt wel.
