### ISSUE TITLE
Als behandelaar wil ik de aanvrager van een inzageverzoek om aanvullende informatie kunnen vragen 

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#303]
...zodat we bij een inzageverzoek alleen de gegevens ophalen en in de beschikking opnemen die gevraagd zijn.

En daarbij de doorlooptijd van het verzoek willen verlengen met (maximaal) de termijn die de initiator krijgt om de vraag te beantwoorden.

Architectuurschets (origineel): [Delft AVG](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md)
RGBZ Mapping: #435 

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Zaak.Zaakstatus: In behandeling genomen
Zaak.Einddatum gepland: +2 weken
Zaak.Uiterlijke einddatum afdoening: +2 weken (?)
Informatieobject: 'Verzoek aanvullende gegevens'

**Comment by jgortmaker1** [comment]
het verlengen van een geplande einddatum lijkt me niet tegen GEMMA. vinkje gezet.

RGBZ-mapping is voor @ArjanKloosterboer

**Comment by ehotting** [comment]
Dit leidt mogelijk tot uitbreiding van business logica in API, benieuwd naar uitwerking

**Comment by sergei-maertens** [comment]
`einddatumGepland` en `uiterlijkeEinddatumAfdoening` zij beide schrijfbaar, dus dit is mogelijk.
