### ISSUE TITLE
Als behandelaar wil ik de reactie op mijn verzoek voor aanvullende informatie kunnen registreren bij de zaak/het inzageverzoek

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#304]
...zodat we verder kunnen met de behandeling van het inzageverzoek.

Maar dat kan natuurlijk ook in de vorm van een notificatie.

Architectuurschets (origineel): [Delft AVG](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md)
RGBZ Mapping: #436  

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan AVG

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Informatieobject: 'Aanvullende gegevens'
Als de initiator binnen de termijn van 2 weken heeft gereageerd veranderen 'Zaak.Einddatum gepland' en wellicht ook 'Zaak.Uiterlijke einddatum afdoening' niet. Als het langer heeft geduurd zou ik denken dat deze weer verdaagd kunnen worden.

**Comment by jgortmaker1** [comment]
registreren bij het inzageverzoek of registreren bij de zaak? of beide?
en kunnen het ook meerdere informatieobjecten zijn? of een meervoudig informatieobject?

Maar dat is iets voor RGBZ-mapping. vanuit GEMMA geen bezwaar..

**Comment by EdwinCoster** [comment]
@jgortmaker1 schreef:

> registreren bij het inzageverzoek of registreren bij de zaak? of beide?

De zaak, titel aangepast.

> en kunnen het ook meerdere informatieobjecten zijn? of een meervoudig informatieobject?

Nee, het is een verduidelijking van de tekstvelden 'onderwerp' en/of 'reden'.

**Comment by ArjanKloosterboer** [comment]
> Als de initiator binnen de termijn van 2 weken heeft gereageerd veranderen 'Zaak.Einddatum gepland' en wellicht ook 'Zaak.Uiterlijke einddatum afdoening' niet. Als het langer heeft geduurd zou ik denken dat deze weer verdaagd kunnen worden. EC: Check wet- en regelgeving en JZ

Ik vermoed dat de zaak opgeschort moet worden gedurende het verzoek om aanvullende informatie. Na ontvangst van die informatie wordt de opschorting beeindigd en de zaak verlengd met de periode van opschorting. Wordt de informatie niet binnen de gestelde termijn ontvangen, dan wordt de zaak afgebroken (beeindigd). Ik vermoed dat het zo staat in het BW.

**Comment by EdwinCoster** [comment]
> Wordt de informatie niet binnen de gestelde termijn ontvangen, dan wordt de zaak afgebroken (beeindigd). Ik vermoed dat het zo staat in het BW.

Dat klopt. Ik heb het even tegen de behandelaar aangehouden en zij vertelde mij dat wanneer de aanvrager niet reageert het inzageverzoek 'buiten behandeling wordt gesteld' . Er wordt een brief gestuurd en de zaak wordt afgesloten.

**Comment by jgortmaker1** [comment]
AWB denk ik ipv BW...

**Comment by Hugo-ter-Doest** [comment]
Dubbel met #648

**Comment by EdwinCoster** [comment]
> Dubbel met #648

Niet waar.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Zie comment @EdwinCoster

**Comment by Hugo-ter-Doest** [comment]
@EdwinCoster kun je er wat meer over zeggen? Hebben we het ten onrechte als notificatie geïntepreteerd bijv.

**Comment by EdwinCoster** [comment]
Ik had deze toegevoegd omdat notificatie hier als optie werd gezien. Verder heb ik in deze user story in eerste instantie de huidige werkwijze verwoord. En dat kan in deze architectuur toch echt niet de bedoeling zijn. Het zal zeker zo zijn dat we een briefje/mailtje sturen en een briefje/mailtje terugkrijgen. Maar zelf ik zet in op een digitale dienstverlening. En dan krijgt de aanvrager een vraag (en wellicht een notificatie daarvan), voert de aanvrager iets in een formulier en krijgt de behandelaar daar een notificatie van.
Er zou eigenlijk een user story moeten zijn waarbij de behandelaar een notificatie krijgt van de handeling van een aanvrager (of een ander), ongeacht het kanaal wat gebruikt wordt.
