### ISSUE TITLE
Als behandelaar wil ik het onderzoek kunnen starten waarbij deskundigen controleren of een persoon is geregistreerd in hun systemen/administraties

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#305]
...zodat ik de benodigde informatie voor de beschikking van het inzageverzoek krijg.

Architectuurschets (origineel): [Delft AVG](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md)
RGBZ Mapping: #494

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigingen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan AVG

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Zaak.Zaakstatus: In behandeling genomen
Zaak.Uiterlijke datum afdoening: Persoonlijk vind ik dit het moment waarop je die daadwerkelijk kunt instellen. 
Informatieobject: 'Verzoek advies intern'

**Comment by jgortmaker1** [comment]
is er een informatiemodel voor de AVG-rechten? @ArjanKloosterboer ?

nog wel onduidelijkheid, daarom nog geen gemma-vinkje:
- hoe worden deskundigen benaderd? (arch bechrijving spreekt van e-mail)
- hier staat "inzage verzoek = zaak". In arch beschrijving stond inzageverzoek onder ORC
- wordt hier met ZAC VJV bedoeld?

**Comment by ehotting** [comment]
Prio M (voor nu) omdat ik verwacht dat dit meer een check is dan uitbreiding API

**Comment by EdwinCoster** [comment]
@jgortmaker1 schrijft:

> nog wel onduidelijkheid, daarom nog geen gemma-vinkje:
> - hoe worden deskundigen benaderd? (arch bechrijving spreekt van e-mail)

Deskundigen worden bij voorkeur benaderd via de ZAC. In onze huidige situatie is dat de mail met diverse privacy-implicaties die we er niet bij willen hebben.

> - hier staat "inzage verzoek = zaak". In arch beschrijving stond inzageverzoek onder ORC

De zaak is van het zaaktype 'persoonsgegevens inzien'. De specifieke gegevens zoals de domeinen (WMO, jeugd, participatie, schuld etc.) die onderzocht worden en de resultaattype daarvan zitten in de ORC onder 'AVG-rechten'. Eventuele bestanden komen in de DRC.

> - wordt hier met ZAC VJV bedoeld?

Idealiter wel.

**Comment by EdwinCoster** [comment]
@ehotting schreef:

> Prio M (voor nu) omdat ik verwacht dat dit meer een check is dan uitbreiding API

Ik denk dat ik het met je eens bent. Het is een statuswijziging, en een stap in het proces waarbij één of meer deskundigen/adviseurs een taak krijgen om gegevens aan te leveren (wat de ZAC/VJV regelt). Het daadwerkelijke aanleveren zit in US #306. 

Ik vind het daarmee een aardige testcase om te kijken welke plaats procesgegevens in de architectuur krijgen.

**Comment by ArjanKloosterboer** [comment]
> is er een informatiemodel voor de AVG-rechten?

Bij mijn weten niet. Ik mis sowieso een opsomming van de benodigde gegevens en de mapping daarvan op RGBZ en ImZTC. Dan wordt duidelijk wat de 'zaaktypespecieke' gegevens zijn. Ik kan dus geen vinkje zetten bij de RGBZ-mapping. 

> Dus we moeten het verband kunnen leggen tussen het Inzageverzoek (de ZAAK), het aandachtsgebied (b.v. AVG-rechten.WMO), de Deskundige (MEDEWERKER met de ROL Behandelaar) en de reactie (AVG-rechten.resultaattype en eventueel Informatieobject) van die Deskundige. Ik verwacht we dit in de ZAC regelen en dat dit in 'AVG-rechten' terechtkomt (AVG-rechten.BehandelaarWMO etc.).

Ik neem toch aan dat de van toepassing zijnde behandelaren wel in de ZRC terechtkomen (als betrokkene medewerkers in de generieke rol van Behandelaar bij de Zaak)? En wat moet ik me bij dat informatieobject voorstellen, wat staat daar zoal in?

**Comment by EdwinCoster** [comment]
@ArjanKloosterboer schreef:

> Ik mis sowieso een opsomming van de benodigde gegevens en de mapping daarvan op RGBZ en ImZTC. 

Yes, it takes time

> Dan wordt duidelijk wat de 'zaaktypespecieke' gegevens zijn. 

Leuke interpretatie van wat daar staat. Maar dat bedoelde ik niet.

> Ik neem toch aan dat de van toepassing zijnde behandelaren wel in de ZRC terechtkomen (als betrokkene medewerkers in de generieke rol van Behandelaar bij de Zaak)

Ja, in de generieke rol van Adviseur.

> En wat moet ik me bij dat informatieobject voorstellen, wat staat daar zoal in?

Zoals in US #306 staat: Een overzicht met verwerkingen of een afschrift van een dossier.

**Comment by ArjanKloosterboer** [comment]
Ik heb de mapping gereviewd. Zie mijn opmerkingen aldaar. Moet nog wat aan gebeuren.

**Comment by TCIMEddy** [comment]
Het enige wat er (in termen van ZTC, ZRC, DRC en BRC) in deze user story gebeurd is een statuswijziging.  Volgens mij kan dit?
