### ISSUE TITLE
Als deskundige wil ik mijn bevindingen/resultaten kunnen toevoegen aan het inzageverzoek

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#306]
...zodat deze gebruikt kunnen worden bij het opstellen van de beschikking.

Architectuurschets (origineel): [Delft AVG](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md)
RGBZ Mapping: #495 

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigingen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan AVG

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
AVG-rechten.resultaattype:
- Persoon komt niet voor
- Persoon komt voor met een overzicht van registraties
- Persoon komt voor met een afschrift van een dossier
- Persoon komt voor met een verzoek om een afspraak te maken om het dossier in te zien

Informatieobject: 'Advies intern' (bij een overzicht van registraties en een afschrift van een dossier)

Zodra alle deskundigen hebben gereageerd wijzigt Zaak.Zaakstatus in 'Advies ingewonnen'.

**Comment by sergei-maertens** [comment]
Is zijdelings ook gerelateerd aan #66

**Comment by ehotting** [comment]
Wat zijn de consequenties van deze user story uitgedrukt in RGBZ terminologie? Veldmapping? Ik wil iets meer beeld bij deze US alvorens te kunnen prioriteren.

**Comment by TCIMEddy** [comment]
volgens ons kan dit al In termen van ZTC, ZRC, DRC en BRC gebeurt hier het volgende:

* Registratie van een `Informatieobject` 'Rapportage/Onderzoeksstuk'
* Koppeling Informatieobject aan de Zaak (DRC.ObjectInformatieobject en ZRC.ZaakInformatieobject)

En zodra de AVGRC bestaat:

* Koppeling Informatieobject aan de Onderzoeksvraag (DRC.ObjectInformatieobject en AVGRC.OnderzoeksvraagInformatieobject).

In termen van de AVGRC:

* Registratie van Onderzoeksresultaattype en OnderzoeksresultaatToelichting;
