### ISSUE TITLE
Als behandelaar wil ik kunnen instellen dat alle deskundigen hebben gereageerd

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#308]
...zodat ik kan starten met het opstellen van de beschikking.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan AVG

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Zaak.Zaakstatus: 'Advies ingewonnen'.

Met het instellen van deze status kunnen deskundigen hun bijdrage niet meer bewerken.

Het zou natuurlijk veel mooier zijn dat zodra de alle deskundigen hebben gereageerd de Zaakstatus automatisch wijzigt in 'Advies ingewonnen' en de Behandelaar (van het Inzageverzoek) daar een Notificatie van krijgt.

**Comment by ehotting** [comment]
Ik vermoed dat beide aangedragen functionele oplossingen voor deze situatie zich in de business logica van de client moeten afspelen - en daarmee out-of-scope. Voor de API betekent het dat je moet kunnen ophalen wat status van de adviesaanvraag is - maar dat staat nogal ver af van de beschreven user story. Zie ik iets over het hoofd @sergei-maertens of kan deze out-of-scope ?

**Comment by EdwinCoster** [comment]
Jammer

**Comment by ehotting** [comment]
Idd, wat betekent dat je deze user story wel vorm kunt geven, zonder dat we de API behoeven aan te passen. Hoor het graag wanneer het in de praktijk anders blijkt. :)
