### ISSUE TITLE
Als behandelaar wil ik de beschikking kunnen versturen

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#310]
...zodat het inzageverzoek kan worden afgesloten.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigingen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan AVG

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Zaak.Zaakstatus: Afgehaneld
Informatieobject: 'Verstuurde persoonsgegevens'

Dat informatieobject kan het volgende bevatten:

- Resultaat de de persoon niet voorkomt (in een aandachstsgebied);
- Overzichten van registraties in applicaties/systemen;
- Afschriften van dossiers, en;
- Uitnodigingen om een dossier in te komen zien.

Vooralsnog ga ik ervan uit dat dit één informatieobject is (enkelvoudig dus).

**Comment by TCIMEddy** [comment]
@ehotting Deze kan wellicht ook naar kolom ‘make ready’. Indien jij hem versleept wil je dan aanvinken dat PO akkoord is.

**Comment by MarcoKlerks** [comment]
Graag aandacht voor het volgende:
- Beschikkingen moeten ondertekend worden. Vaak is degene die gemandateerd is om te tekenen (bijvoorbeeld een afdelingshoofd) niet dezelfde persoon als de steller. Wellicht moet dit nog een aparte user story worden?
- Hoe moet de beschikking verzonden worden? Print de behandelaar hem zelf uit? Wordt er gebruik gemaakt van een centrale print- en verzendfaciliteit? Wil de burger post via MijnOverheid ontvangen? En/of wordt er gebruik gemaakt van een gemeentelijke PIP?

**Comment by ehotting** [comment]
@MarcoKlerks
- Idd aparte user story
- Versturen is buiten scope, evt. een aparte API voor outputmanagement (best interessant)

**Comment by ehotting** [comment]
@EdwinCoster Tenzij ik het verkeer begrijp gaat het binnen de scope van de API om het toevoegen van een document aan een zaak en het afsluiten van de zaak - klopt dat?

**Comment by EdwinCoster** [comment]
@ehotting Ja, dat klopt

**Comment by ehotting** [comment]
Zou moeten werken dan. 

@MarcoKlerks Ondertekenen is qua "seperation of concern" taak van ander component in architectuur, ik verwacht dat een user story daarover 'out-of-scope' wordt maar wellicht zie ik het verkeerd.

**Comment by EdwinCoster** [comment]
@Hugo-ter-Doest : volgens mij kan dit al.

**Comment by TCIMEddy** [comment]
Zo ja uiteraard close :-)
