### ISSUE TITLE
RGBZ Mapping US 301

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#312]
Mapping van velden behorend bij user story #301 

We willen hier:
- (Actie 1) De actuele zaakstatus ('Geregistreerd') opvragen
- (Actie 3) een nieuwe actuele zaakstatus ('Toetsing wet en regelgeving afgerond') bij de zaak vastleggen, 
- (Actie 3) die status ook toevoegen aan Zaak.Statussen, 
- (Actie 3) de indicatie Laatst gezette status bij die nieuwe Zaak.Status instellen aanzetten, 
- (Actie 2) die indicatie weghalen bij de vorige actuele zaak.status ('Geregistreerd'), en 
- (Actie 3) de rol/betrokkene ('Behandelaar', '...de medewerker die behandelaar van inzageverzoeken is...') toevoegen aan die zaak.status zodat duidelijk is wie de status gezet heeft.

Maar als we afspreken dat we de 'indicatie laatst gezette status' weglaten (zie ook US #237), dan vervallen actie 1 en 2.

### Request
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `ZAAK.ZaakIdentificatie` | `zaakid` | UUID | Uniek volgnummer zaak |
| ` ` | ` ` | - | - |

### Answer
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Zaak.Status` | `Status` | STATUS | Huidige status: 'Geregistreerd' |
| ` ` | ` ` | - | - |

Eventueel kun je hier ook nog het volgnummer ophalen via `Status.Staustype.StatusypeVolgnummer`

### Request
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Status.Indicatie laatst gezette status` | ` ` | INDIC | FALSE |
| ` ` | ` ` | -   | - |

### Answer
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Zaak.status` | `Status` | AN200 | URL naar de huidige status: 'Geregistreerd' |
| ` ` | ` ` | - | - |

### Request ZTC (ophalen Zaaktypen)
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Catalogus.Domein` | ` ` | N5 | Een afkorting waarmee wordt aangegeven voor welk domein in een CATALOGUS ZAAKTYPEn zijn uitgewerkt. |
| `Catalogus.RSIN` | ` ` | N9 | Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON die de eigenaar is van een CATALOGUS. |
| `Zaaktype.ZaaktypeIdentificatie` | `ZaaktypeID` | UUID | Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt. |

Wat resulteert in een lijst met Statustypen.

### Answer ZTC
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Statustype. StatustypeVolgnummer` | `Volgnummer` | N4 | Een volgnummer voor statussen van het STATUSTYPE binnen een zaak. |
| `Statustype. Statustypeomschrijving` | `Status` | AN80 | Een korte, voor de initiator van de zaak relevante, omschrijving van de aard van de STATUS van zaken van een ZAAKTYPE. |
| ` ` | ` ` | - | - |

De rol die de status zet.

### Request ZRC
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Rol.Zaak` | `Zaak` | AN200 | URL naar de zaak |
| `Rol.Betrokkene` | ` ` | AN200 | URL naar de Betrokkene in de Rol van 'Behandelaar' |
| `Rol.BetrokkeneType` | ` ` | enumeratie | BetrokkeneType: 'Medewerker' |
| `Rol.RolOmschrijving` | ` ` | AN200 | Omschrijving van de aard van de ROL. _Waarde: 'Behandelaar'_ |
| `Rol.RolOmschrijving Generiek` | ` ` | rolOmschrijving generiek | Algemeen gehanteerde benaming van de aard van de ROL. _Waarde: 'Behandelaar'_ |
| ` ` | ` ` | - | - |

En het gezochte Statustype: '2' 'Toetsing wet- en regelgeving afgerond'
Deze toevoegen aan de zaak en actuele status maken.

### Request ZRC
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Status.datumStatusgezet` | `Datum status` | DATUM | De datum waarop de ZAAK de status heeft verkregen. |
| `Status.statusToelichting` | `Toelichting` | AN1000 | Een, voor de initiator van de zaak relevante, toelichting op de status van een zaak. |
| `Status.indicatieLaatstGezetteStatus` | ` ` | INDIC | Aanduiding of het de laatst bekende bereikte status betreft. _Waarde: True_. |
| `Status.Zaak` | `Zaak` | AN200 | URL naar de zaak |
| `Status.StatusType` | `Statustype` | AN200 | Aanduiding van de aard van de status. URL naar Statustype: 'Toetsing wet- en regelgeving afgerond'  |
| `Status.Rol` | `Rol` | AN200 | URL naar de Betrokkene die in een Rol de Status zet. |

### Answer
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Status` | `Status` | AN200 | URL naar de huidige status: 'Toetsing wet- en regelgeving afgerond' |
| `Status.Zaak` | `Zaak` | AN200 | URL naar de zaak |
| ` ` | ` ` | - | - |

Als we 'Indicatie laatst gezette status' weglaten, dan kan die uit de mapping.
Status.Rol komt op dit moment (20-09-2018) nu nog niet voor in de API specificatie.

**Comment by EdwinCoster** [comment]
@sergei-maertens, @joeribekker, @ArjanKloosterboer Willen jullie de Mapping reviewen en een uitspraak doen over de 'Indicatie laatst gezette status' en de mapping naar Rol.

**Comment by ArjanKloosterboer** [comment]
Mooie mapping, enkele opmerkingen. 
Aangezien je een nieuwe status wilt zetten, speelt die  'Indicatie laatst gezette status' een rol.
Aangezien je "de rol/betrokkene ('Behandelaar', '...de medewerker die behandelaar van inzageverzoeken is...') [wilt] toevoegen aan die zaak.status zodat duidelijk is wie de status gezet heeft" wil je een relatie van de soort 'ROL zet als betrokkene STATUS' leggen (opnemen in je mapping). Dat betekent onder meer dat je de Rol moet kennen waarnaar je die relatie wil leggen. Aangezien dit een relatieklasse is wordt deze geidentificeerd door de unieke aanduidingen van de zaak en de desbetreffende betrokkene. Ik zou dat vermelden als 'ROL. [unieke aanduiding ZAAK]' en 'ROL . [unieke aanduding BETROKKENE]'. Dat moet duidelijk genoeg zijn. 
Verder:
- 'ZAAK . Status' kom ik in het RGBZ niet tegen, wsl. bedoel je 'STATUS (van ZAAK) van STATUSTYPE . Statustype-omschrijving' oftewel de Statustype-omschrijving van het STATUSTYPE van de STATUS van de ZAAK. 
- STATUSTYPE  . Volgnummer heb je ook nodig om de eerstvolgende status te kunnen bepalen. 
- Ik zie in de userstory dat er voorwaarden zijn om te voldoen aan wet- en regelgeving: de initiator is 16 jaar of ouder en de initiator vraagt inzage van zijn/haar eigen gegevens. Dit zou je kunnen vastleggen als twee checklistitems in STATUSTYPE . Checklistitem in de ZTC-component.

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer @EdwinCoster overleg even over de definitieve oplossing zodat deze ready is

**Comment by joeribekker** [comment]
* `Zaak.status` is toegevoegd (alleen lezen) voor convenience omdat deze afgeleid kan worden uit de lijst van statussen. Hij zit niet in het IM maar dat is volgens mij geen probleem (ik vloek in de kerk).

* `Status.indicatieStatusLaatstGezet` is niet (meer) schrijfbaar maar wordt afgeleid uit de `Status.datumStatusGezet`.

`StatusType.volgnummer` zit verder al in het ZTC maar is wel nodig voor status volgorde te bepalen inderdaad.

**Comment by ArjanKloosterboer** [comment]
V.w.b. Zaak.Status, ik had al zo'n vermoeden. Vraag is hoe de mapping verwoord wordt: in RGBZ-termen of in API-termen. Er staat 'RGBZ-mapping' dus vandaar mijn opmerking. Prima om dat API-technisch op te lossen mbv Zaak.Status. Ik hoor dus geen vloek. Maar, desnondanks is 'STATUS (van ZAAK) van STATUSTYPE . Statustype-omschrijving' m.i. nodig, want je wilt het eerstvolgende statustype gebruiken en de waarde van die Omschrijving vastleggen in Zaak.Status.

**Comment by EdwinCoster** [comment]
Doorgevoerde aanpassingen:
- Statustype.StatustypeOmschrijving  toegevoegd
- Staustype.StatustypeVolgnummer  toegevoegd
- Rol  toegevoegd

IndicatieLaatsteStatusGezet heb ik laten staan.

**Comment by ArjanKloosterboer** [comment]
Nog een enkele opmerking.
Je het van ROL nu o.a. ROL.Rolomschrijving opgenomen met als toelichting 'URL naar de Rol van 'Behandelaar van inzageverzoeken'. Die snap ik niet, in ieder geval zit het in het RGBZ zo niet in elkaar. Het lijkt mij dat de aangehaalde tekst in dit geval de waarde van dit attribuut is. 
Ik mis ROL.Omschrijving_generiek met als waarde 'Behandelaar'.

**Comment by EdwinCoster** [comment]
Ja, dat was slecht gekopieerd en inmiddels hersteld. Ik heb de generieke omschrijving toegevoegd.

**Comment by TCIMEddy** [comment]
Bovenliggende user story is closed dus hiermee deze ook
