### ISSUE TITLE
Als teamlid wil ik graag weten waar alle projectbestanden, bv presentaties, scrum-plan etc staan, zodat ik ze kan terugvinden.

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/gemma-zaken#314]
achtergrond: Slack is vluchtig. Maar er staan data veel documenten die we zouden willen bewaren.

Dit geldt ook voor conclusies uit discussies etc.

Van Slack verdwijnt alles automatisch

**Comment by TCIMEddy** [comment]
@jgortmaker1 Bijna alle belangrijke beslissingen zijn gedocumenteerd te vinden op GitHub (met een beetje zoeken) Belangrijke zaken verdwijnen niet maar vindbaarheid is voor verbetering vatbaar

**Comment by TCIMEddy** [comment]
Google docs, Github en publieke site. Blijft punt van aandacht maar gaat stuk beter. Voor nu close ik deze!

**Comment by TCIMEddy** [comment]
Is wat mij betreft opgelost of Github of Google docs, waarna vertaling plaatsvindt naar GitHub. @sergei-maertens wellicht niet een keer uitleg over structuur in GitHub maar wat mij betreft geen prio
