### ISSUE TITLE
Als teamlid wil ik tijdens demo's de interactieve documentatie beter uitlichten...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#316]
...zodat het publiek meer vertrouwd geraakt met deze documentatie en beter kan vinden wat er waar staat.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] het publiek vraagt niet meer waar alles te vinden is

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] documentatie wordt gebruikt in demo presentaties

**Taken**
- [ ] Documentatie opschonen
- [ ] Zorgen dat alle github markdown docs in Hugo opgenomen zijn
- [ ] Bouwen presentaties/demo's op basis van gehoste documentatie

**Comment by ehotting** [comment]
Gaan we 4 oktober doen

**Comment by TCIMEddy** [comment]
@ehotting Niet gelukt dus wat mij betreft in de volgende demo? Wat mij betreft in kolom make ready en donderdag ready maken met hoge prioriteit

**Comment by TCIMEddy** [comment]
Tijdens demo sprint 5 heeft Joeri dit gedemonstreerd. Dus voor nu close
