### ISSUE TITLE
Als scrumteam zaakgericht werken wil ik dat de ontwikkelde services ook in productie draaien bij een gemeente

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#319]
zodat wij kunnen aantonen dat de nieuwe aanpak werkt

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
...

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
...

**Taken**
...

**Comment by TCIMEddy** [comment]
@BoerBas @ehotting @wishalg Het is uiteraard de bedoeling dat de API's gebruikt gaan worden door de betrokken gemeenten, maar @WouterBRu en @wishalg gaan hier voor MOR ook concreet mee aan de slag. Aan het einde van sprint 4 in onze retro op de agenda zetten voor evaluatie.

**Comment by TCIMEddy** [comment]
Amsterdam MOR proces gaat lopen en is aparte user story. Andere gemeenten die zaken in productie willen brengen graag aparte user story opnemen. Deze voor nu close
