### ISSUE TITLE
Als leverancier wil ik ook impliciet verondersteld gedrag van een referentiecomponent achter een API gedocumenteerd zien in een OAS-specificatie en/of bijbehorende functionele documentatie...

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/gemma-zaken#321]
...zodat ik zonder het reverse-engineeren van de referentieimplementatie weet wat ik moet implementeren

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [x] er is een OAS 3.0 specificatie
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [x] Voldoet aan RGBZ 2.0
- [x] Voldoet aan GEMMA 2.0

**Taken**
- [x] Leg impliciet gedrag vast in OAS 3.0 `description` velden
- [x] Documenteer impliciet validatiegedrag in `standaard.md`

**Comment by TCIMEddy** [comment]
Uit retrospective sprint 3. @sergei-maertens kun jij hier iets zinvols over zeggen. Wat zou er dan concreet gemaakt moeten worden?

**Comment by sergei-maertens** [comment]
@TCIMEddy goeie timing - hiervoor is een aanzet in #360 - [`standaard.md`](https://github.com/VNG-Realisatie/gemma-zaken/blob/feature/aanzet-standaard/standaard.md)

**Comment by TCIMEddy** [comment]
@sergei-maertens Ik zou kunnen zeggen dat dit 1 van mijn sterke punten is maar het is puur toeval dank voor je reactie en oplossing (start)

**Comment by sergei-maertens** [comment]
Volgens mij dus ook duplicate van #335

**Comment by TCIMEddy** [comment]
@sergei-maertens Mee eens wat mij betreft 1 van de 2 op voorhand sluiten (won't do) met opgaaf van reden en referentie naar

**Comment by jgortmaker1** [comment]
bedankt voor het mij wijzen op #360, maar ik lees weinig relaties met architectuur... 😕

**Comment by sergei-maertens** [comment]
Is soms voor mij ook niet helder of het nu wel of niet relevant is, dus dan neem ik maar het zekere voor het onzekere. Ga er beter op letten!
