### ISSUE TITLE
 als team(lid) wil ik de kwaliteitseisen waaraan een API spec moet worden beoordeeld helder hebben

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#323]
zodat ik de API specs beter kan beoordelen in relatie tot de architectuur, mapping op RGBZ en design keuzen.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
Uit retro3

**Comment by TCIMEddy** [comment]
@michielverhoef als er lijstje te maken is voegen we het toe aan acceptatiecriteria

**Comment by TCIMEddy** [comment]
@ehotting prio? en wenselijkheid?

**Comment by ehotting** [comment]
Ik heb hier geen concreet beeld bij...

**Comment by TCIMEddy** [comment]
@ehotting geen concreet beeld dan sluiten wat mij betreft of iemand moet nog toelichting geven.

**Comment by michielverhoef** [comment]
Waar is geen concreet beeld bij? De kwaliteitseisen waar een standaard aan moet voldoen of het feit dat we kwaliteitseisen stellen aan een standaard?

In ieder geval denk ik dat het de volgende keer kan helpen om, wanneer iemand concrete taken in een issue heeft (of er worden vragen aan gesteld) dit issue dan aan diegene toe te wijzen. Nu had ik het niet in beeld en blijkt er twee weken geleden iets aan mij gevraagd te zijn. Dat is jammer.

**Comment by TCIMEddy** [comment]
@michielverhoef ik zal er op letten

**Comment by ehotting** [comment]
@michielverhoef Welk type kwaliteitseisen hebben we het hier over? Kan je een concreet voorbeeld noemen (zonder het helemaal uit te werken)? Dat is idd de vraag

**Comment by michielverhoef** [comment]
Het hoeft niet heel spannend te zijn maar ik kan me voorstellen dat de definition of done voor een user story (zoals die nu in dit project gehanteerd wordt) niet voldoende is om de standaard in beheer te nemen.

Misschien is het een kwestie van een keer goed naar de DoD van het project kijken. Volgende week begint de aftrap van het traject om een beheerstraat in te richten voor deze en komende standaarden. Ik denk dat we als één van de resultaten helder moeten krijgen wat nodig is (qua inhoud van een standaard) om deze in beheer te kunnen nemen.

Ik zal in ieder geval nog eens overleggen met de collega's van VNG die ook standaarden beheren, wie weet valt er nog iets bij de StUF standaard te lenen.

**Comment by ehotting** [comment]
OK. Graag iets concreets. Alleen de (op zich valide) gedachte "maar er moeten toch kwaliteitseisen zijn" is niet voldoende, er moet een duidelijke behoefte aan te wijzen zijn. Een gedachtenoefening kan zijn "Als er geen kwaliteitseisen zijn, wat gaat er dan fout?" Dat leidt tot een paar concrete dingen die fout gaan, en daarbij horen dan concrete eisen waarmee je voorkomt dat die dingen fout gaan.

Ik zou eerder bij Kadaster gaan buurten voor inspiratie, omdat zij ook met API's werken.

**Comment by ehotting** [comment]
Ik stel voor dat dit verhuis naar repo api-beheer, en wanneer er eisen zijn, deze aan ZDS team worden medegedeeld. @TCIMEddy kan jij het daarheen verhuizen?

**Comment by TCIMEddy** [comment]
@ehotting regel ik

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest ik close deze. Staat duidelijk op baaklog beheer en is te breed
