### ISSUE TITLE
Als team wil ik meer verdieping/expert kennis in de API specificatie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#324]
...zodat de ZDS 2.0 standaard completer wordt.

**Achtergrond**

Aangedragen tijdens de retrospective van sprint 3. Er zijn grofweg 2 methoden om de REST API te realiseren. Op dit moment doen we dat op basis van User Stories aangedragen door gemeenten. Aan de andere kant kunnen we simpelweg RGBZ 2.0 ontsluiten als REST API (populair gezegd: omcatten).

Dit zijn 2 verschillende uitgangspunten die met elkaar conflicteren: VNG wil graag heel RGBZ ontsluiten, terwijl het project op basis van praktijk gebruik velden wil ontsluiten. Hier zal een vorm voor moeten worden gevonden.

Centrale vraag is, wat is het doel om op te leveren aan het eind van dit traject.

**Comment by TCIMEddy** [comment]
@ehotting Jij hebt hier vast ideeën bij!

**Comment by TCIMEddy** [comment]
@ehotting Gaat morgen denk ik aan de orde komen. Wellicht heb jij al visie of goed idee!?

**Comment by sergei-maertens** [comment]
#405 is beter uitgewerkt en een duplicate, laat ons daar verdergaan

**Comment by TCIMEddy** [comment]
Won’t do

**Comment by TCIMEddy** [comment]
Inderdaad dubbel dus close en wontfix
