### ISSUE TITLE
Rolomschrijving generiek weer toevoegen

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#326]
#296 

zie bovenstaande pull request closed naar mijn mening niet goed opgepakt

**Comment by sergei-maertens** [comment]
Per https://ref.tst.vng.cloud/introduction/bronnen/ is duidelijk dat we op basis van een erg out-of-date informatiemodel/attribuutsoorten aan het werk waren.

We zullen dit aanpassen.

**Comment by TCIMEddy** [comment]
@sergei-maertens Deze kan volgens mij gesloten worden maar ik weet niet meer precies wat het inhoudt...

**Comment by sergei-maertens** [comment]
Klopt, is inderdaad al opgenomen
