### ISSUE TITLE
Als teamlid wil ik dat we als team het proces van samenwerken beter gaan voeren ...

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#328]
… zodat we effectiever betere resultaten opleveren.

Komt voort uit de sprintreview dd. 27-8. In mijn beleving moet en kan er het een en ander verbeterd worden aan de wijze waarop we nu samenwerken en standaarden produceren. Bijvoorbeeld, het reviewen van een gerealiseerde userstory. Wie doen dat? Hoe zorgen we er voor dat dat de juiste mensen zijn? Wanneer hebben er genoeg mensen naar gekeken om 'm ready te kunnen verklaren? En wie doet dat, volgens welke spelregels? Of: het afronden van een discussie. Wanneer is 'ie afgelopen en wat is de uitkomst? Waar gaan de standaardenbouwers van uit, wat maken ze op uit die discussie? Of: welke functionele documentatie leveren we op om een gerealiseerde standaard te kunnen beoordelen? En wie schrijft die en waar is 'ie te vinden? 

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] de aangescherpte en toegevoegde procesafspraken zijn gedocumenteerd
- [ ] iedere projectmedewerker is op de hoogte van de aangescherpte en toegevoegde procesafspraken
- [ ] uit enkele praktijkvoorbeelden blijkt dat de aangescherpte en toegevoegde procesafspraken worden nageleefd

**Acceptatiecriteria**
- [ ] iedere projectmedewerker staat achter de aangescherpte en toegevoegde procesafspraken

**Taken**
- [ ] inventariseren van de aspecten waar de samenwerking en het productieproces verbetering behoeft
- [ ] analyseren op aan te scherpen en toe te voegen procesafspraken
- [ ] documenteren van de aangescherpte en toegevoegde procesafspraken
- [ ] communiceren van de aangescherpte en toegevoegde procesafspraken
- [ ] toetsen op het naleven van de aangescherpte en toegevoegde procesafspraken

**Comment by TCIMEddy** [comment]
Al is de improvement story nog te groot voor 1 sprint gaan we gewoon een start maken om dit voor elkaar te krijgen. @ehotting Kun jij vinkje zetten bij PO akkoord (indien akkoord uiteraard). Ik de user story op naam van @ArjanKloosterboer @ehotting en mijzelf gezet. Ik start met in beeld brengen van review proces

**Comment by ArjanKloosterboer** [comment]
Wat is er gebeurd dat deze nu in review staat? Is er ook maar één van de taken uitgevoerd?

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer dank correcte opmerking maar heb hem wel bewust hier geplaatst om tijdens retrospective 4 oktober te bespreken (als casus te bespreken hoe we dit kunnen voorkomen)

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Jij bent de enige die heeft gereageerd

**Comment by jgortmaker1** [comment]
hij is naast PO en SM ook de enige die geassigned is..

**Comment by TCIMEddy** [comment]
Op verschillende fronten worden deze discussies gevoerd. Wat mij betreft voldoende afgedekt in andere user stories. Daarom close ik deze.
