### ISSUE TITLE
Als teamlid wil ik dat we 'echte' toepassingen gaan koppelen via de ZDS 2.0

### ISSUE THREAD

**Issue by ppcjansen** [VNG-Realisatie/gemma-zaken#330]
...zodat we zichtbare resultaten kunnen tonen aan (potentiële) eindgebruikers.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting Dit is een improvement die komt uit de laatste retrospective. Ik ervan uit de jij ook deze improvement ondersteunt als PO.

**Comment by TCIMEddy** [comment]
In principe lopen er initiatieven in de betreffende gemeenten (en met name in Amsterdam). Tevens wordt er onder leiding van Wouter een nieuw initiatief gestart om een proces in de hele keten (5 lagen) te implementeren.
