### ISSUE TITLE
Als gebruiker van de standaard wil ik dat regels en eisen die niet in de OAS vastgelegd kunnen worden ergens anders beschreven staan

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#335]
...zodat de koppeling niet alleen technisch maar ook functioneel gevalideerd kan worden.

Note: bijvoorbeeld gebruik van een voor een bepaald zaaktype geldig statustype.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [x] er is een OAS 3.0 specificatie
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [x] Voldoet aan RGBZ 2.0
- [x] Voldoet aan GEMMA 2.0

**Taken**
- [x] Aanzet tot een document dat deze regels bevat (zie #360)

**Comment by TCIMEddy** [comment]
Uit retro3

**Comment by sergei-maertens** [comment]
Hiervoor is een aanzet in #360

**Comment by TCIMEddy** [comment]
Is dubbel en wordt opgepakt in #360
