### ISSUE TITLE
Als leverancier wil ik een api tool hebben om het koppelvlak te testen 

### ISSUE THREAD

**Issue by shazada** [VNG-Realisatie/gemma-zaken#336]
...zodat ik de koppelvlak kan testen. Zelf vanuit ervaring met Alfresco zou ik voorstellen om de API documentatie i.c.m. een test-tool te doen zoals bijv. Alfresco dat zelf doet: https://api-explorer.alfresco.com/api-explorer/.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
Wederom dank voor je bijdrage!

**Comment by ehotting** [comment]
Dit is interessant maar zou een grote uitbreiding van de nu afgesproken scope betekenen. Ik denk dat dit beter kan worden ingevoegd in scope van traject wat bezig gaat met API Test platform zodat het generiek voor alle API's kan worden opgezet.

@wishalg kan jij dat oppakken?

**Comment by wishalg** [comment]
Is onlangs opgepakt, er is door de huidige STP beheerder een advies uitgebracht. voor een API testvoorziening De stakeholders gaan zich hierover a.s. vrijdag buigen.

**Comment by ehotting** [comment]
Is wel een ander aspect van testen wat nu niet in die drie scenario's wordt afgedekt, maar zal kijken of we het vrijdag kunnen bespreken.

**Comment by TCIMEddy** [comment]
Wordt opgepakt in traject API-testplatform, dus close hier
