### ISSUE TITLE
Als teamlid wil ik dat de proces-documentatie ook gepubliceerd wordt

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#337]
...zodat ik alle documentatiecontent op 1 centrale plekkan lezen.

Het gaat hier concreet om de `docs/processen`, met een hoop afbeeldingen. Deze worden op dit moment niet meegenomen (er is geen Hugo configuratie). De Hugo configuratie moet meegenomen worden. 1 probleem is echter het embedden van afbeeldingen - voor Hugo moeten deze met absolute paden, maar dat betekent dat ze in Github niet langer zichtbaar zijn (het is het een of het ander). Dat kan het reviewen bemoeilijken.

Mogelijks kan het aanpassen van de markdown files gescript worden in de Docker image build stap om 'best-of-both-worlds' te hebben.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] de procesbeschrijvingen zijn leesbaar op https://ref.tst.vng.cloud/
- [ ] wijzigingen worden automatisch gepubliceerd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Afbeeldingen zijn zichtbaar op https://ref.tst.vng.cloud
- [ ] De procesbeschrijvingen zijn in het menu opgenomen
- [ ] De procesbeschrijvingen zijn vindbaar

**Taken**
- [ ] Hugo configuratie toevoegen
- [ ] Afbeeldingen correct linken/verplaatsen
- [ ] Onderzoek of het build-proces gescript kan worden

**Comment by sergei-maertens** [comment]
@joeribekker @ehotting wat mij betreft is deze ready genoeg :-)

**Comment by joeribekker** [comment]
Vinkjes gezet waar van toepassing voor mij. Of iedereen het begrijpt weet ik niet, maar denk het wel :)

Oplossingsrichting die @sergei-maertens noemt kan wellicht ook anders, door af te stappen van Hugo wat een convenience oplossing was destijds.

**Comment by TCIMEddy** [comment]
@sergei-maertens dit is toch al gerealiseerd?

**Comment by TCIMEddy** [comment]
@ehotting Zie commentaar Sergei en geef maar aan wanneer dit moet gebeuren

**Comment by Hugo-ter-Doest** [comment]
Ik zie de architectuurbeschrijving als instrument voor de analyse van de user stories van gemeenten. Zou ik niet opnemen in de documentatie van de de standaard.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prima besluit -> moeten we dit nog ergens in vastleggen?

**Comment by Hugo-ter-Doest** [comment]
Wat mij betreft is de discussie hierboven voldoende.
