### ISSUE TITLE
Procesbeschrijving Amsterdam is outdated/incorrect

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#338]
Via #315 kwam ik tot de vaststelling dat er best wel wat schort aan de procesbeschrijving van MOR Amsterdam.

Niet ingeschoten als userstory format, omdat ik dit meer als een defect beschouw wat opgepakt moet worden.

Volgens mij moeten Marcel & Jeffrey eens kritisch naar dat document kijken en bijwerken.

**Comment by Hugo-ter-Doest** [comment]
@MarcelMoerman Kun jij de procesbeschrijving van Amsterdam bijwerken?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest als het bijgewerkt wordt close en ook als het niet bijgewerkt is wat mij betreft ook close....

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest wil je hier nog iets mee doen. Zo niet close
