### ISSUE TITLE
Als gemeente wil ik in het ZTC per resultaattype een archiefactietermijn kunnen aangeven

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#344]
...zodat bij het afhandelen van een zaak de juiste vernietigingsdatum dan wel overbrengingsdatum berekend kan worden.

Bewaartermijnen moeten geconfigureerd kunnen worden conform de [VNG-selectielijst](https://vng.nl/onderwerpenindex/dienstverlening-en-informatiebeleid/archieven/publicaties/vastgestelde-selectielijst-2017). Mogelijk zijn hiervoor nog aanpassingen nodig in de RGBZ en/of het ImZTC.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
Dit is de eerste keer dat ik op GitHub een use case indien. Feedback is welkom!

**Comment by TCIMEddy** [comment]
@MarcoKlerks Dank! Ik heb de user story op naam van de product owner Eelco Hotting gezet. We houden je op de hoogte

**Comment by Hugo-ter-Doest** [comment]
Zie ook #549 voor procestype/procesobject/procestermijn.

**Comment by MarcoKlerks** [comment]
> Of je moet deze user story lezen als, ik wil resultaattypen definiëren...

Ja. Of nog scherper: bij het definiëren van resultaattypen wil ik ook de archiefactietermijn kunnen vastleggen.

Verwar overigens de archiefactie**termijn** niet met de archiefactie**datum**. Het een betreft een periode (bijv. 5 jaar), het andere een datum (bijv. 1-2-2025). Een datum kun je berekenen door een andere datum te nemen en daar een of meerdere termijnen / perioden bij op te tellen.

**Comment by EdwinCoster** [comment]
> bij het definiëren van resultaattypen wil ik ook de archiefactietermijn kunnen vastleggen

Ja dat is niet meer dan logisch. Mijn vraag is of er een specifieke user story nodig is voor dit attribuut, of dat je dat beter kunt bundelen zoals is gedaan in US #520 (uitlezen) en US #539 (vastleggen en wijzigen) en is uitgewerkt in #302.

Mijn opmerking over de `archiefactiedatum` doet hier eigenlijk niet ter zake, maar is wellicht iets voor een aparte user story.

**Comment by sergei-maertens** [comment]
voor dit doel is https://ref.tst.vng.cloud/referentielijsten/api/v1/resultaten toegevoegd. We hebben nu dus de mogelijkheid om de hele selectielijst via de API te ontsluiten.

**Comment by sergei-maertens** [comment]
Verdere stappen:

* resultaattype definieren
* relateren met resultaat uit selectielijst (+ bijhorende validaties)
* berekeningsmechanismen/selectielijstlogica inbouwen in ZTC zodat de consumer zo weinig mogelijk zelf moet berekenen

**Comment by sergei-maertens** [comment]
https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/29 ZTC implementatie gaat nu door Q&A
