### ISSUE TITLE
Als archiefbeheerder wil ik dat bij afhandeling van een zaak de vernietigings- of overbrengingsdatum wordt berekend

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#345]
...zodat te zijner tijd de vernietiging dan wel overbrenging geïnitieerd kan worden.

De zaak is (als het goed is) gekoppeld aan een zaaktype. Aan het zaaktype zijn (als het goed is) 1 of meer resultaattypen gekoppeld. Voor of bij het afsluiten van de zaak wordt (als het goed is) één van deze resultaattypen aan de zaak gekoppeld.

Op ieder resultaattype is (als het goed is) een bewaartermijn gedefinieerd (zie use case #344). Deze bewaartermijn en de afhandeldatum vormen de input voor het berekenen van de vernietigings- danwel overbrengingsdatum.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@MarcoKlerks Dank! Ik heb de user story op naam van de product owner Eelco Hotting gezet. We houden je op de hoogte

**Comment by ehotting** [comment]
@MarcoKlerks Klok-klepel: In welke gevallen is sprake van een procestermijn, waarbij de bewaartermijn pas kan worden berekend wanneer een bepaald zaakobject ten einde komt? Valt dat ook onder deze user story?

**Comment by MarcoKlerks** [comment]
@ehotting Ja, dat valt ook onder deze user story. In #344 heb ik aangegeven dat de bewaartermijnen vastgelegd moeten kunnen worden conform de VNG-selectielijst. Daarin staan ook - indien van toepassing - de procestermijnen waar je naar refereert. In deze user story geef ik aan dat de vastgelegde bewaartermijn gebruikt moet worden om de vernietigingsdatum dan wel overbrengingsdatum te berekenen.

Ik heb het een en ander niet verder in detail uitgewerkt. Het is bij het formuleren van een user story altijd even zoeken hoeveel detail je al gelijk gaat invullen. Wil je dat ik bij #344 of deze user story meer in detail treed?

**Comment by ehotting** [comment]
@MarcoKlerks  Vooral de procestermijnen, dus het afhankelijk maken van data in zaakobjecten, is een concept wat de developers goed moeten doorgronden alvorens te kunnen bouwen. Als je daar nog over zou willen uitweiden?

**Comment by MarcoKlerks** [comment]
Verdorie @ehotting, je maakt het me moeilijk! :-)

Ik ga enige tijd nodig hebben om dit zo helder op te schrijven, dat zelfs een developer het kan begrijpen. :-D

Work in progress...

**Comment by MarcoKlerks** [comment]
Wanneer een zaak (vanwege het resultaat) geclassificeerd is als "Vernietigen", dan moet er een 'vernietigingsdatum' berekend worden. De 'vernietigingsdatum' is de datum waarop de 'bewaartermijn' is afgelopen. De 'bewaartermijn' begint te lopen al;s de 'procestermijn' is afgelopen. 

Let op! De term 'procestermijn' heeft hier niets te maken met hoe lang de behandeling van een proces of zaak heeft geduurd dan wel had moeten duren! De term is dus een beetje ongelukkig gekozen, maar bij gebrek aan een betere term hanteer ik hem hier toch.

Voor het berekenen van de 'vernietigingsdatum' hebben we alleen de einddatum nodig van de 'procestermijn'. Als archiefbeheerder zou ik graag de volgende mogelijkheden hebben voor het definiëren dan wel berekenen van de einddatum van de 'procestermijn':
- "Nihil". De einddatum van de procestermijn is gelijk aan de afhandeldatum van de zaak.
- "Gelijk aan zaakeigenschap". De einddatum van de procestermijn is gelijk aan een [eigenschap](https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/objecttype/eigenschap) van de zaak. In het resultaattype moet duidelijk zijn wélke eigenschap. Dit kan bijvoorbeeld de einddatum van een voorziening zijn, het einde van de looptijd van een plan, de einddatum van de looptijd van een contract, etc.
- "Gelijk aan de vervaldatum van het besluit". De einddatum van de procestermijn is gelijk aan de vervaldatum van het besluit. Deze komt met name vaak voor bij vergunningen en ontheffingen.
- "Gelijk aan een attribuut van het zaakobject". De einddatum van de procestermijn is gelijk aan een attribuut van het gekoppelde zaakobject. Het kan daarbij gaan ook gaan om een gekoppeld rechtspersoon (cliënt). Het kan zowel gaan om de startdatum (bouw, geboorte, etc.) als de einddatum (sloop, overlijden, etc.). De datum kan in de toekomst, maar ook in het verleden liggen! (Aandachtspunt: wat als er meerdere zaakobjecten zijn?)

In deze user story vraag ik om het berekenen van de vernietigingsdatum (of overbrengingsdatum) bij het afhandelen van de zaak. In veel gevallen is dat echter nog niet mogelijk. Bij de afhandeling van de zaak is het mogelijk nog niet duidelijk wanneer een besluit vervalt of een zaakobject overlijdt of gesloopt wordt. Wanneer de vernietigingsdatum niet berekend kan worden, omdat de einddatum van de 'procestermijn' nog niet bekend is, dan moet de vernietigingsdatum leeg blijven. Ik zal een aparte user story opstellen over hoe we hiermee om willen gaan.

@ehotting Was dit het verhaal wat je zocht?

**Comment by EdwinCoster** [comment]
Zie ook: [dit verhaal](https://www.gemmaonline.nl/images/gemmaonline/6/62/ImZTC_RGBZ_Wijzigingsvoorstel_Selectielijst_20170921.pdf)

**Comment by Hugo-ter-Doest** [comment]
Ik zet deze op prio ZH, omdat dit het basismechanisme is voor het bepalen van de bewaartermijn van zaken.

**Comment by Hugo-ter-Doest** [comment]
Dit kan alleen bij een bekende einddatum procestermijn.

Bij afsluiten zaak: als einddatum procestermijn bekend is, dan wordt de archiefactietermijn berekend.

Bijv.: aanstelling medewerker met tijdelijk contract. Als deze 5 februari uit dienst gaat, dan is dat de brondatum voor de archiefactietermijn 5 februari. Vanaf die datum wordt de archiefactietermijn gerekend.

**Comment by joeribekker** [comment]
Ik heb het nu geïmplementeerd dat bij het zetten/wijzigen van het RESULTAAT op de ZAAK, de `Zaak.archiefactiedatum` wordt berekend.

Immers, bij het zetten van een RESULTAAT, is het RESULTAATTYPE bekend, waar de nodige informatie in staat.

@Hugo-ter-Doest Graag controle, want jij had het over:

> Bij afsluiten zaak: als einddatum procestermijn bekend is, dan wordt de archiefactietermijn berekend.

**Comment by Hugo-ter-Doest** [comment]
Indien mogelijk wordt dan de archiefactiedatum berekend. "Indien mogelijk", omdat als de procestermijn nog niet bekend is, kun je de archiefactiedatum niet berekenen. Wel is het zo dat met het zetten van het resultaattype de afleidingswijze voor de brondatum bekend is.

**Comment by joeribekker** [comment]
Correct.

* Afleidingswijze `vervaldatum_besluit` en `ingangsdatum_besluit` zijn **niet** geïmplementeerd, zie: #775
* Afleidingswijze `gerelateerde_zaak` is **niet** geïmplementeerd, zie: #776

Verder gereed.
