### ISSUE TITLE
Als archiefbeheerder wil ik de vernietigings- dan wel overbrengingsdatum van een zaak kunnen aanpassen

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#346]
...zodat:
- Een zaak later wordt vernietigd, of
- Een zaak niet wordt vernietigd, maar later zal worden overgebracht, of
- Een zaak eerder wordt overgebracht.

Als het goed is, wordt de vernietigings- dan wel overbrengingsdatum automatisch berekend (zie issue #345). Er kunnen echter redenen zijn om hiervan af te wijken.

Een zaak heeft na afhandeling altijd een vernietigingsdatum óf een overbrengingsdatum. Hij kan niet beide hebben. Ze mogen ook niet allebei leeg zijn.

Het zou fijn zijn als er ook een indicatie en/of toelichting meegegeven kan worden dat en waarom er afgeweken is van de automatisch berekende datum.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@MarcoKlerks Dank! Ik heb de user story op naam van de product owner Eelco Hotting gezet. We houden je op de hoogte

**Comment by joeribekker** [comment]
Dit gaat dus om hetzelfde veld `archiefactiedatum` maar vernietiging/bewaren hangt af van `archiefnominatie` waarde

**Comment by Hugo-ter-Doest** [comment]
Er ka een toelichting worden gegeven bij het aanpassen. Dit komt in de event log /audit trail.

**Comment by sergei-maertens** [comment]
=> self-reminder: manueel invullen blokkeren als deze niet automatisch berekend kan worden (gebeurt niet in praktijd door eindgebruikers, maar zo voorkomen we ongelukjes)

**Comment by sergei-maertens** [comment]
* resultaat toegekend -> datum berekend
* handmatige override -> datum gezet
* ander resultaat (van ander type) toegekend -> datum berekend, overschrijft _opnieuw_ de handmatige datum

**Comment by hdksi** [comment]
Let op dat niet alleen de `archiefactiedatum` maar mogelijk ook de `archiefnominatie` moet worden aangepast om het bedoelde effect te sorteren. Bijvoorbeeld: document dat op de nominatie stond voor vernietiging over 5 jaar moet i.v.m. hotspot nu permanent bewaard worden. Of de `archiefactiedatum` in dit geval gewijzigd moet worden is niet zeker, maar `archiefnominatie` wijzigt in ieder geval.

Verder: kan het beoogde effect altijd gerealiseerd worden door wijziging van (een combinatie van) de twee bovenstaande attributen? Volgens mij wel, maar wellicht goed om daar nog even goed over na te denken.

**Comment by CMasselink** [comment]
Een stuk van dit gedrag is ook al beschreven in pull request nummer #815 
Belangrijk: in de comments van #815 staan een aantal zaken waarvan ik me afvraag of ze daadwerlijke gerealiseerd zijn (zoals toelicting kunnen geven bij overrulen van vernietigingstermijn/archiefactiedatum).
Is alles wat bij #815 staat wel gerealiseerd?

**Comment by joeribekker** [comment]
Uit refinement sessie: Controleer of dit er allemaal in zit, maar volgens mij zit het er in.

**Comment by sergei-maertens** [comment]
Wordt ingevuld via de `X-Audit-Toelichting` header

**Comment by sergei-maertens** [comment]
via @CMasselink gehoord dat het veld "raadzaam" is, dus we laten het veld optioneel
