### ISSUE TITLE
Als archiefbeheerder wil ik alle zaken met een bepaalde overbrengingsdatum of ouder opvragen

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#348]
...zodat ik een concept-overbrengingslijst kan opstellen. Deze lijst controleer ik samen met de proces-eigenaren en de archivaris. Zijn er zaken die we (nog) niet willen overbrengen naar het e-depot? Zo ja, dan pas ik daar de vernietigings- en/of overbrengingsdatum aan (zie use case #346).

Nadat er diverse wijzigingen zijn doorgevoerd, wil ik waarschijnlijk weer een nieuwe concept-overbrengingslijst gaan opstellen..

Zie ook use case #347.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@MarcoKlerks Dank! Ik heb de user story op naam van de product owner Eelco Hotting gezet. We houden je op de hoogte

**Comment by Hugo-ter-Doest** [comment]
Overbrengingsdatum = brondatum + archiefactietermijn.

**Comment by joeribekker** [comment]
vernietingslijst: archiefnominatie = vernietigen + archiefactiedatum < [datum]
overbrengingslijst: archiefnominatie = bewaren + archiefactiedatum < [datum]

**Comment by joeribekker** [comment]
Technische realisatie:

`/api/v1/zaken/?archiefnominatie=blijvend_bewaren&archiefactiedatum__lt=<now>`

**Comment by joeribekker** [comment]
Dit filter is geimplementeerd:

* archiefnominatie
* archiefactiedatum
* archiefactiedatum__lt
* archiefactiedatum__gt
* archiestatus

**Comment by Hugo-ter-Doest** [comment]
Lijkt me goed.
