### ISSUE TITLE
Als archiefbeheerder wil ik een lijst aan zaken kunnen vernietigen

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#349]
...zodat de gegevens van de zaak gewist worden. Daarbij inbegrepen zijn ook alle aan de zaak gerelateerde informatieobjecten, tenzij deze ook gerelateerd zijn aan andere zaken die langer bewaard moeten worden. De vernietiging van de zaak wordt bevestigd (output), zodat er een verslag (definitieve vernietigingslijst) opgesteld kan worden van de uitgevoerde vernietiging.

De lijst aan te vernietigen zaken die als input geldt, is waarschijnlijk eerder opgevraagd als concept-vernietigingslijst (zie use case #347).

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@MarcoKlerks Dank! Ik heb de user story op naam van de product owner Eelco Hotting gezet. We houden je op de hoogte

**Comment by Hugo-ter-Doest** [comment]
Er wordt meestal met een lijst toestemming voor vernietiging gevraagd. Er kunnen zaken tussenuit worden gehaald. Handig als je de lijst zaken kunt markeren voor vernietiging zodat je later niet de lijst met URI's hoeft op te zoeken.
Precieze oplossing bespreken we 28-1.

**Comment by Hugo-ter-Doest** [comment]
Prio ZH, omdat het een basismechanisme is voor archivering.

**Comment by Hugo-ter-Doest** [comment]
Bij vernietigen wordt een lijst opgesteld met de te vernietigen zaken. Deze wordt ter goedkeuring voorgelegd aan zaakeigenaren en archivaris. Zaken kunnen eruit worden gehaald bijv. vanwege historische waarde. Daarna vindt daadwerkelijke vernietiging plaats.

Er vindt bij vernietiging van iedere zaak een validatie plaats op de vernietigingsdatum.

**Comment by hdksi** [comment]
> 
> 
> Technisch willen we een indicatie op het document zoals bijv. "aantal zaken die er aan hangen", als dit 1 is, verwijder je het document zelf, als het 2 of meer is, dan alleen de relatie.

Notitie: een document kan theoretisch gezien ook gekoppeld zijn aan iets anders dan een zaak. De teller reflecteert dat niet. Kan evt. leiden tot ongewenste verwijderen?

**Comment by joeribekker** [comment]
> Notitie: een document kan theoretisch gezien ook gekoppeld zijn aan iets anders dan een zaak. De teller reflecteert dat niet. Kan evt. leiden tot ongewenste verwijdering/vernietiging?

Goed opgemerkt. Weet niet zeker of we dit kunnen tackelen.

Voorlopige scope:

* Autorisatie voor DELETE toevoegen
* DELETE toevoegen aan Zaak-dossier resources
* Geen validatie op deze DELETE (anders dan de autorisatie)

**Comment by joeribekker** [comment]
Geïmplementeerd middels DELETE op de hoofd-elementen van elke API. Voor elke API heb je een eigen scope nodig.

* `DELETE /api/v1/zaken/<uuid>` (scope: `zds.scopes.zaken.verwijderen`)
* `DELETE /api/v1/besluiten/<uuid>` (scope: `scopes.besluiten.verwijderen`)
* `DELETE /api/v1/documenten/<uuid>` (scope: `scopes.documenten.verwijderen`)
