### ISSUE TITLE
Als archiefbeheerder wil ik geïnformeerd worden wanneer er een backup terug geplaatst is

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#350]
...zodat ik weet dat mijn recente beheer-acties zijn teruggedraaid en ik deze dus opnieuw moet uitvoeren.

Bijvoorbeeld, doordat een back-up terug geplaatst is, is de vernietiging van zaken teruggedraaid (zie use case #349). Ik zal deze zaken dan opnieuw moeten vernietigen.

Strikt genomen zouden bij archiefvernietiging ook de zaken uit alle back-ups verwijderd moeten worden. Dit is in de praktijk vaak onhaalbaar. Door procedureel af te spreken dat na terugplaatsing van een back-up de archiefvernietiging nagenoeg onmiddellijk opnieuw wordt uitgevoerd, kunnen de archiefwettelijke consequenties beperkt blijven.

Overigens is deze behoefte niet alleen relevant voor archiefvernietiging, maar ook voor andere handelingen i.h.k.v. informatie- en archiefbeheer.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Heb hier enige tijd over na zitten denken. Deze functionele wens valt op meerdere manieren technisch vorm te geven, maar deze zijn allemaal meer complex dan een goede afspraak maken met degene die backups terugzet (mag hopen dat dat een uitzonderingssituatie is). 

Hoewel functioneel een valide wens zie ik geen impact op de API, vandaar `wontfix`
