### ISSUE TITLE
Als architect wil ik een heldere architectuuruitwerking voor de straatartiest

### ISSUE THREAD

**Issue by jeffreygortmaker1** [VNG-Realisatie/gemma-zaken#352]
...zodat ik kan zien of deze in GEMMA en Common Ground past.

**Comment by Hugo-ter-Doest** [comment]
@BoerBas is dit nog actueel of kan ik hem sluiten?

**Comment by Hugo-ter-Doest** [comment]
@BoerBas Graag een uitwerking van de architectuur maken.

**Comment by TCIMEddy** [comment]
Loopt al te lang
