### ISSUE TITLE
Naamgeving wijzigen van ZDS2.0 naar Zaakgerichte Standaarden

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#357]
- De naam ZDS20 geeft (soms) verwarring
- dekt niet altijd de lading
- onduidelijk voor stakeholders
- etc

Dit is een belangrijke wens van de business owner @TheoVNGPeters 

@ehotting Wil jij als PO hierover een beslissing nemen en (laten) doorvoeren

**Comment by ehotting** [comment]
Het project is nu reeds bekend onder deze naam. Qua communicatie is het onwenselijk nu te wijzigen. Wanneer wij de standaarden opleveren zullen we dat niet onder de naam ZDS 2.0 doen - het gaat dan om de naam van elke API en een overkoepelende naam voor alle API's. Komen we nog op terug. Voor nu moet ons project ZDS 2.0 blijven heten, anders wordt het nog veel lastiger er over te communiceren.
