### ISSUE TITLE
Als gemeente wil ik dat de api's afgeschermd zijn middels authenticatie

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#361]
zodat enkel bevoegden toegang hebben tot de api.

Dit gaat om het technisch al dan niet toegankelijk maken voor bepaalde partijen op basis van identiteit. Autorisatie wordt verder uitgewerkt in een andere user story.

Let op: Dit heeft bredere werking, met impact voor alle API standaarden. Beschouw NLX.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of gedocumenteerd van afgeweken

**Acceptatiecriteria**
- [ ] Voldoet aan GEMMA 2.0
- [ ] Compliant met EIDAS verordening

**Taken**
- [ ] Onderzoek [_verantwoordelijke_]
- [ ] Deelname FieldLab DSO 30/31 oktober. [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting Kun jij aangeven wat jouw wensen zijn t.a.v. autorisatie en of jij akkoord bent met de user story (vinkje :-)

**Comment by TCIMEddy** [comment]
@joeribekker @sergei-maertens Kunnen jullie aangeven wat jullie voor deze user story nodig hebben (architectuur, informatiemodellen, specificaties etc)

**Comment by sergei-maertens** [comment]
Technisch moeten we even kijken hoe we 't aanpakken, al denk ik dat het waarschijnlijk OAUTH2 wordt (ook conform DSO richtlijnen).

RGBZ en GEMMA zijn hier volgens mij niet van toepassing, wat we wel moeten bedenken is hoe we scopes gaan definieren, maar dat hoeft niet als onderdeel van 'ready maken' te gebeuren.

**Comment by TCIMEddy** [comment]
@ehotting Is dit de user story die jullie aan het uitwerken zijn?

**Comment by ehotting** [comment]
Ja, vandaag zoals voorgenomen deze "gespliced" en user stories #424, #425, #426, #427 en #428 gemaakt, ready for sprint. Deze is daarmee "dubbel" en kan gesloten.
