### ISSUE TITLE
Datamodel: informatieobjecten versus documenten

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#368]
Bij de bijeenkomst op 27 augustus werd o.a. het datamodel (repositories) op hoofdlijnen gepresenteerd. Er ontstond enige verwarring en hilariteit over de termen "informatieobject" en "document". Blijkbaar heerst er de aanname dat documenten niet "document" genoemd mogen worden van archivarissen e.d., maar "informatieobject". Deze jargon-discussie is destijds gevoerd bij het opstellen van de [Baseline Informatiehuishouding Gemeenten](https://vng.nl/onderwerpenindex/dienstverlening-en-informatiebeleid/archieven/publicaties/baseline-informatiehuishouding-gemeenten). Ik was daar destijds bij en blijkbaar heeft dit later tot verwarring geleid. Ik hoop dit hier enigszins te kunnen verhelderen.

Om te beginnen, een document is een document. Er zijn twee soorten documenten: analoog en digitaal. Een analoog document bestaat uit één of meerdere velletjes papier (of perkament of whatever) met daarop teksten en beelden. Een digitaal document is een enkel bestand c.q. file waarin teksten en beelden zijn opgenomen. Voorbeelden zijn Word-bestanden, PDF-bestanden, Excel-bestanden,  MP3-bestanden, e-mails, etc.

Een informatieobject is een informatieobject. Een informatieobject is een eenheid aan informatie. Dat kan een document zijn. Maar dat kan ook een regel in een database zijn!  Een zaakregistratie is dus ook een informatieobject. De statusregistratie die daaraan gekoppeld is, is ook een informatieobject.

Het is dus onzinnig om in je database een apart tabelletje op te nemen dat je "informatieobjecten" noemt, waarbij je suggereert dat wat in de andere tabellen staat geen informatieobjecten zouden zijn. Dat zijn het wel! Noem je tabelletje waarin je alle Word- en PDF-bestanden e.d. opslaat gewoon "documenten", want dat zijn het.

Kortom, in de database staan:
- Informatieobjecttypen, bijvoorbeeld: ZAAK, STATUS, DOCUMENT, RECHTSPERSOON, ZAAKTYPE, DOCUMENTTYPE.
- Informatieobjecten, bijvoorbeeld: de registratie van zaak 12345, de registratie van het natuurlijk rechtspersoon met BSN 22222220, het zaaktype 'Het behandelen van een WMO-aanvraag', het document 'ontvangstbevestiging_12345.doc'.

De Archiefwet is van toepassing op alle informatieobjecten en niet alleen op de objecten van het type DOCUMENT. Dat is waarom we in de Baseline de term "document" hebben willen vermijden.

**Comment by ArjanKloosterboer** [comment]
In het RGBZ is INFORMATIEOBJECT gedefinieerd als "Geheel van gegevens met een eigen identiteit ongeacht zijn vorm, met de bijbehorende metadata ontvangen of opgemaakt door een natuurlijke en/of rechtspersoon bij de uitvoering van taken". Dit strookt met de insteek hierboven van @MarcoKlerks. De toelichting licht dit toe: "Een informatieobject is een generiekere term voor het veelgebruikte begrip document dat beperkter van reikwijdte is. Een informatieobject kan van alles zijn, ongeacht aard en vorm: een tekstverwerkingsdocument, een papieren brief, een webpagina, een landkaart, een foto, een geluidsopname, een dataset, een blog, etcetera. En ook een digitaal ontvangen of gecreeerd  informatieobject dat bestaat uit meerdere fysieke informatieobjecten, zoals een aanvraag (als tekstdocument) met bijbehorende tekening (CAD-formaat) en berekening (spreadsheet) of een email met bijlage(n). "
Inderdaad, de informatie over een individuele zaak kan ook als informatieobject beschouwd worden. I.t.t. Marco acht ik het wel zinnig om informatieobjecten in het RGBZ te modelleren om daarmee uit te drukken dat  alle sets aan informatie die niet in het RGBZ gespecificeerd zijn ook aan een zaak gerelateerd kunnen worden. In lijn met de genoemde Baseline Informatiehuishouding. 
Dus, @sergei-maertens, geen implicaties voor het RGBZ.
Wat mij betreft kan dit issue afgesloten worden, @TCIMEddy.

**Comment by sergei-maertens** [comment]
Dank voor deze toelichting op de toelichting! :+1:

**Comment by MarcoKlerks** [comment]
Ah, dus INFORMATIEOBJECT is dus de vergaarbak voor documenten en andere informatieobjecttypen waarvoor (nog) geen apart informatieobjecttype is ingericht. Bij andere informatieobjecttypen zal het daarbij gaan om gestructureerde informatie (data), die dermate specifiek is voor een bepaald proces dat het niet zinvol is om deze apart te modelleren, maar die je wel wil bewaren. Denk aan gegevens over wipkippen, procesgegevens, check/vinklijstjes, etc.

Ik wil dan toch pleiten voor een apart informatieobjecttype DOCUMENT, omdat ik mij heel goed kan voorstellen dat er een functionele behoefte bestaat om deze afzonderlijk op te halen en te presenteren. Documenten worden namelijk doorgaans niet alleen gebruikt om informatie in vast te leggen als ook om deze te communiceren. Bij de behandeling of reconstructie van een zaak is het niet zo zeer van belang welke informatie er bestaat als wel welke informatie met wie op welk moment is gecommuniceerd. Dat bepaalt de rechten en plichten, en verantwoordelijkheid en aansprakelijkheid van de betrokken rechtspersonen.

Daarnaast kan ik mij heel goed voorstellen dat je ten behoeve van het verduurzamen van de documenten andere metadata nodig hebt dan bij de gestructureerde, overige informatieobjecten.

Mijn voorstel is dus om INFORMATIEOBJECT te splitsen in DOCUMENT en OVERIG_INFORMATIEOBJECT.

**Comment by joeribekker** [comment]
> Ik wil dan toch pleiten voor een apart informatieobjecttype DOCUMENT

Dat is er, maar wellicht niet hoe jij het ziet. Er bestaat INFORMATIEOBJECTTYPE (lijstje van typen) en INFORMATIEOBJECT (vergaarbak van van alles).

Een document is volgens mij een INFORMATIEOBJECT van INFORMATIEOBJECTTYPE "document" (of E-mail, of Brief, of whatever gemeentes verzinnen).

Ik zie niet in waarom we daarom INFORMATIEOBJECT moeten splitsen. Het valt allemaal al netjes uit te drukken, op te vragen en aan te maken.

**Comment by MarcoKlerks** [comment]
Het informatieobjecttype INFORMATIEOBJECTTYPE zou dan ook DOCUMENTTYPE moeten gaan heten. ZAAK, STATUS, BESLUIT, PERSOON, etc. zijn ook informatieobjecttypen, maar die gaan we niet opnemen in het lijstje INFORMATIEOBJECTTYPEn, omdat we zaken, statussen, besluiten, personen, etc. niet op gaan nemen in het lijstje INFORMATIEOBJECTen.

Maar dit vraagstuk is inderdaad nogal een inception-geval. Ik praat mijzelf helemaal vast. Ik laat het even rusten.

**Comment by TCIMEddy** [comment]
@ehotting Hier ontstaat waarschijnlijk een interessante discussie maar graag prioriteren voordat we ermee aan de slag gaan. En jouw visie uiteraard

**Comment by ehotting** [comment]
Haha, jaja. Even in de comfort zone van @MarcoKlerks en @ArjanKloosterboer mijn lekenopvatting introduceren, dat doe ik graag. :)  @MarkoKlerks heeft een punt maar als we dit tot in ultimo doorvoeren kunnen we opnieuw beginnen, en wel aan een superkleine API die niemand begrijpt, met bovendien extreem complexe business logica. Liever een API waar nog semantische discussie over mogelijk is maar die aansluit bij hoe in de afgelopen jaren nagedacht is over ZGW door iedereen die RGBZ kent. Als iemand een term bedenkt voor INFORMATIEOBJECT waarmee wel het huidige bakje een nieuwe vlag krijgt maar de rest van de API ongemoeid blijft, welkom. Vooralsnog stel ik voor niets te wijzigen, waarmee het een `wont-fix` wordt.
