### ISSUE TITLE
Als medewerker IB wil ik dat informatieobjecten van status kunnen veranderen (concept, definitief), 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#370]
...zodat de status van het object duidelijk is.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Over welke RGBZ velden hebben we het dan?

**Comment by TCIMEddy** [comment]
@ehotting Voer nooit meer user stories op... :-) @ArjanKloosterboer wil ik even helpen ajb?

**Comment by ArjanKloosterboer** [comment]
Eén van de attributen van Informatieobject is Status en die kent een enumeratie met mogelijke waarden. Dat is natuurlijk niet voor niets dus de mogelijkheid zou er moeten zijn om de waarde van Status te veranderen. Zo staat het min of meer letterlijk in de userstory-titel. Maar ja, waarom en in welke situatie? Oftewel, de userstory is m.i. onvoldoende vanuit de praktijk beschreven. Wat is wel een reele praktijksituatie waarin het wenselijk is om iets te doen met de status van een informatieobject?

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Dank, als ik in mijn geheugen graaf is het antwoord op je vraag bijvoorbeeld een concept besluit -> definitief besluit of concept notulen -> definitieve notulen of concept memo -> definitief. Vergezocht en zeker geen bulk

**Comment by MarcoKlerks** [comment]
Een document dat naar buiten gaat (post, MijnOverheid, publicatie, etc.) moet automatisch definitief worden. Een document dat geagendeerd wordt voor een vergadering moet ook automatisch definitief worden. Wanneer een zaak afgehandeld wordt, dienen alle aanhangende documenten definitef gemaakt te worden. Dit zijn echter nauwelijks losse user stories maar eerder requirements of restrictions voor andere user stories.

Daarnaast zou een gebruiker zelf een document een definitieve status moeten kunnen geven. Dat doen ze wel eens in de praktijk, maar niet consequent.

**Comment by TCIMEddy** [comment]
Commentaar vanuit IB Haarlem Dit kan in Alfresco, maar moet natuurlijk in samenhang met andere applicaties en het zakenmagazijn. Voor een gebruiker moet in een procesapplicatie ook zichtbaar zijn wat de status is. In Alfresco zit hier overigens geen functionaliteit/regels aan vast. Enkel een dropdown menu met drie opties (concept, definitief en in bewerking geloof ik) waaraan wel functionaliteit/regels gekoppeld kunnen worden maar an sich doet het veld niets. NB: Zit er eigenlijk wel iets van status in het contentmodel

**Comment by ehotting** [comment]
Update van status is mogelijk in huidige spec, wellicht verandert de methode nog (create new object naar update) n.a.v. discussie over revisies etc.

Wellicht komt er daarnaast nog iets uit de analyse RGBZ business logica met betrekking hierop, maar dat zien we dan wel. Ik denk dat deze user story niet nodig is. Evengoed dank voor de moeite - dit heb je ingevoerd in tijden van grote schaarste. ;)
