### ISSUE TITLE
Als medewerker IB wil ik dat gebruikers enkel via zaakapplicaties informatieobjecten kunnen opslaan in het DMS, 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#372]
zodat koppeling tussen informatieobjecten en zaken/zaaktypen altijd geborgd is en efficiënt informatiebeheer mogelijk is.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
Graag aandacht voor het scannen en registreren door de postkamer. Onder de noemer van "slim scannen" zal scansoftware proberen om documenten gelijk aan de juiste zaak te relateren. Valt scansoftware onder "zaakapplicaties"?

**Comment by ehotting** [comment]
Hmm... Dit is wat mij betreft niet in lijn met gedachte achter API's

**Comment by TCIMEddy** [comment]
Wat mij betreft dan out of scope of wontfix mits je even aangeeft wat wel in lijn met API’s is

**Comment by Hugo-ter-Doest** [comment]
De DRC zal ook voor niet zaakgerichte documenten worden gebruikt, bijv. documenten die zijn gekoppeld aan een project of client. User story sluit niet aan op de visie. Ik sluit hem.
