### ISSUE TITLE
Als medewerker IB wil ik ook object georiënteerd (NAW, BAG object, etc.) kunnen zoeken naar zaken, 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#374]
zodat samenhang en afhankelijkheden van zaken inzichtelijk kunnen worden.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Graag concreter maken, wat is nou precies de bedoeling? Desnoods meerdere user stories

**Comment by TCIMEddy** [comment]
Ik zal een concreet voorbeeld proberen te geven -> ik wil als ambtenaar bijvoorbeeld weten welke MOR meldingen er zijn in straat x. 
Ik wil weten welke vergunningsaanvragen er lopen in straat
Ik wil weten welke zaken er lopen voor persoon x

Ze willen dus kunnen zoeken op basis van gegevens in allerlei basisadministraties. Klinkt voor de hand liggend en als het geen hout snijdt dan close>

**Comment by ehotting** [comment]
Hmm...  Het gaat om "medewerker IB", dan heb ik een beeld bij voorbeeld 3, maar niet bij voorbeeld 1 en 2. Voorbeeld 3 kan al met huidige API (dus dubbel) voorbeeld 1 en 2 veronderstellen ook info uit een "ander bakje" (dus out-of-scope).  Ik sluit het op basis van voorbeeld 3, welke al mogelijk is (dus dubbel). Als ik het niet goed begrijp hoor ik het wel.
