### ISSUE TITLE
Als medewerker IB wil ik zaken kunnen overbrengen, 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#376]
zodat wordt voldaan aan de Archiefwet.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
De meeste archiefprofessionals gaan ervan uit dat bij overbrenging een export wordt gedraaid, waarna de desbetreffende gegevens worden vernietigd. De export wordt vervolgens ingelezen in het e-depot, waarna de informatie daar benaderd kan worden.

De vraag (die nog niet in het openbaar is gesteld) is of we overbrenging nog wel moeten realiseren volgens de export-import-methode. Kunnen we de informatie niet laten staan waar die staat en de verantwoordelijkheid voor het beheer overdragen aan de archiefdienst? Ook zal dan semi-geautomatiseerd de openbaarheid aangepast moeten worden.

Ik zie elders al use cases die de duurzame toegankelijkheid van de informatie moeten borgen (bijvoorbeeld #380). Dit zijn dezelfde functionaliteiten als die in een e-depotsysteem nodig zijn.

Mijn advies is om i.s.m. KVAN/BRAIN te onderzoeken of Common Ground het gemeenschappelijke e-depotsysteem van gemeenten kan worden. Ondertussen zou ik nog niet aan de slag gaan met overbrengingsfunctionaliteit. Overigens begint het Nationaal Archief binnenkort met het opstellen van een uitwisselingsstandaard, dus ik zou daar ook even de uitkonsten van afwachten.

**Comment by ehotting** [comment]
@MarcoKlerks  Hoewel ik het eens ben met je visie verwacht ik niet dat we binnen afzienbare tijd voortgang zullen zien in die richting. e-Depots een hoop functionaliteit nodig die niet in scope van dit scrum team wil halen, denk aan collectiebeheer. Zelfs al een aantal voorlopende gemeenten dergelijke experimenten aangaan (daar zullen ook allerlei juridische hobbels voor genomen moeten worden zoals wijziging van opdracht GR's, vaak niet eenvoudig!) denk ik dat we veel gemeenten nu beter helpen met een TMLO export.

**Comment by ehotting** [comment]
Deze user story verdient een gemeente die er mee aan de slag wil. @BoerBas  ?

**Comment by Hugo-ter-Doest** [comment]
Prio ZH, omdat het een basismechanisme is voor archiveren.

**Comment by MarcoKlerks** [comment]
Ik heb deze user story gerefined in #718 , #719 en #720 .
