### ISSUE TITLE
Als ambtenaar wil ik dat zaken aan dossiers gekoppeld kunnen worden (documenten aan zaken, documenten aan dossiers, etc), 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#381]
zodat de informatieobjecten in hun context raadpleegbaar zijn.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
Zaken zijn dossiers. We spreken ook wel van zaakdossiers. Ze hoeven niet áán een dossier gekoppeld te worden. Zie het RGBZ.

Vroeger stopten we documenten samen in kartonnen mapjes om ze bij elkaar te houden. Op het mapje schreven we dan o.a. waarover het stapeltje documenten ging en hoe lang we ze wilden bewaren. Mapjes met vergelijkbare inhoud zetten we bij elkaar in de kast, zodat ze makkelijker te vinden waren.

In de digitale situatie relateren we documenten aan zaken. Op de zaak leggen we vast waar deze over gaat en hoe lang we haar willen bewaren. Zoeken doen we door te queriën en te filteren.

In de papieren situatie wilden we inderdaad nog wel eens meerdere zaken in één dossier stoppen. Sommige zaken omvatten dermate weinig informatie (velletjes papier), dat het qua kastruimte zonde was om om iedere zaak een kartonnen mapje te vouwen. We zouden meer karton in onze archiefkasten hebben zitten dan documenten!

Overigens kan de behoefte aan dossiers in Common Ground wel weer opduiken wanneer we ook niet-zaakgericht werken en archiveren willen ondersteunen. Oftewel, als we documenten gaan bewaren die we niet aan een zaak kunnen relateren, dan willen we deze mogelijk (!) aan een dossier kunnen relateren. Denk bijvoorbeeld aan beeldarchieven, beheerdocumentatie (bijv. handleidingen), knipselmappen, etc.

**Comment by ehotting** [comment]
Kennen we in RGBZ het concept dossiers?

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Zie vraag Eelco -> kennen we in RGBZ concept dossiers?

**Comment by ArjanKloosterboer** [comment]
> Zaken zijn dossiers. We spreken ook wel van zaakdossiers. Ze hoeven niet áán een dossier gekoppeld te worden. Zie het RGBZ.

Zo is dat! Userstory graag herformuleren. 

> Overigens kan de behoefte aan dossiers in Common Ground wel weer opduiken wanneer we ook niet-zaakgericht werken en archiveren willen ondersteunen. Oftewel, als we documenten gaan bewaren die we niet aan een zaak kunnen relateren, dan willen we deze mogelijk (!) aan een dossier kunnen relateren. Denk bijvoorbeeld aan beeldarchieven, beheerdocumentatie (bijv. handleidingen), knipselmappen, etc.

Inderdaad, er zijn ook andere dossiers dan zaakdossiers. De bedoeling is dat de, onder de noemer ZDS te ontwikkelen, API's zo generiek zijn dat ze alle typen dossiers aankunnen. Zie discussie #166 en [deze vergadernotitie](https://www.gemmaonline.nl/index.php/EgIM_20180927_ag_4_-_Aanpassingen_RGBZ). 

> Kennen we in RGBZ het concept dossiers?

Nee. Wat is dat, een 'conceptdossier'? M.i. bestaat dit niet. Een dossier is er, dat bestaat in de feitelijke werkelijkheid en moet duurzaam toegankelijk zijn, hoe kort of lang ook. Documenten daarin kunnen een concept-status hebben. 
Het onderwerp van het dossier kan van tijdelijke aard zijn, een proefballonnetje oid. Het dossier is niet meer of minder dan een bundeling van de desbetreffende informatie. Dat dossier heeft een permanente status, die is er 'gewoon'.

**Comment by MarcoKlerks** [comment]
> Inderdaad, er zijn ook andere dossiers dan zaakdossiers. De bedoeling is dat de, onder de noemer ZDS te ontwikkelen, API's zo generiek zijn dat ze alle typen dossiers aankunnen. 

Betekent dat dat er in het gegevensmodel nog een objecttype DOSSIER toegevoegd moet worden, waarbij documenten aan óf een zaak óf een dossier gekoppeld moeten worden? Of worden deze andersoortige dossiers als ZAAK geregistreerd?

**Comment by ehotting** [comment]
Typefout, ik bedoelde _het_ concept. Kennen we _het_ concept "dossier".

Maar, gelet op de reactie van @MarcoKlerks en @ArjanKloosterboer heb ik de indruk dat deze user story kernfunctionaliteit van de API beschrijft die we al aan de hand van een veel meer concrete user story hebben uitgewerkt en ingebouwd.

**Comment by ArjanKloosterboer** [comment]
> Betekent dat dat er in het gegevensmodel nog een objecttype DOSSIER toegevoegd moet worden, waarbij documenten aan óf een zaak óf een dossier gekoppeld moeten worden? Of worden deze andersoortige dossiers als ZAAK geregistreerd?

M.i. niet. Het dossier is de verzameling van informatie 'ergens over'. Dat 'ergens' kan een zaak zijn, een project , een gemeenteraadsvergadering et cetera. De optelsom van gestructureerde en ongestructureerde informatie hierover is het dossier. Dat 'ergens' heb ik in het Informatiemodel Informatieobjecten 'Concept' genoemd. Zie de notitie waarnaar ik eerder verwijs. 

> Typefout, ik bedoelde het concept. Kennen we het concept "dossier".

Ja, dat kennen we. In de informatiemodellen komt dit niet als objecttype terug. Omdat het concept waarop het dossier betrekking heeft al als objecttype onderscheiden wordt. Alle informatie over dat concept vormt gezamenlijk het dossier.  

> Maar, gelet op de reactie van @MarcoKlerks en @ArjanKloosterboer heb ik de indruk dat deze user story kernfunctionaliteit van de API beschrijft die we al aan de hand van een veel meer concrete user story hebben uitgewerkt en ingebouwd.

Dat hebben we v.w.b. zaken ook mijns inziens al gedaan. Wellicht willen we nog een toets of het losgeknipte en generiek gemaakte documentendeel ook buiten het zaakgericht werken toepasbaar is? M..i. is dat deel namelijk wel losgeknipt maar nog niet generiek gemaakt.

**Comment by MarcoKlerks** [comment]
> Het dossier is de verzameling van informatie 'ergens over'. Dat 'ergens' kan een zaak zijn, een project , een gemeenteraadsvergadering et cetera. De optelsom van gestructureerde en ongestructureerde informatie hierover is het dossier. 

Graag aandacht voor het volgende. Als een document niet gekoppeld is aan een zaak (maar wel aan andere informatieobjecten), hoe voeren we dan het informatie- en archiefbeheer uit? De metadata hiervoor (o.a. bewaartermijn) leggen we immers vast op zaken.

Dit vraagt om user stories op alle mogelijke concept-varianten. Bijvoorbeeld:
- Het berekenen van een vernietigingsdatum op documenten die niet aan een zaak, maar wel aan een rechtspersoon zijn gekoppeld (het cliëntdossier)
- Het berekenen van een vernietigingsdatum op documenten die niet aan een zaak, maar wel aan een ruimtelijk object (bijv. pand of brug) zijn gekoppeld (het objectdossier)

En hoe gaan we om met documenten die aan meerdere informatieobjecten (personen, objecten, een project, etc.) gekoppeld zijn? Hoe leggen we vast welk gerelateerd informatieobject hét dossier/concept is langs welke het informatie- en archiefbeheer inrichten?

Jullie begrijpen dat ik voorstander ben voor een apart informatieobject DOSSIER, voor alle niet-zaaksgewijze oplossingen. Het dossier kan dan vervolgens gekoppeld worden aan het informatieobject dat de samenhang definieert van de documenten: "Al deze documenten gaan over..."

Ik kan mij ook voorstellen dat naast de DOSSIERs er aparte informatieobjecten voor PROJECTen en VERGADERINGen in het gegevensmodel worden opgenomen, die een gelijke werking hebben als ZAAKen. Dat wil zeggen dat je documenten direct aan projecten en vergaderingen kunt koppelen en dat beheer-metadata op projecten en vergaderingen worden vastgelegd. Dat vraagt echter mogelijk ook om het definiëren van meerdere PROJECTTYPEn en VERGADERINGTYPEn. Je zou projecten en vergaderingen m.i. echter ook zaaksgewijs kunnen aanpakken, al vragen zij inderdaad om enkele extra functionaliteiten die niet nodig zijn bij "gewone", dienstverlenende processen.

**Comment by ArjanKloosterboer** [comment]
> Jullie begrijpen dat ik voorstander ben voor een apart informatieobject DOSSIER, voor alle niet-zaaksgewijze oplossingen. Het dossier kan dan vervolgens gekoppeld worden aan het informatieobject dat de samenhang definieert van de documenten: "Al deze documenten gaan over..."

Ik niet. Ik heb hiervoor al uitgelegd dat een dossier meer is dan een verzameling informatieobjecten. Wel onderken ik de door jou geschetste problematiek. Primair is m.i. het 'concept' (zaak, project, vergadering e.d.) waarbij oa. de informatieobjecten horen, bepalend voor het archiefbeheer (van alle daarvan vastgelegde informatie). Voor een zaak is dat geregeld, daarover kunnen afspraken vastgelegd worden o.b.v. RGBZ en ImZTC. Maar inderdaad, is er zoiets ook voor project, vergadering e.d.? En zo niet, is het dan een oplossing om dat dan maar vast te leggen in de DRC bij het 'concept' waarvan de informatieobjecten deel uit maken? Wat betekent dat voor de (gestructureerde) informatie die is vastgelegd van een project in een projectenregistratie (in een desbetreffende registratiecomponent), van een vergadering in een raadsinformatiesysteem (idem), et cetera? Of moet bij het ontbreken daarvan de DRC er dan maar in voorzien? 
Vergt al met al nog enig analysewerk.

**Comment by Hugo-ter-Doest** [comment]
Andere CONCEPTen buiten ZAAK zullen voor een archiveringsregime moeten zorgen om CONCEPTdossiers (dus metadata èn documenten) te kunnen archiveren. Ik volg hiermee de draft voor de aanpassingen aan het RGBZ waaraan hierboven wordt gerefereerd.
