### ISSUE TITLE
Als medewerker IB wil ik dat wordt voldaan aan de NEN ISO norm 13008 voor conversie, migratie, e.d.

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#382]
zodat de gemeente voldoet aan de wettelijke eisen voor overdracht en informatie duurzaam toegankelijk blijft.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Expert-input, @MarcoKlerks ?

**Comment by MarcoKlerks** [comment]
Sorry, tot gisteren had ik nog nooit van de ISO 13008 gehoord. Digitale preservatie is niet mijn expertise. Gaan jullie zelf op zoek naar een expert of zal ik eens in mijn netwerk rondvragen?

Wel wil ik alvast ter inspiratie een schrijfsel van mij uit 2016 met jullie delen. Ik heb het nooit afgemaakt (versie 0.1), maar misschien helpt het. 

[20160524 Vraag naar functionaliteit tbv migratie van bestandsformaten.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/2440810/20160524.Vraag.naar.functionaliteit.tbv.migratie.van.bestandsformaten.docx)

**Comment by MarcoKlerks** [comment]
Dit speelt bij alle gemeenten, maar gemeenten gaan hier op verschillende wijzen mee om.

Conversie van bestanden is nodig om te borgen dat zij over tig jaar nog steeds geraadpleegd kunnen worden. Bijvoorbeeld, als ik vandaag een excel-bestand aanmaak en opsla dan kan ik deze volgend jaar waarschijnlijk nog wel openen. Maar kan ik hem over vijf jaar ook nog openen? En over 10 jaar? En over 30 jaar?

Documenten/bestanden die voor eeuwig bewaard moeten worden brengen we over 20 jaar over naar een e-depot. In de nieuwe Archiefwet waar aan gewerkt wordt, gaat deze termijn terug naar 10 jaar. In het e-depot zal geregeld moeten worden dat verouderde bestandsformaten worden geconverteerd naar een actueel formaat.

MAARRRRR....:
- We weten niet of alle bestandsformaten die we nu opslaan nog wel 10 jaar houdbaar zijn, en
- Veel documenten zijn weliswaar niet eeuwig te bewaren, maar moeten wel tientallen jaren bewaard worden.

De vraag is wat jullie met Common Ground willen ondersteunen:

1. De opslag en ontsluiting  van zaken en documenten t/m (vlak na)  de afhandeling, of
2. De opslag en ontsluiting van zaken en documenten t/m vernietiging of overbrenging.

Als jullie  kiezen voor het tweede, dan zullen jullie ook RMA-functionaliteiten moeten ondersteunen zoals het verduurzamen van bestanden middels conversie en migratie.

**Comment by Hugo-ter-Doest** [comment]
Wordt meegenomen bij de epic Archiefbeheer.

**Comment by Hugo-ter-Doest** [comment]
Is dit verplicht?
En is functionaliteit voor verduurzamen onderdeel van deze API?

**Comment by Hugo-ter-Doest** [comment]
Vooralsnog gaan we ervan uit zaakdossier worden overgedragen naar een separaat eDepot en dat de ZGW registraties niet worden gezien als eDepot. Daarmee zijn de eisen van deze standaard buiten scope.
