### ISSUE TITLE
Als medewerker IB wil ik dat er (automatisch) een vernietigingslijst te genereren valt, 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#384]
zodat er adequaat en efficiënt voldaan kan worden aan de selectielijst, vernietigingstaak.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
Het is goed om hier een onderscheid te maken tussen de concept-vernietigingslijst (zie #347 ) en de definitieve vernietigingslijst (zie #349 ).

Mogelijk wil je in de concept-vernietigingslijst wel persoongebonden gegevens (bijv. BSN) opnemen, zodat de proceseigenaar de zaken eruit kan vissen die bij wijze van uitzondering langer bewaard moeten worden. In de definitieve vernietigingslijst mogen echter geen persoonsgegevens voorkomen i.v.m. privacy.

**Comment by ehotting** [comment]
Voor deze user story is een grondige uitwerking van het proces / de business logica belangrijk zodat devs kunnen afleiden welke API calls nodig zijn

**Comment by TCIMEddy** [comment]
@BoerBas Is deze ‘toevallig’ voorhanden?

**Comment by MarcoKlerks** [comment]
Zie ook mijn reactie onder #371. Daarin beschrijf ik kort welke stappen achtereenvolgens gemaakt moeten worden om van een bewaartermijn tot een vernietigingslijst tot daadwerkelijke vernietiging te komen.

**Comment by Hugo-ter-Doest** [comment]
dubbel met #347
