### ISSUE TITLE
Als medewerker IB wil ik dat de opslag van informatieobjecten de taxonomie van documenttypen  volgt, 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#385]
zodat efficiënter informatiebeheer uitgevoerd kan worden en vindbaarheid en toegankelijkheid vergroot wordt.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by bvhme** [comment]
Een vraag: zou er niet een **open standaard** moeten worden gebruikt? De _NEN 2084:2015 nl_ is dit namelijk niet? Op de standaard rust een gesloten licentie op en er moet betaald worden om hem in te kunnen zien.

**Comment by MarcoKlerks** [comment]
Zelf ben ik geen groot fan van deze standaard. Kun je uitleggen welk probleem dit oplost?

Volgens mij kun je gemeenten beter de mogelijkheid bieden om een lijst aan documenttypen in te richten. Als een gemeente het nodig vindt om deze standaard te volgen, dan moet zij dat vooral doen.

**Comment by bvhme** [comment]
Ah, dus begrijp ik het dan goed dat het een feature moet zijn dat gemeentes dit moeten kunnen doen? Als requirement voor de ontwikkeling lijkt het me problematisch omdat je de ontwikkeling afsluit voor diegene die geen toegang hebben tot de standaard. Maar als het arbitrair is om hier aan mee te kunnen doen lijkt het me geen probleem.

**Comment by TCIMEddy** [comment]
@MarcoKlerks @bvhme Dank voor jullie bijdrage/discussie, dit geeft PO @ehotting en team richting.

**Comment by ehotting** [comment]
De richting die het geeft is dat we waarschijnlijk liever geen NEN 2048 willen. ;)  Maar ik check nog even waarom @TCIMEddy dit wel voorstelde - zit er een bepaalde verplichting achter?

**Comment by Hugo-ter-Doest** [comment]
Gemeenten kunnen als onderdeel van de ZTC informatieobjecttypen inrichten volgens eigen inzicht. Daarbij kunnen ze uiteraard gebruik maken van een bestaande ZTC of een standaard die informatieobjecttypen beschrijft.
