### ISSUE TITLE
Als gemeente wil ik dat zaakgegevens en documentgegevens in ZRC en DRC te allen tijde voldoen aan de zaaktypes zoals vastgelegd in de ZTC

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#388]
...zodat de kwaliteit van de gegevens gewaarborgd is.

Op dit moment vindt er via #130 eenvoudige en minimale input-validatie plaats in de referentie-implementaties: de input-URL van linked-data resources moet in een `HTTP 200` resulteren. We kunnen hier echter verder in gaan, en controleren dat dit ook echt zinvolle data bevat.

Enkele voorbeelden (niet-exhaustief):

- `zaaktype` referentie bij het aanmaken of updaten van een zaak: valideer dat de response er ook uitziet als een `ZaakType` resource uit de OAS spec van het ZTC. Indien dat niet het geval is, antwoord met een `HTTP 400`

- Aanmaken van een status bij een zaak:
    - haal de resource `statustype` op
    - valideer dat dit inderdaad overeenkomt met de `StatusType` resource uit de ZTC OAS spec
    - vergelijk de `zaak.zaaktype` URL en de `statustype.zaaktype` URL - indien deze niet overeenkomen, dan antwoorden met een `HTTP 400`

- Toevoegen van een informatieobject bij een zaak:
    - valideer dat het `informatieobject.informatieobjecttype` overeenkomt met een geldige URL in `zaak.zaaktype.informatieobjecttypen`

Je ziet dat er hier op plaatsen best verregaande controles plaatsvinden. Deze moeten ook allemaal gedocumenteerd worden in wat uiteindelijk de standaard wordt, aangezien dit niet afgedwonen kan worden in de OAS spec.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [x] er is een OAS 3.0 specificatie
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by sergei-maertens** [comment]
@ehotting vanuit technisch perspectief wil ik deze graag volgende sprint meenemen :-)

**Comment by ehotting** [comment]
Graag - dit is zeer waardevol voor de API

**Comment by ehotting** [comment]
(Is het hiervoor nodig eerst de business logica RGBZ te kennen, zie #432 ? Zo ja, hier label blok toevoegen)

**Comment by joeribekker** [comment]
Geldt voor alle relaties tussen API's.

**Comment by joeribekker** [comment]
Sommige relaties hoeven we overigens niet te volgen tot een HTTP 200. Kan me voorstellen dat je een object koppelt waar de consumer wel rechten toe heeft, maar het ZRC niet.

**Comment by Hugo-ter-Doest** [comment]
Validatie is op maat afhankelijk van de verwijzing. Bijv. zaaktype verwijziging wordt gecontroleerd op bestaan en inhoud. Het hangt af van wat er gebruikt wordt.

**Comment by Hugo-ter-Doest** [comment]
@michielverhoef maakt een tabelletje.

**Comment by michielverhoef** [comment]
Kunnen jullie hiermee uit de voeten?

| **API** | **resource** | **regel** |
| -------- | -------- | ---------------- |
| **ZRC** | aanmaken of bijwerken van een ZAAK | is ZAAKTYPE correct? |
| | | is url naar ZAAKTYPE geldig en komt er een ZAAKTYPE resource uit? |
| | | is de bronorganisatie gevuld met een geldig RSIN van 9 nummers welke voldoet aan de 11-proef? |
| | | is de verantwoordelijkeOrganisatie gevuld met een geldig RSIN van 9 nummers welke voldoet aan de 11-proef? |
| | | is de startDatum gevuld met een geldige datum die kleiner of gelijk aan vandaag is? |
| | aanmaken of bijwerken STATUS van een ZAAK | is url naar STATUSTYPE geldig en komt er een STATUSTYPE resource uit |
| | | is het STATUSTYPE geldig voor het ZAAKTYPE |
| | | mag dit STATUSTYPE nu gezet worden, maw is het een geldig STATUSTYPE na het voorgaande STATUSTYPE? |
| | | is de datumStatusGezet gevuld met een geldige datum die kleiner of gelijk aan vandaag is? |
| | aanmaken of bijwerken RESULTAAT | is url naar RESULTAATTYPE geldig en komt er een RESULTAATTYPE resource uit|
| | is het RESULTAATTYPE geldig voor het ZAAKTYPE |
| | aanmaken of bijwerken ROL | is het ROLTYPE geldig voor het ZAAKTYPE | 
| | | is url naar ROLTYPE geldig en komt er een ROLTYPE resource uit |
| | aanmaken of bijwerken KLANTCONTACT | is url naar de ZAAK geldig en komt er een ZAAK resource uit|
| | | is de datumTijd gevuld met een geldige datumTijd die kleiner of gelijk aan vandaag is? |
| **DRC** | Aanmaken INFORMATIEOBJECT** | is url naar INFORMATIEOBJECTTYPE geldig en komt er een INFORMATIEOBJECTTYPE resource uit? |
| | | aanmaken of bijwerken ZAAKINFORMATIEOBJECT | is url naar ZAAK geldig en komt er een ZAAK resource uit? |
| | | is url naar INFORMATIEOBJECT geldig en komt er een INFORMATIEOBJECT resource uit? | 
| | | is INFORMATIEOBJECTYPE een geldig type binnen het ZAAKTYPE van de ZAAK? |
| | | aanmaken of bijwerken OBJECTINFORMATIEOBJECT | is url naar OBJECT geldig en komt er een resource uit? |
| | | is url naar INFORMATIEOBJECT geldig en komt er een INFORMATIEOBJECT resource uit? | 
| **BRC** | aanmaken of bijwerken BESLUIT | Is BESLUITTYPE correct? |
| | | Als BESLUIT is uitkomst van een ZAAK: Is BESLUITTYPE toegestaan bij dit ZAAKTYPE |
| | | aanmaken BESLUITINFORMATIEOBJECT | is url naar BESLUIT geldig en komt er een BESLUIT resource uit? |
| | | is url naar INFORMATIEOBJECT geldig en komt er een INFORMATIEOBJECT resource uit? |
| | | Als het een BESLUIT in het kader van een ZAAK betreft, is INFORMATIEOBJECTYPE een geldig type binnen het ZAAKTYPE van de ZAAK? |
| **NRC** | Aanmaken of aanpassen ABONNEMENT | Is de callbackurl correct en kan die url een NOTIFICATIE ontvangen? |
| | | Is de auth gevuld en kan hiermee een NOTIFICATIE naar de callbakcurl verstuurd worden? | 
| | | Is er tenminste één kanaal gevuld | 
| | | Is elk kanaal een correcte URL en kan via deze url een KANAAL resource opgehaald worden? | 
| | aanmaken van een kanaal | is de naam van het kanaal uniek |  
| | | is de documentatieLink een correcte url en kan hiermee documentatie opgehaald worden? | 
| | aanmaken van een notificatie | is het kanaal een geldige naam van een kanaal welke bereikt kan worden? | 
| | | is het hoofdObject een correcte url en kan hiermee een hoofdobject opgehaald worden? | 
| | | is de resource een correcte naam (type?) |
| | | is de resourceURL gevuld en kan hiermee de resource opgehaald worden? |
| | | is de actie gevuld? |
| | | is de aanmaakdatum kleiner of gelijk aan vandaag? |
| **Notificaties Consumer** | Ontvangen van een NOTIFICATIE | is het kanaal een geldige naam van een kanaal welke bereikt kan worden? | 
| | | is het hoofdObject een correcte url en kan hiermee een hoofdobject opgehaald worden? | 
| | | is de resource een correcte naam (type?) |
| | | is de resourceURL gevuld en kan hiermee de resource opgehaald worden? |
| | | is de actie gevuld? |
| | | is de aanmaakdatum kleiner of gelijk aan vandaag? |
| **Authentication** | registreer of bewerk een APPLICATIE | is clientIds gevuld met een correcte waarde? | 
| | | is het label gevuld? (NB. hoe controleren we of het leesbaar is voor eindgebruikers?) | 
| | | Als autorisaties gevuld is (not null) dan moet heeftAlleAutorisaties gelijk zijn aan false of leeg (null) zijn |
| | | Als autorisaties niet gevuld zijn (null) dan moet heeftAlleAutorisaties gevuld zijn met true |

**Comment by joeribekker** [comment]
Er zijn 3 niveaus voor URLs validatie.

1. Validatie op geldig URL formaat
   _Typisch voor niet API-resource URLs. We weten immers niet of dit component bij deze URL kan._
2. Validatie of OBJECT via deze URL kan worden opgevraagd door dit component en de response voldoet aan de geldende OAS
   _Alleen als je weet dat dit component deze URL moet kunnen bereiken om de response te verwerken, zoals bijv. ZAAKTYPE op een ZAAK._
3. Validatie of OBJECT via deze URL kan worden opgehaald door dit component en voldoet aan de nodige businesslogica, te weten: [...]
   _Bijv. alleen STATUSTYPE koppelen die mogelijk is binnen het ZAAKTYPE van de zaak._

Deze vormen van validatie zou eigenlijk bij elk URL-veld moeten komen staan.

**Comment by sergei-maertens** [comment]
@michielverhoef ik heb je [comment](https://github.com/VNG-Realisatie/gemma-zaken/issues/388#issuecomment-510217029) bijgewerkt met de stand van zaken van validaties. Een aantal opmerkingen nog:

**ZRC**

* `Zaak.startdatum <= nu`: RGBZ specifieert dat datums in de toekomst ook toegelaten zijn. Is dit een afwijking of een foutje van jou?
* `Status.statustype`
  > mag dit STATUSTYPE nu gezet worden, maw is het een geldig STATUSTYPE na het voorgaande STATUSTYPE?

  betekent dit dat we volgnummer moeten gaan valideren? wat doen we dan als je van eindstatus terug een lager volgnummer zet om de zaak te heropenen?

**NRC**
* > Is er tenminste één kanaal gevuld

  deze snap ik niet?
* > Is elk kanaal een correcte URL en kan via deze url een KANAAL resource opgehaald worden?

  Kanalen zijn geen URLs bij het aanmaken van abonnementen, maar gewoon de strings/labels ervan.

Notificaties aanmaken:

* > kan het hoofdobject opgehaald worden?
  
  NRC zal m.i. zelden autorisatie hebben om deze objecten op te vragen, dus je kan dit niet testen

* > is de resource een correcte naam (type?)

  Dit betekent dat we lijst moeten vastleggen van alle mogelijke resources in alle mogelijke APIs, en flink inboeten aan flexibiliteit. Dat betekent ook dat APIs die (nog) niet gestandaardiseerd zijn geen gebruik kunnen maken van NRC als ze custom resources hebben.

* > kan de resource opgehaald worden?

  Zie opmerking bij hoofdobject

Ontvangen notificaties:

Validatie hier is volledig aan de ontvanger, volgens mij kan je hier niets afdwingen.

**AC**

* > is clientIds gevuld met een correcte waarde?

  niet na te gaan, client IDs leven in de (zaken|documenten|catalogi|besluiten|autorisaties)-api, die het AC bevragen, niet omgekeerd.

**Comment by Hugo-ter-Doest** [comment]
Ik probeer zoveel mogelijk te beantwoorden:

* Startdatum moet ook in de toekomst kunnen liggen conform RGBZ. Bijv. zinvol voor inplannen toezichtzaken.
* Volgorde statussen: bij heropenen van de zaak geldt die volgorde-eis niet. Dus dan niet valideren. Verder moeten we accepteren dat de statussen niet in volgorde hoeven te zijn.
* Tenminste een kanaal gevuld: ik denk dat bedoeld wordt dat elke component minimaal een kanaal moet hebben. Het heeft geen zin notificatie in te richten met een abonnement als er geen kanaal is.
* Is elk kanaal een correcte URL en kan via deze url een KANAAL resource opgehaald worden? --> weghalen
* kan het hoofdobject opgehaald worden? -> de NRC hoeft niet te weten waar de notificaties over gaan. Is de verantwoordelijkheid van de zender van de notificatie.
* is de resource een correcte naam (type?) -> NRC controleert dit niet.
* ontvangen notificaties: hier zou je kunnen checken of de endpoint bestaat?
* is clientIds gevuld met een correcte waarde? -> eens met opmerking Sergei

**Comment by sergei-maertens** [comment]
Lijstje bijgewerkt - @stevenbal, kan je de open items in [de tabel](https://github.com/VNG-Realisatie/gemma-zaken/issues/388#issuecomment-510217029) nog oppakken? De notificaties consumer kan je overslaan - valt niet te testen.

**Comment by stevenbal** [comment]
@sergei-maertens de tabel is weer bijgewerkt

**Comment by sergei-maertens** [comment]
Top, dan is deze ook afgerond!
