### ISSUE TITLE
Als ontwikkelaar wil ik bij het opvragen van entiteit ook eigenschappen van gerelateerde entiteiten opnemen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/gemma-zaken#389]
...zodat het aantal calls wordt beperkt in de situatie dat er veel voorkomende combinaties van elementen uit verschillende gerelateerde entiteiten zijn. 

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een voorbeeld van hoe dit in een  OAS 3.0 specificatie wordt opgenomen
- [ ] de gemaakte ontwerpkeuzes zijn gedocumenteerd
[ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP]( https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md )
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Visie op geneste entiteiten formuleren  [_verantwoordelijke_]
- [ ] Discussie voeren (waar nodig)
- [ ] Voorbeeldspecificatie OAS3 opstellen  [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Vastleggen \design Decission [_verantwoordelijke_]

**Comment by Occipio** [comment]
In de API's die binnen het project "Bevragingen ingeschreven persoon" worden elementen van gerelateerde entiteiten "embedded" opgenomen volgens JSON Hal. Als we geen JSON Hal gaan toepassen gaan we dan gebruik maken van geneste entiteiten ? 
In de huidige API van Gemma-zaken zie ik daar geen voorbeeld van aangezien van alle gerelateerde entiteiten alleen de links worden opgenomen in de response. 
Ik ben benieuwd hoe binnen het project Gemma-Zaken tegen het nesten van entiteiten wordt aangekeken.

**Comment by sergei-maertens** [comment]
Dit is binnen gemma-zaken nog niet concreet geimplementeerd, maar we volgen hier wel de DSO API-strategie (API-10)

> Resources ondersteunen “lazy” en “eager” laden van relaties
> Resources die een n-op-n relatie kennen ondersteunen zowel het teruggeven van identificaties van
> gerelateerde resources (lazy loading) als het teruggeven van de resources zelf (eager loading).

Voorbeeld:

`GET /aanvragen/12?expand=aanvrager.naam,bevoegd_gezag`

Doordat we JSON Hal hier niet zo fijn vinden, worden deze resources dan inline genest.

Concreet kan dat dus worden:

```http
GET /api/v1/zaken/1234?expand=status

{
    "identificatie": "1234",
    "bronorganisatie": "56789",
    "status": {
        "url": "...",
        "statusType": "https://ztc/api/v1/statustypen/123456789",
        ...
    }
}
```
Merk op dat deze relaties niet altijd ge-expand kunnen worden. Binnen een zaak het zaaktype expanden bijvoorbeeld kan niet omdat dit een referentie is naar een component uit een andere API (ZRC vs. ZTC).

**Comment by joeribekker** [comment]
**Besloten tijdens overleg d.d. 17 september 2018**

We implementeren `expand` zonder HAL. In de documentatie moet dit naar voren komen EN er moet vermeld worden dat expand de OpenAPI elementen worden veranderd (lees: de spec klopt niet meer want er staat opeens een object waar eerst een linkje stond).

**Comment by ehotting** [comment]
Design choice met behoorlijke impact, s.v.p. uitwerken en afronden in afstemming met RSGB team

**Comment by TCIMEddy** [comment]
@joeribekker @Hugo-ter-Doest Weten jullie de status?

**Comment by TCIMEddy** [comment]
@joeribekker @Hugo-ter-Doest Goed punt maar ik weet niet of we dit moeten en kunnen realiseren.

**Comment by Hugo-ter-Doest** [comment]
Ik stel voor: label convenience maken, en later samen met andere gelijksoortige uitbreidingen voor gemak bepalen wat ermee te doen.

**Comment by michielverhoef** [comment]
opgenomen in Zaken API 1.5.0
