### ISSUE TITLE
Als burger wil ik op de website van de gemeente een anonieme melding van het type overlast op het water kunnen doen

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#39]
...zodat de gemeente op de hoogte is van de overlast en hierop kan acteren.

**Shortcuts**
- [RGBZ Mapping](https://github.com/VNG-Realisatie/gemma-zaken/issues/39#issuecomment-395697107)
- [testdata (.json)](https://github.com/VNG-Realisatie/gemma-zaken/issues/39#issuecomment-395698491)

**Definition of done**

- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- ~~[ ] er is functionele documentatie conform het DSO-patroon~~

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] de DSO URI- en API-strategie worden gevolgd

**Taken**
- [x] Opstellen welke velden bij een melding horen [@MarcelMoerman]
- [x] Aanleveren testdata [@MarcelMoerman]
- [x] Schrijven (unit) test voor referentie-implementatie [@sergei-maertens]
- [x] Implementeren in referentie-implementatie [@sergei-maertens]
- [x] Genereren/opstellen van OAS 3.0 [@sergei-maertens]
- ~~[ ] Functionele documentatie [@michielverhoef ]~~
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [?]

**Comment by ehotting** [comment]
Taken:
- [ ] Aanleveren velden
- [ ] Test data
- [ ] Development Street inrichten
- [ ] Unit test
- [ ]

**Comment by sergei-maertens** [comment]
@ehotting ik heb de taken in de originele beschrijving opgenomen, misschien beter om dit af te spreken zodat het niet begraven wordt in comments?

**Comment by jgortmaker1** [comment]
ik mis de 2 reviews die we gisteren hebben besproken:

- de review op GEMMA
- de algemene review als het klaar is

zijn deze vergeten, of mogen reviews geen taken zijn in scrum?

**Comment by sergei-maertens** [comment]
@jgortmaker1 dit lijkt me onderdeel van de review op het pull request wat hiervoor zal volgen

**Comment by ehotting** [comment]
Taak "Dev straat inrichten" verhuist wat mij betreft naar US #93

**Comment by joeribekker** [comment]
Eens, aangepast.

**Comment by ArjanKloosterboer** [comment]
Gaat het hier wel over een zaakdocumentservice? Ik ben geneigd ontkennend te antwoorden. Het betreft het indienen van een melding en dan zijn er twee domeinen bij betrokken: het dienstverleningsdomein en het inhoudelijke domein i.c. openbare veiligheid, (nog) niet het zaken-behandelen-domein (waarin zich de ZDservices bevinden). Het is een melding, geen zaak (net zoals een koe geen biefstuk is al kun je het er wel van maken;-). Hoe wordt die melding verwerkt, hoe loopt 'ie door de organisatie en de informatievoorziening? Het antwoord daarop levert inzicht in aard en inhoud van de service(s). M.i. wordt die melding aangeboden aan een meldingbehandelende applicate zoals een MOR-applicatie of een generieke zaakbehandelapplicatie. Die verwerkt die melding tot zaak. En die zaak kan door naar de ZRC. Over welke API('s) hebben we het nu?

**Comment by jgortmaker1** [comment]
volgens GEMMA 2 2 API`s: nummer 3 hier: https://www.gemmaonline.nl/index.php/ZGW_in_GEMMA_2_compleet#Indienen_productaanvraag_via_webformulier

en nummer 1 hier: https://www.gemmaonline.nl/index.php/ZGW_in_GEMMA_2_compleet#Registreren_zaak_vanuit_Zaakafhandelcomponent 

Hypothese was dat dit voor de API niet uitmaakt...inmiddels zijn we zo ver (zie #78 als ik me niet vergis) dat implementatie wel uitmaakt bij realisatie door verschillende componenten..

En het punt dat overblijft is hoe we (in Common Ground) de gegevens uit de aanvraag over ZRC, DRC en Objectenregistratie (of hoe we dat ook gaan noemen) gaan verdelen en welke API's daarbij horen.

**Comment by sergei-maertens** [comment]
Wat ik begreep van Marcel is dat elke melding een zaak moet worden en zodanig afgehandeld worden.

Er is een webformulier/mobiele app/<iets anders> wat je toelaat om de gegevens in te voeren. Deze data wordt verstuurd naar de backend van de vakapplicatie, en deze praat weer tegen de ZRC/ZTC/DRC/... via de APIs die we specifieren. Ons gaat het hier dan om hoe de vakappliactie(backend) tegen de componenten praat.

@joeribekker @MarcelMoerman graag corrigeren als ik het fout heb :-)

**Comment by ArjanKloosterboer** [comment]
> En het punt dat overblijft is hoe we (in Common Ground) de gegevens uit de aanvraag over ZRC, DRC en Objectenregistratie (of hoe we dat ook gaan noemen) gaan verdelen en welke API's daarbij horen.
-jgortmaker

Het lijkt mij dat in eerste instantie de melding,, voordat die verwerkt wordt door een afhandelcomponent, als (informatie)object wordt vastgelegd als ware het een ingekomen (post)stuk. Bij verwerking kan die als (informatie)object aan de zaak gekoppeld worden. 
Nog wel wat dingetjes nader te bepalen. Vastleggen van een melding als object lijkt me zinvol omdat daarmee oa. een overzicht valt te genereren van ingediende meldingen ('is deze overlast wellicht al gemeld'?). Anderzijds is de melding de ontvangen informatie die aanleiding geeft tot de zaak. En die informatie leggen we normaliter vast als informatieobject (alle ontvangen en gecreeerde informatie).

**Comment by ArjanKloosterboer** [comment]
@ehotting, het is mij niet duidelijk wat je met je laatste opmerking ('frozen') bedoelt. Mag er niet meer nagedacht worden over de uitvoering en invulling van de user-story? M.i. moeten we de context van de user-story goed doorgronden, willen we API's ontwikkelen die daadwerkelijk in de praktijk toepasbaar zijn.

**Comment by TCIMEddy** [comment]
Allen, Ik zie mijn mailbox vol lopen met allerlei discussies op github. Even buiten het feit of deze discussies op dit moment zinvol zijn (lees draagt het bij aan sprint 1) zou ik als scrummaster graag zien dat we dit voeren op Slack en niet op Github. Sommige discussies moet je gewoon binnen het team voeren aangezien wij 3 dagen met elkaar hebben doorgebracht en impliciete en expliciete afspraken met elkaar gemaakt hebben over scrum en hoe we met elkaar omgaan. Ik zie nu discussies ontstaan waarbij mensen de boventoon voeren die niet een in het team zitten. Nogmaals we richten ons op nu op sprint 1 en de daarbij behorende user stories (het is al ingewikkeld genoeg). Wanneer ik het verkeerd begrepen heb graag feedback.

**Comment by ArjanKloosterboer** [comment]
@TCIMEddy , verrassende reactie. Ik dacht dat voor Github gekozen was opdat iedereen mee kan doen. En op wie doel je met 'mensen [die] de boventoon voeren die niet een in het team zitten'?

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer dit is dus precies een voorbeeld van een discussie die we niet op GitHub moeten voeren. Maar om antwoord te geven op je vragen:
- Er is niet voor GitHub gekozen zodat iedereen mee kan doen. We willen iedereen inzicht geven wat we aan het doen zijn. Aan het einde van iedere sprint is er een review/demo waarin iedereen zijn of haar feedback kan geven.
- En ik doelde in dit geval inderdaad op jou omdat ik je naam 10 keer onder elkaar in mijn mailbox kreeg. Ik waardeer dat je input wil leveren maar ik moet ook het team beschermen tegen discussies die we, in de 3 dagen vorige week, al hebben gevoerd. Laten we het hierbij op GitHub bij laten. Mocht je nog opmerkingen/vragen etc hebben benader me dan persoonlijk.

**Comment by sergei-maertens** [comment]
Aangeleverde mapping van @MarcelMoerman:

| RGBZ mapping | Veld in huidige app | Verklaring |
| --- | --- | --- |
| `ZAAK/ZaakIdentificatie` | `id` | Uniek volgnummer zaak |
| `STATUSTYPE/Statustype-omschrijving` | `last_status` | Actuele status |
| `OBJECT/Adres binnenland` | `adres` | Adres van constatering |
| `ZAAK/Registratiedatum` | `datetime` | Meldingsdatum |
| `ENKELVOUDIG INFORMATIEOBJECT` | `text` | Toelichting melding |
| `OBJECT` | `waternet_soort_boot` | Betrokken object |
| `OBJECT` | `waternet_redery` | Betrokken object |
| `OBJECT` | `waternet_naam_boot` | Betrokken object |
| **Datum geconstateerde overlast** | `datetime_overlast` | **Datum van constatering** |
| `BETROKKENE > NP/Anon` | `email` | E-mail van melder |
| `BETROKKENE > NP/Anon` | `phone_number` | Telefoonnr van melder |
| `KLANTCONTACT/Kanaal` | `source` | Kanaal van melding |
| `ZAAK-INFORMATIEOBJECT/` | `text_extra` | Toelichting melding |
| `ZAAK-INFORMATIEOBJECT/` | `image` | Beeld bij melding |
| `ZAAKTYPE/` | `main_category` | Hoofdcategorie |
| `ZAAKTYPE/` | `sub_category` | Subcategorie |
| `ZAAKTYPE/` | `ml_cat` | Meldingcategorie |
| ~~`OBJECT/Adres binnenland`~~ | ~~`adres`~~ | ~~Afgeleid adres locatie~~ al eerder vermeld |
| `OBJECT/` | `stadsdeel` | Afgeleid gebied |
| `> OBJECT/` | `coordinates` | Coordinaten locatie melding |
| `ORGANISATORISCHE EENHEID/` | `verantwoordelijk` | Afhandelende organisatorische eenheid |

**Comment by sergei-maertens** [comment]
Aangeleverde testdata, met de 'n.v.t.' velden gestript:

```json
{
      "id": 9966,
      "last_status": "o",
      "adres": "Oosterdok 51, 1011 Amsterdam, Netherlands",
      "datetime": "2018-05-28T09:05:08.732587+02:00",
      "text": "test",
      "waternet_soort_boot": "Nee",
      "waternet_rederij": "Onbekend",
      "waternet_naam_boot": "",
      "datetime_overlast": null,
      "email": "",
      "phone_number": "",
      "source": "Telefoon 14020",
      "text_extra": "",
      "image": null,
      "main_category": "",
      "sub_category": "Geluid",
      "ml_cat": "melding openbare ruimte",
      "stadsdeel": "Centrum",
      "coordinates": "POINT (4.910649523925713 52.37240093589432)",
      "verantwoordelijk": "Waternet"
}
```

**Comment by sergei-maertens** [comment]
@wishalg wat is de reden dat je dit uit in-progress gesleept hebt? Hier wordt namelijk actief aan gewerkt.

**Comment by wishalg** [comment]
Hoi Sergei,

Is per ongeluk verwijderd, kan je het herstellen.

Groet, Wishal

Van: Sergei Maertens [mailto:notifications@github.com]
Verzonden: woensdag 13 juni 2018 10:38
Aan: VNG-Realisatie/gemma-zaken <gemma-zaken@noreply.github.com>
CC: Wishal Gokoel <Wishal.Gokoel@VNG.NL>; Mention <mention@noreply.github.com>
Onderwerp: Re: [VNG-Realisatie/gemma-zaken] Als burger wil ik op de website van de gemeente een anonieme melding van het type overlast op het water kunnen doen (#39)


@wishalg<https://github.com/wishalg> wat is de reden dat je dit uit in-progress gesleept hebt? Hier wordt namelijk actief aan gewerkt.

**Comment by sergei-maertens** [comment]
@wishalg geen probleem - kon zijn dat ik wat gemist had! :)

**Comment by jgortmaker1** [comment]
censuur?

**Comment by sergei-maertens** [comment]
Functionele documentatie-eis geschrapt - wordt een apart user story voor een eerste opzet.
