### ISSUE TITLE
Hoe verhouden zaak en verzoek zich tot elkaar?

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/gemma-zaken#390]
Openstaande vraag uit architectuurdocument.

Beschrijving:
In bovenstaande figuur is de relatie tussen Melding/Aanvraag (Verzoek) en Zaak als een stippellijn getekend. Dit omdat Verzoek niet in het RGBZ voorkomt (zat wel in GFO Zaken) en we dus niet weten hoe Verzoek en Zaak zich tot elkaar verhouden. Essentie van de relatie lijkt te zijn dat een verzoek of melding een op zichzelf staand ‘iets’ is en behandeld wordt als zaak. Één verzoek kan leiden tot meerdere zaken. Meerdere Verzoeken kunnen ook leiden tot één Zaak? Documenten bij een Verzoek worden bij het Verzoek vastgelegd? en later rechtstreeks gerelateerd aan de zaak? Of...

**Comment by joeribekker** [comment]
@jgortmaker1 Welk "bovenstaande figuur", kan je verwijzing toevoegen naar architectuur document?

**Comment by jgortmaker1** [comment]
🖕

**Comment by joeribekker** [comment]
Geen probleem @jgortmaker1 , ik wacht wel.

**Comment by CMasselink** [comment]
@jgortmaker1 : Heb je toevallig al kans gezien je geschreven papiertje te digitaliseren? Dan kan ik daar op reageren.

**Comment by CMasselink** [comment]
Mijn 2 centen over de dit punt: 
Vanuit een dienstverleningsperspectief kan het wenselijk zijn om bij het indienen van een subsidieaanvraag (verzoek) via een E-formulier, direct een zaaknummer aan de klant door te geven. De klant kan dit nummer dan direct gebruiken bij vragen over zijn/haar aanvraag.
Past op zich ook bij het principe dat we ook bij zaakgericht werken, 'van klant tot klant' werken. De zaak begint bij de klant en eindigt met de klant. Verschil tussen verzoek en zaak is er dan eigenlijk niet meer.
Een verzoek kan eventueel tot meerdere zaken leiden, dit zijn dan deelzaken/bijdrage zaken bij de hoofdzaak.

Toegegeven: bovenstaande past in de huidige situatie voornamelijk bij scenario's vanuit suites waarbij e-formulieren aan een zaaksysteem gekoppeld zijn. 
Het idee om een klant bij het indienen van het verzoek direct van het zaaknummer te voorzien, vind ik geen verkeerde.
Indien verzoek en zaak strikt gescheiden blijven, zou je op een dergelijk scenario kunnen uitkomen:
Klant dient E-formulier in ->E-form vraagt zaaknummer (feitelijk een reservering) op bij zrc -> verzoek komt bij taak/vakapplicatie (zac) terecht inclusief gereserveerd zaaknummer -> taakapplicatie maakt zaak aan bij zrc op basis van het gereserveerde nummer. 
Risico: er wordt een zaaknummer naar de klant gecommuniceerd terwijl de zaak feitelijk nog niet gemaakt is. 
Implicatie: een verzoek leidt altijd tot een zaak.

**Comment by TCIMEddy** [comment]
@jgortmaker1 Als dit gereed is pas je dan de status aan?

**Comment by jgortmaker1** [comment]
uiteraard..

**Comment by MarcoKlerks** [comment]
Een verzoek (melding / aanvraag) kan per webformulier, e-mail papieren post, telefonisch, whatsapp, etc. gedaan worden. De gemeente zal het verzoek moeten vastleggen. Het werk is dan echter nog niet klaar! Er zal een reeks samenhangende activiteiten uitgevoerd moeten worden, waarvan de kwaliteit en doorlooptijd bewaakt moet worden. Dit lijkt mij heel standaard zaakgericht werken.

Er zal dus een zaak aangemaakt moeten worden van het juiste zaaktype. Het verzoek dient vervolgens als informatieobject / document toegevoegd te worden aan de zaak; ongeacht de vorm.

Enkele uitdagingen:
- Als het verzoek niet de vorm heeft van een witte rechthoek (gescand papier of digital born document), gaan we er dan alsnog een witte rechthoek van maken (gebruik makend van templates) of slaan we data op in XML o.i.d.?
- Als het verzoek telefonisch is ingediend, slaan we dan een audio-opname op of vult de KCC-medewerker een webformulier in dat vervolgens wordt opgeslagen?

**Comment by jgortmaker1** [comment]
Is op hoofdlijnen uitgewerkt (In visiedocument, zie Google Docs)
Nu aan @ArjanKloosterboer om eea verder (op informatiemodelniveau) uit te werken

**Comment by jgortmaker1** [comment]
verplaatst van organisatie-bord naar sprint-bord

**Comment by jgortmaker1** [comment]
is een vraag over informatiemodellen..

**Comment by jgortmaker1** [comment]
misschien moet het naar een ander bord?

**Comment by adgerrits** [comment]
Ben wel benieuwd met welke uitkomst er doorontwikkeld wordt. Een paar dingen nav de opmerkingen:
- "Één verzoek kan leiden tot meerdere zaken. Meerdere Verzoeken kunnen ook leiden tot één Zaak" kan ik mee leven, maar het hangt daarbij af van de definities van 'verzoek' en 'zaak'. Wil je alle opties open houden (wat ik zo gek niet vind) dan geldt: verzoek 0>-------<0 zaak
- Ja, een klant moet bij indiening van een verzoek meteen een kenmerk krijgen (geen 'zaaknummer'); hoe je dat doet mag je zelf bedenken (in ieder geval niet als dwingende optie het ophalen van een nummer bij een centraal zaaksysteem)
- Een verzoek wordt niet als informatieobject / document 'toegevoegd' aan de zaak maar er wordt een relatie gelegd tussen verzoek en zaak. We beschrijven 'zaak' nog te vaak als doos waar we dingen in doen.
