### ISSUE TITLE
Waar slaan we procesinformatie op?

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/gemma-zaken#391]
Openstaande vraag uit architectuurdocument (deels):

Het is nog onduidelijk waar we in een gegevenslandschap “Procesinformatie” willen opslaan. In bovenstaande figuur is dit – samen met procesdefinitiegegevens - gepositioneerd in de Zaakafhandelcomponent (net als nu in de diverse Taaksystemen). Dit is echter (mogelijk) in strijd met het uitgangspunt in Common ground dat functionaliteit en gegevens van elkaar gescheiden moeten zijn. Procesgegevens zijn immers ook gegevens. De procesdefinitie is in veel gevallen zelfs impliciet (hard gecodeeerde flow tussen schermen); dat valt dan niet eens los te knippen.
Conclusie: hier is sprake van een glijdende schaal. Je wilt liefst alle domeingegevens en zo veel mogelijk procesgegevens uit de applicaties halen en via een gestandaardiseerde APi ontsluiten. We moeten echter wel oppassen dat we hier te ver in willen gaan en het paard daarmee achter de wagen spannen. In de praktijk zal dit voor veel bestaande taaksystemen een groeipad worden..

**Comment by sergei-maertens** [comment]
Alvast even een kanttekening: het is niet omdat er in het woord 'gegevens' staat, dat dit ook even zinvolle gegevens zijn als de gegevens vereist voor zaakgericht werken.

Ik denk dat het inrichten van het proces (en dus daarbij de procesgegevens) net de kracht is van leveranciers. Deze procesgegevens zijn in principe niet nodig bij de zaak in context van zaakgericht werken, een KCC medewerker bijvoorbeeld heeft hier niets aan.

De achterliggende API calls zijn ook hetzelfde, ongeacht hoe het proces eruit ziet. Procesgegevens zie ik dan meer als 'configuratie' van een applicatie (wat we nu ook hebben in settings files bijvoorbeeld).

**Comment by jgortmaker1** [comment]
mag in review

**Comment by jgortmaker1** [comment]
mag gereviewed worden; heb enkele willekeurige reviewers aangeduid..

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat de precieze procesinrichting, of dat nu met workflow of met case management wordt gedaan, het speelveld van leveranciers is. Daarmee zou ik ook  de opslag van procesdefinities en -gegevens overlaten aan de zaakafhandelcomponenten.

**Comment by Hugo-ter-Doest** [comment]
mee eens!

**Comment by ehotting** [comment]
Deze vraag is beantwoord in visiedoc - hoeft niet in meerdere US getrackt te worden.
