### ISSUE TITLE
Welke bakjes onderkennen we?

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/gemma-zaken#395]
Vraag uit architectuurdocument.

Beschrijving:
In de uitwerking hierboven hebben we al enkele registraties (‘bakjes’) naast de ZRC onderscheiden. Een aparte registratie met besluiten, een aparte registratie voor documenten (bestaat nu vaak al), een aparte registratie voor klanten en klantcontacten,… Dit is echter slechts een eerste aanzet en nog niet volledig uitgewerkt. Willen we voor iedere “object” een aparte registratie? Hoe vertalen we de objecten uit het RGBZ naar registraties in een gegevenslandschap en hoe relateren we deze aan elkaar? Met het informatiemodel laten we de implementatie nadrukkelijk vrij. In een gegevenslandschap is het wenselijk om dit verder uit te werken in een gegevensmodel. En wellicht ook met een concreet voorbeeld om dit concept aan iedereen goed duidelijk te maken.

===
We hebben al een BRC en een ORC. Zijn er nog meer objecten die een aparte registratie verdienen?

**Comment by jgortmaker1** [comment]
@sergei-maertens hoe hebben we in de reeds ontwikkelde API's "Klant"/Initiator en "Medewerker/Behandelaar" opgelost?

**Comment by sergei-maertens** [comment]
@jgortmaker1 we hebben betrokkenen (via de `Rol` relatie) waarbij de `rolomschrijving` opgegeven wordt (zie https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/rol_create). De mogelijke waardes daarbij zijn:

- `Adviseur`
- `Behandelaar`
- `Belanghebbende`
- `Beslisser`
- `Initiator`
- `Klantcontacter`
- `Zaakcoördinator`
- `Mede-initiator`

**Comment by jgortmaker1** [comment]
vandaag besproken in het overleg. @ArjanKloosterboer werkt uit en doet een voorstel

**Comment by joeribekker** [comment]
Even snel opgeschreven uit overleg

- Organisatie en Medewerker registraties
- Bedrijven en Instelleingen registraties
- NPS nog te benoemen als klanten
- KlantContacten regsitraties

 Betrokkene wordt gesplitst. Betrokkene splitsen in initiator en belanghebbende EN behandelaar en advisieur en beslisser (inter vs externe rollen)

**Comment by TCIMEddy** [comment]
@jgortmaker1 Kun je hiermee je architectendocument updaten of zijn er m.b.t. onderwerp nog openstaande zaken?

**Comment by ArjanKloosterboer** [comment]
Het opsplitsen van het RGBZ heb ik uitgewerkt en aan de Expertgroep Informatiemodellen voorgelegd, zie [hier (bladzij 2-3)](https://www.gemmaonline.nl/images/gemmaonline/2/29/EgIM_20180927_ag_4_-_Aanpassingen_RGBZ.pdf). Komt donderdag 27-9 in bespreking.

**Comment by joeribekker** [comment]
> [...] opgevraagd m.b.v. REST/JASON-api’s.

😭 😉

**Comment by TCIMEddy** [comment]
@jgortmaker1 snap ik maar kan ik deze dan sluiten??

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Deze algemene vraag/behoefte hebben we denk ik beantwoord. Moet deze open blijven? (ook al weet ik dat er nog veel bakjesdiscussies komen)

**Comment by jgortmaker1** [comment]
architectuurdocument bijgewerkt. Zie google docs.

Mag van mij in review

=======
Samenvatting:
Zaaktyperegistratie (nu ZTC)(Zaaktype, Statustypen, Resultaattypen,..)
Documentenregistratie (nu DRC) (documenten cq. informatieobjecten)
Kernregistratie Klanten (Burgers) (voor initiators, belanghebbenden, gemachtigden e.d.). Deze registratie verwijst vor persoonsgegevens nar de BRP en bevat enkel de bijkomende informatie, bijvoorbeeld contactvoorkeuren. 
Kernregistratie Bedrijven en Instellingen (idem, maar dan voor bedrijven en instellingen en het handelsregister)
Kernregistratie Organisatie en medewerkers (o.a. voor behandelaars, adviseurs, afdelingen, rollen en bevoegdheden)
Kernregistratie Verzoeken (verzoeken met verwijzingen naar alle bij een verzoek horende gegevens)
Registratie Klantcontacten
Kernregistratie Besluiten (besluiten)
Domein/objectregistraties (domein/objectgegevens; meerdere registraties: één per domein/proces, bijvoorbeeld voor meldingen of subsidies)
Basisregistraties (personen, bedrijven, panden, terreinen, percelen e.d.)
Evt. andere kernregistraties (Zaakobjecten die nog niet genoemd zijn, maar wel behoren tot kerngegevens (meervoudig gebruikt))
En natuurlijk, last-but-not least de kernregistratie Zaken (nu ZRC)

**Comment by sergei-maertens** [comment]
@TCIMEddy wie moet dit weer naar Markdown omzetten?

**Comment by TCIMEddy** [comment]
@sergei-maertens ik wil het wel in md zetten hoor

**Comment by TCIMEddy** [comment]
@sergei-maertens zal ik doen

**Comment by TCIMEddy** [comment]
@jgortmaker1 kan ik jouw architectendocument op GitHub zetten? lees als tussenversie. Mensen mogen commentaar blijven geven maar dan hebben we tussenstand tot nu toe op GitHub staan.

**Comment by ArjanKloosterboer** [comment]
Een paar opmerkingen over de door Jeffrey onderscheiden registraties. 
Het lijkt er op dat we overal meervoud hanteren. Dan wordt het Zaaktype**n**registratie. 
Wat is de reden om het begrip 'kern' in de naam te hanteren? Is dat niet meer een eigenschap van een registratie? Lang niet alle dergelijke eigenschappen komen nu in namen terug. Dus niet zo consequent. En ook niet verstandig. Bovendien, sommige registraties, zoals de Zaaktypenregistratie en de Documentenregistratie, zijn ook kernregistraties. Maar dat staat dan weer niet in de naam. Dus dan wordt het twijfelachtig. Voorstel: laat 'kern' uit de naam weg. 
Wat is de reden om klanten en contacten niet in één registratie te combineren? Kijkend naar bijvoorbeeld een CRM dan zit daar beide in. Voorstel: Klanten- en contacten-registratie. Mag ook Klantenregistratie waar dan o.a. ook de contacten inzitten. Is lekker kort. 
De (kern)registratie Klanten verwijst voor persoonsgegevens naar de BRP, staat er. Waarom voor niet-natuurlijke personen niet naar het HR? Ook bedrijven en instellingen kunnen klanten zijn!
Waarom een (kern)registratie Bedrijven en instellingen? Ook dat zijn klanten. En de basisgegevens ervan staan in het HR. Je onderscheid toch ook geen (kern)registratie Personen? 
Kernregistratie Organisatie en medewerkers: maken medewerkers geen deel uit van de organisatie, dat die apart genoemd worden? Voorstel: Registratie Organisatie.

**Comment by ArjanKloosterboer** [comment]
> ... een "Kernregistratie" is dus vooral bijkomende informatie zoals de contactvoorkeuren, en "Basisregistratie" is zeg maar stamgegevens?

@joeribekker Uit het hoofd, een basisregistratie is een landelijke, bij wet vastgelegde, registratie van gegevens met een gewaarborgde kwaliteit die verplicht gebruikt moeten worden bij de uitvoering van taken door overheidsorganisaties.  
Een kernregistratie is een door de desbetreffende organisatie ingestelde registratie van substantieel meervoudig gebruikte gegevens waarvan de kwaliteit gewaarborgd is en die verplicht gebruikt wordt bij de uitvoering van haar taken door die organisatie.

**Comment by TCIMEddy** [comment]
@jgortmaker1 hou jij de comments in de gaten en verwerk jij ze in google doc. Als het voldoende is afgedekt wil je deze dan close

**Comment by jgortmaker1** [comment]
kern overal verwijderd; meervoud toegepast
registratie klanten (burgers) , registratie klantcontacten en registratie bedrijven en instellingen geconsolideerd tot 1 "klanten- en contactenregistratie ". daar valt nog wel wat op af te dingen (past minder op de huidige GEMMA 2). Maar op de vorige versie ook. 

Kernregistratie bedrijven en instellingen en kernregistratie medewerkers kwamen uit GEMMA 2.. Nieuwe nama en afbakening is beter. Wel organisatie EN medewerkersregistratie gehouden om het verschil niet te groot te laten zijn..

**Comment by jgortmaker1** [comment]
issue mag voor mij nu op close.
