### ISSUE TITLE
Gezamenlijk akkoord op definitie van functionele documentatie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#399]
# Impediment

Er is een PR geweest die destijds is goedgekeurd door Michiel, maar we willen een breder gedragen definitie zodat er gewerkt wordt aan functionele documentatie waar iedereen achter staat.

Het team moet het eens zijn met wat er in de functionele documentatie moet komen. Sergei en Joeri maken dan een voorbeeld die Jeffrey en Henri verder uitwerken.

Leesbare versie: https://ref.tst.vng.cloud/introduction/documentatie/
Document in Github: [docs/content/introduction/documentatie.md](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/content/introduction/documentatie.md)
Pull Request destijds: [#284](https://github.com/VNG-Realisatie/gemma-zaken/pull/284)

**Comment by ArjanKloosterboer** [comment]
Discussie liep en loopt in #188

**Comment by joeribekker** [comment]
Volgens mij zijn we het in afgelopen overleg eens geworden, en overige punten lopen via #188.
