### ISSUE TITLE
Als persoon of vertegenwoordiger van een persoon met een of meer zaken bij de/ een overheid  wil ik direct genotificeerd worden over iedere relevante ontwikkeling binnen mijn zaak

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#4]
Zodat ik geen enkele ontwikkeling binnen een zaak over het hoofd zie

En kennis kan nemen van de laatste ontwikkeling(en) binnen mijn zaak

En tijdig de input kan leveren waar een behandelaar om vraagt

En tijdig kan reageren of een vraag kan stellen.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest graag prio

**Comment by Hugo-ter-Doest** [comment]
https://github.com/VNG-Realisatie/Squad-Architectuur-Samen-Organiseren/issues/153

**Comment by TCIMEddy** [comment]
Idd eerst een uitspraak van architectuur (ter info @jeffreygortmaker1 )

**Comment by Hugo-ter-Doest** [comment]
Vertegenwoordiging is niet relevant voor ZGW API's.

Daarna is het dezelfde user story als #17
