### ISSUE TITLE
Als burger wil ik weten wat de gemeente met mijn melding gaat doen...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#40]
...zodat ik weet of mijn melding naar wens wordt opgepakt.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] **_Userstory is ingevuld op template architectuurschets_**
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Proces**

In Amsterdam is een melding die binnenkomt via het signalen platform anoniem. Als een melder op de hoogte wil worden gehouden is er de mogelijkheid om e-mailadres of telefoonnummer mee te geven in de melding. Op deze manier kan er contact kan worden opgenomen voor toelichting en kan er terugkoppeling worden gegeven over de voortgang.

Een melding wordt nooit geregistreerd op persoon.
Er worden vooralsnog geen publieke lijsten / kaarten gepubliceerd met meldingen en de status.

Dit is anders in de situatie waarbij meldingen binnenkomen via een platform als "verbeter de buurt", die de API van signalen gebruikt, hier wordt wel openbare feedback gegeven op de meldingen en afhandeling.

**Architectuur**

De globale architectuur voor de usecase is beschreven in de Amsterdamse oplossings-schets.
Deze is hier te vinden >> [Documentatie](https://github.com/VNG-Realisatie/blob/master/docs/processen/amsterdam-water.md)

Filters zijn op twee ingangen te gebruiken voor selecties, 

### Selecties op ZRC API
| Attribuut | waarde | OPERATIE |
| :--- | :--- | :--- |
| Zaaktype | melding openbare ruimte | filter |
| Datum, tijd melding | jaar, maand, week, dag, uur | filter, range |
| Datum, tijd gereed | jaar, maand. week. dag, uur | filter, range |
| Status | status typen lijst | filter |

### Selecties op MOR API
| Attribuut | waarde | OPERATIE |
| :--- | :--- | :--- |
| Datum, tijd melding | jaar, maand, week, dag, uur | filter, range |
| Datum, tijd gereed | jaar, maand. week. dag, uur | filter, range |
| Melding ID | meldingen lijst | numeriek, range |
| Sub Categorie | sub-categorie lijst | filter |
| Locatie | punt, openbare ruimte, huisnummer, huisletter, huisnummer_toevoeging | filter |
| Locatie | geometrie | filter |

**Comment by jgortmaker1** [comment]
welke ZDS service is hiervoor nodig?

**Comment by TCIMEddy** [comment]
@MarcelMoerman Kun je nog iets specifieker zijn wat je bedoelt. Wat moet de burger zien of lezen?

**Comment by sergei-maertens** [comment]
@jgortmaker1  Ik begreep dat via de app/website van Amsterdam de meldingen publiek inzichtelijk zouden zijn. Dit betekent dus dat er minimaal een nood is aan het opvragen van zaken van een bepaald zaaktype + in een dieper niveau opvragen van zaaktypedetailinformatie.

Enige verduidelijking van wat precies moet getoond worden zal nodig zijn inderdaad.

**Comment by jgortmaker1** [comment]
WAT de gemeente gaat doen is iets anders dan een informatie over een zaak weergeven. Mijn stelling is dus dat dit niet met een zaken-api kan/moet worden opgelost.

Is de rederij gebeld? Is er handhaving opgestart? Is de politie onderweg? Is er gecontroleerd, maar is de boot niet aangetroffen? Niet alles mag/wil je als gemeente communiceren. Maar dit zijn allemaal inhoudelijke berichten. Geen zaakstatussen.

Melding in behandeling en melding afgehandeld krijg je in het andere geval..en de grap is dat de melding al is afgehandeld nog voordat de handhaver op zijn fiets is gesprongen en de melder er dus iets van merkt..

**Comment by EdwinCoster** [comment]
@MarcelMoerman : Specifieker maken via welk kanaal, welke informatie en hoe (vragen uit de groep). Tip: wees zo specifiek mogelijk (Eddy).

**Comment by ehotting** [comment]
Dit is volgens mij de link naar Mijn Overheid e.d. welke nu volledig via SOAP/XML verloopt. Moet wel gaan werken. Prio H maar wellicht voor sprint 6

**Comment by sergei-maertens** [comment]
Als ik het me goed herinner, dan ging dit ook voor de anonieme meldingen op, wat op API niveau neerkomt op 'ik moet een lijst van zaken kunnen opvragen met de juiste filters (zaaktype, geo)'. Dus nog even formeel opnemen in de sprint zodat we kunnen checken dat alle filter parameters beschikbaar zijn.

@MarcelMoerman kan jij aanleveren op welke gegevens gefilterd moet worden om een melding-zaak van andere zaken te kunnen onderscheiden?

Ik vermoed dat hierbij ook het verhaal van paginering kan gaan spelen overigens...

**Comment by jgortmaker1** [comment]
zie bovenstaande opmerkingen. verduidelijking nodig..
not ready

**Comment by MarcelMoerman** [comment]
Eerste toelichting toegevoegd. 
@sergei-maertens wat bedoel je met filtering? Ik stel mij voor dat je op Zaaktype een filter hebt, een buurt, wijk filter, een tijdstip / sub_type filter. We hebben naast de ZRC natuurlijk ook de Signalen_API waar informatie uit kan worden gehaald.

**Comment by ehotting** [comment]
Maandag 15 oktober bespreken met @MarcelMoerman

**Comment by TCIMEddy** [comment]
@MarcelMoerman wat zit er in zaken-api en wat in meldingen api?

**Comment by ArjanKloosterboer** [comment]
@MarcelMoerman, v.w.b. de bovenvermelde attributen cq. RGBZ-mapping, ongeacht bovenstaande discussie, het volgende over de ZRC-api:
- 'Zaaktype' is de relatie in het RGBZ naar het objecttype Zaaktype in het ImZTC. Daarvan heb je minimaal de Zaaktype-omschrijving nodig. 
- 'Datum, tijd melding' betreft in het RGBZ de Startdatum van Zaak.
- 'Datum, tijd gereed' is in het RGBZ de Einddatum van Zaak.
- 'Status' is in het RGBZ de relatie naar het objecttype Status met daarvan de attribuutsoort 'Indicatie laatst gezette status' en de relatie daarvan naar het objecttype Statustype in het ImZTC waarvan je minimaal de Statustype-omschrijving nodig hebt.  
De locatie van de melding, die bij de MOR-api staat, kan ook mbv het RGBZ ingevuld worden: Zaakgeometrie van het objecttype Zaak.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Kun jij ook even door de opmerkingen bij de issues lopen. Volgen mij kan dit al (en moet de rest in de TSA

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest deze komt vanuit water/mor/amsterdam nog relevant?

**Comment by TCIMEddy** [comment]
In overleg met indiener op close
