### ISSUE TITLE
RGBZ Mapping US #302

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#402]
Mapping van velden behorend bij user story #302 

Voor Besluit zie #362, voor afsluiten zaak zie #351 

### Stappen:
Stap 1. Resultaattype bepalen
Stap 2. ZTC bevragen voor benodigde attributen (Zaaktype, Besluittype, Informatieobjecttype)
Stap 3. Informatieobject toevoegen
Stap 4. ObjectInformatieobject toevoegen
Stap 5. Besluit Toevoegen
Stap 6. BesluitInformatieobject toevoegen
Stap 7. Zaak bijwerken met einddatum, archiefnominatie, -status en -actiedatum en startdatum bewaartermijn  _inclusief archiveringskenmerken en resultaat Afgebroken_.
Stap 8. Status 'Afgehandeld' toevoegen.

### 1. Resultaattypen ophalen uit de ZTC
De benodigde attributen van het Resultaattype ophalen vanuit een lijst

Request

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`Catalogus . Domein` | ` ` | AN5 | Een afkorting waarmee wordt aangegeven voor welk domein in een CATALOGUS ZAAKTYPEn zijn uitgewerkt. 
`Catalogus . RSIN` | ` ` | AN9 | Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON die de eigenaar is van een CATALOGUS. 
`ZAAKTYPE . ZaakIdentificatie` | ` ` | UUID  | Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt. 

Answer

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`RESULTAATTYPE . Resultaattypeomschrijving` | ` ` | AN20 | Omschrijving van de aard van resultaten van het RESULTAATTYPE. 
`RESULTAATTYPE . Procesobjectaard` | ` ` | AN200 | Omschrijving van het object, subject of gebeurtenis waarop, vanuit archiveringsoptiek, het resultaattype bij zaken van dit type betrekking heeft. 
`RESULTAATTYPE . Indicatie specifiek` | ` ` | INDIC | Aanduiding of het, vanuit archiveringsoptiek, een resultaattype betreft dat specifiek is voor een bepaalde procesobjectaard. _Waarde: 'False'_.  
`RESULTAATTYPE . Selectielijstklasse` | ` ` | AN20 | Verwijzing naar de, voor het archiefregime bij het RESULTAATTYPE relevante, categorie in de Selectielijst Archiefbescheiden van de voor het ZAAKTYPE verantwoordelijke overheidsorganisatie. 
`RESULTAATTYPE . Procestermijn` | ` ` | N3 | De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie. 
`RESULTAATTYPE . Archiefnominatie` | ` ` | archiefnominatie  |  Aanduiding die aangeeft of ZAAKen met een resultaat van dit RESULTAATTYPE blijvend moeten worden bewaard of (op termijn) moeten worden vernietigd. 
`RESULTAATTYPE . Archiefactietermijn` | ` ` | N4  | De termijn, na het vervallen van het bedrijfsvoeringsbelang, waarna het zaakdossier (de ZAAK met alle bijbehorende INFORMATIEOBJECTen) van een ZAAK met een resultaat van dit RESULTAATTYPE vernietigd of overgebracht (naar een archiefbewaarplaats) moet worden. 
`RESULTAATTYPE . Brondatum archiefprocedure` | `OBJECT` |  | Specificatie voor het bepalen van de brondatum voor de start van de Archiefactietermijn van het zaakdossier. 

Brondatum archiefprocedure bestaat uit:

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | --
`Afleidingswijze` | ` ` | afleidingswijze Brondatum Archiefprocedure | Wijze van bepalen van de brondatum. _Waarde: 'Afgehandeld'_. 
`Registratie` | ` ` | AN80 | De naam van de registratie waarvan het procesobject deel uit maakt. 
`Objecttype` | ` ` | AN80 | Het soort object in de registratie dat het procesobject representeert. 
`Datumkenmerk` | ` ` | AN80 | Naam van de attribuutsoort van het procesobject dat bepalend is voor het einde van de procestermijn. 
`Einddatum bekend` | ` ` | INDIC | Indicatie dat de einddatum van het procesobject gedurende de uitvoering van de zaak bekend moet worden. 

Daar moet een Resultaattype in voorkomen met een Resultaattypeomschrijving 'Afgewezen' waarbij Procesobjectaard niet is ingevuld (het is een generiek Resultaattype). Als dit Resultaattype niet bestaat dan gaat er iets fout.

Archiefnominatie (waarde: 'Vernietigen') en Archiefactietermijn (waarde: 1) zijn nodig voor het afsluiten van de zaak.

Het Resultaattype 'Afgewezen' leidt tot één bijbehorend Besluittype 'Kennisgeving afwijzing verzoek' wat wordt vastgelegd in één bijbehorende Informatieobjecttype 'Kennisgeving afwijzing inzageverzoek persoonsgegevens'. Dit Informatieobjecttype is dus een verplicht Zaak-Informatieobjecttype van het Resultaattype.

Het Informatieobject zelf wordt aangemaakt door de Behandelaar op basis van een sjabloon waarvan de URL is vastgelegd in `INFORMATIEOBJECTTYPE . Model`

### 2. Bevragen ZTC (overige attributen van Zaaktype, Besluittype en Informatieobjecttype en ZaakInformatieobjecttype)

Request ZTC

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`Catalogus . Domein` | ` ` | AN5 | Een afkorting waarmee wordt aangegeven voor welk domein in een CATALOGUS ZAAKTYPEn zijn uitgewerkt
`Catalogus . RSIN` | ` ` | AN9 | Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON die de eigenaar is van een CATALOGUS.
`ZAAKTYPE . ZaakIdentificatie` | ` ` | UUID  | Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt.

Answer ZTC

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`ZAAKTYPE . Selectielijst procestype` | ` ` | OBJECT | Een vanuit archiveringsoptiek onderkende groep processen met dezelfde kenmerken.
`BESLUITTYPE . Besluittypeomschrijving` | ` ` | AN80 | Omschrijving van de aard van BESLUITen van het BESLUITTYPE. 
`BESLUITTYPE . Reactietermijn` | ` ` | N3 | Het aantal dagen, gerekend vanaf de verzend- of publicatiedatum, dat BESLUITen van dit BESLUITTYPE gepubliceerd moeten blijven. _Waarde: '42'._
`BESLUITTYPE . Informatieobjecttype` | ` ` | Informatieobjecttype | Het INFORMATIEOBJECTTYPE van informatieobjecten waarin besluiten van dit BESLUITTYPE worden vastgelegd. _Waarde: URL naar het Informatieobjectype: 'Kennisgeving afwijzing verzoek'_
`INFORMATIEOBJECTTYPE . Informatieobjecttype-omschrijving` | ` ` | AN80 | Omschrijving van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE.
`INFORMATIEOBJECTTYPE . Model` | ` ` | AN80 | De URL naar het model / sjabloon dat wordt gebruikt voor de creatie van informatieobjecten van dit INFORMATIEOBJECTTYPE.
`ZAAKINFORMATIE OBJECTTYPE . Richting` | ` ` | richting | Aanduiding van de richting van uitwisseling van informatieobjecten van het gerelateerde INFORMATIEOBJECTTYPE bij zaken van het gerelateerde ZAAKTYPE, gezien vanuit de zaakbehandelende organisatie. _Waarde: Uitgaand_

Selectielijst procestype bestaat uit:

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | --
`Naam` | ` ` | AN40 | Benaming van het selectielijst-procestype. _Waarde: 'Verzoeken behandelen'_.
`Nummer` | ` ` | N2 | Nummer van het selectielijst-procestype. _Waarde: 6_.
`Procesobjecttype` | ` ` | AN80 | Het onderwerp waarop het selectielijst-procestype betrekking heeft. _Waarde: Het handelen van het orgaan op basis van het verzoek_.
`Selectielijst-omschrijving` | ` ` | AN80 | Benaming en versie-aanduiding van de selectielijst archiefbescheiden waaraan het procestype is ontleend. _Waarde: Selectielijst gemeenten en intergemeentelijke organen 2017_.

### 3. Informatieobject toevoegen
Zodra het Informatieobject klaar is kan dit toegevoegd worden in de DRC. 

Request DRC
 
 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`ENKELVOUDIGINFORMATIEOBJECT. Formaat` | `Formaat` | AN255 | De code voor de wijze waarop de inhoud van het   ENKELVOUDIG INFORMATIEOBJECT is vastgelegd in een computerbestand. 
`ENKELVOUDIGINFORMATIEOBJECT. Taal` | `Taal` | enum Taal | Een taal van   de intellectuele inhoud van het ENKELVOUDIG INFORMATIEOBJECT. De waardes   komen uit ISO 639-2/B 
`ENKELVOUDIGINFORMATIEOBJECT. Inhoud` | `Inhoud` | AN | Datgene wat in een ENKELVOUDIG INFORMATIEOBJECT wordt meegedeeld. 
`ENKELVOUDIGINFORMATIEOBJECT. Link` | `Link` | AN200 | De URL waarmee de inhoud van het INFORMATIEOBJECT op te vragen is. 
`ENKELVOUDIGINFORMATIEOBJECT. Informatieobject` |   | `Informatieobject` | Geheel van gegevens met een eigen identiteit ongeacht zijn vorm, met de bijbehorende metadata ontvangen of opgemaakt door   een natuurlijke en/of rechtspersoon bij de uitvoering van taken. 
`(ENKELVOUDIG)INFORMATIEOBJECT. Informatieobjectidentificatie` | UUID | AN40 | Een binnen een gegeven   context ondubbelzinnige referentie naar het INFORMATIEOBJECT. 
`(ENKELVOUDIG)INFORMATIEOBJECT. Bronorganisatie` | `Organisatie` | AN9 | Het RSIN van de Niet-natuurlijk persoon zijnde de   organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en   als eerste in een samenwerkingsketen heeft vastgelegd. 
`(ENKELVOUDIG)INFORMATIEOBJECT. Creatiedatum` | `Creatiedatum` | DATUM | Een datum of een   gebeurtenis in de levenscyclus van het INFORMATIEOBJECT. 
`(ENKELVOUDIG)INFORMATIEOBJECT. Titel` | `Titel` | AN200 | De naam waaronder het INFORMATIEOBJECT formeel bekend is. 
`(ENKELVOUDIG)INFORMATIEOBJECT. Auteur` | `Auteur` | AN200 | De persoon of organisatie die in de eerste plaats verantwoordelijk is voor het creëren van de inhoud van het INFORMATIEOBJECT. 
`(ENKELVOUDIG)INFORMATIEOBJECT. Beschrijving` | `Beschrijving` | AN1000 | Een generieke   beschrijving van de inhoud van het INFORMATIEOBJECT. 
`(ENKELVOUDIG)INFORMATIEOBJECT. Informatieobjecttype` | `Type` | AN200 | URL naar de  Informatieobjecttype 'Kennisgeving afwijzing verzoek' in het ZTC. 

(ENKELVOUDIG)INFORMATIEOBJECT is een verwijzing naar het het feit dat INFORMATIEOBJECT en ENKELVOUDIGINFORMATIEOBJECT in de API-specificatie zijn samengevoegd.

Answer DRC

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`(ENKELVOUDIG)INFORMATIEOBJECT. Informatieobjectidentificatie` | `InformatieobjectID` |  AN40 | Uniek volgnummer informatieobject 

### 4. Informatieobject koppelen aan de zaak

Request DRC

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`OBJECTINFORMATIEOBJECT. Zaak` | `Zaak` | AN200 | URL naar de zaak in de ZRC 
`OBJECTINFORMATIEOBJECT. Informatieobject` |   | AN200 | URL naar het informatieobject 

Answer DRC

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`OBJECTINFORMATIEOBJECT. Zaak` | `Zaak` | AN200 | URL naar de zaak in de ZRC 
`OBJECTINFORMATIEOBJECT. Informatieobject` | `Informatieobject`  | AN200 | URL naar het informatieobject 

### 5. Besluit toevoegen
Vervolgens gaan we het BESLUIT toevoegen

Request BRC

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`BESLUIT.Identificatie` | `BesluitID` | UUID | Uniek ID van het Besluit 
`BESLUIT.VerantwoordelijkeOrganisatie` | `Organisatie` | AN9 | Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die het besluit heeft vastgesteld. 
`BESLUIT.Datum` | `Datum` | DATUM | De beslisdatum (AWB) van het besluit. _Waarde: huidige datum_
`BESLUIT.Besluittoelichting` | `Toelichting` | AN1000 | Toelichting bij het  besluit. 
`BESLUIT.Bestuursorgaan` | `Bestuursorgaan` | AN50 | Een orgaan van een rechtspersoon krachtens   publiekrecht ingesteld of een persoon of college, met enig openbaar gezag bekleed onder wiens verantwoordelijkheid het besluit vastgesteld is. 
`BESLUIT.Ingangsdatum` | `Ingangsdatum` | DATUM | Ingangsdatum van de werkingsperiode van het besluit. _Waarde: huidige datum._
`BESLUIT.Verzenddatum` | `Verzenddatum` | DATUM | Datum waarop het besluit verzonden is. _Waarde:   huidige datum._
`BESLUIT.UiterlijkeReactiedatum` | `Uiterlijke reactiedatum` | DATUM | De datum tot wanneer   verweer tegen het besluit mogelijk is. _Waarde: huidige datum + 42 dagen_
`BESLUIT.Besluittype` | `Type` | AN200 | URL naar het Besluittype in de ZTC.
`BESLUIT.Zaak` | `Zaak` | AN200 | URL naar de zaak in de ZRC.

Answer BRC

| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| -- | -- | -- | -- |
|`BESLUIT.Identificatie` | `BesluitID` |   | Uniek ID van het besluit |

### 6. Besluit aan informatieobject koppelen

Request BRC 

| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| -- | -- | -- | -- |
|`BESLUITINFORMATIEOBJECT. Besluit` | `Besluit` | AN200 | URL naar het besluit in de BR(zonder C) |
|`BESLUITINFORMATIEOBJECT. Informatieobject` | `Informatieobject` | AN200 | URL naar het informatieobject in de DRC |

Answer BRC

| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| -- | -- | -- | -- |
|`OBJECTINFORMATIEOBJECT. Zaak` | `Besluit` | AN200 | URL naar het besluit in de BR(zonder C)|
|`OBJECTINFORMATIEOBJECT. Informatieobject` | `Informatieobject` | AN200 | URL naar het informatieobject in de DRC |

### Request ZRC (Zaak Update)
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| -- | -- | -- | -- |
|`ZAAK.Einddatum` |   | DATUM | De datum waarop de uitvoering van de zaak afgerond is. |
|`ZAAK.Archiefnominatie` |   | enum Archiefnominatie | Aanduiding of het zaakdossier blijvend bewaard of na een bepaalde termijn vernietigd moet worden. _Waarde: 'Vernietigen'_ |
|`ZAAK.Archiefstatus` |   | enum Archiefstatus | De fase waarin het zaakdossier zich qua archivering bevindt. _Waarde: 'Gearchiveerd'._ |
|`ZAAK.Archiefactiedatum` |   | DATUM | De datum waarop het gearchiveerde zaakdossier vernietigd moet worden dan wel overgebracht moet worden naar een archiefbewaarplaats. _Waarde: Huidige datum + 1 jaar_ |
|`ZAAK.StartdatumBewaartermijn` |   | DATUM | De datum die de start markeert van de termijn waarop het zaakdossier vernietigd moet worden. _Waarde: Huidige datum_ |
|`ZAAK.Selectielijstklasse.` |   | AN80 | Benaming en versie-aanduiding van de selectielijst archiefbescheiden die geldend is voor (archivering van) de zaak. _Waarde: 'Vernietigen'_ |
|`ZAAK.Selectielijstklasse. Selectielijst-omschrijving` |   | AN80 | Benaming en versie-aanduiding van de selectielijst archiefbescheiden die geldend is voor (archivering van) de zaak. _Waarde: 'Selectielijst gemeenten en intergemeentelijke organen 2017'_ |
|`ZAAK.Selectielijstklasse. Nummer klasse` |   | AN20 | Benaming en versie-aanduiding van de selectielijst archiefbescheiden die geldend is voor (archivering van) de zaak. _Waarde: '6.2'_ |
|`ZAAK.Procesobjectaard` |   | AN200 | Omschrijving van het object, subject of gebeurtenis waarop, vanuit archiveringsoptiek, de zaak betrekking heeft . _Waarde: ''_ |

### Answer ZRC 

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`ZAAKTYPE.Besluittype` |   | Besluittype | De datum waarop de uitvoering van de zaak afgerond is. 
`ZAAK.Archiefnominatie` |   | enum Archiefnominatie | Aanduiding of het zaakdossier blijvend bewaard of na een bepaalde termijn vernietigd moet worden. Waarde: 'Vernietigen' 
`ZAAK.Archiefstatus` |   | enum Archiefstatus | De fase waarin het zaakdossier zich qua archivering bevindt. Waarde: 'Gearchiveerd'. 
`ZAAK.Archiefactiedatum` |   | DATUM | De datum waarop het gearchiveerde zaakdossier vernietigd moet worden dan wel overgebracht moet worden naar een archiefbewaarplaats. Waarde: Huidige datum + 1 jaar 
`ZAAK.StartdatumBewaartermijn` |   | DATUM | De datum die de start markeert van de termijn waarop het zaakdossier vernietigd moet worden. Waarde: Huidige datum 
`` | `` |  | 

### Request ZTC (ophalen Zaaktypen)
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Catalogus.Domein` | ` ` | N5 | Een afkorting waarmee wordt aangegeven voor welk domein in een CATALOGUS ZAAKTYPEn zijn uitgewerkt. |
| `Catalogus.RSIN` | ` ` | N9 | Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON die de eigenaar is van een CATALOGUS. |
| `Zaaktype.ZaaktypeIdentificatie` | `ZaaktypeID` | UUID | Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt. |

Wat resulteert in een lijst met Statustypen.

### Answer ZTC
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Statustype. StatustypeVolgnummer` | `Volgnummer` | N4 | Een volgnummer voor statussen van het STATUSTYPE binnen een zaak. |
| `Statustype. Statustypeomschrijving` | `Status` | AN80 | Een korte, voor de initiator van de zaak relevante, omschrijving van de aard van de STATUS van zaken van een ZAAKTYPE. |
| ` ` | ` ` | - | - |

En het gezochte Statustype: '9' 'Afgehandeld'. Dit is tevens het hoogste volgnummer.
Deze toevoegen aan de zaak en actuele status maken.

### Request ZRC
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Status.datumStatusgezet` | `Datum status` | DATUM | De datum waarop de ZAAK de status heeft verkregen. |
| `Status.statusToelichting` | `Toelichting` | AN1000 | Een, voor de initiator van de zaak relevante, toelichting op de status van een zaak. |
| `Status.indicatieLaatstGezetteStatus` | ` ` | INDIC | Aanduiding of het de laatst bekende bereikte status betreft. _Waarde: True_. |
| `Status.Zaak` | `Zaak` | AN200 | URL naar de zaak |
| `Status.StatusType` | `Statustype` | AN200 | Aanduiding van de aard van de status. URL naar Statustype: 'Afgehandeld'  |
| `Status.Rol` | `Rol` | AN200 | URL naar de Betrokkene die in een Rol de Status zet. |

### Answer
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| --- | --- | --- | --- |
| `Status` | `Status` | AN200 | URL naar de huidige status: 'Toetsing wet- en regelgeving afgerond' |
| `Status.Zaak` | `Zaak` | AN200 | URL naar de zaak |
| ` ` | ` ` | - | - |

**Comment by ArjanKloosterboer** [comment]
Mooi uitgewerkt. Goed gezien dat een document waarin een besluit verwoord is ook aan de zaak gehangen moet worden. 
Enkele opmerkingen.

Stap 1, het beeindigen van de zaak, moet je als laatste doen. Daarna kun je niets meer aan de zaak veranderen. En in die stap leg je ook het resultaat van de zaak vast. Vwb. de archiveringskenmerken:
- als je het goed wilt doen vul je ook ZAAK.Selectielijstklasse en ZAAK.Procesobjectaard. Die vul je a.d.h.v. ZAAKTYPE.Selectielijst_procestype.
- je hebt niet ZAAK.Archiefnominatie.naam (de enumeratie) nodig maar ZAAK.Archiefnominatie (de attribuutsoort).
- idem ZAAK.Archiefstatus.naam.
V.w.b. het resultaat:
- ZAAK heeft bij afronding RESULTAATTYPE . Resultaattype-omschrijving (t.b.v. de aard van het resultaat);
- ZAAK heeft bij afronding RESULTAATTYPE . Procesobjectaard (t.b.v. de aard van het Selectielijst-procesobjectaard). Dit bepaalt tesamen met Resultaattype-omschrijving het van toepassing zijnde resultaat en daarmee de archiefparameters;
- ZAAK heeft bij afronding RESULTAATTYPE . Archiefnomimatie (bepaalt de archiefnominatie van de onderhanden zaak);
- ZAAK heeft bij afronding RESULTAATTYPE . Archiefactietermijn (is bepalend voor de archiefactiedatum van de onderhanden zaak). 
- relaties 'ZAAK is van versie van ZAAKTYPE' en 'RESULTAATTYPE is relevant voor ZAAKTYPE' (zodat je op de zaak van toepassing zijnde resultaattypen uitkomt).   

Zie vwb. STATUS (stap 2) mijn review op mapping #312

 V.w.b. stap 3, het Informatieobject, ik neem aan dat je de gebruiker het van toepassing zijnde informatieobjecttype wil laten bepalen. Daarvoor heb je nodig:
- ZAAKTYPE heeft relevant INFORMATIEOBJECTTYPE (voor de voor de Zaak - van het Zaaktype - relevante informatieobjecttypen);
- ZAAK-INFORMATIEOBJECT TYPE . Richting (om alleen de uitgaande informatieobjecttypen te kunnen presenteren, alleen die zijn in dit geval relevant);
 - INFORMATIEOBJECTTYPE . Omschrijving (om de van toepassing zijnde informatieobjecttypen te kunnen presenteren).
Of,  in de veronderstelling dat je bij het Besluittype (in de Zaaktypecatalogus) hebt gespecificeerd met welk Informatieobjecttype dit wordt vastgelegd:
- BESLUITTYPE wordt vastgelegd in INFORMATIEOBJECTTYPE (voor de relevante informatieobjecttypen);
- INFORMATIEOBJECTTYPE . Omschrijving (om de van toepassing zijnde informatieobjecttypen te kunnen presenteren).
Het mooie is als dit er precies één is, dat je de gebruiker niets meer hoeft te laten kiezen: de software kan het van toepassing zijnde informatieobjecttype eenduidig bepalen. De kans hierop is groot. 

V.w.b. stap 5, het besluit, ik neem aan dat je de gebruiker het van toepassing zijnde besluittype wil laten bepalen. Daarvoor heb je nodig:
- ZAAKTYPE heeft relevant BESLUITTYPE (voor de op de zaak van toepassing zijn besluittypen);
- BESLUITTYPE . Omschrijving (om de van toepassing zijnde besluittypen te kunnen presenteren);
of, in de veronderstelling dat bij het Resultaattype (in de Zaaktypecatalogus) is gespecificeerd tot welke Besluittypen dat leidt:
- RESULTAATTYPE leidt tot BESLUITTYPE  (voor de bij het resultaattype behorende besluittypen); 
- BESLUITTYPE . Omschrijving (om de van toepassing zijnde besluittypen te kunnen presenteren);
en ook:
- BESLUITTYPE . Reactietermijn (om de uiterlijke reactiedatum te kunnen bepalen).

**Comment by EdwinCoster** [comment]
Het Resultaattype = 'Afgebroken'.
Het Informatieobjecttype = 'Kennisgeving afwijzing verzoek'.
Het Besluittype = 'Kennisgeving afwijzing inzageverzoek persoonsgegevens'

**Comment by ArjanKloosterboer** [comment]
Juist ja. Daarmee wil je dan je zaaktype configureren, neem ik aan. Dan moet je wel de desbetreffende attributen van het zaaktype beschikbaar hebben. Dat is o.a. de strekking van mijn review.

**Comment by EdwinCoster** [comment]
Er zijn vooralsnog 4 situaties waarbij de het inzageverzoek wordt afgesloten.
- De aanvrager annuleert het inzageverzoek;
- Het inzageverzoek wordt afgewezen omdat niet aan wet- en regelgeving wordt voldaan;
- Het inzageverzoek wordt buiten behandeling gesteld omdat de aanvrager niet (tijdig) reageert op een verzoek voor extra informatie;
- het inzageverzoek wordt op normale wijze afgehandeld.
In de eerste 3 gevallen is het resultaat 'Afgebroken' met een bewaartermijn van 1 jaar en in het laatste geval is het resultaat 'Afgehandeld' met als bewaartermijn 5 jaar.

Als ik bij het afsluiten van de zaak ook het resultaat moet vastleggen, gaat dat laatste weer voor.

**Comment by ArjanKloosterboer** [comment]
Dat is een keuze, om je resultaten zo te benoemen (ik zou vier soorten resultaten onderkennen, oa. nuttig voor statistische overzichten). Maar dat doet niets af aan mijn bovenstaande review. Ook maar even overleggen dan?

**Comment by EdwinCoster** [comment]
In het zaaktype zoals dat nu bij ons gedefinieerd is zijn 2 resultaten benoemd. Maar dat kan natuurlijk altijd uitgebreid worden ('geannuleerd', 'afgewezen', 'afgebroken' en 'afgehandeld'). De bewaartermijnen veranderen niet. Overleg is prima, maar dan wel telefonisch.

**Comment by ArjanKloosterboer** [comment]
@EdwinCoster, gezien mijn gewijzigde rol in het project, leg ik de bal bij jou neer. Mijn review van de mapping staat nog steeds. Mocht ik wat kunnen bijdragen, laat het me weten.

**Comment by EdwinCoster** [comment]
@ArjanKloosterboer Ik heb een aantal aanpassingen doorgevoerd. Wil je er nog een keer naar kijken?

**Comment by ArjanKloosterboer** [comment]
Mooie mapping. Nog een enkele opmerking.
Je hebt in stap 7 bij de request Zaak.Procesobject staan. Dit moet Zaak.Procesobjectaard zijn: "Omschrijving van het object, subject of gebeurtenis waarop, vanuit archiveringsoptiek, de zaak betrekking heeft". Formaat is AN200. Waarde is, vermoed ik, "Informatieverzoek" (kolom 'Omschrijving' in de Selectielijst).  
Ik zie 'ZAAK-INFORMATIEOBJECT TYPE . Richting' noch 'BESLUITTYPE wordt vastgelegd in INFORMATIEOBJECTTYPE' niet; die gebruik je bewust niet?

**Comment by ArjanKloosterboer** [comment]
Procesobjectaard wordt normaliter verwoord met een zelfstandig naamwoord, niet met een werkwoord (het gaat om de aard van het object, niet om een proces). Enfin ...

**Comment by ArjanKloosterboer** [comment]
Klopt. Bij een generiek resultaat is er geen procesobjectaard omdat het een generiek resultaat is, geldig ongeacht procesobjectaard m.u.v. de procesobjectaarden die vermeld zijn bij de specifieke resultaten.
