### ISSUE TITLE
Als ontwikkelaar wil ik vragen over de standaard kunnen stellen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#404]
...zodat ik niet geblokkeerd wordt bij implementaties.

_Aangemaakt tijdens sprint planning op 13 september 2018, afgesplitst van #187_

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] Er is een manier om vragen te stellen
- [ ] Deze manier is duidelijk te vinden

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Ontwikkelaars kunnen vragen stellen
- [ ] Vragen worden beantwoord

**Taken**
- [ ] VNG beheer organisatie inrichten
- [ ] Communicatie kanaal inrichten

**Comment by michielverhoef** [comment]
Hoewel het niet optimaal is kan ik me voorstellen dat een forum zoals https://discussie.kinggemeenten.nl/ nodig is om vragen en gegeven antwoorden (FAQ?) 

Eventueel kan ik hiervoor een (apart) forum aanmaken.

**Comment by TCIMEddy** [comment]
@ehotting Zie voorstel van Michiel. Wat is wenselijk volgens jou?

**Comment by ehotting** [comment]
Enige reden om het niet op GitHub te doen zou zijn dat het niet publiek mag zijn. Die forums op kinggemeenten.nl zijn wél publiek en bieden dus geen meerwaarde boven Github volgens mij.

Het direct koppelen van issues aan stukken code, en andersom het direct koppelen van oplossingen aan pull requests, lijkt me te prefereren. Ik zou dus adviseren issues in GitHub te maken en dit qua structuur / ordening goed voor te bereiden. Maar hoor graag andere argumenten.

**Comment by ehotting** [comment]
Dit moeten we beleggen bij VNG R, geen taak voor ons team.
