### ISSUE TITLE
Als PO wil ik een analyse op veldniveau om vast te stellen welk deel van RGBZ wordt afgedekt in de API's

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#405]
...zodat we gericht kunnen nagaan welke delen we nog missen en daar user stories bij kunnen bedenken.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [x] Een visuele presentatie van de resultaten van de analyse
- [x] De resultaten van de analyse zijn beschikbaar (in Excel)

**Acceptatiecriteria**
- [x] Niet van toepassing voor deze US

**Taken**
- [x] Excel (of markdown) maken met alle Objecttypes en attributen
- [x] Excel (of markdown)  aanvullen met Ja/Nee of veld is opgenomen in de API.

**Comment by joeribekker** [comment]
Zie: https://docs.google.com/drawings/d/1vtdp3qMEetb8-kYNM7fp3et6jz1IDf7_yQahraRAGng

**Comment by joeribekker** [comment]
Duplicatie van #324 ?

**Comment by TCIMEddy** [comment]
![schermafbeelding 2018-09-26 om 17 06 35](https://user-images.githubusercontent.com/39735549/46089570-1de84900-c1af-11e8-9a19-7e1005f599e2.png)
@ArjanKloosterboer Ik heb je plaat hier geplaatst

**Comment by TCIMEddy** [comment]
Aangezien je gestart bent heb ik deze user story verplaatst naar de sprint!

**Comment by ehotting** [comment]
Svp niet "Gerealiseerd / Te doen" maar gewoon "In API / Niet in API"

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer @joeribekker Er liggen nu twee mooie plaatjes, hoe gaan jullie nu verder? Of worden beide plaatjes uitgewerkt.

**Comment by joeribekker** [comment]
@ArjanKloosterboer Had jij al een Excel gemaakt (hoorde ik tijdens retro op 11-10)

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer deze us is essentieel, kun je een update geven van de stand van zaken.

**Comment by ArjanKloosterboer** [comment]
Dit taartdiagram geeft een indicatie in hoeverre attributen en relaties van de informatiemodellen RGBZ en ImZTC in API's zijn opgenomen. Geen onderscheid wordt gemaakt naar C, R, U en D. D.w.z. een attribuut of relatie dat is opgenomen in één of meer van deze operaties telt mee als 'In API' ook al zijn nog niet alle operaties voor dit attribuut of relatie gerealiseerd. 

![afbeelding](https://user-images.githubusercontent.com/23450232/47173560-a8374f00-d30e-11e8-9fb2-99b21ab22981.png)

**Comment by ArjanKloosterboer** [comment]
Dit staafdiagram geeft per objecttype (in de informatiemodellen RGBZ en ImZTC) aan in hoeverre de attributen en relaties daarvan zijn opgenomen in CRUD-operaties van desbetreffende resources.

![afbeelding](https://user-images.githubusercontent.com/23450232/47173725-1e3bb600-d30f-11e8-9df4-4f94cb00b062.png)

**Comment by ArjanKloosterboer** [comment]
Na nijver knip-, plak-, formule- en zet-kruis-werk is het dan gelukt bovenstaande grafieken te produceren. Ze zien er iets anders uit dan gedacht. Dat komt door voortschrijdend inzicht dat per resource informatie per C-, R-, U- en D-operatie wenseljk is.
Een en ander is opgenomen en komt voor uit een xls-spreadsheet, bijgaand. Lees de Readme (tab) voor een toelichting. 
Ik heb de kruisjes zo goed mogelijk gezet, gebaseerd op [deze informatie](https://ref.tst.vng.cloud/developers/api-specificaties/). Daarin ontbreken objecten, personen e.d. Die zijn dus niet verwerkt in de grafieken.
Graag review van een en ander.
En bepalen wie dit gaat bijhouden. 

[API-compleetheid.xlsx](https://github.com/VNG-Realisatie/gemma-zaken/files/2493132/API-compleetheid.xlsx)

**Comment by michielverhoef** [comment]
> En bepalen wie dit gaat bijhouden.

Dit is een heel mooi voorbeeld van waar ontwikkeling en beheer in elkaar overlopen. Dat noemen we ook wel DEVOps of APIPOps . Lijkt me een mooi klusje voor de beheerder van de Zaak- Documentservices :-D

**Comment by ArjanKloosterboer** [comment]
@TCIMEddy, is dit beter?
![afbeelding](https://user-images.githubusercontent.com/23450232/47350201-a0343200-d6b5-11e8-830b-a3cda7add572.png)

**Comment by TCIMEddy** [comment]
@wishalg Zie vragen en antwoorden mbt beheer van dit document wellicht belangrijk voor jou in beheersverhaal

**Comment by TCIMEddy** [comment]
Goed document, maar wat gaan we concreet doen? Volgens mij is de korte klap mogelijk met de ZTC-API. en niet eenvoudigweg alles aanzetten (API Haarlem). Maar per onderdeel de functionele behoefte achterhalen en beschrijven in een user story. Daarna wenselijkheid en prioriteit bepalen. Er heeft uiteraard een functionele behoefte/user story aan ten grondslag gelegen bij de ontwikkeling van het RGBZ. Exercitie heeft 2 doelen API verbreden/verdiepen en indien nodig informatiemodel aanscherpen.

**Comment by TCIMEddy** [comment]
Wat mij betreft is de analyse klaar en voldoet aan de DoD. Document moet worden beheerd en daar maak in een nieuwe user story voor aan.
