### ISSUE TITLE
Als teamlid wil ik duidelijk maken dat we registraties definieren in plaats van off-the-shelve componenten

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#408]
...zodat gemeentes, architecten en leveranciers geen verkeerde indruk krijgen.

Er was wat discussie over het 'component' element van de namen te strippen:
- zaakregistratiecomponent -> zaakregistratie
- documentregistratiecomponent -> documentregistratie(of infromatieobjectregistratie?)
- zaaktypecatalogus -> zaaktypecatalogus (geen verandering)
- besluitregistratiecomponent -> besluitregistratie

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] ~~_**Userstory is ingevuld op template architectuurschets**_~~
- [ ] ~~**_Userstory is voorzien van veldmapping naar RGBZ2_**~~
- [ ] ~~**_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**~~
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] het woord 'component' is verbannen uit de repositories en documentatie

**Acceptatiecriteria**
- [ ] het woord 'component' komt niet meer voor

**Taken**
- [ ] Repositories van referentieimplementaties hernoemen
    - [ ] ZR
    - [ ] DR
    - [ ] ZTC
    - [ ] BR
    - [ ] OR
- [ ] Component uit de templates/OAS specificaties weghalen
    - [ ] ZR
    - [ ] DR
    - [ ] ZTC
    - [ ] BR
    - [ ] OR
- [ ] Dummy URLs in (unit) tests & `docker-compose.yml` aanpassen
    - [ ] ZR
    - [ ] DR
    - [ ] ZTC
    - [ ] BR
    - [ ] OR
    - [ ] ZIT
- [ ] Beschrijving op Docker Hub aanpassen
    - [ ] ZR
    - [ ] DR
    - [ ] ZTC
    - [ ] BR
    - [ ] OR
- [ ] Documentatie/technische documenten doorlopen en component weghalen
- [ ] Afkortingslijst bijwerken

**Comment by MarcoKlerks** [comment]
De term "component" doet inderdaad vermoeden dat het om een apart systeem of applicatie gaat. Een zaakregistratie klinkt echter als de registratie van één zaak. 

Alternatieven die ik ter afweging wil voorleggen, zijn:
- Zakenmagazijn / Zakencatalogus / Zakenregister
- Documentenmagazijn / Documentencatalogus / Documentenregister
- Zaaktypenmagazijn / Zaaktypencatalogus / Zaaktypenregister
- Belsuitenmagazijn / Besluitencatalogus / Besluitenregister
- etc.

**Comment by TCIMEddy** [comment]
@MarcoKlerks Dank voor al je input!

**Comment by ehotting** [comment]
Moet gebeuren maar ergens aan einde traject ajb

**Comment by hdksi** [comment]
Issue is een aantal keer aan de orde/besproken geweest, maar niet opgelost, met name door onzekerheid over hoe naamgeving er in een gegevenslandschap uit zou moeten zien. 

@ppcjansen had jij hierover iets geschreven?

**Comment by hdksi** [comment]
Maar eens door de issues heen waar mijn naam aan hangt, te beginnen bij de oudste.

zaakregistratiecomponent -> zakenregister
documentregistratiecomponent -> documentenregister (of informatieobjectenregister, maar dan moet ook de API mee)
zaaktypecatalogus -> zaaktypecatalogus (geen verandering)
besluitregistratiecomponent -> besluitenregister

**Comment by hdksi** [comment]
En eigenlijk zou in de naamgeving ook iets van de referentiecomponentenstatus terug moeten komen...

**Comment by hdksi** [comment]
Graag prio voor aanpassingen.

**Comment by michielverhoef** [comment]
> Maar eens door de issues heen waar mijn naam aan hangt, te beginnen bij de oudste.
> 
> zaakregistratiecomponent -> zakenregister documentregistratiecomponent -> documentenregister (of informatieobjectenregister, maar dan moet ook de API mee) zaaktypecatalogus -> zaaktypecatalogus (geen verandering) besluitregistratiecomponent -> besluitenregister

Deze namen zijn inmiddels doorgevoerd
