### ISSUE TITLE
Als record manager wil ik een reeds afgesloten zaak kunnen muteren

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#409]
zodat incomplete zaken die verantwoording onmogelijk maken, compleet gemaakt kunnen worden.
Gerelateerd aan #351 & #442

Splitsing in user story's aangebracht voor kunnen muteren afgesloten zaak (deze userstory) en kunnen heropenen afgesloten zaak (#442)

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting Deze user story kwam vanmiddag aan de orde en is opgevoerd. Zou jij willen aanvinken of je akkoord bent en of deze ready gemaakt mag worden en of de user story scherp genoeg is. Dit voor een goed verloop van het scrumproces :-)

**Comment by ehotting** [comment]
Yep, een andere interessante user story om de flexibiliteit van scopes mee op de proef te stellen.

**Comment by CMasselink** [comment]
> Yep, een andere interessante user story om de flexibiliteit van scopes mee op de proef te stellen.

@ehotting : eigenlijk zijn er twee vraagstukken rond het muteren van afgesloten zaken:
Het hierboven beschreven scenario waarbij de record manager een reeds afgesloten zaak compleet wilt kunnen maken. Hierbij kan een record manager dus een zaak muteren terwijl de zaak afgesloten blijft, de eindstatus blijft staan, idem voor de einddatum.
Maar wat ook voor komt: Een zaak wordt onterecht afgesloten, de zaak is dus niet af: lees er is geen resultaat, de behandeling van de zaak loopt dus eigenlijk door. De record manager zou dan de zaak weer kunnen openen, dat betekent: einddatum verwijderen en status wijzigen naar een eerdere status. Een medewerker/behandelaar kan de zaak dan verder behandelen.
Ik denk dat het handig is om voor het 2e scenario een aparte user story te maken, eens? Of meenemen bij deze user story?

**Comment by Hugo-ter-Doest** [comment]
Uitgesloten zijn status en audit trail.

**Comment by sergei-maertens** [comment]
Formele historie is hier belangrijk uiteindelijk

**Comment by joeribekker** [comment]
klinkt als autorisatie ding: als superuser (tm) mag je toch nog alles aanpassen :)

**Comment by Hugo-ter-Doest** [comment]
Sommige wijzigingen kunnen de procestermijn dan wel de archiefactietermijn wijzigen. Uitzoeken.

**Comment by hdksi** [comment]
Hierbij nadenken over notificaties: als bijvoorbeeld twee jaar na sluiting van een zaak een correctieve wijziging wordt doorgevoerd in een zaak, is het om verwarring te voorkomen waarschijnlijk wenselijk dat betrokkenen daarover geïnformeerd worden, maar bij voorkeur op een niet-verwarrende manier

**Comment by sergei-maertens** [comment]
Bij (partial) update:

* controleer of `Zaak.einddatum` gevuld is ja/nee (=definitie afgesloten zaak)
* indien ja -> verifieer dat nieuwe scope present is

**Comment by joeribekker** [comment]
We slicen dit ticket dus (ondanks alle comments) tot autorisatie beperkingen, zonder te kijken naar notificaties en archief issues.

**Comment by sergei-maertens** [comment]
Implemented in https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/48
