### ISSUE TITLE
Als burger wil ik de status van de melding opvragen...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#41]
...zodat ik weet of de melding al is opgepakt of afgehandeld.

**Comment by jgortmaker1** [comment]
tsja...
anoniem melding doen en toch een status kunnen opvragen, kan dat, willen we dat? Geen idee eigenlijk.
als je niet anoniem melding doet, kun je de status via je portaal inzien, gok ik..

**Comment by TCIMEddy** [comment]
Je kunt alleen een status MOR opvragen na identificatie (DigiD etc..). BIj anonieme meldingen kan dat uiteraard niet en is ook niet wenselijk

**Comment by sergei-maertens** [comment]
@jgortmaker1 @TCIMEddy zie ook https://github.com/VNG-Realisatie/gemma-zaken/issues/40#issuecomment-398314833

De meldingen zullen openbaar en transparent inzichtelijk zijn. Je kan dus anoniem een melding doen, en vervolgens zien dat je melding in de lijst van 'open meldingen' staat en op die manier opvolgen wat de status ervan is.

**Comment by jgortmaker1** [comment]
enkel de open meldingen, of ook de gesloten meldingen? (als er iets mee is gedaan kan ene melding worden afgesloten: als er een handhaver op de fiets wordt gestuurd)..

En mag je dit wel publiceren? een lijstje met meldingen, locaties en namen van boten/rederijen? Dit is geen persoonsinformatie, maar als je lijsten hebt staan met veel voorkomens van boten van rederij x, dan kunnen dat onterechte meldingen zijn. Maar is dat wel info over een bedrijf dat je als gemeente publiceert...zou ik eens een jurist naar laten kijken...

**Comment by TCIMEddy** [comment]
@sergei-maertens dit kan toch al?

**Comment by sergei-maertens** [comment]
Jep, de status van een zaak (om even technisch correct te zijn) kan uitgelezen worden.
