### ISSUE TITLE
Als ontwikkelaar wil ik convenience methods waarmee ik snel veelvoorkomende acties kan uitvoeren

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#413]
...zodat ik het aantal calls kan minimaliseren en functioneel aan blijf sluiten op een mogelijk veranderende REST API.

Toelichting: in de werkgroep gebruikerswensen van de DSO Open API werkgroep werd door aanwezige ontwikkelaars aangegeven dat alleen een REST API niet heel gebruiksvriendelijk is voor ontwikkelaars die het onderliggende informatiemodel niet uit den treure kennen. 

Overigens wil dit niet zeggen dat een REST API niet wenselijk is maar deze zou aangevuld moeten worden met convenience of experience methods.

Deze gedachte begint bij de DSO ook opgang te maken.
Dit lijkt me een mooi onderwerp voor een discussie op maandag.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by sergei-maertens** [comment]
Dit lijkt me iets wat aangeboden kan worden in client-implementaties voor de APIs. Deze clients zouden kunnen gebouwd worden in de vaak-voorkomende programmeertalen.

**Comment by joeribekker** [comment]
Ik denk dat Michiel of doelt op "acties" of op composite APIs?

> Toelichting: in de werkgroep gebruikerswensen van de DSO Open API werkgroep werd door aanwezige ontwikkelaars aangegeven dat alleen een REST API niet heel gebruiksvriendelijk is voor ontwikkelaars die het onderliggende informatiemodel niet uit den treure kennen.

Ik wil daar wel eens bij aansluiten en met de aanwezig ontwikkelaars spreken. Alle grote populaire partijen (Google, Facebook, Twitter, Slack, Instagram, Stripe....) bieden REST-APIs zonder dat het woord informatiemodel ook maar ergens genoemd wordt. Dat je dit zou moeten kennen om met de REST APIs te werken vind ik daarom nogal een statement. Goede API-guide, ja. Informatiemodellen, nee?

**Comment by ArjanKloosterboer** [comment]
**Statement**: _Zonder kennis van de semantiek die technisch uitgewerkt is in een API heb je geen idee wat je aan het doen bent bij het gebruiken van die API_.
Een informatiemodel is een manier om die semantiek duidelijk te maken. Als dat er niet is ben ik benieuwd hoe genoemde partijen dan de semantiek duidelijk maken. En praten we wel over hetzelfde? Bij bevraging-API's maakt het niet zo heel veel uit. Maar bij update-API's luistert het nauw. Als we daar onvoldoende aandacht aan besteden, krijgen we dezelfde non-interoperabiliteitsproblemen als nu bij StUF-berichten. Waar we bij StUF-koppelvlakken achter zijn gekomen is dat de gebeurtenis van belang is die aanleiding geeft tot een update. Voor een specifieke gebeurtenis valt heel specifiek te specificeren wat er wel en niet mag en moet gebeuren en onder welke voorwaarden. Dit lijkt nu aan de client overgelaten te worden. Die moet zelf maar bepalen hoe die een gebeurtenis verwerkt tot de juiste API-calls. Als verschillende clients (van bijvoorbeeld verschillende leveranciers) dat voor dezelfde gebeurtenis op verschillende wijze doen, dan lopen we m.i. hetzelfde risico als nu met het gebruik van StUF-berichten. 
Hoe kunnen we deze (of mijn) zorg wegnemen?

**Comment by ArjanKloosterboer** [comment]
In aanvulling hierop een praktijk voorbeeld n.a.v. deze [designkeuze](https://github.com/VNG-Realisatie/gemma-zaken/issues/166#issuecomment-421980259) waarin de zaak-informatieobect-relatie wordt uitgewerkt in twee resources in twee API's (DRC en ZRC). Je moet als client maar weten dat je de resource in de ZRC-API niet mag updaten. Als je iets met de relatie wil doen, moet je dat doen met de DRC-API die er vervolgens voor zorgt dat de ZRC-resource geupdated wordt. Hoe schermen we af dat alleen die DRC-resource aan die ZRC-resource mag zitten?

**Comment by michielverhoef** [comment]
Om een ander voorbeeld te noemen, het afsluiten van een zaak. Als een zaaktype maar 1 laatste status kan hebben sluit je de zaak af door deze laatste status aan de zaak toe te kennen. Voor die tijd moeten mogelijk nog allerhande updates en controles uitgevoerd worden. Je kunt zeggen dat de client dat helemaal zelf aan moet sturen of je gebruikt een convenience method waarin je de laatste stand van de zaak en de einddatum meegeeft.  De provider zorgt dan zelf voor het correct afhandelen van het afsluiten.

**Comment by ArjanKloosterboer** [comment]
@sergei-maertens Ik ben benieuwd naar de uitwerking en de API-documentatie ;-)

**Comment by michielverhoef** [comment]
Door de validatie in te bouwen in de referentie-implementatie, lopen we dan het risico dat we business logica van de standaard afgeleid moet worden uit die referentie-implementatie? Dat lijkt me geen wenselijke situatie. Bovendien maakt het nog niet dat een ontwikkelaar op eenvoudige manier bijvoorbeeld een gecombineerde call of een call met afhankelijkheden kan doen.
Juist door identieke gebeurtenissen op exact dezelfde manier in te vullen met API calls maak je dat de afhandeling van die gebeurtenis op dezelfde manier gebeurt. Dit kun je bereiken met specificeren welke API calls er gedaan moeten worden in een los document (denk aan de huidige PDF's waarin eea beschreven staat wat niet in de xsd schema's opgenomen kan worden). Of je maakt een convenience method die de business logica uitvoert.
Het staat een client dan nog steeds vrij om zelf de onderliggende REST calls uit te voeren maar dat is dan op eigen risico.

**Comment by sergei-maertens** [comment]
@michielverhoef dit wordt uiteraard in tekstvorm neergepend ook, zie [`standaard.md` in pull request](https://github.com/VNG-Realisatie/gemma-zaken/pull/412/files#diff-cd7d2645382d4713da25a578fa04965d)

**Comment by sergei-maertens** [comment]
> Het staat een client dan nog steeds vrij om zelf de onderliggende REST calls uit te voeren maar dat is dan op eigen risico.

Klopt, maar zelfs dan kunnen we vrij ver dingen valideren. Je kan niet een besluit registreren bij een zaak die nog niet bestaat bijvoorbeeld. Dat wordt via URL validatie afgedwongen. Als je daar een composite API bovenop legt, of een client die typische patronen kent, dan moet deze client nog steeds de juiste volgorde aanhouden om netjes door de validatie heen te komen.

**Comment by sergei-maertens** [comment]
> Een andere convenience method kan zijn het toevoegen van een document in de DRC, aanmaken van een zaakinformatieobject in de DRC en het toevoegen van deze relatie in de ZRC. Dan ligt de verantwoordelijkheid niet meer bij de DRC maar wordt deze actie uit naam van de oorspronkelijke gebruiker onder water vanuit de API call uitgevoerd. Op zich verschilt dit niet heel veel van het idee om de DRC deze call uit te laten voeren (dat gebeurt eigenlijk nog steeds) maar dan is de werkwijze veel inzichtelijker en minder verborgen. Voor een (uitwisselings) standaard is dit beter m.i.

Niet akkoord, omdat je nu interne complexiteit en gedrag van de datalaag naar de API laag trekt, en het alsnog het probleem maakt van de consumer. Voor de consumer wil je een single source of truth.

Dit gaat te veel richting transactiemanagement inbouwen op API niveau (Bad Idea volgens de lectuur over microservices), dus om dat als reden aan te grijpen vind ik niet valide. Het laat ons ook niet toe om op termijn dit soort 'onderwateroperaties' via een event-systeem uit te voeren. Semantisch maak je de relatie tussen een zaak en informatieobject in het DRC, de consumer (of dat nu een echte client of een composite API is) moet je het leven makkelijk maken door slechts 1 call te hoeven doen. Developer first!

**Comment by michielverhoef** [comment]
Ik zie niet hoe het een probleem van de client wordt wanneer je een convenience method aanroept in plaats van erop vertrouwt dat de DRC een vervolgactie gaat uitvoeren. Als client roep je 1 call aan en dat is een wrapper om een aantal andere calls heen.
De hele achtergrond achter dit issue is developer first, het waren immers de ontwikkelaars die met deze vraag kwamen...

**Comment by sergei-maertens** [comment]
Is het de bedoeling dat VNG dan ook een `openapi.yaml` gaat publiceren voor die convenience API? Ik probeer te begrijpen wat de scope is van deze US :)

**Comment by michielverhoef** [comment]
Ook vanuit "buiten" komt nu de vraag om een dergelijke convenience of experience API, zie ook #523 

Met de kennis van nu zou ik zeggen dat de huidige API laag een system API is en daar boven op een process en experience API laag kan komen. 

Een convenience API zou dan denk ik het beste passen in de process API maar daar moet nog maar eens een discussie over gevoerd worden.

**Comment by Hugo-ter-Doest** [comment]
We maken eerst de basis API's af, daarna kijken we naar composite en/of convenience API's

**Comment by TCIMEddy** [comment]
Deze user story is (te) algemeen, maar op de backlog staan inmiddels al de nodige concrete user stories m.b.t. conveniënte (tevens label aangemaakt). Daarom deze op close

**Comment by adgerrits** [comment]
Hoewel op 'close' verwijs ik nog maar even naar mijn opmerking op https://github.com/VNG-Realisatie/gemma-zaken/issues/1013#issuecomment-514620830 over het onderscheiden van verschillende type API's. Ik denk dat een groot deel van wat hier 'convenience' wordt genoemd valt onder wat daar 'process API's' worden genoemd. Lijkt me nuttig als daar een duidelijke visie op komt en duidelijk wordt uitgesproken in hoeverre die wel of niet tot de standaard behoren.
