### ISSUE TITLE
Demo sprint 4 (4 oktober 2018)

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#415]
**Mogelijke onderwerpen**

- [ ] Api BR(C)
- [ ] wat moet een developer (bijvoorbeeld van leverancier doen) om API te bouwen (stappenplan, gebruiksaanwijzing, praktijkvoorbeeld)
- [ ] user story sprint 5 autorisatie en authenticatie bespreken en vragen om input

**Checklist Demo**

- [x] alle stakeholders uitgenodigd

- [x] juiste stakeholders uitgenodigd

- [x] lunch geregeld

- [x] voldoende stoelen in zaal

- [x] geen geluidoverlast

- [ ] 2 schermen

- [ ] 1 powerpoint/presentatie (samengevoegd)

- [x] beamer aanwezig

- [x] flipover aanwezig

- [x] kabels aanwezig om laptops (ook Apple!) aan te sluiten

- [x] wie schrijft mee (met name feedback en acties)

- [ ] bevat demo mix van kennisoverdracht en daadwerkelijk demonstreren

- [ ] context geschetst

- [ ] 'show and shine'-element

- [x] is demo goede weergave wat er in de sprints is gedaan (of niet gedaan)

**Comment by TCIMEddy** [comment]
@wishalg Wil jij voor de lokatie de checklist doorlopen

**Comment by wishalg** [comment]
@michielverhoef Michiel schrijft mee.
