### ISSUE TITLE
Als developer wil ik eenvoudig de referentie-implementaties en afgeleiden kunnen integreren met NLx...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#416]
...zodat ik niet van de NLx details op de hoogte hoef te zijn.

Er is een probleem bij het werken met linked-data en het communiceren van referenties naar andere resources d.m.v. urls. Indien je van NLx gebruik maakt, dan loopt communicatie via een outway, wat tot andere URLs leidt voor dezelde resources indien je geen NLx zou gebruiken. De implementaties moeten hiermee op een opt-in basis kunnen mee omgaan.

In https://github.com/maykinmedia/gemma-nlx-middleware wordt er een middleware ontwikkelt die de URLs in de request en responses op een intelligente manier herschrijft zodat er transparent van NLx kan gebruik gemaakt worden, zonder het risico te lopen dat er NLx URLs opgeslagen worden in plaats van de canonical URLs.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting graag jouw visie toevoegen en uitspraak doen over prioriteit

**Comment by sergei-maertens** [comment]
Upstream [feature request(s) bij NLx](https://gitlab.com/commonground/nlx/issues/316)

**Comment by ehotting** [comment]
Mag op backlog blijven staan, in feite afhankelijk van wat keuzes in ander project (NLX). Vooralsnog 'blok'  (wacht op actie in extern project) en waarschijnlijk daarna out-of-scope.

**Comment by TCIMEddy** [comment]
@sergei-maertens Volgens mij wordt dit 'probleem' opgepakt. Is het nog relevant voor dit project of kan het op close?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest volgens mij kan deze op het bord out of scope?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest deze out of scope gezet en close. Indien niet gewenst roepen :-)
