### ISSUE TITLE
Als ontwikkelaar wil ik dat URLs zowel met als zonder "/" werken voor collections (list)

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#419]
...zodat ik me niet bezig moet houden met onzin.

Voorbeeld: `/api/v1/zaken/?foo=bar` werkt niet, maar `/api/v1/zaken?foo=bar` werkt wel. Moet gewoon allebei werken.

**Comment by sergei-maertens** [comment]
@joeribekker `APPEND_SLASH` is bewust uitgezet omdat de DSO URL-strategie daar wat over zegt...

**Comment by sergei-maertens** [comment]
zie https://github.com/VNG-Realisatie/gemma-zaken-common/blob/master/zds_schema/routers.py#L8

**Comment by TCIMEddy** [comment]
@ehotting Ik heb deze al op prio h gezet wil jij nog vinkje zetten

**Comment by sergei-maertens** [comment]
Ik heb hier nog wel bezwaar over, want dat betekent dat beide URLs (met en zonder slash) in de API spec moeten opgenomen worden. Redirects bij GET requests zijn prima, redirects bij POST/PUT/PATCH zijn... vervelend.

**Comment by sergei-maertens** [comment]
@TCIMEddy hoeft niet, dit is echt niet de moeite waard om in groep te gaan overleggen, typisch gevalletje bike-shedding waar Joeri en ik het eens over moeten worden en klaar.

**Comment by joeribekker** [comment]
Ik ben wellicht van de oude stempel *snif*.

Er is geen RFC die zegt A of B, of allebei. Internet is ook verdeeld.
Veel grote APIs doen alles zonder "/" ([Google](https://developers.google.com/gmail/api/v1/reference/users/drafts/list), [Facebook](https://developers.facebook.com/docs/graph-api/reference/photo/#Creating), maar zelfs [hier](https://restfulapi.net/resource-naming/) staat zonder trailing slash) maar er zijn ook bronnen die juist wel "/" aanhouden ([Wikipedia](https://en.wikipedia.org/wiki/Representational_state_transfer#Relationship_between_URL_and_HTTP_methods))

Het merendeel van het internet vind zonder trailing slash, de DSO zegt er niet iets specifieks over maar alle voorbeelden zijn zonder trailing slash, dus...

Eens, dat er geen trailing slash moet komen.

**Comment by joeribekker** [comment]
Oeps, laten we er wel een design keuze van maken omdat de DSO het alleen heel impliciet aangeeft.

**Comment by ehotting** [comment]
OK, design choice is dus dat API's alleen werken zonder trailing slash.

**Comment by sergei-maertens** [comment]
Hoe communiceren we dit terug naar de DSO? Moet @HenriKorver of @Hugo-ter-Doest hier wat voor doen? Lijkt me fijn als dat op landelijke URI-strategieniveau kan vastgelegd worden ook.

**Comment by ehotting** [comment]
Is voldoende dit te doen via deze Github repo, dan komt het goed terecht: https://github.com/Geonovum/KP-APIs/issues/

Ik haal hier assignees af, zie https://github.com/Geonovum/KP-APIs/issues/8
