### ISSUE TITLE
Als burger wil ik alle meldingen kunnen inzien in mijn omgeving, binnen mijn gemeente...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#42]
...zodat ik weet wat er speelt of dat een melding al gedaan is.

**Definition of done**

- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [x] Voldoet aan RGBZ 2.0
- [x] Voldoet aan GEMMA 2.0

**Taken**
- [x] Architectuurschets opleveren [Marcel Moerman]
- [x] Beschrijven welke data / operaties bij deze functie nodig zijn [Marcel Moerman]
- [x] Aanleveren testdata [_verantwoordelijke_]
- [x] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [x] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [x] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Architectuurschets**
Architectuurschets is hier #180 te vinden.

**Korte beschrijving uitwerking**
Deze operatie verondersteld een GEO.Extensie op de database, hiermee kunnen er selecties worden gedaan op basis van oa. geometrie.

Anoniem: Geef alle meldingen terug binnen een straal van x meter van deze punt op de kaart.
Ingelogd: Geef alle meldingen terug binnen een straal van x meter rond mijn adres.

Als voorbeeld kan de GEO.Search op https://api.data.amsterdam.nl/api/swagger/?url=/geosearch/docs/geosearch.yml#/ dienen.

### READ op ZRC API met filter op 
| Attribuut | Waarde | OPERATIE |
| :--- | :--- | :--- |
| Zaak.object.coordinaat | binnen een straal van ... m |  ... |

**Comment by jgortmaker1** [comment]
wil je dit via ZRC/ZDS laten lopen, of is een handige API op het MOR-systeem hiervoor geschikter/functionele rijker/..?

**Comment by sergei-maertens** [comment]
@jgortmaker1 voor de ZDS services/API niet van toepassing. In het geval van Amsterdam wordt er voor een melding een zaak aangemaakt, de website/app die deze meldingen presenteert zal de zaakservices bevragen, en dat is het relevant aspect voor ons: zaken kunnen opvragen binnen een bepaalde geometrie/buurt.

**Comment by jgortmaker1** [comment]
ik denk dat het wel relevant is...dit is een erg specifieke wens mbt 'zaken' vanuit een MOR-proces. vraag is of je het met zaken moet oplossen..een MOR-specifieke oplossing kon wel eens simpeler en ook functionele rijker zijn..

**Comment by MarcelMoerman** [comment]
Deze "zoek functie" is relevant over alle typen zaken, niet alleen MOR, een handhaver zou ook graag kunnen inzien of er meldingen overlast, vergunning aanvragen (steigers en containers), horeca, of andere "zaken" spelen rond een lokatie waar hij op dat moment is.

**Comment by jgortmaker1** [comment]
nu lopen er al 3 user stories door elkaar:
1. op een kaart meldingen kunnen tonen (zo had ik hem begrepen)
2. kunnen zoeken op zaken
3. overzicht relevante zaken voor een handhaver tonen...

Mijn enige punt was: goed bedenken wat we willen. En dan kijken hoe we dat willen oplossen. 2. en 3 zou ik met zaken oplossen. Voor 1 vind ik dat nog steeds de vraag. Buiten meldingen zijn er denk ik niet erg veel use-cases te verzinnen waarvoor je generieke "toon zaak op kaart" functionaliteit nodig hebt..

Voor het kunnen zoeken/overzicht relevante zaken: moeten we daar ook niet iets met doelbinding in de API regelen?

**Comment by Hugo-ter-Doest** [comment]
Bij Dimpact-leden is er de wens om (selecties van) zaken in het algemeen op een kaart te kunnen tonen. Toepassingen zijn o.a. vergunningen en toezichtzaken. In het algemeen alle zaken die op een of andere manier een zaakgeometrie (kunnen) hebben.

**Comment by Hugo-ter-Doest** [comment]
De locatie van de zaak kun je ook met ZAAK.Zaakgeometrie oplossen. Dan hoeft er geen object aan de zaak gekoppeld te zijn.
