### ISSUE TITLE
Als developer wil ik dat niet toegestane query-params een error geven

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#420]
...zodat ik weet dat ik iets fout doe.

Nu kan je alles meegeven, en krijg je een lijst terug van ALLES als je een invalide query param meegeeft. Dit moet een error geven.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [x] er is een OAS 3.0 specificatie
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [x] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [x] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**

- [ ] ...

**Taken**
- [x] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [x] Implementeren in referentie-implementatie [_verantwoordelijke_]

**Comment by sergei-maertens** [comment]
relevant item in django-filter https://django-filter.readthedocs.io/en/master/guide/migration.html#filterset-strictness-handling-moved-to-view-788

**Comment by TCIMEddy** [comment]
Ik heb iedereen begrijpt de user story afgevinkt omdat hij ready for sprint is al vraag ik me af of iedereen het begrijpt (of moet begrijpen). Prio H dus sprint 5

**Comment by sergei-maertens** [comment]
"of iedereen het moet begrijpen" mwah... dit is van developer-naar-developer, hier hoeven architecten geen mening over te hebben ;)

**Comment by ehotting** [comment]
Om het toch uit te leggen aan geïnteresseerde teamleden: als je in de API call achter het '?' (de query parameters) iets probeert wat de API niet ondersteunt moet een duidelijke foutmelding volgen. Vanzelfsprekend. :)

**Comment by RvdKlip** [comment]
Helder, maar houdt dit nu in dat we voor alle vanzelfsprekende kwaliteitsaspecten van 'nette en goede code/specificatie' aparte userstories moeten aanmaken? Bestaat er niet zoiets als Owasp voor api-gebruikers?

**Comment by ehotting** [comment]
Issues in Github zijn ook een to-do list normaalgesproken. Dingen die nog moeten gebeuren, ook kleine dingetjes - zodat het niet wordt vergeten. In dit geval netjes als user story geformuleerd om geen aanstoot te geven.  ;)
