### ISSUE TITLE
Als ontwikkelaar wil ik zonder problemen de OAS kunnen inlezen met een code generator

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#423]
...zodat ik snel aan de slag kan in mijn (populaire) programmeertaal (Java, .NET) .

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] Bij elke wijziging van de OAS wordt geverifieerd of deze zonder problemen door Java en .NET code generator gehaald kan worden.

**Taken**
- [ ] Populaire talen definiëren
- [ ] Meest gebruikte codegens uitzoeken per taal
- [ ] Jenkins inrichten voor automatische controle
- [ ] Zorgen dat controle wordt uitgevoerd bij elke PR in in Github verschijnt.

**Comment by TCIMEddy** [comment]
@joeribekker graag review m.b.t. Omschrijving

**Comment by jgortmaker1** [comment]
@TCIMEddy verkeerde PO :-)

**Comment by ehotting** [comment]
Waar komt deze vraag vandaan? Waarom zouden gebruikers van .NET (c#) en Java de standaard niet kunnen gebruiken?

**Comment by TCIMEddy** [comment]
@ehotting kwam in een overlegje met Joeri naar voren en heb ik waarschijnlijk verkeerd verwoord. Joeri gevraagd om user story te herschrijven

**Comment by joeribekker** [comment]
In het team van Bevragingen-ingeschreven-personen vragen ze nu steeds Melvin om te kijken of de OAS ingelezen kan worden door een .NET code generator. Dit leek mij vrij repetitief en een niet nuttige tijdsbesteding, en prima te vervangen door een (Jenkins) pipeline. Heb er daar ook een [issue voor aangemaakt](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/issues/46).

De rationale er achter is dat sommige populaire code generators over hun nek gaan bij sommige (valide) OAS constructies. Een voorbeeld was kommas in de tekst representaties van een enumeratie. Ook voor ZDS 1.1 waren WSDLs opgeleverd die niet door SoapUI konden worden ingelezen tot grote frustratie van leveranciers.

Het lijkt me dus wel aardig om te valideren dat dit goed gaat voor populaire talen, in alle te ontwikkelen OASen. De prio hiervan is uiteraard aan de PO maar ik werk in ieder geval de description van dit issue bij.

**Comment by joeribekker** [comment]
Eensch.
