### ISSUE TITLE
Als geïnteresseerde wil ik gestructureerde documentatie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#429]
...zodat ik makkelijk kan vinden wat ik zoek.

Op verzoek van @ArjanKloosterboer wordt de documentatie heringedeeld. De documentatie is naar zijn mening te veel versnipperd en verwijst niet duidelijk naar elkaar. Er moet een duidelijk onderscheid komen tussen technische en functionele documentatie. Deze zijn voor verschillende doelgroepen maar overlappen wel.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] ~~Voorzien van acceptatiecriteria (duidelijk en testbaar)~~ nvt
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] Documentatie is bijgewerkt met nieuwe structuur. Niet alle pagina's hoeven direct compleet te zijn.

**Taken**
- [ ] Inrichten nieuwe structuur
- [ ] Voorzien van zoveel mogelijk content
- [ ] Voorzien van relevante links naar eigen content op andere plekken
- [ ] Verwerk nuttige informatie van `documentatie.md` in andere delen.

Gerelateerd: #414, #188

**Comment by TCIMEddy** [comment]
@ehotting Graag bepalen en vinkje zetten

**Comment by TCIMEddy** [comment]
@joeribekker volgens mij staan er al wat user stories op de backlog die hier betrekking op hebben.

**Comment by joeribekker** [comment]
[WIP]

Voorstel besproken met Arjan, Sergei:

* Technische documentatie
  * Introductie tot de ZGW APIs
    * Consumers
    * Providers
    * Authenticatie en authorisaties
    * Algemene API regels en voorwaarden
  * ZGW API-guides
    * Zaak aanmaken
    * Status bijwerken
    * Document toevoegen aan Zaak
    * Besluit toevoegen aan Zaak
    * Zaak afsluiten
    * ...
  * ZGW use-cases
    * Melding openbare ruimte
    * AVG verzoek
  * Overzicht ZGW APIs
    * Zaken API
      * Verwijzing naar OAS
      * Verwijzing naar referentieimplementatie
      * API specifieke regels en voorwaarden
      * Overzicht relevante API-guides
    * Besluiten API
      * Verwijzing naar OAS
      * Verwijzing naar referentieimplementatie
      * API specifieke regels en voorwaarden
      * Overzicht relevante API-guides
    * Documenten API
      * Verwijzing naar OAS
      * Verwijzing naar referentieimplementatie
      * API specifieke regels en voorwaarden
      * Overzicht relevante API-guides
     * ...
* Functionele documentatie
    -> resources.md
    -> Arjan's API specs (Google Doc)
-> Bijdragen
    -> 

Er zit ook een aanname in verwerkt dat we de API namen gaan versimpelen.

**Comment by ArjanKloosterboer** [comment]
> Functionele documentatie
> -> resources.md
> -> Arjan's API specs (Google Doc)
> -> Bijdragen

De functionele documentatie bestaat wat mij betreft vooralsnog uit een beschrijving per API (md-document per API in [deze map](https://github.com/VNG-Realisatie/gemma-zaken/tree/master/docs/content/functioneel) ). Ik weet niet wat er in die andere twee documenten staat. 
Enneh, beginnen met de functionele documentatie en dan de technische?

**Comment by ehotting** [comment]
Wat afhankelijkheden met evt. move naar Jekyll etc. - niet in komende sprint

**Comment by TCIMEddy** [comment]
@joeribekker Als Eelco morgen tijdens de demo laat zien hoe e.e.a. te vinden is kan deze user story dan gesloten worden of moet er nog wat gebeuren?
