### ISSUE TITLE
Als KCC medewerker wil ik een lijst van meldingen zien met de status en behandelaar...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#43]
... zodat ik zie welke meldingen moeten opgevolgd worden.

* ASCM = actieservicecentrummedewerker (naamgeving Amsterdam)
* KCC = klantcontactcentrum (naamgeving Haarlem)

**Comment by jgortmaker1** [comment]
als ik door mijn oogharen naar alle -water- USsen kijken, denk ik dat een ASCM in het geval van amsterdamse meldingen meer met een melding moet kunnen doen dan een gemiddelde KCC-medewerker met een willekeurige andere zaak kan doen.
ACSM medewerker moet dus toegang hebben tot MOR-afhandelsysteem. We moeten oppassen niet teveel (maar ook net te weinig!) van deze gevraagde functionaliteit in de ZDS te stoppen..

**Comment by sergei-maertens** [comment]
@jgortmaker1 welk systeem er bovenop de zaakservices ligt is hier ook niet relevant - het schetst alleen context. Dat kan MOR-afhandelsysteem zijn wat een koppeling heeft met zaakservices. Kern is dat het via de API mogelijk moet zijn om een status en behandelaar (betrokkene?) op te vragen bij een lijst van zaken.

Dit specifieert dus verder _welke_ informatie nodig is in de response van het equivalent van `geefLijstZaken`

**Comment by jgortmaker1** [comment]
een standaard KCC-medewerker kan van alle/veel zaken de gebruikelijke velden zien: wat loopt er, wie is de afhandelaar, wat is de status, wat is de afhandeldatum. Etc. That's it.
Als een ASC-medewerker moet kunnen zien welke meldingen opgevolgd moeten worden, of meer nog: kunnen ingrijpen in de afhandeling (prioriteren, extra info doorgeven, etc): dan lukt dat niet met enkel zaakinformatie en zaakservices.

Tot op zeker hoogte kun je deze er wel voor misbruiken, maar dat is hier niet de bedoeling.

Achter een melding zitten veel verschillende processen voor het oplossen hiervan: melding doorgeven aan politie, registreren en pas iets doen na 3 voorkomens, handhavingsmedewerker op pad sturen, bestuurlijk sanctie voor een rederij. Dit verzin ik ter plekke, er is vast meer mogelijk.

Als er iemand belt die wil weten hoe ver het met een melding staat, en wil je daar meer inzicht in geven dan "het is in behandeling"...en heb je m.i. toegang nodig tot het meldingen-systeem..

als de hele wereld zaakgericht werkt en al die vervolgacties staan als gerelateerde zaken in dezelfde ZRC, dan kom je wellicht nog best een eind...maar in de toekomst kom je functionele in de knel schat ik in..

**Comment by ehotting** [comment]
Graag een update van @jgortmaker1 & @MarcelMoerman - wat is belang van deze user story gelet op actuele inzichten?

**Comment by Hugo-ter-Doest** [comment]
Ik vat de user story op zoals Sergei heeft geïnterpreteerd hierboven. Ik vermoed dat deze functionaliteit er al is @sergei-maertens ?

**Comment by sergei-maertens** [comment]
@Hugo-ter-Doest ja, via `GET /api/v1/zaken` en `GET /api/v1/rollen` met de relevante filters :)
