### ISSUE TITLE
Als ontwikkelaar wil ik een overzicht van business logica IMZTC

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#432]
...zodat ik deze ter referentie kan raadplegen tijdens het implementeren.

En, kan verwerken in de technische documentatie waar relevant.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Acceptatiecriteria**
* [ ] Documentatie is bijwerkt en overzichtelijk

**Definition of done**
* [ ] Functionele documentatie is bijgewerkt met regels
* [ ] Technische documentatie is bijgewerkt met regels

**Taken**
- [ ] Opleveren huidige lijst aan regels uit RGBZ en ZTC [@ArjanKloosterboer]
- [ ] Technische documentatie bijwerken met regels [@joeribekker]

**Comment by TCIMEddy** [comment]
@ehotting graag ook jouw wensen vanuit jou als PO opnemen

**Comment by joeribekker** [comment]
Dat is wat Arjan aangaf ja, vandaar dat ik Arjan assigned heb.

**Comment by ArjanKloosterboer** [comment]
Als er dat bedoeld wordt, dat kan ik maken ja.

**Comment by michielverhoef** [comment]
In verband met tijd: als kan ik hier nog bij helpen?

**Comment by ehotting** [comment]
Als ik dit goed begrijp gaat het om de manier waarop de API bepaalde bewerkingen uitvoert met data alvorens deze te serveren. De enige manier om daar nu achter te komen is te kijken in de broncode van de referentie-implementatie, dat is onwenselijk. Wat mij betreft dus zeer wenselijk om dit (zo kort mogelijk!) op te nemen in de technische documentatie. Dit kan niet worden gegenereerd vanuit RGBZ, daarvoor wijken we al te sterk af. De enigen die dit kunnen opleveren zijn volgens mij de makers van de referentieimplementatie, of iemand die de code van de referentieimplementatie leest en doorgrondt.

Graag nog wel even userstory compleet maken zodat we hem idd in sprint 5 kunnen oppakken.

**Comment by joeribekker** [comment]
> Als ik dit goed begrijp gaat het om de manier waarop de API bepaalde bewerkingen uitvoert met data alvorens deze te serveren.

Klopt, aangevuld met allerhande validatieregels op attributen bij het opslaan/aanpassen van data, en andersoortige regels.

> De enige manier om daar nu achter te komen is te kijken in de broncode van de referentie-implementatie, dat is onwenselijk.

Dat is niet waar. Deze staan zo goed mogelijk verwoord op OAS attribuut niveau.

> Wat mij betreft dus zeer wenselijk om dit (zo kort mogelijk!) op te nemen in de technische documentatie. Dit kan niet worden gegenereerd vanuit RGBZ, daarvoor wijken we al te sterk af. De enigen die dit kunnen opleveren zijn volgens mij de makers van de referentieimplementatie, of iemand die de code van de referentieimplementatie leest en doorgrondt.

Niet helemaal mee eens, ik wil echt inzicht in de huidige regels van RGBZ. Ik had eerst in mijn hoofd zitten dat deze US vooral het opleveren van de regels betrof door Arjan uit het huidige RGBZ. Nu denk ik dat dat een taak is binnen deze US en dat het doel inderdaad is om hier (kort!) documentatie van te maken.

**Comment by ehotting** [comment]
Helder. Heb "RGBZ" toegevoegd aan titel en Prio gewijzigd.

**Comment by ehotting** [comment]
N.a.v. dicussie tijdens backlog refinement een ander begrip gekregen van de user story. Wat nodig is: een overzicht van alle business logica uit de RGBZ, welke we vervolgens als input kunnen gebruiken bij het maken van de API. Het is dus niet zo dat automatisch alle business logica in de API moet worden opgenomen - het is input ter overweging, zodat we zeker weten dat geen relevante dingen over het hoofd zien. 

Hierdoor verander ik prio naar Hoog, dit kan maar beter z.s.m. geregeld zijn.

**Comment by ArjanKloosterboer** [comment]
Ik heb het overzicht gemaakt van de regels in het RGBZ. Je treft ze aan in het onderstaande document. Als dit voldoet maak ik eenzelfde overzicht van het ImZTC.
[RGBZ Regels.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/2512226/RGBZ.Regels.docx)

**Comment by TCIMEddy** [comment]
@ehotting @joeribekker graag review indien nog niet gedaan naar Arjan zodat hij ook ImZTC kan doen

**Comment by joeribekker** [comment]
@ArjanKloosterboer Dank! Het is in ieder geval iets overzichtelijker dan 150 pagina's :)

2 observaties:

1. Het zijn vooral validatieregels (prima, maar dacht dat er meer business logica zou zijn - de scheidingslijn is wellicht dun)

2. Er staan afleidbare gegevens in het IM. Ik was in de veronderstelling dat dat niet het geval was. Hiermee wordt de scheidingslijn tussen een API spec en informatie model nog dunner. Ik nam bijvoorbeeld op bij Statustype, het attribuut "isEindstatus" (afleidbaar uit volgnummer binnen Zaaktype). Ik verwacht (en kreeg de indruk ook niet van jou) dan niet dat deze zijn weg terug vind in het IM? Waar ligt de grens?

**Comment by ArjanKloosterboer** [comment]
Ad. 1, interessant, wat is business-logica? In een informatiemodel lijkt het alleen te gaan over de consequenties van business-logica voor de integriteit van informatie. Of is dat ook business-logica? 
Ad. 2, afleidbare gegevens in een informatiemodel is een continu punt van discussie. Als ze er in staan, dan is dat bewust. Eén van de doelen van een informatiemodel is het specificeren van de informatie die (over objecten) beschikbaar geacht wordt te zijn en die een gebruiker niet hoeft af te leiden ergens uit. Vandaar dat bijvoorbeeld 'Einddatum' is opgenomen bij ZAAK omdat eenduidige informatie over de zaak beschikbaar dient te zijn of deze beeindigd is en zo ja, wanneer. Dit betekent dat de gebruiker (de business) dit niet zelf hoeft af te leiden uit andere informatie maar dat eenduidig kan raadplegen. 

@joeribekker, voorziet deze opzet in je behoefte of heb je bijvoorbeeld liever één grote tabel, in Excel oid?

**Comment by joeribekker** [comment]
Voor mij is dit genoeg, erg handig!

**Comment by TCIMEddy** [comment]
wat mij betreft gereed

**Comment by ArjanKloosterboer** [comment]
@joeribekker Niet nodig voor het ImZTC?

**Comment by joeribekker** [comment]
> @joeribekker Niet nodig voor het ImZTC?

Ha @ArjanKloosterboer Ja, toch wel :) Kan jij dat makkelijk uitdraaien en toevoegen hier?

**Comment by TCIMEddy** [comment]
@Remkodehaas Kun jij dit oppakken. Bij onduidelijkheden hoor ik het wel.

**Comment by Remkodehaas** [comment]
Hierbij de 'regels' uit imZTC in 2 documenten

[regels Objecttypen en Relatieklassen .docx](https://github.com/VNG-Realisatie/gemma-zaken/files/2807368/regels.Objecttypen.en.Relatieklassen.docx)
[regels Gegevensgroeptypen .docx](https://github.com/VNG-Realisatie/gemma-zaken/files/2807370/regels.Gegevensgroeptypen.docx)
