### ISSUE TITLE
RGBZ Mapping bij US #303

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#435]
Mapping van velden behorend bij user story #303. 

Stap 1. Zaak bijwerken met een indicatie (tijdelijk) en een reden van opschorting. Antwoord is bevat geregistreerde gegevens
Stap 2. Informatieobject toevoegen
Stap 3. ObjectInformatieobject toevoegen - Informatieobject aan zaak koppelen

### Request ZRC (Zaak Update)
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| -- | -- | -- | -- |
| `Zaak.Opschorting zaak.Indicatie opschorting` |   | INDIC | Aanduiding of de behandeling van de ZAAK tijdelijk is opgeschort. Waarde: TRUE |
| `Zaak.Opschorting zaak.Reden opschorting` |   | AN200 | Omschrijving van de reden voor het opschorten van de behandeling van de zaak. Waarde: 'Verzoek om aanvullende gegevens gedaan bij de aanvrager.' |

### Answer ZRC (Nieuwe einddata)
| Return ZRC | Veld | Datatype | Verklaring |
| -- | -- | -- | -- |
| `Zaak.Opschorting zaak.Indicatie opschorting` |   | INDIC | Aanduiding of de behandeling van de ZAAK tijdelijk is opgeschort. Waarde: TRUE |
| `Zaak.Opschorting zaak.Reden opschorting` |   | AN200 | Omschrijving van de reden voor het opschorten van de behandeling van de zaak. Waarde: 'Verzoek om aanvullende gegevens gedaan bij de aanvrager.' |

### 2 Request DRC (Informatieobject toevoegen)
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| -- | -- | -- | -- |
|`ENKELVOUDIGINFORMATIEOBJECT. Formaat` | `Formaat` | AN255 | De code voor de wijze waarop de inhoud van het   ENKELVOUDIG INFORMATIEOBJECT is vastgelegd in een computerbestand. |
|`ENKELVOUDIGINFORMATIEOBJECT. Taal` | `Taal` | enum Taal | Een taal van   de intellectuele inhoud van het ENKELVOUDIG INFORMATIEOBJECT. De waardes   komen uit ISO 639-2/B |
|`ENKELVOUDIGINFORMATIEOBJECT. Inhoud` | `Inhoud` | AN | Datgene wat in een ENKELVOUDIG INFORMATIEOBJECT wordt meegedeeld. |
|`ENKELVOUDIGINFORMATIEOBJECT. Link` | `Link` | AN200 | De URL waarmee de inhoud   van het INFORMATIEOBJECT op te vragen is. |
|`ENKELVOUDIGINFORMATIEOBJECT. Informatieobject` | `Informatieobject`  |  | Geheel van gegevens met een eigen identiteit ongeacht zijn vorm, met de bijbehorende metadata ontvangen of opgemaakt door   een natuurlijke en/of rechtspersoon bij de uitvoering van taken. |
|`(ENKELVOUDIG)INFORMATIEOBJECT. Informatieobjectidentificatie` | UUID | AN40 | Een binnen een gegeven   context ondubbelzinnige referentie naar het INFORMATIEOBJECT. |
|`(ENKELVOUDIG)INFORMATIEOBJECT. Bronorganisatie` | `Organisatie` | AN9 | Het RSIN van de Niet-natuurlijk persoon zijnde de   organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en   als eerste in een samenwerkingsketen heeft vastgelegd. |
|`(ENKELVOUDIG)INFORMATIEOBJECT. Creatiedatum` | `Creatiedatum` | DATUM | Een datum of een   gebeurtenis in de levenscyclus van het INFORMATIEOBJECT. |
|`(ENKELVOUDIG)INFORMATIEOBJECT. Titel` | `Titel` | AN200 | De naam waaronder het INFORMATIEOBJECT formeel bekend is. |
|`(ENKELVOUDIG)INFORMATIEOBJECT. Auteur` | `Auteur` | AN200 | De persoon of organisatie die in de eerste plaats verantwoordelijk is voor het creëren van de inhoud van het INFORMATIEOBJECT. |
|`(ENKELVOUDIG)INFORMATIEOBJECT. Beschrijving` | `Beschrijving` | AN1000 | Een generieke   beschrijving van de inhoud van het INFORMATIEOBJECT. |
|`(ENKELVOUDIG)INFORMATIEOBJECT. Verrtouwelijkheidaanduiding` | `Vertrouwelijkheid` | enum Vertrouwelijkheid aanduiding | Aanduiding van de mate waarin het INFORMATIEOBJECT voor de openbaarheid bestemd is. Waarde = ZAAKVERTROUWELIJK|
|`(ENKELVOUDIG)INFORMATIEOBJECT. Informatieobjecttype` | `Type` | AN200 | URL naar de  Informatieobjecttype 'Verzoek aanvullende gegevens' in het ZTC. |

(ENKELVOUDIG)INFORMATIEOBJECT is een verwijzing naar het het feit dat INFORMATIEOBJECT en ENKELVOUDIGINFORMATIEOBJECT in de API-specificatie zijn samengevoegd.

### Answer DRC (InformatieobjectID)
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| -- | -- | -- | -- |
| `(ENKELVOUDIG)INFORMATIEOBJECT. Informatieobjectidentificatie` | `InformatieobjectID` |  AN40 | Uniek volgnummer informatieobject |

### 4. Request DRC (Informatieobject aan zaak koppelen)
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| -- | -- | -- | -- |
| `OBJECTINFORMATIEOBJECT. Zaak` | `Zaak` | AN200 | URL naar de zaak in de ZRC |
| `OBJECTINFORMATIEOBJECT. Informatieobject` |   | AN200 | URL naar het informatieobject |

### Answer DRC (De gekoppelde objecten)
| RGBZ mapping | Veld in huidige app | Datatype | Verklaring |
| -- | -- | -- | -- |
| `OBJECTINFORMATIEOBJECT. Zaak` | `Zaak` | AN200 | URL naar de zaak in de ZRC |
 |`OBJECTINFORMATIEOBJECT. Informatieobject` | `Informatieobject`  | AN200 | URL naar het informatieobject |

**Comment by ArjanKloosterboer** [comment]
Lijkt me goed zo. Wel een vraag.
Je verlengt de zaak vanwege het verzoeken om aanvullende informatie. Is het niet voor de hand liggender om de zaak op te schorten totdat de informatie is ontvangen (of totdat de termijn voor het aanvullen is verlopen)? Op het moment dat de info is ontvangen gaat de zaak weer lopen en wordt deze verlengd met de termijn van de opschorting. Dat kan 3 dagen zijn maar ook twee weken.

**Comment by EdwinCoster** [comment]
@ArjanKloosterboer Dat ligt inderdaad meer voor de hand. Ik pas het aan.

**Comment by ArjanKloosterboer** [comment]
Ik mis nog de Vertrouwelijkheidaanduiding van het Informatieobject. Als je die niet meegeeft, wat is dan de vertrouwelijkheid? Openbaar? Of alleen toegankelijk voor de auteur? Of ...?

**Comment by EdwinCoster** [comment]
Vertrouwelijkheidaanduiding toegevoegd. En het is in dit geval 'ZAAKVERTROUWELIJK'.

**Comment by michielverhoef** [comment]
#303 is gesloten, deze hoort daarbij dus die sluit ik ook maar.
