### ISSUE TITLE
Als gebruiker van MijnApp wil ik een overzicht van al mijn zaken en bijhorende status bij mijn gemeente zien

### ISSUE THREAD

**Issue by ppcjansen** [VNG-Realisatie/gemma-zaken#44]
**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [x] Opstellen welke velden bij een opvraag zaken en statussen [@ppcjansen]
- [ ] Aanleveren testdata [@ppcjansen]
- [ ] Schrijven (unit) test voor referentie-implementatie [@joeribekker]
- [ ] Implementeren in referentie-implementatie [@joeribekker]
- [ ] Genereren/opstellen van OAS 3.0 [@joeribekker]
- [ ] Functionele documentatie [@michielverhoef ]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [?]

**Comment by ArjanKloosterboer** [comment]
Is er al nagedacht wat 'mijn zaken' inhoudt? Zaken waarvan ik de initiator ben of ook zaken waarbij ik in een andere rol zit (wsl. alleen belanghebbende)? En ook over hoe om te gaan met vertrouwelijkheid (attribuutsoort Vertrouweljkheidaanduiding)? En alleen lopende zaken of ook afgeronde zaken? Oftewel, wat zijn de selectiecriteria voor mijn zaken?

**Comment by ppcjansen** [comment]
[Attributen-ZDS-API-US_44.xlsx](https://github.com/VNG-Realisatie/gemma-zaken/files/2089982/Attributen-ZDS-API-US_44.xlsx)

**Comment by ppcjansen** [comment]
In bijgevoegd bestand de mapping van de RGBZ-objecten en attributen. Ik weet niet zeker of de laatste 3 attributen goed benoemd zijn. In essentie gaat het erom dat de ZAAKen inclusief de STATUSsen van die ZAAKen (waarvan hij/zij de Initiator is) getoond worden via het BSN van de gebruiker van MijnApp. Ik dacht dat het daarbij logisch is de BETROKKENE, ROL en NATUURLIJK PERSOON mee te nemen. Als dit via een ander mechanisme verloopt, verneem ik dat graag.

**Comment by TCIMEddy** [comment]
@ehotting Ondanks dat Eindhoven geen tijd heeft zijn het uiteraard relevante user stories

**Comment by ehotting** [comment]
Is er een architectuurschets?

**Comment by ehotting** [comment]
Zonder specifieke architectuur & RGBZ mapping kan deze user story geen wijzigingen tot gevolg hebben in de API spec. Daarom sluit ik deze. Als MijnApp weer opgepakt wordt kunnen we deze heropenen.
