### ISSUE TITLE
Als record manager wil ik een reeds afgesloten zaak kunnen heropenen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#442]
zodat een afgesloten zaak weer heropend kan worden door een behandelaar.
Gerelateerd aan: #409 & #351
**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ArjanKloosterboer** [comment]
> ... zodat een onterecht/per ongeluk afgesloten zaak weer verder behandeld kan worden door een behandelaar.

Gaat het inderdaad om het heropenen opdat de behandeling weer ter hand genomen kan worden of om het alsnog aanbrengen van enkele wijzigingen? In het eerste geval lijkt me dat geen taak voor de recordmanager maar voor de zaakverantwoordelijke dan wel een door hem/haar gemandateerde (functioneel beheerder oid). Dat moet dan sterk geautoriseerd kunnen worden (alleen die personen cq. rollen). Maar wat dan? Laatste zaakstatus verwijderen? Einddatum zaak wissen?

**Comment by CMasselink** [comment]
Het gaat in deze userstory inderdaad om het eerste: het heropenen zodat de zaak weer ter hand genomen kan worden. 
Bij wie de verantwoordelijkheid ligt, kan inderdaad over gediscussieerd worden. De zaakverantwoordelijke is ook een logische. Eens wat betreft autorisaties. Hieruit blijkt dus de wens om te kunnen autoriseren op het heropenen van een zaak.

Wat betreft het heropeningsmechanisme:
Er zijn denk ik een paar mogelijkheden: 
Inderdaad de einddatum van de zaak wissen (de zaak was immers op de eerder ingegeven datum feitelijk nog niet klaar). Als we het afsluiten van een zaak koppelen aan het feit dat de laatste zaakstatus is bereikt, zal de laatste status inderdaad ook gewijzigd moeten worden naar een eerdere status. Dat kan overigens wel weer allerlei (mogelijk ongewenste) gevolgen hebben indien er applicaties zijn die acteren op het bereiken van een bepaalde status (automatische communicatie naar burger/bedrijf bijvoorbeeld).

Een andere optie/workaround, die ook voor #409 bruikbaar kan zijn:"
Onderscheid maken tussen de statussen 'afgehandeld' en 'afgesloten'.
Waarbij 'afgehandeld' staat voor het afronden van alle processtappen. Doorlooptijden etc. zouden dan ook berekend moeten worden op basis van het bereiken van deze status. Na het bereiken van de status 'afgehandeld' blijft de zaak tot X termijn open en wordt automatisch afgesloten na het verstrijken van deze termijn. In de termijn tussen afgehandeld en afgesloten kan de zaak indien noodzakelijk nog gemuteerd en gecompleteerd worden. Hiermee kan je het aantal gevallen dat een zaak heropend moet worden, beperken. Vraag blijft dan uiteraard wat er moet gebeuren als ook na het verstrijken van de termijn, en dus afsluiten zaak, nog een relevant document/informatieobject nagezonden wordt.

**Comment by TCIMEddy** [comment]
@ehotting wil jij deze voorzien van jouw visie, goedkeuring en prio

**Comment by ArjanKloosterboer** [comment]
Creatief voorstel, "Onderscheid maken tussen de statussen 'afgehandeld' en 'afgesloten'",  maar m.i. is dit slechts het verschuiven van het probleem (zoals je verderop al aangeeft) en niet het structureel oplossen er van. Ook als men er na 'afgehandeld' en voor 'afgesloten' achterkomt dat de behandeling nog niet goed is voltooid, dan moet je iets met die status 'afgehandeld'. En op mij komt het vreemd over: de zaak is afgehandeld maar blijkbaar toch ook niet. Dus nog even verder doordenken naar een echt structurele oplossing.

**Comment by RvdKlip** [comment]
Wat is de ratio achter het niet mogen heropenen van een gesloten zaak? Misschien is dat beter op een andere manier te regelen.

**Comment by ArjanKloosterboer** [comment]
Uit het voorafgaande wordt m.i. duidelijk dat een afgehandelde en daarmee afgesloten zaak heropend moet kunnen worden. Dat lijkt me dus niet (meer) de discussie. De vraag is hoe we dat gaan doen. 
In breder verband gaat het dan om een administratieve correctie, een verschijnsel dat we vaker zullen tegenkomen. Geen 'normaal' business-proces maar wel iets waarin voorzien moet zijn.

**Comment by TCIMEddy** [comment]
@ehotting Ik heb alle eigenaren eraf gehaald, wil jij eerst prioriteit toekennen

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest graag visie en prio

**Comment by Hugo-ter-Doest** [comment]
Dit kan al door een status toe te voegen die geen eindstatus is.

**Comment by michielverhoef** [comment]
Dat het technisch kan snap ik maar mag het ook? In het RGBZ stond ooit iets van de strekking dat een zaak die een eindstatus heeft bereikt niet meer aangepast mag worden. Dus dan zou ook de status niet meer aangepast mogen worden lijkt mij?

**Comment by Hugo-ter-Doest** [comment]
Er moet een inventarisatie worden gemaakt van welke velden leeg moet worden gemaakt.

**Comment by CMasselink** [comment]
@Hugo-ter-Doest & @MarcoKlerks: 
Wat is ook al weer de rationale bij het leeggooien van alles wat bij een resultaat hoort bij het heropenen van een zaak?
Kunnen jullie ook helpen bij het opstellen van de regels:
Bij het heropenen van de zaak wordt er:
- een nieuwe status gezet, anders dan een eindstatus
-Worden deze X velden behorende bij een resultaat leeg gegooid.

De vraag is ook of de API moet gaan herkennen dat er eerst een eindstatus + resultaat op een zaak heeft gezeten en dat er daarna een andere status dan een eindstatus is ingevuld en dat dan als gevolg daarvan er allerlei zaken met resultaat gedaan moet worden.

**Comment by sergei-maertens** [comment]
@CMasselink de API herkent dat al op dit moment en maakt `Zaak.einddatum` leeg als gevolg

**Comment by Hugo-ter-Doest** [comment]
Heb het niet meer zo scherp voor ogen. Ik dacht dat je resultaat leegmaakt omdat je bij heropenen van de zaak van alles kunt aanpassen en dan opnieuw moet bepalen wat het resultaat is. Besluiten zijn van een andere orde: als je een nieuw besluit toevoegt, dan haal je wsch. het oude besluit niet weg, omdat je dit voor zaakhistorie wilt bewaren incl. ev. informatieobjecten.

**Comment by joeribekker** [comment]
Het is nu mogelijk om het RESULTAAT te verwijderen (of te wijzigen). Een nieuw RESULTAAT zetten leidt ook tot herberekening van de archiefactiedatum indien mogelijk.

Verder is heropenen vooral een kwestie van goed consumer gedrag aangezien we op provider niveau dit niet dicht gaan timmeren.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest In het kader van afronden van user stories kun jij wellicht ook goed antwoord geven op de vraag van Joeri.

**Comment by CMasselink** [comment]
@joeribekker Nee dat is nog niet voldoende. Zie ook de opmerking van Marco: als een zaak heropend wordt, is er een redelijke kans dat het resultaat veranderd kan zijn. Gewenst gedrag is dus eigenlijk nog steeds dat als een zaak heropend wordt doordat er een status wordt toegevoegd die geen eindstatus is, resultaat + bijbehorende velden rond archiefactiedatum etc. leeg gemaakt worden.

**Comment by Hugo-ter-Doest** [comment]
Ik wil het aan de consumer overlaten of het resultaat gewist wordt. Als je dit in de ZRC inbakt, ben je minder flexibel. Als de consumer het wil, kan deze het resultaat verwijderen, maar hoeft niet.

**Comment by CMasselink** [comment]
@Hugo-ter-Doest als we inderdaad de keuze maken dat de client dit moet doen, moeten we dat wel ergens beschrijven. Opnemen in de ontwerpkeuzes? 
We moeten denk ik ook goed kunnen beantwoorden waarom we bepaalde dingen wel en niet aan een consumer overlaten. Bij het zetten van een andere status dan een eindstatus, laten we de api namelijk wel de einddatum verwijderen. Dit zou de consumer in theorie ook kunnen doen. Nu maken we voor dit issue een andere keuze. Hebben we zelf helder wat onze criteria zijn om bij dit issue geen logica in te bouwen en bij de andere wel?

**Comment by Hugo-ter-Doest** [comment]
Ja, die einddatum is m.i. onlosmakelijk verbonden met de eindstatus. Het resultaat niet. I.i.g. documenteren lijkt me.

**Comment by CMasselink** [comment]
Ok, ik heropen het issue even voor het afronden van het documenteren van het resultaat van deze userstory. 
@sergei-maertens / joeribekker : ik wil dit wel ergens documenteren maar wat is de handigste plek, standaard.md?

**Comment by sergei-maertens** [comment]
@CMasselink inderdaad, `standaard.md` is de plek hiervoor

**Comment by CMasselink** [comment]
Voorstel voor documentatie staat in PR #815.
Wat nog wel geïmplementeerd moet worden in de API: het leeghalen van de archiefactiedatum en archiefnominatie indien door de client een resultaat wordt verwijderd.

**Comment by joeribekker** [comment]
De concrete implementatie is overigens hier: https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/50

Dit introduceert een nieuwe scope omdat het toch wel een apart dingetje is: zds.scopes.zaken.heropenen

**Comment by sergei-maertens** [comment]
Is gemerged, moet nog wat tekstuele/documentatie updates krijgen
