### ISSUE TITLE
Hoort Klantcontact in ZRC API?

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#446]
Zie https://ref.tst.vng.cloud/zrc/api/v1/schema/#tag/klantcontacten

Wat is het nut van deze informatie in de ZRC?
Ligt het niet meer voor de hand een aparte, rijkere API te hebben, gevoed door een CRM, van waaruit klantcontacten gelinkt kunnen worden aan de ZRC objecten?

**Comment by CMasselink** [comment]
Conceptueel ben ik het er mee eens. Ik kan me overigens wel voorstellen dat gemeenten een soort generiek zaakafhandelcomponent maken waarbij zowel klantcontacten als zaken zichtbaar zijn. Vanuit een klantcontact zou dan eenvoudig een zaak gemaakt moeten kunnen worden. 
Wel belangrijk dat vanuit een zaak, eenvoudig de bijbehorende klantcontacten opgehaald kunnen worden. Maar dat zou kunnen met het ophalen van alle zaakobjecten van het type 'klantcontact'.
Gezien we voorlopig waarschijnlijk nog niet kunnen koppelen aan een CRM op de manier zoals wij zouden willen, tijdelijk maar in het overige registratiecomponent opnemen?

**Comment by ArjanKloosterboer** [comment]
Een rijkere API, CRM-achtig, ligt inderdaad voor de hand. Met zowel klanten als klantcontacten en meer dan alleen klantcontacten i.r.t. zaken. Voor nu zijn klantcontacten gemodelleerd in RGBZ 2, dat zal de reden zijn voor de nu voorliggende API. De volgende stap is het opsplitsen van het RGBZ waaronder het afsplitsen van het klantencontactgedeelte en dat dan generieker maken (zie blz. 2 en 3 van [deze notitie](https://www.gemmaonline.nl/images/gemmaonline/2/29/EgIM_20180927_ag_4_-_Aanpassingen_RGBZ.pdf)). Het is m.i. afhankelijk van userstorys of we dat in dit traject nog gaan doen. 

> Wel belangrijk dat vanuit een zaak, eenvoudig de bijbehorende klantcontacten opgehaald kunnen worden. Maar dat zou kunnen met het ophalen van alle zaakobjecten van het type 'klantcontact'.
> Gezien we voorlopig waarschijnlijk nog niet kunnen koppelen aan een CRM op de manier zoals wij zouden willen, tijdelijk maar in het overige registratiecomponent opnemen?

Een klantcontact is geen zaakobject. Een aangezien klantcontacten gemodelleerd zijn in her RGBZ vallen ze onder de ZRC totdat ze in een eigen model ondergebracht zijn.

**Comment by jgortmaker1** [comment]
discussie is al eens gevoerd. zie comments onder #395 (en reacie van Arjan)
apart bakje voor klantcontacten dus. vergelijkbaar met besluiten..

**Comment by TCIMEddy** [comment]
@jgortmaker1 close omdat discussie gevoerd is

**Comment by sergei-maertens** [comment]
Yep, gaan we t.z.t. verhuizen. Heeft verder geen grote implicaties denk ik.
