### ISSUE TITLE
Als KCC medewerker wil ik een behandelaar kunnen toewijzen...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#45]
... zodat de melding kan worden gerouteerd.

**Links**
* [ZRC pull request](https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/12)
* [ZTC pull request](https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/7)
* [integratietests](https://github.com/VNG-Realisatie/gemma-zaken-test-integratie/pull/4)
* #296

**API spec aanpassingen**
(nog) geen

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story en ziet de toegevoegde waarde.
- [x] Userstory is ingevuld op template architectuurschets
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van definition of Done (duidelijk en testbaar)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd. 
- [x] Vastgelegd Github en in geplaatst in kolom ready
- [x] Userstory is voorzien van veldmapping naar RGBZ2
- [x] Userstory past op wenselijk gebruik ZGW volgens GEMMA 2

(Op termijn ook -> Business Waarde en story points zijn bepaald.)

**Definition of done**
- [x] er is een OAS 3.0 specificatie
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [x] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [x] Voldoet aan GEMMA 2.0

**Taken**
- [x] Architectuurschets opleveren [Marcel Moerman]
- [x] Beschrijven welke data er wordt gemuteerd bij uitvoeren van deze functie [_verantwoordelijke_]
- [x] Aanleveren testdata [_verantwoordelijke_]
- [x] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [x] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [x] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Architectuurschets**
Architectuurschets is hier #180 te vinden.

Voor de selectie van de behandelaar wordt er uit de ZTC een relevant Zaak_type selecteert, de zaak kan worden geüpdate met de juiste Organisatorische-eenheid.

### Select op ZTC API
| Attribuut | OPERATIE |
| :--- | :--- |
| ZTC.ZAAKTYPE.Zaaktype-omschrijving | READ |
| Organisatie-eenheid-identificatie | READ |

### Update op  ZRC API
| Attribuut | OPERATIE |
| :--- | :--- |
| ZTC.ZAAKTYPE.Zaaktype-omschrijving | WRITE |
| Organisatie-eenheid-identificatie | WRITE |

**Comment by jgortmaker1** [comment]
ik weet niet of dit de geëigende weg is..hangt natuurlijk van proces tot proces en van de gemeente af..
maar ik zou zeggen: een zaak wordt in behandeling genomen in de backoffice en daar wordt een behandelaar toegekend.
een KCC medewerker kan status inzien en notities oid (klantcontacten??) toevoegen om de prioriteit aan te geven..

moet hier iets generieks op het procesniveau worden uitgewerkt, of kunnen we zonder verder?

overigens is een zaak (itt zoals het vaak wordt ingezet) ook niet bedoeld om de afhandeling te sturen, maar om mensen te informeren over de status van een zaak..

**Comment by jgortmaker1** [comment]
zie https://www.gemmaonline.nl/index.php/GEMMA_2_Katern_Zaakgericht_Werken

_> "Zaakgericht werken is dus (itt. bijvoorbeeld een workflow-systeem) geen methodiek om medewerkers de juiste dingen te laten doen. De medewerker wordt geacht zelf te weten wat hij of zij moet doen (taakvolwassen medewerker, kenniswerker). Wanneer ondersteuning van medewerkers of verantwoording op een meer gedetailleerd niveau nuttig of noodzakelijk is, is er additionele workflow-, BPM-of specialistische ondersteuning noodzakelijk"_

**Comment by jgortmaker1** [comment]
de behandelend ambtenaar lijkt me niet iets dat (automatisch) inzichtelijk mag zijn voor de burger..

de bovenliggende applicatie (MOR-applicatie) selecteert inderdaad de behandelaar. handmatig of automatisch. Dat hangt van het proces af.

Bovenstaande impliceert echter dat een KCC medewerker door het "aanwijzen" van een behandelaar iemand zou kunnen "sommeren" om te starten met behandelen..
Bovendien werkt een KCC-medewerker in de regel niet met de afhandelende applicatie...en speelt dus geen rol in het toewijzen van behandelaars

**Comment by sergei-maertens** [comment]
@MarcelMoerman 

De interactie/flow hier was niet 100% helder in dit US, maar het komt erg overeen met wat in #169 beschreven staat.

Er is in https://github.com/VNG-Realisatie/gemma-zaken-test-integratie/blob/feature/us-45-behandelaar-toewijzen/tests/test_userstory_45.py (Python test case) een dergelijk scenario uitgewerkt. Het komt neer op het volgende:

**gegeven een ZAAKTYPE**

Vraag op wie de mogelijke behandelers zijn:

```http
GET /ztc/api/v1/catalogus/<uuid>/zaaktype/<uuid>/roltypen?omschrijvingGeneriek=Behandelaar

[{
    "url": "https://example.com/ztc/api/v1/catalogus/<uuid>/zaaktype/<uuid>/roltypen/<uuid>",
    "omschrijvingGeneriek": "Behandelaar",
    "mogelijkeBetrokkenen": [{
        "betrokkene": "https://example.com/api/betrokkenen/1234",
        "betrokkeneType": "Organisatorische eenheid"
    }]
    ...
}]
```

Je kan dus de (eerste) mogelijke betrokkene uitlezen, en die voeg je toe als rol aan de zaak:

```http
POST /zrc/api/v1/rollen

{
    "zaak": "https://example.com/zrc/api/v1/zaken/<uuid>",
    "betrokkene": "https://example.com/api/betrokkenen/1234",
    "betrokkeneType": "Organisatorische eenheid",
    "rolomschrijving": "Behandelaar",
    "roltoelichting": "Lorem Ipsum...",
}
```

Indien een KCC-medewerker een behandelaar moet toewijzen, dan kan alsnog de (generieke) zaakafhandelcomponent uit het ZTC de mogelijke roltypen en bijhorende mogelijke rollen uitlezen, zodat deze als optie getoond kunnen worden aan de medewerker. Als de medewerker dan in een formulier of applicatie een behandelaar aanduidt, dan voert dat formulier/applicatie de tweede call uit om de rol te zetten voor de zaak.

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer nog geen vinkje rgbz
@jgortmaker1 nog geen vinkje gemma2
Ik zet deze terug naar de review kolom

**Comment by jgortmaker1** [comment]
wat moet ik precies reviewen?
Volgens mij is dit een US die niet past op wenselijk gebruik ZGW in GEMMA (zie eerdere opmerkingen boven). Maar de API-calls van 13 dagen geleden hierboven zijn dan weer zo generiek dat er daar vwb GEMMA geen probleem lijkt (want geen link met GEMMA)...

**Comment by TCIMEddy** [comment]
@jgortmaker1 Snap ik, en dit is voor nu ook even voldoende en zo leren we wanneer we jij echt iets moet doen of zeggen

**Comment by joeribekker** [comment]
@jgortmaker1 Wat is "wenselijk gebruik"?

**Comment by ArjanKloosterboer** [comment]
Waar kan ik de documentatie vinden o.b. waarvan ik kan reviewen?

**Comment by jgortmaker1** [comment]
wenselijk gebruik is of de user story in de GEMMA past..
GEMMA zegt dat ZGW geen manier is om werk te sturen..

het door een KCC-medewerker toewijzen van een behandelaar met het oog op het routeren is precies dat.
GEMMA zegt: een nieuw verzoek/aanvraag/melding gaat eerst naar de afhandelapplicatie en die maakt een zaak aan (en zet dus ook de behandelaar)
nieuwe inzichten tgv CG voegen hieraan toe: verzoek wordt geregistreerd als verzoek/aanvraag/melding in ofwel een aparte verzoekenregistratie ofwel een domeinspecifieke registratie (zijn we nog niet uit).
Afhandelende applicatie wordt hierover genotificeerd. Deze maakt vervolgens de zaak aan koppelt het al geregistreerde verzoek aan deze zaak.

Dus de US hierboven is volgens mij fors in strijd met GEMMA

de API call hierboven (de eerste met ophalen uit de ZTC snap ik niet helemaal, maar dat ligt aan mij):
```
POST /zrc/api/v1/rollen
{
    "zaak": "https://example.com/zrc/api/v1/zaken/<uuid>",
    "betrokkene": "https://example.com/api/betrokkenen/1234",
    "betrokkeneType": "Organisatorische eenheid",
    "rolomschrijving": "Behandelaar",
    "roltoelichting": "Lorem Ipsum...",
}
```
voegt gewoon een betrokkene toe aan een zaak in een bepaalde rol...daar kan ik vanuit GEMMA niet zoveel tegen inbrengen denk ik..

**Comment by sergei-maertens** [comment]
@jgortmaker1 helder dat het niet een manier is om werk te sturen.

Als ik kijk naar [de architectuurschets](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/amsterdam-water.md#14--architectuurschets-user-story), dan ziet het SIA blok er voor mij wel erg uit als een afhandelapplicatie :-)

Daarbinnen is er inderdaad sprake van routeren en behandelaar toewijzen, maar dat is 'interne keuken' binnen Amsterdam, en heeft op de ZDS APIs geen weerslag. Wat het wel uitdrukt, is dat het mogelijk moet zijn om via de APIs een betrokkene met een rol te kunnen zetten op een zaak.

Met de voortschrijdende inzichten wordt de meldingsinformatie inderdaad in een aparte registratie (ORC) opgeslagen, en gerelateerd aan de zaak.

> de API call hierboven (de eerste met ophalen uit de ZTC snap ik niet helemaal, maar dat ligt aan mij):
> ... [knip]
> voegt gewoon een betrokkene toe aan een zaak in een bepaalde rol...daar kan ik vanuit GEMMA niet zoveel tegen inbrengen denk ik..

Dat heb je helemaal goed, en dat je daar vanuit GEMMA niet veel kan tegen in brengen is ook precies de bedoeling.

Dit is eigenlijk een heel mooi voorbeeld van hoe een specifeke wens om een behandelaar toe te kennen resulteert in een API call die dat mogelijk maakt, maar vooral generiek genoeg gebouwd wordt om ook andere rollen toe te kunnen wijzen.

**Comment by joeribekker** [comment]
De zaken die @jgortmaker1 in zijn [comment](https://github.com/VNG-Realisatie/gemma-zaken/issues/45#issuecomment-417744343) beschrijft zouden eigenlijk in de functionale documentatie moeten staan, toch @michielverhoef ?

**Comment by ArjanKloosterboer** [comment]
In review en 'overleg nodig'. Kan dat? Dan hoort 'ie toch in 'in progress'? 
Verder blijft mijn [eerdere comment](https://github.com/VNG-Realisatie/gemma-zaken/issues/45#issuecomment-417650122) staan.

**Comment by TCIMEddy** [comment]
correct

**Comment by TCIMEddy** [comment]
@sergei-maertens lange discussie en ik kan niet precies achterhalen wat de status is. Ik had mij opgeworpen om deze om mijn naam te zetten. Weet jij wat er nog moet gebeuren?

**Comment by sergei-maertens** [comment]
Denk dat het stukje ImZTC met betrekking op `mogelijkeBetrokkenen` aan Arjan moet voorgelegd worden, dat is namelijk een afwijking.

**Comment by ehotting** [comment]
@jgortmaker1  @TCIMEddy Dit is al gemerged. De gevolgen van de API van deze user story zijn niet heel omstreden, maar de user story zélf is omstreden door het 'zodat routeren'.  Laten we dat even negeren en alleen kijken naar wat het effect op de API is / was, en of dat en wenselijk effect is.

@sergei-maertens 
Kan jij toelichten wat er gebeurt mbt de "mogelijke betrokkene"? Ik begrijp niet wat hier precies gebeurt:
https://github.com/VNG-Realisatie/gemma-zaken-test-integratie/pull/4/files

**Comment by jgortmaker1** [comment]
ok..maar ik had dat vinkje toch al gezet?
