### ISSUE TITLE
ZRC API geeft foutmelding in REDOC

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#450]
Wanneer ik de ZRC API uit Github probeer in te lezen in REDOC (of Swaggerhub) krijg ik een foutmelding
https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/zrc/openapi.yaml

Error parsing https://cors.apis.guru/https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/zrc/openapi.yaml duplicated mapping key at line 12, column -262: info: ^

Stack trace
ReDoc Version: 2.0.0-alpha.40
Commit: 8f7fccc

Het lijkt er op dat dit alleen in de ZRC API gebeurt, de DRC en ZTC API's geven geen foutmeldingen. Op zich kan ik de tekst van de OAS wel aanpassen en doublures er uit halen maar dat is symptoombestrijding.

**Comment by joeribekker** [comment]
Even een specifieke versie van het bestand dat fout ging voor historie: https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/c8240f1372e3cef16fc4f462e90ccd2e6e19518b/api-specificatie/zrc/openapi.yaml

Hier is een merge fout gegaan.

Je ziet dat halverwege, na *security* het begin van het bestand opnieuw begint. Controle op de API-spec zit alleen in de referentie componenten. Moet wellicht hier ook ingericht worden. Voor nu corrigeer ik het.

```yaml
openapi: 3.0.0
info:
  title: Zaakregistratiecomponent (ZRC) API
  description: Een API om een zaakregistratiecomponent te benaderen
  contact:
    url: 'https://github.com/VNG-Realisatie/gemma-zaken'
    email: support@maykinmedia.nl
  license:
    name: EUPL 1.2
  version: '1'
security:openapi: 3.0.0
info:
  title: Zaakregistratiecomponent (ZRC) API
  description: Een API om een zaakregistratiecomponent te benaderen
  contact:
    url: https://github.com/VNG-Realisatie/gemma-zaken
    email: support@maykinmedia.nl
  license:
    name: EUPL 1.2
  version: '1'
security:
- basic: []
```

**Comment by joeribekker** [comment]
Als #412 en #362 worden gemerged, is dit probleem verholpen.

Als dat is gedaan, testen we opnieuw en als het dan werkt kunnen we dit ticket sluiten.

**Comment by joeribekker** [comment]
Volgens mij gefixed nu, zie: http://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/zrc/openapi.yaml

Sluit je het ticket als je het er mee eens bent @michielverhoef ?

**Comment by michielverhoef** [comment]
Fixed, mag gesloten worden!
