### ISSUE TITLE
Als ontwikkelaar wil ik de openapi.YAML van het component kunnen opvragen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#452]
...zodat ik niet vast zit aan JSON.

Nu is de OAS op te vragen middels: https://ref.tst.vng.cloud/zrc/api/v1/schema/?format=openapi
Dit is echter in het JSON formaat. Het lijkt me handig als we ook de YAML versie zo op kunnen vragen, en tevens op de aanbevolen URL: openapi.yaml

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] er is een referentieimplementatie

**Taken**
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]

**Comment by sergei-maertens** [comment]
@joeribekker 
https://ref.tst.vng.cloud/zrc/api/v1/schema/openapi.yaml
