### ISSUE TITLE
Als ontwikkelaar wil ik het RGBZ 2 online doorzoekbaar en als hypertekst kunnen raadplegen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#458]
...zodat ik naar de relevante delen kan verwijzen in de documentatie . Dat mag best onder het label "in ontwikkeling" maar nu is het lastig verwijzen omdat alleen RGBZ 1 online staat.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] RGBZ2 staat online en is in detail in te zien en naar te verwijzen op een vergelijkbare manier als [RGBZ 1 in Detail](https://www.gemmaonline.nl/index.php/Informatiemodel_Zaken_(RGBZ)#RGBZ_in_detail)   

**Taken**
- [ ] exporteren RGBZ 2 naar html/wiki/markdown/? formaat [_verantwoordelijke_]
- [ ] Human Readable publiceren RGBZ 2 [_verantwoordelijke_]

**Comment by ehotting** [comment]
Sorry, out-of-scope voor dit team. Graag elders oppakken als VNG-R @wishalg.
Op zich wel wenselijk om vanuit onze docs te kunnen deeplinken naar specifieke info in RGBZ.

**Comment by TCIMEddy** [comment]
@wishalg Heb of wil jij een lijstjes bijhouden van zaken die hier van de band vallen (out of stope wont'fix etc) zodat ze geadresseerd blijven (backlog VNG). Wellicht apart GitHub gebeuren.

**Comment by michielverhoef** [comment]
Een online beschikbaar en doorzoekbaar RGBZ zou veel meerwaarde hebben voor de functionele en technische documentatie van dit project. 

Ik heb Arjan en Wishal zojuist al via Slack gevraagd om hier toch snel iets mee te doen. Desnoods via een aparte repository. Omzetten naar wiki of markdown vanuit het huidige word formaat moet niet al te moeilijk zijn.

**Comment by TCIMEddy** [comment]
@wishalg Dit is een voorbeeld van een user story die van de band is gevallen. Staat nu op backlog en op jouw naam. Prioriteren!
