### ISSUE TITLE
Als KCC medewerker wil ik categorien kunnen toewijzen aan een melding...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#46]
... zodat die automatisch kan verwerkt worden en eigendom wordt van een proceseigenaar.

ASCM = actieservicecentrummedewerker

**Comment by ehotting** [comment]
Wat is in deze user story een categorie, in RGBZ termen?
Ik ben nog niet helemaal op de hoogte van 'meldingen' zoals die nu in de API landen. Bestaat 'categorie' daarin?

**Comment by ArjanKloosterboer** [comment]
Met 'categorie' wordt - neem ik aan - bedoeld de categorie van de melding, zoals wateroverlast, waterverontreiniging, verstopping, algenbloei  e.d. Dat is een melding-domein-specifiek gegeven, geen zaak- cq. RGBZ-gegeven (of zo je wilt wel een zaaktypespecifieke eigenschap). 'categorie' hoort m.i. dus in de Meldingen-API, niet in de Zaken-API.

**Comment by Hugo-ter-Doest** [comment]
Dit hoort thuis bij de ev. te ontwikkelen Meldingen API.
