### ISSUE TITLE
RGBZ-mapping US #307

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#462]
Mapping van velden behorend bij user story #307 
Zie ook de [procesbeschrijving en architectuurschets](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/overige/processen/Delft%20AVG.md)
Maar vooral de [pull request](https://github.com/VNG-Realisatie/gemma-zaken/pull/670) met daarin ook het Informatiemodel.

Voor elk Onderzoeksdomein (WMO, Jeugd, Participatie, Schuld, Veiligheid, Overig en Algemeen) dat de Initiator onderzocht wil hebben, is een Onderzoeksvraag gecreëerd. De resultaten daarvan worden vastgelegd in: 
- Inzageverzoek.Onderzoeksvraag(x).Onderszoeksresultaattype,
- Inzageverzoek.Onderzoeksvraag(x).Resultaattypetoelichting en,eventueel in 
- Informatieobject, ObjectInformatieobject en OnderzoeksvraagInformatieobject.

Het Onderzoeksresultaattype is een enumeratie met de volgende waarden:
- 'De persoon komt niet voor', 
- 'Overzicht verwerkingen': Een overzicht van registraties/verwerkingen (in een document), 
- 'Afschrift van dossier': Een afschrift van een dossier (in een document), 
- 'De aanvrager mag een afspraak maken om zijn/haar dossier in te zien' |

Op dit moment leven alle gegevens (behalve het Informatieobject) in de procesapplicatie. Vanwege de mogelijkheid om te kunnen tijdreizen en om alle relevante gegevens terug te kunnen halen is het wellicht noodzakelijk om het Onderzoeksdomein, OnderzoeksResultaattype en Onderzoeksresultaattoelichting vast te leggen bij de Zaak. Wat zou betekenen dat dit Eigenschappen worden.

### Stappen:
Stap | Inhoud
| -- | -- |
| 1. | Controleer de status van de zaak/inzageverzoek. |
|  | Zodra de zaakstatus 'Advies ingewonnen' of hoger is, dan mogen de gegevens alleen nog worden gelezen. Dit moet eigenlijk al duidelijk zijn zodra de Deskundige de gegevens oproept. |
| 2. | Haal de gegevens/documenten op die de deskundige heeft geregistreerd uit AVGRC:
|  | - Onderzoeksresultaattype, Onderzoeksresultaattoelichting en; |
|  | - Het (mogelijk) bijbehorende document. |
|  | De resultaattypen (enumeratie) kunnen zijn: 'De persoon komt niet voor', 'Overzicht verwerkingen' (in een document), 'Afschrift van dossier' (in een document), 'De aanvrager mag een afspraak maken om zijn/haar dossier in te zien' |
| 3. | Wijzig de gegevens. |
|  | Het document wordt vervangen. het is alleen nodig de 'versie' van het document te bewaren die de Behandelaar uiteindelijk gebruikt in de Beschikking. Hoe die Deskundige tot die 'versie' gekomen is, is niet interessant. |

Ik heb 7 medewerkers met `roltype` 'Deskundige', het `generiek roltype` en de `soort betrokkene` zijn 'Adviseur'.
Elk van die Deskundigen levert een deel van het resultaat van het inzageverzoek op. Voor 1 van de 7 onderzoeksdomeinen: WMO, Jeugd, Participatie, ...
Elk van die Deskundigen mag ook alleen maar zijn/haar eigen deel bekijken en wijzigen.
Dat wijzigen mag alleen zolang de status van de zaak/het inzageverzoek 'In behandeling genomen' is.

In het ['Informatiemodel voor AVG-rechten'](https://github.com/VNG-Realisatie/gemma-zaken/pull/670) zijn `Onderzoeksdomeinen` en `Gebruikers` gedefinieerd en aan elkaar gekoppeld. Dit bepaalt wat een Initiator kan laten onderzoeken in zijn `Inzageverzoek`. Die Deskundigen zijn `Gebruikers` met het `Roltype` Adviseur. 
Als een `Onderzoeksdomein` in het `Inzageverzoek` onderzocht moet worden (omdat de Initiator dat aanvinkt) wordt daar een `Onderzoeksvraag` voor gemaakt waar de betreffende Deskundige zijn `Onderzoeksresultaat` kwijt kan. Een bijbehorend `Informatieobject` staat in de DRC en is benaderbaar via `OnderzoeksvraagInformatieobject`.

In het model is dus vastgelegd welke Deskundige over welke gegevens gaat.

### Opvragen Status

**_Request ZRC_**

RGBZ mapping | Veld in huidige app | Datatype | Verklaring
-- | -- | -- | --
 `ZAAK. ZaakIdentificatie` | `zaakid` | UUID | Uniek volgnummer zaak

**_Answer ZRC_**

RGBZ mapping | Veld in huidige app | Datatype | Verklaring
-- | -- | -- | --
 `ZAAK.Status` | `Status` | AN200 | Actuele status van de zaak
 ` ` | ` ` | ... | ...

### Opvragen Onderzoeksresultaat van de Deskundige

**_Request AVGRC_**

IM mapping | Veld in huidige app | Datatype | Verklaring
-- | -- | -- | --
 `Inzageverzoek. VJVNummer` | `VJV Nummer` | N8 | Uniek nummer van het Inzageverzoek
 `Inzageverzoek. GebruikerID` | `GebruikersID` | UUID | Uniek ID van de Gebruiker

**_Answer AVGRC_**

RGBZ mapping | Veld in huidige app | Datatype | Verklaring
-- | -- | -- | --
 `Inzageverzoek. Onderzoeksvraag. Onderzoeks resultaatType` | `Resultaattype` | enumOnderzoeks resultaattype | Het type onderzoeksresultaat
 `Inzageverzoek. Onderzoeksvraag. Onderzoeks resultaat toelichting` | `Toelichting` | AN1000 | Toelichting bij het onderzoeksresultaat
 `Inzageverzoek. Onderzoeksvraag. Onderzoeksvraag Informatieobject. Informatieobject` | `Document` | AN200 | URL naar het document behorende bij het Onderzoeksresultaat

Om het Informatieobject daadwerkelijk op te vragen moet je natuurlijk de DRC benaderen.

### Opslaan gewijzigd Onderzoeksresultaat inclusief Informatieobject

Scenario's: 
- Het Informatieobject wijzigt -> **Informatieobject vervangen**
- Het Onderzoeksresultaattype wijzigt van een type zonder Informatieobject naar een type met Informatieobject -> **Informatieobject toevoegen**
- Het Onderzoeksresultaatype wijzigt van een type met informatieobject naar een type zonder Informatieobject -> **Informatieobject verwijderen**

(ENKELVOUDIG)INFORMATIEOBJECT is een verwijzing naar het het feit dat INFORMATIEOBJECT en ENKELVOUDIGINFORMATIEOBJECT in de API-specificatie zijn samengevoegd.

### Scenario 1. Informatieobject vervangen

**_Request DRC_**

IM mapping | Veld in huidige app | Datatype | Verklaring
-- | -- | -- | --
`ENKELVOUDIG INFORMATIEOBJECT. Informatieobject` |   | `Informatieobject` | Geheel van gegevens met een eigen identiteit ongeacht zijn vorm, met de bijbehorende metadata ontvangen of opgemaakt door   een natuurlijke en/of rechtspersoon bij de uitvoering van taken. 
`ENKELVOUDIG INFORMATIEOBJECT. Inhoud` | `Inhoud` | AN | Datgene wat in een ENKELVOUDIG INFORMATIEOBJECT wordt meegedeeld. 
`ENKELVOUDIG INFORMATIEOBJECT. Link` | `Link` | AN200 | De URL waarmee de inhoud van het INFORMATIEOBJECT op te vragen is. 
`(ENKELVOUDIG) INFORMATIEOBJECT. Informatieobjectidentificatie` | UUID | AN40 | Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT. 
`(ENKELVOUDIG) INFORMATIEOBJECT. Creatiedatum` | `Creatiedatum` | DATUM | Een datum of een   gebeurtenis in de levenscyclus van het INFORMATIEOBJECT. 

**_Answer DRC_**

IM mapping | Veld in huidige app | Datatype | Verklaring
-- | -- | -- | --
`(ENKELVOUDIG) INFORMATIEOBJECT. Informatieobject identificatie` | UUID | AN40 | Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT. 
` ` | ` ` | ... | ...

### Scenario 2. Informatieobject toevoegen

**_Request DRC_**
 
 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`ENKELVOUDIG INFORMATIEOBJECT. Formaat` | `Formaat` | AN255 | De code voor de wijze waarop de inhoud van het   ENKELVOUDIG INFORMATIEOBJECT is vastgelegd in een computerbestand. 
`ENKELVOUDIG INFORMATIEOBJECT. Taal` | `Taal` | enum Taal | Een taal van   de intellectuele inhoud van het ENKELVOUDIG INFORMATIEOBJECT. De waardes komen uit ISO 639-2/B 
`ENKELVOUDIG INFORMATIEOBJECT. Inhoud` | `Inhoud` | AN | Datgene wat in een ENKELVOUDIG INFORMATIEOBJECT wordt meegedeeld. 
`ENKELVOUDIG INFORMATIEOBJECT. Link` | `Link` | AN200 | De URL waarmee de inhoud van het INFORMATIEOBJECT op te vragen is. 
`ENKELVOUDIG INFORMATIEOBJECT. Informatieobject` |   | `Informatieobject` | Geheel van gegevens met een eigen identiteit ongeacht zijn vorm, met de bijbehorende metadata ontvangen of opgemaakt door   een natuurlijke en/of rechtspersoon bij de uitvoering van taken. 
`(ENKELVOUDIG) INFORMATIEOBJECT. Informatieobject identificatie` | UUID | AN40 | Een binnen een gegeven   context ondubbelzinnige referentie naar het INFORMATIEOBJECT. 
`(ENKELVOUDIG) INFORMATIEOBJECT. Bronorganisatie` | `Organisatie` | AN9 | Het RSIN van de Niet-natuurlijk persoon zijnde de   organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en   als eerste in een samenwerkingsketen heeft vastgelegd. 
`(ENKELVOUDIG) INFORMATIEOBJECT. Creatiedatum` | `Creatiedatum` | DATUM | Een datum of een   gebeurtenis in de levenscyclus van het INFORMATIEOBJECT. 
`(ENKELVOUDIG) INFORMATIEOBJECT. Titel` | `Titel` | AN200 | De naam waaronder het INFORMATIEOBJECT formeel bekend is. 
`(ENKELVOUDIG) INFORMATIEOBJECT. Auteur` | `Auteur` | AN200 | De persoon of organisatie die in de eerste plaats verantwoordelijk is voor het creëren van de inhoud van het INFORMATIEOBJECT. 
`(ENKELVOUDIG) INFORMATIEOBJECT. Beschrijving` | `Beschrijving` | AN1000 | Een generieke   beschrijving van de inhoud van het INFORMATIEOBJECT. 
`(ENKELVOUDIG) INFORMATIEOBJECT. Informatieobjecttype` | `Type` | AN200 | URL naar de  Informatieobjecttype 'Rapportage' in het ZTC. 

**_Answer DRC_**

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`(ENKELVOUDIG) INFORMATIEOBJECT. Informatieobjectidentificatie` | `InformatieobjectID` |  AN40 | Uniek volgnummer informatieobject 

**Informatieobject koppelen aan de zaak**

**_Request DRC_**

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`OBJECTINFORMATIE OBJECT. Zaak` | `Zaak` | AN200 | URL naar de zaak in de ZRC 
`OBJECTINFORMATIE OBJECT. Informatieobject` |   | AN200 | URL naar het informatieobject 

**_Answer DRC_**

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`OBJECTINFORMATIE OBJECT. Zaak` | `Zaak` | AN200 | URL naar de zaak in de ZRC 
`OBJECTINFORMATIE OBJECT. Informatieobject` | `Informatieobject`  | AN200 | URL naar het informatieobject 

**_Request AVGRC_**

IM Mapping | Veld in huidige app | Datatype | Verklaring
-- | -- | -- | --
`AVG-Rechten. Onderzoeksvraag .Onderzoeksvraag Informatieobject. Onderzoeksvraag` | `Onderzoeksvraag` | AN200 | De onderzoeksvraag waarop dit Informatieobject een antwoord is.  _Waarde: URL naar het Onderzoeksvraag in AVGRC_ 
`AVG-Rechten. Onderzoeksvraag .Onderzoeksvraag Informatieobject. Informatieobject` | `Onderzoeksvraag` | AN200 | Het Informatieobject met het antwoord op de Onderzoeksvraag. _Waarde: URL naar het Informatieobject in DRC_ 

**_Answer AVGRC_**

IM Mapping | Veld in huidige app | Datatype | Verklaring
-- | -- | -- | --
`AVG-Rechten. Onderzoeksvraag .Onderzoeksvraag Informatieobject. Onderzoeksvraag` | `Onderzoeksvraag` | AN200 | De onderzoeksvraag waarop dit Informatieobject een antwoord is.  _Waarde: URL naar het Onderzoeksvraag in AVGRC_ 
`AVG-Rechten. Onderzoeksvraag .Onderzoeksvraag Informatieobject. Informatieobject` | `Document` | AN200 | Het Informatieobject met het antwoord op de Onderzoeksvraag. _Waarde: URL naar het Informatieobject in DRC_ 

### Scenario 3. Informatieobject verwijderen

je hebt al uitgezocht of er een Informatieobject aan het Onderzoeksresultaat gekoppeld is, dus dat hoef je her niet meer te valideren. Behalve om uit te sluiten dat de gegevens tussentijds (door iemand anders) gewijzigd zijn

**Verwijderen koppeling met ZRC**

**_Request DRC_**

 RGBZ mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`OBJECTINFORMATIE OBJECT. Zaak` | `Zaak` | AN200 | URL naar de zaak in de ZRC 
`OBJECTINFORMATIE OBJECT. Informatieobject` |   | AN200 | URL naar het informatieobject 

**_Answer DRC_**

Waarmee ook de relatie in de ZRC in ZaakInformatieobject verwijderd moet worden

**Verwijderen koppeling met AVGRC**

**_Request DRC_**

 IM mapping | Veld in huidige app | Datatype | Verklaring 
 -- | -- | -- | -- 
`OBJECTINFORMATIE OBJECT. Onderzoeksvraag` | `Onderzoeksvraag` | AN200 | URL naar de Onderzoeksvraag in de AVGRC. 
`OBJECTINFORMATIE OBJECT. Informatieobject` |   | AN200 | URL naar het informatieobject. 

**_Answer DRC_**

Waarmee ook de relatie in AVGRC.OnderzoeksvraagInformatieobject verwijderd moet worden

**_Request DRC_**

IM mapping | Veld in huidige app | Datatype | Verklaring
-- | -- | -- | --
`(ENKELVOUDIG) INFORMATIEOBJECT. Informatieobjectidentificatie` | UUID | AN40 | Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT. 

**_Answer DRC_**

**Comment by EdwinCoster** [comment]
@joeribekker @sergei-maertens @ArjanKloosterboer @jgortmaker1 
Willen jullie je even over mijn vragen buigen?

Als ik het vanuit deze mapping naar #307 moet verplaatsen dan vind ik dat best. Dit was het punt waarop ik in de war raakte.

**Comment by ArjanKloosterboer** [comment]
> Vraag: Gaan we dan een nieuwe versie van een document toevoegen, of mogen we het bestaande document vervangen?

Conform RGBZ voeg je een nieuwe versie toe, er zit materiele en formele historie op de attribuutsoort 'Inhoud'. Vanuit beheeroverwegingen kun je beslissen om het dossier op enig moment op te schonen en niet-actuele versies te verwijderen. Dat kan dus ook bij het toevoegen van een nieuwe versie. 

> Wat (welke attributen, ...) gebruik ik om alleen die gegevens/objecten op te halen die voor een specifieke deskundige van toepassing zijn? en waar leven die? [...] Elk van die Deskundigen mag ook alleen maar zijn/haar eigen deel bekijken en wijzigen.

Grofweg gaat dit om het aantal adviseurs maal twee brokjes informatie: het Resultaattype per discipline cq. deskundige en het Document per discipline cq. deskundige. Het RGBZ biedt geen mogelijkheden om af te schermen dat alleen een bepaalde persoon zo'n brokje informatie kan muteren. Het kent slechts één resultaat per zaak. En documenten kennen weliswaar een vertrouwelijkheidsniveau maar dat is niet aan autorisaties gekoppeld. Het meest voor de hand liggend lijkt het mij om dit in een specifieke zaakafhandelcomponent op te lossen. Voor de ZRC zijn dan alle adviseurs bij de zaak gelijk en hebben alleen zij toegang tot genoemde informatie bij die zaak en die toegang hebben ze alleen via die specifieke zaakafhandelcomponent. 
Je zou het ook, zoals je suggereert, op kunnen lossen met deelzaken maar dat lijkt mij oneigenlijk gebruik.
