### ISSUE TITLE
RGBZ-mapping US 403

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#464]
Mapping van velden behorend bij user story #403

Rapportages:
- Aantal afgehandelde zaken
- Aantal binnengekomen zaken
- Aantal openstaande zaken
- Aantal overschrijdend op geplande einddatum
- Aantal overschrijdend op uiterlijke eind datum afdoening

In de user story genoemde rapportages werken met dezelfde set parameters: 
- Kolom: Afdeling, Groep, Behandelaar, Kanaal, Status, Zaaktype, Doorlooptijd, Overschrijding Einddatum gepland, Overschrijding Uiterlijke einddatum afdoening, Resultaat, Maand, Week, Dag
- Rij: dezelfde mogelijke waarden als bij Kolom
- Periode startdatum
- Periode einddatum

# Request parameters

| RGBZ mapping | Parameter rapportages | Verklaring |
| :--- | :--- | :--- |
| `ORGANISATORISCHE EENHEID is BETROKKENE heeft rol in ZAAK`  | Afdeling  |   |
|  `ORGANISATORISCHE EENHEID is BETROKKENE heeft rol in ZAAK`   | Groep |   |
|  `MEDEWERKER is BETROKKENE heeft rol in ZAAK`  | Behandelaar |   |
| `ZAAK.Communicatiekanaal`  | Kanaal  |   |
| `Statustype-omschrijving van STATUSTYPE van STATUS van ZAAK`  | Status  |   |
|  `Zaaktype-omschrijving van ZAAKTYPE van ZAAK` | Zaaktype  |   |
|  `ZAAK.Startdatum`  | Doorlooptijd  | De tijd in dagen die is verstreken sinds de startdatum van de zaak  |
|  `ZAAK.Einddatum gepland` | Overschrijding Einddatum gepland  |   |
|  `ZAAK.Uiterlijke einddatum afdoening` | Overschrijding Uiterlijke einddatum afdoening |   |
| `Resultaattypeomschrijving van RESULTAATTYPE bij afronding van ZAAK`  | Resultaat  |   |
|  Aantal afgehandelde zaken: `ZAAK.Einddatum`, Aantal binnengekomen zaken: `ZAAK.Registratiedatum`, Aantal openstaande zaken: `ZAAK.Startdatum` en `ZAAK.Einddatum` en `STATUS van ZAAK`, Aantal overschrijdend op geplande einddatum: `ZAAK.Einddatum`, `ZAAK.Geplande einddatum` , Aantal overschrijdend op uiterlijke einddatum afdoening: `ZAAK.Einddatum`, `ZAAK.Uiterlijke einddatum afdoening` | Maand  | Totalen per maand  |
|  idem  | Week  |  Totalen per week |
|  idem  | Dag  |  Totalen per dag |
| `ZAAK.Startdatum` | Periode startdatum | Datum vanaf voor de periode |
| `ZAAK.Startdatum` | Periode einddatum| Datum tot voor de periode |

# Response

Een mapping van rijwaarden naar een mapping van kolomwaarden naar totalen per rij-/kolomwaarde). Bijv. een rapportage van aantal zaken die over de geplande einddatum zijn gegaan, per medewerker per maand.

**Comment by TCIMEddy** [comment]
Deze week review anders ready for sprint

**Comment by ArjanKloosterboer** [comment]
Mooie mapping.
Qua fijnslijperij:
- 'STATUS van ZAAK' moet m.i. iets zijn als: 'Statustype-omschrijving (of de generieke?) van STATUSTYPE van STATUS van ZAAK'.  
- 'ZAAK is van ZAAKTYPE' moet m.i. iets zijn als 'Zaaktype-omschrijving van ZAAKTYPE van ZAAK'.
- 'ZAAK heeft bij afronding RESULTAATTYPE' moet m.i. iets zijn als 'Resultaattypeomschrijving van RESULTAATTYPE bij afronding van ZAAK'.  
- bij 'Aantal openstaande zaken' (in een maand) m.i. ZAAK.Startdatum en ZAAK.Einddatum (alle zaken waarvan de Startdatum ligt in of voor de maand en waarvan de einddatum niet is gevuld dan wel ligt na de maand). 
- bij 'Aantal openstaande zaken' en 'Aantal overschrijdend op uiterlijke einddatum afdoening' heb je m.i. ook de Einddatum nodig (alle niet beeindigde zaken en zaken met een einddatum na de maand waarvan ...).
Bij Parameter rapportages = Einddatum staat in de mapping ZAAK.Startdatum. Ik vermoed dat dit ZAAK.Einddatum moet zijn.
