### ISSUE TITLE
Als leverancier wil ik gemeenten helpen van StUF naar API standaarden over te gaan

### ISSUE THREAD

**Issue by wishalg** [VNG-Realisatie/gemma-zaken#465]
...zodat we geleidelijk aan over kunnen gaan naar een gegevenslandschap.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Begrijpelijke wens maar scrum team heeft alle tijd nodig om de API standaard zo goed mogelijk te krijgen. Dit hoort eerder thuis in team van @jgortmaker1 denk ik. out-of-scope voor dit scrum team.

**Comment by jgortmaker1** [comment]
dit is te specifiek voor squad architectuur :-) 
hoort in de hoek van standaarden/servcies

**Comment by ehotting** [comment]
@wishalg help!

**Comment by TCIMEddy** [comment]
Volgens mij hebben beide teams een rol (en ja die moet nog benoemd worden)

**Comment by wishalg** [comment]
@jgormaker1 het zou gemeenten en leveranciers enorm veel helpen als er vanuit architectuur een uitwerking komt van huidige-migratie-gewenste (ist-gap-soll) situatie van StUF naar API standaarden (Hoe?); met mogelijke migratiepaden.
