### ISSUE TITLE
Als gebruiker van MijnApp wil ik detailinformatie van een zaak inzien.

### ISSUE THREAD

**Issue by ppcjansen** [VNG-Realisatie/gemma-zaken#47]
zodat ik inzage krijg in mijn zaak.

**Comment by ehotting** [comment]
Zonder specifieke architectuur & RGBZ mapping kan deze user story geen wijzigingen tot gevolg hebben in de API spec. Daarom sluit ik deze. Als MijnApp weer opgepakt wordt kunnen we deze heropenen.
