### ISSUE TITLE
Als medewerker van een gemeente wil ik een zaak aan kunnen maken die pas later in behandeling genomen wordt

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#474]
...zodat deze eerst beoordeeld kan worden of deze in behandeling genomen moet worden.

NB. om dit op te lossen moet startdatum in de Zaken API optioneel gemaakt worden bij het aanmaken van een zaak.

Het veld startdatum is nu verplicht bij het aanmaken van een zaak. Nu is dit weliswaar een verplicht gegeven voor een zaak maar een zaak kan aangemaakt maar nog niet direct in behandeling genomen worden.  In dat geval is de startdatum niet bekend. Een dergelijke zaak kan nu niet aangemaakt worden met de API.

https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_create 

Graag startdatum optioneel maken zodat deze ook later gezet kan worden wanneer de zaak daadwerkelijk in behandeling genomen kan worden.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Volgens RGBZ 2 heeft Michiel gelijk, dus dit moet worden aangepast.

@ArjanKloosterboer Waarom is dat eigenlijk? Intuitief zou ik verwachten dat Startdatum uitvoering niet een los attribuut is maar de datum van een status.

<img width="871" alt="screen shot 2018-10-17 at 09 32 06" src="https://user-images.githubusercontent.com/20684884/47069582-914e0b00-d1ef-11e8-8d42-65f384259a97.png">

**Comment by ehotting** [comment]
Kardinaliteit staat overigens op 1 - 1 dus daar zit een mismatch...

**Comment by TCIMEddy** [comment]
@michielverhoef Hier is de discussie gestart dus wellicht 474 hierheen kopiëren en alles behouden en dan 474 close

**Comment by michielverhoef** [comment]
@TCIMEddy Dit is issue 474 :-)

**Comment by TCIMEddy** [comment]
@michielverhoef zie Slack, moet me er ook niet mee bemoeien sorry

**Comment by ArjanKloosterboer** [comment]
> ...zodat deze eerst beoordeeld kan worden of deze in behandeling genomen moet worden.

Dat 'beoordelen' dat is een handeling cq. activiteit d.w.z. er wordt al gewerkt. Waaraan? Aan de zaak! Het is dus niet de vraag of de zaak behandeld gaat worden (hij is al in behandeling) maar of, na de intake van (de aanleiding tot) de zaak, de zaak nog verder behandeld wordt of buiten behandeling wordt gesteld of anderszins wordt beeindigd. Vanuit deze optiek is er dus geen behoefte om de startdatum optioneel te maken. Overigens zou dit na de introductie van VERZOEK anders kunnen gaan. Er is dan klaarblijkelijk een verzoek waarvan het niet zeker is of dat behandeld gaat worden. Dus nog geen zaak. Als tot behandeling besloten wordt, dan wordt een zaak aangemaakt met startdatum (=ontvangstdatum verzoek) ingevuld. Dus ook dan geen optionele startdatum.  
Vanuit een andere optiek wellicht wel. Het moet mogelijk zijn om een zaak alvast te 'agenderen' maar nog niet te starten. Bijvoorbeeld, de vergunning is verleend en je wilt de eerste toezichtactie over een half jaar uitvoeren. Registreer een zaak, stel de startdatum vast op de datum van nu + half jaar en iedereen wordt er op tijd aan herinnerd dat er toezicht gehouden moet gaan worden. 
Maar, ook in dit geval gaat het om een ingevulde startdatum. Zijn er gevallen bekend waarin wel alvast de zaak geregistreerd wordt maar de start daarvan nog niet gepland wordt?

**Comment by ArjanKloosterboer** [comment]
> Intuitief zou ik verwachten dat Startdatum uitvoering niet een los attribuut is maar de datum van een status.

Een status is een bereikte mijlpaal in de behandeling van een zaak (vandaar een voltooid deelwoord in de statusbenaming, het is dus geen aanduiding van datgene waaraan gewerkt wordt dat met een werkwoord aangeduid zou worden). Er is geen verplichting om de start van de zaak als mijlpaal te markeren met een status. De eerste status zal veelal 'Intake afgerond' zijn. De zaak loopt dan al een tijdje. Als er in een zaak nog geen mijlpaal cq. status bereikt is, dan is de - niet vastgelegde - impliciete status 'Zaakbehandeling gestart', uitgaande van een verplichte startdatum.

**Comment by ehotting** [comment]
Waarom een status over de behandeling gaat en niet over de zaak zelf ontgaat me. 
"Zaak geregistreerd" zou toch ook een mooie status zijn? :)

Maar goed, wil hier niet aan tornen. De vraag is dus inderdaad of er situaties zijn waarbij de startdatum NIET gelijk is aan registratiedatum (default) of bij aanmaken in de toekomst wordt vastgesteld. 

@michielverhoef heb je een concrete user story, een praktijkvoorbeeld?

**Comment by Hugo-ter-Doest** [comment]
> Vanuit een andere optiek wellicht wel. Het moet mogelijk zijn om een zaak alvast te 'agenderen' maar nog niet te starten. Bijvoorbeeld, de vergunning is verleend en je wilt de eerste toezichtactie over een half jaar uitvoeren. Registreer een zaak, stel de startdatum vast op de datum van nu + half jaar en iedereen wordt er op tijd aan herinnerd dat er toezicht gehouden moet gaan worden.
Maar, ook in dit geval gaat het om een ingevulde startdatum. Zijn er gevallen bekend waarin wel alvast de zaak geregistreerd wordt maar de start daarvan nog niet gepland wordt (een soort van backlog ;-)?

Deze use case over alvast klaarzetten van zaken is relevant. Echter dan is ook de startdatum bekend. Verder zijn er geen toepassingen aangeleverd voor het openlaten van de startdatum. Ik sluit het issue.
