### ISSUE TITLE
Verbreken relatie zaak - informatieobject niet in alle API's gelijk toegepast

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#475]
Eigenlijk zijn dit meer bevindingen in één issue:
* In de ZAKEN (ZRC) API wordt gesproken over ZAAKINFORMATIEOBJECT
* In de INFORMATIEOBJECTEN (DRC) API  wordt gesproken over OBJECTINFORMATIEOBJECT

Dit snap ik op zich nog wel, in die zin dat een INFORMATIEOBJECT gekoppeld kan zijn aan verschillende soorten objecten (zaak, besluit etc.) terwijl in een ZRC zaken geregistreerd worden en alleen INFORMATIEOBJECTen geregistreerd worden die aan een zaak gekoppeld zijn.

Misschien dat dit (als dit klopt) in de respectievelijke API's opgenomen moet worden? 

* In de ZAKEN (ZRC) API  is het mogelijk via de operatie zaakinformatieobject_delete de koppeling te verwijderen
* In de INFORMATIEOBJECTEN (DRC) API  bestaat deze mogelijkheid niet. Voor de DRC blijft een INFORMATIEOBJECT dus altijd gekoppeld aan een zaak, ondanks dat in de ZRC deze koppeling verwijderd kan zijn?

Volgens mij klopt dit niet, ik zou een operatie objectinformatieobject_delete in de DRC API verwachten om ook daar de relatie te kunnen verbreken.

**Comment by sergei-maertens** [comment]
Klopt, gaat eruit in https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/19
