### ISSUE TITLE
Als proceseigenaar wil ik een lijst van aan mij toegewezen meldingen zien...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#48]
... zodat ik deze meldingen kan oplossen.

**Comment by jgortmaker1** [comment]
als proceseigenaar of als behandelaar?

**Comment by TCIMEddy** [comment]
@MarcelMoerman Wat is de definitie van een proceseigenaar (voor Amsterdam uiteraard)

**Comment by ehotting** [comment]
De API kent straks scopes, waaraan men zelf rollen zoals bekend binnen een gemeente kan koppelen.

Relatie met #424.
Graag een overzicht van velden uit de API die in de user interface nodig zijn voor deze user story.

**Comment by TCIMEddy** [comment]
@ehotting wie moet/kan dat doen?

**Comment by TCIMEddy** [comment]
@joeribekker moet hier nog wat gebeuren in de API?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest deze komt vanuit water/mor/amsterdam nog relevant?

**Comment by TCIMEddy** [comment]
in overleg met indiener Marcel op close gezet
