### ISSUE TITLE
BUG: Demo user in ZTC referentie component heeft onvoldoende rechten om zaaktypes aan te maken

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#487]
Als je met de op redoc aangegeven credentials inlogt op de ZTC admin pagina van het ZTC referentiecomponent heb je onvoldoende rechten om zaaktypes aan te maken.

![afbeelding](https://user-images.githubusercontent.com/39768984/47301804-1ab27280-d620-11e8-97ca-8ed69a401cd9.png)

**Comment by sergei-maertens** [comment]
@CMasselink gefixed - is een bug in een [externe library](https://github.com/maykinmedia/django-admin-index/issues/9)
