### ISSUE TITLE
Als behandelaar wil ik een notificatie kunnen krijgen van nieuwe zaken...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#49]
... zodat ik niet elke dag hoef te controleren op nieuwe meldingen.

**Comment by jgortmaker1** [comment]
hier zit een blokkerende architectuurvraag onder: hoe loopt de flow van een aanvraag?
als deze direct in de afhandelende applicatie (= primaire applicatie van de behandelaar) komt, dan hoeft er niet genotificeerd te worden..

**Comment by Hugo-ter-Doest** [comment]
zie https://github.com/VNG-Realisatie/Squad-Architectuur-Samen-Organiseren/issues/153

**Comment by Hugo-ter-Doest** [comment]
Opgevat als: notificatie over nieuwe zaken van een bepaald zaaktype.

**Comment by joeribekker** [comment]
Scope hier wordt gedekt in https://github.com/VNG-Realisatie/gemma-zaken/pull/764 middels een POST op Zaak API resource Zaken.

**Comment by joeribekker** [comment]
Kapstok US #792 dekt dit af, minus de taak/afhandel-applicatie functies die out-of-scope zijn.
