### ISSUE TITLE
Onenigheid over resources in DRC

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#491]
In https://github.com/VNG-Realisatie/gemma-zaken/pull/412#issuecomment-431864784 sijpelt door dat Arjan het niet eens is met 1 resource in het DRC om de relaties uitgaande van Informatieobjecten te ontsluiten. Het lijkt erop dat de hoofdreden hiervoor is dat de relatie 'anders' is in het RGBZ:

* BESLUIT kan vastgelegd zijn als INFORMATIEOBJECT' en
* ZAAK kent INFORMATIEOBJECT

Volgens Arjan moet dat doorgetrokken worden in de API en dus resulteren in een andere relatie-resource.

Aan de kant van development van de referentieimplementaties gaan we hier niet mee akkoord. Zie ook [mijn PR comment](https://github.com/VNG-Realisatie/gemma-zaken/pull/412#issuecomment-432669981).

We moeten hier gaan uitkomen, want deze manier van reviewen & blocken is niet werkbaar.

**Comment by ArjanKloosterboer** [comment]
> … want deze manier van reviewen & blocken is niet werkbaar

Ik vind zo'n opstelling niet werkbaar.

**Comment by sergei-maertens** [comment]
Probleem & oplossing zijn helder nu - ik implementeer.

**Comment by TCIMEddy** [comment]
@sergei-maertens @ArjanKloosterboer volgens mij hebben we dit gisteren besproken en is de pr in gang gezet. Dus voor nu zet ik dit impediment op close
