### ISSUE TITLE
Issue: relatie tussen Informatieobject en Besluit semantisch afwijkend geimplementeerd in API

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#493]
Betreft Documenten- cq. Informatieobjecten-API. M.i. onjuist en ongewenst. Schept verwarring.
Zie issues #412 en #166

**Comment by sergei-maertens** [comment]
Duplicate #491

**Comment by ArjanKloosterboer** [comment]
En daarom weer geclosed.
