### ISSUE TITLE
Als behandelaar wil ik de belofte kunnen aanpassen...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#50]
... omdat er door omstandigheden een verandering kan optreden in de planning moet een gedane belofte (servicenorm) kunnen worden aangepast door een medewerker ASCM of de behandelende Back-office. De aanpassing gaat altijd gepaard met een toelichting over de gewijzigde status / situatie. 

**ASCM = Actie Service Centrum Medewerker**

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**

- [x] Beschrijven welke data er wordt gemuteerd bij uitvoeren van deze functie [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Architectuur**

De globale architectuur voor de usecase is beschreven in de Amsterdamse oplossings-schets.
Deze is hier te vinden >> [Documentatie](https://github.com/VNG-Realisatie/blob/master/docs/processen/amsterdam-water.md)

### Update op ZRC API
| Attribuut | waarde | OPERATIE |
| :--- | :--- | :--- |
| Zaak.einddatum gepland | YYYYMMDD | UPDATE |
| Zaak.Opschorting |   |   |
|  - Zaak.Opschorting.Indicatie opschorting |  | UPDATE |
|  - Zaak.Opschorting.Reden opschorting |  | UPDATE |
| Zaak.Verlenging |   |   | 
|  - Zaak.Verlenging.Reden Verlenging |  | UPDATE |
|  - Zaak.Verlenging.Duur Verlenging | YYMM:WWDDHH | UPDATE |

**Comment by ehotting** [comment]
Wat is een ASCM? Wat is een belofte?

**Comment by TCIMEddy** [comment]
@MarcelMoerman Hoi Marcel kun jij hier nog aangeven wat ASCM en een belofte is?

**Comment by sergei-maertens** [comment]
Door @MarcelMoerman bevestigd dat dit inderdaad om de servicenorm gaat.

**Comment by MarcelMoerman** [comment]
De belofte is gebaseerd op standaard afspraken, het actie service centrum (en de meldingen app) hebben een standaard belofte die kan worden gecommuniceerd. Als blijkt dat deze belofte niet kan worden waargemaakt moet er een nieuwe belofte kunnen worden afgegeven door de proceseigenaar (back-office). Als ik het goed begrijp staan dit soort dingen in de ZTC onder de attributen "doorlooptijd...""Servicenorm...", "opschorting/....", die kunnen we natuurlijk niet aanpassen dus een "weerslag hiervan zal per zaak moeten worden vastgelegd bij afwijking van de norm".

**Comment by MarcelMoerman** [comment]
Aanpassingen aan userstory om deze duidelijker te maken, toegevoegd de API / Data mutaties.

**Comment by MarcelMoerman** [comment]
Oeps dat was niet de bedoeling, heropent.

**Comment by ehotting** [comment]
Gaat om afhandeldatum en ik herken dit uit de praktijk. Interessant om:
- [ ] uit te zoeken hoe het precies in RGBZ zit
- [ ] na te gaan of het in de API past
   - [ ] zo ja, check & close
   - [ ] zo nee, uitbreiden spec

**Comment by ehotting** [comment]
Is dit idd voorzien van veldmapping RGBZ? Volgens mij niet

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Zou jij je licht willen schijnen over de veldmapping RGBZ?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest deze komt vanuit water/mor/amsterdam nog relevant?

**Comment by Hugo-ter-Doest** [comment]
Met een patch kan de einddatum gepland worden aangepast.
