### ISSUE TITLE
Moet Zaak.einddatum veranderd worden van date naar datetime?

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#502]
Aangezien de einddatum (date) van een Zaak afgeleid wordt uit Status.datumStatusGezet (datetime) kunnen we daar wellicht beter een datetime van maken?

Geen halszaak, maar iets wat opviel bij implementatie.

**Comment by ArjanKloosterboer** [comment]
V.w.b. de einddatum van een zaak volstaat een datum. Een tijdstip geeft schijnnauwkeurigheid en daaraan is geen behoefte. Leidt alleen maar tot verwarring.

**Comment by sergei-maertens** [comment]
Het precieze moment waarop de status opgevoerd wordt is toch bekend? En staat ook als DT in RGBZ, dus waar zit dan de 'schijn' in de schijnnauwkeurigheid?

**Comment by ArjanKloosterboer** [comment]
Het moment waarop de status is vastgelegd is formele historie. De datum waarop de zaak beeindigd wordt is materiele historie. Zijn dus verschillende dingen. Specificatie in minuten heeft niets te maken met de dag waarop de zaak beeindigd is.

**Comment by joeribekker** [comment]
> Het moment waarop de status is vastgelegd is formele historie. De datum waarop de zaak beeindigd wordt is materiele historie.

Dat klinkt vreemd. We hadden toch [besproken](https://github.com/VNG-Realisatie/gemma-zaken/pull/351) en [vastgelegd](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/content/developers/design-keuzes.md#zaak-afsluiten) dat `Zaak.einddatum` afgeleid werd uit de `Status.datumStatusGezet` als dit een eind status betrof?

Dit maakt beide materiele historie waarop het wel kan zijn dat dit ook gewoon de formele historie betreft maar het verschil is niet meer te maken.

**Comment by joeribekker** [comment]
@ArjanKloosterboer Als ik het goed begrijp zeg je hier mee dat we `Zaak.einddatum` dus niet moeten wijzigen van een `date` naar een `datetime`? Als dat klopt mag je het ticket sluiten.

**Comment by ArjanKloosterboer** [comment]
Dat klopt.
