### ISSUE TITLE
Als redacteur van het vakblad Od zoek ik iemand die een artikel over Common Ground wil schrijven

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#504]
...zodat de lezers geïnformeerd worden over deze ontwikkeling. :-)

Dit is uiteraard geen user story, maar ik hoop dat jullie het mij vergeven dat ik langs deze weg contact hierover zoek.

Ik ben naast mijn werk als ambtenaar ook lid van de redactie bij het [vakblad Od](http://www.od-online.nl/). Dit vakblad richt zich op informatie- en archiefbeheerders bij de overheid. Common Ground en de ontwikkeling van zaak- en documentservices hierop zijn uiteraard relevante ontwikkelingen voor onze lezers. Ik ben daarom op zoek naar iemand die in begrijpelijke taal kan uitleggen wat hier gebeurt en hoe informatie- en archiefbeheer in deze ontwikkelingen worden meegenomen.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
@ehotting ?...

**Comment by TCIMEddy** [comment]
Hoi Marco, stuur mij even een mail groet, Eddy eddy.timmer@vng.nl

**Comment by Hugo-ter-Doest** [comment]
Ik neem aan dat dit geregeld is.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Ik denk het niet maar kan idd op closes

**Comment by MarcoKlerks** [comment]
Ik moet inderdaad nog mailen, maar er kwamen wat dingen tussendoor. Mijn mail komt er nog aan @TCIMEddy !

Het issue kan op closed.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Lijkt me mooie communicatie voor jou!

**Comment by Hugo-ter-Doest** [comment]
Ik wil dat wel doen.

**Comment by Hugo-ter-Doest** [comment]
@MarcoKlerks stuurt mij info.
