### ISSUE TITLE
Als behandelaar wil ik de status van de zaak / melding kunnen aanpassen...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#51]
...zodat de actuele status voor de betrokkenen inzichtelijk is.

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd
- [ ] Userstory is ingevuld op template architectuurschets
- [ ] Userstory is voorzien van veldmapping naar RGBZ2
- [x] Userstory past op wenselijk gebruik ZGW volgens GEMMA 2
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Korte toelichting, @MarcelMoerman? Hoe leidt wijzigen status tot "voldoende details"?

**Comment by Hugo-ter-Doest** [comment]
Dit is al mogelijk. Je kunt alleen nog niet meegeven wie de status heeft gezet.

**Comment by TCIMEddy** [comment]
Ik heb DoR toegevoegd

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Mooi dat dit al kan, kunnen we hiermee de User Story op close zetten of moet hij "herschreven worden" zodat we ook kunnen zien of deze gezet wordt

**Comment by Hugo-ter-Doest** [comment]
Deze kan op close denk ik omdat "gezet door" geen onderdeel is van de user story. @sergei-maertens hoe zou je dat moeten realiseren?

**Comment by sergei-maertens** [comment]
@Hugo-ter-Doest ik zie hier geen attribuut voor in de UML van RGBZ die tegen mijn muur hangt, dus zal morgen in de PDFs moeten duiken om te kijken of daar wat voorzien is

**Comment by Hugo-ter-Doest** [comment]
Ik wist dat gezetDoor een element is in de oude ZDS, vandaar. Ik moest ook even zoeken in RGBZ (p. 6 in het meest actuele concept van 13-6-2018)
"Een STATUS wordt altijd gezet door een BETROKKENE in zijn of haar ROL bij de ZAAK."

En in de verstuffing van van RGBZ is het "ZAK heeft ZAKSST is gezet door BTR"  (p. 10) en "STA is gezet door BTR" (pp. 12-13).

En in ZDS 1.2 (pp. 31-32) als element van actualiseerZaakstatus, een StUF-Zaken Lk01.

**Comment by sergei-maertens** [comment]
denk dat een URL-referentie naar de betrokkene dan prima kan, en bij het zetten van de status valideren dat de betrokkene in kwestie inderdaad een rol heeft in de zaak.

Of zouden we eerder moeten verwijzen naar de rol die de status zet, want daar kan je ook de betrokkene uit afleiden vervolgens?

@ArjanKloosterboer moet hier misschien input op geven

**Comment by ArjanKloosterboer** [comment]
De status wordt door een betrokkene in zijn of haar rol bij de zaak gezet. Vandaar dat deze relatie vanuit Status naar Rol loopt. Het zou m.i. dan ook uitgewerkt moeten worden in een url-referentie naar Rol.

**Comment by sergei-maertens** [comment]
Mooi - dit is dan ook volgens het UML-diagram van RGBZ. Dank voor de verheldering!

**Comment by ehotting** [comment]
Zou afgerond moeten kunnen worden

**Comment by TCIMEddy** [comment]
@sergei-maertens kan deze op close?

**Comment by ArjanKloosterboer** [comment]
Is er wat gerealiseerd dan? Kan er gerefereerd worden aan een rol van een betrokkene die de status gezet heeft? Welke gegevens zijn er nog meer nodig? Wat wil die behandelaar allemaal kunnen muteren bij het aanpassen van een status? Over welke gegevens van het RGBZ gaat het, ik zie geen mapping? Zit dit allemaal al in de Statussen-resource?

**Comment by sergei-maertens** [comment]
Kan nog niet dicht wegens wat Arjan aanhaalt

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Graag jouw visie en wat er naar aanleiding van het verzoek van Arjan nog moet gebeuren

**Comment by adgerrits** [comment]
Kleinigheid (?): in https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/status_create is nog geen "rol" opgenomen.

**Comment by TCIMEddy** [comment]
@adgerrits dank voor feedback! van harte welkom

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Dit kan toch al. Ik close deze en als ik het fout heb dan reopen jij hem weer

**Comment by sergei-maertens** [comment]
De opmerkingen hierboven gelden nog steeds

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest deze komt vanuit water/mor/amsterdam nog relevant?

**Comment by Hugo-ter-Doest** [comment]
Is gerealiseerd.
