### ISSUE TITLE
Als beheerder van zaaktypen wil ik zaaktypen kunnen aanmaken en wijzigen

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#513]
...zodat een zaak, waarop de userstory's #39, #153, #154, #161, #169 e.a. betrekking hebben, behandeld kan worden op basis van een zaaktype met desbetreffende parameters. 

Vanuit genoemde userstory's zijn resources in de Zaaktypen-API (ZTC) ontwikkeld met enkele lees-operaties. Maar, als je geen gegevens kunt registreren, dan valt er ook niets te lezen. Doel van deze userstory is om create- en update-operaties te ontwikkelen voor alle nu in ZTC-lees-operaties aanwezige gegevens.  

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
- [ ] De Zaaktypen-API maakt het mogelijk om alle, met de bestaande Zaakypen-API, te raadplegen gegevens vast te leggen en te wijzigen
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0 i.c. ImZTC 2.2 (incl. de daarin gespecificeerde businesslogica)
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Bepalen om welke velden het gaat [_verantwoordelijke_]
- [ ] Bepalen benodigde operaties op resources van de Zaaktypen-API [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting Graag prioriteit bepalen en aangeven hoe jij het wilt hebben. Ik heb al e.e.a. afgevinkt omdat het volgens mij duidelijk is. Corrigeren indien nodig uiteraard.

**Comment by ArjanKloosterboer** [comment]
Er lijkt een overlap met #369 te zijn.

**Comment by ehotting** [comment]
Idd dubbel, zie #369.
Ik neem deze tekst daar in op.
