### ISSUE TITLE
WIP: Refactor relatie Document en Zaak/Besluit

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#517]
Ik keek naar https://github.com/VNG-Realisatie/gemma-zaken/pull/496 en kreeg een beetje rillingen.

Huidige situatie:
```javascript
    {
        "url": "http://example.com",
        "informatieobject": "http://example.com",

        // Relatie
        "object": "http://example.com",
        "objectType": "besluit",
        "aardRelatie": "hoort_bij",
        "aardRelatieWeergave": "string",

        // Meta data bij relatie (voor Zaak)
        "titel": "string",
        "beschrijving": "string",
        "registratiedatum": "2018-10-29T09:21:01Z"
    }
```

De huidige situatie is een opeenstapeling van wijzigingen en compromissen waardoor een zinnige en developer-first API een beetje uit het oog is verloren naar mijn mening:

1. De "hoofd" relatie ligt bij de Documenten API: De relatie tussen Document en "Object" (zoals Zaak of Besluit) zit zowel in het de API van het Object, als in de Documenten API. Echter, de meta data zit bij de Documenten API.

Onduidelijke rationale: Waarom zit meta data van een Zaak in de Documenten API terwijl deze data niet relevant is vanuit het perspectief van de Documenten API? Meta data van een relatie tot een Zaak hoort typisch in de Zaken API. Dit was ook zo in RGBZ 1.0 en 2.0, maar in 2.x is het gewijzigd...

2. Alle relaties van Documenten naar Objecten zijn opvraagbaar met 1 request.

Bad design: Het zijn 2 wezenlijk andere relaties die niet via dezelfde resource te beschrijven zijn.

3. Meta data van een specifiek Object (zoals Zaak) moeten in deze resource worden opgenomen. Dit vervuilt de resource met meta data die afhankelijk van het `objectType` wel of niet gebruikt worden.

Bad design: Afhankelijk van hoeveel objecten er bij komen, komen er veel optionele attributen zijn die slechts in bepaalde cases waarde hebben. Zie ook 2.

4. Het attribuut `aardRelatie` is toegevoegd om semantiek aan de relatie te geven.

Onduidelijk rationale: Semantiek is belangrijk maar hier is de de aard van de relatie 1-op-1 gekoppeld aan het `objectType` en wordt dit attribuut alleen maar toegevoegd ter verduidelijking van iets wat ook te extraheren is uit andere attributen.

5. Het attribuut `aardRelatieWeergave` is toegevoegd zodat de "abstracte" constante van de enum `aardRelatie` een een mooie tekst kan worden weergegeven.

Onduidelijk rationale: Deze opzet is prima als het gaat om eenduidige weergave te verkrijgen. De use case echter om dit te standaardiseren zie ik gewoon niet. Afhankelijk van de UI moet deze naam wel/niet of anders gebruikt worden. Als je uit de constante "legt_vast" niet kan afleiden dat een handige weergave "legt vast" kan (!) zijn, tja...

**Voorstel**

@1 hoofd relatie terug bij component van Object (dus ZRC en BRC) waar de meta data vast ligt.
@2 opsplitsen van relaties zodat in 2 resources zodat de attributen specifiek voor de bewuste relatie zijn
@3 door (2) vervuilt meta data niet meer
@4 door (2) kan de semantiek op het attribuut van de relatie zitten
@5 is gewoon overbodig en vervalt door (4)

```javascript
    {
        "url": "http://example.com",
        "informatieobject": "http://example.com",

        // Relatie
        "besluit": "http://example.com",  // legtVast
    }
```
-en-
```javascript
    {
        "url": "http://example.com",
        "informatieobject": "http://example.com",

        // Relatie
        "zaak": "http://example.com",  // hoortBij

        // Meta data bij relatie (voor Zaak)
        "titel": "string",
        "beschrijving": "string",
        "registratiedatum": "2018-10-29T09:21:01Z"
    }

**Comment by ArjanKloosterboer** [comment]
Interessante redenering. Maar, er valt het een en ander op af te dingen vanwege m.i. onjuiste vooronderstellingen. Het zou waarschijnlijk een lange discussie worden als ik hierop zou reageren. Dit lijkt me iets om te bespreken. As. maandag?

**Comment by joeribekker** [comment]
Dat is prima uiteraard.

**Comment by joeribekker** [comment]
Vandaag overleg gehad met Arjan.

@1 Arjan leunt ook nog altijd op 2 gedachtes waardoor de keuze in principe open ligt.
@2 Opsplitsen resources staat Arjan achter, hoewel het hem voornamelijk gaat om het punt dat de relaties semantisch juist zijn (te herleiden).
@3 Is mooi meegenomen
@4 en @5 Arjan's weerstand hierbij is dat er een nieuw soort enum ontstond die niet in het IM staat, zelfs bestaande uit een key/value lijstje.

Volgens mij staat hiermee de weg open om dit te refactoreren maar zoals aangegeven geen hoge prio.

**Comment by joeribekker** [comment]
Grotendeels vervolgd in #775 en #979

**Comment by Hugo-ter-Doest** [comment]
Is reeds opgelost.
