### ISSUE TITLE
Als gemeente wil ik statussen kunnen filteren op zaak

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#518]
...zodat ik de historie van statussen kan weergeven van een zaak.

Issue vanuit Amsterdam:

> Er is geen filtering mogelijk bij de status op een zaak hierdoor zou je alles moeten ophalen. Dit is niet echt optimaal. Ik zou graag alle statussen willen die bij een zaak horen.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Taken**
- [ ] Toevoegen van filter velden aan ZRC/Status

**Comment by TCIMEddy** [comment]
@joeribekker is dit direct nodig voor project MOR?

**Comment by TCIMEddy** [comment]
@sergei-maertens lijkt me dan de hoogste prioriteit, zeker als het eenvoudig is. Wat mij betreft oppakken dan.

**Comment by TCIMEddy** [comment]
@sergei-maertens zonder tegenbericht van iemand oppakken.

**Comment by TCIMEddy** [comment]
@sergei-maertens ook dat is scrum hahaha

**Comment by sergei-maertens** [comment]
@TCIMEddy was al geimplementeerd & gereleased voor je vorige comment ;)
