### ISSUE TITLE
Als behandelaar wil ik locatie- en/of objectinformatie bij de melding ontvangen...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#52]
...zodat ik voldoende details weet om de melding op te volgen.

**Definition of done**

- [x] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [x] de specificatie is gepubliceerd leesbaar
- [x] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [x] Beschrijven welke data nodig is voor deze functie [ @MarcelMoerman ]
- [x] Aanleveren testdata [ @MarcelMoerman  ]
- [x] Schrijven (unit) test voor referentie-implementatie [ @sergei-maertens ]
- [x] Implementeren in referentie-implementatie [ @sergei-maertens ]
- [x] Genereren/opstellen van OAS 3.0 [ @sergei-maertens ]
- [ ] Functionele documentatie [ @michielverhoef ]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [ @sergei-maertens ]

**Architectuurschets**
Architectuurschets is hier #180 te vinden.

Voor wegschrijven locatie en overige informatie wordt er gebruik gemaakt van uitbreiding op ZAAK.objecttype

### Update op  ZRC API
| Attribuut | waarde | OPERATIE |
| :--- | :--- | :--- |
| Zaak.objecttype | | WRITE |
| Zaak.object.coordinaat | x,y | WRITE |

**Comment by sergei-maertens** [comment]
* ZTC aanpassingen: https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/2

**Comment by ArjanKloosterboer** [comment]
Dit issue is wat heen en weer geschoven tussen kanban-kolommen maar nooit in de review-status gekomen. Ik heb toch wel een opmerking. Hierboven staat ergens "Voor wegschrijven locatie en overige informatie wordt er gebruik gemaakt van uitbreiding op ZAAK.objecttype". Ik vraag me af of dat terecht is. Wat is dan dat objecttype? M.i. kan er alleen maar sprake zijn van de melding als objecttype. Is dat zo bedoeld? En die locatie, daarover staat hierboven "Zaak.object.coordinaat". Wat is dat? De locatie waarop een zaak betrekking heeft, is een attribuut van ZAAK (in het RGBZ). Daar is geen andere constructie voor nodig. 
M.i. ontbreekt hier inzicht in de structuur en inhoud van de betrokken informatie oftewel een informatiemodel. En dan bestaat het risico dat er rare dingen gebeuren …
Issue toch maar weer openen?

**Comment by sergei-maertens** [comment]
In de implementatie heb ik vertaalslag gemaakt naar juiste RGBZ modellen.
Het objecttype gedoe is precies de discussie die gisteren gevoerd is en nu
ook op Slack nog wat loopt. Laat ons daarom niet hier ook die discussie
opentrekken.

**Comment by ArjanKloosterboer** [comment]
Waar en hoe kan ik die vertaalslag en implementatie inzien?

**Comment by ArjanKloosterboer** [comment]
Dank. Die specificaties op swagger zijn zo te zien generiek, los van hoe je het toepast. Over het laatste voeren we elders discussie v.w.b. de zaaktypespecifieke eigenschappen en is wellicht iets voor de review, Prima. V.w.b. die generieke specificaties (get en post) van zaaktypespecifieke eigenschappen, die eigenschappen kunnen genest zijn (m.b.v. 'Groep' als groepattribuutsoort of object). Ik zie niet dat hiermee rekening is gehouden. Is iets voor een volgende sprint met een daarop geënte userstory, lijkt me. .
