### ISSUE TITLE
Als developer wil ik duidelijkere documentatie in de api specs.

### ISSUE THREAD

**Issue by JostCrow** [VNG-Realisatie/gemma-zaken#522]
Zeker voor een developer die niet meteen kennis heeft van alle benamingen voelt het vaak vaag aan. Namen zijn te algemeen of worden voor verschillende doeleinden gebruikt. Hierdoor is het lastig om goed te kunnen bepalen wat bruikbaar is. Ik zal hieronder een aantal voorbeelden geven.

**Dubbele namen voor verschillende dingen.**
Zo was het niet meteen duidelijk waar een objectinformatieobject precies voor was. De spec zelf zegt hier niets over. Pas bij de list komt er een uitleg naar voren. Deze is echter nog al vaag.

> Beheer relatie tussen InformatieObject en OBJECT.

Wat is een object? Bij het ZRC werdt er naar object verwezen naar een object van een externe applicatie. Is dat hier ook het geval? antwoord, nee als je bij de create call kijkt zie je dat het gaat om een zaak of besluit. Dit zou ook in de documentatie kunnen. Of mogelijk een referenctie naar de documentatie die over dit onderdeel gaat. Zonder dat de developer zelf zou hoeven zoeken of moet gaan gokken.

**Vaagheid bij de rollen**
> Koppel een BETROKKENE aan een ZAAK.

Waar komt deze betrokkene vandaan? Ik kan het in de api spec niet terug vinden. Dit zorgt voor verwarring.

**Vaagheid verplicte data**
verantwoordelijkeOrganisatie | string <uri> (Verantwoordelijke organisatie)
URL naar de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak.

Waar komt deze url vandaan? Waar kan ik een lijst vinden met niet natuurlijke personen? Moet ik deze van te voren al kennen?

**Waarvoor is het**
Klantcontacten/Zaak eigenschappen
Waarvoor worden de klant contacten gebruikt? In de api-spec zie ik niets waardoor dit duidelijk kan worden. 
Dit zelfde geld dus ook voor zaak eigenschappen.

Naar mijn idee kan de api-spec beter worden gedocumenteerd. Dit betekend niet dat alle informatie in de api-spec geplaatst moet worden. Bijvoorbeeld voor het klantcontact kan een link worden geplaatst waar je meer informatie over klantcontacten zou kunnen vinden. 

Het is fijner om meer concrete informatie te hebben over waar onderdelen vandaan komen en minder vage termen te gebruiken die meer duidelijkheid geven over wat het doel is van het veld/object.

*Toevoeging door Joeri, via opmerking van Sergei in #519 :*

> Ik heb overlegd met Jorik - er was verwarring over de flow van de calls en de conclusie is dat Jorik een call wilde doen die het DRC zelf onder water al doet.
> We ontsluiten bewust volledige URLs in plaats van parameters in URLs omdat alles met de volledige URLs moet werken.

Het moet duidelijk worden dat dit onder water moet gebeuren.

**Comment by JostCrow** [comment]
Dit zou ook geholpen hebben met de verwarring in ticket #519. 

Als hier bij dit [onderdeel](https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaakinformatieobject_create) zou staan dat dit wordt aangemaakt vanuit het drc met de objectinformatieobject_create call. Dan zou issue #519 niet gemaakt zijn.

**Comment by TCIMEddy** [comment]
@ehotting graag visie en prioriteit

**Comment by JostCrow** [comment]
Nog een voorbeeld, voor het [enkelvoudiginformatieobject](https://ref.tst.vng.cloud/drc/api/v1/schema/#operation/enkelvoudiginformatieobject_create) inhoud laten weten dat het hier gaat om een base64 string. Dit is niet duidelijk uit de api spec.

**Comment by ehotting** [comment]
Deze specifieke voorbeelden worden opgelost adhv deze user story, voor verdere omissies graag nieuwe user stories maken.

**Comment by TCIMEddy** [comment]
@joeribekker wil jij even kijken of dit een user story is concreet of wellicht al af dan close

**Comment by TCIMEddy** [comment]
Deze is te algemeen gesteld al onderkennen we de noodzaak. Indien er specifieke zaken zijn aparte user stories opvoeren
