### ISSUE TITLE
Als developer wil ik een minder omslachtige api

### ISSUE THREAD

**Issue by JostCrow** [VNG-Realisatie/gemma-zaken#523]
Er zijn wat stappen die niet logisch aan voelen. 

Het maken van een zaak zou je verwachten dat je de koppeling naar het object zou kunnen mee geven. Dit moet nu in een losse call gebeuren. Dit voeld niet heel logisch aan.

Hezelfde geld hier ook voor het enkelvoudiginformatieobject. Dit is ook niet met 1 call aan een zaak te koppelen.

Dit betekent niet dat de calls die nu bestaan om een zaak aan een object te koppelen niet meer moeten bestaan maar het zou makkelijker moeten kunnen.

**Comment by sergei-maertens** [comment]
Zouden convenience methods in de gemma-zds-client hier een goeie oplossing voor zijn? Iets als:

```python
client = ZrcClient()
client.create(
    'zaak', 
    informatieobject={...}, 
    object={...}
)
```

**Comment by JostCrow** [comment]
Dat zou zeker een goede oplossing kunnen zijn.

**Comment by TCIMEddy** [comment]
@ehotting graag visie en prioriteit

**Comment by ehotting** [comment]
Antwoord is dus dat de juiste optie wat ons betreft is dat er libraries komen om het voor de consumer eenvoudiger te maken, maar dat is vooralsnog buiten scope van ons scrum team.

**Comment by andyverberne** [comment]
Wanneer de oplossing is het maken van libraries voor consumers dan zul je dus voor elke technology stack een consumer library moeten gaan onderhouden, niet alleen voor Python. Dit lijkt mij geen goed idee. De oplossing moet dus zitten in het aanpassen/uitbreiden van de API.

Ik denk ook dat het een principe zou moeten zijn dat alle zoals het toevoegen van een document aan een zaak via 1 REST call gerealiseerd zouden moeten worden. Dit in het kader van performance en consistentie op de provider en consumer.

**Comment by Hugo-ter-Doest** [comment]
We maken eerst de CRUD/micro services gereed voor gebruik. En kijken dan nog een keer naar convenience API's. Welke calls en hoe te realiseren moeten we dan nog een keer bespreken.

**Comment by Hugo-ter-Doest** [comment]
Zie ook #413

**Comment by TCIMEddy** [comment]
User story is van belang maar wel breed opgenomen. Close hierom en het feit dat deze ook door andere User stories wordt afgedekt

**Comment by michielverhoef** [comment]
Opgenomen in Zaken API 1.5.0
