### ISSUE TITLE
Discussie over relaties tussen entiteiten keert telkens terug

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#527]
# Impediment

Zie ook https://github.com/VNG-Realisatie/gemma-zaken/issues/517

**Comment by joeribekker** [comment]
Begrijp niet zo goed waarom het een impediment is. Ik heb het juist als apart issue opgenomen om de voortgang zoals die nu is niet in de weg te staan. Als we de rationale voor de keuze documenteren kan ik met elke relatie invulling uit de voeten en hoeft het geen impediment te zijn. Wellicht is dit al ergens gedaan maar ik kon het niet vinden.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Terecht punt om aan te kaarten, dank! Het is idd niet de bedoeling om iedere keer zaken opnieuw ter discussie te stellen. @joeribekker heeft een issue aangemaakt waarin, hij een issue waarover veel discussie is geweest, opnieuw tegen het licht houdt. Wat mij betreft prima om nieuwe inzichten bespreekbaar te maken maar het moet de huidige sprint/snelheid e.d. niet in gevaar brengen. Volgens mij was dit ook niet de bedoeling van Joeri. @ehotting wil jij prioriteit bepalen en visie geven.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Ik sluit deze, volgens mij gaan we de goede richting op
