### ISSUE TITLE
Technische richting/scope moet helder worden

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#529]
# Impediment

Er zijn een aantal vragen die we moeten gaan beantwoorden m.b.t. de technische doelstellingen zodat we wat gerichter User Stories kunnen aanmaken vanuit techniek. Sommige vragen zijn al beantwoord via andere issues en of discussies, maar het is wellicht goed deze vragen+antwoorden wat explicieter op te nemen in de project scope/uitgangspunten documentatie.

* Moet heel RGBZ in de API? Zo ja, welke versie?
* Moeten alle DSO richtlijnen (die Hugo als zodanig had aangemerkt) verwerkt zijn, of niet?
* Moet autorisatie voltooid zijn?
* Wat wordt de status van ORC?
* Hoe gaan we om alle objecten uit RSGB waarnaar een Zaak kan verwijzen?
* Hoe gaan we om met personen die gerelateerd zijn aan een Zaak?
* Moeten we een migratie traject/plan maken?
* Moeten we backwards compatible zijn of niet (een beetje, zoals de visie aangeeft werkt niet)

**Comment by TCIMEddy** [comment]
@joeribekker dank! als er nog zaken komende dagen naar boven komen wil je ze dan in deze user story toevoegen. Ik zit a.s. woensdag uitgebreid met Eelco om backlog en sprintplanning te bepalen

**Comment by TCIMEddy** [comment]
@joeribekker Na vandaag maar even aangeven in deze impediment wat wel en nog niet beantwoord is

**Comment by Hugo-ter-Doest** [comment]
@joeribekker kun je aangeven waarop je nog antwoord moet hebben?

**Comment by Hugo-ter-Doest** [comment]
Moet heel RGBZ in de API? Zo ja, welke versie? Nee, entiteiten, relaties en attributen die in de praktijk nodig blijken komen in API's.
Moeten alle DSO richtlijnen (die Hugo als zodanig had aangemerkt) verwerkt zijn, of niet? Ja, in principe wel. Als  bepaalde principes niet worden gevolgd, is er een uitleg voor.
Moet autorisatie voltooid zijn? Ja, eind Q2 moet autorisatie gereed zijn.
Wat wordt de status van ORC? Krijgt geen status, maar geeft wel inspiratie voor de oplossingsrichting van andere entiteiten.
Hoe gaan we om alle objecten uit RSGB waarnaar een Zaak kan verwijzen? TODO
Hoe gaan we om met personen die gerelateerd zijn aan een Zaak? Als betrokkenen in een rol.
Moeten we een migratie traject/plan maken? Migratie krijgt aandacht in fase 2. Regulier overleg met Beheer wordt ook ingepland.
Moeten we backwards compatible zijn of niet (een beetje, zoals de visie aangeeft werkt niet)? Backwards compatible met 1.x? Nee. Wel voeren we een analyse of de functionaliteit van 1.x te realiseren is met 2.x en besteden we aandacht aan de mogelijkheden in een heterogeen landschap en aan migratie.

**Comment by TCIMEddy** [comment]
@joeribekker @Hugo-ter-Doest Is dit nog een impediment (retorische vraag) of is het een user story?

**Comment by Hugo-ter-Doest** [comment]
Waar kunnen de antwoorden het beste in worden verwerkt?
