### ISSUE TITLE
Als gebruiker van MijnApp wil ik bijgevoegde documenten van een zaak inzien

### ISSUE THREAD

**Issue by ppcjansen** [VNG-Realisatie/gemma-zaken#53]
Zodat ik de inhoud van het document kan zien.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Comment by ehotting** [comment]
Prioritering indien mogelijk omdat het oplevering #78 in volgende sprint verder kan brengen vanuit andere user story.

**Comment by ehotting** [comment]
Zonder specifieke architectuur & RGBZ mapping kan deze user story geen wijzigingen tot gevolg hebben in de API spec. Daarom sluit ik deze. Als MijnApp weer opgepakt wordt kunnen we deze heropenen.
