### ISSUE TITLE
Centrale repo met ontwerp-keuzes in plaats van per project

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#531]
Dus ook DoD aanpassen.

**Comment by joeribekker** [comment]
Prima, ik zou het iets scherper verwoorden: Ontwerp keuzes voor de APIs en OAS

Ik zou verder zeggen:

1. @michielverhoef maak een een repo aan
2. Template opstellen voor hoe een design keuze er uit ziet
3. Alle ontwerp keuzes middels PRs toevoegen.
4. DoDs aanpassen voor projecten om de design keuzes daar toe te voegen.

**Comment by michielverhoef** [comment]
Er bestaat al een centrale repo voor architectuur en standaarden (https://github.com/VNG-Realisatie/Architectuur-en-Standaarden) waar ook een begrippenlijst  ed. in staan. Is dat geen goede plek om de ontwerpkeuzes en alle andere overkoepelende informatie (templates ed?) kwijt te kunnen?

**Comment by ehotting** [comment]
Het zou nog en trapje hoger kunnen: https://github.com/Geonovum/KP-APIs/issues
Als we zorgen dat we landelijk de overstijgende design choices maken en daarnaast de domeinspecifieke op niveau van individuele API's standaardiseren we maximaal. Ik verwacht niet dat er daarnaast nog noodzaak is overkoepelende design choices op niveau VNG-R te maken.

**Comment by HenriKorver** [comment]
Eens met @ehotting. Het is beter om de overstijgende design choices meteen landelijk te bespreken. Dan krijg je meteen de expertise van de DSO API experts er gratis bij en besparen we een onnodige tussenlaag ;-)

**Comment by TCIMEddy** [comment]
Eens maar @HenriKorver ben jij dan verantwoordelijk om het daar in te brengen?

**Comment by HenriKorver** [comment]
@TCIMEddy Nee, wat mij betreft kan iedereen daar een overstijgende design choice inbrengen. Mocht het zo zijn dat een discussie op het landelijke forum in een impasse terecht komt omdat twee of meer VNG'ers het niet eens kunnen worden, pas dan zal ik het als mijn taak zien om in te grijpen en de VNG met één tong te laten spreken.

**Comment by TCIMEddy** [comment]
Wat mij betreft kan deze dan op close
