### ISSUE TITLE
Met welk doel bouwen we deze APIs en is daar functionele documentatie voor nodig?

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#535]
# Impediment

Alles wordt op dit moment geblokkeerd omdat er geen functionele documentatie meer wordt gemaakt. Zie o.a. #162 die verwijst naar #413. Ik denk dat hier een ontbrekend stukje visie naar voren komt die al wat langer suddert:

1. Wat voor APIs bouwen we (ofwel, voor wie of wat)?
2. Is functionele documentatie nodig voor dit soort APIs?

De tweede vraag speelt al langer: Wat wordt er precies verstaan onder functionele documentatie, voor wie is het en hoe moet dit er uit zien, en, is het überhaupt nodig? Deze lijkt nu samen te hangen met het soort APIs dat in dit project wordt ontwikkeld.

Op de eerste vraag leven in Slack en in Github comments enkele [plaatjes en namen](https://dzone.com/storage/temp/5344459-ex.png) rond: Experience APIs, Process APIs, System APIs, Composite APIs, Convenience APIs, etc. en ik vermoed dat het onduidelijk is wat voor APIs we aan het bouwen zijn.

**Comment by joeribekker** [comment]
Ik geef in ieder geval vanuit techniek mijn standpunt hierin:

PS. Ik gebruikt even de termen tussen haakjes uit het plaatje dat bij VNG op Slack de ronde doet voor de beeldvorming.

> 1. Wat voor APIs bouwen we (ofwel, voor wie of wat)?

Bij elk van deze termen gaat het om APIs **bovenop** andere APIs. Ikzelf heb ook wel eens Composite APIs genoemd als antwoord op vragen voor specifieke domeinen of cases.

Dit impliceerde bij mij ook direct het antwoord: We bouwen nu de onderste laag (System APIs), waarbij ik nog helemaal niet weet of er ook een laag boven op moet komen (Process APIs). De onderste laag is in ieder geval altijd nodig, of daar nu nog APIs bovenop worden gerealiseerd of niet.

REST is in de basis al zo veel eenvoudiger dan SOAP met StUF, dat een tussenlaag (Process APIs) wellicht niet nodig is maar dit moet uiteindelijk uit User Stories blijken. In dit stadium, lijkt het me wenselijk om eerst deze onderste laag die we nu aan het bouwen zijn (!) te realiseren voordat we gaan kijken of dat onvoldoende biedt voor ontwikkelaars om goed aan de slag te kunnen. Let wel dat deze onderste API laag gewoon **alles moet kunnen** en dat lage daarboven alleen maar voor "convenience" zijn.

Dat er APIs worden gebouwd die met de eindapplicaties communiceren en de ZDS APIs lijkt me evident (Experience APIs). De APIs die wij ontwikkelen moeten nooit direct worden aangesproken door een eindgebruiker (vanuit de browser of mobiele applicatie). Hier zal altijd een stuk software van een leverancier of gemeente zelf tussen zitten.

> 2. Is functionele documentatie nodig voor dit soort APIs?

Mijn standpunt hierin is altijd geweest dat ik het moeilijk vind om dit te bepalen aangezien de doelgroep mij te vaag of te breed is, en ik het lastig vind in te schatten wat deze doelgroep graag wil weten. Vanuit techniek zou ik aan enkele pagina's genoeg hebben, een beetje zoals het hoofdstuk "Model op hoofdlijnen" van [RGBZ 2.0](https://www.gemmaonline.nl/images/gemmaonline/d/d7/GEMMA_RGBZ_2.0_deel_1_CONCEPT3_20141204.pdf) maar verder voldoet voor mij de OAS.

**Comment by ArjanKloosterboer** [comment]
V.w.b. je eerste punt (soort API's), wat mij betreft is er op dit punt geen sprake van een impediment. We bouwen nu System-API's want die hebben we zonder meer nodig. In de evaluatie na afloop van dit project moeten we o.a. bespreken of dit volstaat. Maar dat mag de huidige scope nu niet beinvloeden. 

V.w.b. je tweede punt, Michiel en ik hebben onze poging tot functionele documentatie besproken. We kwamen daarin tot gewijzigde inzichten. Dat zou moeten leiden tot veel kortere functionele documentatie (het 'wat': wat doet het, wat kan ik er mee) terwijl de hoe-vraag (hoe zit het in elkaar, hoe werkt het, hoe moet ik het toepassen) gedocumenteerd zou moeten worden in de API's zelf. Nu loopt dit door elkaar in de (poging tot) functionele documentatie. Ik meen dat Michiel dit zou uitwerken, toch @michielverhoef ? OP de eerstvolgende sprintdemo zou een en ander gereed moeten zijn, lijkt me.

**Comment by joeribekker** [comment]
@ArjanKloosterboer In #162 geeft @michielverhoef aan niet verder te werken aan de functionele documentatie. Aangezien dit in de DoD staat vind ik dit zeker een impediment!

Als we uiteindelijk tot de conclusie komen dat er voor dit soort APIs andere of geen documentatie nodig is prima, maar dan wordt deze impediment opgelost door de DoD als zodanig aan te passen (lees: functionele documentatie er uit) of er moet overeenstemming zijn om andere documentatie te schrijven (wat mijn insziens een issue moet zijn in Github).

> V.w.b. je eerste punt (soort API's), wat mij betreft is er op dit punt geen sprake van een impediment. We bouwen nu System-API's want die hebben we zonder meer nodig. In de evaluatie na afloop van dit project moeten we o.a. bespreken of dit volstaat. Maar dat mag de huidige scope nu niet beinvloeden. Vooral doorgaan.

Dat is mooi, zo sta ik er ook in!

**Comment by michielverhoef** [comment]
> @ArjanKloosterboer In #162 geeft @michielverhoef aan niet verder te werken aan de functionele documentatie. Aangezien dit in de DoD staat vind ik dit zeker een impediment!

De achterliggende reden dat ik niet verder werk is dat ik niet verder _kan_  werken. Domweg omdat geen enkele versie van de functionele documentatie goedgekeurd wordt door Arjan. In een gesprek hebben we eea. doorgenomen en snap ik zijn standpunt wel dus echt kwalijk nemen doe ik het hem niet. Alleen heeft nieuwe documentatie volgens het eerder gemaakte format geen enkele zin als het niet door de review gaat komen.

Wat het lastig maakt is denk ik goed uit te leggen met de vergelijking met lego. Zoals hierboven vermeld bouwen we nu een system api. Dat is te vergelijken met basis lego steentjes in verschillende soorten maten en kleuren, zonder echt expliciete functionaliteit. Eigenlijk zie ik de huidige versie van de system api als een heel beperkt setje steentjes, zeg maar het bekende 2 bij 4 noppen blokje. Pas in de proces en vooral experience api komt functionaliteit om de hoek kijken. Die kun je dan ook beschrijven in functionele documentatie. In de lego vergelijking is dit het equivalent van een kraan gemaakt uit technisch lego. Dat is een product waarmee je bepaalde dingen kunt en die kun je beschrijven.

Of de documentatie voor de eerstvolgende sprint demo gereed is hangt volledig af van het antwoord op de vraag of die functionele documentatie wel iets toevoegt en hout snijdt. Zoals ik het nu zie is de systeem api de onderlaag/basisvoorwaarde om de resources aan te spreken met CRUD operaties. Daar zit geen functionaliteit in.  Ik vraag me dan ook sterk af of voor de system api functionele documentatie wel van toepassing is en of we dit niet moeten schrappen uit de DoD. 

Op de verdere opzet van de API's ga ik hier niet in, daar gaat dit impediment niet over. Maar ik heb er zeker een mening over.

**Comment by ArjanKloosterboer** [comment]
> Ik vraag me dan ook sterk af of voor de system api functionele documentatie wel van toepassing is en of we dit niet moeten schrappen uit de DoD.

Als er geen functionele documentatie zou komen, waar kan ik (en andere niet technisch ingewijden) dan vinden wat er beschikbaar is, wat dat doet en wat er mee kan? Moet iedereen dan de technische specs induiken? Of zie ik mogelijkheden (bronnen) over het hoofd?

**Comment by ehotting** [comment]
@TCIMEddy staat op 2 borden

**Comment by TCIMEddy** [comment]
@ehotting staat nu op 1 bord maar is het nog een impediment. Of moet ik er een user story van maken?

**Comment by ehotting** [comment]
Dit vraagstuk is afgehandeld, in zoverre dat de vraag van Joeri door hemzelf beantwoord is en Arjan en Jeffrey zich daar in kunnen vinden. De vraag welke vorm functionele docs moeten hebben is in andere user stories aan de orde.
