### ISSUE TITLE
Zaken API bevragen ZAAK geeft wel kenmerken maar geen eigenschappen terug

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#536]
In het antwoord van de operaties zaak_list (https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_list)  en zaak_read (https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_read) worden eventuele eigenschappen niet terug gegeven. Deze moeten apart worden opgevraagd met de operatie zaakeigenschap_list (https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaakeigenschap_list).
Dit is raar want het attribuut kenmerk wordt wel genest opgenomen. 

Dit verschil zal waarschijnlijk komen doordat EIGENSCHAP in de ZTC gekoppeld wordt aan de ZAAK via het ZAAKTYPE en als zodanig een aparte resource is. Maar dan zou het minimaal handig zijn wanneer bij het opvragen van een ZAAK aangegeven wordt dat er EIGENSCHAPPEN zijn die opgevraagd moeten worden.

Als dit niet in de system API thuis hoort (watik me kan voorstellen) zou ik dit in een proces of experience API opnemen, het maakt het leven van de ontwikkelaar die de API moet gaan toepassen een stuk makkelijker denk ik.

**Comment by joeribekker** [comment]
Goed opgemerkt. We hebben deze 2 technisch anders verwerkt, om even te kijken wat het beste werkt in de praktijk. Functioneel werkt het beide maar de oplossing is technisch anders.

**Comment by ehotting** [comment]
Goed om keuze te maken en consequent door te voeren ivm voorkomen tech debt

**Comment by joeribekker** [comment]
Bestempeld als niet kritisch

**Comment by joeribekker** [comment]
Concreet besproken:

Een lijstje aan de ZAAK toevoegen met URLs naar EIGENSCHAPpen. Op deze manier kan hij (later) ook met `?expand` uitgebreid worden.

**Comment by joeribekker** [comment]
Waarde voor leveranciers: Je ziet direct of je EIGENSCHAPpen moet opvragen.

**Comment by sergei-maertens** [comment]
Fixed in https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/commit/ffeeea3bbea65379dae2dc80fb88e455d9b37792

**Comment by PDG65** [comment]
Aantal punten gecorrigeerd van 5 naar 1 omdat 5 punten van vorige sprint is en hier alleen nog review voor nodig was
