### ISSUE TITLE
Als PO wil ik dat het excel-sheet waarin op veldniveau de relatie wordt gelegd tussen API en RGBZ beheerd wordt

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#538]
...zodat we altijd overzicht hebben tussen de API en het informatiemodel..

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] analyse is na iedere sprint

**Acceptatiecriteria**
- [ ] up to date
- [ ] md document (?)

**Taken**
- [ ]

**Comment by joeribekker** [comment]
Excel -> Markdown 👍

**Comment by Hugo-ter-Doest** [comment]
Waar is het spreadsheet? @TCIMEddy kun je dat koppelen aan dit issue?

**Comment by TCIMEddy** [comment]
https://github.com/VNG-Realisatie/gemma-zaken/issues/405

**Comment by TCIMEddy** [comment]
ziet in bovenstaande link
