### ISSUE TITLE
Als gebruiker van MijnApp wil ik een document bij een zaak kunnen toevoegen

### ISSUE THREAD

**Issue by ppcjansen** [VNG-Realisatie/gemma-zaken#54]
zodat ik op verzoek van de gemeente mijn lopende zaak met documenten kan aanvullen.

**Comment by TCIMEddy** [comment]
@sergei-maertens Dit is volgens mij al mogelijk toch?

**Comment by ehotting** [comment]
Zonder specifieke architectuur & RGBZ mapping kan deze user story geen wijzigingen tot gevolg hebben in de API spec. Daarom sluit ik deze. Als MijnApp weer opgepakt wordt kunnen we deze heropenen.
