### ISSUE TITLE
Als API-lab deelnemer wil ik gebruik kunnen maken van een demo client die ZDS 2.0 praat

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#544]
...zodat ik kan testen tegen mijn provider implementatie.

**Taken**
- [x] Demo client compatible maken met laatste versie componenten
- [x] Demo client opnemen in documentatie
- [x] Tutorial opzetten voor demo client (van Docker installatie tot curl verzoek)
- [x] Demo client testen als Docker en communicatie met referentie implementaties in Dockers
- [x] Tutorial om Demo client aan de praat te krijgen

**Comment by TCIMEddy** [comment]
in progress en anders terugzetten ajb
