### ISSUE TITLE
Het lijkt er op dat we API's op twee plekken en soms tegenstrijdig documenteren

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#547]
# Impediment

Een API wordt in de API-specificatie zelf gedocumenteerd en er wordt het een en ander in het document standaard.md beschreven. En soms wordt hetzelfde onderwerp in beide beschreven, en dan soms nog tegenstrijdig ook. Waar documenteren we nu wat? Wat is de rol van standaard.md? Hoe beschrijven we een en ander? Uiteraard technisch, maar het moet semantisch wel kloppen. Ook tegen dat laatste wordt m.i. soms gezondigd. Hoe gaan ontwikkelaars, die iets met een API gaat doen, dit interprteren? Leidt dat tot het beoogde resultaat van de Common Ground-beweging?

**Comment by sergei-maertens** [comment]
@ArjanKloosterboer ik meen te weten waarop je doelt, maar volgens mij is dit niet tegenstrijdig (wel anders verwoord). Kan je specifiek aangeven wat er tegenstrijdig is? Want dat moet dan gecorrigeerd worden natuurlijk.

**Comment by TCIMEddy** [comment]
Dit is denk ik geen impediment maar moet wel opgelost worden. @ArjanKloosterboer Aangezien hij op mijn naam staat stuur mij de issues dan ga ik die proberen op te lossen. Het staat je volgens mij vrij om wijzigingen via een PR in het md document te doen.
