### ISSUE TITLE
Als gebruiker van MijnApp wil ik een notificatie in MijnApp krijgen als de status van een zaak wijzigt

### ISSUE THREAD

**Issue by ppcjansen** [VNG-Realisatie/gemma-zaken#55]
zodat ik proactief en real-time op de hoogte gesteld wordt van de voortgang van mijn zaak.

gerelateerd aan #397

**Comment by jgortmaker1** [comment]
eerst een architectuurvraagstuk..

**Comment by TCIMEddy** [comment]
gerelateerd aan #397

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Kun je deze toch een prio geven zodat ik kan aangeven hoe snel het moet worden opgepakt binnen SQARCH

**Comment by Hugo-ter-Doest** [comment]
Jazeker, is prio hoog.

**Comment by joeribekker** [comment]
Scope hier wordt gedekt in https://github.com/VNG-Realisatie/gemma-zaken/pull/764 middels een POST/PUT op Zaak API resource Status.

**Comment by joeribekker** [comment]
Kapstok US #792 dekt dit af, minus de taak/afhandel-applicatie functies die out-of-scope zijn.
