### ISSUE TITLE
Als maintainer wil ik goede CONTRIBUTING richtlijnen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#550]
...zodat PRs volgens een vast stramien kunnen worden gemaakt.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd

**Taken**
- [ ] Voeg CONTRIBUTING bestand toe aan componenten repo's met technische tips
- [ ] Voeg een PR template toe aan de componenten repo's

**Comment by joeribekker** [comment]
Concrete aanleiding is: https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/15

We willen graag PRs van developers maar wel zodat het een beetje in lijn is met wat we willen. Deze User Story adresseert 2 puntjes om dit proces te verbeteren.

Ik assign Eelco om de prio in te schatten.

**Comment by ehotting** [comment]
Vraag me af of een contributing guide direct het gewenste gevolg heeft. Als het weinig tijd kost kan het natuurlijk.  
Haarlem: https://haarlem.github.io/CONTRIBUTING/
Amsterdam: https://amsterdam.github.io/CONTRIBUTING/
NLX (VNG-R): https://gitlab.com/commonground/nlx/blob/master/CONTRIBUTING.md

**Comment by ehotting** [comment]
Prio M omdat we hopen dat er issues komen n.a.v. API lab

**Comment by Hugo-ter-Doest** [comment]
Issues leiden we wel in goede banen via de templates voor issues en de borden. PRs is een ander verhaal. Ik kan me voorstellen dat je daar wat eisen aan stelt. Zoals tests slagen, documentatie aanwezig, changelog bijgewerkt.

**Comment by joeribekker** [comment]
@TCIMEddy Waarom zit dit opeens in sprint 9?

**Comment by TCIMEddy** [comment]
Sorry nu op juiste plaats (Scherp!)
