### ISSUE TITLE
Als API-lab deelnemer wil ik dat er demo data beschikbaar in de componenten

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#553]
...zodat ik niet eerst van alles moet aanmaken en configureren.

**Taken**
- [x] ZTC vullen met demo data (2 of 3 zaaktypen) (@Hugo-ter-Doest )
- [x] Zorgen dat de demo client wat data heeft om door zaken, besluiten en documenten te klikken.

**Comment by TCIMEddy** [comment]
Volgens mij is dit in Progress (anders terugzetten ajb)

**Comment by ehotting** [comment]
High prio ivm deadline - moet gereed zijn voor API lab op 4 december

**Comment by Hugo-ter-Doest** [comment]
Twee zaaktypen uit de ZTC van Omgevingsdienst Haaglanden ingevoerd: Vergunningaanvraag regulier behandelen en deelzaaktype toetsing uitvoeren. Mogelijk volgt nog een vervolgzaaktype voor toezicht.
