### ISSUE TITLE
Als burger wil ik via een portaal inzage in de producten en diensten die er geleverd worden vanuit dit portaal

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#56]
...
zodat ik weet welke informatie ik hier kan vinden

**Comment by jgortmaker1** [comment]
afvoeren. dit heeft niets met ZGW te maken
hiervoor kun je een PDC (producten- en dienstencatalogus) kopen..

**Comment by RvdKlip** [comment]
@jgortmaker1 is er geen enkele afhankelijkheid tussen product/dienst en zaaktype ?

**Comment by jgortmaker1** [comment]
je moet ergens configureren dat een aangevraagd product van type x afgehandeld wordt volgens zaaktype y
maar die burger ziet enkel de pdc en die wordt niet gevoed vanuit een ZTC

**Comment by TCIMEddy** [comment]
@ehotting Volgens mij valt deze user story niet binnen de scope, dus wat mij betreft sluiten

**Comment by ehotting** [comment]
Buiten scope inderdaad, kan altijd later opnieuw worden opgevoerd vanuit userstory
