### ISSUE TITLE
Zaaktype heeft geen Besluittype in het ZTC

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#566]
Dit element ontbreekt in het ZTC bij Zaaktype. De omgekeerde relatie is er wel.

**Comment by sergei-maertens** [comment]
Maand geleden gefixed in https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/commit/ab36c9bd27e9abb460f2e797fce48b0b282b636b
