### ISSUE TITLE
Onderzoek asymetrische encryptie autorisatie ipv shared secret

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#568]
-> pubkey in header

**Comment by TCIMEddy** [comment]
@sergei-maertens is dit nog relevant in oplossing

**Comment by sergei-maertens** [comment]
Ja

**Comment by michielverhoef** [comment]
Dit is buiten scope van Zaakgericht werken en zou moeten worden opgepakt in een apart traject voor een Autorisaties API.
