### ISSUE TITLE
JWT + OpenID connect? JWK?

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#569]
Onderzoeken n.a.v. opmerkingen tijdens demo 6

Zie: https://openid.net/developers/jwt/
Zie: https://tools.ietf.org/html/rfc7517 (JSON Web Key)

**Comment by TCIMEddy** [comment]
@ehotting graag prio en toevoeging

**Comment by TCIMEddy** [comment]
@sergei-maertens is dit nog relevant gezien de ontwikkelde oplossing?

**Comment by sergei-maertens** [comment]
Het is in de context van audit-trail misschien zelfs relevanter geworden. Open vraag, met lage prio. Mag blijven as it is.

**Comment by michielverhoef** [comment]
Dit is buiten scope van Zaakgericht werken en zou moeten worden opgepakt in een apart traject voor een Autorisaties API.
