### ISSUE TITLE
als burger wil ik via een portaal inzage in alle zaken die spelen in mijn fysieke omgeving 

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#57]
...
zodat ik centraal alle overheden kan afhandelen binnen 1 loket
en direct kan beschikken over up-to-date informatie

**Comment by jgortmaker1** [comment]
dat mag ook niet van de AVG
er zijn wel specifieke gevallen wat wel mag, bv alle vergunningsaanvragen binnen een straal van x km binnen een postcodegebed inzien (moet iemand even checken)

dus aub zo scherp maken

**Comment by Hugo-ter-Doest** [comment]
Het loket zal meerdere ZRC's moeten bevragen. En bij de ZRC moet je zaken kunnen ophalen/filteren op basis van locatie/geometrie. Het laatste kan al.

**Comment by michielverhoef** [comment]
Dat klinkt dan alsof dit issue gesloten kan worden?
