### ISSUE TITLE
Verkeerde foutmelding in geval van onjuist JWT-token

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#570]
Als je (per ongeluk) niet de goede token-key in het veld Authorization zet, krijg je een 500 melding (internal server error)  in plaats van een 403 melding (not authenticated)

**Comment by HenriKorver** [comment]
Ik zie nu dat deze fout al eerder is gemeld op een andere plek: https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/issues/30

**Comment by sergei-maertens** [comment]
Yep, ga ik zo oplossen :-)

**Comment by sergei-maertens** [comment]
Core fix in https://github.com/VNG-Realisatie/gemma-zaken-common/commit/36b50e0a4c8f1d67952069a312c6dc1aa0b2516c

Toegepast in https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/commit/6670a05e6da1f9692d4bb847116c502876a663e3, https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/commit/c15d1be711260d07269aef92662c002f87d37e0c, https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/commit/579b7dfbb4cf721f312479de4a87c781338e33e0 en https://github.com/VNG-Realisatie/gemma-besluitregistratiecomponent/commit/f38b66673ed04fc3ccb8adfc2d7b70159c5d38f0
