### ISSUE TITLE
Als burger wil ik via portaal wijzigingen kunnen doorvoeren in mijn fysieke omgeving

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#58]
...
zodat ik centraal alle overheden kan afhandelen binnen 1 loket

**Comment by jgortmaker1** [comment]
dat klinkt wel mooi: via een website een boom laten planten in mijn straat...:-)
maar ook deze is veel te vaag. Afvoeren (of heel erg aanscherpen)

**Comment by TCIMEddy** [comment]
@michielverhoef zou je dit iets duidelijker willen beschrijven. Ik begrijp niet wat wijzigingen in fysieke omgeving inhoudt?

**Comment by ehotting** [comment]
@RvdKlip Hoe is deze user story bedoeld?

**Comment by RvdKlip** [comment]
Gaat uit van het idee om een burger een (3D) weergave van de eigen straat, plein of wijk te geven met hierin mogelijkheden om de consequenties van beoogde wijzigingen (denk aan boom eraf, nieuw huis erbij, bestaand huis verbreden, weg versmallen, etc.) vooraf in beeld te brengen. Met het advies van welke ‘zaken’ her en der daarvoor moeten worden aangevraagd en geregeld. Ook al uitstaande of toegekende wijzigingen(zaakinformatie) in de fysieke omgeving zo in beeld brengen. Dit zodat burger weet welke wijzigingen gepland zijn en welk effect dit heeft op de eigen omgeving.

Hoog DSO karakter dus. Leidt tot opvragen van zaakinformatie of starten van nieuwe zaken. Ik ga er vanuit dat dit reeds gerealiseerde standaard functionaliteit is. Sluiten dus.

**Comment by ehotting** [comment]
OK
