### ISSUE TITLE
Zaaktypecatalogus versionering: hoe?

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#586]
Bijna alle objecttypen in het ImZTC hebben `beginGeldigheid` en `eindGeldigheid` - wat lijkt op een aanzet tot versionering. Er zijn beperkingen aan deze attributen (als: begin geldigheid moet gelijk zijn aan zaaktype versiedatum).

Deze opzet is niet duidelijk en maakt technische implementaties (checks op uniciteit) lastig, dus dit moet even kritisch bekeken worden en overwegen hoe het eventueel beter kan.

**Comment by Hugo-ter-Doest** [comment]
Ik kijk even naar zaaktypen. Zaken van een bepaald zaaktype blijven wijzen naar de oude versie van het zaaktype, omdat het zaaktype o.a. bepaald hoe een zaak wordt behandeld en gearchiveerd. De <code>Datum begin geldigheid zaaktype</code> en <code>Datum einde geldigheid zaaktype</code>. Die data hebben een dubbele functie volgens mij: het aanzetten van een bepaalde versie vanaf een bepaalde datum, maar ook historie bijhouden.

**Comment by ArjanKloosterboer** [comment]
Het ImZTC kent inderdaad versies van een zaaktype. De attributen 'Datum begin geldigheid' en 'Datum einde geldigheid' van een objecttype (Zaaktype, Statustype, Resultaattype e.d.) hebben daarmee evenwel niet zo veel te maken. Zij markeren als het ware de geboorte- en sterfdatum van een object van een dergelijk objecttype: vanaf wanneer was het object geldig en vanaf wanneer niet meer.  Wel zijn deze attributen voorzien van een regel: 'De datum is gelijk aan een Versiedatum van het gerelateerde zaaktype' resp. 'De datum is gelijk aan de dag voorafgaand aan een Versiedatum van het gerelateerde zaaktype.' Een object kan dus niet op een willekeurige datum geldig worden of zijn geldigheid verliezen; dit kan alleen op de datum waarop een nieuwe versie van het zaaktype geldig wordt. 
Voor vrijwel elke attribuutsoort in het ImZTC is Materiele historie = "ja" gespecificeerd. Oftewel, de successievelijke waarden van een attribuutsoort van een object moeten beschikbaar zijn. Maar, ook hier geldt een regel: 'De attribuutsoort verandert alleen van waarde (materiële historie) op een datum die gelijk is aan een Versiedatum van het gerelateerde zaaktype.' Bij elke waardewijziging zou een nieuwe versie van het object (Statustype, Resultaattype e.d.) ontstaan. Genoemde regel perkt de mogelijkheden in om waarden te wijzigen: alleen op de datum waarop een nieuwe versie van het zaakype geldig wordt. kunnen waarden van het zaaktype en daaraan gerelateerde statustypen, resultaattypen e.d. wijzigen. Door deze methodiek hebben de waarden van alle attributen van een zaaktype en van alle daaraan gerelateerde objecten altijd dezelfde periode waarin zij geldig zijn.   
Dit is dus een inperking van het generieke historiemechanisme waarin de waarde van een attribuut op een willekeurig moment kan wijzigen, onafhankelijk van waardewijzigingen van andere attributen van hetzelfde en van andere objecten.

**Comment by Remkodehaas** [comment]
misschien hoort deze bij Sprint 12: Historie- en versiebeheer

**Comment by TCIMEddy** [comment]
zie #889
