### ISSUE TITLE
 Als burger of bedrijf wil ik via de gemeentelijke website een parkeervergunning, horecavergunning of evenementenvergunning kunnen aanvragen en laten behandelen...

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#59]
...zodat ik toestemming krijg om te parkeren en mijn evenement kan houden.

**Comment by jgortmaker1** [comment]
dit wordt inderdaad al geboden door DSO. Dus is al klaar :-)

Er zijn nog andere soorten vergunningen, maar sec de mogelijkheid beden om iets aan te vragen heeft geen enkel relatie met ZGW...
dan zou ik hem scherper maken: als burger of bedrijf wil ik via de gemeentelijke website een parkeervergunning kunnen aanvragen...

**Comment by RvdKlip** [comment]
Ik neem aan dat 'om een aanvraag bij de gemeente te krijgen' er ook een registratie in de gemeentelijke ZRC (incl. bijlagen) tot stand moet zijn gebracht, conform ZKDMS. Wordt hiervoor onze API gebruikt?

**Comment by jgortmaker1** [comment]
nee, die wordt hiervoor net gebruikt.
er komt een bericht vanuit DSO naar de gemeente (via digikoppeling) dat er een nieuwe aanvraag klaar staat
en daarin zit een link naar een DSO-API die de gemeente kan aanroepen om de aanvraag op te halen..

**Comment by jgortmaker1** [comment]
zie hier: https://www.gemmaonline.nl/index.php/Systemen_gemeente en hier https://www.gemmaonline.nl/index.php/Omgevingswetproces_-_015_Behandelen_vergunningaanvraag

standaard voor de notificatie is STAM

**Comment by TCIMEddy** [comment]
@ehotting Moeten we wat met deze user story?

**Comment by ehotting** [comment]
Is OK als er velden + mapping op RGBZ bij aangeleverd kunnen worden...

**Comment by jgortmaker1** [comment]
maar dan voor niet DSO-vergunningen, dus DSO-label verwijderen en ook het zinnetje "voor alle overheden"..

**Comment by Hugo-ter-Doest** [comment]
Je kunt al een zaak creeren.
