### ISSUE TITLE
Als burger wil ik via mijn PIP of MijnOverheid mijn lopende zaken incl. contacten kunnen raadplegen en documenten kunnen uploaden

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#60]
zodat ik de voortgang kan volgen en nieuwe informatie kan toevoegen.
**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by jgortmaker1** [comment]
erg vaag, wat zijn dossiers? welke dossiers?
wat voro loket? ik lees alle overheden, dus dt kan alleen maar  mijn overheid zijn...
maar die biedt dergelijek functionaliteit niet.

Dus ofwel flink aanscherpen. of afvoeren

**Comment by TCIMEddy** [comment]
Eens met Jeffrey, suggestie om het aan te scherpen

Als burger wil ik via mijn<<gemeente>>.nl de documenten behorende bij mijn melding openbare ruimte kunnen raadplegen en nieuwe documenten kunnen uploaden, zodat ik snel en goed mijn melding kan updaten.

**Comment by Hugo-ter-Doest** [comment]
Dossiers zijn zaken denk ik. 
Loket kan zowel PIP van de gemeente als mijnoverheid Lopende zaken zijn. Maakt voor de API niet zoveel uit.
Updaten en muteren zijn synoniemen.

Suggestie voortbouwend op die van Eddy:
Als burger wil ik via mijn<>.nl de documenten behorende bij mijn lopende zaken kunnen raadplegen en documenten kunnen uploaden, zodat ik de voortgang van mijn meldingen en aanvragen kan volgen en nieuwe informatie kan toevoegen.

**Comment by Hugo-ter-Doest** [comment]
En dan het DSO label weghalen

**Comment by jgortmaker1** [comment]
ik denk dat het functioneel wel uitmaakt of het een gemeenteportaal of een overheidportaal betreft..
in het eerst geval hoef je bv niet me te geven van welke organisatie de zaak is (attribuut bronorganisatie)

**Comment by Hugo-ter-Doest** [comment]
Is mogelijk door te filteren op BSN of persoonsgegevens.
