### ISSUE TITLE
Als leverancier (van ESB) wil ik systemen die ZDS 1.x ondersteunen kunnen koppelen met systemen die ZDS 2.x ondersteunen

### ISSUE THREAD

**Issue by Elanthiel** [VNG-Realisatie/gemma-zaken#600]
zodat migratie van de oude naar de nieuwe standaard wordt ondersteund.

In de periode dat het ene systeem nog StUF ZS-DMS gebruikt en het andere systeem de nieuwe zaken-API's, kan het vertalen van de workflow tussen de twee standaarden tot problemen leiden. In de workflow van StUF ZS-DMS wordt eerst het ZaakID aangevraagd, en daarna pas de zaak gepost. In de nieuwe standaard wordt de zaak gepost en ontvangt de consumer als antwoord daarop het zaakID.

Bij vertaling van de nieuwe standaard naar de oude standaard is dat geen probleem. We ontvangen een zaak in de nieuwe standaard, vragen eerst aan het oude systeem een zaakID aan, posten dan de zaak, en geven het zaakID terug aan de consumer. Echter bij vertaling van de oude standaard naar de nieuwe standaard kan dat wel tot problemen leiden. Het oude systeem zal eerst een zaakID aanvragen, en pas als het zaakID binnen is de zaak posten. Dit is niet te vertalen naar de workflow van de nieuwe standaard. 

Ditzelfde probleem geldt overigens bij het aanvragen van documentidentificaties tijdens de bijlagen toevoegen workflow.

**Comment by joeribekker** [comment]
Je kan nog steeds prima zelf een `Zaak.identificatie` meegeven aan een `POST /api/v1/zaken` om deze te zetten. Als je deze niet meegeeft wordt er inderdaad eentje gegenereerd.

Zie: https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_create

Wellicht begrijp ik het probleem niet 100%. Kan je dit verder toelichten of tips geven hoe dit opgelost kan worden?

**Comment by Hugo-ter-Doest** [comment]
Is geen impediment, maar een user story voor migratie in het applicatielandschap van de gemeente, waarbij systemen die oude versie ZDS spreken worden gekoppeld met systemen die nieuwe(re) versie spreken. Op bespreken gezet.

**Comment by michielverhoef** [comment]
> Je kan nog steeds prima zelf een Zaak.identificatie meegeven aan een POST /api/v1/zaken om deze te zetten. Als je deze niet meegeeft wordt er inderdaad eentje gegenereerd.

In de StUF gebaseerde ZDS bestaat de service genereerZaakidentificatie. Dit is omdat er asynchrone berichten gebruikt worden en de consumer dus niet altijd gelijk een antwoord met bevestiging van de aangemaakte zaak (inclusief identificatie) krijgt.

Bij deze API bestaat die service niet en het is dus ook niet mogelijk het StUF bericht genereerZaakidentificatie te vertalen naar een API call.

Dit zou beschreven moeten worden in documentatie die de verhouding tussen StUF ZDS en de API beschrijft.  Zie ook #631

**Comment by joeribekker** [comment]
@michielverhoef gaat dit toelichten.

**Comment by michielverhoef** [comment]
Er wordt in deze discussie iets te snel gedacht in termen van berichten vertalen terwijl de onderliggende architectuur en informatiehuishouding niet genoemd worden. Bovendien vinden er in het zaakgericht werken meer stappen plaats dan alleen het aanmaken van een zaak. Het aanmaken van een zaak is eigenlijk nog het simpelste  bericht in dit verhaal. Daarom doe ik een stapje terug.

Wat betreft de opslag van gegevens verschillen de principes achter de Zaakgericht Werken API’s fundamenteel van de principes achter Zaak- Documentservices. In de oude GEMMA 1 architectuur bevat het Zaaksysteem (ZS) een kopie van de zaakgegevens van de zaken die in de verschillende vakapplicaties (TSA's) zijn opgeslagen en daar worden behandeld. In het ZS worden deze gegevens dus volledig opgeslagen, ook die van gerelateerde objecten, personen etc…

In de Common Ground/GEMMA Gegevenslandschap worden gegevens eenmalig opgeslagen en bij de bron opgehaald. Gegevens van gerelateerde objecten, personen etc… worden dus niet in het Zaakregister (voorheen Zaakregistratiecomponent of ZRC) opgeslagen maar via een verwijzing (in de vorm van een URI) opgenomen bij de zaak.

Voor een vakapplicatie (een zaakafhandelcomponent of ZAC) betekent dit dat de gegevens van de zaken die in behandeling zijn over een aantal verschillende bronnen (types registers, bijvoorbeeld een Besluitregister, Documentregister, Zaaktypenregister) verdeeld worden opgeslagen. Deze bronnen stellen deze gegevens beschikbaar via API's, en objecten (resources) kunnen op deze manier aan elkaar gerelateerd worden zonder dat gegevens meerdere malen gekopieerd hoeven te worden. 

De Zaakgericht werken API's zijn ontworpen om TSA's op die manier te ondersteunen. TSA's die volgens de oude manier van synchroniseren en kopiëren werken passen dus niet bij de wijze waarop de API’s werken. De bron van de zaak is immers niet in het Zaakregister  opgeslagen maar in de vakapplicatie zelf. Andersom zal een TSA die, volgens de nieuwe manier, verwijzingen naar brongegevens opslaat niet voldoende gegevens kunnen aanleveren om een volledig StUF bericht te vullen. De integratielaag zal deze verwijzingen dan moeten oplossen door zelf bevragingen te doen om zodoende alsnog de ontbrekende gegevens op te kunnen nemen in de StUF berichten. Dat betekent echter dat in een ZS dat deze berichten ontvangt nog steeds kopieën van gegevens opgeslagen zullen worden. Er is dan dus geen sprake van eenmalige opslag en bevragen bij de bron. Al met al zal in de integratielaag veel, gevoelige, logica ingebouwd moeten worden met alle risico's op fouten en problemen. Dat is niet de route die VNG adviseert.

In de realisatieprincipes van de Common Ground staat in paragraaf 2.3 Nieuw naast oud - We ontwikkelen nieuw naast bestaand (https://www.gemmaonline.nl/images/gemmaonline/0/01/20190130_-_Common_Ground_-_Realisatieprincipes.pdf pagina 8) het principe beschreven dat naast de nieuw te ontwikkelen systemen de bestaande nog zeker 5 tot 10 jaar zullen moeten kunnen functioneren. Dit betekent dat leveranciers van zaaksystemen de bestaande StUF ZKN en Zaak- Documentservices koppelingen nog een tijd zullen moeten ondersteunen, ook al heeft men de nieuwe Zaakgericht Werken API's al ingebouwd. Op deze manier kan alle onderliggende business logica vanuit het ZS/ZRC aangestuurd worden en hoeven integratielagen zich niet in kromme bochten te wringen om een deel van deze logica te faciliteren in plaats van het ZS/ZRC (waar deze logica tenslotte thuis hoort). Derhalve is het niet de bedoeling om vertalingen te maken tussen de twee berichtenstandaarden en zal dat ook niet actief worden ondersteund in de nieuwe API's met uitbreidingen of andere voorzieningen

Om te voorkomen dat leveranciers tot in lengte van dagen de StUF standaard en koppelvlakken zullen moeten blijven ondersteunen zal door de VNG een end-of-life datum aangegeven moeten worden. Vanaf dat moment zal er geen ondersteuning meer op StUF en/of de koppelvlakken plaats vinden. Hier is echter op dit moment nog geen goede uitspraak over te doen, er zijn immers nog niet voldoende API standaarden beschikbaar om alle soorten koppelingen zoals die nu met StUF gemaakt worden te kunnen vervangen. We kunnen natuurlijk niet de stekker uit een standaard trekken zonder een fatsoenlijk alternatief te bieden.

Bovenstaand verhaal betekent dat bij de opslag van gegevens rekening gehouden moet worden met 2 verschillende datamodellen, RGBZ 1 (het model onder StUF ZKN en ZDS) en RGBZ 2 (het model wat de basis was voor de ZGW API's). Het kunnen mappen van deze modellen op elkaar is dus zeker van belang en daarvoor verwijzen wij naar de mapping tussen beide modellen op GEMMA Online: https://www.gemmaonline.nl/images/gemmaonline/4/4c/RGBZ_1.0_naar_2.0_-_versie_0.1_20141124.zip.  
Let wel, dit is geen officiele mapping van de ZDS op ZGW API's!
