### ISSUE TITLE
uuid niet direct in GET response

### ISSUE THREAD

**Issue by MarkHappel** [VNG-Realisatie/gemma-zaken#601]
# Verbetering

Bij het bevragen van een path zoals:
https://ref.tst.vng.cloud/ztc/api/v1/catalogussen/{catalogus_uuid}/zaaktypen
Word er gevraag om een catalogus_uuid
Deze uuid is het laatste gedeelte van de URL wanneer je de catalogus_list op haalt. Het zou echter een stuk praktischer zijn als de uuid zijn eigen veld heeft in de response:

Huidige response bij het ophalen van een catalogus:
{
        "url": "https://ref.tst.vng.cloud/ztc/api/v1/catalogussen/69a74e08-7911-4df1-94d0-ee9a3cd054aa",
        "domein": "OW",
        "rsin": "123456789",

Het zou praktischer zijn voor koppeling implementaties om hiervan te maken:

{
        "url": "https://ref.tst.vng.cloud/ztc/api/v1/catalogussen/69a74e08-7911-4df1-94d0-ee9a3cd054aa",
        "uuid": "69a74e08-7911-4df1-94d0-ee9a3cd054aa"
        "domein": "OW",
        "rsin": "123456789",

**Comment by joeribekker** [comment]
Thanks voor de observatie!

Geef vooral commentaar terug maar ik weet uit mijn hoofd dat we dit expres niet hebben gedaan omdat de "echte/volledige" resource identifier de volledige URL is en niet alleen het UUID. Aan enkel een UUID heb je niet zo veel zonder dat de URL bekend is. Alleen de URL leidt altijd tot een concreet object.

Ik moet alleen eerlijk bekennen dat we zelf ook UUIDs configureren op plekken waardoor we deze eigenlijk ook gewoon nodig hebben. Praktisch vs Idealistisch denk ik...

**Comment by MarkHappel** [comment]
Ik bekijk dit natuurlijk ook vanuit de bril van integratie partij. Wanneer wij integreren kan het zijn dat wij op bepaalde plekken de volledige URL niet exact hetzelfde meer is als de URL die in het bericht staat, de UUID is hier eigenlijk het enige sleutelgegeven. Vandaar dat ik denk dat het wel praktisch is om deze gelijk in het bericht tot je beschikking te hebben. Natuurlijk is de uuid ook wel uit de URL te knippen wanneer deze nodig is.

**Comment by Hugo-ter-Doest** [comment]
Prio laag, er is een work-around.

**Comment by sergei-maertens** [comment]
@TCIMEddy @Hugo-ter-Doest dan haal ik deze uit de sprint

**Comment by michielverhoef** [comment]
> Bij het bevragen van een path zoals:
> https://ref.tst.vng.cloud/ztc/api/v1/catalogussen/{catalogus_uuid}/zaaktypen
> Word er gevraag om een catalogus_uuid
> Deze uuid is het laatste gedeelte van de URL wanneer je de catalogus_list op haalt. Het zou echter een stuk praktischer zijn als > de uuid zijn eigen veld heeft in de response:

Volgens mij moet je niet de UUID hebben maar de gehele URL van de catalogus die je bevraagt.  Dus alles voor "/zaaktypen" is de url die je in de respons van de GET van de catalogus hebt gekregen.

Maar inmiddels is dit probleem niet meer relevant aangezien de Catalogi API herzien is en Zaaktypen nu geen sub-resource van Catalogussen meer zijn. Zie ook https://catalogi-api.vng.cloud/api/v1/schema/#tag/zaaktypen
