### ISSUE TITLE
Aanmaken zaak: verantwoordelijke organisatie is volgens de definitie een URL maar bevat een RSIN

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#602]
Bevinding tijdens het API Lab:

https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_create

Het veld verantwoordelijke organisatie is volgens de definitie een URL maar volgens het JSON Schema een String. In de praktijk blijkt dit inderdaad een RSIN te zijn.
Dit komt overigens overeen met wat er in het RGBZ beschreven staat:
"Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak. "

**Comment by joeribekker** [comment]
Dit is zojuist gewijzigd van een URL naar een RSIN omdat dit op 2 plekken anders was opgelost. De correcte waarde is dus een RSIN.

**Comment by michielverhoef** [comment]
Ok, dan hoeft alleen de documentatie/beschrijvng aangepast te worden.

**Comment by TCIMEddy** [comment]
@joeribekker kan op Close??

**Comment by michielverhoef** [comment]
Eigenlijk niet want de documentatie/beschrijving komt niet overeen met de waarde van het veld.

**Comment by joeribekker** [comment]
@michielverhoef Waar precies?

**Comment by michielverhoef** [comment]
https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_create 
De beschrijving van de verantwoordelijkeOrganisatie is nu:
_URL naar de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak._

En zou moeten zijn (dit is de omschrijving zoals in RGBZ staat):
Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak.

**Comment by sergei-maertens** [comment]
Bevestigd - de helptekst moet even bijgewerkt worden.

**Comment by sergei-maertens** [comment]
Paar weken terug gefixed in https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/commit/2a4a1a97a379c285838ae24a059c636b2e866b6c
