### ISSUE TITLE
openapi versie 3 bevat verkeerde server url

### ISSUE THREAD

**Issue by JostCrow** [VNG-Realisatie/gemma-zaken#604]
Ik probeer via de ZDS client een call te doen naar zaak_create. Dit resulteert in een 500 omdat de verkeerde `server url` waarde in openapi spec versie 3 word meegegeven.

```
is:
servers:
  - url: https://ref.tst.vng.cloud/api/v1

zou moeten zijn:
servers:
  - url: https://ref.tst.vng.cloud/zrc/api/v1

**Comment by JostCrow** [comment]
Dit probleem speelt ook in het DRC

In het ZTC staat dit correct

```
servers:
  - url: https://ref.tst.vng.cloud/ztc/api/v1
```

**Comment by joeribekker** [comment]
Klopt, als dit gefixed is moet de workaround voor de demo app ook weer er uit en lost dat ook #606 op.

**Comment by sergei-maertens** [comment]
Is al een tijdje gefixed :+1:
