### ISSUE TITLE
Demo applicatie werkt niet op eigen omgeving door patch

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#606]
# Impediment

[beschrijf de impediment]

[assign aan Eddy, voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by michielverhoef** [comment]
Wat is hier de status van? Moet dit ueberhaupt nog opgelost worden?

**Comment by Hugo-ter-Doest** [comment]
Lijkt me achterhaald.
