### ISSUE TITLE
Get call fails on missing response header "Accept-Crs"

### ISSUE THREAD

**Issue by arpa1973** [VNG-Realisatie/gemma-zaken#607]
Access to XMLHttpRequest at 'http://localhost:8000/api/v1/zaken' from origin 'https://localhost:8443' has been blocked by CORS policy: Request header field Accept-Crs is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by joeribekker** [comment]
Kan je iets meer vertellen over wat je precies draait en wat je probeert en via welke interface (lijkt op JS?)?

In principe staat CORS op allow all in de componenten die dus niets mogen blokkeren.
