### ISSUE TITLE
UUIDs zijn niet zichtbaar in de admin maar worden in de demo app (en daarbuiten?) vaak gebruikt voor configuratie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#608]
Geldt voornamelijk voor het ZTC. Nu moet je de API raadplegen of in de Docker/database waardes opzoeken

**Comment by Hugo-ter-Doest** [comment]
@joeribekker Waarom impediment. Kun je niet verder?

**Comment by michielverhoef** [comment]
Is dit nog steeds een issue? Of is de beheer interface inmiddels ver genoeg ontwikkeld?

**Comment by michielverhoef** [comment]
In de beheeromgeving zijn de UUIDs zichtbaar dus ik sluit dit issue
