### ISSUE TITLE
Als Consumer van ZTC wil ik dat de Vertrouwelijkaanduiding van een zaaktype en informatieobjecttype wordt toegevoegd in de get van deze objecten

### ISSUE THREAD

**Issue by miriamgroeneveld** [VNG-Realisatie/gemma-zaken#609]

**Comment by joeribekker** [comment]
Helder en bedankt voor de input!

We gaan de APIs nog uitbreiden met meer attributen uit de informatiemodellen maar concrete verzoeken helpen zeker om deze er eerder in te krijgen EN inzicht te krijgen in welke daadwerkelijk nodig zijn en gebruikt worden.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest ik heb de opmerkingen uit het API-lab netjes bijgewerkt en als er een prioritering nodig is dan vraag ik dat separaat via dit kanaal en assign het ook

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest en feel free om zaken te verplaatsen uiteraard

**Comment by Hugo-ter-Doest** [comment]
Meenemen in #549
