### ISSUE TITLE
Als burger wil ik via een portaal (Persoonlijke Internet Pagina) inzage in de dossiers van alle bevoegde gezagen betreffende mijn zaken...

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#61]
zodat ik centraal alle overheden kan afhandelen binnen 1 loket

**Comment by ArjanKloosterboer** [comment]
Dat portaal is er al: MijnOverheid. De vraag is: wat wil je daar zien en kunnen? En vervolgens: voorziet MijnOverheid daar al in?

**Comment by michielverhoef** [comment]
Deze user story gaat niet over het realiseren van een portaal of functionaliteit daarvoor maar over hoe zaakgegevens benaderd kunnen worden en door wie. In deze user story staat de functionele wens beschreven dat een burger wil kunnen inzien welke zaken er voor hem spelen, eventuele andere gewenste functionaliteit wordt in een andere user story beschreven.

**Comment by jgortmaker1** [comment]
tsja, nog altijd niet scherp genoeg.
wil je inzage in je dossier (is je hele zaak?) of enkel een inzage in de status van je zaken?

Mijnoverheid biedt nu geen inzage in alles denk ik. bovendien is daar een speciaal koppelvlak voor dat niet via de ZDS werkt..
(en MO LZ kon zijn langste tijd wel eens gehad hebben...)

Dus: wat willen we met deze US bereiken?

**Comment by TCIMEddy** [comment]
@jgortmaker1 @michielverhoef Nee mijnoverheid kan dat zeker niet en zal ook niet ontwikkeld worden. In Haarlem wil men deze mogelijkheid wel via mijnhaarlem.nl bieden. Ook het downloaden en uploaden van documenten. Belangrijk bij uploaden is dat behandelaar signaal krijgt.

**Comment by Hugo-ter-Doest** [comment]
Lijkt ook erg op die andere waar we net naar keken #60

**Comment by RvdKlip** [comment]
@jgortmaker1 Wilde met deze US bereiken dat client via het DSO portaal 'zaakinformatie' kan inzien (dus meer dan alleen status van zaken; bijvoorbeeld ook ingediende bouwtekeningen). Voor het updaten en muteren is inderdaad #60 aangemaakt.

**Comment by jgortmaker1** [comment]
OK. maar daarvoor moet je bij DSO zijn, liefst via UIVO-cg.
Daar weet men precies wat DSO kan en niet kan en welke wensen vanuit gemeenten er nog richting DSO liggen..
(concreet; DSo kent een register aanvragen en meldingen. gaat die dez einzage-functionaliteit bieden? voeden van DSO-portaal vanuit lopende zaakdossiers met andere informatie dan de status is volgens mij niet voorzien)

Maar dit aansluiten op DSO is grotendeels politiek. dat zou ik hier graag buiten de deur houden.

Voorstel: deze sluiten en #60 generieker maken

**Comment by RvdKlip** [comment]
in zijn algemeenheid denk ik dat het handig is dat we vanuit de standaard klaar staan om portalen en apps van derden afdoende te kunnen voorzien met de functionaliteit geboden door de api. 
Gemeenten werken steeds meer samen in ketens, waarbij de client niet perse via het gemeenteportaal haar zaken afhandelt. 

Inzage verschaffen is wellicht zodanig anders dan muteren, dat hiervoor een aparte api (onderdeel)nodig is? maar dat kunnen de bouwers beter aangeven. Voorstel: deze US voorlopig nog even laten staan en #60 laten zoals deze is.

**Comment by ehotting** [comment]
MijnOverheid kijkt niet in ZRC's, daar moet je het actief aanbieden. MijnOverheid is wat dat betreft buiten scope, aangezien het niet met API's werkt. Aanbieden bij MijnOverheid vereist een component die de ZDS 2.0 API's uitleest en vervolgens middels MO services dingen aanmaakt / bijwerkt.

Zelf een portaal maken lijkt me overdreven - wel moeten we middels de API dit overzicht op kunnen hoesten voor de eigen achterliggende bronnen.

**Comment by ehotting** [comment]
Not ready.

**Comment by RvdKlip** [comment]
Is #5, echter met toevoeging:
1. In #61 gaat raadplegen ook over documenten in het zaakdossier. 
2. #61 Gaat over alle bevoegde gezagen. Dit suggereert dat er een kenmerk op zaakniveau is waarmee er een verband is naar een ander bevoegd gezag.

Als 1. en 2. ook in 5# wordt gedekt dan kan #61 gesloten worden.

**Comment by michielverhoef** [comment]
Dit is wat MijnZaken biedt: https://vng.nl/artikelen/startgids-mijnzaken-service
