### ISSUE TITLE
Filteren van Status-resource op een Zaak werkt niet

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#610]
# Bug

`https://ref.tst.vng.cloud/zrc/api/v1/statussen?zaak=https://ref.tst.vng.cloud/zrc/api/v1/zaken/638ef8a2-9a0d-4169-8568-eb51e987e916`

Geeft een foutmelding:

```json
{
    "type": "https://ref.tst.vng.cloud/zrc/ref/fouten/ValidationError/",
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:7c398a6f-94c0-4eef-ab1c-322ba7268a0e",
    "invalid-params": [
        {
            "name": "zaak",
            "code": "invalid",
            "reason": "Invalid resource URL supplied"
        }
    ]
}
```

De Zaak bestaat wel en kan correct worden opgevraagd:
`https://ref.tst.vng.cloud/zrc/api/v1/zaken/638ef8a2-9a0d-4169-8568-eb51e987e916`

En alle statussen ook:
`https://ref.tst.vng.cloud/zrc/api/v1/statussen`

**Comment by sergei-maertens** [comment]
Fixed
