### ISSUE TITLE
Sentry opzetten voor VNG

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#611]
# Impediment

[beschrijf de impediment]

[assign aan Eddy, voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by ehotting** [comment]
Incl. Slack integratie?

**Comment by TCIMEddy** [comment]
https://github.com/getsentry

**Comment by Hugo-ter-Doest** [comment]
Is geen impediment volgens mij. Graag een user story voor aanmaken.
