### ISSUE TITLE
Admin interface minimaal voorzien van component naam in titel

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#612]
# Impediment

[beschrijf de impediment]

[assign aan Eddy, voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by TCIMEddy** [comment]
@joeribekker geen impediment

**Comment by joeribekker** [comment]
Geen impediments maar ondertussen opgelost.
