### ISSUE TITLE
Meer uitleg over instellen van autorisaties in ref componenten

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#615]
Gaat om jwt secrets en api credentials en sites.

**Comment by TCIMEddy** [comment]
@joeribekker @sergei-maertens ik zet de bugs etc op jullie naam en in sprint 7 maar feel free om je naam etc te verwijderen als dit niet het geval is

**Comment by sergei-maertens** [comment]
Voor DRC was er een gerelateerd issue - dat staat nu in het project zelf gedocumenteerd: https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/blob/develop/docs/contents/configuration.rst
