### ISSUE TITLE
Windows en localhost communicatie gaan niet samen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#616]
# Bug

Een Zaak aanmaken in de ZRC docker op een Windows machine (localhost:8000) probeert het Zaaktype in de ZTC docker te valideren (localhost:8002). Dit gaat fout omdat het opvragen van `localhost` in een Docker, verwijst simpelweg naar de Docker instance en niet naar het host systeem.

Een workaround is het publieke IP gebruiken (10.x.x.x of 192.x.x.x)

**Comment by joeribekker** [comment]
Link met #605

**Comment by sergei-maertens** [comment]
Dit valt in essentie op te lossen met `network=host` mode, maar die is vaag onder Windows (zie ook https://github.com/VNG-Realisatie/gemma-zaken/commit/80ccb0435ca170a850b0f454c2cef3ac4fb2fdad) :cry:

**Comment by sergei-maertens** [comment]
Windows lijkt wel `docker.host.internal` te ondersteunen (met Docker for Windows) , maar dat werkt dan weer niet onder Linux

**Comment by sergei-maertens** [comment]
Fix in #623

**Comment by sergei-maertens** [comment]
Nee/ja - tijdens API-lab durfde ik het niet aan om iedereen over te laten gaan op deze setup. Deze week op een Windows machine eens testen.

**Comment by joeribekker** [comment]
De meeste recente versie (https://github.com/VNG-Realisatie/gemma-zaken/tree/e62be99e8f4945e4b4c2529f521dcc73e1301c10/infra) getest op Windows 10 Pro met Docker for Windows en werkt prima.
