### ISSUE TITLE
Als consumer en provider van de API wil  ik een goede performance en geen onnodig resource gebruik

### ISSUE THREAD

**Issue by andyverberne** [VNG-Realisatie/gemma-zaken#618]
Veel van de Post REST calls om een object aan te maken retourneren vervolgend het aangemaakt object. Voorstel is om niet het aangemaakt object te retourneren maar de url naar het aangemaakte object te retourneren. In de meeste gevallen is de consumer namelijk niet direct geïnteresseerd in het resultaat omdat deze informatie ten slotte al beschikbaar is. Door het nieuwe object te retourneren worden er onnodig veel resources gebruikt (netwerk en cpu aan de provider kant). Zo gaat de inhoud van het document 2 keer over de lijn.

**Comment by sergei-maertens** [comment]
@andyverberne kan je dit meer toelichten? In principe zijn performance optimalisaties out-of-scope voor de referentieimplementaties (maar moeten wel voor productieimplementaties opgelost worden). Ik zie wel mogelijkheden om caching-mechanismen af te stemmen, dus weet niet goed welke richting je uit wil :)

**Comment by andyverberne** [comment]
Door het gehele object te retourneren maak je optimalisatie onmogelijk, je moet tenslotte het hele object weer terug transformeren naar REST en over de lijn sturen. Zeker met de inhoud van een document is dat niet handig.

Ik heb ook het idee dat het 'gebruikelijker' is om na een Post de uri naar het object te retourneren en niet weer het object zelf.

**Comment by sergei-maertens** [comment]
inhoud van een document wordt in de response een URL per de API spec

**Comment by sergei-maertens** [comment]
Aanvulling: https://stackoverflow.com/a/28951049/973537 wat net argumenteert om wel de volledige resource te retourneren. De stelling:

> Ik heb ook het idee dat het 'gebruikelijker' is om na een Post de uri naar het object te retourneren en niet weer het object zelf.

is in ieder geval niet mijn/onze ervaring, maar misschien zit ik te veel in mijn 'bubble' :smile:

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prio?

**Comment by Hugo-ter-Doest** [comment]
Laten we de conventie volgen van het retourneren van het gehele object. Ik verwacht geen performance-problemen, mede omdat de inhoud van het document niet wordt geretourneerd. Ik sluit het issue.
