### ISSUE TITLE
Als developer wil ik een zinvollere beschrijving van de API's 

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/gemma-zaken#620]
...zodat duidelijker is wat het doel van de API is.

**Comment by basretera** [comment]
De API's waarbij de beschrijving m.i. niet volledig voldoet.

- status_list
- status_create
- status_read
- zaak_read
- zaak_update
- enkelvoudiginformatieobject_list
- objectinformatieobject_list
- objectinformatieobject_partial_update

Maar check voor de volledigheid alle API's aub.

**Comment by joeribekker** [comment]
@basretera Kan je van 1 resource een voorbeeld geven van wat in jouw ogen zinvol is?

**Comment by basretera** [comment]
@joeribekker Bij de 3 resources m.b.t. status staat helemaal geen beschrijving. Bij zaak_read en zaak_update staat exact dezelfde beschrijving, maar deze resources zijn m.i. toch echt andere dingen.
