### ISSUE TITLE
Als leverancier wil ik dat VNG lifecycle management in de standaard opneemt

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#629]
...zodat leveranciers hier rekening mee kunnen houden in hun planning en budgetten

Voorbeelden:

* https://developers.facebook.com/docs/apps/versions/#versioning
* https://support.microsoft.com/nl-nl/help/13853/windows-lifecycle-fact-sheet
* https://devguide.python.org/devcycle/#end-of-life-branches
* https://www.djangoproject.com/weblog/2015/jun/25/roadmap/

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [ ] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Ik vat dit op als dat er behoefte is aan een roadmap, versie management, en hoe om te gaan met backwards compatibility. Deze onderwerpen kunnen niet door het team (alleen) worden beantwoord. Uiteindelijk wordt de standaard in beheer genomen door VNG. En VNG wil (overleg met @michielverhoef) alle standaarden op dezelfde manier beheren. Wordt in 2019 opgepakt in overleg met VNG.

**Comment by Hugo-ter-Doest** [comment]
User story moet worden opgepakt door beheerteam. Buiten scope voor dit project.
