### ISSUE TITLE
als gemeentemedewerker wil ik inzage in alle gegevens over alle domeinen heen die betrekking hebben op de omgeving van een zaak 

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#63]
... die ik in behandeling heb
zodat ik alle relevante informatie heb over de omgeving en betrokken personen

**Comment by jgortmaker1** [comment]
dat mag niet van de AVG. Dus veel specifieker maken
aub specificeren wat je met "de omgeving van een zaak" bedoelt. komt het meer tegen, maar is een erg vaag begrip

**Comment by Hugo-ter-Doest** [comment]
@michielverhoef @RvdKlip Kunnen jullie de user story concreet maken. Zie ook de vragen van Jeffrey hierboven.

**Comment by TCIMEddy** [comment]
Veel te breed dus close. Mocht er nog behoefte zijn graag beter slicen.
