### ISSUE TITLE
Als consumer wil ik dat de namen van eigenschappen overeenkomen met de namen zoals gedefinieerd in de standaard.

### ISSUE THREAD

**Issue by miriamgroeneveld** [VNG-Realisatie/gemma-zaken#636]
Bijvoorbeeld zaaktypeomschrijving en zaaktypeomschrijvinggeneriek i.p.v. omschrijving en omschrijvinggeneriek

**Comment by sergei-maertens** [comment]
Dit vonden we te verbose en in de [design-keuzes](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/overige/technisch/design-keuzes.md#naamgeving-van-de-api-velden-binnen-een-resource) hebben we vastgelegd dat niet te gaan doen.

Is er een reden om dit te doen, anders dan dat het in ImZTC/RGBZ op de verbose manier staat? :slightly_smiling_face:

**Comment by Hugo-ter-Doest** [comment]
Ik sluit het af. Discussie kan heropend worden bij goede argumentatie.
