### ISSUE TITLE
Description Accept-Crs en Content-Crs niet correct

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/gemma-zaken#639]
De description van request header “Accept-Crs” is in de yaml voor ZRC: “Het ‘Coordinate Reference System’ (CRS) van de verzoekdata. (…)”
De description voor response header "Content-Crs" is: "Het 'Coordinate Reference System' (CRS) van de antwoorddata."

In de API strategie staat “Het CRS van de geometrie in de vraag (request body) wordt aangeduid met de header Content-Crs.” en “Het gewenste CRS voor de geometrie in het antwoord (response body) wordt aangeduid met de header Accept-Crs.“.

Daarnaast ontbreekt m.i. bij POST /zaken de request header "Content-Crs".
In de requestBody zit immers attribuut "zaakgeometrie", waarvan de ontvanger de gebruikte CRS moet weten.

**Comment by TCIMEddy** [comment]
@sergei-maertens @Hugo-ter-Doest even label bug toegevoegd (weet niet of het bug is)
