### ISSUE TITLE
Als gemeentemedewerker wil ik een lijst opvragen met aangevraagde en/of toegekende vergunningen die betrekking hebben op gebouwde objecten binnen de wijk (postcodegebied) waarin ik nu loop

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#64]
... zodat ik alle alle relevante vergunning informatie heb om de inspectie goed uit te kunnen voeren (en voor zover de classificatie en doelbinding dit toestaat).

Het betreft ook inspecties in het kader van het behandelen van een vergunningsaanvraag om te beoordelen of een aanvraag toegekend kan worden.

Toegekende vergunningen zijn vastgelegd als besluit (RGBZ Mapping uitdaging).
De behandeling van een vergunningsaanvraag is een zaak.

[Architectuurschets](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/rotterdam-samenloop.md)

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Taken**
- [x] Opstellen architectuurschets [@RvdKlip]
- [x] Opstellen welke velden bij een melding horen [@RvdKlip]
- [ ] Taak toegevoegd: Initiele levering mappen op RGBZ [@michielverhoef]
- [ ] Aanleveren testdata [@RvdKlip]
- [ ] Schrijven (unit) test voor referentie-implementatie [@joeribekker]
- [ ] Implementeren in referentie-implementatie [@joeribekker]
- [ ] Genereren/opstellen van OAS 3.0 [@joeribekker]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [?]

**Comment by RvdKlip** [comment]
Heb nog even nagevraagd wat de business verstaat onder 'samenloopdetectie':

"Hoi Ruub,

 

In de PSA staat: “In veel gevallen kan het voorkomen dat medewerkers moeten weten of een burger betrokken is in een traject, dat aan zorg gerelateerd is, maar waarvan de dienstverlening niet via de Gidso applicatie loopt. Te denken valt aan schuldhulp of leerlingen verzuim. Zij mogen vanwege privacywetgeving/-beleid geen inhoudelijke informatie opvragen (wat-informatie), maar alleen het bestaan ervan (dat-informatie) aangevuld met contactgegevens van de behandelaar/casusregisseur. We noemen dit samenloopdetectie.”

 

Wat we in praktische zin op het oog hebben is een mechanisme dat de medewerkers die in een dedicated taakapplicatie werken (zoals Gidso) vanuit diezelfde taakapplicatie de samenloop met andere zaken kunnen opvragen (tenminste, voor zover die vanuit het werkproces relevant en toegestaan is). We gebruiken het zaaksysteem van de eSuite daartoe als knooppunt en gegevensbron."

**Comment by jgortmaker1** [comment]
ik zie 'samenloopdetectie' niet in de user story staan. Is deze dan wel scherp genoeg?

"alle zaken die betrekking hebben hebben op de omgeving van een zaak die ik in behandeling heb" is ook niet duidelijk. Ik zou deze aanscherpen.
voorstel: als ik werk aan een zaak die betrekking heeft op een bepaald zaakobject, wil ik kunnen zien welke zaken er nog meer lopen met betrekking tot datzelfde zaakobject...

**Comment by jgortmaker1** [comment]
ik wacht nog op een bijgewerkte architectuurbeschrijving...die heb ik denk ik nog niet gezien

**Comment by ehotting** [comment]
Dit is geen CRUD maar vereist stukje business-logica die ook in de client zou kunnen plaatsvinden. Ik zet hem even op Prio L. Kan zijn dat het al mogelijk is met huidige API dankzij MOR, kan jij dat beoordelen @sergei-maertens ?  Zo ja, dan close. Zo nee, oppakken wanneer we tijd over hebben aan einde project.

**Comment by sergei-maertens** [comment]
Is ook een filter verhaal - geo filtering (mogelijk) maar ook filteren op gerelateerde `ZaakObjecten`, en die moet wel nog verder uitgediept worden.

**Comment by michielverhoef** [comment]
Met https://zaken-api.vng.cloud/api/v1/schema/#operation/zaak__zoek is het mogelijk zaken in een bepaald gebied op te zoeken. 
De samenloop detecttie is een stukje logica wat deze zoekmethode kan gebruiken, dit is echter geen onderdeel van de standaard.

Ik sluit dit issue.
