### ISSUE TITLE
Als behandelaar in de TSA wil ik als het document gereed is een melding sturen naar het DMS

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#644]
.... Zodat DIV het document kan versturen

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [ ] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio?

**Comment by Hugo-ter-Doest** [comment]
Je kunt straks nieuwe versie van een document toevoegen #622 en de status van het document wijzigen. De DIV-er kan vervolgens genotificeerd worden over het definitief worden van het document. Ik laat deze story openstaan vanwege het notificatie-aspect. Zoals de story is beschreven wordt deze niet gerealiseerd in DRC.

**Comment by CMasselink** [comment]
Ik zie hier eerder een relatie met output management. Bij het bereiken van een bepaalde status / bij een bepaald event wordt de output management component getriggerd om een document te versturen.
Ik ben het dus eens met Hugo.

**Comment by Hugo-ter-Doest** [comment]
User story is niet duidelijk genoeg. Graag functionaliteit uitwerken.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prio toekennen (en wellicht user stories Johannesbattjes)

**Comment by TCIMEddy** [comment]
Je kunt straks nieuwe versie van een document toevoegen #622 en de status van het document wijzigen. De DIV-er kan vervolgens genotificeerd worden over het definitief worden van het document. Ik laat deze story openstaan vanwege het notificatie-aspect (en prio Hoog). Zoals de story is beschreven wordt deze niet gerealiseerd in DRC.
