### ISSUE TITLE
als gemeentemedewerker  wil ik inzage in alle zaken die betrekking hebben op de persoon/aanvrager behorend bij een zaak die ik in behandeling heb

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#65]
.....
zodat ik alle relevante informatie heb over de  sociale omgeving, zijnde het gezin en betrokken personen.

[Architectuurschets](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/overige/processen/rotterdam-samenloop%20sociaal%20domein.md)

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Acceptatiecriteria**
Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan AVG

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Taken**
- [x] Opstellen architectuurschets [@RvdKlip]
- [x] Opstellen welke velden bij een melding horen [@RvdKlip]
- [ ] Taak toegevoegd: Initiele levering mappen op RGBZ [@michielverhoef]
- [ ] Aanleveren testdata [@RvdKlip]
- [ ] Schrijven (unit) test voor referentie-implementatie [@joeribekker]
- [ ] Implementeren in referentie-implementatie [@joeribekker]
- [ ] Genereren/opstellen van OAS 3.0 [@joeribekker]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [?]

**Comment by RvdKlip** [comment]
Heb nog even nagevraagd wat de business verstaat onder 'samenloopdetectie':

"Hoi Ruub,

In de PSA staat: “In veel gevallen kan het voorkomen dat medewerkers moeten weten of een burger betrokken is in een traject, dat aan zorg gerelateerd is, maar waarvan de dienstverlening niet via de Gidso applicatie loopt. Te denken valt aan schuldhulp of leerlingen verzuim. Zij mogen vanwege privacywetgeving/-beleid geen inhoudelijke informatie opvragen (wat-informatie), maar alleen het bestaan ervan (dat-informatie) aangevuld met contactgegevens van de behandelaar/casusregisseur. We noemen dit samenloopdetectie.”

Wat we in praktische zin op het oog hebben is een mechanisme dat de medewerkers die in een dedicated taakapplicatie werken (zoals Gidso) vanuit diezelfde taakapplicatie de samenloop met andere zaken kunnen opvragen (tenminste, voor zover die vanuit het werkproces relevant en toegestaan is). We gebruiken het zaaksysteem van de eSuite daartoe als knooppunt en gegevensbron."

**Comment by ArjanKloosterboer** [comment]
Wat wordt bedoeld (achter 'zodat') met 'over de omgeving'? Welke of wiens omgeving? En met 'betrokken personen')? Wie allemaal? Alle betrokkenen bij alle zaken van de persoon? Oftewel, welke informatie? En waarom dan, wat is dan - preciezer - het 'zodat'?

**Comment by RvdKlip** [comment]
@ArjanKloosterboer. User story is vanuit Rdam. Daarom in het comment (hierboven) de toelichting erop.
'De omgeving' kan natuurlijk vanuit meerdere perspectieven worden ingevuld. In het fysieke domein (bijv DSO) zal het gaan om de samenloop binnen een afgebakend gebied (bijv. coördinaten, wijk). Vanuit sociaal domein rondom een persoon en een gezin.

**Comment by RvdKlip** [comment]
Hierbij een eerste veldenlijst. Wij hebben nog geen kant en klare interface/app met de functionaliteit conform deze US. Dus de lijst is vanuit functioneel perspectief opgezet. Het lukt me niet om de daarbij overeenkomstige velden vanuit RGBZ/RSGB te vinden. Ik hoop dat bijvoorbeeld Michiel dit kan aanvullen?
[Rdam US 65.pdf](https://github.com/VNG-Realisatie/gemma-zaken/files/2084839/Rdam.US.65.pdf)

**Comment by michielverhoef** [comment]
Ik pak dit op!

**Comment by EdwinCoster** [comment]
@ArjanKloosterboer  en @michielverhoef  we zittten in een scrumproces met elkaar en jullie zijn er niet maar om deze user story ready for sprint te krijgen moet er nog werk verricht worden (review/maken). Kunnen jullie dit oppakken (sorry voor onpersoonlijke weg). Dit is getypt door Eddy

**Comment by EdwinCoster** [comment]
@michielverhoef: Voor zover ik weet niet. Er is zeker geen markdown omdat @RvdKlip in de veronderstelling leeft dat jij die gaat maken. Hij kan vast wel voor een spreadsheet zorgen. Dat is inderdaad makkelijker kopiëren.

**Comment by michielverhoef** [comment]
@RvdKlip hier vind je wat hulp en tutorials voor het maken van tabellen in markdown:
https://www.tablesgenerator.com/markdown_tables 
https://help.github.com/articles/organizing-information-with-tables/

Kun je het spreadsheet omzetten naar markdown? Dan kunnen Arjan en/of ik de mapping aanvullen.

**Comment by ehotting** [comment]
@sergei-maertens Volgens mij kan dit met huidige API specs. Zo ja, graag close. Zo niet, dan moeten we die gaan oppakken in een komende sprint.

**Comment by sergei-maertens** [comment]
De filters hiervoor moeten nog geimplementeerd worden. Graag opnemen dus!

**Comment by RvdKlip** [comment]
Functioneel   (in de app) | Veld | RGBZ/RSGB ???
-- | -- | --
  |   |  
**Input voor   het Zoeken** |   |  
Op burgerservicenummer van de cliënt | Burgerservicenummer |  
Op gezin (verzameling BSN's van gezinsleden client) | Burgerservicenummers |  
Op nummer van het Gezinsplan | Casus   identificatie |  
Op zaaknummer | Zaak   identificatie |  
Op (deel van)   achternaam | Geslachtsnaam   en aangetrouwde naam |  
Op adres | Straat,   Huisnummer, Postcode, Coordinaten |  
Medewerker die bevraging uitvoert ( niet zichtbaar in app, maar   benodigd tbv autorisatie/logging ?) | Medewerker   identificatie IDP |  
Toepassing die bevraging uitvoert (niet zichtbaar in app, maar   benodigd tbv autorisatie/logging ?) | Toepassing   identificatie |  
  |   |  
**Gevonden resultaat is een lijst met alle afgehandelde of in   behandelingzijnde aangetroffen (deel)zaken, met per (deel)zaak een rij   met:** | **Is   'DAT' informatie** | 
Nummer van de   zaak | Zaak   identificatie |  
Omschrijving   van de zaak | Omschrijving Zaak |  
Omschrijving   van het zaaktype | Omschrijving Zaaktype |  
Moment van   starten van de zaak | Startdatum |  
Einddatumgepland | Einddatumgepland |  
Einddatum | Einddatum |  
Status | Status |  
Deelzaakindicatie | Deelzaakindicatie |  
Aanduiding   van de vertrouwelijkheid | VertrouwelijkheidsAanduiding |  
  |   |  
**Na doorklikken op één (deel)zaak alle zaakdetails tonen,   waaronder:** | **Is   'WAT' informatie en doelbinding afhankelijk** |  
Behandelaar   van betreffende gevonden zaak | Medewerker   identificatie of Organisatie identificatie met Achternaam of Organisatienaam |  
Besluit/Beschikking | Besluit |  
**Lijst met   documenten tonen, met hierin:** |   |  
Zaak   identificatie - Document identificatie | Zaak identificatie -   Document identificatie |  
Document   auteur | Document auteur |  
Document   beschrijving | Document beschrijving |  
Document   categorie | Document   categorie |  
Document   creatiedatum | Document creatiedatum |  
Document link   (URL) | Document link   (URL) |

**Comment by RvdKlip** [comment]
^ Hierboven ^ de veldenlijst behorende bij de inmiddels sterk aangepaste userstory (toegespitst op samenloop in sociaal domein). 

Ook de architectuurbeschrijving is hierop aangepast: https://github.com/VNG-Realisatie/gemma-zaken/blob/RvdKlip-patch-1/docs/processen/rotterdam-samenloop%20sociaal%20domein.md
@jgortmaker1, wil jij deze svp reviewen?

@ArjanKloosterboer en @michielverhoef , willen jullie svp de RGBZ kolom met de juiste dingen aanvullen?

**Comment by jgortmaker1** [comment]
review done
veldlijst gevonden...deze maakt al meer duidelijk..maar niet alles zal altijd mogen vrees ik..en ikv "privacy by design" moeten we dat adresseren.

Ik zie bv staan "vertrouwelijkheids-aanduiding"..als een zaak vertrouwelijk is, zou ik deze helemaal niet ni het lijstje verwachten. Maar dat is misschien maar een veronderstelling van mij..

moet je dit niet ook met scopes oplossen @ehotting ?

**Comment by RvdKlip** [comment]
^ Hierboven ^ de veldenlijst aangepast. De input voor het zoeken is teruggebracht naar gericht zoeken op basis van één BSN nummer in combinatie met een Zaaktype. De 'Dat'-output is ook teruggebracht naar het tonen van een Zaaknummer en Behandelaar.

**Comment by TCIMEddy** [comment]
@TCIMEddy veldmapping maken

**Comment by joeribekker** [comment]
`Deelzaakindicatie` op zichzelf is niet voldoende om te zien aan welke zaken een Zaak nog meer hangt.

**Comment by TCIMEddy** [comment]
@RvdKlip @sergei-maertens overleg mapping input output

**Comment by sergei-maertens** [comment]
Yes, we hebben een datum geprikt :+1:

**Comment by sergei-maertens** [comment]
TODO voor mij - opnemen in tabel:

Burgerservicenummer:
    * Zaak.Betrokkene.Burgerservicenummer (via alle rol)
    * Zaak.ZaakObject.Object.Natuurlijk Persoon.Burgerservicenummer

Zaaktype: Zaak.Zaaktype

Medewerker die bevraging uitvoert: n.v.t. - opgelost met autorisatie

Toepassing die bevraging uitvoert: n.v.t. - opgelost met autorisatie

---------

Zoeken: ook deelzaken (ook indirect)!

Zaak identificatie: Zaak.Identificatie

Behandelaar: Zaak.Rol.Betrokkene (omschrijvingGeneriek: behandelaar)

Deelzaakindicatie: Zaak.isDeelZaakVan.Zaak

(Zaak.Vertrouwelijkheidaanduiding toevoegen & meenemen in filter)

---------

Omschrijving zaak: Zaak.Omschrijving

Omschrijving zaaktype: Zaak.Zaaktype.Zaaktype-omschrijving

Startdatum: Zaak.Startdatum

Geplande einddatum: Zaak.Einddatum gepland

Einddatum: Zaak.Einddatum (volgt uit laatste status)

Status: Zaak.Status (url) -> Statustype.Statustype-omschrijving

Besluit: Besluit.Zaak (1 op n) (BRC)

Alle documenten aan zaak (dus ook via besluit)

Enkelvoudig InformatieObject.Informatieobjectidentificatie
Enkelvoudig InformatieObject.Auteur
Enkelvoudig InformatieObject.Beschrijving
Categorie: Enkelvoudig InformatieObject.Informatieobjecttype.Informatieobjectcategorie
Enkelvoudig InformatieObject.CreatieDatum
Enkelvoudig Informatieobject.Inhoud (link)

**Comment by TCIMEddy** [comment]
@RvdKlip @sergei-maertens Lijkt bijna wel scrum :-)

**Comment by sergei-maertens** [comment]
Wat toevallig ;)

**Comment by sergei-maertens** [comment]
@ArjanKloosterboer RGBZ veldmapping staat in https://github.com/VNG-Realisatie/gemma-zaken/issues/65#issuecomment-428109843 - kan je dit reviewen?

**Comment by ArjanKloosterboer** [comment]
Mooie mapping. Essentie is inderdaad dat een persoon op twee manieren aan een zaak kan 'hangen': als object en als betrokkene. Opmerkingen:

- heb je voor het zoeken Bronorganisatie of Verantwoordelijke organisatie niet nodig? De vraag is waarin je zoekt: een registratie met alleen zaken van de organisatie waartoe de zoekende medewerker behoort of een registratie met zaken van meer organisaties? En wat wil je weten: alle zaken of alleen de zaken van de organisatie waartoe de zoekende medewerker behoort?

Bij 'Gevonden resultaat': 
- 'Behandelaar van betreffende gevonden zaak': wie wil je weten? Eén van de behandelaren (en welke dan als het er meer zijn) of de zaakcoordinator? Of de laatste maar als die er niet is één van de behandelaren? De desbetreffende betrokkene is veelal een medewerker of organisatorische eenheid maar kan die bij dergelijke zaken ook een vestiging of niet-natuurlijk persoon zijn? Dan wil je daarvan weer de contactpersoon bij de zaak weten (onderdeel van ROL). 
- Waar heb je de Deelzaakindicatie voor nodig? Een deelzaak is ook maar een zaak ...

V.w.b. 'Na doorklikken':
- 'Besluit/Beschikking', wat wil je hiervan weten, welke attributen? 
- Ik mis daarbij het resultaat: ZAAK heeft bij afronding RESULTAATTYPE en RESULTAATTYPE . Resultaattype-omschrijving. Ik vraag me af of Besluit-info wel eerste prio is. 
- Is hierbij niet ook info over de behandelaar en vertrouwelijkheid nodig? 

V.w.b. documenten:
- In het RGBZ is de Identificatie een attribuut van het INFORMATIEOBJECT.
- Evenzo Auteur, Beschrijving en Creatiedatum. Hoe zinvol is Beschrijving in dit kader? 
- ik mis de Titel van het INFORMATIEOBJECT. M.i. mapt dat op Beschrijving. En heb je Status en Vertrouwelijkheidaanduiding niet nodig? 
- Wat is de reden om Categorie van INFORMATIEOBJECTTYPE op te nemen? Mij lijken  Informatieobjectomschrijving en eventueel 'Informatieobjectomschrijving generiek' zonder meer zinvol om het document te kunnen duiden. En m.i. mappen deze op Categorie.  
- je mapt 'Document link (URL)' op 'ENKELVOUDIG INFORMATIEOBJECT.Inhoud'. Het RGBZ kent ook 'ENKELVOUDIG INFORMATIEOBJECT.Link'. Is dit een correcte mapping? Of Link alleen indien Inhoud geen waarde heeft? 

Nog geen vinkje dus. Nog het een en ander af te wegen.

**Comment by sergei-maertens** [comment]
> heb je voor het zoeken Bronorganisatie of Verantwoordelijke organisatie niet nodig

Lijkt me niet - Ruub gaf aan dat alle zaken moeten terugkomen (iig de zaakidentificatie ervan, of je die zaken mag lezen is een andere kwestie - dat vs. wat)

> 'Behandelaar van betreffende gevonden zaak': wie wil je weten? Eén van de behandelaren (en welke dan als het er meer zijn) of de zaakcoordinator? Of de laatste maar als die er niet is één van de behandelaren? De desbetreffende betrokkene is veelal een medewerker of organisatorische eenheid maar kan die bij dergelijke zaken ook een vestiging of niet-natuurlijk persoon zijn? Dan wil je daarvan weer de contactpersoon bij de zaak weten (onderdeel van ROL).

Vraag voor @RvdKlip . Voor mij triviaal als er meerdere behandelaren zijn, dat die allemaal getoond/opgevraagd worden via de rol bij een zaak die een referentie naar de betrokkene heeft. Zelfde principe geldt voor zaakcoordinator

> Waar heb je de Deelzaakindicatie voor nodig? Een deelzaak is ook maar een zaak ...

Aan API moet toegevoegd worden van welke zaak een zaak een deelzaak is.

> ik mis de relatie 'ZAAK kent INFORMATIEOBJECT'.

Impliciet meegenomen, ondertussen weten we in de API hoe de link tussen DRC en ZRC ligt :slightly_smiling_face: 

> In het RGBZ is de Identificatie een attribuut van het INFORMATIEOBJECT.

Aangepast.

> Wat is de reden om Categorie van INFORMATIEOBJECTTYPE op te nemen? Mij lijken Informatieobjectomschrijving en eventueel 'Informatieobjectomschrijving generiek' zonder meer zinvol om het document te kunnen duiden. En m.i. mappen deze op Categorie.

Vraag: Waarom bestaat `Categorie` dan? Wat is het doel van dat attribuut?

**Comment by sergei-maertens** [comment]
> je mapt 'Document link (URL)' op 'ENKELVOUDIG INFORMATIEOBJECT.Inhoud'. Het RGBZ kent ook 'ENKELVOUDIG INFORMATIEOBJECT.Link'. Is dit een correcte mapping? Of Link alleen indien Inhoud geen waarde heeft?

Kan je een inhoud aan een informatieobject toekennen _en_ een link (url) opgeven?

**Comment by sergei-maertens** [comment]
@RvdKlip meeste vragen van Arjan lijken over gebruik te gaan, en daar kan ik weinig over zeggen :wink:

**Comment by ArjanKloosterboer** [comment]
> Waarom bestaat Categorie dan? Wat is het doel van dat attribuut?

Het ImZTC zegt er dit over. 
_Definitie: Typering van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE.
Toelichting: Voorbeelden hiervan zijn ‘Vergunning’, ‘Subsidie-aanvraag’, ‘Onderzoeksrapport’, 'Besluit.'_
Bij een (generieke) Informatieobjecttype-omschrijving vermeld het ImZTC:
_Definitie: Omschrijving van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE._
Zie daar het verschil.

> Kan je een inhoud aan een informatieobject toekennen en een link (url) opgeven?

Lijkt me van wel. Voor het antwoord op de vraag: wat is de link naar de inhoud?

**Comment by ArjanKloosterboer** [comment]
Kan allebei, lijkt mij.

**Comment by michielverhoef** [comment]
@ArjanKloosterboer : 'Behandelaar van betreffende gevonden zaak': wie wil je weten? Eén van de behandelaren (en welke dan als het er meer zijn) of de zaakcoordinator? Of de laatste maar als die er niet is één van de behandelaren? De desbetreffende betrokkene is veelal een medewerker of organisatorische eenheid maar kan die bij dergelijke zaken ook een vestiging of niet-natuurlijk persoon zijn? Dan wil je daarvan weer de contactpersoon bij de zaak weten (onderdeel van ROL).
@sergei-maertens : Vraag voor @RvdKlip . Voor mij triviaal als er meerdere behandelaren zijn, dat die allemaal getoond/opgevraagd worden via de rol bij een zaak die een referentie naar de betrokkene heeft. Zelfde principe geldt voor zaakcoordinator
@RvdKlip: de eerste behandelaar lijkt me een goede start. Als we daar in praktijk niet mee uitkomen, dan zien we wel weer verder.
michielverhoef: Hoe is te zien of iemand de eerste behandelaar is? Waarom niet gelijk alle behandelaren teruggeven en de client zelf uit laten zoeken welke gegevens hij wel/niet wil tonen?


@RvdKlip : Dit zaaknummer bevat toch ook een organisatie aanduiding? De medewerker of de ZAC weet dan dus al dat het een zaak vanuit een andere organisatie betreft.

michielverhoef: In RGBZ1 (basis voor ZDS 1.x) zijn de eerste vier karakters van de zaakidentificatie de gemeentecode.
In RGBZ 2 wat we nu gebruiken is dit losgetrokken en staat dit gegeven in het attribuut bronorganisatie.

Dus alleen op basis van de zaakidentificatie weet je niet bij welke gemeente de zaak aangemaakt is.

@ArjanKloosterboer : Waar heb je de Deelzaakindicatie voor nodig? Een deelzaak is ook maar een zaak ...
@sergei-maertens : Aan API moet toegevoegd worden van welke zaak een zaak een deelzaak is.
@RvdKlip : Inderdaad. Functioneel gaat het enerzijds om de medewerker te laten weten dat een zaak een behoort bij een andere zaak en dus als geheel bezien moeten worden (zeker als we organisatiegrenzen gaan overstijgen) en anderzijds om het gevonden resultaat prettig te kunnen tonen in de interactieschermen van de ZAC (boomstructuurtje, of zo) 

@michielverhoef : Er bestaan 2 soorten relaties: Zaak is Deelzaak van en Zaak heeft gerelateerde Zaak. 
Om een goed beeld te hebben of een zaak bij een andere zaak hoort moet die laatste relatie niet vergeten worden. Sterker nog, "Zaak hoort bij zaak" klinkt mij meer in de oren als de relatie "Zaak heeft gerelateerde Zaak"

Een voorbeeld: ik verleng mijn paspoort en vraag meteen een visum aan voor mijn vakantie in Balkonïe. Dit zijn in principe losse zaken die los van elkaar behandeld kunnen worden. Er zit echter wel een relatie tussen de zaken: zonder geldig paspoort krijg ik dat visum niet en zonder visum heb ik misschien ook geen geldig paspoort nodig want ik blijf thuis (dit even los van de verplichting dat ik me moet kunnen identificeren, dat doe ik wel met mijn rijbewijs).

Deze aanvragen zijn wel gerelateerde zaken maar geen deelzaken van elkaar, ik kan immers ook een geldig paspoort hebben zonder dat ik het verleng. Het verlengen van een paspoort is dus geen deelzaaktype van het zaaktype visum aanvragen. Andersom hoef ik niet per se een visum aan te vragen om een paspoort te verlengen.

@ArjanKloosterboer : je mapt 'Document link (URL)' op 'ENKELVOUDIG INFORMATIEOBJECT.Inhoud'. Het RGBZ kent ook 'ENKELVOUDIG INFORMATIEOBJECT.Link'. Is dit een correcte mapping? Of Link alleen indien Inhoud geen waarde heeft?
@sergei-maertens : Kan je een inhoud aan een informatieobject toekennen en een link (url) opgeven?
@ArjanKloosterboer : Lijkt me van wel. Voor het antwoord op de vraag: wat is de link naar de inhoud?
@sergei-maertens : Het Link attribuut is dan de downloadlink van de Inhoud? Of begrijp ik het verkeerd? Ik had de indruk dat dat attribuut gebruikt kon worden om een externe Link op te geven, naar bijvoorbeeld een PDF die ergens op internet staat. Is dat niet zo dan?
@Rvdklip: waar het mij functioneel om gaat is dat er een url wordt getoond (in het zoek resultaat) waarop een medewerker kan klikken. Na de klik wordt het achterliggende document vervolgens getoond of geopend in een MS teksteditor. Helder genoeg?

michielverhoef: Het link attribuut is de (download) link van de inhoud, de blob in de database zeg maar. In de documentcreatieservices wordt deze ook gebruikt om na het genereren van een document dit weg te schrijven in het DMS. Ook gebruiken veel documentcreatietools die na het initieel vullen van een sjabloon nog handmatige acties (aanpassen van tekst etc.) mogelijk maken deze link om het document weg te schrijven in het DMS. 
Het is geen link naar een gepubliceerde versie van het document.

**Comment by RvdKlip** [comment]
@ArjanKloosterboer : 'Behandelaar van betreffende gevonden zaak': wie wil je weten? Eén van de behandelaren (en welke dan als het er meer zijn) of de zaakcoordinator? Of de laatste maar als die er niet is één van de behandelaren? De desbetreffende betrokkene is veelal een medewerker of organisatorische eenheid maar kan die bij dergelijke zaken ook een vestiging of niet-natuurlijk persoon zijn? Dan wil je daarvan weer de contactpersoon bij de zaak weten (onderdeel van ROL).
@sergei-maertens : Vraag voor @RvdKlip . Voor mij triviaal als er meerdere behandelaren zijn, dat die allemaal getoond/opgevraagd worden via de rol bij een zaak die een referentie naar de betrokkene heeft. Zelfde principe geldt voor zaakcoordinator
@RvdKlip: de eerste behandelaar lijkt me een goede start. Als we daar in praktijk niet mee uitkomen, dan zien we wel weer verder.
@michielverhoef: Hoe is te zien of iemand de eerste behandelaar is? Waarom niet gelijk alle behandelaren teruggeven en de client zelf uit laten zoeken welke gegevens hij wel/niet wil tonen?
@RvdKlip: Prima!

@RvdKlip : Dit zaaknummer bevat toch ook een organisatie aanduiding? De medewerker of de ZAC weet dan dus al dat het een zaak vanuit een andere organisatie betreft.
@michielverhoef: In RGBZ1 (basis voor ZDS 1.x) zijn de eerste vier karakters van de zaakidentificatie de gemeentecode. In RGBZ 2 wat we nu gebruiken is dit losgetrokken en staat dit gegeven in het attribuut bronorganisatie. Dus alleen op basis van de zaakidentificatie weet je niet bij welke gemeente de zaak aangemaakt is.
@RvdKlip: Okee, dan moet dus ook het attribuut Bronorganisatie in het antwoord teruggegeven worden. Ik zal hem in de mappingtabel toevoegen.

@ArjanKloosterboer : Waar heb je de Deelzaakindicatie voor nodig? Een deelzaak is ook maar een zaak ...
@sergei-maertens : Aan API moet toegevoegd worden van welke zaak een zaak een deelzaak is.
@RvdKlip : Inderdaad. Functioneel gaat het enerzijds om de medewerker te laten weten dat een zaak behoort bij een andere zaak en dus als geheel bezien moeten worden (zeker als we organisatiegrenzen gaan overstijgen) en anderzijds om het gevonden resultaat prettig te kunnen tonen in de interactieschermen van de ZAC (boomstructuurtje, of zo).
@michielverhoef : Er bestaan 2 soorten relaties: Zaak is Deelzaak van en Zaak heeft gerelateerde Zaak. Om een goed beeld te hebben of een zaak bij een andere zaak hoort moet die laatste relatie niet vergeten worden. Sterker nog, "Zaak hoort bij zaak" klinkt mij meer in de oren als de relatie "Zaak heeft gerelateerde Zaak". Een voorbeeld: ik verleng mijn paspoort en vraag meteen een visum aan voor mijn vakantie in Balkonïe. Dit zijn in principe losse zaken die los van elkaar behandeld kunnen worden. Er zit echter wel een relatie tussen de zaken: zonder geldig paspoort krijg ik dat visum niet en zonder visum heb ik misschien ook geen geldig paspoort nodig want ik blijf thuis (dit even los van de verplichting dat ik me moet kunnen identificeren, dat doe ik wel met mijn rijbewijs). Deze aanvragen zijn wel gerelateerde zaken maar geen deelzaken van elkaar, ik kan immers ook een geldig paspoort hebben zonder dat ik het verleng. Het verlengen van een paspoort is dus geen deelzaaktype van het zaaktype visum aanvragen. Andersom hoef ik niet per se een visum aan te vragen om een paspoort te verlengen.
@rvdklip: Het gaat hier mij om de 'Zaak is Deelzaak' relatie.
 
@ArjanKloosterboer : je mapt 'Document link (URL)' op 'ENKELVOUDIG INFORMATIEOBJECT.Inhoud'. Het RGBZ kent ook 'ENKELVOUDIG INFORMATIEOBJECT.Link'. Is dit een correcte mapping? Of Link alleen indien Inhoud geen waarde heeft?
@sergei-maertens : Kan je een inhoud aan een informatieobject toekennen en een link (url) opgeven?
@ArjanKloosterboer : Lijkt me van wel. Voor het antwoord op de vraag: wat is de link naar de inhoud?
@sergei-maertens : Het Link attribuut is dan de downloadlink van de Inhoud? Of begrijp ik het verkeerd? Ik had de indruk dat dat attribuut gebruikt kon worden om een externe Link op te geven, naar bijvoorbeeld een PDF die ergens op internet staat. Is dat niet zo dan?
@RvdKlip: waar het mij functioneel om gaat is dat er een url wordt getoond (in het zoek resultaat) waarop een medewerker kan klikken. Na de klik wordt het achterliggende document vervolgens getoond of geopend in een MS teksteditor. Helder genoeg?
@michielverhoef: Het link attribuut is de (download) link van de inhoud, de blob in de database zeg maar. In de documentcreatieservices wordt deze ook gebruikt om na het genereren van een document dit weg te schrijven in het DMS. Ook gebruiken veel documentcreatietools die na het initieel vullen van een sjabloon nog handmatige acties (aanpassen van tekst etc.) mogelijk maken deze link om het document weg te schrijven in het DMS. Het is geen link naar een gepubliceerde versie van het document.
@rvdklip: Ik laat de juiste attribuutkeuze graag aan Michiel of Sergei over. Functioneel is het toch helder genoeg (het achterliggende document (EDC) tonen of openen in een PDF viewer/MS teksteditor)?

**Comment by RvdKlip** [comment]
Ik heb de mappingtabel aangepast (Bronorganisatie toegevoegd)

Om één of andere reden kan mijn eigen comments niet aanpassen in deze US en kan ook niet een vinkje zetten in de definition of ready bij 'Userstory is voorzien van veldmapping naar RGBZ2' en 
'Vastgelegd Github en in geplaatst in kolom ready'. Kan iemand anders dat even doen?

**Comment by TCIMEddy** [comment]
@RvdKlip done

**Comment by TCIMEddy** [comment]
Als er nog informatiemodel vragen zijn dan Remko inschakelen ik heb hem ook als assignee toegevoegd

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest @EdwinCoster al langlopende discussie/user story. Wat te doen?

**Comment by Hugo-ter-Doest** [comment]
Dit is mogelijk door te filteren.
