### ISSUE TITLE
Als behandelaar in de TSA wil ik zien voor welk bevoegd gezag de zaak is aangevraagd 

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#653]
...zodat ik de juiste behandeling kan toepassen.
Voorbeeld: een omgevingsdienst werkt voor verschillende gemeentes, ieder met hun eigen sjabloon, legesregeling, en koppelvlak met OLO, DROP, .... 
 

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [x] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [x] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Graag visie en prio

**Comment by Hugo-ter-Doest** [comment]
Zie mijn vraag bij #654

**Comment by Hugo-ter-Doest** [comment]
Nog niet helemaal duidelijk. Gaat dit om hetzelfde attribuut als bij #654? Of is dit een ander attribuut "Aangevraagd door bevoegd gezag X"?

**Comment by johannesbattjes** [comment]
Zelfde attribuut. In dit geval voeg ik hem niet toe maar krijg ik hem te zien als de zaak automatisch is toegevoegd aan ZS bijvoorbeeld door een eformulier.

**Comment by Hugo-ter-Doest** [comment]
Net als #654 prio zeeer hoog. Als het kan meenemen bij de laaghangend fruit uitbreidingen.

**Comment by TCIMEddy** [comment]
@sergei-maertens @joeribekker Is de vraag van Hugo mogelijk?

**Comment by sergei-maertens** [comment]
@johannesbattjes Hoe refereer je naar een bevoegd gezag? Is dat een RSIN? Is dat een resource in een andere (toekomstige) API?

**Comment by johannesbattjes** [comment]
Nu RSIN, maar wellicht dat dat in common ground anders moet (uri)

**Comment by hdksi** [comment]
@Hugo-ter-Doest: deze is wat mij betreft beantwoord door de discussie bij #654 (die zelf nog een extra antwoord behoeft). Graag prio en vinken.

**Comment by Hugo-ter-Doest** [comment]
Deze wordt gerealiseerd in #654
