### ISSUE TITLE
Als behandelaar in de TSA wil ik het bevoegd gezag van de zaak kunnen wijzigen

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#654]
...zodat ook in zaaksysteem bekend is dat het bevoegd gezag gewijzigd is

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan) Is geen onderdeel van RGBZ/imZTC
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [x] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [x] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Graag visie en prio

**Comment by Hugo-ter-Doest** [comment]
Ik vind het begrip bevoegd gezag niet uit RGBZ of imZTC. Wil je een nieuw attribuut toevoegen aan zaaktype en/of zaak?

**Comment by johannesbattjes** [comment]
Ja een nieuw attribuut. Bevoegd gezag zit inderdaad niet in RGBZ maar wel bijvoorbeeld in STAM/IMAM ([DSO](https://aandeslagmetdeomgevingswet.nl/publish/pages/143589/standaard_aanvragen_en_meldingen_stam_v0_85_01-10-2018.pdf)). Een mogelijke reden hiervoor is dat RGBZ over de zaken van een gemeentes gaat en de betreffende gemeente impliciet als het bevoegd gezag veronderstelt. 

In de praktijk zitten echter  vaak meerdere organisaties in een systeem bij bijvoorbeeld samenwerkingsverbanden en bij omgevingsdiensten en veiligheidsregio's.

**Comment by Hugo-ter-Doest** [comment]
Duidelijk. Gaan we toevoegen.

**Comment by ArnauldvdHeijden** [comment]
Zou je hiervoor niet gewoon het attribuut Verantwoordelijke organisatie voor kunnen/moeten gebruiken?

**Comment by Hugo-ter-Doest** [comment]
@ArjanKloosterboer Kun jij hier iets over zeggen?

**Comment by ArnauldvdHeijden** [comment]
@johannesbattjes, Dit is een RGBZ (2) gegeven en is al opgenomen in ZRC API.

_Definitie Verantwoordelijke organisatie_
Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak. 
Het betreft het RSIN (Rechtspersonen en Samenwerkingsverbanden InformatieNummer) zoals dat door de KvK in het NHR aan elk rechtspersoon en samenwerkingsverband is toegekend. Dit identificeert uniek de organisatie, zijnde een rechtspersoon of samenwerkingsverband, die eindverantwoordelijk is voor de afhandeling van de zaak. Dit kan dezelfde organisatie zijn als de Bronorganisatie; denkbaar is evenwel, bijvoorbeeld in ketensamenwerking, dat de verantwoordelijkheid voor een zaak overgaat naar een andere organisatie gedurende de behandeling daarvan.

In STAM wordt de relatie tussen verzoek en bevoegd gezag omschreven als: 'heeft als verantwoordelijke voor behandeling'. Het enige verschil is dat RGBZ praat over RSIN en STAM over OIN,

**Comment by sergei-maertens** [comment]
Als ik het goed lees, is `bevoegdGezag` een URL-referentie naar een STAM/IMAM API, correct? @johannesbattjes

**Comment by TCIMEddy** [comment]
@sergei-maertens Als je deze kunt en gaat oplossen dan op springbord zetten

**Comment by sergei-maertens** [comment]
Ik moet eerst antwoord op de vraag krijgen voor ik dat kan inschatten... Besides, voor deze sprint is dat te veel, donderdag is de demo...

**Comment by ArnauldvdHeijden** [comment]
Bevoegd gezag is meer een gegeven van een Procesapplicatie en geen zaakgegeven. In die zin zou de zaak dus eerder gerefereerd moeten worden bij het bevoegd gezag (in de procesapplicatie) ipv het bevoegd gezaag bij de zaak (in het ZRC). Feitelijk is het 'slechte' een referentie van waar de zaak afgehandeld wordt welke is ontstaan uit een verzoek.

**Comment by ArjanKloosterboer** [comment]
De Verantwoordelijke organisatie in het RGBZ (2) is de organisatie die de zaak behandelt, die de zaak tot een goed einde moet leiden. Verantwoordelijk dus dat de zaak uitgevoerd wordt. Het Bevoegd gezag (geen RGBZ-gegeven) is blijkbaar de organisatie onder wiens bevoegdheid de behandeling plaats vindt. Maar die niet persé zelf de behandelaar is. Lijkt me een procesgegeven van het proces dat zaakgericht uitgevoerd wordt door de verantwoordelijke organisatie (zodat die weet voor wie ze het proces als zaak uitvoeren).    

> In STAM wordt de relatie tussen verzoek en bevoegd gezag omschreven als: 'heeft als verantwoordelijke voor behandeling'.

M.i. is dit geen scherpe definitie. Het bevoegd gezag heeft de OD gemandateerd om dergelijke verzoeken te behandelen. Verantwoordelijke voor een dergelijke behandeling is dan dan die OD.  Het bevoegd gezag is verantwoordelijk voor het doen behandelen van dergelijke verzoeken, zijn is niet verantwoordelijke voor de behandeling van een individueel verzoek. 
Jammer dat het Bevoegd gezag aangeduidt wordt met een OIN dat niet meer of minder is dan het 'adres' van de digitale brievenbus van een organisatie ('waar is die organisatie digitaal te vinden') terwijl het hier m.i. gaat om het identificeren van die organisatie. Daar hebben we het HR voor.

**Comment by johannesbattjes** [comment]
UIt Arjan's commentaar concludeer ik dat bevoegd gezag iets anders is dan verantwoordelijke. Daar ben ik ook het mee eens. 
In reactie op @sergei-maertens: bevoegd gezag is geen referente naar STAM/IMAM. Ik kan me voorstellen dat in een ander domein dan omgeving ook een bevoegd gezag kan woren aangewezen voor de zaak. Maar ook los daarvan: een bevoegd gezag (een gemeente bijvoorbeeld) bestaat ook zonder STAM/IMAM. Mij lijkt een referentie naar een RSIN (HR) of een andere lijst met bevoegd gezagen logischer.
"Bevoegd gezag is meer een gegeven van een Procesapplicatie en geen zaakgegeven". Een procesapplicatie kan gegevens van meerdere bevoegde gezagen bevatten, dat is juist het probleem waar we tegenaanlopen. En dat we als Roxit oplossen door een veld "Bevoegd Gezag" bij de zaak. Maar dat kunnen we nu dus niet goed uitwisselen met het leidend zaakysteem.

**Comment by ArnauldvdHeijden** [comment]
Je zou Eigenschap kunnen gebruiken. Ik denk dat er voor gewaakt moet worden dat er van alles toegevoegd wordt aan zaakgegevens die niet voorkomen in de RGBZ. Zeker gezien het feit dat nog lang niet alle gegevens aanwezig zijn.

**Comment by ArjanKloosterboer** [comment]
Een Bevoegd gezag is m.i. niet meer of minder dan een rol (specialisatie) van een Niet-natuurlijk persoon. Verwijzen dus naar het HR.
V.w.b. opname conform RGBZ, het heeft er veel van weg dat een dergelijk bevoegd gezag een rol heeft bij een desbetreffende zaak. Hij is opdrachtgever in generieke zin. Een optie is dan om het desbetreffende bevoegde gezag (NNP) vast te leggen als Betrokkene bij de Zaak in een Rol met als 'Rolomschrijving generiek': "belanghebbende" en als 'Rolomschrijving': "Bevoegd gezag".

**Comment by ArjanKloosterboer** [comment]
De vraag is of deze standaardisatie wel thuis hoort in de standaard RGBZ. De laatste is een standaard voor zaakgericht werken in het algemeen, niet voor het behandelen van specifieke typen zaken in specifieke domeinen. Gegevens van die specifieke typen zaken (de zgn. zaaktypespecifieke gegevens) horen thuis in het (standaard) informatiemodel van het desbetreffende domein (en in de desbetreffende registratiecomponent). Niet in een generiek model als het RGBZ. 
De vraag die beantwoord moet worden is of 'Bevoegd gezag' een domein-specifiek gegeven is dan wel dusdanig domeinoverstijgend is dat er voldoende redenen zijn dit op te nemen in een generiek model. Een generiek model i.c. RGBZ dat hiervoor al voorzieningen heeft (rol als belanghebbende). Vaag is het laatste niet, het wordt gespecificeerd bij het desbetreffende zaaktype. Daar liggen de afspraken omtrent zaakinrichting vast.

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat het domeinoverstijgend is. Ik kan me prima vinden in de richting die Arjan schetst met betrokkenen bij een zaak in een rol "Bevoegd gezag". Ik stel voor het zo op te lossen.

**Comment by johannesbattjes** [comment]
Beste Arjan,

Volgens mij is het niet goed werkbaar dit als betrokkene met rol bevoegd gezag te modelleren. In een zaaksysteem of TSA zitten heel veel functies die van de waarde van dit veld afhankelijk zijn. Zoals de legesverordening, de werkverdeling, de exports en koppelingen naar verschillende externe systemen. Deze software moet kunnen uitgaan van een ‘vast’ veld en niet van een rol die wijzigbaar is de in de ZTC.

Daarnaast is het in de uitwisseling te vrijblijvend. Het is slechts een van de vele mogelijke rollen, en wordt daarom wellicht niet goed gevuld of ondersteund door het systeem waarmee gecommuniceerd wordt.

Hieronder overigens nog een eis uit een aanbesteding die ik vanmorgen zag:
Een aantal Opdrachtgevers [] voert taken uit voor meer dan één Bevoegd Gezag.  De VTH-Oplossing moet geschikt zijn om de taken die één Opdrachtgever uitvoert voor verschillende Bevoegde Gezagen functioneel - en zonodig ook technisch - van elkaar te scheiden. De voornaamste redenen daarvoor zijn de scheiding van - veelal wettelijk vastgelegde - verantwoordelijkheden, taken en bevoegdheden per Bevoegd Gezag, resulterend in (niet uitputtend):
•    lokaal beleid
•    lokale regelgeving
•    lokale (be)sturing
•    lokale verantwoording
•    lokale financiering
Daarom moet binnen de VTH-Oplossing logisch, functioneel én technisch onderscheid kunnen worden gemaakt tussen de verschillende Bevoegde Gezagen waarvan de VTH-taken door de VTH-Oplossing worden ondersteund. ..
Met vriendelijke groet,
Johannes Battjes
Product manager koppelingen
m

06 10395351


Nieuwsgierig naar Roxit? Meld u aan voor onze digitale nieuwsbrief<mailto:nieuwsbrief@roxit.nl>.

Van: Arjan Kloosterboer (VNG Realisatie) [mailto:notifications@github.com]
Verzonden: maandag 17 december 2018 08:54
Aan: VNG-Realisatie/ZDS2.0 <ZDS2.0@noreply.github.com>
CC: Johannes Battjes <Johannes.Battjes@roxit.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [VNG-Realisatie/ZDS2.0] Als behandelaar in de TSA wil ik het bevoegd gezag van de zaak kunnen wijzigen (#654)


Een Bevoegd gezag is m.i. niet meer of minder dan een rol (specialisatie) van een Niet-natuurlijk persoon. Verwijzen dus naar het HR.
V.w.b. opname conform RGBZ, het heeft er veel van weg dat een dergelijk bevoegd gezag een rol heeft bij een desbetreffende zaak. Hij is opdrachtgever in generieke zin. Een optie is dan om het desbetreffende bevoegde gezag (NNP) vast te leggen als Betrokkene bij de Zaak in een Rol met als 'Rolomschrijving generiek': "belanghebbende" en als 'Rolomschrijving': "Bevoegd gezag".

**Comment by Hugo-ter-Doest** [comment]
Om de consistentie te behouden in de API wil ik het bestaande patroon volgen voor betrokkenen in een rol. Eventueel voegen we later (voor het gemak) een afgeleid attribuut aan de zaak toe om direct(er) het bevoegd gezag te kunnen ophalen.

**Comment by hdksi** [comment]
Tijdens de laatste sprint planning is deze user story uit de backlog gevist. Daarom een nieuwe reactie op basis van nieuwe inzichten.

Het lijkt mij de praktijk van het uitvoeren van processen 'op gezag van' een andere dan de eigen organisatie bij samenwerkingsorganisaties binnen verschillende domeinen aan de orde van de dag is. Daardoor is wat mij betreft dus sprake van een generiek, niet aan een specifiek domein of proces gerelateerd, issue.

Bovendien is ‘bevoegd gezag’ wat mij betreft qua karakter iets fundamenteel anders dan een ‘betrokkene’. Zonder toestemming van het bevoegd gezag mag immers niet beschikt of besloten worden. Een attribuut 'bevoegd gezag' (opdrachtgever) hoort daarom wat mij betreft thuis op hetzelfde niveau als het attribuut 'verantwoordelijkeOrganisatie' (opdrachtnemer).

Als het gaat om het daadwerkelijk kennen van het bevoegd gezag, vraagt dat om twee attributen: 1) een verwijzing naar de organisatie waarbinnen het bevoegd gezag zetelt, en 2) een verwijzing naar het bestuursorgaan binnen die organisatie dat optreedt als bevoegd gezag. Voor gemeenten zijn dit bijvoorbeeld 'burgemeester', 'gemeenteraad' en 'college van B&W'. Het bestuursorgaan wordt overigens al optioneel vastgelegd bij een besluit (zie bijvoorbeeld https://besluiten-api.vng.cloud/api/v1/schema/#operation/besluit_create).

Merk op dat ‘bestuursorgaan’ en daarmee ‘bevoegd gezag’ publiek-/bestuursrechtelijke begrippen zijn. Het opnemen van deze attributen impliceert dan ook dat er alleen interesse is om te weten wie verantwoordelijk is voor een proces zolang die zaak invulling geeft aan taken die binnen deze rechtsgebieden vallen, en bovendien zaken die leiden tot het afgeven van een beschikking of het nemen van een besluit.

Vraag is wel of het verzoek van @johannesbattjes (en dan primair #653) daadwerkelijk gaat om het ‘de jure’ kennen van een bevoegd gezag bij een bepaalde zaak (en dan vooral de bevoegdheid daarbinnen beschikkingen af te geven of besluiten te nemen), of dat het eigenlijke doel is om onderscheid te kunnen maken tussen verschillende organisaties waarvoor zaken worden behandeld. Als dat inderdaad zo is, dan is het waarschijnlijk beter om een meer algemeen attribuut als ‘opdrachtgevende organisatie’ bij ‘zaak’ op te nemen.

> **Opdrachtgevende organisatie**
> De krachtens publiekrecht ingestelde rechtspersoon dan wel ander niet-natuurlijk persoon waarbinnen het (bestuurs)orgaan zetelt dat opdracht heeft gegeven om taken uit te voeren waaraan de zaak invulling geeft.
> 

Het eerste deel van de definitie verwijst naar een organisatie en daarbinnen bevoegd gezag als opdrachtgever. Hierdoor worden eisen gesteld aan het karakter van de opdrachtgever - dat kan dus niet zomaar iedereen zijn. Maar het tweede deel stelt geen verdere eisen aan de inhoud van de gegeven opdracht. Daardoor is binnen de definitie óók ruimte voor privaatrechtelijke opdrachten van een college van B&W aan samenwerkingsorganisaties uit te voeren (het leveren van ICT-ondersteuningsdiensten bijvoorbeeld).

Deze user story vraagt ten slotte om de mogelijkheid het bevoegd gezag/opdrachtgevende organisatie te wijzigen. Ik me voorstellen dat zo’n wijziging invloed kan hebben op verloop en uitkomst van een zaak (afwijkende regels, drempels etc.). Vraag van mij is daarom of, en zo ja hoe vaak één zaaktype voor meerdere organisaties worden gebruikt. Als dat niet aan de orde is, dan kan het voorgestelde attribuut misschien beter bij ‘zaaktype’ dan bij ‘zaak’ worden toegevoegd. Consequentie daarvan is uiteraard wel dat de in deze user story gevraagde functionaliteit niet kan worden gerealiseerd.

Dank aan @ArjanKloosterboer voor het meedenken.

**Comment by johannesbattjes** [comment]
Beste Ivo,

Ik ben blij met de oplossing die je schetst. We zullen hier beter mee overweg kunnen dan met een betrokkene met rol. 

De vraag om bevoegd gezag binnen een organisatie (B& W, Burgemeester, ..) ook vast te leggen komen wel tegen bijvoorbeeld bij publicaties van bekendmakingen (aan wie bezwaar te richten) en bij adviesverzoeken (aan wie adviesverzoek te richten), maar deze vraag is niet zeer dringend.

Het is wel dringend om per zaak de organisatie te kunnen vastleggen. Stel een Omgevingsdienst bedient de omgevingsvergunningen voor tien gemeentes op basis van zaaktype "Aanvraag beschikking behandelen".
Dan is het handig per zaak de opdrachtgever vast te kunnen leggen. Anders zou de omgevingsdienst tien vrijwel identieke zaaktypes moeten configureren, alleen om de opdrachtgever vast te kunnen leggen. Dit kan veel werk en onderhoud betekenen: alle wijzigingen zullen dan tien keer moeten worden doorgevoerd.
Deze werkwijze van het vastleggen per zaak  is gebruikelijk bij omgevingsdiensten die bij ons klant zijn, evenals bij veiligheidsregio's en bij samenwerkingsverbanden van gemeentes.

**Comment by hdksi** [comment]
Uit de toelichting van @johannesbattjes haal ik dat aan het kennen van het daadwerkelijke 'bevoegd gezag' bij een zaak weliswaar nodig kan zijn, maar dat daaraan een andere functionele wens ten grondslag ligt dan degene waarop de voorliggende user story is gericht.

Vanwege de beperkingen - geen ruimte voor privaatrechtelijke opdrachten van een college van B&W aan samenwerkingsorganisaties - die het hanteren van 'bevoegd gezag' voor het doel van de user story met zich meebrengt, stel ik voor bij `Zaak` een nieuw, optioneel attribuut op te nemen, namelijk:

**> Opdrachtgevende organisatie**
> De krachtens publiekrecht ingestelde rechtspersoon dan wel ander niet-natuurlijk persoon waarbinnen het (bestuurs)orgaan zetelt dat opdracht heeft gegeven om taken uit te voeren waaraan de zaak invulling geeft.

Deze `Opdrachtgevende organisatie` wordt geïdentificeerd aan de hand van zijn RSIN.

**Comment by johannesbattjes** [comment]
Lijkt mij prima!

**Comment by hdksi** [comment]
@johannesbattjes: nog één vraag hierover: door de discussie hierboven over hoe een Opdrachtgevende organisatie kan worden vastgelegd - eigenlijk een antwoord op #653 - is de vraag die hoort bij deze specifieke user story enigszins uit zicht verdwenen.

Om daadwerkelijk antwoord te geven op de US , is dus nog de vraag of, en zo ja in welke gevallen je de 'Opdrachtgevende organisatie' zou willen kunnen of mogen aanpassen. Ik vraag me namelijk af of zo'n aanpassing überhaupt mogelijk moet zijn. Heb je een concreet voorbeeld van zo'n situatie?

**Comment by NolWitte** [comment]
@hdksi: Dit kan voorkomen als tijdens de behandeling blijkt dat het zwaartepunt van een vergunningaanvraag toch bij een ander bevoegd gezag ligt (bij een aanvraag die dicht op de grens tussen twee gemeenten ligt) of als bijvoorbeeld een klacht (stank, herrie) betrekking blijkt te hebben op een provinciale milieuinrichting (en niet op een gemeentelijke). 

Tot slot zou het natuurlijk ook mogelijk moeten zijn om een menselijke fout in de registratie te corrigeren. Wat dat betreft is dit gegeven wat mij betreft metadata van de zaak als elk ander.

**Comment by hdksi** [comment]
@NolWitte: de eerste situatie lijkt, me, gezien de [hier eerder door @MarcoKlerks uiteengezette archiefwettelijke verplichtingen bij overdracht van dossiers tussen organisaties](https://github.com/VNG-Realisatie/gemma-zaken/issues/367#issuecomment-426614788) erg ingewikkeld. Komt dit daadwerkelijk voor?

Correctie van menselijke fouten lijkt me inderdaad een ander verhaal, al geldt daarvoor wellicht  formeel hetzelfde.

**Comment by NolWitte** [comment]
Naar mijn indruk is de casus van Marco compleet anders dan die bij mij speelt. Als ODMH voeren wij het formele digitale archief voor onze zeven opdrachtgevers. Aanvragen/meldingen komen direct binnen bij de ODMH; de opdrachtgevers hebben bij die zaken noch bij ontstaan, noch bij behandeling noch bij de archivering in praktische zin een rol.

In mijn voorbeeld zou het een vergunningaanvraag kunnen betreffen die eerst gezien wordt als een zaak waarvoor wij voor bevoegd gezag Gouda de taken uitvoeren. Bij nadere beoordeling blijkt dat de zaak feitelijk onder de bevoegdheid van gemeente Waddinxveen valt. Voor die beide gemeenten voeren we de taken uit. In praktische zin verandert er dus niks, behalve dat je bij de zaak de juiste "opdrachtgevende instantie" wilt kunnen registreren.

**Comment by hdksi** [comment]
@NolWitte dank voor je toelichting en voorbeeld. Ik begrijp inderdaad dat omgang met en verantwoordelijkheid voor archiefbeheer afhankelijk is van de gekozen samenwerkingsvorm en dat Marco's casus niet per se geldt voor alle varianten van samenwerkingsverbanden.

Wijzigen van attribuut is dus toegestaan.

@Hugo-ter-Doest: ook hier graag prioriteit.

**Comment by Hugo-ter-Doest** [comment]
Er wordt een attribuut toegevoegd opdrachtgevendeOrganisatie aan zaken van type string. Er wordt gevalideerd of het een RSIN is.

**Comment by HenriKorver** [comment]
@michielverhoef Kun jij deze oppakken?

**Comment by michielverhoef** [comment]
Het valt niet helemaal onder dit issue wellicht maar is het niet nodig om ook op 'Opdrachtgevende organisatie' te kunnen filteren? 

Hier moet dan een nieuwe userstory voor aangemaakt worden maar ik zou het graag meenemen als ik toch bezig ben.

@hdksi ?

**Comment by hdksi** [comment]
@michielverhoef Kan me inderdaad voorstellen dat dat nuttig is. Wellicht dat @johannesbattjes hier vanuit de praktijk iets over kan zeggen?

**Comment by michielverhoef** [comment]
Het attribuut Opdrachtgevende Organisatie is in ieder geval alvast toegevoegd aan https://github.com/VNG-Realisatie/gemma-zaken/tree/MichielVerhoef-654-bevoegdgezagwijzigen/api-specificatie/DESIGN/zrc 

Volgens mij hoeven er geen extra/aparte autorisaties ed. ingesteld te worden en is er ook geen speciaal gedrag nodig. 

@joeribekker  is dit voldoende zo voor jou?

**Comment by michielverhoef** [comment]
Voor het eventueel kunnen filteren op Opdrachtgevende Organisatie heb ik US #1660 aangemaakt.

**Comment by johannesbattjes** [comment]
Ik ken de wens om werkvoorraad te filteren op opdrachtgever niet direct uit eigen ervaring, maar ga dit direct navragen. 
Het antwoord voeg ik dan toe  aan #1660

**Comment by joeribekker** [comment]
Wordt onderdeel van 1.0.2.
