### ISSUE TITLE
Bump dependencies in referentieimplementaties ivm vulnerabilities

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#668]
Alle referentieimplementaties hebben momenteel dependencies op door vulnerabilities geplaagde software, graag bijwerken.

<img width="747" alt="screenshot 2018-12-12 at 22 17 51" src="https://user-images.githubusercontent.com/20684884/49899412-ee66e580-fe5b-11e8-9d4d-49256b805387.png">

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Graag prio aangeven (ik heb geen idee wat het is)

**Comment by sergei-maertens** [comment]
Alles is gepatched
