### ISSUE TITLE
Google Maps wordt niet correct geladen in MOR-demo

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#669]
# Bug

Bij mij kan Google Maps kan niet meer correct worden geladen in MOR-demo: https://ref.tst.vng.cloud/demo/demo/mor/

**Comment by joeribekker** [comment]
Opgelost. Ging om de API key die in een verlopen project zat.

**Comment by sergei-maertens** [comment]
Is nu gefixed.
