### ISSUE TITLE
Hoe om te gaan met RGBZ dat (een deel van) de RSGB/ZTC/BAG modellen bevat?

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#67]
**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

Uitgangspunt van de nieuwe ZDS is o.a. het RGBZ 2.0. Echter, er is overlap en/of overgeerft uit RSGB, ZTC en BAG informatiemodellen.

Moet dit juist opgesplitst worden? Het gaat bijvoorbeeld om Waterdeel, Terreindeel, etc. dat in RSGB en RGBZ zit. Zaaktype leeft in ZTC en in RGBZ.

Ik zelf neig er naar om de data-bij-de-bron (tm) te houden en te verwijzen. Ter illustratie: Een Zaak, ontsloten via API X (met daarachter een RGBZ-ish datamodel), is van Zaaktype die staat beschreven in API Y (met daarachter een ZTC-ish datamodel). Dit betekent dus echt dat er geen kopie van het Zaaktype leeft in in het RGBZ-ish datamodel.

**Comment by ehotting** [comment]
Zo zijn de informatiemodellen (RGBZ, RSGB) ook bedoeld. De informatiemodellen zijn niet bedoeld om 1 op 1 om te zetten in datamodellen. In de beschrijving van het objecttype "Zaaktype" staat "herkomst: ZTC". In welke datamodel / in welke database dat leeft vindt men op niveau informatiemodel niet interessant. Dit soort keuzen moet idd worden gemaakt, en is deel van het specificeren van een samenhangend geheel aan API's.  Het informatiemodel laat zelfs ruimte voor het ophalen van zaaktypen uit verschillende zaaktypecatalogussen, door RSIN toe te voegen. Je zou dus zaken van zaaktype A kunnen ophalen uit ZTC organisatie X en zaaktype B uit ZTC organisatie Y.

**Comment by joeribekker** [comment]
Klinkt goed, ook als hier consensus over is binnen VNG.

Side-effect van deze overlap is volgens mij dat het concept "versioning" aanwezig is in de informatiemodellen, zoals ik heb begrepen dat het bij VNG leeft. Ter illustratie:

_Als een Zaak wordt aangemaakt in het ZRC wordt de dan geldende Zaaktype data (uit het ZTC) gekopieerd naar het ZRC. Als het Zaaktype later wijzigt, dan heeft de destijds aangemaakte Zaak de destijds geldende versie van het Zaaktype zoals dat in het ZRC stond._

Het is dus niet zo dat wij in de huidige situatie in het ZRC een overzicht kunnen zien van alle versies van een bepaald Zaaktype. Dit lijkt me wel wenselijk in de nieuwe specificatie.

**Comment by ehotting** [comment]
Ben benieuwd naar opinie @ArjanKloosterboer over dit onderwerp.

**Comment by ArjanKloosterboer** [comment]
Allereerst, het RGBZ speelt alleen 'leentje buur' bij ImZTC en RSGB, niet (direct) bij de BAG. Het RSGB op zijn beurt is een view op basisregistraties, zoals de BAG en ook BGT, BRK, BRP, HR en BrWOZ. De genoemde voorbeelden zoals Waterdeel komen uit de BGT, niet uit de BAG.
Verder, RSGB en ImZTC zijn informatiemodellen. Die hebben geen enkel verband met (de plek van) fysieke opslag van data waarmee dergelijke modellen fysiek zijn geimplementeerd. Als er in het RGBZ bijvoorbeeld staat 'Herkomst: ImZTC' dan duidt dat alleen aan aan welke kennisbron een objecttype, een definitie e.d. ontleend is. Het doet geen enkele uitspraak over de plek van data waarin dergelijke informatie is geimplementeerd. Implementatie van informatiemodellen in databases is dus een min of meer vrije keus, wel telkens binnen de kaders van het desbetreffende informatiemodel. Maar m.i. gaat het meer om de API's dan waar de data staat. In ieder geval moeten die twee goed uit elkaar gehouden worden. 
Dan, het RGBZ is gemodelleerd voor het domein 'generiek behandelen van en informeren over zaken'. Dat is een ander domein dan het beheren van zaaktypen (ImZTC) en het informeren over basis- en kerngegevens (RSGB). Uiteraard is er een overlap. Die is verwerkt als view in het RGBZ. Binnen het RGBZ-domein is aan minder informatie over zaaktypen en basis- en kerngegevens behoefte dan in de andere domeinen. Het lijkt mij dan ook dat er op basis van het RGBZ en dus voor het generiek behandelen van en informeren over zaken specifieke API's zijn ten opzichte van API's o.b.v. ImZTC en RSGB. Dus nee, geen hergebruik van API's, dan verlies je scherpte. Dat geldt m.i. dus ook weer voor RSGB-gerelateerde API's versus basisregistratie-API's. De data waarop deze API's acteren kan daarentegen wel telkens op één plek geimplementeerd zijn. Dus voor de zaakbehandelende organisatie bijvoorbeeld één database met zaaktypen conform ImZTC met daarop zowel ImZTC- als RGBZ-gerelateerde API's. M.i. betreft dit in GEMMA2 de ZTC-component, niet de ZRC. Maar ik kan me vergissen. De zaken-database (ZRC) zou dan alleen het gedeelte van het RGBZ bevatten dat geen view is op het ImZTC (en idem RSGB). 
Al met al, data netjes gescheiden, alles éénmalig, maar informatiemodel- cq. domein-gebonden API's, met overlap, ja, want elk domein en elke usecase stelt z'n eigen vragen. 

Voor wat betreft de laatste opmerking van Youri, m.i. wordt een (versie van een) zaaktype niet gekopieerd naar de ZRC op het moment er een zaak van dat type wordt aangemaakt. Zaaktypen staan 'in de ZTC-database' (alles eenmalig op één plek). M.b.v. een op het RGBZ-gebaseerde API kunnen de voor het RGBZ-domein relevante gegevens van een versie van een zaaktype 'opgehaald' worden uit 'die ZTC-database'.

**Comment by ehotting** [comment]
> Voor wat betreft de laatste opmerking van Youri, m.i. wordt een (versie van een) zaaktype niet gekopieerd naar de ZRC op het moment er een zaak van dat type wordt aangemaakt. Zaaktypen staan 'in de ZTC-database' (alles eenmalig op één plek). M.b.v. een op het RGBZ-gebaseerde API kunnen de voor het RGBZ-domein relevante gegevens van een versie van een zaaktype 'opgehaald' worden uit 'die ZTC-database'.

Dit betekent dat de API voor ZTC volledig "tijdreizen" mogelijk moet maken, correct?

**Comment by joeribekker** [comment]
Bedankt voor je uiteenzetting @ArjanKloosterboer en uiteraard eens met je opmerking dat de informatiemodellen niets zeggen over de fysieke opslag.

> Voor wat betreft de laatste opmerking van Youri, m.i. wordt een (versie van een) zaaktype niet gekopieerd naar de ZRC op het moment er een zaak van dat type wordt aangemaakt.
_\- ArjanKloosterboer_

@michielverhoef heeft dit zo aan mij uitgelegd en was er zelf ook recent pas achtergekomen. Ik kan hem natuurlijk verkeerd begrepen hebben.

De synchronizatie berichten die voor in [StUF-ZTC](https://www.gemmaonline.nl/index.php/Sectormodel_Zaaktypen(-catalogus):_StUF%E2%80%93ZTC) zijn opgesteld lijken echter wel aan te geven dat er e.e.a. heen en weer wordt gekopieerd/gesynchronizeerd?

> Dit betekent dat de API voor ZTC volledig "tijdreizen" mogelijk moet maken, correct?
_\- ehotting_

Hoewel ik er vrij zeker van ben het antwoord op je vraag ja moet zijn, vind ik 1 belemmering in het informatiemodel hiervoor, en het ontbreken van uitleg over hoe dit zou moeten werken maakt het lastig.

Ik denk dat Arjan en ik elkaar niet begrijpen op dit punt in eerdere discussies:
* https://discussie.kinggemeenten.nl/discussie/gemma/ztc/unieke-aanduiding-zaaktype-bij-meerdere-versies
* https://discussie.kinggemeenten.nl/comment/5851#comment-5851

**Comment by ehotting** [comment]
Dat is correct: we begrijpen elkaar niet goed genoeg. Ik denk ieders op zich coherente verhaal te volgen, welke ontstaan vanuit verschillende gezichtspunten op de materie. Kan helaas nog niet pinpointen waarom deze verschillende viewpoints niet op een zelfde onderliggende werkelijkheid lijken te passen. 

 Ik denk dat een sessie rond een whiteboard nodig is. Van minimaal 2 - 3 uur.

**Comment by michielverhoef** [comment]
@ehotting : voor mezelf kan ik alleen maar aangeven dat ik teveel vanuit een implementatie standpunt denk: ik maak er een datamodel voor een (relationele) database van. Dan snap ik het. 
De informatiemodellen zijn soms anders gemodelleerd dan een relationele database en hoewel de uitleg wel te begrijpen is is het voor ontwikkelaars soms niet in 1 oogopslag duidelijk hoe dingen bedoeld zijn.
In dat licht is een referentiedatamodel misschien niet eens zo'n gek idee, het maakt het wel veel eenvoudiger communiceren.

**Comment by ArjanKloosterboer** [comment]
> Dit betekent dat de API voor ZTC volledig "tijdreizen" mogelijk moet maken, correct?
> - ehotting
> Hoewel ik er vrij zeker van ben het antwoord op je vraag ja moet zijn, vind ik 1 belemmering in het informatiemodel hiervoor, en het ontbreken van uitleg over hoe dit zou moeten werken maakt het lastig.
> - joeribekker

Wat bedoel je precies met tijdreizen? M.i. moet het mogelijk zijn om de specificaties van een zaaktype op te vragen zoals die op een bepaald moment (datum) geldig waren of zijn. Feitelijk vraag je daarmee de versie van een zaaktype op die op dat moment geldig is. Vul je geen datum in, dan krijg je de actuele versie (versie met laatstbekende versiedatum).
V.w.b. de aangehaalde discussie 'Unieke aanduiding ZaakType bij meerdere versies' (en ook de andere), in het informatiemodel bestaat de unieke aanduiding van een zaaktype uit de unieke aanduiding van de Catalogus waartoe het zaaktype behoort i.c.m. de Zaaktype-identificatie (zonder versiedatum, dat is immers historie die we verder niet uitmodelleren in een SIM). In een database (en ook een UGM?) zal de versiedatum wel deel uitmaken van de identificatie van een record betreffende het zaaktype, teneinde de verschillende waarden van gegevens van een zaaktype bij de onderscheiden versies vast te kunnen leggen.

**Comment by ArjanKloosterboer** [comment]
> Dat is correct: we begrijpen elkaar niet goed genoeg. Ik denk ieders op zich coherente verhaal te volgen, welke ontstaan vanuit verschillende gezichtspunten op de materie. Kan helaas nog niet pinpointen waarom deze verschillende viewpoints niet op een zelfde onderliggende werkelijkheid lijken te passen.
> _ehotting_
Wellicht wordt dit veroorzaakt doordat de een vanuit een conceptueel informatiemodel (SIM RGBZ) denkt, de ander vanuit een - daarvan afgeleid - gegevensmodel (UGM Zaken), weer een ander vanuit een API en nog iemand anders vanuit een database.  Check voor jezelf.

**Comment by joeribekker** [comment]
> in het informatiemodel bestaat de unieke aanduiding van een zaaktype uit de unieke aanduiding van de Catalogus waartoe het zaaktype behoort i.c.m. de Zaaktype-identificatie (zonder versiedatum, dat is immers historie die we verder niet uitmodelleren in een SIM). In een database (en ook een UGM?) zal de versiedatum m.i. wel deel uitmaken van de identificatie van een record betreffende het zaaktype
_\- ArjanKloosterboer_

Dit is het ontbrekende stukje informatie voor mij.

Hoewel ik het vreemd vind dat als het attribuut versiedatum in het informatiemodel zit en er wordt in aangegeven wat een Zaaktype uniek maakt, dat versiedatum daar niet expliciet bij staat. Enfin, helder.

Ik plak Arjan's antwoord ook even in het forum topic :)

**Comment by ehotting** [comment]
> Wat bedoel je precies met tijdreizen?
> _- ArjanKloosterboer_

Een term die door overheidsarchitecten wordt gebruikt voor een wat meer geavanceerde vorm van toegang tot historie - de materiële en formele historie beschikbaar maken via de API zeg maar. Alleen een datum van ingang wijziging is niet voldoende wanneer de ZTC de authentieke bron is, er zullen situaties ontstaan waardoor de typen met terugwerkende kracht moeten worden gewijzigd - dan heb je materiële en formele historie. De "versiedatum" is wat dat betreft niet neutraal, het geeft beperkend richting aan de manieren waarop het vervolgens nog gemodelleerd kan worden in een relationele database. Stel dat we het zouden willen modelleren in een Graph database of dit probleem met event buffers zouden willen oplossen dan wordt het lastig.

Ik hoor vaak over SIM en UGM, maar gemmaonline.nl reageert niet op die zoektermen. Ook niet op GBZ. Ik neem aan dat ergens verwoord staat welke ontwerpkeuzes voor de SIMs gelden, waaronder het uitgangspunt dat historie niet uitgemodelleerd wordt in een SIM? Dat document zou ik graag lezen voor een beter begrip van hoe e.e.a. zich tot elkaar verhoudt.

> Wellicht wordt dit veroorzaakt doordat de een vanuit een conceptueel informatiemodel (SIM RGBZ) denkt, de ander vanuit een - daarvan afgeleid - gegevensmodel (UGM Zaken), weer een ander vanuit een API en nog iemand anders vanuit een database.
> - ArjanKloosterboer

Ondanks dat zou het wel allemaal op elkaar moeten passen. :)

**Comment by ArjanKloosterboer** [comment]
> Hoewel ik het vreemd vind dat als het attribuut versiedatum in het informatiemodel zit en er wordt in aangegeven wat een Zaaktype uniek maakt, dat versiedatum daar niet expliciet bij staat. Enfin, helder.
> - _joeribekker_
Een zaaktype wordt geidentificeerd door de zaaktypeidentificatie i.c.m. van de Id van de zaaktypecatalogus waar het zaaktype deel van uit maakt. 
Een versie van een zaaktype wordt geidentificeerd door de versiedatum van de versie van het zaaktype i.c.m. de identificatie van dat zaaktype en de Id van de zaaktypecatalogus waar het zaaktype deel van uit maakt.

**Comment by ArjanKloosterboer** [comment]
> @ehotting,  historie in het ImZTC cq. een zaaktypecatalogus. 

In het ImZTC werken we ook met materiele en formele historie. Alleen zijn daar beperkingen aan gesteld (specifiek voor het ImZTC). De materiele historiedatum van een versie van waarden van enkele zaaktypegegevens moet gelijk zijn aan een versiedatum van het zaaktype. Daarmee bereiken we dat we kunnen werken met versies van zaaktypen waarvoor de waarden van de zaaktypegegevens stabiel zijn voor een versie (kunnen alleen wijzigen op een versiedatum). Door ook formele historie toe te passen kunnen waarden van een oude versie eventueel gewijzigd worden; je kunt dan zien wanneer die wijziging is doorgevoerd wat wel 's na de volgende versiedatum kan liggen. Het doorvoeren van mutaties in het verleden luistert nauw, consequenties moeten goed doorzien worden. 
Samengevat, jouw kijk (en die van de door jou aangehaalde overheidsarchitecten) op tijdreizen was al en is en blijft geheel verwerkt in alle GEMMA-informatiemodellen. Het ImZTC heeft daarop nog een aanvullende restrictie.
Waar is de wijze van modelleren van historie na te lezen, vraag je? In het [MIM, het Metamodel voor Informatiemodellering](https://www.geonovum.nl/geo-standaarden/metamodel-informatiemodellering/nationaal-metamodel-voor-informatiemodellering), onze 'bijbel' voor het specificeren van informatiemodellen. Zie oa. par. 3.9.

**Comment by ehotting** [comment]
Dank. In RGBZ 2 zelf zijn indicaties historie bij Zaaktype dus niet aangeduid, bij ImZTC wel. Moet toegeven dat ik het nog niet begrijp. 

Het MIM ken ik, daarin vind ik de termen SIM en UGM niet terug. Een document waarin staat dat de SIM een Conceptueel Informatiemodel betreft, en een UGM een Logisch Informatiemodel - een dergelijk document bestaat vast wel? Immers ook in de inleiding van RGBZ specificatie staat niet dat het een Conceptueel Informatiemodel betreft.

Heb vooral een hoop vragen bij de afwegingen rond het modelleren van het Conceptueel Model. Dit issue is echter niet de juiste plek - maar als er een document is waarin e.e.a. nader wordt toegelicht, heel graag.

**Comment by ArjanKloosterboer** [comment]
> In RGBZ 2 zelf zijn indicaties historie bij Zaaktype dus niet aangeduid, bij ImZTC wel.

In RGBZ2 zijn objecttypen en attribuutsoorten ontleend aan o.a. het ImZTC. Dergelijke proxy-constructies worden slechts beperkt gespecificeerd, alleen voor de specificaties die specifiek zijn voor het model waarin ze zijn opgenomen, in dit geval het RGBZ. Voor het overige worden de specificaties overgeërfd van de specificatie in het andere model, v.w.b. ZAAKTYPE dus het ImZTC. En daarin is van alles gespecificeerd over materiele en formele historie wat dus ook van toepassing is op het RGBZ. 

> Het MIM ken ik, daarin vind ik de termen SIM en UGM niet terug. Een document waarin staat dat de SIM een Conceptueel Informatiemodel betreft, en een UGM een Logisch Informatiemodel - een dergelijk document bestaat vast wel? 

Ik heb even gezocht. Kan het zo 1-2-3 niet vinden. Moet er zijn of komen. Ga ik achterheen. Je vertaling klopt in ieder geval.

> Immers ook in de inleiding van RGBZ specificatie staat niet dat het een Conceptueel Informatiemodel betreft.

Dit is een voorlopige rapportage, nog niet de formele zoals in de inleiding vermeld staat. De rapportage is juist gepubliceerd om snel in de behoefte van dit project te voorzien. Aan de formele rapportage wordt gewerkt. Daar komt één en ander wel in te staan.

> Heb vooral een hoop vragen bij de afwegingen rond het modelleren van het Conceptueel Model. Dit issue is echter niet de juiste plek - maar als er een document is waarin e.e.a. nader wordt toegelicht, heel graag.

Als je vragen gaan over het conceptueel modelleren op zich, dan moeten we daar een keer voor gaan zitten. Als ze gaan over RGBZ2 dan hebben we daar een [vragen- en discussieplatform](https://discussie.kinggemeenten.nl/discussie/gemma/rgbz) voor.

**Comment by joeribekker** [comment]
Voor mij is dit issue nu helder. De delen die overlappen worden verwijderd. Middels linked data komen deze modellen bij de bron te zitten.

Ik sluit het issue niet zodat @ArjanKloosterboer en @ehotting hun vragen aan elkaar kunnen beantwoorden.

**Comment by Hugo-ter-Doest** [comment]
Volgens mij kan deze dicht. Wordt opgelost met linked data.
