### ISSUE TITLE
Epic: Als medewerker informatiebeheer wil ik dat de ZDS API's het mogelijk maken om archiefbeheer conform NEN2082 uit te voeren

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#674]
zodat we als gemeenten aan de archiefvereisten voldoen (recordmanagement/overbrenging) en bijvoorbeeld vervanging mogelijk wordt.

**toelichting*
Het gaat er niet om dat de API's zelf record management functionaliteit moet bevatten maar de door middel van de API's moet wel alle informatie opgehaald kunnen worden om record management / overbrenging op de juiste manier toe te kunnen passen.
Heeft relatie met: #364

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
Opdelen in user stories wat staat er dan allemaal in de NEN2082?

**Comment by Hugo-ter-Doest** [comment]
Naar verwachting zal niet alles uit NEN2082 van toepassing zijn. Analyse van relevante eisen is nodig.

**Comment by Hugo-ter-Doest** [comment]
Er worden user stories aangemaakt per paragraaf van functionele eisen.
