### ISSUE TITLE
Als leverancier wil ik weten waar en wanneer de Sprint Reviews van ZDS 2.0 gehouden worden

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/gemma-zaken#678]
...zodat ik tijdig mijn agenda hiervoor kan vrijmaken.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@basretera Hierbij de voorlopige data voor 2019 maar ga er maar vanuit dat het definitief is. Info op site volgt nog.


Demo Data (tijdstip ochtend)
Sprint 8 | donderdag 31 januari 2019
Sprint 9 | donderdag 28 februari 2019
Sprint 10 | donderdag 28 maart 2019
Sprint 11 | donderdag 25 april 2019
Sprint 12 | donderdag 23 mei 2019
Sprint 13 | donderdag 20 juni 2019
Sprint 14 | donderdag 18 juli 2019
