### ISSUE TITLE
Als vakapplicatie wil ik een gefilterde lijst van zaken kunnen ophalen uit het ZRC...

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#68]
...zodat dat ik deze kan weergeven.

_Onderdeel van feature(s): #42, #43, #48_

**Acceptance criteria**
* Filteren op zaaktype
* Filteren op lokatie
* Filteren op behandelaar

**Comment by jgortmaker1** [comment]
welke gegevens wil je ophalen?

**Comment by TCIMEddy** [comment]
@ehotting Is deze wat jou betreft voldoende omschreven?

**Comment by ehotting** [comment]
Was oorspronkelijk "Water" en is "DSO" aan toegevoegd. Denk dat het goed is deze eerst vanuit "Water" op te pakken, wanneer wordt geprioriteerd vanuit Amsterdam.

**Comment by michielverhoef** [comment]
Deze userstory is ook van toepassing voor #1 

Alleen moet dan gefilterd kunnen worden op (BSN van) initiator  en/of betrokkene

**Comment by joeribekker** [comment]
Deze User Story is te breed.

De acceptatie criteria impliceren complexe zaken per punt. Wellicht 1 filter per User Story gaan maken tenzij hetzelfde "soort" (direct veld, relatie veld, linked data veld, geo) filter gebruikt kan worden

* Filteren op zaaktype -> Dit is filteren op linked data. Moet ook nog specifieker gemaakt worden: zaaktype code, omschrijving, oid? En kan dat?
* Filteren op lokatie -> Impliceert filteren op geografische queries. 
* Filteren op behandelaar -> Is een filter op een relatie (eventueel zelfs polymorphisch)

De genoemde "features" (andere user stories) zijn denk ik beter en moet deze user story gewoon weg.

**Comment by TCIMEddy** [comment]
@ehotting Zie commentaar van @joeribekker dus wat mij betreft close!
