### ISSUE TITLE
Dode link op https://ref.tst.vng.cloud/

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#686]
# Bug

De URL op https://ref.tst.vn.cloud naar de API index is dood / verwijst nog naar een oude locatie.
![image](https://user-images.githubusercontent.com/39768984/50558998-e67bc200-0cf2-11e9-86ea-b4fd7a9394e4.png)

Juiste locatie moet zijn:
https://ref.tst.vng.cloud/standaard/apis/index

**Comment by sergei-maertens** [comment]
Nieuwe image gebuild & deployed in 1ffd080c9cc4f7b8515b57071b44afc0e95f1c5c
