### ISSUE TITLE
Als Leverancier/gemeente wil ik een zaaktype kunnen opvragen zonder catalogus op te hoeven geven

### ISSUE THREAD

**Issue by shazada** [VNG-Realisatie/gemma-zaken#687]
# Improvement Story

Nu is het proces zo dat je altijd een catalogus moet hebben waaronder een zaaktype valt.
Dat is voor registratie zeker van belang, echter bij opvragen is dat dubbel werk dat je eerst de lijst met catalogi ophalen en vervolgens de juiste zaaktype.

Dat zijn 2 calls, terwijl je dit ook met 1 call kunt doen en filter client-side kunt toepassen of filtering mee kunt geven.

Nu wordt dit component enkel in cluster Sociaal gebruikt en er is gekozen voor 1 catalogus. Uiteraard kan de uuid hardcoded ergens opgeslagen worden om dit te versimpelen, maar dat is een kromme oplossing :).

[assign aan teamlid en voeg label 'improvement story' toe]

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Graag prio en visie

**Comment by michielverhoef** [comment]
Volgens mij is dit met het platslaan van de catalogi api al bereikt: zaaktype is een resource die nu rechtstreeks te benaderen is zonder dat er eerst een bovenliggende catalogus moet worden aangegeven. Toch, @joeribekker, @sergei-maertens ?
