### ISSUE TITLE
Als gemeente wil ik duidelijke afspraken hebben over het in een community beheren van de standaard

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#69]
zodat er geen onduidelijkheid is over wie wat en wanneer moet doen

**Comment by ehotting** [comment]
Belangrijk, maar ik denk dat we nog een sprint ervaring moeten doen alvorens te poging dit op te schrijven.

**Comment by Hugo-ter-Doest** [comment]
Eerste ervaringen en voorzet voor de afspraken kunnen hier. Beheerteam moet het daarna overnemen. Ik laat hem nog openstaan.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest ik zou deze toch op close zetten (te algemeen)
