### ISSUE TITLE
Als teamlid wil ik iets doen met Zaak.duurVerlenging...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#690]
...zodat de client minder werk heeft om gegevens af te leiden.

Een zaak kan een verlenging hebben van een bepaalde duur (uitgedrukt in werkdagen). Ik vraag me af hoe dit tot uiting komt - is het de bedoeling dat bij het zetten van de duur verlenging ook de ZAAK.einddatumGepland bijgewerkt wordt? Of kunnen we een berekend, alleen-lezen attribuut toevoegen die het resultaat is van `ZAAK.einddatumGepland + Zaak.verlenging.duur` bijvoorbeeld?

Dit moet getoetst worden tegen de betekenis van het informatiemodel - ik heb namelijk geen idee of dit ook maar iets met de geplande einddatum te maken heeft of niet.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat je de einddatum geplande opnieuw moet berekenen. Als je daarna weer zaken filtert op deze einddatum krijg je de goede set zaken terug. In de zaakhistorie kun je altijd terugzien wannneer de zaak verlengd is met hoeveel dagen.

**Comment by sergei-maertens** [comment]
@Hugo-ter-Doest waar kunnen we terecht om dit te bevestigen? Is dit ook wat er bij Atos gebeurt?

**Comment by Hugo-ter-Doest** [comment]
via slack beantwoord.

**Comment by sergei-maertens** [comment]
Conclusie: `einddatum` en `einddatumGepland` bijwerken met het aantal dagen.
