### ISSUE TITLE
Hoe zien zaakkenmerken eruit?

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#693]
Een zaak kent kenmerken, wat de identificatiegegevens moeten zijn van een zaak in andere administraties.

Ik vraag me af hoe dat er concreet uitziet in StUF, en of het nog relevant is in een common-ground gedachte van data bij de bron. Daarom dus de gemeenten als assignee aangeduid om deze input te verzamelen. Mogelijks kan dit geschrapt worden, of is er hier nog ruimte voor verdere standaardisering op de inhoud.

**Comment by michielverhoef** [comment]
Ik heb geen idee of dit ook echt zo gebeurt maar ik kan me voorstellen dat bijvoorbeeld een aanvraag voor een parkeervergunning in een afhandelapplicatie vastgelegd wordt en van daaruit als zaak aangemaakt wordt. Die vastgelegde aanvraag heeft dan in de afhandelapplicatie een identificatie gekregen, dat is niet de zaakidentificatie maar iets anders. Zo'n identificatie kan dan in een kenmerk opgeslagen worden.

Dit voorbeeld staat in het STP, bericht geefZaakdetails:
			<ZKN:kenmerk>
				<ZKN:kenmerk>13113</ZKN:kenmerk>
				<ZKN:bron>KING</ZKN:bron>
			</ZKN:kenmerk>

Dit is natuurlijk vanuit de gedachte dat een afhandelapplicatie alles intern opslaat en bij wijzigingen een afslag maakt naar het ZS. Of dit nog nodig gaat zijn hangt af van de afhandelapplicaties, of die hun gegevens zelf nog lokaal opslaan of niet.

**Comment by sergei-maertens** [comment]
@michielverhoef 
> Ik heb geen idee of dit ook echt zo gebeurt maar ik kan me voorstellen dat... [knip]

Dat is dus problematisch - als systemen met elkaar moeten kunnen communiceren moeten we echt weten hoe dit eruit (gaat) zie(n)(t) :wink: 

@EdwinCoster volgens RGBZ:

> Dit groepsattribuut beschrijft identificerende gegevens waaronder de zaak in
> andere administraties is opgenomen. Aangezien de zaak in meerdere andere
> administraties kan voorkomen, kan deze gegevensgroep meerdere malen
> voorkomen. Het betreft een groepattribuutsoort dat bestaat uit de volgende
> attribuutsoorten: - Kenmerk - Kenmerk bron

Ik heb het hier dan eigenlijk vooral moeilijk met "Aangezien de zaak in meerdere andere administraties kan voorkomen," - dit hoort niet te gebeuren in een common-ground gedachte namelijk.

**Comment by michielverhoef** [comment]
In een vakapplicatie (zaakafhandelcomponent)  worden gegevens opgeslagen die nodig zijn voor het afhandelen van datgene wat leidt tot een zaak (bijvoorbeeld een aanvraag/verzoek of een melding). Lang niet alle gegevens komen in een zaak terecht, kijk maar naar de melding wateroverlast.  De zaak is een afslag van zaakgegevens, niet de bron waarop de afhandeling van die zaak gebeurt.

Zo heel gek is het in dat licht niet dat in de zaak de identificatie en het afhandelsysteem bekend is.

Als je heel strikt zou redeneren kan in de common-ground gedachte het ZRC eigenlijk niet, die gegevens (en meer) staan immers al in de vakapplicatie.  Een ZRC zou dan eerder een virtueel systeem zijn wat als een soort broker bij afhandelcomponenten zaken op kan vragen.  Glad ijs ...
;-)

**Comment by EdwinCoster** [comment]
@sergei-maertens: Ik ben het met je eens. Ik ging er eigenlijk al vanuit dat dit alleen een relatie betreft en niet een kopie van de zaak in een andere administratie. Die kopie is niet (meer) nodig/gewenst. En relaties worden anders gemodelleerd.

In een eerder stadium is (in de reviews van het architectuurverhaal) geconcludeerd dat de ZAC (Procesapplicatie, Afhandelapplicatie) moet weten welke API's aangesproken moeten worden, voor welke gegevens en in welke volgorde. Dus als er al een plek is waar 'kenmerken' uit andere registraties worden bijgehouden, dan is het daar en niet in de ZRC.

**Comment by sergei-maertens** [comment]
Ooooh, dus je zou prima als kenmerk kunnen opnemen dat het een `MOR` is, met als ID `12345` bijvoorbeeld?

**Comment by EdwinCoster** [comment]
Zie ook #153, #237 en #313.

**Comment by sergei-maertens** [comment]
@EdwinCoster thanks, deze details had ik over het hoofd gezien, maar wist wel dat het toegevoegd was voor Delft!

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat het werken met kenmerken niet aansluit bij het werken met resources en uri's. We hebben eerder gezegd dat alle business objecten ook uitgewerkt gaan worden. Denk aan melding, aanvraag, etc. Vanuit de zaak kun je dan met een relatie "heeft betrekking op ander zaakobject" verwijzen naar een ander object. Ander zaakobject is bedoeld voor alle objecten buiten RSGB en RGBZ.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Wat is hier dan het gevolg van/voor. Moet er nog iets gebeuren of kan deze op close

**Comment by Hugo-ter-Doest** [comment]
Ik sluit hem.

**Comment by sergei-maertens** [comment]
Prima om te sluiten. Voorlopig zit het nog in de API, maar ik heb in https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/commit/8ab266bc8fb8599065e5c98e57c8cbc50c5442a1 wel de API-documentatie bijgewerkt die aangeeft dat je eigenlijk URL-referenties zou moeten gebruiken.
