### ISSUE TITLE
Betekenis van ZAAK.selectielijstklasse als URL-referentie?

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#694]
# Vraag

Wat is de betekenis van `ZAAK.selectielijstklasse`? RGBZ maakte dit voor mij niet duidelijker. In #549 staat deze gemarkeerd als URI-referentie, maar naar wat voor registratie?

**Comment by Hugo-ter-Doest** [comment]
Dat is de selectielijstklasse voor het bepalen van de bewaartermijn van een zaak. We gaan ervan uit dat op termijn de gemeentelijke selectielijst ook via een API is te benaderen. Voorlopig dus oplossen met de ORC.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Moet hier dan nog iets mee gebeuren of kan deze ook op close?

**Comment by Hugo-ter-Doest** [comment]
Dat kan @sergei-maertens beter aangeven.

**Comment by sergei-maertens** [comment]
Iets in ORC dus for the time being - vraag beantwoord! Ik zal naar ImZTC kijken als ik het in ORC bouw dan. Dan komen er vast meer vragen, maar dat zie ik dan wel weer.
