### ISSUE TITLE
Als medewerker wil ik een document kunnen ontkoppelen uit een zaakdossier

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#696]
...zodat het dossier geen documenten bevat die niets (meer) met de zaak te maken hebben.

NB. Dit is noodzakelijk voor #21 

Toelichting:
Het gaat hier om ontkoppelen van de zaak, niet om verwijderen van informatieobject zelf.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Thanks!

**Comment by CMasselink** [comment]
En dit moet ook kunnen bij een reeds afgesloten zaak (vaak door een record manager), zie ook #409

**Comment by TCIMEddy** [comment]
het kan!

**Comment by sergei-maertens** [comment]
Hoe? Zo: https://ref.tst.vng.cloud/drc/api/v1/schema/#operation/objectinformatieobject_delete
