### ISSUE TITLE
Als gemeente wil ik autorisatie op informatieobjecttype  die niet aan een zaak zijn gekoppeld inrichten op basis van Informatieobjecttype en VA in de DRC

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#699]
...zodat deze informatieobjecten niet vrijelijk toegankelijk zijn en gewijzigd kunnen worden.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by michielverhoef** [comment]
Is deze userstory van toepassing voor standaarden juist opgezet zijn om zaakgericht werken te ondersteunen?

Voor je het weet moet alles kunnen en is de scope ineens enorm opgerekt.

**Comment by joeribekker** [comment]
Demo: Toegang tot document geweigerd :)

**Comment by Hugo-ter-Doest** [comment]
> Is deze userstory van toepassing voor standaarden juist opgezet zijn om zaakgericht werken te ondersteunen?

> Voor je het weet moet alles kunnen en is de scope ineens enorm opgerekt.

Strikt genomen niet noodzakelijk voor ZGW inderdaad, maar informatieobjecten worden eerst geregistreerd zonder koppeling met een zaak, en je kunt straks informatieobjecten ontkoppelen van een zaak. En dan moet de toegang tot een informatieobject ook worden geautoriseerd.
