### ISSUE TITLE
Als medewerker wil ik een klantcontact kunnen registreren

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#7]
zodat de vraag of verzoek van de klant (burger of bedrijf) opgevolgd kan worden.

Secundair: analyse van klantcontacten (BI).

**Comment by michielverhoef** [comment]
Als persoon of vertegenwoordiger voer je geen klantcontacten op, dat doet een (KCC) medewerker.

**Comment by PDG65** [comment]
Todo:
- nieuwe API set aanmaken 
- API resource maken voor contactmoment (=klantcontact)
- CI opzetten (Travis)
- API documenteren

**Comment by EdwinCoster** [comment]
Deze user story leidt tot een wijziging van het gegevensmodel.

**Comment by joeribekker** [comment]
Nieuwe (lege) API is opgezet:

API specificatie (tot nu toe):
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-klantcontactcomponent/3ceefd469ba3646ec62c6220e1b054a06dc0f503/src/openapi.yaml

Referentie implementatie (code):
https://github.com/VNG-Realisatie/gemma-klantcontactcomponent
