### ISSUE TITLE
Hoofzaaktypen vs. deelzaaktypen - inconsistentie in informatiemodel?

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#700]
# RGBZ vs. ImZTC

**Gegeven**:

* (hoofd)zaken kunnen deelzaken hebben
* cfr. RGBZ kan een deelzaak zelf geen verdere deelzaken hebben
* zaken moeten van een bepaald zaaktype zijn
* ImZTC kent zaaktypes en deelzaaktypes

**Probleem**

Volgens de kardinaliteit in [ImZTC](https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/relatiesoort/zaaktype.is_deelzaaktype_van_zaaktype) kan een zaaktype meerdere deelzaaktypen hebben, en een deelzaaktype kan dus ook bij meerdere zaaktypes horen.

Ik zie echter geen regel die voorschrijft dat een hoofzaaktype deelzaaktypen kan hebben en dat het niet kan dat een deelzaaktype zelf deelzaaktypen heeft. Met de kardinaliteit is dit wel mogelijk.

Naar mijn gevoel moeten deze regels ook gelden/vermeld worden:

* een deelzaak moet als zaaktype een zaaktype hebben dat een deelzaaktype is van het hoofdzaaktype
* deelzaaktypen kunnen geen deelzaaktypen hebben

Het lijkt me namelijk vreemd dat een zaaktype zou aangemerkt staan als deelzaaktype van een ander zaaktype, en dat je daar een hoofzaak van kan maken. In de context van het sturen van processen zou ik verwachten dat je altijd vertrekt van een hoofdzaak die een hoofdzaaktype is, en daar mogelijks deelzaken uit volgen om het af te handelen. Of kan je vertrekken van deelzaaktypen?

**Comment by michielverhoef** [comment]
De deelzaken kunnen op hun beurt ook gewoon als enkelvoudige zaak (dus zonder deelzaken of hoofdzaken) bestaan.  Deelzaken hebben dan ook een begin, behandeling en einde.  

Bijvoorbeeld het aanvragen van een paspoort. Je kunt als inwoner alleen maar een paspoort aanvragen dat is dan een enkelvoudige zaak (deze term is overigens ter plekke verzonnen dus geen onderdeel van RGBZ of een standaard oid). Maar het aanvragen van een paspoort kan ook onderdeel zijn van een groter geheel en dan een deelzaak worden.

Of een meer abstract voorbeeld: het wegzetten van een boek in de boekenkast. Dit kun je uitvoeren als onderdeel van het opbergen van een nieuw aangeschaft boek of als onderdeel van het opruimen van je huis. Dan is het wegzetten van een boek een deelzaak van het grotere geheel opruimen van je huis. 
Hopelijk slaat dit voorbeeld een beetje ergens op :-)

**Comment by Remkodehaas** [comment]
Ik denk er het volgende over (op dit moment):
1.	Een zaak start bij een hoofdzaak.
2.	Een deelzaak kan alleen bestaan als er een hoofdzaak is
3.	Volgens de ZTC ‘OD Haaglanden’ kan een zaaktype ook een deelzaak zijn van een andere (hoofd)zaaktype. Zie hiervoor zaaktype ‘Zienswijze behandelen’ (zie o.a. par.3.16, pagina 138) in de bijlage.
4.	Volgens imZTC kan een deelzaak weer andere deelzaken hebben. 
Ik vraag me wel af in hoeverre dat werkelijk in de praktijk wordt gebruikt, ik heb namelijk geen idee
5.	De veronderstelling: “een deelzaak moet als zaaktype een zaaktype hebben dat een deelzaaktype is van het hoofdzaaktype” klinkt me logisch in de oren.

[OD Haaglanden - Zaaktypecatalogus v1.0 - 20120210.pdf](https://github.com/VNG-Realisatie/gemma-zaken/files/2782410/OD.Haaglanden.-.Zaaktypecatalogus.v1.0.-.20120210.pdf)

**Comment by michielverhoef** [comment]
Voor de liefhebbers nog wat leesvoer: https://www.gemmaonline.nl/index.php/Hoofd-_en_deelzaken_en_gerelateerde_zaken

**Comment by Hugo-ter-Doest** [comment]
Deelzaken kunnen geen deelzaken hebben volgens RGBZ:  zie RGBZ Concept versie 20180613, deel II, 2.18.35 - Relatiesoort is deelzaak van (met dank aan @sergei-maertens). De regels die Sergei in het issue noemt zijn prima!

**Comment by Remkodehaas** [comment]
van Sergei:
Naar mijn gevoel moeten deze regels ook gelden/vermeld worden:

* deelzaaktypen kunnen geen deelzaaktypen hebben
* een deelzaak moet als zaaktype een zaaktype hebben dat een deelzaaktype is van het hoofdzaaktype

Het lijkt me namelijk vreemd dat een zaaktype zou aangemerkt staan als deelzaaktype van een ander zaaktype, en dat je daar een hoofzaak van kan maken. In de context van het sturen van processen zou ik verwachten dat je altijd vertrekt van een hoofdzaak die een hoofdzaaktype is, en daar mogelijks deelzaken uit volgen om het af te handelen. Of kan je vertrekken van deelzaaktypen?

------
reactie:

- Mij lijkt het vertrekpunt een hoofdzaak. 
- deelzaaktypen kunnen geen deelzaaktypen hebben:  -->  laten gemeenten en leveranciers maar weten als dit werkelijk wel nodig is. 
- een deelzaak moet als zaaktype een zaaktype hebben dat een deelzaaktype is van het hoofdzaaktype: prima, met de **aanvulling** dat die betreffende deelzaaktype ook: 1.) ook een zaaktype kan zijn en 2.) een deelzaaktype van een ander hoofdzaaktype kan zijn.

zie mijn eerdere opmerking 3.: 
3\. Volgens de ZTC ‘OD Haaglanden’ kan een zaaktype ook een deelzaak zijn van een andere (hoofd)zaaktype. Zie hiervoor zaaktype ‘Zienswijze behandelen’ (zie o.a. par.3.16, pagina 138) in de bijlage.

Misschien is het dan handiger om de relatie om te draaien (?): een zaaktype heeft 0 of meerdere deelzaaktypen

**Comment by michielverhoef** [comment]
>Het lijkt me namelijk vreemd dat een zaaktype zou aangemerkt staan als deelzaaktype van een ander zaaktype, en dat je daar een hoofzaak van kan maken. In de context van het sturen van processen zou ik verwachten dat je altijd vertrekt van een hoofdzaak die een hoofdzaaktype is, en daar mogelijks deelzaken uit volgen om het af te handelen. Of kan je vertrekken van deelzaaktypen?


Als het op deze manier formuleert heb je in feite twee soorten zaaktype: een zaaktype en een deelzaaktype. Die verschillen in die zin dat een zaaktype 0 of meerdere deelzaaktypen kan hebben en een deelzaaktype niet.

Ik zou verwachten dat een hoofdzaak alleen geinteresseerd is in de uitkomst van de deelzaak. Of die deelzaak om dit te bereiken onderverdeeld is in deelzaken maakt voor de hoofdzaak niet uit. Dus techisch gesproken is het heel goed mogelijk dat een deelzaak op zijn beurt weer een hoofdzaak met eigen deelzaken is.

Daarnaast, een deelzaak kan ook als zelfstandige zaak uitgevoerd worden. In dat geval is de beperking dat het bewuste zaaktype geen deelzaken mag hebben niet van toepassing. Wordt de regel dan slectief toegepast? Wanneer een zaaktype als deelzaaktype uitgevoerd wordt mag dit zaaktype geen deelzaaktypen kennen, wanneer een zaaktype niet als deelzaaktype uitgevoerd wordt mag dit zaaktype wel deelzaaktypen kennen. 

Volgens mij is het vrij simpel: een zaaktype kan zowel een zelfstandig uit te voeren zaaktype als een deelzaaktype zijn. In beide gevallen kan dat zaaktype dan deelzaaktypen hebben. Al is het voor de overzichtelijkheid misschien wel beter om niet tot in het oneindige te nesten.

**Comment by Hugo-ter-Doest** [comment]
Op type-niveau: een zaaktype dat deelzaaktype is, kan zelf ook weer hoofdzaaktype zijn van andere deelzaaktypen. Op instantie-niveau: moet je voorkomen dat deelzaken weer deelzaken krijgen.

@Remkodehaas Ik vind het ook een goed idee de relatie van hoofdzaaktype naar deelzaaktype te leggen.

@sergei-maertens weet je nu voldoende om het te implementeren?

**Comment by michielverhoef** [comment]
> Op type-niveau: een zaaktype dat deelzaaktype is, kan zelf ook weer hoofdzaaktype zijn van andere deelzaaktypen. Op instantie-niveau: moet je voorkomen dat deelzaken weer deelzaken krijgen.

Dan begrijp ik voorzichtig: wanneer een deelzaak (A) weer eigen deelzaken (B) krijgt kun je dit oplossen door die deelzaken (B) rechtstreeks deelzaken van de hoofdzaak worden. Dan heb je in de praktijk geen problemen.

Of zie ik het verkeerd?

**Comment by Hugo-ter-Doest** [comment]
Misschien dat we dat later toevoegen als er behoefte aan is. Voor nu kan/mag het niet.

**Comment by adgerrits** [comment]
Zonder pretentie dat het in deze context het slimst is (er hoeft dus ook niks mee te gebeuren...) mijn visie op het vraagstuk. Ik probeer bij modelleren altijd zo dicht mogelijk bij de werkelijkheid te blijven. Volgens mij komen daar alle genoemde varianten voor (ook dingen als dat een deelzaak als eerste ontstaat of dat deelzaken weer deelzaken kennen). In een model zou ik dan ook zo min mogelijk beperkingen opnemen. Waar het model overigens ook een stuk eenvoudiger van wordt. Hier bijv.: je hebt zaken en daar kan (oa) een 'is deelzaak van' relatie tussen bestaan.
