### ISSUE TITLE
Als user/stakeholder wil ik naast de API-standaard ook inzicht in het onderliggende gegevensmodel 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#701]
...zodat ik dit kan gebruiken.

Toelichting:
Als leverancier wil ik documentatie waarin wordt uitgelegd hoe de resources aan elkaar gerelateerd zijn en welke calls ik na elkaar moet doen om objecten aan te maken (en relateren aan andere)

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest @wishalg @Hugo-ter-Doest graag hier jullie visie t.a.v. informatiemodellen etc.

**Comment by Remkodehaas** [comment]
Ik ben nieuw in het team en ik heb nog geen goed beeld wat onze eindproducten (zullen) zijn. Daar hoop ik snel een beeld van te hebben. Het gebruik van de eindproducten/API-standaard staat voorop.
Vul onderstaande gerust aan.

**Wat beschrijven met het (informatie)model?**
- Welke objecttypen er zijn met en onderlinge relaties.
- Welke eigenschappen (attributen) bij de objecttypen horen
- diagram(men) van objecttypen met en zonder attributen
- mogelijk een toelichting op het model.

**Hoe?**     
online, pdf/Word/Odt(?), mogelijk nog andere formaten
 
**Uitgangspunten/stelling** (waarop geschoten kan worden): 
- Leggen  zoveel mogelijk vast bij de eind-producten (of standaard) en dat is bij de API. Bij het eindresultaat is de API zoveel mogelijk de bron voor het (informatie)model.
- Wat er aan extra informatie nodig is voor het (informatie)model zal op een andere manier worden vastgelegd. Dit kan gaan om bepaalde eigenschappen van objecttypen en de onderlinge relaties 
- Er is ook behoefte aan visuele overzichten (diagram) met de objecten en de onderlinge relaties
- Het (informatie)model hoort bij de API, maar is geen standaard op zichzelf. Het is een hulpmiddel om tot de standaard te komen en een weergave van de objecttypen. Het project gaat dus Rgbz en imZtc niet aanpassen. In de toekomst worden de (ZGW)API’s doorontwikkeld en het bijbehorende (informatie)model aangepast. Rgbz en imZtc zijn bronnen daarvoor. 
- Bij de oplevering van de API moet ook gemotiveerd worden welke keuzes er zijn gemaakt t.a.v. bestaande versies van Rgbz en imZtc. Dit gebeurt in de API-documentatie en niet bij het (informatie)model.

**Onderzoeksvragen:**
1. Wat kan/wordt er vastgelegd in de API en wat zou in een informatiemodel moeten worden gehouden?
1. Wat willen we in het (informatie)model terug laten komen aan extra informatie over de objecten, de  attributen en de relaties, die in de API ontbreekt? * Is het ook nodig dat we het zo uitgebreid doen als bij Rgbz?
1. Hoe kunnen we informatie uit de API in het (informatie)model krijgen?
o	Export?
o	Is het nodig dat er een relatie is tussen de API en het (informatie)model? En zo ja: hoe realiseren we dat?
o	Welke tool?      Diagrammen / Vng gebruikt nu Sparx / Moet het (informatie)model ook in een herbruikbare format beschikbaar worden gesteld, zodat andere organisaties er mee aan de slag kunnen? / Is het handig om objecten met definities met bijv. LOD te publiceren?

**Comment by TCIMEddy** [comment]
@Remkodehaas Dank! Mooi start en houvast om feedback op te geven

**Comment by jeffreygortmaker1** [comment]
heel belangrijk. Als de standaard af is, moet er ook een bijgewerkte versie van het RGBZ zijn. Of een RGBZ light. Waarschijnlijk opgeknipt in verschillende modellen: per API één, met onderlinge relaties.

Niet te onderschatten. Wel belangrijk, want anders leveren wij straks een API die niet klopt met het actuele informatiemodel (nu RGBZ 2.0). En dat is een goede reden om nog niet te beginnen met implementeren. Die moeten we dus wegnemen...

**Comment by TCIMEddy** [comment]
@jeffreygortmaker1 Deze sprint leveren we igg methode op en maken er een start mee. Het informatiemodel (in welke vorm dan ook) is onderliggend 'hulpmiddel' van de API-standaard. En als ik het niet goed zeg wordt in ongetwijfeld verbeterd.

**Comment by jeffreygortmaker1** [comment]
tsja...ik vrees dat heel veel leveranciers en gemeenten dat nog anders zien en een API als implementatie van het informatiemodel zien..

Ik snap de strekking van het plan wel: je kunt niet én een informatiemodel als standaard vaststellen en dan een API bouwen en ook dat als standaard vaststellen...maar dat moeten we dus erg duidelijk communiceren.

Als ik jullie plannen interpreteer misschien wel zo scherp als: we hadden het RGBZ en het ImZTC die zijn nu EOL. En hebben we een API + referentieimplementatie die leidend zijn. En om deze goed te kunnen interpreteren en inbouwen leveren we een (paar) beschrijvend(e) informatiemodel(len) mee...

Maar het lijkt me goed om hier wat meer beelden bij op te halen en af te stemmen. Voor 1/6 moeten we hier echt 100% uit zijn zou ik denken. Ondertussen een goed idee om de methode op te leveren en een start te maken.. Iets voor @wishalg om te organiseren...

**Comment by TCIMEddy** [comment]
@Remkodehaas Ik begrijp uiteraard dat dit nog niet af is maar zou wel goed zijn om dit issue te sluiten en het vervolg als nieuwe user story op te nemen (en dan specifieker zijn met wat nog open staat),

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest kan deze user story op close? basis staat feedback en verbeteringen altijd mogelijk....
