### ISSUE TITLE
Demo sprint 8

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#702]
# Demo Sprint 8 31 januari 2018

Onderwerpen

Inleiding (@Hugo-ter-Doest)
Naamswijziging en 2e tranche (@Hugo-ter-Doest)
Informatiemodellen en bijbehorend proces (@Hugo-ter-Doest @Remkodehaas )
Resultaten sprint 8 (@sergei-maertens @joeribekker)
Roadmap (@Hugo-ter-Doest)
Demo API-testvoorziening (@HenriKorver)
"Demo/tussenstand" Beheer (@melsk-r)
Sluiting (@Hugo-ter-Doest)

ACTIEHOUDERS: Graag updates geven in deze user stories

Coördinatie PO
Zaal en dergelijke
Checklist Demo
alle stakeholders uitgenodigd
juiste stakeholders uitgenodigd
lunch geregeld
voldoende stoelen in zaal
geen geluidoverlast
2 schermen
1 powerpoint/presentatie (samengevoegd)
beamer aanwezig
flipover aanwezig
kabels aanwezig om laptops (ook Apple!) aan te sluiten
wie schrijft mee (met name feedback en acties)
bevat demo mix van kennisoverdracht en daadwerkelijk demonstreren
context geschetst
'show and shine'-element
is demo goede weergave wat er in de sprints is gedaan (of niet gedaan)

**Comment by HenriKorver** [comment]
Mijn laptop geeft geen HDMI uitgang (wel Displayport). Heeft de beamer wel een VGA-aansluiting en is er ook een VGA-kabel?
