### ISSUE TITLE
Als geinteresseerde moet ik de context goed kunnen begrijpen

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#71]
Zodat ik mee kan denken en input kan leveren over de te ontwikkelen producten

**Comment by TCIMEddy** [comment]
@BoerBas @ehotting Moet hier nog wat mee gebeuren of is de context geschetst op GitHub voldoende? Zo ja graag close anders iets beter specificeren.

**Comment by TCIMEddy** [comment]
@ehotting Wordt volgens mij voldoende belicht in andere user stories en is ook aandachtspunt in communicatie en demo's. Ik zet deze op wontfix
