### ISSUE TITLE
Als Informatiebeheerder Delft wil ik een inzageverzoek persoonsgegevens compleet kunnen uitplaatsen naar een e-depot

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#712]
...zodat alle (proces-) informatie duurzaam bewaard wordt.

Zie ook de beschrijving van [het proces](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/overige/processen/Delft%20AVG.md)

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Uit de procesbeschrijving:
Delft test het scenario van uitplaatsing in een e-depot pilot, waarbij zaken nadat ze zijn afgehandeld worden uitgeplaatst bij het e-Depot. Dit betekent dat bij een eventueel bezwaar en beroep het e-Depot informatie uit de originele zaak levert en niet de combinatie ZRC/DRC/Domeinspecifieke gegevens. Delft wil graag onderzoeken wat dit betekent voor de standaard, wat dit betekent voor de ZAC (VJV), of de keuze voor uitplaatsing wel past bij het gebruik van de standaard. Verder komt 'uitgeplaatst' niet voor in de enumeratie voor archiefstatus. Er is wel een archiefstatus voor 'overgedragen', maar of dat fundamentalistisch correct is.

**Comment by Hugo-ter-Doest** [comment]
Wordt opgelost in #376.

**Comment by EdwinCoster** [comment]
Hugo schreef:

> Wordt opgelost in #376 

Dan moet je die (376) wel anders beschrijven denk ik. Bij Informatieobjecten denk ik aan de DRC. En met 'compleet' bedoelen wij alle relevante gegevens en informatie, dus ook uit de registratie voor een specifieke afhandel applicatie of (ander) zaakobject (zoals het Inzageverzoek).

**Comment by Hugo-ter-Doest** [comment]
De aanvullende vragen kun je het beste als afzonderlijke user stories opvoeren.
