### ISSUE TITLE
De huidige implementatie van JWT tokens aan de hand van vertrouwde lijkt datalekken in de hand te werken.

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#713]
# Avg 

Als ik de implementatie van JWT tokens goed begrijp handelt iedere applicatie zelf autorisatie en authenticatie af om vervolgens aan de hand van een certificaat een token te maken waarmee elders informatie wordt opgevraagd.

Maar als ik het goed lees wordt vervolgens bij de tweede applicatie alleen de geldigheid van het token gecontroleerd, er lijkt niet te worden nagegaan bij de vragende applicatie of deze de token ook echt heeft afgegeven? En nog erger er wordt niet nagegaan of de veronderstelde scope klopt voor de betreffende gebruiker.

Daarmee lijkt er een ketting te ontstaan waarbij alle data van de betrokken applicaties in één keer op straat komt te liggen als erg ergens in het ecosysteem bij één applicatie wordt ingebroken en deze technisch geldige (maar autorisatie gezien ongeldige) token afgeeft. Ofwel een fout in de parkeervergunning bij landgraaf kan alle BSN nummers van Groningen op straat doen belanden.     

Zie ik hier iets over het hoofd?

**Comment by sergei-maertens** [comment]
In essentie klopt dit en dat is wat mij ook (persoonlijk) dwars zit - er is geen preventieve controle om te voorkomen dat er te veel data opgevraagd wordt, er is wel een mechanisme voor audits.

Het is wel zo dat applicaties die tokens uitgeven moeten bekend zijn bij de datahouder - op basis van het `client_id` wordt het bijhorende `secret` opvraagd om de geldigheid van het token te kunnen controleren. Indien een applicatie dus niet geregistreerd is bij de databron, dan leidt dit tot een ongeldig token en mag je sowieso niets ontsluiten.

Dat maakt:

> er lijkt niet te worden nagegaan bij de vragende applicatie of deze de token ook echt heeft afgegeven

geen correcte conclusie. Indien er in de vragende applicatie fouten zitten waardoor die incorrecte tokens afgeeft, dan is er inderdaad een dergelijk risico.

> En nog erger er wordt niet nagegaan of de veronderstelde scope klopt voor de betreffende gebruiker.

Op dit moment is dat zo, er is geen check terug naar de gebruiker. Dit zou eisen dat alle organisaties op dezelfde manier een mechanisme instellen om dit te controleren, wat ons niet haalbaar lijkt en flexibiliteit om auth/autz in te richten bij organisaties.

Ik speel wel met het idee om organisaties bij de databron profielen te kunnen laten instellen over wie toegang heeft tot welke data. De 'wie'-gegevens kunnen dan nog steeds in het token opgenomen worden, en dit kan dan bij de databron gematched worden als 'mask' over de gegevens om enkel wat nodig is vrij te geven. Maar dit is op dit moment nog een concept dat enkel in mijn hoofd leeft.

> Daarmee lijkt er een ketting te ontstaan waarbij alle data van de betrokken applicaties in één keer op straat komt te liggen als erg ergens in het ecosysteem bij één applicatie wordt ingebroken en deze technisch geldige (maar autorisatie gezien ongeldige) token afgeeft.

Indien er ingebroken wordt in een applicatie, dan ga ik uit van:

1. aanvaller heeft client IDs bemachtigd
2. aanvaller heeft client secrets bemachtigd

De aanvaller verkrijgt hiermee geen toegang tot databronnen waarvan de applicatie geen gebruik maakt, want client ID + secret zijn daar niet geregistreerd/bekend.

Databronnen zoals ZTC/ZRC communiceren onderling via eigen client IDs + secrets, deze liggen dus niet op straat. Als je client ID & secret van ZRC bemachtigt, krijg je daarmee niet automatisch toegang tot het achterliggend ZTC of DRC.

> Ofwel een fout in de parkeervergunning bij landgraaf kan alle BSN nummers van Groningen op straat doen belanden.

Enkel als die parkeervergunningapplicatie ook een client ID/secret heeft voor de BRP van Groningen, en dat lijkt mij een vreemde configuratie omdat die applicatie daar helemaal geen toegang zou moeten hebben.

Indien zo'n inbraak gebeurtl, dan is het zaak om de client IDs/secrets te roteren - dit invalideert alle bestaande tokens.

Met een opzet waarbij van OAUTH2 gebruik gemaakt wordt bijvoorbeeld heb je nog steeds het principe van scopes, waarbij aangegeven wordt dat je toegang hebt tot pakweg BSNs van Groningen. Een malafide developer kan nog steeds refresh tokens uit de applicatie stelen en ongeautoriseerd deze gegevens opvragen.

Ik onderken dus het probleem, eenmaal je toegang hebt tot de applicatie, dan 'ben je binnen', maar ik zie ook geen voor de hand liggende oplossingen om dat te voorkomen anders dan dat een organisatie zelf hun informatiebeveiliging op orde heeft. In de Common Ground visie van data-bij-de-bron is het zo dat clients toegang hebben tot de datalaag over APIs, en als je zaken via NLX ontsluit, dan heb je daar al een eerste bescherming waarbij je een whitelist van organisaties bijhoudt voor je service. Van een kettingreactie is er volgens mij echter geen sprake, maar ik hoor het graag als ik fout ben, want dit moeten we wel goed doen!

**Comment by joeribekker** [comment]
Denk dat Sergei goed de voor- en nadelen opsomt waar Ruben iets te kort door de bocht gaat.

Voor de volledigheid: Beide partijen, zeg **Pietje** en **mail** hebben zowel het `client_id` als het `secret` nodig om met elkaar te **kunnen** praten. Het `secret` gaat nooit over de (netwerk)lijn, maar het `client_id` wel. Het is dus, net als bij WIFI een pre-shared secret.

> Als ik de implementatie van JWT tokens goed begrijp handelt iedere applicatie zelf autorisatie en authenticatie af om vervolgens aan de hand van een certificaat een token te maken waarmee elders informatie wordt opgevraagd.

Het klopt dat elke applicatie m.b.v. het `client_id` en `secret` een `token` maakt waar bepaalde `scopes` in zitten die hij zelf mag kiezen. 

> Maar als ik het goed lees wordt vervolgens bij de tweede applicatie alleen de geldigheid van het token gecontroleerd, er lijkt niet te worden nagegaan bij de vragende applicatie of deze de token ook echt heeft afgegeven?

Dat klopt, dat zou namelijk best veel netwerk overhead zijn en is en bewuste keuze. Echter, ze zijn beide op de hoogte van het `secret`, dat als bewijs dient.

> En nog erger er wordt niet nagegaan of de veronderstelde scope klopt voor de betreffende gebruiker.

Applicatie A kan wel een bepaalde `scope` meegeven maar dat wil **niet** zeggen dat Applicatie B deze `scope` moet geven. Applicatie B **kan** prima geconfigureerd zijn dat het bewuste `client_id` alleen maar **bepaalde scopes mag hebben**. Op dit moment hebben we die controle echter niet in de standaard opgenomen; en is nog in overweging.

> Daarmee lijkt er een ketting te ontstaan waarbij alle data van de betrokken applicaties in één keer op straat komt te liggen als erg ergens in het ecosysteem bij één applicatie wordt ingebroken en deze technisch geldige (maar autorisatie gezien ongeldige) token afgeeft. Ofwel een fout in de parkeervergunning bij landgraaf kan alle BSN nummers van Groningen op straat doen belanden.

Applicatie A mag bij Applicatie B, en als Applicatie B data uit Applicatie C nodig heeft dan worden deze (middels een pre-shared secret tussen Applicatie B en C) onttrokken t.b.v. het antwoord van B aan A. Het is echter niet zo dat Applicatie A opeens bij Applicatie C kan.

Als iemand het `client_id` en `secret` heeft "gestolen" heeft voor de communicatie tussen A en B dan kan je daar dus inderdaad wat mee. Als bekend wordt dat het secret gestolen is, moeten A en B een nieuw secret afspreken.

**Comment by Hugo-ter-Doest** [comment]
@joeribekker Kunnen jullie bovenstaande analyse toevoegen aan de documentatie? Ik denk in de vorm van een paar stellingen of risico's met een weerlegging dan wel een mogelijke oplossingsrichting. Verder voeg ik dit issue toe aan sprint 11 Autorisatie.

**Comment by joeribekker** [comment]
Volgens Henri moeten we dit ook duidelijk maken in het  sequence diagram ij autorisaties dat hetzelfde JWT van TA naar ZRC niet gebruikt van ZRC naar ZTC. Dit betreft een nieuw JWT op basis van client_id en secret geconfigureerd in het ZRC ten behoeve van het ZTC.

**Comment by rubenvdlinde** [comment]
Nou de kern van het verschil van inzicht zit er denk ik in dat applicaties toegang hebben in de huidige  architectuur ipv van gebruikers. Das nog even een aandachtspunt met betrekking tot AVG logging etc. Maar das een discussie voor elders

De casus hier is dan dus wel dat applicatie A via applicatie B info kan opvragen bij C zonder daar zelf toestemming voor te hebben? Daarmee krijg je wel data boogjes, waarmee je weer data lekken inde hand werkt. Tis ook wat strijdig met de gedachte van linked data waarbij de client zelf verantwoordelijk is voor het doorvragen en verkrijgen van extra data.

Wat is de afweging waarom de oorspronkelijke aanvraag token niet gewoon wordt doorgegeven?

**Comment by sergei-maertens** [comment]
@rubenvdlinde net niet, het is NIET mogelijk dat applicatie A via applicatie B info kan opvragen bij C. A krijgt van B alleen URLs naar C terug, en A is zelf verantwoordelijk voor het opvragen van gegevens bij C. Indien A geen credentials heeft voor C, dan kan je daar dus niet bij.

Applicatie B kan soms gegevens moeten opvragen bij C voor het correcte functioneren, maar die gebruikt eigen credentials, en die gegevensstroom stopt bij B en sijpelt niet door naar A.

Je moet dit wel zien in combinatie met de API specificatie. Theoretisch gezien kan B inderdaad een response van C embedden in het antwoord naar A, maar dan volg je niet langer de OAS en ben je sowieso als applicatie B niet compliant met de standaard.

**Comment by sergei-maertens** [comment]
> Das nog even een aandachtspunt met betrekking tot AVG logging etc. Maar das een discussie voor elders

Dit is precies waarvoor NLX en doelbinding bestaat toch?

> Wat is de afweging waarom de oorspronkelijke aanvraag token niet gewoon wordt doorgegeven?

We willen dat je enkel maar de scopes meegeeft die enkel nodig zijn voor dat specifieke verzoek. We willen ook dat in audits duidelijk is dat een data-verzoek niet door een gebruiker gebeurde, maar door systeem-systeem, en we willen voldoende flexibiliteit hebben om client IDs/secrets te kunnen revoken. Token doorgeven zou namelijk betekenen dat de taakapplicatie met zelfde client_id + secret bij API B en API C bekend staat, wat credential-hergebruik is, en geen best practice security-wise.

**Comment by rubenvdlinde** [comment]
> @rubenvdlinde net niet, het is NIET mogelijk dat applicatie A via applicatie B info kan opvragen bij C. A krijgt van B alleen URLs naar C terug, en A is zelf verantwoordelijk voor het opvragen van gegevens bij C. Indien A geen credentials heeft voor C, dan kan je daar dus niet bij.
> 
> Applicatie B kan soms gegevens moeten opvragen bij C voor het correcte functioneren, maar die gebruikt eigen credentials, en die gegevensstroom stopt bij B en sijpelt niet door naar A.
> 
> Je moet dit wel zien in combinatie met de API specificatie. Theoretisch gezien kan B inderdaad een response van C embedden in het antwoord naar A, maar dan volg je niet langer de OAS en ben je sowieso als applicatie B niet compliant met de standaard.

Kijk, dan zitten iedereen :) Zo lang iedereen een data verwijzing doet ipv embed komt het goed. Om een of andere reden had ik in mijn hoofd zitten dat er wel data werd embed. Enfin. helder nu waarvoor dank.

> Dit is precies waarvoor NLX en doelbinding bestaat toch?

Yup, maar de vraag is of we ver genoeg gaan ;)

Laatste keer dat ik er naar keek (en ik ga nu iets zeggen zonder de docs te hebben gepakt) houden we bij welke organisaties voor welk doel gegevens hebben opgevraagd in de NLX logs. Thats nice en conform huidige specs. 

Maaaaaaaaaaaaaar er zijn precedenten aan het ontstaan waarbij er ook moet worden gelogd op welke personen data opvragen. (mooie casus in het ziekenhuis van Utrecht laatst) en dan wordt die ingewikkeld. Omdat we via verschillende systemen een bron benaderen wordt het lastig om op systeem niveau misbruik vast te stellen (het misbruik van een gebruiker kan over systemen verdeeld zijn waardoor het wegvalt tegen natuurlijke ruis) Je zou dit kunnen tacklen door het raadpleeg log bij de bron op te vragen en daarna alle raadplegers logs te laten inleveren maar das in de complexiteit van NL niet echt  handmatig te doen. En er was dacht ik ook nog geen standaard voor logs aan de vraagzijde? En dan is het nog maar de vraag waarop je een gebruiker uniek kan maken over meerdere systemen.  Etc etc

Op termijn moeten we die vraag op NLX niveau wel kunnen beantwoorden (via welke systeemen heeft ambtenaar x allemaal gegevens over persoon y geraadpleegd). En dat geautomatiseerd kunnen doen. Daar zitten volgensmij nog wat haken en ogen aan waar we nog niet over hebben nagedacht. Maar wat voorbij gaat aan deze discussie. En vervolgens komt ook de privacy van Ambtenaren weer in beeld en dan wordt het weer mee beleid dan technisch.

**Comment by TCIMEddy** [comment]
Volgens mij zit iedereen weer op dezelfde golflengte dus ik sluit deze. Mocht ik het verkeerd hebben dan wordt het weer geopend.
