### ISSUE TITLE
Als medewerker IB wil ik dat bestanden conform de NEN 2082 (par. 6.3) beheerd, onderhouden en gevolgd kunnen worden

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#727]
NEN 2082:

> Voorwaarden
> 
> In het geval van digitale archiefstukken moet er een lijst zijn van (versies van) toegelaten bestandsformaten die regelmatig moet worden onderhouden. De lijst is bedoeld om ‘nieuwe’ bestandsformaten toe te laten. ‘Oude’ toegelaten bestandsformaten mogen niet uit de lijst worden verwijderd om te voorkomen dat er bij onderhoud en gebruik problemen optreden.  Daarnaast houdt het beheer ook in dat de integriteit van de archiefbestanddelen en de bijbehorende metadata wordt gewaarborgd

In de NEN 2082 worden specifieke eisen gesteld, die ik hier niet citeer i.v.m. de auteurswet.

Wel geef ik enkele aandachtspunten:
- Ik ben het volstrekt oneens met de bovenstaande benadering. Ik vermoed dat ik niet de enige zal zijn in het werkveld. Ik heb liever een exotisch bestand in het archief, dan dat ik de informatie helemaal niet in het archief heb (mensen werken om het systeem heen, omdat ze belemmerd worden). Maar ja, het bovenstaande is wel "de standaard".
- Het "volgen" betreft de fysieke en/of virtuele locatie van het archiefstuk. In welke systemen heeft het eerst gezeten? Is er ook nog een papieren exemplaar? Waar is die geweest en waar is die nu?

Een nadere analyse van de eisen is nodig.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
Bij de refinement-sessie op 28-01-2019 heb ik beloofd dat ik #364 (over de NEN 2082) zou opknippen in een user story per paragraaf. Het gaat dan om de paragrafen waarin concrete functionele en/of tehcnische eisen worden geformuleerd. Dit heeft geleid tot de user stories #725, #726, #727, #728, #729, #730, #731 en #732.

Ik geloof overigens niet dat de developers hier voldoende mee geholpen zijn. Nadere analyse lijkt mij noodzakelijk.

**Comment by Hugo-ter-Doest** [comment]
Is buiten scope van de ZGW API's. Zie ook #740
