### ISSUE TITLE
Als medewerker IB wil ik dat archiefbescheiden conform de NEN 2082 (par. 6.4) beschikbaar gesteld kunnen worden

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#728]
NEN 2082:

> Beschikbaar stellen mag alleen geschieden aan gebruikers die in hun rol daartoe zijn geautoriseerd binnen een bepaald gebruikersprofiel. Van (metadata van of over) archiefstukken op elk aggreggatieniveau moet worden bepaald of zij beschikbaar mogen worden gesteld op basis van de rol en aan de hand van de vastgelegde beveiligingsniveaus. 

In de NEN 2082 worden specifieke eisen gesteld, die ik hier niet citeer i.v.m. de auteurswet.

Wel geef ik enkele aandachtspunten:
- Er is aandacht voor autorisaties, zoekfunctionaliteit en presentatie (viewer?)
- Voor wat betreft autorisaties, zie ook #731 en #732. In die delen van de NEN 2082 worden strengere eisen gesteld.
- Ik zou hier uitgaan van wat de business vraagt.

Een nadere analyse van de eisen is nodig.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
Bij de refinement-sessie op 28-01-2019 heb ik beloofd dat ik #364 (over de NEN 2082) zou opknippen in een user story per paragraaf. Het gaat dan om de paragrafen waarin concrete functionele en/of tehcnische eisen worden geformuleerd. Dit heeft geleid tot de user stories #725, #726, #727, #728, #729, #730, #731 en #732.

Ik geloof overigens niet dat de developers hier voldoende mee geholpen zijn. Nadere analyse lijkt mij noodzakelijk.

**Comment by hdksi** [comment]
> Ik zou hier uitgaan van wat de business vraagt.

Gezien de beperkte mogelijkheden die we nog hebben om archiveringsfunctionaliteit toe te voegen, lijkt dit me vooralsnog een goed advies.
