### ISSUE TITLE
Als beheerder IB wil ik beschikken over beheerinstrumenten zoals beschreven in de NEN 2082 (par. 6.8)

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#732]
NEN 2082:
> Een selectie-instrument is o.a. een overzicht van criteria op basis waarvan de waardering wordt vormgegeven (vaak selectiecriteria genoemd), leidend tot een selectiebeslissing. Dat wil zeggen de keuze welke archiefstukken voor blijvende bewaring en dus overdracht, dan wel op termijn voor vernietiging in aanmerking komen, waarbij dan ook die termijn is vastgesteld. De neerslag van het proces van waardering is terug te vinden in bewaarschema’s. Deze bewaarschema’s kunnen de vorm hebben van basisselectiedocumenten (BSD’s), selectielijsten of vernietigingslijsten. Overheidsorganen moeten bij het ontwerpen, vaststellen en onderhouden van bewaarschema’s rekening houden met in wet- en regelgeving gestelde richtlijnen daaromtrent.
> 
> (...)
> 
> Archiefstukken en archiefbestanddelen worden geordend volgens een classificatieschema met als doel:
> - de samenhang ervan weer te geven en te waarborgen en 
> - de toegankelijkheid te bevorderen.
> 
> (...)
> 
> Binnen de autorisatietabel (in NEN-ISO 15489 ‘toegangsclassificatieschema’ genoemd) wordt bepaald welke handelingen, activiteiten of taken tot een rol behoren en welke rollen toegangsrechten geven tot archiefstukken die bepaalde beveiligingsniveaus hebben. De autorisatietabel bepaalt wat gebruikers wel of niet mogen. Elke gebruiker heeft een gebruikersprofiel. Een gebruikersprofiel bestaat uit één of meer rollen.
> 
> (...)
> 
> De toegang tot archiefstukken en/of archiefbestanddelen kan om verschillende redenen zijn beperkt: bijv. vanwege vertrouwelijkheid, beperkte openbaarheid en om privacyredenen. Om de toegang te kunnen beperken moeten beveiligingsniveaus kunnen worden toegekend. 

In de NEN 2082 worden specifieke eisen gesteld, die ik hier niet citeer i.v.m. de auteurswet.

Een nadere analyse van de eisen is nodig.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
Bij de refinement-sessie op 28-01-2019 heb ik beloofd dat ik #364 (over de NEN 2082) zou opknippen in een user story per paragraaf. Het gaat dan om de paragrafen waarin concrete functionele en/of tehcnische eisen worden geformuleerd. Dit heeft geleid tot de user stories #725, #726, #727, #728, #729, #730, #731 en #732.

Ik geloof overigens niet dat de developers hier voldoende mee geholpen zijn. Nadere analyse lijkt mij noodzakelijk.

**Comment by Hugo-ter-Doest** [comment]
Dankjewel @MarcoKlerks. Inderdaad is analyse nodig, maar nu hebben we de onderwerpen beter in beeld.

**Comment by hdksi** [comment]
Bij overdracht van archiefbescheiden kan het handig/nodig(?) zijn een overzicht van beperkingen die rusten op de over te dragen bescheiden aan te leveren.

**Comment by hdksi** [comment]
> Ik zou hier uitgaan van wat de business vraagt.

Gezien de beperkte mogelijkheden die we nog hebben om archiveringsfunctionaliteit toe te voegen, lijkt dit me vooralsnog een goed advies.
