### ISSUE TITLE
Tabellen in Jekyll theme zijn lelijk

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#735]
... en die kunnen minder lelijk :smiley: 

Voorbeelden:

* https://ref.tst.vng.cloud/overige/functioneel/zaken_api
* https://ref.tst.vng.cloud/overige/technisch/zds-vs-zgw

In github zelf zien ze er nog aardig uit, maar het gebrek aan scheidingslijnen/schakeringen maakt het wel erg rommeling in Jekyll.

**Comment by michielverhoef** [comment]
We gebruiken al een tijdje geen jekyll meer
