### ISSUE TITLE
Als recordmanager wil ik een hoofd- en deelzaak (vorm van gerelateerde zaken) vernietigen volgens de daarvoor staande termijnen per resultaattype per procestype

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#737]
...zodat hoofd- en deelzaken conform de selectielijst worden vernietigd.

Toelichting:
Dit betekent dus het losknippen van twee zaken (als dat gewenst is). Het alternatief is dat hoofd- en deelzaak de bewaartermijnen meekrijgen volgens de termijn van de hoofdzaak die dan altijd langer moet zijn dan van iedere deelzaak.  Over dit fenomeen lag een aantal jaren terug een rapport over in verband met de WABO (integrale vernietiging voor de gehele WABO  aanvraag of vernietiging per deelzaak). Dat rapport geeft goed inzicht in hoe hiermee om te gaan.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Bij het zaaktype kan voor brondatum archiefprocedure.afleidingswijze Hoofdzaak worden gekozen. Daarmee kun je aangeven dat voor de bepaling van de brondatum van een deelzaak naar de hoofdzaak moet worden gekeken. Dit kun je dus specificeren.

**Comment by hdksi** [comment]
Misschien is het te lang geleden om het probleem nog goed te zien, maar volgens mij is dit vooral een inrichtingsvraagstuk. Gewoon geen deelzaken van zaaktypen toestaan die een langere bewaartermijn kennen dan de gerelateerde hoofdzaak, óf accepteren dat je mogelijk met incomplete deelzaken komt te zitten. En als je zeker wil zijn van een gelijke nominatie/termijnen tussen hoofd- en deelzaken dan afleidingswijze Hoofdzaak kiezen.
