### ISSUE TITLE
Als recordmanager wil ik weten of alle informatie in een zaak voldoet aan de Nederlandse standaard voor duurzame formaten

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#740]
...zodat ik het zaakdossier zoveel mogelijk in een duurzame vorm kan opslaan.

Toelichting:
De wet (archiefregeling 2010) stelt dat ‘Digitale archiefbescheiden worden, uiterlijk op het tijdstip van overbrenging, opgeslagen in een valideerbaar en volledig gedocumenteerd bestandsformaat dat voldoet aan een open standaard, tenzij dit redelijkerwijs niet van de zorgdrager kan worden verlangd’
Bijvoorbeeld betekent dit: geen samengestelde Zip-bestanden of MSG bestanden of Amerikaanse SPSS bestanden etc.). 
Zie voor alle voorkeursformaten het rapport van het nationaal archief https://www.nationaalarchief.nl/archiveren/kennisbank/handreiking-voorkeursformaten-nationaal-archief

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Vraagt analyse hoe we dit kunnen ondersteunen. NEN2082 bevat ook een eis over toegestane formaten. Ik kan me voorstellen dat er een referentielijst is met duurzame formaten, en dat als alle informatieobjecten bij een zaak duurzaam zijn, de zaak een vlag "DUURZAAM" krijgt.

**Comment by MarcoKlerks** [comment]
De NEN 2082 is al een paar jaar oud. Ik zal even op Twitter vragen of er een actuele, breed-gedragen lijst is met duurzame formaten: https://twitter.com/MarcoKlerks/status/1090913132959227904

**Comment by MarcoKlerks** [comment]
Een ander lijstje: https://dans.knaw.nl/nl/deponeren/toelichting-data-deponeren/voor-het-deponeren/bestandsformaten

Het lijstje is van DANS. Zij zijn onder ingewijden bekend en hebben een goede naam.

**Comment by MarcoKlerks** [comment]
Ook een interessante bron, met name ook voor het herkennen van bestandstypen: http://www.nationalarchives.gov.uk/PRONOM/Default.aspx#

**Comment by Hugo-ter-Doest** [comment]
Dit is buiten scope omdat preserveren in duurzame formaten verantwoordelijkheid is van eDepot.
