### ISSUE TITLE
Als gemeente wil ik helder en toegankelijk overzicht en inzicht hebben in de beschikbare api's en de functionaliteiten van de api en de typische inzetmogelijkheden van de api (patronen)

### ISSUE THREAD

**Issue by RvdKlip** [VNG-Realisatie/gemma-zaken#75]
... zodat ik weet waarvoor ik de api kan gebruiken in mijn processen en interfaces

**Comment by michielverhoef** [comment]
Meenemen in de herinrichting van de documentatie

**Comment by RvdKlip** [comment]
Kan dicht. Goeddeels opgelost met componenten/software catalogus
