### ISSUE TITLE
Als ontwikkelaar wil ik een eenduidige definitie van "zaakdossier"...

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#750]
...zodat ik precies weet wat er allemaal bij een zaak hoort en niet t.b.v. vernietiging van een "zaakdossier".

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Een zaakdossier is het geheel van zaak-metadata, bijbehorende informatieobjecten incl. metadata, statussen, resultaten en besluiten, en gekoppelde entiteiten:
-	Deelzaken (of hoofdzaak)
-	Vervolgzaken (of is zelf vervolgzaak)
-	Gerelateerde zaken (via zakenrelatie)
-	Zaakobjecten: andere objecten uit het RGBZ of RSGB waarop de zaak betrekking heeft
-	Ander zaakobjecten: objecten waarop de zaak betrekking heeft maar die geen onderdeel uitmaken van RGBZ of RSGB. Dit kunnen business objecten zoals melding of aanvraag zijn.


Entiteit | Vernietigen als onderdeel van de zaak?
-- | --
Zaak | Ja incl. statussen, resultaten, besluiten (niet de typen   uiteraard)
Gekoppelde informatieobjecten | Ja, elk informatieobject dat geen andere relaties heeft, bijv. naar andere zaken of naar besluiten die niet aan deze zaak zijn gekoppeld
Deelzaken | zie #737
Vervolgzaken | zie #736
Gerelateerde zaken | Gerelateerde zaken archiveren volgens hun eigen zaaktype
Zaakobjecten | Nee
Andere zaakobjecten | Ja, deze moeten tesamen met de zaak worden vernietigd. Er  wordt typisch een notificatie gestuurd naar de andere registratie voor vernietiging. Zie ook #651.

**Comment by joeribekker** [comment]
We hanteren voor nu de definitie die Hugo heeft beschreven.

**Comment by JohnRooijakkers** [comment]
Als een "zaakdossier" ook de gerelateerde hoofd, deel, gerelateerde en vervolg zaken bevat, dan is de afbekaning van een "zaakdossier" voor mij niet duidelijk. Ik neem aan dat bedoeld wordt dat de "verwijzing" naar deze (ander) zaken onderdeel uitmaken van het "zaakdossier".

**Comment by Hugo-ter-Doest** [comment]
Ja, het gaat me inderdaad om de "verwijziging". En relaties met andere zaken hebben gevolgen voor archivering.
