### ISSUE TITLE
Zoeken door API-specificatiepagina's werkt niet

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#754]
Zoeken levert geen resultaat op.

Zie bijvoorbeeld https://ref.tst.vng.cloud/brc/api/v1/schema/.

**Comment by sergei-maertens** [comment]
Welke zoekterm gebruikte je? Wat verwachte je? Welke browser heb je gebruikt?

**Comment by hdksi** [comment]
Excuses, verkeerde link gepost. Het ging om https://ref.tst.vng.cloud/zrc/api/v1/schema/

1) "Initiator", "Belanghebbende" (zoals bijvoorbeeld opgenomen in de enumeratie bij 'rolomschrijving')
2) Firefox 64.
3) Verwachtte bij de zoekfunctie een indicatie van gevonden match te krijgen, of dat de viewport zou worden gericht op de plaats waar de eerste overeenkomst met de zoekterm werd aangetroffen. Door uitblijven van beide gevolgen leek het alsof de zoekfunctie in het geheel niet werkte.

Ik zie nu dat treffers geel gemarkeerd worden. De zoekfunctie werkt dus prima, echter gedraagt zich niet helemaal conform (mijn) verwachtingen. Geen groot probleem.

**Comment by sergei-maertens** [comment]
Gezien dat dit een 3rd-party app is (redoc javascript) & dus in principe wel functioneel denk ik dat dit prio L wordt. @Hugo-ter-Doest akkoord? lijkt me niet nuttig om hier tijd in te stoppen.

**Comment by Hugo-ter-Doest** [comment]
Ja lage prio inderdaad.

**Comment by TCIMEddy** [comment]
Geen bug en prio L dus uit sprint gehaald en naar backlog verplaatst
