### ISSUE TITLE
Als burger wil ik genotificeerd worden over wijzigingen in zaken binnen een bepaald geografisch gebied

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#760]
....zodat ik kan beschikken over up-to-date informatie

Opmerkingen:
Hier speelt privacy een rol. Wat mag de burger zien?

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Zaken API stuurt events naar Notificatie API. Notificatie API published events door naar subscribers:

```
Zaken API -(event)-> Notificatie API -(publish)-> X, Y en Z subscribers
```

Als we alleen URL (en evt. ZaakType en Event type) meesturen in een notificatie, dan moet voor deze US dus altijd de Zaak worden opgevraagd om de geo-coordinaten op te halen, om vervolgens te kijken of de subscriber geinteresseerd is in dit specifieke geo-gebied.

Performance bottleneck?

**Comment by Hugo-ter-Doest** [comment]
Moet specifieker gemaakt worden: notificaties over vergunningzaken of MOR-meldingen bijv. in een bepaald gebied. 
Welke attributen moeten we meesturen met de events vanuit ZRC: 
- URI
- UUID notificatie
- Zaaktype
- Event: CRUD operaties, en ook meer inhoudelijke events zoals statuswijziging

**Comment by Hugo-ter-Doest** [comment]
We volgen de CG lijn: events bevatten zo min mogelijk gegevens, de subscriber moet zelf de gegevens ophalen indien nodig.

**Comment by joeribekker** [comment]
Zie mijn opzetje: #764

**Comment by Hugo-ter-Doest** [comment]
De scope binnen ZGW is we events sturen van creeren of wijzigen van zaken zodat afhandelapplicaties op basis van events de zaak kunnen ophalen en kunnen bepalen of het binnen een bepaald gebied is.

**Comment by adgerrits** [comment]
Volgens mij geldt voor alle user stories binnen 'EPIC Notificatie (Sprint 10)' dat ze mogelijk worden gemaakt via  #764 door per behoefte een daarbij passend gebeurtenistype  (zie https://github.com/VNG-Realisatie/gemma-zaken/pull/764#issuecomment-464157326) op te nemen.

**Comment by joeribekker** [comment]
Wat mij betreft Ready for Sprint, door scoping door [Hugo's comment](https://github.com/VNG-Realisatie/gemma-zaken/issues/760#issuecomment-463985799)

**Comment by joeribekker** [comment]
Kapstok US #792 dekt dit af, minus de taak/afhandel-applicatie functies die out-of-scope zijn.

Het geografische element wordt afgedekt met het ophalen van de Zaak-details en deze op geografische relevantie te beoordelen, wat dus mogelijk is op dit moment.
