### ISSUE TITLE
Links for API specs of ZRC and ZTC don't work at host 127.0.0.1

### ISSUE THREAD

**Issue by annashamray** [VNG-Realisatie/gemma-zaken#771]
# Bug

Links http://127.0.0.1:8000/api/v1/schema/ and http://127.0.0.1:8001/api/v1/schema/ show blank pages instead of API specs. 

According to browser debugger a following error appears:
"Uncaught TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'. at redoc-init.js:38"

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Direct oppakken?

**Comment by TCIMEddy** [comment]
@annashamray Could you please tell me where I can find the links mentioned?

**Comment by annashamray** [comment]
What I did (steps to reproduce the error):
1. cloned this repository
1. followed [documentation] (https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/ontwikkelaars/aan-de-slag.md) part **Snelle start** to run Docker containers

Links http://127.0.0.1:8000/api/v1/schema/ and http://127.0.0.1:8001/api/v1/schema/ - are links to docker containers of ZRC and ZTC components running locally at my host

**Comment by TCIMEddy** [comment]
@annashamray thx

**Comment by TCIMEddy** [comment]
@joeribekker kun je het nu beter beoordelen?

**Comment by joeribekker** [comment]
Works for me on for both ZRC and ZTC on `stable/1.0.x` branches.
