### ISSUE TITLE
Als API-consumer wil ik dat de brondatumbepalingssparameters gestandaardiseerd zijn

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#773]
...zodat ik weet welke waardes ik kan verwachten en zeker ben dat het ZTC correct geconfigureerd is.

Dit bedacht ik me tijdens het implementeren van het `brondatumArchiefprocedure` groepattribuut, wat veel parametrisering bevat (zie #344 ).

voor het bepalen van brondatum kan je op resultaattype parametriseren wat je moet gebruiken, dat doe je via 3 velden (sterk versimpeld):

• datumkenmerk (= naam van het attribuut)
• objecttype (= naam van de resource, in essentie)
• registratie (= vb. ZRC ofzo?)

Dit laat een ZRC toe om het betreffende object op te zoeken en de waarde uit te lezen om die als brondatum te gebruiken. Echter, dit is nog te open - de velden zijn allemaal vrije tekst op dit moment, dus iemand kan `zrc` invullen, maar ook `ZRC`, en dan moet een consumer dat maar begrijpen. Dit zou ik dus strakker willen standaardiseren. Dat betekent ook dat er een mechanisme moet zijn om de objecten te lokaliseren.

Als je als concreet voorbeeld neem `datumkenmerk='meldingsdatum'`, `objecttype=Melding`, `registratie='ORC'`, dan zie ik de volgende opties:

• ZTC haalt de OAS op van het ORC, hiervoor moeten we een mapping hebben van registratielabel naar welke OAS relevant is (kan als configuratie in ZTC)
• ZTC leest OAS uit en kijkt naar het schema van de resource `Melding`. Indien niet gevonden -> validatiefout in ZTC.
• ZTC inspecteert resource `Melding` en controleert dat het veld `meldingsdatum` bestaat EN het formaat `date` heeft, indien niet -> validatiefout in het ZTC

Een consumer die dit uitleest, die moet dan vervolgens de zaakobjecten opvragen van de betreffende zaak, en kan filteren op `objectType=Melding` (dus: objecttype moet een enum zijn van bekende objectTypes!). daarna kan dan inderdaad het datumkenmerk uitgelezen worden. voor de consumer is de registratie dan niet zo belangrijk denk ik, doordat we vanuit de zaak de relaties (zullen) kunnen opvragen
als je met besluit werkt bijvoorbeeld, dan betekent dat ook dat we in ZRC gerelateerde besluiten moeten bijhouden om te voorkomen dat we alle BRCs moeten scannen (en/of een directory service hiervoor nodig hebben) - tot die vaststelling kwamen @joeribekker  en ik gisteren al

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
ik mis de rol van `Afleidingswijze` in dit verhaal, die bepaalt hoe je de genoemde attributen moet gebruiken.

**Comment by sergei-maertens** [comment]
Ja, dit is een direct gevolg van dat veld/attribuut. Het is geimplementeerd _hoe_ je ze moet gebruiken, alleen de _inhoud_ ervan moet nog gevalideerd worden imo.

**Comment by Hugo-ter-Doest** [comment]
We gaan dit niet valideren en denken bovendien dat dit niet geautomatiseerd kan worden gearchiveerd omdat resources en attributen over tijd zullen veranderen.

**Comment by hdksi** [comment]
In principe is dit een goed idee, maar de vraag is of hiermee geen vals geval van zekerheid wordt gecreëerd. We weten immers niet hoe de registratie waarin het object leeft er over 1, 5 of 10 jaar uitziet. Best mogelijk immers dat het bij het zaaktype gevalideerde attribuut op dat moment niet meer bestaat.
