### ISSUE TITLE
Als developer wil ik toegang tot Besluit vanaf de Zaak in de API...

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#775]
...zodat ik niet onnodig het BRC hoef te raadplegen (en archivering kan afmaken).

Deze US kwam voort uit behoefte om het Besluit te raadplegen vanaf de Zaak, zodat de (t.b.v. archivering) de afleidingswijze "vervaldatum_besluit" en "ingangsdatum_besluit" geïmplementeerd kunnen worden (t.b.v. het bepalen van de brondatum cq. de archiefactiedatum).

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Op verzoek van refinement sessie naar Ready gesleept.

**Comment by Hugo-ter-Doest** [comment]
zie ook #979

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest close?
