### ISSUE TITLE
Sprint demo 25-4

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#777]
Demo

Omdat er al een leveranciersdag is eind maart en er een demo is gepland op 28-4 is het idee om dit samen te voegen met 1 API-lab (en dan wel 2 dagen).

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Ik ben zo vrij geweest om label ZH er aan te hangen... Als het niet goed is graag wijzigen.

**Comment by joeribekker** [comment]
Hugo stelt voor:

* Leveranciers leegtrekken: Specifieke vragen met als gedacht: wat is er nog nodig?
* Crashcourses: Notificaties en Autorisaties

We mogen Eddy de vragen mailen

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest wellicht kun je de taken al aangeven (als het van toepassing is...)

**Comment by Hugo-ter-Doest** [comment]
Voor de tutorials op het API-lab user stories: #862 #863 #865 #866 

Voor de enquete op het API-lab zie #888

**Comment by Hugo-ter-Doest** [comment]
Dit was gecombineerde story voor sprint-demo en API-lab. Gesplitst.
