### ISSUE TITLE
Onnodige header verplichtingen

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#783]
De headers Accept-Crs en Content-Crs zijn op veel plaatsen verplicht terwijl ze niet worden gebruikt (bijvoorbeeld bij het aanmaken van zaak zonder locatie). Dat is wat onnodig.

Zowiezo is het gek om via headers aan te geven wat je voor content terug verwacht op een parameter.  Dat zou in principe kunnen worden afgevangen door validatie op die parameter (zo als het overigens voor de overige parameters ook gebeurd).

**Comment by sergei-maertens** [comment]
Zie ook https://github.com/Geonovum/KP-APIs/issues/3

Voordien was mij meegedeeld dat ze _altijd_ moesten meegegeven worden, dat github issue lijkt nu het tegendeel te beweren.

> Zowiezo is het gek om via headers aan te geven wat je voor content terug verwacht op een parameter. Dat zou in principe kunnen worden afgevangen door validatie op die parameter (zo als het overigens voor de overige parameters ook gebeurd).

In dit geval niet (helemaal) - GeoJSON heeft niet ingebakken om welk CRS het gaat (dat was er in een draft wel, maar is eruit gesloopt). Het default CRS van GeoJSON is niet precies genoeg voor Nederland/Europa, en op termijn moeten deze 2 andere coordinatenstelsels ook ondersteund worden.

**Comment by rubenvdlinde** [comment]
Maar tot in hoeverre kan er verwarring ontstaan over de CRS standaard? In principe gaat het over de mate van accuracy van de coördinaten, wat zich vertaald in de opbouw/lengte van de coördinaten. 

Daar valt op te valideren zonder dat je überhaupt  de CRS weet, een als er een beperkt aantal objecten valide kan je ook  een switch gebruiken in de validatie. Defacto beperken we ons hier nogal. In de verwijs gedacht kan ik me namenlijk prima voorstellen dat een BAG url hier op termijn ook valide invoer is.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio en visie?

**Comment by Hugo-ter-Doest** [comment]
De guidelines van de KP-API lijken me prima. Ik sluit hem af.

**Comment by sergei-maertens** [comment]
@rubenvdlinde nog voor extra context - dezelfde locatie in CRS WSG:84 heeft andere waarden in de GeoJSON dan in RD! De betekenis van de waarden verandert zelfs.

Ik denk dat verdere issues hiermee bij KP-API moeten aangedragen worden.

**Comment by inoorhoff** [comment]
> Maar tot in hoeverre kan er verwarring ontstaan over de CRS standaard? In principe gaat het over de mate van accuracy van de coördinaten, wat zich vertaald in de opbouw/lengte van de coördinaten.
> 
> Daar valt op te valideren zonder dat je überhaupt de CRS weet, een als er een beperkt aantal objecten valide kan je ook een switch gebruiken in de validatie. Defacto beperken we ons hier nogal. In de verwijs gedacht kan ik me namenlijk prima voorstellen dat een BAG url hier op termijn ook valide invoer is.

Ik begrijp dit niet helemaal, wordt de ontvanger geacht aan de hand van coördinaten zelf te gokken welk CRS er gebruikt wordt ?
