### ISSUE TITLE
API Versie meegeven in calls

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#784]
Op dit moment wordt de api versie meegegeven in response headers, maar vanuit contactring zou ik hem juist in de calls verwachten. zodat je een bepaalde versie van de API kan aanroepen?

Het lijkt nu enigszins in de in de enpoint te zitten (v1) maar dat wijkt af van de teruggeven api versie (1.0.0 Alpha) bovendien zou dat betekenen dat met een verzie wijziging ook alle endpoint opschuiven...

**Comment by sergei-maertens** [comment]
Zodra er meerdere versies komen moet inderdaad version-negotation geimplementeerd worden via de request.

De endpoint bevat enkel de major versie, bij een nieuwe major versie krijg je inderdaad een endpoint wat opschuift, maar hier zijn breaking changes aan verbonden. De response header bevat gedetailleerde versie informatie zoals minor en patch versie (cfr. semantic versioning). Dit laat toe om te bepalen welke (laatste) versie een API ondersteunt - de spec kan namelijk nieuwer zijn en nog niet alle implementaties bijgewerkt.

**Comment by rubenvdlinde** [comment]
Ik lees dit als een "we zijn het eens en pakken het op zodra het daadwerkelijk nodig is, dat is het nu nog niet" ;)

**Comment by Hugo-ter-Doest** [comment]
Hoort niet bij de epic Historie- en Versiebeheer. Gaat om versiebeheer van de API's en hoe we omgaan met endpoints en versie-informatie in berichten.

**Comment by sergei-maertens** [comment]
@rubenvdlinde dat lees je goed :wink:

**Comment by melsk-r** [comment]
@rubenvdlinde: Zie https://github.com/VNG-Realisatie/api-beheer/blob/master/versiebeheer.md. Daarin is beschreven hoe we om willen gaan met versiebeheer zodra een API standaard in beheer is genomen. Wellicht goed als je eens kijkt of we daarin wel alle noodzakelijk facetten hebben meegenomen. Input altijd welkom.

**Comment by Hugo-ter-Doest** [comment]
Zie ook #931

**Comment by Hugo-ter-Doest** [comment]
Het is nu duidelijk hoe we met versies in relatie tot endpoints en responses omgaan.
