### ISSUE TITLE
JWT Token in Authorization

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#785]
De JWT Token moet in de de Authorization header worden meegegeven, das natuurlijk een mega opendeur maar het staat nu niet in het stukje documentatie over hoe de authenticatie plaats vind. ;)

**Comment by sergei-maertens** [comment]
Zie ook https://ref.tst.vng.cloud/standaard/standaard#autorisatie :)

**Comment by rubenvdlinde** [comment]
Ow eens, bessides dit is kleuter kennis :) Maar tis denk ik wel mooi om een te herhalen in de auth tabbel bovenaan de decentrale docs. Voorkomt ook dat je er vanuit gaat dat mensen door meerdere docs tegelijkertijd heen lopen.

Daarnaast denk ik zowiezo dat we een beetje van de "dat staat daar gedachte" af moeten als we willen dat het verhaal wat gaat leven. En bij wijze een willekeurige student op de zolder kamer er ook mee aan de haal kan zonder tig stukken te lezen.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Ik weet niet of het Improvement of bug is. Graag prio en visie

**Comment by sergei-maertens** [comment]
> Ow eens, bessides dit is kleuter kennis :) Maar tis denk ik wel mooi om een te herhalen in de auth tabbel bovenaan de decentrale docs. Voorkomt ook dat je er vanuit gaat dat mensen door meerdere docs tegelijkertijd heen lopen.

Had ernaar gekeken, maar volgens mij kan dat niet op die manier in OAS. Uit [OAS](https://swagger.io/docs/specification/authentication/) volgt dat het HTTP scheme betekent dat je de `Authorization` header moet gebruiken. Dus is eigenlijk een stukje 'weet wat OAS 3.0 betekent/hoe het werkt'. Niet ideaal, want ik snap je punt, maar het zit er dus wel in vervat.

> Daarnaast denk ik zowiezo dat we een beetje van de "dat staat daar gedachte" af moeten als we willen dat het verhaal wat gaat leven. En bij wijze een willekeurige student op de zolder kamer er ook mee aan de haal kan zonder tig stukken te lezen.

Is een beetje moeilijk, want je kan niet _alles_ beschrijven in een OAS. Volgordelijkheid, validaties... etc. kan je enkel in detail op een andere plek beschrijven. Ook hier begrijpen we je punt, het speelt ook bij ons en het is een uitdaging om de documentatie goed doorklikbaar/logisch te volgen te maken.

Ik sluit deze omdat het originele probleem m.i. 'opgelost' is.
