### ISSUE TITLE
Parameters aanvullen

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#786]
Ik mis wat algemeen normale parameters, zo als aangemaaktOp etc

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest ik weet niet of het een bug is maar heb dit label er voor nu aan gehangen.

**Comment by Hugo-ter-Doest** [comment]
Geen bug. Nieuwe attributen kunnen gewoon als user story worden opgevoerd.

Van welke entiteit is aangemaaktOp?

**Comment by michielverhoef** [comment]
Dit is opgelost met het opnemen van RGBZ 2 in de API's.
