### ISSUE TITLE
Documentatie zaak geometrie

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#787]
De omschrijving van de gewenste invoer bij zaak geometrie zou wellicht iets leesbaarder kunnen.

![geosjongeometrie](https://user-images.githubusercontent.com/4021899/53403161-69e42780-39b3-11e9-9edf-d62560e6c643.PNG)

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest bug en prio H, huidige sprint? anders volgende sprint (en dan mag het in de kolom ready for sprint)

**Comment by Hugo-ter-Doest** [comment]
Het is geen bug en kan mee in de volgende sprint.

**Comment by sergei-maertens** [comment]
Was gefixed in https://github.com/VNG-Realisatie/vng-api-common/commit/55519328ef7ecc11fed6960697f1af016db8ac02

**Comment by joeribekker** [comment]
![image](https://user-images.githubusercontent.com/96970/63690180-40924000-c80c-11e9-95b4-ba5439ca83b7.png)
