### ISSUE TITLE
Beter bug-informatie verzamelen

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#789]
# Improvement Story

We moeten even tijd stoppen in de bug-template bij de Github issues, om gerichter te kunnen ondersteunen. De volgende vragen moeten beantwoord worden:

1. Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)
2. Welke claims/payload bevat je JWT?

**Comment by TCIMEddy** [comment]
Wat mij betreft gedaan
