### ISSUE TITLE
Als productmanager wil ik een overzicht van de ondersteunde functionaliteit van een api

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#79]
...
zodat ik kan zien of inbouwen van deze API voor mijn product van toepassing is

**Comment by TCIMEddy** [comment]
@michielverhoef @ehotting is deze nog van toepassing? Volgens mij voldoen we aan dit item wanneer we voldoen aan de definition of done van alle user stories.

**Comment by ehotting** [comment]
Klopt, dubbel met DoD's
