### ISSUE TITLE
Revisions 

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#790]
Hoe wordt er gedacht over revisions managment? We gaan voor te trouwplanner waarschijnlijk de couchdb manier volgen, ofwel `"_rev": "1-bea5fa18e06522d12026f4aee6b15ee4"`. 

Dit geeft ons een git achtige mogelijkheid om om te gaan met conflicten, en creëerd ook de mogelijkheid om  "oude" versies van een object op te halen.

voordeel van het volgen van de couchdb methode is dat er nogal wat kant en klare methodes zijn waar mee er vervolgens service workers op gezet kunnen worden (pouchdb om er maar eens een te noemen) .

**Comment by sergei-maertens** [comment]
we zitten zelf te denken om ETag te gebruiken bij het muteren van objecten, zodat enkel geupdatet kan/mag worden als provider en consumer dezelfde state van een resource hebben.

Versionering als concept heeft een eigen EPIC en staat in de roadmap, omdat hier ook tijdreizen bij komt kijken.

**Comment by rubenvdlinde** [comment]
Op zich zouden te elkaar redelijk goed aanvullen eigenlijk, zeker omdat ETag in de header gaat en _rev in het object.

Voordeel  is dat je dat je dan de HTTP 304 kracht van ETag kan gebruiken, om te controleren of je de meest recente versie in cache hebt en de kracht van -rev voor versiebeheer. Beetje best of both worlds.

Als ik naar de [Etag definitie](https://tools.ietf.org/html/rfc7232#section-2.3) kijk is een _rev een geldige ETAG. Dus defacto is het enige wat we daarvoor hoeven te doen de _ref tevens mee te geven als Etag.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio en visie
