### ISSUE TITLE
Als provider wil ik dat DELETE door-cascadet naar DRC/BRC (wat betreft relaties tussen de objecten)

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#791]
...zodat relaties consistent blijven.

Bij het DELETEn van een Zaak in het kader van vernietiging (archivering) worden gerelateerde objecten meevernietigd, zo ook `ZaakInformatieobject`. Zaakinformatieobjecten worden door het DRC aangemaakt als reactie op het aanmaken van ObjectInformatieObject-relaties. Het verwijderen van Zaakinformatieobjecten moet dus ook de gespiegelde ObjectInformatieObject-relatie verwijderen.

Dit kan onder water door het ZRC gebeuren of inhaken op de notificatie-mechanismen.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Ik zou dit wel beperken tot relaties, en niet de objecten achter die relaties in andere APIs

**Comment by sergei-maertens** [comment]
Dat was mijn insteek, inderdaad

**Comment by JohnRooijakkers** [comment]
Wat is de consequentie hiervan voor het vernietigen van een zaak (dossier)? Moeten dan alle bij de zaak behorende informatieobjecten seperaat worden verwijderd? Dit lijkt mij niet wenselijk. Als de zaak wordt vernietigd dan moeten (mijn inziens) ook alle daarin opgenomen informatieobjecten worden vernietigd. Als dit niet automatisch gebeurt, dan moet die taak expliciet elders worden belegd.

**Comment by Hugo-ter-Doest** [comment]
Ja, dat wordt dan belegd bij de consumers. Zullen we documenteren in de standaard.

**Comment by sergei-maertens** [comment]
> Als de zaak wordt vernietigd dan moeten (mijn inziens) ook alle daarin opgenomen informatieobjecten worden vernietigd

Dat kan enkel als het informatieobject niet in andere niet-vernietigde zaken voorkomt.

**Comment by michielverhoef** [comment]
Voor zover ik weet werkt het nu ook zo dat een zaaksysteem geen documenten verwijdert uit het DMS maar dat "weesdocumenten" (documenten die geen relatie meer hebben met een zaak) in een apart proces opgeruimd worden.

**Comment by Hugo-ter-Doest** [comment]
NB: gaat alleen over de relaties met andere objecten (zoals zaakinformatieobject), niet over de objecten zelf. Het is aan de client om deze ook te verwijderen (indien nodig).

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest kan deze dan op close?

**Comment by sergei-maertens** [comment]
Opgelost door het omkeren van de relatie, maar nog even formeel verifiëren als review. De updates aan integratietests zijn WIP

**Comment by sergei-maertens** [comment]
Nog niet gefixed, ik pak op

**Comment by sergei-maertens** [comment]
PR: https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/pull/61/files
