### ISSUE TITLE
(NR) Als Consumer-A wil ik geïnformeerd worden als een Zaak/Document gewijzigd wordt door Consumer-B

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#792]
...zodat de Consumer-A de gebruikers kan informeren over de wijziging.
Voorbeelden:
- er wordt document toegevoegd aan Zaak
- er wordt een document verwijderd
- er zijn gegevens van de zaak gewijzigd (omschrijving, archieftermijn,..)

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Heeft overlap met #648

**Comment by joeribekker** [comment]
Veel overlap maar wel een goede insteek voor documentatie om dit zo op te nemen.

**Comment by joeribekker** [comment]
Invulling van deze US:

Hiervoor maakt het ZRC een kanaal "zaken" aan op het NC. Abonnees op het kanaal "zaken" van het NC krijgen berichten.

**Comment by MaartenRutten** [comment]
Scenario: Consumer-A behandelt zaken en voegt documenten toe aan zaken en wil een notificatie op het moment dat een andere Consumer een document toevoegt aan één van deze zaken.

**Comment by MaartenRutten** [comment]
Scenario: Consumer-A behandelt zaken samen met Consumer-B en beide Consumers willen notificaties ontvangen als de andere Consumers iets wijzigt (bv. de status).
