### ISSUE TITLE
Nieuwe scopes staan niet in OAS 3.0

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#797]
# Bug

In ZRC worden de scopes wel opgepikt, in DRC/BRC/ZTC niet. Even kijken waarom dit niet gebeurt.

**Comment by sergei-maertens** [comment]
Found the cause - the mapping in the code has `delete` as key instead of `destroy`

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest trio?

**Comment by TCIMEddy** [comment]
@sergei-maertens is dit dan al opgelost? Zo ja graag close

**Comment by sergei-maertens** [comment]
https://github.com/VNG-Realisatie/gemma-zaken/pull/809 is pending...
