### ISSUE TITLE
Validatie op zaaktype

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#799]
Volgens de documentatie https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_create zou zaaktype een geldige url moeten zijn, de praktijk lijkt iets weerbarstiger....

Wat is hier het idee? Moet dit een actieve url die status 200 geeft zijn? in de zaakcatalagus?

In principe hoeft een url niet actief te zijn om valide te zijn ;) En zijn er meer statussen dan 200 die valide zijn (301,302 etc).

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by sergei-maertens** [comment]
Dit staat in https://ref.tst.vng.cloud/standaard/standaard#definities:

> ‘Uiteindelijk resulteren’ betekent dat redirects (`HTTP 301`, `HTTP 302`) toegestaan zijn, mits deze redirect-locatie resulteert in een `HTTP 200`.

> de praktijk lijkt iets weerbarstiger...

Kan je dit verder toelichten?

**Comment by rubenvdlinde** [comment]
www.google.nl geeft ook netjes een HTTP 200, neem niet aan dat we dat een geldig zaaktype vinden ;)

En onder het kopje ieder jaar aan besteden en linked data zie ik een redirect nog wel eindigen in een redirect.

**Comment by Hugo-ter-Doest** [comment]
Laten we kijken naar betere validatie van zaaktypes.

**Comment by sergei-maertens** [comment]
@rubenvdlinde de opmerking dat de validatie verstrakt wordt staat ook in `standaard.md` :) Op het moment van implementeren was dat niet mogelijk, nu hebben we al op een paar plekken dat we kunnen verwijzen naar de verwachte resource (via API-spec van de target-API). Dus dan is een HTTP 200 alleen niet meer voldoende, maar moet het object er ook uitzien zoals verwacht.

**Comment by Hugo-ter-Doest** [comment]
Wordt er op dit gevalideerd op de vorm van het zaaktype?

**Comment by sergei-maertens** [comment]
@Hugo-ter-Doest nee

**Comment by sergei-maertens** [comment]
Dit gebeurt nu wel (in de `develop` branch)
