### ISSUE TITLE
Als archivaris wil ik dat een ZAAK automatisch de archiefstatus "gearchiveerd" krijgt bij vervallen belang

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#802]
...(als het moment daar is) zodat dit geen handmatige stap is. 

Kan ook een event zijn dat er voor zorgt dat dit gezet wordt. Voorbeelden van triggers zijn:

* het overlijden van het object van een zaak (trigger is het vullen van de overlijdensdatum van de persoon)
* het slopen van het object van een zaak (trigger is het vullen van de einddatum van het pand)

Het komt er dus op neer dat het (altijd?) van een datumelement op het object komt, waarop de zaak betrekking heeft.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Waar zou dat event vandaan moeten komen?

**Comment by joeribekker** [comment]
Ja, goede vraag. Er is een archiefstatus "gearchiveerd (procestermijn nog niet bekend)". Als dit bekend wordt moet de archiefstatus naar "gearchiveerd" gezet worden. Waardoor of wie verantwoordelijk is voor het event dat het bekend wordt weet ik ook niet direct.

**Comment by erikdelepper** [comment]
Dit is relevant voor zaaktypes waarbij sprake is van 'vervallen belang'. Voorbeelden van triggers zijn:

- het overlijden van het object van een zaak (trigger is het vullen van de overlijdensdatum van de persoon)
- het slopen van het object van een zaak (trigger is het vullen van de einddatum van het pand)

Het komt er dus op neer dat het (altijd?) van een datumelement op het object komt, waarop de zaak betrekking heeft.

**Comment by erikdelepper** [comment]
Ik weet niet of ik hier een aparte user story voor moet opvoeren, maar in het geval van zo'n geautomatiseerde verwerking van een notificatie, wil ik als archivaris dat bij een fout tijdens het notificeren iemand of iets genotificeerd wordt dat deze fout is opgetreden, omdat anders het vervolgproces (in dit geval vernietiging) nooit wordt gestart.

**Comment by Hugo-ter-Doest** [comment]
Ik heb de formulering van de user story n.a.v. de discussie hierboven. 

Vooralsnog kunnen we voor de meeste procesobjecten geen notificaties ontvangen. Voor besluit en resultaat kan dat wel.
