### ISSUE TITLE
Als ik klik op de link https://ref.tst.vng.cloud/demo/ krijg ik de boodschap "502 Bad Gateway"

### ISSUE THREAD

**Issue by RitaBerghuis** [VNG-Realisatie/gemma-zaken#803]
# Bug

Op de pagina https://ref.tst.vng.cloud/ontwikkelaars/demo-applicatie staat een link naar de demo applicatie. Als we daar op klikken krijgen we de boodschap 502 Bad Gateway.

[assign aan Joeri en/of Sergei, voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint'] Beiden geassigned.

Om gericht te ondersteunen graag ook antwoord op de onderstaande vragen:

Waar staan de componenten gehost? ref.tst.vng.cloud

Welke claims/payload bevat je JWT? Geen idee

**Comment by sergei-maertens** [comment]
Gefixed.

@joeribekker de Kubernetes service mapte 8000 op 8000, terwijl de container zelf 8080 exposet. Mapping aangepast naar 8000 op 8080.
