### ISSUE TITLE
Als product owner wil ik weten hoe de gekozen notificatieoplossing zich verhoudt tot de door het Expertisecentrum Architectuur gepresenteerde opties

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#807]
...zodat ik inzicht krijg in de verhouding tussen architectuurkaders en (deze) praktische oplossing.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Zie voor de opzet van de implementatie hier: https://github.com/VNG-Realisatie/gemma-zaken/blob/7297ddfd6caa6db497a113eba7251ffe18f09b80/docs/_content/ontwikkelaars/algemeen/notificaties.md

Om antwoorden te geven op de vragen uit de presentatie van @ppcjansen d.d. 25 februari 2019:

> Welke topics gaan we hanteren en kunnen we die standaardiseren? Baseren we de topics op de UPL, ZTC, SC, Verwerkingsregister?

Ik heb gekozen voor rsin + API naam (in kleine letters). Voorbeelden zijn: 15619615-zaken, 15619615-zaaktypen, 15619615-documenten

Eventueel kunnen we een postfix nummer toevoegen als er meerdere ZRC, DRC, etc. zijn. Het maakt in essentie ook niet zo veel uit, als de topics maar ergens opgevraagd kunnen worden zodat andere componenten juist geconfigureerd kunnen worden.

> Hoe gaan we autorisatie implementeren? Wanneer mag een subscriber wel een notificatie ontvangen en wanneer niet? Hoe weet je dat?

Voorlopig niet. In principe kan iedereen zich subscriben op een topic. Echter, om details op te vragen moet je wel de juiste autorisaties hebben op die API, dus lost dit probleem zich ook meteen op.

> Welk protocol gaan we standaardiseren?

In het eerder genoemde voorstel wordt het (naar goed VNG gebruik) een Nederlandstalige wrapper om Pub/Sub-functionaliteit heen. Onderliggend gebruiken we RabbitMQ die weer is gebaseerd op AMQP.

> Welke attributen zijn verplicht in de notificatie?

Zie [hier](https://github.com/VNG-Realisatie/gemma-zaken/blob/7297ddfd6caa6db497a113eba7251ffe18f09b80/docs/_content/ontwikkelaars/algemeen/notificaties.md#notificatie)

Het attribuut `kenmerken` is vrij in te vullen volgens de NC specificatie (lees: vrij object), maar op API component niveau moet dit WEL gespecificeerd worden (lees: welke waarden zijn mogelijk). Voor de Zaken API is een kenmerk bijvoorbeeld `zaaktype`.

We hebben toch besloten om niet `methode` (POST, PUT, PATCH) maar `actie` toe te voegen. De suggestie van @adgerrits wordt dus meegenomen teneinde arbitraire acties te definiëren. Hoewel NC dit dus niet specificeert (lees: `string`) dient elk API component dit voor notificatie doeleinden WEL te specificeren (lees: gedocumenteerde `enum`).

> Hoe weet een subscriber wanneer de gewijzigde gegevens interessant zijn?

Dit blijft altijd een balans tussen:
1. Specifiekheid van het topic -vs- Mogelijk missen van notificaties door verschillende topics
2. Informatie in bericht -vs- Autorisatie/ophalen van informatie

Met het voorstel hierboven in het achterhoofd is de notificatie informatie dus beperkt tot maximaal een Zaak van een bepaald Zaaktype.

**Comment by adgerrits** [comment]
Heb 18 maart een eerste ruwe versie van architectuurdocument 'Gegevenslandschap - notificeren van gebeurtenissen;' opgeleverd voor een aantal basale keuzes. Wil dit zsm binnen VNG laten reviewen en (voorlopig) vaststellen. Heb daarvoor nog https://github.com/VNG-Realisatie/gemma-zaken/blob/7297ddfd6caa6db497a113eba7251ffe18f09b80/docs/_content/ontwikkelaars/algemeen/notificaties.md van @joeribekker nog onvoldoende goed doorgenomen/opgenomen Ga dit nu doen, mede als input voor overleg met ZGW-werkgroep waar notificeren nieuwe stijl nu wordt ontwikkeld. Het loopt in de tijd dus wat voor en naast elkaar, maar ik denk dat er op deze manier wel wat goeds uit kan gaan komen. Zal met @Hugo-ter-Doest  en @ppcjansen afstemmen daarvoor.

**Comment by adgerrits** [comment]
Heb afgesproken dat notitie deze week intern gereviewed wordt en ik de aanpassingen vrijdag verwerk. Ik lever vrijdag (kan 23:29 worden...) 0.2 versie hier aan. Zal met Hugo proberen afspraak te plannen.

**Comment by Hugo-ter-Doest** [comment]
@adgerrits  Kun je mij dat document alvast sturen? Dan kan ons team het ook reviewen.

**Comment by adgerrits** [comment]
Heb versie 0.2 zojuist afgerond. Mail het naar @Hugo-ter-Doest die het verder kan verspreiden. Is nog 'work in progress'. Belangrijke vervolgstap wat mij betreft om het met ZGW-werkgroep te bespreken. Wat mij betreft snel een afspraak te maken.

**Comment by JohnRooijakkers** [comment]
Kan iemand me verwijzen naar het meest actuele document dat beschrijft wat de beoogde functionaliteit is van de notificaties?

**Comment by hdksi** [comment]
Hoi John, de documentatie is wat verspreid.

- Algemene richtlijnen met betrekking tot notificeren hier: https://ref.tst.vng.cloud/standaard/standaard
- Instructies voor publiceren/abonneren: https://ref.tst.vng.cloud/ontwikkelaars/notificeren
- API-spec's voor Notificatie(routering)component: https://ref.tst.vng.cloud/standaard/apis/nc
- De presentatie bij de demo van gisteren kan ook nog helpen bij de beeldvorming, die wordt binnenkort hier gepubliceerd: https://ref.tst.vng.cloud/community/bijeenkomsten/index

Het architectuurstuk met meer generieke richtlijnen rondom notificeren is nog in ontwikkeling en zal worden gepubliceerd op GEMMA Online.

**Comment by sergei-maertens** [comment]
Update: er is wat bijgespijkerd:

* designdocument wat tot NRC leidde: https://ref.tst.vng.cloud/ontwikkelaars/algemeen/notificaties
* Algemene eisen/richtlijnen notificeren: https://ref.tst.vng.cloud/standaard/standaard#notificaties
* API specs voor NRC: https://ref.tst.vng.cloud/standaard/apis/nrc
* Developer document met voorbeeldcalls: https://ref.tst.vng.cloud/ontwikkelaars/notificeren
* API lab tutorial: https://ref.tst.vng.cloud/ontwikkelaars/tutorials/notificeren
