### ISSUE TITLE
Als gemeentelijk inkoper wil ik weten voor welke applicaties de OAS relevant is

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#81]
... zodat ik kan bepalen of deze standaard van toepassing is/gevraagd moet worden in een aanbesteding

**Comment by michielverhoef** [comment]
Is een gemeentelijk inkoper echt geïnteresseerd in de relevantie van de OAS of in de relevantie van de standaard? Volgens mij gaat een gemeente niet sturen op een (technisch) onderdeel als een OAS maar op ondersteuning van en voldoen aan  bepaalde standaarden.

**Comment by jgortmaker1** [comment]
de inkoper met weten wat hj moet vragen voro wleke applicatie.
nu gaat dat niet verder dan "voldoet aan ZDS 2.0", of erger "ondersteunt StUF"

zo'n inkoper moet precies worden verteld wat hij moet vragen. OAS gaat veel te diep.

**Comment by Hugo-ter-Doest** [comment]
Hoort niet thuis in dit project, maar is ondersteuning van VNG-R aan gemeenten bij leveranciersmanagement.
