### ISSUE TITLE
Als medewerker informatiebeheer wil ik dat de archiefnominatie en bewaartermijn van een zaak indien nodig kunnen worden aangepast 

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#810]
...zodat bijvoorbeeld geboorteaktes (blijvend te bewaren) niet worden verwijderd bij een zaak 'aangifte geboorte' (110 jaar bewaren).

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by hdksi** [comment]
Meer info volgt

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio en visie

**Comment by Hugo-ter-Doest** [comment]
Ik begrijp de wens. In het RGBZ wordt hierin (nog) niet voorzien. Informatieobject kent de attributen Archiefnominatie en Archiefactiedatum niet. We kunnen deze uiteraard toevoegen aan informatieobjecten. Je moet dan ook het gedrag bij vernietigen en bij heropenen van de zaak bepalen. Als de zaak dan weer met een resultaat en eindstatus afsluit, wat moet dan met de archiefnominatie op het informatie-object worden gedaan?

**Comment by JohnRooijakkers** [comment]
Ik heb tot nu toe altijd gehoord dat de langste bewaartermijn van enig document (informatieobject) binnen de zaak, leidend is voor de termijn voor de zaak als geheel. Deze nieuwe wens is belangrijk genoeg om deskundigen (archivarissen) te raadplegen. Hier geen eigen interpretatie toepassen.

**Comment by Hugo-ter-Doest** [comment]
Als ik het goed begrijp zou dan de bewaartermijn van de zaak moeten worden aangepast, als een document langer moet worden bewaard dan de zaak. Als een document korter moet worden bewaard of zelfs vernietigd, verandert er voor de zaak niets. We hebben een aantal archief-experts betrokken bij deze epic. Die gaan we raadplegen.

**Comment by hdksi** [comment]
Misschien te snel opgeschreven, US ontstond middenin een gesprek. Volgens mij gaat het er inderdaad om dat voor een selectielijstproces (in dit geval 7.1.2) een bepaalde bewaartermijn (110 jaar) is gedefinieerd, die als basis wordt gebruikt voor het bepalen van de bewaartermijn van een zaak. Uitkomst van diezelfde zaak kan echter zijn dat informatieobjecten ontstaan met een afwijkende (in dit geval langere) bewaartermijn, waarop de bewaartermijn van de zaak zou (kunnen/moeten?) worden bijgewerkt.

**Comment by Hugo-ter-Doest** [comment]
In dat geval is het een duplicaat van #346

**Comment by hdksi** [comment]
Niet mee eens, #346 beschrijft algemene functionaliteit, (volgens mij) primair bedoeld voor als er geen regels beschikbaar zijn op basis waarvan de archiefnominatie/bewaartermijn kan worden berekend of als die op basis van een onverwachte gebeurtenis moeten worden aanpast. In dit voorbeeld zouden nominatie en termijn prima kunnen worden afgeleid. Hoe vaak dit voorkomt en met welke prioriteit dit moet worden opgepakt is een tweede...

**Comment by TCIMEddy** [comment]
geen overeenstemming dus roepen

**Comment by Hugo-ter-Doest** [comment]
Duidelijk. Wil je dan een nieuwe user story opvoeren (of deze aanpassen) voor het aanpassen van archiefnominatie en bewaartermijn?

**Comment by hdksi** [comment]
De gemaakte aanpassing gaat ervan uit dat de opmerking van @JohnRooijakkers klopt. Hoewel ik geen reden heb daaraan te twijfelen, begrijp ik dit mechanisme niet helemaal. Een eerste inschrijving BRP zal in de meeste gevallen het gevolg zijn van een geboorte. Als de geboorteakte blijvend moet worden bewaard, en de bewaartermijn van het langst te bewaren bij de zaak horende informatieobject leidend is voor de bewaartermijn van de zaak als geheel, waarom staat de bewaartermijn van het bijbehorende proces dan op 110 jaar?

Ik zal dit inderdaad nog eens voorleggen aan de specialisten.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio?

**Comment by Hugo-ter-Doest** [comment]
@hdksi heb je hier al met specialisten over gesproken?

**Comment by Hugo-ter-Doest** [comment]
Ik haal een stukje zin uit de user story "in gevallen dat een bij de zaak horend informatieobject een van bij de zaak horende selectielijstproces afwijkende (altijd langere?) bewaartermijn of archiefnominatie kent", en geef hem prio hoog. Ik denk nl. dat je hoe dan ook de bewaartermijn en archiefactie van een zaak moet kunnen aanpassen.

**Comment by sergei-maertens** [comment]
Je kan `Zaak.archiefnominatie` aanpassen, is dat de archiefactie? `blijvend_bewaren` of `vernietigen`.

De `Zaak.archiefactiedatum` kan ook geschreven worden. Die wordt nu berekent met de termijn van het zaaktype, maar je kan hem dus overschrijven.

@Hugo-ter-Doest mis ik hier nog wat dan?

**Comment by Hugo-ter-Doest** [comment]
Nee, dan mis je niets meer, en dat betekent dat de user story dicht kan! Tnx
