### ISSUE TITLE
Als Consumer wil ik Zaakinformatie via StUF en Documentinformatie via REST kunnen leveren

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#814]
...zodat Consumer stapsgewijs kan bewegen naar de situatie waarin alle ZGW API's geïmplementeerd en beschikbaar zijn voor Consumer.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Ondersteuning van StUF-berichten is buiten scope van ZGW API's die gebruik maken van REST/JSON. Ik kan me voorstellen dat in het applicatielandschap van de gemeente dit soort combinaties ontstaan. Ik denk dat ESB's of adapters hier een rol in kunnen spelen. Er wordt in Utrecht bijv. gewerkt aan een DRC/CMIS adapter.

**Comment by MaartenRutten** [comment]
Eens. Maar het punt wat ik wilde adresseren is de vraag of en op welke wijze  een verwijzing naar een zaak (of ander object buiten DRC) opgenomen kan worden in het datamodel van DRC. 
Of omgekeerd.
Dus hoe gaat een Referentiecomponent om met verwijzing naar gegevens in niet-Referentiecomponenten.
