### ISSUE TITLE
Als scrumteam lid wil ik POSTMAN testscripts voor de referentie-implementaties waarmee we al het gewenst gedrag zoals beschreven in standaard.md, kunnen testen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#816]
Zodat we aansluiten op de VNG testmethode en referentie implementatie op een uniforme wijze kunnen testen.

Implicatie: beschikbaarheid van POSTMAN testscripts onderdeel maken van de DOD.
@Hugo-ter-Doest : graag hier even overleg over

**Comment by TCIMEddy** [comment]
@HenriKorver Wellicht ook interessant voor jou

**Comment by melsk-r** [comment]
Ook voor beheer is dit van belang. Sterker het is een van de criteria om een standaard in beheer te kunnen nemen.

**Comment by joeribekker** [comment]
Er is gewerkt aan deze User Story.
Zie: https://github.com/VNG-Realisatie/gemma-postman-tests

Echter, de User Story omvat nu "alles" wat niet echt lekker gesliced is. Onze test engineer werkt 2 dagen per week hier aan en is halverwege de sprint ingesprongen.

>Als scrumteam lid wil ik POSTMAN testscripts voor de referentie-implementaties waarmee we **al** het gewenst gedrag zoals beschreven in standaard.md kunnen testen

Ik vraag me daarom af of we deze User Story wel kunnen halen. Het lijkt me beter dit User Story te sluiten en nieuwe User Stories op te voeren die deze tests afdekken per component en/of in de DoD opnemen.

**Comment by CMasselink** [comment]
@joeribekker Het uiteindelijke doel lijkt me wel duidelijk toch? 
Lijkt me inderdaad goed om de testscripts in de DoD op te nemen voor nieuwe functionaliteit. Dat laat nog wel rework over voor de functionaliteit die nu al gerealiseerd is. Als het handig is om daar aparte user stories voor te maken, vind ik dat prima. Als we het einddoel maar gaan halen (even aangenomen dat we het eens zijn over het einddoel).
Dat we qua tijd een impediment hebben, is een ander verhaal....

**Comment by TCIMEddy** [comment]
Idd opnemen in DoD en 'achterstallig'/inhaalwerk aparte user story en deze dus sluiten

**Comment by TCIMEddy** [comment]
@joeribekker Ik zou deze user story nog iets herschrijven in de trant van inhalen of zoiets. In algemeenheid opgenomen in DoD

**Comment by TCIMEddy** [comment]
@joeribekker deze user story hebben we opgenomen voor 'het inhaalwerk' vervolgens maakt hij deel uit van de DoD. Als 'het inhaalwerk' gedaan is dan mag deze op close.

**Comment by TCIMEddy** [comment]
@joeribekker volgens mij nu dod en inhaalslag gereed of bijna gereed dus graag op close zetten

**Comment by Hugo-ter-Doest** [comment]
Inhaalslag is gereed, de rest is dod
