### ISSUE TITLE
Als gemeentelijk inkoper wil ik van applicaties weten of zij voldoen aan de OpenAPI specificatie

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#82]
... zodat ik een goede keuze kan maken welke producten voor mijn gemeente geschikt zijn.

**Comment by Hugo-ter-Doest** [comment]
Is buiten scope van het project. Moet worden gezocht bij de softwarecatalogus.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Ruimt lekker op...
