### ISSUE TITLE
Identificatie i.s.m. bronOrganisatie

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#821]
Dwingen jullie af dat bij een op een zaak gegeven identificatie ook uniek is binnen de bron organisatie?

**Comment by sergei-maertens** [comment]
Ja, zie [standaard](https://ref.tst.vng.cloud/standaard/standaard#run-time-gedrag):

> **Garanderen uniciteit `bronorganisatie` en `identificatie` op de `Zaak`-resource**
>
> Bij het aanmaken (`zaak_create`) en bijwerken (`zaak_update` en `zaak_partial_update`) MOET gevalideerd worden dat de combiantie identificatie en bronorganisatie uniek is, indien de identificatie door de consumer meegestuurd wordt.

Zie ook de [api-spec](https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_create):

> Indien geen identificatie gegeven is, dan wordt deze automatisch gegenereerd. _De identificatie moet uniek zijn binnen de bronorganisatie_.

(emphasis mine)

En voor de volledigheid: [de implementatie](https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/blob/610e2d156609f667f09e9d9f852b27c37f87538e/src/zrc/api/serializers.py#L213)

**Comment by sergei-maertens** [comment]
Merk op dat er 1 pitfall is hierbij:

1. Gegeven RSIN van bronorganiatie `123456`
2. Gegeven ZRC1 binnen organisatie
3. Gegeven ZRC2 binnen organisatie
4. Maak zaak aan met identificatie `abc` en bronorganisatie `123456` in ZRC1
5. Maak zaak aan met identificatie `abc` en bronorganisatie `123456` in ZRC2

Dit zal geen foutmelding geven. ZRC1 weet niet van het bestaan van ZRC2 af en vice versa. Het is aan de organisatie om te voorkomen dat dit gebeurt:

* Gebruik slechts 1 ZRC die de check kan doen
* Gebruik een ZRC dat van het bestaan van andere ZRCs afweet en deze kan bevragen. Zelfs dan is er een concurrency-risico.

**Comment by rubenvdlinde** [comment]
Top thanxs :)
