### ISSUE TITLE
Als geïnteresseerde wil ik de sprint review remote bijwonen

### ISSUE THREAD

**Issue by ArnauldvdHeijden** [VNG-Realisatie/gemma-zaken#829]
# Improvement Story

zodat ik mijn tijd efficiënt kan gebruiken en toch 'live' op de hoogte gehouden wordt van de vorderingen.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest zet deze in ready for sprint

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest ik ben bezig om wat te regelen. Is dit goed? zo ja sleep het dan in de sprint op mijn naam.

**Comment by Hugo-ter-Doest** [comment]
ja is prima!

**Comment by wishalg** [comment]
@TCIMEddy @Hugo-ter-Doest Ik heb voor de volgende demo een camera met statief kunnen regelen die wij bij VNGR gebruiken voor opnames. Ook gaat Henri dit op de VNGR YouTube plaatsen, link via Github.

**Comment by TCIMEddy** [comment]
Gaaf!

**Comment by HenriKorver** [comment]
@TCIMEddy Ik denk dat @wishalg mijn voornaamgenoot Henri Kaper bedoelt

**Comment by TCIMEddy** [comment]
@HenriKorver ok dank
