### ISSUE TITLE
Als leverancier/gemeente wil ik een uitleg hebben hoe en wanneer ik een bijdrage kan leveren

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#83]
Zodat mijn inbreng waardevol te laten zijn

**Comment by ehotting** [comment]
Denk dat deze gesplitst mag worden, communicatie naar gemeenten is heel anders dan naar leveranciers

**Comment by TCIMEddy** [comment]
@ehotting Volgens mij kunnen we hier geen concrete acties aanhangen en zou ik deze op close zetten

**Comment by ehotting** [comment]
Hebben we inmiddels op andere wijze opgepakt. Aanhaken nieuwe gemeenten kan pas wanneer huidig team kleiner wordt.
