### ISSUE TITLE
Max length veld statusType te strak afgesteld

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/gemma-zaken#831]
# Bug

In de testvoorziening worden URLs herschreven zodat de de prefix van de URL wordt vervangen door de hostnaam van de testvoorziening en de sessie waarin de test wordt uitgevoerd:

Bijvoorbeeld:

https://ref.tst.vng.cloud/ztc/api/v1/catalogussen/f7afd156-c8f5-4666-b8b5-28a4a9b5dfc7/zaaktypen/0119dd4e-7be9-477e-bccf-75023b1453c1/statustypen/e53becac-cb4f-4dc7-911b-7d2ca066c041

wordt herschreven naar

https://vng-staging.maykin.nl/runtest/155197263757/ZTC/api/v1/catalogussen/f7afd156-c8f5-4666-b8b5-28a4a9b5dfc7/zaaktypen/0119dd4e-7be9-477e-bccf-75023b1453c1/statustypen/e53becac-cb4f-4dc7-911b-7d2ca066c041

Bij deze transformatie gaat de waarde van het veld statusType over de maximale lengte eis van 200 heen.

```json
{
    "type": "https://vng-staging.maykin.nl/runtest/155197136903/ZRC/ref/fouten/ValidationError/",
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:32a494d0-9d8f-4bfc-9776-a68d773d02fc",
    "invalid-params": [
        {
            "name": "statusType",
            "code": "max_length",
            "reason": "Zorg ervoor dat dit veld niet meer dan 200 karakters bevat."
        }
    ]
}
```

**Comment by sergei-maertens** [comment]
:+1: Gaan we verhogen naar 1000, dit speelt nog op meerdere plekken ook.

**Comment by sergei-maertens** [comment]
Fixed via https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/commit/0f8880837bcdf1d99e6ab00320f9e4c5d2b52b23

This is going through CI right now, follow the build at https://jenkins.nlx.io/job/gemma-zaakregistratiecomponent-stable/
