### ISSUE TITLE
ZTC beheer/admin pagina crasht door incorrectie validatie

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#832]
# Bug

Als je bijvoorbeeld bij het aanmaken van een resultaattype bij de  `selectielijstklasse` een URL invult naar een procestype i.p.v. een resultaat-URL, dan krijg je een crash/error i.p.v. een nette melding met wat er fout is: Sorry, a server error has occurred (500)

We have been automatically notified about the problem and will investigate as soon as possible.

Hosting: ref.tst.vng.cloud (https://ref.tst.vng.cloud/ztc/admin/)
JWT: niet relevant

**Comment by stevenbal** [comment]
@joeribekker 
Pull request voor deze issue
https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/35
