### ISSUE TITLE
linkje werkt niet 

### ISSUE THREAD

**Issue by RvdKlip** [VNG-Realisatie/gemma-zaken#836]
# Bug

Op de site https://ref.tst.vng.cloud/overige/technisch/design-keuzes werkt de verwijzing naar documentatie over authenticatie en autorisatie niet:
https://ref.tst.vng.cloud/overige/architectuur/authenticatie-autorisatie

**Comment by TCIMEddy** [comment]
@joeribekker De laatste link werkt nog niet
