### ISSUE TITLE
Als team lid wil ik de op te leveren OAS YAML file kunnen wijzigen

### ISSUE THREAD

**Issue by andyverberne** [VNG-Realisatie/gemma-zaken#84]
Zodat ik de specificatie kan reviewen en ook pull requests kan doen zonder dat ik de referentie-implementatie hoef aan te passen.

**Comment by joeribekker** [comment]
YAML en/of JSON.

**Comment by ehotting** [comment]
@andyverberne Ben je akkoord als we deze userstory specifiek als acceptatiecriterium opnemen in #72, zodat deze kan worden gesloten? Bijv. als acceptatiecriterium:
`Het is duidelijk hoe teamleden wijzigingen in de specificatie kunnen voorstellen zonder ook de referentieimplementatie te hoeven wijzigen`

Dit zou overigens sowieso geen probleem worden, mijn voorstel was meer gericht op de periode nadat ZDS 2.0 tot standaard wordt verheven.

**Comment by ehotting** [comment]
Verplaatst naar acceptatiecriteria #72, wens is helder. 
Gedurende ontwikkelsprints zijn PR's altijd mogelijk tot anders wordt besloten. Rest afhankelijk van wijze waarop specs tot stand komen (genereren of handmatig), wat we komende tijd uitvinden.
