### ISSUE TITLE
Als gemeente wil ik dat de ZGW api's de scopes en claims die een taakapplicatie meegeeft, gevalideerd worden

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#843]
zodat we er als gemeente zeker van zijn dat een taakapplicatie enkel acties uit kan voeren waar die de juiste rechten toe heeft. We geven hiermee invulling aan het principe van privacy by design en filteren bij de bron.
Gerelateerd aan #838

Gewenste functionaliteit:
Op basis van clientID wil je in de ZGW api's kunnen vastleggen welke scopes en claims/zaaktypes bij het clientID horen. Zie hiervoor ook #838. Vervolgens moeten de scopes en claims die door een taakapplicatie meegegeven worden, op de vastgelegde rechten worden gecontroleerd / gevalideerd. 

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Dit neigt naar een nieuw component.

**Comment by Hugo-ter-Doest** [comment]
Is toch dubbel met #838? Ik zie geen verschil.
