### ISSUE TITLE
As a developer I need consistently named fields in API specs

### ISSUE THREAD

**Issue by GeertJohan** [VNG-Realisatie/gemma-zaken#854]
I was just browsing https://ref.tst.vng.cloud/ontwikkelaars/notificeren and found that the API uses Dutch and English terms in the JSON bodies, as well as in URLs.

I'd like to see a consistent naming strategy, to avoid confusion over whether a term is written in English or Dutch.

I would also prefer English to be used as the language to describe data objects. Having to constantly translate between languages is annoying and costly. It causes confusion, looks immature, and isn't well suited for non-dutch developers. I have never met a skilled Dutch developer that doesn't by default write code in English, so going with English shouldn't be a problem.

For example:
```json
 {
   "callbackUrl": "https://my-consumer.nl/api/callbacks",
   "auth": "Token abcde12345",
   "kanalen": [
     {
       "naam": "zaken",
       "filters": [
         {"bronorganisatie": "224557609"}
       ]
     }
   ]
 }
```

This should be:
```json
 {
   "callbackURL": "https://my-consumer.nl/api/callbacks",
   "auth": "Token abcde12345",
   "channels": [
     {
       "name": "zaken",
       "filters": [
         {"sourceOrganization": "224557609"}
       ]
     }
   ]
 }
```

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest graag prioriteren

**Comment by Hugo-ter-Doest** [comment]
The naming of most fields in the API's is based on RGBZ and imZTC. These are Dutch standards for case management. I want to keep a connection to these standards because that is still the reference for municipalities and companies. Your proposal for translating bronorganisation to sourceOrganization is therefore problematic. Fields that do not originate from these models (like kanalen), could be in English. But then we still have the problem like you describe... So, to make it consistent it would be Dutch.

BUT: What is more important we should write English documentation that explains the API's including all fields for foreign developers in order to create a level playing field for companies.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest zie eerdere user stories. Ik onderschrijf wat er staat maar is dit de hoogste prio? Zo niet...

**Comment by TCIMEddy** [comment]
wordt behandeld in #869 maar zal vanuit #869 verwijzen naar deze user story
