### ISSUE TITLE
Verwijder alle referenties aan OAS2 en maak er 3 van

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#855]
Dit is bij het ophalen van `/api/v1/schema.yaml` -> deze serveert nu OAS 2 ipv 3

Checklist:
- [x] ZRC
- [x] DRC
- [x] ZTC
- [x] BRC
- [x] NRC
- [x] AC

**Comment by sergei-maertens** [comment]
Alle componenten zijn nu voorzien van expliciete tests hiervoor & `develop` branches hebben de implementatie
