### ISSUE TITLE
Als zaakbehandelaar wil ik een nieuwe versie van een document kunnen toevoegen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#857]
zodat er niet 5 dezelfde soort documenten aan de zaak hangen zonder dat je weet wat de recentste versie is.

**Bepaling prioriteit door PO**

- [x] verbreding of verdieping API's
- [x] stimuleert gebruik door gemeenten
- [x] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prio bepalen

**Comment by joeribekker** [comment]
Deze US impliceert dat IO historie ondersteund.

* nieuwe velden:
  - `beginRegistratie` (formeel)
  - `eindRegistratie`
* we hebben niet:
  - `beginGeldigheid` (materieel)
  - `eindGeldigheid`
* query parameters: `?versie=` en `?registratieOp=`
* versie wordt per update automatisch opgehoogd
* checkout/lock en checkin/unlockis nodig (zie #903)
* men moet kunnen unlocken met bepaalde rechten (zie #904)
