### ISSUE TITLE
Als Consumer wil ik zelf kunnen bepalen welke Zaken/Documenten wel/niet aan gebruiker getoond worden 

### ISSUE THREAD

**Issue by MaartenRutten** [VNG-Realisatie/gemma-zaken#858]
...zodat een Consumer  alle ruimte heeft om eigen specifieke autorisaties te implementeren.

Voorbeeld:
De zaak 'Sollicitatie kandidaat-A' van het Zaaktype 'Afhandelen Sollicitatie' is Zaakvertrouwelijk wat betekent dat de behandelende HR-medewerker de zaak met documenten kan raadplegen MAAR dat een andere HR-medewerker met DEZELFDE autorisaties maar die NIET betrokken is bij de zaak, de zaak NIET kan inzien. 

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest bepalen of het kan en zo niet prio bepalen

**Comment by Hugo-ter-Doest** [comment]
- Gaat niet over notificaties (label eraf gehaald)
- De registratiecomponent heeft geen informatie over welke medewerkers bij welke zaken betrokken zijn en daarmee bepaalde documenten wel of niet mogen inzien. Het is aan de consumer om specifiekere autorisatie op niveau van individuele medewerkers te implementeren.
