### ISSUE TITLE
Schrijven testscenario's

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#860]
# Impediment

Het schrijven van de bijbehorende testscenario's is een taak van het team. Er is echter geen capaciteit voor, zeker gezien het feit dat er geen extra development capaciteit bijkomt. Tester is nodig

**Comment by joeribekker** [comment]
Ik wil hier een junior developer op zetten, die fungeert als tester.

Een developer weet gewoon hoe APIs werken, kan met Postman omgaan en kan eventueel ook nog foutmeldingen of situaties interpreteren voor ons :)

**Comment by wishalg** [comment]
@joeri @hugo ik heb zsm een opdrachtomschrijving nodig zodat ik dit snel ingang kan zetten.

**Comment by TCIMEddy** [comment]
Op close gezet aangezien testontwikkelaar gestart is
