### ISSUE TITLE
Als record manager wil ik een toelichting kunnen geven bij het wijzigen van de archiefnominatie & de archiefactiedatum

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#864]
zodat we ons als gemeente kunnen verantwoorden over waarom deze waarden gewijzigd zijn.

Extra toelichting:
Je wilt kunnen aangeven of een wijziging op de archiefnominatie & archiefactiedatum een correctie is ten gevolg van een fout ingevulde waarde of dat je bewust afwijkt van een eerder getelde norm.
Het gebeurt bijvoorbeeld wel eens dat er wordt bepaald dat een zaak een jaar langer bewaard moet worden dan volgens de selectielijst zou moeten. Je wilt je hier over kunnen verantwoorden waarom deze keuze is gemaakt.
Gerelateerd aan: #815

Gevraagde functionaliteit:
Mogelijkheid tot geven van toelichting bij wijzigen archiefnominatie en archiefactiedatum

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prio?

**Comment by joeribekker** [comment]
Dit valt op z'n plaats als toelichting-header, zodat dit ook als toelichting opgenomen kan worden in de auditlog.

**Comment by joeribekker** [comment]
Je kan per heden een toelichting bij ELKE API-call toevoegen middels de header `X-Audit-Toelichting`. Deze toelichting komt in de audit log terecht.
