### ISSUE TITLE
Als leverancier wil ik dat de documentatie in het Engels beschikbaar is

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#869]
...zodat ook leveranciers en ontwikkelaars die het Nederlands niet beheersen, kunnen werken aan oplossingen die gebruik maken van de ZGW API's.

zie ook #854 

Toelichting:
Dit draagt bij aan een level playing field voor leveranciers en ontwikkelaars van binnen en buiten Nederland en daarmee aan meer concurrentie.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Deze discussie komt steeds terug en dat begrijp ik. Qua prioritering wel even bepalen of dit bepalend is voor succes/release candidate.

**Comment by michielverhoef** [comment]
Misschien helpt deze regel uit de NL API Strategie:
https://geonovum.github.io/KP-APIs/#api-04-definitie-van-het-koppelvlak-is-in-het-nederlands-tenzij-er-sprake-is-van-een-officieel-engelstalig-begrippenkader

Wanneer alle overheids-API's zich hier aan houden is taalkeuze voor de OAS in ieder geval consistent Nederlands. Niet-nederlandstalige ontwikkelaars zullen hier dan een oplossing voor moeten vinden maar dat ligt buiten scope van de standaard.

**Comment by joeribekker** [comment]
@Hugo-ter-Doest Wat vind je dat minimaal moet worden vertaald?

- API spec
- Documentatie standaard
- Overige documentatie
- etc.

**Comment by jeffreygortmaker1** [comment]
MT VNG Realisatie heeft hierop in juni een standpunt ingenomen: alles enkel in het Nederlands.
Zal ik volgende week verder aan Hugo toelichten, maar bij deze alvast voor het geval ik het vergeet..

**Comment by Hugo-ter-Doest** [comment]
Als product owner ben ik het niet eens met het standpunt omdat er onmiskenbaar behoefte is aan Engelstalige documentatie en omdat het bij zou dragen aan het level playing field, maar ik sluit de user story als buiten scope.
