### ISSUE TITLE
Als ontwikkelaar wil ik inzicht in issues (500-errors) die spelen op de "test" omgeving

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#879]
...zodat deze op de radar komen en opgelost kunnen worden.

Mogelijke invulling: Een [Sentry](https://sentry.io/welcome/) installatie in Haven voor VNG.

Wel is de vraag wie dit in de gaten moet houden. Een beheerder die er issues voor aanmaakt of de ontwikkelaars zelf? In mijn optiek moet dit een DevOps zijn (hai Roderick) die het probleem reproduceert, mogelijk met configuratie al oplost en/of er een goede User Story voor aanmaakt zodat een ontwikkelaar deze snel kan oplossen.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prio?

**Comment by Hugo-ter-Doest** [comment]
Niet in dit project oplossen, maar aan het beheerteam doorgeven.
