### ISSUE TITLE
https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/overige/technisch/zds-vs-zgw.md

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#885]
docs/_content/overige/technisch/zds-vs-zgw.md

Aanvullen verbeteren om goed inzicht te krijgen (kwaliteit) wat nu en wat straks?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest zoals besproken in de call van 5 april 2019

**Comment by CMasselink** [comment]
Het overzicht van de api's klopt volgens mij.
1 opmerking over Ontkoppel Zaakdocument. Bij de voetnoot staat dat de functionaliteit om een relatie tussen een zaak en een document te verwijderen nog moeten toevoegen. Kunnen we dit niet al met 'objectinformatieobject_delete' vanuit het DRC?

Ik ben overigens ook erg benieuwd naar mogelijke userstories voor 'maakZaakdocument_EdcLk01'...

**Comment by TCIMEddy** [comment]
@joeribekker Kun jij de vraag van Constantijn beantwoorden?

**Comment by joeribekker** [comment]
> 1 opmerking over Ontkoppel Zaakdocument. Bij de voetnoot staat dat de functionaliteit om een relatie tussen een zaak en een document te verwijderen nog moeten toevoegen. Kunnen we dit niet al met 'objectinformatieobject_delete' vanuit het DRC?

Goed opgemerkt. Ik werk het bij.
