### ISSUE TITLE
Als zaakbehandelaar wil ik kunnen zien wat de waarde van de zaakgegevens + bijbehorende resources was

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#886]
zodat ik kan zien op basis van welke informatie een besluit tot stand is gekomen / een vergunning verleend is.

Extra toelichting:
De grootste uitdaging zit in deze userstory vermoed ik in de resources waarnaar we verwijzen met URL verwijzingen (en kunnen we dus ook niet oplossen vanuit dit team). Voorbeeld: een zaak wordt aan een burger gekoppeld. Het adres van de burger is relevant voor de behandeling van de zaak maar wordt niet bij de zaak opgeslagen. Adres wordt opgehaald via de URL referentie. Gedurende de behandeling van de zaak woont de burger op moment T op adres A maar op moment T + 30 dagen op adres B .
Je wilt kunnen tijdreizen om te kunnen zien wat het adres op moment T was.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
Prio?

**Comment by TCIMEddy** [comment]
Je wilt kunnen tijdreizen om te kunnen zien wat het adres op moment T was. => dit is niet in scope van zgw 2.0

**Comment by CMasselink** [comment]
Het voorbeeld van adres is uiteraard out of scope. Was meer als tijdreisvoorbeeld. Ik zal kijken naar eenzelfde voorbeeld voor zaakgegevens

**Comment by joeribekker** [comment]
Dit is eigenlijk "gewoon" formele historie, (devs lees: Reversion). Iets wat we toch al aanleggen voor audit trail in #722 maar nog niet via een API ontsluiten.

**Comment by Hugo-ter-Doest** [comment]
Er is een audit trail op de Besluiten API gerealiseerd.
