### ISSUE TITLE
Als zaakbehandelaar / zaaktypebeheerder wil ik versiebeheer kunnen toepassen op zaaktypes

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#887]
zodat aanpassingen aan een zaaktype niet doorwerken op bestaande zaken die al gemaakt zijn met het betreffende zaaktype.

Waarom is dit belangrijk: 
Voorbeeld is bijvoorbeeld maximale doorlooptijd en servicenorm. In een zaaktype kan je definiëren wat de maximale doorlooptijd van een zaak mag zijn. Deze informatie kan ook aan de burger gecommuniceerd worden. Als je dan een zaaktype gaat aanpassen zonder dat daar rekening wordt gehouden met versies, zit er ineens een andere doorlooptijd op bestaande zaken.
Levert ook problemen op met monitoring / rapportages.

**Bepaling prioriteit door PO**

- [x] verbreding of verdieping API's
- [x] stimuleert gebruik door gemeenten
- [x] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prio?

**Comment by erenes** [comment]
Zojuist liep ik hier tijdens het API lab ook tegenaan dus bij deze een korte beschrijving hoe deze gegevens bij ons worden opgeslagen: 
Een zaaktype heeft een centraal ID (uuid), op basis van dit ID bepalen wij altijd de laatste versie van het zaaktype en geven die terug. Daarnaast heeft een zaaktype ook een versienummer (numeriek), en een specifiek ID voor de versie van het zaaktype, zodat het mogelijk is ook oudere versies op te halen op basis van dat ID. 

Een paar ideeën over hoe dit geïmplementeerd zou kunnen worden (niet uitputtend): 
1) opnemen oude versies in gerelateerdeZaaktypen 
Voordeel: Hergebruik bestaand veld
Nadeel: Data moet altijd(?) worden teruggegeven terwijl dit waarschijnlijk zelden wordt gebruikt.

2) Extra api call zaaktypen/versies/:uuid (waarbij uuid = is zaaktype-id) 
Voordeel: Van elk zaaktype zijn alle versies op te halen, het type bericht 'zaaktype' wordt niet groter met elke nieuwe versie van een zaaktype. 
Nadeel: nieuwe API call om te implementeren.

3) We zouden ook de versie in het ID kunnen opnemen: zaaktypen/:uuid/:versie
Voordeel: Bij elke zaak is expliciet aangegeven om welke versie zaaktype het gaat. 
Nadeel: ?

Extra vragen die dit voor mij opwerpt: 
Geven we bij "list zaaktypen" alleen de laatste versies van alle zaaktypen terug, of alle versies? 
Is het relevant om te weten welk versienummer van het zaaktype je gebruikt?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Graag even kijken naar reactie van erenes. Prio is al zeer hoog en wordt waarschijnlijk volgende sprint opgepakt.

**Comment by Hugo-ter-Doest** [comment]
@erenes dank voor je ideeën. Je kunt met de datum waarop de zaak is gecreeerd de juiste versie van het zaaktype ophalen. <code>/api/v1/zaaktypen/a67b91?geldigOp=2020</code> Dat is hoe historie moet werken, en maak aanvullende API calls of uitbreiding van de verwijzing naar zaaktypen overbodig.

**Comment by erenes** [comment]
@Hugo-ter-Doest Alhoewel de geldigheidsdatum bij ons geen verplicht attribuut is, denk ik dat we dit wel op die manier kunnen implementeren (we weten tenslotte wel wanneer elk zaaktype historisch geldig was op basis van publicatiedatum).

 Ik vraag me hierbij wel af hoe specifiek de datum/tijd is waarop gefilterd zal worden (en wat het formaat is). Ik heb net even wat statistiek gedraaid op onze database (in totaal ~241000 gepubliceerde zaaktype-versies), en ongeveer 50% van alle zaaktypen worden binnen een maand vervangen door een nieuwe versie. Ongeveer 32% van onze zaaktypen worden binnen de eerste week van publicatie vervangen en 18% wordt binnen een dag vervangen. 

Daar staat tegenover dat ook 15% van de gepubliceerde zaaktypen maar één versie hebben en dus nog nooit zijn vervangen. 

In dat licht, als er wordt gevraagd om `/api/v1/zaaktypen/a67b91?geldigOp=2020`, verwacht je dan alle zaaktypen met id a67b91 die geldig waren in het jaar 2020? Of alleen één zaaktype? In het geval van het laatste: Welk zaaktype? Kan bijvoorbeeld ook opgevraagd worden welk zaaktype op 23 april 2018 om 9:15 geldig was?

**Comment by Hugo-ter-Doest** [comment]
Nee, ik verwacht alleen zaaktype /api/v1/zaaktypen/a67b91, en de datum 2020 is een voorbeeld. Moet natuurlijk een volledige datum zijn.

**Comment by joeribekker** [comment]
Zie https://github.com/VNG-Realisatie/gemma-zaken/issues/1182
