### ISSUE TITLE
Als zaakbeheerder wil ik dat altijd een _versie_ van een zaaktype aan een zaak gekoppeld wordt, 

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#889]
...zodat wijzigingen op een zaaktype geen invloed hebben op zaken die aan dat zaaktype gekoppeld zijn (een wijziging van het zaaktype moet dan ook altijd tot een nieuwe versie van het zaaktype leiden)

Hoe zie ik de oplossing voor me:
Bij een zaak moet een zaaktype in de vorm van een URI meegegeven worden. Deze URI wordt altijd vergezeld door een timestamp aan de hand waarvan de versie bepaald kan worden.

**Bepaling prioriteit door PO**

- [x] verbreding of verdieping API's
- [x] stimuleert gebruik door gemeenten
- [x] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prio?

**Comment by joeribekker** [comment]
Oplossingsrichting als volgt besproken:

Het ZaakType (bijv. `/api/v1/zaaktypen/a67b91`) toont altijd de  **actuele** versie volgens `beginGeldigheid` en `eindGeldigheid` zodat applicaties kunnen wijzen naar een bepaald (zonder versie) ZaakType en altijd de juiste gebruiken.

Stel, er zijn 2 versies van een ZaakType (met exacte datum begin/eind geldigheid maar ik noem even alleen het jaar), dan hebben we de volgende URLs:

* `/api/v1/zaaktypen/a67b91` (redirect -of- toont, in 2019, naar `/api/v1/zaaktypen/a67b91/1`)
* `/api/v1/zaaktypen/a67b91/1` (geldigheid=2019)
* `/api/v1/zaaktypen/a67b91/2` (geldigheid=2020)

Ook een query parameter moet werken: `/api/v1/zaaktypen/a67b91`?geldigOp=2020` redirect -of- toont altijd naar `/api/v1/zaaktypen/a67b91/2`

Je mag overigens nog steeds geen versie aanmaken met een beginGeldiggheid in het verleden.

**Comment by CMasselink** [comment]
> 
> 
> Oplossingsrichting als volgt besproken:
> 
> Het ZaakType (bijv. `/api/v1/zaaktypen/a67b91`) toont altijd de **actuele** versie volgens `beginGeldigheid` en `eindGeldigheid` zodat applicaties kunnen wijzen naar een bepaald (zonder versie) ZaakType en altijd de juiste gebruiken.
> 
> Stel, er zijn 2 versies van een ZaakType (met exacte datum begin/eind geldigheid maar ik noem even alleen het jaar), dan hebben we de volgende URLs:
> 
>     * `/api/v1/zaaktypen/a67b91` (redirect -of- toont, in 2019, naar `/api/v1/zaaktypen/a67b91/1`)
> 
>     * `/api/v1/zaaktypen/a67b91/1` (geldigheid=2019)
> 
>     * `/api/v1/zaaktypen/a67b91/2` (geldigheid=2020)
> 
> 
> Ook een query parameter moet werken: `/api/v1/zaaktypen/a67b91?geldigOp=2020` redirect -of- toont altijd naar `/api/v1/zaaktypen/a67b91/2`
> 
> Je mag overigens nog steeds geen versie aanmaken met een beginGeldiggheid in het verleden. En, de validatie op versiedatum en dat gedoe moet er gewoon uit. Zie ook #586


Ik snap de oplossingsrichting niet helemaal. 
Als ik goed begrijp wil je dat een taakapplicatie bij het maken van een zaak, altijd naar de actuele versie van een zaaktype kan verwijzen.  Dus: /api/v1/zaaktypen/a67b91.
Dit betekent dat /api/v1/zaaktypen/a67b91 daadwerkelijk als dan van toepassing zijnde zaaktype bij de zaak wordt opgeslagen.

Als er nu 5 dagen na het aanmaken van een zaak, een nieuwe versie van dit zaaktype wordt gemaakt, waarbij bijvoorbeeld de doorlooptijd wordt gewijzigd. Hoe zie ik dan nog wat de doorlooptijd was op het moment dat de betreffende zaak gemaakt werd? Door bij het opvragen van dat soort informatie altijd een geldigOP in de query parameter op te nemen?

**Comment by Hugo-ter-Doest** [comment]
@CMasselink Klopt, de beschreven oplossingsrichting geeft nog geen oplossing voor het verwijzen naar de juiste versie vanuit de zaak. Moeten we nog een keuze in maken. Zie ook #887 waar @erenes een paar opties geeft.

**Comment by michielverhoef** [comment]
Dat is eigenlijk ook hoe het met de huidige StUF ZKN / Zaak- Documentservices werkt: via de omschrijving en de ingangsdatumObject kun je het zaaktype zoals dat ten tijde van het aanmaken van de zaak geldig was ophalen.

**Comment by joeribekker** [comment]
Dit werkt impliciet doordat elke versie van een Zaaktype een eigen UUID en dus een eigen URL krijgt. Het kan dus niet zo zijn dat een Zaak per ongeluk aan een andere versie van hetzelfde zaaktype komt te hangen.
