### ISSUE TITLE
Als ZTC-inrichter wil ik meerdere statustypen kunnen markeren als eindstatus...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#895]
...zodat de zaak in meerdere status-progressies afgesloten kan worden.

Het BInG zaaktype van Utrecht kent 'ingetrokken' en 'afgehandeld' als statustypes, beide leiden tot het afsluiten van de zaak.

Kanttekening: misschien moet dit via resultaattype lopen?

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest trio?

**Comment by CMasselink** [comment]
@sergei-maertens ik ben het denk ik eens met je kanttekening. Dit lijkt iets wat je normaal in een resultaat oplost. Ik zie het overigens wel bij meer zaaktypen voorkomen. 
Voor ingetrokken kan ik het me ergens nog wel voorstellen, je zou kunnen stellen dat bij het intrekken een zaak niet afgehandeld is en dat dit dus een extra eindstatus zou rechtvaardigen.
Wat ik ook nog wel eens zie: meerdere eindstatussen waarmee eigenlijk een resultaat wordt weergegeven, dus een eindstatus 'goedgekeurd' en een eindstatus 'afgekeurd'. Dat zou je volgens mij echt in het resultaat moeten oplossen en niet met statussen. Dus een status afgehandeld met mogelijke resultaten goedgekeurd of afgekeurd.

**Comment by Hugo-ter-Doest** [comment]
Dit moet je inderdaad met resultaat oplossen, niet met statustype.

**Comment by sergei-maertens** [comment]
@aboerma jullie doen bij Exxellence wel aan meerdere eindstatussen begreep ik, hoe lastig is deze conclusie?
