### ISSUE TITLE
Als gemeentelijk ICT beheerder wil ik accounts en autorisaties op één plek kunnen beheren

### ISSUE THREAD

**Issue by markbacker** [VNG-Realisatie/gemma-zaken#898]
... zodat de CISO kan beoordelen of de autorisaties juist zijn en ik bij wijzigingen of problemen overzicht heb.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [x] stimuleert gebruik door gemeenten
- [x] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een beheerdocument voor het beheren van autorisaties
- [ ] Er is een referentieimplementatie autorisaties met beheerfunctionaliteit
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest goede user story en ook zeer relevant maar voor ons out of scope denk ik. Mooie om op bord toekomst te plaatsen zodat we dit niet vergeten. Maar Prio is uiteraard aan jou als product owner :-)

**Comment by Hugo-ter-Doest** [comment]
Inderdaad buiten scope. Zo'n applicatie (plek) kan gebruik maken van de Autorisatie API, maar moet koppelen met nog andere API's om ook gebruikersbeheer (accounts) te doen.
