### ISSUE TITLE
Als behandelaar van een zaak wil ik dat een zaak gestart in mijn vakapplicatie vastgelegd wordt op een plaats waar deze zaakgegevens gedeeld kunnen worden (zaaksysteem)

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#9]
zodat een persoon of vertegenwoordiger van een persoon met een zaak bij de/ een overheid`inzage heeft in de gegevens en documenten van deze zaak

**Comment by TCIMEddy** [comment]
@ehotting Volgens mij is dit een principe en is uitgangspunt in alle user stories .Ik zet het op wontfix en close. Mocht het niet kloppen dat uiteraard weer openen en op backlog
