### ISSUE TITLE
Als ontwikkelaar wil ik weten wat het uitgangspunt precies inhoudt...

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#90]
...zodat de basis voor de referentie implementatie goed neergezet kan worden.

Additionele toelichting:

Een van de te realiseren producten is een open source referentie implementatie van een ZRC waarin de nieuwe API specificatie is gebouwd. Voor gemeente Haarlem is reeds een open source ZRC gerealiseerd. Dit is *geen* referentie implementatie maar biedt wel de mogelijkheid om voortgang te versnellen door deze (deels) te (her)gebruiken.

Ik zie 4 mogelijkheden om als uitgangspunt te gebruiken:

* De laatste versie van het Haarlem ZRC
* Een uitgeklede versie van Haarlem ZRC (meerdere sub-mogelijkheden:)
  * Alleen de SOAP-services er uit
  * Alleen RGBZ datamodel behouden
* Een volledig nieuwe code base

**Definition of done**

- [ ] Er een basis om als uitgangspunt voor code te nemen

**Taken**

- [ ] Er moet een beslissing genomen worden welk uitgangspunt wordt gekozen

**Comment by BoerBas** [comment]
Wat is hier de taak? Wat mij betreft het ZRC van Haarlem, alleen de SOAP services er uit. Maar wie mag dit roepen?

**Comment by joeribekker** [comment]
Taak toegevoegd. Mijn mening hierover is dat we beter niet opnieuw kunnen beginnen, want dan is de opdracht verkeerd. We willen nu naar een AOS en referentie implementatie met als uitgangspunt RGBZ 2.0, dat is precies wat ook bij de Haarlemse ZRC is gedaan.

Als we van scratch beginnen zjin we eigenlijk RGBZ 2.0 opnieuw aan het implementeren.

**Comment by michielverhoef** [comment]
Eens met het idee om de huidige ZRC van Haarlem te gebruiken en de SOAP gebaseerde ZDS te vervangen door een nieuwe OAS api. Een compleet nieuw ZRC bouwen is niet handig, tenzij er goede redenen zijn (kan ze nu niet bedenken) om dit wel te doen.

**Comment by ehotting** [comment]
Wie beslist: Product Owner. Product owner zou technische beslissingen ook kunnen delegeren naar lead developer, maar in dit stadium is het goed zaken uit te argumenteren.

**Comment by joeribekker** [comment]
Om het zo basic mogelijk te houden, zou ik eigenlijk bijna alleen het RGBZ data model willen gebruiken. Dit is ook meer conform een referentie implementatie. Het Haarlem ZRC bevat nu enkele zaken die strict genomen buiten scope vallen. Mijn mening hierover:

Wat vervalt:

- De RGBZ 1.0 -> 2.0 vertaal laag (Uitgangspunt is RGBZ 2.0)
- Auditlog (Handig maar niet in scope, bovendien geent op SOAP services)
- SOAP stack (Tja, SOAP is geen REST)

Waar ik over twijfel:

- RSGB 3.0 datalaag (Dit zijn allerlei datamodellen die middels verwijzingen in RGBZ zijn opgenomen maar dit zou eigenlijk een andere API kunnen zijn)
- CMIS koppeling (ZDS impliceert Zaak- EN Documentservices, echter het is eigenlijk vreemd dat je via een Zaak API een Document moet inschieten. Waarom niet direct praten tegen de CMIS API vanuit de consumer = taakapplicatie?).

Wat behouden blijft:

- RGBZ 2.0 datalaag (In scope)
- Technische beheer interface voor RGBZ 2.0 (Handig voor data beheer via web interface en zeer weinig code waardoor het nauwelijks vervuilt)

Wat nieuw te ontwikkelen:

- REST API
- AOS specificatie

Overige overwegingen:

- RGBZ 2.0 is uitgangspunt maar bevat kopieën van het ZTC, voor bijvoorbeeld Zaaktype. Eigenlijk zou het Zaaktype niet in RGBZ moeten zitten maar alleen een verwijzing bevatten naar het Zaaktype in het ZTC.

**Comment by BoerBas** [comment]
Een aantal metaggevens over informatieobjecten zit in de ZRC. Dit zagen wij vanuit Haarlem ook liever niet, maar omdat we de standaard wilden volgen is dat wel gedaan. Al kan ik mij wel voorstellen dat gerelateerde dingen als bv besluit toch een referentie naar IO nodig hebben.

Dan ga je haast een kleine studie doen op verbeteringen en impact op het datamodel van Haarlem? Toch?

**Comment by ehotting** [comment]
Is dit een user story of een impediment?

**Comment by joeribekker** [comment]
Het is wat mij betreft niet blokkerend. Ik probeerde enigszins discussie uit te lokken met deze US om betrokkenheid bij wat er ontwikkeld wordt te vergroten en eventuele bezwaren en meningen uit te lokken. 

Het kan later alsnog anders

**Comment by ehotting** [comment]
Alles wat in de referentieimplementatie wordt toegevoegd moet ook worden onderhouden. Vanuit dat oogpunt is het verstandig de referentieimplementatie zo klein mogelijk te houden. "just enough"

**Comment by RvdKlip** [comment]
...dus eigenlijk van scratch af aan inrichten. 

Als we spreken over ZRC haarlem, is dat dan feitelijk een implementatie van alle functionaliteit uit de ‘Referentiecomponent Zaaksysteem (ZS)’ uit de ‘Standaard Zaak- en Documentservices (versie 1.2)’ ? Ook DMS functionaliteit. We hebben daar verder niets van gezien afgelopen 3 dagen.

In de standaard hadden we voorheen methoden voor zaakfunctionaliteit en documentfunctionliteit. Ik ben geen ontwikkelaar, maar het lijkt me handig om de bij de zaakbehorende informatieobjecten consistent af te handelen vanuit 1 en dezelfde api. De gegevenslaag moet dit uiteraard ook ondersteunen.

‘Eigenlijk zou het Zaaktype niet in RGBZ moeten zitten maar alleen een verwijzing bevatten naar het Zaaktype in het ZTC.’ Staat er in de RGBZ 2.0 standaard dat verwijzen niet mag dan?
Ik lees in de opdracht en rgbz2.0 ook iets over contactmomenten bijhouden. Ook daar zal moeten wordne verwezen naar crm tabellen of iets dergelijks.

**Comment by ehotting** [comment]
Ik merk in de discussie steeds verwarring over het verschil tussen informatiemodel (RGBZ) en datamodel (structuur van vastlegging in database(s) waarmee informatiemodel wordt vormgegeven. Wellicht moeten we dat even heel scherp neerzetten.

**Comment by joeribekker** [comment]
> Als we spreken over ZRC haarlem, is dat dan feitelijk een implementatie van alle functionaliteit uit de ‘Referentiecomponent Zaaksysteem (ZS)’ uit de ‘Standaard Zaak- en Documentservices (versie 1.2)’ ?
\- _RvdKlip_

Kort gezegd: Ja.

Voor Haarlem is _Referentiecomponent Zaaksysteem (ZS)_ het uitgangspunt geweest. Deze omschrijving staat in het [ZDS 1.2 pagina 10](https://www.gemmaonline.nl/images/gemmaonline/0/0e/Specificatie_Zaak-_en_Documentservices_v1.2.pdf):

> * Aanmaken, delen en wijzigen van zaken
> * Faciliteren van aanmaken, delen en wijzigen van zaakgerelateerde documenten (daadwerkelijke opslag vindt plaats in het DMS)
> * Genereren unieke zaakidentificatienummers
> * Genereren unieke documentidentificatienummers
> * Synchroniseren van zaakgegevens die zijn vastgelegd in het DMS o.b.v. CMIS;
> 
> Het ZS biedt bovenstaande functionaliteit aan middels services. De functionaliteit wordt niet
aangeboden via een userinterface.
\- _ZDS 1.2.0.1_

Volgens mij vond Haarlem de naam Zaaksysteem toch verwarrend en koos voor Zakenmagazijn omdat er geen user interface is. Ik vermoed dat VNG het toen opgesplitst heeft in Zaakregistratiecomponent (ZRC) en andere componenten. Dit lijkt ook ondersteund te worden door [Gemma Online](https://www.gemmaonline.nl/index.php/Zaakgerichtwerken/0.9/id-a97b6545-d5a7-485d-9b13-3ce22db5b9cf) met de definitie voor een ZRC: "Component voor opslag en ontsluiting van zaakgegevens."

> Ook DMS functionaliteit. We hebben daar verder niets van gezien afgelopen 3 dagen.
\- _RvdKlip_

Er zijn best een aantal user stories die dit toch impliceren: #11 #20 #21 #53 #54 #78 
We zullen er dus wel wat aan moeten doen maar ik denk dat [deze wijziging door Eelco](https://github.com/VNG-Realisatie/gemma-zaken/pull/91#event-1659751732) in de productvisie hier ruimte voor laat.

> In de standaard hadden we voorheen methoden voor zaakfunctionaliteit en documentfunctionliteit. Ik ben geen ontwikkelaar, maar het lijkt me handig om de bij de zaakbehorende informatieobjecten consistent af te handelen vanuit 1 en dezelfde api. De gegevenslaag moet dit uiteraard ook ondersteunen.
\- _RvdKlip_

Punt van discussie. Volgens mij maakt het eindgebruikers niets uit of het met 1 API of meerdere werkt, als het maar werkt. Technisch: Als je documenten en zaken via 1 API ontsluit in dezelfde datalaag dan maak je het onmogelijk de componenten los te vervangen (je zit dan bijvoorbeeld vast aan 1 leverancier voor je DMS en je ZRC - en waarschijnlijk de rest ook). Ik denk meer aan [microservices](https://en.wikipedia.org/wiki/Microservices):

> The benefit of decomposing an application into different smaller services is that it improves modularity and makes the application easier to understand, develop, test, and more resilient to architecture erosion.
\- _Wikipedia_

> Ik merk in de discussie steeds verwarring over het verschil tussen informatiemodel (RGBZ) en datamodel (structuur van vastlegging in database(s) waarmee informatiemodel wordt vormgegeven). Wellicht moeten we dat even heel scherp neerzetten.
\- _ehotting_

Ja. Ik betrap mezelf ook regelmatig op verwarring (in gedachten en in verwoordingen). Een referentie implementatie gaat echter ook uitspraken doen over de datamodellen, die dan voor het eerst - naar mijn weten - ook onder beheer van VNG Realisatie beheer gaan vallen.

**Comment by RvdKlip** [comment]
Opinie: het lijkt me niet dat we vanuit onze nieuwe standaard de leverancier een datamodel moeten opleggen, in de gedachtegang dat dit systeemspecifieke dingen zijn. Een juiste toepassing van het informatiemodel lijkt me wel onderdeel van de standaard. 

(is het wel de bedoeling discussies op deze manier in github te voeren of moet dat in slack?)

**Comment by ehotting** [comment]
Het gaat niet zozeer over het opleggen van een datamodel als wel "uitspraken over" het datamodel. Dat kan niet anders wanneer je aspecten als b.v. referentiële integriteit e.d. in ogenschouw neemt in een architectuur waarbij applicaties alleen nog de API zien. Precies hier zit de mismatch tussen het denken in informatiemodellen die gericht zijn op 'uitwisseling" (StUF = Uitwisselformaat) en het denken in API's die gericht zijn op gebruiken van data in de bron.

Deze discussie beter hier, dan kan men het nalezen. Op Slack is het vluchtig.

**Comment by jgortmaker1** [comment]
poging tot reactie (waar beginnen??? )

1. de ZDS API die we ontwikkelen verhoudt zich op geen enkele manier tot Zaaksystemen of DMSsen uit de huidige Zaak-documentservices. Architectuuruitwerking in de huidige ZDS was ondermaats. En nog gebaseerd op GEMMA 1. Dus beginnen we van scratch. Uitgangspunten: GEMMA 2. Katern ZGW. Uitwerking ZGW in GEMMA 2. (zie product vision en GEMMA Online). En Common ground.

2. RGBZ is idd een informatiemodel en geen datamodel. Bedoeld om een subset van informatie over een bepaald proces op een uniforme wijze te kunnen ontsluiten naar geïnteresseerden. Je kunt er dus niet alle informatie over een proces in kwijt (al kun je met de link met OBJECT en zaaktypespecifieke eigenschappen een eind komen). En dat moet je ook niet willen. Zie ook de uitwerking in GEMMA integratiepatronen ZGW (https://www.gemmaonline.nl/index.php/ZGW_in_GEMMA_2_compleet#Integratiepatronen_voor_Zaakgericht_Werken)

3. Het RGBZ zegt dus ook niets over wat waar is opgeslagen en dus ook niet welke gegevens wel of niet in de ZRC moeten worden opgenomen. Daar moeten we vanuit CG een eigen visie op ontwikkelen. Bv in de vorm van wat algemene principes. Hoe verhoudt een zaken-api zich tot bv persoons- of andere basisgegevens die wel bij een zaak horen, maar je niet in een zaak wilt opslaan. Maar ook: processpecifieke gegevens. Die kun je op zekere hoogte relateren aan een zaak, maar waar wil je die registreren en hoe link je dat met een API..

**Comment by ehotting** [comment]
@joeribekker @sergei-maertens Gelet op de orginele vraag, wat is nu wat Maykin de facto doet?

**Comment by joeribekker** [comment]
Voor het ZRC starten we vanaf scratch en wordt relevante code die al open source is ontwikkeld overgenomen. Per User Story wordt naar relevante code gekeken en wel/niet overgenomen.

Het open source ZTC zoals ontwikkeld door Haarlem wordt gecloned en door ontwikkeld met inzichten uit dit project. Hierin was al een REST API gemaakt op basis van DSO richtlijnen en vergt relatief weinig aanpassingen.

Eventuele overige componenten zijn volledig nieuw.

**Comment by ehotting** [comment]
Helder, dank. Hiermee sluiten we deze discussie, alleen over CMIS moeten we nog nader een besluit nemen want dat valt op deze manier buiten de boot. Openen we een issue voor.
