### ISSUE TITLE
Als behandelaar wil ik een informatieobject kunnen (un)locken 

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#903]
...zodat ik een nieuwe versie kan maken en uploaden zonder dat mijn collega's nieuwe versies kunnen uploaden.

**Bepaling prioriteit door PO**

- [x] verbreding of verdieping API's
- [x] stimuleert gebruik door gemeenten
- [x] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by joeribekker** [comment]
Semafoortje, Eddy

**Comment by michielverhoef** [comment]
Even voor de zekerheid: dat unlocken is dan alleen van je eigen informatieobjecten, niet die een ander in bewerking heeft?

**Comment by Hugo-ter-Doest** [comment]
Ja, en #904 zorgt ervoor dat er geen problemen ontstaan met gelockte documenten die maar niet vrijgegeven worden.

**Comment by CMasselink** [comment]
Deze functionaliteit heeft invloed op het afsluiten van een zaak:
Een zaak mag alleen afgesloten worden, als alle documenten geunlocked zijn.

**Comment by CMasselink** [comment]
@annashamray @sergei-maertens : Is mijn laatste opmerking over het aanpassen van standaard.md ook verwerkt? Ik kan het niet terug vinden, heropenen dus?
