### ISSUE TITLE
Als belanghebbende wil ik graag consistente naamgeving en consequente beschrijving van attributen in de ZGW-componenten

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#906]
...zodat het er netjes uitziet en er geen onduidelijkheid ontstaat.

Ook wordt een deel van de documentatie gegenereerd vanuit de API's wat een consistente en consequente naamgeving noodzakelijk maakt.

Belanghebbenden zijn ontwerpers, testers, developers, architecten, beheerders en diverse rollen bij gemeenten.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by EdwinCoster** [comment]
[RGBZ-ZGW-Historie.xlsx](https://github.com/VNG-Realisatie/gemma-zaken/files/3069004/RGBZ-ZGW-Historie.xlsx)

**Comment by EdwinCoster** [comment]
Bovenstaand een vergelijking tussen RGBZ/imZTC en ZGW API's. Per 11-04 staan hier ook een aantal vregen in m.b.t. o.a. de naamgeving van attributen. 
Dit is nog niet volledig. Ook de overige componenten dienen hierin te worden opgenomen. En de vergelijking met RGBZ/imZTC kan er waarschijnlijk wel uit. Maar dat is iets voor de uitvoering van sprint 14.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Prio?

**Comment by EdwinCoster** [comment]
Is dit gerelateerd aan #1121

**Comment by michielverhoef** [comment]
Waar het volgens mij aan ontbreekt (ontbrak?) is een duidelijke beschrijving van de betekenis en samenhang van attributen etc. 
In de komende releases (https://github.com/VNG-Realisatie/gemma-zaken/milestones) wordt het volledige RGBZ in de API's toegepast, dan kan dat ook gebruikt worden als extra informatie. Nu is dat nog een beetje een zoekplaatje (wat zit er wel/niet in etc.)

**Comment by michielverhoef** [comment]
Inmiddels zijn we zover dat het mogelijk is alle zaken van een bepaalde betrokkene op te halen dus de informatie kan via de API's opgehaald worden. Of dit getoond wordt in een portaal of anders gebruikt wordt, daar gaat de API standaard niet over.

Ik sluit dit issue.
