### ISSUE TITLE
Document relatie verwijderen werkt niet door in het ZRC

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#909]
# Bug

Het DRC maakt een relatie aan van het `(DRC) EnkelvoudigInformatieObject->(DRC) ObjectInformatieObject->(ZRC) Zaak`. In het ZRC komt vervolgens `(ZRC) Zaak->(ZRC) InformatieObject->(DRC) EnkelvoudigInformatieObject`

Door de relatie `(DRC) ObjectInformatieObject->(ZRC) Zaak` weet het DRC dus niet direct welke relatie `(ZRC) InformatieObject` hierbij hoort in het ZRC. Dit kan je alleen opvragen, door alle relaties af te gaan van de Zaak, en de relatie van het overeenkomende `(DRC) EnkelvoudigInformatieObject` te verwijderen.

**Comment by Hugo-ter-Doest** [comment]
Dubbel met wat is overgebleven van #696

**Comment by stevenbal** [comment]
@joeribekker 
pull request voor zds-client:
https://github.com/VNG-Realisatie/gemma-zds-client/pull/12

pull request voor DRC:
https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/pull/43

**Comment by joeribekker** [comment]
Deze PRs lossen het probleem technisch op maar ik ben niet overtuigd van de architectuur die ik beschrijf in het ticket. Ik laat het ticket even bestaan en zal in #20 dit aanmerken als opgelost.

**Comment by sergei-maertens** [comment]
Fixed als side-effect van het omkeren relatie + code-refactor.
