### ISSUE TITLE
Als ontwikkelaar wil ik het "reliability" niveau van het NRC weten

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#910]
...zodat ik hier bepaalde acties aan kan hangen.

Wat is het doel van het NRC? Kan ik het gebruiken voor (A) synchronizeren van bijv. relaties, of (B) is het niet erg dat er af en toe een notificatie verdwijnt door whatever reason?

We hebben hier geen uitspraak over gedaan en soms zeggen we A en soms B.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Voorlopig zou ik zeggen B.

**Comment by sergei-maertens** [comment]
We moeten iets zeggen over reliabability en de eisen, anders krijg je dat consumers/applicaties hier niet gaan op bouwen omdat er geen garanties zijn. We gaan er dus wel wat over zeggen, echter gaan we hier niet op focussen in de implementatie wegens de opgerekte scope.

Het huidige NRC + inrichting en hosting van andere componenten in kubernetes voldoet momenteel voor ons in hoeveelheid reliability (onze autorisatie sync steunt op notificaties).

We moeten beschrijven dat 100% reliability niet mogelijk is en dat applicaties hiervoor een fall-back mechanisme moeten voorzien.
