### ISSUE TITLE
Breng verbetering aan op https://ref.tst.vng.cloud/ontwikkelaars/guides

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/gemma-zaken#919]
# Scrumtaak

In stap 1 van de pagina waarop wordt uitgelegd hoe je autorisatie moet regelen is bullet 3 niet duidelijk. Er staat nu:

> 3. Bewaar de gegevens op de volgende pagina:
    - Client ID (bijv. mijn-consumer-RuAJiUr4sUQp)
    - Secret (bijv. qy7gBX1zZj06epGQeyX9KrBNTMUu6eefSecretqy7gBX1zZj06epGQeyX9KrBNTMUu6eef)

Wat die 'volgende pagina' is wordt echter niet duidelijk.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio en visie?

**Comment by TCIMEddy** [comment]
Update guides.md #972
