### ISSUE TITLE
Als behandelaar van een zaak wil ik dat de zaak nadat deze afgehandeld is gesloten wordt

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#92]
...zodat deze verwerkt kan worden volgens het geldende archief regime.

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite/VNG-Realisatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [@michielverhoef]
- [ ] Validatie op aansluiten bij informatiemodel en OAS 3.0/DSO API Strategie [@michielverhoef]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ArjanKloosterboer** [comment]
Wat bedoel je met
> ...zodat deze verwerkt kan worden volgens het geldende archief regime?

Als de zaak afgehandeld is, dan is ook het archiefregime bepaald en zijn de daarvoor benodigde parameters bij de zaak vastgelegd. Als dat nog zou moeten gebeuren, dan is 'ie nog niet afgehandeld.
En wat is het verschil tussen 'afgehandeld' en 'gesloten'? Ik zou het niet weten. Als 'ie afgehandeld is, krijgt 'ie een einddatum. Klaar. Niet meer aankomen ...

**Comment by jgortmaker1** [comment]
die moet wel goed gedocumenteerd worden, want sommige leveranciers zetten nu ene einddatum. anderen zetten de laatste status, anderen...
dit is nu een bestaand issue, dus een goede US wat mij betreft

**Comment by TCIMEddy** [comment]
@ehotting Ik weet niet of deze user story in deze vorm uitgevoerd gaat worde (wellicht bij een zaaktype). Mochten we deze generiek kunnen oppakken mooi anders close of op backlog houden

**Comment by ArjanKloosterboer** [comment]
Koppelen aan #161 en #351. Daarmee zou ie wel s afgehandeld kunnen worden.

**Comment by ehotting** [comment]
Dubbel, zie #161 en #351 die meer specifiek delen van deze user story behandelen.
