### ISSUE TITLE
Als gebruiker van de Docker's heb ik geen behoefte aan inlog beveiliging

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#924]
...waardoor ik soms wordt buitengesloten en mijn account moet resetten.

Dit betekent concreet dat Django-Axes er uit moet die wij standaard in elk project hebben zitten. De vraag is wel of deze er uit moet in de gehoste variant...

3 mensen liepen hier op dag 1 tegen aan. Makkelijk te verhelpen maar je moet wel weten hoe je je account reset.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Ik neem aan dat dit gaat om het inloggen in de admin interface van de registratiecomponenten. De beveiliging moet bij de gehoste componenten blijven bestaan. Voor de lokale componenten kun je het misschien uitzetten?

**Comment by michielverhoef** [comment]
In de huidige ZDS 1.2 standaard staat in hoofdstuk 3.1 Authenticatie opgenomen dat voor ontwikkel- en testdoeleinden een onbeveiligde verbinding ondersteund moet worden.

Misschien is dat via een instelling of opstartparameter te sturen? Het lijkt me wel verstandig als eis te houden dat bij acceptatie- en productieomgevingen een beveiligde verbinding etc.  verplicht is.

**Comment by sergei-maertens** [comment]
Valt makkelijk aan/uit te zetten via een environment variable, die we kunnen configureren in de `docker-compose.yml`

**Comment by TCIMEddy** [comment]
@sergei-maertens dus close toch?
