### ISSUE TITLE
Product en Diensten in moet duidelijk een lijst zijn in ZTC admin

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#925]
> Graag verifieren, controleren of er een reden voor is geweest om dit zo te doen, en anders fixen.

Dit is correct geimplementeerd MAAR het is onduidelijk in de admin dat dit een comma-seperated lijst betreft. Moet even aangepast worden in de admin interface zodat het niet doorlekt in de API spec.

**Comment by Hugo-ter-Doest** [comment]
imZTC zegt hierover:
> Om die reden modelleert KING een 1:n-relatie tussen zaaktypen in de ZTC en producten in de PDC. Uiteraard kan daarmee nog steeds ook een 1:1-koppeling tussen zaaktypen en producten worden geïmplementeerd.
(p. 9)

Een zaaktype kan dus meerdere producten/diensten opleveren. Moet een lijst zijn dus.
