### ISSUE TITLE
Bij DRC EnkelvoudigInformatieObject.formaat staat niet dat een MIME-type moet zijn

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#926]
Graag verifieren en fixen in de API spec docs.

**Comment by Hugo-ter-Doest** [comment]
p. 27 van RGBZ deel II:
> Het gaat hier om de bestandsoort van het enkelvoudig informatieobject. Het betreft het Dublin Core metadata-element ?Format? met als toelichting: Typically, Format will include the media-type or dimensions of the resource. Format may be used to identify the software, hardware, or other equipment needed to display or operate the resource. Examples of dimensions include size and duration. Recommended best practice is to select a value from a controlled vocabulary (for example, the list of Internet Media Types (MIME) defining computer media formats). Aangezien, bij bijvoorbeeld omzetting naar een duurzaam bewaarbaar informatieobject, het formaat kan wijzigen kent deze attribuutsoort historie.

Prima dus om MIME-types te gebruiken voor formaat.

**Comment by joeribekker** [comment]
> Het "Media Type" (voorheen "MIME type") voor de wijze waarop de inhoud van het INFORMATIEOBJECT is vastgelegd in een computerbestand. Voorbeeld: `application/msword`.
