### ISSUE TITLE
Als developer wil ik een werkende TDD dev-straat

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#93]
...zodat ik kan focussen op development terwijl zoveel mogelijk DevOps taken geautomatiseerd worden uitgevoerd.

**Definition of done**

- [x] er is infrastructuur waarop deployment plaats kan vinden
    - [x] Serveert op publiek IP adres met URL
- [x] er is een automation server voor builden, testen en deployment
     - [x] Automation server integreert met Github repository
          - [x] Triggert op PR's naar master branch
          - [x] Geeft resultaat build terug naar Github
          - [x] Builds & deploys na merge naar master branch
     - [ ] Automation server integreert met Slack
- [x] Tooling om OAS spec json/yaml file te genereren uit referentie-implementatie
- [ ] ~~Automatisch committen van OAS spec update bij mergen van user story~~
- [ ] er is basic alerting ingericht met Slack integratie
- [x] de componenten van de dev-straat zijn beschreven 

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- Waar mogelijk op basis van Open Standaarden

**Taken**
- [x] Regelen dat infra beschikbaar komt [@ehotting]
- [x] Access regelen voor @sergei-maertens [@ehotting]
- [x] DNS configuratie [@ehotting]
- [x] Opzetten tooling voor genereren OAS specs [@sergei-maertens]
- [x] Initieel inrichten NLX Jenkins [@ehotting]
- [x] Initieel inrichten Uptime Robot [@ehotting]
- [x] Integratie Github [@sergei-maertens]
- [x] Integratie Slack [@ehotting]
- [x] Documenteren dev-straat [@sergei-maertens]

**Comment by ehotting** [comment]
@sergei-maertens 
- Is Jenkins OK? Hebben we al draaien. 
- Aanvullingen voor DoD / taken?

**Comment by sergei-maertens** [comment]
Jenkins is prima, heb met beide ervaring.

I.v.m. met builden/testen denk ik dat Alfresco nog wel een aandachtspuntje is - hiervoor gebruiken wij nu op lokale machines een Vagrant box, maar die kan je niet bovenop een al gevirtualiseerde server regelen. Dus als Jenkins op bare-metal draait, dan komt er een taak bij om Vagrant (met VirtualBox provider?) te voorzien, of we moeten een alternatieve oplossing bedenken.

**Comment by ehotting** [comment]
Ik herinner me vaag dat @GeertJohan hier een oplossing voor heeft gemaakt...

**Comment by ehotting** [comment]
Overlap met #87 (sorry)

**Comment by ehotting** [comment]
@joeribekker Nog dingen toevoegen aan de DOD / AC / taken? Wat je schreef over Python bijv?

**Comment by joeribekker** [comment]
Denk dat het hier wel gecovered wordt, Python 3 support is nodig maar zal wel loslopen tenzij je Windows servers gaat voorstellen. Een betere acceptatie criteria is dat de ZRC van Haarlem er op moet kunnen draaien ipv een uitputtende lijst van requirements hiervoor.

**Comment by ehotting** [comment]
Komt goed.

**Comment by ehotting** [comment]
Jenkins moppert dat build fails omdat zetten van status nog niet lukt - moet even wachten op accepteren uitnodiging "collaborator"

**Comment by ehotting** [comment]
Welke public facing hosts hebben we nodig? Gaat me om DNS. Ik ga uit van domein vng.cloud.

Volgend de URI strategie van de DSO, de volgende suggestie:

**Referentieimplementatie API's:** ```
Productie:  https://data.vng.cloud/referentie/api/v1/zaken/
Test:           https://data.tst.vng.cloud/referentie/api/v1/zaken/

**API documentatie:**
Productie:  https://vng.cloud/docs/api/
Test:           https://tst.vng.cloud/docs/api/

**Comment by sergei-maertens** [comment]
@ehotting ik denk dat we ZRC, ZTC en DRC (en ondersteunend ORC) als losse, onafhankelijke componenten zien. Dus stel ik voor:

**Referentieimplementatie APIs**
*Productie*
* https://zrc-data.vng.cloud/...
* https://ztc-data.vng.cloud/...
* https://drc-data.vng.cloud/...
* https://orc-data.vng.cloud/...

Dit zullen infrastructuur-gewijs allemaal onafhankelijk gedeployde apps zijn, en ze hebben dan allemaal hun API spec beschikbaar op `/referentie/api/v1/openapi.yaml`. Indien ZRC/ZTC/DRC niet zouden uitgesplitst worden, dan moeten de specs samengevoegd worden in 1 bestand, en dat wordt onhandig.
