### ISSUE TITLE
Als gebruiker van het DRC weet ik soms het IO-type niet van te voren

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#930]
...dus kan ik geen IO aanmaken want IO-type is verplicht.

Concrete case kwam van Circle Software die aangaf dat (naast dat het anders werkt in hun eigen implementatie) dat als je een document in scant, het document wel gemaakt moet worden maar je weet niet wat je hebt gescant. Zij hebben hun software hierop aangepast zodat IO-type niet meer verplicht is, maar pas gezet wordt bij het relateren aan een Zaak.

Technisch valt dit prima op te lossen: Relatie met Zaak (of Object) mag alleen als IO-type bekend is.

Vraag is vooral of er argumenten zijn om dit NIET te doen.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Vooralsnog denk ik dat je dit niet moet toestaan. Je moet een soort invariant hanteren voor registratiecomponenten dat een minimale set metadata beschikbaar is voor alle geregistreerde informatieobjecten. IO-type hoort daarbij. Documenten waarvan het type nog niet bekend, leven nog even in de client van de registratiecomponent. Deze moeten nog door een soort intake voordat ze in de DRC kunnen worden geregistreerd.
