### ISSUE TITLE
Als gebruiker (consumer) van de API wil ik met 1 call veel informatie uit het ZTC trekken

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#932]
...zodat ik niet een call moet doen voor de Catalogus, het Zaaktype, en dan de Statustypen.

Aangebracht door Tilburg. Ik heb met ze besproken dat dit (nesten van resources) voor het ZTC nog wel zou kunnen omdat het een read-only API is op dit moment. Met schrijfacties wordt het lastiger om dit te doen. Ook over de `expand` parameter verteld om optioneel te nesten, maar deze zit er ook nog niet in.

Als ik er heel transparent over ben, begrijp ik dat dit als "complex" kan overkomen, maar dat is het natuurlijk niet. Complex betekent "ingewikkeld", en wat extra calls zijn niet ingewikkeld om te doen. Wel is het "convenient" als er meer data zou terugkomen maar het vergt best wat uitzoek werk wat dat dan precies moet zijn, en hoe diep je automatisch gaat.

Ik vraag me zelfs af of het niet complexer is dat je door data gaat spitten als je ALLES hebt binnen gekregen, dan gericht een call te doen en precies krijgt wat je wilt.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by michielverhoef** [comment]
Is dit gerelateerd aan #413 ?

**Comment by michielverhoef** [comment]
Opgenomen in Zaken API 1.5.0
