### ISSUE TITLE
UUID in de admin/detail is zonder streepjes

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#937]
# Bug

1. UUID formaat oplossen in admin
~~2. Oplossing bedenken voor wat we doen met attribuut identificatie~~
  a. Moet het nummer gaan heten?
  b. Moet de default geen UUID zijn?

**Comment by michielverhoef** [comment]
Volgens mij is dit niet zozeer een fout in de API als wel een gevolg van gedrag van ontwikkelaars: er wordt alleen naar de OAS3 gekeken en proefondervindelijk iets vastgesteld. De (functionele) documentatie (waaronder de beschrijving van het onderliggende informatiemodel) wordt niet of nauwelijks gelezen en daardoor onstaat deze verwarring. Eenzelfde iets leidde tot de vraag waarom een enkelvoudiginformatieobject niet gewoon document heet. Dat heette in StUF ZKN overigens ook al enkelvoudig document (edc) ;-)

Overigens zou ik de identificatie niet gewoon nummer noemen. Het is de identificatie van de zaak en er kunnen ook letters in voorkomen (dit gebeurt in de praktijk ook).  Dan zou ik het attribuut eerder zaakidentificatie (of documentidentificatie etc .) noemen. 

Dit komt ook terug in mijn bevindingen (observaties meer) die samen met die van Robert nog jullie kant opkomen.

**Comment by joeribekker** [comment]
> Volgens mij is dit niet zozeer een fout in de API als wel een gevolg van gedrag van ontwikkelaars: er wordt alleen naar de OAS3 gekeken en proefondervindelijk iets vastgesteld. De (functionele) documentatie (waaronder de beschrijving van het onderliggende informatiemodel) wordt niet of nauwelijks gelezen en daardoor onstaat deze verwarring.

Vandaar korte documentatie!
Maar ik vind het ook verwarrend. Puntje 1 is een bug (niet in API wel in Ref Impl). Puntje 2 is een verbetering. Even bij elkaar geveegd in dit issue maar wellicht niet moeten doen.

> Eenzelfde iets leidde tot de vraag waarom een enkelvoudiginformatieobject niet gewoon document heet. Dat heette in StUF ZKN overigens ook al enkelvoudig document (edc) ;-)

Niet "al" maar "nog". Je praat over [RGBZ 1.0](https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/enkelvoudig_document) maar in [RGBZ 2.0](https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/objecttype/enkelvoudig_informatieobject) heet het toch echt "EnkelvoudigInformatieObject"

> Overigens zou ik de identificatie niet gewoon nummer noemen. Het is de identificatie van de zaak en er kunnen ook letters in voorkomen (dit gebeurt in de praktijk ook).

Wellicht "referentie" dan, maar kan het ook "identificatie" laten. Denk dat als we een md5 hash van now() er in gooien als default dat het in ieder geval verwarring met het UUID voorkomt.

> Dan zou ik het attribuut eerder zaakidentificatie (of documentidentificatie etc .) noemen.

Dat nooit natuurlijk :)

**Comment by erenes** [comment]
Het is een beetje ambigu hoe over welke identificatie dit issue gaat, maar uit de context maak ik op dat het om zaken gaat? 

In ons systeem gebruiken we intern UUIDs als unieke identifiers, dit is niet heel leesbaar voor mensen natuurlijk. Een zaaknummer kan klantafhankelijk ingesteld worden, maar heeft over het algemeen het formaat: 
Z/19/012345 (waarbij Z = zaak, 19 = jaar, 012345 = volgnummer).
Documenten hebben meestal alleen een volgnummer (12345). 
Zaaktypen hebben bij ons niet per sé een human-readable identifier (ik zou dan willen terugvallen op de uuid). Maar ALS ze die hebben, hebben ze bijna altijd een alfanumeriek formaat, vaak een prefix met volgnummer: B001, LP000033, etc.

Hope this helps :)

**Comment by michielverhoef** [comment]
> Vandaar korte documentatie!
> Maar ik vind het ook verwarrend. Puntje 1 is een bug (niet in API wel in Ref Impl). Puntje 2 is een verbetering. Even bij elkaar geveegd in dit issue maar wellicht niet moeten doen.

Dit scheiden in 2 issues is inderdaad helderder.

> Niet "al" maar "nog". Je praat over RGBZ 1.0 maar in RGBZ 2.0 heet het toch echt 
"EnkelvoudigInformatieObject"

Ik had het inderdaad over StUF ZKN en RGBZ 1 maar de clou was natuurlijk "enkelvoudig". De constructie  van objecttypen Document, Enkelvoudig Document en Samengesteld Document bestond ook toen al.

> Wellicht "referentie" dan, maar kan het ook "identificatie" laten. Denk dat als we een md5 hash van now() er in gooien als default dat het in ieder geval verwarring met het UUID voorkomt.

Dat maakt inderdaad duidelijker dat de identificatie geen UUID is.  Het patroon van Erik vind ik overigens ook een mooie, dan is meteen duidelijk dat het geen UUID is en het is ook nog wel uit te spreken, mocht het nodig zijn.

**Comment by Hugo-ter-Doest** [comment]
UUID's zijn niet geschikt om aan de eindgebruiker te tonen. Maar voor eindgebruikers is er wel een behoefte om zaken, documenten, besluiten, etc. te kunnen identificeren in gesprekken in documenten. Tegelijkertijd zijn identificaties zoals in RGBZ zijn gedefinieerd niet meer nodig om objecten uniek te identificeren (daar hebben we nu URL + UUID voor). Het lijkt erop dat we identificatie nodig hebben voor communicatie. Eens?

**Comment by Hugo-ter-Doest** [comment]
Zie #970 voor een vriendelijke zaakidentificatie.

@joeribekker kun jij deze splitsen? Er is ook een relatie met de discussie over invulling van unieke verwijzingen naar zaken; niet de volledige URL, maar een pad.

**Comment by joeribekker** [comment]
#976 volgens mij. Bij deze opgesplitst

**Comment by joeribekker** [comment]
Volgens mij geen issue meer in stable/1.0.x
