### ISSUE TITLE
Het is niet duidelijk waar paginering begint met tellen

### ISSUE THREAD

**Issue by erenes** [VNG-Realisatie/gemma-zaken#942]
# Impediment
In ZTC, bij het ophalen van de lijst van resultaattypen kan een parameter 'pagina' worden meegegeven. De documentatie "A page number within the paginated result set." definieert niet wat de geldige waarden kunnen zijn voor een paginanummer.
 
In de meeste programmeertalen beginnen we met tellen bij 0, maar de meeste mensen zullen beginnen met tellen bij 1. Het is dus niet duidelijk wat de eerste pagina in een resultset zou moeten zijn, en wat het gedrag zou moeten zijn bij het meegeven van 0.
 
Negatieve getallen zijn ook impliciet toegestaan, maar het verwachte gedrag is niet gedefinieerd.
Mijn idee zou zijn om met negatieve getallen aan te geven dat je de vanaf het einde wilt terugtellen (bv: pagecount-1), maar dat lijkt me een interpretatie die per leverancier verschillend kan zijn als het niet in de standaard is opgenomen.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio?

**Comment by joeribekker** [comment]
Even documenteren, zoals deze: https://developer.github.com/v3/#pagination

Besluit is dat we 1-based aanhouden.
