### ISSUE TITLE
Het is onduidelijk welke URLs te gebruiken in resultaattypeomschrijving en selectielijstklasse

### ISSUE THREAD

**Issue by erenes** [VNG-Realisatie/gemma-zaken#943]
# Impediment
Het object ResultaatType heeft (o.a.) de verplichte eigenschappen: 

> **resultaattypeomschrijving** 
> Algemeen gehanteerde omschrijving van de aard van resultaten van het RESULTAATTYPE. Dit moet een URL-referentie zijn naar de referenlijst van generieke resultaattypeomschrijvingen. Im ImZTC heet dit 'omschrijving generiek'

Naast deze eigenschap, heeft een zaaktype ook een eigenschap "omschrijvingGeneriek". Dat is verwarrend, omdat volgens de api documentatie: resultaattypeomschrijving = omschrijving generiek in het ImZtc. 

Ervanuitgaande dat bovenstaande verwarring wordt opgeklaard, moet ik dit veld vullen met een URL. Ik heb binnen de API specificaties geen component gevonden die een referentielijst van  generieke resultaattypeomschrijvingen beschrijft, dus neem ik aan dat deze ergens anders online beschikbaar zou moeten zijn. Voor de implementatie is het handig als het duidelijk zou zijn waar deze lijst te vinden is. Misschien moet het een enum zijn? 
[**ImZtc over omschrijving generiek:**](https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/resultaattype.resultaattypeomschrijving_generiek)
>Het gaat om resultaten zoals 'verleend', 'toegekend', 'afgewezen', 'verwerkt', 'gegrond', 'ongegrond', 'geweigerd', 'niet nodig', 'ontvankelijk', 'niet ontvankelijk', 'vastgesteld', 'niet vastgesteld'. 

> **selectielijstklasse**
> Verwijzing naar de, voor het archiefregime bij het RESULTAATTYPE relevante, categorie in de Selectielijst Archiefbescheiden van de voor het ZAAKTYPE verantwoordelijke overheidsorganisatie. Dit is een URL-referentie naar een resultaat uit de selectielijst API

Voor de selectielijstklasse geldt dat wij in ons systeem daar een woordelijke beschrijving van hebben, bijvoorbeeld: 
>Gemeentelijke Selectielijst 1996, categorie 2.7

Het enige dat ik online heb kunnen vinden is een dode link naar een csv bestand met vastgestelde selectielijsten: 
https://data.overheid.nl/data/dataset/vastgestelde--selectielijsten

Ik heb geen Selectielijst API kunnen vinden. Uit de beschrijving maak ik op dat die wellicht per overheidsorganisatie bestaat? Als er wel een selectielijst API is lijkt het me verstandig om instructies hoe deze te vinden op te nemen in de spec. Als deze niet bestaat zou ik dit graag als vrije tekst kunnen teruggeven.

Deels worden deze zorgen denk ik gedeeld in het api-beheer issue 86:
https://github.com/VNG-Realisatie/api-beheer/issues/86
(een van de hits op google als ik zoek op selectielijst api)

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio en visie?

**Comment by joeribekker** [comment]
Alvast een vraag beantwoorden:

> Het enige dat ik online heb kunnen vinden is een dode link naar een csv bestand met vastgestelde selectielijsten:
> https://data.overheid.nl/data/dataset/vastgestelde--selectielijsten

VNG is bronhouder van de Selectielijst Gemeenten. Hoewel deze zeker niet fijn te vinden is, staat deze hier:

https://vng.nl/onderwerpenindex/dienstverlening-en-informatiebeleid/archieven/nieuws/selectielijst-gemeenten-en-intergemeentelijke-organen-2017

> Ik heb geen Selectielijst API kunnen vinden. Uit de beschrijving maak ik op dat die wellicht per overheidsorganisatie bestaat? Als er wel een selectielijst API is lijkt het me verstandig om instructies hoe deze te vinden op te nemen in de spec. Als deze niet bestaat zou ik dit graag als vrije tekst kunnen teruggeven.

Deze is nog niet officieel. Sterker, het is op dit moment een snelle API ontwikkeld tijdens een sprint bij ZGW als bijproduct (!). Wij van ZGW proberen deze API een officiele status te geven (het is immers een 1-op-1 vertaling van de Excel maar dan wel netjes). Dit moet echter een behoorlijke politieke molen door, wat al begint bij dat ZGW onder VNG Realisatie valt, en de Selectielijst onder VNG....

De API die je (denk ik) zoekt, staat hier:

* API endpoint: https://ref.tst.vng.cloud/referentielijsten/api/v1/
* API schema: https://ref.tst.vng.cloud/referentielijsten/api/v1/schema/

Op dit moment hebben we em geschaard onder "referentielijsten" omdat we ook een lijst van erkende landen, talen, etc hierin verwachten maar ik vermoed dat hij uiteindelijk als aparte API komt.

**Comment by erenes** [comment]
@joeribekker Bedankt voor de antwoorden, hier kan ik alvast mee uit de voeten :)

**Comment by Hugo-ter-Doest** [comment]
Ik sluit deze af. Als er nieuwe vragen zijn over dit onderwerp graag een nieuw issue openen.
