### ISSUE TITLE
Als berichtontwikkelaar Open RaadsInformatie wil ik een relatie kunnen leggen tussen een informatie object en de objecten "Vergadering" en "Agendapunt" zodat alle informatieobjecten die gerelateerd zijn aan Raads- of Staten informatie 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/gemma-zaken#951]
zodat voor alle informatieobjecten die gerelateerd zijn aan Raads- of Staten informatie de relevante relatie kan worden uitgewisseld. 

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by JohanBoer** [comment]
Het gaat hier om het vanstleggen van een informatieobject als bijlage bij een vergadering of bij een agendapunt. 

Ter verduidelijking een snapshot van het relevante deel van het model voor open-raads- en stateninformatie.

![image](https://user-images.githubusercontent.com/18071357/56883403-e0121280-6a66-11e9-9e73-74d9b9e2db5e.png)

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest graag prio en visie

**Comment by JohanBoer** [comment]
Na wat discussie ben ik tot de conclusie gekomen dat het leggen van deze relatie niet in de DRC plaats dient te vinden, maar in de Open raads- en staten informatie component. Wat mij betreft kan deze dus weer van de lijst af. Sorry voor de overlast.
