### ISSUE TITLE
Als Berichtontwikkelaar Open Raads- en stateninformatie wil ik de mogelijkheid hebben om aan te geven wie een informatieobject heeft ingediend

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/gemma-zaken#952]
...zodat de indiener toelichting kan geven op zijn ingdeniende stuk en/of terugkoppeling kan ontvangen op de behandeling van het ingediende document.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest visie en prio

**Comment by JohanBoer** [comment]
Een vergelijkbare koppeling is nu via de "betrokkene"ook gerealiseerd voor zaak. Ik kan me voorstellen dat deze relatie op een vergelijkbare manier wordt gelegd tussen een informatie-object en een natuurlijk persoon óf een organisatie. 

In het model van open raads- en stateninformatie is dat als volgt gemodelleerd, maar dat kan uiteraard aangepast worden als er binnen het DRC voor een andere oplossing gekozen wordt. Dit is een functionele wens en ORI conformeert zich aan de technische uitwerking in de DRC- API-standaard.

![image](https://user-images.githubusercontent.com/18071357/56883910-5ebb7f80-6a68-11e9-8c1f-a8737e2ab559.png)

**Comment by Hugo-ter-Doest** [comment]
Ik zou de user story graag anders geformuleerd zien, nl. vanuit medewerker of gemeente. Als medewerker van het secr. wil ik de indiener van een voorstel kunnen koppelen aan een document zodat ...

Verder is het evident dat de DRC zal worden gebruikt voor raadsinformatie. Echter zullen we dit niet in deze tranche van het project realiseren. Ik sluit hem als buiten scope en plaats hem op het juiste vord.
