### ISSUE TITLE
Resultaattype.brondatum_archiefprocedure_procestermijn wordt incorrect weergegeven in ZTC admin en veroorzaakt bug met serialisatie

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#954]
# Bug

Twee problemen, beide in het ZTC voor het ResultaatType:
1. Bij het aanmaken van een ResultaatType met brondatum_archiefprocedure_afleidingswijze `procestermijn` en brondatum_archiefprocedure_procestermijn gezet (bijv. `P5Y`), wordt de waarde voor brondatum_archiefprocedure_procestermijn weergegeven als een relativedelta i.p.v. een duration in ISO8601 formaat
2. Bij het ophalen van een of meerdere ResultaatTypen via ZTC api wordt brondatum_archiefprocedure_procestermijn niet goed geserialized, en wordt de volgende error gegeven door het ZTC:

`TypeError: Object of type 'relativedelta' is not JSON serializable`

**Comment by stevenbal** [comment]
PR voor deze issue:
https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/37

**Comment by sergei-maertens** [comment]
Fixed in ZTC@0.11.1
