### ISSUE TITLE
Inrichten ZGW Docker image(s) tbv API test-voorziening

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/gemma-zaken#965]
# Impediment

Momenteel hebben we de API test-voorziening gekoppeld aan een Kubernetes cluster waarop automatisch pods worden gestart. Dit doen we nu met Joeri's Demo-API Docker image, en dit werkt zoals verwacht.

De volgende stap is het mogelijk maken dat de ZGW API Docker images via ATV's Kubernetes cluster automatisch kunnen worden opgestart, echter we hebben te beperkte kennis van de onderlinge afhankelijkheden tussen de ZGW images om dit zelf uit te voeren.

Dit hebben we beschreven in een ATV story:

https://github.com/VNG-Realisatie/api-testvoorziening/issues/91

We zouden graag zien dat @sergei-maertens hier in ons assisteert. Dan kunnen wij aan onze kant zorgen voor de benodigde aanpassingen aan het ATV om vanuit het test-platform 'eigen' ZGW omgevingen te kunnen starten.

[assign aan Eddy, voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by TCIMEddy** [comment]
@wishalg ter info @Hugo-ter-Doest visie?

**Comment by TCIMEddy** [comment]
Het is uiteraard een impediment voor testvoorziening maar aangezien inzet Sergei gevraagd wordt ook voor ons

**Comment by wishalg** [comment]
@TCIMEddy is dit iets dat Roderick kan oppakken?

**Comment by Hugo-ter-Doest** [comment]
Hoe groot is dit (in punten)?

**Comment by TCIMEddy** [comment]
@wishalg sorry kan ik lastig beoordelen (en is voor testvoorziening)

**Comment by alextreme** [comment]
Ik verwacht dat we met een halve dag Sergei voldoende hebben hiervoor.

**Comment by Hugo-ter-Doest** [comment]
Ok, moeten we doen!

**Comment by TCIMEddy** [comment]
@HenriKorver zie beslissing Hugo

**Comment by HenriKorver** [comment]
Ben blij met de reactie van Hugo, maar wil dit issue pas sluiten wanneer de ZGW Docker image daadwerkelijk ingericht is voor de API Testvoorziening

**Comment by TCIMEddy** [comment]
prima

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest nog impediment nog in sprint 14 zo niet graag close

**Comment by sergei-maertens** [comment]
@alextreme -  Alvise was informed about how everything works together, I'm available for more questions and the docker images now have support for loading fixtures during startup time. This provides enough tooling to spin up environments as you'd like. It's not the most user-friendly yet, but we can point at the right things :-)
