### ISSUE TITLE
Als gemeentemedewerker wil ik dat de informatie op GEMMA Online aansluit op de ZGW API's

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#967]
...zodat ik de nieuwe standaarden kan plaatsen en weet voor welke referentiecomponenten en systemen die deze implementeren relevant zijn.

NB. Op dit moment staan voor de referentiecomponenten alleen nog de StUF standaarden als verplichte standaarden benoemd. In ieder geval moeten daar de ZGW API's bij komen en mogelijk vervangen de API's de StUF standaarden helemaal? Over dit laatste zal nog een beslissing genomen moeten worden door oa. het expertisecentrum architectuur. 

Zie ook https://www.gemmaonline.nl/index.php/GEMMA2/0.9/id-a97b6545-d5a7-485d-9b13-3ce22db5b9cf

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by melsk-r** [comment]
Hoi Hugo,

Ik kan me voorstellen dat je vindt dat deze userstory niet moet worden doorgevoerd i.h.k.v. het ontwikkelen van de standaard en Referentie Implementatie en dat hij daarom out-of-scope is voor jou.
Het is n.m.m. echter zeker een activiteit die moet worden uitgevoerd voor 18 juli zodat men straks tegelijkertijd met het uitbrengen van de release candidate ook informatie over de nieuwe standaard op GEMMA Online kan vinden.
Je hebt eerder Michiel al verzocht voor het ZGW project de documentatie bij te werken en volgens mij kunnen we deze activiteit daar ook in onderbrengen. Ik ben daarom zo vrij om deze userstory weer te heropenen.

Als je desondanks vindt dat deze userstory gesloten moet worden dan hoor ik graag van je waarom je dat vindt.

**Comment by Hugo-ter-Doest** [comment]
Omdat het een acceptatiecriterium is...

**Comment by melsk-r** [comment]
Maar als het een acceptatiecriterium is dan moet het i.i.g. uitgevoerd worden. Het opvoeren van een userstory waarborgt dat dit gebeurd en niet vergeten wordt. 
Wellicht moet het geen userstory zijn maar een taak maar het moet i.i.g. in de backlog kunnen worden gezet.

**Comment by Hugo-ter-Doest** [comment]
Nee, zo werkt scrum nu eenmaal niet.

**Comment by melsk-r** [comment]
Ik ben het hier niet mee eens! Of het nu een acceptatiecriterium is of niet het is wel een activiteit die uitgevoerd moet worden. Daarom voeren we dit issue op. Of moeten we nu weer in een heel ander systeem een ticket inleggen om er voor te zorgen dat we het niet vergeten. 
Ik begrijp het argument 'zo werkt scrum nu eenmaal niet' ook niet.
