### ISSUE TITLE
Als ontwikkelaar wil ik dat de API's gebruik maken van zichzelf

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#968]
...zodat elke actie op een resource altijd op dezelfde manier gebeurt en er geen onder water acties bestaan die niet duidelijk zijn.

Toelichting: Bij het verwijderen van een zaak worden alle gerelateerde objecten en relatieklassen ook verwijderd. Echter, voor lang niet alle gerelateerde objecten en relatieklassen bestaat er een DEL API call. Deze worden dan waarschijnlijk onder water verwijderd. 

In het kader van "eat your own dogfood" zou eigenlijk elke bewerking op een resource via een API call gedaan moeten worden. Nu is een deel van de werking afgeschermd en niet duidelijk hoe of waar iets precies gebeurt.

Zie ook: https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_delete 

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Is geen user story, meer een uitgangspunt.

**Comment by Hugo-ter-Doest** [comment]
Nog een keer naar dit issue gekeken, En ik vind niet belangrijk hoe de API subresources opruimt. Het gaat om het extern waarneembaar gedrag, niet hoe de registratie onder water werkt.
