### ISSUE TITLE
Als PO wil ik de referentie-implementaties en documentatie migreren van NLX naar Haven

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#973]
...zodat beschikbaarheid gegarandeerd is.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] ~~verbreding of verdieping API's~~
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] ~~de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.~~
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] ~~Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.~~
- [ ] ~~De technische specificatie (standaard.md) is gepubliceerd leesbaar~~
- [ ] ~~Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.~~

**Acceptatiecriteria**
- [ ] ~~De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze~~
- [ ] ~~Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.~~

**Taken**
- [x] Haven moet shared storage ondersteunen _(@kciredor)_
- [x] Admin gebruiker voor gemma-namespace in Haven _(@kciredor)_
- [x] Kubernetes PostgreSQL configuratie moet shared storage gaan gebruiken _(@sergei-maertens)_
- [x] Hello World
- [x] Kubernetes Ingress configuratie moet gebruik maken van Traefik i.p.v. Nginx _(@kciredor)_  _(@sergei-maertens)_
- [x] Kubernetes configuratie: requests/limits instellen in yaml-bestanden _(@sergei-maertens)_
- [x] Kubernetes configuratie: healthz endpoint instellen _(@sergei-maertens)_
- [x] Not migrating jenkins vm to Haven because Sergei will migrate from jenkins to travis anyway
- [x] Deployments vanuit Jenkins naar Haven _(@sergei-maertens @kciredor)_
- [ ] Zodra @sergei-maertens zo ver is met forwarding docker image: `ref.tst.vng.cloud` naar Haven via @kciredor
- [ ] Backups -> waar nodig, is het nodig nu?
- [ ] OTAP inrichten -> lijkt me uit scope van de migratie van oud naar nieuw cluster en deze story?
- [x] Domeinen in uptime-robot (@sergei-maertens)
    - [x] zaken-api.vng.cloud
    - [x] documenten-api.vng.cloud
    - [x] catalogi-api.vng.cloud
    - [x] besluiten-api.vng.cloud
    - [x] notificaties-api.vng.cloud
    - [x] autorisaties-api.vng.cloud
    - [x] zaken-auth.vng.cloud
- [x] Migreren database content
- [ ] Debug deploy annotations - docs gaan nu niet mee (tenzij we gaan taggen & Jenkins job aanpassen)

@kciredor Commando om te deployen vanaf Jenkins: `ssh console.nlx /snap/bin/kubectl --namespace=gemma set image deployment/zrc zrc=vngr/gemma-zrc:0.14.0`

*We schatten in dat er 3 dagen nodig is voor het geheel, waarbij er geschakeld moet kunnen worden met het ZGW team*

**Comment by kciredor** [comment]
Zie: https://gitlab.com/commonground/haven/issues/8

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest @joeribekker Neem ook verschillende omgevingen mee (OT)AP

**Comment by Hugo-ter-Doest** [comment]
@TCIMEddy dank voor de tip. We moeten een acceptatie en productieomgeving van iedere API hebben en we moeten de actuele en vorige versie van iedere API kunnen aanbieden. Op dit moment ga ik nog uit van versionering per API, en voor de gehele set API's. Dit is nog onderwerp van overleg.

We streven ernaar de overgang naar HAVEN te maken voor 18-7.

**Comment by kciredor** [comment]
Aanvulling dns: *.vng.cloud is nu in beheer van Haven. Niet meer nodig om *.haven.vng.cloud te gebruiken. Dus delegated zone deleten, vng.cloud zone cleanup (domainkey tenzij mail, deny spf, naked domain pointers, andere evt. leftover subdomains) en uitbreiden met nieuwe subdomains.

**Comment by RitaBerghuis** [comment]
Zorgen jullie er wel voor dat als mensen nog gebruik maken van ref.tst.vng.cloud, ze doorgelinkt worden naar het nieuwe domein? Waarschijnlijk een overbodige vraag, maar in de marktconsultatie verwijs ik nu nog naar ref.tst.vng.cloud

**Comment by sergei-maertens** [comment]
Redirects zijn inderdaad ingesteld, dank je voor de reminder :+1:
