### ISSUE TITLE
Als gemeente wil ik dat de registratiecomponenten gebruikersvriendelijke unieke identificaties genereren als de identificatie niet wordt meegegeven

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#976]
...zodat ik niet zelf identificaties hoef te genereren.

Geldt i.i.g. voor zaken, informatieobjecten, besluiten.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by CMasselink** [comment]
Qua werk voor ons vraagt dit denk ik de volgende zaken:
Gewenst gedrag / functionaliteit in standaard.md beschrijven. Mijn voorstel zou zijn om te specificeren dat de identificatie human readable moet zijn maar om de implementatiewijze vrij te laten. 
Referentie implementatie ZRC aanpassen zodat een human readable identificatie gemaakt wordt als er geen identificatie aangegeven wordt

**Comment by TCIMEddy** [comment]
de provider zou een gebruikersvriendelijk nummer terug moeten geven voor het veld identificatie.

**Comment by joeribekker** [comment]
Lekker concreet allemaal "human readable", "gebruiksvriendelijk"... De specificatie geeft op dit moment niet aan dat een identificatie een UUID moet zijn, maar een uniek waarde.

**Voorstel**

Om in ieder geval makkelijker onderscheid te maken tussen de "UUID van de Zaak" en de "identificatie van de Zaak", kunnen we `<TYPE>-<JAAR>-<10-PADDED-VOLGNUMMER>` hanteren.

Dus concreet:

* ZAAK-2019-0000000001, ZAAK-2019-0000000002, ZAAK-2019-0000000003, etc.
* DOCUMENT-2019-0000000001...
* BESLUIT-2019-0000000001...

**Comment by Hugo-ter-Doest** [comment]
ja, prima, zoiets bedoelen we.
