### ISSUE TITLE
Als gemeente wil ik betrokkenen aan de zaak kunnen koppelen met BSN dan wel Vestigingsnummer dan wel KVK-nummer

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#980]
...zodat ik betrokkenen in het huidige gegevenslandschap kan opvoeren.

...omdat personen en bedrijven nog niet via URI's kunnen worden ontsloten.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by sergei-maertens** [comment]
* URL eruithalen
* identificatie veld toevoegen
* type-veld behouden

**Comment by Hugo-ter-Doest** [comment]
BSN of een groep identificerende gegevens om burger te koppelen als betrokkene.

**Comment by joeribekker** [comment]
Conclusie:

* Het ORC expliciet bestempelen als tijdelijke "bron"
* In het ORC komen ook: Vestiging en OrganisatorischeEenheid (totaal dus alle 5 de betrokkene resources)
* De identificerende (matching gegevens) komen zeker in elke resource
* De overige attributen blijven er uit (maar we zien de "noodzaak" dat alle attributen uit het RGSB worden opgenomen tzt).

**Comment by CMasselink** [comment]
@joeribekker hoe gaan we resources opvoeren? 
Stel: persoon X is de initiator voor zaak A. Persoon X is ook de initiator op zaak B.
Gaat persoon X als twee resources in het ORC opgevoerd worden met elk een eigen verwijzing naar de eigen zaak (zaak A en zaak B)? 
Of voeren we persoon A 1x op in het ORC en koppelen deze persoon aan meerdere zaken?

Eigenlijk is in beide gevallen versiebeheer op de attributen belangrijk:
Als persoon X verhuist, wil je niet dat je niet meer kan zien op welk adres deze persoon woonde op ten tijden van een oudere zaak.

**Comment by joeribekker** [comment]
@CMasselink 

> Stel: persoon X is de initiator voor zaak A. Persoon X is ook de initiator op zaak B.
> Gaat persoon X als twee resources in het ORC opgevoerd worden met elk een eigen verwijzing naar de eigen zaak (zaak A en zaak B)?
> Of voeren we persoon A 1x op in het ORC en koppelen deze persoon aan meerdere zaken?

Ik kom niet uit op een goed antwoord met de huidige insteek (stop gegevens in ORC). Je conclusie van versiebeheer is namelijk correct en dat wil ik echt vermijden, aangezien dit thema buiten scope valt, en we zouden het dan realiseren vaan een API die elders ook al is/wordt ontwikkeld.

Mijn redenatie is als volgt: Het liefst wilde ik referenties gebruiken naar een persoon. Als het om dezelfde persoon gaat, wil naar deze persoon voor elke zaak in principe verwijzen (want CG visie: niet kopieren/dubbel opslaan).

Je wilt op op het moment dat je persoonsgegevens hebt, deze  zoals ze op dat moment zijn, altijd beschikbaar hebben bij de Zaak. Je wilt niet dat deze persoonsgegevens worden bijgewerkt later. Dit kan dus op 2 manieren:

1. Verwijzen naar een bron met tijdreizen `/personen/7825?geregistreerdOp=2018-10-22`
2. De persoonsgegevens die op dat moment bekend zijn, opslaan bij de Zaak (of gerelateerde resource)

Probleem met oplossing 1 is dat deze API er niet binnenkort zal zijn en dat wij hem niet op deze manier "even snel" kunnen realiseren. Daarnaast is het de vraag of je wel echt een verwijzing naar deze persoon wilt hebben, in plaats van simpelweg wat gegevens die op dat moment van toepassing waren.

Probleem met oplossing 2 is dat als we dat in een ORC doen, dan krijgen we dus voor elke betrokkene bij elke zaak, een NatuurlijkPersoon (of Vestiging, etc.) object in een ORC. Er komen dus VEEL "dubbele" persoon registraties in, wat straks lastig te migreren is naar een BRP achtige API oplossing waar er dus maar 1 object per NatuurlijkPersoon zal zijn.

Mijn voorstel is daarom om NatuurlijkPersoon, Vestiging, etc. NIET op te nemen in een ORC maar deze onderdeel te maken van het ZRC met daarin de kerngegevens EN een optioneel URL-attribuut voor een eventuele verwijzing naar de bron. Dit adresseert de genoemde problemen als volgt:

1. We slaan de persoonsgegevens op zoals ze zijn op dat moment, zonder gebruik van versie beheer.
2. Er is geen centrale API (het ORC) waar je alle NatuurlijkePersonen kan opvragen en dus heel veel dubbelen krijgt. Je kan de NatuurlijkePersonen immers alleen van de Zaak krijgen.
3. Deze persoonsgegevens kan je zien als een kopie van BRP gegevens. Echter, ik vind dit niet persé tegen Common Ground in gaan. Het doel is immers niet een verwijzing krijgen naar ALLE persoonsgegevens zoals deze in BRP staan.

TBC

**Comment by sergei-maertens** [comment]
Gedragen door het team met ongeveer 50/50 +1 en 0+

**Comment by joeribekker** [comment]
Na refinement over bovenstaand voorstel gestemd:

- Edwin: +0
- Hugo: +1
- Joeri: +1
- Sergei: 0+
- Ivo: 0
- Henri: +0.5
- Michiel: +0
- Robert: +0
- Robert: +Edwin
- Eddy: +1

Er waren geen negatieve stemmen.

**Comment by CMasselink** [comment]
@joeribekker een gedeelte van de problematiek beschrijf je in 'grenzen van het API-lanschap omschreven', ik denk dat het verstandig is om de keuze ook ergens bij de ontwerpkeuze vast te leggen, eens? Of had jij het api landschap document als dusdanig bedoeld?

**Comment by EdwinCoster** [comment]
Consequentie voor het gegevenslandschap: De resources `medewerker`, `natuurlijkpersoon`, `nietnatuurlijkpersoon`, `organisatorischeEenheid` en `vestiging` uit de ORC overnemen in de ZRC.

**Comment by joeribekker** [comment]
Deze is opgelost middels in https://github.com/VNG-Realisatie/gemma-zaken/pull/1097
