### ISSUE TITLE
Als gemeente wil ik zaakobjecten met hun identificatie (anders dan de UUID) kunnen koppelen aan de zaak

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#981]
zodat ik een zaakobject kan koppelen als daar nog geen aparte API's voor zijn waar we naar kunnen verwijzen.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio en visie

**Comment by Hugo-ter-Doest** [comment]
Dit moet ook via de ORC worden opgelost analoog aan personen en bedrijven.

**Comment by joeribekker** [comment]
Na refinement sessie gekozen voor zelfde oplossing als #980

**Comment by EdwinCoster** [comment]
Consequentie voor het gegevenslandschap: De resources `mor`, `inzageverzoek` en `verblijfsobject` uit de ORC overnemen in de ZRC.

**Comment by joeribekker** [comment]
het attribuut `zaakobject` moet een vrije invulling kennen t.b.v flexibiliteit naar objecten die niet gedefinieerd zijn. We zijn ons er van bewust dat deze flexibiliteit tot incompatibiliteit kan leiden tussen consumers MAAR ze moeten zo snel mogelijk gestandaardiseerd worden zodra "vrije invulling" gebruikt wordt.
