### ISSUE TITLE
Als gemeente wil ik dezelfde resultaattype kunnen koppelen aan meerdere zaaktypen

### ISSUE THREAD

**Issue by shazada** [VNG-Realisatie/gemma-zaken#994]
# Improvement Story

De gemeente Amsterdam (oudere versie) is bezig met het invullen dan hun 'complete' ZTC, maar komt al heel snel tot de conclusie dat 85% van de tijd dezelfde resultaattypeomschrijving & selectieklasse hoort bij meerdere zaaktypes.
![FireShot Pro Screen Capture #211 - 'Selecteer Resultaattype om te wijzigen I Zaaktypecatal_' - ztc_projecten_contezza_nl_admin_datamodel_resultaattype](https://user-images.githubusercontent.com/1477763/57687468-c57d9300-763b-11e9-98e0-aba7a9bd7714.jpg)

Het is nu een 1 op 1 relatie en het moet mogelijk zijn om een 1 op n relatie te zijn.
Met zo'n 800 zaaktypes wordt de lijst met resultaattypeomschrijving al heel snel 4000 groot, wat niet meer te beheren valt :).

[assign aan teamlid en voeg label 'improvement story' toe]

**Comment by PDG65** [comment]
Het gaat hier om de ZTC van Haarlem. Staat daar nu hard in gekoppeld. Het is een "Admin interface probleem, geen probleem in de API's.

Voorstel: afwijzen omdat het geen waarde toevoegt

**Comment by sergei-maertens** [comment]
We begrijpen het geschetste probleem, maar er zijn een aantal afwegingen:

* in het gegevensmodel hoort een resultaattype bij een enkel zaaktype. Indien je dit niet doet, dan krijg je onverwacht gedrag als daardoor (onbedoeld) andere zaaktypen aangeraakt worden. Daar komt ook bij dat je resultaattypen enkel kan wijzigen zolang het zaaktype nog in concept status is.

* dit is meer een user-interface probleem - je wil ontdubbeling naar de catalogi-beheerders toe, omdat je dan niet met zo'n ellenlange lijst geconfronteerd wordt. Leveranciers kunnen een interface implementeren waarbij je een bestaand resultaattype selecteert van een ander zaaktype, en dan wordt deze naar het doel-zaaktype gekopieerd. _Hoe_ dit geimplementeerd wordt, is aan de leveranciers.

Deze usertory heeeft verder geen effect op de API definities, dus daarom sluiten we deze.
