### ISSUE TITLE
Als Productowner wil ik voor mijn stakeholders een (OT)A voor de ondersteunde versies van de standaard en voor de ontwikkelversie

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#995]
...zodat ondersteunde versies van de standaard op een efficiente en beheersbare wijze kunnen worden getest en uitgerold.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Er moeten straten komen voor de ondersteunde (in gebruik zijnde) versies en er moet een ontwikkelstraat zijn (zoals nu).

**Comment by sergei-maertens** [comment]
`develop` branches -> ref.tst.vng.cloud
stable (= tagged `master`) -> ref.acc.vng.cloud of ref.stable.vng.cloud o.i.d.

**Comment by joeribekker** [comment]
Verdere specificatie van Hugo:

Er komen 2 type omgevingen: **Testing** en **Stable** (om even af te stappen van OTAP waar de P erg gevaarlijk is qua naamgeving). Er komt van elke API versie een Stable omgeving.

Bijvoorbeeld:

* Test omgeving: Laatste code en OAS
* Stable omgeving API v1
* Stable omgeving API v2
etc.
